#!/usr/bin/env python3
"""Add at least 15 example sentences to each vocabulary sublesson (chapters 798-824)"""
import json

# Example sentences for each chapter - [English, Telugu, Transliteration]
SENTENCES = {
    798: [  # Body parts
        ["My head is hurting.", "నా తల నొప్పిగా ఉంది.", "nā tala noppigā undi."],
        ["Wash your hands.", "చేతులు కడుక్కోండి.", "cētulu kaḍukkōṇḍi."],
        ["I have pain in my leg.", "నా కాలికి నొప్పి ఉంది.", "nā kāliki noppi undi."],
        ["Close your eyes.", "కళ్లు మూసుకోండి.", "kaḷḷu mūsukōṇḍi."],
        ["My ear is paining.", "నా చెవికి నొప్పి ఉంది.", "nā ceviki noppi undi."],
        ["Brush your teeth.", "పంటలు ఉతుక్కోండి.", "paṇṭalu utukkōṇḍi."],
        ["My stomach is full.", "నా కడుపు నిండింది.", "nā kaḍupu niṇḍindi."],
        ["My heart is beating fast.", "నా గుండె వేగంగా కొట్టుకుంటోంది.", "nā guṇḍe vēgaṃgā koṭṭukuṇṭōndi."],
        ["Point with your finger.", "వేలుతో చూపించండి.", "vēlutō cūpin̄caṇḍi."],
        ["Stick out your tongue.", "నాలుక బయటకు తీయండి.", "nāluka bayaṭaku tīyaṇḍi."],
        ["Open your mouth.", "నోరు తెరవండి.", "nōru teravaṇḍi."],
        ["My nose is blocked.", "నా ముక్కు అడ్డుకున్నది.", "nā mukku aḍḍukunnadi."],
        ["She has beautiful eyes.", "ఆమెకు అందమైన కళ్లు ఉన్నాయి.", "āmeku andaṃaina kaḷḷu unnāyi."],
        ["He broke his hand.", "అతని చేయి విరిగింది.", "atani cēyi virigindi."],
        ["The doctor checked my heart.", "డాక్టర్ నా గుండెను పరిశీలించారు.", "ḍākṭar nā guṇḍenu pariśīlin̄cāru."],
    ],
    799: [  # Greetings & Basics
        ["Hello, how are you?", "నమస్తే, ఎలా ఉన్నారు?", "namastē, elā unnāru?"],
        ["I am fine, thank you.", "నేను బాగున్నాను, ధన్యవాదాలు.", "nēnu bāgunnānu, dhanyavādālu."],
        ["Good morning!", "శుభోదయం!", "śubhōdayaṃ!"],
        ["Good evening!", "శుభ సాయంత్రం!", "śubha sāyantraṃ!"],
        ["Good night!", "శుభ రాత్రి!", "śubha rātri!"],
        ["Thank you very much.", "చాలా ధన్యవాదాలు.", "cālā dhanyavādālu."],
        ["You are welcome.", "మీకు స్వాగతం.", "mīku svāgataṃ."],
        ["Please help me.", "దయచేసి నాకు సహాయం చేయండి.", "dayacēsi nāku sahāyaṃ cēyaṇḍi."],
        ["Excuse me.", "క్షమించండి.", "kṣamin̄caṇḍi."],
        ["See you later.", "తర్వాత కలుద్దాం.", "tarvāta kaluddāṃ."],
        ["Goodbye!", "వీడ్కోలు!", "vīḍkōlu!"],
        ["What is your name?", "మీ పేరు ఏమిటి?", "mī pēru ēmiṭi?"],
        ["My name is Rama.", "నా పేరు రామ.", "nā pēru rāma."],
        ["Pleased to meet you.", "మిమ్మల్ని కలవడం నాకు సంతోషంగా ఉంది.", "mim'malni kalavaḍaṃ nāku saṃtōṣaṃgā undi."],
        ["Don't worry.", "చింతించకండి.", "cintin̄cakaṇḍi."],
    ],
    800: [  # Frequently used words - Miscellaneous
        ["Where is this place?", "ఈ చోటు ఎక్కడ ఉంది?", "ī cōṭu ekkada undi?"],
        ["I don't have time.", "నాకు సమయం లేదు.", "nāku samayaṃ lēdu."],
        ["What day is today?", "ఈ రోజు ఏ రోజు?", "ī rōju ē rōju?"],
        ["I have work to do.", "నాకు చేయాల్సిన పని ఉంది.", "nāku cēyālsina pani undi."],
        ["Give me some water.", "నాకు కొంచెం నీరు ఇవ్వండి.", "nāku koncaṃ nīru ivvaṇḍi."],
        ["I need food.", "నాకు ఆహారం కావాలి.", "nāku āhāraṃ kāvāli."],
        ["This is my house.", "ఇది నా ఇల్లు.", "idi nā illu."],
        ["I don't have money.", "నాకు డబ్బు లేదు.", "nāku ḍabbu lēdu."],
        ["I need your help.", "నాకు మీ సహాయం కావాలి.", "nāku mī sahāyaṃ kāvāli."],
        ["What is your name?", "మీ పేరు ఏమిటి?", "mī pēru ēmiṭi?"],
        ["Show me the way.", "నాకు దారి చూపించండి.", "nāku dāri cūpin̄caṇḍi."],
        ["Where is this thing?", "ఈ వస్తువు ఎక్కడ ఉంది?", "ī vastuvu ekkada undi?"],
        ["I have no time today.", "ఈ రోజు నాకు సమయం లేదు.", "ī rōju nāku samayaṃ lēdu."],
        ["Water is essential.", "నీరు అవసరం.", "nīru avasaraṃ."],
        ["Work is important.", "పని ముఖ్యం.", "pani mukhyaṃ."],
    ],
    801: [  # Relations
        ["My father is a teacher.", "నా నాన్న ఉపాధ్యాయుడు.", "nā nānna upādhyāyuḍu."],
        ["My mother cooks well.", "నా అమ్మ బాగా వంట చేస్తుంది.", "nā amma bāgā vaṇṭa cēstundi."],
        ["I have an elder brother.", "నాకు అన్నయ్య ఉన్నాడు.", "nāku annayya unnāḍu."],
        ["My younger sister is studying.", "నా చెల్లి చదువుకుంటోంది.", "nā celli caduvukuṇṭōndi."],
        ["He is my husband.", "అతను నా భర్త.", "atanu nā bharta."],
        ["She is my wife.", "ఆమె నా భార్య.", "āme nā bhārya."],
        ["I have one son.", "నాకు ఒక కొడుకు ఉన్నాడు.", "nāku oka koḍuku unnāḍu."],
        ["My daughter is beautiful.", "నా కూతురు అందంగా ఉంది.", "nā kūturu andaṃgā undi."],
        ["My grandfather tells stories.", "నా తాతయ్య కథలు చెప్పుతాడు.", "nā tātayya kathalu cepputāḍu."],
        ["My grandmother loves me.", "నా అమ్మమ్మ నన్ను ప్రేమిస్తుంది.", "nā ammamma nannu prēmistundi."],
        ["My elder sister helps me.", "నా అక్క నాకు సహాయం చేస్తుంది.", "nā akka nāku sahāyaṃ cēstundi."],
        ["My younger brother plays cricket.", "నా తమ్ముడు క్రికెట్ ఆడుతాడు.", "nā tammuḍu krikeṭ āḍutāḍu."],
        ["We are a big family.", "మేము పెద్ద కుటుంబం.", "mēmu pedda kuṭumbaṃ."],
        ["My father works in a bank.", "నా నాన్న బ్యాంకులో పని చేస్తాడు.", "nā nānna byāṃkulō pani cēstāḍu."],
        ["My mother is at home.", "నా అమ్మ ఇంట్లో ఉంది.", "nā amma iṇṭlō undi."],
    ],
    802: [  # Numbers Part 1
        ["I have one book.", "నాకు ఒక పుస్తకం ఉంది.", "nāku oka pustakaṃ undi."],
        ["Give me two apples.", "నాకు రెండు ఆపిల్స్ ఇవ్వండి.", "nāku reṇḍu āpils ivvaṇḍi."],
        ["There are three people.", "ముగ్గురు మంది ఉన్నారు.", "mugguru mandi unnāru."],
        ["I need four chairs.", "నాకు నాలుగు కుర్చీలు కావాలి.", "nāku nālugu kurcīlu kāvāli."],
        ["We are five friends.", "మేము ఐదుగురు స్నేహితులు.", "mēmu aiduguru snēhitulu."],
        ["Six days in a week.", "వారంలో ఆరు రోజులు.", "vāraṃlō āru rōjulu."],
        ["Seven colours in a rainbow.", "ఇంద్రధనుస్సులో ఏడు రంగులు.", "indradhanussulō ēḍu raṃgulu."],
        ["Eight hours of sleep.", "ఎనిమిది గంటల నిద్ర.", "enimidi gaṇṭala nidra."],
        ["Nine months in pregnancy.", "గర్భంలో తొమ్మిది నెలలు.", "garbhaṃlō tommidi nelalu."],
        ["Ten fingers on hands.", "చేతులపై పది వేళ్లు.", "cētulapai padi vēḷḷu."],
        ["I am twenty years old.", "నాకు ఇరవై సంవత్సరాలు.", "nāku iravai saṃvatsarālu."],
        ["Zero is nothing.", "సున్నా ఏమీ లేదు.", "sunnā ēmī lēdu."],
        ["One plus one is two.", "ఒక్కటి ప్లస్ ఒక్కటి రెండు.", "okkaṭi plas okkaṭi reṇḍu."],
        ["I woke up at six.", "నేను ఆరు గంటలకు లేచాను.", "nēnu āru gaṇṭalaku lēcānu."],
        ["We have ten students.", "మాకు పది విద్యార్థులు ఉన్నారు.", "māku padi vidyārthulu unnāru."],
    ],
    803: [  # Numbers Part 2
        ["I am thirty years old.", "నాకు ముప్పై సంవత్సరాలు.", "nāku muppai saṃvatsarālu."],
        ["The bus costs forty rupees.", "బస్సు నలభై రూపాయలు.", "bassu nalabhai rūpāyalu."],
        ["There are fifty people.", "యాబై మంది ఉన్నారు.", "yābai mandi unnāru."],
        ["Sixty minutes in an hour.", "ఒక గంటలో అరవై నిమిషాలు.", "oka gaṇṭalō aravai nimiṣālu."],
        ["She is seventy years old.", "ఆమెకు డెబ్బై సంవత్సరాలు.", "āmeku debbai saṃvatsarālu."],
        ["Eighty percent passed.", "ఎనభై శాతం పాస్ అయ్యారు.", "enabhai śātaṃ pās ayyāru."],
        ["Ninety days warranty.", "తొంభై రోజుల వారంటీ.", "tombhai rōjula vāraṇṭī."],
        ["One hundred rupees.", "వంద రూపాయలు.", "vanda rūpāyalu."],
        ["One thousand people.", "వెయ్యి మంది.", "veyyi mandi."],
        ["One lakh rupees.", "ఒక లక్ష రూపాయలు.", "oka lakṣa rūpāyalu."],
        ["Thirty days in a month.", "నెలలో ముప్పై రోజులు.", "nelalō muppai rōjulu."],
        ["The price is hundred rupees.", "ధర వంద రూపాయలు.", "dhara vanda rūpāyalu."],
        ["I have fifty books.", "నాకు యాబై పుస్తకాలు ఉన్నాయి.", "nāku yābai pustakālu unnāyi."],
        ["Wait for ten minutes.", "పది నిమిషాలు వేచి ఉండండి.", "padi nimiṣālu vēci uṇḍaṇḍi."],
        ["It costs thousand rupees.", "ఇది వెయ్యి రూపాయలు.", "idi veyyi rūpāyalu."],
    ],
    804: [  # Fractional numbers
        ["Give me half.", "నాకు సగం ఇవ్వండి.", "nāku sagaṃ ivvaṇḍi."],
        ["A quarter of an hour.", "ఒక గంటలో క్వార్టర్.", "oka gaṇṭalō kvārṭar."],
        ["He came first.", "అతను మొదటి వచ్చాడు.", "atanu modaṭi vaccāḍu."],
        ["She got second prize.", "ఆమె రెండవ బహుమతి పొందింది.", "āme reṇḍava bahumati poṇdindi."],
        ["This is the third time.", "ఇది మూడవ సారి.", "idi mūḍava sāri."],
        ["Fifty percent discount.", "యాబై శాతం తగ్గింపు.", "yābai śātaṃ taggimpu."],
        ["Double the amount.", "రెట్టింపు మొత్తం.", "reṭṭiṃpu mottaṃ."],
        ["Half the work is done.", "సగం పని అయింది.", "sagaṃ pani ayindi."],
        ["I am first in class.", "నేను తరగతిలో మొదటి.", "nēnu taragatilō modaṭi."],
        ["Second floor please.", "రెండవ అంతస్తు దయచేసి.", "reṇḍava aṃtastu dayacēsi."],
        ["Third door on the left.", "ఎడమవైపు మూడవ తలుపు.", "eḍamavaipu mūḍava talupu."],
        ["Ten percent interest.", "పది శాతం వడ్డి.", "padi śātaṃ vaḍḍi."],
        ["Quarter past six.", "ఆరు గంటల పదిహేనుకు.", "āru gaṇṭala padihēnuku."],
        ["Double the quantity.", "రెట్టింపు పరిమాణం.", "reṭṭiṃpu parimāṇaṃ."],
        ["First come first served.", "మొదటి వచ్చినవాడికి మొదట.", "modaṭi vaccinavāḍiki modaṭa."],
    ],
    805: [  # Verbs Part 1
        ["I am at home.", "నేను ఇంట్లో ఉన్నాను.", "nēnu iṇṭlō unnānu."],
        ["I have a car.", "నాకు కారు ఉంది.", "nāku kāru undi."],
        ["What are you doing?", "నువ్వు ఏమి చేస్తున్నావు?", "nuvvu ēmi cēstunnāvu?"],
        ["Don't say that.", "అలా చెప్పకండి.", "alā ceppakaṇḍi."],
        ["I am going to the market.", "నేను మార్కెట్ కి వెళ్తున్నాను.", "nēnu mārkeṭ ki veḷtunnānu."],
        ["Please come here.", "దయచేసి ఇక్కడికి రండి.", "dayacēsi ikkaḍiki raṇḍi."],
        ["I saw him yesterday.", "నేను అతన్ని నిన్న చూశాను.", "nēnu atanni ninna cūśānu."],
        ["I don't know.", "నాకు తెలియదు.", "nāku teliyadu."],
        ["She is a teacher.", "ఆమె ఉపాధ్యాయిని.", "āme upādhyāyini."],
        ["We have time.", "మాకు సమయం ఉంది.", "māku samayaṃ undi."],
        ["Do your work.", "మీ పని చేయండి.", "mī pani cēyaṇḍi."],
        ["Tell me the truth.", "నాకు నిజం చెప్పండి.", "nāku nijaṃ ceppaṇḍi."],
        ["He went to school.", "అతను స్కూల్ కి వెళ్లాడు.", "atanu skūl ki veḷḷāḍu."],
        ["Come tomorrow.", "రేపు రండి.", "rēpu raṇḍi."],
        ["I know her.", "నాకు ఆమె తెలుసు.", "nāku āme telusu."],
    ],
    806: [  # Verbs Part 2
        ["I got a gift.", "నాకు బహుమతి వచ్చింది.", "nāku bahumati vaccindi."],
        ["She makes good food.", "ఆమె బాగా వంట చేస్తుంది.", "āme bāgā vaṇṭa cēstundi."],
        ["I am thinking.", "నేను ఆలోచిస్తున్నాను.", "nēnu ālōcistunnānu."],
        ["Take this book.", "ఈ పుస్తకం తీసుకోండి.", "ī pustakaṃ tīsukōṇḍi."],
        ["Tell me your name.", "మీ పేరు చెప్పండి.", "mī pēru ceppaṇḍi."],
        ["Don't ask me.", "నన్ను అడగకండి.", "nannu aḍagakaṇḍi."],
        ["I found my keys.", "నా కీలు కనుగొన్నాను.", "nā kīlu kanugonnānu."],
        ["I feel happy.", "నాకు సంతోషంగా ఉంది.", "nāku saṃtōṣaṃgā undi."],
        ["Get some water.", "కొంచెం నీరు తీసుకురండి.", "koncaṃ nīru tīsukuraṇḍi."],
        ["Make a cup of tea.", "ఒక కప్పు టీ చేయండి.", "oka kappu ṭī cēyaṇḍi."],
        ["Think before you speak.", "మాట్లాడే ముందు ఆలోచించండి.", "māṭlāḍē muṇdu ālōcin̄caṇḍi."],
        ["Take a seat.", "కూర్చోండి.", "kūrcōṇḍi."],
        ["Ask the teacher.", "ఉపాధ్యాయుడిని అడగండి.", "upādhyāyuḍini aḍagaṇḍi."],
        ["I cannot find it.", "నాకు కనుగొనలేకపోయాను.", "nāku kanugonalēkapōyānu."],
        ["How do you feel?", "మీకు ఎలా అనిపిస్తుంది?", "mīku elā anipistundi?"],
    ],
    807: [  # Verbs Part 3
        ["I eat breakfast at eight.", "నేను ఎనిమిది గంటలకు అల్పాహారం తింటాను.", "nēnu enimidi gaṇṭalaku alpāhāraṃ tiṇṭānu."],
        ["Drink some water.", "కొంచెం నీరు త్రాగండి.", "koncaṃ nīru trāgaṇḍi."],
        ["I want to sleep.", "నాకు నిద్ర పోవాలనిపిస్తోంది.", "nāku nidra pōvālanipistōndi."],
        ["I read books.", "నేను పుస్తకాలు చదువుతాను.", "nēnu pustakālu caduvutānu."],
        ["Write your name.", "మీ పేరు రాయండి.", "mī pēru rāyaṇḍi."],
        ["I want to buy this.", "నాకు ఇది కొనాలనిపిస్తోంది.", "nāku idi konālanipistōndi."],
        ["They sell vegetables.", "వారు కూరగాయలు అమ్ముతారు.", "vāru kūragāyalu ammutāru."],
        ["Give me that.", "అది నాకు ఇవ్వండి.", "adi nāku ivvaṇḍi."],
        ["Eat your food.", "మీ ఆహారం తినండి.", "mī āhāraṃ tinaṇḍi."],
        ["Don't drink cold water.", "చలి నీరు త్రాగకండి.", "cali nīru trāgakaṇḍi."],
        ["I slept well.", "నేను బాగా నిద్రపోయాను.", "nēnu bāgā nidrapōyānu."],
        ["Read this letter.", "ఈ లేఖ చదవండి.", "ī lēkha cadavaṇḍi."],
        ["I am writing a letter.", "నేను ఒక లేఖ రాస్తున్నాను.", "nēnu oka lēkha rāstunnānu."],
        ["I bought a new phone.", "నేను కొత్త ఫోన్ కొన్నాను.", "nēnu kotta phōn konnānu."],
        ["Please give me water.", "దయచేసి నాకు నీరు ఇవ్వండి.", "dayacēsi nāku nīru ivvaṇḍi."],
    ],
    808: [  # Verbs Part 4
        ["Open the door.", "తలుపు తెరవండి.", "talupu teravaṇḍi."],
        ["Close the window.", "కిటికీ మూయండి.", "kiṭikī mūyaṇḍi."],
        ["Please sit down.", "దయచేసి కూర్చోండి.", "dayacēsi kūrcōṇḍi."],
        ["Stand up.", "లేచి నిలబడండి.", "lēci nilabaḍaṇḍi."],
        ["Don't run here.", "ఇక్కడ పరుగెత్తకండి.", "ikkaḍa parugettakaṇḍi."],
        ["Let's walk together.", "కలిసి నడుద్దాం.", "kalisi naḍuddāṃ."],
        ["Speak slowly.", "నెమ్మదిగా మాట్లాడండి.", "nemmadigā māṭlāḍaṇḍi."],
        ["Listen to me.", "నా మాట వినండి.", "nā māṭa vinaṇḍi."],
        ["Open the book.", "పుస్తకం తెరవండి.", "pustakaṃ teravaṇḍi."],
        ["Close your eyes.", "కళ్లు మూసుకోండి.", "kaḷḷu mūsukōṇḍi."],
        ["Sit on the chair.", "కుర్చీ మీద కూర్చోండి.", "kurcī mīda kūrcōṇḍi."],
        ["He ran fast.", "అతను వేగంగా పరిగెత్తాడు.", "atanu vēgaṃgā parigettāḍu."],
        ["Walk carefully.", "జాగ్రత్తగా నడవండి.", "jāgrattagā naḍavaṇḍi."],
        ["She speaks Telugu.", "ఆమె తెలుగు మాట్లాడుతుంది.", "āme telugu māṭlāḍutundi."],
        ["Listen to the music.", "సంగీతం వినండి.", "saṃgītaṃ vinaṇḍi."],
    ],
    809: [  # పెట్టడం verb
        ["Put it on the table.", "మేజా మీద పెట్టండి.", "mējā mīda peṭṭaṇḍi."],
        ["She wears gold ornaments.", "ఆమె బంగారు నగలు పెట్టుకుంటుంది.", "āme baṃgāru nagalu peṭṭukuṇṭundi."],
        ["Apply cream on your face.", "ముఖంపై క్రీమ్ పెట్టండి.", "mukhaṃpai krīm peṭṭaṇḍi."],
        ["Switch on the light.", "లైట్ పెట్టండి.", "laiṭ peṭṭaṇḍi."],
        ["Let's start the meeting.", "మీటింగ్ ప్రారంభిద్దాం.", "mīṭiṃg prāraṃbhidāṃ."],
        ["Don't bet on that.", "అందుపై పెట్టకండి.", "andupai peṭṭakaṇḍi."],
        ["Put the bag here.", "బ్యాగ్ ఇక్కడ పెట్టండి.", "byāg ikkaḍa peṭṭaṇḍi."],
        ["She put on a saree.", "ఆమె సీరె పెట్టుకుంది.", "āme sīre peṭṭukundi."],
        ["Put oil on your hair.", "మీ వెంట్రుకలపై నూనె పెట్టండి.", "mī veṇṭrukalapai nūne peṭṭaṇḍi."],
        ["Put on the fan.", "ఫ్యాన్ పెట్టండి.", "phyān peṭṭaṇḍi."],
        ["Start the car.", "కారు స్టార్ట్ చేయండి.", "kāru stārṭ cēyaṇḍi."],
        ["He put the book down.", "అతను పుస్తకం పెట్టాడు.", "atanu pustakaṃ peṭṭāḍu."],
        ["Put sugar in the tea.", "టీలో చక్కెర పెట్టండి.", "ṭīlō cakkera peṭṭaṇḍi."],
        ["Put on the AC.", "ఎసి పెట్టండి.", "esi peṭṭaṇḍi."],
        ["Don't put it there.", "అక్కడ పెట్టకండి.", "akkaḍa peṭṭakaṇḍi."],
    ],
    810: [  # చేయడం verb
        ["What are you doing?", "నువ్వు ఏమి చేస్తున్నావు?", "nuvvu ēmi cēstunnāvu?"],
        ["I am making tea.", "నేను టీ చేస్తున్నాను.", "nēnu ṭī cēstunnānu."],
        ["She cooks well.", "ఆమె బాగా వంట చేస్తుంది.", "āme bāgā vaṇṭa cēstundi."],
        ["I am doing my work.", "నేను నా పని చేస్తున్నాను.", "nēnu nā pani cēstunnānu."],
        ["Please help me.", "దయచేసి నాకు సహాయం చేయండి.", "dayacēsi nāku sahāyaṃ cēyaṇḍi."],
        ["I will try.", "నేను ప్రయత్నిస్తాను.", "nēnu prayatnistānu."],
        ["Do your homework.", "మీ హోంవర్క్ చేయండి.", "mī hōṃvark cēyaṇḍi."],
        ["Make a list.", "ఒక జాబితా చేయండి.", "oka jābitā cēyaṇḍi."],
        ["She does yoga daily.", "ఆమె రోజూ యోగా చేస్తుంది.", "āme rōjū yōgā cēstundi."],
        ["I am doing exercise.", "నేను వ్యాయామం చేస్తున్నాను.", "nēnu vyāyāmaṃ cēstunnānu."],
        ["Try again.", "మళ్ళీ ప్రయత్నించండి.", "maḷḷī prayatin̄caṇḍi."],
        ["Do it now.", "ఇప్పుడే చేయండి.", "ippuḍē cēyaṇḍi."],
        ["What did you do?", "నువ్వు ఏమి చేశావు?", "nuvvu ēmi cēśāvu?"],
        ["I am trying to learn.", "నేను నేర్చుకోవడానికి ప్రయత్నిస్తున్నాను.", "nēnu nērcukōvaḍāniki prayatnistunnānu."],
        ["Do not do that.", "అలా చేయకండి.", "alā cēyakaṇḍi."],
    ],
    811: [  # Adjectives
        ["This is good.", "ఇది మంచిది.", "idi maṃcidi."],
        ["That is bad.", "అది చెడ్డది.", "adi ceḍḍadi."],
        ["It is a big house.", "ఇది పెద్ద ఇల్లు.", "idi pedda illu."],
        ["She has a small bag.", "ఆమెకు చిన్న బ్యాగ్ ఉంది.", "āmeku cinna byāg undi."],
        ["It is a long road.", "ఇది పొడవైన రోడ్.", "idi poḍavaina rōḍ."],
        ["Give me a short summary.", "నాకు చిన్న సారాంశం ఇవ్వండి.", "nāku cinna sārāṃśaṃ ivvaṇḍi."],
        ["The water is hot.", "నీరు వేడిగా ఉంది.", "nīru vēḍigā undi."],
        ["Today is cold.", "ఈ రోజు చలిగా ఉంది.", "ī rōju caligā undi."],
        ["She is beautiful.", "ఆమె అందంగా ఉంది.", "āme andaṃgā undi."],
        ["I have a new phone.", "నాకు కొత్త ఫోన్ ఉంది.", "nāku kotta phōn undi."],
        ["This is an old building.", "ఇది పాత భవనం.", "idi pāta bhavanaṃ."],
        ["Good morning!", "శుభోదయం!", "śubhōdayaṃ!"],
        ["Bad weather today.", "ఈ రోజు చెడ్డ వాతావరణం.", "ī rōju ceḍḍa vātāvaraṇaṃ."],
        ["Big city.", "పెద్ద నగరం.", "pedda nagaraṃ."],
        ["Small village.", "చిన్న గ్రామం.", "cinna grāmaṃ."],
    ],
    812: [  # Adverbs Part 1
        ["I am going today.", "నేను ఈ రోజు వెళ్తున్నాను.", "nēnu ī rōju veḷtunnānu."],
        ["See you tomorrow.", "రేపు కలుద్దాం.", "rēpu kaluddāṃ."],
        ["I came yesterday.", "నేను నిన్న వచ్చాను.", "nēnu ninna vaccānu."],
        ["Do it now.", "ఇప్పుడే చేయండి.", "ippuḍē cēyaṇḍi."],
        ["Come here.", "ఇక్కడికి రండి.", "ikkaḍiki raṇḍi."],
        ["Go there.", "అక్కడికి వెళ్లండి.", "akkaḍiki veḷḷaṇḍi."],
        ["I always wake up early.", "నేను ఎప్పుడూ తొందరగా లేస్తాను.", "nēnu eppuḍū toṃdaragā lēstānu."],
        ["I never lie.", "నేను ఎప్పుడూ అబద్ధం చెప్పను.", "nēnu eppuḍū abaddhaṃ ceppanu."],
        ["I often visit them.", "నేను తరచుగా వారిని సందర్శిస్తాను.", "nēnu taracugā vārini saṃdarśistānu."],
        ["Walk slowly.", "నెమ్మదిగా నడవండి.", "nemmadigā naḍavaṇḍi."],
        ["He runs fast.", "అతను వేగంగా పరుగెత్తుతాడు.", "atanu vēgaṃgā parugettutāḍu."],
        ["I will come tomorrow.", "నేను రేపు వస్తాను.", "nēnu rēpu vastānu."],
        ["She is here.", "ఆమె ఇక్కడ ఉంది.", "āme ikkaḍa undi."],
        ["They are there.", "వారు అక్కడ ఉన్నారు.", "vāru akkaḍa unnāru."],
        ["Now or never.", "ఇప్పుడే లేదా ఎప్పుడూ కాదు.", "ippuḍē lēdā eppuḍū kādu."],
    ],
    813: [  # List of adverbs
        ["Very good!", "చాలా బాగుంది!", "cālā bāgundi!"],
        ["Thank you very much.", "చాలా ధన్యవాదాలు.", "cālā dhanyavādālu."],
        ["I have much work.", "నాకు ఎక్కువ పని ఉంది.", "nāku ekkuva pani undi."],
        ["Just a little.", "కొంచెం మాత్రమే.", "koncaṃ mātramē."],
        ["That's enough.", "సరిపోతుంది.", "saripōtundi."],
        ["I am also coming.", "నేను కూడా వస్తున్నాను.", "nēnu kūḍā vastunnānu."],
        ["Only one left.", "ఒక్కటి మాత్రమే మిగిలింది.", "okkaṭi mātramē migilindi."],
        ["Even he agreed.", "అతను కూడా అంగీకరించాడు.", "atanu kūḍā aṃgīkarin̄cāḍu."],
        ["I am still waiting.", "నేను ఇంకా వేచి ఉన్నాను.", "nēnu iṃkā vēci unnānu."],
        ["It is very hot.", "చాలా వేడిగా ఉంది.", "cālā vēḍigā undi."],
        ["Too much sugar.", "ఎక్కువ చక్కెర.", "ekkuva cakkera."],
        ["A little bit more.", "కొంచెం ఇంకా.", "koncaṃ iṃkā."],
        ["Enough for today.", "ఈ రోజుకు సరిపోతుంది.", "ī rōjuku saripōtundi."],
        ["She also said yes.", "ఆమె కూడా అవును అంది.", "āme kūḍā avunu andi."],
        ["Only you can do it.", "నువ్వు మాత్రమే చేయగలవు.", "nuvvu mātramē cēyagalavu."],
    ],
    814: [  # Vegetables
        ["I need tomatoes.", "నాకు టమాటాలు కావాలి.", "nāku ṭamāṭālu kāvāli."],
        ["Potato is cheap.", "బంగాళాదుంప చౌక.", "baṃgāḷāduṃpa cauka."],
        ["Add some onion.", "కొంచెం ఉల్లిపాయ వేయండి.", "koncaṃ ullipāya vēyaṇḍi."],
        ["I don't like brinjal.", "నాకు వంకాయ ఇష్టం లేదు.", "nāku vaṃkāya iṣṭaṃ lēdu."],
        ["Buy lady's finger.", "బెండకాయ కొనండి.", "beṇḍakāya konaṇḍi."],
        ["Cucumber is fresh.", "దోసకాయ తాజా.", "dōsakāya tājā."],
        ["Carrot is good for health.", "కారెట్ ఆరోగ్యానికి మంచిది.", "kāreṭ ārōgyāniki maṃcidi."],
        ["I love spinach.", "నాకు పాలకూర ఇష్టం.", "nāku pālakūra iṣṭaṃ."],
        ["How much for pumpkin?", "గుమ్మడికాయ ఎంత?", "gummaḍikāya enta?"],
        ["Bitter gourd is healthy.", "కాకరకాయ ఆరోగ్యకరం.", "kākarakāya ārōgyakaraṃ."],
        ["Add one chilli.", "ఒక మిరపకాయ వేయండి.", "oka mirapakāya vēyaṇḍi."],
        ["Bring vegetables.", "కూరగాయలు తీసుకురండి.", "kūragāyalu tīsukuraṇḍi."],
        ["Tomato curry is tasty.", "టమాటా కూర రుచిగా ఉంది.", "ṭamāṭā kūra rucigā undi."],
        ["Onion makes you cry.", "ఉల్లిపాయ కన్నీరు పుడుతుంది.", "ullipāya kannīru puḍutundi."],
        ["Fresh vegetables here.", "ఇక్కడ తాజా కూరగాయలు.", "ikkaḍa tājā kūragāyalu."],
    ],
    815: [  # Fruits
        ["Mango is my favourite.", "మామిడిపండు నాకు ఇష్టం.", "māmiḍipaṇḍu nāku iṣṭaṃ."],
        ["Eat a banana.", "అరటిపండు తినండి.", "araṭipaṇḍu tinaṇḍi."],
        ["Apple a day.", "రోజుకు ఒక ఆపిల్.", "rōjuku oka āpil."],
        ["Orange is sweet.", "కమలపండు తీపి.", "kamalapaṇḍu tīpi."],
        ["Grapes are fresh.", "ద్రాక్ష తాజా.", "drākṣa tājā."],
        ["Papaya is good.", "బొప్పాయ మంచిది.", "boppāya maṃcidi."],
        ["I like guava.", "నాకు జామ ఇష్టం.", "nāku jāma iṣṭaṃ."],
        ["Watermelon in summer.", "వేసవిలో పుచ్చకాయ.", "vēsavilō puccakāya."],
        ["Pomegranate is healthy.", "దానిమ్మ ఆరోగ్యకరం.", "dānimma ārōgyakaraṃ."],
        ["Lemon for the drink.", "పానీయానికి నిమ్మకాయ.", "pānīyāniki nimmakāya."],
        ["Coconut water is cool.", "కొబ్బరి నీరు చల్లగా ఉంది.", "kobbari nīru callagā undi."],
        ["Buy some fruits.", "కొంచెం పండ్లు కొనండి.", "koncaṃ paṇḍlu konaṇḍi."],
        ["Ripe mango is sweet.", "పండిన మామిడిపండు తీపి.", "paṇḍina māmiḍipaṇḍu tīpi."],
        ["Fruits are good for health.", "పండ్లు ఆరోగ్యానికి మంచివి.", "paṇḍlu ārōgyāniki maṃcivi."],
        ["Seasonal fruits are cheap.", "ఋతుపవన పండ్లు చౌక.", "ṛtupavana paṇḍlu cauka."],
    ],
    816: [  # Birds
        ["The crow is black.", "కాకి నలుపు.", "kāki nalupu."],
        ["Parrot can talk.", "చిలుక మాట్లాడగలదు.", "ciluka māṭlāḍagaladu."],
        ["Peacock is beautiful.", "నెమలి అందంగా ఉంది.", "nemali andaṃgā undi."],
        ["Sparrow is small.", "పిచుక చిన్నది.", "picuka cinnadi."],
        ["Eagle flies high.", "గ్రద్ద ఎత్తుగా ఎగురుతుంది.", "gradda ettugā egurutundi."],
        ["Pigeon is white.", "పావురం తెలుపు.", "pāvuraṃ telupu."],
        ["Owl comes at night.", "గుడ్లగూబ రాత్రి వస్తుంది.", "guḍlagūba rātri vastundi."],
        ["Crow is clever.", "కాకి తెలివైనది.", "kāki telivainadi."],
        ["Peacock has feathers.", "నెమలికి ఈకలు ఉన్నాయి.", "nemaliki īkalu unnāyi."],
        ["Birds fly in the sky.", "పక్షులు ఆకాశంలో ఎగురుతాయి.", "pakṣulu ākāśaṃlō egurutāyi."],
        ["Sparrow builds nest.", "పిచుక గూడు కట్టుతుంది.", "picuka gūḍu kaṭṭutundi."],
        ["Parrot is green.", "చిలుక పచ్చ.", "ciluka pacca."],
        ["I saw an eagle.", "నేను ఒక గ్రద్ద చూశాను.", "nēnu oka gradda cūśānu."],
        ["Birds sing in morning.", "పక్షులు ఉదయం పాడుతాయి.", "pakṣulu udayaṃ pāḍutāyi."],
        ["Peacock dances in rain.", "నెమలి వర్షంలో నాట్యం చేస్తుంది.", "nemali varṣaṃlō nāṭyaṃ cēstundi."],
    ],
    817: [  # Insects
        ["Ant is small.", "చీమ చిన్నది.", "cīma cinnadi."],
        ["Bee makes honey.", "తేనెటీగ తేనె చేస్తుంది.", "tēneṭīga tēne cēstundi."],
        ["Butterfly is colourful.", "సీతాకోకచిలుక రంగురంగులది.", "sītākōkaciluka raṃguraṃguladi."],
        ["Mosquito bites.", "సాంక్రాతి కుటుతుంది.", "sāṃkrāti kuṭutundi."],
        ["Spider spins web.", "సాలెపురుగు జాలం నేస్తుంది.", "sālepurugu jālaṃ nēstundi."],
        ["Cockroach runs fast.", "బొద్దింక వేగంగా పరుగెత్తుతుంది.", "boddin̄ka vēgaṃgā parugettutundi."],
        ["Fly is annoying.", "ఈగ బాధించేది.", "īga bādhin̄cēdi."],
        ["Honey from bees.", "తేనెటీగల నుండి తేనె.", "tēneṭīgala nuṇḍi tēne."],
        ["Ants work hard.", "చీమలు కష్టపడి పని చేస్తాయి.", "cīmalu kaṣṭapaḍi pani cēstāyi."],
        ["Butterfly on the flower.", "పుష్పంపై సీతాకోకచిలుక.", "puṣpaṃpai sītākōkaciluka."],
        ["Kill the mosquito.", "సాంక్రాతిని చంపండి.", "sāṃkrātini caṃpaṇḍi."],
        ["Spider caught a fly.", "సాలెపురుగు ఈగను పట్టుకుంది.", "sālepurugu īganu paṭṭukundi."],
        ["Bee stings.", "తేనెటీగ కుటుతుంది.", "tēneṭīga kuṭutundi."],
        ["Ants in a line.", "చీమలు వరుసలో.", "cīmalu varusalō."],
        ["Butterfly is beautiful.", "సీతాకోకచిలుక అందంగా ఉంది.", "sītākōkaciluka andaṃgā undi."],
    ],
    818: [  # Colours
        ["Red is my favourite.", "ఎరుపు నాకు ఇష్టం.", "erupu nāku iṣṭaṃ."],
        ["Sky is blue.", "ఆకాశం నీలం.", "ākāśaṃ nīlaṃ."],
        ["Grass is green.", "గడ్డి పచ్చ.", "gaḍḍi pacca."],
        ["Sun is yellow.", "సూర్యుడు పసుపు.", "sūryuḍu pasupu."],
        ["Cloud is white.", "మేఘం తెలుపు.", "mēghaṃ telupu."],
        ["Night is black.", "రాత్రి నలుపు.", "rātri nalupu."],
        ["Orange is orange.", "నారింజ నారింజ రంగు.", "nārin̄ja nārin̄ja raṃgu."],
        ["I like pink.", "నాకు గులాబీ ఇష్టం.", "nāku gulābī iṣṭaṃ."],
        ["Purple flower.", "ఊదా పుష్పం.", "ūdā puṣpaṃ."],
        ["Brown hair.", "గోధుమ వెంట్రుకలు.", "gōdhuma veṇṭrukalu."],
        ["Black and white.", "నలుపు మరియు తెలుపు.", "nalupu mariyu telupu."],
        ["Green leaves.", "పచ్చ ఆకులు.", "pacca ākulu."],
        ["Blue sea.", "నీలం సముద్రం.", "nīlaṃ samudraṃ."],
        ["Red rose.", "ఎరుపు గులాబి.", "erupu gulābi."],
        ["White shirt.", "తెలుపు చొక్కా.", "telupu cokkā."],
    ],
    819: [  # Flowers
        ["Rose is beautiful.", "గులాబి అందంగా ఉంది.", "gulābi andaṃgā undi."],
        ["Jasmine smells good.", "మల్లె పరిమళంగా ఉంది.", "malle parimaḷaṃgā undi."],
        ["Lotus is national flower.", "పద్మం జాతీయ పుష్పం.", "padmaṃ jātīya puṣpaṃ."],
        ["Sunflower is yellow.", "పొద్దుతిరుగుడు పసుపు.", "poddutiruguḍu pasupu."],
        ["Marigold is orange.", "బంతి నారింజ రంగు.", "baṃti nārin̄ja raṃgu."],
        ["I love flowers.", "నాకు పుష్పాలు ఇష్టం.", "nāku puṣpālu iṣṭaṃ."],
        ["Give me a rose.", "నాకు ఒక గులాబి ఇవ్వండి.", "nāku oka gulābi ivvaṇḍi."],
        ["Jasmine for hair.", "వెంట్రుకలకు మల్లె.", "veṇṭrukalaku malle."],
        ["Lotus in the pond.", "చెరువులో పద్మం.", "ceruvulō padmaṃ."],
        ["Flowers in the garden.", "తోటలో పుష్పాలు.", "tōṭalō puṣpālu."],
        ["Red rose for you.", "మీకోసం ఎరుపు గులాబి.", "mīkōsaṃ erupu gulābi."],
        ["Fresh flowers.", "తాజా పుష్పాలు.", "tājā puṣpālu."],
        ["Smell the flower.", "పుష్పం వాసన చూడండి.", "puṣpaṃ vāsana cūḍaṇḍi."],
        ["Flower garland.", "పుష్పమాల.", "puṣpamāla."],
        ["Plant flowers.", "పుష్పాలు నాటండి.", "puṣpālu nāṭaṇḍi."],
    ],
    820: [  # Animals
        ["Dog is loyal.", "కుక్క విశ్వాసపాత్రం.", "kukka viśvāsapātraṃ."],
        ["Cat drinks milk.", "పిల్లి పాల త్రాగుతుంది.", "pilli pāla trāgutundi."],
        ["Cow gives milk.", "ఆవు పాలిస్తుంది.", "āvu pālistundi."],
        ["Elephant is big.", "ఏనుగు పెద్దది.", "ēnugu peddadi."],
        ["Lion is king.", "సింహం రాజు.", "sin̄haṃ rāju."],
        ["Tiger has stripes.", "పులికి పట్టలు ఉన్నాయి.", "puliki paṭṭalu unnāyi."],
        ["Monkey climbs trees.", "కోతి చెట్లు ఎక్కుతుంది.", "kōti ceṭlu ekkutundi."],
        ["Horse runs fast.", "గుర్రం వేగంగా పరుగెత్తుతుంది.", "gurraṃ vēgaṃgā parugettutundi."],
        ["Rabbit is soft.", "చిట్టెలుక మృదువుగా ఉంది.", "ciṭṭeluka mṛduvugā undi."],
        ["Goat gives milk.", "మేక పాలిస్తుంది.", "mēka pālistundi."],
        ["I have a dog.", "నాకు ఒక కుక్క ఉంది.", "nāku oka kukka undi."],
        ["Wild animals in forest.", "అడవిలో అడవి జంతువులు.", "aḍavilō aḍavi jaṃtuvulu."],
        ["Cat catches mouse.", "పిల్లి ఎలుకను పట్టుకుంటుంది.", "pilli elukanu paṭṭukuṇṭundi."],
        ["Elephant has trunk.", "ఏనుగుకి తొండం ఉంది.", "ēnuguki toṃḍaṃ undi."],
        ["Respect the cow.", "ఆవును గౌరవించండి.", "āvunu gauravin̄caṇḍi."],
    ],
    821: [  # Food & Drink
        ["I am hungry.", "నాకు ఆకలిగా ఉంది.", "nāku ākaligā undi."],
        ["I am thirsty.", "నాకు దాహంగా ఉంది.", "nāku dāhaṃgā undi."],
        ["Rice is staple food.", "అన్నం ప్రధాన ఆహారం.", "annaṃ pradhāna āhāraṃ."],
        ["Give me water.", "నాకు నీరు ఇవ్వండి.", "nāku nīru ivvaṇḍi."],
        ["Food is ready.", "ఆహారం సిద్ధంగా ఉంది.", "āhāraṃ siddhaṃgā undi."],
        ["I want coffee.", "నాకు కాఫీ కావాలి.", "nāku kāphī kāvāli."],
        ["Tea or coffee?", "టీ లేదా కాఫీ?", "ṭī lēdā kāphī?"],
        ["Breakfast is important.", "అల్పాహారం ముఖ్యం.", "alpāhāraṃ mukhyaṃ."],
        ["Lunch at one.", "ఒక గంటకు భోజనం.", "oka gaṇṭaku bhōjanaṃ."],
        ["Dinner at night.", "రాత్రి భోజనం.", "rātri bhōjanaṃ."],
        ["Spicy food.", "మసాలా ఆహారం.", "masālā āhāraṃ."],
        ["Sweet dessert.", "తీపి డెజర్ట్.", "tīpi ḍejarṭ."],
        ["Hot soup.", "వేడి సూప్.", "vēḍi sūp."],
        ["Cold drink.", "చలి పానీయం.", "cali pānīyaṃ."],
        ["Healthy food.", "ఆరోగ్యకర ఆహారం.", "ārōgyakara āhāraṃ."],
    ],
    822: [  # Daily Life, Time, Transportation
        ["Wake up early.", "తొందరగా లేయండి.", "toṃdaragā lēyaṇḍi."],
        ["What time is it?", "ఎన్ని గంటలయింది?", "enni gaṇṭalayindi?"],
        ["I go by bus.", "నేను బస్సుతో వెళ్తాను.", "nēnu bassutō veḷtānu."],
        ["Train is late.", "రైలు ఆలస్యంగా ఉంది.", "railu ālasyamgā undi."],
        ["Take an auto.", "ఆటో తీసుకోండి.", "āṭō tīsukōṇḍi."],
        ["Morning walk.", "ఉదయం నడక.", "udayaṃ naḍaka."],
        ["Office at nine.", "తొమ్మిది గంటలకు ఆఫీస్.", "tommidi gaṇṭalaku āphīs."],
        ["Come home early.", "తొందరగా ఇంటికి రండి.", "toṃdaragā iṇṭiki raṇḍi."],
        ["Weekend holiday.", "వారాంతం సెలవు.", "vārāṃtaṃ selavu."],
        ["Monday to Friday.", "సోమవారం నుండి శుక్రవారం.", "sōmavāraṃ nuṇḍi śukravāraṃ."],
        ["Bus stop nearby.", "సమీపంలో బస్ స్టాప్.", "samīpaṃlō bas stāp."],
        ["Book a ticket.", "టికెట్ బుక్ చేయండి.", "ṭikeṭ buk cēyaṇḍi."],
        ["Traffic is heavy.", "ట్రాఫిక్ ఎక్కువ.", "ṭrāphik ekkuva."],
        ["Reach by six.", "ఆరు గంటలకు చేరండి.", "āru gaṇṭalaku cēraṇḍi."],
        ["Daily routine.", "రోజువారీ పని.", "rōjuvārī pani."],
    ],
    823: [  # Shopping, Travel, Emergency
        ["How much is this?", "ఇది ఎంత?", "idi enta?"],
        ["Too expensive.", "చాలా ఖరీదు.", "cālā kharīdu."],
        ["Give discount.", "తగ్గింపు ఇవ్వండి.", "taggimpu ivvaṇḍi."],
        ["I want to travel.", "నాకు ప్రయాణం చేయాలనిపిస్తోంది.", "nāku prayāṇaṃ cēyālanipistōndi."],
        ["Help!", "సహాయం!", "sahāyaṃ!"],
        ["Call the police.", "పోలీసును పిలవండి.", "pōlīsunu pilavaṇḍi."],
        ["Call ambulance.", "అంబులెన్స్ పిలవండి.", "aṃbulens pilavaṇḍi."],
        ["There's an accident.", "ప్రమాదం జరిగింది.", "pramādaṃ jarigindi."],
        ["I need a doctor.", "నాకు డాక్టర్ కావాలి.", "nāku ḍākṭar kāvāli."],
        ["Where is hospital?", "ఆసుపత్రి ఎక్కడ ఉంది?", "āsupatri ekkada undi?"],
        ["I am lost.", "నేను ఓడిపోయాను.", "nēnu ōḍipōyānu."],
        ["My bag is stolen.", "నా బ్యాగ్ దొంగిలించబడింది.", "nā byāg doṃgilin̄cabaḍindi."],
        ["Can I return this?", "ఇది తిరిగి ఇవ్వవచ్చా?", "idi tirigi ivvavaccā?"],
        ["Book a room.", "గది బుక్ చేయండి.", "gadi buk cēyaṇḍi."],
        ["Emergency exit.", "అత్యవసర నిష్క్రమణ.", "atyavasara niṣkramaṇa."],
    ],
    824: [  # Miscellaneous
        ["What is this?", "ఇది ఏమిటి?", "idi ēmiṭi?"],
        ["Where is it?", "అది ఎక్కడ ఉంది?", "adi ekkada undi?"],
        ["When will you come?", "మీరు ఎప్పుడు వస్తారు?", "mīru eppuḍu vastāru?"],
        ["Why did you do that?", "ఎందుకు అలా చేశారు?", "enduku alā cēśāru?"],
        ["How are you?", "మీరు ఎలా ఉన్నారు?", "mīru elā unnāru?"],
        ["Who is that?", "అతను ఎవరు?", "atanu evaru?"],
        ["Which one?", "ఏది?", "ēdi?"],
        ["No problem.", "సమస్య లేదు.", "samasya lēdu."],
        ["It's okay.", "సరే.", "sarē."],
        ["Of course.", "ఖచ్చితంగా.", "khaccitaṃgā."],
        ["Maybe.", "బహుశా.", "bahuśā."],
        ["I think so.", "నేను అలా అనుకుంటున్నాను.", "nēnu alā anukuṇṭunnānu."],
        ["I don't understand.", "నాకు అర్థం కాదు.", "nāku arthaṃ kādu."],
        ["Repeat please.", "మళ్ళీ చెప్పండి దయచేసి.", "maḷḷī ceppaṇḍi dayacēsi."],
        ["Speak in Telugu.", "తెలుగులో మాట్లాడండి.", "telugulō māṭlāḍaṇḍi."],
    ],
}

def main():
    with open("data_telugu.json", "r", encoding="utf-8") as f:
        data = json.load(f)

    for chapter in data:
        cid = chapter.get("id")
        if cid not in SENTENCES:
            continue
        rows = SENTENCES[cid]
        sent_table = {
            "heading": "Example sentences",
            "headers": ["English", "Telugu", "Transliteration"],
            "speakCol": 1,
            "rows": rows
        }
        tables = chapter.get("tables", [])
        # Find and replace or add Example sentences table
        found = False
        for i, t in enumerate(tables):
            if t.get("heading") == "Example sentences":
                tables[i] = sent_table
                found = True
                break
        if not found:
            tables.append(sent_table)
        chapter["tables"] = tables

    with open("data_telugu.json", "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"Added/updated example sentences for {len(SENTENCES)} chapters (798-824)")

if __name__ == "__main__":
    main()
