# -*- coding: utf-8 -*-
"""Add 15 unique topic-specific sentences per chapter 765-797 based on web search."""
import json

PATH = "data_telugu.json"

# 15 unique rows per chapter [English, Telugu, Transliteration] - from web search
CONTENT = {
    765: [  # To Want/Need with other verbs - కావాలనుంది pattern
        ["I want to eat.", "నాకు తినాలనుంది.", "nāku tinālanundi."],
        ["She wants to go home.", "ఆమెకి ఇంటికి వెళ్లాలనుంది.", "āmeki iṇṭiki veḷḷālanundi."],
        ["We need to finish the work.", "మాకు పని పూర్తిచేయాల్సి ఉంది.", "māku pani pūrticēyālsi undi."],
        ["He wants to learn Telugu.", "అతనికి తెలుగు నేర్చుకోవాలనుంది.", "ataniki telugu nērchukōvālanundi."],
        ["I want to sleep.", "నాకు నిద్రపోవాలనుంది.", "nāku nidrapōvālanundi."],
        ["They want to watch a movie.", "వారికి సినిమా చూడాలనుంది.", "vāriki sinimā cūdālanundi."],
        ["Do you want to drink tea?", "నీకు టీ తాగాలనుందా?", "nīku ṭī tāgālanundā?"],
        ["She wants to buy a dress.", "ఆమెకి డ్రెస్ కొనాలనుంది.", "āmeki ḍres konālanundi."],
        ["We want to meet you.", "మాకు నిన్ను కలవాలనుంది.", "māku ninnu kalavālanundi."],
        ["He needs to call his parents.", "అతనికి తల్లిదండ్రులకు ఫోన్ చేయాల్సి ఉంది.", "ataniki tallidaṇḍrulaku phōn cēyālsi undi."],
        ["I don't want to wait.", "నాకు ఎదురు చూడాలనిపించడం లేదు.", "nāku eduru cūdālanipiṇḍaṃ lēdu."],
        ["Children want to play.", "పిల్లలకు ఆడాలనుంది.", "pillalaku āḍālanundi."],
        ["She wants to read this book.", "ఆమెకి ఈ పుస్తకం చదవాలనుంది.", "āmeki ī pustakaṃ cadavālanundi."],
        ["We need to leave early.", "మనం త్వరగా బయటకు వెళ్లాల్సి ఉంది.", "manaṃ tvaragā bayataku veḷḷālsi undi."],
        ["He wants to speak to you.", "అతనికి నీతో మాట్లాడాలనుంది.", "ataniki nītō māṭlāḍālanundi."],
    ],
    766: [  # To Want with other person - రావాలని కావాలి / కోరుకుంటున్నాను
        ["I want him to come.", "అతను రావాలని నాకు కావాలి.", "atanu rāvālani nāku kāvāli."],
        ["She wants me to help.", "ఆమె నాకు సహాయం చేయమని కోరుతోంది.", "āme nāku sahāyaṃ cēyamani kōrutōndi."],
        ["We want them to stay here.", "వారు ఇక్కడే ఉండాలని మేము కోరుకుంటున్నాం.", "vāru ikkāḍē uṇḍālani mēmu kōrukuṇṭunnāṃ."],
        ["My parents want me to study.", "నాకు చదవాలని నా తల్లిదండ్రులు కోరుకుంటున్నారు.", "nāku cadavālani nā tallidaṇḍrulu kōrukuṇṭunnāru."],
        ["I want you to come here.", "నువ్వు ఇక్కడికి రావాలని నాకు కావాలి.", "nuvvu ikkaḍiki rāvālani nāku kāvāli."],
        ["They want us to visit them.", "మేము వారిని చూడాలని వారు కోరుతున్నారు.", "mēmu vārini cūdālani vāru kōrutunnāru."],
        ["Do you want me to call you?", "నేను నీకు ఫోన్ చేయాలని ఉందా?", "nēnu nīku phōn cēyālani undā?"],
        ["Teacher wants students to listen.", "విద్యార్థులు శ్రద్ధగా వినాలని గురువు కోరుతున్నారు.", "vidyārthulu śraddhagā vinālani guruvu kōrutunnāru."],
        ["I want everyone to be happy.", "అందరూ సంతోషంగా ఉండాలని నేను కోరుకుంటున్నాను.", "andarū santoṣaṅgā uṇḍālani nēnu kōrukuṇṭunnānu."],
        ["She wants him to wait.", "అతను ఎదురు చూడాలని ఆమె కోరుతోంది.", "atanu eduru cūdālani āme kōrutōndi."],
        ["We want the children to eat.", "పిల్లలు తినాలని మేము కోరుకుంటున్నాం.", "pillalu tinālani mēmu kōrukuṇṭunnāṃ."],
        ["He wants her to sing.", "ఆమె పాడాలని అతను కోరుతున్నాడు.", "āme pāḍālani atanu kōrutunnāḍu."],
        ["Parents want children to tell the truth.", "పిల్లలు నిజం చెప్పాలని తల్లిదండ్రులు కోరుకుంటారు.", "pillalu nijam ceppālani tallidaṇḍrulu kōrukuṇṭāru."],
        ["I don't want her to go alone.", "ఆమె ఒంటరిగా వెళ్లకూడదనుకుంటున్నాను.", "āme oṇṭarigā veḷḷakūḍadanukuṇṭunnānu."],
        ["Boss wants us to finish today.", "ఇవాళ పూర్తిచేయాలని బాస్ కోరుతున్నాడు.", "ivāḷ pūrticēyālani bās kōrutunnāḍu."],
    ],
    767: [  # supposed to - వెళ్లాల్సి ఉంది pattern
        ["I am supposed to go now.", "ఇప్పుడు నేను వెళ్లాల్సి ఉంది.", "ippuḍu nēnu veḷḷālsi undi."],
        ["He was supposed to call me.", "అతను నాకు ఫోన్ చేయాల్సి ఉండేది.", "atanu nāku phōn cēyālsi uṇḍēdi."],
        ["We were supposed to meet yesterday.", "నిన్న మనం కలవాల్సి ఉండేది.", "ninna manaṃ kalavālsi uṇḍēdi."],
        ["You are supposed to submit the form.", "నీవు ఫారం సమర్పించాల్సి ఉంది.", "nīvu phāraṃ samarpiñcālsi undi."],
        ["The bus is supposed to come at six.", "బస్సు ఆరుగంటలకు రావాల్సి ఉంది.", "bassu ārugaṇṭalaku rāvālsi undi."],
        ["She is supposed to be here.", "ఆమె ఇక్కడ ఉండాల్సి ఉంది.", "āme ikkaḍa uṇḍālsi undi."],
        ["They were supposed to finish this work.", "వారు ఈ పని పూర్తిచేయాల్సి ఉండేది.", "vāru ī pani pūrticēyālsi uṇḍēdi."],
        ["Am I supposed to wait?", "నేను ఎదురు చూడాలా?", "nēnu eduru cūdālā?"],
        ["Guests are supposed to arrive tomorrow.", "అతిథులు రేపు రావాల్సి ఉంది.", "atithulu rēpu rāvālsi undi."],
        ["You were not supposed to tell this.", "ఇది నీవు చెప్పకూడదు.", "idi nīvu ceppakūḍadu."],
        ["He is supposed to pay the bill.", "అతను బిల్లు కట్టాల్సి ఉంది.", "atanu billu kaṭṭālsi undi."],
        ["Students are supposed to wear uniform.", "విద్యార్థులు యూనిఫారం ధరించాల్సి ఉంది.", "vidyārthulu yūniphāraṃ dharin̄cālsi undi."],
        ["The meeting was supposed to start at ten.", "మీటింగ్ పది గంటలకు ప్రారంభమవాల్సి ఉండేది.", "mīṭiṅg padi gaṇṭalaku prārambhamavālsi uṇḍēdi."],
        ["I was supposed to leave early.", "నేను త్వరగా బయటకు వెళ్లాల్సి ఉండేది.", "nēnu tvaragā bayataku veḷḷālsi uṇḍēdi."],
        ["She is supposed to cook today.", "ఆమె ఇవాళ వంట చేయాల్సి ఉంది.", "āme ivāḷ vaṇṭa cēyālsi undi."],
    ],
    768: [  # To Like with verbs - నాకు చదవడం ఇష్టం
        ["I like to read books.", "నాకు పుస్తకాలు చదవడం ఇష్టం.", "nāku pustakālu cadavaḍaṃ iṣṭaṃ."],
        ["She likes to sing songs.", "ఆమెకి పాటలు పాడడం ఇష్టం.", "āmeki pāṭalu pāḍaḍaṃ iṣṭaṃ."],
        ["They like to play cricket.", "వారికి క్రికెట్ ఆడడం ఇష్టం.", "vāriki krikeṭ āḍaḍaṃ iṣṭaṃ."],
        ["We like to travel.", "మాకు ప్రయాణం చేయడం ఇష్టం.", "māku prayāṇaṃ cēyaḍaṃ iṣṭaṃ."],
        ["He likes to cook.", "అతనికి వంట చేయడం ఇష్టం.", "ataniki vaṇṭa cēyaḍaṃ iṣṭaṃ."],
        ["Children like to draw.", "పిల్లలకు చిత్రాలు వేయడం ఇష్టం.", "pillalaku citrālu vēyaḍaṃ iṣṭaṃ."],
        ["Do you like to dance?", "నీకు డ్యాన్స్ చేయడం ఇష్టమా?", "nīku ḍyāns cēyaḍaṃ iṣṭamā?"],
        ["She doesn't like to wait.", "ఆమెకి ఎదురు చూడడం ఇష్టం లేదు.", "āmeki eduru cūḍaḍaṃ iṣṭaṃ lēdu."],
        ["I like to help others.", "ఇతరులకు సహాయం చేయడం నాకు ఇష్టం.", "itarulaku sahāyaṃ cēyaḍaṃ nāku iṣṭaṃ."],
        ["We like to learn new things.", "కొత్త విషయాలు నేర్చుకోవడం మాకు ఇష్టం.", "kotta viṣayālu nērchukōvaḍaṃ māku iṣṭaṃ."],
        ["He likes to watch movies.", "అతనికి సినిమాలు చూడడం ఇష్టం.", "ataniki sinimālu cūḍaḍaṃ iṣṭaṃ."],
        ["She likes to write letters.", "ఆమెకి ఉత్తరాలు రాయడం ఇష్టం.", "āmeki uttarālu rāyaḍaṃ iṣṭaṃ."],
        ["They like to swim.", "వారికి ఈత కొట్టడం ఇష్టం.", "vāriki īta koṭṭaḍaṃ iṣṭaṃ."],
        ["I like to drink coffee.", "నాకు కాఫీ తాగడం ఇష్టం.", "nāku kāphī tāgaḍaṃ iṣṭaṃ."],
        ["We don't like to argue.", "మాకు వాదించడం ఇష్టం లేదు.", "māku vādin̄caḍaṃ iṣṭaṃ lēdu."],
    ],
    769: [  # Verbs with preposition To - అతనికి ఇచ్చాను pattern
        ["I gave the book to him.", "అతనికి పుస్తకం ఇచ్చాను.", "ataniki pustakaṃ icchānu."],
        ["She spoke to the teacher.", "ఆమె గురువుతో మాట్లాడింది.", "āme guruvutō māṭlāḍindi."],
        ["He wrote a letter to his friend.", "అతను తన స్నేహితుడికి ఉత్తరం రాశాడు.", "atanu tana snēhituḍiki uttaraṃ rāśāḍu."],
        ["We explained everything to them.", "మేము వారికి అన్నీ వివరించాము.", "mēmu vāriki annī vivarin̄cāmu."],
        ["They shouted to the children.", "వారు పిల్లలకు అరిచారు.", "vāru pillalaku aricāru."],
        ["Mother told a story to the kids.", "అమ్మ పిల్లలకు కథ చెప్పింది.", "amma pillalaku katha ceppindi."],
        ["I showed the way to him.", "అతనికి దారి చూపించాను.", "ataniki dāri cūpin̄cānu."],
        ["Can you listen to me?", "నువ్వు నన్ను వినగలవా?", "nuvvu nannu vinagalavā?"],
        ["We sent money to our parents.", "మేము మా తల్లిదండ్రులకు డబ్బు పంపాము.", "mēmu mā tallidaṇḍrulaku ḍabbu paṃpāmu."],
        ["She smiled at me.", "ఆమె నా వైపు నవ్వింది.", "āme nā vaipu navvindi."],
        ["He returned the book to the library.", "అతను పుస్తకం లైబ్రరీకి తిరిగి ఇచ్చాడు.", "atanu pustakaṃ laibrarīki tirigi icchāḍu."],
        ["Please give this to her.", "దయచేసి ఇది ఆమెకి ఇవ్వండి.", "dayacēsi idi āmeki ivvaṇḍi."],
        ["I promised to help him.", "అతనికి సహాయం చేస్తానని వాగ్దానం చేశాను.", "ataniki sahāyaṃ cēstānanī vāgdānaṃ cēśānu."],
        ["She introduced me to her family.", "ఆమె నన్ను ఆమె కుటుంబానికి పరిచయం చేసింది.", "āme nannu āme kuṭumbānikī paricayaṃ cēsindi."],
        ["They offered water to the guests.", "వారు అతిథులకు నీళ్లు అందించారు.", "vāru atithulaku nīḷḷu andin̄cāru."],
    ],
    770: [  # Short forms - వెళ్తున్నా వస్తున్నాం
        ["I'm going.", "నేను వెళ్తున్నా.", "nēnu veḷtunnā."],
        ["We're coming.", "మేము వస్తున్నాం.", "mēmu vastunnāṃ."],
        ["He's doing it.", "అతను చేస్తున్నాడు.", "atanu cēstunnāḍu."],
        ["What are you doing?", "ఏం చేస్తున్నావ్?", "ēṃ cēstunnāv?"],
        ["Where are you?", "ఎక్కడున్నావ్?", "ekkaḍunnāv?"],
        ["I'll call you.", "నిన్ను కాల్ చేస్తా.", "ninnu kāl cēstā."],
        ["We'll see later.", "తర్వాత చూద్దాం.", "tarvāta cūddāṃ."],
        ["I don't know.", "నాకు తెలీదు రా.", "nāku telīdu rā."],
        ["Come fast.", "త్వరగా రా.", "tvaragā rā."],
        ["Sit down.", "కూర్చో రా.", "kūrcō rā."],
        ["She's sleeping.", "ఆమె నిద్రపోతోంది.", "āme nidrapōtōndi."],
        ["They're eating.", "వారు తింటున్నారు.", "vāru tintunnāru."],
        ["I'm tired.", "నాకు అలసిపోయింది.", "nāku alasipōyindi."],
        ["Let's go.", "వెళ్దాం.", "veldāṃ."],
        ["It's okay.", "పరవాలేదు.", "paravālēdu."],
    ],
    771: [  # Greetings, Wishes, Blessings
        ["Namaste.", "నమస్తే.", "namastē."],
        ["Good morning.", "శుభోదయం.", "śubhōdayaṃ."],
        ["Good night.", "శుభరాత్రి.", "śubharātri."],
        ["Happy birthday!", "పుట్టినరోజు శుభాకాంక్షలు!", "puṭṭinarōju śubhākāṅkṣalu!"],
        ["Happy New Year!", "నూతన సంవత్సర శుభాకాంక్షలు!", "nūtana samvatsara śubhākāṅkṣalu!"],
        ["Best wishes for your exam.", "నీ పరీక్షకు శుభాకాంక్షలు.", "nī parīkṣaku śubhākāṅkṣalu."],
        ["May you live long.", "నువ్వు దీర్ఘాయుష్మాన్ భవ.", "nuvvu dīrghāyuṣmān bhava."],
        ["Get well soon.", "త్వరగా కోలుకో.", "tvaragā kōlukō."],
        ["Long live our country.", "జై హింద్! మా దేశం చిరంజీవి కావాలి.", "jai hind! mā dēśaṃ cirañjīvi kāvāli."],
        ["Happy Diwali!", "దీపావళి శుభాకాంక్షలు!", "dīpāvaḷi śubhākāṅkṣalu!"],
        ["Happy Ugadi!", "ఉగాది శుభాకాంక్షలు!", "ugādi śubhākāṅkṣalu!"],
        ["Good afternoon.", "శుభ మధ్యాహ్నం.", "śubha madhyāhnaṃ."],
        ["Good evening.", "శుభ సాయంత్రం.", "śubha sāyantraṃ."],
        ["Are you well?", "బాగున్నారా?", "bāgunnārā?"],
        ["Congratulations!", "అభినందనలు!", "abhinandanalu!"],
    ],
    772: [  # Compound verbs - తినేశాను వెళ్లిపోయాడు
        ["I ate it up.", "నేను తినేశాను.", "nēnu tinēśānu."],
        ["He went away.", "అతను వెళ్లిపోయాడు.", "atanu veḷḷipōyāḍu."],
        ["She gave it away.", "ఆమె ఇచ్చేశింది.", "āme icchēśindi."],
        ["He finished writing.", "అతను రాసేసాడు.", "atanu rāsēsāḍu."],
        ["We washed it off.", "మేము కడిగేశాము.", "mēmu kaḍigēśāmu."],
        ["They broke it completely.", "వారు పగలగొట్టేశారు.", "vāru pagalagōṭṭēśāru."],
        ["She read it and kept aside.", "ఆమె చదివేసి పెట్టింది.", "āme cadivēsi peṭṭindi."],
        ["Don't throw it away.", "అదిని పారేయకు.", "adini pārēyaku."],
        ["He forgot completely.", "అతను మరచిపోయాడు.", "atanu maracipōyāḍu."],
        ["Light turned off.", "లైట్ ఆఫైపోయింది.", "laiṭ āphaipōyindi."],
        ["She closed the door.", "ఆమె తలుపు మూసేసింది.", "āme talupu mūsēsindi."],
        ["We cleaned it up.", "మేము శుభ్రంచేసేశాము.", "mēmu śubhraṃcēsēśāmu."],
        ["He ran away.", "అతను పరుగెత్తి పోయాడు.", "atanu parugetti pōyāḍu."],
        ["She woke up.", "ఆమె నిద్రలేచింది.", "āme nidralēcindi."],
        ["I finished eating.", "నేను తినేశాను.", "nēnu tinēśānu."],
    ],
    773: [  # Calling/Addressing - ఓయి అన్నా అక్కా
        ["Hey, Ravi!", "ఓయ్ రవి!", "ōy ravi!"],
        ["Brother, please come here.", "అన్నా, ఇక్కడికి రా.", "annā, ikkaḍiki rā."],
        ["Sister, listen once.", "అక్కా, ఒక్కసారి విను.", "akkā, okkasāri vinu."],
        ["Uncle, please sit here.", "మామయ్య, ఇక్కడ కూర్చోండి.", "māmayya, ikkaḍa kūrcōṇḍi."],
        ["Aunt, have some tea.", "అత్తయ్య, కొంచెం టీ తాగండి.", "attayya, konchaṃ ṭī tāgaṇḍi."],
        ["Sir, may I come in?", "సార్, లోపలికి రావచ్చా?", "sār, lōpaliki rāvaccā?"],
        ["Madam, please sign here.", "మేడమ్, ఇక్కడ సైన్ చేయండి.", "mēḍam, ikkaḍa sain cēyaṇḍi."],
        ["Children, be quiet.", "పిల్లలూ, నిశ్శబ్దంగా ఉండండి.", "pillalū, niśśabdaṅgā uṇḍaṇḍi."],
        ["Friends, let's go.", "మిత్రులారా, వెళ్దాం.", "mitrulārā, veldāṃ."],
        ["Grandma, tell a story.", "అమ్మమ్మా, ఒక కథ చెప్పు.", "ammammā, oka katha ceppu."],
        ["Grandpa, where are you?", "తాతయ్య, ఎక్కడున్నారు?", "tātayya, ekkaḍunnāru?"],
        ["Doctor, I have pain.", "డాక్టర్ గారు, నాకు నొప్పి ఉంది.", "ḍākṭar gāru, nāku noppi undi."],
        ["Teacher, I have a doubt.", "సార్, నాకు సందేహం ఉంది.", "sār, nāku sandēhaṃ undi."],
        ["Driver, stop the bus.", "డ్రైవర్, బస్సు ఆపండి.", "ḍraivar, bassu āpaṇḍi."],
        ["Waiter, bring water.", "వెయిటర్, నీళ్లు తెచ్చండి.", "veyiṭar, nīḷḷu tecchaṇḍi."],
    ],
    774: [  # Exclamations - అయ్యో వావ్ అబ్బా
        ["Wow!", "వావ్!", "vāv!"],
        ["Oh no!", "అయ్యో!", "ayyō!"],
        ["Alas!", "అయ్యయ్యో!", "ayyayyō!"],
        ["Great!", "అద్భుతం!", "adbhutaṃ!"],
        ["How beautiful!", "ఎంత బాగుంది!", "enta bāgundi!"],
        ["How sad!", "చాలా దురదృష్టం!", "chālā duradṛṣṭaṃ!"],
        ["Oh God!", "ఓ దేవుడా!", "ō dēvuḍā!"],
        ["Fantastic!", "అరెరే! అదిరిపోయింది!", "arerē! adiripōyindi!"],
        ["What a shame!", "చీ చీ!", "chī chī!"],
        ["Wow, that's nice!", "అబ్బా, బాగా ఉంది!", "abbā, bāgā undi!"],
        ["Oh my God!", "అరే బాబోయ్!", "arē bābōy!"],
        ["Really?", "ఓహో! నిజమా?", "ōhō! nijamā?"],
        ["Did you see?", "చూసావా?", "cūsāvā?"],
        ["How wonderful!", "ఎంత అద్భుతం!", "enta adbhutaṃ!"],
        ["Oh dear!", "అయ్యో పాపము!", "ayyō pāpamu!"],
    ],
    775: [  # Requesting - May I / Can you
        ["May I sit here?", "నేను ఇక్కడ కూర్చోవచ్చా?", "nēnu ikkaḍa kūrcōvaccā?"],
        ["Can you help me, please?", "దయచేసి నాకు సహాయం చేస్తారా?", "dayacēsi nāku sahāyaṃ cēstārā?"],
        ["Could you open the window?", "దయచేసి కిటికీ తెరవగలరా?", "dayacēsi kiṭikī teravagalarā?"],
        ["May I come in?", "లోపలికి రావచ్చా?", "lōpaliki rāvaccā?"],
        ["Please give me some water.", "కొంచెం నీళ్లు ఇస్తారా?", "konchaṃ nīḷḷu istārā?"],
        ["Can you repeat once?", "ఒక్కసారి మళ్లీ చెబుతారా?", "okkasāri mallī chebutārā?"],
        ["Please wait for a minute.", "ఒక నిమిషం వేచి ఉండండి.", "oka nimiṣaṃ vēci uṇḍaṇḍi."],
        ["Would you close the door?", "దయచేసి తలుపు మూసేస్తారా?", "dayacēsi talupu mūsēstārā?"],
        ["Please speak slowly.", "దయచేసి నెమ్మదిగా మాట్లాడండి.", "dayacēsi nemmadigā māṭlāḍaṇḍi."],
        ["Can I ask you something?", "మీని ఏదో అడగవచ్చా?", "mīni ēdō aḍagavaccā?"],
        ["May I use your phone?", "మీ ఫోన్ వాడవచ్చా?", "mī phōn vāḍavaccā?"],
        ["Could you lend me a pen?", "ఒక పెన్ ఇవ్వగలరా?", "oka pen ivvagalarā?"],
        ["Please don't go.", "దయచేసి వెళ్లకండి.", "dayacēsi veḷḷakaṇḍi."],
        ["Can you show me the way?", "దారి చూపిస్తారా?", "dāri cūpistārā?"],
        ["Would you mind moving?", "కొంచెం కదిలిస్తారా?", "konchaṃ kadilistārā?"],
    ],
    776: [  # May, Might - uncertainty
        ["It may rain.", "వర్షం పడవచ్చు.", "varṣaṃ paḍavaccu."],
        ["He might come late.", "అతను ఆలస్యంగా రావచ్చు.", "atanu ālasyāṅgā rāvaccu."],
        ["She may not agree.", "ఆమె ఒప్పుకోకపోవచ్చు.", "āme oppukōkapōvaccu."],
        ["We might miss the train.", "మనం రైలును మిస్ కావచ్చు.", "manaṃ railunu mis kāvaccu."],
        ["They may ask questions.", "వారు ప్రశ్నలు అడగవచ్చు.", "vāru praśnalu aḍagavaccu."],
        ["It might be true.", "అది నిజమవచ్చు.", "adi nijamavaccu."],
        ["He may have left.", "అతను వెళ్లిపోయి ఉండవచ్చు.", "atanu veḷḷipōyi uṇḍavaccu."],
        ["She might be sleeping.", "ఆమె నిద్రపోతూ ఉండవచ్చు.", "āme nidrapōtū uṇḍavaccu."],
        ["The bus might be late.", "బస్సు ఆలస్యంగా రావచ్చు.", "bassu ālasyāṅgā rāvaccu."],
        ["I may not come tomorrow.", "నేను రేపు రాకపోవచ్చు.", "nēnu rēpu rākapōvaccu."],
        ["It might rain today.", "ఇవాళ వర్షం పడవచ్చు.", "ivāḷ varṣaṃ paḍavaccu."],
        ["They might have forgotten.", "వారు మరచిపోయి ఉండవచ్చు.", "vāru maracipōyi uṇḍavaccu."],
        ["She may know the answer.", "ఆమెకి సమాధానం తెలిసి ఉండవచ్చు.", "āmeki samādhānaṃ telisi uṇḍavaccu."],
        ["We might need help.", "మనకు సహాయం అవసరమవచ్చు.", "manaku sahāyaṃ avasaramavaccu."],
        ["He might be busy.", "అతను బిజీగా ఉండవచ్చు.", "atanu bijīgā uṇḍavaccu."],
    ],
    777: [  # Adjectives from verb - పరుగెత్తుతున్న విరిగిన
        ["The running boy.", "పరుగెత్తుతున్న అబ్బాయి.", "parugettunna abbāyi."],
        ["A broken glass.", "విరిగిన గ్లాస్.", "virigina glās."],
        ["The sleeping child.", "నిద్రపోతున్న పిల్లవాడు.", "nidrapōtunna pillavāḍu."],
        ["Written work.", "రాసిన పని.", "rāsina pani."],
        ["The crying baby.", "ఏడుతున్న బిడ్డ.", "ēḍutunna biḍḍa."],
        ["A closed door.", "మూసిన తలుపు.", "mūsina talupu."],
        ["The coming train.", "వస్తున్న రైలు.", "vastunna railu."],
        ["Cooked food.", "వండిన ఆహారం.", "vaṇḍina āhāraṃ."],
        ["The reading girl.", "చదువుతున్న అమ్మాయి.", "caduvutunna ammāyi."],
        ["A torn shirt.", "కీడిన చొక్కా.", "kīḍina cokkā."],
        ["The walking man.", "నడుస్తున్న మనిషి.", "naḍustunna maniṣi."],
        ["Lost keys.", "పోయిన తాళాలు.", "pōyina tāḷālu."],
        ["The singing bird.", "పాడుతున్న పక్షి.", "pāḍutunna pakṣi."],
        ["A painted wall.", "వేసిన గోడ.", "vēsina gōḍa."],
        ["The falling leaves.", "పడుతున్న ఆకులు.", "paḍutunna ākulu."],
    ],
    778: [  # Adjectives with prepositions - full of, afraid of
        ["Full of water.", "నీటితో నిండి ఉంది.", "nīṭitō niṇḍi undi."],
        ["Afraid of dogs.", "కుక్కలకు భయం.", "kukkalaku bhayaṃ."],
        ["Proud of you.", "నీ మీద గర్వం.", "nī mīda garvaṃ."],
        ["Tired of waiting.", "ఎదురు చూడడంతో అలసిపోయింది.", "eduru cūḍaḍaṃtō alasipōyindi."],
        ["Fond of music.", "సంగీతం మీద ఇష్టం.", "saṅgītaṃ mīda iṣṭaṃ."],
        ["Aware of the problem.", "సమస్య గురించి తెలుసు.", "samasya gurin̄ci telusu."],
        ["Capable of doing it.", "దాన్ని చేయగల సామర్థ్యం.", "dānni cēyagala sāmarthyaṃ."],
        ["Sure of success.", "విజయంపై ఖచ్చితం.", "vijayaṃpai khaccitaṃ."],
        ["Guilty of the crime.", "నేరంపై నేరస్థుడు.", "nēraṃpai nērasthuḍu."],
        ["Worthy of respect.", "గౌరవానికి అర్హుడు.", "gauravāniki arhuḍu."],
        ["Full of joy.", "సంతోషంతో నిండి ఉంది.", "santoṣaṃtō niṇḍi undi."],
        ["Afraid of the dark.", "చీకటికి భయం.", "cīkaṭiki bhayaṃ."],
        ["Tired of work.", "పనితో అలసిపోయింది.", "panitō alasipōyindi."],
        ["Proud of his son.", "తన కుమారుడిపై గర్వం.", "tana kumāruḍipai garvaṃ."],
        ["Aware of the danger.", "ప్రమాదం గురించి తెలుసు.", "pramādaṃ gurin̄ci telusu."],
    ],
    779: [  # May to express wish - ఆశీర్వదించాలి
        ["May you be happy.", "నీకు సంతోషంగా ఉండాలి.", "nīku santoṣaṅgā uṇḍāli."],
        ["May God bless you.", "దేవుడు నిన్ను దీవించుగాక.", "dēvuḍu ninnu dīvin̄cugāka."],
        ["May you succeed.", "నీకు విజయం లభించాలి.", "nīku vijayaṃ labhin̄cāli."],
        ["May he recover soon.", "అతను త్వరగా కోలుకోవాలి.", "atanu tvaragā kōlukōvāli."],
        ["May they be happy.", "వారు సంతోషంగా ఉండాలి.", "vāru santoṣaṅgā uṇḍāli."],
        ["May your wishes come true.", "నీ కోరికలు నెరవేరాలి.", "nī kōrikalu neravērāli."],
        ["May the new year bring joy.", "నూతన సంవత్సరం సంతోషం తెచ్చుగాక.", "nūtana samvatsaraṃ santoṣaṃ tecchugāka."],
        ["May she live long.", "ఆమె దీర్ఘాయుష్మాన్ భవ.", "āme dīrghāyuṣmān bhava."],
        ["May we meet again.", "మనం మళ్లీ కలుసుకుందాం.", "manaṃ mallī kalusukundāṃ."],
        ["May peace prevail.", "శాంతి నెలకొనాలి.", "śānti nelakonāli."],
        ["May you have a safe journey.", "నీకు సురక్షిత ప్రయాణం కావాలి.", "nīku surakṣita prayāṇaṃ kāvāli."],
        ["May God help you.", "దేవుడు నీకు సహాయం చేయుగాక.", "dēvuḍu nīku sahāyaṃ cēyugāka."],
        ["May the child be healthy.", "పిల్లవాడు ఆరోగ్యంగా ఉండాలి.", "pillavāḍu ārōgyaṅgā uṇḍāli."],
        ["May your exam go well.", "నీ పరీక్ష బాగా జరగాలి.", "nī parīkṣa bāgā jaragāli."],
        ["May happiness be with you.", "నీతో సంతోషం ఉండుగాక.", "nītō santoṣaṃ uṇḍugāka."],
    ],
    780: [  # Make someone do - చేయించాను తినిపించింది
        ["I made him work.", "నేను అతనితో పని చేయించాను.", "nēnu atanitō pani cēyin̄cānu."],
        ["She made the child eat.", "ఆమె పిల్లకు తినిపించింది.", "āme pillaku tinipin̄cindi."],
        ["He made me wait.", "అతను నన్ను ఎదురు చూడిపించాడు.", "atanu nannu eduru cūḍipin̄cāḍu."],
        ["Mother made the child study.", "అమ్మ పిల్లవాడికి చదివించింది.", "amma pillavāḍiki cadivin̄cindi."],
        ["I made her sing.", "నేను ఆమెకు పాడించాను.", "nēnu āmeki pāḍin̄cānu."],
        ["Teacher made students write.", "గురువు విద్యార్థులకు రాయించారు.", "guruvu vidyārthulaku rāyin̄cāru."],
        ["She made him clean the room.", "ఆమె అతనితో గది శుభ్రంచేయించింది.", "āme atanitō gadi śubhraṃcēyin̄cindi."],
        ["Father made the boy go.", "నాన్న అబ్బాయిని వెళ్లిపంపించాడు.", "nānna abbāyini veḷḷipaṃpin̄cāḍu."],
        ["We made them listen.", "మేము వారిని వినిపించాము.", "mēmu vārini vinipin̄cāmu."],
        ["He made the dog run.", "అతను కుక్కను పరుగెత్తించాడు.", "atanu kukkanu parugettin̄cāḍu."],
        ["She made me laugh.", "ఆమె నన్ను నవ్వించింది.", "āme nannu navvin̄cindi."],
        ["Boss made us stay late.", "బాస్ మమ్మల్ని ఆలస్యంగా ఉండిపించాడు.", "bās mammalni ālasyāṅgā uṇḍipin̄cāḍu."],
        ["I made him understand.", "నేను అతనికి అర్థం చేయించాను.", "nēnu ataniki arthaṃ cēyin̄cānu."],
        ["They made the child sleep.", "వారు పిల్లకు నిద్రపుచ్చారు.", "vāru pillaku nidrapucchāru."],
        ["She made the water boil.", "ఆమె నీళ్లు కాచించింది.", "āme nīḷḷu kācin̄cindi."],
    ],
    781: [  # Emphasize - నేనే మాత్రమే
        ["I myself did it.", "నేనే చేశాను.", "nēnē cēśānu."],
        ["He only came.", "అతను మాత్రమే వచ్చాడు.", "atanu mātramē vaccāḍu."],
        ["She herself told me.", "ఆమెయే నాకు చెప్పింది.", "āmeyē nāku ceppindi."],
        ["We ourselves will do it.", "మేమే చేస్తాం.", "mēmē cēstāṃ."],
        ["The teacher himself came.", "గురువుగారే వచ్చారు.", "guruvugārē vaccāru."],
        ["Only you can help.", "నువ్వే సహాయం చేయగలవు.", "nuvvē sahāyaṃ cēyagalavu."],
        ["It is he who said it.", "అతనే చెప్పాడు.", "atanē ceppāḍu."],
        ["Even I don't know.", "నాకు కూడా తెలియదు.", "nāku kūḍā teliyadu."],
        ["That very day he left.", "ఆ రోజునే అతను వెళ్లిపోయాడు.", "ā rōjunē atanu veḷḷipōyāḍu."],
        ["Only then did I understand.", "అప్పుడే నాకు అర్థమైంది.", "appuḍē nāku arthamaindi."],
        ["I too want to come.", "నాకు కూడా రావాలనిపిస్తోంది.", "nāku kūḍā rāvālanipistōndi."],
        ["He alone finished the work.", "అతను ఒక్కడే పని పూర్తిచేశాడు.", "atanu okkaḍē pani pūrticēśāḍu."],
        ["She herself is responsible.", "ఆమెయే బాధ్యత వహిస్తోంది.", "āmeyē bādhyata vahistōndi."],
        ["Exactly this is what I wanted.", "ఇదే నాకు కావాల్సింది.", "idē nāku kāvālsiṃdi."],
        ["Even children know this.", "పిల్లలకు కూడా ఇది తెలుసు.", "pillalaku kūḍā idi telusu."],
    ],
    782: [  # Generalising - ఎవరో ఎక్కడో ఏదైనా
        ["Someone called.", "ఎవరో ఫోన్ చేశారు.", "evarō phōn cēśāru."],
        ["I want to go somewhere.", "నాకు ఎక్కడికో వెళ్లాలనుంది.", "nāku ekkaḍikō veḷḷālanundi."],
        ["Anyone can do it.", "ఎవరైనా చేయగలరు.", "evarainā cēyagalaru."],
        ["Something happened.", "ఏదో జరిగింది.", "ēdō jarigindi."],
        ["I'll do it somehow.", "ఏదో విధంగా చేస్తాను.", "ēdō vidhaṃgā cēstānu."],
        ["Someone is at the door.", "ఎవరో తలుపు దగ్గర ఉన్నారు.", "evarō talupu daggara unnāru."],
        ["We met somewhere.", "మనం ఎక్కడో కలిశాం.", "manaṃ ekkaḍō kaliśāṃ."],
        ["Tell me anything.", "ఏదైనా చెప్పు.", "ēdainā ceppu."],
        ["Anybody can help.", "ఎవరైనా సహాయం చేయగలరు.", "evarainā sahāyaṃ cēyagalaru."],
        ["I need something.", "నాకు ఏదో కావాలి.", "nāku ēdō kāvāli."],
        ["We'll go somewhere nice.", "మనం ఎక్కడో మంచిచోటికి వెళ్తాం.", "manaṃ ekkaḍō man̄cicōṭiki veḷtāṃ."],
        ["Somehow we managed.", "ఏదో విధంగా నిభాయించాము.", "ēdō vidhaṃgā nibhāyin̄cāmu."],
        ["Anyone can try.", "ఎవరైనా ప్రయత్నించవచ్చు.", "evarainā prayatnin̄cavaccu."],
        ["Something is wrong.", "ఏదో తప్పు ఉంది.", "ēdō tappu undi."],
        ["I'll call you sometime.", "ఎప్పుడో నిన్ను కాల్ చేస్తాను.", "eppuḍō ninnu kāl cēstānu."],
    ],
    783: [  # To have - possession
        ["I have a car.", "నా దగ్గర కారు ఉంది.", "nā daggara kāru undi."],
        ["She has a brother.", "ఆమెకు అన్నయ్య ఉన్నాడు.", "āmeku annayya unnāḍu."],
        ["He has two children.", "అతనికి ఇద్దరు పిల్లలు ఉన్నారు.", "ataniki iddaru pillalu unnāru."],
        ["We have a big house.", "మాకు పెద్ద ఇల్లు ఉంది.", "māku peḍḍa illu undi."],
        ["They have many books.", "వారికి చాలా పుస్తకాలు ఉన్నాయి.", "vāriki chālā pustakālu unnāyi."],
        ["Do you have a pen?", "నీ దగ్గర పెన్ ఉందా?", "nī daggara pen undā?"],
        ["She has long hair.", "ఆమెకు పొడవైన వెంట్రుకలు ఉన్నాయి.", "āmeku poḍavaina ven̄trukalu unnāyi."],
        ["He has no money.", "అతని దగ్గర డబ్బు లేదు.", "atani daggara ḍabbu lēdu."],
        ["I have a question.", "నాకు ఒక ప్రశ్న ఉంది.", "nāku oka praśna undi."],
        ["We have time.", "మాకు సమయం ఉంది.", "māku samayaṃ undi."],
        ["She has a beautiful smile.", "ఆమెకు అందమైన నవ్వు ఉంది.", "āmeku andamaina navvu undi."],
        ["He has three sisters.", "అతనికి ముగ్గురు సోదరీమణులు ఉన్నారు.", "ataniki mugguru sōdarīmaṇulu unnāru."],
        ["They have a dog.", "వారికి ఒక కుక్క ఉంది.", "vāriki oka kukka undi."],
        ["I have an idea.", "నాకు ఒక ఆలోచన ఉంది.", "nāku oka ālōcana undi."],
        ["We have enough food.", "మాకు తగినంత ఆహారం ఉంది.", "māku taginaṃta āhāraṃ undi."],
    ],
    784: [  # To mean - అర్థం ఏమిటి
        ["What does this mean?", "ఇది అర్థం ఏమిటి?", "idi arthaṃ ēmiṭi?"],
        ["I mean it.", "నేను అంటే అదే.", "nēnu aṇṭē adē."],
        ["What do you mean?", "నీకు అంటే ఏమిటి?", "nīku aṇṭē ēmiṭi?"],
        ["This word means happiness.", "ఈ పదానికి అర్థం సంతోషం.", "ī padāniki arthaṃ santoṣaṃ."],
        ["I didn't mean to hurt you.", "నిన్ను బాధపెట్టాలని ఉద్దేశం లేదు.", "ninnu bādhapeṭṭālanī uddēśaṃ lēdu."],
        ["What does that sign mean?", "ఆ గుర్తుకు అర్థం ఏమిటి?", "ā gurtuku arthaṃ ēmiṭi?"],
        ["She means well.", "ఆమె మంచిది అనుకుంటోంది.", "āme man̄cidi anukuṇṭōndi."],
        ["By that I mean tomorrow.", "అంటే రేపు అని.", "aṇṭē rēpu ani."],
        ["Can you explain the meaning?", "అర్థం వివరించగలరా?", "arthaṃ vivarin̄cagalarā?"],
        ["This means a lot to me.", "ఇది నాకు చాలా అర్థం.", "idi nāku chālā arthaṃ."],
        ["What is the meaning of this?", "ఇది ఏమిటి అర్థం?", "idi ēmiṭi arthaṃ?"],
        ["I mean what I said.", "నేను చెప్పిందే అర్థం.", "nēnu ceppindē arthaṃ."],
        ["That means we are late.", "అంటే మనం ఆలస్యంగా వచ్చాం.", "aṇṭē manaṃ ālasyāṅgā vaccāṃ."],
        ["Do you understand what I mean?", "నా అంటే ఏమిటో అర్థమైందా?", "nā aṇṭē ēmiṭō arthamaindā?"],
        ["The same meaning.", "అదే అర్థం.", "adē arthaṃ."],
    ],
    785: [  # Conjunctions 1 - And, But, Because, So, That
        ["I am reading and writing.", "నేను చదువుతున్నాను మరియు రాస్తున్నాను.", "nēnu caduvutunnānu mariyu rāstunnānu."],
        ["This is beautiful but that is not.", "ఇది అందంగా ఉంది కానీ అది కాదు.", "idi andaṅgā undi kānī adi kādu."],
        ["I am happy because I saw you.", "నిన్ను చూసినందుకు నేను సంతోషంగా ఉన్నాను.", "ninnu cūsinanduku nēnu santoṣaṅgā unnānu."],
        ["It was raining so we stayed.", "వర్షం పడుతోంది కాబట్టి మేము ఉండిపోయాము.", "varṣaṃ paḍutōndi kābaṭṭi mēmu uṇḍipōyāmu."],
        ["I know that he will come.", "అతను వస్తాడని నాకు తెలుసు.", "atanu vastāḍani nāku telusu."],
        ["She is tall and smart.", "ఆమె ఎత్తుగా ఉంది మరియు తెలివైనది.", "āme ettugā undi mariyu telivainadi."],
        ["I tried but failed.", "నేను ప్రయత్నించాను కానీ విఫలమయ్యాను.", "nēnu prayatnin̄cānu kānī viphalamayyānu."],
        ["We left early because of traffic.", "ట్రాఫిక్ ఉన్నందుకు మేము త్వరగా బయటకు వెళ్లాము.", "ṭrāphik unnaṃduku mēmu tvaragā bayataku veḷḷāmu."],
        ["He was tired so he slept.", "అలసిపోయినందుకు అతను నిద్రపోయాడు.", "alasipōyinaṃduku atanu nidrapōyāḍu."],
        ["Tell me that you understand.", "నీకు అర్థమైందని చెప్పు.", "nīku arthamaindani ceppu."],
        ["Tea and coffee are available.", "టీ మరియు కాఫీ ఉన్నాయి.", "ṭī mariyu kāphī unnāyi."],
        ["It is cheap but good.", "ఇది చౌక కానీ మంచిది.", "idi cauka kānī man̄cidi."],
        ["Because you asked I came.", "నువ్వు అడిగినందుకు నేను వచ్చాను.", "nuvvu aḍiginaṃduku nēnu vaccānu."],
        ["So that you understand.", "నీకు అర్థమవడానికి.", "nīku arthamavaḍāniki."],
        ["I hope that she comes.", "ఆమె వస్తుందని ఆశిస్తున్నాను.", "āme vastundi ani āśistunnānu."],
    ],
    786: [  # Conjunctions 2 - As, Or, If, in case, provided
        ["As you said.", "నువ్వు చెప్పినట్లు.", "nuvvu ceppinaṭlu."],
        ["Tea or coffee?", "టీ లేక కాఫీ?", "ṭī lēka kāphī?"],
        ["If you come we will go.", "నువ్వు వస్తే మేము వెళ్తాం.", "nuvvu vastē mēmu veḷtāṃ."],
        ["Do as I say.", "నేను చెప్పినట్లు చేయి.", "nēnu ceppinaṭlu cēyi."],
        ["Stay or leave?", "ఉండాలా లేక వెళ్లాలా?", "uṇḍālā lēka veḷḷālā?"],
        ["If it rains we will stay.", "వర్షం పడితే మేము ఉండిపోతాం.", "varṣaṃ paḍitē mēmu uṇḍipōtāṃ."],
        ["As far as I know.", "నాకు తెలిసినంత వరకు.", "nāku telisinaṃta varaku."],
        ["Red or blue?", "ఎరుపు లేక నీలం?", "erupu lēka nīlaṃ?"],
        ["In case of emergency call.", "అత్యవసరం లేకపోతే కాల్ చేయండి.", "atyavasaraṃ lēkapōtē kāl cēyaṇḍi."],
        ["As I told you.", "నేను నీకు చెప్పినట్లు.", "nēnu nīku ceppinaṭlu."],
        ["Morning or evening?", "ఉదయం లేక సాయంత్రం?", "udayaṃ lēka sāyantraṃ?"],
        ["Provided you agree.", "నువ్వు ఒప్పుకుంటే.", "nuvvu oppukuṇṭē."],
        ["As long as you are here.", "నువ్వు ఇక్కడ ఉన్నంత కాలం.", "nuvvu ikkaḍa unnaṃta kālaṃ."],
        ["Yes or no?", "అవునా లేక కాదా?", "avunā lēka kādā?"],
        ["If you want I will come.", "నీకు కావాలంటే నేను వస్తాను.", "nīku kāvālaṇṭē nēnu vastānu."],
    ],
    787: [  # Conjunctions 3 - After, then, As far as, As long as
        ["After eating we left.", "తిన్న తర్వాత మేము వెళ్లిపోయాము.", "tinna tarvāta mēmu veḷḷipōyāmu."],
        ["As long as you are here.", "నువ్వు ఇక్కడ ఉన్నంత కాలం.", "nuvvu ikkaḍa unnaṃta kālaṃ."],
        ["First study then play.", "ముందు చదువు తర్వాత ఆడు.", "mundu caduvu tarvāta āḍu."],
        ["As far as I know he is good.", "నాకు తెలిసినంత వరకు అతను మంచివాడు.", "nāku telisinaṃta varaku atanu man̄civāḍu."],
        ["After the meeting we will go.", "మీటింగ్ తర్వాత మేము వెళ్తాం.", "mīṭiṅg tarvāta mēmu veḷtāṃ."],
        ["As long as there is hope.", "ఆశ ఉన్నంత కాలం.", "āśa unnaṃta kālaṃ."],
        ["Then what happened?", "అప్పుడు ఏం జరిగింది?", "appuḍu ēṃ jarigindi?"],
        ["After he came we left.", "అతను వచ్చిన తర్వాత మేము వెళ్లిపోయాము.", "atanu vaccina tarvāta mēmu veḷḷipōyāmu."],
        ["As far as the eye can see.", "కంటికి కనిపించినంత వరకు.", "kaṇṭiki kanipin̄cinaṃta varaku."],
        ["As long as you are happy.", "నువ్వు సంతోషంగా ఉన్నంత కాలం.", "nuvvu santoṣaṅgā unnaṃta kālaṃ."],
        ["After school we play.", "స్కూల్ తర్వాత మేము ఆడుతాం.", "skūl tarvāta mēmu āḍutāṃ."],
        ["Then I understood.", "అప్పుడే నాకు అర్థమైంది.", "appuḍē nāku arthamaindi."],
        ["As far as possible.", "సాధ్యమైనంత వరకు.", "sādhyamainaṃta varaku."],
        ["After the rain it cooled.", "వర్షం తర్వాత చల్లగా అయింది.", "varṣaṃ tarvāta callagā ayindi."],
        ["As long as you need.", "నీకు అవసరమున్నంత కాలం.", "nīku avasaramunnaṃta kālaṃ."],
    ],
    788: [  # Conjunctions 4 - As soon as, Once, Rather than, So that
        ["As soon as he came.", "అతను వచ్చిన వెంటనే.", "atanu vaccina ven̄tanē."],
        ["Rather than that.", "అది కంటే.", "adi kaṇṭē."],
        ["So that you understand.", "నీకు అర్థమవడానికి.", "nīku arthamavaḍāniki."],
        ["As soon as I heard I came.", "విన్న వెంటనే నేను వచ్చాను.", "vinna ven̄tanē nēnu vaccānu."],
        ["Once you start you will like it.", "ఒకసారి ప్రారంభిస్తే నచ్చుతుంది.", "okasāri prārambhistē nacchutundi."],
        ["Rather than walking take a bus.", "నడవడం కంటే బస్సు ఎక్కు.", "naḍavaḍaṃ kaṇṭē bassu ekku."],
        ["So that we can finish.", "మేము పూర్తిచేయగలిగేటట్లు.", "mēmu pūrticēyagaligēṭaṭlu."],
        ["As soon as the bell rang.", "గంట మోగిన వెంటనే.", "gaṇṭa mōgina ven̄tanē."],
        ["Once upon a time.", "ఒకప్పుడు.", "okappuḍu."],
        ["Rather than tea I want coffee.", "టీ కంటే నాకు కాఫీ కావాలి.", "ṭī kaṇṭē nāku kāphī kāvāli."],
        ["So that everyone knows.", "అందరికి తెలిసేటట్లు.", "andariki telisēṭaṭlu."],
        ["As soon as possible.", "వీలైనంత త్వరగా.", "vīlainaṃta tvaragā."],
        ["Once you learn you won't forget.", "ఒకసారి నేర్చుకుంటే మరచిపోవు.", "okasāri nērchukuṇṭē maracipōvu."],
        ["Rather than complain do something.", "ఫిర్యాదు చేయడం కంటే ఏదో చేయి.", "phiryādu cēyaḍaṃ kaṇṭē ēdō cēyi."],
        ["So that it works.", "అది పనిచేసేటట్లు.", "adi panicēsēṭaṭlu."],
    ],
    789: [  # List of Conjunctions
        ["And – మరియు", "మరియు", "mariyu"],
        ["But – కానీ", "కానీ", "kānī"],
        ["Because – ఎందుకంటే", "ఎందుకంటే", "endukaṇṭē"],
        ["So – కాబట్టి", "కాబట్టి", "kābaṭṭi"],
        ["Or – లేక", "లేక", "lēka"],
        ["If – ఒకవేళ", "ఒకవేళ", "okavēḷa"],
        ["That – అని", "అని", "ani"],
        ["As – అట్లు", "అట్లు", "aṭlu"],
        ["When – ఎప్పుడు", "ఎప్పుడు", "eppuḍu"],
        ["After – తర్వాత", "తర్వాత", "tarvāta"],
        ["Before – ముందు", "ముందు", "mundu"],
        ["Although – అయినప్పటికీ", "అయినప్పటికీ", "ayinappaṭikī"],
        ["Until – వరకు", "వరకు", "varaku"],
        ["Since – నుండి", "నుండి", "nun̄ḍi"],
        ["While – సమయంలో", "సమయంలో", "samayaṃlō"],
    ],
    790: [  # Combining sentences
        ["I came and I saw.", "నేను వచ్చాను మరియు చూసాను.", "nēnu vaccānu mariyu cūsānu."],
        ["He left because he was tired.", "అలసిపోయినందుకు అతను వెళ్లిపోయాడు.", "alasipōyinaṃduku atanu veḷḷipōyāḍu."],
        ["She studied hard so she passed.", "బాగా చదివినందుకు ఆమె పాస్ అయింది.", "bāgā cadivinaṃduku āme pās ayindi."],
        ["We ate and then we left.", "మేము తిన్నాము మరియు తర్వాత వెళ్లిపోయాము.", "mēmu tinnāmu mariyu tarvāta veḷḷipōyāmu."],
        ["It's raining so take an umbrella.", "వర్షం పడుతోంది కాబట్టి గొడుగు తీసుకో.", "varṣaṃ paḍutōndi kābaṭṭi goḍugu tīsukō."],
        ["He came but she left.", "అతను వచ్చాడు కానీ ఆమె వెళ్లిపోయింది.", "atanu vaccāḍu kānī āme veḷḷipōyindi."],
        ["I called because I needed help.", "సహాయం కావాలని నేను కాల్ చేశాను.", "sahāyaṃ kāvālanī nēnu kāl cēśānu."],
        ["She smiled and waved.", "ఆమె నవ్వింది మరియు చేయి ఊపింది.", "āme navvindi mariyu cēyi ūpindi."],
        ["They were hungry so they ate.", "వారికి ఆకలి ఉంది కాబట్టి వారు తిన్నారు.", "vāriki ākali undi kābaṭṭi vāru tinnāru."],
        ["I know that he is honest.", "అతను నిజాయితీపరుడని నాకు తెలుసు.", "atanu nijāyitīparuḍani nāku telusu."],
        ["We waited but he didn't come.", "మేము ఎదురుచూశాము కానీ అతను రాలేదు.", "mēmu edurucūśāmu kānī atanu rālēdu."],
        ["Because you helped I succeeded.", "నువ్వు సహాయం చేసినందుకు నేను విజయం సాధించాను.", "nuvvu sahāyaṃ cēsinaṃduku nēnu vijayaṃ sādhin̄cānu."],
        ["She is tired so she is resting.", "ఆమె అలసిపోయింది కాబట్టి విశ్రాంతి తీసుకుంటోంది.", "āme alasipōyindi kābaṭṭi viśrānti tīsukuṇṭōndi."],
        ["I thought that you knew.", "నీకు తెలుసా అని అనుకున్నాను.", "nīku telusā ani anukunnānu."],
        ["He ran and caught the bus.", "అతను పరుగెత్తాడు మరియు బస్సు పట్టుకున్నాడు.", "atanu parugettāḍu mariyu bassu paṭṭukunnāḍu."],
    ],
    791: [  # Compound verbs 2
        ["He ran away.", "అతను పరుగెత్తి పోయాడు.", "atanu parugetti pōyāḍu."],
        ["She woke up.", "ఆమె నిద్రలేచింది.", "āme nidralēcindi."],
        ["We sat down.", "మేము కూర్చున్నాము.", "mēmu kūrcunnāmu."],
        ["They stood up.", "వారు నిలబడ్డారు.", "vāru nilabaḍḍāru."],
        ["I lay down.", "నేను పడుకున్నాను.", "nēnu paḍukunnānu."],
        ["He picked it up.", "అతను అది ఎత్తుకున్నాడు.", "atanu adi ettukunnāḍu."],
        ["She put it down.", "ఆమె అది పెట్టింది.", "āme adi peṭṭindi."],
        ["We cleaned it up.", "మేము శుభ్రంచేసేశాము.", "mēmu śubhraṃcēsēśāmu."],
        ["He turned it off.", "అతను ఆఫ్ చేసేశాడు.", "atanu āph cēsēśāḍu."],
        ["She turned it on.", "ఆమె ఆన్ చేసింది.", "āme ān cēsindi."],
        ["They gave up.", "వారు వదులుకున్నారు.", "vāru vadulukunnāru."],
        ["I looked up.", "నేను పైకి చూశాను.", "nēnu paiki cūśānu."],
        ["He went out.", "అతను బయటకు వెళ్లాడు.", "atanu bayataku veḷḷāḍu."],
        ["She came in.", "ఆమె లోపలికి వచ్చింది.", "āme lōpaliki vaccindi."],
        ["We moved on.", "మేము ముందుకు సాగాము.", "mēmu munduku sāgāmu."],
    ],
    792: [  # Active Passive
        ["Rice is eaten by us.", "అన్నం మాచే తినబడుతుంది.", "annaṃ mācē tinabaḍutundi."],
        ["The letter was written.", "ఉత్తరం రాయబడింది.", "uttaraṃ rāyabaḍindi."],
        ["The door was opened by him.", "తలుపు అతనిచే తెరవబడింది.", "talupu atanicē teravabaḍindi."],
        ["English is spoken here.", "ఇక్కడ ఇంగ్లీష్ మాట్లాడబడుతుంది.", "ikkaḍa ingliṣ māṭlāḍabaḍutundi."],
        ["The work was done.", "పని చేయబడింది.", "pani cēyabaḍindi."],
        ["The book is being read.", "పుస్తకం చదువబడుతోంది.", "pustakaṃ caduvabaḍutōndi."],
        ["The house was built.", "ఇల్లు కట్టబడింది.", "illu kaṭṭabaḍindi."],
        ["Tea is served.", "టీ పెట్టబడుతుంది.", "ṭī peṭṭabaḍutundi."],
        ["The song was sung.", "పాట పాడబడింది.", "pāṭa pāḍabaḍindi."],
        ["The car was driven.", "కారు నడపబడింది.", "kāru naḍapabaḍindi."],
        ["The lesson is taught.", "పాఠం బోధించబడుతుంది.", "pāṭhaṃ bōdhin̄cabaḍutundi."],
        ["The news was heard.", "వార్త వినబడింది.", "vārta vinabaḍindi."],
        ["The food is cooked.", "ఆహారం వండబడుతుంది.", "āhāraṃ vaṇḍabaḍutundi."],
        ["The window was broken.", "కిటికీ విరిగబడింది.", "kiṭikī virigabaḍindi."],
        ["The question was asked.", "ప్రశ్న అడగబడింది.", "praśna aḍagabaḍindi."],
    ],
    793: [  # Active Passive 2
        ["English is taught by her.", "ఇంగ్లీష్ ఆమెచే బోధించబడుతుంది.", "ingliṣ āmecē bōdhin̄cabaḍutundi."],
        ["The work was done.", "పని చేయబడింది.", "pani cēyabaḍindi."],
        ["The movie was watched.", "సినిమా చూడబడింది.", "sinimā cūḍabaḍindi."],
        ["The phone was answered.", "ఫోన్ జవాబిచ్చబడింది.", "phōn javābicchabaḍindi."],
        ["The room was cleaned.", "గది శుభ్రంచేయబడింది.", "gadi śubhraṃcēyabaḍindi."],
        ["The bill was paid.", "బిల్లు కట్టబడింది.", "billu kaṭṭabaḍindi."],
        ["The form was filled.", "ఫారం నింపబడింది.", "phāraṃ niṃpabaḍindi."],
        ["The meeting was held.", "మీటింగ్ జరిగింది.", "mīṭiṅg jarigindi."],
        ["The problem was solved.", "సమస్య పరిష్కరించబడింది.", "samasya pariṣkarin̄cabaḍindi."],
        ["The story was told.", "కథ చెప్పబడింది.", "katha ceppabaḍindi."],
        ["The gift was given.", "బహుమతి ఇవ్వబడింది.", "bahumati ivvabaḍindi."],
        ["The song was sung.", "పాట పాడబడింది.", "pāṭa pāḍabaḍindi."],
        ["The letter was sent.", "ఉత్తరం పంపబడింది.", "uttaraṃ paṃpabaḍindi."],
        ["The door was closed.", "తలుపు మూయబడింది.", "talupu mūyabaḍindi."],
        ["The cake was cut.", "కేక్ కత్తిరించబడింది.", "kēk kattirin̄cabaḍindi."],
    ],
    794: [  # To Feel & Think
        ["I feel happy.", "నాకు సంతోషంగా ఉంది.", "nāku santoṣaṅgā undi."],
        ["She thinks it is true.", "ఆమెకి అది నిజంగా ఉందని అనిపిస్తుంది.", "āmeki adi nijaṅgā undani anipistundi."],
        ["He feels tired.", "అతనికి అలసిపోయింది అనిపిస్తోంది.", "ataniki alasipōyindi anipistōndi."],
        ["I think you are right.", "నువ్వు సరైనవాడు అని నాకు అనిపిస్తోంది.", "nuvvu sarainavāḍu ani nāku anipistōndi."],
        ["She feels cold.", "ఆమెకి చలి అనిపిస్తోంది.", "āmeki cali anipistōndi."],
        ["We think it will rain.", "వర్షం పడుతుంది అని మాకు అనిపిస్తోంది.", "varṣaṃ paḍutundi ani māku anipistōndi."],
        ["He feels better now.", "అతనికి ఇప్పుడు బాగా అనిపిస్తోంది.", "ataniki ippuḍu bāgā anipistōndi."],
        ["I feel sorry.", "నాకు అయ్యో అనిపిస్తోంది.", "nāku ayyō anipistōndi."],
        ["She thinks he is lying.", "అతను అబద్ధం చెప్పుతున్నాడు అని ఆమె అనుకుంటోంది.", "atanu abaddhaṃ cepputunnāḍu ani āme anukuṇṭōndi."],
        ["They feel excited.", "వారికి ఉత్సాహంగా ఉంది.", "vāriki utsāhaṅgā undi."],
        ["I think so.", "నాకు అలా అనిపిస్తోంది.", "nāku alā anipistōndi."],
        ["She feels nervous.", "ఆమెకి భయంగా ఉంది.", "āmeki bhayaṃgā undi."],
        ["He thinks about it.", "అతను దాని గురించి ఆలోచిస్తున్నాడు.", "atanu dāni gurin̄ci ālōcistunnāḍu."],
        ["We feel proud.", "మాకు గర్వంగా ఉంది.", "māku garvaṃgā undi."],
        ["I feel like eating.", "నాకు తినాలనిపిస్తోంది.", "nāku tinālanipistōndi."],
    ],
    795: [  # Idioms 1
        ["Time is money.", "సమయం ధనం.", "samayaṃ dhanaṃ."],
        ["Practice makes perfect.", "అభ్యాసంతో నిపుణత వస్తుంది.", "abhyāsaṃtō nipuṇata vastundi."],
        ["Where there is a will there is a way.", "ఇచ్ఛ ఉంటే మార్గం ఉంటుంది.", "iccha uṇṭē mārgaṃ uṇṭundi."],
        ["Actions speak louder than words.", "కార్యాలు మాటల కంటే ఎక్కువ చెబుతాయి.", "kāryālu māṭala kaṇṭē ekkuva cebutāyi."],
        ["Better late than never.", "ఎప్పుడూ కాకుండా ఆలస్యంగా వస్తే మంచిది.", "eppuḍū kākuṇḍā ālasyāṅgā vastē man̄cidi."],
        ["Health is wealth.", "ఆరోగ్యమే ధనం.", "ārōgyamē dhanaṃ."],
        ["Honesty is the best policy.", "నిజాయితీ ఉత్తమ పద్ధతి.", "nijāyitī uttama paddhati."],
        ["Knowledge is power.", "జ్ఞానమే శక్తి.", "jñānamē śakti."],
        ["Unity is strength.", "ఐకమత్యమే బలం.", "aikamatyamē balaṃ."],
        ["Slow and steady wins the race.", "నెమ్మదిగా మరియు స్థిరంగా పరిగెడుతూ గెలుస్తాం.", "nemmadigā mariyu sthiraṃgā parigeḍutū gelustāṃ."],
        ["A stitch in time saves nine.", "సమయంలో చేసిన పని తర్వాత మేలు.", "samayaṃlō cēsina pani tarvāta mēlu."],
        ["All that glitters is not gold.", "మెరిసేదంతా బంగారం కాదు.", "merisēdaṃtā baṃgāraṃ kādu."],
        ["Experience is the best teacher.", "అనుభవమే ఉత్తమ గురువు.", "anubhavamē uttama guruvu."],
        ["No pain no gain.", "కష్టం లేకుండా లాభం లేదు.", "kaṣṭaṃ lēkuṇḍā lābhaṃ lēdu."],
        ["Rome was not built in a day.", "ఒక రోజులో చేసిన పని కాదు.", "oka rōjulō cēsina pani kādu."],
    ],
    796: [  # Idioms 2
        ["Actions speak louder.", "కార్యాలు మాటల కంటే ఎక్కువ చెబుతాయి.", "kāryālu māṭala kaṇṭē ekkuva cebutāyi."],
        ["Better late than never.", "ఎప్పుడూ కాకుండా ఆలస్యంగా వస్తే మంచిది.", "eppuḍū kākuṇḍā ālasyāṅgā vastē man̄cidi."],
        ["Health is wealth.", "ఆరోగ్యమే ధనం.", "ārōgyamē dhanaṃ."],
        ["Those who help in need are family.", "అక్కరకు వచ్చినవాడే మనవాడు.", "akkaraku vaccinavāḍē manavāḍu."],
        ["Delay turns nectar into poison.", "ఆలస్యం అమృతం విషం.", "ālasyāṃ amṛtaṃ viṣaṃ."],
        ["If speech is good village is good.", "నోరు మంచిదిఅయితే ఊరు మంచిదిఅవుతుంది.", "nōru man̄cidiayitē ūru man̄cidiavutundi."],
        ["Don't buy a pig in a poke.", "కీడెంచి మేలెంచమన్నారు.", "kīḍen̄ci mēlen̄camannāru."],
        ["Hunger doesn't know taste.", "ఆకలి రుచి ఎరుగదు.", "ākali ruci erugadu."],
        ["First come first served.", "ముందు వచ్చినవాడికి ముందు.", "mundu vaccinavāḍiki mundu."],
        ["A friend in need is a friend indeed.", "అత్యవసరంలో సహాయం చేసేవాడే స్నేహితుడు.", "atyavasaraṃlō sahāyaṃ cēsēvāḍē snēhituḍu."],
        ["Every cloud has a silver lining.", "అంధకారంలో కూడా వెలుగు ఉంటుంది.", "andhakāraṃlō kūḍā velugu uṇṭundi."],
        ["When in Rome do as Romans do.", "ఎక్కడ ఉంటే అక్కడ నియమాలు పాటించాలి.", "ekkaḍa uṇṭē akkaḍa niyamālu pāṭin̄cāli."],
        ["Birds of a feather flock together.", "ఒక రకమైనవారు ఒక్కడే ఉంటారు.", "oka rakamainavāru okkaḍē uṇṭāru."],
        ["Strike while the iron is hot.", "వేడిగా ఉన్నప్పుడు కొట్టేయి.", "vēḍigā unnappuḍu koṭṭēyi."],
        ["Look before you leap.", "జంప్ వేయడానికి ముందు చూడండి.", "jaṃp vēyaḍāniki mundu cūḍaṇḍi."],
    ],
    797: [  # If-Then Style 2 - conditional
        ["Had I known I would have come.", "తెలిసి ఉంటే నేను వచ్చేవాడిని.", "telisi uṇṭē nēnu vaccēvāḍini."],
        ["If you had told me.", "నాకు చెప్పి ఉంటే.", "nāku ceppi uṇṭē."],
        ["Were he here we would go.", "అతను ఇక్కడ ఉంటే మేము వెళ్లేవాళ్లం.", "atanu ikkaḍa uṇṭē mēmu veḷḷēvāḷḷaṃ."],
        ["Had she invited I would have gone.", "ఆమె ఆహ్వానించి ఉంటే నేను వెళ్లేవాడిని.", "āme āhvānin̄ci uṇṭē nēnu veḷḷēvāḍini."],
        ["If I had money I would buy.", "నాకు డబ్బు ఉంటే నేను కొనేవాడిని.", "nāku ḍabbu uṇṭē nēnu konēvāḍini."],
        ["Had she studied she would have passed.", "ఆమె చదివి ఉంటే పాస్ అయ్యేది.", "āme cadivi uṇṭē pās ayyēdi."],
        ["If you had come earlier.", "నువ్వు ముందుగా వచ్చి ఉంటే.", "nuvvu mundugā vacci uṇṭē."],
        ["Were it possible I would.", "సాధ్యమైతే నేను చేసేవాడిని.", "sādhyamaitē nēnu cēsēvāḍini."],
        ["Had she known she would have told.", "ఆమెకి తెలిసి ఉంటే చెప్పేది.", "āmeki telisi uṇṭē ceppēdi."],
        ["If you had asked I would have helped.", "నువ్వు అడిగి ఉంటే నేను సహాయం చేసేవాడిని.", "nuvvu aḍigi uṇṭē nēnu sahāyaṃ cēsēvāḍini."],
        ["Had she waited we would have met.", "ఆమె ఎదురుచూసి ఉంటే మేము కలుసుకునేవాళ్లం.", "āme edurucūsi uṇṭē mēmu kalusukunēvāḷḷaṃ."],
        ["If he had tried he would have succeeded.", "అతను ప్రయత్నించి ఉంటే విజయం సాధించేవాడు.", "atanu prayatnin̄ci uṇṭē vijayaṃ sādhin̄cēvāḍu."],
        ["Were you here I would tell.", "నువ్వు ఇక్కడ ఉంటే నేను చెప్పేవాడిని.", "nuvvu ikkaḍa uṇṭē nēnu ceppēvāḍini."],
        ["Had they known they would have come.", "వారికి తెలిసి ఉంటే వారు వచ్చేవాళ్లం.", "vāriki telisi uṇṭē vāru vaccēvāḷḷaṃ."],
        ["If I had time I would visit.", "నాకు సమయం ఉంటే నేను వెళ్లేవాడిని.", "nāku samayaṃ uṇṭē nēnu veḷḷēvāḍini."],
    ],
}

# Apply updates to data_telugu.json
with open(PATH, "r", encoding="utf-8") as f:
    data = json.load(f)

for ch in data:
    cid = ch.get("id")
    if cid in CONTENT:
        if "tables" in ch and ch["tables"]:
            ch["tables"][0]["rows"] = CONTENT[cid]
        ch["intro"] = "Practice topic-specific Telugu sentences with English and transliteration."

with open(PATH, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Updated {len(CONTENT)} chapters (765-797) with 15 unique sentences each.")

