// Auto-generated from lesson JSON — Phrases & Words tabs
const ASSAMESE_PHRASES = {
  greetings_1: {
    name: "Greetings",
    color: "#2B6CB0",
    icon: "👋",
    phrases: [
      { en: "What is your name?", mr: "আপনার নাম কী?", roman: "Āpār nām ki?", hint: "" },
      { en: "How much is this?", mr: "এটার দাম কত?", roman: "Ēṭār dām kôt?", hint: "" },
      { en: "Can I use your phone?", mr: "আমি কি আপনার ফোন ব্যবহার করতে পারি?", roman: "Āmi ki āpār phōn bôbohār kôrte pāri?", hint: "" },
      { en: "What did you do?", mr: "তুমি কী করলে?", roman: "Tumi ki korle?", hint: "" },
      { en: "When will you come?", mr: "তুমি কখন আসবে?", roman: "Tumi kôkhon āshbe?", hint: "" },
      { en: "The keys are in the bag", mr: "চাবিগুলো ব্যাগে আছে", roman: "Chābigulō bẽgē āchhe", hint: "" },
      { en: "The dog is under the table", mr: "কুকুরটা টেবিলের নিচে", roman: "Kukurṭā ṭēbilēr nīche", hint: "" },
      { en: "She spoke about the plan", mr: "সে পরিকল্পনা নিয়ে বলল", roman: "Sē pôrikolponā niyē bôllō", hint: "" },
      { en: "I will have food sent", mr: "আমি খাবার পাঠাব", roman: "Āmi khābār pāṭhābō", hint: "" },
      { en: "I was reading (ongoing past)", mr: "আমি পড়ছিলাম", roman: "Āmi pōṛchilām", hint: "" },
      { en: "I don't want to go", mr: "আমি যেতে চাই না", roman: "Āmi jēte chāi nā", hint: "" },
      { en: "He is going to read the report.", mr: "তেখেত প্ৰতিবেদন পঢ়িবলৈ যায়।", roman: "Tekhet prôtibedôn pôrhibôlôi jaẏ.", hint: "" },
      { en: "We are going to meet near the river bridge.", mr: "আমি নদীৰ দলঙৰ কাষতে দেখা কৰিবলৈ যাম।", roman: "Ami nodir dôlôngôr kaxhôte dekha koribôlôi jam.", hint: "" },
      { en: "She is going to sleep early tonight.", mr: "আজি ৰাতি তাই পোহৰেই সোৱাবলৈ যায়।", roman: "Aji rati tai pohorei xuabôlôi jaẏ.", hint: "" },
      { en: "She used to sing in the college choir.", mr: "তাই মহাবিদ্যালয়ৰ গায়ক দলত গাইছিল।", roman: "Tai môhavidyalôr gaẏôk dôlôt gaixil.", hint: "" },
      { en: "We used to play cricket in this open field.", mr: "আমি এই খোলা পথাৰত ক্ৰিকেট খেলিছিলোঁ।", roman: "Ami ei khula potharôt kriket khelexilũ.", hint: "" },
    ]
  },
  travel_1: {
    name: "Travel",
    color: "#38A169",
    icon: "🚌",
    phrases: [
      { en: "Can you help me?", mr: "আপনি কি আমাকে সাহায্য করতে পারবেন?", roman: "Āpni ki āmākē sāhājjo kôrte pārben?", hint: "" },
      { en: "Do you speak English?", mr: "আপনি কি ইংরেজি বলেন?", roman: "Āpni ki iṅrejī bôlen?", hint: "" },
      { en: "I haven't done anything wrong", mr: "আমি কিছু ভুল করিনি", roman: "Āmi kichhu bhul korini", hint: "" },
      { en: "What were you doing?", mr: "তুমি কী করছিলে?", roman: "Tumi ki korchhile?", hint: "" },
      { en: "Why are you late?", mr: "তুমি দেরি কেন?", roman: "Tumi dēri kēn?", hint: "" },
      { en: "She works at the office", mr: "সে অফিসে কাজ করে", roman: "Sē ôphisē kāj kore", hint: "" },
      { en: "I read a book (subject–object)", mr: "আমি বই পড়ি", roman: "Āmi bôi pōṛi", hint: "" },
      { en: "See you the day after tomorrow", mr: "পরশু দেখা হবে", roman: "Pôrôshu dēkhā hōbe", hint: "" },
      { en: "By then I will have finished", mr: "তখন আমি শেষ করে ফেলব", roman: "Tokhon āmi shēsh kōre phelbo", hint: "" },
      { en: "I will have been working", mr: "আমি কাজ করতে থাকব", roman: "Āmi kāj korte thākbo", hint: "" },
      { en: "He doesn't want to come", mr: "সে আসতে চায় না", roman: "Sē āste chāy nā", hint: "" },
      { en: "I am going to buy vegetables from the market.", mr: "মই বজাৰৰ পৰা পাচলি কিনিবলৈ যাওঁ।", roman: "Moi bajarôr pôra pasoli kinibôlôi jaũ.", hint: "" },
      { en: "I am going to Guwahati for two days.", mr: "মই দুদিনৰ বাবে গুৱাহাটীলৈ যাওঁ।", roman: "Moi dudinôr babe Guwahatiloi jaũ.", hint: "" },
      { en: "We are not going to wait if the bus is late.", mr: "বাছ দেৰি কৰিলে আমি অপেক্ষা নকৰিবলৈ যাওঁ।", roman: "Bax deri korile ami ôpekkha nôkoribôlôi jaũ.", hint: "" },
      { en: "They used to walk slowly along the embankment.", mr: "তেওঁলোকে পথাৰৰ দাঁতিত ধীৰে ধীৰে খোজ কঢ়িছিল।", roman: "Teoluke potharôr dãtit dhire dhire khôj koṛixil.", hint: "" },
      { en: "She used to teach village children after school.", mr: "বিদ্যালয়ৰ পিছত তাই গাঁৱৰ ল’ৰা-ছোৱালীক পঢ়াইছিল।", roman: "Bidyalôr pisôt tai gãwôr lora-xuwalik pôṛaixil.", hint: "" },
    ]
  },
  food_1: {
    name: "Food",
    color: "#DD6B20",
    icon: "🍛",
    phrases: [
      { en: "That is a good idea", mr: "সেটা ভালো ধারণা", roman: "Sēṭā bhālō dhārôṇā", hint: "" },
      { en: "Is there someone who speaks English?", mr: "কেউ কি ইংরেজি বলে?", roman: "Keu ki iṅrejī bōle?", hint: "" },
      { en: "I want to talk to a lawyer", mr: "আমি একজন আইনজীবীর সঙ্গে কথা বলতে চাই", roman: "Āmi ekjon āinjībīr songe kōthā bolte chāi", hint: "" },
      { en: "By then I will have gone", mr: "তখন আমি চলে যাব", roman: "Tokhon āmi chōlē jābo", hint: "" },
      { en: "Tomorrow I won't be free", mr: "কাল আমি ফাঁকা থাকব না", roman: "Kāl āmi phãkā thākbo nā", hint: "" },
      { en: "Wait in front of the gate", mr: "দরজার সামনে দাঁড়াও", roman: "Dôrjār sāmne dãṛāo", hint: "" },
      { en: "He gave me a pen (dative)", mr: "সে আমাকে কলম দিল", roman: "Sē āmākē kolom dil", hint: "" },
      { en: "What time is it?", mr: "কটা বাজে?", roman: "Koṭā bāje?", hint: "" },
      { en: "He has not come yet", mr: "সে এখনও আসেনি", roman: "Sē ēkhonō āsēni", hint: "" },
      { en: "By then she will have been teaching", mr: "তখন সে পড়াচ্ছিল", roman: "Tokhon sē pōṛāchchhil", hint: "" },
      { en: "I don't feel like it", mr: "আমার ইচ্ছে হচ্ছে না", roman: "Āmār icchē hochchhe nā", hint: "" },
      { en: "They are going to play football in the evening.", mr: "সন্ধিয়া তেওঁলোকে ফুটবল খেলিবলৈ যাব।", roman: "Xondhiya teoluke futbol khelibôlôi jab.", hint: "" },
      { en: "He is going to study harder this year.", mr: "এই বছৰ তেখেত অধিক পৰিশ্ৰমেৰে পঢ়িবলৈ যায়।", roman: "Ei bôsôr tekhet ôdhik porixrome pôrhibôlôi jaẏ.", hint: "" },
      { en: "When are you going to start your new course?", mr: "তোমাৰ নতুন পাঠ্যক্ৰম কেতিয়াৰ পৰা আৰম্ভ কৰিবলৈ যাবা?", roman: "Tomar nôtun patthôkrom ketiyar pôra arômbh koribôlôi jaba?", hint: "" },
      { en: "I used to eat breakfast before sunrise.", mr: "মই সূৰ্যোদয়ৰ আগতে নাস্তা খাইছিলোঁ।", roman: "Moi xûrjyôdôyôr agôte nastha khaixilũ.", hint: "" },
      { en: "I did not use to drink tea at night.", mr: "মই ৰাতি চাহ নিছিলোঁ।", roman: "Moi rati chah nixilũ.", hint: "" },
    ]
  },
  daily_1: {
    name: "Daily life",
    color: "#805AD5",
    icon: "🏠",
    phrases: [
      { en: "Do you speak Bengali?", mr: "আপনি কি বাংলা বলতে পারেন?", roman: "Āpni ki bāṅlā bolte pāren?", hint: "" },
      { en: "Where is the toilet?", mr: "টয়লেট কোথায়?", roman: "Ōyaleṭ kōthāy?", hint: "" },
      { en: "he / she (hon., present)", mr: "তিনি", roman: "Tini", hint: "" },
      { en: "in front of the school", mr: "স্কুলের সামনে", roman: "sḳulēr sāmne", hint: "" },
      { en: "The book is on the table", mr: "বইটা টেবিলের উপরে", roman: "Bôiṭā ṭēbilēr upore", hint: "" },
      { en: "The shop is across the road", mr: "দোকানটা রাস্তার ওপারে", roman: "Dokānṭā rāstār opārē", hint: "" },
      { en: "She wrote with a pen", mr: "সে কলম দিয়ে লিখল", roman: "Sē kolom diẏe likhlō", hint: "" },
      { en: "He had the letter written", mr: "সে চিঠি লিখিয়ে নিল", roman: "Sē chiṭhi likhiyē nil", hint: "" },
      { en: "By Monday I will have done it", mr: "সোমবারের মধ্যে আমি করে ফেলব", roman: "Sōmbārēr môdhye āmi kōre phelbo", hint: "" },
      { en: "I have been waiting long", mr: "আমি অনেকক্ষণ ধরে অপেক্ষা করছি", roman: "Āmi ônekkhôn dhôre ôpekhshā korchhi", hint: "" },
      { en: "I am going to eat now.", mr: "মই এতিয়া খাবলৈ যাওঁ।", roman: "Moi etiya khabôlôi jaũ.", hint: "" },
      { en: "Are you going to come to our house tomorrow?", mr: "তুমি কাইলৈ আমাৰ ঘৰলৈ আহিবলৈ যাবা নেকি?", roman: "Tumi kailoi amar ghorloi ahibôlôi jaba neki?", hint: "" },
      { en: "They are going to travel by night train.", mr: "তেওঁলোকে ৰাতিৰ ৰেলেৰে ভ্ৰমণ কৰিবলৈ যাব।", roman: "Teoluke ratir relere bhromôn koribôlôi jab.", hint: "" },
      { en: "I used to live in this neighbourhood.", mr: "মই এই মহলাত থাকিছিলোঁ।", roman: "Moi ei môholat thakixilũ.", hint: "" },
      { en: "You used to come home quite late from work.", mr: "তুমি কামৰ পৰা বহু দেৰিকৈ ঘৰলৈ আহিছিলা।", roman: "Tumi kamôr pôra bôhu derikoi ghorloi ahixa.", hint: "" },
      { en: "He used to visit us during festivals.", mr: "উৎসৱৰ সময়ত তেখেতে আমাক সাক্ষাৎ কৰিছিল।", roman: "Utsôbôr xomôyôt tekhete amak xakxat korixil.", hint: "" },
    ]
  },
  shopping_1: {
    name: "Shopping",
    color: "#D69E2E",
    icon: "🛒",
    phrases: [
      { en: "Speak to me in Bengali", mr: "আমার সঙ্গে বাংলায় কথা বলুন", roman: "Āmār songe bāṅlāy kōthā bôlun", hint: "" },
      { en: "I will stay one night", mr: "আমি এক রাত থাকব", roman: "Āmi ek rāt thākbo", hint: "" },
      { en: "What are you doing?", mr: "তুমি কী করছো?", roman: "Tumi ki korchho?", hint: "" },
      { en: "I will go to you", mr: "আমি তোমার কাছে যাব", roman: "Āmi tōmār kāchhe jābo", hint: "" },
      { en: "The cat is under the chair", mr: "বিড়ালটা চেয়ারের নিচে", roman: "Biṛālṭā cheẏārēr nīche", hint: "" },
      { en: "I live near the park", mr: "আমি পার্কের কাছে থাকি", roman: "Āmi pāṛkēr kāchhe thāki", hint: "" },
      { en: "He sits on the chair", mr: "সে চেয়ারে বসে", roman: "Sē cheẏāre bôse", hint: "" },
      { en: "I will get it printed", mr: "আমি ছাপিয়ে নেব", roman: "Āmi chāpiyē nebo", hint: "" },
      { en: "They have sold the house", mr: "তারা বাড়ি বেচেছে", roman: "Tārā bāṛi bēchēchhe", hint: "" },
      { en: "They had been living there", mr: "তারা সেখানে থাকত", roman: "Tārā shēkhāne thāktō", hint: "" },
      { en: "She is going to sing at the function.", mr: "তাই অনুষ্ঠানত গাবলৈ যায়।", roman: "Tai anusthanôt gabôlôi jaẏ.", hint: "" },
      { en: "I am going to call you after the meeting.", mr: "মিটিঙৰ পিছত মই তোমাক ফোন কৰিবলৈ যাওঁ।", roman: "Miṭiṅôr pisôt moi tumak phôn koribôlôi jaũ.", hint: "" },
      { en: "I am going to rest because I feel tired.", mr: "মই ক্লান্ত অনুভৱ কৰোঁ, গতিকে বিশ্ৰাম ল’বলৈ যাওঁ।", roman: "Moi klantô ônubhôb korũ, gotike bixram lôbôlôi jaũ.", hint: "" },
      { en: "He used to read the newspaper every morning.", mr: "তেখেতে প্ৰতিদিনে ৰাতিপুৱা বাতৰিকাকত পঢ়িছিল।", roman: "Tekhete prôtidine ratipuwa batôrikakôt pôrixil.", hint: "" },
      { en: "It used to rain heavily in June here.", mr: "ইয়াত জুন মাহত বৰষুণ বেছি হৈছিল।", roman: "Iyat Jun mahôt boroxun beshi hoixil.", hint: "" },
      { en: "They used to live on the other bank of the river.", mr: "তেওঁলোকে নদীৰ সিপাৰে থাকিছিল।", roman: "Teoluke nodir xipare thakixil.", hint: "" },
    ]
  },
  emergency_1: {
    name: "Emergency",
    color: "#E53E3E",
    icon: "🚨",
    phrases: [
      { en: "How do you say ... in Bengali?", mr: "... বাংলায় কী বলে?", roman: "... bāṅlāy ki bōle?", hint: "" },
      { en: "What time is breakfast?", mr: "নাস্তা কখন?", roman: "Nāstā kôkhon?", hint: "" },
      { en: "When did you go?", mr: "তুমি কখন গেলি?", roman: "Tumi kôkhon gēli?", hint: "" },
      { en: "Where do you live?", mr: "তুমি কোথায় থাকো?", roman: "Tumi kōthāy thākō?", hint: "" },
      { en: "We met at the station", mr: "আমরা স্টেশনে দেখা করলাম", roman: "Āmrā sṭēshone dēkhā korlām", hint: "" },
      { en: "The lamp is on the roof", mr: "ল্যাম্পটা ছাদের উপরে", roman: "Lyāmṭā chādēr upore", hint: "" },
      { en: "I bought from the market", mr: "আমি বাজার থেকে কিনলাম", roman: "Āmi bājār theke kinlām", hint: "" },
      { en: "He opened the door for me", mr: "সে আমার জন্য দরজা খুলল", roman: "Sē āmār jônyo dôrjā khullō", hint: "" },
      { en: "It will have been done", mr: "সেটা হয়ে যাবে", roman: "Sēṭā hōye jābe", hint: "" },
      { en: "The show had been running", mr: "শো চলছিল", roman: "Ō cholchhil", hint: "" },
      { en: "We are going to leave after tea.", mr: "আমি চাহ খোৱাৰ পিছত ওলাই যাম।", roman: "Ami chah khuwar pisôt olai jam.", hint: "" },
      { en: "Mother is going to cook fish for lunch.", mr: "মাকে দুপৰীয়া মাছ ৰান্ধিবলৈ যায়।", roman: "Make duporiya mas randhibôlôi jaẏ.", hint: "" },
      { en: "We are going to help clean the community hall.", mr: "আমি সমাজৰ কাৰ্যালয় পৰিষ্কাৰ কৰাত সহায় কৰিবলৈ যাম।", roman: "Ami xomajôr karyaloy poriskar korat xohaẏ koribôlôi jam.", hint: "" },
      { en: "We used to meet every Sunday at the park.", mr: "আমি প্ৰতি একেৰাহী উদ্যানত দেখা কৰিছিলোঁ।", roman: "Ami prôtiekerahi udyônôt dekha korixilũ.", hint: "" },
      { en: "Father used to work in the tea garden.", mr: "দেউতাই চাহ বাগিচাত কাম কৰিছিল।", roman: "Deutai chah bagixat kam korixil.", hint: "" },
      { en: "I used to wake up before five o'clock.", mr: "মই পাঁচটাৰ আগতে উঠিছিলোঁ।", roman: "Moi pãsôtar agôte uṭhixilũ.", hint: "" },
    ]
  },
};

const ASSAMESE_DICTIONARY = {
  basics_1: {
    name: "Basic words",
    words: [
      { en: "name", mr: "নাম", roman: "nām" },
      { en: "house", mr: "বাড়ি", roman: "bāṛi" },
      { en: "tea", mr: "চা", roman: "chā" },
      { en: "yes", mr: "হ্যাঁ", roman: "hyẫ" },
      { en: "Hello (formal)", mr: "নমস্কার", roman: "Nômôskār" },
      { en: "Please", mr: "দয়া করে", roman: "Dôya kōre" },
      { en: "Good night", mr: "শুভ রাত্রি", roman: "Shubh rātri" },
      { en: "This is my book", mr: "এটা আমার বই", roman: "Ēṭā āmār bôi" },
      { en: "He was brave", mr: "সে সাহসী ছিল", roman: "Sē sāhsī chhil" },
      { en: "Well done", mr: "খুব ভালো হয়েছে", roman: "Khub bhālō hōyēchhe" },
      { en: "I'm hungry", mr: "আমার খিদে পেয়েছে", roman: "Āmār khidē pēyēchhe" },
      { en: "Get well soon", mr: "আশা করি তাড়াতাড়ি সুস্থ হবেন", roman: "Āshā kori ṭāṛāṭāṛi sustho hōben" },
      { en: "See you", mr: "আবার দেখা হবে", roman: "Ābār dēkhā hōbe" },
      { en: "Please say that again", mr: "আবার বলবেন?", roman: "Ābār bôlben?" },
      { en: "Sorry", mr: "দুঃখিত", roman: "Duhkhito" },
      { en: "Look out!", mr: "সাবধান!", roman: "Sābdhān!" },
    ]
  },
  family_1: {
    name: "Family",
    words: [
      { en: "water", mr: "জল", roman: "jôl" },
      { en: "good", mr: "ভালো", roman: "bhālō" },
      { en: "one", mr: "এক", roman: "ek" },
      { en: "no", mr: "না", roman: "nā" },
      { en: "How are you?", mr: "আপনি কেমন আছেন?", roman: "Āpni kēmon āchen?" },
      { en: "I love you", mr: "আমি তোমাকে ভালোবাসি", roman: "Āmi tōmākē bhālōbāsi" },
      { en: "Help!", mr: "সাহায্য করুন!", roman: "Sāhājjo kôrun!" },
      { en: "This is my friend", mr: "এই আমার বন্ধু", roman: "Ei āmār bondhu" },
      { en: "I'm so happy", mr: "আমি খুব খুশি", roman: "Āmi khub khushi" },
      { en: "Come in", mr: "ভিতরে আসুন", roman: "Bhitōre āsun" },
      { en: "Take care", mr: "যত্ন নিন", roman: "Jôtno nin" },
      { en: "No worries", mr: "চিন্তা নেই", roman: "Chinta nēi" },
      { en: "I'm sorry", mr: "আমি দুঃখিত", roman: "Āmi duhkhito" },
      { en: "Please write it down", mr: "এটা লিখে দিন", roman: "Ēṭā likhe din" },
      { en: "You're welcome", mr: "স্বাগতম", roman: "Swāgotom" },
      { en: "Good evening", mr: "শুভ সন্ধ্যা", roman: "Shubh sondhyā" },
    ]
  },
  verbs_1: {
    name: "Common verbs",
    words: [
      { en: "rice", mr: "ভাত", roman: "bhāt" },
      { en: "today", mr: "আজ", roman: "āj" },
      { en: "two", mr: "দুই", roman: "dui" },
      { en: "Welcome", mr: "স্বাগতম", roman: "Swāgotom" },
      { en: "I am fine", mr: "আমি ভালো আছি", roman: "Āmi bhālō āchi" },
      { en: "Goodbye", mr: "বিদায়", roman: "Bidāy" },
      { en: "I am a student", mr: "আমি ছাত্র", roman: "Āmi chātrô" },
      { en: "We are happy", mr: "আমরা খুশি", roman: "Āmrā khushi" },
      { en: "Good idea", mr: "ভালো ধারণা", roman: "Bhālō dhārôṇā" },
      { en: "Please come in", mr: "দয়া করে ভিতরে আসুন", roman: "Dôya kōre bhitōre āsun" },
      { en: "I miss you", mr: "আমি তোমাকে মিস করি", roman: "Āmi tōmākē mis kori" },
      { en: "Congratulations", mr: "অভিনন্দন", roman: "Ôbhinondon" },
      { en: "I don't understand", mr: "আমি বুঝতে পারছি না", roman: "Āmi bujhte pārchhi nā" },
      { en: "Yes, a little", mr: "হ্যাঁ, একটু", roman: "Hyẫ, ekṭu" },
      { en: "I'm so sorry", mr: "আমি খুব দুঃখিত", roman: "Āmi khub duhkhito" },
      { en: "I'm lost", mr: "আমি পথ হারিয়েছি", roman: "Āmi poth hāriēchhi" },
    ]
  },
  nature_1: {
    name: "Nature",
    words: [
      { en: "day", mr: "দিন", roman: "din" },
      { en: "come", mr: "আসা", roman: "āsā" },
      { en: "body", mr: "শরীর", roman: "shorīr" },
      { en: "Thank you", mr: "ধন্যবাদ", roman: "Dhonyobād" },
      { en: "My name is...", mr: "আমার নাম...", roman: "Āmār nām..." },
      { en: "Good morning", mr: "সুপ্রভাত", roman: "Suprobhāt" },
      { en: "You are a teacher", mr: "তুমি শিক্ষক", roman: "Tumi shikkhôk" },
      { en: "She is beautiful", mr: "সে সুন্দর", roman: "Sē sundor" },
      { en: "Very good", mr: "খুব ভালো", roman: "Khub bhālō" },
      { en: "Have you eaten?", mr: "খেয়েছেন?", roman: "Khēyēchen?" },
      { en: "No problem", mr: "কোনো সমস্যা নেই", roman: "Kōnō shomosshā nēi" },
      { en: "Good luck", mr: "শুভকামনা", roman: "Shubhokāmnā" },
      { en: "Please speak slowly", mr: "আস্তে আস্তে বলুন", roman: "Āste āste bôlun" },
      { en: "Excuse me", mr: "মাফ করবেন", roman: "Māph kôrben" },
      { en: "Please speak more slowly", mr: "আরও আস্তে বলুন", roman: "Ārō āste bôlun" },
      { en: "Leave me alone", mr: "আমাকে একা থাকতে দিন", roman: "Āmākē ekā thākte din" },
    ]
  },
};
