// Auto-generated from lesson JSON — Phrases & Words tabs
const BENGALI_PHRASES = {
  greetings_1: {
    name: "Greetings",
    color: "#2B6CB0",
    icon: "👋",
    phrases: [
      { en: "What is your name?", mr: "আপনার নাম কী?", roman: "Āpār nām ki?", hint: "" },
      { en: "How much is this?", mr: "এটার দাম কত?", roman: "Ēṭār dām kôt?", hint: "" },
      { en: "Can I use your phone?", mr: "আমি কি আপনার ফোন ব্যবহার করতে পারি?", roman: "Āmi ki āpār phōn bôbohār kôrte pāri?", hint: "" },
      { en: "What did you do?", mr: "তুমি কী করলে?", roman: "Tumi ki korle?", hint: "" },
      { en: "When will you come?", mr: "তুমি কখন আসবে?", roman: "Tumi kôkhon āshbe?", hint: "" },
      { en: "The keys are in the bag", mr: "চাবিগুলো ব্যাগে আছে", roman: "Chābigulō bẽgē āchhe", hint: "" },
      { en: "The dog is under the table", mr: "কুকুরটা টেবিলের নিচে", roman: "Kukurṭā ṭēbilēr nīche", hint: "" },
      { en: "She spoke about the plan", mr: "সে পরিকল্পনা নিয়ে বলল", roman: "Sē pôrikolponā niyē bôllō", hint: "" },
      { en: "I will have food sent", mr: "আমি খাবার পাঠাব", roman: "Āmi khābār pāṭhābō", hint: "" },
      { en: "I was reading (ongoing past)", mr: "আমি পড়ছিলাম", roman: "Āmi pōṛchilām", hint: "" },
      { en: "I don't want to go", mr: "আমি যেতে চাই না", roman: "Āmi jēte chāi nā", hint: "" },
      { en: "He is going to read.", mr: "সে পড়তে যাচ্ছে।", roman: "Sē pōṛte jāchchhe.", hint: "" },
      { en: "We are going to meet.", mr: "আমরা দেখা করতে যাচ্ছি।", roman: "Āmrā dēkhā korte jāchchhi.", hint: "" },
      { en: "She is going to sleep.", mr: "সে ঘুমাতে যাচ্ছে।", roman: "Sē ghumāte jāchchhe.", hint: "" },
      { en: "She used to sing well.", mr: "সে ভালো গাইত।", roman: "Sē bhālō gāitō.", hint: "" },
      { en: "We used to play in this field.", mr: "আমরা এই মাঠে খেলতাম।", roman: "Āmrā ei māṭhe kheltām.", hint: "" },
    ]
  },
  travel_1: {
    name: "Travel",
    color: "#38A169",
    icon: "🚌",
    phrases: [
      { en: "Can you help me?", mr: "আপনি কি আমাকে সাহায্য করতে পারবেন?", roman: "Āpni ki āmākē sāhājjo kôrte pārben?", hint: "" },
      { en: "Do you speak English?", mr: "আপনি কি ইংরেজি বলেন?", roman: "Āpni ki iṅrejī bôlen?", hint: "" },
      { en: "I haven't done anything wrong", mr: "আমি কিছু ভুল করিনি", roman: "Āmi kichhu bhul korini", hint: "" },
      { en: "What were you doing?", mr: "তুমি কী করছিলে?", roman: "Tumi ki korchhile?", hint: "" },
      { en: "Why are you late?", mr: "তুমি দেরি কেন?", roman: "Tumi dēri kēn?", hint: "" },
      { en: "She works at the office", mr: "সে অফিসে কাজ করে", roman: "Sē ôphisē kāj kore", hint: "" },
      { en: "I read a book (subject–object)", mr: "আমি বই পড়ি", roman: "Āmi bôi pōṛi", hint: "" },
      { en: "See you the day after tomorrow", mr: "পরশু দেখা হবে", roman: "Pôrôshu dēkhā hōbe", hint: "" },
      { en: "By then I will have finished", mr: "তখন আমি শেষ করে ফেলব", roman: "Tokhon āmi shēsh kōre phelbo", hint: "" },
      { en: "I will have been working", mr: "আমি কাজ করতে থাকব", roman: "Āmi kāj korte thākbo", hint: "" },
      { en: "He doesn't want to come", mr: "সে আসতে চায় না", roman: "Sē āste chāy nā", hint: "" },
      { en: "I am going to buy a book.", mr: "আমি বই কিনতে যাচ্ছি।", roman: "Āmi bôi kinte jāchchhi.", hint: "" },
      { en: "I am going to Kolkata.", mr: "আমি কলকাতা যাচ্ছি।", roman: "Āmi Kolkātā jāchchhi.", hint: "" },
      { en: "We are not going to wait.", mr: "আমরা অপেক্ষা করতে যাচ্ছি না।", roman: "Āmrā ôpekhshā korte jāchchhi nā.", hint: "" },
      { en: "They used to walk slowly.", mr: "তারা ধীরে ধীরে হাঁটত।", roman: "Tārā dhīre dhīre hãṭtō.", hint: "" },
      { en: "She used to teach children.", mr: "সে বাচ্চাদের পড়াত।", roman: "Sē bāchchādēr pōṛātō.", hint: "" },
    ]
  },
  food_1: {
    name: "Food",
    color: "#DD6B20",
    icon: "🍛",
    phrases: [
      { en: "That is a good idea", mr: "সেটা ভালো ধারণা", roman: "Sēṭā bhālō dhārôṇā", hint: "" },
      { en: "Is there someone who speaks English?", mr: "কেউ কি ইংরেজি বলে?", roman: "Keu ki iṅrejī bōle?", hint: "" },
      { en: "I want to talk to a lawyer", mr: "আমি একজন আইনজীবীর সঙ্গে কথা বলতে চাই", roman: "Āmi ekjon āinjībīr songe kōthā bolte chāi", hint: "" },
      { en: "By then I will have gone", mr: "তখন আমি চলে যাব", roman: "Tokhon āmi chōlē jābo", hint: "" },
      { en: "Tomorrow I won't be free", mr: "কাল আমি ফাঁকা থাকব না", roman: "Kāl āmi phãkā thākbo nā", hint: "" },
      { en: "Wait in front of the gate", mr: "দরজার সামনে দাঁড়াও", roman: "Dôrjār sāmne dãṛāo", hint: "" },
      { en: "He gave me a pen (dative)", mr: "সে আমাকে কলম দিল", roman: "Sē āmākē kolom dil", hint: "" },
      { en: "What time is it?", mr: "কটা বাজে?", roman: "Koṭā bāje?", hint: "" },
      { en: "He has not come yet", mr: "সে এখনও আসেনি", roman: "Sē ēkhonō āsēni", hint: "" },
      { en: "By then she will have been teaching", mr: "তখন সে পড়াচ্ছিল", roman: "Tokhon sē pōṛāchchhil", hint: "" },
      { en: "I don't feel like it", mr: "আমার ইচ্ছে হচ্ছে না", roman: "Āmār icchē hochchhe nā", hint: "" },
      { en: "They are going to play.", mr: "তারা খেলতে যাচ্ছে।", roman: "Tārā khelte jāchchhe.", hint: "" },
      { en: "He is going to study.", mr: "সে পড়াশোনা করতে যাচ্ছে।", roman: "Sē pōṛāshonā korte jāchchhe.", hint: "" },
      { en: "When are you going to start?", mr: "তুমি কখন শুরু করতে যাচ্ছ?", roman: "Tumi kôkhon shuru korte jāchchho?", hint: "" },
      { en: "I used to eat early.", mr: "আমি তাড়াতাড়ি খেতাম।", roman: "Āmi ṭāṛāṭāṛi khētām.", hint: "" },
      { en: "I did not use to smoke.", mr: "আমি ধূমপান করতাম না।", roman: "Āmi dhūmpān kortām nā.", hint: "" },
    ]
  },
  daily_1: {
    name: "Daily life",
    color: "#805AD5",
    icon: "🏠",
    phrases: [
      { en: "Do you speak Bengali?", mr: "আপনি কি বাংলা বলতে পারেন?", roman: "Āpni ki bāṅlā bolte pāren?", hint: "" },
      { en: "Where is the toilet?", mr: "টয়লেট কোথায়?", roman: "Ōyaleṭ kōthāy?", hint: "" },
      { en: "he / she (hon., present)", mr: "তিনি", roman: "Tini", hint: "" },
      { en: "in front of the school", mr: "স্কুলের সামনে", roman: "sḳulēr sāmne", hint: "" },
      { en: "The book is on the table", mr: "বইটা টেবিলের উপরে", roman: "Bôiṭā ṭēbilēr upore", hint: "" },
      { en: "The shop is across the road", mr: "দোকানটা রাস্তার ওপারে", roman: "Dokānṭā rāstār opārē", hint: "" },
      { en: "She wrote with a pen", mr: "সে কলম দিয়ে লিখল", roman: "Sē kolom diẏe likhlō", hint: "" },
      { en: "He had the letter written", mr: "সে চিঠি লিখিয়ে নিল", roman: "Sē chiṭhi likhiyē nil", hint: "" },
      { en: "By Monday I will have done it", mr: "সোমবারের মধ্যে আমি করে ফেলব", roman: "Sōmbārēr môdhye āmi kōre phelbo", hint: "" },
      { en: "I have been waiting long", mr: "আমি অনেকক্ষণ ধরে অপেক্ষা করছি", roman: "Āmi ônekkhôn dhôre ôpekhshā korchhi", hint: "" },
      { en: "I am going to eat.", mr: "আমি খেতে যাচ্ছি।", roman: "Āmi khete jāchchhi.", hint: "" },
      { en: "Are you going to come?", mr: "তুমি আসতে যাচ্ছ?", roman: "Tumi āste jāchchho?", hint: "" },
      { en: "They are going to travel.", mr: "তারা ভ্রমণ করতে যাচ্ছে।", roman: "Tārā bhromaṇ korte jāchchhe.", hint: "" },
      { en: "I used to live here.", mr: "আমি এখানে থাকতাম।", roman: "Āmi ēkhāne thāktām.", hint: "" },
      { en: "You used to come late.", mr: "তুমি দেরি করে আসতে।", roman: "Tumi dēri kōre āstē.", hint: "" },
      { en: "He used to visit us.", mr: "সে আমাদের দেখতে আসত।", roman: "Sē āmādēr dekhte āstō.", hint: "" },
    ]
  },
  shopping_1: {
    name: "Shopping",
    color: "#D69E2E",
    icon: "🛒",
    phrases: [
      { en: "Speak to me in Bengali", mr: "আমার সঙ্গে বাংলায় কথা বলুন", roman: "Āmār songe bāṅlāy kōthā bôlun", hint: "" },
      { en: "I will stay one night", mr: "আমি এক রাত থাকব", roman: "Āmi ek rāt thākbo", hint: "" },
      { en: "What are you doing?", mr: "তুমি কী করছো?", roman: "Tumi ki korchho?", hint: "" },
      { en: "I will go to you", mr: "আমি তোমার কাছে যাব", roman: "Āmi tōmār kāchhe jābo", hint: "" },
      { en: "The cat is under the chair", mr: "বিড়ালটা চেয়ারের নিচে", roman: "Biṛālṭā cheẏārēr nīche", hint: "" },
      { en: "I live near the park", mr: "আমি পার্কের কাছে থাকি", roman: "Āmi pāṛkēr kāchhe thāki", hint: "" },
      { en: "He sits on the chair", mr: "সে চেয়ারে বসে", roman: "Sē cheẏāre bôse", hint: "" },
      { en: "I will get it printed", mr: "আমি ছাপিয়ে নেব", roman: "Āmi chāpiyē nebo", hint: "" },
      { en: "They have sold the house", mr: "তারা বাড়ি বেচেছে", roman: "Tārā bāṛi bēchēchhe", hint: "" },
      { en: "They had been living there", mr: "তারা সেখানে থাকত", roman: "Tārā shēkhāne thāktō", hint: "" },
      { en: "She is going to sing.", mr: "সে গাইতে যাচ্ছে।", roman: "Sē gāite jāchchhe.", hint: "" },
      { en: "I am going to call you.", mr: "আমি তোমাকে ফোন করতে যাচ্ছি।", roman: "Āmi tōmākē phōn korte jāchchhi.", hint: "" },
      { en: "I am going to rest.", mr: "আমি বিশ্রাম নিতে যাচ্ছি।", roman: "Āmi bishrām nite jāchchhi.", hint: "" },
      { en: "He used to read a lot.", mr: "সে অনেক পড়ত।", roman: "Sē ônek pōṛtō.", hint: "" },
      { en: "It used to rain often.", mr: "প্রায় বৃষ্টি হত।", roman: "Prāẏ briṣṭi hotō.", hint: "" },
      { en: "They used to live in Dhaka.", mr: "তারা ঢাকায় থাকত।", roman: "Tārā Ḍhākāy thāktō.", hint: "" },
    ]
  },
  emergency_1: {
    name: "Emergency",
    color: "#E53E3E",
    icon: "🚨",
    phrases: [
      { en: "How do you say ... in Bengali?", mr: "... বাংলায় কী বলে?", roman: "... bāṅlāy ki bōle?", hint: "" },
      { en: "What time is breakfast?", mr: "নাস্তা কখন?", roman: "Nāstā kôkhon?", hint: "" },
      { en: "When did you go?", mr: "তুমি কখন গেলি?", roman: "Tumi kôkhon gēli?", hint: "" },
      { en: "Where do you live?", mr: "তুমি কোথায় থাকো?", roman: "Tumi kōthāy thākō?", hint: "" },
      { en: "We met at the station", mr: "আমরা স্টেশনে দেখা করলাম", roman: "Āmrā sṭēshone dēkhā korlām", hint: "" },
      { en: "The lamp is on the roof", mr: "ল্যাম্পটা ছাদের উপরে", roman: "Lyāmṭā chādēr upore", hint: "" },
      { en: "I bought from the market", mr: "আমি বাজার থেকে কিনলাম", roman: "Āmi bājār theke kinlām", hint: "" },
      { en: "He opened the door for me", mr: "সে আমার জন্য দরজা খুলল", roman: "Sē āmār jônyo dôrjā khullō", hint: "" },
      { en: "It will have been done", mr: "সেটা হয়ে যাবে", roman: "Sēṭā hōye jābe", hint: "" },
      { en: "The show had been running", mr: "শো চলছিল", roman: "Ō cholchhil", hint: "" },
      { en: "We are going to leave.", mr: "আমরা চলে যাচ্ছি।", roman: "Āmrā chōlē jāchchhi.", hint: "" },
      { en: "She is going to cook.", mr: "সে রান্না করতে যাচ্ছে।", roman: "Sē rānnā korte jāchchhe.", hint: "" },
      { en: "I am going to help.", mr: "আমি সাহায্য করতে যাচ্ছি।", roman: "Āmi sāhājjo korte jāchchhi.", hint: "" },
      { en: "We used to meet every week.", mr: "আমরা প্রতি সপ্তাহে দেখা করতাম।", roman: "Āmrā prôti soptāhē dēkhā kortām.", hint: "" },
      { en: "Father used to work there.", mr: "বাবা সেখানে কাজ করতেন।", roman: "Bābā shēkhāne kāj kortēn.", hint: "" },
      { en: "I used to wake up early.", mr: "আমি ভোরে উঠতাম।", roman: "Āmi bhōre uṭhtām.", hint: "" },
    ]
  },
};

const BENGALI_DICTIONARY = {
  basics_1: {
    name: "Basic words",
    words: [
      { en: "name", mr: "নাম", roman: "nām" },
      { en: "house", mr: "বাড়ি", roman: "bāṛi" },
      { en: "tea", mr: "চা", roman: "chā" },
      { en: "yes", mr: "হ্যাঁ", roman: "hyẫ" },
      { en: "Hello (formal)", mr: "নমস্কার", roman: "Nômôskār" },
      { en: "Please", mr: "দয়া করে", roman: "Dôya kōre" },
      { en: "Good night", mr: "শুভ রাত্রি", roman: "Shubh rātri" },
      { en: "This is my book", mr: "এটা আমার বই", roman: "Ēṭā āmār bôi" },
      { en: "He was brave", mr: "সে সাহসী ছিল", roman: "Sē sāhsī chhil" },
      { en: "Well done", mr: "খুব ভালো হয়েছে", roman: "Khub bhālō hōyēchhe" },
      { en: "I'm hungry", mr: "আমার খিদে পেয়েছে", roman: "Āmār khidē pēyēchhe" },
      { en: "Get well soon", mr: "আশা করি তাড়াতাড়ি সুস্থ হবেন", roman: "Āshā kori ṭāṛāṭāṛi sustho hōben" },
      { en: "See you", mr: "আবার দেখা হবে", roman: "Ābār dēkhā hōbe" },
      { en: "Please say that again", mr: "আবার বলবেন?", roman: "Ābār bôlben?" },
      { en: "Sorry", mr: "দুঃখিত", roman: "Duhkhito" },
      { en: "Look out!", mr: "সাবধান!", roman: "Sābdhān!" },
    ]
  },
  family_1: {
    name: "Family",
    words: [
      { en: "water", mr: "জল", roman: "jôl" },
      { en: "good", mr: "ভালো", roman: "bhālō" },
      { en: "one", mr: "এক", roman: "ek" },
      { en: "no", mr: "না", roman: "nā" },
      { en: "How are you?", mr: "আপনি কেমন আছেন?", roman: "Āpni kēmon āchen?" },
      { en: "I love you", mr: "আমি তোমাকে ভালোবাসি", roman: "Āmi tōmākē bhālōbāsi" },
      { en: "Help!", mr: "সাহায্য করুন!", roman: "Sāhājjo kôrun!" },
      { en: "This is my friend", mr: "এই আমার বন্ধু", roman: "Ei āmār bondhu" },
      { en: "I'm so happy", mr: "আমি খুব খুশি", roman: "Āmi khub khushi" },
      { en: "Come in", mr: "ভিতরে আসুন", roman: "Bhitōre āsun" },
      { en: "Take care", mr: "যত্ন নিন", roman: "Jôtno nin" },
      { en: "No worries", mr: "চিন্তা নেই", roman: "Chinta nēi" },
      { en: "I'm sorry", mr: "আমি দুঃখিত", roman: "Āmi duhkhito" },
      { en: "Please write it down", mr: "এটা লিখে দিন", roman: "Ēṭā likhe din" },
      { en: "You're welcome", mr: "স্বাগতম", roman: "Swāgotom" },
      { en: "Good evening", mr: "শুভ সন্ধ্যা", roman: "Shubh sondhyā" },
    ]
  },
  verbs_1: {
    name: "Common verbs",
    words: [
      { en: "rice", mr: "ভাত", roman: "bhāt" },
      { en: "today", mr: "আজ", roman: "āj" },
      { en: "two", mr: "দুই", roman: "dui" },
      { en: "Welcome", mr: "স্বাগতম", roman: "Swāgotom" },
      { en: "I am fine", mr: "আমি ভালো আছি", roman: "Āmi bhālō āchi" },
      { en: "Goodbye", mr: "বিদায়", roman: "Bidāy" },
      { en: "I am a student", mr: "আমি ছাত্র", roman: "Āmi chātrô" },
      { en: "We are happy", mr: "আমরা খুশি", roman: "Āmrā khushi" },
      { en: "Good idea", mr: "ভালো ধারণা", roman: "Bhālō dhārôṇā" },
      { en: "Please come in", mr: "দয়া করে ভিতরে আসুন", roman: "Dôya kōre bhitōre āsun" },
      { en: "I miss you", mr: "আমি তোমাকে মিস করি", roman: "Āmi tōmākē mis kori" },
      { en: "Congratulations", mr: "অভিনন্দন", roman: "Ôbhinondon" },
      { en: "I don't understand", mr: "আমি বুঝতে পারছি না", roman: "Āmi bujhte pārchhi nā" },
      { en: "Yes, a little", mr: "হ্যাঁ, একটু", roman: "Hyẫ, ekṭu" },
      { en: "I'm so sorry", mr: "আমি খুব দুঃখিত", roman: "Āmi khub duhkhito" },
      { en: "I'm lost", mr: "আমি পথ হারিয়েছি", roman: "Āmi poth hāriēchhi" },
    ]
  },
  nature_1: {
    name: "Nature",
    words: [
      { en: "day", mr: "দিন", roman: "din" },
      { en: "come", mr: "আসা", roman: "āsā" },
      { en: "body", mr: "শরীর", roman: "shorīr" },
      { en: "Thank you", mr: "ধন্যবাদ", roman: "Dhonyobād" },
      { en: "My name is...", mr: "আমার নাম...", roman: "Āmār nām..." },
      { en: "Good morning", mr: "সুপ্রভাত", roman: "Suprobhāt" },
      { en: "You are a teacher", mr: "তুমি শিক্ষক", roman: "Tumi shikkhôk" },
      { en: "She is beautiful", mr: "সে সুন্দর", roman: "Sē sundor" },
      { en: "Very good", mr: "খুব ভালো", roman: "Khub bhālō" },
      { en: "Have you eaten?", mr: "খেয়েছেন?", roman: "Khēyēchen?" },
      { en: "No problem", mr: "কোনো সমস্যা নেই", roman: "Kōnō shomosshā nēi" },
      { en: "Good luck", mr: "শুভকামনা", roman: "Shubhokāmnā" },
      { en: "Please speak slowly", mr: "আস্তে আস্তে বলুন", roman: "Āste āste bôlun" },
      { en: "Excuse me", mr: "মাফ করবেন", roman: "Māph kôrben" },
      { en: "Please speak more slowly", mr: "আরও আস্তে বলুন", roman: "Ārō āste bôlun" },
      { en: "Leave me alone", mr: "আমাকে একা থাকতে দিন", roman: "Āmākē ekā thākte din" },
    ]
  },
};
