# Bodo Lesson 2 — chunk A (chapter IDs 510–526).
# Columns: English, Bodo (Devanagari), Transliteration.

LESSONS_S2A = {
    510: [
        ["I", "आँ", "āṅ"],
        ["You (informal)", "नों", "noṅ"],
        ["You (respectful)", "नेंथां", "nenthāṅ"],
        ["He / she / that one", "बो / बि", "bo / bi"],
        ["We", "जिंग", "jiṅ"],
        ["You (plural / polite)", "नेंफां", "nenphāṅ"],
        ["They", "बिफां", "biphāṅ"],
        ["This", "निं", "nin"],
        ["That", "उं", "uṅ"],
        ["One boy", "गोथो मुसा", "gotho musā"],
        ["One girl", "गोथो मुसु", "gotho musu"],
        ["The boy (this one)", "निं मुसा", "nin musā"],
        ["My book", "आँनि पुस्तक", "āṅni pustak"],
        ["Your book (informal)", "नोंनि पुस्तक", "noṅni pustak"],
        ["His / her house", "बिनि गोर / बोनि गोर", "bini gor / boni gor"],
        ["Our school", "जिंनि इस्कुल", "jiṅni iskul"],
        ["These children", "निं सोरफोर", "nin sorphor"],
        ["Those men", "उं मानसिफोर", "uṅ mānasi-phor"],
        ["Who is he?", "बो माव्नो?", "bo māwno?"],
        ["What is this?", "निं मा?", "nin mā?"],
    ],
    511: [
        ["How are you? (respectful)", "नेंथां गोरै दं?", "nenthāṅ gorai dong?"],
        ["Please sit (formal)", "बैठ खालाम", "baiṭh khālam"],
        ["Father is reading (honorific)", "बाफा पुस्तक फर फिदिं", "bāphā pustak pha phidiṅ"],
        ["Mother is cooking (honorific)", "आमा खाम फोथो दिं", "āmā khām photho diṅ"],
        ["Grandfather spoke (respect)", "आगो बोलाय दं", "āgo bolāy dong"],
        ["The teacher has come", "मास्तार आय दं", "māstār āy dong"],
        ["Uncle went (respect past)", "काका जाय दं", "kākā jāy dong"],
        ["The doctor is at home", "डाक्टर गोराव दं", "ḍāktār gorāw dong"],
        ["Please tell me (formal)", "आँनि लाम होनाय ला", "āṅni lām honāy lā"],
        ["He is eating (respect verb)", "बो जा दिं", "bo jā diṅ"],
        ["She speaks softly (polite)", "बि हौलै लैब दिं", "bi haulai laib diṅ"],
        ["They said (honorific)", "बिफां बोलाय दं", "biphāṅ bolāy dong"],
        ["You will go (polite future)", "नेंथां तोंगो", "nenthāṅ toṅgo"],
        ["We greet you (respect)", "जिंग नेंफांनि नमस्कार ला दं", "jiṅ nenphāṅni namaskār lā dong"],
        ["Respected elder", "गोथो मानसि", "gotho mānasi"],
        ["Please eat (formal)", "जा खालाम", "jā khālam"],
        ["The officer is sitting", "ऑफिसर बैठा दं", "ophisar baiṭhā dong"],
        ["May I leave? (to elder)", "आँ जाय नामा?", "āṅ jāy nāmā?"],
        ["Thank you (formal)", "थांखाय", "thāṅkhāy"],
        ["Grandmother is resting", "आगो आराम ला दिं", "āgo āram lā diṅ"],
    ],
    512: [
        ["To eat", "जानाय", "jānāy"],
        ["To go", "तोंनाय", "toṅnāy"],
        ["To come", "विन्नाय", "vinnāy"],
        ["To read", "पदनाय", "padanāy"],
        ["To write", "लिरनाय", "liranāy"],
        ["To speak", "लैबनाय", "laibnāy"],
        ["To see", "नेउनाय", "neunāy"],
        ["To do", "दानाय", "dānāy"],
        ["To sit", "बैथानाय", "baithānāy"],
        ["To sleep", "सानाय", "sānāy"],
        ["I eat bread", "आँ रोटि जा दों", "āṅ roṭi jā doṅ"],
        ["He reads a book", "बो पुस्तक पद दिं", "bo pustak pad diṅ"],
        ["She writes a letter", "बि चिट्ठि लिर दिं", "bi chiṭṭhi lir diṅ"],
        ["We go to school", "जिंग इस्कुल तों दों", "jiṅ iskul toṅ doṅ"],
        ["They play in the field", "बिफां मैदानाव खेल दिं", "biphāṅ maidānāw khel diṅ"],
        ["Mother cooks food", "आमा खाम फोथो दिं", "āmā khām photho diṅ"],
        ["The boy runs fast", "मुसा दैखो दौड़ दिं", "musā daikho dauṛ diṅ"],
        ["I want to learn Bodo", "आँ बोडो सिमुनाय ला दों", "āṅ boḍo simunāy lā doṅ"],
        ["It is good to help", "गोथो मदद दानाय गोजोन", "gotho madad dānāy gojon"],
        ["They came to meet us", "बिफां जिंनि मोनसे विन दं", "biphāṅ jiṅni monse vin dong"],
    ],
    513: [
        ["I drink water", "आँ दै नुं दों", "āṅ dai nuṅ doṅ"],
        ["You speak loudly (informal)", "नों जोरै लैब दिं", "noṅ jorai laib diṅ"],
        ["He works in Kokrajhar", "बो कोक्राझाराव काम दिं", "bo kokrājhārāw kām diṅ"],
        ["She teaches Bodo", "बि बोडो पद दिं", "bi boḍo pad diṅ"],
        ["We live in the village", "जिंग गाउनि गोर दों", "jiṅ gāuni gor doṅ"],
        ["They sell fruit", "बिफां फल बेस दिं", "biphāṅ phal bes diṅ"],
        ["The sun rises in the east", "सुर उदाय पूबाव थां", "sur udāy pūbāw thāṅ"],
        ["Birds fly in the sky", "सिमफोर आकाशाव उड़ दिं", "simphor ākāśāw uṛ diṅ"],
        ["I know this story", "आँ निं कथि मोन दों", "āṅ nin kathi mon doṅ"],
        ["You understand the lesson", "नों सबक मोन दिं", "noṅ sabak mon diṅ"],
        ["He likes sweet tea", "बो मिथा चा ला दिं", "bo mithā cā lā diṅ"],
        ["She sings every morning", "बि फुंनि गोजोन्थं गान दिं", "bi phuṅni gojonthaṅ gān diṅ"],
        ["We finish homework at night", "जिंग राति गोरनि काम फोर दों", "jiṅ rāti gorani kām phor doṅ"],
        ["They wait at the bus stop", "बिफां बस स्टेन्दाव थां दिं", "biphāṅ bas stendāw thāṅ diṅ"],
        ["The train leaves at six", "ट्रेन सोर वजाव थां", "ṭren sor vajāw thāṅ"],
        ["I pay the bill", "आँ बिल हो दों", "āṅ bil ho doṅ"],
        ["You wash your hands", "नों खौ नुं दिं", "noṅ khau nuṅ diṅ"],
        ["Children play in the park", "सोरफोर पार्काव खेल दिं", "sorphor pārkāw khel diṅ"],
        ["He reads the newspaper daily", "बो दिनफोर खबर पद दिं", "bo dinphor khabar pad diṅ"],
        ["We respect our teachers", "जिंग जिंनि मास्तारफोरनि मान ला दों", "jiṅ jiṅni māstārphorni mān lā doṅ"],
    ],
    514: [
        ["I am a student", "आँ गोथो विद्यार्थी दों", "āṅ gotho vidyārthī doṅ"],
        ["You are tall (informal)", "नों दैङर दं", "noṅ daiṅar dong"],
        ["You are kind (polite)", "नेंथां गोजोन दं", "nenthāṅ gojon dong"],
        ["He is my brother", "बो आँनि दा दं", "bo āṅni dā dong"],
        ["She is a doctor", "बि डाक्टर दं", "bi ḍāktar dong"],
        ["We are ready", "जिंग तैयार दों", "jiṅ taiyār doṅ"],
        ["They are friends", "बिफां दोस्त दं", "biphāṅ dost dong"],
        ["This is my house", "निं आँनि गोर दं", "nin āṅni gor dong"],
        ["That is a temple", "उं गोथो थांसोलि दं", "uṅ gotho thāṃsoli dong"],
        ["It is cold today", "दिनि थंड दं", "dini thaṇḍ dong"],
        ["I am at home", "आँ गोराव दों", "āṅ gorāw doṅ"],
        ["We are in Kokrajhar", "जिंग कोक्राझाराव दों", "jiṅ kokrājhārāw doṅ"],
        ["They are on the road", "बिफां रस्ताव दं", "biphāṅ rastāw dong"],
        ["The keys are on the table", "चाबि मेजाव दं", "cābi mejāw dong"],
        ["There is water in the pot", "हांडि दै दं", "hāṇḍi dai dong"],
        ["There are many people", "बाहागो मानसि दं", "bāhāgo mānasi dong"],
        ["I am fine", "आँ गोरै दों", "āṅ gorai doṅ"],
        ["How are you? (informal)", "नों गोरै दं?", "noṅ gorai dong?"],
        ["How are you? (polite)", "नेंथां गोरै दं?", "nenthāṅ gorai dong?"],
        ["This book is new", "निं पुस्तक गोदान दं", "nin pustak godān dong"],
    ],
    515: [
        ["I am eating now", "आँ दा जा दों", "āṅ dā jā doṅ"],
        ["You are going to school", "नों इस्कुल तों दिं", "noṅ iskul toṅ diṅ"],
        ["He is reading", "बो पद दिं", "bo pad diṅ"],
        ["She is cooking", "बि खाम फोथो दिं", "bi khām photho diṅ"],
        ["We are coming", "जिंग विन दों", "jiṅ vin doṅ"],
        ["They are playing", "बिफां खेल दिं", "biphāṅ khel diṅ"],
        ["It is raining", "दै थां दिं", "dai thāṅ diṅ"],
        ["The baby is sleeping", "सोनोसो सा दिं", "sonoso sā diṅ"],
        ["I am writing a letter", "आँ चिट्ठि लिर दों", "āṅ chiṭṭhi lir doṅ"],
        ["You are listening", "नों नुंथै दिं", "noṅ nunthai diṅ"],
        ["He is driving the car", "बो गाडि चलाय दिं", "bo gāḍi calāy diṅ"],
        ["She is singing", "बि गान दिं", "bi gān diṅ"],
        ["We are waiting for the bus", "जिंग बसनि थां दों", "jiṅ basani thāṅ doṅ"],
        ["They are building a house", "बिफां गोर बोन दिं", "biphāṅ gor bon diṅ"],
        ["I am learning Bodo", "आँ बोडो सिम दों", "āṅ boḍo sim doṅ"],
        ["The dog is barking", "कुथि भौं दिं", "kuthi bhauṅ diṅ"],
        ["Children are studying", "सोरफोर पद दिं", "sorphor pad diṅ"],
        ["Mother is calling you", "आमा नोंनि बोलाय दिं", "āmā noṅni bolāy diṅ"],
        ["Why are you laughing?", "नों माबा हस दिं?", "noṅ mābā has diṅ?"],
        ["We are not leaving yet", "जिंग दा जाय नङा", "jiṅ dā jāy naṅā"],
    ],
    516: [
        ["I will go tomorrow", "आँ गाब्ला तोंगो", "āṅ gāblā toṅgo"],
        ["You will eat later", "नों बादि जागो", "noṅ bādi jāgo"],
        ["He will come soon", "बो दैखो विनगो", "bo daikho vingo"],
        ["She will read this book", "बि निं पुस्तक पदगो", "bi nin pustak padgo"],
        ["We will meet again", "जिंग फिन मोनसे ला दों", "jiṅ phin monse lā doṅ"],
        ["They will return home", "बिफां गोर फिन ला दिं", "biphāṅ gor phin lā diṅ"],
        ["It will rain today", "दिनि दै थांगो", "dini dai thāṅgo"],
        ["I will call you", "आँ नोंनि फोन ला दों", "āṅ noṅni fon lā doṅ"],
        ["You will pass the exam", "नों परीक्षा पास ला दिं", "noṅ parīkṣā pās lā diṅ"],
        ["He will buy rice", "बो मै खरिद ला दिं", "bo mai kharid lā diṅ"],
        ["She will visit Bathou thanshali", "बि बथौ थांसोलि जागो", "bi bathau thāṃsoli jāgo"],
        ["We will help you", "जिंग नोंनि मदद ला दों", "jiṅ noṅni madad lā doṅ"],
        ["They will sing at the function", "बिफां फंक्शनाव गान ला दिं", "biphāṅ phankśanāw gān lā diṅ"],
        ["The train will arrive at eight", "ट्रेन आठ वजाव फै दं", "ṭren āṭh vajāw phai dong"],
        ["I will not lie", "आँ मिथिखौ नङा", "āṅ mithikhau naṅā"],
        ["Will you come with me?", "नों आँनि सों विनगो?", "noṅ āṅni soṅ vingo?"],
        ["He will finish the work", "बो काम फोर ला दिं", "bo kām phor lā diṅ"],
        ["We will celebrate Diwali", "जिंग दिवालि मनाय ला दों", "jiṅ divāli manāy lā doṅ"],
        ["They will build a school", "बिफां गोथो इस्कुल बोन ला दिं", "biphāṅ gotho iskul bon lā diṅ"],
        ["I will send a message", "आँ सन्देस हो दों", "āṅ sandes ho doṅ"],
    ],
    517: [
        ["I will be studying tonight", "आँ राति पद ला दों", "āṅ rāti pad lā doṅ"],
        ["You will be waiting here", "नों दा थां ला दिं", "noṅ dā thāṅ lā diṅ"],
        ["He will be working then", "बो दा काम ला दिं", "bo dā kām lā diṅ"],
        ["She will be cooking in the evening", "बि सांजि खाम फोथो ला दिं", "bi sāṃji khām photho lā diṅ"],
        ["We will be travelling tomorrow", "जिंग गाब्ला सफर ला दों", "jiṅ gāblā safar lā doṅ"],
        ["They will be playing at four", "बिफां सोर वजाव खेल ला दिं", "biphāṅ sor vajāw khel lā diṅ"],
        ["It will be raining there", "दा दै थां ला दं", "dā dai thāṅ lā dong"],
        ["I will be reading on the train", "आँ ट्रेनाव पद ला दों", "āṅ ṭrenāw pad lā doṅ"],
        ["You will be resting at home", "नों गोराव आराम ला दिं", "noṅ gorāw āram lā diṅ"],
        ["He will be speaking at the meeting", "बो मिटिंगाव लैब ला दिं", "bo miṭiṅgāw laib lā diṅ"],
        ["She will be teaching that day", "बि दिनि पद ला दिं", "bi dini pad lā diṅ"],
        ["We will be watching the match", "जिंग मेच नेउ ला दों", "jiṅ mec neu lā doṅ"],
        ["They will be helping guests", "बिफां मेहमानफोरनि मदद ला दिं", "biphāṅ mehmānphorni madad lā diṅ"],
        ["The bus will be leaving soon", "बस दैखो चल ला दं", "bas daikho cal lā dong"],
        ["I will be coming by that road", "आँ उं रस्ताव विन ला दों", "āṅ uṅ rastāw vin lā doṅ"],
        ["Will you be staying here?", "नों दा थां ला दिं?", "noṅ dā thāṅ lā diṅ?"],
        ["He will not be going alone", "बो गोथो नङा तोंगो", "bo gotho naṅā toṅgo"],
        ["We will be waiting until evening", "जिंग सांजि थां ला दों", "jiṅ sāṃji thāṅ lā doṅ"],
        ["They will be building the bridge", "बिफां पुल बोन ला दिं", "biphāṅ pul bon lā diṅ"],
        ["I will be sleeping by then", "आँ दा सा ला दों", "āṅ dā sā lā doṅ"],
    ],
    518: [
        ["I went yesterday", "आँ मैया जा दं", "āṅ maiyā jā dong"],
        ["You came early (informal)", "नों दैखो विन दं", "noṅ daikho vin dong"],
        ["He slept well", "बो गोजोन सा दं", "bo gojon sā dong"],
        ["She laughed loudly", "बि जोरै हस दं", "bi jorai has dong"],
        ["We sat there", "जिंग दा बैठ दं", "jiṅ dā baiṭh dong"],
        ["They stood up", "बिफां खड़ दं", "biphāṅ khaṛ dong"],
        ["I ran fast", "आँ दैखो दौड़ दं", "āṅ daikho dauṛ dong"],
        ["You walked slowly", "नों हौलै चल दं", "noṅ haulai cal dong"],
        ["He fell down", "बो डिग दं", "bo ḍig dong"],
        ["She woke up late", "बि देरै उठ दं", "bi derai uṭh dong"],
        ["We danced at the festival", "जिंग उत्सवाव नाच दं", "jiṅ utsavāw nāc dong"],
        ["They shouted with joy", "बिफां खुसिफोरै खोर दं", "biphāṅ khusiphorai khor dong"],
        ["The bird flew away", "सिम उड़ जा दं", "sim uṛ jā dong"],
        ["It rained heavily", "जोरै दै थां दं", "jorai dai thāṅ dong"],
        ["I cried once", "आँ गोथो थां रो दं", "āṅ gotho thāṅ ro dong"],
        ["You arrived on time", "नों वक्ताव फै दं", "noṅ vaktāw phai dong"],
        ["He hurried home", "बो दैखो गोर जा दं", "bo daikho gor jā dong"],
        ["We rested under the tree", "जिंग गोजो गाह्राव आराम दं", "jiṅ gojo gāhrāw āram dong"],
        ["They returned late", "बिफां देरै फिन दं", "biphāṅ derai phin dong"],
        ["The sun set in the west", "सुर पसिमाव डुब दं", "sur pasimāw ḍub dong"],
    ],
    519: [
        ["I ate rice", "आँ मै खा दं", "āṅ mai khā dong"],
        ["You read the book", "नों पुस्तक पद दं", "noṅ pustak pad dong"],
        ["He opened the door", "बो दरवाजा खोल दं", "bo daravājā khol dong"],
        ["She wrote a letter", "बि चिट्ठि लिर दं", "bi chiṭṭhi lir dong"],
        ["We saw a film", "जिंग गोथो फिल्म नेउ दं", "jiṅ gotho film neu dong"],
        ["They bought vegetables", "बिफां सब्जि खरिद दं", "biphāṅ sabji kharid dong"],
        ["I gave him money", "आँ बिनि पैसा हो दं", "āṅ bini paisā ho dong"],
        ["You told the truth", "नों सोलों बोल दं", "noṅ soloṅ bol dong"],
        ["He caught the ball", "बो बल फड़ दं", "bo bal faṛ dong"],
        ["She made tea", "बि चा बोन दं", "bi cā bon dong"],
        ["We finished the work", "जिंग काम फोर दं", "jiṅ kām phor dong"],
        ["They broke the glass", "बिफां सिसा तोर दं", "biphāṅ sisā tor dong"],
        ["I lost my pen", "आँ आँनि कलम गोम दं", "āṅ āṅni kalam gom dong"],
        ["You found the keys", "नों चाबि लाब दं", "noṅ cābi lāb dong"],
        ["He closed the window", "बो खिड़कि बन्द दं", "bo khiṛaki band dong"],
        ["She washed the clothes", "बि कपड़ नुं दं", "bi kapaṛ nuṅ dong"],
        ["We heard the news", "जिंग खबर नुंथ दं", "jiṅ khabar nunth dong"],
        ["They answered every question", "बिफां हर सोंनायनि जवाब हो दं", "biphāṅ har soṃnāyni javāb ho dong"],
        ["I drank milk", "आँ दूध नुं दं", "āṅ dūdh nuṅ dong"],
        ["You helped your friend", "नों नोंनि दोस्तनि मदद दं", "noṅ noṅni dostani madad dong"],
    ],
    520: [
        ["I was at home", "आँ गोराव दं", "āṅ gorāw dong"],
        ["You were tired (informal)", "नों थाक दं", "noṅ thāk dong"],
        ["He was ill", "बो बिमार दं", "bo bimār dong"],
        ["She was happy", "बि खुसि दं", "bi khusi dong"],
        ["We were students", "जिंग विद्यार्थी दं", "jiṅ vidyārthī dong"],
        ["They were teachers", "बिफां मास्तार दं", "biphāṅ māstār dong"],
        ["It was cold", "थंड दं", "thaṇḍ dong"],
        ["There was a problem", "गोथो समस्या दं", "gotho samasyā dong"],
        ["There were many guests", "बाहागो मेहमान दं", "bāhāgo mehmān dong"],
        ["I was in Kokrajhar", "आँ कोक्राझाराव दं", "āṅ kokrājhārāw dong"],
        ["You were late", "नों देरै दं", "noṅ derai dong"],
        ["He was my neighbour", "बो आँनि गाह्रि दं", "bo āṅni gāhri dong"],
        ["She was ready", "बि तैयार दं", "bi taiyār dong"],
        ["We were together", "जिंग गोथो दं", "jiṅ gotho dong"],
        ["They were absent", "बिफां नेथ दं", "biphāṅ neth dong"],
        ["The shop was closed", "दुकान बन्द दं", "dukān band dong"],
        ["The roads were wet", "रस्ता गिलि दं", "rastā gili dong"],
        ["I was not afraid", "आँ डर नङा", "āṅ ḍar naṅā"],
        ["Were you there?", "नों दा दं?", "noṅ dā dong?"],
        ["It was a good day", "गोजोन दिन दं", "gojon din dong"],
    ],
    521: [
        ["He goes → he went", "बो तों दिं → बो जा दं", "bo toṅ diṅ → bo jā dong"],
        ["He does → he did", "बो दा दिं → बो दं", "bo dā diṅ → bo dong"],
        ["He gives → he gave", "बो हो दिं → बो हो दं", "bo ho diṅ → bo ho dong"],
        ["He takes → he took", "बो ला दिं → बो ला दं", "bo lā diṅ → bo lā dong"],
        ["He says → he said", "बो बोल दिं → बो बोल दं", "bo bol diṅ → bo bol dong"],
        ["He sees → he saw", "बो नेउ दिं → बो नेउ दं", "bo neu diṅ → bo neu dong"],
        ["He sits → he sat", "बो बैठ दिं → बो बैठ दं", "bo baiṭh diṅ → bo baiṭh dong"],
        ["He comes → he came", "बो विन दिं → बो विन दं", "bo vin diṅ → bo vin dong"],
        ["I go → I went", "आँ तों दों → आँ जा दं", "āṅ toṅ doṅ → āṅ jā dong"],
        ["I eat → I ate", "आँ जा दों → आँ खा दं", "āṅ jā doṅ → āṅ khā dong"],
        ["You drink → you drank", "नों नुं दिं → नों नुं दं", "noṅ nuṅ diṅ → noṅ nuṅ dong"],
        ["We come → we came", "जिंग विन दों → जिंग विन दं", "jiṅ vin doṅ → jiṅ vin dong"],
        ["They go → they went", "बिफां तों दिं → बिफां जा दं", "biphāṅ toṅ diṅ → biphāṅ jā dong"],
        ["He sleeps → he slept", "बो सा दिं → बो सा दं", "bo sā diṅ → bo sā dong"],
        ["She reads → she read", "बि पद दिं → बि पद दं", "bi pad diṅ → bi pad dong"],
        ["He runs → he ran", "बो दौड़ दिं → बो दौड़ दं", "bo dauṛ diṅ → bo dauṛ dong"],
        ["It falls → it fell", "बो डिग दिं → बो डिग दं", "bo ḍig diṅ → bo ḍig dong"],
        ["He knows → he knew", "बो मोन दिं → बो मोन दं", "bo mon diṅ → bo mon dong"],
        ["I bring → I brought", "आँ ला दों → आँ ला दं", "āṅ lā doṅ → āṅ lā dong"],
        ["You forget → you forgot", "नों गोम दिं → नों गोम दं", "noṅ gom diṅ → noṅ gom dong"],
    ],
    522: [
        ["I was reading then", "आँ दा पद दं", "āṅ dā pad dong"],
        ["You were sleeping", "नों सा दं", "noṅ sā dong"],
        ["He was walking home", "बो गोर नि चल दं", "bo gor ni cal dong"],
        ["She was cooking rice", "बि मै रांद दं", "bi mai rānd dong"],
        ["We were talking", "जिंग गल ला दं", "jiṅ gal lā dong"],
        ["They were playing", "बिफां खेल दं", "biphāṅ khel dong"],
        ["It was raining", "दै थां दं", "dai thāṅ dong"],
        ["The baby was crying", "सोनोसो रो दं", "sonoso ro dong"],
        ["I was waiting for you", "आँ नोंनि थां दं", "āṅ noṅni thāṅ dong"],
        ["You were driving fast", "नों दैखो गाडि चल दं", "noṅ daikho gāḍi cal dong"],
        ["He was writing a letter", "बो चिट्ठि लिर दं", "bo chiṭṭhi lir dong"],
        ["She was singing on stage", "बि मंचाव गान दं", "bi mañcāw gān dong"],
        ["We were watching TV", "जिंग टिभि नेउ दं", "jiṅ ṭibhi neu dong"],
        ["They were building a wall", "बिफां दिबार बोन दं", "biphāṅ dibār bon dong"],
        ["The dog was barking", "कुथि भौं दं", "kuthi bhauṅ dong"],
        ["I was not listening", "आँ नुंथ नङा", "āṅ nunth naṅā"],
        ["Why were you late?", "नों माबा देर दं?", "noṅ mābā der dong?"],
        ["He was helping his father", "बो बिनि बाफानि मदद दं", "bo bini bāphāni madad dong"],
        ["We were studying all day", "जिंग दिनफोर पद दं", "jiṅ dinphor pad dong"],
        ["They were laughing loudly", "बिफां जोरै हस दं", "biphāṅ jorai has dong"],
    ],
    523: [
        ["I have eaten", "आँ खा जाब दं", "āṅ khā jāb dong"],
        ["You have come", "नों विन जाब दं", "noṅ vin jāb dong"],
        ["He has gone", "बो जा जाब दं", "bo jā jāb dong"],
        ["She has finished", "बि फोर जाब दं", "bi phor jāb dong"],
        ["We have seen it", "जिंग नेउ जाब दं", "jiṅ neu jāb dong"],
        ["They have left", "बिफां चल जाब दं", "biphāṅ cal jāb dong"],
        ["I had slept", "आँ सा जाब दं", "āṅ sā jāb dong"],
        ["You had told me", "नों आँनि बोल जाब दं", "noṅ āṅni bol jāb dong"],
        ["He had arrived", "बो फै जाब दं", "bo phai jāb dong"],
        ["She had cooked", "बि रांद जाब दं", "bi rānd jāb dong"],
        ["We had agreed", "जिंग राजि जाब दं", "jiṅ rāji jāb dong"],
        ["They had gone before us", "बिफां जिंनि सों चल जाब दं", "biphāṅ jiṅni soṅ cal jāb dong"],
        ["I will have finished", "आँ फोर जागो", "āṅ phor jāgo"],
        ["You will have left", "नों चल जागो", "noṅ cal jāgo"],
        ["He will have read", "बो पद जागो", "bo pad jāgo"],
        ["By then I will have gone", "दा आँ जा जागो", "dā āṅ jā jāgo"],
        ["She will have cooked by evening", "सांजि बि रांद जागो", "sāṃji bi rānd jāgo"],
        ["We have not met yet", "जिंग हाय मोन नङा", "jiṅ hāy mon naṅā"],
        ["Have you heard?", "नों नुंथ दं?", "noṅ nunth dong?"],
        ["They had never seen snow", "बिफां बर्फ नेउ नङा", "biphāṅ barf neu naṅā"],
    ],
    524: [
        ["In the room", "रुमाव", "rumāw"],
        ["On the table", "मेजाव", "mejāw"],
        ["Under the bed", "बिस्तर थालाव", "bistar thālāw"],
        ["Near the river", "दरिया गाह्रि", "dariyā gāhri"],
        ["From the city", "सहर निफ्राय", "sahar niphrāy"],
        ["To the market", "बाजाराव", "bājārāw"],
        ["With my mother", "आँनि आमानि सों", "āṅni āmāni soṅ"],
        ["Without money", "पैसा नङै", "paisā naṅai"],
        ["Between two trees", "गोजो रुखफोर नि", "gojo rukhphor ni"],
        ["Behind the house", "गोर पिसिन", "gor pisini"],
        ["In front of the gate", "दरवाजा सिंनि", "daravājā siṃni"],
        ["Inside the box", "डिब्बाव", "ḍibbāw"],
        ["Outside the village", "गाउ निफ्राय", "gāu niphrāy"],
        ["Across the bridge", "पुल पार", "pul pār"],
        ["Until tomorrow", "गाब्ला थां", "gāblā thāṅ"],
        ["After lunch", "दुपर बाद", "dupar bād"],
        ["Before sunrise", "सुर उदाय सों", "sur udāy soṅ"],
        ["I am at school", "आँ इस्कुलाव दों", "āṅ iskulāw doṅ"],
        ["The book is in the bag", "पुस्तक थैलि दं", "pustak thaili dong"],
        ["He sat beside me", "बो आँनि गाह्रि बैठ दं", "bo āṅni gāhri baiṭh dong"],
    ],
    525: [
        ["Go to school", "स्कुलाव जा", "skulāw jā"],
        ["Come to my house", "आँनि गोराव विन", "āṅni gorāw vin"],
        ["Return to work", "कामाव फिन", "kāmāw phin"],
        ["Walk to the shop", "दुकानाव पैदल जा", "dukānāw paidal jā"],
        ["Run to the field", "मैदानाव दौड़", "maidānāw dauṛ"],
        ["Send a letter to him", "बिनि चिट्ठि हो", "bini chiṭṭhi ho"],
        ["Give water to the dog", "कुथिनि दै हो", "kuthini dai ho"],
        ["I am going to Kokrajhar", "आँ कोक्राझार तों दों", "āṅ kokrājhār toṅ doṅ"],
        ["We went to the temple", "जिंग थांसोलि जा दं", "jiṅ thāṃsoli jā dong"],
        ["They came to help", "बिफां मदद ला विन दं", "biphāṅ madad lā vin dong"],
        ["Take this to father", "निं बाफानि हो", "nin bāphāni ho"],
        ["Come to me", "आँनि गाह्रि विन", "āṅni gāhri vin"],
        ["Fly to Delhi", "दिल्लियाव उड़", "dilliyāw uṛ"],
        ["Drive to the station", "स्टेशनाव गाडि ला", "sṭeśanāw gāḍi lā"],
        ["I will go to the bank", "आँ बैंक तोंगो", "āṅ baenk toṅgo"],
        ["She ran to the door", "बि दरवाजाव दौड़ दं", "bi daravājāw dauṛ dong"],
        ["Bring fruit to me", "आँनि फल ला", "āṅni phal lā"],
        ["Do not go to the river alone", "गोथो दरिया नङा जा", "gotho dariyā naṅā jā"],
        ["We are going to Udalguri", "जिंग उदलगुरि तों दों", "jiṅ udalaguri toṅ doṅ"],
        ["He came to the meeting", "बो मिटिंगाव विन दं", "bo miṭiṅgāw vin dong"],
    ],
    526: [
        ["I saw him", "आँ बिनि नेउ दं", "āṅ bini neu dong"],
        ["You called her", "नों बिनि बोल दं", "noṅ bini bol dong"],
        ["He helped them", "बो बिफांनि मदद दं", "bo biphāṅni madad dong"],
        ["She loves her mother", "बि बिनि आमानि मान ला दिं", "bi bini āmāni mān lā diṅ"],
        ["We invited the guests", "जिंग मेहमानफोरनि बोल दं", "jiṅ mehmānphorni bol dong"],
        ["They praised the teacher", "बिफां मास्तारनि मान ला दं", "biphāṅ māstārani mān lā dong"],
        ["I gave the child a sweet", "आँ सोरनि मिथाइ हो दं", "āṅ sorani mithāi ho dong"],
        ["You told us the story", "नों जिंनि कथि बोल दं", "noṅ jiṅni kathi bol dong"],
        ["He sent me a message", "बो आँनि सन्देस हो दं", "bo āṅni sandes ho dong"],
        ["She showed me the photo", "बि आँनि फोटो नेउ दं", "bi āṅni phoṭo neu dong"],
        ["Find the boy", "मुसानि लाब", "musāni lāb"],
        ["Call the doctor", "डाक्टरनि बोल", "ḍākṭarani bol"],
        ["Respect your elders", "गोथो मानसिफोरनि मान ला", "gotho mānasi-phorni mān lā"],
        ["I met my friend", "आँ आँनि दोस्तनि मोन दं", "āṅ āṅni dostani mon dong"],
        ["We missed you", "जिंग नोंनि याद ला दं", "jiṅ noṅni yād lā dong"],
        ["They forgot him", "बिफां बिनि गोम दं", "biphāṅ bini gom dong"],
        ["Do not hurt anyone", "गोथो मानसिनि चोट नङा", "gotho mānasini choṭ naṅā"],
        ["I taught the students", "आँ विद्यार्थिफोरनि पद दं", "āṅ vidyārthiphorni pad dong"],
        ["She fed the baby", "बि सोनोसोनि जा हो दं", "bi sonosoni jā ho dong"],
        ["He thanked his parents", "बो बिनि बाफा-आमानि थांखाय हो दं", "bo bini bāphā-āmāni thāṅkhāy ho dong"],
    ],
}
