# Bodo Lesson 4 — Vocabulary (chapter IDs 597–619).

LESSONS_S4 = {
    597: [
        ["Head", "सिर", "sir"],
        ["Hair", "खुर", "khur"],
        ["Eye", "अख", "akh"],
        ["Ear", "कान", "kān"],
        ["Nose", "नाक", "nāk"],
        ["Mouth", "मों", "moṅ"],
        ["Tooth / teeth", "दांत", "dānt"],
        ["Tongue", "जिभ", "jibh"],
        ["Neck", "गर्दन", "gardan"],
        ["Shoulder", "कांध", "kāndh"],
        ["Arm", "बांह", "bāṅh"],
        ["Hand", "खौ", "khau"],
        ["Finger", "अंगुलि", "aṅguli"],
        ["Chest", "छाति", "chāti"],
        ["Stomach", "पेट", "peṭ"],
        ["Back", "पीठ", "pīṭh"],
        ["Leg", "लात", "lāt"],
        ["Foot", "पैर", "pair"],
        ["Skin", "चमड़ि", "camaṛi"],
        ["Bone", "हाड्डि", "hāḍḍi"],
    ],
    598: [
        ["House", "गोर", "gor"],
        ["Door", "दरवाजा", "daravājā"],
        ["Window", "खिड़कि", "khiṛaki"],
        ["Road", "रस्ता", "rastā"],
        ["Water", "दै", "dai"],
        ["Fire", "अग", "ag"],
        ["Sky", "आकाश", "ākāś"],
        ["Earth / soil", "दिंग", "diṅg"],
        ["Sun", "सुर", "sur"],
        ["Moon", "जुन", "jun"],
        ["Star", "तारा", "tārā"],
        ["Wind", "हावा", "hāvā"],
        ["Rain", "मींह", "mīṅh"],
        ["Day", "दिन", "din"],
        ["Night", "रात", "rāt"],
        ["Morning", "फुंनि", "phuṅni"],
        ["Evening", "संजा", "sañjā"],
        ["Market", "बाजार", "bājār"],
        ["Shop", "दुकान", "dukān"],
        ["School", "इस्कुल", "iskul"],
    ],
    599: [
        ["Father", "बा", "bā"],
        ["Mother", "आमा", "āmā"],
        ["Brother", "दा", "dā"],
        ["Sister", "बे", "be"],
        ["Son", "सोन", "son"],
        ["Daughter", "सोनोसो", "sonoso"],
        ["Husband", "कमला", "kamalā"],
        ["Wife", "जायई", "jāyī"],
        ["Grandfather", "आगो", "āgo"],
        ["Grandmother", "आगो आमा", "āgo āmā"],
        ["Uncle (father's brother)", "काका", "kākā"],
        ["Aunt", "काकी", "kākī"],
        ["Maternal uncle", "मामा", "māmā"],
        ["Maternal aunt", "मामी", "māmī"],
        ["Father-in-law", "ससुर", "sasur"],
        ["Mother-in-law", "सस", "sas"],
        ["Nephew", "भांजा", "bhāñjā"],
        ["Niece", "भांजी", "bhāñjī"],
        ["Cousin", "फिसाफोर दा / बे", "phisāphor dā / be"],
        ["Friend", "दोस्त", "dost"],
    ],
    600: [
        ["One", "से / इक", "se / ik"],
        ["Two", "नै / दो", "nai / do"],
        ["Three", "थाम / तिन", "thām / tin"],
        ["Four", "ब्रै / चार", "brai / cār"],
        ["Five", "बा / पाँच", "bā / pā̃c"],
        ["Six", "रो / छे", "ro / che"],
        ["Seven", "स्नि / सात", "sni / sāt"],
        ["Eight", "जाद / आठ", "jād / āṭh"],
        ["Nine", "गु / नौ", "gu / nau"],
        ["Ten", "जि / दस", "ji / das"],
        ["Eleven", "ग्यारह", "gyārah"],
        ["Twelve", "बारह", "bārah"],
        ["Thirteen", "तेरह", "terah"],
        ["Fourteen", "चौदह", "caudah"],
        ["Fifteen", "पंद्रह", "pandrah"],
        ["Sixteen", "सोलह", "solah"],
        ["Seventeen", "सतारह", "satārah"],
        ["Eighteen", "अठारह", "aṭhārah"],
        ["Nineteen", "उन्नीस", "unnīs"],
        ["Twenty", "बीस / नेइ", "bīs / nei"],
    ],
    601: [
        ["Twenty-one", "इक्की", "ikkī"],
        ["Thirty", "तीस", "tīs"],
        ["Forty", "चाली", "cālī"],
        ["Fifty", "पचास", "pacās"],
        ["Sixty", "साठ", "sāṭh"],
        ["Seventy", "सत्तर", "sattar"],
        ["Eighty", "असी", "asī"],
        ["Ninety", "नब्बे", "nabbe"],
        ["One hundred", "सौ", "sau"],
        ["Two hundred", "दो सौ", "do sau"],
        ["One thousand", "एक हजार", "ek hazār"],
        ["Ten thousand", "दस हजार", "das hazār"],
        ["One lakh", "एक लाख", "ek lākh"],
        ["First", "गोथो", "gotho"],
        ["Second", "नैथां", "naithāṅ"],
        ["Third", "थामथां", "thāmthāṅ"],
        ["Last", "आखिरि", "ākhiri"],
        ["Next", "फिननि", "finani"],
        ["Previous", "मोथाइनि", "mothāini"],
        ["How many?", "माबो?", "mābo?"],
    ],
    602: [
        ["Half", "आधि", "ādhi"],
        ["Quarter", "पाव", "pāv"],
        ["One third", "थाम गोथो", "thām gotho"],
        ["Twice", "नै वार", "nai vār"],
        ["Thrice", "थाम वार", "thām vār"],
        ["Double", "दुगुन", "dugun"],
        ["Single", "गोथो", "gotho"],
        ["Pair", "जोड़", "joṛ"],
        ["Percent", "फिसदि", "phisadi"],
        ["Number", "नंबर", "nambar"],
        ["Series", "लड़ि", "laṛi"],
        ["Order", "क्रम", "kram"],
        ["Before (sequence)", "मोथाइ", "mothāi"],
        ["After (sequence)", "फिन", "phin"],
        ["Again", "फिन", "phin"],
        ["Once", "गोथो वार", "gotho vār"],
        ["Fraction", "अंश", "aṃś"],
        ["Whole", "गोबो", "gobo"],
        ["Equal", "बराबर", "barābar"],
        ["Approximate", "लगभग", "lagabhag"],
    ],
    603: [
        ["To go", "तोंनाय", "toṅnāy"],
        ["To come", "विन्नाय", "vinnāy"],
        ["To eat", "जानाय", "jānāy"],
        ["To drink", "नुंनाय", "nuṅnāy"],
        ["To sleep", "सानाय", "sānāy"],
        ["To wake up", "उठनाय", "uṭhanāy"],
        ["To sit", "बैथानाय", "baithānāy"],
        ["To stand", "उबथानाय", "ubathānāy"],
        ["To walk", "टुरनाय", "ṭuranāy"],
        ["To run", "दौड़नाय", "dauṛanāy"],
        ["To speak", "लैबनाय", "laibnāy"],
        ["To listen", "नुंथानाय", "nunthānāy"],
        ["To see", "नेउनाय", "neunāy"],
        ["To read", "पदनाय", "padanāy"],
        ["To write", "लिरनाय", "liranāy"],
        ["To learn", "सिमुनाय", "simunāy"],
        ["To teach", "पदौनाय", "padounāy"],
        ["To buy", "खरिदनाय", "kharidanāy"],
        ["To sell", "बेसनाय", "besanāy"],
        ["To give", "होनाय / दानाय", "honāy / dānāy"],
    ],
    604: [
        ["To take", "लानाय", "lānāy"],
        ["To bring", "लैआनाय", "laiānāy"],
        ["To send", "खोरनाय", "khoranāy"],
        ["To open", "खोलनाय", "kholanāy"],
        ["To close", "बन्द खालाम", "band khālam"],
        ["To wash", "नुनाय", "nunāy"],
        ["To cook", "फोथोनाय", "phothonāy"],
        ["To cut", "काटनाय", "kāṭanāy"],
        ["To play", "खेलनाय", "khelanāy"],
        ["To sing", "गाननाय", "gānanāy"],
        ["To dance", "नाचनाय", "nācanāy"],
        ["To laugh", "हसनाय", "hasanāy"],
        ["To cry", "रोनाय", "ronāy"],
        ["To ask", "फुंनाय", "phuṅnāy"],
        ["To answer", "जवाब होनाय", "javāb honāy"],
        ["To think", "सोंलोनाय", "soṅlonāy"],
        ["To understand", "मोननाय", "monanāy"],
        ["To forget", "गोमनाय", "gomanāy"],
        ["To remember", "याद खालाम", "yād khālam"],
        ["To wait", "थांनाय", "thāṅnāy"],
    ],
    605: [
        ["To work", "काम दानाय", "kām dānāy"],
        ["To rest", "आराम खालाम", "ārām khālam"],
        ["To help", "मदद दानाय", "madad dānāy"],
        ["To fight", "लाडनाय", "lāḍanāy"],
        ["To love", "प्यार दानाय", "pyār dānāy"],
        ["To hate", "नेफ्राय", "nephrai"],
        ["To like", "पसंद लानाय", "pasand lānāy"],
        ["To try", "कोशिश खालाम", "koshish khālam"],
        ["To start", "सुरु खालाम", "surū khālam"],
        ["To finish", "मुकनाय", "mukanāy"],
        ["To use", "बाहागो", "bāhāgo"],
        ["To need", "लाम होनाय", "lām honāy"],
        ["To fall", "डिगनाय", "ḍiganāy"],
        ["To climb", "चढ़नाय", "caṛhanāy"],
        ["To fall (drop)", "गिरनाय", "giranāy"],
        ["To meet", "मिलनाय", "milanāy"],
        ["To leave", "चलनाय", "calanāy"],
        ["To return", "मुडनाय", "muḍanāy"],
        ["To stay", "थांनाय", "thāṅnāy"],
        ["To live", "जिउनाय", "jiunāy"],
    ],
    606: [
        ["To call (phone)", "फोन खालाम", "fon khālam"],
        ["To message", "खोर होनाय", "khor honāy"],
        ["To search", "नायनाय", "nāynāy"],
        ["To choose", "सायनाय", "sāynāy"],
        ["To change", "बदलनाय", "badalanāy"],
        ["To break", "टुटनाय", "ṭuṭanāy"],
        ["To join", "जोडनाय", "joḍanāy"],
        ["To pay", "भरनाय", "bharanāy"],
        ["To borrow", "उधार लानाय", "udhār lānāy"],
        ["To lend", "उधार होनाय", "udhār honāy"],
        ["To win", "जितनाय", "jitanāy"],
        ["To lose", "हारनाय", "hāranāy"],
        ["To push", "धकेलनाय", "dhekalanāy"],
        ["To pull", "खिंचनाय", "khincanāy"],
        ["To throw", "सुटनाय", "suṭanāy"],
        ["To catch", "फडनाय", "phaḍanāy"],
        ["To carry", "चुकनाय", "cukanāy"],
        ["To build", "बानाय", "bānāy"],
        ["To clean", "साफ खालाम", "sāph khālam"],
        ["To sweep", "झाड़ खालाम", "jhāṛ khālam"],
    ],
    607: [
        ["To give (laav-) — I give", "आँ हो दों", "āṅ ho doṅ"],
        ["Give me water", "आँनि दै हो", "āṅni dai ho"],
        ["He gives help", "बो मदद हो दिं", "bo madad ho diṅ"],
        ["Give way / let pass", "रस्ता हो", "rastā ho"],
        ["Give a slap (colloquial)", "थप्पड हो", "thappaḍ ho"],
        ["To take (leb-) — I take", "आँ ला दों", "āṅ lā doṅ"],
        ["Take this", "निं ला", "nin lā"],
        ["Take care", "ख्याल राख", "khyāl rākh"],
        ["Take permission", "इजाजत ला", "ijāzat lā"],
        ["Take revenge", "बदला ला", "badalā lā"],
        ["Multiple senses of 'give'", "होनाय — दान, भेंट", "honāy — dān, bheṇṭ"],
        ["Give respect", "मान हो", "mān ho"],
        ["Give pain", "दुख हो", "dukh ho"],
        ["Take a bath", "नहा / गोसल", "nahā / gosal"],
        ["Take a photo", "फोटो खिंच", "phoṭo khinc"],
        ["Take time", "सम ला", "sam lā"],
        ["Take medicine", "दवाई ला", "davāī lā"],
        ["Give an answer", "जवाब हो", "javāb ho"],
        ["Take a seat", "बैठ जा", "baiṭh jā"],
        ["Give a speech", "भाषण हो", "bhāṣaṇ ho"],
    ],
    608: [
        ["To feel / seem (laag-) — it seems good", "गोजोन लाग", "gojon lāg"],
        ["I feel cold", "आँनि थंड लाग", "āṅni thaṇḍ lāg"],
        ["It suits you", "नोंनि गोजो लाग", "noṅni gojon lāg"],
        ["To be attached", "लाग — मोजां लाग", "lāg — mojāṅ lāg"],
        ["To begin (work)", "कम लाग", "kam lāg"],
        ["To cost", "पैसा लाग", "paisā lāg"],
        ["To take time", "सम लाग", "sam lāg"],
        ["Headache 'lags'", "सिर दर्द लाग", "sir dard lāg"],
        ["Feel ashamed", "लाज लाग", "lāj lāg"],
        ["Feel hungry", "भुख लाग", "bhukh lāg"],
        ["Feel sleepy", "नुंथाइ लाग", "nunthāi lāg"],
        ["It appears / looks", "नेउ लाग", "neu lāg"],
        ["Match / pair (verb)", "जोड लाग", "joḍ lāg"],
        ["To stick", "चिपक — गोंद लाग", "cipak — gond lāg"],
        ["To be needed", "लाम लाग", "lām lāg"],
        ["To get habit", "आदत लाग", "ādat lāg"],
        ["To befall (trouble)", "मुसिबत लाग", "musibat lāg"],
        ["Feel like (I want to go)", "तोंनाय मन लाग", "toṅnāy man lāg"],
        ["Colour 'sits' well", "रंग गोजो लाग", "raṅ gojon lāg"],
        ["Seems expensive", "महंगा लाग", "mahangā lāg"],
    ],
    609: [
        ["Good", "गोजोन", "gojon"],
        ["Bad", "माड़ा", "māṛā"],
        ["Big", "बाहागो", "bāhāgo"],
        ["Small", "हिन", "hin"],
        ["New", "गोदान", "godān"],
        ["Old", "पुराना / बुजुर्ग", "purānā / bujurg"],
        ["Hot", "गरम", "garam"],
        ["Cold", "ठंडा", "ṭhaṇḍā"],
        ["Sweet", "मिथा", "mithā"],
        ["Bitter", "तिता", "titā"],
        ["Sour", "खट्टा", "khaṭṭā"],
        ["Salted", "निमख", "nimakh"],
        ["Clean", "साफ", "sāph"],
        ["Dirty", "मैला", "mailā"],
        ["Beautiful", "सोन", "son"],
        ["Ugly", "बदसूरत", "badasūrat"],
        ["Tall", "दैङर", "daiṅar"],
        ["Short", "हिन / निवा", "hin / nivā"],
        ["Fat", "मोटा", "moṭā"],
        ["Thin", "पतला", "patlā"],
    ],
    610: [
        ["Quickly", "दैखो", "daikho"],
        ["Slowly", "हौलै", "haulai"],
        ["Always", "गासै", "gāsai"],
        ["Never", "कदे नङा", "kade naṅā"],
        ["Sometimes", "कदे कदे", "kade kade"],
        ["Often", "बाहागो", "bāhāgo"],
        ["Today", "दिनि", "dini"],
        ["Tomorrow", "गाब्ला", "gāblā"],
        ["Yesterday", "मैया दिन", "maiyā din"],
        ["Now", "दा", "dā"],
        ["Then", "फिन", "phin"],
        ["Here", "निं", "nin"],
        ["There", "उं", "uṅ"],
        ["Where", "कुथां", "kuthāṅ"],
        ["How", "माबो", "mābo"],
        ["Why", "माब्ला", "māblā"],
        ["Very", "बाहागो", "bāhāgo"],
        ["Little", "थोड़", "thoṛ"],
        ["Too much", "ज्यादा", "zyādā"],
        ["Enough", "बस / काफि", "bas / kāphi"],
    ],
    611: [
        ["Upstairs", "उप्पर", "uppar"],
        ["Downstairs", "थल्ले", "thalle"],
        ["Inside", "अन्दर", "andar"],
        ["Outside", "बाहर", "bāhar"],
        ["Near", "गाह्रि", "gāhri"],
        ["Far", "दूर", "dūr"],
        ["Left", "खब्बा", "khabbā"],
        ["Right", "सज्जा", "sajjā"],
        ["Straight", "सीधा", "sīdhā"],
        ["Around", "गाह्रि गाह्रि", "gāhri gāhri"],
        ["Ahead", "मोथाइ", "mothāi"],
        ["Behind", "पिसिन", "pisini"],
        ["Together", "मिल", "mil"],
        ["Alone", "गोथो", "gotho"],
        ["Perhaps", "हो ला दं", "ho lā dong"],
        ["Certainly", "जरूर", "jarūr"],
        ["Maybe", "हो ला दं", "ho lā dong"],
        ["Again", "फिन", "phin"],
        ["Already", "मोथाइ", "mothāi"],
        ["Yet / still", "थां", "thāṅ"],
    ],
    612: [
        ["Potato", "आलू", "ālū"],
        ["Onion", "गांदा", "gāndā"],
        ["Tomato", "टमाटर", "ṭamāṭar"],
        ["Brinjal / eggplant", "बैंगन", "baiṅgan"],
        ["Cauliflower", "फूलगोभि", "phūlgobhi"],
        ["Cabbage", "गोभि", "gobhi"],
        ["Spinach", "पालक", "pālak"],
        ["Pumpkin", "कद्दू", "kaddū"],
        ["Bottle gourd", "लौकि", "lauki"],
        ["Radish", "मूला", "mūlā"],
        ["Carrot", "गाजर", "gājar"],
        ["Peas", "मटर", "maṭar"],
        ["Beans", "फलि", "phali"],
        ["Chilli", "मिर्च", "mirch"],
        ["Coriander", "धनिया", "dhaniyā"],
        ["Garlic", "लहसुन", "lahasun"],
        ["Ginger", "अदा", "adā"],
        ["Turnip", "शलगम", "śalgam"],
        ["Lady's finger", "भिंडि", "bhiṇḍi"],
        ["Cucumber", "खीरा", "khīrā"],
    ],
    613: [
        ["Mango", "आम", "ām"],
        ["Banana", "कोल", "kol"],
        ["Apple", "सेब", "seb"],
        ["Grapes", "अंगूर", "aṅgūr"],
        ["Orange", "संतरा", "santarā"],
        ["Guava", "मदाम", "madām"],
        ["Pomegranate", "दालिम", "dālim"],
        ["Watermelon", "तरबूज", "tarbūj"],
        ["Muskmelon", "खरबूज", "kharbūj"],
        ["Papaya", "पपीता", "papītā"],
        ["Pear", "नाशपाति", "nāśpāti"],
        ["Plum / jamun", "जामुन", "jāmun"],
        ["Lemon", "निम्ब", "nimb"],
        ["Coconut", "नारियल", "nāriyal"],
        ["Lychee", "लीचि", "līci"],
        ["Sweet lime", "मौसंबि", "mausambi"],
        ["Fig", "दुमुर", "dumur"],
        ["Cherry (loan)", "चेरी", "cerī"],
        ["Strawberry", "स्ट्रॉबेरी", "sṭrāoberī"],
        ["Ripe (fruit)", "फोथो", "photho"],
    ],
    614: [
        ["Crow", "काँव", "kā̃v"],
        ["Sparrow", "चिड़ि", "ciṛi"],
        ["Pigeon", "पारो", "pāro"],
        ["Parrot", "सुआ", "suā"],
        ["Peacock", "मोर", "mor"],
        ["Eagle", "बाज", "bāj"],
        ["Owl", "पेचा", "pecā"],
        ["Duck", "हाँह", "hā̃h"],
        ["Hen", "कोइ", "koi"],
        ["Rooster", "कुकर", "kukar"],
        ["Swallow", "अबाबिल", "abābil"],
        ["Koel", "कुइल", "kuil"],
        ["Myna", "मैना", "mainā"],
        ["Crane (bird)", "बगुला", "bagulā"],
        ["Woodpecker", "काठफोड़ा", "kāṭhphoṛā"],
        ["Singing bird", "गान गोजो सिम", "gān gojo sim"],
        ["Nest", "घुल", "ghul"],
        ["Wing", "पर", "par"],
        ["Feather", "पंख", "paṅkh"],
        ["Beak", "चुंज", "cuṅj"],
    ],
    615: [
        ["Ant", "पोलो", "polo"],
        ["Bee", "मुं", "muṅ"],
        ["Fly", "मक्ख", "makkha"],
        ["Mosquito", "मैसे", "maise"],
        ["Butterfly", "पोथो", "potho"],
        ["Spider", "माको", "māko"],
        ["Cockroach", "तिलको", "tilko"],
        ["Worm", "कीड़", "kīṛ"],
        ["Louse", "जूं", "jūṅ"],
        ["Bedbug", "खटमल", "khaṭmal"],
        ["Termite", "दिमा", "dimā"],
        ["Grasshopper", "फिडिं", "phiḍiṅ"],
        ["Beetle", "भुंड", "bhuṇḍ"],
        ["Scorpion", "बिच्छु", "bicchu"],
        ["Centipede", "खनखजुरा", "khanakhajurā"],
        ["Leech", "जोंक", "joṅk"],
        ["Honey", "मद", "mad"],
        ["Hive", "छत्ता", "chattā"],
        ["Bite (insect)", "काट", "kāṭ"],
        ["Poisonous", "जहरि", "jahari"],
    ],
    616: [
        ["Red", "गिबि", "gibi"],
        ["Blue", "नेला", "nelā"],
        ["Green", "हाब", "hāb"],
        ["Yellow", "हें", "heṅ"],
        ["White", "फोर", "phor"],
        ["Black", "गोलो", "golo"],
        ["Brown", "धुंसा", "dhuṅsā"],
        ["Orange (colour)", "नारंगि", "nāraṅgi"],
        ["Pink", "गुलाबि", "gulābi"],
        ["Purple", "बैंगनि", "baiṅgni"],
        ["Grey", "स्लेटि", "sleṭi"],
        ["Golden", "सुनहर", "sunahar"],
        ["Silver", "रूपि", "rūpi"],
        ["Dark", "गहरा", "gaharā"],
        ["Light (colour)", "हल्का", "halkā"],
        ["Bright", "चमकदार", "camakadār"],
        ["Pale", "फिक्का", "fikkā"],
        ["Colourful", "रंगदार", "raṅgadār"],
        ["Stain", "दाग", "dāg"],
        ["Dye", "रंग", "raṅ"],
    ],
    617: [
        ["Rose", "गुलाब", "gulāb"],
        ["Marigold", "गेंदा", "geṅdā"],
        ["Jasmine", "जुंफुर", "juṅphur"],
        ["Lotus", "कमल", "kamal"],
        ["Sunflower", "सुरमुखि", "surmukhi"],
        ["Hibiscus", "जबा", "jabā"],
        ["Champa", "चंपा", "campā"],
        ["Lily", "लिलि", "lili"],
        ["Tulip (loan)", "ट्युलिप", "ṭyulip"],
        ["Bouquet", "गुलदस्ता", "guldastā"],
        ["Petals", "पंखुड़ि", "paṅkhuṛi"],
        ["Thorn", "कांटा", "kā̃ṭā"],
        ["Fragrance", "महक", "mahak"],
        ["Garden", "बाग", "bāg"],
        ["Flower bed", "फूलनि क्यारि", "phūlani kyāri"],
        ["Wild flower", "जंगलि फूल", "jaṅgali phūl"],
        ["To bloom", "फुल", "phul"],
        ["Withered", "मुरजाय", "murajāy"],
        ["Pollen", "पराग", "parāg"],
    ],
    618: [
        ["Dog", "कुथि", "kuthi"],
        ["Cat", "बिलाइ", "bilāi"],
        ["Cow", "गो", "go"],
        ["Buffalo", "मैस", "mais"],
        ["Goat", "सोल", "sol"],
        ["Sheep", "भेड", "bheḍ"],
        ["Horse", "गोरा", "gorā"],
        ["Donkey", "गाध", "gādh"],
        ["Elephant", "हाथि", "hāthi"],
        ["Lion", "सिंह", "siṅh"],
        ["Tiger", "बाघ", "bāgh"],
        ["Monkey", "बन्दर", "baṅdar"],
        ["Rabbit", "खरगोस", "khargos"],
        ["Camel", "ऊंट", "ūṅṭ"],
        ["Bear", "भलुक", "bhaluk"],
        ["Deer", "हरिन", "harin"],
        ["Squirrel", "गिलहरि", "gilahari"],
        ["Rat", "डाह", "ḍāh"],
        ["Ox", "बैल", "bail"],
        ["Pig", "दुं", "duṅ"],
    ],
    619: [
        ["Friend", "दोस्त", "dost"],
        ["Guest", "मेहमान", "mehmān"],
        ["Neighbour", "गाह्रि गोर", "gāhri gor"],
        ["Money", "पैसा", "paisā"],
        ["Work", "काम", "kām"],
        ["Time", "सम", "sam"],
        ["News", "खबर", "khabar"],
        ["Problem", "मुसिबत", "musibat"],
        ["Help", "मदद", "madad"],
        ["Love", "मोजां", "mojāṅ"],
        ["Anger", "रिसा", "risā"],
        ["Peace", "समदि", "samadi"],
        ["Luck", "नसिब", "nasib"],
        ["Pain", "दुख", "dukh"],
        ["Joy", "खुशि", "khusi"],
        ["Fear", "डर", "ḍar"],
        ["Hope", "उमेद", "umed"],
        ["Idea", "सोंनाय", "soṅnāy"],
        ["Chance", "मौका", "maukā"],
        ["Result", "नतिजा", "natijā"],
    ],
}
