# Bodo Lesson 3 — chunk A (chapter IDs 543–565). Rows: English, Bodo (Devanagari), Transliteration.

LESSONS_S3A = {
    543: [
        ["I am going to eat now", "आँ दा जा ला दों", "āṅ dā jā lā doṅ"],
        ["She is going to read", "बि पद ला दिं", "bi pad lā diṅ"],
        ["We are going to Kokrajhar tomorrow", "जिंग गाब्ला कोक्राझार तों ला दों", "jiṅ gāblā kokrājhār toṅ lā doṅ"],
        ["He is going to call you", "बो नेंफांनि फोन ला दिं", "bo nenphāṅni fon lā diṅ"],
        ["They are going to leave", "बिफां चल ला दिं", "biphāṅ cal lā diṅ"],
        ["It is going to rain today", "दिनि दै थां ला दं", "dini dai thāṅ lā dong"],
        ["I am going to try my best", "आँ गोथो कोशिश ला दों", "āṅ gotho kōśiś lā doṅ"],
        ["Are you going to come?", "नेंथां विन ला दिं नामा?", "nenthāṅ vin lā diṅ nāmā?"],
        ["What are you going to do?", "नों मा दा ला दिं?", "noṅ mā dā lā diṅ?"],
        ["I am going to sleep early", "आँ दैखो सा ला दों", "āṅ daikho sā lā doṅ"],
        ["The bus is going to start", "बस चल ला दं", "bas cal lā dong"],
        ["I am going to buy vegetables", "आँ सब्जि खरिद ला दों", "āṅ sabji kharid lā doṅ"],
        ["She is going to cook rice", "बि मै रांद ला दिं", "bi mai rānd lā diṅ"],
        ["We are going to meet at the temple", "जिंग थांसोलि मोन ला दों", "jiṅ thāṃsoli mon lā doṅ"],
        ["He is not going to tell lies", "बो मिथिखौ नङा बोल ला दिं", "bo mithikhau naṅā bol lā diṅ"],
        ["I am going to learn Bodo", "आँ बोडो सिम ला दों", "āṅ boḍo sim lā doṅ"],
        ["Nothing is going to change", "गोथो नङा बदल ला दं", "gotho naṅā badal lā dong"],
    ],
    544: [
        ["I used to play in this street", "आँ निं गलि खेल दंगो", "āṅ nin gali khel daṅgo"],
        ["He used to walk every morning", "बो हर फुंनि चल दंगो", "bo har phuṅni cal daṅgo"],
        ["We used to live in the village", "जिंग गाउ थां दंगो", "jiṅ gāu thāṅ daṅgo"],
        ["She used to sing well", "बि गोजोन गान दंगो", "bi gojon gān daṅgo"],
        ["They used to visit us often", "बिफां जिंनि मोन दंगो", "biphāṅ jiṅni mon daṅgo"],
        ["I used to fear the dark", "आँ अंधार डर दंगो", "āṅ andhār ḍar daṅgo"],
        ["Mother used to wake up early", "आमा दैखो उठ दंगो", "āmā daikho uṭh daṅgo"],
        ["He used to work in the fields", "बो खेताव काम दंगो", "bo khetāw kām daṅgo"],
        ["We used to eat together", "जिंग गोथो जा दंगो", "jiṅ gotho jā daṅgo"],
        ["It used to be very cold here", "दा बाहागो थंड दंगो", "dā bāhāgo thaṇḍ daṅgo"],
        ["I used to read the newspaper", "आँ खबर पद दंगो", "āṅ khabar pad daṅgo"],
        ["You used to help everyone (informal)", "नों गोथोनि मदद दंगो", "noṅ gothoni madad daṅgo"],
        ["The shop used to open late", "दुकान देरै खोल दंगो", "dukān derai khol daṅgo"],
        ["Children used to play outside", "सोरफोर बाहिर खेल दंगो", "sorphor bāhir khel daṅgo"],
        ["I used to go by bus", "आँ बस सों तों दंगो", "āṅ bas soṅ toṅ daṅgo"],
        ["Grandfather used to tell stories", "आगो कथि बोल दंगो", "āgo kathi bol daṅgo"],
        ["We used to bathe in the river", "जिंग दरियाव नुं दंगो", "jiṅ dariyāw nuṅ daṅgo"],
    ],
    545: [
        ["Long ago I used to study here", "लाम आँ दा पद दंगो", "lām āṅ dā pad daṅgo"],
        ["In those days he used to travel on foot", "दा बो पैदल तों दंगो", "dā bo paidal toṅ daṅgo"],
        ["People used to respect elders more", "मानसिफोर गोथो मान ला दंगो", "mānasi-phor gotho mān lā daṅgo"],
        ["We used to sit under this tree", "जिंग निं गोजो थालाव बैठ दंगो", "jiṅ nin gojo thālāw baiṭh daṅgo"],
        ["The fair used to come every year", "मेला हर बोसोर विन दंगो", "melā har bosor vin daṅgo"],
        ["I used to fear exams", "आँ परीक्षा डर दंगो", "āṅ parīkṣā ḍar daṅgo"],
        ["She used to wear a white suit", "बि सफेद कपड़ पिन दंगो", "bi safed kapaṛ pin daṅgo"],
        ["They used to farm this land", "बिफां निं जमिन जोत दंगो", "biphāṅ nin jamin jot daṅgo"],
        ["Winter used to be harsher", "थंड बाहागो सख्त दंगो", "thaṇḍ bāhāgo sakhat daṅgo"],
        ["I used to know him since childhood", "आँ सोरनिफ्राय बिनि मोन दंगो", "āṅ soraniphrāy bini mon daṅgo"],
        ["We used to fetch water from the well", "जिंग कुइ निफ्राय दै ला दंगो", "jiṅ kui niphrāy dai lā daṅgo"],
        ["The teacher used to be strict", "मास्तार सख्त दंगो", "māstār sakhat daṅgo"],
        ["I used to listen to the radio", "आँ रेडियो नुंथ दंगो", "āṅ reḍiyo nunth daṅgo"],
        ["Villages used to be quieter", "गाउ थांथि दंगो", "gāu thāṃthi daṅgo"],
        ["He used to return before sunset", "बो सुर डुब सों फिन दंगो", "bo sur ḍub soṅ phin daṅgo"],
        ["We used to share one room", "जिंग गोथो रुम थां दंगो", "jiṅ gotho rum thāṅ daṅgo"],
        ["Food used to taste different then", "दा खाम गोथो स्वाद दंगो", "dā khām gotho svād daṅgo"],
    ],
    546: [
        ["If it rains, I will stay home", "जे दै थां आँ गोर थांगो", "je dai thāṅ āṅ gor thāṅgo"],
        ["If you come, we will go together", "जे नों विन जिंग गोथो तोंगो", "je noṅ vin jiṅ gotho toṅgo"],
        ["If he studies, he will pass", "जे बो पद पास ला दिं", "je bo pad pās lā diṅ"],
        ["If you are tired, rest", "जे नों थाक आराम हो", "je noṅ thāk āram ho"],
        ["If she calls, tell her I am busy", "जे बि फोन ला आँ ब्यस्त दं", "je bi fon lā āṅ byast dong"],
        ["If we leave now, we will be on time", "जे जिंग दा चल वक्ताव फैगो", "je jiṅ dā cal vaktāw phaigo"],
        ["If the bus is late, take a taxi", "जे बस देर टैक्सी ला", "je bas der ṭaiksī lā"],
        ["If you need help, ask me", "जे मदद ला आँनि बोल", "je madad lā āṅni bol"],
        ["If I had money, I would buy a house", "जे आँनि पैसा गोर खरिद ला दों", "je āṅni paisā gor kharid lā doṅ"],
        ["If they agree, start the work", "जे बिफां राजि काम सुरु हो", "je biphāṅ rāji kām suru ho"],
        ["If you eat too much, you will feel ill", "जे नों बाहागो जा बिमार ला दिं", "je noṅ bāhāgo jā bimār lā diṅ"],
        ["If the road is bad, drive slowly", "जे रस्ता खराब हौले चल", "je rastā kharāb haulai cal"],
        ["If winter comes, wear warm clothes", "जे थंड गरम कपड़ पिन", "je thaṇḍ garam kapaṛ pin"],
        ["If you lie, nobody will trust you", "जे नों मिथिखौ बोल गोथो भरोसा नङा", "je noṅ mithikhau bol gotho bharosā naṅā"],
        ["If I see him, I will inform you", "जे आँ बिनि नेउ नेंफांनि बोलगो", "je āṅ bini neu nenphāṅni bolgo"],
        ["If the shop is closed, come tomorrow", "जे दुकान बन्द गाब्ला विन", "je dukān band gāblā vin"],
        ["If we work hard, we will succeed", "जे जिंग मेहनत सफल होगो", "je jiṅ mehnat safal hogo"],
    ],
    547: [
        ["I am waiting for you", "आँ नोंनि थां दों", "āṅ noṅni thāṅ doṅ"],
        ["She depends on her parents", "बि बिनि बाफा-आमानि सों दं", "bi bini bāphā-āmāni soṅ dong"],
        ["Listen to the teacher", "मास्तारनि नुंथ", "māstārani nunth"],
        ["He laughed at the joke", "बो चुटकुलि हस दं", "bo cuṭkul has dong"],
        ["We believe in hard work", "जिंग मेहनताव भरोसा दों", "jiṅ mehnatāw bharosā doṅ"],
        ["Think about the future", "फिननि गोनोथि सोच", "finani gonothi soca"],
        ["She is angry with her brother", "बि बिनि दानि गुस्सा दं", "bi bini dāni gussā dong"],
        ["I agree with you", "आँ नेंथांनि सों राजि दों", "āṅ nenthāṅni soṅ rāji doṅ"],
        ["They ran towards the gate", "बिफां गेटाव दौड़ दं", "biphāṅ gēṭāw dauṛ dong"],
        ["Sit on this chair", "निं कुर्सीाव बैठ", "nin kursīāw baiṭh"],
        ["The cat hid under the bed", "बिलाइ बिस्तर थालाव लुक दं", "bilāi bistar thālāw luk dong"],
        ["Put the book on the table", "पुस्तक मेजाव राख", "pustak mejāw rākh"],
        ["He jumped into the water", "बो दैाव कूद दं", "bo daiāw kūd dong"],
        ["We walked along the river", "जिंग दरिया गाह्रि चल दं", "jiṅ dariyā gāhri cal dong"],
        ["She looked at the sky", "बि आकाश नेउ दं", "bi ākāś neu dong"],
        ["I am thinking of home", "आँ गोरनि सोच दों", "āṅ gorani soc doṅ"],
        ["They spoke about the plan", "बिफां योजनानि बोल दं", "biphāṅ yojanān bol dong"],
    ],
    548: [
        ["This is a big house", "निं बाहागो गोर दं", "nin bāhāgo gor dong"],
        ["That is a small room", "उं हिलो रुम दं", "uṅ hilo rum dong"],
        ["She is a good teacher", "बि गोजोन मास्तार दं", "bi gojon māstār dong"],
        ["The water is cold", "दै थंड दं", "dai thaṇḍ dong"],
        ["The tea is very sweet", "चा बाहागो मिथा दं", "cā bāhāgo mithā dong"],
        ["He is taller than his brother", "बो बिनि दानि दैङर दं", "bo bini dānai daiṅar dong"],
        ["This road is dangerous", "निं रस्ता खतरनाक दं", "nin rastā khatarnāk dong"],
        ["The sky is clear today", "दिनि आकाश साफ दं", "dini ākāś sāph dong"],
        ["Her voice is soft", "बिनि आवाज नर्म दं", "bini āvāj narm dong"],
        ["The fruit is ripe", "फल पाक दं", "phal pāk dong"],
        ["We are ready to go", "जिंग तोंनि तैयार दों", "jiṅ toṅni taiyār doṅ"],
        ["The child is afraid", "सोर डर दं", "sor ḍar dong"],
        ["This book is interesting", "निं पुस्तक दिलचस्प दं", "nin pustak dilcaspa dong"],
        ["The milk is sour", "दूध खट्टा दं", "dūdh khaṭṭā dong"],
        ["He looks tired", "बो थाक नेउ दं", "bo thāk neu dong"],
        ["The fields are green", "खेत हरा दं", "khet harā dong"],
        ["Your idea is useful", "नोंनि बिचार काम दं", "noṅni bicār kām dong"],
    ],
    549: [
        ["I can swim", "आँ तैर ला दों", "āṅ tair lā doṅ"],
        ["Can you help me?", "नों आँनि मदद ला दिं नामा?", "noṅ āṅni madad lā diṅ nāmā?"],
        ["He cannot come today", "बो दिनि विन नङा", "bo dini vin naṅā"],
        ["She can sing very well", "बि बाहागो गान ला दिं", "bi bāhāgo gān lā diṅ"],
        ["We can finish this work", "जिंग निं काम फोर ला दों", "jiṅ nin kām phor lā doṅ"],
        ["Can I sit here?", "आँ दा बैठ ला दों नामा?", "āṅ dā baiṭh lā doṅ nāmā?"],
        ["They can understand Bodo", "बिफां बोडो मोन ला दिं", "biphāṅ boḍo mon lā diṅ"],
        ["I could not sleep", "आँ सा नङा दं", "āṅ sā naṅā dong"],
        ["You will be able to drive soon", "नों दैखो गाडि चल ला दिं", "noṅ daikho gāḍi cal lā diṅ"],
        ["Nobody could open the lock", "गोथो ताला खोल नङा", "gotho tālā khol naṅā"],
        ["Can she cook without help?", "बि मदद नङै रांद ला दिं नामा?", "bi madad naṅai rānd lā diṅ nāmā?"],
        ["I can try once more", "आँ फिन गोथो कोशिश ला दों", "āṅ phin gotho kōśiś lā doṅ"],
        ["He can lift this box", "बो निं डिब्बा चुक ला दिं", "bo nin ḍibbā cuk lā diṅ"],
        ["We could not find the way", "जिंग रस्ता लाब नङा दं", "jiṅ rastā lāb naṅā dong"],
        ["Can you repeat that?", "नों फिन बोल ला दिं नामा?", "noṅ phin bol lā diṅ nāmā?"],
        ["The child can already read", "सोर पद ला दं", "sor pad lā dong"],
        ["I cannot forget that day", "आँ उं दिन गोम नङा", "āṅ uṅ din gom naṅā"],
    ],
    550: [
        ["I want water", "आँनि दै ला दों", "āṅni dai lā doṅ"],
        ["I need rest today", "आँनि दिनि आराम ला दों", "āṅni dini āram lā doṅ"],
        ["She wants to study abroad", "बि बाहिर सिम ला दिं", "bi bāhir sim lā diṅ"],
        ["We need your permission", "जिंग नोंनि इजाजत ला दों", "jiṅ noṅni ijāzat lā doṅ"],
        ["He does not want to fight", "बो लडाइ नङा ला दिं", "bo laḍāi naṅā lā diṅ"],
        ["Do you want tea?", "नोंनि चा ला दिं नामा?", "noṅni cā lā diṅ nāmā?"],
        ["I need a little time", "आँनि हिलो सम ला दों", "āṅni hilo sam lā doṅ"],
        ["They want to meet tomorrow", "बिफां गाब्ला मोन ला दिं", "biphāṅ gāblā mon lā diṅ"],
        ["The plant needs water", "पौधानि दै ला दं", "paudhāni dai lā dong"],
        ["I want to learn music", "आँ संगीत सिम ला दों", "āṅ saṅgīt sim lā doṅ"],
        ["She needs medicine", "बिनि दवाइ ला दिं", "bini davāi lā diṅ"],
        ["We do not want trouble", "जिंग समस्या नङा ला दों", "jiṅ samasyā naṅā lā doṅ"],
        ["He wants a new bicycle", "बो गोदान साइकल ला दिं", "bo godān sāikal lā diṅ"],
        ["I need your advice", "आँनि नोंनि सलाह ला दों", "āṅni noṅni salāh lā doṅ"],
        ["Do they want rice or bread?", "बिफां मै न रोटि ला दिं नामा?", "biphāṅ mai na roṭi lā diṅ nāmā?"],
        ["The child wants to play", "सोर खेल ला दं", "sor khel lā dong"],
        ["I want peace in the house", "आँनि गोराव थांथि ला दों", "āṅni gorāw thāṃthi lā doṅ"],
    ],
    551: [
        ["It will become cold at night", "राति थंड होगो", "rāti thaṇḍ hogo"],
        ["He became a doctor", "बो डाक्टर हो दं", "bo ḍākṭar ho dong"],
        ["What happened yesterday?", "मैया मा हो दं?", "maiyā mā ho dong?"],
        ["The milk turned sour", "दूध खट्टा हो दं", "dūdh khaṭṭā ho dong"],
        ["She became famous", "बि मशहूर हो दं", "bi mashhūr ho dong"],
        ["Don't become lazy", "आलसि नङा हो", "ālasi naṅā ho"],
        ["The sky became cloudy", "आकाश मेग हो दं", "ākāś mega ho dong"],
        ["We became friends", "जिंग दोस्त हो दं", "jiṅ dost ho dong"],
        ["It happens every day", "हर दिन हो दं", "har din ho dong"],
        ["The child became quiet", "सोर थांथि हो दं", "sor thāṃthi ho dong"],
        ["Things will become easier", "गोथो आसान होगो", "gotho āsān hogo"],
        ["He became angry suddenly", "बो अचानक गुस्सा हो दं", "bo acānak gussā ho dong"],
        ["Winter is coming; leaves will fall", "थंड आ दं; पात झरगो", "thaṇḍ ā dong; pāt jharago"],
        ["She wants to become a teacher", "बि मास्तार हो ला दिं", "bi māstār ho lā diṅ"],
        ["Nothing happened without reason", "गोथो मोन नङै हो नङा", "gotho mon naṅai ho naṅā"],
        ["The road became muddy", "रस्ता कीचड़ हो दं", "rastā kīcaṛ ho dong"],
        ["He became old but stayed kind", "बो बुजुर्ग हो गोजोन दं", "bo bujurg ho gojon dong"],
    ],
    552: [
        ["You should rest now", "नों दा आराम ला दिं", "noṅ dā āram lā diṅ"],
        ["We should help the poor", "जिंग गरिबफोरनि मदद ला दों", "jiṅ garibphorni madad lā doṅ"],
        ["He should tell the truth", "बो सोलों बोल ला दिं", "bo soloṅ bol lā diṅ"],
        ["Children should respect elders", "सोरफोर गोथो मानसिफोरनि मान ला दिं", "sorphor gotho mānasi-phorni mān lā diṅ"],
        ["You should not waste food", "नों खाम नङा गोम ला दिं", "noṅ khām naṅā gom lā diṅ"],
        ["I should leave early tomorrow", "आँ गाब्ला दैखो चल ला दों", "āṅ gāblā daikho cal lā doṅ"],
        ["She should see a doctor", "बि डाक्टराव विन ला दिं", "bi ḍākṭarāw vin lā diṅ"],
        ["We should save water", "जिंग दै बच ला दों", "jiṅ dai bac lā doṅ"],
        ["They should apologize", "बिफां माफि माग ला दिं", "biphāṅ māphi māg lā diṅ"],
        ["You should wear a helmet", "नों हेलमेट पिन ला दिं", "noṅ helmeṭ pin lā diṅ"],
        ["One should speak softly", "हौलै लैब ला दं", "haulai laib lā dong"],
        ["We should not spread rumours", "जिंग अफवा नङा फैल ला दों", "jiṅ aphavā naṅā phail lā doṅ"],
        ["He should finish his homework", "बो गोरनि काम फोर ला दिं", "bo gorani kām phor lā diṅ"],
        ["You should call before coming", "विन सों फिन फोन ला दिं", "vin soṅ phin fon lā diṅ"],
        ["I should have told you earlier", "आँ नोंनि लाम बोल ला दं", "āṅ noṅni lām bol lā dong"],
    ],
    553: [
        ["I must go now", "आँ दा तों ला दों", "āṅ dā toṅ lā doṅ"],
        ["You must bring your ID", "नों आँनि पहचान पत्र ला दिं", "noṅ āṅni pahcān patra lā diṅ"],
        ["We must obey the rules", "जिंग नियम मान ला दों", "jiṅ niyam mān lā doṅ"],
        ["She must take medicine on time", "बि वक्ताव दवाइ ला दिं", "bi vaktāw davāi lā diṅ"],
        ["They must report to the office", "बिफां ऑफिसाव रिपोर्ट ला दिं", "biphāṅ ophīsāw riporṭ lā diṅ"],
        ["The form must be filled", "फर्म भर ला दं", "pharm bhar lā dong"],
        ["I must not be late", "आँ देर नङा दों", "āṅ der naṅā doṅ"],
        ["You must tell the truth in court", "नों कोर्टाव सोलों बोल ला दिं", "noṅ korṭāw soloṅ bol lā diṅ"],
        ["We must save electricity", "जिंग बिजली बच ला दों", "jiṅ bijlī bac lā doṅ"],
        ["He must pay the fine", "बो जुर्माना हो ला दिं", "bo jurmānā ho lā diṅ"],
        ["Students must attend class", "विद्यार्थिफोर क्लास ला दिं", "vidyārthiphor klās lā diṅ"],
        ["I must call my mother", "आँ आमानि फोन ला दों", "āṅ āmāni fon lā doṅ"],
        ["You must not skip breakfast", "नों नास्ता नङा छाड ला दिं", "noṅ nāstā naṅā chāḍ lā diṅ"],
        ["We must leave before dark", "जिंग अंधार सों चल ला दों", "jiṅ andhār soṅ cal lā doṅ"],
        ["The door must be locked", "दरवाजा बन्द ला दं", "daravājā band lā dong"],
        ["I must finish this today", "आँ दिनि निं फोर ला दों", "āṅ dini nin phor lā doṅ"],
    ],
    554: [
        ["He keeps talking", "बो लगातार लैब दिं", "bo lagātār laib diṅ"],
        ["She keeps forgetting", "बि लगातार गोम दिं", "bi lagātār gom diṅ"],
        ["The baby keeps crying", "सोनोसो लगातार रो दिं", "sonoso lagātār ro diṅ"],
        ["They keep asking questions", "बिफां सोंनाय ला दिं", "biphāṅ soṃnāy lā diṅ"],
        ["I keep thinking of you", "आँ नोंनि सोच दों", "āṅ noṅni soc doṅ"],
        ["The phone keeps ringing", "फोन लगातार बज दिं", "fon lagātār baj diṅ"],
        ["It keeps raining", "दै लगातार थां दिं", "dai lagātār thāṅ diṅ"],
        ["We keep trying", "जिंग कोशिश ला दों", "jiṅ kōśiś lā doṅ"],
        ["Don't keep arguing", "लगातार लडाइ नङा", "lagātār laḍāi naṅā"],
        ["He keeps changing his mind", "बो बिनि मोन बदल दिं", "bo bini mon badal diṅ"],
        ["She keeps the house clean", "बि गोर साफ राख दिं", "bi gor sāph rākh diṅ"],
        ["The fan keeps making noise", "पंखा शोर ला दिं", "paṅkhā śor lā diṅ"],
        ["I keep telling you the same thing", "आँ गोथो गोथो बोल दों", "āṅ gotho gotho bol doṅ"],
        ["They keep postponing the meeting", "बिफां मिटिंग टाल दिं", "biphāṅ miṭiṅg ṭāl diṅ"],
        ["Water keeps dripping", "दै टप टप दिं", "dai ṭap ṭap diṅ"],
        ["You keep improving", "नों लगातार सुधर दिं", "noṅ lagātār sudhar diṅ"],
    ],
    555: [
        ["This tree is taller than that one", "निं गोजो उं खोमा दैङर दं", "nin gojo uṅ khomā daiṅar dong"],
        ["She is the best singer here", "बि दा गोबो गायिका दं", "bi dā gobo gāyikā dong"],
        ["This road is shorter", "निं रस्ता हिलो दं", "nin rastā hilo dong"],
        ["He runs faster than me", "बो आँ खोमा दैखो दौड़ दिं", "bo āṅ khomā daikho dauṛ diṅ"],
        ["This book is more useful", "निं पुस्तक बाहागो काम दं", "nin pustak bāhāgo kām dong"],
        ["Winter is colder this year", "ए बोसोर थंड बाहागो सख्त दं", "e bosor thaṇḍ bāhāgo sakhat dong"],
        ["She speaks more politely", "बि बाहागो हौलै लैब दिं", "bi bāhāgo haulai laib diṅ"],
        ["This is the biggest market", "निं गोबो बाजार दं", "nin gobo bājār dong"],
        ["My house is nearer", "आँनि गोर गाह्रि दं", "āṅni gor gāhri dong"],
        ["He is as wise as his father", "बो बिनि बाफा सम मोन दं", "bo bini bāphā sam mon dong"],
        ["This sweet is sweeter than that", "निं मिथाइ उं खोमा बाहागो मिथा दं", "nin mithāi uṅ khomā bāhāgo mithā dong"],
        ["The second question is harder", "नेइ सोंनाय गोथो खोमा दं", "nei soṃnāy gotho khomā dong"],
        ["She is younger than her sister", "बि बिनि बहन खोमा हिलो दं", "bi bini bahan khomā hilo dong"],
        ["This cloth is softer", "निं कपड़ नर्म दं", "nin kapaṛ narm dong"],
        ["He earns less than before", "बो मैया सों कट काम दिं", "bo maiyā soṅ kaṭ kām diṅ"],
        ["This path is safer at day", "निं रस्ता दिनि सुरक्षित दं", "nin rastā dini surakṣit dong"],
    ],
    556: [
        ["I know this boy", "आँ निं मुसानि मोन दों", "āṅ nin musāni mon doṅ"],
        ["Do you know her name?", "नों बिनि मुं मोन दिं नामा?", "noṅ bini muṅ mon diṅ nāmā?"],
        ["He knows how to drive", "बो गाडि चलाय मोन दिं", "bo gāḍi calāy mon diṅ"],
        ["I don't know the answer", "आँ जवाब मोन नङा", "āṅ javāb mon naṅā"],
        ["We know the truth", "जिंग सोलों मोन दों", "jiṅ soloṅ mon doṅ"],
        ["She knows three languages", "बि तिनि भाषा मोन दिं", "bi tini bhāṣā mon diṅ"],
        ["Nobody knows what will happen", "गोथो मा होगो मोन नङा", "gotho mā hogo mon naṅā"],
        ["I knew him from school", "आँ बिनि इस्कुल निफ्राय मोन दं", "āṅ bini iskul niphrāy mon dong"],
        ["You should know your duty", "नों आँनि काम मोन ला दिं", "noṅ āṅni kām mon lā diṅ"],
        ["Let me know when you arrive", "नों फै विन आँनि बोल", "noṅ phai vin āṅni bol"],
        ["I want to know the reason", "आँ मोन ला दों", "āṅ mon lā doṅ"],
        ["Does he know cooking?", "बो रांद मोन दिं नामा?", "bo rānd mon diṅ nāmā?"],
        ["We knew they would come", "जिंग बिफां विनगो मोन दं", "jiṅ biphāṅ vingo mon dong"],
        ["I know it by heart", "आँ याद कोल मोन दों", "āṅ yād kol mon doṅ"],
        ["She knows the way to the temple", "बि थांसोलि रस्ता मोन दिं", "bi thāṃsoli rastā mon diṅ"],
        ["How do you know?", "नों मोन माबा दिं?", "noṅ mon mābā diṅ?"],
        ["They know nothing about it", "बिफां निं बारे गोथो मोन नङा", "biphāṅ nin bāre gotho mon naṅā"],
    ],
    557: [
        ["Let him speak", "बो लैब ला", "bo laib lā"],
        ["Let us go now", "जिंग दा तों", "jiṅ dā toṅ"],
        ["Let her rest", "बि आराम ला", "bi āram lā"],
        ["Let's eat together", "जिंग गोथो जा", "jiṅ gotho jā"],
        ["Let the children play", "सोरफोर खेल ला", "sorphor khel lā"],
        ["Shall we start?", "जिंग सुरु ला नामा?", "jiṅ suru lā nāmā?"],
        ["Shall I open the door?", "आँ दरवाजा खोल ला नामा?", "āṅ daravājā khol lā nāmā?"],
        ["Let's wait five minutes", "जिंग पाँच मिनट थां", "jiṅ pā̃c minaṭ thāṅ"],
        ["Don't let him go alone", "बो गोथो नङा तों", "bo gotho naṅā toṅ"],
        ["Let the water boil", "दै उबल ला", "dai ubal lā"],
        ["Shall we meet tomorrow?", "जिंग गाब्ला मोन ला नामा?", "jiṅ gāblā mon lā nāmā?"],
        ["Let me try once", "आँ गोथो कोशिश ला", "āṅ gotho kōśiś lā"],
        ["Let's take a photo", "जिंग फोटो ला", "jiṅ phoṭo lā"],
        ["Let them decide", "बिफां फैसला ला", "biphāṅ phaislā lā"],
        ["Shall we walk?", "जिंग पैदल चल ला नामा?", "jiṅ paidal cal lā nāmā?"],
        ["Let it be; don't worry", "थां दं; फिकर नङा", "thāṅ dong; phikar naṅā"],
    ],
    558: [
        ["The book that I bought is good", "आँ खरिद पुस्तक गोजोन दं", "āṅ kharid pustak gojon dong"],
        ["The man who came is my uncle", "विन मोथाइ आँनि काका दं", "vin mothāi āṅni kākā dong"],
        ["What you said is true", "नों बोलखौ सोलों दं", "noṅ bolkhau soloṅ dong"],
        ["I know where he lives", "आँ बो मोन थां दिं मोन दों", "āṅ bo mon thāṅ diṅ mon doṅ"],
        ["Tell me which bus goes to Kokrajhar", "मा बस कोक्राझार तों दिं बोल", "mā bas kokrājhār toṅ diṅ bol"],
        ["That is the house that I want", "उं गोर आँ ला दं", "uṅ gor āṅ lā dong"],
        ["The girl whose bag this is stood up", "मुसु बिनि बेग निं खड़ हो दं", "musu bini beg nin khaṛ ho dong"],
        ["I forgot what he asked", "आँ बिनि मा सोंनाय गोम दं", "āṅ bini mā soṃnāy gom dong"],
        ["Show me what you wrote", "नों लिरखौ नेउ", "noṅ lirkhau neu"],
        ["This is the road that leads to the temple", "निं रस्ता थांसोलि तों दं", "nin rastā thāṃsoli toṅ dong"],
        ["I like the song that she sang", "आँ बिनि गीत ला दं", "āṅ bini gīt lā dong"],
        ["Whoever comes, welcome them", "जो विन स्वागत हो", "jo vin svāgat ho"],
        ["Whatever happens, stay calm", "जो हो थांथि थां", "jo ho thāṃthi thāṅ"],
        ["The reason why he left is unclear", "बो माबा चल जा दं साफ नङा", "bo mābā cal jā dong sāph naṅā"],
        ["That is not what I meant", "उं आँ बोलखौ नङा", "uṅ āṅ bolkhau naṅā"],
        ["Tell me when you will come", "मोन विनगो बोल", "mon vingo bol"],
    ],
    559: [
        ["Please read the notice carefully", "थांखाय नोटिस ध्यानै पद", "thāṅkhāy noṭis dhyānai pad"],
        ["Kindly submit the form by Friday", "थांखाय फर्म शुक्रवार सों हो", "thāṅkhāy pharm śukravār soṅ ho"],
        ["Employees must wear ID cards", "कर्मचारिफोर आइडि कार्ड पिन ला दिं", "karmacāriphor āiḍi kārḍ pin lā diṅ"],
        ["Do not use mobile phones here", "दा मोबाइल नङा बाहागो", "dā mobāil naṅā bāhāgo"],
        ["Please maintain silence in the library", "लाइब्रेरिआव थांथि थां", "lāibrerīāw thāṃthi thāṅ"],
        ["Visitors should register at the gate", "मुलाकातिफोर गेटाव नां लिर", "mulākātiphor gēṭāw nā̃ lir"],
        ["Follow the safety instructions", "सुरक्षा हिदायत मान", "surakṣā hidāyat mān"],
        ["Please queue in a line", "थांखाय लाइनाव लाग", "thāṅkhāy laināw lāg"],
        ["Do not touch the exhibits", "प्रदर्शनि नङा छु", "pradarśani naṅā chu"],
        ["Report any suspicious bag", "संदेह डिब्बानि खबर हो", "saṃdeh ḍibbāni khabar ho"],
        ["Please switch off lights when leaving", "चल सों बत्ति बन्द हो", "cal soṅ batti band ho"],
        ["Staff must not share passwords", "स्टाफ पासवर्ड शेयर नङा", "sṭāph pāsavarḍ śeyar naṅā"],
        ["Kindly keep the corridor clear", "गलियारा साफ राख", "galiyārā sāph rākh"],
        ["Patients should take tokens before waiting", "मरीज टोकन ला थां", "marīj ṭokan lā thāṅ"],
        ["Please sign here and here", "दा आरो दा साइन हो", "dā āro dā sāin ho"],
        ["Do not smoke on these premises", "दा धुम्रपान नङा", "dā dhumrapān naṅā"],
    ],
    560: [
        ["I like mangoes", "आँनि आम ला दों", "āṅni ām lā doṅ"],
        ["She likes to dance", "बि नाच ला दिं", "bi nāc lā diṅ"],
        ["We like this place", "जिंग निं जायगा ला दों", "jiṅ nin jāyagā lā doṅ"],
        ["Do you like spicy food?", "नों तिखा खाम ला दिं नामा?", "noṅ tikha khām lā diṅ nāmā?"],
        ["He doesn't like crowds", "बो भीड ला नङा दिं", "bo bhīḍ lā naṅā diṅ"],
        ["Children like sweets", "सोरफोर मिथाइ ला दिं", "sorphor mithāi lā diṅ"],
        ["I would like some tea", "आँनि हिलो चा ला दों", "āṅni hilo cā lā doṅ"],
        ["She likes reading novels", "बि नावल पद ला दिं", "bi nāwal pad lā diṅ"],
        ["We like your company", "जिंग नोंनि सों ला दों", "jiṅ noṅni soṅ lā doṅ"],
        ["I don't like lies", "आँ मिथिखौ ला नङा", "āṅ mithikhau lā naṅā"],
        ["He likes cold weather", "बो थंड मौसम ला दिं", "bo thaṇḍ mausam lā diṅ"],
        ["Do you like Bodo films?", "नों बोडो फिल्म ला दिं नामा?", "noṅ boḍo film lā diṅ nāmā?"],
        ["I like walking in the morning", "आँ फुंनि चल ला दों", "āṅ phuṅni cal lā doṅ"],
        ["She likes helping others", "बि गोथो मदद ला दिं", "bi gotho madad lā diṅ"],
        ["We liked the programme", "जिंग प्रोग्राम ला दं", "jiṅ progrām lā dong"],
        ["He would like to meet you", "बो नोंनि मोन ला दिं", "bo noṅni mon lā diṅ"],
    ],
    561: [
        ["I would help if I could", "जे ला दों आँ मदद हो", "je lā doṅ āṅ madad ho"],
        ["Would you like some water?", "नोंनि दै ला दिं नामा?", "noṅni dai lā diṅ nāmā?"],
        ["He would come every Sunday", "बो हर रविवार विन दंगो", "bo har ravivār vin daṅgo"],
        ["We would sit under this tree", "जिंग निं गोजो थालाव बैठ दंगो", "jiṅ nin gojo thālāw baiṭh daṅgo"],
        ["I would read before sleeping", "आँ सा सों पद दंगो", "āṅ sā soṅ pad daṅgo"],
        ["She would sing softly", "बि हौलै गान दंगो", "bi haulai gān daṅgo"],
        ["They would play in the street", "बिफां गलि खेल दंगो", "biphāṅ gali khel daṅgo"],
        ["It would rain in July", "जुलाइ दै थां दंगो", "julāi dai thāṅ daṅgo"],
        ["I would rather walk", "आँ पैदल चल ला दों", "āṅ paidal cal lā doṅ"],
        ["Would you mind closing the door?", "नों दरवाजा बन्द हो नामा?", "noṅ daravājā band ho nāmā?"],
        ["He would never tell lies", "बो कदे मिथिखौ नङा बोल दंगो", "bo kade mithikhau naṅā bol daṅgo"],
        ["We would share our lunch", "जिंग दुपर खाम गोथो दंगो", "jiṅ dupar khām gotho daṅgo"],
        ["Mother would wake up early", "आमा फुंनि उठ दंगो", "āmā phuṅni uṭh daṅgo"],
        ["I would feel scared at night", "आँ राति डर दंगो", "āṅ rāti ḍar daṅgo"],
        ["That would be fine", "उं गोजोन होगो", "uṅ gojon hogo"],
        ["Would they agree?", "बिफां राजि ला नामा?", "biphāṅ rāji lā nāmā?"],
    ],
    562: [
        ["I understand your problem", "आँ नोंनि समस्या मोन दों", "āṅ noṅni samasyā mon doṅ"],
        ["Did you understand the lesson?", "नों सबक मोन दिं नामा?", "noṅ sabak mon diṅ nāmā?"],
        ["I suddenly understood the trick", "आँ अचानक नुस्खा मोन दं", "āṅ acānak nuskha mon dong"],
        ["She does not understand Bodo well", "बि बोडो गोजोन मोन नङा", "bi boḍo gojon mon naṅā"],
        ["Help me understand this map", "निं नक्शा मोनाव मदद हो", "nin nakśā monāw madad ho"],
        ["I came to know the news yesterday", "आँ मैया खबर मोन दं", "āṅ maiyā khabar mon dong"],
        ["How did you come to know?", "नों माबा मोन दं?", "noṅ mābā mon dong?"],
        ["We came to know through TV", "जिंग टिभि निफ्राय मोन दं", "jiṅ ṭibhi niphrāy mon dong"],
        ["He came to know the truth later", "बो बादि सोलों मोन दं", "bo bādi soloṅ mon dong"],
        ["I understand; don't worry", "मोन दं; फिकर नङा", "mon dong; phikar naṅā"],
        ["Little children understand slowly", "हिलो सोर धीरै मोन दिं", "hilo sor dhīrai mon diṅ"],
        ["I could not understand his accent", "आँ बिनि लहजा मोन नङा", "āṅ bini lahajā mon naṅā"],
        ["She understood without words", "बि बिना बोल मोन दं", "bi binā bol mon dong"],
        ["Let me know if you understand", "जे मोन आवे आँनि बोल", "je mon āwe āṅni bol"],
        ["I understand the situation now", "आँ दा हालात मोन दं", "āṅ dā hālāt mon dong"],
        ["They came to know each other at college", "बिफां कलेजाव गोथो मोन दं", "biphāṅ kalejāw gotho mon dong"],
    ],
    563: [
        ["You are coming, aren't you?", "नों विन दिं, नामा?", "noṅ vin diṅ, nāmā?"],
        ["He is at home, isn't he?", "बो गोराव दं, नामा?", "bo gorāw dong, nāmā?"],
        ["She can drive, can't she?", "बि गाडि चल ला दिं, नामा?", "bi gāḍi cal lā diṅ, nāmā?"],
        ["We will go tomorrow, won't we?", "जिंग गाब्ला तोंगो, नामा?", "jiṅ gāblā toṅgo, nāmā?"],
        ["It is cold today, isn't it?", "दिनि थंड दं, नामा?", "dini thaṇḍ dong, nāmā?"],
        ["You don't eat meat, do you?", "नों मास नङा जा दिं, नामा?", "noṅ mās naṅā jā diṅ, nāmā?"],
        ["They haven't come yet, have they?", "बिफां हाय विन नङा, नामा?", "biphāṅ hāy vin naṅā, nāmā?"],
        ["This is your book, isn't it?", "निं नोंनि पुस्तक दं, नामा?", "nin noṅni pustak dong, nāmā?"],
        ["You were there, weren't you?", "नों दा दं, नामा?", "noṅ dā dong, nāmā?"],
        ["Let's go, shall we?", "जिंग तों, नामा?", "jiṅ toṅ, nāmā?"],
        ["He won't agree, will he?", "बो राजि नङागो, नामा?", "bo rāji naṅāgo, nāmā?"],
        ["She likes sweets, doesn't she?", "बिनि मिथाइ ला दिं, नामा?", "bini mithāi lā diṅ, nāmā?"],
        ["You can swim, can't you?", "नों तैर ला दिं, नामा?", "noṅ tair lā diṅ, nāmā?"],
        ["It won't rain, will it?", "दै नङा थांगो, नामा?", "dai naṅā thāṅgo, nāmā?"],
        ["We should leave, shouldn't we?", "जिंग चल ला दों, नामा?", "jiṅ cal lā doṅ, nāmā?"],
        ["He is your brother, isn't he?", "बो नोंनि दा दं, नामा?", "bo noṅni dā dong, nāmā?"],
    ],
    564: [
        ["I remember your name", "आँ नोंनि मुं याद दों", "āṅ noṅni muṅ yād doṅ"],
        ["I forgot where I kept the keys", "आँ चाबि मोन गोम दं", "āṅ cābi mon gom dong"],
        ["Try to remember the date", "तारिख याद राखनि कोशिश हो", "tārikh yād rākhani kōśiś ho"],
        ["I suddenly remembered the promise", "आँ अचानक वादा याद दं", "āṅ acānak vādā yād dong"],
        ["She remembers everything", "बि गोथो याद राख दिं", "bi gotho yād rākh diṅ"],
        ["Do you remember me?", "नों आँनि याद ला दिं नामा?", "noṅ āṅni yād lā diṅ nāmā?"],
        ["I can't remember that word", "आँ उं सब्द याद नङा", "āṅ uṅ sabda yād naṅā"],
        ["We remember our teachers", "जिंग जिंनि मास्तार याद ला दों", "jiṅ jiṅni māstār yād lā doṅ"],
        ["Remember to lock the door", "दरवाजा बन्द याद राख", "daravājā band yād rākh"],
        ["He remembered the way", "बो रस्ता याद दं", "bo rastā yād dong"],
        ["Childhood memories are sweet", "सोरनि याद मिथा दं", "sorani yād mithā dong"],
        ["I will never forget this help", "आँ निं मदद कदे गोम नङागो", "āṅ nin madad kade gom naṅāgo"],
        ["Please remind me tomorrow", "थांखाय गाब्ला आँनि याद हो", "thāṅkhāy gāblā āṅni yād ho"],
        ["She forgot to bring the file", "बि फाइल ला गोम दं", "bi phāil lā gom dong"],
        ["I remember seeing him here", "आँ बिनि दा नेउ याद दं", "āṅ bini dā neu yād dong"],
        ["Memories fade with time", "याद सम सों फिक दिं", "yād sam soṅ phik diṅ"],
    ],
    565: [
        ["I want to go home", "आँ गोर तों ला दों", "āṅ gor toṅ lā doṅ"],
        ["She wants to sleep early", "बि दैखो सा ला दिं", "bi daikho sā lā diṅ"],
        ["We want to watch the match", "जिंग मेच नेउ ला दों", "jiṅ mec neu lā doṅ"],
        ["He wants to buy a phone", "बो फोन खरिद ला दिं", "bo fon kharid lā diṅ"],
        ["They want to learn English", "बिफां इङ्लिस सिम ला दिं", "biphāṅ iṅglis sim lā diṅ"],
        ["I don't want to argue", "आँ लडाइ नङा ला दों", "āṅ laḍāi naṅā lā doṅ"],
        ["Do you want to come along?", "नों सों विन ला दिं नामा?", "noṅ soṅ vin lā diṅ nāmā?"],
        ["She wants to help her mother", "बि बिनि आमानि मदद ला दिं", "bi bini āmāni madad lā diṅ"],
        ["We want peace", "जिंग थांथि ला दों", "jiṅ thāṃthi lā doṅ"],
        ["He wants to leave the job", "बो नोकरी छाड ला दिं", "bo nokarī chāḍ lā diṅ"],
        ["I want to drink cold water", "आँ थंड दै नुं ला दों", "āṅ thaṇḍ dai nuṅ lā doṅ"],
        ["Children want to play", "सोर खेल ला दिं", "sor khel lā diṅ"],
        ["She wants to become a nurse", "बि नर्स हो ला दिं", "bi nars ho lā diṅ"],
        ["We want to visit Kashmir", "जिंग कश्मिर जा ला दों", "jiṅ kaśmir jā lā doṅ"],
        ["He wants to save money", "बो पैसा बच ला दिं", "bo paisā bac lā diṅ"],
        ["I want to tell you something", "आँ नोंनि गोथो बोल ला दों", "āṅ noṅni gotho bol lā doṅ"],
    ],
}
