# Bodo Lesson 5 — Conversation practice, chunk A (chapter IDs 620–641).

LESSONS_S5A = {
    620: [
        ["Happy Diwali!", "दिवाली गोजोन!", "divālī gojon!"],
        ["May your home shine with lamps", "नोंनि गोराव दिया चमके", "noṅni gorāw diyā camke"],
        ["We light candles at dusk", "जिंग संजाव मोमबति जग दों", "jiṅ sañjāw mombati jag doṅ"],
        ["Children burst crackers safely", "सोरफोर सावधानै पटाखा फोर दिं", "soraphor sāvadhānai paṭākhā phor diṅ"],
        ["We worship Lakshmi tonight", "जिंग दिनि राति लक्ष्मी पूजा खालामगोन", "jiṅ dini rāti lakṣmī pūjā khālamgon"],
        ["Sweet shops are crowded", "मिथाइ दुकानाव बीड दं", "mithāi dukānāw bīḍ dong"],
        ["Wear new clothes today", "दिनि गोदान कपड पा", "dini godān kapaḍ pā"],
        ["Share sweets with neighbours", "गाह्रि गोरफोरजों मिथाइ बांड", "gāhri gorphorajoṃ mithāi bāṇḍ"],
        ["Diwali means victory of light", "दिवालीनि मतलब उजालानि जित", "divālīni matalab ujālāni jit"],
        ["Come to our house for puja", "पूजा लाम जिंनि गोर विन", "pūjā lām jiṅni gor vin"],
        ["The whole city looks beautiful", "बाहागो सहर सोन दं", "bāhāgo sahar son dong"],
        ["We greet elders first", "जिंग मोथाइ गोथो मानसिखौ नमस्कार ला दों", "jiṅ mothāi gotho mānasi khau namaskār lā doṅ"],
        ["Fireworks should be careful", "पटाखा सावधानै चला", "paṭākhā sāvadhānai calā"],
        ["May prosperity stay with you", "नों गोजो थां ना", "noṅ gojo thāṅ nā"],
        ["After puja we eat sweets", "पूजा फिन जिंग मिथाइ जा दों", "pūjā phin jiṅ mithāi jā doṅ"],
        ["Happy festival to your family", "नोंनि गराव पर्व गोजोन", "noṅni garāw parva gojon"],
    ],
    621: [
        ["Hello / Namaste", "नमस्कार / फुंनि गोजोन्थं", "namaskār / phuṅni gojonthaṅ"],
        ["How are you?", "नों गोरै दं?", "noṅ gorai dong?"],
        ["I am fine, thank you", "आँ गोरै दों, थांखाय", "āṅ gorai doṅ, thāṅkhāy"],
        ["What is your name?", "नोंनि नां मा दं?", "noṅni nāṃ mā dong?"],
        ["My name is Ravi", "आँनि नां रवि दं", "āṅni nāṃ ravi dong"],
        ["Where are you from?", "नों कुथां निफ्राय दं?", "noṅ kuthāṅ niphrāy dong?"],
        ["I am from Kokrajhar", "आँ कोक्राझार निफ्राय दों", "āṅ kokrājhār niphrāy doṅ"],
        ["Nice to meet you", "मिलि खुशि हो", "mili khusi ho"],
        ["See you again", "फिन मिलन फै", "phin milan phai"],
        ["Good morning", "फुंनि गोजोन्थं", "phuṅni gojonthaṅ"],
        ["Good night", "राति गोजोन", "rāti gojon"],
        ["Take care", "ख्याल राख", "khyāl rākh"],
        ["Welcome to our home", "जिंनि गोराव स्वागत", "jiṅni gorāw svāgat"],
        ["Please sit", "थांखाय बैठ", "thāṅkhāy baiṭh"],
        ["May I help you?", "आँ मदद ला दों नामा?", "āṅ madad lā doṅ nāmā?"],
        ["Thank you for coming", "विन लाम थांखाय", "vin lām thāṅkhāy"],
    ],
    622: [
        ["What time is it?", "माबो वज दं?", "mābo vaja dong?"],
        ["It is seven o'clock", "स्नि वज दं", "sni vaja dong"],
        ["I will come at five", "आँ बा वजाव विनों", "āṅ bā vajāw vinoṅ"],
        ["Wait five minutes", "बा मिनट थां हो", "bā minaṭ thāṅ ho"],
        ["Today is Monday", "दिनि सोमबार दं", "dini somabār dong"],
        ["Tomorrow is a holiday", "गाब्ला छुट्टि दं", "gāblā chuṭṭi dong"],
        ["I woke up early", "आँ फुंनि उठाय", "āṅ phuṅni uṭhāy"],
        ["The train leaves at noon", "ट्रेन दुपहराव थां", "ṭren dupaharāw thāṅ"],
        ["We work from nine to five", "जिंग गु निफ्राय बा थां काम दों", "jiṅ gu niphrāy bā thāṅ kām doṅ"],
        ["Last week I was busy", "मैया हफ्ता आँ बेस्त दों", "maiyā haftā āṅ best doṅ"],
        ["Next month we will travel", "फिन दान जिंग सफर खालामगोन", "phin dān jiṅ safar khālamgon"],
        ["The shop opens at ten", "दुकान जि वजाव खुल दं", "dukān ji vajāw khul dong"],
        ["I am late today", "आँ दिनि देर दों", "āṅ dini der doṅ"],
        ["Hurry, it is getting dark", "दैखो, अन्धेरा हो दं", "daikho, andherā ho dong"],
        ["See you tomorrow morning", "गाब्ला फुंनि मिलन फै", "gāblā phuṅni milan phai"],
        ["The meeting starts soon", "मिटिंग दैखो सुरु होगोन", "miṭiṅ daikho surū hogona"],
    ],
    623: [
        ["Where is the bus stand?", "बस स्टेन्द कुथां दं?", "bas stenda kuthāṅ dong?"],
        ["It is near the temple", "बो थांसोलि गाह्रि दं", "bo thāṃsoli gāhri dong"],
        ["How far is the airport?", "एयरपोर्ट माबो दूर दं?", "airpoṭ mābo dūr dong?"],
        ["About ten kilometres", "लगभग जि किलोमितर", "lagabhag ji kilomitar"],
        ["Is there a hotel nearby?", "गाह्रि होटल मोनो दं नामा?", "gāhri hoṭal mono dong nāmā?"],
        ["Turn left from the crossing", "चौक निफ्राय खब्बै मुड", "cauk niphrāy khabbai muḍ"],
        ["The road goes to the village", "रस्ता गाउ नां थां", "rastā gāu nāṃ thāṅ"],
        ["I am lost; help me", "आँ रस्ता गोम; मदद हो", "āṅ rastā gom; madad ho"],
        ["This is the right address", "निं ठिक थांहो दं", "nin ṭhik thāṃho dong"],
        ["The park is behind the school", "पार्क इस्कुल पिसिन दं", "pārak iskul pisini dong"],
        ["Can you show on the map?", "नों नक्साव दिखा ला दिं नामा?", "noṅ naksāw dikha lā diṅ nāmā?"],
        ["We live on the second floor", "जिंग नैथां मंजिलाव थां दों", "jiṅ naithāṅ mañzilāw thāṅ doṅ"],
        ["The river is beyond those trees", "दरिया उं गोजो पार दं", "dariyā uṅ gojo pār dong"],
        ["Is this the way to Kokrajhar?", "निं रस्ता कोक्राझार थां नामा?", "nin rastā kokrājhār thāṅ nāmā?"],
        ["Stop at the red light", "लाल बत्ति थां रुक", "lāl batti thāṅ ruk"],
        ["The bridge is under repair", "पुल मरमताव दं", "pul maramatāw dong"],
    ],
    624: [
        ["I need a room for two nights", "आँनि नै रात लाम रुम लाम दं", "āṅnai nai rāt lām rum lām dong"],
        ["Is breakfast included?", "नास्ता थां दं नामा?", "nāstā thāṅ dong nāmā?"],
        ["Please give the room key", "थांखाय रुमनि चाबि हो", "thāṅkhāy rumani cābi ho"],
        ["The AC is not working", "एसि काम नङा दं", "esi kām naṅā dong"],
        ["Can I get extra towels?", "आँ होर तौलिया ला दों नामा?", "āṅ hor tauliyā lā doṅ nāmā?"],
        ["What time is checkout?", "चेकआउट माबो वज दं?", "cekaāuṭ mābo vaja dong?"],
        ["Please call a taxi", "थांखाय टैक्सि बोल हो", "thāṅkhāy ṭaiksi bol ho"],
        ["The bill is too high", "बिल बाहागो चढ़ दं", "bil bāhāgo chaṛ dong"],
        ["I booked online", "आँ ऑनलाइन बुक खालाम", "āṅ online buk khālam"],
        ["Water in the bathroom is cold", "बाथरुमाव दै ठंड दं", "bāthurumāw dai ṭhaṇḍ dong"],
        ["Send food to room 204", "खाम रुम 204 खोर हो", "khām rum 204 khor ho"],
        ["Is Wi‑Fi free?", "वाइफाइ फ्री दं नामा?", "vāiphāi phrī dong nāmā?"],
        ["The lift is on the left", "लिफ्ट खब्बै पासाव दं", "lifṭ khabbai pāsāw dong"],
        ["Please keep luggage safe", "सामान थांथै राख", "sāmān thāṃthai rākh"],
        ["I want to extend one day", "आँ गोथो दिन होर थां ला दों", "āṅ gotho din hor thāṅ lā doṅ"],
        ["Thank you for your hospitality", "मेहमाननवाजि लाम थांखाय", "mehmānanavāji lām thāṅkhāy"],
    ],
    625: [
        ["It is very hot today", "दिनि बाहागो गरम दं", "dini bāhāgo garam dong"],
        ["Winter is very cold here", "निं थां थंड बाहागो दं", "nin thāṅ thaṇḍ bāhāgo dong"],
        ["It may rain tomorrow", "गाब्ला दै थां ला दं", "gāblā dai thāṅ lā dong"],
        ["The wind is strong", "हावा तेज दं", "hāvā tej dong"],
        ["Take an umbrella", "छाता ला", "chātā lā"],
        ["Fog on the highway", "हाइवे कोहरा दं", "haive koharā dong"],
        ["The weather is pleasant", "मौसम सुहावना दं", "mausam suhāvanā dong"],
        ["Summer starts in April", "गरमि एप्रिलाव सुरु दं", "garami epprilāw suru dong"],
        ["I like rainy season", "आँनि दैथां मौसम ला दों", "āṅnai daithāṅ mausam lā doṅ"],
        ["Climate is changing", "मौसम बदल दं", "mausam badal dong"],
        ["Wear warm clothes", "गरम कपड पा", "garam kapaḍ pā"],
        ["The fan is enough tonight", "दिनि रात पंखा काफि दं", "dini rāt paṅkhā kāphi dong"],
        ["Lightning flashed", "बिजली चम दं", "bijalī cam dong"],
        ["Flood in the river", "दरियाव बाढ दं", "dariyāw bāḍh dong"],
        ["Beautiful clouds in the sky", "आकाशाव सोन बादल", "ākāśāw son bādal"],
        ["Storm may come; stay inside", "तुफान आ ला दं; अन्दर थां", "tuphān ā lā dong; andar thāṅ"],
    ],
    626: [
        ["Sir, my licence please", "साहेब, आँनि लाइसेन्स नुं", "sāheb, āṅnai laisens nuṅ"],
        ["I was not speeding", "आँ ओभरस्पिड खालाम नङा", "āṅ obharaspiḍ khālam naṅā"],
        ["Here is the RC and insurance", "निं आरसि आरो बिमा", "nin ārsi āro bimā"],
        ["I will wear the helmet now", "आँ दा हेलमेट पामों", "āṅ dā helmeṭ pāmoṅ"],
        ["Sorry, I parked wrong", "माफ, आँ गलत पार्क खालाम", "māf, āṅ galat pārkk khālam"],
        ["Where should I pay the fine?", "आँनि जुर्माना कुथां भरनि लाम?", "āṅnai juramānā kuthāṅ bharani lām?"],
        ["Is this a one‑way road?", "निं इकपासि रस्ता दं नामा?", "nin ikapāsi rastā dong nāmā?"],
        ["The signal was green", "सिग्नल हाब दं", "signal hāb dong"],
        ["My documents are complete", "आँनि कागज पुरा दं", "āṅnai kāgaj purā dong"],
        ["Thank you, officer", "थांखाय, ऑफिसर", "thāṅkhāy, ophisar"],
        ["I will follow traffic rules", "आँ ट्रैफिक नियम मानों", "āṅ ṭraifik niyam mānoṅ"],
        ["Is there a checking ahead?", "मोथाइ चेकिंग मोनो दं नामा?", "mothāi cekiṅ mono dong nāmā?"],
        ["My vehicle papers are valid", "आँनि गारिनि कागज ठिक दं", "āṅnai gārini kāgaj ṭhik dong"],
        ["Please guide me to the RTO", "आरटिओ थां दिखा हो", "āraṭio thāṅ dikha ho"],
        ["I did not jump the red light", "आँ लाल बत्ति नङा कुट", "āṅ lāl batti naṅā kuṭ"],
        ["Drive safely", "थांथै चला", "thāṃthai calā"],
    ],
    627: [
        ["How much to the railway station?", "रेलवे स्टेशन माबो पैसा?", "relave sṭeśan mābo paisā?"],
        ["Please use the meter", "थांखाय मिटर लगा हो", "thāṅkhāy miṭar lagā ho"],
        ["Stop here near the gate", "गेट गाह्रि निं थां रुक", "geṭ gāhri nin thāṅ ruk"],
        ["Keep the change", "बकाया राख", "bakāyā rākh"],
        ["Is this the shortest route?", "निं गोथो रस्ता दं नामा?", "nin gotho rastā dong nāmā?"],
        ["Don't take a long detour", "लाम चक्कर नङा ला", "lām cakkar naṅā lā"],
        ["I am in a hurry", "आँ दैखो दों", "āṅ daikho doṅ"],
        ["Please drive slowly on bumps", "उबडखाबड थां हौलै चला", "ubaḍakhābaḍ thāṅ haulai calā"],
        ["Drop me at the main road", "आँनि मुख्य रस्ताव उतार हो", "āṅni mukhya rastāw utār ho"],
        ["The fare seems high", "किराया बाहागो लाग दं", "kirāyā bāhāgo lāg dong"],
        ["Can you help with the bags?", "नों बेग चुक ला दिं नामा?", "noṅ beg cuk lā diṅ nāmā?"],
        ["Wait two minutes, I am coming", "नै मिनट थां हो, आँ विन दों", "nai minaṭ thāṅ ho, āṅ vin doṅ"],
        ["Turn on the AC please", "एसि चला हो", "esi calā ho"],
        ["Is Ola/Uber available here?", "निं ओला उबर मिल दं नामा?", "nin olā ubar mil dong nāmā?"],
        ["Thank you; here is your money", "थांखाय; नोंनि पैसा", "thāṅkhāy; noṅni paisā"],
        ["Have a safe day", "थांथै दिन हो", "thāṃthai din ho"],
    ],
    628: [
        ["We deploy on Friday", "जिंग सुक्रबार डिप्लय खालामगोन", "jiṅ sukrabār ḍiplai khālamgon"],
        ["The build failed in CI", "सिआइ आव बिल्ड फेल हो", "siāi āw bilḍ phel ho"],
        ["Please review my pull request", "आँनि पुल रिक्वेस्ट रिभ्यू हो", "āṅnai pul rikwest ribhyū ho"],
        ["Let's sync in the stand‑up", "स्टेन्दअपाव सिंक खालाम", "sṭendapāw siṅk khālam"],
        ["I will push the fix tonight", "आँ दिनि रात फिक्स पुस खालामों", "āṅ dini rāt phiks pus khālamoṅ"],
        ["The bug is reproducible", "बग फिन हो ला दं", "bag phin ho lā dong"],
        ["We need more test coverage", "जिंनि होर टेस्ट कभरेज लाम", "jiṅni hor ṭesṭ kabharej lām"],
        ["The API latency is high", "एपिआइ लेटेन्सि बाहागो दं", "epiāi leṭensi bāhāgo dong"],
        ["Let's pair program on this", "निं आव पेयर प्रोग्रामिंग खालाम", "nin āw peyar progrāmiṅ khālam"],
        ["I am on leave tomorrow", "आँ गाब्ला छुट्टि थां दों", "āṅ gāblā chuṭṭi thāṅ doṅ"],
        ["The client wants a demo", "क्लाइन्ट डेमो लाम दं", "klāinṭ ḍemo lām dong"],
        ["VPN is not connecting", "भिपिएन जोड नङा दं", "bhipien joḍ naṅā dong"],
        ["Please share the log file", "लग फाइल सेयर हो", "lag phāil seyar ho"],
        ["We follow agile in our team", "जिंग जिंनि टिम एजाइलाव काम दों", "jiṅ jiṅni ṭim ejāilāw kām doṅ"],
        ["The sprint ends next week", "स्प्रिन्ट फिन हफ्ताव मुक दं", "sprinṭ phin haftāw muk dong"],
        ["Great job on the release", "रिलिज आव शाबास", "rilij āw śābās"],
    ],
    629: [
        ["Half a kilo of potatoes", "आलू आधि किलो", "ālū ādhi kilo"],
        ["Is this fresh?", "निं ताजा दं नामा?", "nin tājā dong nāmā?"],
        ["The price went up today", "दिनि रेट चढ़ दं", "dini reṭ chaṛ dong"],
        ["Give coriander as well", "धनिया फिन हो", "dhaniyā phin ho"],
        ["I need three lemons", "आँनि थिन निम्ब लाम", "āṅnai thin nimb lām"],
        ["Do you have organic vegetables?", "नों अर्गेनिक सब्जि दं नामा?", "noṅ argenik sabji dong nāmā?"],
        ["This looks wilted", "निं मुरजाय दं", "nin murajāy dong"],
        ["Pack separately", "अलग अलग पैक हो", "alag alag paik ho"],
        ["I will pay by UPI", "आँ युपिआइ बिफिन भरों", "āṅ yupiāi bifin bharoṅ"],
        ["Give a receipt", "रसिद हो", "rasid ho"],
        ["The onions are strong", "गांदा तेज दं", "gāndā tej dong"],
        ["Any discount today?", "दिनि छुट दं नामा?", "dini chuṭ dong nāmā?"],
        ["I shop here every week", "आँ हर हफ्ता निं ला दों", "āṅ har haftā nin lā doṅ"],
        ["Keep the change", "बकाया राख", "bakāyā rākh"],
        ["Where is the weighing scale?", "तराजु कुथां दं?", "tarāju kuthāṅ dong?"],
        ["Thank you, brother", "थांखाय, दा", "thāṅkhāy, dā"],
    ],
    630: [
        ["Doctor, I have fever since yesterday", "डाक्टर, मैया दिन निफ्राय आँनि बुखार दं", "ḍākṭar, maiyā din niphrāy āṅni bukhār dong"],
        ["Any cough or cold?", "खांस नामा जुकाम?", "khā̃s nāmā jukām?"],
        ["Take this medicine twice a day", "निं दवाई दिनि नै वार ला", "nin davāī dini nai vār lā"],
        ["Drink plenty of water", "बाहागो दै नुं", "bāhāgo dai nuṅ"],
        ["Get blood tests done", "ब्लड टेस्ट खालाम", "blaḍ ṭesṭ khālam"],
        ["Avoid spicy food", "तीखा खाम नङा जा", "tīkhā khām naṅā jā"],
        ["Rest for three days", "थाम दिन आराम हो", "thām din ārām ho"],
        ["Come back after a week", "गोथो हफ्ता फिन मिल", "gotho haftā phin mil"],
        ["Is an X‑ray needed?", "एक्सरे लाम दं नामा?", "eksare lām dong nāmā?"],
        ["The pain is in the chest", "दर्द छाति थां दं", "dard chāti thāṅ dong"],
        ["I am allergic to penicillin", "आँनि पेनिसिलिन एलर्जि दं", "āṅni penisilin elarji dong"],
        ["Nurse will give the injection", "नर्स इन्जेक्शन होगोन", "nars injekśan hogona"],
        ["Hospital timings?", "हस्पतालनि सम?", "haspatālani sam?"],
        ["Emergency is on the ground floor", "इमरजेन्सि ग्राउन्ड फ्लोराव दं", "imarajensi graunḍ phlorāw dong"],
        ["Thank you, doctor", "थांखाय, डाक्टर", "thāṅkhāy, ḍākṭar"],
        ["I feel better now", "आँ दा ठिक महसुस ला दों", "āṅ dā ṭhik mahasus lā doṅ"],
    ],
    631: [
        ["Good morning, teacher", "फुंनि गोजोन्थं, मास्तार", "phuṅni gojonthaṅ, māstār"],
        ["May I enter the class?", "आँ क्लासाव विन ला दों नामा?", "āṅ klāsāw vin lā doṅ nāmā?"],
        ["I completed the homework", "आँ गोरनि काम मुकाय", "āṅ gorani kām mukāy"],
        ["Can you explain this sum?", "नों निं सवाल सोंलों ला दिं नामा?", "noṅ nin savāl soloṅ lā diṅ nāmā?"],
        ["The exam is next Monday", "परीक्षा फिन सोमबार दं", "parīkṣā phin somabār dong"],
        ["Please speak louder", "जोरै लैब हो", "jorai laib ho"],
        ["Group discussion tomorrow", "गाब्ला ग्रुप गोबो दं", "gāblā grup gobo dong"],
        ["I will submit the project online", "आँ प्रोजेक्ट ऑनलाइन जमा खालामों", "āṅ projekt online jamā khālamoṅ"],
        ["May I ask a doubt?", "आँ सवाल फुं ला दों नामा?", "āṅ savāl phuṅ lā doṅ nāmā?"],
        ["Library books due date?", "लाइब्रेरिनि पुस्तकनि तारिख?", "lāibrerini pustakani tārikh?"],
        ["Sports period is last", "खेलनि पिरियड आखिरि दं", "khelani piriyāḍ ākhiri dong"],
        ["Congratulations on your result", "नतिजा आव गोजोन", "natijā āw gojon"],
        ["Don't use mobile in class", "क्लासाव मोबाइल बाहागो नङा", "klāsāw mobāil bāhāgo naṅā"],
        ["We will have a quiz today", "जिंग दिनि क्विज लामगोन", "jiṅ dini kwij lāmagon"],
        ["Thank you for teaching Bodo", "बोडो पदौन लाम थांखाय", "boḍo padoun lām thāṅkhāy"],
        ["See you tomorrow", "गाब्ला मिलन फै", "gāblā milan phai"],
    ],
    632: [
        ["Hello, it's Ravi speaking", "हेलो, रवि लैब दों", "helo, ravi laib doṅ"],
        ["Is Priya there?", "प्रिया निं दं नामा?", "priyā nin dong nāmā?"],
        ["She is not at home right now", "बि दा गोराव नङा", "bi dā gorāw naṅā"],
        ["Can I leave a message?", "आँ खोर खो ला दों नामा?", "āṅ khor kho lā doṅ nāmā?"],
        ["Tell her to call me back", "बिनि आँखौ फिन फोन हो बोल", "bini āṅkhau phin fon ho bol"],
        ["The signal is weak", "सिग्नल कमजोर दं", "signal kamajor dong"],
        ["I will WhatsApp the location", "आँ लोकेसन व्हाट्सएप खालामों", "āṅ lokesan vhāṭsepa khālamoṅ"],
        ["Sorry, wrong number", "माफ, गलत नंबर", "māf, galat nambar"],
        ["Can you hear me?", "नों आँनि नुंथ ला दिं नामा?", "noṅ āṅni nunth lā diṅ nāmā?"],
        ["I'll call again in five minutes", "आँ बा मिनट फिन फोन खालामों", "āṅ bā minaṭ phin fon khālamoṅ"],
        ["Battery is dying", "बैटरी मुक दं", "baiṭarī muk dong"],
        ["Talk to you later", "फिन गोबो खालामगोन", "phin gobo khālamgon"],
        ["I'm driving; I'll call back", "आँ गारि चला दों; फिन फोन खालाम", "āṅ gāri calā doṅ; phin fon khālam"],
        ["Please text me the address", "थांहो मेसेज हो", "thāṃho mesej ho"],
        ["Nice talking to you", "गोबो खालाम के गोजोन लाग", "gobo khālam ke gojon lāg"],
        ["Bye, take care", "बाय, ख्याल राख", "bāy, khyāl rākh"],
    ],
    633: [
        ["How much per kilo for tomatoes?", "टमाटर किलो माबो?", "ṭamāṭar kilo mābo?"],
        ["These beans look fresh", "निं फलि ताजा दं", "nin phali tājā dong"],
        ["Give one bundle of spinach", "गोथो गड्डि पालक हो", "gotho gaḍḍi pālak ho"],
        ["Too expensive; reduce a little", "बाहागो महंगा; थोड़ कटा", "bāhāgo mahangā; thoṛ kaṭā"],
        ["I need ginger and garlic", "आँनि अदा आरो लहसुन लाम", "āṅni adā āro lahasun lām"],
        ["Weigh one kilo potatoes", "गोथो किलो आलू तौल", "gotho kilo ālū taul"],
        ["The market is crowded today", "दिनि बाजाराव बीड दं", "dini bājārāw bīḍ dong"],
        ["Carry the bag to my scooter", "बेग आँनि स्कुटराव राख हो", "beg āṅni skuṭarāw rākh ho"],
        ["Any discount for regular customers?", "रेगुलर ग्राहक लाम छुट दं नामा?", "regular grāhak lām chuṭ dong nāmā?"],
        ["This pumpkin is sweet", "निं कद्दू मिथा दं", "nin kaddū mithā dong"],
        ["I will come every Sunday", "आँ हर ऐतवार विनों", "āṅ har aitavār vinoṅ"],
        ["Keep separate bills", "अलग बिल बाना", "alag bil bānā"],
        ["Organic vegetables there", "उं अर्गेनिक सब्जि मिल दं", "uṅ argenik sabji mil dong"],
        ["Wash before cooking", "फोथोनि मोथाइ नुं", "phothoni mothāi nuṅ"],
        ["Thank you, see you next week", "थांखाय, फिन हफ्ताव मिलन फै", "thāṅkhāy, phin haftāw milan phai"],
        ["Have a good day", "गोजोन दिन हो", "gojon din ho"],
    ],
    634: [
        ["Which bus goes to the city?", "माबो बस सहर थां?", "mābo bas sahar thāṅ?"],
        ["The next bus is in ten minutes", "फिन बस जि मिनटाव दं", "phin bas ji minaṭāw dong"],
        ["Is this seat free?", "निं सिट खालि दं नामा?", "nin siṭ khāli dong nāmā?"],
        ["Please move inside", "थांखाय अन्दर चल", "thāṅkhāy andar cal"],
        ["Where should I get down?", "आँ कुथां उतरनि लाम?", "āṅ kuthāṅ utarani lām?"],
        ["Conductor, one ticket to Kokrajhar", "कन्डक्टर, कोक्राझार गोथो टिकट", "kanḍakṭar, kokrājhār gotho ṭikaṭ"],
        ["Keep luggage in the rack", "सामान रेकाव राख", "sāmān rekāw rākh"],
        ["The bus is crowded", "बस बीड थां दं", "bas bīḍ thāṅ dong"],
        ["Is there an AC bus?", "एसि बस मिल दं नामा?", "esi bas mil dong nāmā?"],
        ["The stop is announced", "स्टप बोल दं", "sṭap bol dong"],
        ["Don't stand near the door", "दरवाजा गाह्रि नङा खड़", "daravājā gāhri naṅā khaṛ"],
        ["I missed my stop", "आँनि स्टप छुट जा", "āṅni sṭap chuṭ jā"],
        ["Is this the express?", "निं एक्सप्रेस दं नामा?", "nin ekspres dong nāmā?"],
        ["How long is the journey?", "सफर माबो लाम दं?", "safar mābo lām dong?"],
        ["Thank you, driver", "थांखाय, ड्राइभर", "thāṅkhāy, ḍrāibhar"],
        ["Have a safe trip", "सफर थांथै हो", "safar thāṃthai ho"],
    ],
    635: [
        ["Excuse me, where is this lane?", "माफ, निं गली कुथां?", "māf, nin galī kuthāṅ?"],
        ["How far is the post office?", "डाकघर माबो दूर दं?", "ḍākghar mābo dūr dong?"],
        ["Take the second left", "नैथां खब्बै ला", "naithāṅ khabbai lā"],
        ["It is opposite the school", "बो इस्कुल सिंनि दं", "bo iskul siṃni dong"],
        ["Ask anyone there; they know", "उं मानसिखौ फुं; बिफां मोन दं", "uṅ mānasi khau phuṅ; biphāṅ mon dong"],
        ["The house number is 42", "गोर नंबर बयालि दं", "gor nambar bayāli dong"],
        ["Near the temple, not the mosque", "थांसोलि गाह्रि, मस्जिद नङा", "thāṃsoli gāhri, masjid naṅā"],
        ["Can you write the address?", "नों थांहो लिर ला दिं नामा?", "noṅ thāṃho lir lā diṅ nāmā?"],
        ["I will put it in maps", "आँ मेपाव पा दों", "āṅ mepāw pā doṅ"],
        ["Landmark is the big banyan tree", "निशान बाहागो बरगद दं", "niśān bāhāgo bargad dong"],
        ["Ring the bell twice", "घंटि नै वार बजा", "ghaṇṭi nai vār bajā"],
        ["Is this the correct pin code?", "निं ठिक पिनकोड दं नामा?", "nin ṭhik pinakoḍ dong nāmā?"],
        ["The lane is one‑way", "निं गली इकपासि दं", "nin galī ikapāsi dong"],
        ["Thank you for guiding", "रस्ता दसन लाम थांखाय", "rastā dasan lām thāṅkhāy"],
        ["I found the house", "आँ गोर नाय", "āṅ gor nāy"],
        ["Goodbye", "फिन मिलन फै", "phin milan phai"],
    ],
    636: [
        ["I like you very much", "आँनि नों बाहागो पसंद", "āṅni noṅ bāhāgo pasand"],
        ["Will you be my friend?", "नों आँनि दोस्त जा नामा?", "noṅ āṅni dost jā nāmā?"],
        ["You mean a lot to me", "नों आँनि लाम बाहागो दं", "noṅ āṅni lām bāhāgo dong"],
        ["I want to spend time with you", "आँ नोंजों सम गज्जा ला दों", "āṅ noṅjoṃ sam gajjā lā doṅ"],
        ["May I walk you home?", "आँ नोंखौ गोर थां टुर ला दों नामा?", "āṅ noṅkhau gor thāṅ ṭur lā doṅ nāmā?"],
        ["You have a beautiful smile", "नोंनि मुस्कान सोन दं", "noṅni muskān son dong"],
        ["I respect your feelings", "आँ नोंनि भाव मान ला दों", "āṅ noṅni bhāv mān lā doṅ"],
        ["Let's meet again soon", "फिन दैखो मिल", "phin daikho mil"],
        ["I wrote this for you", "आँ निं नों लाम लिर", "āṅ nin noṅ lām lir"],
        ["Happy Valentine's Day", "भालेन्टाइन दिबस गोजोन", "bhālenṭāin dibas gojon"],
        ["You are special to me", "नों आँनि लाम खास दं", "noṅ āṅni lām khās dong"],
        ["Can we talk privately?", "जिंग गोथो गोबो ला दों नामा?", "jiṅ gotho gobo lā doṅ nāmā?"],
        ["I promise to care for you", "आँ नोंनि ख्याल राखनाय वादा ला दों", "āṅ noṅni khyāl rākhanāy vādā lā doṅ"],
        ["Thank you for understanding", "मोन लाम थांखाय", "mon lām thāṅkhāy"],
        ["Whatever you decide, I respect it", "नों फैसला खालाम के आँ मान ला दों", "noṅ phaislā khālam ke āṅ mān lā doṅ"],
        ["Wishing you happiness", "नों खुशि थां", "noṅ khusi thāṅ"],
    ],
    637: [
        ["Tell me about yourself", "नोंनि बारे दस", "noṅni bāre das"],
        ["Why do you want this job?", "नों निं नौकरी माब्ला लाम?", "noṅ nin naukarī māblā lām?"],
        ["My strengths are teamwork", "आँनि ताकत टिम वर्क दं", "āṅni tākat ṭim vark dong"],
        ["I have three years' experience", "आँनि थाम बोसोरनि तजुर्बा दं", "āṅnai thām bosorani tajurbā dong"],
        ["My expected salary is…", "आँनि उमेद तनखा … दं", "āṅnai umed tanakhā … dong"],
        ["I can join next month", "आँ फिन दान जॉइन ला दों", "āṅ phin dān join lā doṅ"],
        ["I am willing to relocate", "आँ ट्रान्सफर लाम तैयार दों", "āṅ ṭrānsfar lām taiyār doṅ"],
        ["How do you handle pressure?", "नों दाब माबो खालाम?", "noṅ dāb mābo khālam?"],
        ["Describe a difficult project", "गोथो अखा प्रोजेक्ट दस", "gotho akhā projekṭ das"],
        ["Where do you see yourself in five years?", "बा बोसोर फिन नों आँनि कुथां नेउ?", "bā bosor phin noṅ āṅni kuthāṅ neu?"],
        ["Any questions for us?", "जिंनि लाम मोनो सवाल दं नामा?", "jiṅni lām mono savāl dong nāmā?"],
        ["Thank you for this opportunity", "निं मौका लाम थांखाय", "nin maukā lām thāṅkhāy"],
        ["I will send documents by email", "आँ कागज ईमेल खोर खालामों", "āṅ kāgaj īmel khor khālamoṅ"],
        ["I am comfortable with Bodo and Hindi", "आँ बोडो आरो हिन्दि थां सहज दों", "āṅ boḍo āro hindi thāṅ sahaj doṅ"],
        ["When can I expect the result?", "नतिजा माबो मिल?", "natijā mābo mil?"],
        ["Goodbye; hope to work with you", "अलबिदा; जिंगनि काम लाम उमेद", "alabidā; jiṅni kām lām umed"],
    ],
    638: [
        ["Please clean the kitchen today", "थांखाय दिनि रसुइ साफ हो", "thāṅkhāy dini rasui sāph ho"],
        ["Wash clothes twice a week", "हफ्ताव नै वार कपड नुं", "haftāw nai vār kapaḍ nuṅ"],
        ["The floor needs mopping", "फर्श पोंछ लाम", "farś poṅch lām"],
        ["I will pay salary on the fifth", "आँ बा थां तनखा हो दों", "āṅ bā thāṅ tanakhā ho doṅ"],
        ["Take Sunday off", "ऐतवार छुट्टि राख", "aitavār chuṭṭi rākh"],
        ["Please lock the door when you leave", "चलनि बेला दरवाजा बन्द हो", "calani belā daravājā band ho"],
        ["Vegetables are in the fridge", "सब्जि फ्रिज थां दं", "sabji frij thāṅ dong"],
        ["Don't use too much detergent", "ज्यादा डिटर्जेन्ट बाहागो नङा", "zyādā ḍiṭarjenṭ bāhāgo naṅā"],
        ["Call me if there is a problem", "मुसिबत होय फोन हो", "musibat hoya fon ho"],
        ["Iron these shirts", "निं कमिज इस्त्रि हो", "nin kamij istri ho"],
        ["Guests are coming; tidy the hall", "मेहमान विनगोन; हाल सजा", "mehmān vingona; hāl sajā"],
        ["Water the plants on the balcony", "बाल्कोनि पौधा दै हो", "bālakoni paudhā dai ho"],
        ["Keep the keys on the table", "चाबि मेजाव राख", "cābi mejāw rākh"],
        ["I trust your work", "आँ नोंनि काम आव भरोसा ला दों", "āṅ noṅni kām āv bharosā lā doṅ"],
        ["Take care of yourself", "आँनि ख्याल राख", "āṅni khyāl rākh"],
        ["Thank you for your help", "मदद लाम थांखाय", "madad lām thāṅkhāy"],
    ],
    639: [
        ["Open the Aadhaar app", "आधार ऐप खोल", "ādhār aip khol"],
        ["Enter your mobile number", "नोंनि मोबाइल नंबर पा", "noṅni mobāil nambar pā"],
        ["You will get an OTP", "नोंनि ओटिपि मिलगोन", "noṅni oṭipi milagon"],
        ["Enter OTP to verify", "वेरिफाइ लाम ओटिपि पा", "veriphāi lām oṭipi pā"],
        ["Linking is successful", "लिंक जा दं", "liṅk jā dong"],
        ["If it fails, try again later", "जे फेल हो फिन कोशिश हो", "je phel ho phin koshish ho"],
        ["Keep your Aadhaar safe", "नोंनि आधार थांथै राख", "noṅni ādhār thāṃthai rākh"],
        ["Do not share OTP with anyone", "ओटिपि मानसिखौ नङा हो", "oṭipi mānasi khau naṅā ho"],
        ["Use only official apps", "ऑफिसियल ऐप बाहागो", "ophisiyal aip bāhāgo"],
        ["Update your mobile if changed", "मोबाइल बदल फिन अपडेट हो", "mobāil badal phin apadeṭ ho"],
        ["Helpline number is on the website", "हेल्पलाइन वेबसाइटाव दं", "helplain vebsāiṭāw dong"],
        ["Carry original ID for verification", "वेरिफिकेसन लाम असलि आइडि ला", "veriphikesan lām asali āiḍi lā"],
        ["The shopkeeper can help scan", "दुकानदार स्केनाव मदद ला दं", "dukāndār skenāw madad lā dong"],
        ["Check SMS for confirmation", "पक्के लाम एसएमएस नेउ", "pakke lām esemes neu"],
        ["Logout after finishing", "मुक फिन लगआउट हो", "muk phin lagāuṭ ho"],
        ["Your data is protected", "नोंनि डाटा थांथै दं", "noṅni ḍāṭā thāṃthai dong"],
    ],
    640: [
        ["Open mobile settings", "मोबाइल सेटिंग खोल", "mobāil seṭiṅ khol"],
        ["Go to SIM card settings", "सिम कार्ड सेटिंग थां जा", "sim kārḍ seṭiṅ thāṅ jā"],
        ["Select Aadhaar linking option", "आधार लिंकनि विकल्प साय", "ādhār liṅkani vikalp sāy"],
        ["Enter Aadhaar number carefully", "आधार नंबर ध्यानै पा", "ādhār nambar dhyānai pā"],
        ["OTP will come on registered mobile", "रेजिस्टर्ड मोबाइलाव ओटिपि आगोन", "rejisṭarḍ mobāilāw oṭipi āgon"],
        ["Do not share the OTP", "ओटिपि सेयर नङा", "oṭipi seyar naṅā"],
        ["Linking may take a few minutes", "लिंक होनि मोनो मिनट लाग ला दं", "liṅk honi mono minaṭ lāg lā dong"],
        ["If wrong, recheck the number", "गलत हो नंबर फिन चेक हो", "galat ho nambar phin cek ho"],
        ["Visit the telecom store if needed", "लाम हो टेलिकम स्टोर जा", "lām ho ṭelikam sṭor jā"],
        ["Carry Aadhaar and ID proof", "आधार आरो पहचान पत्र ला", "ādhār āro pehchān patra lā"],
        ["Official website has FAQs", "ऑफिसियल वेबसाइटाव सवाल जवाब दं", "ophisiyal vebsāiṭāw savāl javāb dong"],
        ["Beware of fake links", "नकलि लिंक निफ्राय सावधान", "nakali liṅk niphrāy sāvadhān"],
        ["Customer care can guide", "कस्टमर केयर दिखा ला दं", "kasṭamar keyar dikha lā dong"],
        ["Keep transaction SMS", "लेनदेननि एसएस राख", "lendenani eses rākh"],
        ["Update KYC if asked", "केवाइसि अपडेट मांग फिन हो", "kevāisi apadeṭ māṅg phin ho"],
        ["Your number is now verified", "नोंनि नंबर दा वेरिफाइ जा दं", "noṅni nambar dā veriphāi jā dong"],
    ],
    641: [
        ["Long live the Republic!", "गणतन्त्र जिन्दाबाद!", "gaṇatantra zindābād!"],
        ["We hoist the flag at dawn", "जिंग फुंनि जंडा फर दों", "jiṅ phuṅni jaṇḍā phar doṅ"],
        ["The parade is beautiful", "परेड सोन दं", "pareḍ son dong"],
        ["Children sing the anthem", "सोरफोर राष्ट्रगित गान दिं", "sorphor rāṣṭragit gān diṅ"],
        ["We remember the Constitution", "जिंग संबिधान याद खालाम दों", "jiṅ saṃbidhān yād khālam doṅ"],
        ["Tri‑colour sweets in the market", "बाजाराव तिरंगा मिथाइ", "bājārāw tiraṅgā mithāi"],
        ["Everyone feels proud", "मानसिफोरनि गर्व दं", "mānasi phorni garv dong"],
        ["Schools have a holiday", "इस्कुलाव छुट्टि दं", "iskulāw chuṭṭi dong"],
        ["We watch the ceremony on TV", "जिंग टिवि आव समारोह नेउ दों", "jiṅ ṭivi āv samāroh neu doṅ"],
        ["Guests are invited", "मेहमान बुलाय गोन", "mehmān bulāy gona"],
        ["The band plays patriotic songs", "बेन्ड देसभक्ति गित बज दं", "benḍ desabhakti git baja dong"],
        ["Fly kites in the evening", "संजाव पतंग उडा", "sañjāw pataṅg uḍā"],
        ["Respect the national symbols", "राष्ट्रिय निशाननि मान हो", "rāṣṭriya niśānani mān ho"],
        ["Happy Republic Day!", "गणतन्त्र दिबस गोजोन!", "gaṇatantra dibas gojon!"],
        ["Jai Hind!", "जय हिन्द!", "jaya hind!"],
        ["Unity in diversity", "फरायफरायाव मिल", "pharāypharāyāw mil"],
    ],
}
