# Bodo Lesson 2 — chunk B (chapter IDs 527–542).
# Columns: English, Bodo (Devanagari), Transliteration.

LESSONS_S2B = {
    527: [
        ["My book", "आँनि पुस्तक", "āṅni pustak"],
        ["Your book (informal)", "नोंनि पुस्तक", "noṅni pustak"],
        ["Your book (polite)", "नेंफांनि पुस्तक", "nenphāṅni pustak"],
        ["His book", "बोनि पुस्तक", "boni pustak"],
        ["Her book", "बिनि पुस्तक", "bini pustak"],
        ["Our house", "जिंनि गोर", "jiṅni gor"],
        ["Your house (pl.)", "नेंफांनि गोर", "nenphāṅni gor"],
        ["Their house", "बिफांनि गोर", "biphāṅni gor"],
        ["My father", "आँनि बाफा", "āṅni bāphā"],
        ["His father", "बोनि बाफा", "boni bāphā"],
        ["Her mother", "बिनि आमा", "bini āmā"],
        ["Our teacher", "जिंनि मास्तार", "jiṅni māstār"],
        ["Their children", "बिफांनि सोरफोर", "biphāṅni sorphor"],
        ["This is mine", "निं आँनि दं", "nin āṅni dong"],
        ["That is yours", "उं नोंनि दं", "uṅ noṅni dong"],
        ["The pen is his", "कलम बोनि दं", "kalam boni dong"],
        ["These are our books", "निं जिंनि पुस्तकफोर दं", "nin jiṅni pustakphor dong"],
        ["I lost my keys", "आँ आँनि चाबि गोम दं", "āṅ āṅni cābi gom dong"],
        ["She took her bag", "बि बिनि थैलि ला दं", "bi bini thaili lā dong"],
        ["We love our village", "जिंग जिंनि गाउनि मान ला दों", "jiṅ jiṅni gāuni mān lā doṅ"],
    ],
    528: [
        ["What is your name?", "नोंनि मुं मा दं?", "noṅni muṅ mā dong?"],
        ["Where are you going?", "नों मोन तों दिं?", "noṅ mon toṅ diṅ?"],
        ["When did he come?", "बो मोन विन दं?", "bo mon vin dong?"],
        ["Why are you sad?", "नों माबा खुसि नङा दिं?", "noṅ mābā khusi naṅā diṅ?"],
        ["How are you?", "नों गोरै दं?", "noṅ gorai dong?"],
        ["Who is that?", "उं माव्नो दं?", "uṅ māwno dong?"],
        ["How much is this?", "निं मोनखो दं?", "nin monakho dong?"],
        ["Which book do you want?", "नों मा पुस्तक ला दिं?", "noṅ mā pustak lā diṅ?"],
        ["Whose pen is this?", "निं मानि कलम दं?", "nin māni kalam dong?"],
        ["How many people came?", "मोनखो मानसि विन दं?", "monakho mānasi vin dong?"],
        ["Where do you live?", "नों मोन थां दिं?", "noṅ mon thāṅ diṅ?"],
        ["What do you do?", "नों मा दा दिं?", "noṅ mā dā diṅ?"],
        ["When will you return?", "नों मोन फिन ला दिं?", "noṅ mon phin lā diṅ?"],
        ["Why did she leave?", "बि माबा चल जा दं?", "bi mābā cal jā dong?"],
        ["How did you come?", "नों मोन विन दं?", "noṅ mon vin dong?"],
        ["Is this yours?", "निं नोंनि दं?", "nin noṅni dong?"],
        ["Are they ready?", "बिफां तैयार दं?", "biphāṅ taiyār dong?"],
        ["Can you help me?", "नों आँनि मदद ला दिं नामा?", "noṅ āṅni madad lā diṅ nāmā?"],
        ["Do you know Bodo?", "नों बोडो मोन दिं?", "noṅ boḍo mon diṅ?"],
        ["What happened?", "मा हो दं?", "mā ho dong?"],
    ],
    529: [
        ["I do not eat meat", "आँ मास नङा जा दों", "āṅ mās naṅā jā doṅ"],
        ["You do not understand", "नों मोन नङा दिं", "noṅ mon naṅā diṅ"],
        ["He does not lie", "बो मिथिखौ नङा बोल दिं", "bo mithikhau naṅā bol diṅ"],
        ["She does not sing today", "बि दिनि गान नङा दिं", "bi dini gān naṅā diṅ"],
        ["We do not play now", "जिंग दा खेल नङा दों", "jiṅ dā khel naṅā doṅ"],
        ["They do not come here", "बिफां दा विन नङा दिं", "biphāṅ dā vin naṅā diṅ"],
        ["I do not know", "आँ मोन नङा दों", "āṅ mon naṅā doṅ"],
        ["You do not listen", "नों नुंथ नङा दिं", "noṅ nunth naṅā diṅ"],
        ["He does not work on Sunday", "बो रविवार काम नङा दिं", "bo ravivār kām naṅā diṅ"],
        ["She does not like tea", "बि चा ला नङा दिं", "bi cā lā naṅā diṅ"],
        ["We do not forget", "जिंग गोम नङा दों", "jiṅ gom naṅā doṅ"],
        ["They do not agree", "बिफां राजि नङा दिं", "biphāṅ rāji naṅā diṅ"],
        ["There is no water", "दै नङा दं", "dai naṅā dong"],
        ["I am not afraid", "आँ डर नङा दों", "āṅ ḍar naṅā doṅ"],
        ["This is not mine", "निं आँनि नङा", "nin āṅni naṅā"],
        ["We are not late", "जिंग देर नङा दों", "jiṅ der naṅā doṅ"],
        ["He is not at home", "बो गोराव नङा दं", "bo gorāw naṅā dong"],
        ["Do not run here", "दा दौड़ नङा", "dā dauṛ naṅā"],
        ["I do not want it", "आँ ला नङा दों", "āṅ lā naṅā doṅ"],
        ["You do not need to go", "नों तोंनाय नङा दिं", "noṅ toṅnāy naṅā diṅ"],
    ],
    530: [
        ["I did not go", "आँ जा नङा दं", "āṅ jā naṅā dong"],
        ["You did not eat", "नों खा नङा दं", "noṅ khā naṅā dong"],
        ["He did not come", "बो विन नङा दं", "bo vin naṅā dong"],
        ["She did not sleep", "बि सा नङा दं", "bi sā naṅā dong"],
        ["We did not see him", "जिंग बिनि नेउ नङा दं", "jiṅ bini neu naṅā dong"],
        ["They did not hear", "बिफां नुंथ नङा दं", "biphāṅ nunth naṅā dong"],
        ["I did not buy it", "आँ खरिद नङा दं", "āṅ kharid naṅā dong"],
        ["You did not tell me", "नों आँनि बोल नङा दं", "noṅ āṅni bol naṅā dong"],
        ["He did not open the door", "बो दरवाजा खोल नङा दं", "bo daravājā khol naṅā dong"],
        ["She did not write", "बि लिर नङा दं", "bi lir naṅā dong"],
        ["We did not finish", "जिंग फोर नङा दं", "jiṅ phor naṅā dong"],
        ["They did not wait", "बिफां थां नङा दं", "biphāṅ thāṅ naṅā dong"],
        ["I was not there", "आँ दा नङा दं", "āṅ dā naṅā dong"],
        ["It did not rain", "दै थां नङा दं", "dai thāṅ naṅā dong"],
        ["He did not agree", "बो राजि नङा दं", "bo rāji naṅā dong"],
        ["We did not meet", "जिंग मोन नङा दं", "jiṅ mon naṅā dong"],
        ["She did not answer", "बि जवाब हो नङा दं", "bi javāb ho naṅā dong"],
        ["I did not forget", "आँ गोम नङा दं", "āṅ gom naṅā dong"],
        ["You did not try", "नों कोशिश नङा दं", "noṅ kōśiś naṅā dong"],
        ["They did not return", "बिफां फिन नङा दं", "biphāṅ phin naṅā dong"],
    ],
    531: [
        ["I will not go", "आँ तों नङागो", "āṅ toṅ naṅāgo"],
        ["You will not eat", "नों जा नङागो", "noṅ jā naṅāgo"],
        ["He will not come", "बो विन नङागो", "bo vin naṅāgo"],
        ["She will not leave", "बि चल नङागो", "bi cal naṅāgo"],
        ["We will not forget", "जिंग गोम नङागो", "jiṅ gom naṅāgo"],
        ["They will not come tomorrow", "बिफां गाब्ला विन नङागो", "biphāṅ gāblā vin naṅāgo"],
        ["I will not tell anyone", "आँ गोथोनि बोल नङागो", "āṅ gothoni bol naṅāgo"],
        ["You will not regret", "नों पछताव नङागो", "noṅ pachatāv naṅāgo"],
        ["He will not agree", "बो राजि नङागो", "bo rāji naṅāgo"],
        ["She will not sing", "बि गान नङागो", "bi gān naṅāgo"],
        ["We will not stop", "जिंग रुक नङागो", "jiṅ ruk naṅāgo"],
        ["They will not pay", "बिफां पैसा हो नङागो", "biphāṅ paisā ho naṅāgo"],
        ["It will not happen", "निं हो नङागो", "nin ho naṅāgo"],
        ["I will not be late", "आँ देर नङागो", "āṅ der naṅāgo"],
        ["You will not fail", "नों फेल नङागो", "noṅ phel naṅāgo"],
        ["He will not return alone", "बो गोथो फिन नङागो", "bo gotho phin naṅāgo"],
        ["We will not give up", "जिंग हार नङागो", "jiṅ hār naṅāgo"],
        ["They will not build here", "बिफां दा बोन नङागो", "biphāṅ dā bon naṅāgo"],
        ["I will never lie", "आँ मिथिखौ नङा बोलगो", "āṅ mithikhau naṅā bolgo"],
        ["She will not marry him", "बि बिनि बिहो नङागो", "bi bini biho naṅāgo"],
    ],
    532: [
        ["Boy", "मुसा", "musā"],
        ["Boys", "मुसाफोर", "musāphor"],
        ["Girl", "मुसु", "musu"],
        ["Girls", "मुसुफोर", "musuphor"],
        ["Man", "मोथाइ", "mothāi"],
        ["Men", "मोथाइफोर", "mothāiphor"],
        ["Woman", "मिथाइ", "mithāi"],
        ["Women", "मिथाइफोर", "mithāiphor"],
        ["Lion", "सिंह", "siṃha"],
        ["Cow", "गोर", "gor"],
        ["Teacher (male)", "मास्तार", "māstār"],
        ["Teacher (female)", "मास्तारनि", "māstārani"],
        ["One tree", "गोथो गोजो", "gotho gojo"],
        ["Many trees", "बाहागो गोजो", "bāhāgo gojo"],
        ["One book", "गोथो पुस्तक", "gotho pustak"],
        ["Several books", "बाहागो पुस्तक", "bāhāgo pustak"],
        ["The boy runs", "मुसा दौड़ दिं", "musā dauṛ diṅ"],
        ["The girls sang", "मुसुफोर गान दं", "musuphor gān dong"],
        ["Good men help others", "गोजोन मोथाइफोर गोथो मदद ला दिं", "gojon mothāiphor gotho madad lā diṅ"],
        ["Those women are teachers", "उं मिथाइफोर मास्तार दं", "uṅ mithāiphor māstār dong"],
    ],
    533: [
        ["Fish in the river", "दरियाव मास", "dariyāw mās"],
        ["Birds on the roof", "छताव सिमफोर", "chatāw simphor"],
        ["Fruit in the basket", "टोकरीाव फल", "ṭokarīāw phal"],
        ["Money in the pocket", "जेबाव पैसा", "jebāw paisā"],
        ["Cat under the chair", "कुर्सी थालाव बिलाइ", "kursī thālāw bilāi"],
        ["Dog near the gate", "दरवाजा गाह्रि कुथि", "daravājā gāhri kuthi"],
        ["Books on the shelf", "अलमारीाव पुस्तक", "almārīāw pustak"],
        ["Flowers in the garden", "बागाव फुल", "bāgāw phul"],
        ["Students in the class", "क्लासाव विद्यार्थी", "klāsāw vidyārthī"],
        ["People at the market", "बाजाराव मानसि", "bājārāw mānasi"],
        ["Stars in the sky", "आकाशाव तारा", "ākāśāw tārā"],
        ["Boat on the water", "दैाव नाव", "daiāw nāw"],
        ["I put rice in the pot", "आँ हांडि मै हो दं", "āṅ hāṇḍi mai ho dong"],
        ["There is a hole in the wall", "दिबाराव गोथो छेद दं", "dibārāw gotho ched dong"],
        ["She kept fruit in the fridge", "बि फ्रिजाव फल राख दं", "bi frijāw phal rākh dong"],
        ["We sat on the grass", "जिंग घासाव बैठ दं", "jiṅ ghāsāw baiṭh dong"],
        ["The keys are in the drawer", "चाबि दराजाव दं", "cābi darājāw dong"],
        ["Children played in the field", "सोरफोर मैदानाव खेल दं", "sorphor maidānāw khel dong"],
        ["There is a temple on the hill", "दालाव गोथो थांसोलि दं", "dālāw gotho thāṃsoli dong"],
        ["He works at the office", "बो ऑफिसाव काम दिं", "bo ophīsāw kām diṅ"],
    ],
    534: [
        ["Near / beside (kol)", "गाह्रि", "gāhri"],
        ["Close (nede)", "गोबो", "gobo"],
        ["Inside (andar / ch)", "अन्दर / आव", "andara / āw"],
        ["On (te)", "आव", "āw"],
        ["Under (thalle)", "थालाव", "thālāw"],
        ["Behind (pichhe)", "पिसिन", "pisini"],
        ["In front (agge)", "सिंनि", "siṃni"],
        ["Between (vich)", "नि", "ni"],
        ["Until (talak)", "थां", "thāṅ"],
        ["Sit beside me", "आँनि गाह्रि बैठ", "āṅni gāhri baiṭh"],
        ["Stand near the door", "दरवाजा गाह्रि खड़", "daravājā gāhri khaṛ"],
        ["The cat is under the table", "बिलाइ मेज थालाव दं", "bilāi mej thālāw dong"],
        ["The picture is on the wall", "फोटो दिबाराव दं", "phoṭo dibārāw dong"],
        ["We work until evening", "जिंग सांजि थां काम दों", "jiṅ sāṃji thāṅ kām doṅ"],
        ["He lives near the river", "बो दरिया गाह्रि थां दिं", "bo dariyā gāhri thāṅ diṅ"],
        ["The shop is behind the post office", "दुकान पोस्ट ऑफिस पिसिन दं", "dukān posṭ ophīs pisini dong"],
        ["Keep shoes under the bed", "जूता बिस्तर थालाव राख", "jūtā bistar thālāw rākh"],
        ["Between you and me", "नों आँ नि", "noṅ āṅ ni"],
        ["Wait until I come", "आँ विन थां थां", "āṅ vin thāṅ thāṅ"],
        ["Come in front of me", "आँनि सिंनि विन", "āṅni siṃni vin"],
    ],
    535: [
        ["Subject: The boy reads", "मुसा पद दिं", "musā pad diṅ"],
        ["Object: I see him", "आँ बिनि नेउ दों", "āṅ bini neu doṅ"],
        ["With a pen (instrument)", "कलम सों", "kalam soṅ"],
        ["To me (dative)", "आँनि", "āṅni"],
        ["From the village", "गाउ निफ्राय", "gāu niphrāy"],
        ["Of Rama (genitive)", "रामनि", "rāmani"],
        ["On the roof (locative)", "छताव", "chatāw"],
        ["Give the book to her", "बिनि पुस्तक हो", "bini pustak ho"],
        ["He came by bus", "बो बस सों विन दं", "bo bas soṅ vin dong"],
        ["She wrote with chalk", "बि चक सों लिर दं", "bi cak soṅ lir dong"],
        ["Water flows from the tap", "टोंटि निफ्राय दै दं", "ṭoṇṭi niphrāy dai dong"],
        ["This is mother's sari", "निं आमानि साडि दं", "nin āmāni sāḍi dong"],
        ["The boy hid behind the door", "मुसा दरवाजा पिसिन लुक दं", "musā daravājā pisini luk dong"],
        ["I sat on the floor", "आँ फर्शाव बैठ दं", "āṅ pharśāw baiṭh dong"],
        ["They came from Udalguri", "बिफां उदलगुरि निफ्राय विन दं", "biphāṅ udalaguri niphrāy vin dong"],
        ["She cut with a knife", "बि चाकु सों काट दं", "bi cāku soṅ kāṭ dong"],
        ["We sent money to him", "जिंग बिनि पैसा हो दं", "jiṅ bini paisā ho dong"],
        ["The bird is on the branch", "सिम गाह्राव दं", "sim gāhrāw dong"],
        ["I learned from the teacher", "आँ मास्तार निफ्राय सिम दं", "āṅ māstār niphrāy sim dong"],
        ["He died of fever", "बो बुखार सों मर दं", "bo bukhār soṅ mar dong"],
    ],
    536: [
        ["Come!", "विन!", "vin!"],
        ["Go!", "तों!", "toṅ!"],
        ["Sit!", "बैठ!", "baiṭh!"],
        ["Eat!", "जा!", "jā!"],
        ["Drink water!", "दै नुं!", "dai nuṅ!"],
        ["Read!", "पद!", "pad!"],
        ["Write!", "लिर!", "lir!"],
        ["Listen!", "नुंथै!", "nunthai!"],
        ["Open the door!", "दरवाजा खोल!", "daravājā khol!"],
        ["Close it!", "बन्द हो!", "band ho!"],
        ["Please come (formal)", "थांखाय विन", "thāṅkhāy vin"],
        ["Please sit (formal)", "बैठ खालाम", "baiṭh khālam"],
        ["Do not go!", "जा नङा!", "jā naṅā!"],
        ["Do not shout!", "खोर नङा!", "khor naṅā!"],
        ["Let's go together", "जिंग गोथो तों", "jiṅ gotho toṅ"],
        ["Tell the truth!", "सोलों बोल!", "soloṅ bol!"],
        ["Help him!", "बिनि मदद हो!", "bini madad ho!"],
        ["Wait here!", "दा थां!", "dā thāṅ!"],
        ["Bring the book!", "पुस्तक ला!", "pustak lā!"],
        ["Forgive me!", "आँनि माफ हो!", "āṅni māph ho!"],
    ],
    537: [
        ["Today", "दिनि", "dini"],
        ["Tomorrow", "गाब्ला", "gāblā"],
        ["Yesterday", "मैया", "maiyā"],
        ["Day before yesterday", "मैया सों", "maiyā soṅ"],
        ["Now", "दा", "dā"],
        ["Morning", "फुंनि", "phuṅni"],
        ["Afternoon", "दुपर", "dupar"],
        ["Evening", "सांजि", "sāṃji"],
        ["Night", "राति", "rāti"],
        ["Week", "हफ्ता", "haftā"],
        ["Month", "मैना", "mainā"],
        ["Year", "बोसोर", "bosor"],
        ["Sometimes", "कदे कदे", "kade kade"],
        ["Always", "हर दिन", "har din"],
        ["Never", "कदे नङा", "kade naṅā"],
        ["I will come tomorrow morning", "आँ गाब्ला फुंनि विनगो", "āṅ gāblā phuṅni vingo"],
        ["We met yesterday evening", "जिंग मैया सांजि मोन दं", "jiṅ maiyā sāṃji mon dong"],
        ["He works every day", "बो हर दिन काम दिं", "bo har din kām diṅ"],
        ["At night it is quiet", "राति थांथि दं", "rāti thāṃthi dong"],
        ["See you next week", "फिन हफ्ताव मोनगो", "phin haftāw mongo"],
        ["She was born in 2010", "बि दो हजार दसाव जन्म दं", "bi do hajār dasāw janma dong"],
    ],
    538: [
        ["I feed the child", "आँ सोरनि जा हो दों", "āṅ sorani jā ho doṅ"],
        ["She makes him study", "बि बिनि पद ला दिं", "bi bini pad lā diṅ"],
        ["Mother puts the baby to sleep", "आमा सोनोसोनि सा ला दिं", "āmā sonosoni sā lā diṅ"],
        ["The teacher makes us read", "मास्तार जिंनि पद ला दिं", "māstār jiṅni pad lā diṅ"],
        ["I got the letter written", "आँ चिट्ठि लिर हो दं", "āṅ chiṭṭhi lir ho dong"],
        ["He had the house painted", "बो गोर रंग हो दं", "bo gor raṅ ho dong"],
        ["She made me laugh", "बि आँनि हस हो दं", "bi āṅni has ho dong"],
        ["We let them go", "जिंग बिफांनि जा हो दं", "jiṅ biphāṅni jā ho dong"],
        ["He showed the way", "बो रस्ता नेउ हो दं", "bo rastā neu ho dong"],
        ["I will get the work done", "आँ काम फोर होगो", "āṅ kām phor hogo"],
        ["They made him understand", "बिफां बिनि मोन हो दं", "biphāṅ bini mon ho dong"],
        ["Father made me sit", "बाफा आँनि बैठ हो दं", "bāphā āṅni baiṭh ho dong"],
        ["The doctor made him drink medicine", "डाक्टर बिनि दवाइ नुं हो दं", "ḍākṭar bini davāi nuṅ ho dong"],
        ["I had the car repaired", "आँ गाडि ठिक हो दं", "āṅ gāḍi ṭhik ho dong"],
        ["She gets clothes washed", "बि कपड़ नुं ला दिं", "bi kapaṛ nuṅ lā diṅ"],
        ["We teach children to write", "जिंग सोरफोरनि लिर ला दों", "jiṅ sorphorni lir lā doṅ"],
        ["He made the dog run", "बो कुथिनि दौड़ हो दं", "bo kuthini dauṛ ho dong"],
        ["Let me speak", "आँ लैब ला", "āṅ laib lā"],
        ["I will make you see", "आँ नोंनि नेउ होगो", "āṅ noṅni neu hogo"],
        ["They caused trouble", "बिफां समस्या हो दं", "biphāṅ samasyā ho dong"],
    ],
    539: [
        ["The boy went (masc. sing.)", "मुसा जा दं", "musā jā dong"],
        ["The girl went (fem. sing.)", "मुसु जा दं", "musu jā dong"],
        ["The boys went (masc. pl.)", "मुसाफोर जा दं", "musāphor jā dong"],
        ["The girls went (fem. pl.)", "मुसुफोर जा दं", "musuphor jā dong"],
        ["He is a good student", "बो गोजोन विद्यार्थी दं", "bo gojon vidyārthī dong"],
        ["She is a good student", "बि गोजोन विद्यार्थी दं", "bi gojon vidyārthī dong"],
        ["They (men) are teachers", "बिफां मास्तार दं", "biphāṅ māstār dong"],
        ["They (women) are teachers", "बिफां मास्तारनि दं", "biphāṅ māstārani dong"],
        ["This boy reads", "निं मुसा पद दिं", "nin musā pad diṅ"],
        ["This girl reads", "निं मुसु पद दिं", "nin musu pad diṅ"],
        ["Those men work", "उं मोथाइफोर काम दिं", "uṅ mothāiphor kām diṅ"],
        ["Those women work", "उं मिथाइफोर काम दिं", "uṅ mithāiphor kām diṅ"],
        ["The lion roared", "सिंह खोर दं", "siṃha khor dong"],
        ["The cow mooed", "गोर रो दं", "gor ro dong"],
        ["Many children play", "बाहागो सोर खेल दिं", "bāhāgo sor khel diṅ"],
        ["One boy, two boys", "गोथो मुसा, नेइ मुसा", "gotho musā, nei musā"],
        ["One girl, two girls", "गोथो मुसु, नेइ मुसु", "gotho musu, nei musu"],
        ["He speaks politely", "बो हौलै लैब दिं", "bo haulai laib diṅ"],
        ["They (mixed) left", "बिफां चल दं", "biphāṅ cal dong"],
        ["Elder speaks (respect)", "गोथो मानसि लैब दिं", "gotho mānasi laib diṅ"],
    ],
    540: [
        ["The work is done", "काम हो दं", "kām ho dong"],
        ["The letter has been sent", "चिट्ठि हो दं", "chiṭṭhi ho dong"],
        ["Food has been cooked", "खाम फोथो दं", "khām photho dong"],
        ["The house was built", "गोर बोन दं", "gor bon dong"],
        ["He had been informed", "बिनि बोल हो दं", "bini bol ho dong"],
        ["The match had started", "मेच सुरु हो जाब दं", "mec suru ho jāb dong"],
        ["It has been decided", "फैसला हो दं", "phaislā ho dong"],
        ["The bill was paid", "बिल हो दं", "bil ho dong"],
        ["The door was closed", "दरवाजा बन्द दं", "daravājā band dong"],
        ["The work will have been finished", "काम फोर होगो", "kām phor hogo"],
        ["The news has spread", "खबर फैल दं", "khabar phail dong"],
        ["He has been called", "बिनि बोल हो दं", "bini bol ho dong"],
        ["She has been chosen", "बिनि साय हो दं", "bini sāy ho dong"],
        ["We have been invited", "जिंग बोल हो दं", "jiṅ bol ho dong"],
        ["The field has been ploughed", "खेत हल जा दं", "khet hal jā dong"],
        ["The letter had been lost", "चिट्ठि गोम हो दं", "chiṭṭhi gom ho dong"],
        ["Money has been returned", "पैसा फिन हो दं", "paisā phin ho dong"],
        ["The problem was solved", "समस्या हल हो दं", "samasyā hal ho dong"],
        ["The book has been found", "पुस्तक लाब दं", "pustak lāb dong"],
        ["The rule has been changed", "नियम बदल दं", "niyam badal dong"],
    ],
    541: [
        ["I have been reading since morning", "आँ फुंनि निफ्राय पद दों", "āṅ phuṅni niphrāy pad doṅ"],
        ["He has been working for hours", "बो घण्टा निफ्राय काम दिं", "bo ghaṇṭā niphrāy kām diṅ"],
        ["She has been waiting long", "बि बाहागो थां दिं", "bi bāhāgo thāṅ diṅ"],
        ["We have been living here for years", "जिंग बोसोर निफ्राय दा थां दों", "jiṅ bosor niphrāy dā thāṅ doṅ"],
        ["They have been playing all day", "बिफां दिनफोर खेल दिं", "biphāṅ dinphor khel diṅ"],
        ["It had been raining", "दै थां दं", "dai thāṅ dong"],
        ["I had been studying before you came", "नों विन सों आँ पद दं", "noṅ vin soṅ āṅ pad dong"],
        ["He had been ill", "बो बिमार दं", "bo bimār dong"],
        ["She had been singing", "बि गान दं", "bi gān dong"],
        ["We had been walking", "जिंग चल दं", "jiṅ cal dong"],
        ["They had been building the road", "बिफां रस्ता बोन दं", "biphāṅ rastā bon dong"],
        ["How long have you been here?", "नों दा मोनखो थां दिं?", "noṅ dā monakho thāṅ diṅ?"],
        ["I have not been sleeping well", "आँ गोजोन सा नङा दों", "āṅ gojon sā naṅā doṅ"],
        ["He has been absent", "बो नेथ दं", "bo neth dong"],
        ["She has been teaching here", "बि दा पद दिं", "bi dā pad diṅ"],
        ["We have been trying hard", "जिंग मेहनत ला दों", "jiṅ mehnat lā doṅ"],
        ["They have been friends for long", "बिफां लाम दोस्त दं", "biphāṅ lām dost dong"],
        ["The baby has been crying", "सोनोसो रो दं", "sonoso ro dong"],
        ["I will have been working ten years", "आँ दस बोसोर काम ला दों", "āṅ das bosor kām lā doṅ"],
        ["By then she will have been studying", "दा बि पद ला दिं", "dā bi pad lā diṅ"],
    ],
    542: [
        ["I do not eat (simple negation)", "आँ जा नङा दों", "āṅ jā naṅā doṅ"],
        ["I do not want to eat", "आँ जानाय ला नङा दों", "āṅ jānāy lā naṅā doṅ"],
        ["He is not here", "बो दा नङा दं", "bo dā naṅā dong"],
        ["He does not want to go", "बो तोंनाय ला नङा दिं", "bo toṅnāy lā naṅā diṅ"],
        ["There is no sugar", "चिनि नङा दं", "cini naṅā dong"],
        ["I don't want sugar", "आँ चिनि ला नङा दों", "āṅ cini lā naṅā doṅ"],
        ["She did not come", "बि विन नङा दं", "bi vin naṅā dong"],
        ["She did not want to come", "बि विन्नाय ला नङा दं", "bi vinnāy lā naṅā dong"],
        ["We will not buy it", "जिंग खरिद नङागो", "jiṅ kharid naṅāgo"],
        ["We don't want to buy it", "जिंग खरिदनाय ला नङा दों", "jiṅ kharidnāy lā naṅā doṅ"],
        ["No, that is wrong", "ना, निं गलत दं", "nā, nin galat dong"],
        ["I need not go", "आँ तों नङा दों", "āṅ toṅ naṅā doṅ"],
        ["I refuse / I don't want", "आँ ला नङा दों", "āṅ lā naṅā doṅ"],
        ["He has no fear", "बिनि डर नङा", "bini ḍar naṅā"],
        ["He doesn't want to try", "बो कोशिश ला नङा दिं", "bo kōśiś lā naṅā diṅ"],
        ["Don't! (prohibition)", "नङा!", "naṅā!"],
        ["Please don't", "थांखाय नङा", "thāṅkhāy naṅā"],
        ["I am not hungry", "आँ भुख नङा दों", "āṅ bhukh naṅā doṅ"],
        ["I don't feel like eating", "आँ जानाय मोन नङा दों", "āṅ jānāy mon naṅā doṅ"],
        ["They said no", "बिफां ना बोल दं", "biphāṅ nā bol dong"],
    ],
}
