# Bodo Lesson 1 — Script & pronunciation (chapter IDs 501–509).
# Columns: English, Bodo (Devanagari), Transliteration.

LESSONS_S1 = {
    501: [
        ["Bodo uses the Devanagari alphabet in schools", "बोडोनि देवनागरी लिपि बाहागो दं", "bodonī devanāgarī lipi bāhāgo dong"],
        ["Short अ (a)", "अ", "a"],
        ["Long आ (aa)", "आ", "aa"],
        ["Short इ (i)", "इ", "i"],
        ["Long ई (ee)", "ई", "ee"],
        ["Short उ (u)", "उ", "u"],
        ["Long ऊ (oo)", "ऊ", "oo"],
        ["Vowel ए (e)", "ए", "e"],
        ["Vowel ऐ (ai)", "ऐ", "ai"],
        ["Vowel ओ (o)", "ओ", "o"],
        ["Vowel औ (au)", "औ", "au"],
        ["Vowels are written with clear height and length", "स्वरफोरा होन्नाय गोलो आरो दैखो", "svaraphorā honnāy golo āro daikho"],
        ["Practice writing अ आ इ ई", "अ आ इ ई लिर", "a ā i ī lira"],
        ["Good morning — फुंनि गोजोन्थं", "फुंनि गोजोन्थं", "phungni gojonthang"],
        ["Thank you — थांखाय", "थांखाय", "thāṅkhāy"],
    ],
    502: [
        ["Consonants are called by their place of articulation", "ब्यञ्जनफोरा उच्चारखौ थाखाय होनाय", "byañjanaphorā uccārakhā thākhāy honāy"],
        ["Velar क ख ग घ ङ", "क ख ग घ ङ", "ka kha ga gha ṅa"],
        ["Palatal च छ ज झ ञ", "च छ ज झ ञ", "ca cha ja jha ña"],
        ["Retroflex ट ठ ड ढ ण", "ट ठ ड ढ ण", "ṭa ṭha ḍa ḍha ṇa"],
        ["Dental त थ द ध न", "त थ द ध न", "ta tha da dha na"],
        ["Labial प फ ब भ म", "प फ ब भ म", "pa pha ba bha ma"],
        ["Semi-vowel य र ल व", "य र ल व", "ya ra la va"],
        ["Sibilants श ष स", "श ष स", "śa ṣa sa"],
        ["Aspirated letters need a puff of air", "महाप्राण अक्षरफोरा वायु लागो", "mahāprāṇ akṣaraphorā vāyū lāgo"],
        ["Unaspirated क is light", "अल्पप्राण ककार हल्का", "alpaprāṇ kakāra halkā"],
        ["Practice: क-ग, च-ज, ट-ड", "क-ग च-ज ट-ड सोलों", "ka-ga ca-ja ṭa-ḍa soloṅ"],
        ["Nasal ङ matches velars", "कवर्गनि थाङ ङ्", "kavargani thāṅ ṅ"],
        ["ञ follows palatals", "तालब्यवर्गनि थाङ ञ्", "tālyavargani thāṅ ñ"],
        ["Retroflex ट sounds farther back than त", "मूर्धन्य ट दन्त्य त खोमा", "mūrdhanya ṭa dantya ta khomā"],
        ["Read syllables slowly first", "प्रथम धीरै सिलेबल पड", "prathama dhīrai silebala paḍa"],
        ["Repeat after the teacher", "गुरुनि उनावै फिन फिन नुन", "guruni unāwai phin phin nun"],
    ],
    503: [
        ["Barakhadi: each consonant + vowel sign", "बरखादि: ब्यञ्जन + स्वरचिन्ह", "barakhādi: byañjana + svaracihna"],
        ["क + अ = क (ka)", "क", "ka"],
        ["क + आ = का (kaa)", "का", "kā"],
        ["क + इ = कि (ki)", "कि", "ki"],
        ["क + ई = की (kii)", "की", "kī"],
        ["क + उ = कु (ku)", "कु", "ku"],
        ["क + ऊ = कू (kuu)", "कू", "kū"],
        ["क + ए = के (ke)", "के", "ke"],
        ["क + ऐ = कै (kai)", "कै", "kai"],
        ["क + ओ = को (ko)", "को", "ko"],
        ["क + औ = कौ (kau)", "कौ", "kau"],
        ["Practice: गा गि गु गे…", "गा गि गु गे लिर", "gā gi gu ge lira"],
        ["Each consonant has a full vowel row", "प्रत्येक ब्यञ्जनाव स्वरफोरा दं", "pratyeka byañjanāw svaraphorā dong"],
        ["Read aloud: ख खा खि…", "ख खा खि उच्चार", "kha khā khi uccāra"],
        ["Write from memory: च चा चि…", "च चा चि स्मरणै", "ca cā ci smaraṇai"],
        ["Read words: दै (water), गोर (house)", "दै गोर पड", "dai gor paḍa"],
    ],
    504: [
        ["Aspiration: ख is not k + h as in English", "ख इङ्लिस ख’ नङा", "kha iṅglis kha’ naṅā"],
        ["Retroflex ट is made with the tongue curled back", "ट मूर्धन्य जिभ गुबुन", "ṭa mūrdhanya jibha gubun"],
        ["Dental त touches near the teeth", "त दन्त्य दाँत सम", "ta dantya dā̃t sama"],
        ["Do not mix up श and ष", "श ष फराय", "śa ṣa pharāy"],
        ["Long vowels are held longer", "दीर्घ स्वर दैखो", "dīrgha svara daikho"],
        ["अनुस्वार follows the vowel in the syllable", "अनुस्वार स्वरनि थाङ", "anusvāra svarani thāṅ"],
        ["Avoid English r for Bodo र", "इङ्लिस r रनि बाहागो नङा", "iṅglis r rani bāhāgo naṅā"],
        ["Practice pairs: प फ, ब भ", "प फ ब भ मिल", "pa pha ba bha mila"],
        ["Listen and repeat three times", "गोबुन नुंथै फिन फिन सोम", "gobun nunthai phin phin soma"],
        ["Stress usually falls on the first heavy syllable", "बल गोबो लाम स्वराव", "bala gobo lāma svarāw"],
        ["Nasal sounds are light, not full English n", "अनुनासिक हल्का", "anunāsika halkā"],
        ["Record yourself and compare", "रেকर्ड खालामै तुलना", "rekord khālamai tulnā"],
        ["Read: आं दै जादों (I am eating)", "आं दै जादों", "āṅ dai jādong"],
        ["Clear sounds matter more than speed", "स्पष्ट उच्चार बेग खोमा", "spaṣṭa uccāra bega khomā"],
    ],
    505: [
        ["Anusvār (ं) sounds like the class nasal", "अनुस्वार वर्गीय अनुनासिक", "anusvāra vargīya anunāsika"],
        ["Before क ख ग घ → ङ्", "कवर्ग उनावै ङ्", "kavarga unāwai ṅ"],
        ["Before च छ ज झ → ञ्", "चवर्ग उनावै ञ्", "cavarga unāwai ñ"],
        ["Before ट ठ ड ढ → ण्", "टवर्ग उनावै ण्", "ṭavarga unāwai ṇ"],
        ["Before त थ द ध → न्", "तवर्ग उनावै न्", "tavarga unāwai n"],
        ["Before प फ ब भ → म्", "पवर्ग उनावै म्", "pavarga unāwai m"],
        ["Example: संगीत (music)", "संगीत", "saṅgīt"],
        ["Example: गङ्गा (Ganga)", "गङ्गा", "gaṅgā"],
        ["Example: अञ्जलि (offering)", "अञ्जलि", "añjali"],
        ["In handwriting the dot may be small", "हस्तलेखाय बिन्दु हिलो", "hastalekhāy bindu hilo"],
        ["Pronounce the nasal softly", "अनुनासिक मृदु", "anunāsika mṛdu"],
        ["Practice: संथिया, पंचायत", "संथिया पंचायत", "saṅthiyā pañcāyat"],
        ["Do not skip the nasal", "अनुस्वार नङा", "anusvāra naṅā"],
        ["Listen to fluent readers", "दक्से पढ़नाय गोबुन", "dakse paḍhanāy gobun"],
        ["Read: बोडो गीत", "बोडो गीत", "boḍo gīt"],
    ],
    506: [
        ["Conjuncts join consonants without a vowel between", "जुड़ाक्षर माजां स्वर नङा", "juṛākṣara mājā̃ svara naṅā"],
        ["क् + त = क्त", "क्त", "kta"],
        ["प् + त = प्त", "प्त", "pta"],
        ["न् + त = न्त", "न्त", "nta"],
        ["स् + त = स्त", "स्त", "sta"],
        ["म् + प = म्प", "म्प", "mpa"],
        ["Split conjuncts from left to right", "दाङनिफ्राय दायनाव पड", "dāṅniphrāy dāyānāw paḍa"],
        ["Practice: प्र ट्र क्ष", "प्र ट्र क्ष लिर", "pra ṭra kṣa lira"],
        ["Common clusters: स्त स्प स्म", "स्त स्प स्म", "sta spa sma"],
        ["Write: विद्यालय, सत्य", "विद्यालय सत्य", "vidyālaya satya"],
        ["Read slowly: अस्ति", "अस्ति", "asti"],
        ["Release each part of the cluster clearly", "जुड़ा खोमै स्पष्ट", "juṛā khomai spaṣṭa"],
        ["Example: पुस्तक", "पुस्तक", "pustak"],
        ["Example: संस्कार", "संस्कार", "saṃskāra"],
    ],
    507: [
        ["र् in प्र त्र क्र comes after the first part", "प्र त्र क्र रि दाम", "pra tra kra ri dām"],
        ["प्र = प् + र", "प्र", "pra"],
        ["त्र", "त्र", "tra"],
        ["क्र", "क्र", "kra"],
        ["ग्र", "ग्र", "gra"],
        ["द्र", "द्र", "dra"],
        ["श्र", "श्र", "śra"],
        ["When र is first: र्क र्ग", "र्क र्ग", "rka rga"],
        ["Practice: प्रथम, त्रि", "प्रथम त्रि", "prathama tri"],
        ["Read: गुरु, श्री", "गुरु श्री", "guru śrī"],
        ["Do not add a vowel after half-र", "र् उनावै स्वर नङा", "r unāwai svara naṅā"],
        ["Write five words with प्र", "प्र गुदि पाँच", "pra gudi pā̃c"],
        ["Cluster drill: ब्र भ्र म्र", "ब्र भ्र म्र", "bra bhra mra"],
    ],
    508: [
        ["ह् combines with many letters", "ह् बाहागो दिहुन", "h bāhāgo dihun"],
        ["क्ष is taught as one letter", "क्ष गोथो अक्षर", "kṣa gotho akṣara"],
        ["ज्ञ is taught as one letter", "ज्ञ गोथो अक्षर", "jña gotho akṣara"],
        ["ह is from the throat", "ह कण्ठ्य", "ha kaṇṭhya"],
        ["Practice: महा, वह", "महा वह", "mahā vaha"],
        ["Read: साहित्य, बाहिर", "साहित्य बाहिर", "sāhitya bāhira"],
        ["ह at word end is short", "ह अन्त हलन्त", "ha anta halanta"],
        ["Write: अनुभव, स्नेह", "अनुभव स्नेह", "anubhava sneha"],
        ["Common: नमस्कार, दुःख", "नमस्कार दुःख", "namaskār duḥkha"],
        ["Drill: योग, रोग", "योग रोग", "yoga roga"],
    ],
    509: [
        ["Some fonts show clusters differently", "फन्ट जुड़ा फराय", "phanṭa juṛā pharāy"],
        ["क्ष ज्ञ may be written as ligatures", "क्ष ज्ञ लिगेचर", "kṣa jña ligecara"],
        ["Print and handwriting shapes may differ", "छाप आ हस्तलेख फराय", "chāpa ā hastalekha pharāy"],
        ["Rare clusters need careful copying", "दुर्लभ जुड़ा सावधानै", "durlabha juṛā sāvadhānai"],
        ["Practice: कर्म, धर्म", "कर्म धर्म", "karma dharma"],
        ["Read a cluster list from your book", "पुस्तक निफ्राय जुड़ा सूची", "pustak niphrāy juṛā sūcī"],
        ["Write your name in Devanagari", "नोंनि नां देवनागरी", "nongni nā̃ devanāgarī"],
        ["Check dots for ं and ः", "बिन्दु विसर्ग", "bindu visarga"],
        ["Virām (्) removes the vowel", "विराम स्वर होनाय", "virām svara honāy"],
        ["Example: नमस्ते", "नमस्ते", "namaste"],
        ["Example: हरि ॐ", "हरि ॐ", "hari om"],
        ["Keep practising every day", "मैनै मैनै सोलों", "mainai mainai soloṅ"],
    ],
}
