# Bodo Lesson 3 — chunk B (chapter IDs 566–596).

LESSONS_S3B = {
    566: [
        ["I want him to study", "आँ बिनि पद ला दों", "āṅ bini pad lā doṅ"],
        ["She wants us to wait", "बि जिंनि थां ला दिं", "bi jiṅni thāṅ lā diṅ"],
        ["They want me to sing", "बिफां आँ गान ला दिं", "biphāṅ āṅ gān lā diṅ"],
        ["We want you to be careful", "जिंग नोंनि सावधान थां ला दों", "jiṅ noṅni sāvadhān thāṅ lā doṅ"],
        ["He wants his son to work hard", "बो बिनि मुसानि मेहनत ला दिं", "bo bini musāni mehnat lā diṅ"],
        ["Mother wants me to marry", "आमा आँ बिहो ला दिं", "āmā āṅ biho lā diṅ"],
        ["I don't want them to fight", "आँ बिफां लडाइ नङा ला दों", "āṅ biphāṅ laḍāi naṅā lā doṅ"],
        ["The teacher wants students to be quiet", "मास्तार सोरफोर थांथि थां ला दिं", "māstār sorphor thāṃthi thāṅ lā diṅ"],
        ["She wants the doctor to come", "बि डाक्टर विन ला दिं", "bi ḍākṭar vin lā diṅ"],
        ["I want you to understand", "आँ नोंनि मोन ला दों", "āṅ noṅni mon lā doṅ"],
        ["We want the government to help", "जिंग सरकारनि मदद ला दों", "jiṅ sarkārani madad lā doṅ"],
        ["He wants his friend to leave", "बो बिनि दोस्त चल ला दिं", "bo bini dost cal lā diṅ"],
        ["Do you want me to call?", "नों आँ फोन ला दिं नामा?", "noṅ āṅ fon lā diṅ nāmā?"],
        ["I want her to feel safe", "आँ बिनि सुरक्षित थां ला दों", "āṅ bini surakṣit thāṅ lā doṅ"],
        ["Parents want children to study", "बाफा-आमा सोर पद ला दिं", "bāphā-āmā sor pad lā diṅ"],
        ["She wants everyone to be happy", "बि गोथो खुसि थां ला दिं", "bi gotho khusi thāṅ lā diṅ"],
    ],
    567: [
        ["I am supposed to reach by nine", "आँ नौ वजाव फै ला दों", "āṅ nau vajāw phai lā doṅ"],
        ["You are supposed to wear uniform", "नों युनिफर्म पिन ला दिं", "noṅ yunipharm pin lā diṅ"],
        ["He is supposed to pay today", "बो दिनि हो ला दिं", "bo dini ho lā diṅ"],
        ["We are supposed to attend the meeting", "जिंग मिटिंगाव विन ला दों", "jiṅ miṭiṅgāw vin lā doṅ"],
        ["The train is supposed to arrive now", "ट्रेन दा फै ला दं", "ṭren dā phai lā dong"],
        ["I was supposed to call yesterday", "आँ मैया फोन ला दं", "āṅ maiyā fon lā dong"],
        ["Students are supposed to bring books", "विद्यार्थिफोर पुस्तक ला दिं", "vidyārthiphor pustak lā diṅ"],
        ["She is supposed to rest", "बि आराम ला दिं", "bi āram lā diṅ"],
        ["You were supposed to inform me", "नों आँनि बोल ला दं", "noṅ āṅni bol lā dong"],
        ["The shop is supposed to open at ten", "दुकान दस वजे खोल ला दं", "dukān das vaje khol lā dong"],
        ["I am not supposed to tell anyone", "आँ गोथोनि बोल नङा", "āṅ gothoni bol naṅā"],
        ["They are supposed to report early", "बिफां दैखो रिपोर्ट ला दिं", "biphāṅ daikho riporṭ lā diṅ"],
        ["What am I supposed to do?", "आँ मा दा ला दों?", "āṅ mā dā lā doṅ?"],
        ["The medicine is supposed to work fast", "दवाइ दैखो असर ला दं", "davāi daikho asar lā dong"],
        ["We were supposed to meet at six", "जिंग सोर वजे मोन दं", "jiṅ sor vaje mon dong"],
        ["He is supposed to be the chief guest", "बो मुख्य मेहमान हो ला दिं", "bo mukhya mehmān ho lā diṅ"],
    ],
    568: [
        ["I like to walk in the rain", "आँ दै थां चल ला दों", "āṅ dai thāṅ cal lā doṅ"],
        ["She likes to read before sleep", "बि सा सों पद ला दिं", "bi sā soṅ pad lā diṅ"],
        ["We like to eat together", "जिंग गोथो जा ला दों", "jiṅ gotho jā lā doṅ"],
        ["He doesn't like to wait", "बो थां ला नङा दिं", "bo thāṅ lā naṅā diṅ"],
        ["Children like to ask questions", "सोरफोर सोंनाय ला दिं", "sorphor soṃnāy lā diṅ"],
        ["I would like to visit your village", "आँ नोंनि गाउ जा ला दों", "āṅ noṅni gāu jā lā doṅ"],
        ["She likes to help in the kitchen", "बि रसुइ मदद ला दिं", "bi rasui madad lā diṅ"],
        ["Do you like to sing?", "नों गान ला दिं नामा?", "noṅ gān lā diṅ nāmā?"],
        ["We like to watch news", "जिंग खबर नेउ ला दों", "jiṅ khabar neu lā doṅ"],
        ["He likes to fix old things", "बो गोजोन गुदि ठिक ला दिं", "bo gojon gudi ṭhik lā diṅ"],
        ["I don't like to argue", "आँ बहस ला नङा", "āṅ bahas lā naṅā"],
        ["They like to travel by train", "बिफां ट्रेन सों सफर ला दिं", "biphāṅ ṭren soṅ safar lā diṅ"],
        ["Grandmother likes to tell stories", "आगो कथि बोल ला दिं", "āgo kathi bol lā diṅ"],
        ["I like to drink hot milk", "आँ गरम दूध नुं ला दों", "āṅ garam dūdh nuṅ lā doṅ"],
        ["She likes to dress neatly", "बि सफाइ सों कपड़ पिन ला दिं", "bi safāi soṅ kapaṛ pin lā diṅ"],
        ["We like to celebrate festivals", "जिंग उत्सव मन ला दों", "jiṅ utsav man lā doṅ"],
    ],
    569: [
        ["I listen to the radio", "आँ रेडियो नुंथ दों", "āṅ reḍiyo nunth doṅ"],
        ["She looks at the moon", "बि चन्द्रमा नेउ दिं", "bi candramā neu diṅ"],
        ["We agree to the plan", "जिंग योजनाव राजि दों", "jiṅ yojanāw rāji doṅ"],
        ["He replied to the letter", "बो चिट्ठिनि जवाब हो दं", "bo chiṭṭhini javāb ho dong"],
        ["They objected to the rule", "बिफां नियमाव इतराज हो दं", "biphāṅ niyamāw itarāj ho dong"],
        ["I belong to this village", "आँ निं गाउनि दं", "āṅ nin gāuni dong"],
        ["She listens to her teacher", "बि मास्तारनि नुंथ दिं", "bi māstārani nunth diṅ"],
        ["We pray to God every day", "जिंग हर दिन सिगाउनि प्रार्थना दों", "jiṅ har din sigāuni prārthanā doṅ"],
        ["He shouted to the crowd", "बो भीडाव खोर दं", "bo bhīḍāw khor dong"],
        ["I wrote to my brother", "आँ बिनि दानि चिट्ठि लिर दं", "āṅ bini dāni chiṭṭhi lir dong"],
        ["She waved to the children", "बि सोरफोरनि हाथ हल दं", "bi sorphorni hāth hal dong"],
        ["We bow to elders", "जिंग गोथो मानसिफोरनि निव दों", "jiṅ gotho mānasi-phorni niv doṅ"],
        ["He pointed to the map", "बो नक्शाव इशारा हो दं", "bo nakśāw iśārā ho dong"],
        ["I explained to the guests", "आँ मेहमानफोरनि समझ हो दं", "āṅ mehmānphorni samajh ho dong"],
        ["They clapped for the singer", "बिफां गायकनि तालि हो दं", "biphāṅ gāykani tāli ho dong"],
        ["She smiled at the baby", "बि सोरनि मुस्कान हो दं", "bi sorani muskān ho dong"],
    ],
    570: [
        ["I am fine (spoken short)", "आँ गोरै दों", "āṅ gorai doṅ"],
        ["What happened? (casual)", "मा हो दं?", "mā ho dong?"],
        ["Come here (informal)", "दा विन", "dā vin"],
        ["I don't know (short)", "मोन नङा", "mon naṅā"],
        ["Okay / yes (casual)", "ठीक / हो", "ṭhīk / ho"],
        ["Where are you going?", "मोन तों दिं?", "mon toṅ diṅ?"],
        ["See you later", "फिन मोन", "phin mon"],
        ["No problem", "समस्या नङा", "samasyā naṅā"],
        ["Hurry up", "दैखो हो", "daikho ho"],
        ["Leave it (don't bother)", "छाड दे", "chāḍ de"],
        ["Really? (surprise)", "सोलों नामा?", "soloṅ nāmā?"],
        ["I will come (short promise)", "विनगो", "vingo"],
        ["Don't worry", "फिकर नङा", "phikar naṅā"],
        ["That's enough", "बस दा", "bas dā"],
        ["Who knows? (shrug)", "माव्नो मोन?", "māwno mon?"],
        ["Same to you (reply)", "नोंनि सों", "noṅni soṅ"],
    ],
    571: [
        ["Good morning", "फुंनि गोजोन्थं", "phuṅni gojonthaṅ"],
        ["Good evening", "सांजि गोजोन्थं", "sāṃji gojonthaṅ"],
        ["Namaste / respectful greeting", "नमस्कार / थांखाय", "namaskār / thāṅkhāy"],
        ["Happy birthday", "जन्म दिननि बधाइ", "janma dinani badhāi"],
        ["Happy New Year", "गोदान बोसोरनि बधाइ", "godān bosorani badhāi"],
        ["Congratulations", "बधाइ", "badhāi"],
        ["Get well soon", "दैखो गोजोन हो", "daikho gojon ho"],
        ["May God bless you", "सिगाउ नोंनि राख", "sigāu noṅni rākh"],
        ["Long live (toast)", "जिन्दाबाद", "jindābād"],
        ["Welcome", "स्वागत", "svāgata"],
        ["Goodbye / go safely", "फिन मोन / थांथि तों", "phin mon / thāṃthi toṅ"],
        ["Happy Diwali", "दिवालिनि बधाइ", "divālini badhāi"],
        ["Happy festival", "उत्सवनि बधाइ", "utsavani badhāi"],
        ["May you prosper", "नों गोजोन थां", "noṅ gojon thāṅ"],
        ["Thank you very much", "बाहागो थांखाय", "bāhāgo thāṅkhāy"],
        ["With your permission (leave)", "नोंनि मान सों", "noṅni mān soṅ"],
    ],
    572: [
        ["I will eat and leave", "आँ खा के चल जागो", "āṅ khā ke cal jāgo"],
        ["Sit down and rest", "बैठ के आराम हो", "baiṭh ke āram ho"],
        ["He stood up and spoke", "बो खड़ हो के बोल दं", "bo khaṛ ho ke bol dong"],
        ["Come and see", "विन के नेउ", "vin ke neu"],
        ["She cried and slept", "बि रो के सा दं", "bi ro ke sā dong"],
        ["We read and discussed", "जिंग पद के गल हो दं", "jiṅ pad ke gal ho dong"],
        ["Open the door and enter", "दरवाजा खोल के अन्दर विन", "daravājā khol ke andar vin"],
        ["Think and answer", "सोच के जवाब हो", "soc ke javāb ho"],
        ["Finish work and go home", "काम फोर के गोर जा", "kām phor ke gor jā"],
        ["Wash hands and eat", "खौ धो के जा", "khau dhoke jā"],
        ["He ran and caught the bus", "बो दौड़ के बस फड़ दं", "bo dauṛ ke bas faṛ dong"],
        ["Listen carefully and write", "ध्यानै नुंथ के लिर", "dhyānai nunth ke lir"],
        ["She smiled and nodded", "बि मुस्कान के सिर हल दं", "bi muskān ke sir hal dong"],
        ["We met and planned", "जिंग मोन के योजना हो दं", "jiṅ mon ke yojanā ho dong"],
        ["Pack the bag and leave", "बेग पैक के चल", "beg paik ke cal"],
        ["Call me and confirm", "आँनि फोन के पक्का हो", "āṅni fon ke pakkā ho"],
    ],
    573: [
        ["Brother (to a boy)", "दा", "dā"],
        ["Sister (to a girl)", "बे", "be"],
        ["Uncle (father's brother)", "काका", "kākā"],
        ["Aunt", "काकी", "kākī"],
        ["Grandfather", "आगो", "āgo"],
        ["Grandmother", "आगो आमा", "āgo āmā"],
        ["Respected sir (to elder man)", "गोथो मानसि", "gotho mānasi"],
        ["Listen, friend (informal)", "सुन दोस्त", "sun dost"],
        ["Son", "सोन", "son"],
        ["Daughter", "सोनोसो", "sonoso"],
        ["Calling a stranger politely", "बाहा / बेहन", "bāhā / behan"],
        ["Hey there (very informal)", "ऐ नों", "ai noṅ"],
        ["Respected teacher", "मास्तार", "māstār"],
        ["Doctor (address)", "डाक्टर", "ḍākṭar"],
        ["Calling the waiter", "बाहा, दा विन", "bāhā, dā vin"],
        ["Young man", "मुसा", "musā"],
    ],
    574: [
        ["Oh! What a surprise!", "ओ! मा सरप्राइज!", "o! mā sarapraij!"],
        ["Alas! He is gone", "हाय! बो चल दं!", "hāy! bo cal dong!"],
        ["Wow! Beautiful!", "वाह! गोजोन!", "vāh! gojon!"],
        ["Ouch! It hurts", "ऐ! दुख दं!", "ai! dukh dong!"],
        ["Hey! Stop!", "ऐ! रुक!", "ai! ruk!"],
        ["Bravo! Well done", "शाबास! गोजोन हो!", "śābās! gojon ho!"],
        ["What nonsense!", "मा बकवास!", "mā bakavās!"],
        ["Thank heavens!", "सिगाउनि थांखाय!", "sigāuni thāṅkhāy!"],
        ["How sad!", "मा दुख!", "mā dukh!"],
        ["So sweet!", "बाहागो मिथा!", "bāhāgo mithā!"],
        ["What a noise!", "बाहागो शोर!", "bāhāgo śor!"],
        ["Impossible!", "नामुमकिन!", "nāmumakin!"],
        ["God forbid!", "सिगाउ नङा करे!", "sigāu naṅā kare!"],
        ["Hurry!", "दैखो!", "daikho!"],
        ["Silence!", "थांथि!", "thāṃthi!"],
        ["Look out!", "सावधान!", "sāvadhān!"],
    ],
    575: [
        ["May I come in?", "आँ अन्दर विन ला दों नामा?", "āṅ andar vin lā doṅ nāmā?"],
        ["Can you help me?", "नों आँनि मदद ला दिं नामा?", "noṅ āṅni madad lā diṅ nāmā?"],
        ["Could you pass the salt?", "नों निमख हो नामा?", "noṅ nimakh ho nāmā?"],
        ["Would you please sit?", "थांखाय बैठ", "thāṅkhāy baiṭh"],
        ["May I use your phone?", "आँ नोंनि फोन बाहागो ला दों नामा?", "āṅ noṅni fon bāhāgo lā doṅ nāmā?"],
        ["Can you repeat that?", "नों फिन बोल ला दिं नामा?", "noṅ phin bol lā diṅ nāmā?"],
        ["Would you mind waiting?", "नों थां ला दिं नामा?", "noṅ thāṅ lā diṅ nāmā?"],
        ["May I ask a question?", "आँ सोंनाय ला दों नामा?", "āṅ soṃnāy lā doṅ nāmā?"],
        ["Can you show the way?", "नों रस्ता नेउ ला दिं नामा?", "noṅ rastā neu lā diṅ nāmā?"],
        ["Could you speak slowly?", "नों हौलै लैब ला दिं नामा?", "noṅ haulai laib lā diṅ nāmā?"],
        ["May I take this seat?", "आँ निं सिट ला दों नामा?", "āṅ nin siṭ lā doṅ nāmā?"],
        ["Can you call a taxi?", "नों टैक्सी बोल ला दिं नामा?", "noṅ ṭaiksī bol lā diṅ nāmā?"],
        ["Would you like some tea?", "नोंनि चा ला दिं नामा?", "noṅni cā lā diṅ nāmā?"],
        ["May I leave early today?", "आँ दिनि दैखो चल ला दों नामा?", "āṅ dini daikho cal lā doṅ nāmā?"],
        ["Can you read this for me?", "नों निं आँनि लाम पद ला दिं नामा?", "noṅ nin āṅni lām pad lā diṅ nāmā?"],
        ["Could you keep my bag?", "नों आँनि बेग राख ला दिं नामा?", "noṅ āṅni beg rākh lā diṅ nāmā?"],
    ],
    576: [
        ["It might rain tomorrow", "गाब्ला दै थां ला दं", "gāblā dai thāṅ lā dong"],
        ["He may come late", "बो देर विन ला दं", "bo der vin lā dong"],
        ["We might take the bus", "जिंग बस ला दों", "jiṅ bas lā doṅ"],
        ["She might not agree", "बि राजि नङा", "bi rāji naṅā"],
        ["It may be true", "निं सोलों हो ला दं", "nin soloṅ ho lā dong"],
        ["I might forget; remind me", "आँ गोम ला दों; याद हो", "āṅ gom lā doṅ; yād ho"],
        ["The keys might be inside", "चाबि अन्दर हो ला दं", "cābi andar ho lā dong"],
        ["They might have left", "बिफां चल जाब दं", "biphāṅ cal jāb dong"],
        ["This might help", "निं मदद हो ला दं", "nin madad ho lā dong"],
        ["You might feel tired", "नों थाक ला दिं", "noṅ thāk lā diṅ"],
        ["The shop might be closed", "दुकान बन्द हो ला दं", "dukān band ho lā dong"],
        ["We might visit next week", "जिंग फिन हफ्ताव जा ला दों", "jiṅ phin haftāw jā lā doṅ"],
        ["He might call tonight", "बो राति फोन ला दिं", "bo rāti fon lā diṅ"],
        ["It might snow in winter", "थंडाव बर्फ थां ला दं", "thaṇḍāw baraf thāṅ lā dong"],
        ["She might know the answer", "बिनि जवाब मोन ला दिं", "bini javāb mon lā diṅ"],
        ["I might stay home", "आँ गोर थां ला दों", "āṅ gor thāṅ lā doṅ"],
    ],
    577: [
        ["a written letter", "लिर जाब चिट्ठि", "lir jāb chiṭṭhi"],
        ["boiled water", "उबल दै", "ubal dai"],
        ["fried bread", "तला रोटि", "talā roṭi"],
        ["broken chair", "टुट कुर्सि", "ṭuṭ kursi"],
        ["closed door", "बन्द दरवाजा", "band daravājā"],
        ["open window", "खुला खिड़कि", "khulā khiṛaki"],
        ["lost keys", "गोम चाबि", "gom cābi"],
        ["tired traveller", "थाक यात्री", "thāk yātrī"],
        ["cooked food", "फोथो खाम", "photho khām"],
        ["washed clothes", "धो कपड़", "dho kapaṛ"],
        ["painted wall", "रंग दिबार", "raṅ dibār"],
        ["signed form", "साइन फर्म", "sāin pharm"],
        ["packed bag", "पैक बेग", "paik beg"],
        ["frozen water", "जम दै", "jam dai"],
        ["roasted nuts", "भुन मेवा", "bhun mevā"],
        ["printed book", "छप पुस्तक", "chap pustak"],
    ],
    578: [
        ["the boy inside the house", "गोर अन्दरनि मुसा", "gor andarani musā"],
        ["the shop near the bridge", "पुल गाह्रि दुकान", "pul gāhri dukān"],
        ["people from the village", "गाउ निफ्राय मानसि", "gāu niphrāy mānasi"],
        ["the road to Kokrajhar", "कोक्राझारनि रस्ता", "kokrājhārani rastā"],
        ["trees along the river", "दरिया गाह्रि गोजो", "dariyā gāhri gojo"],
        ["the cat under the bed", "बिस्तर थालाव बिलाइ", "bistar thālāw bilāi"],
        ["the book on the table", "मेजाव पुस्तक", "mejāw pustak"],
        ["friends behind us", "जिंनि पिसिन दोस्त", "jiṅn pisini dost"],
        ["the school opposite the park", "पार्क सिंनि इस्कुल", "pārak siṃni iskul"],
        ["water in the pot", "हांडि दै", "hāṇḍi dai"],
        ["the man before me", "आँ सिंनि मोथाइ", "āṅ siṃni mothāi"],
        ["children between the rows", "लाइनाव सोर", "laināw sor"],
        ["the field beyond the hill", "दाल पार खेत", "dāl pār khet"],
        ["money in the pocket", "जेबाव पैसा", "jebāw paisā"],
        ["stars above the roof", "छताव तारा", "chatāw tārā"],
        ["the first house after the turn", "मोड फिन गोथो गोर", "moḍ phin gotho gor"],
    ],
    579: [
        ["May you live long", "नों देर जिउ ला था", "noṅ der jiu lā thā"],
        ["May God protect you", "सिगाउ नोंआङ राखा करो", "sigāu noṅāṅ rākhā karo"],
        ["May peace prevail", "समदि जागो", "samadi jāgo"],
        ["May your wishes come true", "नोंनि सोंनाय फुन जाय", "noṅni soṃnāy phun jāy"],
        ["May the festival bring joy", "पर्वाङ जोय लानि दों", "parvāṅ joy lāni dong"],
        ["May you succeed", "नों कामायाब जा", "noṅ kāmāyāb jā"],
        ["May there be rain for farmers", "खेतीगिरिनि थांथै दै थां", "khetīgiri thāṃthai dai thāṅ"],
        ["May the sick recover soon", "बिमारफोर लै दैखो ठिक जा", "bimārphor lai daikho ṭhik jā"],
        ["May our friendship last", "जिंनि दोस्ति दैखो नाय", "jiṅni dusti daikho nāy"],
        ["May no one go hungry", "मानसि भुखाव खोम", "mānasi bhukhāw khom"],
        ["May the children study well", "सोरफोर बाहागोनि पड", "soraphor bāhāgoni paḍa"],
        ["May the journey be safe", "यात्रा थांथै जा", "yātrā thāṃthai jā"],
        ["May your family be happy", "नोंनि गर बाहागो खुश थां", "noṅni gar bāhāgo khush thāṅ"],
        ["May truth win", "सोंलों जित", "soloṅ jit"],
        ["May we meet again", "फिन फिन मिलन फै", "phin phin milan phai"],
        ["May this house prosper", "निं गोर गोजो थां ना", "nin gor gojo thāṅ nā"],
    ],
    580: [
        ["Mother made the child sleep", "आमा सोरखौ नुंथाय", "āmā sorakhau nunthāy"],
        ["He got the car repaired", "बो गारि ठिक खालामाय", "bo gāri ṭhik khālamāy"],
        ["She had him write the letter", "बिनि बिफांखौ चिट्ठि लिर खालामाय", "bini biphāṅkhau chiṭṭhi lir khālamāy"],
        ["I will get the room painted", "आँ रुम रंग खालामों", "āṅ rum raṅ khālamoṅ"],
        ["They made us wait", "बिफां जिंखौ थां खालामाय", "biphāṅ jiṅkhau thāṅ khālamāy"],
        ["The teacher made students read aloud", "गुरु सोरफोरखौ जोरै पड खालामाय", "guru soraphorakhau jorai paḍa khālamāy"],
        ["Get this work done", "निं कम खालाम", "nin kam khālam"],
        ["She had the food cooked", "बिनि खाम फोथो खालामाय", "bini khām photho khālamāy"],
        ["He made the dog run away", "बो कुथिखौ फिन खालामाय", "bo kuthikhau phin khālamāy"],
        ["I can't make him understand", "आँ बिफांखौ सोंलों खालाम नङा", "āṅ biphāṅkhau soloṅ khālam naṅā"],
        ["We will get a new gate made", "जिंग गोदान गेट खालामगोन", "jiṅ godān geṭ khālamgon"],
        ["The boss got the report typed", "बस रिपोट टाइप खालामाय", "bas ripoṭ ṭāip khālamāy"],
        ["She makes everyone laugh", "बि मानसिफोरखौ हस खालाम", "bi mānasiaphorakhau has khālam"],
        ["Don't make the baby cry", "सोरखौ रो खालाम नङा", "sorkhau ro khālam naṅā"],
        ["He got his hair cut", "बो खुर खालामाय", "bo khur khālamāy"],
        ["They made him the leader", "बिफां बिफांखौ मुखिया खालामाय", "biphāṅ biphāṅkhau mukhiyā khālamāy"],
    ],
    581: [
        ["Someone is at the door", "मानसि दरवाजाव दं", "mānasi daravājāw dong"],
        ["I left something in the room", "आँ रुमाव मोनो खो", "āṅ rumāw mono kho"],
        ["Nothing is impossible", "मोनो नङा नामुमकिन", "mono naṅā nāmumakin"],
        ["Anyone can try", "मानसि कोशिश ला दं", "mānasi koshish lā dong"],
        ["Somewhere in the city", "सहराव मोनो थां", "saharāw mono thāṅ"],
        ["Somehow we managed", "मोनो मोनो जिंग निबटाय", "mono mono jiṅ nibṭāy"],
        ["Everybody was happy", "मानसिफोर खुश दं", "mānasiaphor khush dong"],
        ["Nowhere is safe without care", "सावधान नङा थांथै नङा", "sāvadhān naṅā thāṃthai naṅā"],
        ["Anything can happen", "मोनो हो ला दं", "mono ho lā dong"],
        ["Someone called you", "मानसिनि नोंखौ फोन खालाम", "mānasini noṅkhau fon khālam"],
        ["I need something to eat", "आँनि खाम लामोनो दं", "āṅni khām lāmono dong"],
        ["Nobody came", "मानसि नङा विन", "mānasi naṅā vin"],
        ["Everywhere was decorated", "थांथां सजाय दं", "thāṃthāṃ sajāy dong"],
        ["Sometimes I feel tired", "कदे कदे आँ थाक महसुस ला दों", "kade kade āṅ thāk mahasus lā doṅ"],
        ["Is there anywhere to sit?", "बैठनि थां मोनो दं नामा?", "baiṭhani thāṅ mono dong nāmā?"],
        ["Use anything you need", "जो लाम दं बाहागो", "jo lām dong bāhāgo"],
    ],
    582: [
        ["I have two brothers", "आँनि दा दा दं", "āṅni dā dā dong"],
        ["She has a fever", "बिनि बुखार दं", "bini bukhār dong"],
        ["We have a small house", "जिंनि गोर हिन दं", "jiṅni gor hin dong"],
        ["He has no money today", "बो दिनि पैसा नङा", "bo dini paisā naṅā"],
        ["Do you have children?", "नोंनि सोर दं नामा?", "noṅni sor dong nāmā?"],
        ["I have an idea", "आँनि सोंनाय दं", "āṅni soṃnāy dong"],
        ["The tree has many branches", "गोजोनि डालफोर बाह दं", "gojoni ḍālaphor bāh dong"],
        ["She has long hair", "बिनि खुर लाम दं", "bini khur lām dong"],
        ["We have time until evening", "जिंनि सम राति थां दं", "jiṅni sam rāti thāṅ dong"],
        ["He has a kind heart", "बो दिल नेक दं", "bo dil nek dong"],
        ["I have nothing to say", "आँनि बोलनि मोनो नङा", "āṅni bolani mono naṅā"],
        ["They have three cars", "बिफांनि थिन गारि दं", "biphāṅni thin gāri dong"],
        ["The bag has a hole", "बेगाव छेद दं", "begāw ched dong"],
        ["I have relatives in Delhi", "आँनि दिल्लियाव रिस्ता दं", "āṅni dilliyāw ristā dong"],
        ["She has courage", "बिनि हिम्मत दं", "bini himmat dong"],
        ["We have faith in God", "जिंनि सिगाउआव भरोसा दं", "jiṅni sigāuāw bharosā dong"],
    ],
    583: [
        ["What does this word mean?", "निं सोरनि मतलब मा दं?", "nin sorani matalab mā dong?"],
        ["I don't understand the meaning", "आँनि मतलब सोंलों नङा", "āṅni matalab soloṅ naṅā"],
        ["This sentence means peace", "निं वाक समदिनि मतलब दं", "nin vāk samadini matalab dong"],
        ["What do you mean?", "नोंनि मतलब मा दं?", "noṅni matalab mā dong?"],
        ["I meant to help", "आँनि मतलब मदद दं", "āṅni matalab madad dong"],
        ["Words can mean different things", "सोरफोरफोरनि मतलब फराय दं", "soraphoraphorani matalab pharāy dong"],
        ["Explain the meaning", "मतलब सोंलों हो", "matalab soloṅ ho"],
        ["That name means 'light'", "निं नां उजालानि मतलब दं", "nin nāṃ ujālāni matalab dong"],
        ["I didn't mean to hurt", "आँनि मतलब दुख दं नङा", "āṅni matalab dukh dong naṅā"],
        ["What is meant by this sign?", "निं निशाननि मतलब मा दं?", "nin niśānani matalab mā dong?"],
        ["The teacher explained the meaning", "गुरुनि मतलब सोंलों खालाम", "guruni matalab soloṅ khālam"],
        ["Double meaning (joke)", "दो मतलब", "do matalab"],
        ["I know what you mean", "आँ नोंनि मतलब मोन ला दों", "āṅ noṅni matalab mon lā doṅ"],
        ["This proverb means hard work", "निं कहावत मेहनतनि मतलब दं", "nin kahāwat mehanatani matalab dong"],
        ["Look up the meaning in a dictionary", "सोरकोशाव मतलब नाय", "sorkośāw matalab nāy"],
        ["His words meant danger", "बिनि सोरफोरनि मतलब खतरा दं", "bini soraphorani matalab khatarā dong"],
    ],
    584: [
        ["I came and he left", "आँ विन बो चल जाब दं", "āṅ vin bo cal jāb dong"],
        ["But it is raining", "थां दै थां दं", "thāṅ dai thāṅ dong"],
        ["Because I was ill", "आँ बिमार दं बिफिन", "āṅ bimār dong bifin"],
        ["So we stayed home", "जिंग गोर थां दं", "jiṅ gor thāṅ dong"],
        ["He said that he will come", "बो बोल दं बो विन ला दंगोन", "bo bol dong bo vin lā dangona"],
        ["Although it was late, we went", "देर दं थां जिंग जा दं", "der dong thāṅ jiṅ jā dong"],
        ["Though tired, she worked", "थाक बि कम ला दं", "thāk bi kam lā dong"],
        ["Still I hope", "फिन आँ उमेद ला दों", "phin āṅ umed lā doṅ"],
        ["Yet nobody came", "थां मानसि नङा विन", "thāṅ mānasi naṅā vin"],
        ["Bread and milk", "रोटि आरो दुध", "roṭi āro dudh"],
        ["Slow but steady", "हौलै थां लगातार", "haulai thāṅ lagātār"],
        ["Because of rain the match stopped", "दै बिफिन मेच रुक जाब दं", "dai bifin mec ruk jāb dong"],
        ["So that children may learn", "सोरफोर सिखन लाम", "soraphor sikhan lām"],
        ["I think that it is true", "आँ सोंलों ला दों निं सोंलों दं", "āṅ soloṅ lā doṅ nin soloṅ dong"],
        ["He ran but missed the bus", "बो दौड बस छुट जाब दं", "bo dauḍ bas chuṭ jāb dong"],
        ["Although old, he is active", "बुजुर्ग थां बो सक्रिय दं", "bujurg thāṅ bo sakriy dong"],
    ],
    585: [
        ["As you wish", "नोंनि सोंनाय बाहागो", "noṅni soṃnāy bāhāgo"],
        ["Tea or coffee?", "चा नामा कफि?", "cā nāmā kafi?"],
        ["Neither he nor she came", "बो नङा बि नङा विन", "bo naṅā bi naṅā vin"],
        ["I have neither time nor money", "आँनि ना सम ना पैसा", "āṅni nā sam nā paisā"],
        ["If it rains, we will stay", "जे दै थां जिंग थां ला दों", "je dai thāṅ jiṅ thāṅ lā doṅ"],
        ["In case you need help", "जे मदद लाम दं", "je madad lām dong"],
        ["Provided you agree", "जे नों राजि", "je noṅ rāji"],
        ["Or else we cancel", "नङा जिंग रद खालाम", "naṅā jiṅ rada khālam"],
        ["Neither this nor that", "ना निं ना निं", "nā nin nā nin"],
        ["As I told you", "आँ नोंखौ दस दं बाहागो", "āṅ noṅkhau das dong bāhāgo"],
        ["Coffee or tea — your choice", "कफि नामा चा — नोंनि मर्जि", "kafi nāmā cā — noṅni marji"],
        ["If not today, then tomorrow", "दिनि नङा गाब्ला", "dini naṅā gāblā"],
        ["Neither here nor there", "ना निं थां ना निं थां", "nā nin thāṅ nā nin thāṅ"],
        ["As long as you are honest", "नों इमानदार दं थां", "noṅ imānadār dong thāṅ"],
        ["In case of emergency call police", "हडबडि पुलिसखौ फोन हो", "haḍabadi puliskhau fon ho"],
        ["Either come or send word", "जां विन जां खोर हो", "jāṅ vin jāṅ khor ho"],
    ],
    586: [
        ["After dinner we walked", "राति खाम फिन जिंग टुर", "rāti khām phin jiṅ ṭur"],
        ["Then he spoke", "फिन बो बोल", "phin bo bol"],
        ["As far as I know", "आँ मोन ला दों थां", "āṅ mon lā doṅ thāṅ"],
        ["As long as you stay, I am happy", "नों थां दं थां आँ खुश दों", "noṅ thāṅ dong thāṅ āṅ khush doṅ"],
        ["As if nothing happened", "मोनो नङा हो बाहागो", "mono naṅā ho bāhāgo"],
        ["After the exam we rested", "परीक्षा फिन जिंग आराम खालाम", "parīkṣā phin jiṅ ārām khālam"],
        ["Then the bus arrived", "फिन बस विन", "phin bas vin"],
        ["As far as the eye can see", "अख नुंथै वेख ला दं थां", "akh nunthai vekh lā dong thāṅ"],
        ["As long as there is life", "जान दं थां", "jān dong thāṅ"],
        ["He looked as if he was afraid", "बो डर बाहागो वेख", "bo ḍar bāhāgo vekh"],
        ["After you finish, call me", "मुक फिन आँखौ फोन हो", "muk phin āṅkhau fon ho"],
        ["Then we will decide", "फिन जिंग फैसला होगोन", "phin jiṅ phaislā hogona"],
        ["As far as this matter goes", "निं मामलाव थां", "nin māmalaw thāṅ"],
        ["As long as it takes", "जिन सम लाग", "jina sam lāg"],
        ["She acted as if she knew", "बि मोन बाहागो चाल चल", "bi mon bāhāgo cāl cal"],
        ["After the rain, the air was fresh", "दै फिन हावा ताजा दं", "dai phin hāvā tājā dong"],
    ],
    587: [
        ["As soon as I reached, it rained", "आँ फै दै थां दं", "āṅ phai dai thāṅ dong"],
        ["Once you try, you will like it", "इ बार कोशिश खालाम फिन पसंद जा", "i bār koshish khālam phin pasand jā"],
        ["Rather than fight, talk", "लाड खालाम नङा गोबो हो", "lāḍ khālam naṅā gobo ho"],
        ["Instead of bus, take a train", "बस नङा ट्रेन ला", "bas naṅā ṭren lā"],
        ["So that nobody gets hurt", "मानसिफोर चोट नङा लागन लाम", "mānasiaphor coṭ naṅā lāgan lām"],
        ["As soon as the bell rang, class started", "घंटि बज फिन क्लास सुरु दं", "ghaṇṭi baja phin klās suru dong"],
        ["Once I know, I will tell", "आँ मोन ला दों फिन दसों", "āṅ mon lā doṅ phin dasoṅ"],
        ["Rather than wait, go ahead", "थां नङा फिन चल", "thāṅ naṅā phin cal"],
        ["Instead of sugar, use jaggery", "चिनि नङा गुड बाहागो", "cini naṅā guḍ bāhāgo"],
        ["Study so that you pass", "पड तां जे पास जा", "paḍ tāṅ je pās jā"],
        ["As soon as he saw me, he smiled", "बो आँ वेख फिन मुस्कान खालाम", "bo āṅ vekh phin muskān khālam"],
        ["Once the sun sets, come back", "सुरज डुब फिन मुड विन", "suraj ḍub phin muḍ vin"],
        ["Rather than blame, help", "दोस नङा मदद हो", "dos naṅā madad ho"],
        ["Instead of here, meet there", "निं नङा निं मिल", "nin naṅā nin mil"],
        ["Speak clearly so that all understand", "साफ बोल तां जे मानसिफोर सोंलों", "sāph bol tāṅ je mānasiaphor soloṅ"],
        ["As soon as possible", "जिन दैखो हो ला दं", "jina daikho ho lā dong"],
    ],
    588: [
        ["Conjunction 'and' — bread and milk", "आरो — रोटि आरो दुध", "āro — roṭi āro dudh"],
        ["Conjunction 'but' — small but strong", "थां — हिन थां मजबुत", "thāṅ — hin thāṅ majbut"],
        ["Because — late because of traffic", "बिफिन — ट्रैफिक बिफिन देर", "bifin — ṭraifik bifin der"],
        ["So — tired, so I rested", "बाहागो — थाक आँ आराम खालाम", "bāhāgo — thāk āṅ ārām khālam"],
        ["That — I think that it is true", "सोंलों — आँ सोंलों निं सोंलों दं", "soloṅ — āṅ soloṅ nin soloṅ dong"],
        ["Although — old, still active", "थां — बुजुर्ग थां फिन सक्रिय", "thāṅ — bujurg thāṅ phin sakriy"],
        ["Though — difficult, try", "थां — अखा, कोशिश हो", "thāṅ — akhā, koshish ho"],
        ["Still — I still hope", "फिन — आँ फिन उमेद ला दों", "phin — āṅ phin umed lā doṅ"],
        ["Yet — not done yet", "थां — हालै मुक नङा", "thāṅ — hālai muk naṅā"],
        ["Or — tea or coffee", "नामा — चा नामा कफि", "nāmā — cā nāmā kafi"],
        ["Neither… nor — neither he nor she", "ना — बो नङा बि नङा", "nā — bo naṅā bi naṅā"],
        ["If — if it rains", "जे — जे दै थां", "je — je dai thāṅ"],
        ["As — as I said", "बाहागो — आँ बो दं", "bāhāgo — āṅ bo dong"],
        ["After — after food", "फिन — खाम फिन", "phin — khām phin"],
        ["Before — before sleep", "मोथाइ — नुंथाइ मोथाइ", "mothāi — nunthāi mothāi"],
        ["Until — wait until evening", "थां — राति थां थां हो", "thāṅ — rāti thāṅ thāṅ ho"],
    ],
    589: [
        ["The sun rose. The birds sang.", "सुरज उग। सिमफोरनि गान दं।", "suraj uga. simphorani gān dong."],
        ["We combined: The sun rose and the birds sang.", "सुरज उग आरो सिमफोरनि गान दं।", "suraj uga āro simphorani gān dong."],
        ["He was tired. He slept.", "बो थाक दं। बो नुंथाय।", "bo thāk dong. bo nunthāy."],
        ["Combined: Tired from work, he slept.", "कम बिफिन थाक बो नुंथाय।", "kam bifin thāk bo nunthāy."],
        ["It rained. We stayed home.", "दै थां। जिंग गोर थां।", "dai thāṅ. jiṅ gor thāṅ."],
        ["Combined: Because it rained, we stayed home.", "दै बिफिन जिंग गोर थां।", "dai bifin jiṅ gor thāṅ."],
        ["She opened the book. She began to read.", "बिनि पुस्तक खोल। पड सुरु खालाम।", "bini pustak khol. paḍ suru khālam."],
        ["Combined: Opening the book, she began to read.", "पुस्तक खोल के बिनि पड सुरु खालाम।", "pustak khol ke bini paḍ suru khālam."],
        ["The train arrived. We boarded.", "ट्रेन विन। जिंग चढ़।", "ṭren vin. jiṅ chaṛh."],
        ["Combined: When the train arrived, we boarded.", "ट्रेन विन थां जिंग चढ़।", "ṭren vin thāṅ jiṅ chaṛh."],
        ["He studied hard. He passed.", "बो मेहनत खालाम। बो पास जा।", "bo mehanat khālam. bo pās jā."],
        ["Combined: Having studied hard, he passed.", "मेहनत खालाम के बो पास जा।", "mehanat khālam ke bo pās jā."],
        ["The shop closed. We returned.", "दुकान बन्द। जिंग मुड विन।", "dukān band. jiṅ muḍ vin."],
        ["Combined: The shop was closed, so we returned.", "दुकान बन्द दं बाहागो जिंग मुड विन।", "dukān band dong bāhāgo jiṅ muḍ vin."],
        ["I saw him. I waved.", "आँ बो वेख। आँ खुर हल।", "āṅ bo vekh. āṅ khur hal."],
        ["Combined: Seeing him, I waved.", "बो वेख के आँ खुर हल।", "bo vekh ke āṅ khur hal."],
    ],
    590: [
        ["I will go and see", "आँ जा के वेखों", "āṅ jā ke vekhoṅ"],
        ["Eat and drink", "जा आरो लां", "jā āro lām"],
        ["He read and understood", "बो पड के सोंलों लाय", "bo paḍ ke soloṅ lāy"],
        ["Come and sit", "विन आरो बैठ", "vin āro baiṭh"],
        ["She stood up and left", "बि खड़ हो के चल जा", "bi khaṛ ho ke cal jā"],
        ["We laughed and talked", "जिंग हस के गोबो खालाम", "jiṅ has ke gobo khālam"],
        ["Take and give", "ला के दे", "lā ke de"],
        ["He searched and found", "बो नाय के नाय लाय", "bo nāy ke nāy lāy"],
        ["Run and catch", "दौड के फड", "dauḍ ke phaḍ"],
        ["Listen and answer", "नुंथ के जवाब हो", "nunth ke javāb ho"],
        ["I tried but failed", "आँ कोशिश खालाम थां फेल जा", "āṅ koshish khālam thāṅ phel jā"],
        ["Write and show", "लिर के दिखा", "lir ke dikha"],
        ["Wash and wear", "धो के पा", "dho ke pā"],
        ["He paid and left", "बो भर के चल जा", "bo bhar ke cal jā"],
        ["Open and read", "खोल के पड", "khol ke paḍ"],
        ["We met and decided", "जिंग मिल के फैसला खालाम", "jiṅ mil ke phaislā khālam"],
    ],
    591: [
        ["Ravi wrote the letter", "रविनि चिट्ठि लिर", "ravini chiṭṭhi lir"],
        ["Passive: The letter was written by Ravi", "चिट्ठि रविनि लिर जाब दं", "chiṭṭhi ravini lir jāb dong"],
        ["The dog bit the man", "कुथिनि मानसिखौ काट", "kuthini mānasi khau kāṭ"],
        ["The man was bitten by the dog", "मानसि कुथिनि काट जाब दं", "mānasi kuthini kāṭ jāb dong"],
        ["They built the bridge", "बिफां पुल बानाय", "biphāṅ pul bānāy"],
        ["The bridge was built by them", "पुल बिफांनि बानाय जाब दं", "pul biphāṅni bānāy jāb dong"],
        ["She cooks food", "बि खाम फोथो", "bi khām photho"],
        ["Food is cooked by her", "खाम बिनि फोथो जा दं", "khām bini photho jā dong"],
        ["We will finish the work", "जिंग कम मुकगोन", "jiṅ kam mukagon"],
        ["The work will be finished by us", "कम जिंनि मुक जा दं", "kam jiṅni muk jā dong"],
        ["He opened the door", "बो दरवाजा खोल", "bo daravājā khol"],
        ["The door was opened by him", "दरवाजा बोनि खोल जाब दं", "daravājā boni khol jāb dong"],
        ["They are painting the wall", "बिफां दिबार रंग खालाम", "biphāṅ dibār raṅ khālam"],
        ["The wall is being painted", "दिबार रंग जा दं", "dibār raṅ jā dong"],
        ["I have posted the letter", "आँ चिट्ठि पोस्ट खालाम", "āṅ chiṭṭhi posṭ khālam"],
        ["The letter has been posted", "चिट्ठि पोस्ट जाब दं", "chiṭṭhi posṭ jāb dong"],
    ],
    592: [
        ["Someone stole my cycle", "मानसिनि आँनि साइकल चोर खालाम", "mānasini āṅni sāikal cor khālam"],
        ["My cycle got stolen", "आँनि साइकल चोर जाब दं", "āṅni sāikal cor jāb dong"],
        ["Water fills the pot", "दै हांडि भर", "dai hāṇḍi bhar"],
        ["The pot gets filled with water", "हांडि दैनि भर जा दं", "hāṇḍi daini bhar jā dong"],
        ["Heat opened the door", "गरमिनि दरवाजा खोल", "garmini daravājā khol"],
        ["The door opened from the heat", "गरमि बिफिन दरवाजा खुल जा", "garami bifin daravājā khul jā"],
        ["They elected him leader", "बिफां बिफांखौ मुखिया साय", "biphāṅ biphāṅkhau mukhiyā sāy"],
        ["He was elected leader", "बो मुखिया साय जाब दं", "bo mukhiyā sāy jāb dong"],
        ["The news surprised everyone", "खबरनि मानसिफोर हैरान खालाम", "khabarani mānasiaphor hairān khālam"],
        ["Everyone was surprised by the news", "मानसिफोर खबर बिफिन हैरान", "mānasiaphor khabar bifin hairān"],
        ["Time solves problems", "सम समस्या हल हो", "sam samasyā hal ho"],
        ["Problems get solved with time", "समस्याफोर सम बिफिन हल जा", "samasyāphor sam bifin hal jā"],
        ["We must do the work", "जिंनि कम खालाम लाम", "jiṅni kam khālam lām"],
        ["The work must be done", "कम खालाम लाम", "kam khālam lām"],
        ["He is reading the book", "बो पुस्तक पड", "bo pustak paḍ"],
        ["The book is being read", "पुस्तक पड जा दं", "pustak paḍ jā dong"],
    ],
    593: [
        ["I feel cold", "आँनि थंड लाग", "āṅni thaṇḍ lāg"],
        ["She feels happy today", "बि दिनि खुश महसुस हो", "bi dini khush mahasus ho"],
        ["I feel that you are right", "आँ सोंलों नों ठिक दं", "āṅ soloṅ noṅ ṭhik dong"],
        ["He feels pain in his leg", "बो खुराव दर्द महसुस हो", "bo khurāw dard mahasus ho"],
        ["We feel proud of you", "जिंनि नोंआव गर्व दं", "jiṅni noṅāw garv dong"],
        ["Do you feel better?", "नों ठिक महसुस ला दिं नामा?", "noṅ ṭhik mahasus lā diṅ nāmā?"],
        ["I think it will rain", "आँ सोंलों दै थां ला दं", "āṅ soloṅ dai thāṅ lā dong"],
        ["What do you think?", "नों मा सोंलों ला दिं?", "noṅ mā soloṅ lā diṅ?"],
        ["She thinks before she speaks", "बि बोलनि मोथाइ सोंलों", "bi bolani mothāi soloṅ"],
        ["I thought you knew", "आँ सोंलों नों मोन दं", "āṅ soloṅ noṅ mon dong"],
        ["We think this is fair", "जिंग सोंलों निं ठिक दं", "jiṅ soloṅ nin ṭhik dong"],
        ["He thinks too much", "बो बाहागो सोंलों", "bo bāhāgo soloṅ"],
        ["I feel like sleeping", "आँनि नुंथाइ मन हो", "āṅni nunthāi man ho"],
        ["She feels lonely in the city", "बि सहराव गोथो महसुस हो", "bi saharāw gotho mahasus ho"],
        ["They think we are wrong", "बिफां सोंलों जिंग गलत दं", "biphāṅ soloṅ jiṅ galat dong"],
        ["I don't think so", "आँ निं सोंलों नङा", "āṅ nin soloṅ naṅā"],
    ],
    594: [
        ["To kill two birds with one stone", "इ गोली बिफिन दा निशान", "i golī bifin dā niśān"],
        ["After a long time", "लाम सम फिन", "lām sam phin"],
        ["Heart to heart talk", "दिल गाह्रि दिलनि गोबो", "dil gāhri dilani gobo"],
        ["To turn a blind eye", "अन्धा बान के वेख", "andhā bān ke vekh"],
        ["To be in seventh heaven", "सातव आसमानाव दं", "sātava āsmānāw dong"],
        ["To add fuel to fire", "आगाव घि पा", "āgāw ghi pā"],
        ["Better late than never", "देर विन थां नङा नङा", "der vin thāṅ naṅā naṅā"],
        ["All that glitters is not gold", "जो चमक सोना नङा", "jo camak sonā naṅā"],
        ["Once in a blue moon", "बाहागो दैखो", "bāhāgo daikho"],
        ["To bite the hand that feeds", "जो रोटि दे बिनि खुर काट", "jo roṭi de bini khur kāṭ"],
        ["The early bird catches the worm", "जो दैखो उठ बो फायदा ला", "jo daikho uṭh bo phāydā lā"],
        ["Every cloud has a silver lining", "हर मुसिबताव रस्ता दं", "har musibatāw rastā dong"],
        ["To cry over spilt milk", "बीति गोबोनि थां रो", "bīti goboni thāṅ ro"],
        ["To hit the nail on the head", "सोंलों गोबो थां दस्तक", "soloṅ gobo thāṅ dastak"],
        ["Between the devil and the deep sea", "मोथाइ कुआ पिसिन खाइ", "mothāi kuā pisini khāi"],
        ["To mind one's own business", "आँनि गोबोनि थां थां", "āṅni goboni thāṅ thāṅ"],
    ],
    595: [
        ["To burn midnight oil", "रात भर पड खालाम", "rāt bhar paḍ khālam"],
        ["To smell a rat", "मोनो गडबड लाग", "mono gaḍabaḍ lāg"],
        ["To break the ice", "गोथो गोबो खालाम के माहौल ठिक", "gotho gobo khālam ke māhaul ṭhik"],
        ["To cost an arm and a leg", "बाहागो महंगा", "bāhāgo mahangā"],
        ["To let the cat out of the bag", "राज खोल दे", "rāj khol de"],
        ["To beat about the bush", "सोंलों गोबो नङा", "soloṅ gobo naṅā"],
        ["To pull someone's leg", "मानसिनि मजाक उडा", "mānasini majāk uḍā"],
        ["To be on cloud nine", "बाहागो खुश", "bāhāgo khush"],
        ["To get cold feet", "डर के मुड जा", "ḍar ke muḍ jā"],
        ["To throw in the towel", "हार मान ला", "hār mān lā"],
        ["To spill the beans", "मोनो दस दे", "mono das de"],
        ["A piece of cake", "बाहागो आसान कम", "bāhāgo āsān kam"],
        ["To hit the sack", "नुंथाइ चल जा", "nunthāi cal jā"],
        ["To kill time", "सम गज्जा", "sam gajjā"],
        ["To see eye to eye", "इ राय हो", "i rāy ho"],
        ["To be in hot water", "मुसिबताव फंस", "musibatāw phans"],
    ],
    596: [
        ["If you hurry, you will catch the bus", "जे नों दैखो खालाम बस फड ला दिं", "je noṅ daikho khālam bas phaḍ lā diṅ"],
        ["If I were rich, I would help more", "जे आँ धन दों ज्यादा मदद खालाम", "je āṅ dhan doṅ zyādā madad khālam"],
        ["Unless you try, you won't learn", "जे कोशिश नङा सिख नङा", "je koshish naṅā sikh naṅā"],
        ["Provided you pay, you can take it", "जे नों भर दे ला ला दिं", "je noṅ bhar de lā lā diṅ"],
        ["If it had rained, crops would have grown", "जे दै थां हौ फसल बाह दं", "je dai thāṅ hau phasal bāh dong"],
        ["If she had called, I would have come", "जे बिनि फोन खालाम आँ विन हौ", "je bini fon khālam āṅ vin hau"],
        ["If they agree, the deal is done", "जे बिफां राजि सौदा पक्का", "je biphāṅ rāji saudā pakka"],
        ["If not today, then tomorrow for sure", "दिनि नङा गाब्ला जरूर", "dini naṅā gāblā jarūr"],
        ["If you eat less spice, your health will be better", "जे कम मिर्च जा सेहत गोजो", "je kam mirc jā sehat gojo"],
        ["Were I you, I would not wait", "जे आँ नों दों थां नङा", "je āṅ noṅ doṅ thāṅ naṅā"],
        ["If the road is clear, we will reach fast", "जे रस्ता साफ जल्दी फै", "je rastā sāph jaldai phai"],
        ["If you had told me, I would have helped", "जे नों दस दे आँ मदद खालाम", "je noṅ das de āṅ madad khālam"],
        ["If winter sets in, wear warm clothes", "जे थंड पै जा गरम कपड पा", "je thaṇḍ pai jā garam kapaḍ pā"],
        ["If you don't ask, you won't get", "जे नङा फुं नङा मिल", "je naṅā phuṅ naṅā mil"],
        ["If everyone cooperates, work finishes fast", "जे मानसिफोर मिल कम दैखो मुक", "je mānasiaphor mil kam daikho muk"],
        ["If lightning strikes, stay indoors", "जे बिजली चम गोर अन्दर थां", "je bijalī cama gor andar thāṅ"],
    ],
}
