# Bodo Lesson 5 — Conversation practice, chunk B (chapter IDs 642–662).

LESSONS_S5B = {
    642: [
        ["I want to open an account", "आँ खाता खोलनाय ला दों", "āṅ khātā kholanāy lā doṅ"],
        ["Please fill this form", "थांखाय निं फर्म भर", "thāṅkhāy nin pharm bhar"],
        ["I need a cheque book", "आँनि चेक बुक लाम", "āṅni cek buk lām"],
        ["What is the minimum balance?", "गोथो बैलेन्स मा दं?", "gotho bailens mā dong?"],
        ["I want to deposit cash", "आँ नकद जमा ला दों", "āṅ nakad jamā lā doṅ"],
        ["Please count the notes", "नोट गिन", "noṭ gin"],
        ["I forgot my PIN", "आँ पिन गोम", "āṅ pin gom"],
        ["Block my card; it is lost", "आँनि कार्ड ब्लक हो; गोम जा", "āṅni kārḍ blak ho; gom jā"],
        ["Transfer money to this account", "निं खाताव पैसा ट्रान्सफर हो", "nin khātāw paisā ṭrānsfar ho"],
        ["What are the service charges?", "सेवा सुल्क मा दं?", "sevā sulka mā dong?"],
        ["I need a loan for a house", "आँ गोर लाम लोन लाम", "āṅ gor lām lon lām"],
        ["EMI starts next month", "ईएमआइ फिन दान सुरु होगोन", "īemāi phin dān surū hogona"],
        ["Please update my mobile number", "थांखाय आँनि मोबाइल नंबर अपडेट हो", "thāṅkhāy āṅni mobāil nambar apadeṭ ho"],
        ["The queue is long", "लाइन लाम दं", "lāin lām dong"],
        ["Thank you, have a good day", "थांखाय, गोजोन दिन हो", "thāṅkhāy, gojon din ho"],
        ["Visit the manager for approval", "मन्जुरि लाम मेनेजर थां जा", "manjuri lām menejar thāṅ jā"],
    ],
    643: [
        ["What time does the temple open?", "थांसोलि माबो वज खुल दं?", "thāṃsoli mābo vaja khul dong?"],
        ["Is photography allowed?", "फोटो खिंच ला दिं नामा?", "phoṭo khinc lā diṅ nāmā?"],
        ["Where do we keep shoes?", "जुता कुथां राखनि लाम?", "jutā kuthāṅ rākhani lām?"],
        ["Is there prasad today?", "दिनि प्रसाद दं नामा?", "dini prasād dong nāmā?"],
        ["How old is this temple?", "निं थांसोलि माबो पुराना?", "nin thāṃsoli mābo purānā?"],
        ["Tell me about the history", "इतिहास दस", "itihās das"],
        ["Is there parking nearby?", "गाह्रि पार्किंग दं नामा?", "gāhri pārkiṅ dong nāmā?"],
        ["We came for darshan", "जिंग दर्शन लाम विन", "jiṅ darśan lām vin"],
        ["Special aarti in the evening", "संजाव खास आरति दं", "sañjāw khās ārti dong"],
        ["Dress modestly, please", "थांखाय सलीकेदार कपड पा", "thāṅkhāy salīkedār kapaḍ pā"],
        ["Donations go to the trust", "दान ट्रस्ट थां जा दं", "dān ṭrasṭ thāṅ jā dong"],
        ["Festival rush is heavy", "पर्वाव बीड बाहागो दं", "parvāw bīḍ bāhāgo dong"],
        ["Is there a guide available?", "गाइड मिल दं नामा?", "gāiḍ mil dong nāmā?"],
        ["We will ring the bell thrice", "जिंग घंटि थाम वार बजामगोन", "jiṅ ghaṇṭi thām vār bajāmagon"],
        ["Peaceful atmosphere here", "निं थां समदि माहौल दं", "nin thāṅ samadi māhaul dong"],
        ["Thank you for the information", "जानकारि लाम थांखाय", "jānkāri lām thāṅkhāy"],
    ],
    644: [
        ["Namaste, uncle and aunty", "नमस्कार, काका काकी", "namaskār, kākā kākī"],
        ["Thank you for inviting us", "जिंखौ बुलाइ लाम थांखाय", "jiṅkhau bulāi lām thāṅkhāy"],
        ["The food is delicious", "खाम बाहागो स्वादिष्ट दं", "khām bāhāgo svādiṣṭa dong"],
        ["Please have some more roti", "होर रोटि ला", "hor roṭi lā"],
        ["I am full; thank you", "थन भर; थांखाय", "than bhar; thāṅkhāy"],
        ["Your home is beautiful", "नोंनि गोर सोन दं", "noṅni gor son dong"],
        ["May I help in the kitchen?", "आँ रसुइ मदद ला दों नामा?", "āṅ rasui madad lā doṅ nāmā?"],
        ["The garden is lovely", "बाग प्यारा दं", "bāg pyārā dong"],
        ["We should leave before dark", "अन्धेरा मोथाइ चल", "andherā mothāi cal"],
        ["Our parents send regards", "जिंनि बा आमा नमस्कार", "jiṅni bā āmā namaskār"],
        ["Hope to see you again", "फिन मिलनि उमेद", "phin milani umed"],
        ["Drive safely back", "थांथै चल के जा", "thāṃthai cal ke jā"],
        ["The tea was perfect", "चा बिलकुल ठिक दं", "cā bilkul ṭhik dong"],
        ["We enjoyed the lunch", "जिंनि लंच गोजोन लाग", "jiṅni lañc gojon lāg"],
        ["Bless the children", "सोरफोरखौ आशिर्बाद हो", "soraphor khau āśirbād ho"],
        ["Goodbye; take care", "अलबिदा; ख्याल राख", "alabidā; khyāl rākh"],
    ],
    645: [
        ["Which teams are playing?", "माबो टिमफोर खेल दिं?", "mābo ṭimphor khel diṅ?"],
        ["The score is one–one", "स्कोर से-से दं", "skor se-se dong"],
        ["What a goal!", "मा गोल!", "mā gol!"],
        ["The referee gave a card", "रेफरिनि कार्ड हो", "repharini kārḍ ho"],
        ["Our team is attacking", "जिंनि टिम अटेक दिं", "jiṅni ṭim aṭek diṅ"],
        ["Pass the ball!", "बाल पास हो!", "bāl pās ho!"],
        ["The crowd is cheering", "बीड तालि मार दिं", "bīḍ tāli mār diṅ"],
        ["Half-time break", "हाफ टाइम ब्रेक", "hāf ṭāim brek"],
        ["Injury; player is leaving", "चोट; खेलगिरि चल जा", "coṭ; khelagiri cal jā"],
        ["Extra time may come", "एक्स्ट्रा टाइम आ ला दं", "ekstrā ṭāim ā lā dong"],
        ["Penalty shootout", "पेनल्टि सुटआउट", "penalṭi suṭā'uṭ"],
        ["We won!", "जिंग जित!", "jiṅ jit!"],
        ["Better luck next time", "फिन वार गोजोन नसिब", "phin vār gojon nasib"],
        ["The match was fair", "मेच इमानदार दं", "mec imānadār dong"],
        ["Let's watch highlights", "हाइलाइट नेउ", "hāilāiṭ neu"],
        ["Football unites everyone", "फुटबल मानसिफोर जोड दं", "fuṭbal mānasi phor joḍ dong"],
    ],
    646: [
        ["Which movie is playing?", "माबो फिल्म चल दं?", "mābo film cal dong?"],
        ["Two tickets for the nine o'clock show", "गु वजनि शो नै टिकट", "gu vajani śo nai ṭikaṭ"],
        ["Popcorn and cold drink?", "पपकर्न आरो कोल्ड्रिंक?", "papakarna āro kolḍriṅk?"],
        ["This seat is reserved", "निं सिट रिजर्भ दं", "nin siṭ rijarbha dong"],
        ["Please switch off your mobile", "थांखाय मोबाइल बन्द हो", "thāṅkhāy mobāil band ho"],
        ["The interval is long", "इन्टरभल लाम दं", "inṭarabal lām dong"],
        ["The story is interesting", "कथि दिलचस्प दं", "kathi dilcaspa dong"],
        ["The songs are good", "गान गोजोन दं", "gān gojon dong"],
        ["It is a family film", "निं फेमिलि फिल्म दं", "nin phemili film dong"],
        ["Too loud; lower the volume", "बाहागो शोर; भलियुम घटा", "bāhāgo śor; bhalyum ghaṭā"],
        ["The climax was emotional", "क्लाइमेक्स भावुक दं", "klāimeks bhāvuk dong"],
        ["Let's leave after credits", "क्रेडिट फिन चल", "kreḍiṭ phin cal"],
        ["How did you like the film?", "नोंनि फिल्म माबो लाग?", "noṅni film mābo lāg?"],
        ["We should book online next time", "फिन वार ऑनलाइन बुक खालाम", "phin vār online buk khālam"],
        ["The theatre is crowded", "थिएटर बीड दं", "thieṭar bīḍ dong"],
        ["Nice evening; let's go home", "सोन संजा; गोर चल", "son sañjā; gor cal"],
    ],
    647: [
        ["Which country is your favourite?", "नोंनि पसंदिदा टिम माबो दं?", "noṅni pasandidā ṭim mābo dong?"],
        ["The World Cup is every four years", "वर्ल्ड कप हर ब्रै बोसोर थां", "varlḍ kap har brai bosor thāṅ"],
        ["We watched the final together", "जिंग फाइनल मिलि नेउ", "jiṅ phāinal mili neu"],
        ["What a save by the goalkeeper!", "गोलकिपरनि मा सेभ!", "golkiparani mā sebha!"],
        ["Offside; the goal is cancelled", "ऑफसाइड; गोल रद", "ophausaiḍ; gol rada"],
        ["The stadium is full", "स्टेडियम भर दं", "sṭeḍiyam bhar dong"],
        ["Penalty in the last minute", "आखिरि मिनट पेनल्टि", "ākhiri minaṭ penalṭi"],
        ["Extra time — still no goal", "एक्स्ट्रा टाइम — गोल नङा", "ekstrā ṭāim — gol naṅā"],
        ["We lost on penalties", "जिंग पेनल्टि थां हार", "jiṅ penalṭi thāṅ hār"],
        ["Let's watch the replay", "रिप्ले नेउ", "riple neu"],
        ["The referee's decision was tough", "रेफरिनि फैसला सख्त दं", "repharini phaislā sakhta dong"],
        ["Fans are singing in the streets", "फेन गलियाव गान दिं", "phen galiyāw gān diṅ"],
        ["My country reached the semi‑final", "आँनि देस सेमि फाइनल फै", "āṅnai des semi phāinal phai"],
        ["Injuries changed the match", "चोटफोरनि मेच बदल", "coṭaphorani mec badal"],
        ["Football brings the world together", "फुटबल दुनिया जोड दं", "fuṭbal duniyā joḍ dong"],
        ["See you for the next match", "फिन मेच थां मिलन फै", "phin mec thāṅ milan phai"],
    ],
    648: [
        ["Welcome to Kokrajhar", "कोक्राझाराव स्वागत", "kokrājhārāw svāgat"],
        ["This fort is three hundred years old", "निं किला थाम सो बोसोर पुराना दं", "nin kilā thām so bosor purānā dong"],
        ["We will walk for twenty minutes", "जिंग बीस मिनट टुरगोन", "jiṅ bīs minaṭ ṭurgona"],
        ["Take photos here", "निं थां फोटो खिंच", "nin thāṅ phoṭo khinc"],
        ["The river is sacred", "दरिया पवित्र दं", "dariyā pavitra dong"],
        ["Local food is spicy", "लोकेल खाम तीखा दं", "lokel khām tīkhā dong"],
        ["Souvenir shops are there", "उं सुवेनिर दुकान दं", "uṅ suvenir dukān dong"],
        ["Wear comfortable shoes", "आरामदायक जुता पा", "ārāmadāyak jutā pā"],
        ["Stay with the group", "ग्रुपजों थां", "grupajoṃ thāṅ"],
        ["The view from here is amazing", "निं निफ्राय दृश्य अद्भुत दं", "nin niphrāy dr̥śya adbhuta dong"],
        ["History lovers enjoy this place", "इतिहास प्रेमिनि निं जगा पसंद", "itihās premini nin jagā pasand"],
        ["We return before sunset", "जिंग सुर डुबनि मोथाइ मुडगोन", "jiṅ sura ḍubani mothāi muḍagon"],
        ["Tips are optional", "टिप वैकल्पिक दं", "ṭip vaikalpika dong"],
        ["Keep water with you", "दै संग राख", "dai saṅg rākh"],
        ["Any questions?", "मोनो सवाल?", "mono savāl?"],
        ["Hope you enjoyed the tour", "टुर गोजोन लाग उमेद", "ṭur gojon lāg umed"],
    ],
    649: [
        ["Good morning; please sit", "फुंनि गोजोन्थं; थांखाय बैठ", "phuṅni gojonthaṅ; thāṅkhāy baiṭh"],
        ["Introduce yourself in Bodo", "बोडो आव आँनि परिचय हो", "boḍo āv āṅni parichay ho"],
        ["Why should we hire you?", "जिंनि नों माब्ला राखनि लाम?", "jiṅni noṅ māblā rākhani lām?"],
        ["Describe your village", "नोंनि गाउ दस", "noṅni gāu das"],
        ["Read this paragraph aloud", "निं पेराग्राफ जोरै पड", "nin perāgrāph jorai paḍa"],
        ["Translate this sentence", "निं वाक अनुबाद हो", "nin vāk anubād ho"],
        ["Write a short essay", "हिन निबन्ध लिर", "hin nibandh lir"],
        ["Formal vs informal speech", "रस्मि आरो गैररस्मि लैब", "rasmi āro gairarasmi laib"],
        ["Listen and repeat", "नुंथ आरो फिन फिन हो", "nunth āro phin phin ho"],
        ["Any difficulty with grammar?", "ग्रामराव मोनो दिक्कत?", "grāmarāw mono dikkat?"],
        ["Speak slowly and clearly", "हौलै आरो साफ लैब हो", "haulai āro sāph laib ho"],
        ["We test reading and speaking", "जिंग पद आरो लैब जाँच दों", "jiṅ pad āro laib jā̃c doṅ"],
        ["Do you know banking terms?", "नों बैंकिंग सोर मोन दं नामा?", "noṅ baiṅkiṅ sor mon dong nāmā?"],
        ["Thank you; result will be emailed", "थांखाय; नतिजा ईमेल होगोन", "thāṅkhāy; natijā īmel hogona"],
        ["Confidence matters", "आत्मबिस्वास जरूरि दं", "ātmabisvās jaruri dong"],
        ["All the best", "गोबो गोजोन", "gobo gojon"],
    ],
    650: [
        ["What is for lunch today?", "दिनि दुपहर मा खाम?", "dini dupahar mā khām?"],
        ["I prefer roti and dal", "आँनि रोटि आरो डाल पसंद", "āṅni roṭi āro ḍāl pasand"],
        ["Less oil, please", "कम तेल थांखाय", "kam tel thāṅkhāy"],
        ["The curry is spicy", "करी तीखा दं", "karī tīkhā dong"],
        ["Add salad on the side", "सलाद साइडाव राख", "salād sāiḍāw rākh"],
        ["I am vegetarian", "आँ साकाहारि दों", "āṅ sākāhāri doṅ"],
        ["No onion garlic today", "दिनि गांदा लहसुन नङा", "dini gāndā lahasun naṅā"],
        ["Pack lunch for office", "ऑफिस लाम लंच पैक हो", "ophis lām lañc paik ho"],
        ["The rice is well cooked", "चोल गोजोन फोथो दं", "col gojon photho dong"],
        ["Dessert after meal", "खाम फिन मिथाइ", "khām phin mithāi"],
        ["Drink water between bites", "निवाला बिफिन दै नुं", "nivālā bifin dai nuṅ"],
        ["Host served generously", "मेहमान नवाजि बाहागो खालाम", "mehmān navāji bāhāgo khālam"],
        ["Compliments to the cook", "फोथोगिरि शाबास", "phothogiri śābās"],
        ["I am full", "थन भर", "than bhar"],
        ["Help clear the table", "मेज साफ लाम मदद हो", "mej sāph lām madad ho"],
        ["Thanks for the lovely meal", "सोन खाम लाम थांखाय", "son khām lām thāṅkhāy"],
    ],
    651: [
        ["I joined a music class", "आँ संगित क्लासाव नां लिर", "āṅ saṅgit klāsāw nāṃ lir"],
        ["Painting is my hobby", "पेन्टिंग आँनि शौक दं", "penṭiṅg āṅni śauk dong"],
        ["We meet every Saturday", "जिंग हर सनिबार मिल दों", "jiṅ har sanibār mil doṅ"],
        ["The teacher is very patient", "मास्तार बाहागो सब्र दं", "māstār bāhāgo sabra dong"],
        ["I practice guitar at home", "आँ गोराव गितार बजा दों", "āṅ gorāw gitār bajā doṅ"],
        ["Fees are affordable", "फिस सस्ति दं", "phis sasti dong"],
        ["Certificate after one year", "गोथो बोसोर फिन सर्टिफिकेट", "gotho bosor phin sartifiket"],
        ["I missed two classes", "आँ नै क्लास छुट", "āṅ nai klās chuṭ"],
        ["Friends from class", "क्लास निफ्राय दोस्त", "klās niphrāy dost"],
        ["Hobby reduces stress", "शौक तनाव घट दं", "śauk tanāv ghaṭ dong"],
        ["I want to learn tabla", "आँ तबला सिमुनाय ला दों", "āṅ tabalā simunāy lā doṅ"],
        ["The hall is well lit", "हालाव रोशनि गोजोन दं", "hālāw rośani gojon dong"],
        ["Parents support my hobby", "बा आमा आँनि शौक हो", "bā āmā āṅni śauk ho"],
        ["Annual show next month", "फिन दान सालाना शो", "phin dān sālānā śo"],
        ["Practice makes perfect", "अभ्यास खालाम के गोजोन", "abhyās khālam ke gojon"],
        ["I enjoy every lesson", "आँनि हर सबक गोजोन लाग", "āṅni har sabak gojon lāg"],
    ],
    652: [
        ["See you soon", "फिन दैखो मिलन फै", "phin daikho milan phai"],
        ["No problem at all", "मोनो गोलो नङा", "mono golo naṅā"],
        ["I will try my best", "आँ पुरि कोशिश खालामों", "āṅ puri koshish khālamoṅ"],
        ["Congratulations on your success", "सफलता आव गोजोन", "saphalatā āw gojon"],
        ["Sorry for the delay", "देर लाम माफ", "der lām māf"],
        ["Please wait a moment", "गोथो पल थां हो", "gotho pal thāṅ ho"],
        ["I agree with you", "आँ नोंजों सहमत दों", "āṅ noṅjoṃ sahamat doṅ"],
        ["I don't think so", "आँ निं सोंलों नङा", "āṅ nin soṅloṅ naṅā"],
        ["Let's discuss tomorrow", "गाब्ला गोबो खालामगोन", "gāblā gobo khālamgon"],
        ["That sounds good", "उं गोजोन लाग दं", "uṅ gojon lāg dong"],
        ["I need more time", "आँनि होर सम लाम", "āṅni hor sam lām"],
        ["Can we reschedule?", "जिंग दूजि तारिख ला दों नामा?", "jiṅ dūji tārikh lā doṅ nāmā?"],
        ["I'll send you the details", "आँ नोंखौ बिस्तार खोर खालामों", "āṅ noṅkhau bistār khor khālamoṅ"],
        ["Keep me updated", "आँनि खबर फिन हो", "āṅni khabar phin ho"],
        ["Have a nice day", "गोजोन दिन हो", "gojon din ho"],
        ["Take care of your health", "सेहतनि ख्याल राख", "sehatani khyāl rākh"],
    ],
    653: [
        ["Long time no see", "लाम सम फिन मिल", "lām sam phin mil"],
        ["How is your family?", "नोंनि गर माबो दं?", "noṅni gar mābo dong?"],
        ["Work is busy these days", "ए दिन काम बेस्त दं", "e din kām best dong"],
        ["We went on a short trip", "जिंग हिन सफर थां गे", "jiṅ hin safar thāṅ ge"],
        ["The weather was pleasant", "मौसम सुहावना दं", "mausam suhāvanā dong"],
        ["Photos are on my phone", "फोटा आँनि मोबाइल थां", "phoṭā āṅni mobāil thāṅ"],
        ["Let's plan a picnic", "पिकनिकनि योजना बाना", "pikanikani yojanā bānā"],
        ["Traffic was terrible", "ट्रैफिक माड़ा दं", "ṭraifik māṛā dong"],
        ["I bought a new book", "आँ गोदान पुस्तक खरिद", "āṅ godān pustak kharid"],
        ["The movie was average", "फिल्म ठिकठाक दं", "film ṭhikṭhāk dong"],
        ["We should exercise daily", "दिनफोर ब्यायाम खालाम लाम", "dinphor byāyām khālam lām"],
        ["Sleep early for health", "सेहत लाम दैखो नुं", "sehat lām daikho nuṅ"],
        ["Drink more water", "ज्यादा दै नुं", "zyādā dai nuṅ"],
        ["Festivals bring joy", "पर्व खुशि लानि दं", "parva khusi lāni dong"],
        ["Hope to meet again", "फिन मिलनि उमेद", "phin milani umed"],
        ["Stay happy and healthy", "खुश थां तन्दुरुस्त थां", "khush thāṅ tandurust thāṅ"],
    ],
    654: [
        ["We learn by speaking", "जिंग लैब के सिम दों", "jiṅ laib ke sim doṅ"],
        ["Don't fear mistakes", "गलति निफ्राय डर नङा", "galati niphrāy ḍar naṅā"],
        ["Repeat after the teacher", "मास्तार निफ्राय फिन फिन हो", "māstār niphrāy phin phin ho"],
        ["Use new words daily", "दिनफोर गोदान सोर बाहागो", "dinphor godān sor bāhāgo"],
        ["Listen to Bodo songs", "बोडो गित नुंथ", "boḍo git nunth"],
        ["Talk with neighbours", "गाह्रि गोरजों गोबो हो", "gāhri gorajoṃ gobo ho"],
        ["Label things at home", "गोराव सोरफोर थांहो लिर", "gorāw sorphor thāṃho lir"],
        ["Keep a small diary", "हिन डायरी राख", "hin ḍāyarī rākh"],
        ["Watch Bodo videos", "बोडो विडियो नेउ", "boḍo viḍiyo neu"],
        ["Ask 'how do you say…?'", "'… माबो लैब?' फुं", "… mābo laib?' phuṅ"],
        ["Praise progress, not perfection", "तरक्किनि तारिफ हो", "tarkkini tāriph ho"],
        ["Learn with family", "गरजों सिम", "garajoṃ sim"],
        ["Play word games", "सोर खेल खेल", "sor khel khel"],
        ["Read signs on the road", "रस्तानि निशान पड", "rastāni niśān paḍa"],
        ["Confidence grows with practice", "अभ्यास बिफिन आत्मबिस्वास बाह", "abhyās bifin ātmabisvās bāh"],
        ["Enjoy the journey of learning", "सिमुनि सफर माजा ला", "simuni safar mājā lā"],
    ],
    655: [
        ["This is my book", "निं आँनि पुस्तक दं", "nin āṅni pustak dong"],
        ["That is your pen", "उं नोंनि कलम दं", "uṅ noṅni kalam dong"],
        ["I am a student", "आँ गोथो विद्यार्थी दों", "āṅ gotho vidyārthī doṅ"],
        ["We live in Kokrajhar", "जिंग कोक्राझाराव थां दों", "jiṅ kokrājhārāw thāṅ doṅ"],
        ["She cooks well", "बि गोजोन फोथो दिं", "bi gojon photho diṅ"],
        ["They play cricket", "बिफां क्रिकेट खेल दिं", "biphāṅ krikeṭ khel diṅ"],
        ["The dog is barking", "कुथि भौंक दं", "kuthi bhauṅk dong"],
        ["Open the window", "खिड़कि खोल", "khiṛaki khol"],
        ["Close the door", "दरवाजा बन्द हो", "daravājā band ho"],
        ["Water the plants", "पौधाखौ दै हो", "paudhākhau dai ho"],
        ["Read page ten", "जि सफा पड", "ji safā paḍa"],
        ["Write your name", "नोंनि नां लिर", "noṅni nāṃ lir"],
        ["Come here", "निं विन", "nin vin"],
        ["Go slowly", "हौलै जा", "haulai jā"],
        ["Sit down", "बैठ जा", "baiṭh jā"],
        ["Stand up", "खड़े हो जा", "khaṛe ho jā"],
    ],
    656: [
        ["The book is on the table", "पुस्तक मेजाव दं", "pustak mejāw dong"],
        ["The cat is under the chair", "बिलाइ कुर्सि थालाव दं", "bilāi kursi thālāw dong"],
        ["He is in the room", "बो रुमाव दं", "bo rumāw dong"],
        ["We walked along the river", "जिंग दरिया गाह्रि टुर", "jiṅ dariyā gāhri ṭur"],
        ["Turn towards the market", "बाजार वल मुड", "bājār val muḍ"],
        ["The keys are inside the drawer", "चाबि दराज अन्दर दं", "cābi darāj andar dong"],
        ["Sit between them", "बिफांनि माजाव बैठ", "biphāṅni mājāw baiṭh"],
        ["The school is near the temple", "इस्कुल थांसोलि गाह्रि दं", "iskul thāṃsoli gāhri dong"],
        ["Run behind the ball", "बाल पिसिन दौड", "bāl pisini dauḍ"],
        ["Put the bag on the shelf", "बेग शेल्फाव राख", "beg śelphāw rākh"],
        ["Jump into the water", "दै थां कुद", "dai thāṅ kud"],
        ["Drive across the bridge", "पुल पार चला", "pul pār calā"],
        ["Wait at the gate", "गेट थां रुक", "geṭ thāṅ ruk"],
        ["The shop is opposite the bank", "दुकान बेंक सिंनि दं", "dukān benk siṃni dong"],
        ["Birds flew over the house", "सिमफोर गोर उदों उड", "simphor gor udoṃ uḍ"],
        ["He hid behind the tree", "बो गोजो पिसिन लुक", "bo gojo pisini luk"],
    ],
    657: [
        ["Teacher: Why are you late?", "मास्तार: नों देर माब्ला?", "māstār: noṅ der māblā?"],
        ["Student: The road was blocked", "विद्यार्थि: रस्ता बन्द दं", "vidyārthi: rastā band dong"],
        ["Teacher: Bring homework tomorrow", "मास्तार: गाब्ला गोरनि काम ला", "māstār: gāblā gorani kām lā"],
        ["Student: Yes, I will", "विद्यार्थि: जी, लामों", "vidyārthi: jī, lāmoṅ"],
        ["Two friends meet", "नै दोस्त मिल दं", "nai dost mil dong"],
        ["One says: I lost my money", "गोथो बो: पैसा गोम", "gotho bo: paisā gom"],
        ["Other says: Search your pocket", "फिन बो: जेब नाय", "phin bo: jeb nāy"],
        ["Son: Mom, food is ready?", "सोन: आमा, खाम तैयार?", "son: āmā, khām taiyār?"],
        ["Mother: Five more minutes", "आमा: होर बा मिनट", "āmā: hor bā minaṭ"],
        ["Villager: The well is dry", "गाउ मानसि: कुआ सुख", "gāu mānasi: kuā sukh"],
        ["Other: Dig deeper next week", "फिन: फिन हफ्ता होर खोद", "phin: phin haftā hor khod"],
        ["Shopkeeper: Fresh milk!", "दुकानदार: ताजा दुध!", "dukāndār: tājā dudh!"],
        ["Customer: Keep half a litre", "ग्राहक: आधि लिटर राख", "grāhak: ādhi liṭar rākh"],
        ["Punchline: Money first!", "मजा: मोथाइ पैसा!", "majā: mothāi paisā!"],
        ["Everyone laughs", "मानसिफोर हस दं", "mānasi phor has dong"],
        ["That's Bodo humour", "उं बोडो चुटकुला दं", "uṅ boḍo cuṭkulā dong"],
    ],
    658: [
        ["A thought for the day: work honestly", "दिननि सों: इमानदारै काम हो", "dinani soṃ: imānadārai kām ho"],
        ["Small steps bring big change", "हिन कदम बाहागो बदलाव ला", "hin kadam bāhāgo badalāv lā"],
        ["Kind words cost nothing", "नरम सोरफोरनि खर्च नङा", "naram sorphorni kharcha naṅā"],
        ["Read one page before sleep", "नुंथाइ मोथाइ गोथो सफा पड", "nunthāi mothāi gotho safā paḍa"],
        ["Share a joke with a friend", "दोस्तजों चुटकुला हो", "dostajoṃ cuṭkulā ho"],
        ["Quote: unity is strength", "सुविचार: एकताय ताकत", "suvicār: ekatāy tākat"],
        ["Smile at strangers too", "अजनबिखौ फिन मुस्कान", "ajanabikhau phin muskān"],
        ["Help someone quietly today", "दिनि चुपचाप मानसिखौ मदद", "dini cupcāp mānasikhau madad"],
        ["Write three new words", "थाम गोदान सोर लिर", "thām godān sor lir"],
        ["Listen to a short story", "हिन कथि नुंथ", "hin kathi nunth"],
        ["Repeat a proverb aloud", "कहावत जोरै लैब", "kahāwat jorai laib"],
        ["Note one good habit", "गोथो गोजो आदत लिर", "gotho gojo ādat lir"],
        ["Avoid one bad habit today", "दिनि गोथो माड़ि आदत नङा", "dini gotho māṛi ādat naṅā"],
        ["Thank three people mentally", "मन थां थाम मानसिखौ थांखाय", "man thāṅ thām mānasi khau thāṅkhāy"],
        ["Sleep with a calm mind", "शान्त मनजों नुं", "śānt manajoṃ nuṅ"],
        ["Tomorrow read again", "गाब्ला फिन पड", "gāblā phin paḍa"],
    ],
    659: [
        ["I spend less time online now", "आँ दा ऑनलाइन कम सम गज्जा दों", "āṅ dā online kam sam gajjā doṅ"],
        ["Social media can distract", "सोसियल मिडिया ध्यान भटका ला दं", "sosiyal miḍiyā dhyān bhaṭakā lā dong"],
        ["I follow news pages", "आँ खबरनि पेज फलो दों", "āṅ khabarani pej phalo doṅ"],
        ["Too many notifications annoy", "बाहागो नोटिफिकेसन तङ दं", "bāhāgo noṭiphikesan taṅ dong"],
        ["I mute groups at night", "आँ रात ग्रुप म्युट दों", "āṅ rāt grup myuṭ doṅ"],
        ["Video calls with relatives", "रिस्तादारजों विडियो कल", "ristādārajoṃ viḍiyo kal"],
        ["I learn Bodo from short reels", "आँ हिन रिल निफ्राय बोडो सिम दों", "āṅ hin ril niphrāy boḍo sim doṅ"],
        ["Cyber safety is important", "साइबर थांथै जरूरि दं", "sāibar thāṃthai jaruri dong"],
        ["Don't share OTP publicly", "ओटिपि सार्वजनिक नङा हो", "oṭipi sārvajanik naṅā ho"],
        ["Take breaks from the screen", "स्क्रिन निफ्राय ब्रेक ला", "skrin niphrāy brek lā"],
        ["Real friends meet offline", "सोंलों दोस्त ऑफलाइन मिल दं", "soṅloṅ dost ophulāin mil dong"],
        ["I deleted unused apps", "आँ बेकार ऐप मुट", "āṅ bekār aip muṭ"],
        ["Good posts spread positivity", "गोजोन पोस्ट सकारात्मक फैला दं", "gojon posṭ sakārātmak phailā dong"],
        ["Limit scrolling before sleep", "नुंथाइ मोथाइ स्क्रल कम हो", "nunthāi mothāi skral kam ho"],
        ["Balance screen and family time", "स्क्रिन आरो गरनि सम सन्तुलन", "skrin āro garani sam santulan"],
        ["Digital discipline helps studies", "डिजिटल अनुशासन पढाइ मदद दं", "ḍijiṭal anuśāsana paḍāi madad dong"],
    ],
    660: [
        ["Today there is a solar eclipse", "दिनि सुर ग्रहन दं", "dini sura grahan dong"],
        ["Do not look at the sun directly", "सुर सिधा नङा नेउ", "sur sidhā naṅā neu"],
        ["Use certified glasses", "प्रमाणित चस्म बाहागो", "pramāṇit casma bāhāgo"],
        ["Children should be supervised", "सोरफोर निगरानि राख", "sorphor nigārāni rākh"],
        ["Myth: food turns poisonous — not true", "गलत: खाम जहर — सोंलों नङा", "galat: khām jahar — soṅloṅ naṅā"],
        ["Temples may have special prayers", "थांसोलिफोराव खास पूजा हो ला दं", "thāṃsoliforāw khās pūjā ho lā dong"],
        ["Scientists explain the eclipse", "बैज्ञानिकफोर ग्रहन सोंलों हो", "baijñānikphor grahan soṅloṅ ho"],
        ["The sky becomes dim", "आकाश मन्द हो दं", "ākāś mand ho dong"],
        ["Birds return to nests", "सिमफोर घुलाव मुड दं", "simphor ghulāw muḍ dong"],
        ["Temperature may drop slightly", "तापमान थोड़ घट ला दं", "tāpamān thoṛ ghaṭ lā dong"],
        ["Photograph with proper filter", "ठिक फिल्टरै फोटो खिंच", "ṭhik philṭrai phoṭo khinc"],
        ["After eclipse, normal routine", "ग्रहन फिन रुटिन साधारन", "grahan phin ruṭin sādhāran"],
        ["Share correct information online", "सोंलों जानकारि ऑनलाइन हो", "soṅloṅ jānkāri online ho"],
        ["Children ask many questions", "सोरफोर बाहागो सवाल फुं दं", "sorphor bāhāgo savāl phuṅ dong"],
        ["Nature is amazing", "कुदरत अद्भुत दं", "kudrat adbhuta dong"],
        ["Let's watch the next eclipse safely", "फिन ग्रहन थांथै नेउगोन", "phin grahan thāṃthai negugona"],
    ],
    661: [
        ["Happy Women's Day!", "महिला दिबसनि गोजोन!", "mahilā dibasani gojon!"],
        ["We honour women's contributions", "जिंग महिलाफोरनि योगदानखौ सम्मान हो", "jiṅ mahilāphorani yogadānkhau sammān ho"],
        ["Equal opportunity for all", "सावफोरनि थामगौ मौका बराबर", "sāvaphorani thām gau maukā barābar"],
        ["Education empowers girls", "सिक्था माइफोरखौ सशक्त बाहागो", "sikthā māiphorkhau śaśakta bāhāgo"],
        ["Respect at home and work", "गोर आरो कामाव आदर", "gor āro kāmāw ādar"],
        ["Say no to discrimination", "भेदभाव नङा हो", "bhedabhāv naṅā ho"],
        ["Mothers shape society", "आमाफोर समाज होन दं", "āmāphor samāj hon dong"],
        ["Sisters deserve support", "बेहेनफोर गोबोन साहाय लाम", "behenphor gobon sāhāy lām"],
        ["Women lead in every field", "हर खेत्राव महिलाफोर नां लिडार दं", "har khetrāw mahilāphor nāṃ liḍār dong"],
        ["Safety is everyone's duty", "थांथै हौगौ सम दं", "thāṃthai haugau sam dong"],
        ["Celebrate achievements loudly", "कामयाब खालामनाय जोरै हाब", "kāmayāb khālamanāy jorai hāb"],
        ["Listen to women's voices", "महिलाफोरनि सोर नुंथ", "mahilāphorani sor nunth"],
        ["Share household work fairly", "गोरनि काम बराबर बांड", "gorani kām barābar bāṇḍ"],
        ["Healthcare access for all", "सावफोरखौ सेहत सेवा", "sāvaphorkhau sehat sevā"],
        ["Together we build equality", "थामगौ जुटाय बराबरी होन", "thām gau juṭāy barābarī hon"],
        ["Proud of the women in my life", "आँनि जिबुनि महिलाफोर गोबोन", "āṅni jibuni mahilāphor gobon"],
    ],
    662: [
        ["Why didn't you clean the room?", "नों गेदेन साफ नङा लाय?", "noṅ geden sāph naṅā lāy?"],
        ["I was tired after office", "आँ ऑफिस निफ्राय थका जा", "āṅ ophisa niphrāy thakā jā"],
        ["That is not an excuse", "निं बहाना नङा", "nin bahānā naṅā"],
        ["The guests are coming tomorrow", "गाब्ला मेहमान वान", "gāblā mehmān wān"],
        ["Please understand my workload", "थांखाय आँनि कामनि बोझ समझ", "thāṅkhāy āṅni kāmani bojh samajh"],
        ["Lower your voice", "सोर हौली हो", "sor haulī ho"],
        ["I am not arguing for fun", "आँ मजा निफ्राय बहस नङा", "āṅ majā niphrāy bahas naṅā"],
        ["Let's solve this calmly", "जिंग शान्तै हल खालाम", "jiṅ śāntai hal khālam"],
        ["Sorry, I spoke harshly", "माफ, आँ दुसर बोलं", "māph, āṅ dusar bolaṅ"],
        ["We are a family; we adjust", "जिंग गर; समायोजन खालाम", "jiṅ gar; samāyojan khālam"],
        ["Divide chores fairly", "काम बराबर बांड", "kām barābar bāṇḍ"],
        ["Children are listening", "सोरफोर नुंथ दं", "sorphor nunth dong"],
        ["Let's talk after dinner", "राति खाम फिन गोऑ", "rāti khām phin go'ā"],
        ["I need respect too", "आँखौ आदर लाम", "āṅkhau ādar lām"],
        ["Hug and make peace", "सोननि ला आरो समदान हो", "sonani lā āro samadān ho"],
        ["Tomorrow will be better", "गाब्ला गोजो होगो", "gāblā gojo hogo"],
    ],
}
