# Section 5: Conversation practice (chapterIds 620–662). Eighteen natural lines each: English, Bengali, transliteration.
from bengali_lesson_helpers import ch, r, block_table


def _c(cid: int, title: str, content: str, intro: str, rows: list) -> dict:
    return ch(cid, title, content, intro, blocks=[block_table("Conversation", rows)])


def add_chapters_620_662(out: list) -> None:
    """Curated conversation lines for each topic (no generic filler)."""
    # ----- 620–629 -----
    out.append(
        _c(
            620,
            "Diwali Festival in Bengali",
            "Phrases for greetings, lights, sweets, and wishes during Diwali / Kali Puja season.",
            "শুভ দীপাবলি — common festive greeting.",
            [
                r("Happy Diwali!", "শুভ দীপাবলি!", "Shubh dīpāboli!"),
                r("Happy Kali Puja!", "শুভ কালীপূজা!", "Shubh Kālīpūjā!"),
                r("Light the lamps.", "প্রদীপ জ্বালান।", "Prôdīp jālān."),
                r("We light diyas at home.", "আমরা বাড়িতে প্রদীপ জ্বালাই।", "Āmrā bāṛite prôdīp jālāi."),
                r("May your home be bright.", "আপনার ঘর উজ্জ্বল হোক।", "Āpār ghor ujjôl hōk."),
                r("Have some sweets.", "মিষ্টি নিন।", "Miṣṭi nin."),
                r("These are homemade ladoos.", "এগুলো বাড়ির লাড্ডু।", "Egulō bāṛir lāḍḍu."),
                r("We burst crackers carefully.", "আমরা সাবধানে পটকা ফোটাই।", "Āmrā sābdhāne poṭkā phoṭāi."),
                r("Wear safe clothes.", "নিরাপদ কাপড় পরুন।", "Nirāpôd kāpoṛ pôrun."),
                r("The whole street is lit up.", "পুরো রাস্তা জ্বলজ্বল করছে।", "Purō rāstā jôljôl korchhe."),
                r("Come to our house tonight.", "আজ রাতে আমাদের বাড়ি আসুন।", "Āj rāte āmādēr bāṛi āsun."),
                r("Thank you for the invitation.", "আমন্ত্রণের জন্য ধন্যবাদ।", "Āmontrôṇēr jônyo dhonyobād."),
                r("May prosperity come to you.", "আপনার সমৃদ্ধি হোক।", "Āpār somṛiddhi hōk."),
                r("I bought new clothes.", "আমি নতুন জামা কিনেছি।", "Āmi nôtun jāmā kinechhi."),
                r("The puja was beautiful.", "পূজাটা সুন্দর হয়েছে।", "Pūjāṭā sundor hōyēchhe."),
                r("Good night, sleep well.", "শুভ রাত্রি, ভালো ঘুমান।", "Shubho rātri, bhālō ghumān."),
                r("See you tomorrow morning.", "কাল সকালে দেখা হবে।", "Kāl sākālē dēkhā hōbe."),
                r("Happy holidays to your family.", "আপনার পরিবারকে শুভেচ্ছা।", "Āpār poribār kē shubhēchchhā."),
            ],
        )
    )
    out.append(
        _c(
            621,
            "Simple Sentences in Bengali – Introduction/Salutation",
            "Introducing yourself, asking names, and polite hellos.",
            "নমস্কার — neutral greeting; তুমি/আপনি by age and formality.",
            [
                r("Hello.", "নমস্কার।", "Nômôskār."),
                r("Good morning.", "সুপ্রভাত।", "Suprobhāt."),
                r("Good evening.", "শুভ সন্ধ্যা।", "Shubho sondhyā."),
                r("My name is Ananya.", "আমার নাম অনন্যা।", "Āmār nām Ônonyā."),
                r("What is your name?", "আপনার নাম কী?", "Āpār nām ki?"),
                r("I am pleased to meet you.", "আপনার সঙ্গে দেখা হয়ে ভালো লাগল।", "Āpār songe dēkhā hōye bhālō lāglo."),
                r("Where are you from?", "আপনি কোথা থেকে এসেছেন?", "Āpni kōthā theke ēsechhen?"),
                r("I am from Kolkata.", "আমি কলকাতা থেকে এসেছি।", "Āmi Kolkātā theke ēsechhi."),
                r("This is my friend.", "এটা আমার বন্ধু।", "Ēṭā āmār bondhu."),
                r("Welcome to our home.", "আমাদের বাড়িতে স্বাগতম।", "Āmādēr bāṛite shbāgotom."),
                r("Please sit down.", "দয়া করে বসুন।", "Dôya kōre bôsun."),
                r("Would you like tea?", "চা খাবেন?", "Chā khāben?"),
                r("Thank you very much.", "অনেক ধন্যবাদ।", "Ônek dhonyobād."),
                r("You are very kind.", "আপনি খুব দয়ালু।", "Āpni khub dôyālu."),
                r("See you again.", "আবার দেখা হবে।", "Ābār dēkhā hōbe."),
                r("Goodbye.", "বিদায়।", "Bidāy."),
                r("Take care.", "ভালো থাকবেন।", "Bhālō thākben."),
                r("Have a nice day.", "শুভ দিন কাটুক।", "Shubho din kāṭuk."),
            ],
        )
    )
    out.append(
        _c(
            622,
            "Simple Bengali Sentences – Time Related",
            "Asking and telling the time, days, and schedules.",
            "কটা বাজে? — What time is it?",
            [
                r("What time is it?", "কটা বাজে?", "Koṭā bāje?"),
                r("It is five o'clock.", "পাঁচটা বাজে।", "Pā̃choṭā bāje."),
                r("It is half past eight.", "সাড়ে আটটা বাজে।", "Sāṛe āṭoṭā bāje."),
                r("I wake up at six.", "আমি ছয়টায় উঠি।", "Āmi chhôyṭāẏ uṭhi."),
                r("Breakfast is at eight.", "নাস্তা আটটায়।", "Nāstā āṭoṭāẏ."),
                r("The meeting is at ten.", "মিটিং দশটায়।", "Miṭiṃ dôshoṭāẏ."),
                r("I work from nine to five.", "আমি নয়টা থেকে পাঁচটা কাজ করি।", "Āmi nôyṭā theke pā̃choṭā kāj kori."),
                r("Today is Monday.", "আজ সোমবার।", "Āj sōmbār."),
                r("Tomorrow is Tuesday.", "কাল মঙ্গলবার।", "Kāl môngolbār."),
                r("I will come tomorrow morning.", "আমি আগামীকাল সকালে আসব।", "Āmi āgāmīkāl sākālē āsbo."),
                r("We leave in an hour.", "আমরা এক ঘণ্টায় চলব।", "Āmrā ek ghôṇṭāẏ cholbo."),
                r("The shop opens at ten.", "দোকান দশটায় খোলে।", "Dokān dôshoṭāẏ khōle."),
                r("Sorry, I am late.", "দুঃখিত, আমি দেরি করেছি।", "Duhkhito, āmi dēri korechhi."),
                r("Please wait five minutes.", "পাঁচ মিনিট অপেক্ষা করুন।", "Pā̃ch miniṭ ôpekhshā kôrun."),
                r("What time do you sleep?", "আপনি কখন ঘুমান?", "Āpni kôkhon ghumān?"),
                r("I usually sleep at eleven.", "আমি সাধারণত এগারোটায় ঘুমাই।", "Āmi sādhāroṇoto egārōṭāẏ ghumāi."),
                r("See you at four.", "চারটায় দেখা হবে।", "Chārṭāẏ dēkhā hōbe."),
                r("Have a good afternoon.", "শুভ অপরাহ্ন।", "Shubho ôporāhno."),
            ],
        )
    )
    out.append(
        _c(
            623,
            "Simple Bengali Sentences – Where/Place Related",
            "Asking directions and describing locations.",
            "কোথায় — where; বাঁ/ডান — left/right.",
            [
                r("Where is the station?", "স্টেশন কোথায়?", "Sṭēshon kōthāy?"),
                r("How far is the airport?", "বিমানবন্দর কত দূর?", "Bimānbondor kôt dūr?"),
                r("Go straight.", "সোজা যান।", "Sōjā jān."),
                r("Turn left at the signal.", "সিগনালে বাঁ দিকে মোড় দিন।", "Signālē bã dikē mōṛ din."),
                r("Turn right after the bridge.", "সেতু পেরিয়ে ডান দিকে।", "Sētu periẏē ḍān dikē."),
                r("It is near the post office.", "ডাকঘরের কাছে।", "Ḍākghorēr kāchhe."),
                r("The hotel is opposite the park.", "হোটেল পার্কের উল্টো দিকে।", "Hōṭēl pāṛkēr ulṭō dikē."),
                r("Is there parking here?", "এখানে পার্কিং আছে?", "Ēkhāne pārkiṃ āchhe?"),
                r("I am lost.", "আমি পথ হারিয়েছি।", "Āmi poth hāriẏechhi."),
                r("Can you show me on the map?", "মানচিত্রে দেখিয়ে দেবেন?", "Māncitre dēkhiẏē deben?"),
                r("Which bus goes to Salt Lake?", "কোন বাস সল্ট লেক যাবে?", "Kōn bās Soṭ Lēk jābe?"),
                r("Get down at the next stop.", "পরের স্টপে নামবেন।", "Pōrēr sṭōpē nāmben."),
                r("The toilet is on the first floor.", "টয়লেট প্রথম তলায়।", "Ōyalēṭ prôthom tolāẏ."),
                r("I live in this area.", "আমি এই এলাকায় থাকি।", "Āmi ei ēlākāẏ thāki."),
                r("There is a good restaurant nearby.", "কাছেই একটা ভালো রেস্টুরেন্ট আছে।", "Kāchhei ekṭā bhālō rēsṭurēnṭ āchhe."),
                r("Where can I get a taxi?", "কোথায় ট্যাক্সি পাব?", "Kōthāy ṭyāksi pāb?"),
                r("The road is under repair.", "রাস্তা মেরামত চলছে।", "Rāstā mērāmot cholchhe."),
                r("Thank you for the directions.", "রাস্তা বলার জন্য ধন্যবাদ।", "Rāstā bolār jônyo dhonyobād."),
            ],
        )
    )
    out.append(
        _c(
            624,
            "Simple Bengali Sentences – In Hotel",
            "Booking a room, keys, checkout, and basic requests.",
            "রিসেপশন — reception; চেকআউট — checkout.",
            [
                r("I have a reservation.", "আমার বুকিং আছে।", "Āmār bukiṃ āchhe."),
                r("I need a double room.", "আমার ডাবল রুম দরকার।", "Āmār ḍābol rum dôrkār."),
                r("What is the rate per night?", "প্রতি রাতের ভাড়া কত?", "Prôti rāter bhāṛā kôt?"),
                r("Is breakfast included?", "নাস্তা অন্তর্ভুক্ত?", "Nāstā ôntorbhuktô?"),
                r("May I see the room?", "রুমটা দেখতে পারি?", "Rumṭā dekhte pāri?"),
                r("The AC is not working.", "এসি চলছে না।", "Ēsi cholchhe nā."),
                r("Please send extra towels.", "আরও তোয়ালে দিন।", "Ārō tōẏālē din."),
                r("What is the Wi‑Fi password?", "ওয়াই-ফাই পাসওয়ার্ড কী?", "Ōẏ-phāi pāsōẏārḍ ki?"),
                r("When is checkout?", "চেকআউট কখন?", "Chēkāuṭ kôkhon?"),
                r("Please keep my luggage.", "আমার লাগেজ রাখুন।", "Āmār lāgēj rākhun."),
                r("I would like to extend one night.", "আর এক রাত বাড়াতে চাই।", "Ār ek rāt bāṛāte chāi."),
                r("Can I pay by card?", "কার্ডে দিতে পারি?", "Kārḍē dite pāri?"),
                r("Please give me the bill.", "বিলটা দিন।", "Bilṭā din."),
                r("Call a taxi for me.", "একটা ট্যাক্সি ডেকে দিন।", "Ekoṭā ṭyāksi ḍēkē din."),
                r("Is there hot water?", "গরম জল আছে?", "Gôrom jol āchhe?"),
                r("The room is very clean.", "ঘরটা খুব পরিষ্কার।", "Ghorṭā khub porishkār."),
                r("Thank you, we enjoyed our stay.", "ধন্যবাদ, আমাদের ভালো কেটেছে।", "Dhonyobād, āmādēr bhālō kēṭechhe."),
                r("Goodbye, we will come again.", "বিদায়, আবার আসব।", "Bidāy, ābār āsbo."),
            ],
        )
    )
    out.append(
        _c(
            625,
            "Simple Bengali sentences – Weather related",
            "Talking about heat, rain, cold, and seasons.",
            "বৃষ্টি হচ্ছে — it is raining.",
            [
                r("How is the weather today?", "আজ আবহাওয়া কেমন?", "Āj ābohāoẏā kēmon?"),
                r("It is very hot.", "খুব গরম।", "Khub gorom."),
                r("It is cold today.", "আজ ঠান্ডা।", "Āj ṭhāṇḍā."),
                r("It is raining.", "বৃষ্টি হচ্ছে।", "Briṣṭi hochchhe."),
                r("Take an umbrella.", "ছাতা নিন।", "Chātā nin."),
                r("The sky is cloudy.", "আকাশ মেঘলা।", "Ākāś mēghlā."),
                r("A storm may come.", "ঝড় আসতে পারে।", "Jhoṛ āste pārē."),
                r("I like winter in Kolkata.", "আমার কলকাতায় শীত ভালো লাগে।", "Āmār Kolkātāẏ shīt bhālō lāgē."),
                r("Summer is uncomfortable.", "গ্রীষ্ম অস্বস্তিকর।", "Grīṣhm ôsbosthikôr."),
                r("The fan is enough.", "পাখা যথেষ্ট।", "Pākhā jôthēshṭo."),
                r("Humidity is high.", "আর্দ্রতা বেশি।", "Ārdrotā bēshi."),
                r("Wear a jacket.", "জ্যাকেট পরুন।", "Jyākeṭ pôrun."),
                r("The roads are flooded.", "রাস্তা জলমগ্ন।", "Rāstā jolmogno."),
                r("The weather cleared up.", "আবহাওয়া পরিষ্কার হয়েছে।", "Ābohāoẏā porishkār hōyēchhe."),
                r("It is pleasant in the evening.", "সন্ধ্যায় আরামদায়ক।", "Sondhyāẏ ārāmdāẏok."),
                r("Do not go out in the heat.", "রোদে বেরোবেন না।", "Rōdē berōben nā."),
                r("The forecast says rain.", "খবরে বৃষ্টির কথা।", "Khôbore briṣṭir kōthā."),
                r("Stay safe in bad weather.", "খারাপ আবহাওয়ায় নিরাপদ থাকুন।", "Khārāp ābohāoẏāẏ nirāpôd thākun."),
            ],
        )
    )
    out.append(
        _c(
            626,
            "Bengali conversation – with traffic police",
            "Stopping, documents, fines, and polite explanations.",
            "লাইসেন্স — licence; স্লো করুন — slow down.",
            [
                r("Please stop the car.", "গাড়ি থামান।", "Gāṛi thāman."),
                r("Good evening, sir.", "শুভ সন্ধ্যা, স্যার।", "Shubho sondhyā, syār."),
                r("Here is my driving licence.", "এটা আমার ড্রাইভিং লাইসেন্স।", "Ēṭā āmār ḍrāibiṃ lāisēns."),
                r("I was wearing my seat belt.", "আমি সিট বেল্ট পরেছিলাম।", "Āmi siṭ bēlṭ porēchilām."),
                r("Sorry, I was in a hurry.", "দুঃখিত, আমি তাড়াহুড়ো করছিলাম।", "Duhkhito, āmi ṭāṛāhuṛō korchhilām."),
                r("This is my registration paper.", "এটা রেজিস্ট্রেশন কাগজ।", "Ēṭā rējisṭrēshon kāgôj."),
                r("I did not jump the signal.", "আমি সিগনাল ভাঙিনি।", "Āmi signāl bhāṅini."),
                r("Where should I park?", "কোথায় পার্ক করব?", "Kōthāy pāṛk korbo?"),
                r("Is there a fine?", "জরিমানা আছে?", "Jorimānā āchhe?"),
                r("I will pay online.", "আমি অনলাইনে দেব।", "Āmi ônlāinē debō."),
                r("Please show me your ID.", "আইডি দেখান।", "Āiḍi dēkhān."),
                r("Drive slowly in the rain.", "বৃষ্টিতে ধীরে চালান।", "Briṣṭite dhīre chālān."),
                r("Helmets are compulsory for two-wheelers.", "দুই চাকার জন্য হেলমেট বাধ্যতামূলক।", "Dui chākār jônyo hēlmēṭ bādhyotāmūlok."),
                r("Thank you for the warning.", "সতর্ক করার জন্য ধন্যবাদ।", "Sôtôrk korār jônyo dhonyobād."),
                r("I will be careful.", "আমি সাবধান হব।", "Āmi sābdhān habō."),
                r("Have a safe journey.", "শুভ যাত্রা।", "Shubho jātrā."),
                r("May I go now?", "আমি কি এখন যেতে পারি?", "Āmi ki ēkhon jēte pāri?"),
                r("Thank you, officer.", "ধন্যবাদ, অফিসার।", "Dhonyobād, ôphisār."),
            ],
        )
    )
    out.append(
        _c(
            627,
            "Simple Bengali conversation – Rickshaw/Taxi driver",
            "Fares, routes, meter, and drop-off requests.",
            "ভাড়া — fare; মিটার — meter.",
            [
                r("Please take me to Howrah station.", "আমাকে হাওড়া স্টেশনে নিয়ে যান।", "Āmākē Hāoṛā sṭēshone niyē jān."),
                r("How much is the fare?", "ভাড়া কত?", "Bhāṛā kôt?"),
                r("Please use the meter.", "মিটার লাগান।", "Miṭār lāgān."),
                r("Do you know Park Street?", "পার্ক স্ট্রিট চেনেন?", "Pāṛk sṭriṭ chēnen?"),
                r("Stop in front of the hotel.", "হোটেলের সামনে থামবেন।", "Hōṭēlēr sāmne thāmaben."),
                r("Please drive slowly.", "ধীরে চালান।", "Dhīre chālān."),
                r("I am in a hurry.", "আমার তাড়া আছে।", "Āmār ṭāṛā āchhe."),
                r("Is this the shortest route?", "এটা কি সবচেয়ে ছোট রাস্তা?", "Ēṭā ki sôbcheye choṭ rāstā?"),
                r("Turn left here.", "এখানে বাঁ দিকে।", "Ēkhāne bã dikē."),
                r("Please wait two minutes.", "দু মিনিট অপেক্ষা করুন।", "Du miniṭ ôpekhshā kôrun."),
                r("Keep the change.", "বাকিটা রাখুন।", "Bākiṭā rākhun."),
                r("The traffic is heavy today.", "আজ ট্রাফিক বেশি।", "Āj ṭrāphik bēshi."),
                r("Drop me at the corner.", "মোড়ে নামিয়ে দিন।", "Moṛē nāmiẏē din."),
                r("Can you come at six?", "আপনি কি ছয়টায় আসবেন?", "Āpni ki chhôyṭāẏ āsben?"),
                r("I will call you tomorrow.", "আমি কাল ফোন করব।", "Āmi kāl phōn korbo."),
                r("Thank you, drive safely.", "ধন্যবাদ, নিরাপদে চালান।", "Dhonyobād, nirāpôdē chālān."),
                r("Here is the exact fare.", "ঠিক ভাড়া নিন।", "Ṭhik bhāṛā nin."),
                r("Goodbye.", "বিদায়।", "Bidāy."),
            ],
        )
    )
    out.append(
        _c(
            628,
            "Simple Bengali Conversation – Software Engineers",
            "Office talk: stand-ups, bugs, deployments, and meetings.",
            "ডিপ্লয় — deploy; বাগ — bug.",
            [
                r("The build failed last night.", "গতরাতে বিল্ড ফেল করেছে।", "Gôtorāte bilḍ phēl korechhe."),
                r("I will fix the bug today.", "আমি আজ বাগ ঠিক করব।", "Āmi āj bāg ṭhik korbo."),
                r("Please review my pull request.", "আমার পুল রিকোয়েস্ট দেখুন।", "Āmār pul rikōẏesṭ dēkhun."),
                r("The server is down.", "সার্ভার ডাউন।", "Sārbhār ḍāun."),
                r("We deploy on Friday evening.", "আমরা শুক্রবার সন্ধ্যায় ডিপ্লয় করি।", "Āmrā shukrobār sondhyāẏ ḍiplōẏ kori."),
                r("Let's sync after lunch.", "লাঞ্চের পরে সিঙ্ক করি।", "Lāñchēr pōre siṅk kori."),
                r("I am on a call with the client.", "আমি ক্লায়েন্টের সঙ্গে কলে।", "Āmi klāyenṭēr songe kōlē."),
                r("The API response is slow.", "এপিআই রেসপন্স ধীর।", "Epiāi rēspons dhīr."),
                r("Please update the ticket.", "টিকিট আপডেট করুন।", "Ṭikiṭ āpḍēṭ kôrun."),
                r("I will push the changes tonight.", "আমি আজ রাতে চেঞ্জ পুশ করব।", "Āmi āj rāte chēnj push korbo."),
                r("Can we extend the deadline?", "ডেডলাইন বাড়ানো যাবে?", "Ḍēdlāin bāṛānō jābe?"),
                r("The demo went well.", "ডেমো ভালো হয়েছে।", "Ḍēmō bhālō hōyēchhe."),
                r("I need access to the repo.", "রিপো অ্যাক্সেস দরকার।", "Ripō ẹksēs dôrkār."),
                r("Let's test on staging first.", "আগে স্টেজিং এ টেস্ট করি।", "Āgē sṭējim̃ e ṭēsṭ kori."),
                r("Memory usage is high.", "মেমরি ব্যবহার বেশি।", "Mēmôri bẽbohār bēshi."),
                r("I will document this tomorrow.", "আমি এটা কাল ডকুমেন্ট করব।", "Āmi ēṭā kāl ḍkumēnṭ korbo."),
                r("Good work, team.", "ভালো কাজ, টিম।", "Bhālō kāj, ṭim."),
                r("See you in the stand-up.", "স্ট্যান্ড-আপে দেখা হবে।", "Sṭênḍ-āpē dēkhā hōbe."),
            ],
        )
    )
    out.append(
        _c(
            629,
            "Simple Bengali conversation – Grocery shop",
            "Weights, prices, fresh produce, and paying.",
            "এক কিলো — one kilo; দাম — price.",
            [
                r("One kilo rice, please.", "এক কিলো চাল দিন।", "Ek kilō chāl din."),
                r("How much per kilo?", "প্রতি কিলো কত?", "Prôti kilō kôt?"),
                r("Is this basmati rice?", "এটা কি বাসমতি চাল?", "Ēṭā ki Bāsmti chāl?"),
                r("Give me half a kilo of dal.", "আধা কিলো ডাল দিন।", "Ādhā kilō ḍāl din."),
                r("Do you have fresh milk?", "তাজা দুধ আছে?", "Tājā dudh āchhe?"),
                r("The curd looks good.", "দইটা ভালো দেখাচ্ছে।", "Dôiṭā bhālō dēkhāchchhe."),
                r("I need cooking oil.", "আমার রান্নার তেল দরকার।", "Āmār rānnār tēl dôrkār."),
                r("This packet is too expensive.", "এই প্যাকেট খুব দামি।", "Ei pyākeṭ khub dāmi."),
                r("Any discount today?", "আজ কোনো ছাড় আছে?", "Āj kōnō chāṛ āchhe?"),
                r("Please weigh it again.", "আবার ওজন করুন।", "Ābār ojon kôrun."),
                r("Do you take UPI?", "ইউপিআই নেন?", "Iupiāi nēn?"),
                r("Give me the bill.", "বিল দিন।", "Bil din."),
                r("Keep the change.", "বাকিটা রাখুন।", "Bākiṭā rākhun."),
                r("The lentils are clean.", "ডাল পরিষ্কার।", "Ḍāl porishkār."),
                r("I will come next week.", "আমি আগামী সপ্তাহে আসব।", "Āmi āgāmī soptāhē āsbo."),
                r("Close the shop on time.", "সময়মতো দোকান বন্ধ করুন।", "Somōymôtō dokān bondho kôrun."),
                r("Thank you, brother.", "ধন্যবাদ, ভাই।", "Dhonyobād, bhāi."),
                r("Goodbye.", "টাটা।", "Ṭāṭā."),
            ],
        )
    )
    # ----- 630–644 -----
    out.append(
        _c(
            630,
            "Simple Bengali Conversation – Doctor-Patient",
            "Symptoms, duration, medicine, and follow-up.",
            "জ্বর — fever; ওষুধ — medicine.",
            [
                r("Good morning, doctor.", "সুপ্রভাত, ডাক্তার।", "Suprobhāt, ḍāktār."),
                r("I have a fever.", "আমার জ্বর।", "Āmār jwor."),
                r("Since yesterday evening.", "গতকাল সন্ধ্যা থেকে।", "Gôtokāl sondhyā theke."),
                r("My head hurts.", "আমার মাথা ধরেছে।", "Āmār māthā dhorēchhe."),
                r("I feel weak.", "আমার দুর্বল লাগছে।", "Āmār durbôl lāgchhe."),
                r("Any cough or cold?", "কাশি বা সর্দি আছে?", "Kāshi bā sôrdi āchhe?"),
                r("I have allergies to penicillin.", "আমার পেনিসিলিনে অ্যালার্জি।", "Āmār penisilinē ẹlārji."),
                r("Please check my blood pressure.", "ব্লাড প্রেশার দেখুন।", "Blāḍ prēshār dēkhun."),
                r("Take this medicine twice a day.", "দিনে দুবার ওষুধ খান।", "Dinē dubār oṣudh khān."),
                r("Drink plenty of water.", "প্রচুর জল খান।", "Prôchur jol khān."),
                r("Rest for two days.", "দুদিন বিশ্রাম নিন।", "Dudin bishrām nin."),
                r("Come back if it gets worse.", "খারাপ হলে আবার আসুন।", "Khārāp hlē ābār āsun."),
                r("Do I need tests?", "টেস্ট লাগবে?", "Ṭēsṭ lāgbe?"),
                r("The report will come tomorrow.", "রিপোর্ট কাল আসবে।", "Ripōṭ kāl āsbe."),
                r("Thank you, doctor.", "ধন্যবাদ, ডাক্তার।", "Dhonyobād, ḍāktār."),
                r("What is your fee?", "ফি কত?", "Phī kôt?"),
                r("Get well soon.", "তাড়াতাড়ি সুস্থ হন।", "Ṭāṛāṭāṛi sustho hon."),
                r("Goodbye.", "বিদায়।", "Bidāy."),
            ],
        )
    )
    out.append(
        _c(
            631,
            "Simple Bengali Conversation – Teacher & Students",
            "Classroom instructions, homework, and questions.",
            "ছাত্র — student; পাঠ — lesson.",
            [
                r("Good morning, students.", "সুপ্রভাত, ছাত্রছাত্রীরা।", "Suprobhāt, chātrôchātrīrā."),
                r("Open your books to page ten.", "দশ নম্বর পাতায় বই খুলুন।", "Dôsh nombor pātāẏ bôi khulun."),
                r("Who will read the first paragraph?", "প্রথম অনুচ্ছেদ কে পড়বে?", "Prôthom ônuchchhēd kē pōṛbe?"),
                r("Raise your hand if you know.", "জানলে হাত তুলুন।", "Jānle hāt tulun."),
                r("Please write the answer.", "উত্তর লিখুন।", "Uttor likhun."),
                r("Homework is on the board.", "বোর্ডে বাড়ির কাজ।", "Bōrḍē bāṛir kāj."),
                r("Submit by Friday.", "শুক্রবারের মধ্যে জমা দিন।", "Shukrobārēr môdhye jomā din."),
                r("Any questions?", "কোনো প্রশ্ন?", "Kōnō prôshno?"),
                r("I did not understand this part.", "আমি এই অংশটা বুঝিনি।", "Āmi ei ôṅshoṭā bujhini."),
                r("Let me explain again.", "আবার বুঝিয়ে দিই।", "Ābār bujhiẏē dii."),
                r("Very good answer.", "খুব ভালো উত্তর।", "Khub bhālō uttor."),
                r("Do not talk in class.", "ক্লাসে কথা বলবেন না।", "Klāsē kōthā kôrben nā."),
                r("The exam is next month.", "পরীক্ষা আগামী মাসে।", "Porīkkhā āgāmī māsē."),
                r("Study chapter three.", "তৃতীয় অধ্যায় পড়ুন।", "Tritīẏô odhyāẏ pōṛun."),
                r("Be on time tomorrow.", "কাল সময়মতো আসবেন।", "Kāl somōymôtō āsben."),
                r("Thank you, teacher.", "ধন্যবাদ, স্যার।", "Dhonyobād, syār."),
                r("See you tomorrow.", "কাল দেখা হবে।", "Kāl dēkhā hōbe."),
                r("Class dismissed.", "ক্লাস শেষ।", "Klās shēsh."),
            ],
        )
    )
    out.append(
        _c(
            632,
            "Simple Bengali conversation – Informal phone conversation",
            "Casual calls among friends: plans, signal, callbacks.",
            "ফোন — phone; সিগনাল — signal.",
            [
                r("Hello, it's me.", "হ্যালো, আমি।", "Hyālō, āmi."),
                r("Can you hear me?", "শুনতে পাচ্ছিস?", "Shunte pāchchhis?"),
                r("The signal is weak.", "সিগনাল দুর্বল।", "Signāl durbôl."),
                r("Where are you?", "তুই কোথায়?", "Tui kōthāy?"),
                r("I am at home.", "আমি বাড়িতে।", "Āmi bāṛite."),
                r("Come to my place in an hour.", "এক ঘণ্টায় আমার বাড়ি চলে আয়।", "Ek ghôṇṭāẏ āmār bāṛi chōle āy."),
                r("Sorry, I am busy now.", "সরি, এখন ব্যস্ত।", "Sori, ēkhon bēsto."),
                r("I will call you back.", "আমি আবার ফোন করব।", "Āmi ābār phōn korbo."),
                r("Text me the address.", "ঠিকানা মেসেজ কর।", "Ṭhikānā mēsēj koro."),
                r("Did you eat?", "খেয়েছিস?", "Khēyēchhis?"),
                r("Let's meet at the café.", "ক্যাফেতে দেখা করি।", "Kyāfētē dēkhā kori."),
                r("I am on the way.", "আমি আসছি।", "Āmi āschhi."),
                r("Don't cut the call.", "লাইন কাটিস না।", "Lāin kāṭis nā."),
                r("My battery is low.", "ব্যাটারি কম।", "Bẽṭāri kom."),
                r("Talk to you later.", "পরে কথা হবে।", "Pōre kōthā hōbe."),
                r("Take care.", "ভালো থাকিস।", "Bhālō thākis."),
                r("Bye.", "টাটা।", "Ṭāṭā."),
                r("Miss you.", "তোর কথা মনে পড়ে।", "Tōr kōthā mōne pōṛē."),
            ],
        )
    )
    out.append(
        _c(
            633,
            "Simple Bengali conversation – Vegetable Market",
            "Haggling, freshness, and buying by weight.",
            "তাজা — fresh; দর — price.",
            [
                r("How much for the potatoes?", "আলুর দাম কত?", "Ālur dām kôt?"),
                r("Give me two kilos of onions.", "দু কিলো পেঁয়াজ দিন।", "Du kilō pẽyāj din."),
                r("Is this tomato fresh?", "টমেটো তাজা?", "Ṭomeṭō tājā?"),
                r("The brinjals look good.", "বেগুনগুলো ভালো।", "Bēgungulō bhālō."),
                r("Too expensive, reduce a little.", "খুব দামি, একটু কমান।", "Khub dāmi, ekoṭu komān."),
                r("I will take this bunch of spinach.", "এই পালং শাকটা নিই।", "Ei pāloṅ shākṭā nii."),
                r("Do you have coriander?", "ধনেপাতা আছে?", "Dhonēpātā āchhe?"),
                r("Add some green chillies.", "কাঁচা মরিচ দিন।", "Kãchā morich din."),
                r("Weigh the pumpkin.", "কুমড়ো ওজন করুন।", "Kumṛō ojon kôrun."),
                r("I need ginger and garlic.", "আদা রসুন দরকার।", "Ādā rôsun dôrkār."),
                r("The beans are tender.", "শিম নরম।", "Shim norom."),
                r("I shop here every week.", "আমি প্রতি সপ্তাহে এখানে কেনাকাটা করি।", "Āmi prôti soptāhē ēkhāne kēnākāṭā kori."),
                r("Give a fair price.", "ন্যায্য দাম দিন।", "Nẽjjo dām din."),
                r("I will pay cash.", "নগদ দেব।", "Nogod debō."),
                r("Put everything in this bag.", "এই ব্যাগে সব দিন।", "Ei bẽgē sôb din."),
                r("Thank you, uncle.", "ধন্যবাদ, কাকা।", "Dhonyobād, kākā."),
                r("See you tomorrow.", "কাল আসব।", "Kāl āsbo."),
                r("Goodbye.", "টাটা।", "Ṭāṭā."),
            ],
        )
    )
    out.append(
        _c(
            634,
            "Simple Bengali Conversation – at bus stop and in bus",
            "Routes, tickets, seats, and stops.",
            "টিকিট — ticket; স্টপ — stop.",
            [
                r("Does this bus go to Gariahat?", "এই বাস গড়িয়াহাট যাবে?", "Ei bās Goṛiāhāṭ jābe?"),
                r("Where is the bus stand?", "বাস স্ট্যান্ড কোথায়?", "Bās sṭênḍ kōthāy?"),
                r("One ticket to Esplanade.", "এসপ্লানেড একটা টিকিট।", "Ēsplānēḍ ekṭā ṭikiṭ."),
                r("How much is the fare?", "ভাড়া কত?", "Bhāṛā kôt?"),
                r("Is this seat free?", "এই সিট ফাঁকা?", "Ei siṭ fãkā?"),
                r("Please move a little.", "একটু সরে বসুন।", "Ekoṭu śorē bôsun."),
                r("Where should I get down?", "কোথায় নামব?", "Kōthāy nāmobo?"),
                r("Tell me when we reach.", "পৌঁছালে বলবেন।", "Poũchhālē bôlben."),
                r("The bus is crowded.", "বাস ভিড়।", "Bās bhiṛ."),
                r("Hold the railing.", "রড ধরুন।", "Roḍ dhorun."),
                r("My stop is next.", "পরের স্টপে নামব।", "Pōrēr sṭōpē nāmobo."),
                r("Is there a ladies' seat?", "মহিলাদের আসন আছে?", "Mohilādēr āsôn āchhe?"),
                r("The conductor is honest.", "কন্ডাক্টর সৎ।", "Kônḍākṭôr sôt."),
                r("I missed my stop.", "স্টপ মিস করেছি।", "Sṭōp mis korechhi."),
                r("Please stop the bus.", "বাস থামান।", "Bās thāman."),
                r("Thank you.", "ধন্যবাদ।", "Dhonyobād."),
                r("Have a safe journey.", "শুভ যাত্রা।", "Shubho jātrā."),
                r("Goodbye.", "বিদায়।", "Bidāy."),
            ],
        )
    )
    out.append(
        _c(
            635,
            "Asking address in Bengali",
            "Getting street names, landmarks, and flat numbers.",
            "ঠিকানা — address; ল্যান্ডমার্ক — landmark.",
            [
                r("What is your full address?", "আপনার সম্পূর্ণ ঠিকানা কী?", "Āpār shompūrṇ ṭhikānā ki?"),
                r("Write it in my phone.", "ফোনে লিখে দিন।", "Phōnē likhe din."),
                r("Which building is it?", "কোন বিল্ডিং?", "Kōn bilḍiṃ?"),
                r("Flat number seven B.", "ফ্ল্যাট সেভেন বি।", "Phlẽṭ sēven bi."),
                r("Near the big temple.", "বড় মন্দিরের কাছে।", "Boṛ mondirēr kāchhe."),
                r("Opposite the petrol pump.", "পেট্রোল পাম্পের উল্টো দিকে।", "Peṭrol pām̃pēr ulṭō dikē."),
                r("Lane number three.", "তিন নম্বর লেন।", "Tin nombor lēn."),
                r("The pin code is seven zero zero zero one.", "পিন কোড সাত শূন্য শূন্য শূন্য এক।", "Pin kōḍ sāt shūnyo shūnyo shūnyo ek."),
                r("How do I reach from the station?", "স্টেশন থেকে কীভাবে যাব?", "Sṭēshon theke kībhābē jāb?"),
                r("Take a left from the crossing.", "মোড় থেকে বাঁ দিকে।", "Moṛ theke bã dikē."),
                r("Ring the bell twice.", "দুবার বেল বাজান।", "Dubār bel bājān."),
                r("I will send you the location.", "লোকেশন পাঠাব।", "Lōkēshon pāṭhābō."),
                r("Is there parking?", "পার্কিং আছে?", "Pārkiṃ āchhe?"),
                r("Call me when you arrive.", "পৌঁছালে ফোন করবেন।", "Poũchhālē phōn kôrben."),
                r("I live on the third floor.", "আমি তৃতীয় তলায় থাকি।", "Āmi tritīẏo tolāẏ thāki."),
                r("Thank you for the details.", "বিস্তারিত জানানোর জন্য ধন্যবাদ।", "Bistārito jānānōr jônyo dhonyobād."),
                r("See you at your place.", "আপনার বাড়িতে দেখা হবে।", "Āpār bāṛite dēkhā hōbe."),
                r("Goodbye.", "বিদায়।", "Bidāy."),
            ],
        )
    )
    out.append(
        _c(
            636,
            "I Love you in Bengali – Proposing someone",
            "Romantic but respectful phrases; adjust তুমি/আপনি to context.",
            "ভালোবাসি — I love you (intimate).",
            [
                r("I love you.", "আমি তোমাকে ভালোবাসি।", "Āmi tōmākē bhālōbāsi."),
                r("You mean a lot to me.", "তুমি আমার কাছে অনেক গুরুত্বপূর্ণ।", "Tumi āmār kāchhe ônek gurutwopūrṇo."),
                r("Will you be my partner?", "তুমি কি আমার সঙ্গী হবে?", "Tumi ki āmār songī hōbe?"),
                r("I want to spend life with you.", "আমি তোমার সঙ্গে জীবন কাটাতে চাই।", "Āmi tōmār songe jībon kāṭāte chāi."),
                r("You make me happy.", "তুমি আমাকে খুশি করো।", "Tumi āmākē khushi kōrō."),
                r("I respect your dreams.", "আমি তোমার স্বপ্নকে সম্মান করি।", "Āmi tōmār shôpnōkē shommān kori."),
                r("May I meet your parents?", "আমি কি তোমার বাবা-মার সঙ্গে দেখা করতে পারি?", "Āmi ki tōmār bābā-mār songe dēkhā korte pāri?"),
                r("I am serious about us.", "আমি আমাদের ব্যাপারে সিরিয়াস।", "Āmi āmādēr bẽpārē siriās."),
                r("Take your time to think.", "ভেবে নিও, সময় আছে।", "Bhēbē niō, somoy āchhe."),
                r("I will wait for your answer.", "আমি তোমার উত্তরের অপেক্ষায়।", "Āmi tōmār uttorēr ôpekhshāẏ."),
                r("Whatever you decide, I understand.", "তুমি যা বলবে, আমি বুঝব।", "Tumi jā bōlbe, āmi bujhbō."),
                r("You are beautiful inside and out.", "তুমি ভিতরে বাইরে সুন্দর।", "Tumi bhitore bāire sundor."),
                r("Thank you for being you.", "তুমি যেমন, তার জন্য ধন্যবাদ।", "Tumi jēmon, tār jônyo dhonyobād."),
                r("Can we go for coffee?", "আমরা কি কফি খেতে যাব?", "Āmrā ki kophi khete jāb?"),
                r("I miss you.", "তোমাকে মিস করি।", "Tōmākē mis kori."),
                r("Good night, sleep well.", "শুভ রাত্রি, ভালো ঘুমোও।", "Shubho rātri, bhālō ghumōo."),
                r("Talk tomorrow?", "কাল কথা হবে?", "Kāl kōthā hōbe?"),
                r("Take care of yourself.", "নিজের যত্ন নিও।", "Nijēr jôtno niō."),
            ],
        )
    )
    out.append(
        _c(
            637,
            "Simple Bengali Conversation – Interview",
            "Job interviews: background, skills, salary, joining.",
            "অভিজ্ঞতা — experience; বেতন — salary.",
            [
                r("Good morning, please sit.", "সুপ্রভাত, বসুন।", "Suprobhāt, bôsun."),
                r("Tell me about yourself.", "নিজের সম্পর্কে বলুন।", "Nijēr sômpôrkē bôlun."),
                r("I have five years of experience.", "আমার পাঁচ বছরের অভিজ্ঞতা আছে।", "Āmār pā̃ch bôchorer ôbhiggyotā āchhe."),
                r("I worked as a team lead.", "আমি টিম লিড হিসেবে কাজ করেছি।", "Āmi ṭim liḍ hisēbē kāj korechhi."),
                r("My strength is communication.", "আমার শক্তি যোগাযোগ।", "Āmār shokti jōgājog."),
                r("I enjoy solving problems.", "আমি সমস্যা সমাধানে আনন্দ পাই।", "Āmi shomosshā somādānē ānondo pāi."),
                r("Why do you want this job?", "এই চাকরি কেন চান?", "Ei chākri kēn chān?"),
                r("What salary do you expect?", "কত বেতন আশা করেন?", "Kôt bēton āshā kôren?"),
                r("I can join in two weeks.", "আমি দু সপ্তাহে যোগ দিতে পারি।", "Āmi du soptāhē jōg dite pāri."),
                r("Do you have any questions for us?", "আপনার কোনো প্রশ্ন আছে?", "Āpār kōnō prôshno āchhe?"),
                r("What are the working hours?", "কাজের সময় কেমন?", "Kājēr somoy kēmon?"),
                r("Is there work from home?", "ওয়ার্ক ফ্রম হোম আছে?", "Ōārk phrom hōm āchhe?"),
                r("Thank you for the opportunity.", "সুযোগের জন্য ধন্যবাদ।", "Sujogēr jônyo dhonyobād."),
                r("I will do my best.", "আমি সর্বোচ্চ চেষ্টা করব।", "Āmi sôrbōchchō chēṣṭā korbo."),
                r("We will inform you by email.", "ইমেইলে জানাব।", "Imēilē jānābō."),
                r("Nice talking to you.", "কথা বলে ভালো লাগল।", "Kōthā bōlē bhālō lāglo."),
                r("Have a good day.", "শুভ দিন।", "Shubho din."),
                r("Goodbye.", "বিদায়।", "Bidāy."),
            ],
        )
    )
    out.append(
        _c(
            638,
            "Simple Bengali conversation – with housemaid",
            "Tasks, timing, pay, and polite requests at home.",
            "বেতন — salary; কাজ — work.",
            [
                r("Please come at seven in the morning.", "সকাল সাতটায় আসবেন।", "Sākāl sātṭāẏ āsben."),
                r("Clean the kitchen today.", "আজ রান্নাঘর পরিষ্কার করুন।", "Āj rānnāghôr porishkār kôrun."),
                r("Wash the clothes in the machine.", "কাপড় মেশিনে ধুয়ে দিন।", "Kāpoṛ mēshinē dhuẏē din."),
                r("The floor needs mopping.", "ফ্লোর মোছা দরকার।", "Phlōr mōchhā dôrkār."),
                r("Please buy vegetables from the market.", "বাজার থেকে সবজি কিনে আনুন।", "Bājār theke sôbji kinē ānun."),
                r("Do not use too much soap.", "বেশি সাবান লাগাবেন না।", "Bēshi sābān lāgāben nā."),
                r("Take Sunday off.", "রবিবার ছুটি।", "Rôbibār chhuṭi."),
                r("I will pay you on the first.", "এক তারিখে বেতন দেব।", "Ek tārikhē bēton debō."),
                r("Is this salary okay?", "এই বেতন ঠিক আছে?", "Ei bēton ṭhik āchhe?"),
                r("Please lock the door when you leave.", "চলে যাওয়ার সময় তালা দেবেন।", "Chōlē jāoẏār somoy tālā deben."),
                r("Call me if you are late.", "দেরি হলে ফোন করবেন।", "Dēri hlē phōn kôrben."),
                r("The children are sleeping.", "বাচ্চারা ঘুমোচ্ছে।", "Bāchchārā ghumochchhe."),
                r("Thank you for your help.", "সাহায্যের জন্য ধন্যবাদ।", "Sāhājjēr jônyo dhonyobād."),
                r("Take care of yourself.", "নিজের যত্ন নেবেন।", "Nijēr jôtno neben."),
                r("We respect your work.", "আমরা আপনার কাজকে সম্মান করি।", "Āmrā āpār kāj kē shommān kori."),
                r("See you tomorrow.", "কাল দেখা হবে।", "Kāl dēkhā hōbe."),
                r("Good night.", "শুভ রাত্রি।", "Shubho rātri."),
                r("Goodbye.", "বিদায়।", "Bidāy."),
            ],
        )
    )
    out.append(
        _c(
            639,
            "Simple Bengali conversation: Linking AADHAR card to mobile number",
            "OTP, ID proof, and mobile shop dialogue.",
            "আধার — Aadhaar; ওটিপি — OTP.",
            [
                r("I want to link Aadhaar to my mobile.", "আমি আধার মোবাইলে লিঙ্ক করতে চাই।", "Āmi ādhār mōbāile liṅk korte chāi."),
                r("Here is my Aadhaar card.", "এটা আমার আধার কার্ড।", "Ēṭā āmār ādhār kāṛ."),
                r("Please verify the number.", "নম্বরটা যাচাই করুন।", "Nomborṭā jāchāi kôrun."),
                r("Enter the OTP.", "ওটিপি দিন।", "Ōṭipi din."),
                r("I did not receive the OTP.", "ওটিপি আসেনি।", "Ōṭipi āsēni."),
                r("Please resend the SMS.", "এসএমএস আবার পাঠান।", "Esemes ābār pāṭhān."),
                r("Is my fingerprint needed?", "আঙুলের ছাপ লাগবে?", "Āṅulēr chāp lāgbe?"),
                r("This is my original ID.", "এটা আমার আসল পরিচয়পত্র।", "Ēṭā āmār ôsol porichôypôtro."),
                r("How long will it take?", "কতক্ষণ লাগবে?", "Kôtokkhoṇ lāgbe?"),
                r("Is there any charge?", "কোনো চার্জ আছে?", "Kōnō chārj āchhe?"),
                r("Please give me a receipt.", "রসিদ দিন।", "Rôsid din."),
                r("The link is successful.", "লিঙ্ক সফল হয়েছে।", "Liṅk sôphol hōyēchhe."),
                r("Thank you for your help.", "সাহায্যের জন্য ধন্যবাদ।", "Sāhājjēr jônyo dhonyobād."),
                r("Call me if there is a problem.", "সমস্যা হলে ফোন করবেন।", "Shomosshā hlē phōn kôrben."),
                r("Goodbye.", "বিদায়।", "Bidāy."),
                r("Have a good day.", "শুভ দিন।", "Shubho din."),
                r("See you again.", "আবার আসব।", "Ābār āsbo."),
                r("Take care.", "ভালো থাকবেন।", "Bhālō thākben."),
            ],
        )
    )
    out.append(
        _c(
            640,
            "Simple Bengali conversation: Linking mobile number to AADHAR card",
            "Updating Aadhaar records with a new phone number.",
            "আপডেট — update; যাচাই — verification.",
            [
                r("I need to update my mobile on Aadhaar.", "আমি আধারে মোবাইল নম্বর আপডেট করতে চাই।", "Āmi ādhārē mōbāil nombor āpḍēṭ korte chāi."),
                r("This is my new SIM.", "এটা আমার নতুন সিম।", "Ēṭā āmār nôtun sim."),
                r("Please scan the QR code.", "কিউআর কোড স্ক্যান করুন।", "Kiuār kōḍ skyan kôrun."),
                r("I brought my ID proof.", "পরিচয়পত্র এনেছি।", "Porichôypôtro ēnechhi."),
                r("Send OTP to this number.", "এই নম্বরে ওটিপি পাঠান।", "Ei nomborē Ōṭipi pāṭhān."),
                r("The OTP has expired.", "ওটিপির মেয়াদ শেষ।", "Ōṭipir mēẏād shēsh."),
                r("Let me try again.", "আবার চেষ্টা করি।", "Ābār chēṣṭā kori."),
                r("Is biometric verification needed?", "বায়োমেট্রিক লাগবে?", "Bāyōmeṭrik lāgbe?"),
                r("Please print the acknowledgement.", "স্বীকারপত্র প্রিন্ট দিন।", "Shīkārpotro prinṭ din."),
                r("How many days for update?", "আপডেটে কত দিন লাগে?", "Āpḍēṭē kôt din lāgē?"),
                r("Track status online.", "অনলাইনে স্ট্যাটাস দেখুন।", "Ônlāinē sṭẽṭās dēkhun."),
                r("Thank you, officer.", "ধন্যবাদ, অফিসার।", "Dhonyobād, ôphisār."),
                r("Goodbye.", "বিদায়।", "Bidāy."),
                r("Have a good day.", "শুভ দিন।", "Shubho din."),
                r("I will wait for confirmation.", "নিশ্চিতকরণের অপেক্ষায়।", "Nishchitkôroṇēr ôpekhshāẏ."),
                r("Please keep my data safe.", "আমার তথ্য নিরাপদ রাখুন।", "Āmār tôthyo nirāpôd rākhun."),
                r("See you.", "দেখা হবে।", "Dēkhā hōbe."),
                r("Take care.", "ভালো থাকবেন।", "Bhālō thākben."),
            ],
        )
    )
    out.append(
        _c(
            641,
            "Simple Bengali conversation – Republic Day 26th January celebration",
            "Parade, flag, national anthem, and patriotic phrases.",
            "জাতীয় সঙ্গীত — national anthem.",
            [
                r("Happy Republic Day!", "গণতন্ত্র দিবসের শুভেচ্ছা!", "Gônotôntro dibosēr shubhēchchhā!"),
                r("26 January is our Republic Day.", "২৬ জানুয়ারি আমাদের প্রজাতন্ত্র দিবস।", "26 Jānuārī āmādēr prôjātôntro dibos."),
                r("We hoist the flag.", "আমরা পতাকা উত্তোলন করি।", "Āmrā potākā uttôlon kori."),
                r("Please stand for the anthem.", "জাতীয় সঙ্গীতের জন্য দাঁড়ান।", "Jātīẏô songītēr jônyo dãṛān."),
                r("The parade was amazing.", "প্যারেড দারুণ ছিল।", "Pyārēḍ dāruṇ chhil."),
                r("Children performed nicely.", "বাচ্চারা সুন্দর পরিবেশন করেছে।", "Bāchchārā sundor poribēshôn korechhe."),
                r("I feel proud to be Indian.", "ভারতীয় হয়ে গর্বিত।", "Bhārôtīẏô hōye gôrbito."),
                r("Long live the Constitution.", "সংবিধান চিরজীবী হোক।", "Shôngbidhān chirjībi hōk."),
                r("We remember the freedom fighters.", "স্বাধীনতা সংগ্রামীদের মনে করি।", "Shādhīnotā songrāmīdēr mōne kori."),
                r("Let's maintain unity.", "একতা বজায় রাখি।", "Ēkotā bojāy rākhi."),
                r("Jai Hind!", "জয় হিন্দ!", "Joy Hind!"),
                r("Bharat Mata ki jai!", "ভারত মাতা কী জয়!", "Bhārôt mātā ki joy!"),
                r("The weather is cold today.", "আজ ঠান্ডা।", "Āj ṭhāṇḍā."),
                r("Wear warm clothes.", "গরম কাপড় পরুন।", "Gôrom kāpoṛ pôrun."),
                r("Thank you for organizing.", "আয়োজনের জন্য ধন্যবাদ।", "Āẏojonēr jônyo dhonyobād."),
                r("See you at the school function.", "স্কুলের অনুষ্ঠানে দেখা হবে।", "Skulēr ônushṭhānē dēkhā hōbe."),
                r("Good night.", "শুভ রাত্রি।", "Shubho rātri."),
                r("Goodbye.", "বিদায়।", "Bidāy."),
            ],
        )
    )
    out.append(
        _c(
            642,
            "Simple Bengali conversation – In Bank",
            "Account opening, balance, withdrawal, and forms.",
            "অ্যাকাউন্ট — account; ব্যালান্স — balance.",
            [
                r("I want to open a savings account.", "আমি সঞ্চয় অ্যাকাউন্ট খুলতে চাই।", "Āmi sôñchôẏ ẹkāuṇṭ khulte chāi."),
                r("Here are my documents.", "আমার কাগজপত্র।", "Āmār kāgôjpotro."),
                r("What is the minimum balance?", "সর্বনিম্ন ব্যালান্স কত?", "Sôrbônimno bẽlāns kôt?"),
                r("What is my account number?", "অ্যাকাউন্ট নম্বর কী?", "Ẹkāuṇṭ nombor ki?"),
                r("Please check my balance.", "ব্যালান্স দেখুন।", "Bẽlāns dēkhun."),
                r("I need to withdraw cash.", "নগদ তুলতে হবে।", "Nogod tulte hōbe."),
                r("Fill this withdrawal form.", "উত্তোলন ফর্ম পূরণ করুন।", "Uttôlon phôrm pūroṇ kôrun."),
                r("How many free ATM transactions?", "কত ফ্রি এটিএম ট্রানজাকশন?", "Kôt phri eṭiem ṭrānjākshon?"),
                r("I want to deposit a cheque.", "চেক জমা দিতে চাই।", "Chek jomā dite chāi."),
                r("Please update my mobile number.", "মোবাইল নম্বর আপডেট করুন।", "Mōbāil nombor āpḍēṭ kôrun."),
                r("Is net banking available?", "নেট ব্যাংকিং আছে?", "Nēṭ bẽṅkiṃ āchhe?"),
                r("Thank you for your help.", "সাহায্যের জন্য ধন্যবাদ।", "Sāhājjēr jônyo dhonyobād."),
                r("Goodbye.", "বিদায়।", "Bidāy."),
                r("Have a good day.", "শুভ দিন।", "Shubho din."),
                r("See you next week.", "আগামী সপ্তাহে।", "Āgāmī soptāhē."),
                r("Please stamp this form.", "ফর্মে স্ট্যাম্প দিন।", "Phôrmē sṭẽmp din."),
                r("Where is the token counter?", "টোকেন কাউন্টার কোথায়?", "Ṭōkēn kāuṇṭār kōthāy?"),
                r("Next person, please.", "পরের জন, আসুন।", "Pōrēr jon, āsun."),
            ],
        )
    )
    out.append(
        _c(
            643,
            "Simple Bengali conversation – Enquiry about Temple Visit",
            "Timings, dress code, prasad, and photography rules.",
            "দর্শন — visit; প্রসাদ — prasad.",
            [
                r("When does the temple open?", "মন্দির কখন খোলে?", "Mondir kôkhon khōle?"),
                r("When does it close?", "কখন বন্ধ হয়?", "Kôkhon bondho hōy?"),
                r("Is there an evening aarti?", "সন্ধ্যার আরতি আছে?", "Sondhyār ārti āchhe?"),
                r("Where do we keep shoes?", "জুতো কোথায় রাখব?", "Jutō kōthāy rākhbō?"),
                r("Is photography allowed?", "ছবি তোলা যাবে?", "Chobi tōlā jābe?"),
                r("Please cover your shoulders.", "কাঁধ ঢেকে নিন।", "Kãdh dhēkē nin."),
                r("How do I get prasad?", "প্রসাদ কীভাবে পাব?", "Prāsād kībhābē pāb?"),
                r("Is there a special darshan ticket?", "বিশেষ দর্শনের টিকিট আছে?", "Bishēṣ dôrshonēr ṭikiṭ āchhe?"),
                r("Where is the main deity?", "মূল মূর্তি কোথায়?", "Mūl mūrti kōthāy?"),
                r("Can I offer flowers?", "ফুল দিতে পারি?", "Phul dite pāri?"),
                r("The temple is very peaceful.", "মন্দির খুব শান্ত।", "Mondir khub shānto."),
                r("Thank you for the information.", "তথ্যের জন্য ধন্যবাদ।", "Tôthyēr jônyo dhonyobād."),
                r("May I sit inside?", "ভিতরে বসতে পারি?", "Bhitore boste pāri?"),
                r("Please maintain silence.", "নীরব থাকুন।", "Nīrob thākun."),
                r("Happy journey to the shrine.", "মন্দির যাত্রা শুভ হোক।", "Mondir jātrā shubho hōk."),
                r("Goodbye.", "বিদায়।", "Bidāy."),
                r("See you again.", "আবার আসব।", "Ābār āsbo."),
                r("God bless you.", "ভগবান আপনাকে রাখুক।", "Bhogobān āpnākē rākhuk."),
            ],
        )
    )
    out.append(
        _c(
            644,
            "Simple Bengali conversation – with friend's parents at lunch table",
            "Polite mealtime talk with elders.",
            "আর কিছু — want some more?",
            [
                r("Namaskar, aunty and uncle.", "নমস্কার, মাসি আর কাকা।", "Nômôskār, māsi ār kākā."),
                r("The food smells wonderful.", "খাবারের গন্ধ দারুণ।", "Khābārēr gôndh dāruṇ."),
                r("May I wash my hands?", "হাত ধুতে যাব?", "Hāt dhute jāb?"),
                r("This dal is delicious.", "ডালটা অসাধারণ।", "Ḍālṭā ôsādhāroṇ."),
                r("A little more rice, please.", "আর একটু ভাত দিন।", "Ār ekoṭu bhāt din."),
                r("I am full, thank you.", "পেট ভরে গেছে, ধন্যবাদ।", "Pēṭ bhorē gēchhe, dhonyobād."),
                r("Your cooking is excellent.", "রান্না খুব ভালো।", "Rānnā khub bhālō."),
                r("What sweet is this?", "মিষ্টিটা কী?", "Miṣṭiṭā ki?"),
                r("I will help clear the table.", "টেবিল গুছিয়ে দিই।", "Ṭēbil guchhiẏē dii."),
                r("Thank you for inviting me.", "আমন্ত্রণের জন্য ধন্যবাদ।", "Āmontrôṇēr jônyo dhonyobād."),
                r("Your home is beautiful.", "বাড়িটা সুন্দর।", "Bāṛiṭā sundor."),
                r("I should leave now.", "আমি এখন চলব।", "Āmi ēkhon cholbo."),
                r("Please visit us too.", "আপনারাও আসবেন।", "Āpnārāo āsben."),
                r("Goodbye.", "বিদায়।", "Bidāy."),
                r("Take care.", "ভালো থাকবেন।", "Bhālō thākben."),
                r("See you soon.", "শীঘ্রই দেখা হবে।", "Shīghroi dēkhā hōbe."),
                r("Thank you for everything.", "সবকিছুর জন্য ধন্যবাদ।", "Sôbkichhur jônyo dhonyobād."),
                r("Good afternoon.", "শুভ অপরাহ্ন।", "Shubho ôporāhno."),
            ],
        )
    )
    # ----- 645–657 -----
    out.append(
        _c(
            645,
            "Simple Bengali conversation – Friend talking about football match",
            "Scores, players, and post-match chat.",
            "গোল — goal; ম্যাচ — match.",
            [
                r("Did you watch last night's match?", "গতকাল রাতের ম্যাচ দেখেছিস?", "Gôtokāl rāter myāch dēkhēchhis?"),
                r("Our team won!", "আমাদের দল জিতেছে!", "Āmādēr dôl jitechhe!"),
                r("The final goal was amazing.", "শেষ গোলটা অসাধারণ।", "Shēsh gōlṭā ôsādhāroṇ."),
                r("The goalkeeper saved a penalty.", "গোলকিপার পেনাল্টি বাঁচাল।", "Gōlkipār penālṭi bãchāl."),
                r("The referee was strict.", "রেফারি কড়া ছিল।", "Rēphāri koṛā chhil."),
                r("We missed an easy chance.", "সহজ সুযোগ মিস করেছি।", "Sôhoj sujog mis korechhi."),
                r("Next match is on Sunday.", "পরের ম্যাচ রবিবার।", "Pōrēr myāch rôbibār."),
                r("Let's watch together.", "একসাথে দেখি।", "Ēksāthe dēkhi."),
                r("I will bring snacks.", "নাস্তা নিয়ে আসব।", "Nāstā niyē āsbo."),
                r("The stadium was full.", "স্টেডিয়াম ভর্তি।", "Sṭēḍiẏām bhôrti."),
                r("I support this club.", "আমি এই ক্লাবকে সমর্থন করি।", "Āmi ei klābkē somorthon kori."),
                r("He is my favourite player.", "সে আমার প্রিয় খেলোয়াড়।", "Sē āmār priyo khēloẏāṛ."),
                r("Bad luck for the other team.", "অন্য দলের দুর্ভাগ্য।", "Ônno dōlēr dubhāggyo."),
                r("What a match!", "কী ম্যাচ!", "Ki myāch!"),
                r("See you at the cafe.", "ক্যাফেতে দেখা হবে।", "Kyāfētē dēkhā hōbe."),
                r("Bye.", "টাটা।", "Ṭāṭā."),
                r("Good night.", "শুভ রাত্রি।", "Shubho rātri."),
                r("Talk tomorrow.", "কাল কথা হবে।", "Kāl kōthā hōbe."),
            ],
        )
    )
    out.append(
        _c(
            646,
            "Simple Bengali conversation – Friends plan to watch movie",
            "Choosing a film, time, tickets, and snacks.",
            "সিনেমা — movie; টিকিট — ticket.",
            [
                r("Shall we watch a film tonight?", "আজ রাতে সিনেমা দেখব?", "Āj rāte sinēmā dēkhbō?"),
                r("Which hall?", "কোন হলে?", "Kōn hōlē?"),
                r("What time is the show?", "শো কখন?", "Ō kôkhon?"),
                r("Book two tickets in the middle row.", "মাঝের সারিতে দুটো টিকিট বুক করো।", "Mājher sārite duṭō ṭikiṭ buk kōrō."),
                r("I will pay online.", "আমি অনলাইনে দেব।", "Āmi ônlāinē debō."),
                r("Popcorn or nachos?", "পপকর্ন না নাচোস?", "Popkôrn nā nāchos?"),
                r("Do not spoil the story.", "গল্প ফাঁস করিস না।", "Gôlpô fãs koris nā."),
                r("The reviews are good.", "রিভিউ ভালো।", "Ribhiu bhālō."),
                r("Let's meet at six.", "ছয়টায় দেখা করি।", "Chhôyṭāẏ dēkhā kori."),
                r("I am running late.", "আমি দেরি করছি।", "Āmi dēri korchhi."),
                r("Save a seat for me.", "আমার জন্য সিট রাখ।", "Āmār jônyo siṭ rākh."),
                r("The AC is too cold.", "এসি খুব ঠান্ডা।", "Ēsi khub ṭhāṇḍā."),
                r("That scene was emotional.", "সেই দৃশ্যটা ইমোশনাল।", "Sēi drishyoṭā imōshonāl."),
                r("Let's eat after the movie.", "সিনেমার পরে খাই।", "Sinēmār pōrē khāi."),
                r("Great plan!", "দারুণ প্ল্যান!", "Dāruṇ plên!"),
                r("See you.", "দেখা হবে।", "Dēkhā hōbe."),
                r("Bye.", "টাটা।", "Ṭāṭā."),
                r("Good night.", "শুভ রাত্রি।", "Shubho rātri."),
            ],
        )
    )
    out.append(
        _c(
            647,
            "Simple Bengali conversation – Friends talking about football world cup",
            "Teams, groups, favourites, and watching together.",
            "ওয়ার্ল্ড কাপ — World Cup.",
            [
                r("The World Cup has started.", "ওয়ার্ল্ড কাপ শুরু হয়েছে।", "Ōārld kāp shuru hōyēchhe."),
                r("Which team do you support?", "কোন দলকে সমর্থন করো?", "Kōn dôlkē somorthon kōrō?"),
                r("Brazil plays well.", "ব্রাজিল ভালো খেলে।", "Brājil bhālō khēlē."),
                r("Argentina has strong fans.", "আর্জেন্টিনার সমর্থক বেশি।", "Ārjenṭinār somorthok bēshi."),
                r("The match was a draw.", "ম্যাচ ড্র হয়েছে।", "Myāch ḍrô hōyēchhe."),
                r("What a goal!", "কী গোল!", "Ki gōl!"),
                r("The referee gave a red card.", "রেফারি লাল কার্ড দিল।", "Rēphāri lāl kāṛ dil."),
                r("Let's watch at my place.", "আমার বাড়িতে দেখি।", "Āmār bāṛite dēkhi."),
                r("I will bring chips.", "চিপস নিয়ে আসব।", "Chips niyē āsbo."),
                r("Who will win?", "কে জিতবে?", "Kē jitbē?"),
                r("Penalty shoot-out is tense.", "পেনাল্টি শুটআউট উত্তেজনাপূর্ণ।", "Penālṭi shuṭāuṭ uttējonāpūrṇo."),
                r("The crowd is cheering.", "দর্শকরা চিয়ার করছে।", "Dôrshôkrā chiyār korchhe."),
                r("Next match is tomorrow.", "পরের ম্যাচ কাল।", "Pōrēr myāch kāl."),
                r("Do not wake the neighbours.", "প্রতিবেশীকে জাগিও না।", "Prôtibēshīkē jāgio nā."),
                r("That was unfair.", "এটা অন্যায়।", "Ēṭā ônyāẏ."),
                r("See you for the final.", "ফাইনালে দেখা হবে।", "Phāinālē dēkhā hōbe."),
                r("Bye.", "টাটা।", "Ṭāṭā."),
                r("Good night.", "শুভ রাত্রি।", "Shubho rātri."),
            ],
        )
    )
    out.append(
        _c(
            648,
            "Simple Bengali conversation – Tour guide with tourists",
            "Sightseeing, timing, tickets, and safety tips.",
            "দর্শনীয় স্থান — place of interest.",
            [
                r("Welcome to Kolkata.", "কলকাতায় স্বাগতম।", "Kolkātāẏ shbāgotom."),
                r("Today we visit Victoria Memorial.", "আজ ভিক্টোরিয়া মেমোরিয়াল দেখব।", "Āj Vikṭōriẏā Mēmōriẏāl dēkhbō."),
                r("Please assemble at nine.", "নয়টায় জড়ো হন।", "Nôyṭāẏ jōṛō hon."),
                r("This building is from the British era.", "এই ভবন ব্রিটিশ আমলের।", "Ei bhôbôn Briṭish āmlēr."),
                r("Photography is allowed here.", "এখানে ছবি তোলা যাবে।", "Ēkhāne chobi tōlā jābe."),
                r("Do not litter.", "আবর্জনা ফেলবেন না।", "Ābôrjōnā phēlben nā."),
                r("We have one hour here.", "এখানে এক ঘণ্টা আছে।", "Ēkhāne ek ghôṇṭā āchhe."),
                r("Follow me, please.", "আমার পিছনে আসুন।", "Āmār pichhōne āsun."),
                r("The museum is closed on Mondays.", "সোমবার জাদুঘর বন্ধ।", "Sōmbār jādughôr bondho."),
                r("Buy tickets at the counter.", "কাউন্টার থেকে টিকিট কিনুন।", "Kāuṇṭār theke ṭikiṭ kinun."),
                r("Stay with the group.", "দলের সঙ্গে থাকুন।", "Dōlēr songe thākun."),
                r("Hydrate in the heat.", "গরমে জল খান।", "Gôromē jol khān."),
                r("Any questions?", "কোনো প্রশ্ন?", "Kōnō prôshno?"),
                r("Thank you for visiting.", "ঘুরে দেখার জন্য ধন্যবাদ।", "Ghurē dēkhār jônyo dhonyobād."),
                r("Enjoy your stay.", "ভালো কাটুক।", "Bhālō kāṭuk."),
                r("Goodbye.", "বিদায়।", "Bidāy."),
                r("See you tomorrow.", "কাল দেখা হবে।", "Kāl dēkhā hōbe."),
                r("Take care.", "ভালো থাকবেন।", "Bhālō thākben."),
            ],
        )
    )
    out.append(
        _c(
            649,
            "Simple Bengali Conversation – Language Proficiency Test for banks",
            "Formal test context: reading, comprehension, instructions.",
            "পরীক্ষা — exam; অনুচ্ছেদ — paragraph.",
            [
                r("Good morning, I am the examiner.", "সুপ্রভাত, আমি পরীক্ষক।", "Suprobhāt, āmi porīkhkôk."),
                r("Please read this paragraph aloud.", "এই অনুচ্ছেদ জোরে পড়ুন।", "Ei ônuchchhēd jōrē pōṛun."),
                r("Can you translate this sentence?", "এই বাক্যটা অনুবাদ করতে পারবেন?", "Ei bākyaṭā ônubād korte pārben?"),
                r("What is the main idea?", "মূল ভাবনা কী?", "Mūl bhābnā ki?"),
                r("Please answer in Bengali.", "বাংলায় উত্তর দিন।", "Bāṅlāẏ uttor din."),
                r("Speak slowly and clearly.", "ধীরে স্পষ্ট বলুন।", "Dhīre spôshṭ bôlun."),
                r("You have ten minutes.", "দশ মিনিট সময় আছে।", "Dôsh miniṭ somoy āchhe."),
                r("Do you understand the question?", "প্রশ্নটা বুঝেছেন?", "Prôshnoṭā bujhechhen?"),
                r("Take your time.", "সময় নিন।", "Somoy nin."),
                r("Thank you, that is enough.", "ধন্যবাদ, যথেষ্ট।", "Dhonyobād, jôthēshṭo."),
                r("Your pronunciation is clear.", "উচ্চারণ পরিষ্কার।", "Ucchāroṇ porishkār."),
                r("Practice reading newspapers daily.", "প্রতিদিন পত্রিকা পড়ুন।", "Prôtidin potrikā pōṛun."),
                r("We will inform the results by email.", "ফল ইমেইলে জানাব।", "Phol imēilē jānābō."),
                r("Good effort.", "ভালো চেষ্টা।", "Bhālō chēṣṭā."),
                r("You may leave now.", "এখন যেতে পারেন।", "Ēkhon jēte pāren."),
                r("Goodbye.", "বিদায়।", "Bidāy."),
                r("Have a good day.", "শুভ দিন।", "Shubho din."),
                r("All the best.", "সব ভালো হোক।", "Sôb bhālō hōk."),
            ],
        )
    )
    out.append(
        _c(
            650,
            "Simple Bengali conversation about food, lunch, meal",
            "Meals, taste, diet, and restaurant talk.",
            "দুপুরের খাবার — lunch.",
            [
                r("What did you eat for lunch?", "দুপুরে কী খেয়েছো?", "Dupurē ki khēyēchho?"),
                r("I had rice and fish.", "ভাত আর মাছ খেয়েছি।", "Bhāt ār māch khēyēchhi."),
                r("I am vegetarian.", "আমি নিরামিষ খাই।", "Āmi nirāmiṣ khāi."),
                r("This curry is spicy.", "এই ঝালটা ঝাল।", "Ei jhālṭā jhāl."),
                r("Please pass the salt.", "লবণ দিন।", "Lôboṇ din."),
                r("The dessert was sweet.", "মিষ্টিটা মিষ্টি।", "Miṣṭiṭā miṣṭi."),
                r("I am full.", "পেট ভরে গেছে।", "Pēṭ bhorē gēchhe."),
                r("Shall we order tea?", "চা অর্ডার করব?", "Chā ôrḍār korbō?"),
                r("The bill, please.", "বিল দিন।", "Bil din."),
                r("Service was quick.", "সেবা দ্রুত।", "Sēbā drut."),
                r("I do not eat beef.", "আমি গরুর মাংস খাই না।", "Āmi gorur māṅsō khāi nā."),
                r("Home food is best.", "বাড়ির খাবার সেরা।", "Bāṛir khābār sērā."),
                r("Let's cook together.", "একসাথে রান্না করি।", "Ēksāthe rānnā kori."),
                r("Wash your hands.", "হাত ধুয়ে নাও।", "Hāt dhuẏē nāo."),
                r("Bon appetit.", "ভালো করে খাও।", "Bhālō kōre khāo."),
                r("Thank you for the meal.", "খাবারের জন্য ধন্যবাদ।", "Khābārēr jônyo dhonyobād."),
                r("See you at dinner.", "রাতের খাবারে দেখা হবে।", "Rāter khābārē dēkhā hōbe."),
                r("Good night.", "শুভ রাত্রি।", "Shubho rātri."),
            ],
        )
    )
    out.append(
        _c(
            651,
            "Simple Bengali Conversation – About hobby class",
            "Music, art, dance classes and schedules.",
            "ক্লাস — class; অনুশীলন — practice.",
            [
                r("What is your hobby?", "আপনার শখ কী?", "Āpār shôkh ki?"),
                r("I like painting.", "আমি ছবি আঁকতে পছন্দ করি।", "Āmi chobi ãkte pôchondo kori."),
                r("I learn tabla on Sundays.", "আমি রবিবার তবলা শিখি।", "Āmi rôbibār tablā shikhi."),
                r("The class is at five.", "ক্লাস পাঁচটায়।", "Klās pā̃choṭāẏ."),
                r("Bring your own instrument.", "নিজের বাজনা নিয়ে আসুন।", "Nijēr bājnā niyē āsun."),
                r("The teacher is very patient.", "শিক্ষক খুব ধৈর্যশীল।", "Shikkhôk khub dhôirjoshīl."),
                r("Practice fifteen minutes daily.", "প্রতিদিন পোনেরো মিনিট অনুশীলন।", "Prôtidin pōnērō miniṭ ônushīlon."),
                r("May I watch the demo class?", "ডেমো ক্লাস দেখতে পারি?", "Ḍēmō klās dekhte pāri?"),
                r("What is the monthly fee?", "মাসিক ফি কত?", "Māsik phī kôt?"),
                r("I will join next month.", "আগামী মাসে ভর্তি হব।", "Āgāmī māsē bhôrti hobo."),
                r("Wear comfortable clothes.", "আরামদায়ক কাপড় পরুন।", "Ārāmdāẏok kāpoṛ pôrun."),
                r("Thank you for the information.", "তথ্যের জন্য ধন্যবাদ।", "Tôthyēr jônyo dhonyobād."),
                r("See you in class.", "ক্লাসে দেখা হবে।", "Klāsē dēkhā hōbe."),
                r("Goodbye.", "বিদায়।", "Bidāy."),
                r("Have fun.", "মজা করো।", "Mojā kōrō."),
                r("Keep practicing.", "অনুশীলন চালিয়ে যান।", "Ônushīlon chāliẏē jān."),
                r("Good luck.", "শুভকামনা।", "Shubhokāmnā."),
                r("Take care.", "ভালো থাকবেন।", "Bhālō thākben."),
            ],
        )
    )
    out.append(
        _c(
            652,
            "Frequently used sentences in Bengali – miscellaneous",
            "Short lines for everyday situations.",
            "চলো — let's go; এক মিনিট — one minute.",
            [
                r("I am going now.", "আমি এখন যাচ্ছি।", "Āmi ēkhon jāchchhi."),
                r("Wait a minute.", "এক মিনিট অপেক্ষা করো।", "Ek miniṭ ôpekhshā kōrō."),
                r("See you later.", "পরে দেখা হবে।", "Pōre dēkhā hōbe."),
                r("Call me.", "আমাকে ফোন করো।", "Āmākē phōn kōrō."),
                r("I will message you.", "মেসেজ করব।", "Mēsēj korbo."),
                r("No problem.", "কোনো ব্যাপার না।", "Kōnō bẽpār nā."),
                r("Sorry for the delay.", "দেরির জন্য সরি।", "Dērir jônyo sori."),
                r("What happened?", "কী হয়েছে?", "Ki hōyēchhe?"),
                r("I forgot.", "ভুলে গেছি।", "Bhule gēchhi."),
                r("I remember.", "মনে আছে।", "Mōne āchhe."),
                r("Help me, please.", "সাহায্য করো।", "Sāhājjo kōrō."),
                r("I am busy.", "আমি ব্যস্ত।", "Āmi bēsto."),
                r("Come quickly.", "তাড়াতাড়ি এসো।", "Ṭāṛāṭāṛi ēsō."),
                r("Let's go.", "চলো যাই।", "Chōlō jāi."),
                r("Okay.", "ঠিক আছে।", "Ṭhik āchhe."),
                r("Really?", "সত্যি?", "Sôtyi?"),
                r("Thank you.", "ধন্যবাদ।", "Dhonyobād."),
                r("Good night.", "শুভ রাত্রি।", "Shubho rātri."),
            ],
        )
    )
    out.append(
        _c(
            653,
            "Frequently used sentences in Bengali – miscellaneous part 2",
            "More everyday phrases: shopping, travel, feelings.",
            "দাম — price; ভিড় — crowd.",
            [
                r("I am tired.", "আমি ক্লান্ত।", "Āmi klānto."),
                r("Take your time.", "সময় নিন।", "Somoy nin."),
                r("How much is this?", "এটার দাম কত?", "Ēṭār dām kôt?"),
                r("Too expensive.", "খুব দামি।", "Khub dāmi."),
                r("Give a discount.", "ছাড় দিন।", "Chāṛ din."),
                r("I like this.", "আমার এটা ভালো লাগে।", "Āmār ēṭā bhālō lāgē."),
                r("I do not like it.", "আমার ভালো লাগে না।", "Āmār bhālō lāgē nā."),
                r("Where is the toilet?", "টয়লেট কোথায়?", "Ōyalēṭ kōthāy?"),
                r("I feel sick.", "আমার খারাপ লাগছে।", "Āmār khārāp lāgchhe."),
                r("Be careful.", "সাবধান।", "Sābdhān."),
                r("Hurry up.", "তাড়াতাড়ি করো।", "Ṭāṛāṭāṛi kōrō."),
                r("I am lost.", "পথ হারিয়েছি।", "Poth hāriẏechhi."),
                r("Can you help?", "সাহায্য করবেন?", "Sāhājjo kôrben?"),
                r("The traffic is bad.", "ট্রাফিক খারাপ।", "Ṭrāphik khārāp."),
                r("I am hungry.", "আমার খিদে পেয়েছে।", "Āmār khide peẏechhe."),
                r("I am thirsty.", "আমার তেষ্টা পেয়েছে।", "Āmār tēshṭā peẏechhe."),
                r("Good idea.", "ভালো ধারণা।", "Bhālō dhāroṇā."),
                r("See you.", "দেখা হবে।", "Dēkhā hōbe."),
            ],
        )
    )
    out.append(
        _c(
            654,
            "Learn Bengali by Communicative Approach",
            "Learning tips: speak, listen, repeat, real tasks.",
            "যোগাযোগ — communication.",
            [
                r("Practice speaking every day.", "প্রতিদিন বলার অনুশীলন করুন।", "Prôtidin bolār ônushīlon kôrun."),
                r("Do not fear mistakes.", "ভুলের ভয় করবেন না।", "Bhuler bhôy kôrben nā."),
                r("Listen to native speakers.", "মাতৃভাষীদের কথা শুনুন।", "Mātṛbhāṣhīdēr kōthā shunun."),
                r("Repeat after the audio.", "অডিওর পরে পুনরাবৃত্তি করুন।", "Oḍiōr pōre punorābritti kôrun."),
                r("Learn phrases, not only words.", "শুধু শব্দ নয়, বাক্য শিখুন।", "Shudhu shôbdô nôy, bākya shikhun."),
                r("Talk about your day.", "আপনার দিন নিয়ে কথা বলুন।", "Āpār din niyē kōthā bôlun."),
                r("Write a short diary in Bengali.", "বাংলায় ছোট ডায়রি লিখুন।", "Bāṅlāẏ choṭ ḍāẏri likhun."),
                r("Watch Bengali films with subtitles.", "সাবটাইটেল দিয়ে সিনেমা দেখুন।", "Sābṭāiṭel diẏē sinēmā dēkhun."),
                r("Find a language partner.", "একজন ভাষা সঙ্গী খুঁজুন।", "Ekjon bhāṣā songī khun̐jun."),
                r("Set small weekly goals.", "সাপ্তাহিক ছোট লক্ষ্য রাখুন।", "Sāptāhik choṭ lôkkho rākhun."),
                r("Celebrate small wins.", "ছোট জয় উদযাপন করুন।", "Choṭ jôy udẏāpôn kôrun."),
                r("Ask: How do you say this?", "এটা বাংলায় কী বলে জিজ্ঞেস করুন।", "Ēṭā bāṅlāẏ ki bōlē jijñēs kôrun."),
                r("Keep a vocabulary notebook.", "শব্দের খাতা রাখুন।", "Shôbdēr khātā rākhun."),
                r("Read signs on the street.", "রাস্তার সাইনবোর্ড পড়ুন।", "Rāstār sāinbōrḍ pōṛun."),
                r("You will improve slowly.", "ধীরে ধীরে ভালো হবে।", "Dhīre dhīre bhālō hōbe."),
                r("Keep going.", "চালিয়ে যান।", "Chāliẏē jān."),
                r("Good luck.", "শুভকামনা।", "Shubhokāmnā."),
                r("We believe in you.", "আমরা আপনাকে বিশ্বাস করি।", "Āmrā āpnākē bishbās kori."),
            ],
        )
    )
    out.append(
        _c(
            655,
            "Simple Bengali sentences practice – 1",
            "Drill lines for greetings, origin, and polite chat.",
            "আমি … থেকে — I am from …",
            [
                r("Where are you from?", "আপনি কোথা থেকে?", "Āpni kōthā theke?"),
                r("I am from Kolkata.", "আমি কলকাতার।", "Āmi Kolkātār."),
                r("I am from Dhaka.", "আমি ঢাকার।", "Āmi Ḍhākār."),
                r("Nice to meet you.", "দেখা হয়ে ভালো লাগল।", "Dēkhā hōye bhālō lāglo."),
                r("What do you do?", "আপনি কী করেন?", "Āpni ki kôren?"),
                r("I am a student.", "আমি ছাত্র।", "Āmi chātrô."),
                r("I am a teacher.", "আমি শিক্ষক।", "Āmi shikkhôk."),
                r("I work in a bank.", "আমি ব্যাংকে কাজ করি।", "Āmi bẽkē kāj kori."),
                r("How is your family?", "পরিবার কেমন আছে?", "Poribār kēmon āchhe?"),
                r("Everyone is fine.", "সবাই ভালো আছে।", "Sôbāi bhālō āchhe."),
                r("What are your hobbies?", "শখ কী?", "Shôkh ki?"),
                r("I like music.", "আমার গান পছন্দ।", "Āmār gān pôchondo."),
                r("Do you speak English?", "আপনি ইংরেজি বলেন?", "Āpni iṃrēji bôlen?"),
                r("A little Bengali.", "একটু বাংলা।", "Ekoṭu bāṅlā."),
                r("Please speak slowly.", "আস্তে বলুন।", "Āste bôlun."),
                r("Thank you for talking.", "কথা বলার জন্য ধন্যবাদ।", "Kōthā bolār jônyo dhonyobād."),
                r("See you again.", "আবার দেখা হবে।", "Ābār dēkhā hōbe."),
                r("Goodbye.", "বিদায়।", "Bidāy."),
            ],
        )
    )
    out.append(
        _c(
            656,
            "Bengali practice session – prepositions",
            "In, on, under, behind, between — in short sentences.",
            "উপরে — on; নিচে — under.",
            [
                r("The book is on the table.", "বইটা টেবিলে।", "Bôiṭā ṭēbile."),
                r("The bag is under the chair.", "ব্যাগটা চেয়ারের নিচে।", "Bẽgṭā cheẏārēr nīche."),
                r("The keys are in the drawer.", "চাবি দরাজে।", "Chābi dôrājē."),
                r("The cat is behind the door.", "বিড়াল দরজার পিছনে।", "Biṛāl dôrjār pichhōne."),
                r("Sit between us.", "আমাদের মাঝে বসো।", "Āmādēr mājhe bôsō."),
                r("The shop is near the bank.", "দোকান ব্যাংকের কাছে।", "Dokān bẽkēr kāchhe."),
                r("He lives across the river.", "নদীর ওপারে থাকে।", "Nodīr ōpārē thākē."),
                r("Wait at the gate.", "গেটে দাঁড়াও।", "Gēṭē dãṛāo."),
                r("Put the phone on charge.", "ফোন চার্জে দাও।", "Phōn chārjē dāo."),
                r("The picture is on the wall.", "ছবিটা দেয়ালে।", "Chobiṭā dēẏālē."),
                r("Come in front of the class.", "ক্লাসের সামনে এসো।", "Klāsēr sāmne ēsō."),
                r("The keys fell from my hand.", "হাত থেকে চাবি পড়ে গেছে।", "Hāt theke chābi poṛē gēchhe."),
                r("Stand beside me.", "আমার পাশে দাঁড়াও।", "Āmār pāshe dãṛāo."),
                r("The car is in the garage.", "গাড়ি গ্যারেজে।", "Gāṛi gyārējē."),
                r("We walked along the river.", "নদী ধরে হেঁটেছি।", "Nodī dhōre hẽṭechhi."),
                r("Good examples.", "ভালো উদাহরণ।", "Bhālō udāhoroṇ."),
                r("Practice again tomorrow.", "কাল আবার অনুশীলন।", "Kāl ābār ônushīlon."),
                r("Well done.", "খুব ভালো।", "Khub bhālō."),
            ],
        )
    )
    out.append(
        _c(
            657,
            "Bengali jokes – Learn Bengali in a fun way",
            "Light riddles and punchlines for learners.",
            "হাসি — laughter.",
            [
                r("Why did the boy laugh?", "ছেলেটা কেন হাসল?", "Chēlēṭā kēn hāslo?"),
                r("Because it was funny!", "কারণ মজার ছিল!", "Kāraṇ mojār chhil!"),
                r("Teacher: Where is Bengal?", "শিক্ষক: বাংলা কোথায়?", "Shikkhôk: Bāṅlā kōthāy?"),
                r("Student: In my heart.", "ছাত্র: আমার মনে।", "Chātrô: āmār mōne."),
                r("What has keys but cannot open locks?", "চাবি আছে কিন্তু তালা খোলে না—কী?", "Chābi āchhe kintu tālā khōle nā—ki?"),
                r("A piano!", "পিয়ানো!", "Piẏānō!"),
                r("Why is six afraid of seven?", "ছয় সাতকে কেন ভয় পায়?", "Chhôy sātkē kēn bhôy pāẏ?"),
                r("Because seven eight nine.", "কারণ সাত আট নয়।", "Kāraṇ sāt āṭ nôy."),
                r("That is a number joke!", "সংখ্যার কৌতুক!", "Shôngkhyār koutuk!"),
                r("Laughing is healthy.", "হাসা স্বাস্থ্যের জন্য ভালো।", "Hāsā swāsthyēr jônyo bhālō."),
                r("Tell me another joke.", "আর একটা কৌতুক বলো।", "Ār ekṭā koutuk bōlō."),
                r("I will try.", "চেষ্টা করি।", "Chēṣṭā kori."),
                r("Comedy shows help learning.", "কমেডি শেখাতে সাহায্য করে।", "Komēḍi shēkhātē sāhājjo kōre."),
                r("Smile, please.", "হাসুন।", "Hāsun."),
                r("Good mood today?", "আজ মেজ ভালো?", "Āj mej bhālō?"),
                r("Yes, very happy.", "হ্যাঁ, খুব খুশি।", "Hyẫ, khub khushi."),
                r("See you.", "দেখা হবে।", "Dēkhā hōbe."),
                r("Bye.", "টাটা।", "Ṭāṭā."),
            ],
        )
    )
    # ----- 658–662 -----
    out.append(
        _c(
            658,
            "Daily Bengali reading practice – jokes, thoughts, quotes",
            "Short reflective lines for reading aloud.",
            "সময় — time; স্বাস্থ্য — health.",
            [
                r("Time is precious.", "সময় অনেক মূল্যবান।", "Somoy ônek mūlyabān."),
                r("Health is wealth.", "স্বাস্থ্যই সম্পদ।", "Swāsthōi sômpod."),
                r("Never give up.", "হার মানবেন না।", "Hār mānben nā."),
                r("Small steps bring big change.", "ছোট পদক্ষেপ বড় পরিবর্তন আনে।", "Choṭ podokhēp boṛ poribôrtôn ānē."),
                r("Read a little every day.", "প্রতিদিন একটু পড়ুন।", "Prôtidin ekoṭu pōṛun."),
                r("Kind words heal.", "কোমল কথা সুস্থ করে।", "Kōmol kōthā sustho kōre."),
                r("Help someone today.", "আজ কাউকে সাহায্য করুন।", "Āj kāukē sāhājjo kôrun."),
                r("Silence is also an answer.", "নীরবতাও উত্তর।", "Nīrobotāo uttor."),
                r("Dream big, work hard.", "বড় স্বপ্ন, কঠোর পরিশ্রম।", "Boṛ shôpno, kôṭhor porishrom."),
                r("Family comes first.", "পরিবার আগে।", "Poribār āgē."),
                r("Smile more.", "বেশি হাসুন।", "Bēshi hāsun."),
                r("Learn something new.", "নতুন কিছু শিখুন।", "Nôtun kichhu shikhun."),
                r("Walk in the morning.", "সকালে হাঁটুন।", "Sākālē hãṭun."),
                r("Save money wisely.", "বুদ্ধিমত্তায় টাকা জমান।", "Buddhimottāẏ ṭākā jomān."),
                r("Forgive and move on.", "ক্ষমা করে এগিয়ে যান।", "Khomā kōre egiẏē jān."),
                r("Today is a new day.", "আজ নতুন দিন।", "Āj nôtun din."),
                r("Good night.", "শুভ রাত্রি।", "Shubho rātri."),
                r("Sleep well.", "ভালো ঘুমান।", "Bhālō ghumān."),
            ],
        )
    )
    out.append(
        _c(
            659,
            "Simple Bengali sentences – My experience with Social Media",
            "Posting, scrolling, balance, and privacy.",
            "ফেসবুক — Facebook; ইনস্টাগ্রাম — Instagram.",
            [
                r("I use social media daily.", "আমি প্রতিদিন সোশ্যাল মিডিয়া ব্যবহার করি।", "Āmi prôtidin sōshyāl miḍiyā bôbohār kori."),
                r("Too much screen time.", "স্ক্রিন টাইম বেশি।", "Skrin ṭāim bēshi."),
                r("I posted a photo yesterday.", "গতকাল ছবি পোস্ট করেছি।", "Gôtokāl chobi pōsṭ korechhi."),
                r("I follow news pages.", "আমি নিউজ পেজ ফলো করি।", "Āmi niuj pej pholō kori."),
                r("Please respect privacy.", "গোপনীয়তা সম্মান করুন।", "Gôpônīẏotā shommān kôrun."),
                r("Do not share OTP.", "ওটিপি শেয়ার করবেন না।", "Ōṭipi sheẏār kôrben nā."),
                r("I muted noisy groups.", "আমি গ্রুপ মিউট করেছি।", "Āmi grūp miuṭ korechhi."),
                r("I limit usage at night.", "রাতে ব্যবহার কমাই।", "Rātē bôbohār komāi."),
                r("Real friends matter more.", "আসল বন্ধু বেশি দরকার।", "Ôsôl bondhu bēshi dôrkār."),
                r("I enjoy cooking videos.", "রান্নার ভিডিও ভালো লাগে।", "Rānnār biḍiō bhālō lāgē."),
                r("Cyber bullying is wrong.", "সাইবার বুলিং অন্যায়।", "Sāibār buliṃ ônyāẏ."),
                r("Report harmful posts.", "ক্ষতিকর পোস্ট রিপোর্ট করুন।", "Khotikôr pōsṭ ripōrṭ kôrun."),
                r("Take breaks from the phone.", "ফোন থেকে বিরতি নিন।", "Phōn theke birôti nin."),
                r("I feel better offline sometimes.", "কখনো অফলাইনে ভালো লাগে।", "Kôkhonô ôflāinē bhālō lāgē."),
                r("Balance is important.", "ভারসাম্য দরকার।", "Bhārshômmyo dôrkār."),
                r("Thank you for reading.", "পড়ার জন্য ধন্যবাদ।", "Pōṛār jônyo dhonyobād."),
                r("Good night.", "শুভ রাত্রি।", "Shubho rātri."),
                r("See you online.", "অনলাইনে দেখা হবে।", "Ônlāinē dēkhā hōbe."),
            ],
        )
    )
    out.append(
        _c(
            660,
            "Conversation about the eclipse in Bengali",
            "Safety, timing, and what people say during an eclipse.",
            "গ্রহণ — eclipse.",
            [
                r("There will be an eclipse today.", "আজ গ্রহণ হবে।", "Āj grôhoṇ hōbe."),
                r("What time does it start?", "কখন শুরু হবে?", "Kôkhon shuru hōbe?"),
                r("Do not look at the sun directly.", "সূর্যের দিকে সরাসরি তাকাবেন না।", "Sūryēr dikē sorāsori tākāben nā."),
                r("Use certified glasses.", "সার্টিফাইড চশমা ব্যবহার করুন।", "Sārṭiphāiḍ chôshomā bôbohār kôrun."),
                r("Children must be supervised.", "বাচ্চাদের দেখাশোনা করুন।", "Bāchchādēr dēkhāshonā kôrun."),
                r("The sky will look dark.", "আকাশ অন্ধকার হবে।", "Ākāś ôndhokār hōbe."),
                r("Some people fast during the eclipse.", "কেউ গ্রহণকালে উপবাস করে।", "Keu grôhoṇkālē upobās kōre."),
                r("I will watch the live stream.", "লাইভ স্ট্রিম দেখব।", "Lāib sṭrim dēkhbō."),
                r("Do not take photos without filters.", "ফিল্টার ছাড়া ছবি তুলবেন না।", "Philṭār chāṛā chobi tulben nā."),
                r("Animals may act strangely.", "পশুদের আচরণ অদ্ভুত হতে পারে।", "Pôshudēr āchôrôṇ ôdbhut hote pārē."),
                r("Check official timings.", "অফিসিয়াল সময় দেখুন।", "Ôphisiāl somoy dēkhun."),
                r("Stay indoors if cloudy.", "মেঘ থাকলে ঘরে থাকুন।", "Mēgh thāklē ghore thākun."),
                r("This is a rare event.", "এটা বিরল ঘটনা।", "Ēṭā birol ghoṭonā."),
                r("I am excited but careful.", "উত্তেজিত কিন্তু সাবধান।", "Uttējit kintu sābdhān."),
                r("Share correct information.", "সঠিক তথ্য শেয়ার করুন।", "Soṭhik tôthyo sheẏār kôrun."),
                r("Goodbye, stay safe.", "বিদায়, নিরাপদ থাকুন।", "Bidāy, nirāpôd thākun."),
                r("See you after the eclipse.", "গ্রহণের পরে দেখা হবে।", "Grôhoṇēr pōre dēkhā hōbe."),
                r("Thank you.", "ধন্যবাদ।", "Dhonyobād."),
            ],
        )
    )
    out.append(
        _c(
            661,
            "International Women's Day in Bengali",
            "Respect, equality, and appreciation phrases.",
            "নারী দিবস — Women's Day.",
            [
                r("Happy Women's Day!", "নারী দিবসের শুভেচ্ছা!", "Nārī dibosēr shubhēchchhā!"),
                r("Equality for all.", "সবার সমান অধিকার।", "Sobār somān ôdhikār."),
                r("Thank you to all women.", "সব নারীকে ধন্যবাদ।", "Sob nārīkē dhonyobād."),
                r("Women lead in every field.", "নারীরা প্রতিটি ক্ষেত্রে নেতৃত্ব দেন।", "Nārīrā prôtiṭi khētrē nētritwo dēn."),
                r("Respect women's choices.", "নারীদের পছন্দ সম্মান করুন।", "Nārīdēr pôchondo shommān kôrun."),
                r("Safety is a right.", "নিরাপত্তা অধিকার।", "Nirāpôttā ôdhikār."),
                r("Education empowers girls.", "শিক্ষা মেয়েদের শক্তি দেয়।", "Shikkhā mēẏēdēr shokti dēẏ."),
                r("Support working mothers.", "কর্মজীবী মাদের সাহায্য করুন।", "Kôrmojībi mādēr sāhājjo kôrun."),
                r("No to harassment.", "হয়রানি নয়।", "Hôẏrāni nôy."),
                r("Celebrate achievements.", "অর্জন উদযাপন করুন।", "Orjon udẏāpôn kôrun."),
                r("Listen to women's voices.", "নারীদের কথা শুনুন।", "Nārīdēr kōthā shunun."),
                r("Fair pay for fair work.", "ন্যায্য কাজে ন্যায্য বেতন।", "Nẽjjo kājē nẽjjo bēton."),
                r("Together we progress.", "একসাথে এগোব।", "Ēksāthe egōbō."),
                r("Flowers for you.", "আপনার জন্য ফুল।", "Āpār jônyo phul."),
                r("You inspire us.", "আপনি অনুপ্রাণিত করেন।", "Āpni ônuprāṇit kôren."),
                r("Have a wonderful day.", "সুন্দর দিন কাটুক।", "Sundor din kāṭuk."),
                r("Goodbye.", "বিদায়।", "Bidāy."),
                r("Take care.", "ভালো থাকবেন।", "Bhālō thākben."),
            ],
        )
    )
    out.append(
        _c(
            662,
            "Simple Bengali conversation – Quarrel at home",
            "Calming down, apologizing, and making peace.",
            "শান্ত হও — calm down.",
            [
                r("Please lower your voice.", "স্বর একটু নামান।", "Sôro ekoṭu nāmān."),
                r("Don't shout.", "চেঁচিয়ো না।", "Chẽchiyō nā."),
                r("Calm down.", "শান্ত হও।", "Shānto hō."),
                r("I am sorry.", "আমি দুঃখিত।", "Āmi duhkhito."),
                r("I did not mean to hurt you.", "তোমাকে কষ্ট দিতে চাইনি।", "Tōmākē kôshṭo dite chāini."),
                r("Let's talk calmly.", "শান্তভাবে কথা বলি।", "Shāntabhābē kōthā boli."),
                r("We can solve this.", "আমরা এটা মিটিয়ে নিতে পারি।", "Āmrā ēṭā miṭiẏe nite pāri."),
                r("I was stressed.", "আমি চাপে ছিলাম।", "Āmi chāpē chhilām."),
                r("Please forgive me.", "আমাকে ক্ষমা করো।", "Āmākē khomā kōrō."),
                r("Family is more important than ego.", "অহংকারের চেয়ে পরিবার বড়।", "Ôhoṅkārēr cheye poribār boṛ."),
                r("Let's take a break.", "একটু বিরতি নিই।", "Ekoṭu birôti nii."),
                r("I will listen to you.", "আমি তোমার কথা শুনব।", "Āmi tōmār kōthā shunbō."),
                r("Hugging helps sometimes.", "কখনো জড়িয়ে ধরা সাহায্য করে।", "Kôkhono joṛiẏe dhorā sāhājjo kōre."),
                r("Tomorrow is a new day.", "কাল নতুন দিন।", "Kāl nôtun din."),
                r("I love you all.", "আমি সবাইকে ভালোবাসি।", "Āmi sôbāikē bhālōbāsi."),
                r("Peace.", "শান্তি।", "Shānti."),
                r("Good night.", "শুভ রাত্রি।", "Shubho rātri."),
                r("We are okay now.", "এখন ঠিক আছি।", "Ēkhon ṭhik āchi."),
            ],
        )
    )
