# Section 4: Vocabulary (chapterIds 597–619). Eighteen rows each: English, Assamese, ITRANS-style transliteration.
from assamese_lesson_helpers import ch, r, block_table


def _b(cid: int, title: str, content: str, intro: str, rows: list, heading: str = "Vocabulary") -> dict:
    return ch(cid, title, content, intro, blocks=[block_table(heading, rows)])


def add_chapters_597_619(out: list) -> None:
    """Append vocabulary lessons 597–619 with full example tables (no generic expansion)."""
    out.append(
        _b(
            597,
            "List of Body parts in Assamese",
            "Common nouns for parts of the body; everyday compounds like চকুৰ পাত (eyelid) appear in speech.",
            "মূৰ, চকু, হাত — core anatomy words for describing health and appearance.",
            [
                r("head", "মূৰ", "mur"),
                r("hair", "চুল", "chul"),
                r("face", "মুখ", "mukh"),
                r("eye", "চকু", "choku"),
                r("ear", "কান", "kan"),
                r("nose", "নাক", "nak"),
                r("mouth", "মুখ", "mukh"),
                r("tooth", "দাঁত", "dãt"),
                r("tongue", "জিভা", "jibha"),
                r("neck", "ডিঙি", "dingi"),
                r("shoulder", "কাঁধ", "kãdh"),
                r("arm", "বাহু", "bahu"),
                r("hand", "হাত", "hat"),
                r("finger", "আঙুলি", "aṅuli"),
                r("chest", "বুক", "buk"),
                r("stomach / belly", "পেট", "pet"),
                r("leg", "ভৰি", "bhori"),
                r("foot", "পা", "pa"),
            ],
            heading="Body parts",
        )
    )
    out.append(
        _b(
            598,
            "Frequently used words – Miscellaneous in Assamese",
            "High-frequency nouns for daily life, places, and objects in modern Assamese.",
            "Use these in short lines: মোৰ ঘৰ, আজি কাম — possession and time.",
            [
                r("water", "পানী", "pani"),
                r("food / meal", "আহাৰ", "ahar"),
                r("house / home", "ঘৰ", "ghor"),
                r("room", "কোঠা", "kotha"),
                r("door", "দৰজা", "dorza"),
                r("window", "খিড়িকি", "khiriki"),
                r("road", "ৰাস্তা", "rasta"),
                r("city", "চহৰ", "sohor"),
                r("village", "গাঁও", "gãw"),
                r("school", "বিদ্যালয়", "bidyaloy"),
                r("book", "কিতাপ", "kitap"),
                r("paper", "কাগজ", "kagoj"),
                r("pen", "কলম", "kolom"),
                r("bag", "থলি", "tholi"),
                r("phone", "ফোন", "phon"),
                r("money", "টকা", "toka"),
                r("time", "সময়", "xomoy"),
                r("work", "কাম", "kam"),
            ],
            heading="Words",
        )
    )
    out.append(
        _b(
            599,
            "Relations in Assamese",
            "Kinship terms; some forms vary by side of the family and region.",
            "দেউতা/মা for parents; দাদা/ভাই for older brother in many homes.",
            [
                r("father", "দেউতা", "deuta"),
                r("mother", "মা", "ma"),
                r("brother", "ভাই", "bhai"),
                r("sister", "বোন", "bon"),
                r("son", "পুতেক", "puteek"),
                r("daughter", "জীয়ৰী", "jiyori"),
                r("husband", "স্বামী", "swami"),
                r("wife", "পত্নী", "patni"),
                r("uncle (father's side)", "কাকা", "kaka"),
                r("aunt (mother's sister)", "মাসি", "masi"),
                r("grandfather", "দাদু", "dadu"),
                r("grandmother", "আইটা", "aita"),
                r("father-in-law", "শ্বশুৰ", "xoxur"),
                r("mother-in-law", "শ্বাশুৰী", "xaxuri"),
                r("nephew / niece (context)", "ভাইপো / ভাইজি", "bhaipo / bhaiji"),
                r("cousin (brother)", "কাজিন ভাই", "kazin bhai"),
                r("friend", "বন্ধু", "bondhu"),
                r("neighbour", "প্ৰতিবেশী", "protibexi"),
            ],
            heading="Relations",
        )
    )
    out.append(
        _b(
            600,
            "Numbers in Assamese – Part 1",
            "Cardinals ০–১০ and key tens; practise aloud for shops and buses.",
            "এক, দুই, তিনি — counting is essential for fares and quantities.",
            [
                r("0 / zero", "শূন্য", "xunnya"),
                r("1 / one", "এক", "ek"),
                r("2 / two", "দুই", "dui"),
                r("3 / three", "তিনি", "tini"),
                r("4 / four", "চাৰি", "sari"),
                r("5 / five", "পাঁচ", "pãch"),
                r("6 / six", "ছয়", "xoy"),
                r("7 / seven", "সাত", "xat"),
                r("8 / eight", "আঠ", "aṭh"),
                r("9 / nine", "ন", "no"),
                r("10 / ten", "দহ", "doh"),
                r("11 / eleven", "একেৰা", "ekera"),
                r("12 / twelve", "বাৰ", "bar"),
                r("20 / twenty", "বিশ", "bix"),
                r("30 / thirty", "ত্ৰিশ", "tris"),
                r("40 / forty", "চল্লিশ", "sollix"),
                r("50 / fifty", "পঞ্চাশ", "ponchax"),
                r("100 / hundred", "একশ", "ekxo"),
            ],
            heading="Numbers",
        )
    )
    out.append(
        _b(
            601,
            "Numbers in Assamese – Part 2",
            "Larger amounts, ordinals, and number words used in prices and news.",
            "হাজাৰ, লাখ — common in rent, salary, and population figures.",
            [
                r("13 / thirteen", "তেৰা", "tera"),
                r("15 / fifteen", "পনোৰ", "ponor"),
                r("21 / twenty-one", "একৈশ", "ekoix"),
                r("1000 / thousand", "হাজাৰ", "hajar"),
                r("100000 / lakh", "লাখ", "lakh"),
                r("10 million / crore", "কোটি", "koṭi"),
                r("first", "প্ৰথম", "protthom"),
                r("second", "দ্বিতীয়", "dwitiyo"),
                r("third", "তৃতীয়", "tritiyo"),
                r("last", "শেষ", "xex"),
                r("next", "পৰৱৰ্তী", "pororxoti"),
                r("previous", "পূৰ্বৰ", "purbor"),
                r("half (of something)", "আধা", "adha"),
                r("double", "দুগুণ", "dugun"),
                r("pair", "জোৰা", "jora"),
                r("single", "একক", "ekok"),
                r("many / much", "বহু", "bohu"),
                r("few", "কেইটামান", "keiṭaman"),
            ],
            heading="Numbers",
        )
    )
    out.append(
        _b(
            602,
            "Fractional numbers, sequence, percentage in Assamese",
            "Fractions, order words, and how people say percent in educated speech.",
            "পঞ্চাশ শতাংশ — fifty percent in formal contexts.",
            [
                r("half", "আধা", "adha"),
                r("one quarter", "এক চতুৰ্থাংশ", "ek choturthangxo"),
                r("three quarters", "তিনি চতুৰ্থাংশ", "tini choturthangxo"),
                r("one third", "এক তৃতীয়াংশ", "ek tritiyangxo"),
                r("percent", "শতাংশ", "xotangxo"),
                r("50 percent", "পঞ্চাশ শতাংশ", "ponchax xotangxo"),
                r("first (in a series)", "প্ৰথম", "protthom"),
                r("second", "দ্বিতীয়", "dwitiyo"),
                r("third", "তৃতীয়", "tritiyo"),
                r("fourth", "চতুৰ্থ", "choturtho"),
                r("fifth", "পঞ্চম", "ponchom"),
                r("before", "আগতে", "agote"),
                r("after", "পিছত", "pisot"),
                r("between", "মাজত", "majot"),
                r("sequence", "ক্ৰম", "krom"),
                r("number (abstract)", "সংখ্যা", "xonkhya"),
                r("total", "মুঠ", "muṭh"),
                r("remainder", "অৱশিষ্ট", "ôbixishṭo"),
            ],
            heading="Fractions & order",
        )
    )
    out.append(
        _b(
            603,
            "Frequently used verbs in Assamese – Part 1",
            "Core action verbs; infinitives often use –িবলৈ / –োৱা patterns in speech.",
            "খোৱা, যোৱা — build lines with মই … কৰোঁ.",
            [
                r("to be", "হোৱা", "hua"),
                r("to do / to make", "কৰা", "kora"),
                r("to go", "যোৱা", "zua"),
                r("to come", "আহা", "aha"),
                r("to eat", "খোৱা", "khuwa"),
                r("to drink", "পান কৰা", "pan kora"),
                r("to sleep", "শোৱা", "xua"),
                r("to see / to watch", "চোৱা", "sua"),
                r("to hear / to listen", "শুনা", "xuna"),
                r("to speak / to say", "কোৱা", "kua"),
                r("to read", "পঢ়া", "poṛa"),
                r("to write", "লিখা", "likha"),
                r("to know", "জানা", "jana"),
                r("to understand", "বুজা", "buja"),
                r("to give", "দিয়া", "diya"),
                r("to take", "লোৱা", "lua"),
                r("to sit", "বহা", "boha"),
                r("to stand", "থিয় হোৱা", "thiya hua"),
            ],
            heading="Verbs",
        )
    )
    out.append(
        _b(
            604,
            "Frequently used verbs in Assamese – Part 2",
            "Verbs for wants, social actions, and daily errands.",
            "বিচাৰা, কিনা — very common in markets and polite requests.",
            [
                r("to want", "বিচাৰা", "bisara"),
                r("to need", "দৰকাৰ হোৱা", "dorkar hua"),
                r("to like", "ভাল পোৱা", "bhal pua"),
                r("to love", "ভালপোৱা", "bhalpua"),
                r("to think", "ভাবা", "bhaba"),
                r("to try / attempt", "চেষ্টা কৰা", "cesta kora"),
                r("to open", "খোলা", "khula"),
                r("to close", "বন্ধ কৰা", "bondho kora"),
                r("to buy", "কিনা", "kina"),
                r("to sell", "বেচা", "besa"),
                r("to ask", "সোধা", "xodha"),
                r("to answer", "উত্তৰ দিয়া", "uttor diya"),
                r("to help", "সহায় কৰা", "xohaẏ kora"),
                r("to wait", "অপেক্ষা কৰা", "ôpekkha kora"),
                r("to meet", "দেখা কৰা", "dekha kora"),
                r("to run", "দৌৰা", "doura"),
                r("to walk", "খোজ কঢ়া", "khôj koṛa"),
                r("to swim", "সাঁতোৰা", "sãtua"),
            ],
            heading="Verbs",
        )
    )
    out.append(
        _b(
            605,
            "Frequently used verbs in Assamese – Part 3",
            "Verbs for study, work, play, and household activities.",
            "ৰান্ধা, পৰিষ্কাৰ কৰা — daily routine around the home.",
            [
                r("to work", "কাম কৰা", "kam kora"),
                r("to play", "খেলা", "khela"),
                r("to cook", "ৰান্ধা", "randha"),
                r("to clean", "পৰিষ্কাৰ কৰা", "poriskar kora"),
                r("to wash", "ধোৱা", "dhuwa"),
                r("to drive", "গাড়ী চলোৱা", "gaṛi slua"),
                r("to fly", "উৰা", "ura"),
                r("to sing", "গাঁও", "gãw"),
                r("to dance", "নাচা", "nacha"),
                r("to study", "পঢ়াশোনা কৰা", "poṛaxona kora"),
                r("to teach", "পঢ়োৱা", "poṛua"),
                r("to learn", "শিকা", "xika"),
                r("to send", "পঠোৱা", "poṭhua"),
                r("to receive / to get", "পোৱা", "pua"),
                r("to pay", "টকা দিয়া", "toka diya"),
                r("to win", "জিকা", "jika"),
                r("to lose", "হৰা", "hora"),
                r("to forget", "পাহৰি যোৱা", "pohri zua"),
            ],
            heading="Verbs",
        )
    )
    out.append(
        _b(
            606,
            "Frequently used verbs in Assamese – Part 4",
            "Verbs for placement, change, and finishing actions.",
            "ৰখা, শেষ কৰা — instructions and short narratives.",
            [
                r("to put / to place", "ৰখা", "rakha"),
                r("to keep", "ৰখা", "rakha"),
                r("to change", "সলনি কৰা", "soloni kora"),
                r("to begin / to start", "আৰম্ভ কৰা", "arômbh kora"),
                r("to finish", "শেষ কৰা", "xex kora"),
                r("to stop", "থমোৱা", "thmua"),
                r("to return", "উভতি আহা", "ubhoti aha"),
                r("to leave (go away)", "অলাই যোৱা", "olai zua"),
                r("to arrive", "আহি পোৱা", "ahi pua"),
                r("to use", "ব্যৱহাৰ কৰা", "bẽbohar kora"),
                r("to build / to make", "বনোৱা", "bonua"),
                r("to break", "ভাঙা", "bhaṅa"),
                r("to repair / to fix", "মেৰামত কৰা", "meramot kora"),
                r("to choose", "বাছি লোৱা", "baxi lua"),
                r("to decide", "সিদ্ধান্ত লোৱা", "xidhhant lua"),
                r("to remember", "মনত ৰখা", "monot rakha"),
                r("to hope", "আশা কৰা", "axa kora"),
                r("to fear", "ভয় খোৱা", "bhoy khuwa"),
            ],
            heading="Verbs",
        )
    )
    out.append(
        _b(
            607,
            'One verb, multiple meanings – দিয়া in Assamese',
            "দিয়া often means “give”, but appears in paying, allowing, and fixed expressions.",
            "Each row: English cue → natural Assamese phrase.",
            [
                r("to give (something)", "দিয়া", "diya"),
                r("Give me water.", "মোক পানী দিয়ক।", "Mok pani diyak."),
                r("to pay money", "টকা দিয়া", "toka diya"),
                r("to give time", "সময় দিয়া", "xomoy diya"),
                r("to give permission", "অনুমতি দিয়া", "ônumoti diya"),
                r("to lend", "ধাৰ দিয়া", "dhar diya"),
                r("to donate", "দান কৰা", "dan kora"),
                r("to hand over", "তুলি দিয়া", "tuli diya"),
                r("to give a gift", "উপহাৰ দিয়া", "upohar diya"),
                r("to give advice", "উপদেশ দিয়া", "upodesh diya"),
                r("to give an answer", "উত্তৰ দিয়া", "uttor diya"),
                r("to give back / return", "ঘূৰাই দিয়া", "ghurai diya"),
                r("to give up", "এৰি দিয়া", "eri diya"),
                r("to let in / allow entry", "ভিতৰলৈ যাবলৈ দিয়া", "bhitôrlôi zabôlôi diya"),
                r("to apply (ointment)", "লগোৱা", "logua"),
                r("to let / allow (soft)", "কৰিবলৈ দিয়া", "koribôlôi diya"),
                r("to fine (penalty)", "জৰিমানা কৰা", "jorimana kora"),
                r("to assign (work)", "দায়িত্ব দিয়া", "dayitto diya"),
            ],
            heading="দিয়া",
        )
    )
    out.append(
        _b(
            608,
            'One verb, multiple meanings – লাগা in Assamese',
            "লাগা covers “stick”, “feel”, “cost”, “need”, and more in compounds.",
            "ঠাণ্ডা লাগিছে = I feel cold; দাম লাগে = it costs.",
            [
                r("to feel cold / hot", "ঠাণ্ডা/গৰম লাগা", "thaṇḍa/gorom laga"),
                r("to need (I need …)", "… লাগে", "… lage"),
                r("to cost", "দাম লাগা", "dam laga"),
                r("to stick / to attach", "লাগি থাকা", "lagi thaka"),
                r("to suit / to look good", "ভাল লাগা", "bhal laga"),
                r("to feel like (desire)", "ইচ্ছা হোৱা", "iccha hua"),
                r("to get angry", "ৰাগ হোৱা", "rag hua"),
                r("to begin (it starts)", "আৰম্ভ হোৱা", "arômbh hua"),
                r("to touch lightly", "স্পৰ্শ কৰা", "sporxo kora"),
                r("to nail / to hammer in", "ঠোকা", "thuka"),
                r("to feel hungry", "ভোক লাগা", "bhook laga"),
                r("to feel sleepy", "নিদ লাগা", "nid laga"),
                r("to be enough", "যথেষ্ট হোৱা", "jotheshṭo hua"),
                r("to match (colour)", "মিলি যোৱা", "mili zua"),
                r("to feel ashamed", "লাজ লাগা", "laj laga"),
                r("to apply cream", "মলম লগোৱা", "molom logua"),
                r("to plant (a tree)", "লগোৱা", "logua"),
                r("to feel bored", "বিৰক্ত লাগা", "birkoto laga"),
            ],
            heading="লাগা",
        )
    )
    out.append(
        _b(
            609,
            "List of Assamese Adjectives – Part 1",
            "Common adjectives for size, quality, temperature, and feeling.",
            "ডাঙৰ/সৰু, ভাল/বেয়া — often placed before the noun.",
            [
                r("big", "ডাঙৰ", "daṅor"),
                r("small", "সৰু", "soru"),
                r("good", "ভাল", "bhal"),
                r("bad", "বেয়া", "beẏa"),
                r("new", "নতুন", "nôtun"),
                r("old (thing)", "পুৰণি", "puroni"),
                r("hot", "গৰম", "gorom"),
                r("cold", "ঠাণ্ডা", "thaṇḍa"),
                r("beautiful", "ধুনীয়া", "dhuniya"),
                r("ugly", "কুৎসিত", "kutsit"),
                r("easy", "সহজ", "xohoz"),
                r("difficult", "কঠিন", "koṭhin"),
                r("happy", "আনন্দিত", "anondito"),
                r("sad", "দুখী", "dukhi"),
                r("fast", "দ্ৰুত", "drut"),
                r("slow", "ধীৰ", "dhir"),
                r("clean", "পৰিষ্কাৰ", "poriskar"),
                r("dirty", "নোংৰা", "noṅra"),
            ],
            heading="Adjectives",
        )
    )
    out.append(
        _b(
            610,
            "Adverbs in Assamese – Part 1",
            "Time and place adverbs; many double as question words.",
            "এতিয়া, আজি, ইয়াত — anchor speech in time and space.",
            [
                r("here", "ইয়াত", "iyat"),
                r("there", "তাত", "tat"),
                r("where", "ক’ত", "kot"),
                r("now", "এতিয়া", "etiya"),
                r("today", "আজি", "aji"),
                r("tomorrow", "কাইলৈ", "kailoi"),
                r("yesterday", "কালি", "kali"),
                r("always", "সদায়", "xoday"),
                r("never", "কেতিয়াও নহয়", "ketiyao nohoẏ"),
                r("often", "প্ৰায়ে", "praẏe"),
                r("sometimes", "কেতিয়াবা", "ketiyaba"),
                r("soon", "সোনকালে", "xonkale"),
                r("late", "পলমকৈ", "polomkoi"),
                r("early", "পোহৰতে", "pohorte"),
                r("together", "একেলগে", "keloge"),
                r("alone", "একলা", "ekla"),
                r("near", "কাষত", "kaxhot"),
                r("far", "দূৰত", "durôt"),
            ],
            heading="Adverbs",
        )
    )
    out.append(
        _b(
            611,
            "List of adverbs in Assamese",
            "Manner, probability, and focus adverbs for richer sentences.",
            "দ্ৰুত, ধীৰে — describe how something happens.",
            [
                r("inside", "ভিতৰত", "bhitôrot"),
                r("outside", "বাহিৰত", "bahirôt"),
                r("upstairs", "ওপৰত", "ôporot"),
                r("downstairs", "তলত", "tolot"),
                r("quickly", "দ্ৰুতে", "drute"),
                r("slowly", "ধীৰে", "dhire"),
                r("well", "ভালকৈ", "bhal koi"),
                r("badly", "বেয়াকৈ", "beẏakoi"),
                r("perhaps", "সম্ভৱতে", "xombhôvote"),
                r("certainly", "নিশ্চয়", "nixoy"),
                r("again", "আকৌ", "akou"),
                r("back", "উভতি", "ubhoti"),
                r("only", "মাত্ৰ", "matro"),
                r("also", "ও", "o"),
                r("even", "এনেকেই", "enekoi"),
                r("exactly", "ঠিক", "ṭhik"),
                r("very", "বৰ", "bor"),
                r("too (excess)", "বৰ বেছি", "bor bexi"),
            ],
            heading="Adverbs",
        )
    )
    out.append(
        _b(
            612,
            "List of vegetable names in Assamese",
            "Everyday vegetables in haat-bazar and home kitchens.",
            "আলু, পিঁয়াজ — staples for jolpan and main meals.",
            [
                r("potato", "আলু", "alu"),
                r("onion", "পিঁয়াজ", "piẽz"),
                r("tomato", "টমেটো", "ṭomeṭo"),
                r("brinjal / eggplant", "বেঙেন", "bengen"),
                r("cauliflower", "ফুলকবি", "phulkobi"),
                r("cabbage", "বাঁধাকবি", "bãdhakobi"),
                r("spinach (palak)", "পালং", "paloṅ"),
                r("carrot", "গাজৰ", "gajor"),
                r("cucumber", "তেঙা", "tenga"),
                r("pumpkin", "ৰাঙালাউ", "rangalau"),
                r("green chilli", "কেঁচা জলকীয়া", "kẽça jolkiya"),
                r("ginger", "আদা", "ada"),
                r("garlic", "নহোৰু", "nohôru"),
                r("coriander leaves", "ধনিয়া পাত", "dhoniya pat"),
                r("beans", "শিম", "xim"),
                r("radish", "মুলা", "mula"),
                r("okra / ladies' finger", "ভেন্দি", "bhendi"),
                r("peas", "মটৰ শুটি", "motôr xuṭi"),
            ],
            heading="Vegetables",
        )
    )
    out.append(
        _b(
            613,
            "List of names of fruits in Assamese",
            "Common fruits; some names echo colour words (কমলা).",
            "আম, কল — widely enjoyed across Assam.",
            [
                r("mango", "আম", "am"),
                r("banana", "কল", "kol"),
                r("apple", "এপল", "epol"),
                r("orange (fruit)", "কমলা", "komola"),
                r("grapes", "আঙুৰ", "aṅur"),
                r("guava", "মদুৰ", "modur"),
                r("papaya", "অমিতা", "omita"),
                r("coconut", "নাৰিকল", "narikol"),
                r("lemon", "নিমোক", "nimok"),
                r("jackfruit", "কঠাল", "koṭhal"),
                r("pineapple", "আনাৰস", "anarôs"),
                r("watermelon", "তৰমুজ", "tôrmuj"),
                r("pomegranate", "ডালিম", "ḍalim"),
                r("lychee", "লিচু", "lichu"),
                r("date (fruit)", "খেজুৰ", "khejur"),
                r("custard apple", "আটা", "ata"),
                r("black plum / jamun", "জামুৰ", "jamur"),
                r("wood apple", "ওলটেঙা", "olṭenga"),
            ],
            heading="Fruits",
        )
    )
    out.append(
        _b(
            614,
            "List of names of birds in Assamese",
            "Common birds in towns, fields, and riverbanks.",
            "কাঁৱৰ, কুলি — familiar calls across neighbourhoods.",
            [
                r("crow", "কাক", "kak"),
                r("sparrow", "চৰাই", "sorai"),
                r("parrot", "চিয়া", "siya"),
                r("pigeon", "কবুতৰ", "kobutor"),
                r("duck", "হাঁহ", "hãh"),
                r("hen / chicken", "কুকুৰা", "kukura"),
                r("eagle", "বাজপাখি", "bajpakhi"),
                r("owl", "পেঁচা", "pẽsa"),
                r("peacock", "ময়ূৰ", "moẏur"),
                r("koel (cuckoo)", "কুলি", "kuli"),
                r("myna", "চালিক", "salik"),
                r("swan", "ৰাজহাঁহ", "rajhãh"),
                r("crane (bird)", "বগ", "bog"),
                r("woodpecker", "কাঠঠোকৰা", "kaṭhthokora"),
                r("kingfisher", "মাছৰাঙা", "masraṅa"),
                r("kite (bird)", "চিল", "sil"),
                r("seagull", "গাংচিল", "gaṅsil"),
                r("bat", "বাদুলি", "baduli"),
            ],
            heading="Birds",
        )
    )
    out.append(
        _b(
            615,
            "List of names of insects in Assamese",
            "Common insects; several turn up in household talk and idioms.",
            "মাখি, পিপৰা — everyday vocabulary.",
            [
                r("ant", "পিপৰা", "pipora"),
                r("bee", "মৌমাছি", "maumaxi"),
                r("mosquito", "মকু", "moku"),
                r("housefly", "মাখি", "makhi"),
                r("spider", "মাকৰ", "makor"),
                r("butterfly", "প্ৰজাপতি", "projapoti"),
                r("worm", "কীড়া", "kiṛa"),
                r("cockroach", "বিছাপোকা", "bichapoka"),
                r("beetle / bug", "পোকা", "poka"),
                r("louse", "উকুন", "ukun"),
                r("firefly", "জোনাকী", "jonaki"),
                r("scorpion", "বিছুটি", "bichuṭi"),
                r("centipede", "কেন্নো", "kenno"),
                r("termite", "উইপোকা", "uipoka"),
                r("dragonfly", "ফৰিং", "phoriṅ"),
                r("grasshopper", "ঘাসফৰিং", "ghasphoriṅ"),
                r("moth", "পতংগা", "potôṅga"),
                r("bedbug", "গুম", "gum"),
            ],
            heading="Insects",
        )
    )
    out.append(
        _b(
            616,
            "List of colours in Assamese",
            "Basic colour words; often used as adjectives before nouns.",
            "লাল গামোছা, নীল আকাশ.",
            [
                r("red", "লাল", "lal"),
                r("blue", "নীল", "nil"),
                r("green", "সেউজ", "xeuj"),
                r("yellow", "হালধীয়া", "haldhiya"),
                r("white", "বগা", "boga"),
                r("black", "ক’লা", "kola"),
                r("orange (colour)", "কমলা", "komola"),
                r("purple", "বেঙুনীয়া", "benguniya"),
                r("pink", "গোলাপী", "golapi"),
                r("brown", "মটিয়া", "moṭiya"),
                r("grey", "ধূসৰ", "dhuxor"),
                r("golden", "সোণালী", "xoṇali"),
                r("silver", "ৰূপালী", "rupali"),
                r("dark (shade)", "গাঢ়", "gaṛh"),
                r("light (shade)", "পাতল", "patol"),
                r("colour", "ৰং", "roṅ"),
                r("multicoloured", "ৰঙীন", "roṅin"),
                r("pale", "ফিকা", "phika"),
            ],
            heading="Colours",
        )
    )
    out.append(
        _b(
            617,
            "List of names of flowers in Assamese",
            "Common flowers in gardens, naamghar, and markets.",
            "গোলাপ, টগৰ — culturally rich plant names.",
            [
                r("rose", "গোলাপ", "golap"),
                r("lotus", "পদুম", "padum"),
                r("jasmine", "জুঁই", "jũi"),
                r("marigold", "গাঁধুলি", "gãdhuli"),
                r("sunflower", "সূৰ্যমুখী", "xurjomukhi"),
                r("hibiscus (joba)", "জবা", "joba"),
                r("lily", "লিলি", "lili"),
                r("chrysanthemum", "চন্দ্ৰমল্লিকা", "chondromollika"),
                r("tulip", "টিউলিপ", "ṭiulip"),
                r("daisy", "ডেইজি", "ḍeiji"),
                r("flower (general)", "ফুল", "phul"),
                r("bud", "কুঁৰি", "kũri"),
                r("fragrance", "সুগন্ধ", "xugondh"),
                r("garland", "মালা", "mala"),
                r("leaf", "পাত", "pat"),
                r("thorn", "কাঁটা", "kãṭa"),
                r("petal", "পাপৰি", "papori"),
                r("nectar", "মধু", "modhu"),
            ],
            heading="Flowers",
        )
    )
    out.append(
        _b(
            618,
            "List of names of animals in Assamese",
            "Common mammals, reptiles, and small animals in speech and stories.",
            "কুকুৰ, মেকুৰী — pets and village life.",
            [
                r("dog", "কুকুৰ", "kukur"),
                r("cat", "মেকুৰী", "mekuri"),
                r("cow", "গৰু", "goru"),
                r("goat", "ছাগল", "xagol"),
                r("horse", "ঘোঁৰা", "ghoṛa"),
                r("elephant", "হাতী", "hati"),
                r("tiger", "বাঘ", "bagh"),
                r("lion", "সিংহ", "xingho"),
                r("monkey", "বানৰ", "banor"),
                r("snake", "সাপ", "xap"),
                r("fish", "মাছ", "max"),
                r("bird", "পাখি", "pakhi"),
                r("rabbit", "খৰগোস", "khorgos"),
                r("camel", "উট", "uṭ"),
                r("fox", "শিয়াল", "xiyal"),
                r("deer", "হৰিণ", "horin"),
                r("bear", "ভালুক", "bhaluk"),
                r("crocodile", "কুমিৰ", "kumir"),
            ],
            heading="Animals",
        )
    )
    out.append(
        _b(
            619,
            "Frequently used or common words in Assamese – Miscellaneous",
            "Polite words, greetings, and question words for basic communication.",
            "কি, কিয়, ক’ত — natural question starters.",
            [
                r("yes", "হয়", "hoẏ"),
                r("no", "নাই", "nai"),
                r("please", "অনুগ্ৰহ কৰি", "ônugrah kori"),
                r("thank you", "ধন্যবাদ", "dhonnobad"),
                r("sorry", "ক্ষমা কৰিব", "khoma korib"),
                r("excuse me", "মাফ কৰিব", "maf korib"),
                r("hello", "নমস্কাৰ", "nomoskar"),
                r("goodbye", "বিদায়", "bidaẏ"),
                r("good morning", "সুপ্ৰভাত", "suprobhat"),
                r("good night", "শুভ ৰাতি", "xubh rati"),
                r("welcome", "স্বাগতম", "swagotom"),
                r("what", "কি", "ki"),
                r("who", "কোন", "kon"),
                r("where", "ক’ত", "kot"),
                r("when", "কেতিয়া", "ketiya"),
                r("why", "কিয়", "kio"),
                r("how", "কেনেকৈ", "kenekoi"),
                r("which", "কোনটো", "konṭo"),
            ],
            heading="Common words",
        )
    )
