# Section 4: Vocabulary (chapterIds 597–619). Eighteen rows each: English, Bengali, ITRANS-style transliteration.
from bengali_lesson_helpers import ch, r, block_table


def _b(cid: int, title: str, content: str, intro: str, rows: list, heading: str = "Vocabulary") -> dict:
    return ch(cid, title, content, intro, blocks=[block_table(heading, rows)])


def add_chapters_597_619(out: list) -> None:
    """Append vocabulary lessons 597–619 with full example tables (no generic expansion)."""
    out.append(
        _b(
            597,
            "List of Body parts in Bengali",
            "Common nouns for parts of the body; some have everyday compounds (e.g. চোখের পাতা).",
            "মাথা, চোখ, হাত — basic anatomy words.",
            [
                r("head", "মাথা", "māthā"),
                r("hair", "চুল", "chul"),
                r("face", "মুখ", "mukh"),
                r("eye", "চোখ", "chōkh"),
                r("ear", "কান", "kān"),
                r("nose", "নাক", "nāk"),
                r("mouth", "মুখ", "mukh"),
                r("tooth", "দাঁত", "dãt"),
                r("tongue", "জিহ্বা", "jihbā"),
                r("neck", "গলা", "galā"),
                r("shoulder", "কাঁধ", "kãdh"),
                r("arm", "বাহু", "bāhu"),
                r("hand", "হাত", "hāt"),
                r("finger", "আঙুল", "āṅul"),
                r("chest", "বুক", "buk"),
                r("stomach / belly", "পেট", "pēṭ"),
                r("leg", "পা", "pā"),
                r("foot", "পা", "pā"),
            ],
            heading="Body parts",
        )
    )
    out.append(
        _b(
            598,
            "Frequently used words – Miscellaneous in Bengali",
            "High-frequency nouns for daily life, places, and objects.",
            "Use these in short sentences: আমার বাড়ি, আজ কাজ.",
            [
                r("water", "জল", "jol"),
                r("food", "খাবার", "khābār"),
                r("house / home", "বাড়ি", "bāṛi"),
                r("room", "ঘর", "ghor"),
                r("door", "দরজা", "dôrjā"),
                r("window", "জানলা", "jānlā"),
                r("road", "রাস্তা", "rāstā"),
                r("city", "শহর", "shôhor"),
                r("village", "গ্রাম", "grām"),
                r("school", "স্কুল", "skul"),
                r("book", "বই", "bôi"),
                r("paper", "কাগজ", "kāgôj"),
                r("pen", "কলম", "kolom"),
                r("bag", "ব্যাগ", "bẽg"),
                r("phone", "ফোন", "phōn"),
                r("money", "টাকা", "ṭākā"),
                r("time", "সময়", "somoy"),
                r("work", "কাজ", "kāj"),
            ],
            heading="Words",
        )
    )
    out.append(
        _b(
            599,
            "Relations in Bengali",
            "Kinship terms; some vary by side (মামা vs কাকা).",
            "বাবা/মা for parents; দাদা/দিদি often for older siblings in the family.",
            [
                r("father", "বাবা", "bābā"),
                r("mother", "মা", "mā"),
                r("brother", "ভাই", "bhāi"),
                r("sister", "বোন", "bōn"),
                r("son", "ছেলে", "chēlē"),
                r("daughter", "মেয়ে", "mēẏē"),
                r("husband", "স্বামী", "swāmī"),
                r("wife", "স্ত্রী", "strī"),
                r("uncle (father's side)", "কাকা", "kākā"),
                r("aunt (mother's sister)", "মাসি", "māsi"),
                r("grandfather", "দাদু / ঠাকুরদাদু", "dādu / ṭhākurdādu"),
                r("grandmother", "ঠাকুমা / দিদিমা", "ṭhākumā / didimā"),
                r("father-in-law", "শ্বশুর", "shôshur"),
                r("mother-in-law", "শাশুড়ি", "shāshuṛi"),
                r("nephew / niece (context)", "ভাইপো / ভাইঝি", "bhāipo / bhāijhi"),
                r("cousin (brother)", "কাজিন ভাই", "kājin bhāi"),
                r("friend", "বন্ধু", "bondhu"),
                r("neighbour", "প্রতিবেশী", "prôtibēshī"),
            ],
            heading="Relations",
        )
    )
    out.append(
        _b(
            600,
            "Numbers in Bengali – Part 1",
            "Cardinals ০–১০ and key tens; digits match Bangla numerals in writing.",
            "এক দুই তিন — practice counting aloud.",
            [
                r("0 / zero", "শূন্য", "shūnyo"),
                r("1 / one", "এক", "ek"),
                r("2 / two", "দুই", "dui"),
                r("3 / three", "তিন", "tin"),
                r("4 / four", "চার", "chār"),
                r("5 / five", "পাঁচ", "pā̃ch"),
                r("6 / six", "ছয়", "chhôy"),
                r("7 / seven", "সাত", "sāt"),
                r("8 / eight", "আট", "āṭ"),
                r("9 / nine", "নয়", "nôy"),
                r("10 / ten", "দশ", "dôsh"),
                r("11 / eleven", "এগারো", "egārō"),
                r("12 / twelve", "বারো", "bārō"),
                r("20 / twenty", "বিশ", "bish"),
                r("30 / thirty", "তিরিশ", "tirish"),
                r("40 / forty", "চল্লিশ", "chollish"),
                r("50 / fifty", "পঞ্চাশ", "pônchāsh"),
                r("100 / hundred", "একশ", "ekshô"),
            ],
            heading="Numbers",
        )
    )
    out.append(
        _b(
            601,
            "Numbers in Bengali – Part 2",
            "Larger amounts, ordinals, and common number words in speech.",
            "হাজার, লাখ — used in prices and populations.",
            [
                r("13 / thirteen", "তেরো", "tērō"),
                r("15 / fifteen", "পনেরো", "pōnērō"),
                r("21 / twenty-one", "একুশ", "ekush"),
                r("1000 / thousand", "হাজার", "hājār"),
                r("100000 / lakh", "লাখ", "lākh"),
                r("10 million / crore", "কোটি", "kōṭi"),
                r("first", "প্রথম", "prôthom"),
                r("second", "দ্বিতীয়", "dbitīẏo"),
                r("third", "তৃতীয়", "tritīẏo"),
                r("last", "শেষ", "shēsh"),
                r("next", "পরের", "pōrēr"),
                r("previous", "আগের", "āgēr"),
                r("half (of something)", "অর্ধেক", "ôrdhek"),
                r("double", "দ্বিগুণ", "dbiguṇ"),
                r("pair", "জোড়া", "jōṛā"),
                r("single", "একক", "ekkô"),
                r("many / much", "অনেক", "ônek"),
                r("few", "কয়েক", "kôyek"),
            ],
            heading="Numbers",
        )
    )
    out.append(
        _b(
            602,
            "Fractional numbers, sequence, percentage in Bengali",
            "Fractions, order words, and how people say percent in Bangla.",
            "৫০ শতাংশ — fifty percent.",
            [
                r("half", "অর্ধেক", "ôrdhek"),
                r("one quarter", "এক চতুর্থ", "ek chôturtho"),
                r("three quarters", "তিন চতুর্থাংশ", "tin chôturthāṅsho"),
                r("one third", "এক তৃতীয়াংশ", "ek tritīẏāṅsho"),
                r("percent", "শতাংশ", "shôtāṅsho"),
                r("50 percent", "পঞ্চাশ শতাংশ", "pônchāsh shôtāṅsho"),
                r("first (in a series)", "প্রথম", "prôthom"),
                r("second", "দ্বিতীয়", "dbitīẏo"),
                r("third", "তৃতীয়", "tritīẏo"),
                r("fourth", "চতুর্থ", "chôturtho"),
                r("fifth", "পঞ্চম", "pônchom"),
                r("before", "আগে", "āgē"),
                r("after", "পরে", "pōrē"),
                r("between", "মাঝে", "mājhe"),
                r("sequence", "ক্রম", "krom"),
                r("number (abstract)", "সংখ্যা", "shôngkhyā"),
                r("total", "মোট", "mōṭ"),
                r("remainder", "অবশিষ্ট", "ôbishishṭo"),
            ],
            heading="Fractions & order",
        )
    )
    out.append(
        _b(
            603,
            "Frequently used verbs in Bengali – Part 1",
            "Core action verbs; infinitives often end in –া / –তে.",
            "খাওয়া, যাওয়া — build sentences with আমি … করি.",
            [
                r("to be", "হওয়া", "hōōyā"),
                r("to do / to make", "করা", "korā"),
                r("to go", "যাওয়া", "jāōyā"),
                r("to come", "আসা", "āsā"),
                r("to eat", "খাওয়া", "khāōyā"),
                r("to drink", "পান করা", "pān korā"),
                r("to sleep", "ঘুমানো", "ghumānō"),
                r("to see / to watch", "দেখা", "dēkhā"),
                r("to hear / to listen", "শোনা", "shonā"),
                r("to speak / to say", "বলা", "bolā"),
                r("to read", "পড়া", "pōṛā"),
                r("to write", "লেখা", "lēkhā"),
                r("to know", "জানা", "jānā"),
                r("to understand", "বোঝা", "bōjhā"),
                r("to give", "দেওয়া", "dēōyā"),
                r("to take", "নেওয়া", "nēōyā"),
                r("to sit", "বসা", "bôsā"),
                r("to stand", "দাঁড়ানো", "dãṛānō"),
            ],
            heading="Verbs",
        )
    )
    out.append(
        _b(
            604,
            "Frequently used verbs in Bengali – Part 2",
            "Verbs for wants, social actions, and daily errands.",
            "চাওয়া, কেনা — very common in shops and requests.",
            [
                r("to want", "চাওয়া", "chāōyā"),
                r("to need", "দরকার হওয়া", "dôrkār hōōyā"),
                r("to like", "পছন্দ করা", "pôchondo korā"),
                r("to love", "ভালোবাসা", "bhālōbāsā"),
                r("to think", "ভাবা", "bhābā"),
                r("to try / attempt", "চেষ্টা করা", "chēṣṭā korā"),
                r("to open", "খোলা", "khōlā"),
                r("to close", "বন্ধ করা", "bondho korā"),
                r("to buy", "কেনা", "kēnā"),
                r("to sell", "বেচা", "bēchā"),
                r("to ask", "জিজ্ঞাসা করা", "jijñāsā korā"),
                r("to answer", "উত্তর দেওয়া", "uttor dēōyā"),
                r("to help", "সাহায্য করা", "sāhājjo korā"),
                r("to wait", "অপেক্ষা করা", "ôpekhshā korā"),
                r("to meet", "দেখা করা", "dēkhā korā"),
                r("to run", "দৌড়ানো", "douṛānō"),
                r("to walk", "হাঁটা", "hãṭā"),
                r("to swim", "সাঁতার কাটা", "sãtār kāṭā"),
            ],
            heading="Verbs",
        )
    )
    out.append(
        _b(
            605,
            "Frequently used verbs in Bengali – Part 3",
            "Verbs for study, work, play, and household activities.",
            "রান্না করা, পরিষ্কার করা — daily routine.",
            [
                r("to work", "কাজ করা", "kāj korā"),
                r("to play", "খেলা", "khelā"),
                r("to cook", "রান্না করা", "rānnā korā"),
                r("to clean", "পরিষ্কার করা", "porishkār korā"),
                r("to wash", "ধোয়া", "dhōoẏā"),
                r("to drive", "গাড়ি চালানো", "gāṛi chālānō"),
                r("to fly", "উড়া", "uṛā"),
                r("to sing", "গাওয়া", "gāōyā"),
                r("to dance", "নাচা", "nāchā"),
                r("to study", "পড়াশোনা করা", "pōṛāshonā korā"),
                r("to teach", "পড়ানো", "pōṛānō"),
                r("to learn", "শেখা", "shēkhā"),
                r("to send", "পাঠানো", "pāṭhānō"),
                r("to receive / to get", "পাওয়া", "pāōyā"),
                r("to pay", "টাকা দেওয়া", "ṭākā dēōyā"),
                r("to win", "জেতা", "jētā"),
                r("to lose", "হারানো", "hārānō"),
                r("to forget", "ভুলে যাওয়া", "bhule jāōyā"),
            ],
            heading="Verbs",
        )
    )
    out.append(
        _b(
            606,
            "Frequently used verbs in Bengali – Part 4",
            "Verbs for placement, change, and finishing actions.",
            "রাখা, শেষ করা — narrative and instructions.",
            [
                r("to put / to place", "রাখা", "rākhā"),
                r("to keep", "রাখা", "rākhā"),
                r("to change", "বদলানো", "bôdlānō"),
                r("to begin / to start", "শুরু করা", "shuru korā"),
                r("to finish", "শেষ করা", "shēsh korā"),
                r("to stop", "থামা", "thāmā"),
                r("to return", "ফিরে আসা", "phire āsā"),
                r("to leave (go away)", "চলে যাওয়া", "chōlē jāōyā"),
                r("to arrive", "পৌঁছানো", "poũchhānō"),
                r("to use", "ব্যবহার করা", "bẽbohār korā"),
                r("to build / to make", "বানানো", "bānānō"),
                r("to break", "ভাঙা", "bhāṅā"),
                r("to repair / to fix", "ঠিক করা", "ṭhik korā"),
                r("to choose", "বেছে নেওয়া", "bēchē nēōyā"),
                r("to decide", "সিদ্ধান্ত নেওয়া", "siddhānto nēōyā"),
                r("to remember", "মনে রাখা", "mōne rākhā"),
                r("to hope", "আশা করা", "āshā korā"),
                r("to fear", "ভয় পাওয়া", "bhôy pāōyā"),
            ],
            heading="Verbs",
        )
    )
    out.append(
        _b(
            607,
            'One verb, multiple meanings – দেওয়া / দেয়া in Bengali',
            "দেওয়া often means “give”, but appears in many fixed expressions (দাম দেওয়া, ছেড়ে দেওয়া).",
            "Each row: English cue → natural Bangla phrase.",
            [
                r("to give (something)", "দেওয়া", "dēōyā"),
                r("Give me water.", "আমাকে জল দিন।", "Āmākē jol din."),
                r("to pay money", "টাকা দেওয়া", "ṭākā dēōyā"),
                r("to give time", "সময় দেওয়া", "somoy dēōyā"),
                r("to give permission", "অনুমতি দেওয়া", "ônumoti dēōyā"),
                r("to lend", "ধার দেওয়া", "dhār dēōyā"),
                r("to donate", "দান করা", "dān korā"),
                r("to hand over", "তুলে দেওয়া", "tulē dēōyā"),
                r("to give a gift", "উপহার দেওয়া", "upohār dēōyā"),
                r("to give advice", "উপদেশ দেওয়া", "upodēsh dēōyā"),
                r("to give an answer", "উত্তর দেওয়া", "uttor dēōyā"),
                r("to give back / return", "ফেরত দেওয়া", "phērôt dēōyā"),
                r("to give up", "ছেড়ে দেওয়া", "chēṛē dēōyā"),
                r("to let in / allow entry", "ঢুকতে দেওয়া", "dhukte dēōyā"),
                r("to apply (ointment)", "লাগানো", "lāgānō"),
                r("to let / allow (soft)", "দিতে দেওয়া", "dite dēōyā"),
                r("to fine (penalty)", "জরিমানা করা", "jorimānā korā"),
                r("to assign (work)", "দায়িত্ব দেওয়া", "dāyitwo dēōyā"),
            ],
            heading="দেওয়া",
        )
    )
    out.append(
        _b(
            608,
            'One verb, multiple meanings – লাগা in Bengali',
            "লাগা covers “stick”, “feel”, “cost”, “need”, and more in compound verbs.",
            "ঠান্ডা লাগছে = I feel cold; দাম লাগে = it costs.",
            [
                r("to feel cold / hot", "ঠান্ডা/গরম লাগা", "ṭhāṇḍā/gorom lāgā"),
                r("to need (I need …)", "… লাগে", "… lāgē"),
                r("to cost", "দাম লাগা", "dām lāgā"),
                r("to stick / to attach", "লেগে থাকা", "lēge thākā"),
                r("to suit / to look good", "মানানসই লাগা", "mānānsôi lāgā"),
                r("to feel like (desire)", "ইচ্ছে হওয়া", "icchē hōōyā"),
                r("to get angry", "রাগ হওয়া", "rāg hōōyā"),
                r("to begin (it starts)", "শুরু হওয়া", "shuru hōōyā"),
                r("to touch lightly", "স্পর্শ করা", "spôrsho korā"),
                r("to nail / to hammer in", "ঠোকা", "ṭhōkā"),
                r("to feel hungry", "খিদে পাওয়া", "khidē pāōyā"),
                r("to feel sleepy", "ঘুম পাওয়া", "ghum pāōyā"),
                r("to be enough", "যথেষ্ট হওয়া", "jôthēshṭo hōōyā"),
                r("to match (colour)", "মিলে যাওয়া", "mile jāōyā"),
                r("to feel ashamed", "লজ্জা লাগা", "lôjja lāgā"),
                r("to apply cream", "মলম লাগানো", "molom lāgānō"),
                r("to plant (a tree)", "লাগানো", "lāgānō"),
                r("to feel bored", "বিরক্ত লাগা", "birkto lāgā"),
            ],
            heading="লাগা",
        )
    )
    out.append(
        _b(
            609,
            "List of Bengali Adjectives – Part 1",
            "Common adjectives for size, quality, temperature, and feeling.",
            "বড়/ছোট, ভালো/খারাপ — place before or after noun depending on phrase.",
            [
                r("big", "বড়", "boṛ"),
                r("small", "ছোট", "choṭ"),
                r("good", "ভালো", "bhālō"),
                r("bad", "খারাপ", "khārāp"),
                r("new", "নতুন", "nôtun"),
                r("old (thing)", "পুরনো", "purnō"),
                r("hot", "গরম", "gorom"),
                r("cold", "ঠান্ডা", "ṭhāṇḍā"),
                r("beautiful", "সুন্দর", "sundor"),
                r("ugly", "কুৎসিত", "kutsit"),
                r("easy", "সহজ", "sôhoj"),
                r("difficult", "কঠিন", "kôṭhin"),
                r("happy", "খুশি", "khushi"),
                r("sad", "দুঃখিত", "duhkhito"),
                r("fast", "দ্রুত", "drut"),
                r("slow", "ধীর", "dhīr"),
                r("clean", "পরিষ্কার", "porishkār"),
                r("dirty", "নোংরা", "noṅrā"),
            ],
            heading="Adjectives",
        )
    )
    out.append(
        _b(
            610,
            "Adverbs in Bengali – Part 1",
            "Time and place adverbs; many double as question words.",
            "এখন, আজ, এখানে — anchor your sentences in time and space.",
            [
                r("here", "এখানে", "ēkhāne"),
                r("there", "ওখানে", "ōkhāne"),
                r("where", "কোথায়", "kōthāy"),
                r("now", "এখন", "ēkhon"),
                r("today", "আজ", "āj"),
                r("tomorrow", "কাল", "kāl"),
                r("yesterday", "গতকাল", "gôtokāl"),
                r("always", "সবসময়", "sôbsomoy"),
                r("never", "কখনও না", "kôkhonō nā"),
                r("often", "প্রায়ই", "prāẏi"),
                r("sometimes", "কখনো কখনো", "kôkhonō kôkhonō"),
                r("soon", "শীঘ্রই", "shīghroi"),
                r("late", "দেরিতে", "dērite"),
                r("early", "তাড়াতাড়ি", "ṭāṛāṭāṛi"),
                r("together", "একসাথে", "ēksāthe"),
                r("alone", "একা", "ekā"),
                r("near", "কাছে", "kāchhe"),
                r("far", "দূরে", "dūrē"),
            ],
            heading="Adverbs",
        )
    )
    out.append(
        _b(
            611,
            "List of adverbs in Bengali",
            "Manner, probability, and focus adverbs for richer sentences.",
            "দ্রুত, ধীরে — describe how something happens.",
            [
                r("inside", "ভিতরে", "bhitore"),
                r("outside", "বাইরে", "bāire"),
                r("upstairs", "উপরে", "upore"),
                r("downstairs", "নিচে", "nīche"),
                r("quickly", "দ্রুত", "drut"),
                r("slowly", "ধীরে", "dhīre"),
                r("well", "ভালোভাবে", "bhālōbhābē"),
                r("badly", "খারাপভাবে", "khārāpbhābē"),
                r("perhaps", "সম্ভবত", "shombhobôt"),
                r("certainly", "নিশ্চয়", "nishchôy"),
                r("again", "আবার", "ābār"),
                r("back", "ফিরে", "phire"),
                r("only", "শুধু", "shudhu"),
                r("also", "ও", "o"),
                r("even", "এমনকি", "ēmônki"),
                r("exactly", "ঠিক", "ṭhik"),
                r("very", "খুব", "khub"),
                r("too (excess)", "খুব বেশি", "khub bēshi"),
            ],
            heading="Adverbs",
        )
    )
    out.append(
        _b(
            612,
            "List of vegetable names in Bengali",
            "Everyday vegetables in markets and kitchens.",
            "আলু, পেঁয়াজ — core cooking ingredients.",
            [
                r("potato", "আলু", "ālū"),
                r("onion", "পেঁয়াজ", "pẽyāj"),
                r("tomato", "টমেটো", "ṭomeṭō"),
                r("brinjal / eggplant", "বেগুন", "bēgun"),
                r("cauliflower", "ফুলকপি", "phulkopi"),
                r("cabbage", "বাঁধাকপি", "bãdhākopi"),
                r("spinach (palak)", "পালং শাক", "pāloṅ shāk"),
                r("carrot", "গাজর", "gājor"),
                r("cucumber", "শসা", "shôsā"),
                r("pumpkin", "কুমড়ো", "kumṛō"),
                r("green chilli", "কাঁচা মরিচ", "kãchā morich"),
                r("ginger", "আদা", "ādā"),
                r("garlic", "রসুন", "rôsun"),
                r("coriander leaves", "ধনেপাতা", "dhonēpātā"),
                r("beans", "শিম", "shim"),
                r("radish", "মূলা", "mūlā"),
                r("okra / ladies' finger", "ঢেঁড়স", "dhẽṛôs"),
                r("peas", "মটরশুটি", "moṭôrshuṭi"),
            ],
            heading="Vegetables",
        )
    )
    out.append(
        _b(
            613,
            "List of names of fruits in Bengali",
            "Common fruits; some names are shared with colour words (কমলা).",
            "আম, কলা — widely eaten across Bengal.",
            [
                r("mango", "আম", "ām"),
                r("banana", "কলা", "kolā"),
                r("apple", "আপেল", "āpel"),
                r("orange (fruit)", "কমলা", "komolā"),
                r("grapes", "আঙুর", "āṅur"),
                r("guava", "পেয়ারা", "peẏārā"),
                r("papaya", "পেঁপে", "pẽpe"),
                r("coconut", "নারকেল", "nārkel"),
                r("lemon", "লেবু", "lēbu"),
                r("jackfruit", "কাঁঠাল", "kãṭhāl"),
                r("pineapple", "আনারস", "ānārôs"),
                r("watermelon", "তরমুজ", "tôrmuj"),
                r("pomegranate", "ডালিম", "ḍālim"),
                r("lychee", "লিচু", "lichu"),
                r("date (fruit)", "খেজুর", "khējur"),
                r("custard apple", "আতা", "ātā"),
                r("black plum / jamun", "কালোজাম", "kālōjām"),
                r("wood apple", "কদবেল", "kôdbēl"),
            ],
            heading="Fruits",
        )
    )
    out.append(
        _b(
            614,
            "List of names of birds in Bengali",
            "Common birds in towns and countryside.",
            "কাক, কোকিল — familiar sounds in Bengal.",
            [
                r("crow", "কাক", "kāk"),
                r("sparrow", "চড়াই", "choṛāi"),
                r("parrot", "টিয়া", "ṭiẏā"),
                r("pigeon", "কবুতর", "kôbutor"),
                r("duck", "হাঁস", "hãs"),
                r("hen / chicken", "মুরগি", "murgi"),
                r("eagle", "ঈগল / বাজপাখি", "īgôl / bājpākhi"),
                r("owl", "পেঁচা", "pẽchā"),
                r("peacock", "ময়ূর", "môyūr"),
                r("koel (cuckoo)", "কোকিল", "kōkil"),
                r("myna", "শালিক", "shālik"),
                r("swan", "রাজহাঁস", "rājhãs"),
                r("crane (bird)", "সারস", "sāras"),
                r("woodpecker", "কাঠঠোকরা", "kāṭhṭhōkrā"),
                r("kingfisher", "মাছরাঙা", "māchhrāṅā"),
                r("kite (bird)", "চিল", "chil"),
                r("seagull", "গাংচিল", "gāṅchil"),
                r("bat", "বাদুড়", "bāduṛ"),
            ],
            heading="Birds",
        )
    )
    out.append(
        _b(
            615,
            "List of names of insects in Bengali",
            "Common insects; several appear in idioms and daily complaints.",
            "মশা, পিঁপড়ে — household vocabulary.",
            [
                r("ant", "পিঁপড়ে", "pĩpoṛē"),
                r("bee", "মৌমাছি", "maumāchhi"),
                r("mosquito", "মশা", "môshā"),
                r("housefly", "মাছি", "māchhi"),
                r("spider", "মাকড়সা", "mākoṛsā"),
                r("butterfly", "প্রজাপতি", "prôjāpoti"),
                r("worm", "কীড়া", "kīṛā"),
                r("cockroach", "তেলাপোকা", "tēlāpōkā"),
                r("beetle / bug", "পোকা", "pōkā"),
                r("louse", "উকুন", "ukun"),
                r("firefly", "জোনাকি", "jōnāki"),
                r("scorpion", "বিছুটি", "bichhuṭi"),
                r("centipede", "কেন্নো", "kēnnō"),
                r("termite", "উইপোকা", "uipōkā"),
                r("dragonfly", "ফড়িং", "phoṛiṃ"),
                r("grasshopper", "ঘাসফড়িং", "ghāsphoṛiṃ"),
                r("moth", "রাতপোকা", "rātpōkā"),
                r("bedbug", "খুমটে", "khumṭe"),
            ],
            heading="Insects",
        )
    )
    out.append(
        _b(
            616,
            "List of colours in Bengali",
            "Basic and common colour words; often used as adjectives before nouns.",
            "লাল শাড়ি, নীল আকাশ.",
            [
                r("red", "লাল", "lāl"),
                r("blue", "নীল", "nīl"),
                r("green", "সবুজ", "sbuj"),
                r("yellow", "হলুদ", "hlud"),
                r("white", "সাদা", "sādā"),
                r("black", "কালো", "kālō"),
                r("orange (colour)", "কমলা", "komolā"),
                r("purple", "বেগুনি", "bēguni"),
                r("pink", "গোলাপি", "gōlāpi"),
                r("brown", "খয়েরি", "khôyēri"),
                r("grey", "ধূসর", "dhūsôr"),
                r("golden", "সোনালি", "sōnāli"),
                r("silver", "রুপালি", "rupāli"),
                r("dark (shade)", "গাঢ়", "gāṛh"),
                r("light (shade)", "হালকা", "hālka"),
                r("colour", "রং", "rông"),
                r("multicoloured", "রঙিন", "rôngin"),
                r("pale", "ফিকে", "phikē"),
            ],
            heading="Colours",
        )
    )
    out.append(
        _b(
            617,
            "List of names of flowers in Bengali",
            "Common flowers in gardens, worship, and markets.",
            "গোলাপ, জুঁই — strong cultural symbols.",
            [
                r("rose", "গোলাপ", "gōlāp"),
                r("lotus", "পদ্ম", "pôddo"),
                r("jasmine", "জুঁই", "jũi"),
                r("marigold", "গাঁদা", "gãdā"),
                r("sunflower", "সূর্যমুখী", "sūryomukhī"),
                r("hibiscus (joba)", "জবা", "jobā"),
                r("lily", "লিলি", "lili"),
                r("chrysanthemum", "চন্দ্রমল্লিকা", "chôndrômollikā"),
                r("tulip", "টিউলিপ", "ṭiulip"),
                r("daisy", "ডেইজি", "ḍēji"),
                r("flower (general)", "ফুল", "phul"),
                r("bud", "কুঁড়ি", "kũṛi"),
                r("fragrance", "সুগন্ধ", "sugôndh"),
                r("garland", "মালা", "mālā"),
                r("leaf", "পাতা", "pātā"),
                r("thorn", "কাঁটা", "kãṭā"),
                r("petal", "পাপড়ি", "pāpoṛi"),
                r("nectar", "মধু", "môdhu"),
            ],
            heading="Flowers",
        )
    )
    out.append(
        _b(
            618,
            "List of names of animals in Bengali",
            "Common mammals, reptiles, and small animals.",
            "কুকুর, বিড়াল — pets and street animals.",
            [
                r("dog", "কুকুর", "kukur"),
                r("cat", "বিড়াল", "biṛāl"),
                r("cow", "গরু", "goru"),
                r("goat", "ছাগল", "chāgôl"),
                r("horse", "ঘোড়া", "ghōṛā"),
                r("elephant", "হাতি", "hāti"),
                r("tiger", "বাঘ", "bāgh"),
                r("lion", "সিংহ", "siṃho"),
                r("monkey", "বানর", "bānôr"),
                r("snake", "সাপ", "sāp"),
                r("fish", "মাছ", "māch"),
                r("bird", "পাখি", "pākhi"),
                r("rabbit", "খরগোশ", "khôrgōsh"),
                r("camel", "উট", "uṭ"),
                r("fox", "শিয়াল", "shiẏāl"),
                r("deer", "হরিণ", "horiṇ"),
                r("bear", "ভালুক", "bhāluk"),
                r("crocodile", "কুমির", "kumir"),
            ],
            heading="Animals",
        )
    )
    out.append(
        _b(
            619,
            "Frequently used or common words in Bengali – Miscellaneous",
            "Polite words, greetings, and question words for basic communication.",
            "কী, কেন, কোথায় — start questions naturally.",
            [
                r("yes", "হ্যাঁ", "hyẫ"),
                r("no", "না", "nā"),
                r("please", "দয়া করে", "dôya kōre"),
                r("thank you", "ধন্যবাদ", "dhonyobād"),
                r("sorry", "দুঃখিত", "duhkhito"),
                r("excuse me", "মাফ করবেন", "māph kôrben"),
                r("hello", "হ্যালো / নমস্কার", "hyālō / nômôskār"),
                r("goodbye", "বিদায়", "bidāy"),
                r("good morning", "সুপ্রভাত", "suprobhāt"),
                r("good night", "শুভ রাত্রি", "shubho rātri"),
                r("welcome", "স্বাগতম", "shbāgotom"),
                r("what", "কী", "ki"),
                r("who", "কে", "kē"),
                r("where", "কোথায়", "kōthāy"),
                r("when", "কখন", "kôkhon"),
                r("why", "কেন", "kēn"),
                r("how", "কীভাবে", "kībhābē"),
                r("which", "কোন", "kōn"),
            ],
            heading="Common words",
        )
    )
