# Dogri grammar lessons 510–533 (Devanagari + Roman). Aligns with lessons_structure_dogri.json.

LESSONS_A = {
    510: [  # Pronouns and Articles in Dogri
        ["I", "मैं", "main"],
        ["You (informal)", "तू", "tu"],
        ["You (respectful)", "तुस", "tus"],
        ["He / she / that one", "ओ", "o"],
        ["We", "असी", "asi"],
        ["You (plural / polite)", "तुसां", "tusaan"],
        ["They", "ओ", "o"],
        ["This", "ए", "e"],
        ["That", "ओ", "o"],
        ["One boy", "इक मुंडा", "ik mundaa"],
        ["One girl", "इक कुड़ी", "ik kuddee"],
        ["The boy (this one)", "ए मुंडा", "e mundaa"],
        ["My book", "मेरी किताब", "meri kitaab"],
        ["Your book (informal)", "तैड़ी किताब", "taiddee kitaab"],
        ["His / her house", "ओदा घर", "odaa ghar"],
        ["Our school", "साडा सकूल", "saadaa sakool"],
        ["These children", "ए बच्चे", "e bacche"],
        ["Those men", "ओ आदमी", "o aadmee"],
        ["Who is he?", "ओ कौन आए?", "o kaun aaey?"],
        ["What is this?", "ए की आए?", "e kee aaey?"],
    ],
    511: [  # Using plurals to indicate respect in Dogri
        ["How are you? (respectful)", "तुस कैह् आए हो?", "tus kaih aaey ho?"],
        ["Please sit (formal)", "बैठ जाओ / बैठो", "baitho"],
        ["Father is reading (honorific)", "बापू पढ़दे आए", "baapu padhde aaey"],
        ["Mother is cooking (honorific)", "माँ रांधदी आए", "maa raandhdee aaey"],
        ["Grandfather spoke (respect)", "बुज्जुर्ग बोल्ले", "bujjurg bolle"],
        ["The teacher has come", "मास्टर आए गे", "maastar aaey ge"],
        ["Uncle went (respect past)", "चाचा चले गे", "chaachaa chale ge"],
        ["The doctor is at home", "डाक्टर घरे आए", "daaktar ghare aaey"],
        ["Please tell me (formal)", "मिगी दस्सो", "migee dasso"],
        ["He is eating (respect verb)", "ओ खांदा आए", "o khaandaa aaey"],
        ["She speaks softly (polite)", "ओ हौले बोलदी आए", "o haule boldee aaey"],
        ["They said (honorific)", "ओ बोल्ले", "o bolle"],
        ["You will go (polite future)", "तुस जाओगे", "tus jaoge"],
        ["We greet you (respect)", "असी तुसां नमस्कार करदे आं", "asi tusaan namaskaar karde aan"],
        ["Respected elder", "बुज्जुर्ग", "bujjurg"],
        ["Please eat (formal)", "खाओ / खाइयो", "khaao"],
        ["The officer is sitting", "ओफिसर बैठा आए", "ofisar baithaa aaey"],
        ["May I leave? (to elder)", "मैं जा सकदा आं?", "main jaa sakdaa aan?"],
        ["Thank you (formal)", "तुसां धन्नवाद", "tusaan dhannavaad"],
        ["Grandmother is resting", "दादी आराम करदी आए", "daadee aaraam kardee aaey"],
    ],
    512: [  # Verbs in Dogri
        ["To eat", "खाणा", "khaanaa"],
        ["To go", "जाणा", "jaanaa"],
        ["To come", "आणा", "aanaa"],
        ["To read", "पढ़ना", "padhnaa"],
        ["To write", "लिखना", "likhnaa"],
        ["To speak", "बोलना", "bolnaa"],
        ["To see", "दिखना / वेखना", "dekhnaa / vekhnaa"],
        ["To do", "करना", "karnaa"],
        ["To sit", "बैठना", "baithnaa"],
        ["To sleep", "सौणा", "saunaa"],
        ["I eat bread", "मैं रोटी खांदा आं", "main rotee khaandaa aan"],
        ["He reads a book", "ओ किताब पढ़दा आए", "o kitaab padhdaa aaey"],
        ["She writes a letter", "ओ चिट्ठी लिखदी आए", "o chitthee likhdee aaey"],
        ["We go to school", "असी सकूल जांदे आं", "asi sakool jaande aan"],
        ["They play in the field", "ओ मैदाने खेड़दे आए", "o maidaane khedde aaey"],
        ["Mother cooks food", "माँ खाना बनांदी आए", "maa khaanaa banaandee aaey"],
        ["The boy runs fast", "मुंडा तेज दौड़दा आए", "mundaa tej daurdaa aaey"],
        ["I want to learn Dogri", "मैं डोगरी सिखणा चांदा आं", "main dogree sikhanaa chaandaa aan"],
        ["It is good to help", "मदद करना चंगा आए", "madad karnaa changaa aaey"],
        ["They came to meet us", "ओ असें मिलने आए", "o asen milne aaey"],
    ],
    513: [  # Simple Present Tense
        ["I drink water", "मैं पाणी पींदा आं", "main paanee peendaa aan"],
        ["You speak loudly (informal)", "तू जोर कोल बोलदा आए", "tu zor kol boldaa aaey"],
        ["He works in Jammu", "ओ जम्मू च कम करदा आए", "o jammoo ch kam kardaa aaey"],
        ["She teaches Dogri", "ओ डोगरी पढ़ांदी आए", "o dogree padhaandee aaey"],
        ["We live in the village", "असी पेंड च रेंदे आं", "asi pend ch rende aan"],
        ["They sell fruit", "ओ फल बेचदे आए", "o phal bechde aaey"],
        ["The sun rises in the east", "सूरज पूरब च उगदा आए", "sooraj poorab ch ugdaa aaey"],
        ["Birds fly in the sky", "पंछी आकाश च उड़दे आए", "panchee aakaash ch uddde aaey"],
        ["I know this story", "मैं ए कहाणी जांदा आं", "main e kahaanee jaandaa aan"],
        ["You understand the lesson", "तू सबक समझदा आए", "tu sabak samajhdaa aaey"],
        ["He likes sweet tea", "ओ मिठ्ठी चा पसंद करदा आए", "o mitthee chaa pasand kardaa aaey"],
        ["She sings every morning", "ओ हर सवेर गांदी आए", "o har saver gaandee aaey"],
        ["We finish homework at night", "असी रात न गृह कम्म पूरा करदे आं", "asi raat n grih kamm pooraa karde aan"],
        ["They wait at the bus stop", "ओ बस स्टैंड ते इंतजार करदे आए", "o bas stand te intazaar karde aaey"],
        ["The train leaves at six", "ट्रेन छे वजे चलदी आए", "tren che vaje chaldee aaey"],
        ["I pay the bill", "मैं बिल दिंदा आं", "main bill dindaa aan"],
        ["You wash your hands", "तू हथ धोंदा आए", "tu hath dhondaa aaey"],
        ["Children play in the park", "बच्चे पार्क च खेड़दे आए", "bacche park ch khedde aaey"],
        ["He reads the newspaper daily", "ओ रोज अखबार पढ़दा आए", "o roz akhbaar padhdaa aaey"],
        ["We respect our teachers", "असी अपने मास्टरां दी इज़त करदे आं", "asi apne maastaraan dee izzat karde aan"],
    ],
    514: [  # Simple Present of "To Be"
        ["I am a student", "मैं इक विद्यार्थी आं", "main ik vidyaarthee aan"],
        ["You are tall (informal)", "तू लंबा आए", "tu lambaa aaey"],
        ["You are kind (polite)", "तुस नेक आए हो", "tus nek aaey ho"],
        ["He is my brother", "ओ मेरा प्रा आए", "o meraa praa aaey"],
        ["She is a doctor", "ओ डाक्टर आए", "o daaktar aaey"],
        ["We are ready", "असी तैयार आं", "asi taiyaar aan"],
        ["They are friends", "ओ दोस्त आए", "o dost aaey"],
        ["This is my house", "ए मेरा घर आए", "e meraa ghar aaey"],
        ["That is a temple", "ओ इक मंदिर आए", "o ik mandir aaey"],
        ["It is cold today", "अज ठंड आए", "aj thand aaey"],
        ["I am at home", "मैं घरे आं", "main ghare aan"],
        ["We are in Jammu", "असी जम्मू च आं", "asi jammoo ch aan"],
        ["They are on the road", "ओ सड़क ते आए", "o sarrak te aaey"],
        ["The keys are on the table", "चाबी मेज ते आए", "chaabee mez te aaey"],
        ["There is water in the pot", "बर्तन च पाणी आए", "bartan ch paanee aaey"],
        ["There are many people", "बहुत लोक आए", "bahut lok aaey"],
        ["I am fine", "मैं ठीक आं", "main theek aan"],
        ["How are you? (informal)", "तू कैह् आए?", "tu kaih aaey?"],
        ["How are you? (polite)", "तुस कैह् आए हो?", "tus kaih aaey ho?"],
        ["This book is new", "ए किताब नमी आए", "e kitaab namee aaey"],
    ],
    515: [  # Present Continuous
        ["I am eating now", "मैं हुन खांदा आं", "main hun khaandaa aan"],
        ["You are going to school", "तू सकूल जांदा आए", "tu sakool jaandaa aaey"],
        ["He is reading", "ओ पढ़दा आए", "o padhdaa aaey"],
        ["She is cooking", "ओ रांधदी आए", "o raandhee aaey"],
        ["We are coming", "असी आंदे आं", "asi aande aan"],
        ["They are playing", "ओ खेड़दे आए", "o khedde aaey"],
        ["It is raining", "मींह पैंदा आए", "meenh paindaa aaey"],
        ["The baby is sleeping", "नन्हा सौंदा आए", "nanhaa saundaa aaey"],
        ["I am writing a letter", "मैं चिट्ठी लिखदा आं", "main chitthee likhdaa aan"],
        ["You are listening", "तू सुनदा आए", "tu sundaa aaey"],
        ["He is driving the car", "ओ गड्डी चलांदा आए", "o gadddee chalaandaa aaey"],
        ["She is singing", "ओ गांदी आए", "o gaandee aaey"],
        ["We are waiting for the bus", "असी बस दा इंतजार करदे आं", "asi bas da intazaar karde aan"],
        ["They are building a house", "ओ घर बनांदे आए", "o ghar banaande aaey"],
        ["I am learning Dogri", "मैं डोगरी सिखदा आं", "main dogree sikhdaa aan"],
        ["The dog is barking", "कुत्ता भौंकदा आए", "kuttaa bhaunkdaa aaey"],
        ["Children are studying", "बच्चे पढ़दे आए", "bacche padhde aaey"],
        ["Mother is calling you", "माँ तूँ बुलांदी आए", "maa toon bulaandee aaey"],
        ["Why are you laughing?", "तू क्यों हसदा आए?", "tu kyon hasdaa aaey?"],
        ["We are not leaving yet", "असी हले नेईं जांदे", "asi hale nein jaande"],
    ],
    516: [  # Simple Future
        ["I will go tomorrow", "मैं काल्हे जामां", "main kaalhe jaamaan"],
        ["You will eat later", "तू बाद च खाइंगा", "tu baad ch khaingaa"],
        ["He will come soon", "ओ जल्दी आवेगा", "o jaldee aavegaa"],
        ["She will read this book", "ओ ए किताब पढ़ेगी", "o e kitaab padhegee"],
        ["We will meet again", "असी फेर मिलांगे", "asi fer milaange"],
        ["They will return home", "ओ घर मुड़नगे", "o ghar muddange"],
        ["It will rain today", "अज मींह पवेगा", "aj meenh pavegaa"],
        ["I will call you", "मैं तूँ फोन करांगा", "main toon fon karaanga"],
        ["You will pass the exam", "तू परीक्षा पास करेंगा", "tu pareekshaa paas karengaa"],
        ["He will buy rice", "ओ चावल खरीदेगा", "o chaaval khareedegaa"],
        ["She will visit Vaishno Devi", "ओ वैष्णो देवी जावेगी", "o vaishno devee jaavegee"],
        ["We will help you", "असी तुहाड़ी मदद करांगे", "asi tuhaadee madad karaange"],
        ["They will sing at the function", "ओ फंक्शन च गावनगे", "o phankshan ch gaavange"],
        ["The train will arrive at eight", "ट्रेन आठ वजे पहुंचेगी", "tren aath vaje pahunchegee"],
        ["I will not lie", "मैं झूठ नेईं बोलां", "main jhoot nein bolaan"],
        ["Will you come with me?", "तू मेरे नाल आएंगा?", "tu mere naal aaengaa?"],
        ["He will finish the work", "ओ कम्म पूरा करेगा", "o kamm pooraa karegaa"],
        ["We will celebrate Diwali", "असी दिवाली मनामांगे", "asi divaalee manaamaange"],
        ["They will build a school", "ओ इक सकूल बनावनगे", "o ik sakool banaavange"],
        ["I will send a message", "मैं संदेश भेजां", "main sandesh bhejaan"],
    ],
    517: [  # Future Continuous
        ["I will be studying tonight", "मैं रात न पढ़दा रहूंगा", "main raat n padhdaa rahungaa"],
        ["You will be waiting here", "तू इत्थे इंतजार करदा रहेंगा", "tu itthe intazaar kardaa rahengaa"],
        ["He will be working then", "ओ उस वेले कम करदा रहुगा", "o us vele kam kardaa rahugaa"],
        ["She will be cooking in the evening", "ओ शाम न रांधदी रहुगी", "o shaam n raandhee rahugee"],
        ["We will be travelling tomorrow", "असी काल्हे सफर करदे रहांगे", "asi kaalhe safar karde rahaange"],
        ["They will be playing at four", "ओ चार वजे खेड़दे रहनगे", "o chaar vaje khedde rahange"],
        ["It will be raining there", "उत्थे मींह पैंदा रहुगा", "utthe meenh paindaa rahugaa"],
        ["I will be reading on the train", "मैं ट्रेन च पढ़दा रहूंगा", "main tren ch padhdaa rahungaa"],
        ["You will be resting at home", "तू घरे आराम करदा रहेंगा", "tu ghare aaraam kardaa rahengaa"],
        ["He will be speaking at the meeting", "ओ मीटिंग च बोलदा रहुगा", "o meeting ch boldaa rahugaa"],
        ["She will be teaching that day", "ओ उस दिन पढ़ांदी रहुगी", "o us din padhaandee rahugee"],
        ["We will be watching the match", "असी मैच वेखदे रहांगे", "asi match vekhde rahaange"],
        ["They will be helping guests", "ओ मेहमानां दी मदद करदे रहनगे", "o mehmaanaan dee madad karde rahange"],
        ["The bus will be leaving soon", "बस जल्दी चलदी रहुगी", "bas jaldee chaldee rahugee"],
        ["I will be coming by that road", "मैं उस सड़क कोल आंदा रहूंगा", "main us sarrak kol aandaa rahungaa"],
        ["Will you be staying here?", "तू इत्थे रेंदा रहेंगा?", "tu itthe renda rahengaa?"],
        ["He will not be going alone", "ओ अकेला नेईं जावेगा", "o akelaa nein jaavegaa"],
        ["We will be waiting until evening", "असी शाम तलक इंतजार करदे रहांगे", "asi shaam talak intazaar karde rahaange"],
        ["They will be building the bridge", "ओ पुल बनांदे रहनगे", "o pul banaande rahange"],
        ["I will be sleeping by then", "मैं उस वेले सौंदा रहूंगा", "main us vele saundaa rahungaa"],
    ],
    518: [  # Simple Past Part 1 (no object)
        ["I went yesterday", "मैं कल्हे गेआ", "main kalhe geaa"],
        ["You came early (informal)", "तू जल्दी आइआ", "tu jaldee aaiaa"],
        ["He slept well", "ओ चंगी नींद सुत्या", "o changee neend sutyaa"],
        ["She laughed loudly", "ओ जोर कोल हसी", "o zor kol hasee"],
        ["We sat there", "असी उत्थे बैठे", "asi utthe baitthe"],
        ["They stood up", "ओ खड़े होए", "o kharre hoe"],
        ["I ran fast", "मैं तेज दौड़ेआ", "main tej dauriaa"],
        ["You walked slowly", "तू हौले चलेआ", "tu haule chaliaa"],
        ["He fell down", "ओ डिग्ग्या", "o diggyaa"],
        ["She woke up late", "ओ डेर न उठी", "o der n utthee"],
        ["We danced at the festival", "असी त्योहार च नाचे", "asi tyauhaar ch naache"],
        ["They shouted with joy", "ओ खुशी च चिल्लाए", "o khushee ch chillaae"],
        ["The bird flew away", "पंछी उड़ी गेआ", "panchee uddee geaa"],
        ["It rained heavily", "जोर कोल मींह पेआ", "zor kol meenh peaa"],
        ["I cried once", "मैं इक वार रोइआ", "main ik waar roiaa"],
        ["You arrived on time", "तू वक्त ते पहुंचेआ", "tu vakt te pahunchiaa"],
        ["He hurried home", "ओ जल्दी घर गेआ", "o jaldee ghar geaa"],
        ["We rested under the tree", "असी डंड तले आराम किता", "asi dand tale aaraam kitaa"],
        ["They returned late", "ओ डेर न मुड़े", "o der n mudde"],
        ["The sun set in the west", "सूरज पच्छम च डुब्या", "sooraj pachcham ch dubbyaa"],
    ],
    519: [  # Simple Past Part 2 (with object)
        ["I ate rice", "मैं चावल खादे", "main chaaval khaade"],
        ["You read the book", "तू किताब पढ़ी", "tu kitaab padhee"],
        ["He opened the door", "ओ दरवाजा खोलेआ", "o daravaajaa kholeaa"],
        ["She wrote a letter", "ओ चिट्ठी लिखी", "o chitthee likhee"],
        ["We saw a film", "असी इक फिल्म वेखी", "asi ik film vekhee"],
        ["They bought vegetables", "ओ सब्जी खरीदी", "o sabjee khareedee"],
        ["I gave him money", "मैं उसनू पैसे दित्ते", "main usanoo paise ditte"],
        ["You told the truth", "तू सच बोलेआ", "tu sach boliaa"],
        ["He caught the ball", "ओ गेंद फड़ी", "o gend faddee"],
        ["She made tea", "ओ चा बनाई", "o chaa banaaee"],
        ["We finished the work", "असी कम्म पूरा किता", "asi kamm pooraa kitaa"],
        ["They broke the glass", "ओ शीशा तोड़ेआ", "o sheeshaa toriaa"],
        ["I lost my pen", "मैं अपनी कलम गवाई", "main apanee kalam gavaaee"],
        ["You found the keys", "तू चाबी लब्भी", "tu chaabee labbhee"],
        ["He closed the window", "ओ खिड़की बंद किती", "o khidkee band kitee"],
        ["She washed the clothes", "ओ कपड़े धोए", "o kaprre dhoe"],
        ["We heard the news", "असी खबर सुनी", "asi khabar sunee"],
        ["They answered every question", "ओ हर सवाल दा जवाब दिता", "o har savaal da javaab ditaa"],
        ["I drank milk", "मैं दूध पीता", "main doodh peetaa"],
        ["You helped your friend", "तू अपने यार दी मदद किती", "tu apne yaar dee madad kitee"],
    ],
    520: [  # Past tense of "to be"
        ["I was at home", "मैं घरे सी", "main ghare see"],
        ["You were tired (informal)", "तू थका होआ", "tu thakaa hoaa"],
        ["He was ill", "ओ बिमार सी", "o bimaar see"],
        ["She was happy", "ओ खुश सी", "o khush see"],
        ["We were students", "असी विद्यार्थी सां", "asi vidyaarthee saan"],
        ["They were teachers", "ओ मास्टर सान", "o maastar saan"],
        ["It was cold", "ठंड सी", "thand see"],
        ["There was a problem", "इक मसला सी", "ik maslaa see"],
        ["There were many guests", "बहुत मेहमान सान", "bahut mehmaan saan"],
        ["I was in Jammu", "मैं जम्मू च सी", "main jammoo ch see"],
        ["You were late", "तू डेर न आइआ", "tu der n aaiaa"],
        ["He was my neighbour", "ओ मेरा पड़ोसी सी", "o meraa parosee see"],
        ["She was ready", "ओ तैयार सी", "o taiyaar see"],
        ["We were together", "असी इकठे सां", "asi ikatthe saan"],
        ["They were absent", "ओ गैर हाज़िर सान", "o gair haazir saan"],
        ["The shop was closed", "दुकान बंद सी", "dukaan band see"],
        ["The roads were wet", "सड़कां गीली सान", "sarrakaan geelee saan"],
        ["I was not afraid", "मैं डरा नेईं सी", "main daraa nein see"],
        ["Were you there?", "तू उत्थे सी?", "tu utthe see?"],
        ["It was a good day", "चंगा दिन सी", "changaa din see"],
    ],
    521: [  # Exceptional verbs (past)
        ["He goes → he went", "ओ जांदा आए → ओ गेआ", "o jaandaa aaey → o geaa"],
        ["He does → he did", "ओ करदा आए → ओ किता", "o kardaa aaey → o kitaa"],
        ["He gives → he gave", "ओ दिंदा आए → ओ दिता", "o dindaa aaey → o ditaa"],
        ["He takes → he took", "ओ लेंदा आए → ओ लेआ", "o lendaa aaey → o leaa"],
        ["He says → he said", "ओ बोलदा आए → ओ बोलेआ", "o boldaa aaey → o boliaa"],
        ["He sees → he saw", "ओ वेखदा आए → ओ वेखेआ", "o vekhdaa aaey → o vekhiaa"],
        ["He sits → he sat", "ओ बैठदा आए → ओ बैठेआ", "o baithdaa aaey → o baithiaa"],
        ["He comes → he came", "ओ आंदा आए → ओ आइआ", "o aandaa aaey → o aaiaa"],
        ["I go → I went", "मैं जांदा आं → मैं गेआ", "main jaandaa aan → main geaa"],
        ["I eat → I ate", "मैं खांदा आं → मैं खादा", "main khaandaa aan → main khaadaa"],
        ["You drink → you drank", "तू पींदा आए → तू पीता", "tu peendaa aaey → tu peetaa"],
        ["We come → we came", "असी आंदे आं → असी आए", "asi aande aan → asi aaey"],
        ["They go → they went", "ओ जांदे आए → ओ गे", "o jaande aaey → o ge"],
        ["He sleeps → he slept", "ओ सौंदा आए → ओ सुत्या", "o saundaa aaey → o sutyaa"],
        ["She reads → she read", "ओ पढ़दी आए → ओ पढ़ी", "o padhee aaey → o padhee"],
        ["He runs → he ran", "ओ दौड़दा आए → ओ दौड़ेआ", "o daurdaa aaey → o dauriaa"],
        ["It falls → it fell", "ओ डिग्गदा आए → ओ डिग्ग्या", "o diggdaa aaey → o diggyaa"],
        ["He knows → he knew", "ओ जांदा आए → ओ जाणेआ", "o jaandaa aaey → o jaaneaa"],
        ["I bring → I brought", "मैं लेंदा आं → मैं लेआ", "main lendaa aan → main leaa"],
        ["You forget → you forgot", "तू भुलदा आए → तू भुलेआ", "tu bhuldaa aaey → tu bhuleaa"],
    ],
    522: [  # Past Continuous
        ["I was reading then", "मैं उस वेले पढ़दा सी", "main us vele padhdaa see"],
        ["You were sleeping", "तू सुतदा सी", "tu sutdaa see"],
        ["He was walking home", "ओ घर न चलदा सी", "o ghar n chaldaa see"],
        ["She was cooking rice", "ओ चावल रांधदी सी", "o chaaval raandhee see"],
        ["We were talking", "असी गल्ल करदे सां", "asi gall karde saan"],
        ["They were playing", "ओ खेड़दे सान", "o khedde saan"],
        ["It was raining", "मींह पैंदा सी", "meenh paindaa see"],
        ["The baby was crying", "नन्हा रोंदा सी", "nanhaa rondaa see"],
        ["I was waiting for you", "मैं तेरा इंतजार करदा सी", "main teraa intazaar kardaa see"],
        ["You were driving fast", "तू तेज गड्डी चलांदा सी", "tu tej gadddee chalaandaa see"],
        ["He was writing a letter", "ओ चिट्ठी लिखदा सी", "o chitthee likhdaa see"],
        ["She was singing on stage", "ओ मंच ते गांदी सी", "o manch te gaandee see"],
        ["We were watching TV", "असी टीवी वेखदे सां", "asi teevee vekhde saan"],
        ["They were building a wall", "ओ दीवार बनांदे सान", "o deevaar banaande saan"],
        ["The dog was barking", "कुत्ता भौंकदा सी", "kuttaa bhaunkdaa see"],
        ["I was not listening", "मैं नेईं सुनदा सी", "main nein sundaa see"],
        ["Why were you late?", "तू डेर क्यों करी?", "tu der kyon karee?"],
        ["He was helping his father", "ओ अपने बापू दी मदद करदा सी", "o apne baapoo dee madad kardaa see"],
        ["We were studying all day", "असी सारा दिन पढ़दे सां", "asi saaraa din padhde saan"],
        ["They were laughing loudly", "ओ जोर कोल हसदे सान", "o zor kol hasde saan"],
    ],
    523: [  # Perfect tenses
        ["I have eaten", "मैं खा चुकेआ", "main khaa chukeaa"],
        ["You have come", "तू आ चुकेआ", "tu aa chukeaa"],
        ["He has gone", "ओ जा चुकेआ", "o jaa chukeaa"],
        ["She has finished", "ओ पूरा कर चुकी", "o pooraa kar chukee"],
        ["We have seen it", "असी वेख चुके", "asi vekh chuke"],
        ["They have left", "ओ चले गे", "o chale ge"],
        ["I had slept", "मैं सुत चुकेआ सी", "main sut chukeaa see"],
        ["You had told me", "तू मिगी दस्स चुकेआ", "tu migee dass chukeaa"],
        ["He had arrived", "ओ पहुंच चुकेआ सी", "o pahunch chukeaa see"],
        ["She had cooked", "ओ रांध चुकी सी", "o raandh chukee see"],
        ["We had agreed", "असी राज़ी हो चुके सां", "asi raazee ho chuke saan"],
        ["They had gone before us", "ओ साडे पैह्लें चले गे", "o saade paihlen chale ge"],
        ["I will have finished", "मैं पूरा कर चुकूंगा", "main pooraa kar chukungaa"],
        ["You will have left", "तू चले जा चुकेंगा", "tu chale jaa chukengaa"],
        ["He will have read", "ओ पढ़ चुकेगा", "o padh chukegaa"],
        ["By then I will have gone", "उस वेले मैं जा चुकूंगा", "us vele main jaa chukungaa"],
        ["She will have cooked by evening", "शाम तलक ओ रांध चुकेगी", "shaam talak o raandh chukegee"],
        ["We have not met yet", "असी हले नेईं मिले", "asi hale nein mile"],
        ["Have you heard?", "तू सुनेआ?", "tu suneaa?"],
        ["They had never seen snow", "ओ कदे बर्फ नेईं वेखी", "o kade baraf nein vekhee"],
    ],
    524: [  # Prepositions
        ["In the room", "कमरे च", "kamre ch"],
        ["On the table", "मेज ते", "mez te"],
        ["Under the bed", "बिस्तरे थल्ले", "bistare thalle"],
        ["Near the river", "दरिया कोल", "dariyaa kol"],
        ["From the city", "शहर कोलों", "shehar kolon"],
        ["To the market", "बाज़ार नू", "baazaar noo"],
        ["With my mother", "मेरी माँ नाल", "meree maa naal"],
        ["Without money", "पैसे बिना", "paise binaa"],
        ["Between two trees", "दो रुखां विच", "do rukhaan vich"],
        ["Behind the house", "घर पिछे", "ghar pichhe"],
        ["In front of the gate", "दरवाजे अग्गे", "daravaaje agge"],
        ["Inside the box", "डिब्बे च", "dibbe ch"],
        ["Outside the village", "पेंड कोलों", "pend kolon"],
        ["Across the bridge", "पुल पार", "pul paar"],
        ["Until tomorrow", "काल्हे तलक", "kaalhe talak"],
        ["After lunch", "दुपहरे बाद", "dupahre baad"],
        ["Before sunrise", "सूरज चढ़ने पैह्लें", "sooraj chadhne paihlen"],
        ["I am at school", "मैं सकूल च आं", "main sakool ch aan"],
        ["The book is in the bag", "किताब थैली च आए", "kitaab thailee ch aaey"],
        ["He sat beside me", "ओ मेरे कोल बैठेआ", "o mere kol baithiaa"],
    ],
    525: [  # Preposition TO (motion)
        ["Go to school", "सकूल नू जा", "sakool noo jaa"],
        ["Come to my house", "मेरे घर आ", "mere ghar aa"],
        ["Return to work", "कम्म ते मुड़", "kamm te mudd"],
        ["Walk to the shop", "दुकान नू पैदल जा", "dukaan noo paidal jaa"],
        ["Run to the field", "मैदाने दौड़", "maidaane daur"],
        ["Send a letter to him", "उसनू चिट्ठी भेज", "usanoo chitthee bhej"],
        ["Give water to the dog", "कुत्ते नू पाणी दे", "kutte noo paanee de"],
        ["I am going to Katra", "मैं कटड़ा जांदा आं", "main katrraa jaandaa aan"],
        ["We went to the temple", "असी मंदिर गेए", "asi mandir geae"],
        ["They came to help", "ओ मदद करने आए", "o madad karne aaey"],
        ["Take this to father", "ए बापू नू ले जा", "e baapoo noo le jaa"],
        ["Come to me", "मेरे कोल आ", "mere kol aa"],
        ["Fly to Delhi", "दिल्ली नू उड़", "dillee noo udd"],
        ["Drive to the station", "स्टेशन नू गड्डी ले जा", "steshan noo gadddee le jaa"],
        ["I will go to the bank", "मैं बैंक जामां", "main baenk jaamaan"],
        ["She ran to the door", "ओ दरवाजे दौड़ी", "o daravaaje daurdee"],
        ["Bring fruit to me", "मिगी फल ले आ", "migee phal le aa"],
        ["Do not go to the river alone", "अकेला दरिया नेईं जा", "akelaa dariyaa nein jaa"],
        ["We are going to Udhampur", "असी उधमपुर जांदे आं", "asi udhampur jaande aan"],
        ["He came to the meeting", "ओ मीटिंग च आइआ", "o meeting ch aaiaa"],
    ],
    526: [  # Person as object
        ["I saw him", "मैं उसनू वेखेआ", "main usanoo vekhiaa"],
        ["You called her", "तू उसनू बुलाइआ", "tu usanoo bulaiaa"],
        ["He helped them", "ओ उनां दी मदद किती", "o unaan dee madad kitee"],
        ["She loves her mother", "ओ अपनी माँ नू प्यार करदी आए", "o apanee maa noo pyaar kardee aaey"],
        ["We invited the guests", "असी मेहमानां नू बुलाइआ", "asi mehmaanaan noo bulaiaa"],
        ["They praised the teacher", "ओ मास्टर दी तारीफ किती", "o maastar dee taareef kitee"],
        ["I gave the child a sweet", "मैं बच्चे नू मिठाई दिती", "main bacce noo mithaai ditee"],
        ["You told us the story", "तू असें कहाणी सुनाइई", "tu asen kahaanee sunaaee"],
        ["He sent me a message", "ओ मिगी संदेश भेजेआ", "o migee sandesh bhejiaa"],
        ["She showed me the photo", "ओ मिगी फोटो दिखाइई", "o migee foto dikhaaee"],
        ["Find the boy", "मुंडे नू लब्भ", "mundee noo labbh"],
        ["Call the doctor", "डाक्टर नू फोन कर", "daaktar noo fon kar"],
        ["Respect your elders", "बुज्जुर्गां दी इज़त कर", "bujjurgaan dee izzat kar"],
        ["I met my friend", "मैं अपने यार नू मिलेआ", "main apne yaar noo miliaa"],
        ["We missed you", "असी तुहानू याद किता", "asi tuhaanoo yaad kitaa"],
        ["They forgot him", "ओ उसनू भुले गे", "o usanoo bhule ge"],
        ["Do not hurt anyone", "किसे नू चोट नेईं दे", "kise noo chot nein de"],
        ["I taught the students", "मैं विद्यार्थियां नू पढ़ाइआ", "main vidyaarthiyaan noo padhaiaa"],
        ["She fed the baby", "ओ नन्हे नू खुआइआ", "o nanhe noo khuaiaa"],
        ["He thanked his parents", "ओ अपने माता-पिता दा धन्नवाद किता", "o apne maataa-pitaa da dhannavaad kitaa"],
    ],
    527: [  # My / His / Her
        ["My book", "मेरी किताब", "meree kitaab"],
        ["Your book (informal)", "तैड़ी किताब", "taiddee kitaab"],
        ["Your book (polite)", "तुहाड़ी किताब", "tuhaadee kitaab"],
        ["His book", "उदी किताब", "udee kitaab"],
        ["Her book", "उदी किताब", "udee kitaab"],
        ["Our house", "साडा घर", "saadaa ghar"],
        ["Your house (pl.)", "तुहाडा घर", "tuhaadaa ghar"],
        ["Their house", "उनां दा घर", "unaan daa ghar"],
        ["My father", "मेरा बापू", "meraa baapoo"],
        ["His father", "उदा बापू", "udaa baapoo"],
        ["Her mother", "उदी माँ", "udee maa"],
        ["Our teacher", "साडा मास्टर", "saadaa maastar"],
        ["Their children", "उनां दे बच्चे", "unaan de bacche"],
        ["This is mine", "ए मेरा आए", "e meraa aaey"],
        ["That is yours", "ओ तुहाडा आए", "o tuhaadaa aaey"],
        ["The pen is his", "कलम उदी आए", "kalam udee aaey"],
        ["These are our books", "ए साडियां किताबां आए", "e saadeeaan kitaabaan aaey"],
        ["I lost my keys", "मैं अपनी चाबी गवाई", "main apanee chaabee gavaaee"],
        ["She took her bag", "ओ अपनी थैली लेई", "o apanee thailee leee"],
        ["We love our village", "असी अपने पेंड नू प्यार करदे आं", "asi apne pend noo pyaar karde aan"],
    ],
    528: [  # WH questions
        ["What is your name?", "तुहाडा नां की आए?", "tuhaadaa naan kee aaey?"],
        ["Where are you going?", "तू कुथे जांदा आए?", "tu kuthe jaandaa aaey?"],
        ["When did he come?", "ओ कदों आइआ?", "o kadon aaiaa?"],
        ["Why are you sad?", "तू उदास क्यों आए?", "tu udaas kyon aaey?"],
        ["How are you?", "तू कैह् आए?", "tu kaih aaey?"],
        ["Who is that?", "ओ कौन आए?", "o kaun aaey?"],
        ["How much is this?", "ए कन्ना दा आए?", "e kannaa daa aaey?"],
        ["Which book do you want?", "तू केड़ी किताब चांदा आए?", "tu keddee kitaab chaandaa aaey?"],
        ["Whose pen is this?", "ए किसदी कलम आए?", "e kisdee kalam aaey?"],
        ["How many people came?", "कन्ने लोक आए?", "kanne lok aaey?"],
        ["Where do you live?", "तू कुथे रेंदा आए?", "tu kuthe renda aaey?"],
        ["What do you do?", "तू की करदा आए?", "tu kee kardaa aaey?"],
        ["When will you return?", "तू कदों मुड़ेंगा?", "tu kadon mudenga?"],
        ["Why did she leave?", "ओ क्यों चली गई?", "o kyon chalee gaee?"],
        ["How did you come?", "तू किमें आइआ?", "tu kimen aaiaa?"],
        ["Is this yours?", "ए तुहाडा आए?", "e tuhaadaa aaey?"],
        ["Are they ready?", "ओ तैयार आए?", "o taiyaar aaey?"],
        ["Can you help me?", "तू मेरी मदद कर सकदा आए?", "tu meree madad kar sakdaa aaey?"],
        ["Do you know Dogri?", "तू डोगरी जांदा आए?", "tu dogree jaandaa aaey?"],
        ["What happened?", "की होइआ?", "kee hoiaa?"],
    ],
    529: [  # Negative present
        ["I do not eat meat", "मैं मांस नेईं खांदा", "main maans nein khaandaa"],
        ["You do not understand", "तू नेईं समझदा", "tu nein samajhdaa"],
        ["He does not lie", "ओ झूठ नेईं बोलदा", "o jhoot nein boldaa"],
        ["She does not sing today", "ओ अज नेईं गांदी", "o aj nein gaandee"],
        ["We do not play now", "असी हुन नेईं खेड़दे", "asi hun nein khedde"],
        ["They do not come here", "ओ इत्थे नेईं आंदे", "o itthe nein aande"],
        ["I do not know", "मैं नेईं जांदा", "main nein jaandaa"],
        ["You do not listen", "तू नेईं सुनदा", "tu nein sundaa"],
        ["He does not work on Sunday", "ओ रविवार नेईं कम करदा", "o ravivaar nein kam kardaa"],
        ["She does not like tea", "ओ चा पसंद नेईं करदी", "o chaa pasand nein kardee"],
        ["We do not forget", "असी नेईं भुलदे", "asi nein bhulde"],
        ["They do not agree", "ओ राज़ी नेईं होंदे", "o raazee nein honde"],
        ["There is no water", "पाणी नेईं आए", "paanee nein aaey"],
        ["I am not afraid", "मैं डरा नेईं", "main daraa nein"],
        ["This is not mine", "ए मेरा नेईं", "e meraa nein"],
        ["We are not late", "असी डेर नेईं", "asi der nein"],
        ["He is not at home", "ओ घरे नेईं", "o ghare nein"],
        ["Do not run here", "इत्थे नेईं दौड़", "itthe nein daur"],
        ["I do not want it", "मिगी ए चाइदा नेईं", "migee e chaaidaa nein"],
        ["You do not need to go", "तून्हू जाणे दी लोड़ नेईं", "toonhoo jaane dee lor nein"],
    ],
    530: [  # Negative past
        ["I did not go", "मैं नेईं गेआ", "main nein geaa"],
        ["You did not eat", "तू नेईं खादा", "tu nein khaadaa"],
        ["He did not come", "ओ नेईं आइआ", "o nein aaiaa"],
        ["She did not sleep", "ओ नेईं सुती", "o nein sutee"],
        ["We did not see him", "असी उसनू नेईं वेखेआ", "asi usanoo nein vekhiaa"],
        ["They did not hear", "ओ नेईं सुने", "o nein sune"],
        ["I did not buy it", "मैं ए नेईं खरीदेआ", "main e nein khareediaa"],
        ["You did not tell me", "तू मिगी नेईं दस्सेआ", "tu migee nein dassiaa"],
        ["He did not open the door", "ओ दरवाजा नेईं खोलेआ", "o daravaajaa nein kholeaa"],
        ["She did not write", "ओ नेईं लिखी", "o nein likhee"],
        ["We did not finish", "असी पूरा नेईं किता", "asi pooraa nein kitaa"],
        ["They did not wait", "ओ इंतजार नेईं किता", "o intazaar nein kitaa"],
        ["I was not there", "मैं उत्थे नेईं सी", "main utthe nein see"],
        ["It did not rain", "मींह नेईं पेआ", "meenh nein peaa"],
        ["He did not agree", "ओ राज़ी नेईं होइआ", "o raazee nein hoiaa"],
        ["We did not meet", "असी नेईं मिले", "asi nein mile"],
        ["She did not answer", "ओ जवाब नेईं दिता", "o javaab nein ditaa"],
        ["I did not forget", "मैं नेईं भुलेआ", "main nein bhuleaa"],
        ["You did not try", "तू कोशिश नेईं किती", "tu koshish nein kitee"],
        ["They did not return", "ओ नेईं मुड़े", "o nein mudde"],
    ],
    531: [  # Negative future
        ["I will not go", "मैं नेईं जामां", "main nein jaamaan"],
        ["You will not eat", "तू नेईं खाइंगा", "tu nein khaingaa"],
        ["He will not come", "ओ नेईं आवेगा", "o nein aavegaa"],
        ["She will not leave", "ओ नेईं जावेगी", "o nein jaavegee"],
        ["We will not forget", "असी नेईं भुलांगे", "asi nein bhulaange"],
        ["They will not come tomorrow", "ओ काल्हे नेईं आनगे", "o kaalhe nein aanage"],
        ["I will not tell anyone", "मैं किसे नेईं दस्सां", "main kise nein dassaan"],
        ["You will not regret", "तू पछतावा नेईं करेंगा", "tu pachhtaavaa nein karengaa"],
        ["He will not agree", "ओ राज़ी नेईं होवेगा", "o raazee nein hovegaa"],
        ["She will not sing", "ओ नेईं गावेगी", "o nein gaavegee"],
        ["We will not stop", "असी नेईं रुकांगे", "asi nein rukaange"],
        ["They will not pay", "ओ पैसे नेईं देनगे", "o paise nein denage"],
        ["It will not happen", "ए नेईं होवेगा", "e nein hovegaa"],
        ["I will not be late", "मैं डेर नेईं करां", "main der nein karaan"],
        ["You will not fail", "तू फेल नेईं होवेंगा", "tu fel nein hovengaa"],
        ["He will not return alone", "ओ अकेला नेईं मुड़ेगा", "o akelaa nein muddegaa"],
        ["We will not give up", "असी हार नेईं मानांगे", "asi haar nein manaange"],
        ["They will not build here", "ओ इत्थे नेईं बनानगे", "o itthe nein banaanage"],
        ["I will never lie", "मैं कदे झूठ नेईं बोलां", "main kade jhoot nein bolaan"],
        ["She will not marry him", "ओ उसनू नेईं ब्याहेगी", "o usanoo nein byaahegee"],
    ],
    532: [  # Gender & plurals
        ["Boy", "मुंडा", "mundaa"],
        ["Boys", "मुंडे", "mundde"],
        ["Girl", "कुड़ी", "kuddee"],
        ["Girls", "कुड़ियां", "kuddeeaan"],
        ["Man", "आदमी", "aadmee"],
        ["Men", "आदमी", "aadmee"],
        ["Woman", "औरत", "aurat"],
        ["Women", "औरतां", "aurataan"],
        ["Lion", "शेर", "sher"],
        ["Cow", "गां", "gaan"],
        ["Teacher (male)", "मास्टर", "maastar"],
        ["Teacher (female)", "मास्टरनी", "maastaranee"],
        ["One tree", "इक रुख", "ik rukh"],
        ["Many trees", "बहुत रुख", "bahut rukh"],
        ["One book", "इक किताब", "ik kitaab"],
        ["Several books", "कई किताबां", "kaee kitaabaan"],
        ["The boy runs", "मुंडा दौड़दा आए", "mundaa daurdaa aaey"],
        ["The girls sang", "कुड़ियां गाइयां", "kuddeeaan gaaiaan"],
        ["Good men help others", "चंगे आदमी होरां दी मदद करदे आए", "change aadmee horaan dee madad karde aaey"],
        ["Those women are teachers", "ओ औरतां मास्टरनी आए", "o aurataan maastaranee aaey"],
    ],
    533: [  # Nouns + prepositions
        ["Fish in the river", "दरिया च मछली", "dariyaa ch machhlee"],
        ["Birds on the roof", "छत ते पंछी", "chhat te panchee"],
        ["Fruit in the basket", "टोकरी च फल", "tokree ch phal"],
        ["Money in the pocket", "जेब च पैसे", "jeb ch paise"],
        ["Cat under the chair", "कुर्सी थल्ले बिल्ली", "kursee thalle billee"],
        ["Dog near the gate", "दरवाजे कोल कुत्ता", "daravaaje kol kuttaa"],
        ["Books on the shelf", "अलमारी ते किताबां", "almaaree te kitaabaan"],
        ["Flowers in the garden", "बाग च फुल", "baag ch phul"],
        ["Students in the class", "क्लास च विद्यार्थी", "klaas ch vidyaarthee"],
        ["People at the market", "बाज़ार च लोक", "baazaar ch lok"],
        ["Stars in the sky", "आकाश च तारे", "aakaash ch taare"],
        ["Boat on the water", "पाणी ते नाव", "paanee te naav"],
        ["I put rice in the pot", "मैं हांडी च चावल पाइआ", "main haandee ch chaaval paaiaa"],
        ["There is a hole in the wall", "दीवार च इक छेद आए", "deevaar ch ik chhed aaey"],
        ["She kept fruit in the fridge", "ओ फ्रिज च फल रखे", "o frij ch phal rakhe"],
        ["We sat on the grass", "असी घास ते बैठे", "asi ghaas te baitthe"],
        ["The keys are in the drawer", "चाबी दराज च आए", "chaabee daraaj ch aaey"],
        ["Children played in the field", "बच्चे मैदाने खेड़े", "bacche maidaane khedde"],
        ["There is a temple on the hill", "पहाड़ ते इक मंदिर आए", "pahaarr te ik mandir aaey"],
        ["He works at the office", "ओ ऑफिस च कम करदा आए", "o ofis ch kam kardaa aaey"],
    ],
}
