# Dogri grammar lessons 534–542

LESSONS_B = {
    534: [  # Similar prepositions
        ["Near / beside (kol)", "कोल", "kol"],
        ["Close (nede)", "नेड़े", "nedde"],
        ["Inside (andar / ch)", "अंदर / च", "andar / ch"],
        ["On (te)", "ते", "te"],
        ["Under (thalle)", "थल्ले", "thalle"],
        ["Behind (pichhe)", "पिछे", "pichhe"],
        ["In front (agge)", "अग्गे", "agge"],
        ["Between (vich)", "विच", "vich"],
        ["Until (talak)", "तलक", "talak"],
        ["Sit beside me", "मेरे कोल बैठ", "mere kol baith"],
        ["Stand near the door", "दरवाजे नेड़े खड़ा हो", "daravaaje nedde kharraa ho"],
        ["The cat is under the table", "बिल्ली मेज थल्ले आए", "billee mez thalle aaey"],
        ["The picture is on the wall", "तस्वीर दीवार ते आए", "tasweer deevaar te aaey"],
        ["We work until evening", "असी शाम तलक कम करदे आं", "asi shaam talak kam karde aan"],
        ["He lives near the river", "ओ दरिया कोल रेंदा आए", "o dariyaa kol renda aaey"],
        ["The shop is behind the post office", "दुकान पोस्ट ऑफिस पिछे आए", "dukaan post ofis pichhe aaey"],
        ["Keep shoes under the bed", "जूते बिस्तरे थल्ले रख", "joote bistare thalle rakh"],
        ["Between you and me", "तुसां अते मेरे विच", "tusaan ate mere vich"],
        ["Wait until I come", "जदों मैं आं तद तलक इंतजार कर", "jadon main aan tad talak intazaar kar"],
        ["Come in front of me", "मेरे अग्गे आ", "mere agge aa"],
    ],
    535: [  # Cases (विभक्ति)
        ["Subject: The boy reads", "मुंडा पढ़दा आए", "mundaa padhdaa aaey"],
        ["Object: I see him", "मैं उसनू वेखदा आं", "main usanoo vekhdaa aan"],
        ["With a pen (instrument)", "कलम कोल", "kalam kol"],
        ["To me (dative)", "मिगी", "migee"],
        ["From the village", "पेंड कोलों", "pend kolon"],
        ["Of Rama (genitive)", "राम दा", "raam daa"],
        ["On the roof (locative)", "छत ते", "chhat te"],
        ["Give the book to her", "उसनू किताब दे", "usanoo kitaab de"],
        ["He came by bus", "ओ बस कोल आइआ", "o bas kol aaiaa"],
        ["She wrote with chalk", "ओ चॉक कोल लिखी", "o chok kol likhee"],
        ["Water flows from the tap", "टोंटी कोलों पाणी आंदा आए", "tontee kolon paanee aandaa aaey"],
        ["This is mother's sari", "ए माँ दी साड़ी आए", "e maa dee saarree aaey"],
        ["The boy hid behind the door", "मुंडा दरवाजे पिछे लुकेआ", "mundaa daravaaje pichhe lukeaa"],
        ["I sat on the floor", "मैं फर्श ते बैठेआ", "main pharsh te baithiaa"],
        ["They came from Udhampur", "ओ उधमपुर कोलों आए", "o udhampur kolon aaey"],
        ["She cut with a knife", "ओ चाकू कोल काटी", "o chaakoo kol kaatee"],
        ["We sent money to him", "असी उसनू पैसे भेजे", "asi usanoo paise bheje"],
        ["The bird is on the branch", "पंछी डंड ते आए", "panchee dand te aaey"],
        ["I learned from the teacher", "मैं मास्टर कोलों सिखेआ", "main maastar kolon sikhyaa"],
        ["He died of fever", "ओ बुखार कोल मरेआ", "o bukhaar kol mareaa"],
    ],
    536: [  # Commands
        ["Come!", "आ!", "aa!"],
        ["Go!", "जा!", "jaa!"],
        ["Sit!", "बैठ!", "baith!"],
        ["Eat!", "खा!", "khaa!"],
        ["Drink water!", "पाणी पी!", "paanee pee!"],
        ["Read!", "पढ़!", "padh!"],
        ["Write!", "लिख!", "likh!"],
        ["Listen!", "सुन!", "sun!"],
        ["Open the door!", "दरवाजा खोल!", "daravaajaa khol!"],
        ["Close it!", "बंद कर!", "band kar!"],
        ["Please come (formal)", "मेहरबानी करियै आओ", "meharbaanee kariyai aao"],
        ["Please sit (formal)", "बैठ जाओ", "baith jaa"],
        ["Do not go!", "नेईं जा!", "nein jaa!"],
        ["Do not shout!", "नेईं चिल्ला!", "nein chillaa!"],
        ["Let's go together", "इकठे चलिए", "ikatthe chalie"],
        ["Tell the truth!", "सच बोल!", "sach bol!"],
        ["Help him!", "उदी मदद कर!", "udee madad kar!"],
        ["Wait here!", "इत्थे इंतजार कर!", "itthe intazaar kar!"],
        ["Bring the book!", "किताब ले आ!", "kitaab le aa!"],
        ["Forgive me!", "माफ करियो!", "maaf kariyo!"],
    ],
    537: [  # Time words
        ["Today", "अज", "aj"],
        ["Tomorrow", "काल्हे", "kaalhe"],
        ["Yesterday", "कल्हे / कल", "kalhe / kal"],
        ["Day before yesterday", "परसों", "parson"],
        ["Now", "हुन / अब", "hun / ab"],
        ["Morning", "सवेर / सवेरे", "saver / savere"],
        ["Afternoon", "दुपहर", "dupahar"],
        ["Evening", "शाम", "shaam"],
        ["Night", "रात", "raat"],
        ["Week", "हफ्ता", "haftaa"],
        ["Month", "महीना", "maheenaa"],
        ["Year", "साल", "saal"],
        ["Sometimes", "कदे कदे", "kade kade"],
        ["Always", "हमेशा", "hameshaa"],
        ["Never", "कदे नेईं", "kade nein"],
        ["I will come tomorrow morning", "मैं काल्हे सवेरे आमां", "main kaalhe savere aamaan"],
        ["We met yesterday evening", "असी कल्हे शाम न मिले", "asi kalhe shaam n mile"],
        ["He works every day", "ओ हर दिन कम करदा आए", "o har din kam kardaa aaey"],
        ["At night it is quiet", "रात न शांति होंदी आए", "raat n shaanti hondee aaey"],
        ["See you next week", "अगले हफ्ते मिलांगे", "agle hafte milaange"],
        ["She was born in 2010", "ओ दो हजार दस च जन्मी", "o do hazaar das ch janmee"],
    ],
    538: [  # Causative
        ["I feed the child", "मैं बच्चे नू खुआंदा आं", "main bacce noo khuaandaa aan"],
        ["She makes him study", "ओ उसनू पढ़ांदी आए", "o usanoo padhaandee aaey"],
        ["Mother puts the baby to sleep", "माँ नन्हे नू सुलांदी आए", "maa nanhe noo sullaandee aaey"],
        ["The teacher makes us read", "मास्टर असें पढ़ांदा आए", "maastar asen padhaandaa aaey"],
        ["I got the letter written", "मैं चिट्ठी लिखवाइई", "main chitthee likhvaayee"],
        ["He had the house painted", "ओ घर रंगवाइआ", "o ghar rangvaiaa"],
        ["She made me laugh", "ओ मिगी हसाइआ", "o migee hasaaiaa"],
        ["We let them go", "असी उनां नू जाण दिता", "asi unaan noo jaan ditaa"],
        ["He showed the way", "ओ रस्ता दिखाइआ", "o rastaa dikhaiaa"],
        ["I will get the work done", "मैं कम्म करवामां", "main kamm karvaamaan"],
        ["They made him understand", "ओ उसनू समझाइआ", "o usanoo samjhaiaa"],
        ["Father made me sit", "बापू ने मिगी बैठाइआ", "baapoo ne migee baithaiaa"],
        ["The doctor made him drink medicine", "डाक्टर ने उसनू दवाई पिलाइई", "daaktar ne usanoo davaaee pilaaee"],
        ["I had the car repaired", "मैं गड्डी ठीक करवाइई", "main gadddee theek karvaayee"],
        ["She gets clothes washed", "ओ कपड़े धुआंदी आए", "o kaprre dhuaandee aaey"],
        ["We teach children to write", "असी बच्चियां नू लिखवांदे आं", "asi bacchiyaan noo likhvaande aan"],
        ["He made the dog run", "ओ कुत्ते नू दौड़ाइआ", "o kutte noo dauraaiaa"],
        ["Let me speak", "मिगी बोलण दे", "migee bolan de"],
        ["I will make you see", "मैं तूँ वखावां", "main toon vakhaavaan"],
        ["They caused trouble", "ओ झगड़ा पैदा किता", "o jhagrraa paidaa kitaa"],
    ],
    539: [  # Gender–number agreement
        ["The boy went (masc. sing.)", "मुंडा गेआ", "mundaa geaa"],
        ["The girl went (fem. sing.)", "कुड़ी गई", "kuddee gaee"],
        ["The boys went (masc. pl.)", "मुंडे गे", "mundde ge"],
        ["The girls went (fem. pl.)", "कुड़ियां गइयां", "kuddeeaan gaiaan"],
        ["He is a good student", "ओ चंगा विद्यार्थी आए", "o changaa vidyaarthee aaey"],
        ["She is a good student", "ओ चंगी विद्यार्थिन आए", "o changee vidyaarthin aaey"],
        ["They (men) are teachers", "ओ मास्टर आए", "o maastar aaey"],
        ["They (women) are teachers", "ओ मास्टरनी आए", "o maastaranee aaey"],
        ["This boy reads", "ए मुंडा पढ़दा आए", "e mundaa padhdaa aaey"],
        ["This girl reads", "ए कुड़ी पढ़दी आए", "e kuddee padhdee aaey"],
        ["Those men work", "ओ आदमी कम करदे आए", "o aadmee kam karde aaey"],
        ["Those women work", "ओ औरतां कम करदियां आए", "o aurataan kam kardiaan aaey"],
        ["The lion roared", "शेर दहाड़ेआ", "sher dahaarr iaa"],
        ["The cow mooed", "गां रोंदी", "gaan rondee"],
        ["Many children play", "बहुत बच्चे खेड़दे आए", "bahut bacche khedde aaey"],
        ["One boy, two boys", "इक मुंडा, दो मुंडे", "ik mundaa, do mundde"],
        ["One girl, two girls", "इक कुड़ी, दो कुड़ियां", "ik kuddee, do kuddeeaan"],
        ["He speaks politely", "ओ नम्रता कोल बोलदा आए", "o namrata kol boldaa aaey"],
        ["They (mixed) left", "ओ चले गे", "o chale ge"],
        ["Elder speaks (respect)", "बुज्जुर्ग बोलदे आए", "bujjurg bolde aaey"],
    ],
    540: [  # Perfect second style
        ["The work is done", "कम्म होइ चुकेआ", "kamm hoi chukeaa"],
        ["The letter has been sent", "चिट्ठी भेजी गई", "chitthee bhejee gaee"],
        ["Food has been cooked", "खाना बणाइआ गेआ", "khaanaa banaiaa geaa"],
        ["The house was built", "घर बणेआ गेआ", "ghar baneaa geaa"],
        ["He had been informed", "उसनू दस्सेआ गेआ", "usanoo dassiaa geaa"],
        ["The match had started", "मैच शुरू होइ चुकेआ सी", "maech shuroo hoi chukeaa see"],
        ["It has been decided", "फैसला होइ चुकेआ", "faislaa hoi chukeaa"],
        ["The bill was paid", "बिल दिता गेआ", "bill ditaa geaa"],
        ["The door was closed", "दरवाजा बंद किता गेआ", "daravaajaa band kitaa geaa"],
        ["The work will have been finished", "कम्म पूरा हो जावेगा", "kamm pooraa ho jaavegaa"],
        ["The news has spread", "खबर फैल गई", "khabar fail gaee"],
        ["He has been called", "उसनू बुलाइआ गेआ", "usanoo bulaiaa geaa"],
        ["She has been chosen", "उसनू चुणेआ गेआ", "usanoo chuneaa geaa"],
        ["We have been invited", "सानू बुलाइआ गेआ", "saanoo bulaiaa geaa"],
        ["The field has been ploughed", "खेत हल चुकेआ", "khet hal chukeaa"],
        ["The letter had been lost", "चिट्ठी गुम होइ चुकी सी", "chitthee gum hoi chukee see"],
        ["Money has been returned", "पैसे वापस किते गे", "paise vaapas kite ge"],
        ["The problem was solved", "मसला हल होइ गेआ", "maslaa hal hoi geaa"],
        ["The book has been found", "किताब लब्भी गई", "kitaab labbhee gaee"],
        ["The rule has been changed", "नियम बदलेआ गेआ", "niyam badaleaa geaa"],
    ],
    541: [  # Perfect continuous
        ["I have been reading since morning", "मैं सवेरे कोल पढ़दा आं", "main savere kol padhdaa aan"],
        ["He has been working for hours", "ओ घंटे कोल कम करदा आए", "o ghante kol kam kardaa aaey"],
        ["She has been waiting long", "ओ बड़ी देर कोल इंतजार करदी आए", "o badee der kol intazaar kardee aaey"],
        ["We have been living here for years", "असी सालां कोल इत्थे रेंदे आं", "asi saalaan kol itthe rende aan"],
        ["They have been playing all day", "ओ सारा दिन खेड़दे आए", "o saaraa din khedde aaey"],
        ["It had been raining", "मींह पैंदा सी", "meenh paindaa see"],
        ["I had been studying before you came", "तू आने पैह्लें मैं पढ़दा सी", "tu aane paihlen main padhdaa see"],
        ["He had been ill", "ओ बिमार सी", "o bimaar see"],
        ["She had been singing", "ओ गांदी सी", "o gaandee see"],
        ["We had been walking", "असी चलदे सां", "asi chalde saan"],
        ["They had been building the road", "ओ सड़क बनांदे सान", "o sarrak banaande saan"],
        ["How long have you been here?", "तू इत्थे कन्ने वेले कोल आए?", "tu itthe kanne vele kol aaey?"],
        ["I have not been sleeping well", "मैं चंगी नींद नेईं सुतदा", "main changee neend nein sutdaa"],
        ["He has been absent", "ओ गैर हाज़िर आए", "o gair haazir aaey"],
        ["She has been teaching here", "ओ इत्थे पढ़ांदी आए", "o itthe padhaandee aaey"],
        ["We have been trying hard", "असी मेहनत करदे आं", "asi mehnat karde aan"],
        ["They have been friends for long", "ओ लम्बे वेले कोल दोस्त आए", "o lambe vele kol dost aaey"],
        ["The baby has been crying", "नन्हा रोंदा आए", "nanhaa rondaa aaey"],
        ["I will have been working ten years", "मैं दस साल कोल कम करदा रहूंगा", "main das saal kol kam kardaa rahungaa"],
        ["By then she will have been studying", "उस वेले ओ पढ़दी रहुगी", "us vele o padhee rahugee"],
    ],
    542: [  # no/not vs don't want
        ["I do not eat (simple negation)", "मैं नेईं खांदा", "main nein khaandaa"],
        ["I do not want to eat", "मैं खाणा नेईं चांदा", "main khaanaa nein chaandaa"],
        ["He is not here", "ओ इत्थे नेईं", "o itthe nein"],
        ["He does not want to go", "ओ जाणा नेईं चांदा", "o jaanaa nein chaandaa"],
        ["There is no sugar", "चीनी नेईं आए", "cheenee nein aaey"],
        ["I don't want sugar", "मिगी चीनी चाइदी नेईं", "migee cheenee chaidee nein"],
        ["She did not come", "ओ नेईं आई", "o nein aaee"],
        ["She did not want to come", "ओ आणा नेईं चांदी सी", "o aanaa nein chaandee see"],
        ["We will not buy it", "असी ए नेईं खरीदांगे", "asi e nein khareedaange"],
        ["We don't want to buy it", "असी खरीदणा नेईं चांदे", "asi khareednaa nein chaande"],
        ["No, that is wrong", "ना, ए गलत आए", "naa, e galat aaey"],
        ["I need not go", "मिगी जाणे दी लोड़ नेईं", "migee jaane dee lor nein"],
        ["I refuse / I don't want", "मैं नेईं चांदा", "main nein chaandaa"],
        ["He has no fear", "उदा डर नेईं", "udaa dar nein"],
        ["He doesn't want to try", "ओ कोशिश नेईं करना चांदा", "o koshish nein karnaa chaandaa"],
        ["Don't! (prohibition)", "नेईं कर!", "nein kar!"],
        ["Please don't", "मेहरबानी करियै नेईं", "meharbaanee kariyai nein"],
        ["I am not hungry", "मिगी भूख नेईं", "migee bhookh nein"],
        ["I don't feel like eating", "मिगी खाणे दा मन नेईं", "migee khaane daa man nein"],
        ["They said no", "ओ ना बोल्ले", "o naa bolle"],
    ],
}
