# Dogri Lesson 3 — chunk B (chapter IDs 566–596).

LESSONS_S3B = {
    566: [
        ["I want him to study", "मैं चांदा आं ओ पढ़े", "main chaandaa aan o padhe"],
        ["She wants us to wait", "ओ चांदी आए असी इंतज़ार करिए", "o chaandee aaey asi intazaar karie"],
        ["They want me to sing", "ओ चांदे आए मैं गावां", "o chaande aan main gaavaan"],
        ["We want you to be careful", "असी चांदे आं तुस सावधान रहो", "asi chaande aan tus saavadhaan raho"],
        ["He wants his son to work hard", "ओ चांदा आए ओदा मुंडा मेहनत करे", "o chaandaa aaey odaa mundaa mehnat kare"],
        ["Mother wants me to marry", "माँ चांदी आए मैं व्या करां", "maa chaandee aan main vyaa karaan"],
        ["I don't want them to fight", "मैं नेईं चांदा ओ लड़न", "main nein chaandaa o ladan"],
        ["The teacher wants students to be quiet", "मास्टर चांदा आए बच्चे चुप रहन", "maastar chaandaa aan bacche chup rahan"],
        ["She wants the doctor to come", "ओ चांदी आए डाक्टर आवे", "o chaandee aaey daaktar aave"],
        ["I want you to understand", "मैं चांदा आं तुस समझो", "main chaandaa aan tus samjho"],
        ["We want the government to help", "असी चांदे आं सरकार मदद करे", "asi chaande aan sarkaar madad kare"],
        ["He wants his friend to leave", "ओ चांदा आए ओदा दोस्त चले जावे", "o chaandaa aaey odaa dost chale jaave"],
        ["Do you want me to call?", "की तुस चांदे हो मैं फोन करां?", "kee tus chaande ho main fon karaan?"],
        ["I want her to feel safe", "मैं चांदा आए ओ सुरक्षित महसूस करे", "main chaandaa aaey o surakshit mahasoos kare"],
        ["Parents want children to study", "मां-बाप चांदे आए बच्चे पढ़न", "maan-baap chaande aan bacche padhan"],
        ["She wants everyone to be happy", "ओ चांदी आए सब खुश रहन", "o chaandee aan sab khush rahan"],
    ],
    567: [
        ["I am supposed to reach by nine", "मिगी नौ वजे पैह्लें पैह् जाणा आए", "migee nau vaje paihlen paih jaanaa aaey"],
        ["You are supposed to wear uniform", "तुस यूनिफॉर्म पाना चाहीदा आए", "tus yooniform paanaa chaahidaa aaey"],
        ["He is supposed to pay today", "ओने आज भरना चाहीदा आए", "one aaj bharnaa chaahidaa aaey"],
        ["We are supposed to attend the meeting", "सानू मीटिंग च आणा चाहीदा आए", "saanoo meeting ch aanaa chaahidaa aaey"],
        ["The train is supposed to arrive now", "ट्रेन हुन आणी चाहीदी आए", "train hun aanee chaahidee aaey"],
        ["I was supposed to call yesterday", "मिगी कल फोन करना सी", "migee kal fon karnaa see"],
        ["Students are supposed to bring books", "विद्यार्थियां नू किताबां लेआणी चाहीदी आए", "vidyaarthiyaan noon kitaabaan leaanee chaahidee aaey"],
        ["She is supposed to rest", "ओने आराम करना चाहीदा आए", "one aaraam karnaa chaahidaa aaey"],
        ["You were supposed to inform me", "तुसें मिगी दस्सना सी", "tasen migee dassanaa see"],
        ["The shop is supposed to open at ten", "दुकान दस वजे खुलनी चाहीदी आए", "dukaan das vaje khulanee chaahidee aaey"],
        ["I am not supposed to tell anyone", "मिगी किसे नेईं दस्सना", "migee kise nein dassanaa"],
        ["They are supposed to report early", "ओने जल्दी रिपोर्ट करनी चाहीदी आए", "one jaldee riport karnee chaahidee aaey"],
        ["What am I supposed to do?", "मिगी की करना चाहीदा आए?", "migee kee karnaa chaahidaa aaey?"],
        ["The medicine is supposed to work fast", "दवाई जल्दी असर करनी चाहीदी आए", "davaaee jaldee asar karnee chaahidee aaey"],
        ["We were supposed to meet at six", "सानू छे वजे मिलना सी", "saanoo che vaje milanaa see"],
        ["He is supposed to be the chief guest", "ओ मुख्य मेहमान होना चाहीदा आए", "o mukhy mehmaan honaa chaahidaa aaey"],
    ],
    568: [
        ["I like to walk in the rain", "मिगी मींह च टहल पसंद आए", "migee meenh ch tahal pasand aaey"],
        ["She likes to read before sleep", "ओने सौण कोलों पढ़ना पसंद आए", "one saun kolon padhanaa pasand aaey"],
        ["We like to eat together", "सानू इकठ्ठे खाणा पसंद आए", "saanoo ikatthe khaanaa pasand aaey"],
        ["He doesn't like to wait", "ओ इंतज़ार करना पसंद नेईं करदा", "o intazaar karnaa pasand nein kardaa"],
        ["Children like to ask questions", "बच्चेयां नू सवाल पुछना पसंद आए", "baccheyaan noon savaal puchhanaa pasand aaey"],
        ["I would like to visit your village", "मिगी तुसां दा पेंड घूमणा पसंद आए", "migee tusaan daa pend ghoomanaa pasand aaey"],
        ["She likes to help in the kitchen", "ओने रसोई च मदद करना पसंद आए", "one rasoee ch madad karnaa pasand aaey"],
        ["Do you like to sing?", "की तुस गाणा पसंद करदे हो?", "kee tus gaanaa pasand karde ho?"],
        ["We like to watch news", "सानू खबरां वेखना पसंद आए", "saanoo khbaraan vekhanaa pasand aaey"],
        ["He likes to fix old things", "ओ पुराणी चीज़ां ठीक करना पसंद करदा आए", "o puraanee cheezaan theek karnaa pasand kardaa aaey"],
        ["I don't like to argue", "मिगी बहस करना पसंद नेईं", "migee behas karnaa pasand nein"],
        ["They like to travel by train", "ओने ट्रेन च सफर करना पसंद आए", "one train ch safar karnaa pasand aaey"],
        ["Grandmother likes to tell stories", "दादी कहाणी सुनोंना पसंद करदी आए", "daadee kahaanee sunonaa pasand kardee aaey"],
        ["I like to drink hot milk", "मिगी गरम दुद्ध पीणा पसंद आए", "migee garam duddh peenaa pasand aaey"],
        ["She likes to dress neatly", "ओने सफाई कोल कपड़े पाना पसंद आए", "one safaee kol kapde paanaa pasand aaey"],
        ["We like to celebrate festivals", "सानू त्योहार मनोंना पसंद आए", "saanoo tyauhaar manonaa pasand aaey"],
    ],
    569: [
        ["I listen to the radio", "मैं रेडियो सुनदा आं", "main rediyo sunadaa aan"],
        ["She looks at the moon", "ओ चंद्रमा वल वेखदी आए", "o chandramaa val vekhdee aaey"],
        ["We agree to the plan", "असी योजना कोल सहमत आं", "asi yojanaa kol sahamat aan"],
        ["He replied to the letter", "ओने चिट्ठी दा जवाब दिता", "one chitthee daa jawaab ditaa"],
        ["They objected to the rule", "ओने नियम कोल इतराज़ कीता", "one niyam kol itaraaz keetaa"],
        ["I belong to this village", "मैं ए पेंड दा आं", "main e pend daa aan"],
        ["She listens to her teacher", "ओ मास्टर दी गल सुनदी आए", "o maastar dee gal sunadee aaey"],
        ["We pray to God every day", "असी हर रोज रब कोल प्रार्थना करदे आं", "asi har roz rab kol praarthanaa karde aan"],
        ["He shouted to the crowd", "ओ भीड़ कोल चिल्लाया", "o bheer kol chillaayaa"],
        ["I wrote to my brother", "मैं अपने प्रा नू चिट्ठी लिखी", "main apne praa noon chitthee likhee"],
        ["She waved to the children", "ओने बच्चेयां नू हाथ हलाया", "one baccheyaan noon haath halaayaa"],
        ["We bow to elders", "असी बुज्जुर्गां नू निवांदे आं", "asi bujjurgaan noon nivaande aan"],
        ["He pointed to the map", "ओने नक्शे वल इशारा कीता", "one nakshe val ishaaraa keetaa"],
        ["I explained to the guests", "मैं मेहमानां नू समझाया", "main mehmaanaan noon samjhaayaa"],
        ["They clapped for the singer", "ओने गायक लई ताड़ियां मारियां", "one gaayak lai taarriyaan maariyaan"],
        ["She smiled at the baby", "ओने बच्चे उत्ते मुस्कराया", "one bacche ute muskaraayaa"],
    ],
    570: [
        ["I am fine (spoken short)", "मैं ठीक आं", "main theek aan"],
        ["What happened? (casual)", "की भया?", "kee bhayaa?"],
        ["Come here (informal)", "इत्थे आ", "itthe aa"],
        ["I don't know (short)", "पता नेईं", "pata nein"],
        ["Okay / yes (casual)", "ठीक आ / हाँ", "theek aa / haan"],
        ["Where are you going?", "कुथे जांदे?", "kuthe jaande?"],
        ["See you later", "फेर मिलांगे", "pher milaange"],
        ["No problem", "कोई गल नेईं", "koee gal nein"],
        ["Hurry up", "जल्दी कर", "jaldee kar"],
        ["Leave it (don't bother)", "छड़ दे", "chhad de"],
        ["Really? (surprise)", "सच्ची?", "sachchee?"],
        ["I will come (short promise)", "आ जामां", "aa jaamaan"],
        ["Don't worry", "फिकर ना कर", "fikar na kar"],
        ["That's enough", "बस एन्ना ही", "bas ennaa hi"],
        ["Who knows? (shrug)", "कौन जाने?", "kaun jaane?"],
        ["Same to you (reply)", "तुसां नू वी", "tusaan noon vee"],
    ],
    571: [
        ["Good morning", "सुप्रभात / सत श्री अकाल", "suprabhaat / sat sree akaal"],
        ["Good evening", "शुभ संध्या", "shubh sandhyaa"],
        ["Namaste / respectful greeting", "नमस्कार / जी आयां नूं", "namaskaar / ji aayaan noon"],
        ["Happy birthday", "जन्म दिन दियां बधाइयां", "janm din diyaan badhaaiyaan"],
        ["Happy New Year", "नवें साल दियां बधाइयां", "naven saal diyaan badhaaiyaan"],
        ["Congratulations", "मुबारकां", "mubaarakaan"],
        ["Get well soon", "जल्दी ठीक हो जाओ", "jaldee theek ho jaao"],
        ["May God bless you", "रब रखे तुसां नू", "rab rakhe tusaan noon"],
        ["Long live (toast)", "जिंदाबाद", "zindaabaad"],
        ["Welcome", "स्वागत आए", "swaagat aaey"],
        ["Goodbye / go safely", "रब रखा / फिर मिलांगे", "rab rakhaa / phir milaange"],
        ["Happy Diwali", "दिवाली दियां बधाइयां", "divaalee diyaan badhaaiyaan"],
        ["Happy festival", "त्योहार दियां बधाइयां", "tyauhaar diyaan badhaaiyaan"],
        ["May you prosper", "चढ़दी कला च रहो", "chhaddee kalaa ch raho"],
        ["Thank you very much", "बहुत धन्नवाद", "bahut dhannavaad"],
        ["With your permission (leave)", "जी आयां नूं", "ji aayaan noon"],
    ],
    572: [
        ["I will eat and leave", "मैं खा के चल जामां", "main khaa ke chal jaamaan"],
        ["Sit down and rest", "बैठ के आराम करो", "baith ke aaraam karo"],
        ["He stood up and spoke", "ओ खड़ा हो के बोल्या", "o khadaa ho ke bolyaa"],
        ["Come and see", "आ के वेखो", "aa ke vekho"],
        ["She cried and slept", "ओ रोई के सौई", "o roee ke saui"],
        ["We read and discussed", "असी पढ़ के गल्ल कीती", "asi padh ke gall keetee"],
        ["Open the door and enter", "दरवाजा खोल के अंदर आओ", "daravaajaa khol ke andar aao"],
        ["Think and answer", "सोच के जवाब देओ", "soch ke jawaab deo"],
        ["Finish work and go home", "कम मुक्का के घर जाओ", "kam mukkaa ke ghar jaao"],
        ["Wash hands and eat", "हथ धो के खाओ", "hath dho ke khaao"],
        ["He ran and caught the bus", "ओ दौड़ के बस फड़ी", "o daur ke bas faddee"],
        ["Listen carefully and write", "ध्यान कोल सुनो अते लिखो", "dhyaan kol suno ate likho"],
        ["She smiled and nodded", "ओ मुस्कराई के सिर हलाया", "o muskuraai ke sir halaayaa"],
        ["We met and planned", "असी मिल के योजना बनाई", "asi mil ke yojanaa banaaee"],
        ["Pack the bag and leave", "बैग पैक कर के चलो", "baeg paik kar ke chalo"],
        ["Call me and confirm", "मिगी फोन कर के पक्का करो", "migee fon kar ke pakkaa karo"],
    ],
    573: [
        ["Brother (to a boy)", "प्रा / भैया", "praa / bhaiyaa"],
        ["Sister (to a girl)", "बहण / दीदी", "bahan / deedee"],
        ["Uncle (father's brother)", "चाचा", "chaachaa"],
        ["Aunt", "चाची", "chaachee"],
        ["Grandfather", "दादा", "daadaa"],
        ["Grandmother", "दादी", "daadee"],
        ["Respected sir (to elder man)", "बुज्जुर्ग / जी", "bujjurg / jee"],
        ["Listen, friend (informal)", "सुन भाई", "sun bhaai"],
        ["Son", "पुत", "put"],
        ["Daughter", "धी", "dhee"],
        ["Calling a stranger politely", "भाई साहब / बहन जी", "bhaai saahab / bhan jee"],
        ["Hey there (very informal)", "ऐ सुन", "ai sun"],
        ["Respected teacher", "मास्टर जी", "maastar jee"],
        ["Doctor (address)", "डाक्टर साहब", "daaktar saahab"],
        ["Calling the waiter", "भैया, इत्थे आओ", "bhaiyaa, itthe aao"],
        ["Young man", "मुंडा / लड़का", "mundaa / larkaa"],
    ],
    574: [
        ["Oh! What a surprise!", "ओह! की सरप्राइज़!", "oh! kee sarapraiz!"],
        ["Alas! He is gone", "हाय! ओ चल गया", "haai! o chal gayaa"],
        ["Wow! Beautiful!", "वाह! सोणा!", "vaah! sonaa!"],
        ["Ouch! It hurts", "ऐ! दुखदा आए!", "ai! dukhdaa aaey!"],
        ["Hey! Stop!", "ऐ! रुको!", "ai! ruko!"],
        ["Bravo! Well done", "शाबाश! चंगा कीता", "shaabaash! changaa keetaa"],
        ["What nonsense!", "की बकवास!", "kee bakavaas!"],
        ["Thank heavens!", "रब दा लख लख शुकर!", "rab daa lakh lakh shukar!"],
        ["How sad!", "की दुख!", "kee dukh!"],
        ["So sweet!", "किन्ना मिठा!", "kinaa mitthaa!"],
        ["What a noise!", "किन्ना शोर!", "kinaa shor!"],
        ["Impossible!", "नामुमकिन!", "naamumkin!"],
        ["God forbid!", "रब ना करे!", "rab na kare!"],
        ["Hurry!", "जल्दी!", "jaldee!"],
        ["Silence!", "चुप!", "chup!"],
        ["Look out!", "सावधान!", "saavadhaan!"],
    ],
    575: [
        ["May I come in?", "की मैं अंदर आ सकदा आं?", "kee main andar aa sakdaa aan?"],
        ["Can you help me?", "की तुस मेरी मदद कर सकदे हो?", "kee tus meree madad kar sakde ho?"],
        ["Could you pass the salt?", "की तुस नमक दे सकदे हो?", "kee tus namak de sakde ho?"],
        ["Would you please sit?", "किरपा करियै बैठो", "kirpaa kariyai baitho"],
        ["May I use your phone?", "की मैं तुसां दा फोन वरत सकदा आं?", "kee main tusaan daa fon varat sakdaa aan?"],
        ["Can you repeat that?", "की तुस ए दोहरा सकदे हो?", "kee tus e dohraa sakde ho?"],
        ["Would you mind waiting?", "की तुस इंतज़ार करोगे?", "kee tus intazaar karoge?"],
        ["May I ask a question?", "की मैं सवाल पुछ सकदा आं?", "kee main savaal puchh sakdaa aan?"],
        ["Can you show the way?", "की तुस रस्ता दिखा सकदे हो?", "kee tus rastaa dikhaa sakde ho?"],
        ["Could you speak slowly?", "की तुस हौले बोल सकदे हो?", "kee tus haule bol sakde ho?"],
        ["May I take this seat?", "की मैं ए सीट लै सकदा आं?", "kee main e seet lai sakdaa aan?"],
        ["Can you call a taxi?", "की तुस टैक्सी बुला सकदे हो?", "kee tus taiksee bulaa sakde ho?"],
        ["Would you like some tea?", "की तुसां चा लेओगे?", "kee tusaan chaa leoge?"],
        ["May I leave early today?", "की मैं आज जल्दी जा सकदा आं?", "kee main aaj jaldee jaa sakdaa aan?"],
        ["Can you read this for me?", "की तुस ए मेरे लई पढ़ सकदे हो?", "kee tus e mere lai padh sakde ho?"],
        ["Could you keep my bag?", "की तुस मेरा बैग रख सकदे हो?", "kee tus meraa baeg rakh sakde ho?"],
    ],
    576: [
        ["It might rain tomorrow", "कल मींह पै सकदा आए", "kal meenh pai sakdaa aaey"],
        ["He may come late", "ओ देर कोल आ सकदा आए", "o der kol aa sakdaa aaey"],
        ["We might take the bus", "असी बस लै सकदे आं", "asi bas lai sakde aan"],
        ["She might not agree", "ओ नेईं मान सकदी", "o nein maan sakdee"],
        ["It may be true", "ए सच हो सकदा आए", "e sach ho sakdaa aaey"],
        ["I might forget; remind me", "मैं भुल सकदा आं; याद कराइयो", "main bhul sakdaa aan; yaad karaaiyo"],
        ["The keys might be inside", "चाबी अंदर हो सकदी आए", "chaabee andar ho sakdee aaey"],
        ["They might have left", "ओ चले गे होन", "o chale ge hon"],
        ["This might help", "ए मदद हो सकदा आए", "e madad ho sakdaa aaey"],
        ["You might feel tired", "तुस थके महसूस कर सकदे हो", "tus thake mahasoos kar sakde ho"],
        ["The shop might be closed", "दुकान बंद हो सकदी आए", "dukaan band ho sakdee aaey"],
        ["We might visit next week", "असी अगले हफ्ते आ सकदे आं", "asi agale hafte aa sakde aan"],
        ["He might call tonight", "ओ आज रात फोन कर सकदा आए", "o aaj raat fon kar sakdaa aaey"],
        ["It might snow in winter", "सर्दी च बर्फ पै सकदी आए", "sardee ch baraf pai sakdee aaey"],
        ["She might know the answer", "ओने जवाब पता हो सकदा आए", "one jawaab pata ho sakdaa aaey"],
        ["I might stay home", "मैं घरे रै सकदा आं", "main ghare rai sakdaa aan"],
    ],
    577: [
        ["a written letter", "लिखी होई चिट्ठी", "likhee hoee chitthee"],
        ["boiled water", "उबला पाणी", "ubalaa paanee"],
        ["fried bread", "तली होई रोटी", "talee hoee rotee"],
        ["broken chair", "टूटी कुर्सी", "toottee kursee"],
        ["closed door", "बंद दरवाजा", "band daravaajaa"],
        ["open window", "खुला खिड़की", "khulaa khidakee"],
        ["lost keys", "गुम चाबी", "gum chaabee"],
        ["tired traveller", "थका यात्री", "thakaa yaatree"],
        ["cooked food", "बनाया खाना", "banaayaa khaanaa"],
        ["washed clothes", "धोए कपड़े", "dhoe kapde"],
        ["painted wall", "रंग कीती दीवार", "rang keetee deevaar"],
        ["signed form", "साइन कीता फॉर्म", "saain keetaa form"],
        ["packed bag", "पैक कीता बैग", "paik keetaa baeg"],
        ["frozen water", "जमया पाणी", "jamayaa paanee"],
        ["roasted nuts", "भुने मेवे", "bhune meve"],
        ["printed book", "छपी किताब", "chhapee kitaab"],
    ],
    578: [
        ["the boy inside the house", "घर अंदर दा मुंडा", "ghar andar daa mundaa"],
        ["the shop near the bridge", "पुल कोल दी दुकान", "pul kol dee dukaan"],
        ["people from the village", "पेंड कोलों लोक", "pend kolon lok"],
        ["the road to Jammu", "जम्मू वल दा रस्ता", "jammu val daa rastaa"],
        ["trees along the river", "नदी कोल दे रुख", "nadee kol de rukh"],
        ["the cat under the bed", "बिस्तरे हेठ दी बिल्ली", "bistare heth dee billee"],
        ["the book on the table", "मेज उत्ते दी किताब", "mej ute dee kitaab"],
        ["friends behind us", "साडे पिछे दे दोस्त", "saade pichhe de dost"],
        ["the school opposite the park", "पार्क सामने दा सकूल", "paark saamne daa sakool"],
        ["water in the pot", "बर्तन च पाणी", "bartan ch paanee"],
        ["the man before me", "मिगे अगले दा आदमी", "mige agle daa aadamee"],
        ["children between the rows", "लाइना च बच्चे", "lainaa ch bacche"],
        ["the field beyond the hill", "पहाड़ पार दा खेत", "pahaad paar daa khet"],
        ["money in the pocket", "जेब च पैसे", "jeb ch paise"],
        ["stars above the roof", "छत उत्ते दे तारे", "chat ute de taare"],
        ["the first house after the turn", "मोड़ बाद दा पैह्ला घर", "mor baad daa paihlaa ghar"],
    ],
    579: [
        ["May you live long", "तुसां दी उम्र लंबी होवे", "tusaan dee umr lambee hove"],
        ["May God protect you", "रब तुसां दी रख्या करे", "rab tusaan dee rakhyaa kare"],
        ["May peace prevail", "सुकून कायम रहे", "sukoon kaayam rahe"],
        ["May your wishes come true", "तुसां दियां मुरादां पूरी होन", "tusaan diyaan muraadaan pooree hon"],
        ["May the festival bring joy", "त्योहार खुशियां ले आवे", "tyauhaar khushiyaan le aave"],
        ["May you succeed", "तुस कामयाब होवो", "tus kaamayaab hovo"],
        ["May there be rain for farmers", "किसानां लई मींह पवे", "kisaanaan lai meenh pave"],
        ["May the sick recover soon", "बिमार जल्दी ठीक होन", "bimaar jaldee theek hon"],
        ["May our friendship last", "साडी दोस्ती कायम रहे", "saadee dostee kaayam rahe"],
        ["May no one go hungry", "कोई भुखा ना रहे", "koee bhukhaa na rahe"],
        ["May the children study well", "बच्चे चंगा पढ़न", "bacche changaa padhan"],
        ["May the journey be safe", "सफर सुरक्षित रहे", "safar surakshit rahe"],
        ["May your family be happy", "तुसां दा परिवार खुश रहे", "tusaan daa parivaar khush rahe"],
        ["May truth win", "सच जिते", "sach jite"],
        ["May we meet again", "फेर मिलांगे", "pher milaange"],
        ["May this house prosper", "ए घर चढ़दी कला च रहे", "e ghar chhaddee kalaa ch rahe"],
    ],
    580: [
        ["Mother made the child sleep", "माँ ने बच्चे नू सुलाया", "maan ne bacche noon sulaaayaa"],
        ["He got the car repaired", "ओने गड्डी ठीक कराई", "one gaddee theek karaaee"],
        ["She had him write the letter", "ओने ओने चिट्ठी लिखवाई", "one one chitthee likhwaayaa"],
        ["I will get the room painted", "मैं कमरा रंग देआंगा", "main kamraa rang deaanga"],
        ["They made us wait", "ओने असें इंतज़ार करवाया", "one asen intazaar karvaayaa"],
        ["The teacher made students read aloud", "मास्टर ने बच्चेयां कोल जोर कोल पढ़वाया", "maastar ne baccheyaan kol zor kol padhvaayaa"],
        ["Get this work done", "ए कम करवाओ", "e kam karvaao"],
        ["She had the food cooked", "ओने खाना बणवाया", "one khaanaa banvaayaa"],
        ["He made the dog run away", "ओने कुत्ते नू भजाया", "one kutte noon bhajaayaa"],
        ["I can't make him understand", "मैं ओने समझा नेईं सकदा", "main one samjhaa nein sakdaa"],
        ["We will get a new gate made", "असी नवा गेट बणवामांगे", "asi navaa get banvaamaange"],
        ["The boss got the report typed", "बॉस ने रिपोट टाइप करवाई", "bos ne ripot taip karaaee"],
        ["She makes everyone laugh", "ओ सबनू हसोंदी आए", "o sab noon hasondee aaey"],
        ["Don't make the baby cry", "बच्चे नू ना रुलाओ", "bacche noon na rulaa"],
        ["He got his hair cut", "ओने बाल कटवाए", "one baal kutvaae"],
        ["They made him the leader", "ओने ओने मुखिया बणाया", "one one mukhiya banaayaa"],
    ],
    581: [
        ["Someone is at the door", "कोई दरवाजे उत्ते आए", "koee daravaaje ute aaey"],
        ["I left something in the room", "मैं कमरे च कुछ छड़या", "main kamre ch kuchh chhadyaa"],
        ["Nothing is impossible", "कुछ नेईं नामुमकिन", "kuchh nein naamumkin"],
        ["Anyone can try", "कोई भी कोशिश कर सकदा आए", "koee bhee koshish kar sakdaa aaey"],
        ["Somewhere in the city", "शहर च किते", "shehar ch kite"],
        ["Somehow we managed", "किसे ना किसे असी निबटे", "kise na kise asi nibate"],
        ["Everybody was happy", "सब खुश सं", "sab khush san"],
        ["Nowhere is safe without care", "बिना सावधानी कोई थांह् सुरक्षित नेईं", "binaa saavadhaanee koee thaanh surakshit nein"],
        ["Anything can happen", "कुछ भी हो सकदा आए", "kuchh bhee ho sakdaa aaey"],
        ["Someone called you", "किसे ने तुसां फोन कीता", "kise ne tusaan fon keetaa"],
        ["I need something to eat", "मिगी खाण लई कुछ चाहिदा आए", "migee khaan lai kuchh chaahidaa aaey"],
        ["Nobody came", "कोई नेईं आया", "koee nein aayaa"],
        ["Everywhere was decorated", "हर थांह् सजी होई सी", "har thaanh sajee hoee see"],
        ["Sometimes I feel tired", "कदे-कदे मैं थका महसूस करदा आं", "kade-kade main thakaa mahasoos kardaa aan"],
        ["Is there anywhere to sit?", "की बैठने लई किते थांह् आए?", "kee baithne lai kite thaanh aaey?"],
        ["Use anything you need", "जो चाहीदा वरतो", "jo chaahidaa varato"],
    ],
    582: [
        ["I have two brothers", "मेरे दो प्रा आए", "mere do praa aaey"],
        ["She has a fever", "ओने बुखार आए", "one bukhaar aaey"],
        ["We have a small house", "साडा छोटा घर आए", "saadaa chhottaa ghar aaey"],
        ["He has no money today", "ओदे कोल आज पैसे नेईं", "ode kol aaj paise nein"],
        ["Do you have children?", "की तुसां बच्चे आए?", "kee tusaan bacche aaey?"],
        ["I have an idea", "मेरे कोल इक विचार आए", "mere kol ik vichaar aaey"],
        ["The tree has many branches", "रुख कोल बड़े टूट आए", "rukh kol bare toot aaey"],
        ["She has long hair", "ओदे लंबे बाल आए", "ode lambe baal aaey"],
        ["We have time until evening", "सानू शाम तक समें आए", "saanoo shaam tak samen aaey"],
        ["He has a kind heart", "ओदा दिल नेक आए", "odaa dil nek aaey"],
        ["I have nothing to say", "मेरे कोल कुछ बोलने नेईं", "mere kol kuchh bolne nein"],
        ["They have three cars", "ओदे तिन गड्डियां आए", "ode tin gaddiyaan aaey"],
        ["The bag has a hole", "बैग च छेद आए", "baeg ch chhed aaey"],
        ["I have relatives in Delhi", "मेरे दिल्ली च रिश्तेदार आए", "mere dillee ch rishtedaar aaey"],
        ["She has courage", "ओदे हिम्मत आए", "ode himmat aaey"],
        ["We have faith in God", "सानू रब पर भरोसा आए", "saanoo rab par bharosaa aaey"],
    ],
    583: [
        ["What does this word mean?", "ए शब्द दा की मतलब आए?", "e shabd daa kee matalab aaey?"],
        ["I don't understand the meaning", "मिगी मतलब नेईं समझ आया", "migee matalab nein samajh aayaa"],
        ["This sentence means peace", "ए वाक शांति दा मतलब आए", "e vaak shaanti daa matalab aaey"],
        ["What do you mean?", "तुसां दा की मतलब आए?", "tusaan daa kee matalab aaey?"],
        ["I meant to help", "मेरा मतलब मदद करने दा सी", "meraa matalab madad karne daa see"],
        ["Words can mean different things", "शब्दां दे अलग-अलग मतलब हो सकदे आए", "shabdaan de alag-alag matalab ho sakde aaey"],
        ["Explain the meaning", "मतलब समझाओ", "matalab samjhaao"],
        ["That name means 'light'", "ओ नां दा मतलब 'उजाला' आए", "o naan daa matalab 'ujaalaa' aaey"],
        ["I didn't mean to hurt", "मेरा मतलब दुख देने दा नेईं सी", "meraa matalab dukh dene daa nein see"],
        ["What is meant by this sign?", "ए निशान दा की मतलब आए?", "e nishaan daa kee matalab aaey?"],
        ["The teacher explained the meaning", "मास्टर ने मतलब समझाया", "maastar ne matalab samjhaayaa"],
        ["Double meaning (joke)", "दो मतलब", "do matalab"],
        ["I know what you mean", "मैं तुसां दा मतलब जांदा आं", "main tusaan daa matalab jaandaa aan"],
        ["This proverb means hard work", "ए कहावत मेहनत दा मतलब आए", "e kahaavat mehnat daa matalab aaey"],
        ["Look up the meaning in a dictionary", "शब्दकोश च मतलब लब्भो", "shabdkosh ch matalab labbho"],
        ["His words meant danger", "ओदियां गल्लां दा मतलब खतरा सी", "odeeyaan gallaan daa matalab khataraa see"],
    ],
    584: [
        ["I came and he left", "मैं आया अते ओ चल गया", "main aayaa ate o chal gayaa"],
        ["But it is raining", "पर मींह पैंदा आए", "par meenh paindaa aaey"],
        ["Because I was ill", "क्योंकि मैं बिमार सी", "kyonki main bimaar see"],
        ["So we stayed home", "इस करके असी घरे रहे", "is karke asi ghare rahe"],
        ["He said that he will come", "ओने कहा ओ आवेगा", "one kahaa o aavegaa"],
        ["Although it was late, we went", "हालांकि देर होई गई सी, असी चले गे", "haalaankee der hoee gaee see, asi chale ge"],
        ["Though tired, she worked", "थकी होई पर ओ कम करदी रही", "thakee hoee par o kam kardee rahee"],
        ["Still I hope", "फिर वी मैं उम्मीद करदा आं", "phir vee main ummeed kardaa aan"],
        ["Yet nobody came", "पर कोई नेईं आया", "par koee nein aayaa"],
        ["Bread and butter", "रोटी अते मक्खन", "rotee ate makkhan"],
        ["Slow but steady", "हौले पर लगातार", "haule par lagaataar"],
        ["Because of rain the match stopped", "मींह करके मैच रुक गया", "meenh karke maich ruk gayaa"],
        ["So that children may learn", "तां जे बच्चे सिखन", "taan je bacche sikhan"],
        ["I think that it is true", "मैं सोचदा आां ओ सच आए", "main sochdaa aan o sach aaey"],
        ["He ran but missed the bus", "ओ दौड़्या पर बस छूट गई", "o daurhyaa par bas chhoot gaee"],
        ["Although old, he is active", "बुज्जुर्ग होई पर ओ सक्रिय आए", "bujjurg hoee par o sakriy aaey"],
    ],
    585: [
        ["As you wish", "जियां तुस चाहो", "jiyaan tus chaho"],
        ["Tea or coffee?", "चा जां कॉफी?", "chaa jaan coffee?"],
        ["Neither he nor she came", "ना ओ आया ना ओ आई", "na o aayaa na o aaee"],
        ["I have neither time nor money", "मेरे कोल ना समें ना पैसे", "mere kol na samen na paise"],
        ["If it rains, we will stay", "जे मींह पवे त रहमां", "je meenh pave ta rahamaan"],
        ["In case you need help", "जे मदद चाहीदी होवे त", "je madad chaahidee hove ta"],
        ["Provided you agree", "जे तुस मान जाओ त", "je tus maan jaao ta"],
        ["Or else we cancel", "न त असी रद्द करदे आं", "na ta asi radd karde aan"],
        ["Neither this nor that", "ना ए ना ओ", "na e na o"],
        ["As I told you", "जियां मैं दस्स्या", "jiyaan main dassyaa"],
        ["Coffee or tea — your choice", "कॉफी जां चा — तुसां दी मर्ज़ी", "coffee jaan chaa — tusaan dee marzee"],
        ["If not today, then tomorrow", "आज नेईं त कल", "aaj nein ta kal"],
        ["Neither here nor there", "ना इत्थे ना उत्थे", "na itthe na utthe"],
        ["As long as you are honest", "जिन्ना च तुस ईमानदार हो", "jinnaa ch tus eemaanadaar ho"],
        ["In case of emergency call police", "इमरजेंसी च पुलिस नू फोन करो", "imarjensee ch police noon fon karo"],
        ["Either come or send word", "जां आओ जां संदेश भेजो", "jaan aao jaan sandesh bhejo"],
    ],
    586: [
        ["After dinner we walked", "रात दे खाने बाद असी टुरे", "raat de khaane baad asi ture"],
        ["Then he spoke", "फिर ओ बोल्या", "phir o bolyaa"],
        ["As far as I know", "मेरे जाणने कोलों", "mere jaanne kolon"],
        ["As long as you stay, I am happy", "जिन्ना च तुस रहो मैं खुश आं", "jinnaa ch tus raho main khush aan"],
        ["As if nothing happened", "जियां कुछ भया ही नेईं", "jiyaan kuchh bhayaa hi nein"],
        ["After the exam we rested", "परीक्षा बाद असी आराम कीता", "pareekshaa baad asi aaraam keetaa"],
        ["Then the bus arrived", "फिर बस आई", "phir bas aaee"],
        ["As far as the eye can see", "जिन्ना अख नींदी वेख सके", "jinnaa akh neendee vekh sake"],
        ["As long as there is life", "जिन्ना च जान आए", "jinnaa ch jaan aaey"],
        ["He looked as if he was afraid", "ओ डरया दिखदा सी जियां", "o daryaa dikhdaa see jiyaan"],
        ["After you finish, call me", "जदों मुक्के त फोन करियो", "jadon mukke ta fon kariyo"],
        ["Then we will decide", "फिर फैसला करांगे", "phir faislaa karaange"],
        ["As far as this matter goes", "इस मामले कोलों जिन्ना", "is maamale kolon jinnaa"],
        ["As long as it takes", "जिन्ना समें लगे", "jinnaa samen lage"],
        ["She acted as if she knew", "ओ जियां जांदी होई चाल चली", "o jiyaan jaandee hoee chaal chalee"],
        ["After the rain, the air was fresh", "मींह बाद हवा ताज़ा होई", "meenh baad havaa taazaa hoee"],
    ],
    587: [
        ["As soon as I reached, it rained", "मैं पैह् पैह् आया मींह पै गया", "main paih paih aayaa meenh pai gayaa"],
        ["Once you try, you will like it", "इक वार कोशिश करोगे त पसंद आ जागा", "ik vaar koshish karoge ta pasand aa jaagaa"],
        ["Rather than fight, talk", "लड़ने कोलों चंगा गल्ल करो", "ladne kolon changaa gall karo"],
        ["Instead of bus, take a train", "बस कोलों ट्रेन लेओ", "bas kolon train leo"],
        ["So that nobody gets hurt", "तां जे किसे चोट ना लगे", "taan je kise chot na lage"],
        ["As soon as the bell rang, class started", "घंटी बजदी ही क्लास शुरू होई", "ghantee bajdee hi klaas shuroo hoee"],
        ["Once I know, I will tell", "इक वार पता लगे त दस्सां", "ik vaar pata lage ta dassaan"],
        ["Rather than wait, go ahead", "इंतज़ार कोलों चंगा चलो", "intazaar kolon changaa chalo"],
        ["Instead of sugar, use jaggery", "चीनी कोलों गुड़ वरतो", "cheenee kolon gud varato"],
        ["Study so that you pass", "पढ़ो तां जे पास होवो", "padho taan je paas hovo"],
        ["As soon as he saw me, he smiled", "ओने मिगी वेखदी ही मुस्कराया", "one migee vekhdee hi muskaraayaa"],
        ["Once the sun sets, come back", "सूरज डुबदी ही मुड़ आओ", "sooraj dubdee hi mud aao"],
        ["Rather than blame, help", "दोष लोंदे कोलों मदद करो", "dosh londe kolon madad karo"],
        ["Instead of here, meet there", "इत्थे कोलों उत्थे मिलो", "itthe kolon utthe milo"],
        ["Speak clearly so that all understand", "साफ बोलो तां जे सब समझन", "saaf bol taan je sab samajhan"],
        ["As soon as possible", "जिन्ना जल्दी हो सके", "jinnaa jaldee ho sake"],
    ],
    588: [
        ["Conjunction 'and' — bread and milk", "रोटी अते दुद्ध", "rotee ate duddh"],
        ["Conjunction 'but' — small but strong", "छोटा पर मजबूत", "chhottaa par majboot"],
        ["Because — late because of traffic", "ट्रैफिक करके देर", "traifik karke der"],
        ["So — tired, so I rested", "थका इस करके आराम कीता", "thakaa is karke aaraam keetaa"],
        ["That — I think that it is true", "मैं सोचदा आां ओ सच आए", "main sochdaa aan o sach aaey"],
        ["Although — old, still active", "हालांकि बुज्जुर्ग, फिर वी सक्रिय", "haalaankee bujjurg, phir vee sakriy"],
        ["Though — difficult, try", "भले अखा, कोशिश कर", "bhale akhaa, koshish kar"],
        ["Still — I still hope", "फिर वी मैं उम्मीद करदा आं", "phir vee main ummeed kardaa aan"],
        ["Yet — not done yet", "हले नेईं मुक्के", "hale nein mukke"],
        ["Or — tea or coffee", "चा जां कॉफी", "chaa jaan coffee"],
        ["Neither… nor — neither he nor she", "ना ओ ना ओ", "na o na o"],
        ["If — if it rains", "जे मींह पवे", "je meenh pave"],
        ["As — as I said", "जियां मैं कहा", "jiyaan main kahaa"],
        ["After — after food", "खाने बाद", "khaane baad"],
        ["Before — before sleep", "सौण कोलों पैह्लें", "saun kolon paihlen"],
        ["Until — wait until evening", "शाम तिक्क इंतज़ार करो", "shaam tikk intazaar karo"],
    ],
    589: [
        ["The sun rose. The birds sang.", "सूरज उग्या। पंछी गाए।", "sooraj ugayaa. panchee gaae."],
        ["We combined: The sun rose and the birds sang.", "सूरज उग्या अते पंछी गाए।", "sooraj ugayaa ate panchee gaae."],
        ["He was tired. He slept.", "ओ थका सी। ओ सौ गया।", "o thakaa see. o sau gayaa."],
        ["Combined: Tired from work, he slept.", "कम करके थका, ओ सौ गया।", "kam karke thakaa, o sau gayaa."],
        ["It rained. We stayed home.", "मींह पया। असी घरे रहे।", "meenh payaa. asi ghare rahe."],
        ["Combined: Because it rained, we stayed home.", "मींह करके असी घरे रहे।", "meenh karke asi ghare rahe."],
        ["She opened the book. She began to read.", "ओने किताब खोली। पढ़ना शुरू कीता।", "one kitaab kholee. padhanaa shuroo keetaa."],
        ["Combined: Opening the book, she began to read.", "किताब खोल के ओने पढ़ना शुरू कीता।", "kitaab khol ke one padhanaa shuroo keetaa."],
        ["The train arrived. We boarded.", "ट्रेन आई। असी चढ़े।", "train aaee. asi chadhe."],
        ["Combined: When the train arrived, we boarded.", "जदों ट्रेन आई त असी चढ़े।", "jadon train aaee ta asi chadhe."],
        ["He studied hard. He passed.", "ओ ने मेहनत कीती। ओ पास हो गया।", "one mehnat keetee. o paas ho gayaa."],
        ["Combined: Having studied hard, he passed.", "मेहनत करके ओ पास हो गया।", "mehnat karke o paas ho gayaa."],
        ["The shop closed. We returned.", "दुकान बंद होई। असी मुड़ आए।", "dukaan band hoee. asi mud aaey."],
        ["Combined: The shop was closed, so we returned.", "दुकान बंद सी इस करके असी मुड़ आए।", "dukaan band see is karke asi mud aaey."],
        ["I saw him. I waved.", "मैं ओने वेख्या। मैं हाथ हलाया।", "main one vekhyaa. main haath halaayaa."],
        ["Combined: Seeing him, I waved.", "ओने वेख के मैं हाथ हलाया।", "one vekh ke main haath halaayaa."],
    ],
    590: [
        ["I will go and see", "मैं जा के वेखांगा", "main jaa ke vekhaangaa"],
        ["Eat and drink", "खा अते पी", "khaa ate pee"],
        ["He read and understood", "ओने पढ़ के समझ लया", "one padh ke samajh layaa"],
        ["Come and sit", "आ के बैठो", "aa ke baitho"],
        ["She stood up and left", "ओ खड़ी होई के चल गई", "o khadee hoee ke chal gaee"],
        ["We laughed and talked", "असी हस के गल्लां कीतीं", "asi has ke gallaan keeteen"],
        ["Take and give", "लै के दे", "lai ke de"],
        ["He searched and found", "ओने लब्भ के लब्भ लया", "one labbh ke labbh layaa"],
        ["Run and catch", "दौड़ के फड़ो", "daur ke fado"],
        ["Listen and answer", "सुन के जवाब देओ", "sun ke jawaab deo"],
        ["I tried but failed", "मैं कोशिश कीती पर फेल हो गया", "main koshish keetee par fail ho gayaa"],
        ["Write and show", "लिख के दिखाओ", "likh ke dikhaao"],
        ["Wash and wear", "धो के पाओ", "dho ke pao"],
        ["He paid and left", "ओने भर के चल गया", "one bhar ke chal gayaa"],
        ["Open and read", "खोल के पढ़ो", "khol ke padho"],
        ["We met and decided", "असी मिल के फैसला कीता", "asi mil ke faislaa keetaa"],
    ],
    591: [
        ["Ravi wrote the letter", "रवि ने चिट्ठी लिखी", "ravi ne chitthee likhee"],
        ["Passive: The letter was written by Ravi", "चिट्ठी रवि कोलों लिखी गई", "chitthee ravi kolon likhee gaee"],
        ["The dog bit the man", "कुत्ते ने आदमी नू काट्या", "kutte ne aadmee noon kaatyaa"],
        ["The man was bitten by the dog", "आदमी कुत्ते कोलों काट्या गया", "aadamee kutte kolon kaatyaa gayaa"],
        ["They built the bridge", "ओने पुल बणाया", "one pul banaayaa"],
        ["The bridge was built by them", "पुल ओना कोलों बणाया गया", "pul ona kolon banaayaa gayaa"],
        ["She cooks food", "ओ खाना बनांदी आए", "o khaanaa banaandee aaey"],
        ["Food is cooked by her", "खाना ओने कोलों बनाया जांदा आए", "khaanaa one kolon banaayaa jaandaa aaey"],
        ["We will finish the work", "असी कम मुक्कामांगे", "asi kam mukaamaange"],
        ["The work will be finished by us", "कम असें कोलों मुक्के जागा", "kam asen kolon mukke jaagaa"],
        ["He opened the door", "ओने दरवाजा खोल्या", "one daravaajaa kholyaa"],
        ["The door was opened by him", "दरवाजा ओने कोलों खोल्या गया", "daravaajaa one kolon kholyaa gayaa"],
        ["They are painting the wall", "ओ दीवार रंग करदे आए", "o deevaarang karde aaey"],
        ["The wall is being painted", "दीवार रंग कीती जांदी आए", "deevaarang keetee jaandee aaey"],
        ["I have posted the letter", "मैं चिट्ठी पोस्ट कीती", "main chitthee post keetee"],
        ["The letter has been posted", "चिट्ठी पोस्ट हो चुकी आए", "chitthee post ho chukee aaey"],
    ],
    592: [
        ["Someone stole my cycle", "किसे ने मेरी साइकल चोरी कीती", "kise ne meree saikal choree keetee"],
        ["My cycle got stolen", "मेरी साइकल चोरी हो गई", "meree saikal choree ho gaee"],
        ["Water fills the pot", "पाणी बर्तन भरदा आए", "paanee bartan bhardaa aaey"],
        ["The pot gets filled with water", "बर्तन पाणी कोलों भर जांदा आए", "bartan paanee kolon bhar jaandaa aaey"],
        ["Heat opened the door", "गर्मी ने दरवाजा खोल दिता", "garmee ne daravaajaa khol ditaa"],
        ["The door opened from the heat", "गर्मी कोलों दरवाजा खुल गया", "garmee kolon daravaajaa khul gayaa"],
        ["They elected him leader", "ओने ओने मुखिया चुण्या", "one one mukhiya chunya"],
        ["He was elected leader", "ओ मुखिया चुण्या गया", "o mukhiya chunyaa gayaa"],
        ["The news surprised everyone", "खबर ने सबनू हैरान कीता", "khabar ne sab noon hairaan keetaa"],
        ["Everyone was surprised by the news", "सब खबर कोलों हैरान होए", "sab khabar kolon hairaan hoe"],
        ["Time solves problems", "समें समस्या हल करदा आए", "samen samasyaa hal kardaa aaey"],
        ["Problems get solved with time", "समस्यां समें कोलों हल होंदियां आए", "samasyaa samen kolon hal hondeeyaan aaey"],
        ["We must do the work", "सानू कम करना पवेगा", "saanoo karnaa pavegaa"],
        ["The work must be done", "कम होना पवेगा", "kam honaa pavegaa"],
        ["He is reading the book", "ओ किताब पढ़दा आए", "o kitaab padhdaa aaey"],
        ["The book is being read", "किताब पढ़ी जांदी आए", "kitaab padhee jaandee aaey"],
    ],
    593: [
        ["I feel cold", "मिगी ठंड लगदी आए", "migee thand lagdee aaey"],
        ["She feels happy today", "ओने आज खुशी महसूस होदी आए", "one aaj khushee mahasoos hodee aaey"],
        ["I feel that you are right", "मिगी लगदा आए तुस ठीक हो", "migee lagdaa aaey tus theek ho"],
        ["He feels pain in his leg", "ओने पैर च दर्द महसूस होदा आए", "o pair ch dard mahasoos hodaa aaey"],
        ["We feel proud of you", "सानू तुसां उत्ते नाज़ आए", "saanoo tusaan ute naaz aaey"],
        ["Do you feel better?", "की तुस ठीक महसूस करदे हो?", "kee tus theek mahasoos karde ho?"],
        ["I think it will rain", "मैं सोचदा आां मींह पवेगा", "main sochdaa aan meenh pavegaa"],
        ["What do you think?", "तुस की सोचदे हो?", "tus kee sochde ho?"],
        ["She thinks before she speaks", "ओ बोलने कोलों पैह्लें सोचदी आए", "o bolne kolon paihlen sochdee aaey"],
        ["I thought you knew", "मैं सोच्या तुस जांदे हो", "main sochhyaa tus jaande ho"],
        ["We think this is fair", "असी सोचदे आां ए ठीक आए", "asi sochde aan e theek aaey"],
        ["He thinks too much", "ओ ज्यादा सोचदा आए", "o zyaadaa sochdaa aaey"],
        ["I feel like sleeping", "मिगी सौणे दा मन करदा आए", "migee saune daa man kardaa aaey"],
        ["She feels lonely in the city", "ओ शहर च अकेलापन महसूस करदी आए", "o shehar ch akelapan mahasoos kardee aaey"],
        ["They think we are wrong", "ओ सोचदे आए असी गलत आं", "o sochde aan asi galat aan"],
        ["I don't think so", "मैं एह् नेईं सोचदा", "main eh nein sochdaa"],
    ],
    594: [
        ["To kill two birds with one stone", "इक गोली नाल दो निशाने", "ik golee naal do nishaane"],
        ["After a long time", "लंबे समें बाद", "lambe samen baad"],
        ["Heart to heart talk", "दिल कोल दिल दी गल", "dil kol dil dee gal"],
        ["To turn a blind eye", "अंधा बण के वेखणा", "andhaa ban ke vekhanaa"],
        ["To be in seventh heaven", "सातवें आसमान च होणा", "saatven aasmaan ch honaa"],
        ["To add fuel to fire", "आग च घी पाओ", "aag ch ghee pao"],
        ["Better late than never", "देर आवे पर दुरुस्त आवे", "der aave par durust aave"],
        ["All that glitters is not gold", "जो चमकदा ओ सोना नेईं होंदा", "jo chamakdaa o sonaa nein honda"],
        ["Once in a blue moon", "बड़ी कठनाई कोल", "baree kathanaaee kol"],
        ["To bite the hand that feeds", "जिस दी रोटी खाई ओदा ही हाथ काटणा", "jis dee rotee khaaee odaa hi haath kaatanaa"],
        ["The early bird catches the worm", "जेड़ा जल्दी उठदा ओ फायदा लैंदा", "jedaa jaldee uthdaa o faaydaa laindaa"],
        ["Every cloud has a silver lining", "हर मुसीबत च कोई रस्ता होंदा आए", "har museebat ch koee rastaa honda aaey"],
        ["To cry over spilt milk", "बीती गल्लां कोल रोंणा", "beetee gallaan kol rona"],
        ["To hit the nail on the head", "सही गल उत्ते दस्तक देणा", "sahi gal ute dastak denaa"],
        ["Between the devil and the deep sea", "आगे कुआं पिछे खाई", "aage kuaan pichhe khaaee"],
        ["To mind one's own business", "अपनी गल्ल च रहणा", "apanee gall ch rahanaa"],
    ],
    595: [
        ["To burn midnight oil", "रात भर पढ़ाई करणा", "raat bhar padhaaee karnaa"],
        ["To smell a rat", "कुछ गड़बड़ लगणा", "kuchh garbad laganaa"],
        ["To break the ice", "पैह्ली गल्ल करके माहौल ठीक करणा", "paihlee gall karke maahaul theek karnaa"],
        ["To cost an arm and a leg", "बड़ा महंगा पैणा", "baraa mahangaa painaa"],
        ["To let the cat out of the bag", "राज़ खोल देणा", "raaz khol denaa"],
        ["To beat about the bush", "सीधी गल्ल ना करणा", "seedhee gall na karnaa"],
        ["To pull someone's leg", "किसे दा मज़ाक उड़ाणा", "kise daa mazaak udaanaa"],
        ["To be on cloud nine", "बड़ा खुश होणा", "baraa khush honaa"],
        ["To get cold feet", "डर के मुड़ जाणा", "dar ke mud jaanaa"],
        ["To throw in the towel", "हार मान लेणा", "haar maan lenaa"],
        ["To spill the beans", "सब कुछ दस्स देणा", "sab kuchh dass denaa"],
        ["A piece of cake", "बड़ा आसान कम", "baraa aasaan kam"],
        ["To hit the sack", "सौण चले जाणा", "saun chale jaanaa"],
        ["To kill time", "समें गज्जाणा", "samen gajjaanaa"],
        ["To see eye to eye", "इक राय होणा", "ik raay honaa"],
        ["To be in hot water", "मुसीबत च फंसणा", "museebat ch phansanaa"],
    ],
    596: [
        ["If you hurry, you will catch the bus", "जे तुस जल्दी करोगे त बस फड़ लोगे", "je tus jaldee karoge ta bas fad loge"],
        ["If I were rich, I would help more", "जे मैं अमीर होंदा त ज्यादा मदद करदा", "je main ameer honda ta zyaadaa madad karadaa"],
        ["Unless you try, you won't learn", "जे कोशिश नेईं करोगे त नेईं सिखोगे", "je koshish nein karoge ta nein sikhoge"],
        ["Provided you pay, you can take it", "जे तुस भर देओ त लै सकदे हो", "je tus bhar deo ta lai sakde ho"],
        ["If it had rained, crops would have grown", "जे मींह पै गया होंदा त फसल वधदी", "je meenh pai gayaa honda ta fasal vadhdee"],
        ["If she had called, I would have come", "जे ओने फोन कीता होंदा त मैं आया होंदा", "je one fon keetaa honda ta main aayaa honda"],
        ["If they agree, the deal is done", "जे ओ मान जान त सौदा पक्का", "je o maan jaan ta saudaa pakkaa"],
        ["If not today, then tomorrow for sure", "आज नेईं त कल जरूर", "aaj nein ta kal jaroor"],
        ["If you eat less spice, your health will be better", "जे कम मिर्च खाओगे त सेहत चंगी होगी", "je kam mirch khaoge ta sehat changee hogee"],
        ["Were I you, I would not wait", "जे मैं तुसां दी जगह होंदा त इंतज़ार ना करदा", "je main tusaan dee jagah honda ta intazaar na karadaa"],
        ["If the road is clear, we will reach fast", "जे रस्ता साफ होवे त जल्दी पै जामां", "je rastaa saaf hove ta jaldee pai jaamaan"],
        ["If you had told me, I would have helped", "जे तुस दस्सदे त मैं मदद करदा", "je tus dassde ta main madad karadaa"],
        ["If winter sets in, wear warm clothes", "जे सर्दी पै जावे त गरम कपड़े पाओ", "je sardee pai jaave ta garam kapde pao"],
        ["If you don't ask, you won't get", "जे नेईं पुछोगे त नेईं मिलेगा", "je nein puchhoge ta nein milegaa"],
        ["If everyone cooperates, work finishes fast", "जे सब मिल के करन त कम जल्दी मुक्के", "je sab mil karan ta kam jaldee mukke"],
        ["If lightning strikes, stay indoors", "जे बिजली चमके त अंदर रहो", "je bijlee chamke ta andar raho"],
    ],
}
