# Dogri Lesson 5 — Conversation practice, chunk B (chapter IDs 642–662).

LESSONS_S5B = {
    642: [
        ["I want to open an account", "मिगी खाता खोलना आए", "migee khaataa kholanaa aaey"],
        ["Please fill this form", "किरपा करियै ए फॉर्म भरो", "kirpaa kariyai e form bharo"],
        ["I need a cheque book", "मिगी चेक बुक चाहिदी आए", "migee chek buk chaahidee aaey"],
        ["What is the minimum balance?", "घट कोल घट बैलेंस की आए?", "ghat kol ghat bailens kee aaey?"],
        ["I want to deposit cash", "मिगी नकद जमा करना आए", "migee nakad jama karnaa aaey"],
        ["Please count the notes", "नोट गिनो", "not gino"],
        ["I forgot my PIN", "मैं पिन भुल गया", "main pin bhul gayaa"],
        ["Block my card; it is lost", "मेरा कार्ड ब्लॉक करो; गुम हो गया", "meraa kaard blok karo; gum ho gayaa"],
        ["Transfer money to this account", "ए खाते च पैसे ट्रांसफर करो", "e khaate ch paise traansfar karo"],
        ["What are the service charges?", "सेवा शुल्क की आए?", "sevaa shulk kee aaey?"],
        ["I need a loan for a house", "मिगी घर लई लोन चाहिदा आए", "migee ghar lai lon chaahidaa aaey"],
        ["EMI starts next month", "ईएमआई अगले महीने शुरू होगी", "eemai agale maheene shuroo hogee"],
        ["Please update my mobile number", "मेरा मोबाइल नंबर अपडेट करो", "meraa mobail nambar apadet karo"],
        ["The queue is long", "लाइन लंबी आए", "lain lambee aaey"],
        ["Thank you, have a good day", "धन्नवाद, चंगा दिन रहे", "dhannavaad, changaa din rahe"],
        ["Visit the manager for approval", "मंज़ूरी लई मैनेजर कोल जाओ", "manjooree lai mainejr kol jaao"],
    ],
    643: [
        ["What time does the temple open?", "मंदिर किन्ने वजे खुलदा आए?", "mandir kinne vaje khuldaa aaey?"],
        ["Is photography allowed?", "की फोटो खिंच सकदे आं?", "kee foto khinch sakde aan?"],
        ["Where do we keep shoes?", "जूते कुथे रखने आए?", "joote kuthe rakhne aaey?"],
        ["Is there prasad today?", "की आज प्रसाद आए?", "kee aj prasaad aaey?"],
        ["How old is this temple?", "ए मंदिर किन्ना पुराणा आए?", "e mandir kinnaa puraanaa aaey?"],
        ["Tell me about the history", "इतिहास दस्सो", "itihaas dasso"],
        ["Is there parking nearby?", "की नेड़े पार्किंग आए?", "kee nedde paarking aaey?"],
        ["We came for darshan", "असी दर्शन लई आए", "asi darshan lai aaey"],
        ["Special aarti in the evening", "शाम ने खास आरती आए", "shaam ne khaas aartee aaey"],
        ["Dress modestly, please", "किरपा करियै सलीकेदार कपड़े पाओ", "kirpaa kariyai saleekedaar kapde pao"],
        ["Donations go to the trust", "दान ट्रस्ट नू जांदा आए", "daan trast noon jaandaa aaey"],
        ["Festival rush is heavy", "त्योहार च भीड़ बड़ी आए", "tyauhaar ch bheer baree aaey"],
        ["Is there a guide available?", "की गाइड मिलदा आए?", "kee gaid mildaa aaey?"],
        ["We will ring the bell thrice", "असी घंटी तिन वार बजामांगे", "asi ghantee tin vaar bajaamaange"],
        ["Peaceful atmosphere here", "इत्थे सुकून वाला माहौल आए", "itthe sukoon vaalaa maahaul aaey"],
        ["Thank you for the information", "जानकारी लई धन्नवाद", "jaanakaaree lai dhannavaad"],
    ],
    644: [
        ["Namaste, uncle and aunty", "नमस्कार, चाचा चाची", "namaskaar, chaachaa chaachee"],
        ["Thank you for inviting us", "सानू बुलाने लई धन्नवाद", "saanoo bulaane lai dhannavaad"],
        ["The food is delicious", "खाना बड़ा स्वादिष्ट आए", "khaanaa baraa svaadisht aaey"],
        ["Please have some more roti", "होर रोटी लो", "hor rotee lo"],
        ["I am full; thank you", "पेट भर गया; धन्नवाद", "pet bhar gayaa; dhannavaad"],
        ["Your home is beautiful", "तुसां दा घर बड़ा सोणा आए", "tusaan daa ghar baraa sonaa aaey"],
        ["May I help in the kitchen?", "की मैं रसोई च मदद करां?", "kee main rasoee ch madad karaan?"],
        ["The garden is lovely", "बाग बड़ा प्यारा आए", "baag baraa pyaaraa aaey"],
        ["We should leave before dark", "अंधेरे कोलों पैह्लें चलिए", "andhere kolon paihlen chalie"],
        ["Our parents send regards", "साडे मां-बाप नू नमस्कार", "saade maan-baap noon namaskaar"],
        ["Hope to see you again", "फेर मिलने दी उम्मीद", "pher milne dee ummeed"],
        ["Drive safely back", "सुरक्षित चल के जाओ", "surakshit chal ke jaao"],
        ["The tea was perfect", "चा बिलकुल ठीक सी", "chaa bilkul theek see"],
        ["We enjoyed the lunch", "सानू लंच बड़ा चंगा लगा", "saanoo lunch baraa changaa lagaa"],
        ["Bless the children", "बच्चेयां नू आशीर्वाद देओ", "baccheyaan noon aasheerwaad deo"],
        ["Goodbye; take care", "अलविदा; ख्याल रखो", "alvida; khyaal rakho"],
    ],
    645: [
        ["Which teams are playing?", "केड़ी-केड़ी टीमें खेड़दियां आए?", "keddee-keddee teemen kheddeeyaan aaey?"],
        ["The score is one–one", "स्कोर इक-इक आए", "skor ik-ik aaey"],
        ["What a goal!", "की गोल!", "kee gol!"],
        ["The referee gave a card", "रेफरी ने कार्ड दिता", "refree ne kaard ditaa"],
        ["Our team is attacking", "साडी टीम अटैक करदी आए", "saadee teem attek kardee aaey"],
        ["Pass the ball!", "बाल पास करो!", "baal paas karo!"],
        ["The crowd is cheering", "भीड़ ताड़ियां मारदी आए", "bheer taarriyaan maardee aaey"],
        ["Half-time break", "हाफ टाइम दा ब्रेक", "haaf taaim daa brek"],
        ["Injury; player is leaving", "चोट; खेड़ारी चल गया", "chot; khedaaree chal gayaa"],
        ["Extra time may come", "एक्स्ट्रा टाइम आ सकदा आए", "ekstraa taaim aa sakdaa aaey"],
        ["Penalty shootout", "पेनल्टी शूटआउट", "penaltee shootaaut"],
        ["We won!", "असी जित गे!", "asi jit ge!"],
        ["Better luck next time", "अगली वार चंगी किस्मत", "agalee vaar changee kismat"],
        ["The match was fair", "मैच ईमानदार रहा", "maich eemaanadaar rahaa"],
        ["Let's watch highlights", "हाइलाइट्स वेखिए", "haailaits vekhie"],
        ["Football unites everyone", "फुटबॉल सबनू जोड़दा आए", "futbol sab noon joddaa aaey"],
    ],
    646: [
        ["Which movie is playing?", "केड़ी फिल्म चलदी आए?", "keddee film chaldee aaey?"],
        ["Two tickets for the nine o'clock show", "नौ वजे दा शो दो टिकट", "nau vaje daa sho do tikat"],
        ["Popcorn and cold drink?", "पॉपकॉर्न अते कोल्ड्रिंक?", "popkorn ate koldrink?"],
        ["This seat is reserved", "ए सीट रिज़र्व आए", "e seet rizarv aaey"],
        ["Please switch off your mobile", "किरपा करियै मोबाइल बंद करो", "kirpaa kariyai mobail band karo"],
        ["The interval is long", "इंटरवल लंबा आए", "intaraval lambaa aaey"],
        ["The story is interesting", "कहाणी दिलचस्प आए", "kahaanee dilchasp aaey"],
        ["The songs are good", "गाने चंगे आए", "gaane change aaey"],
        ["It is a family film", "ए फैमिली फिल्म आए", "e faemilee film aaey"],
        ["Too loud; lower the volume", "बड़ा शोर; वॉल्यूम घटाओ", "baraa shor; volyoom ghataao"],
        ["The climax was emotional", "क्लाइमैक्स भावुक सी", "klaaimaiks bhaavuk see"],
        ["Let's leave after credits", "क्रेडिट्स बाद चलिए", "kredits baad chalie"],
        ["How did you like the film?", "तुसां नू फिल्म कियां लगी?", "tusaan noon film kiyaan lagee?"],
        ["We should book online next time", "अगली वार ऑनलाइन बुक करिए", "agalee vaar online buk karie"],
        ["The theatre is crowded", "थिएटर भीड़ च आए", "thieetr bheer ch aaey"],
        ["Nice evening; let's go home", "सोणी शाम; घर चलिए", "sonee shaam; ghar chalie"],
    ],
    647: [
        ["Which country is your favourite?", "तुसां दी पसंदीदा टीम केड़ी आए?", "tusaan dee pasandeeda teem keddee aaey?"],
        ["The World Cup is every four years", "वर्ल्ड कप हर चार साल च आए", "varld kap har chaar saal ch aaey"],
        ["We watched the final together", "असी फाइनल इकठ्ठे वेखी", "asi fainal ikatthe vekhee"],
        ["What a save by the goalkeeper!", "गोलकीपर ने की सेव!", "golakeepar ne kee sev!"],
        ["Offside; the goal is cancelled", "ऑफसाइड; गोल रद्द", "ofsaid; gol radd"],
        ["The stadium is full", "स्टेडियम भरया आए", "sttediyam bharyaa aaey"],
        ["Penalty in the last minute", "आखरी मिनट च पेनल्टी", "aakharee minat ch penaltee"],
        ["Extra time — still no goal", "एक्स्ट्रा टाइम — गोल नेईं", "ekstraa taaim — gol nein"],
        ["We lost on penalties", "असी पेनल्टी उत्ते हारे", "asi penaltee ute haare"],
        ["Let's watch the replay", "रिप्ले वेखिए", "riple vekhie"],
        ["The referee's decision was tough", "रेफरी दा फैसला सख्त सी", "refree daa faislaa sakht see"],
        ["Fans are singing in the streets", "फैन गलियां च गा रहे आए", "faen galiyaan ch gaa rahe aaey"],
        ["My country reached the semi‑final", "मेरा देश सेमी फाइनल पै गया", "meraa desh seemee fainal pai gayaa"],
        ["Injuries changed the match", "चोटें ने मैच बदल दिता", "choten ne maich badal ditaa"],
        ["Football brings the world together", "फुटबॉल दुनिया जोड़दा आए", "futbol duniyaa joddaa aaey"],
        ["See you for the next match", "अगले मैच उत्ते मिलांगे", "agale maich ute milaange"],
    ],
    648: [
        ["Welcome to Jammu", "जम्मू च स्वागत आए", "jammu ch swaagat aaey"],
        ["This fort is three hundred years old", "ए किला तिन सौ साल पुराणा आए", "e kilaa tin sau saal puraanaa aaey"],
        ["We will walk for twenty minutes", "असी बी मिनट टुरांगे", "asi bee minat turaange"],
        ["Take photos here", "इत्थे फोटो खिंचो", "itthe foto khincho"],
        ["The river is sacred", "नदी पवित्र आए", "nadee pavitra aaey"],
        ["Local food is spicy", "लोकल खाना तीखा आए", "lokal khaanaa teekhaa aaey"],
        ["Souvenir shops are there", "उत्थे सुवेनियर दुकानां आए", "utthe suveneer dukaanaan aaey"],
        ["Wear comfortable shoes", "आरामदायक जूते पाओ", "aaraamadaayak joote pao"],
        ["Stay with the group", "ग्रुप कोल रहो", "grup kol raho"],
        ["The view from here is amazing", "इत्थों दृश्य अद्भुत आए", "itthon drishya adbhut aaey"],
        ["History lovers enjoy this place", "इतिहास प्रेमी ए जगह पसंद करदे आए", "itihaas premee e jagah pasand karde aaey"],
        ["We return before sunset", "असी सूरज डुबण कोलों पैह्लें मुड़ांगे", "asi sooraj duban kolon paihlen mudaange"],
        ["Tips are optional", "टिप वैकल्पिक आए", "tip vaikalpik aaey"],
        ["Keep water with you", "पाणी संग रखो", "paanee sang rakho"],
        ["Any questions?", "कोई सवाल?", "koee savaal?"],
        ["Hope you enjoyed the tour", "उम्मीद आए टूर चंगा लगा", "ummeed aaey toor changaa lagaa"],
    ],
    649: [
        ["Good morning; please sit", "सुप्रभात; बैठो", "suprabhaat; baitho"],
        ["Introduce yourself in Dogri", "अपना परिचय डोगरी च देओ", "apnaa parichay dogree ch deo"],
        ["Why should we hire you?", "सानू तुसां नू कियों रखना चाहीदा?", "saanoo tusaan noon kyon rakhanaa chaahidaa?"],
        ["Describe your village", "अपना पेंड दस्सो", "apnaa pend dasso"],
        ["Read this paragraph aloud", "ए पैराग्राफ जोर कोल पढ़ो", "e pairaagraaf zor kol padho"],
        ["Translate this sentence", "ए वाक अनुवाद करो", "e vaak anuvaad karo"],
        ["Write a short essay", "छोटा निबंध लिखो", "chhottaa nibandh likho"],
        ["Formal vs informal speech", "रस्मी अते गैर-रस्मी बोली", "rasamee ate gair-rasamee bolee"],
        ["Listen and repeat", "सुनो अते दोहराओ", "suno ate dohraao"],
        ["Any difficulty with grammar?", "ग्रामर च कोई दिक्कत?", "graamar ch koee dikat?"],
        ["Speak slowly and clearly", "हौले अते साफ बोलो", "haule ate saaf bolo"],
        ["We test reading and speaking", "असी पढ़ाई अते बोली जांचदे आं", "asi padhaaee ate bolee jaanchde aan"],
        ["Do you know banking terms?", "की तुसां नू बैंकिंग शब्द पता आए?", "kee tusaan noon bainking shabd pataa aaey?"],
        ["Thank you; result will be emailed", "धन्नवाद; नतीजा ईमेल होगा", "dhannavaad; nateejaa eemel hogaa"],
        ["Confidence matters", "आत्मविश्वास जरूरी आए", "aatmavishvaas jaroori aaey"],
        ["All the best", "सारी कामनाएं", "saaree kaamnaan"],
    ],
    650: [
        ["What is for lunch today?", "आज दुपहर की बणे आए?", "aj dupahar kee bane aaey?"],
        ["I prefer roti and dal", "मिगी रोटी अते दाल पसंद आए", "migee rotee ate daal pasand aaey"],
        ["Less oil, please", "कम तेल पाओ", "kam tel pao"],
        ["The curry is spicy", "सालन तीखा आए", "saan teekhaa aaey"],
        ["Add salad on the side", "सलाद साइड उत्ते रखो", "salaad saaid ute rakho"],
        ["I am vegetarian", "मैं शाकाहारी आं", "main shaakaahaaree aan"],
        ["No onion garlic today", "आज गांदा-लहसुन नेईं", "aj gaandaa-lahasun nein"],
        ["Pack lunch for office", "ऑफिस लई लंच पैक करो", "ofis lai lunch paik karo"],
        ["The rice is well cooked", "चोल चंगी रांधी आए", "chol changee raandhee aaey"],
        ["Dessert after meal", "खाने बाद मिठाई", "khaane baad mithaai"],
        ["Drink water between bites", "निवालें कोलों पाणी पीओ", "nivaalen kolon paanee peo"],
        ["Host served generously", "मेहमान नवाज़ी बड़ी कीती", "mehmaan navaazee baree keetee"],
        ["Compliments to the cook", "रांधने वाले दी शाबाश", "raadhne vaalee dee shaabaash"],
        ["I am full", "पेट भर गया", "pet bhar gayaa"],
        ["Help clear the table", "मेज साफ करने च मदद करो", "mej saaf karne ch madad karo"],
        ["Thanks for the lovely meal", "सोणे खाने लई धन्नवाद", "sone khaane lai dhannavaad"],
    ],
    651: [
        ["I joined a music class", "मैं संगीत क्लास च नां लिखाया", "main sangeet klaas ch naan likhaayaa"],
        ["Painting is my hobby", "पेंटिंग मेरा शौक आए", "penting meraa shauk aaey"],
        ["We meet every Saturday", "असी हर शनिवार मिलदे आं", "asi har shanivaar milde aan"],
        ["The teacher is very patient", "मास्टर बड़ा सब्र वाला आए", "maastar baraa sabr vaalaa aaey"],
        ["I practice guitar at home", "मैं घरे गिटार वजांदा आं", "main ghare gitaar vajaandaa aan"],
        ["Fees are affordable", "फीस सस्ती आए", "fees sastee aaey"],
        ["Certificate after one year", "इक साल बाद सर्टिफिकेट", "ik saal baad sartifiket"],
        ["I missed two classes", "मैं दो क्लास छूटियां", "main do klaas chhootiyaan"],
        ["Friends from class", "क्लास कोल दोस्त", "klaas kol dost"],
        ["Hobby reduces stress", "शौक तनाव घटांदा आए", "shauk tanaav ghataandaa aaey"],
        ["I want to learn tabla", "मैं तबला सिखणा चांदा आं", "main tablaa sikhanaa chaandaa aan"],
        ["The hall is well lit", "हाल च रोशनी चंगी आए", "haal ch roshanee changee aaey"],
        ["Parents support my hobby", "मां-बाप मेरे शौक दे हिमायती आए", "maan-baap mere shauk de himaayatee aaey"],
        ["Annual show next month", "अगले महीने सालाना शो", "agale maheene saalaanaa sho"],
        ["Practice makes perfect", "अभ्यास करने कोल चंगा फेर", "abhyaas karne kol changaa pher"],
        ["I enjoy every lesson", "मिगी हर सबक चंगा लगदा", "migee har sabak changaa lagdaa"],
    ],
    652: [
        ["See you soon", "फेर जल्दी मिलांगे", "pher jaldee milaange"],
        ["No problem at all", "कोई गल नेईं", "koee gal nein"],
        ["I will try my best", "मैं पूरी कोशिश करांगा", "main pooree koshish karaangaa"],
        ["Congratulations on your success", "सफलता उत्ते बधाइयां", "safalata ute badhaaiyaan"],
        ["Sorry for the delay", "देर लई माफी", "der lai maafee"],
        ["Please wait a moment", "इक पल इंतज़ार करो", "ik pal intazaar karo"],
        ["I agree with you", "मैं तुसां कोल सहमत आं", "main tusaan kol sahamat aan"],
        ["I don't think so", "मैं एह् नेईं सोचदा", "main eh nein sochdaa"],
        ["Let's discuss tomorrow", "कल गल्ल करांगे", "kal gall karaange"],
        ["That sounds good", "ओ चंगा लगदा आए", "o changaa lagdaa aaey"],
        ["I need more time", "मिगी होर समें चाहिदा", "migee hor samen chaahidaa"],
        ["Can we reschedule?", "की असी दूजी तारीख लमां?", "kee asi doojee taareekh lamaan?"],
        ["I'll send you the details", "मैं तुसां नू विस्तार भेजांगा", "main tusaan noon vistaar bhejaangaa"],
        ["Keep me updated", "मिगी खबर देंदे रहो", "migee khabar dende raho"],
        ["Have a nice day", "चंगा दिन रहे", "changaa din rahe"],
        ["Take care of your health", "सेहत दा ख्याल रखो", "sehat daa khyaal rakho"],
    ],
    653: [
        ["Long time no see", "बड़े चिरां बाद मिलन", "bare chiraan baad milan"],
        ["How is your family?", "तुसां दा परिवार कैह् आए?", "tusaan daa parivaar kaih aaey?"],
        ["Work is busy these days", "ए दिन बड़ा कम च ब्यस्त आए", "e din baraa kam ch byast aaey"],
        ["We went on a short trip", "असी छोटे सफर उत्ते गे", "asi chhotte safar ute ge"],
        ["The weather was pleasant", "मौसम सुहावना सी", "mausam suhaavanaa see"],
        ["Photos are on my phone", "फोटा मेरे मोबाइल च आए", "fota mere mobail ch aaey"],
        ["Let's plan a picnic", "पिकनिक दी योजना बणाओ", "pikanik dee yojanaa banaao"],
        ["Traffic was terrible", "ट्रैफिक बड़ा माड़ा सी", "traifik baraa maarraa see"],
        ["I bought a new book", "मैं नवी किताब खरीदी", "main navee kitaab khareedee"],
        ["The movie was average", "फिल्म ठीक-ठाक सी", "film theek-thaak see"],
        ["We should exercise daily", "रोज व्यायाम करना चाहीदा", "roz vyaayaam karnaa chaahidaa"],
        ["Sleep early for health", "सेहत लई जल्दी सोओ", "sehat lai jaldee soo"],
        ["Drink more water", "ज्यादा पाणी पीओ", "zyaadaa paanee peo"],
        ["Festivals bring joy", "त्योहार खुशी ले आंदे आए", "tyauhaar khushee le aande aaey"],
        ["Hope to meet again", "फेर मिलने दी उम्मीद", "pher milne dee ummeed"],
        ["Stay happy and healthy", "खुश रहो अते तंदरुस्त रहो", "khush raho ate tandarust raho"],
    ],
    654: [
        ["We learn by speaking", "असी बोल के सिखदे आं", "asi bol ke sikhde aan"],
        ["Don't fear mistakes", "गलती कोलों ना डरो", "galtee kolon na daro"],
        ["Repeat after the teacher", "मास्टर कोलों दोहराओ", "maastar kolon dohraao"],
        ["Use new words daily", "रोज नवे शब्द वरतो", "roz nave shabd varato"],
        ["Listen to Dogri songs", "डोगरी गीत सुनो", "dogree geet suno"],
        ["Talk with neighbours", "पड़ोसियां कोल गल्ल करो", "parosiyaan kol gall karo"],
        ["Label things at home", "घर च चीज़ां उत्ते नां लिखो", "ghar ch cheezaan ute naan likho"],
        ["Keep a small diary", "छोटी डायरी रखो", "chhotee daayaree rakho"],
        ["Watch Dogri videos", "डोगरी वीडियो वेखो", "dogree veediyo vekho"],
        ["Ask 'how do you say…?'", "'…कियां बोलदे?' पुछो", "… kiyaan bolde?' puchho"],
        ["Praise progress, not perfection", "तरक्की दी तारीफ करो", "tarakkee dee taareef karo"],
        ["Learn with family", "परिवार कोल सिखो", "parivaar kol sikho"],
        ["Play word games", "शब्द खेड़ खेड़ो", "shabd khed khedo"],
        ["Read signs on the road", "रस्ते दे निशान पढ़ो", "raste de nishaan padho"],
        ["Confidence grows with practice", "अभ्यास कोल आत्मविश्वास वधदा आए", "abhyaas kol aatmavishvaas vadhdaa aaey"],
        ["Enjoy the journey of learning", "सिखने दे सफर च मज़ा लो", "sikhne de safar ch mazaa lo"],
    ],
    655: [
        ["This is my book", "ए मेरी किताब आए", "e meree kitaab aaey"],
        ["That is your pen", "ओ तुसां दा कलम आए", "o tusaan daa kalam aaey"],
        ["I am a student", "मैं विद्यार्थी आं", "main vidyaarthee aan"],
        ["We live in Jammu", "असी जम्मू च रेंदे आं", "asi jammu ch rende aan"],
        ["She cooks well", "ओ चंगा रांधदी आए", "o changaa raandhee aaey"],
        ["They play cricket", "ओ क्रिकेट खेड़दे आए", "o kriket khedde aaey"],
        ["The dog is barking", "कुत्ता भौंकदा आए", "kuttaa bhonkaa aaey"],
        ["Open the window", "खिड़की खोलो", "khidakee kholo"],
        ["Close the door", "दरवाजा बंद करो", "daravaajaa band karo"],
        ["Water the plants", "पौधे नू पाणी देओ", "paude noon paanee deo"],
        ["Read page ten", "दसवां सफा पढ़ो", "dasavaan safaa padho"],
        ["Write your name", "अपना नां लिखो", "apnaa naan likho"],
        ["Come here", "इत्थे आओ", "itthe aao"],
        ["Go slowly", "हौले जाओ", "haule jaao"],
        ["Sit down", "बैठ जाओ", "baith jaao"],
        ["Stand up", "खड़े हो जाओ", "khade ho jaao"],
    ],
    656: [
        ["The book is on the table", "किताब मेज उत्ते आए", "kitaab mej ute aaey"],
        ["The cat is under the chair", "बिल्ली कुर्सी हेठ आए", "billee kursee heth aaey"],
        ["He is in the room", "ओ कमरे च आए", "o kamre ch aaey"],
        ["We walked along the river", "असी नदी कोलों टुरे", "asi nadee kolon ture"],
        ["Turn towards the market", "बाज़ार वल मुड़ो", "baazaar val mudo"],
        ["The keys are inside the drawer", "चाबी दराज च आए", "chaabee daraaj ch aaey"],
        ["Sit between them", "ओना कोलों वच बैठो", "ona kolon vach baitho"],
        ["The school is near the temple", "सकूल मंदिर कोल आए", "sakool mandir kol aaey"],
        ["Run behind the ball", "बाल पिछे दौड़ो", "baal pichhe dauro"],
        ["Put the bag on the shelf", "बैग शेल्फ उत्ते रखो", "baeg shelf ute rakho"],
        ["Jump into the water", "पाणी च कूदो", "paanee ch kudo"],
        ["Drive across the bridge", "पुल पार करो", "pul paar karo"],
        ["Wait at the gate", "गेट उत्ते रुको", "get ute ruko"],
        ["The shop is opposite the bank", "दुकान बैंक सामने आए", "dukaan baink saamne aaey"],
        ["Birds flew over the house", "पंछी घर उत्तों उड़े", "panchee ghar utton udde"],
        ["He hid behind the tree", "ओ रुख पिछे लुक्या", "o rukh pichhe lukyaa"],
    ],
    657: [
        ["Teacher: Why are you late?", "मास्टर: तुस देर कोल कियों आए?", "maastar: tus der kol kyon aaey?"],
        ["Student: The road was blocked", "विद्यार्थी: रस्ता बंद सी", "vidyaarthee: rastaa band see"],
        ["Teacher: Bring homework tomorrow", "मास्टर: कल होमवर्क लेआओ", "maastar: kal homavark leaao"],
        ["Student: Yes, I will", "विद्यार्थी: जी, लेआमां", "vidyaarthee: jee, leaamaan"],
        ["Two friends meet", "दो दोस्त मिलदे आए", "do dost milde aaey"],
        ["One says: I lost my money", "इक कहंदा: पैसे गुम हो गे", "ik kahandaa: paise gum ho ge"],
        ["Other says: Search your pocket", "बैया कहंदा: जेब च लब्भ", "baiyaa kahandaa: jeb ch labbh"],
        ["Son: Mom, food is ready?", "पुत: माँ, खाना तैयार?", "put: maa, khaanaa taiyaar?"],
        ["Mother: Five more minutes", "माँ: होर पाँच मिनट", "maa: hor paanch minat"],
        ["Villager: The well is dry", "पेंडू: कुआं सूख गया", "pendoo: kuaan sookh gayaa"],
        ["Other: Dig deeper next week", "बैया: अगले हफ्ते होर खोदांगे", "baiyaa: agale hafte hor khodaange"],
        ["Shopkeeper: Fresh milk!", "दुकानदार: ताज़ा दुद्ध!", "dukaandaar: taazaa duddh!"],
        ["Customer: Keep half a litre", "ग्राहक: आधा लीटर रखो", "graahak: aadhaa leetr rakho"],
        ["Punchline: Money first!", "मज़ा: पैह्लें पैसे!", "mazaa: paihlen paise!"],
        ["Everyone laughs", "सब हसदे आए", "sab hasde aaey"],
        ["That's Dogri humour", "ओ डोगरी चुटकुला आए", "o dogree chutkulaa aaey"],
    ],
    658: [
        ["A thought for the day: work honestly", "दिन दी सोच: ईमानदारी कोल कम करो", "din dee soch: eemaanadaaree kol kam karo"],
        ["Small steps bring big change", "छोटे कदम बड़ा बदलाव ले आंदे आए", "chhotte kadam baraa badalaav le aande aaey"],
        ["Kind words cost nothing", "नर्म शब्दां दा कोई खर्चा नेईं", "narm shabdaan daa koee kharchaa nein"],
        ["Read one page before sleep", "सौण कोलों पैह्लें इक सफा पढ़ो", "saun kolon paihlen ik safaa padho"],
        ["Share a joke with a friend", "दोस्त कोल चुटकुला सुनाओ", "dost kol chutkulaa sunaao"],
        ["Quote: unity is strength", "सुविचार: एकता च ताकत", "suvichaar: ekataa ch taakat"],
        ["Smile at strangers too", "अजनबियां उत्ते वी मुस्कराओ", "ajanabiyaan ute vee muskaraao"],
        ["Help someone quietly today", "आज चुपचाप किसे दी मदद करो", "aj chupchaap kise dee madad karo"],
        ["Write three new words", "तिन नवे शब्द लिखो", "tin nave shabd likho"],
        ["Listen to a short story", "छोटी कहाणी सुनो", "chhotee kahaanee suno"],
        ["Repeat a proverb aloud", "कहावत जोर कोल बोलो", "kahaavat zor kol bolo"],
        ["Note one good habit", "इक चंगी आदत लिखो", "ik changee aadat likho"],
        ["Avoid one bad habit today", "आज इक माड़ी आदत छड़ो", "aj ik maardee aadat chhado"],
        ["Thank three people mentally", "मन च तिन लोकां दा शुकर करो", "man ch tin lokaan daa shukar karo"],
        ["Sleep with a calm mind", "शांत मन कोल सोओ", "shaant man kol soo"],
        ["Tomorrow read again", "कल फेर पढ़ो", "kal pher padho"],
    ],
    659: [
        ["I spend less time online now", "मैं हुन ऑनलाइन कट समें गज्जांदा आं", "main hun online kat samen gajjaandaa aan"],
        ["Social media can distract", "सोशल मीडिया ध्यान भटका सकदा आए", "soshal meediya dhyaan bhatkaa sakdaa aaey"],
        ["I follow news pages", "मैं खबरां दे पेज फॉलो करदा आं", "main khbaraan de pej follow kardaa aan"],
        ["Too many notifications annoy", "ज्यादा नोटिफिकेशन तंग करदे आए", "zyaadaa notifikeshan tang karde aaey"],
        ["I mute groups at night", "मैं रात ग्रुप म्यूट करदा आं", "main raat grup myoot kardaa aan"],
        ["Video calls with relatives", "रिश्तेदारां कोल वीडियो कॉल", "rishtedaaraan kol veediyo kol"],
        ["I learn Dogri from short reels", "मैं छोटियां रीलां कोलों डोगरी सिखदा आं", "main chhotiyaan reelaa kolon dogree sikhdaa aan"],
        ["Cyber safety is important", "साइबर सुरक्षा जरूरी आए", "saibar surakshaa jaroori aaey"],
        ["Don't share OTP publicly", "ओटीपी सार्वजनिक ना सांझा करो", "oteepee saarvajanik na saanjhaa karo"],
        ["Take breaks from the screen", "स्क्रीन कोलों ब्रेक लो", "skreen kolon brek lo"],
        ["Real friends meet offline", "असली दोस्त ऑफलाइन मिलदे आए", "asalee dost oflain milde aaey"],
        ["I deleted unused apps", "मैं बेकार ऐप मिटाए", "main bekaar aip mitaae"],
        ["Good posts spread positivity", "चंगी पोस्ट सकारात्मकता फैलांदी आए", "changee post skaaraatmaktaa failaandee aaey"],
        ["Limit scrolling before sleep", "सौण कोलों स्क्रॉल कम करो", "saun kolon skrol kam karo"],
        ["Balance screen and family time", "स्क्रीन अते परिवार दा संतुलन", "skreen ate parivaar daa santulan"],
        ["Digital discipline helps studies", "डिजिटल अनुशासन पढ़ाई च मदद करदा आए", "dijital anushaasana padhaaee ch madad kardaa aaey"],
    ],
    660: [
        ["Today there is a solar eclipse", "आज सूरज ग्रहण आए", "aaj sooraj grahan aaey"],
        ["Do not look at the sun directly", "सूरज सीधा ना वेखो", "sooraj seedhaa na vekho"],
        ["Use certified glasses", "प्रमाणित चश्मे वरतो", "pramaanit chashme varato"],
        ["Children should be supervised", "बच्चेयां उत्ते निगरानी रखो", "baccheyaan ute nigaraanee rakho"],
        ["Myth: food turns poisonous — not true", "गलत धारणा: खाना ज़हर — सच नेईं", "galat dhaarnaa: khaanaa zahar — sach nein"],
        ["Temples may have special prayers", "मंदिरां च खास पूजा हो सकदी आए", "mandiraan ch khaas pooja ho sakdee aaey"],
        ["Scientists explain the eclipse", "वैज्ञानिक ग्रहण समझांदे आए", "vaigyaanik grahan samjhaande aaey"],
        ["The sky becomes dim", "आकाश मंद हो जांदा आए", "aakaash mand ho jaandaa aaey"],
        ["Birds return to nests", "पंछी घुल्लां च मुड़दे आए", "panchee ghullaan ch murde aaey"],
        ["Temperature may drop slightly", "तापमान थोड़ा घट सकदा आए", "taapamaan thoddaa ghat sakdaa aaey"],
        ["Photograph with proper filter", "ठीक फिल्टर कोल फोटो खिंचो", "theek filter kol foto khincho"],
        ["After eclipse, normal routine", "ग्रहण बाद रूटीन साधारण", "grahan baad rooteen saadhaaran"],
        ["Share correct information online", "सही जानकारी ऑनलाइन सांझी करो", "sahi jaanakaaree online saanjhee karo"],
        ["Children ask many questions", "बच्चे बड़े सवाल पुछदे आए", "bacche bare savaal puchhde aaey"],
        ["Nature is amazing", "कुदरत अद्भुत आए", "kudrat adbhut aaey"],
        ["Let's watch the next eclipse safely", "अगले ग्रहण सुरक्षित वेखांगे", "agale grahan surakshit vekhaange"],
    ],
    661: [
        ["Happy Women's Day!", "अंतर्राष्ट्रीय महिला दिवस दियां बधाइयां!", "antarraashtreey mahilaa divas diyaan badhaaiyaan!"],
        ["We honour women's contributions", "असी औरतां दे योगदान दा सम्मान करदे आं", "asi aurataan de yogadaan daa sammaan karde aan"],
        ["Equal opportunity for all", "सब लई बराबर मौका", "sab lai baraabar maukaa"],
        ["Education empowers girls", "सिख्या कुड़ियां नू सशक्त बणांदी आए", "sikhyaa kudriyaan noon sashakt banaandee aaey"],
        ["Respect at home and work", "घर अते कम उत्ते आदर", "ghar ate kam ute aadar"],
        ["Say no to discrimination", "भेदभाव ना ना करो", "bhedbhaav na na karo"],
        ["Mothers shape society", "मांवां समाज बणांदियां आए", "maanvaan samaaj banaandiyaan aaey"],
        ["Sisters deserve support", "बहणां दी सहायता बनदी आए", "bahaanaan dee sahaayata bandee aaey"],
        ["Women lead in every field", "हर क्षेत्र च औरतें अगुवाई करदियां आए", "har kshetr ch auraten aguvaai kardeeyaan aaey"],
        ["Safety is everyone's duty", "सुरक्षा सबदा फर्ज आए", "surakshaa sabdaa farz aaey"],
        ["Celebrate achievements loudly", "कामयाबियां जोर कोल मनाओ", "kaamyaabiyaan zor kol manaao"],
        ["Listen to women's voices", "औरतां दियां आवाज़ां सुनो", "aurataan diyaan aavaazaan suno"],
        ["Share household work fairly", "घर दा कम बराबर बांड़ो", "ghar daa kam baraabar baando"],
        ["Healthcare access for all", "सब लई सेहत सेवा", "sab lai sehat sevaa"],
        ["Together we build equality", "इकठ्ठे बराबरी बणांदे आं", "ikatthe baraabaree banaande aan"],
        ["Proud of the women in my life", "मिगी जिंदगी दियां औरतां उत्ते नाज़", "migee zindagee diyaan aurataan ute naaz"],
    ],
    662: [
        ["Why didn't you clean the room?", "की तुस कमरा साफ नेईं कीता?", "kee tus kamraa saaf nein keetaa?"],
        ["I was tired after office", "मैं ऑफिस कोलों थका सी", "main ofis kolon thakaa see"],
        ["That is not an excuse", "ओ बहाना नेईं", "o bahaanaa nein"],
        ["The guests are coming tomorrow", "कल मेहमान आनगे", "kal mehmaan aanage"],
        ["Please understand my workload", "मेरे कम दा बोझ समझो", "mere kam daa bojh samjho"],
        ["Lower your voice", "आवाज़ हौली करो", "aavaaz haulee karo"],
        ["I am not arguing for fun", "मैं मज़े लई नेईं बहस करदा", "main maze lai nein behas kardaa"],
        ["Let's solve this calmly", "ए शांति कोल हल करिए", "e shaanti kol hal karie"],
        ["Sorry, I spoke harshly", "माफ करो, मैं सख्त बोल्या", "maaf karo, main sakht bolyaa"],
        ["We are a family; we adjust", "असी परिवार आं; समायोजन करदे आं", "asi parivaar aan; samaayojan karde aan"],
        ["Divide chores fairly", "कम बराबर बांड़ो", "kam baraabar baando"],
        ["Children are listening", "बच्चे सुनदे आए", "bacche sunde aaey"],
        ["Let's talk after dinner", "रात दे खाने बाद गल्ल करिए", "raat de khaane baad gall karie"],
        ["I need respect too", "मिगी वी आदर चाहीदा", "migee vee aadar chaahidaa"],
        ["Hug and make peace", "गले लगो अते सुलह करो", "gale lago ate sulah karo"],
        ["Tomorrow will be better", "कल चंगा होगा", "kal changaa hogaa"],
    ],
}
