# Dogri Lesson 5 — Conversation practice, chunk A (chapter IDs 620–641).

LESSONS_S5A = {
    620: [
        ["Happy Diwali!", "दिवाली दियां बधाइयां!", "divaalee diyaan badhaaiyaan!"],
        ["May your home shine with lamps", "तुसां दा घर दीयें कोल चमके", "tusaan daa ghar deeyen kol chamke"],
        ["We light candles at dusk", "असी शाम ने मोमबत्तियां जगांदे आं", "asi shaam ne momabatiyaan jagaande aan"],
        ["Children burst crackers safely", "बच्चे सावधानी कोल पटाखे फोड़दे आए", "bacche saavadhaanee kol pataakhe forde aaey"],
        ["We worship Lakshmi tonight", "असी अज रात लक्ष्मी दी पूजा करांगे", "asi aj raat lakshmee dee pooja karaange"],
        ["Sweet shops are crowded", "मिठाई दियां दुकानां च भीड़ आए", "mithaai diyaan dukaanaan ch bheer aaey"],
        ["Wear new clothes today", "आज नवे कपड़े पाओ", "aaj nave kapde pao"],
        ["Share sweets with neighbours", "पड़ोसियां कोल मिठाइयां बांड़ो", "parosiyaan kol mithaaiyaan baando"],
        ["Diwali means victory of light", "दिवाली दा मतलब उजाले दी जित आए", "divaalee daa matalab ujaale dee jit aaey"],
        ["Come to our house for puja", "पूजा लई साडे घर आओ", "pooja lai saade ghar aao"],
        ["The whole city looks beautiful", "सारा शहर सोणा दिखदा आए", "saaraa shehar sonaa dikhdaa aaey"],
        ["We greet elders first", "असी पैह्लें बुज्जुर्गां नू नमस्कार करदे आं", "asi paihlen bujjurgaan noon namaskaar karde aan"],
        ["Fireworks should be careful", "पटाखे सावधानी कोल चलाओ", "pataakhe saavadhaanee kol chalaao"],
        ["May prosperity stay with you", "चढ़दी कला च रहो", "chhaddee kalaa ch raho"],
        ["After puja we eat sweets", "पूजा बाद असी मिठाइयां खांदे आं", "pooja baad asi mithaaiyaan khaande aan"],
        ["Happy festival to your family", "तुसां दे परिवार नू त्योहार दियां बधाइयां", "tusaan de parivaar noon tyauhaar diyaan badhaaiyaan"],
    ],
    621: [
        ["Hello / Namaste", "नमस्कार / जी आयां नूं", "namaskaar / ji aayaan noon"],
        ["How are you?", "तुस कैह् आए हो?", "tus kaih aaey ho?"],
        ["I am fine, thank you", "मैं ठीक आं, धन्नवाद", "main theek aan, dhannavaad"],
        ["What is your name?", "तुसां दा नां की आए?", "tusaan daa naan kee aaey?"],
        ["My name is Ravi", "मेरा नां रवि आए", "meraa naan ravi aaey"],
        ["Where are you from?", "तुस कुथों आए हो?", "tus kutthon aaey ho?"],
        ["I am from Jammu", "मैं जम्मू कोलों आं", "main jammu kolon aan"],
        ["Nice to meet you", "मिल के खुशी होई", "mil ke khushee hoee"],
        ["See you again", "फेर मिलांगे", "pher milaange"],
        ["Good morning", "सुप्रभात", "suprabhaat"],
        ["Good night", "शुभ रात्रि", "shubh raatri"],
        ["Take care", "ख्याल रखो", "khyaal rakho"],
        ["Welcome to our home", "साडे घर स्वागत आए", "saade ghar swaagat aaey"],
        ["Please sit", "बैठो", "baitho"],
        ["May I help you?", "की मैं मदद करां?", "kee main madad karaan?"],
        ["Thank you for coming", "आण लई धन्नवाद", "aan lai dhannavaad"],
    ],
    622: [
        ["What time is it?", "किन्ने वजे आए?", "kinne vaje aaey?"],
        ["It is seven o'clock", "सत्त वजे आए", "satt vaje aaey"],
        ["I will come at five", "मैं पंज वजे आमां", "main panj vaje aamaan"],
        ["Wait five minutes", "पाँच मिनट इंतज़ार करो", "paanch minat intazaar karo"],
        ["Today is Monday", "आज सोमवार आए", "aaj somavaar aaey"],
        ["Tomorrow is a holiday", "कल छुट्टी आए", "kal chhuttee aaey"],
        ["I woke up early", "मैं सवेर उठ्या", "main saver uthyaa"],
        ["The train leaves at noon", "ट्रेन दुपहर च चलदी आए", "train dupahar ch chaldee aaey"],
        ["We work from nine to five", "असी नौ कोलों पंज तक कम करदे आं", "asi nau kolon panj tak kam karde aan"],
        ["Last week I was busy", "पिछले हफ्ते मैं ब्यस्त सी", "pichhle hafte main byast see"],
        ["Next month we will travel", "अगले महीने असी सफर करांगे", "agale maheene asi safar karaange"],
        ["The shop opens at ten", "दुकान दस वजे खुलदी आए", "dukaan das vaje khuldee aaey"],
        ["I am late today", "मैं आज देर कोल आं", "main aaj der kol aan"],
        ["Hurry, it is getting dark", "जल्दी करो, अंधेरा होदा आए", "jaldee karo, andheraa hoda aaey"],
        ["See you tomorrow morning", "कल सवेर मिलांगे", "kal saver milaange"],
        ["The meeting starts soon", "मीटिंग जल्दी शुरू होगी", "meeting jaldee shuroo hogee"],
    ],
    623: [
        ["Where is the bus stand?", "बस स्टैंड कुथे आए?", "bas sttend kuthe aaey?"],
        ["It is near the temple", "ओ मंदिर कोल आए", "o mandir kol aaey"],
        ["How far is the airport?", "एयरपोर्ट किन्ना दूर आए?", "airport kinnaa door aaey?"],
        ["About ten kilometres", "लगभग दस किलोमीटर", "lagabhag das kilomeetar"],
        ["Is there a hotel nearby?", "की नेड़े कोई होटल आए?", "kee nedde koee hotel aaey?"],
        ["Turn left from the crossing", "चौक कोलों खब्बे मुड़ो", "chauk kolon khabbe mudo"],
        ["The road goes to the village", "रस्ता पेंड नू जांदा आए", "rastaa pend noon jaandaa aaey"],
        ["I am lost; help me", "मैं रस्ता भुल गया; मदद करो", "main rastaa bhul gayaa; madad karo"],
        ["This is the right address", "ए ठीक पता आए", "e theek pataa aaey"],
        ["The park is behind the school", "पार्क सकूल पिछे आए", "paark sakool pichhe aaey"],
        ["Can you show on the map?", "की तुस नक्शे उत्ते दिखा सकदे हो?", "kee tus nakshe ute dikhaa sakde ho?"],
        ["We live on the second floor", "असी दूजे मंजिल उत्ते रेंदे आं", "asi dooje manzil ute rende aan"],
        ["The river is beyond those trees", "नदी ओ रुखां पार आए", "nadee o rukhaan paar aaey"],
        ["Is this the way to Katra?", "की ए रस्ता कटड़ा नू जांदा आए?", "kee e rastaa katrraa noon jaandaa aaey?"],
        ["Stop at the red light", "लाल बत्ती उत्ते रुको", "laal battee ute ruko"],
        ["The bridge is under repair", "पुल मरम्मत च आए", "pul murammat ch aaey"],
    ],
    624: [
        ["I need a room for two nights", "मिगी दो रातां लई कमरा चाहिदा आए", "migee do raataan lai kamraa chaahidaa aaey"],
        ["Is breakfast included?", "की नाश्ता शामल आए?", "kee naashataa shaamal aaey?"],
        ["Please give the room key", "किरपा करियै कमरे दी चाबी देओ", "kirpaa kariyai kamre dee chaabee deo"],
        ["The AC is not working", "एसी कम नेईं करदा", "AC kam nein kardaa"],
        ["Can I get extra towels?", "की होर तौलिए मिल सकदे आए?", "kee hor tauliye mil sakde aaey?"],
        ["What time is checkout?", "चेकआउट किन्ने वजे आए?", "chekaaut kinne vaje aaey?"],
        ["Please call a taxi", "किरपा करियै टैक्सी बुलाओ", "kirpaa kariyai taiksee bulaa"],
        ["The bill is too high", "बिल बड़ा चढ़या आए", "bil baraa chadyaa aaey"],
        ["I booked online", "मैं ऑनलाइन बुक कीता", "main online buk keetaa"],
        ["Water in the bathroom is cold", "बाथरूम च पाणी ठंडा आए", "baathroom ch paanee thandaa aaey"],
        ["Send food to room 204", "खाना कमरा 204 च भेजो", "khaanaa kamraa 204 ch bhejo"],
        ["Is Wi‑Fi free?", "की वाई-फाई फ्री आए?", "kee vaai-faai free aaey?"],
        ["The lift is on the left", "लिफ्ट खब्बे पासे आए", "lift khabbe paase aaey"],
        ["Please keep luggage safe", "सामान सुरक्षित रखो", "samaan surakshit rakho"],
        ["I want to extend one day", "मैं इक दिन होर रहना चांदा आं", "main ik din hor rahanaa chaandaa aan"],
        ["Thank you for your hospitality", "तुसां दी मेहमाननवाज़ी लई धन्नवाद", "tusaan dee mehmaananaavaazee lai dhannavaad"],
    ],
    625: [
        ["It is very hot today", "आज बड़ा गरम आए", "aaj baraa garam aaey"],
        ["Winter is very cold here", "इत्थे सर्दी बड़ी सख्त आए", "itthe sardee baree sakht aaey"],
        ["It may rain tomorrow", "कल मींह पै सकदा आए", "kal meenh pai sakdaa aaey"],
        ["The wind is strong", "हवा तेज़ आए", "havaa tez aaey"],
        ["Take an umbrella", "छाता लेआओ", "chaataa leaao"],
        ["Fog on the highway", "हाईवे उत्ते कोहरा आए", "haai ve ute koharaa aaey"],
        ["The weather is pleasant", "मौसम सुहावना आए", "mausam suhaavanaa aaey"],
        ["Summer starts in April", "गर्मी अप्रैल च शुरू होंदी आए", "garmee aprail ch shuroo hondee aaey"],
        ["I like rainy season", "मिगी मींह दा मौसम पसंद आए", "migee meenh daa mausam pasand aaey"],
        ["Climate is changing", "मौसम बदलदा आए", "mausam badaldaa aaey"],
        ["Wear warm clothes", "गरम कपड़े पाओ", "garam kapde pao"],
        ["The fan is enough tonight", "अज रात पंखा काफी आए", "aj raat pankhaa kaafee aaey"],
        ["Lightning flashed", "बिजली चमकी", "bijlee chamkee"],
        ["Flood in the river", "नदी च बाढ़ आई", "nadee ch baarh aaee"],
        ["Beautiful clouds in the sky", "आकाश च सोणे बादल", "aakaash ch sone baadal"],
        ["Storm may come; stay inside", "तूफान आ सकदा आए; अंदर रहो", "toofaana aa sakdaa aaey; andar raho"],
    ],
    626: [
        ["Sir, my licence please", "साहब, मेरी लाइसेंस दिखो", "saahab, meree laisens dikho"],
        ["I was not speeding", "मैं ओवरस्पीड नेईं करदा सी", "main overspeed nein kardaa see"],
        ["Here is the RC and insurance", "ए आरसी अते बीमा आए", "e arasee ate beemaa aaey"],
        ["I will wear the helmet now", "मैं हुन हेलमेट पामां", "main hun helmeet paamaan"],
        ["Sorry, I parked wrong", "माफ करो, गलत पार्क कीता", "maaf karo, galat paark keetaa"],
        ["Where should I pay the fine?", "मिगी जुर्माना कुथे भरना आए?", "migee jurmaanaa kuthe bharnaa aaey?"],
        ["Is this a one‑way road?", "की ए इक-पासी रस्ता आए?", "kee e ik-paasee rastaa aaey?"],
        ["The signal was green", "सिग्नल हरा सी", "signal haraa see"],
        ["My documents are complete", "मेरे कागज पूरे आए", "mere kaagaz poore aaey"],
        ["Thank you, officer", "धन्नवाद, ओफिसर", "dhannavaad, ofisar"],
        ["I will follow traffic rules", "मैं ट्रैफिक नियम मनांगा", "main traifik niyam manaanga"],
        ["Is there a checking ahead?", "की अग्गे चेकिंग आए?", "kee agge cheking aaey?"],
        ["My vehicle papers are valid", "मेरे गड्डी दे कागज ठीक आए", "mere gaddee de kaagaz theek aaey"],
        ["Please guide me to the RTO", "आरटीओ वल दिखाओ", "aarteeo val dikhaao"],
        ["I did not jump the red light", "मैं लाल बत्ती नेईं कुट्टी", "main laal battee nein kuttee"],
        ["Drive safely", "सुरक्षित चलाओ", "surakshit chalaao"],
    ],
    627: [
        ["How much to the railway station?", "रेलवे स्टेशन किन्ने पैसे?", "relave stteshan kinne paise?"],
        ["Please use the meter", "किरपा करियै मीटर लगाओ", "kirpaa kariyai meetar lagaa"],
        ["Stop here near the gate", "गेट कोल इत्थे रोको", "get kol itthe roko"],
        ["Keep the change", "बकाया रख लो", "bakaayaa rakh lo"],
        ["Is this the shortest route?", "की ए सब कोलों छोटा रस्ता आए?", "kee e sab kolon chhottaa rastaa aaey?"],
        ["Don't take a long detour", "लंबा चक्कर ना लाओ", "lambaa chakkar na laao"],
        ["I am in a hurry", "मैं जल्दी च आं", "main jaldee ch aan"],
        ["Please drive slowly on bumps", "उबड़-खाबड़ उत्ते हौले चलाओ", "ubar-khaabar ute haule chalaao"],
        ["Drop me at the main road", "मिगी मुख्य रस्ते उत्ते उतार देओ", "migee mukhy raste ute utaar deo"],
        ["The fare seems high", "किराया ज्यादा लगदा आए", "kiraayaa zyaadaa lagdaa aaey"],
        ["Can you help with the bags?", "की तुस बैग च चुक सकदे हो?", "kee tus baeg ch chuk sakde ho?"],
        ["Wait two minutes, I am coming", "दो मिनट इंतज़ार करो, मैं आंदा आं", "do minat intazaar karo, main aandaa aan"],
        ["Turn on the AC please", "एसी चलाओ", "AC chalaa"],
        ["Is Ola/Uber available here?", "की इत्थे ओला/उबर मिलदा आए?", "kee itthe ola/ubar mildaa aaey?"],
        ["Thank you; here is your money", "धन्नवाद; लो पैसे", "dhannavaad; lo paise"],
        ["Have a safe day", "सुरक्षित रहो", "surakshit raho"],
    ],
    628: [
        ["We deploy on Friday", "असी शुक्रवार नू डिप्लॉय करांगे", "asi shukravaar noon deploy karaange"],
        ["The build failed in CI", "सीआई च बिल्ड फेल होई", "seeaaee ch bild fail hoee"],
        ["Please review my pull request", "मेरा पुल रिक्वेस्ट रिव्यू करो", "meraa pul rikvest rivyoo karo"],
        ["Let's sync in the stand‑up", "स्टैंड-अप च सिंक करिए", "sttend-ap ch sink karie"],
        ["I will push the fix tonight", "मैं आज रात फिक्स पुश करांगा", "main aaj raat fiks push karaangaa"],
        ["The bug is reproducible", "बग दुबारा हो सकदा आए", "bag dubaraa ho sakdaa aaey"],
        ["We need more test coverage", "सानू होर टेस्ट कवरेज चाहीदी आए", "saanoo hor test kavaraj chaahidee aaey"],
        ["The API latency is high", "एपीआई लेटेंसी बड़ी आए", "epeeai letensee baree aaey"],
        ["Let's pair program on this", "इस उत्ते पेयर प्रोग्रामिंग करिए", "is ute peyar prograaming karie"],
        ["I am on leave tomorrow", "मैं कल छुट्टी उत्ते आं", "main kal chuttee ute aan"],
        ["The client wants a demo", "क्लाइंट डेमो चांदा आए", "klaaaint demo chaandaa aaey"],
        ["VPN is not connecting", "वीपीएन कनेक्ट नेईं होदा", "veepien connect nein hoda"],
        ["Please share the log file", "लॉग फाइल शेयर करो", "log faail share karo"],
        ["We follow agile in our team", "साडी टीम एजाइल च कम करदी आए", "saadee teem ejaail ch kam kardee aaey"],
        ["The sprint ends next week", "स्प्रिंट अगले हफ्ते मुक्कदी आए", "sprint agale hafte mukkadee aaey"],
        ["Great job on the release", "रिलीज उत्ते शाबाश", "rilij ute shaabaash"],
    ],
    629: [
        ["Half a kilo of potatoes", "आलू आधा किलो", "aaloo aadhaa kilo"],
        ["Is this fresh?", "की ए ताज़ा आए?", "kee e taazaa aaey?"],
        ["The price went up today", "आज रेट चढ़या", "aaj ret chadyaa"],
        ["Give coriander as well", "धनिया वी देओ", "dhaniyaa vee deo"],
        ["I need three lemons", "मिगी तिन नींबू", "migee tin neemboo"],
        ["Do you have organic vegetables?", "की तुस ऑर्गेनिक सब्जी रखदे हो?", "kee tus aariganik sabzee rakhde ho?"],
        ["This looks wilted", "ए मुरझाया दिखदा आए", "e murjhaayaa dikhdaa aaey"],
        ["Pack separately", "अलग-अलग पैक करो", "alag-alag paik karo"],
        ["I will pay by UPI", "मैं यूपीआई कोलों भरांगा", "main yoopeeai kolon bharaangaa"],
        ["Give a receipt", "रसीद देओ", "raseed deo"],
        ["The onions are strong", "गांदे तेज़ आए", "gaande tez aaey"],
        ["Any discount today?", "की आज छूट आए?", "kee aaj chhoot aaey?"],
        ["I shop here every week", "मैं हर हफ्ते इत्थे लैंदा आं", "main har hafte itthe laindaa aan"],
        ["Keep the change", "बकाया रख लो", "bakaayaa rakh lo"],
        ["Where is the weighing scale?", "तराजू कुथे आए?", "taraajoo kuthe aaey?"],
        ["Thank you, brother", "धन्नवाद, भैया", "dhannavaad, bhaiyaa"],
    ],
    630: [
        ["Doctor, I have fever since yesterday", "डाक्टर, मिगी कल कोल बुखार आए", "daaktar, migee kal kol bukhaar aaey"],
        ["Any cough or cold?", "की खांस अते जुकाम आए?", "kee khaans ate jukaam aaey?"],
        ["Take this medicine twice a day", "ए दवाई दिन च दो वार लो", "e davaaee din ch do vaar lo"],
        ["Drink plenty of water", "बड़ा पाणी पीओ", "baraa paanee peo"],
        ["Get blood tests done", "ब्लड टेस्ट कराओ", "bladd test karaao"],
        ["Avoid spicy food", "तीखा खाना छड़ो", "teekhaa khaanaa chhado"],
        ["Rest for three days", "तिन दिन आराम करो", "tin din aaraam karo"],
        ["Come back after a week", "इक हफ्ते बाद मिलो", "ik hafte baad milo"],
        ["Is an X‑ray needed?", "की एक्स-रे जरूरी आए?", "kee eks-re jaroori aaey?"],
        ["The pain is in the chest", "दर्द छाती च आए", "dard chaatee ch aaey"],
        ["I am allergic to penicillin", "मिगी पेनिसिलिन कोल एलर्जी आए", "migee penisilin kol alarjee aaey"],
        ["Nurse will give the injection", "नर्स इंजेक्शन लगाएगी", "nars injekshan lagaayagee"],
        ["Hospital timings?", "हस्पताल दे वक्त?", "haspataal de vakt?"],
        ["Emergency is on the ground floor", "इमरजेंसी ग्राउंड फ्लोर उत्ते आए", "imarjensee graaund flor ute aaey"],
        ["Thank you, doctor", "धन्नवाद, डाक्टर", "dhannavaad, daaktar"],
        ["I feel better now", "मैं हुन ठीक महसूस करदा आं", "main hun theek mahasoos kardaa aan"],
    ],
    631: [
        ["Good morning, teacher", "सुप्रभात, मास्टर जी", "suprabhaat, maastar jee"],
        ["May I enter the class?", "की मैं क्लास च आ सकदा आं?", "kee main klaas ch aa sakdaa aan?"],
        ["I completed the homework", "मैं होमवर्क मुकाया", "main homavark mukaayaa"],
        ["Can you explain this sum?", "की तुस ए सवाल समझा सकदे हो?", "kee tus e savaal samjhaa sakde ho?"],
        ["The exam is next Monday", "परीक्षा अगले सोमवार आए", "pareekshaa agale somavaar aaey"],
        ["Please speak louder", "जोर कोल बोलो", "zor kol bolo"],
        ["Group discussion tomorrow", "कल ग्रुप डिस्कशन आए", "kal grap diskashan aaey"],
        ["I will submit the project online", "मैं प्रोजेक्ट ऑनलाइन जमा करांगा", "main projekt online jama karaangaa"],
        ["May I ask a doubt?", "की मैं सवाल पुछ सकदा आं?", "kee main savaal puchh sakdaa aan?"],
        ["Library books due date?", "लाइब्रेरी किताब दी तारीख?", "laibreree kitaab dee taareekh?"],
        ["Sports period is last", "खेल दी पीरियड आखरी आए", "khel dee peiriod aakhree aaey"],
        ["Congratulations on your result", "नतीजे उत्ते बधाइयां", "nateeje ute badhaaiyaan"],
        ["Don't use mobile in class", "क्लास च मोबाइल ना वरतो", "klaas ch mobail na varato"],
        ["We will have a quiz today", "असी आज क्विज लमांगे", "asi aaj kwij lamaange"],
        ["Thank you for teaching Dogri", "डोगरी पढ़ौने लई धन्नवाद", "dogree padhaune lai dhannavaad"],
        ["See you tomorrow", "कल मिलांगे", "kal milaange"],
    ],
    632: [
        ["Hello, it's Ravi speaking", "हैलो, रवि बोलदा आं", "helo, ravi boldaa aan"],
        ["Is Priya there?", "की प्रिया इत्थे आए?", "kee priyaa itthe aaey?"],
        ["She is not at home right now", "ओ हले घरे नेईं आए", "o hale ghare nein aaey"],
        ["Can I leave a message?", "की मैं संदेश छड़ सकदा आं?", "kee main sandesh chhad sakdaa aan?"],
        ["Tell her to call me back", "ओने दस्सो मिगी फोन मुड़ करे", "one dasso migee fon mud kare"],
        ["The signal is weak", "सिग्नल कमजोर आए", "signal kamajor aaey"],
        ["I will WhatsApp the location", "मैं लोकेशन व्हाट्सऐप करांगा", "main lokeshan vhaatsaap karaangaa"],
        ["Sorry, wrong number", "माफ करो, गलत नंबर", "maaf karo, galat nambar"],
        ["Can you hear me?", "की तुस मिगी सुन सकदे हो?", "kee tus migee sun sakde ho?"],
        ["I'll call again in five minutes", "मैं पाँच मिनट बाद फेर फोन करांगा", "main paanch minat baad pher fon karaangaa"],
        ["Battery is dying", "बैटरी खत्म होदी आए", "baitaree khatam hondee aaey"],
        ["Talk to you later", "फेर गल्ल करांगे", "pher gall karaange"],
        ["I'm driving; I'll call back", "मैं गड्डी चलांदा आं; फेर फोन करां", "main gaddee chalaandaa aan; pher fon karaan"],
        ["Please text me the address", "पता मैसेज कर देओ", "pataa mesej kar deo"],
        ["Nice talking to you", "गल्ल करके चंगा लगा", "gall karke changaa lagaa"],
        ["Bye, take care", "बाय, ख्याल रखो", "baai, khyaal rakho"],
    ],
    633: [
        ["How much per kilo for tomatoes?", "टमाटर किलो किन्ने दा?", "tamaatar kilo kinne daa?"],
        ["These beans look fresh", "ए फलियां ताज़ा दिखदियां आए", "e faliyaan taazaa dikhdiyaan aaey"],
        ["Give one bundle of spinach", "इक गड्डी पालक देओ", "ik gadddee paalak deo"],
        ["Too expensive; reduce a little", "बड़ा महंगा; थोड़ा कटाओ", "baraa mahangaa; thoddaa kataao"],
        ["I need ginger and garlic", "मिगी अदरक अते लहसुन", "migee adrak ate lahasun"],
        ["Weigh one kilo potatoes", "इक किलो आलू तौलो", "ik kilo aaloo tau"],
        ["The market is crowded today", "आज बाज़ार च भीड़ आए", "aaj baazaar ch bheer aaey"],
        ["Carry the bag to my scooter", "बैग मेरी स्कूटर उत्ते रख देओ", "baeg meree skooter ute rakh deo"],
        ["Any discount for regular customers?", "की रेगुलर ग्राहकां लई छूट आए?", "kee regulr graahakaan lai chhoot aaey?"],
        ["This pumpkin is sweet", "ए कद्दू मिठा आए", "e kaddoo mitthaa aaey"],
        ["I will come every Sunday", "मैं हर ऐतवार आमां", "main har aitavaar aamaan"],
        ["Keep separate bills", "अलग बिल बनाओ", "alag bil banaao"],
        ["Organic vegetables there", "उत्थे ऑर्गेनिक सब्जी मिलदी आए", "utthe aariganik sabzee mildee aaey"],
        ["Wash before cooking", "रांधने कोलों पैह्लें धोओ", "raadhne kolon paihlen dhoo"],
        ["Thank you, see you next week", "धन्नवाद, अगले हफ्ते मिलांगे", "dhannavaad, agale hafte milaange"],
        ["Have a good day", "चंगा दिन रहे", "changaa din rahe"],
    ],
    634: [
        ["Which bus goes to the city?", "केड़ी बस शहर जांदी आए?", "keddee bas shehar jaandee aaey?"],
        ["The next bus is in ten minutes", "अगली बस दस मिनट च आए", "agalee bas das minat ch aaey"],
        ["Is this seat free?", "की ए सीट खाली आए?", "kee e seet khaalee aaey?"],
        ["Please move inside", "किरपा करियै अंदर चलो", "kirpaa kariyai andar chalo"],
        ["Where should I get down?", "मिगी कुथे उतरना आए?", "migee kuthe utarnaa aaey?"],
        ["Conductor, one ticket to Katra", "कंडक्टर, कटड़े दा इक टिकट", "kandaktr, katdde daa ik tikat"],
        ["Keep luggage in the rack", "सामान रैक च रखो", "samaan raik ch rakho"],
        ["The bus is crowded", "बस भीड़ च आए", "bas bheer ch aaey"],
        ["Is there an AC bus?", "की एसी बस मिलदी आए?", "kee AC bas mildee aaey?"],
        ["The stop is announced", "स्टॉप दस्सी जांदी आए", "sttop dassi jaandee aaey"],
        ["Don't stand near the door", "दरवाजे कोल ना खड़ो", "daravaaje kol na khado"],
        ["I missed my stop", "मेरा स्टॉप छूट गया", "meraa sttop chhoot gayaa"],
        ["Is this the express?", "की ए एक्सप्रेस आए?", "kee e ekspres aaey?"],
        ["How long is the journey?", "सफर किन्ना लंबा आए?", "safar kinnaa lambaa aaey?"],
        ["Thank you, driver", "धन्नवाद, ड्राइवर", "dhannavaad, draivar"],
        ["Have a safe trip", "सफर सुरक्षित रहे", "safar surakshit rahe"],
    ],
    635: [
        ["Excuse me, where is this lane?", "माफ करो, ए गली कुथे जांदी आए?", "maaf karo, e gallee kuthe jaandee aaey?"],
        ["How far is the post office?", "डाकघर किन्ना दूर आए?", "daakghar kinnaa door aaey?"],
        ["Take the second left", "दूजा खब्बा लो", "doojaa khabbaa lo"],
        ["It is opposite the school", "ओ सकूल दे सामने आए", "o sakool de saamne aaey"],
        ["Ask anyone there; they know", "उत्थे किसे कोल पुछ लो; सब जांदे आए", "utthe kise kol puchh lo; sab jaande aaey"],
        ["The house number is 42", "घर नंबर बयाली आए", "ghar nambar bayaalee aaey"],
        ["Near the temple, not the mosque", "मंदिर कोल, मस्जिद नेईं", "mandir kol, masjid nein"],
        ["Can you write the address?", "की तुस पता लिख सकदे हो?", "kee tus pataa likh sakde ho?"],
        ["I will put it in maps", "मैं मैप च पा दिंदा आं", "main maip ch paa dindaa aan"],
        ["Landmark is the big banyan tree", "निशान बड़ा बरगद आए", "nishaan baraa bargad aaey"],
        ["Ring the bell twice", "घंटी दो वार बजाओ", "ghantee do vaar bajaao"],
        ["Is this the correct pin code?", "की ए ठीक पिन कोड आए?", "kee e theek pin kod aaey?"],
        ["The lane is one‑way", "ए गली इक-पासी आए", "e gallee ik-paasee aaey"],
        ["Thank you for guiding", "रस्ता दस्सने लई धन्नवाद", "rastaa dassne lai dhannavaad"],
        ["I found the house", "मिगी घर लब्भ गया", "migee ghar labbh gayaa"],
        ["Goodbye", "फिर मिलांगे", "phir milaange"],
    ],
    636: [
        ["I like you very much", "मिगी तुस बड़े पसंद आए", "migee tus bare pasand aaey"],
        ["Will you be my friend?", "की तुस मेरे दोस्त बनोगे?", "kee tus mere dost banoge?"],
        ["You mean a lot to me", "तुस मेरे लई बड़े मायने रखदे हो", "tus mere lai bare maayane rakhde ho"],
        ["I want to spend time with you", "मैं तुसां कोल समें गज्जाणा चांदा आं", "main tusaan kol samen gajjaanaa chaandaa aan"],
        ["May I walk you home?", "की मैं तुसां नू घर तिक लै चलां?", "kee main tusaan noon ghar tak lai chalaan?"],
        ["You have a beautiful smile", "तुसां दी मुस्कान बड़ी सोणी आए", "tusaan dee muskaan baree sonee aaey"],
        ["I respect your feelings", "मैं तुसां दियां भावनां दा आदर करदा आं", "main tusaan diyaan bhavanaan daa aadar kardaa aan"],
        ["Let's meet again soon", "फेर जल्दी मिलदे आं", "pher jaldee milde aan"],
        ["I wrote this for you", "मैं ए तुसां लई लिख्या", "main e tusaan lai likhyaa"],
        ["Happy Valentine's Day", "वैलेंटाइन दिवस दियां बधाइयां", "vailentain divas diyaan badhaaiyaan"],
        ["You are special to me", "तुस मेरे लई खास आए", "tus mere lai khaas aaey"],
        ["Can we talk privately?", "की असी इकल्ले च गल्ल कर सकदे आं?", "kee asi ikalle ch gall kar sakde aan?"],
        ["I promise to care for you", "मैं तुसां दा ख्याल रखने दा वादा करदा आं", "main tusaan daa khyaal rakhne daa vaadaa kardaa aan"],
        ["Thank you for understanding", "समझने लई धन्नवाद", "samajhne lai dhannavaad"],
        ["Whatever you decide, I respect it", "जो भी तुस फैसला करो, मैं आदर करदा आं", "jo bhee tus faislaa karo, main aadar kardaa aan"],
        ["Wishing you happiness", "तुसां नू खुशियां", "tusaan noon khushiyaan"],
    ],
    637: [
        ["Tell me about yourself", "अपने बारे दस्सो", "apne baare dasso"],
        ["Why do you want this job?", "तुस ए नौकरी कियों चांदे हो?", "tus e naukaree kyon chaande ho?"],
        ["My strengths are teamwork", "मेरी ताकत टीम वर्क आए", "meree taakat teem vark aaey"],
        ["I have three years' experience", "मेरे तिन साल दा तजुर्बा आए", "mere tin saal daa tajurbaa aaey"],
        ["My expected salary is…", "मेरी उम्मीद तनखाह … आए", "meree ummeed tanakhaah … aaey"],
        ["I can join next month", "मैं अगले महीने जॉइन कर सकदा आं", "main agale maheene join kar sakdaa aan"],
        ["I am willing to relocate", "मैं ट्रांसफर लई तैयार आं", "main traansfar lai taiyaar aan"],
        ["How do you handle pressure?", "तुस दबाव कोल की करदे हो?", "tus dabaav kol kee karde ho?"],
        ["Describe a difficult project", "इक अखे प्रोजेक्ट दस्सो", "ik akhe projekt dasso"],
        ["Where do you see yourself in five years?", "पाँज साल बाद अपने नू कुथे वेखदे हो?", "paanj saal baad apne noon kuthe vekhde ho?"],
        ["Any questions for us?", "की साडे कोल कोई सवाल आए?", "kee saade kol koee savaal aaey?"],
        ["Thank you for this opportunity", "ए मौका देने लई धन्नवाद", "e mauka dene lai dhannavaad"],
        ["I will send documents by email", "मैं कागज ईमेल कोलों भेज दिंगा", "main kaagaz eemel kolon bhej dingaa"],
        ["I am comfortable with Dogri and Hindi", "मैं डोगरी अते हिंदी च सहज आं", "main dogree ate hindee ch sahaj aan"],
        ["When can I expect the result?", "नतीजा कदों मिलेगा?", "nateejaa kadon milegaa?"],
        ["Goodbye; hope to work with you", "अलविदा; उम्मीद आए साथ कम करां", "alvida; ummeed aaey saath kam karaan"],
    ],
    638: [
        ["Please clean the kitchen today", "किरपा करियै अज रसोई साफ करो", "kirpaa kariyai aj rasoee saaf karo"],
        ["Wash clothes twice a week", "हफ्ते च दो वार कपड़े धोओ", "hafte ch do vaar kapde dhoo"],
        ["The floor needs mopping", "फर्श पोंछना आए", "farsh ponchnaa aaey"],
        ["I will pay salary on the fifth", "मैं पंज तक तनखाह देआंगा", "main panj tak tanakhaah deaanga"],
        ["Take Sunday off", "ऐतवार छुट्टी रखो", "aitavaar chuttee rakho"],
        ["Please lock the door when you leave", "जांदे वेले दरवाजा बंद करो", "jaande vele daravaajaa band karo"],
        ["Vegetables are in the fridge", "सब्जी फ्रिज च आए", "sabzee frij ch aaey"],
        ["Don't use too much detergent", "ज्यादा डिटर्जेंट ना वरतो", "zyaadaa dittrjent na varato"],
        ["Call me if there is a problem", "मुसीबत होवे त फोन करियो", "museebat hove ta fon kariyo"],
        ["Iron these shirts", "ए कमीज़ इस्त्री करो", "e kameez istree karo"],
        ["Guests are coming; tidy the hall", "मेहमान आनगे; हाल सजाओ", "mehmaan aanage; haal sajaao"],
        ["Water the plants on the balcony", "बालकनी च पौधे नू पाणी देओ", "baalkanee ch paude noon paanee deo"],
        ["Keep the keys on the table", "चाबी मेज उत्ते रखो", "chaabee mej ute rakho"],
        ["I trust your work", "मैं तुसां दे कम पर भरोसा करदा आं", "main tusaan de kam par bharosaa kardaa aan"],
        ["Take care of yourself", "अपना ख्याल रखो", "apnaa khyaal rakho"],
        ["Thank you for your help", "मदद लई धन्नवाद", "madad lai dhannavaad"],
    ],
    639: [
        ["Open the Aadhaar app", "आधार ऐप खोलो", "aadhaar aip kholo"],
        ["Enter your mobile number", "अपना मोबाइल नंबर पाओ", "apnaa mobail nambar pao"],
        ["You will get an OTP", "तुसां नू ओटीपी मिलेगी", "tusaan noon oteepee milegee"],
        ["Enter OTP to verify", "वेरीफाई लई ओटीपी पाओ", "verifaai lai oteepee pao"],
        ["Linking is successful", "लिंक हो गया", "link ho gayaa"],
        ["If it fails, try again later", "जे फेल होवे त फेर कोशिश करो", "je fail hove ta pher koshish karo"],
        ["Keep your Aadhaar safe", "अपना आधार सुरक्षित रखो", "apnaa aadhaar surakshit rakho"],
        ["Do not share OTP with anyone", "ओटीपी किसे कोल ना देओ", "oteepee kise kol na deo"],
        ["Use only official apps", "सिर्फ ऑफिशियल ऐप वरतो", "sirph ofishiyal aip varato"],
        ["Update your mobile if changed", "मोबाइल बदल्या त अपडेट करो", "mobail badalyaa ta apadet karo"],
        ["Helpline number is on the website", "हेल्पलाइन नंबर वेबसाइट उत्ते आए", "helplain nambar vebsaitt ute aaey"],
        ["Carry original ID for verification", "वेरीफिकेशन लई असली आईडी लेआओ", "verifikeshan lai asalee aaiddee leaao"],
        ["The shopkeeper can help scan", "दुकानदार स्कैन च मदद कर सकदा आए", "dukaandaar skain ch madad kar sakdaa aaey"],
        ["Check SMS for confirmation", "पक्के लई एसएमएस वेखो", "pakke lai esemes vekho"],
        ["Logout after finishing", "मुक्के बाद लॉगआउट करो", "mukke baad logaaut karo"],
        ["Your data is protected", "तुसां दा डाटा सुरक्षित आए", "tusaan daa daataa surakshit aaey"],
    ],
    640: [
        ["Open mobile settings", "मोबाइल सेटिंग खोलो", "mobail seting kholo"],
        ["Go to SIM card settings", "सिम कार्ड सेटिंग च जाओ", "sim kaard seting ch jaao"],
        ["Select Aadhaar linking option", "आधार लिंक दा विकल्प चुनो", "aadhaar link daa vikalp chuno"],
        ["Enter Aadhaar number carefully", "आधार नंबर ध्यान कोल पाओ", "aadhaar nambar dhyaan kol pao"],
        ["OTP will come on registered mobile", "रजिस्टर्ड मोबाइल उत्ते ओटीपी आवेगी", "rajistardd mobail ute oteepee aavegee"],
        ["Do not share the OTP", "ओटीपी शेयर ना करो", "oteepee share na karo"],
        ["Linking may take a few minutes", "लिंक होने च कुछ मिनट लग सकदे आए", "link hone ch kuchh minat lag sakde aaey"],
        ["If wrong, recheck the number", "गलत होवे त नंबर फेर चेक करो", "galat hove ta nambar pher chek karo"],
        ["Visit the telecom store if needed", "लोड़ पवे त टेलीकॉम स्टोर जाओ", "lorr pave ta teleekom stor jaao"],
        ["Carry Aadhaar and ID proof", "आधार अते पहचान पत्र लेआओ", "aadhaar ate pehchaan patr leaao"],
        ["Official website has FAQs", "ऑफिशियल वेबसाइट उत्ते सवाल-जवाब आए", "ofishiyal vebsaitt ute savaal-jawaab aaey"],
        ["Beware of fake links", "नकली लिंक कोलों सावधान", "nakalee link kolon saavadhaan"],
        ["Customer care can guide", "कस्टमर केयर दिखा सकदी आए", "kastmar keer dikhaa sakdee aaey"],
        ["Keep transaction SMS", "लेन-देन दा एसएमएस रखो", "len-den daa esemes rakho"],
        ["Update KYC if asked", "केवाईसी अपडेट मंगे त करो", "kevaaiisee apadet mange ta karo"],
        ["Your number is now verified", "तुसां दा नंबर हुन वेरीफाई हो गया", "tusaan daa nambar hun verifaai ho gayaa"],
    ],
    641: [
        ["Long live the Republic!", "गणतंत्र जिंदाबाद!", "ganatantra zindaabaad!"],
        ["We hoist the flag at dawn", "असी सवेर झंडा फहरांदे आं", "asi saver jhandaa phahraande aan"],
        ["The parade is beautiful", "परेड बड़ी सोणी आए", "paredd baree sonee aaey"],
        ["Children sing the anthem", "बच्चे राष्ट्रगीत गांदे आए", "bacche rashtrageet gaande aaey"],
        ["We remember the Constitution", "असी संविधान नू याद करदे आं", "asi sanvidhaan noon yaad karde aan"],
        ["Tri‑colour sweets in the market", "बाज़ार च तिरंगा मिठाइयां", "baazaar ch tirangaa mithaaiyaan"],
        ["Everyone feels proud", "सब नू नाज़ आए", "sab noon naaz aaey"],
        ["Schools have a holiday", "सकूलां च छुट्टी आए", "sakoolaan ch chuttee aaey"],
        ["We watch the ceremony on TV", "असी टीवी उत्ते समारोह वेखदे आं", "asi TV ute samaaroh vekhde aan"],
        ["Guests are invited", "मेहमान बुलाए गे", "mehmaan bulaae ge"],
        ["The band plays patriotic songs", "बैंड देशभक्ति गीत बजांदा आए", "baind deshbhakti geet bajaandaa aaey"],
        ["Fly kites in the evening", "शाम ने पतंग उड़ाओ", "shaam ne patang udaao"],
        ["Respect the national symbols", "राष्ट्रीय निशानां दा आदर करो", "rashtreey nishaanaan daa aadar karo"],
        ["Happy Republic Day!", "गणतंत्र दिवस दियां बधाइयां!", "ganatantra divas diyaan badhaaiyaan!"],
        ["Jai Hind!", "जय हिंद!", "jay hind!"],
        ["Unity in diversity", "अनेकता च एकता", "anekataa ch ekataa"],
    ],
}
