# Dogri Lesson 3 — chunk A (chapter IDs 543–565). Rows: English, Dogri (Devanagari), Transliteration.

LESSONS_S3A = {
    543: [
        ["I am going to eat now", "हुन मैं खाण जारहा आं", "hun main khaan jaarahaa aan"],
        ["She is going to read", "ओ पढ़ण जारही आए", "o padhan jaarahee aaey"],
        ["We are going to Jammu tomorrow", "असी कल जम्मू जारहे आं", "asi kal jammu jaarehe aan"],
        ["He is going to call you", "ओ तुसां फोन करण जारहा आए", "o tusaan fon karan jaarahaa aaey"],
        ["They are going to leave", "ओ जाण जारहे आए", "o jaan jaarehe aaey"],
        ["It is going to rain today", "आज मींह पैण जारहा आए", "aaj meenh pain jaarahaa aaey"],
        ["I am going to try my best", "मैं अपनी पूरी कोशिश करण जारहा आं", "main apanee pooree koshish karan jaarahaa aan"],
        ["Are you going to come?", "तुस आण जारहे हो?", "tus aan jaarehe ho?"],
        ["What are you going to do?", "तुस की करण जारहे हो?", "tus kee karan jaarehe ho?"],
        ["I am going to sleep early", "मैं जल्दी सौण जारहा आं", "main jaldee saun jaarahaa aan"],
        ["The bus is going to start", "बस चलण लगी आए", "bus chalan lagee aaey"],
        ["I am going to buy vegetables", "मैं सब्जी खरीदण जारहा आं", "main sabzee kharidan jaarahaa aan"],
        ["She is going to cook rice", "ओ चोल रांधण जारही आए", "o chol raandhan jaarahee aaey"],
        ["We are going to meet at the temple", "असी मंदिर मिलण जारहे आं", "asi mandir milan jaarehe aan"],
        ["He is not going to tell lies", "ओ झूठ नेईं बोलण जारहा", "o jhoot nein bolan jaarahaa"],
        ["I am going to learn Dogri", "मैं डोगरी सिखण जारहा आं", "main dogree sikhan jaarahaa aan"],
        ["Nothing is going to change", "कुछ नेईं बदलण जारहा", "kuchh nein badalan jaarahaa"],
    ],
    544: [
        ["I used to play in this street", "मैं ए गली च खेड़दा हेंदा", "main e gallee ch kheddaa hendaa"],
        ["He used to walk every morning", "ओ हर सवेर टहलदा हेंदा", "o har saver tahaldaa hendaa"],
        ["We used to live in the village", "असी पेंड च रेंदे हेंदे", "asi pend ch rende hende"],
        ["She used to sing well", "ओ चंगा गांदी हेंदी", "o changaa gaandee hendee"],
        ["They used to visit us often", "ओ अक्सर असें मिलदे हेंदे", "o aksar asen milde hende"],
        ["I used to fear the dark", "मैं अंधेरे कोलों डरदा हेंदा", "main andhere kolon dardaa hendaa"],
        ["Mother used to wake up early", "माँ सवेर उठदी हेंदी", "maa saver uthdee hendee"],
        ["He used to work in the fields", "ओ खेतें च कम करदा हेंदा", "o kheten ch kam kardaa hendaa"],
        ["We used to eat together", "असी इकठ्ठे खांदे हेंदे", "asi ikatthe khaande hende"],
        ["It used to be very cold here", "इत्थे बड़ा ठंडा होंदा हेंदा", "itthe baraa thandaa honda hendaa"],
        ["I used to read the newspaper", "मैं अखबार पढ़दा हेंदा", "main akhbaar padhdaa hendaa"],
        ["You used to help everyone (informal)", "तू सबदी मदद करदा हेंदा", "tu sabdee madad kardaa hendaa"],
        ["The shop used to open late", "दुकान देर कोल खुलदी हेंदी", "dukaan der kol khuldee hendee"],
        ["Children used to play outside", "बच्चे बाहर खेड़दे हेंदे", "bacche baahar khedde hende"],
        ["I used to go by bus", "मैं बस च जांदा हेंदा", "main bas ch jaandaa hendaa"],
        ["Grandfather used to tell stories", "दादा कहाणियां सुनोंदा हेंदा", "daadaa kahaaniyaan sunondaa hendaa"],
        ["We used to bathe in the river", "असी नदी च न्होंदे हेंदे", "asi nadee ch nhonde hende"],
    ],
    545: [
        ["Long ago I used to study here", "पैह्लें मैं इत्थे पढ़दा था", "paihlen main itthe padhdaa thaa"],
        ["In those days he used to travel on foot", "उस वेले ओ पैदल जांदा था", "us vele o paidal jaandaa thaa"],
        ["People used to respect elders more", "लोक बुज्जुर्गां दा ज्यादा आदर करदे सं", "lok bujjurgaan daa zyaadaa aadar karde san"],
        ["We used to sit under this tree", "असी ए रुख हेठ बैठदे सं", "asi e rukh heth baithe san"],
        ["The fair used to come every year", "मेला हर साल आंदा था", "melaa har saal aandaa thaa"],
        ["I used to fear exams", "मैं परीक्षा कोलों डरदा था", "main pareekshaa kolon dardaa thaa"],
        ["She used to wear a white suit", "ओ सफेद सूट पांदी थी", "o safed soot paandee thee"],
        ["They used to farm this land", "ओ ए जमीन जोतदे सं", "o e jameen jotde san"],
        ["Winter used to be harsher", "सर्दी ज्यादा सख्त होंदी थी", "sardee zyaadaa sakht hondee thee"],
        ["I used to know him since childhood", "मैं बचपन कोलों ओने जांदा था", "main bachpan kolon one jaandaa thaa"],
        ["We used to fetch water from the well", "असी कुएं कोलों पाणी लेंदे सं", "asi kuen kolon paanee lende san"],
        ["The teacher used to be strict", "मास्टर सख्त होंदा था", "maastar sakht honda thaa"],
        ["I used to listen to the radio", "मैं रेडियो सुनदा था", "main rediyo sunadaa thaa"],
        ["Villages used to be quieter", "पेंड शांत होंदे सं", "pend shaant honde san"],
        ["He used to return before sunset", "ओ सूरज डुबण कोलों पैह्लें मुड़दा था", "o sooraj duban kolon paihlen murdaa thaa"],
        ["We used to share one room", "असी इक कमरे च रेंदे सं", "asi ik kamre ch rende san"],
        ["Food used to taste different then", "उस वेले खाना होर स्वाद होंदा था", "us vele khaanaa hor swaad honda thaa"],
    ],
    546: [
        ["If it rains, I will stay home", "जे मींह पवे त मैं घरे रहूंगा", "je meenh pave ta main ghare rahungaa"],
        ["If you come, we will go together", "जे तुस आओ त असी इकठ्ठे जामां", "je tus aao ta asi ikatthe jaamaan"],
        ["If he studies, he will pass", "जे ओ पढ़े त पास हो जागा", "je o padhe ta paas ho jaagaa"],
        ["If you are tired, rest", "जे थके हो त आराम करो", "je thake ho ta aaraam karo"],
        ["If she calls, tell her I am busy", "जे ओ फोन करे त दस्सी ओ ब्यस्त आं", "je o fon kare ta dassi o byast aan"],
        ["If we leave now, we will be on time", "जे हुन चलिए त समें पै जामां", "je hun chalie ta samen pai jaamaan"],
        ["If the bus is late, take a taxi", "जे बस देर होवे त टैक्सी लेओ", "je bas der hove ta taiksee leo"],
        ["If you need help, ask me", "जे मदद चाहीदी त मिगी पूछो", "je madad chaahidee ta migee poochho"],
        ["If I had money, I would buy a house", "जे मेरे कोल पैसे होंदे त मैं घर खरीददा", "je mere kol paise honde ta main ghar kharidadaa"],
        ["If they agree, start the work", "जे ओ मान जान त कम शुरू करो", "je o maan jaan ta kam shuroo karo"],
        ["If you eat too much, you will feel ill", "जे ज्यादा खाओगे त बिमार लगोगे", "je zyaadaa khaoge ta bimaar lagoge"],
        ["If the road is bad, drive slowly", "जे रस्ता खराब होवे त हौले चलाओ", "je rastaa kharaab hove ta haule chalaao"],
        ["If winter comes, wear warm clothes", "जे सर्दी आवे त गरम कपड़े पाओ", "je sardee aave ta garam kapde pao"],
        ["If you lie, nobody will trust you", "जे झूठ बोलोगे त कोई भरोसा नेईं करेगा", "je jhoot bologe ta koee bharosaa nein karegaa"],
        ["If I see him, I will inform you", "जे ओ दिखे त मैं तुसां दस्सां", "je o dikhe ta main tusaan dassaan"],
        ["If the shop is closed, come tomorrow", "जे दुकान बंद होवे त कल आइयो", "je dukaan band hove ta kal aaiyo"],
        ["If we work hard, we will succeed", "जे मेहनत करां त सफल होमांगे", "je mehnat karaan ta safal homaange"],
    ],
    547: [
        ["I am waiting for you", "मैं तुसां दी प्रतीक्षा करदा आं", "main tusaan dee prateekshaa kardaa aan"],
        ["She depends on her parents", "ओ अपने मां-बाप पर निर्भर आए", "o apne maan-baap par nirbhar aaey"],
        ["Listen to the teacher", "मास्टर दी गल सुनो", "maastar dee gal suno"],
        ["He laughed at the joke", "ओ चुटकुले उत्ते हस्या", "o chutkule ute hasyaa"],
        ["We believe in hard work", "असी मेहनत पर भरोसा करदे आं", "asi mehnat par bharosaa karde aan"],
        ["Think about the future", "भविष्य दे बारे सोचो", "bhavishya de baare socho"],
        ["She is angry with her brother", "ओ अपने प्रा कोल गुस्से च आए", "o apne praa kol gusse ch aaey"],
        ["I agree with you", "मैं तुसां कोल सहमत आं", "main tusaan kol sahamat aan"],
        ["They ran towards the gate", "ओ गेट वल दौड़े", "o get val daurre"],
        ["Sit on this chair", "ए कुर्सी उत्ते बैठो", "e kursee ute baitho"],
        ["The cat hid under the bed", "बिल्ली बिस्तरे हेठ लुकी", "billee bistare heth lukee"],
        ["Put the book on the table", "किताब मेज उत्ते रखो", "kitaab mej ute rakho"],
        ["He jumped into the water", "ओ पाणी च कूद्या", "o paanee ch koodyaa"],
        ["We walked along the river", "असी नदी कोलों टुरे", "asi nadee kolon ture"],
        ["She looked at the sky", "ओ आकाश वल वेखी", "o aakaash val vekhee"],
        ["I am thinking of home", "मैं घर दी सोच करदा आं", "main ghar dee soch kardaa aan"],
        ["They spoke about the plan", "ओ योजना बारे बोल्ले", "o yojanaa baare bolle"],
    ],
    548: [
        ["This is a big house", "ए बड़ा घर आए", "e baraa ghar aaey"],
        ["That is a small room", "ओ छोटा कमरा आए", "o chhottaa kamraa aaey"],
        ["She is a good teacher", "ओ चंगी मास्टरनी आए", "o changee maastaranee aaey"],
        ["The water is cold", "पाणी ठंडा आए", "paanee thandaa aaey"],
        ["The tea is very sweet", "चा बड़ी मिठी आए", "chaa bardee mithee aaey"],
        ["He is taller than his brother", "ओ अपने प्रा कोलों लंबा आए", "o apne praa kolon lambaa aaey"],
        ["This road is dangerous", "ए रस्ता खतरनाक आए", "e rastaa khatarnaak aaey"],
        ["The sky is clear today", "आज आकाश साफ आए", "aaj aakaash saaf aaey"],
        ["Her voice is soft", "ओदी आवाज़ नर्म आए", "odee aavaaz narm aaey"],
        ["The fruit is ripe", "फल पका आए", "phal pakaa aaey"],
        ["We are ready to go", "असी जाण लई तैयार आं", "asi jaan lai taiyaar aan"],
        ["The child is afraid", "बच्चा डरया आए", "bachchaa daryaa aaey"],
        ["This book is interesting", "ए किताब दिलचस्प आए", "e kitaab dilchasp aaey"],
        ["The milk is sour", "दुद्ध खट्टा आए", "duddh khattaa aaey"],
        ["He looks tired", "ओ थका दिखदा आए", "o thakaa dikhdaa aaey"],
        ["The fields are green", "खेत हरे आए", "khet hare aaey"],
        ["Your idea is useful", "तुसां दा विचार काम आए", "tusaan daa vichaar kaam aaey"],
    ],
    549: [
        ["I can swim", "मैं तैर सकदा आं", "main tair sakdaa aan"],
        ["Can you help me?", "तुस मेरी मदद कर सकदे हो?", "tus meree madad kar sakde ho?"],
        ["He cannot come today", "ओ आज नेईं आ सकदा", "o aaj nein aa sakdaa"],
        ["She can sing very well", "ओ बड़ा चंगा गा सकदी आए", "o baraa changaa gaa sakdee aaey"],
        ["We can finish this work", "असी ए कम मुक्का सकदे आं", "asi e kam mukkaa sakde aan"],
        ["Can I sit here?", "की मैं इत्थे बैठ सकदा आं?", "kee main itthe baith sakdaa aan?"],
        ["They can understand Dogri", "ओ डोगरी समझ सकदे आए", "o dogree samajh sakde aaey"],
        ["I could not sleep", "मैं सौई नेईं सक्या", "main saui nein sakyaa"],
        ["You will be able to drive soon", "तुस जल्दी गड्डी चला सकोगे", "tus jaldee gaddee chalaa sakoge"],
        ["Nobody could open the lock", "कोई ताला नेईं खोल सक्या", "koee taalaa nein khol sakyaa"],
        ["Can she cook without help?", "की ओ बिना मदद को रांध सकदी आए?", "kee o binaa madad ko raandh sakdee aaey?"],
        ["I can try once more", "मैं इक वार होर कोशिश कर सकदा आं", "main ik vaar hor koshish kar sakdaa aan"],
        ["He can lift this box", "ओ ए डिब्बा चुक सकदा आए", "o e dibbaa chuk sakdaa aaey"],
        ["We could not find the way", "असी रस्ता नेईं लब्भा सके", "asi rastaa nein labbhaa sake"],
        ["Can you repeat that?", "की तुस ए दोहरा सकदे हो?", "kee tus e dohraa sakde ho?"],
        ["The child can already read", "बच्चा पढ़ सकदा आए", "bachchaa padh sakdaa aaey"],
        ["I cannot forget that day", "मैं ओ दिन नेईं भुला सकदा", "main o din nein bhulaa sakdaa"],
    ],
    550: [
        ["I want water", "मिगी पाणी चाहिदा आए", "migee paanee chaahidaa aaey"],
        ["I need rest today", "मिगी आज आराम चाहिदा आए", "migee aaj aaraam chaahidaa aaey"],
        ["She wants to study abroad", "ओ बाहर पढ़णा चांदी आए", "o baahar padhanaa chaandee aaey"],
        ["We need your permission", "सानू तुसां दी इजाज़त चाहिदी आए", "saanoo tusaan dee ijaazat chaahidee aaey"],
        ["He does not want to fight", "ओ लड़णा नेईं चांदा", "o ladanaa nein chaandaa"],
        ["Do you want tea?", "की तुसां चा चाहिदी आए?", "kee tusaan chaa chaahidee aaey?"],
        ["I need a little time", "मिगी थोड़ा समें चाहिदा आए", "migee thoddaa samen chaahidaa aaey"],
        ["They want to meet tomorrow", "ओ कल मिलणा चांदे आए", "o kal milanaa chaande aaey"],
        ["The plant needs water", "पौधे नू पाणी चाहिदा आए", "paude noon paanee chaahidaa aaey"],
        ["I want to learn music", "मैं संगीत सिखणा चांदा आं", "main sangeet sikhanaa chaandaa aan"],
        ["She needs medicine", "ओने दवाई चाहिदी आए", "one davaaee chaahidee aaey"],
        ["We do not want trouble", "असी झगड़ा नेईं चांदे", "asi jhagdaa nein chaande"],
        ["He wants a new bicycle", "ओ नवी साइकल चांदा आए", "o navee saikal chaandaa aaey"],
        ["I need your advice", "मिगी तुसां दा सलाह चाहिदा आए", "migee tusaan daa salaah chaahidaa aaey"],
        ["Do they want rice or bread?", "की ओ चोल चांदे न रोटी?", "kee o chol chaande na rotee?"],
        ["The child wants to play", "बच्चा खेड़णा चांदा आए", "bachchaa khedanaa chaandaa aaey"],
        ["I want peace in the house", "मिगी घरे सुकून चाहिदा आए", "migee ghare sukoon chaahidaa aaey"],
    ],
    551: [
        ["It will become cold at night", "रात ने ठंड हो जागी", "raat ne thand ho jaagee"],
        ["He became a doctor", "ओ डाक्टर बन गे", "o daaktar ban ge"],
        ["What happened yesterday?", "कल की भया?", "kal kee bhayaa?"],
        ["The milk turned sour", "दुद्ध खट्टा हो गया", "duddh khattaa ho gayaa"],
        ["She became famous", "ओ मशहूर हो गई", "o mashhoor ho gaee"],
        ["Don't become lazy", "आलसी ना बनो", "aalasee na bano"],
        ["The sky became cloudy", "आकाश बदल गया", "aakaash badal gayaa"],
        ["We became friends", "असी दोस्त बन गे", "asi dost ban ge"],
        ["It happens every day", "हर रोज एह् होदा आए", "har roz eh hoda aaey"],
        ["The child became quiet", "बच्चा चुप हो गया", "bachchaa chup ho gayaa"],
        ["Things will become easier", "गल्लां आसान हो जानगियां", "gallaan aasaan ho jaangiyaan"],
        ["He became angry suddenly", "ओ अचानक गुस्सा हो गया", "o achaanak gussaa ho gayaa"],
        ["Winter is coming; leaves will fall", "सर्दी आंदी आए; पत्ते झड़न गे", "sardee aandee aaey; patte jhadan ge"],
        ["She wants to become a teacher", "ओ मास्टरनी बनणा चांदी आए", "o maastaranee bananaa chaandee aaey"],
        ["Nothing happened without reason", "बिना वजह कुछ नेईं भया", "binaa vajah kuchh nein bhayaa"],
        ["The road became muddy", "रस्ता कीचड़ भर गया", "rastaa keechad bhar gayaa"],
        ["He became old but stayed kind", "ओ बुज्जुर्ग हो गया पर नेक रया", "o bujjurg ho gayaa par nek rayaa"],
    ],
    552: [
        ["You should rest now", "तुस हुन आराम करना चाहीदा आए", "tus hun aaraam karnaa chaahidaa aaey"],
        ["We should help the poor", "सानू गरीबां दी मदद करनी चाहीदी आए", "saanoo gareebaan dee madad karnee chaahidee aaey"],
        ["He should tell the truth", "ओ सच बोलना चाहीदा आए", "o sach bolanaa chaahidaa aaey"],
        ["Children should respect elders", "बच्चेयां नू बुज्जुर्गां दा आदर करना चाहीदा आए", "baccheyaan noon bujjurgaan daa aadar karnaa chaahidaa aaey"],
        ["You should not waste food", "तुस खाना नेईं गवाना चाहीदा", "tus khaanaa nein gavaanaa chaahidaa"],
        ["I should leave early tomorrow", "मिगी कल जल्दी निकलना चाहीदा आए", "migee kal jaldee nikalanaa chaahidaa aaey"],
        ["She should see a doctor", "ओने डाक्टर कोल जाना चाहीदा आए", "one daaktar kol jaanaa chaahidaa aaey"],
        ["We should save water", "सानू पाणी बचाना चाहीदा आए", "saanoo paanee bachaanaa chaahidaa aaey"],
        ["They should apologize", "ओ माफी मंगणी चाहीदी आए", "o maafee mangnee chaahidee aaey"],
        ["You should wear a helmet", "तुस हेलमेट पाना चाहीदा आए", "tus helmeet paanaa chaahidaa aaey"],
        ["One should speak softly", "हौले बोलना चाहीदा आए", "haule bolanaa chaahidaa aaey"],
        ["We should not spread rumours", "सानू अफवाह नेईं फैलानी चाहीदी", "saanoo afwaah nein failaanee chaahidee"],
        ["He should finish his homework", "ओ होमवर्क मुक्काना चाहीदा आए", "o homavark mukkaanaa chaahidaa aaey"],
        ["You should call before coming", "आण कोलों पैह्लें फोन करना चाहीदा", "aan kolon paihlen fon karnaa chaahidaa"],
        ["I should have told you earlier", "मिगी तुसां पैह्लें दस्सना चाहीदा सी", "migee tusaan paihlen dassanaa chaahidaa see"],
    ],
    553: [
        ["I must go now", "मिगी हुन जाणा ही पवेगा", "migee hun jaanaa hi pavegaa"],
        ["You must bring your ID", "तुस अपनी पहचान पत्र लेआणा ही पवेगा", "tus apanee pehchaan patr leaanaa hi pavegaa"],
        ["We must obey the rules", "सानू नियम मन्नने ही पवनगे", "saanoo niyam manne hi pavange"],
        ["She must take medicine on time", "ओने दवाई समें पर लेनी ही पवेगी", "one davaaee samen par lenee hi pavegee"],
        ["They must report to the office", "ओने ओफिस च रिपोर्ट करनी ही पवेगी", "one ofis ch riport karnee hi pavegee"],
        ["The form must be filled", "फॉर्म भरना ही पवेगा", "form bharnaa hi pavegaa"],
        ["I must not be late", "मिगी देर नेईं होनी चाहीदी", "migee der nein honee chaahidee"],
        ["You must tell the truth in court", "तुस कोर्ट च सच ही बोलना पवेगा", "tus kort ch sach hi bolanaa pavegaa"],
        ["We must save electricity", "सानू बिजली बचानी ही पवेगी", "saanoo bijlee bachaanee hi pavegee"],
        ["He must pay the fine", "ओने जुर्माना भरना ही पवेगा", "one jurmaanaa bharnaa hi pavegaa"],
        ["Students must attend class", "विद्यार्थियां नू क्लास लेनी ही पवेगी", "vidyaarthiyaan noon klaas lenee hi pavegee"],
        ["I must call my mother", "मिगी माँ नू फोन करना ही पवेगा", "migee maan noon fon karnaa hi pavegaa"],
        ["You must not skip breakfast", "तुस नाश्ता नेईं छड़ाना चाहीदा", "tus naashataa nein chhadaanaa chaahidaa"],
        ["We must leave before dark", "सानू अंधेरे कोलों पैह्लें निकलना ही पवेगा", "saanoo andhere kolon paihlen nikalanaa hi pavegaa"],
        ["The door must be locked", "दरवाजा बंद करना ही पवेगा", "daravaajaa band karnaa hi pavegaa"],
        ["I must finish this today", "मिगी ए आज ही मुक्काना पवेगा", "migee e aaj hi mukkaanaa pavegaa"],
    ],
    554: [
        ["He keeps talking", "ओ लगातार बोलदा रेंदा आए", "o lagaataar boldaa rendaa aaey"],
        ["She keeps forgetting", "ओ लगातार भुलंदी रेंदी आए", "o lagaataar bhulandee rendee aaey"],
        ["The baby keeps crying", "बच्चा लगातार रोंदा आए", "bachchaa lagaataar rondaa aaey"],
        ["They keep asking questions", "ओ सवाल पुछदे रेंदे आए", "o savaal puchhde rende aaey"],
        ["I keep thinking of you", "मैं तुसां दी सोच करदा रेंदा आं", "main tusaan dee soch kardaa rendaa aan"],
        ["The phone keeps ringing", "फोन लगातार बजदा आए", "fon lagaataar bajdaa aaey"],
        ["It keeps raining", "मींह लगातार पैंदा आए", "meenh lagaataar paindaa aaey"],
        ["We keep trying", "असी कोशिश करदे रेंदे आं", "asi koshish karde rende aan"],
        ["Don't keep arguing", "लगातार ना झगड़ो", "lagaataar na jhagro"],
        ["He keeps changing his mind", "ओ अपना मन बदलदा रेंदा आए", "o apnaa man badaldaa rendaa aaey"],
        ["She keeps the house clean", "ओ घर साफ रखदी आए", "o ghar saaf rakhdee aaey"],
        ["The fan keeps making noise", "पंखा शोर करदा रेंदा आए", "pankhaa shor kardaa rendaa aaey"],
        ["I keep telling you the same thing", "मैं इक ही गल दोहरांदा रेंदा आं", "main ik hi gal dohraandaa rendaa aan"],
        ["They keep postponing the meeting", "ओ मीटिंग टालदे रेंदे आए", "o meeting taalde rende aaey"],
        ["Water keeps dripping", "पाणी टपकदा रेंदा आए", "paanee tapakdaa rendaa aaey"],
        ["You keep improving", "तुस लगातार सुधरदे हो", "tus lagaataar sudharde ho"],
    ],
    555: [
        ["This tree is taller than that one", "ए रुख ओ कोलों लंबा आए", "e rukh o kolon lambaa aaey"],
        ["She is the best singer here", "ओ इत्थे सब कोलों चंगी गायिका आए", "o itthe sab kolon changee gaayikaa aaey"],
        ["This road is shorter", "ए रस्ता छोटा आए", "e rastaa chhottaa aaey"],
        ["He runs faster than me", "ओ मिगे कोलों तेज दौड़दा आए", "o mige kolon tej daurdaa aaey"],
        ["This book is more useful", "ए किताब ज्यादा काम आए", "e kitaab zyaadaa kaam aaey"],
        ["Winter is colder this year", "ए साल सर्दी ज्यादा सख्त आए", "e saal sardee zyaadaa sakht aaey"],
        ["She speaks more politely", "ओ ज्यादा नर्मी कोल बोलदी आए", "o zyaadaa narmee kol boldee aaey"],
        ["This is the biggest market", "ए सब कोलों बड़ा बाज़ार आए", "e sab kolon baraa baazaar aaey"],
        ["My house is nearer", "मेरा घर नेड़ा आए", "meraa ghar neddaa aaey"],
        ["He is as wise as his father", "ओ अपने बापू जिन्ना समझदार आए", "o apne baapu jinaa samajhdaar aaey"],
        ["This sweet is sweeter than that", "ए मिठाई ओ कोलों ज्यादा मिठी आए", "e mithaai o kolon zyaadaa mithee aaey"],
        ["The second question is harder", "दूजा सवाल ओ कोलों अखा आए", "doojaa savaal o kolon akhaa aaey"],
        ["She is younger than her sister", "ओ अपनी बहण कोलों छोटी आए", "o apanee bahan kolon chhottee aaey"],
        ["This cloth is softer", "ए कपड़ा नर्म आए", "e kapdaa narm aaey"],
        ["He earns less than before", "ओ पैह्लें कोलों कट कमांदा आए", "o paihlen kolon kat kamaandaa aaey"],
        ["This path is safer at day", "ए रस्ता दिन ने सुरक्षित आए", "e rastaa din ne surakshit aaey"],
    ],
    556: [
        ["I know this boy", "मैं ए मुंडे नू जांदा आं", "main e mund noon jaandaa aan"],
        ["Do you know her name?", "की तुस ओदा नां जांदे हो?", "kee tus odaa naan jaande ho?"],
        ["He knows how to drive", "ओ गड्डी चलोंदा जांदा आए", "o gaddee chalondaa jaandaa aaey"],
        ["I don't know the answer", "मैं जवाब नेईं जांदा", "main jawaab nein jaandaa"],
        ["We know the truth", "असी सच जांदे आं", "asi sach jaande aan"],
        ["She knows three languages", "ओ तिन्न भाषा जांदी आए", "o tinn bhaashaa jaandee aaey"],
        ["Nobody knows what will happen", "कोई नेईं जांदा की होगा", "koee nein jaandaa kee hogaa"],
        ["I knew him from school", "मैं ओने सकूल कोलों जांदा था", "main one sakool kolon jaandaa thaa"],
        ["You should know your duty", "तुस अपना फर्ज जाणना चाहीदा", "tus apnaa farz jaannaa chaahidaa"],
        ["Let me know when you arrive", "जदों पै जाओ त दस्सी देओ", "jadon pai jaao ta dassi deo"],
        ["I want to know the reason", "मैं वजह जाणना चांदा आं", "main vajah jaannaa chaandaa aan"],
        ["Does he know cooking?", "की ओ रांधणा जांदा आए?", "kee o raandhanaa jaandaa aaey?"],
        ["We knew they would come", "असी जांदे सं ओ आनगे", "asi jaande san o aanage"],
        ["I know it by heart", "मैं ए याद कोल जांदा आं", "main e yaad kol jaandaa aan"],
        ["She knows the way to the temple", "ओ मंदिर दा रस्ता जांदी आए", "o mandir daa rastaa jaandee aaey"],
        ["How do you know?", "तुस कियां जांदे हो?", "tus kiyaan jaande ho?"],
        ["They know nothing about it", "ओ इस बारे कुछ नेईं जांदे", "o is baare kuchh nein jaande"],
    ],
    557: [
        ["Let him speak", "ओने बोलन देओ", "one bolan deo"],
        ["Let us go now", "चलो हुन चलिए", "chalo hun chalie"],
        ["Let her rest", "ओने आराम करन देओ", "one aaraam karan deo"],
        ["Let's eat together", "चलो इकठ्ठे खाईए", "chalo ikatthe khaaie"],
        ["Let the children play", "बच्चेयां नू खेड़न देओ", "baccheyaan noon khedan deo"],
        ["Shall we start?", "की असी शुरू करिए?", "kee asi shuroo karie?"],
        ["Shall I open the door?", "की मैं दरवाजा खोलां?", "kee main daravaajaa kholaan?"],
        ["Let's wait five minutes", "चलो पाँच मिनट इंतज़ार करिए", "chalo paanch minat intazaar karie"],
        ["Don't let him go alone", "ओने इकल्ले ना जाण देओ", "one ikalle na jaan deo"],
        ["Let the water boil", "पाणी उबलन देओ", "paanee ubalan deo"],
        ["Shall we meet tomorrow?", "की असी कल मिलां?", "kee asi kal milaan?"],
        ["Let me try once", "मिगी इक वार कोशिश करन देओ", "migee ik vaar koshish karan deo"],
        ["Let's take a photo", "चलो फोटो खिंचिए", "chalo photo khinchie"],
        ["Let them decide", "ओ फैसला करन देओ", "o faisalaa karan deo"],
        ["Shall we walk?", "की असी पैदल चलिए?", "kee asi paidal chalie?"],
        ["Let it be; don't worry", "रहन देओ; फिकर ना करो", "rahan deo; fikar na karo"],
    ],
    558: [
        ["The book that I bought is good", "किताब जेड़ी मैं खरीदी ओ चंगी आए", "kitaab jeddee main khareedee o changee aaey"],
        ["The man who came is my uncle", "आदमी जेड़ा आया ओ मेरा चाचा आए", "aadamee jedaa aayaa o meraa chaachaa aaey"],
        ["What you said is true", "जो तुस बोल्या ओ सच आए", "jo tus bolyaa o sach aaey"],
        ["I know where he lives", "मैं जांदा आं कुथे ओ रेंदा आए", "main jaandaa aan kuthe o rendaa aaey"],
        ["Tell me which bus goes to Jammu", "दस्सो केड़ी बस जम्मू जांदी आए", "daso keddee bas jammu jaandee aaey"],
        ["That is the house that I want", "ओह् घर आए जेड़ा मैं चांदा आं", "oh ghar aaey jedaa main chaandaa aan"],
        ["The girl whose bag this is stood up", "कुड़ी जिसदा ए बैग ओ खड़ी हो गई", "kuddee jisdaa e baeg o khadee ho gaee"],
        ["I forgot what he asked", "मैं भुल गया ओने की पुछ्या", "main bhul gayaa one kee puchhyaa"],
        ["Show me what you wrote", "दिखाओ जो तुस लिख्या", "dikhaao jo tus likhyaa"],
        ["This is the road that leads to the temple", "ए रस्ता आए जेड़ा मंदिर नू जांदा आए", "e rastaa aaey jedaa mandir noon jaandaa aaey"],
        ["I like the song that she sang", "मिगी ओ गीत पसंद आए जेड़ा ओने गाया", "migee o geet pasand aaey jedaa one gaayaa"],
        ["Whoever comes, welcome them", "जेड़ा भी आवे ओदा स्वागत करो", "jedaa bhee aave odaa swaagat karo"],
        ["Whatever happens, stay calm", "जो भी होवे शांत रहो", "jo bhee hove shaant raho"],
        ["The reason why he left is unclear", "ओ कियां गया ओ साफ नेईं", "o kiyaan gayaa o saaf nein"],
        ["That is not what I meant", "ओ नेईं आए जो मैं कहना चाहंदा था", "o nein aaey jo main kahanaa chaahandaa thaa"],
        ["Tell me when you will come", "दस्सो कदों आओगे", "daso kadon aaoge"],
    ],
    559: [
        ["Please read the notice carefully", "किरपा करियै नोटिस ध्यान कोल पढ़ो", "kirpaa kariyai notices dhyaan kol padho"],
        ["Kindly submit the form by Friday", "किरपा करियै फॉर्म शुक्रवार कोल जमा करो", "kirpaa kariyai form shukravaar kol jama karo"],
        ["Employees must wear ID cards", "कर्मचारियां नू आईडी कार्ड पाना जरूरी आए", "karmachaariyaan noon ID card paanaa jaroori aaey"],
        ["Do not use mobile phones here", "इत्थे मोबाइल नेईं वरतो", "itthe mobail nein varato"],
        ["Please maintain silence in the library", "लाइब्रेरी च चुप रहो", "laibreree ch chup raho"],
        ["Visitors should register at the gate", "मुलाकाती गेट उत्ते नां लिखवाओ", "mulaakaatee get ute naan likhwaao"],
        ["Follow the safety instructions", "सुरक्षा दियां हिदायतां मन्नो", "surakshaa diyaan hidaataan manno"],
        ["Please queue in a line", "किरपा करियै लाइन च लगो", "kirpaa kariyai lain ch lago"],
        ["Do not touch the exhibits", "प्रदर्शनी नेईं छुओ", "pradarshanee nein chhoo"],
        ["Report any suspicious bag", "शकी डिब्बे दी खबर देओ", "shakee dibbee dee khabar deo"],
        ["Please switch off lights when leaving", "जांदे वेले बत्ती बंद करो", "jaande vele battee band karo"],
        ["Staff must not share passwords", "स्टाफ पासवर्ड शेयर ना करे", "staaf paasavard share na kare"],
        ["Kindly keep the corridor clear", "गलियारा साफ रखो", "galiyaaraa saaf rakho"],
        ["Patients should take tokens before waiting", "मरीज टोकन लेआ के इंतज़ार करन", "mareez token leaa ke intazaar karan"],
        ["Please sign here and here", "इत्थे अते इत्थे साइन करो", "itthe ate itthe saain karo"],
        ["Do not smoke on these premises", "इत्थे धूम्रपान ना करो", "itthe dhoomrapaan na karo"],
    ],
    560: [
        ["I like mangoes", "मिगी आम पसंद आए", "migee aam pasand aaey"],
        ["She likes to dance", "ओ नचणा पसंद करदी आए", "o nachanaa pasand kardee aaey"],
        ["We like this place", "सानू ए जगह पसंद आए", "saanoo e jagah pasand aaey"],
        ["Do you like spicy food?", "की तुस तीखा खाना पसंद करदे हो?", "kee tus teekhaa khaanaa pasand karde ho?"],
        ["He doesn't like crowds", "ओ भीड़ पसंद नेईं करदा", "o bheer pasand nein kardaa"],
        ["Children like sweets", "बच्चेयां नू मिठाइयां पसंद आए", "baccheyaan noon mithaaiyaan pasand aaey"],
        ["I would like some tea", "मिगी थोड़ी चा चाहीदी आए", "migee thodee chaa chaahidee aaey"],
        ["She likes reading novels", "ओ नावल पढ़णा पसंद करदी आए", "o naaval padhanaa pasand kardee aaey"],
        ["We like your company", "सानू तुसां दा साथ पसंद आए", "saanoo tusaan daa saath pasand aaey"],
        ["I don't like lies", "मिगी झूठ पसंद नेईं", "migee jhoot pasand nein"],
        ["He likes cold weather", "ओ ठंडा मौसम पसंद करदा आए", "o thandaa mausam pasand kardaa aaey"],
        ["Do you like Dogri films?", "की तुस डोगरी फिल्मां पसंद करदे हो?", "kee tus dogree filmaan pasand karde ho?"],
        ["I like walking in the morning", "मिगी सवेर टहल पसंद आए", "migee saver tahal pasand aaey"],
        ["She likes helping others", "ओ होरां दी मदद करना पसंद करदी आए", "o horaan dee madad karnaa pasand kardee aaey"],
        ["We liked the programme", "सानू प्रोग्राम पसंद आया", "saanoo prograam pasand aayaa"],
        ["He would like to meet you", "ओ तुसां कोल मिलना चांदा आए", "o tusaan kol milanaa chaandaa aaey"],
    ],
    561: [
        ["I would help if I could", "मैं मदद करदा जे कर सकदा", "main madad karadaa je kar sakdaa"],
        ["Would you like some water?", "की तुसां पाणी लेओगे?", "kee tusaan paanee leoge?"],
        ["He would come every Sunday", "ओ हर ऐतवार आंदा", "o har aitavaar aandaa"],
        ["We would sit under this tree", "असी ए रुख हेठ बैठदे", "asi e rukh heth baithe"],
        ["I would read before sleeping", "मैं सौण कोलों पढ़दा", "main saun kolon padhdaa"],
        ["She would sing softly", "ओ हौले गांदी", "o haule gaandee"],
        ["They would play in the street", "ओ गली च खेड़दे", "o gallee ch khedde"],
        ["It would rain in July", "सावण च मींह पैंदा", "saavan ch meenh paindaa"],
        ["I would rather walk", "मैं पैदल चलना पसंद करदा", "main paidal chalanaa pasand kardaa"],
        ["Would you mind closing the door?", "की तुस दरवाजा बंद कर देओगे?", "kee tus daravaajaa band kar deoge?"],
        ["He would never tell lies", "ओ कदे झूठ नेईं बोलदा", "o kade jhoot nein boldaa"],
        ["We would share our lunch", "असी लंच शेयर करदे", "asi lunch share karde"],
        ["Mother would wake up early", "माँ सवेर उठदी", "maa saver uthdee"],
        ["I would feel scared at night", "मैं रात ने डरदा", "main raat ne dardaa"],
        ["That would be fine", "ओ ठीक होगा", "o theek hogaa"],
        ["Would they agree?", "की ओ मान जान?", "kee o maan jaan?"],
    ],
    562: [
        ["I understand your problem", "मैं तुसां दी समस्या समझदा आं", "main tusaan dee samasyaa samajhdaa aan"],
        ["Did you understand the lesson?", "की तुस सबक समझे?", "kee tus sabak samjhe?"],
        ["I suddenly understood the trick", "मैं अचानक नुस्खा समझ गया", "main achaanak nuskhaa samajh gayaa"],
        ["She does not understand Dogri well", "ओ डोगरी चंगी नेईं समझदी", "o dogree changee nein samajhdee"],
        ["Help me understand this map", "ए नक्शा समझने च मदद करो", "e nakshaa samajhne ch madad karo"],
        ["I came to know the news yesterday", "मिगी कल पता लगा", "migee kal pata lagaa"],
        ["How did you come to know?", "तुसें कियां पता लगा?", "tasen kiyaan pata lagaa?"],
        ["We came to know through TV", "सानू टीवी कोलों पता लगा", "saanoo TV kolon pata lagaa"],
        ["He came to know the truth later", "ओने बाद च सच पता लगा", "one baad ch sach pata lagaa"],
        ["I understand; don't worry", "समझ गया; फिकर ना करो", "samajh gayaa; fikar na karo"],
        ["Little children understand slowly", "छोटे बच्चे धीरे समझदे आए", "chhotte bacche dheere samajhde aaey"],
        ["I could not understand his accent", "मैं ओदा लहजा नेईं समझ सक्या", "main odaa lahajaa nein samajh sakyaa"],
        ["She understood without words", "ओ बिना बोले समझ गई", "o binaa bole samajh gaee"],
        ["Let me know if you understand", "जे समझ आवे त दस्सी देओ", "je samajh aave ta dassi deo"],
        ["I understand the situation now", "मैं हुन हालात समझ गया", "main hun haalaat samajh gayaa"],
        ["They came to know each other at college", "ओने कालेज च इक दूजे नू जाणा", "one kaalej ch ik dooje noon jaanaa"],
    ],
    563: [
        ["You are coming, aren't you?", "तुस आंदे हो, नी?", "tus aande ho, nee?"],
        ["He is at home, isn't he?", "ओ घरे आए, नी?", "o ghare aaey, nee?"],
        ["She can drive, can't she?", "ओ गड्डी चला सकदी आए, नी?", "o gaddee chalaa sakdee aaey, nee?"],
        ["We will go tomorrow, won't we?", "असी कल जामां, नी?", "asi kal jaamaan, nee?"],
        ["It is cold today, isn't it?", "आज ठंड आए, नी?", "aaj thand aaey, nee?"],
        ["You don't eat meat, do you?", "तुस मांस नेईं खांदे, नी?", "tus maans nein khaande, nee?"],
        ["They haven't come yet, have they?", "ओ हले नेईं आए, नी?", "o hale nein aaey, nee?"],
        ["This is your book, isn't it?", "ए तुसां दी किताब आए, नी?", "e tusaan dee kitaab aaey, nee?"],
        ["You were there, weren't you?", "तुस उत्थे सं, नी?", "tus utthe san, nee?"],
        ["Let's go, shall we?", "चलिए, चलिए?", "chalie, chalie?"],
        ["He won't agree, will he?", "ओ नेईं मानेगा, नी?", "o nein maanegaa, nee?"],
        ["She likes sweets, doesn't she?", "ओने मिठाइयां पसंद आए, नी?", "one mithaaiyaan pasand aaey, nee?"],
        ["You can swim, can't you?", "तुस तैर सकदे हो, नी?", "tus tair sakde ho, nee?"],
        ["It won't rain, will it?", "मींह नेईं पवेगा, नी?", "meenh nein pavegaa, nee?"],
        ["We should leave, shouldn't we?", "सानू निकलना चाहीदा, नी?", "saanoo nikalanaa chaahidaa, nee?"],
        ["He is your brother, isn't he?", "ओ तुसां दा प्रा आए, नी?", "o tusaan daa praa aaey, nee?"],
    ],
    564: [
        ["I remember your name", "मैं तुसां दा नां याद आए", "main tusaan daa naan yaad aaey"],
        ["I forgot where I kept the keys", "मैं भुल गया कुथे चाबी रखी", "main bhul gayaa kuthe chaabee rakhee"],
        ["Try to remember the date", "तारीख याद रखने कोशिश करो", "taareekh yaad rakhne koshish karo"],
        ["I suddenly remembered the promise", "मैं अचानक वादा याद आया", "main achaanak vaadaa yaad aayaa"],
        ["She remembers everything", "ओ सब कुछ याद रखदी आए", "o sab kuchh yaad rakhdee aaey"],
        ["Do you remember me?", "की तुस मिगी याद करदे हो?", "kee tus migee yaad karde ho?"],
        ["I can't remember that word", "मैं ओ शब्द याद नेईं कर सकदा", "main o shabd yaad nein kar sakdaa"],
        ["We remember our teachers", "असी अपने मास्टर याद करदे आं", "asi apne maastar yaad karde aan"],
        ["Remember to lock the door", "दरवाजा बंद करना याद रखो", "daravaajaa band karnaa yaad rakho"],
        ["He remembered the way", "ओने रस्ता याद आया", "one rastaa yaad aayaa"],
        ["Childhood memories are sweet", "बचपन दियां यादां मिठियां आए", "bachpan diyaan yaadaan mitthiyaan aaey"],
        ["I will never forget this help", "मैं ए मदद कदे नेईं भुलांगा", "main e madad kade nein bhulaangaa"],
        ["Please remind me tomorrow", "मिगी कल याद कराइयो", "migee kal yaad karaaiyo"],
        ["She forgot to bring the file", "ओने फाइल लेआणा भुल गया", "one faail leaanaa bhul gayaa"],
        ["I remember seeing him here", "मैं ओने इत्थे वेख्या याद आए", "main one itthe vekhyaa yaad aaey"],
        ["Memories fade with time", "यादां समें कोलों फिक्की होंदी आए", "yaadaan samen kolon fikkee hondee aaey"],
    ],
    565: [
        ["I want to go home", "मैं घर जाणा चांदा आं", "main ghar jaanaa chaandaa aan"],
        ["She wants to sleep early", "ओ जल्दी सौणा चांदी आए", "o jaldee saunaa chaandee aaey"],
        ["We want to watch the match", "असी मैच वेखणा चांदे आं", "asi maich vekhanaa chaande aan"],
        ["He wants to buy a phone", "ओ फोन खरीदणा चांदा आए", "o fon kharidanaa chaandaa aaey"],
        ["They want to learn English", "ओ अंग्रेज़ी सिखणा चांदे आए", "o angrezee sikhanaa chaande aaey"],
        ["I don't want to argue", "मैं झगड़ा नेईं चांदा", "main jhagdaa nein chaandaa"],
        ["Do you want to come along?", "की तुस नाल आणा चांदे हो?", "kee tus naal aanaa chaande ho?"],
        ["She wants to help her mother", "ओ अपनी माँ दी मदद करना चांदी आए", "o apanee maan dee madad karnaa chaandee aaey"],
        ["We want peace", "सानू सुकून चाहिदा आए", "saanoo sukoon chaahidaa aaey"],
        ["He wants to leave the job", "ओ नौकरी छड़णा चांदा आए", "o naukaree chhadanaa chaandaa aaey"],
        ["I want to drink cold water", "मैं ठंडा पाणी पीणा चांदा आं", "main thandaa paanee peenaa chaandaa aan"],
        ["Children want to play", "बच्चे खेड़णा चांदे आए", "bacche khedanaa chaande aaey"],
        ["She wants to become a nurse", "ओ नर्स बनणा चांदी आए", "o nas bananaa chaandee aaey"],
        ["We want to visit Kashmir", "असी कश्मीर घूमणा चांदे आं", "asi kashmeer ghoomanaa chaande aan"],
        ["He wants to save money", "ओ पैसे बचाणा चांदा आए", "o paise bachaanaa chaandaa aaey"],
        ["I want to tell you something", "मिगी तुसां कुछ दस्सणा आए", "migee tusaan kuchh dassanaa aaey"],
    ],
}
