# Dogri Lesson 4 — Vocabulary (chapter IDs 597–619).

LESSONS_S4 = {
    597: [
        ["Head", "सिर", "sir"],
        ["Hair", "वाल", "vaal / kesh"],
        ["Eye", "अख", "akh"],
        ["Ear", "कान", "kaan"],
        ["Nose", "नाक", "naak"],
        ["Mouth", "मूंह", "moonh"],
        ["Tooth / teeth", "दांत", "daant"],
        ["Tongue", "जीभ", "jeebh"],
        ["Neck", "गardan", "gardan"],
        ["Shoulder", "कंध", "kandh"],
        ["Arm", "बाँह", "baanh"],
        ["Hand", "हथ", "hath"],
        ["Finger", "ऊंगल", "oongal"],
        ["Chest", "छाती", "chaatee"],
        ["Stomach", "पेट", "pet"],
        ["Back", "पीठ", "peeth"],
        ["Leg", "लत्त", "latt"],
        ["Foot", "पैर", "pair"],
        ["Skin", "चमड़ी", "chamadee"],
        ["Bone", "हड्डी", "hadddee"],
    ],
    598: [
        ["House", "घर", "ghar"],
        ["Door", "दरवाजा", "daravaajaa"],
        ["Window", "खिड़की", "khidakee"],
        ["Road", "रस्ता", "rastaa / sarrak"],
        ["Water", "पाणी", "paanee"],
        ["Fire", "अग", "ag"],
        ["Sky", "आकाश", "aakaash"],
        ["Earth / soil", "धरती", "dhartee"],
        ["Sun", "सूरज", "sooraj"],
        ["Moon", "चंद्रमा", "chandramaa"],
        ["Star", "तारा", "taaraa"],
        ["Wind", "हवा", "havaa"],
        ["Rain", "मींह", "meenh"],
        ["Day", "दिन", "din"],
        ["Night", "रात", "raat"],
        ["Morning", "सवेर", "saver"],
        ["Evening", "शाम", "shaam"],
        ["Market", "बाज़ार", "baazaar"],
        ["Shop", "दुकान", "dukaan"],
        ["School", "सकूल", "sakool"],
    ],
    599: [
        ["Father", "बापू", "baapu"],
        ["Mother", "माँ", "maa"],
        ["Brother", "प्रा", "praa / bhaiyaa"],
        ["Sister", "बहण", "bahan / deedee"],
        ["Son", "पुत", "put / putra"],
        ["Daughter", "धी", "dhee"],
        ["Husband", "कमला", "kamalaa / pati"],
        ["Wife", "जायई", "jaayee / patnee"],
        ["Grandfather", "दादा", "daadaa"],
        ["Grandmother", "दादी", "daadee"],
        ["Uncle (father's brother)", "चाचा", "chaachaa"],
        ["Aunt", "चाची", "chaachee"],
        ["Maternal uncle", "मामा", "maamaa"],
        ["Maternal aunt", "मामी", "maamee"],
        ["Father-in-law", "ससुर", "sasur"],
        ["Mother-in-law", "सस", "sas"],
        ["Nephew", "भांजा", "bhaanjaa"],
        ["Niece", "भांजी", "bhaanjee"],
        ["Cousin", "चचेरा भाई", "chacheraa bhaai"],
        ["Friend", "दोस्त", "dost / yaar"],
    ],
    600: [
        ["One", "इक", "ik"],
        ["Two", "दो", "do"],
        ["Three", "त्रै", "trai"],
        ["Four", "चार", "chaar"],
        ["Five", "पंज", "panj"],
        ["Six", "छे", "che"],
        ["Seven", "सत्त", "satt"],
        ["Eight", "अठ्ठ", "atth"],
        ["Nine", "नौ", "nau"],
        ["Ten", "दस", "das"],
        ["Eleven", "ग्यारह", "gyaarah"],
        ["Twelve", "बारह", "baarah"],
        ["Thirteen", "तेरह", "terah"],
        ["Fourteen", "चौदह", "chaudah"],
        ["Fifteen", "पंद्रह", "pandrah"],
        ["Sixteen", "सोलह", "solah"],
        ["Seventeen", "सतारह", "sataarah"],
        ["Eighteen", "अठारह", "athaarah"],
        ["Nineteen", "उन्नी", "unnee"],
        ["Twenty", "वीह", "vee"],
    ],
    601: [
        ["Twenty-one", "इक्की", "ikkee"],
        ["Thirty", "तीह", "teeh"],
        ["Forty", "चाली", "chaalee"],
        ["Fifty", "पंजाह", "panjaah"],
        ["Sixty", "साठ", "saath"],
        ["Seventy", "सत्तर", "sattar"],
        ["Eighty", "असी", "asee"],
        ["Ninety", "नब्बे", "nabbe"],
        ["One hundred", "सौ", "sau"],
        ["Two hundred", "दो सौ", "do sau"],
        ["One thousand", "इक हजार", "ik hazaar"],
        ["Ten thousand", "दस हजार", "das hazaar"],
        ["One lakh", "इक लाख", "ik laakh"],
        ["First", "पैह्ला", "paihlaa"],
        ["Second", "दूजा", "doojaa"],
        ["Third", "तीजा", "teejaa"],
        ["Last", "आखरी", "aakhree"],
        ["Next", "अगला", "aglaa"],
        ["Previous", "पिछला", "pichhlaa"],
        ["How many?", "किन्ने?", "kinne?"],
    ],
    602: [
        ["Half", "आधा", "aadhaa"],
        ["Quarter", "पाव", "paav / suth"],
        ["One third", "इक तिहाई", "ik tihaaee"],
        ["Twice", "दो वार", "do vaar"],
        ["Thrice", "तिन वार", "tin vaar"],
        ["Double", "दुगना", "duganaa"],
        ["Single", "इकल्ला", "ikallaa"],
        ["Pair", "जोड़ा", "jorraa"],
        ["Percent", "फीसदी", "feesdee"],
        ["Number", "नंबर", "nambar / ank"],
        ["Series", "लड़ी", "larree / karree"],
        ["Order", "क्रम", "kram"],
        ["Before (sequence)", "पैह्लें", "paihlen"],
        ["After (sequence)", "बाद", "baad"],
        ["Again", "फेर", "pher / dubaaraa"],
        ["Once", "इक वार", "ik vaar"],
        ["Fraction", "अंश", "ansh"],
        ["Whole", "सारा", "saaraa"],
        ["Equal", "बराबर", "baraabar"],
        ["Approximate", "लगभग", "lagabhag"],
    ],
    603: [
        ["To go", "जाणा", "jaanaa"],
        ["To come", "आणा", "aanaa"],
        ["To eat", "खाणा", "khaanaa"],
        ["To drink", "पीणा", "peenaa"],
        ["To sleep", "सौणा", "saunaa"],
        ["To wake up", "उठणा", "utthanaa"],
        ["To sit", "बैठणा", "baithanaa"],
        ["To stand", "खड़ा होणा", "khadaa honaa"],
        ["To walk", "टुरणा", "turanaa / chalanaa"],
        ["To run", "दौड़णा", "dauranaa"],
        ["To speak", "बोलणा", "bolanaa"],
        ["To listen", "सुनणा", "sunanaa"],
        ["To see", "वेखणा", "vekhanaa"],
        ["To read", "पढ़णा", "padhanaa"],
        ["To write", "लिखणा", "likhanaa"],
        ["To learn", "सिखणा", "sikhanaa"],
        ["To teach", "पढ़ौणा", "padhaunaa / sikhaunaa"],
        ["To buy", "खरीदणा", "kharidanaa"],
        ["To sell", "बेचणा", "bechanaa"],
        ["To give", "देणा", "denaa"],
    ],
    604: [
        ["To take", "लेणा", "lenaa"],
        ["To bring", "लेआणा", "leaanaa"],
        ["To send", "भेजणा", "bhejanaa"],
        ["To open", "खोलणा", "kholanaa"],
        ["To close", "बंद करणा", "band karnaa"],
        ["To wash", "धोणा", "dhonaa"],
        ["To cook", "रांधणा", "raandhanaa / banaunaa"],
        ["To cut", "कटौणा", "kataunaa / kaatanaa"],
        ["To play", "खेड़णा", "khedanaa"],
        ["To sing", "गाणा", "gaanaa"],
        ["To dance", "नचणा", "nachanaa"],
        ["To laugh", "हसणा", "hasanaa"],
        ["To cry", "रोणा", "ronaa"],
        ["To ask", "पुछणा", "puchhanaa"],
        ["To answer", "जवाब देणा", "jawaab denaa"],
        ["To think", "सोचणा", "sochanaa"],
        ["To understand", "समझणा", "samajhanaa"],
        ["To forget", "भुलणा", "bhulanaa"],
        ["To remember", "याद करणा", "yaad karnaa"],
        ["To wait", "इंतज़ार करणा", "intazaar karnaa"],
    ],
    605: [
        ["To work", "कम करणा", "kam karnaa"],
        ["To rest", "आराम करणा", "aaraam karnaa"],
        ["To help", "मदद करणा", "madad karnaa"],
        ["To fight", "लड़णा", "ladanaa"],
        ["To love", "प्यार करणा", "piyaar karnaa"],
        ["To hate", "नफरत करणा", "nafrat karnaa"],
        ["To like", "पसंद करणा", "pasand karnaa"],
        ["To try", "कोशिश करणा", "koshish karnaa"],
        ["To start", "शुरू करणा", "shuroo karnaa"],
        ["To finish", "मुक्काणा", "mukkaanaa / khatam karnaa"],
        ["To use", "वरतणा", "varatanaa"],
        ["To need", "लोड़ होणा", "lorr honaa"],
        ["To fall", "डिगणा", "diganaa / giranaa"],
        ["To climb", "चढ़णा", "chadhanaa"],
        ["To fall (drop)", "गिरौणा", "giraunaa"],
        ["To meet", "मिलणा", "milanaa"],
        ["To leave", "चलणा", "chalanaa / chhadanaa"],
        ["To return", "मुड़णा", "muranaa / vaapas aanaa"],
        ["To stay", "रैणा", "rainaa / rahanaa"],
        ["To live", "रैणा", "rainaa / jeenaa"],
    ],
    606: [
        ["To call (phone)", "फोन करणा", "fon karnaa"],
        ["To message", "संदेश भेजणा", "sandesh bhejanaa"],
        ["To search", "लब्भणा", "labbhanaa / khojanaa"],
        ["To choose", "चुनणा", "chunanaa"],
        ["To change", "बदलणा", "badalanaa"],
        ["To break", "तोड़णा", "torrnaa"],
        ["To join", "जोड़णा", "jorrnaa"],
        ["To pay", "भरणा", "bharnaa / pe karnaa"],
        ["To borrow", "उधार लेणा", "udhaar lenaa"],
        ["To lend", "उधार देणा", "udhaar denaa"],
        ["To win", "जितणा", "jitanaa"],
        ["To lose", "हारणा", "haaranaa"],
        ["To push", "धकेलणा", "dhakelanaa"],
        ["To pull", "खिंचणा", "khinchanaa"],
        ["To throw", "सुटणा", "suttanaa"],
        ["To catch", "फड़णा", "farranaa"],
        ["To carry", "चुकणा", "chukanaa / lejaanaa"],
        ["To build", "बनौणा", "banaunaa"],
        ["To clean", "साफ करणा", "saaf karnaa"],
        ["To sweep", "झाड़णा", "jhaarranaa"],
    ],
    607: [
        ["To give (laav-) — I give", "मैं देंदा", "main denda / dendee aan"],
        ["Give me water", "मिगी पाणी दे", "migee paanee de"],
        ["He gives help", "ओ मदद देंदा आए", "o madad dendaa aaey"],
        ["Give way / let pass", "रास्ता दे", "rastaa de"],
        ["Give a slap (colloquial)", "थप्पड़ दे", "thapparr de"],
        ["To take (leb-) — I take", "मैं लेंदा आं", "main lendaa aan"],
        ["Take this", "ए लै ले", "e lai le"],
        ["Take care", "ख्याल रख", "khyaal rakh"],
        ["Take permission", "इजाज़त लै", "ijaazat lai"],
        ["Take revenge", "बदला लै", "badlaa lai"],
        ["Multiple senses of 'give'", "देब — दान, भेंट, सौंप", "deb — daan, bhent, saunp"],
        ["Give respect", "आदर दे", "aadar de"],
        ["Give pain", "दुख दे", "dukh de"],
        ["Take a bath", "नहा", "nahaa / gosal kar"],
        ["Take a photo", "फोटो खिंच", "photo khinch"],
        ["Take time", "समें लै", "samen lai"],
        ["Take medicine", "दवाई लै", "davaaee lai"],
        ["Give an answer", "जवाब दे", "jawaab de"],
        ["Take a seat", "बैठ जा", "baith jaa / seet lai"],
        ["Give a speech", "भाशण दे", "bhaashan de"],
    ],
    608: [
        ["To feel / seem (laag-) — it seems good", "चंगा लगदा आए", "changaa lagdaa aaey"],
        ["I feel cold", "मिगी ठंड लगदी आए", "migee thand lagdee aaey"],
        ["It suits you", "तुसां उत्ते चंगा लगदा आए", "tusaan ute changaa lagdaa aaey"],
        ["To be attached", "लगणा — प्यार लगणा", "laganaa — piyaar laganaa"],
        ["To begin (work)", "कम लग पया", "kam lag payaa"],
        ["To cost", "इन्ने पैसे लगे", "inne paise lage"],
        ["To take time", "समें लगे", "samen lage"],
        ["Headache 'lags'", "सिर दर्द लगदा आए", "sir dard lagdaa aaey"],
        ["Feel ashamed", "शर्म लगदी आए", "sharm lagdee aaey"],
        ["Feel hungry", "भूख लगदी आए", "bhookh lagdee aaey"],
        ["Feel sleepy", "नींद लगदी आए", "neend lagdee aaey"],
        ["It appears / looks", "दिखदा लगदा आए", "dikhdaa lagdaa aaey"],
        ["Match / pair (verb)", "जोड़ लगे", "jorr lage"],
        ["To stick", "चिपकणा — गोंद लगी", "chipakanaa — gond lagee"],
        ["To be needed", "लोड़ लगे", "lorr lage"],
        ["To get habit", "आदत लगी", "aadat lagee"],
        ["To befall (trouble)", "मुसीबत लगी", "museebat lagee"],
        ["Feel like (I want to go)", "जाणे दा मन लगदा", "jaane daa man lagdaa"],
        ["Colour 'sits' well", "रंग चंगा लगदा आए", "rang changaa lagdaa aaey"],
        ["Seems expensive", "महंगा लगदा आए", "mahangaa lagdaa aaey"],
    ],
    609: [
        ["Good", "चंगा", "changaa / bhalaa"],
        ["Bad", "माड़ा", "maarraa / kharaab"],
        ["Big", "बड़ा", "baraa"],
        ["Small", "छोटा", "chhottaa"],
        ["New", "नवां", "navaan / nayaa"],
        ["Old", "पुराणा", "puraanaa / bujjurg"],
        ["Hot", "गरम", "garam"],
        ["Cold", "ठंडा", "thandaa"],
        ["Sweet", "मिठा", "mithaa / mitthaa"],
        ["Bitter", "कड़वा", "kadvaa"],
        ["Sour", "खट्टा", "khattaa"],
        ["Salted", "नमकीन", "namakeen"],
        ["Clean", "साफ", "saaf"],
        ["Dirty", "गंदा", "gandaa / mailaa"],
        ["Beautiful", "सोणा", "sonaa / sundar"],
        ["Ugly", "बदसूरत", "badsoorat"],
        ["Tall", "लंबा", "lambaa"],
        ["Short", "छोटा", "chhottaa / nivaan"],
        ["Fat", "मोटा", "motaa"],
        ["Thin", "पतला", "patlaa"],
    ],
    610: [
        ["Quickly", "जल्दी", "jaldee / tez"],
        ["Slowly", "हौले", "haule / dheere"],
        ["Always", "हमेशा", "hameshaa"],
        ["Never", "कदे नेईं", "kade nein"],
        ["Sometimes", "कदे-कदे", "kade-kade"],
        ["Often", "अक्सर", "aksar"],
        ["Today", "आज", "aaj"],
        ["Tomorrow", "कल", "kal"],
        ["Yesterday", "कल (बीता)", "kal (beetaa) / paihlen din"],
        ["Now", "हुन", "hun / ab"],
        ["Then", "फिर", "phir / us vele"],
        ["Here", "इत्थे", "itthe"],
        ["There", "उत्थे", "utthe"],
        ["Where", "कुथे", "kuthe"],
        ["How", "कियां", "kiyaan / kiven"],
        ["Why", "कियों", "kiyon / kaah"],
        ["Very", "बड़ा", "baraa / bahut"],
        ["Little", "थोड़ा", "thoddaa"],
        ["Too much", "ज्यादा", "zyaadaa"],
        ["Enough", "बस", "bas / kaafee"],
    ],
    611: [
        ["Upstairs", "उप्पर", "uppar"],
        ["Downstairs", "थल्ले", "thalle"],
        ["Inside", "अंदर", "andar"],
        ["Outside", "बाहर", "baahar"],
        ["Near", "नेड़े", "nedde"],
        ["Far", "दूर", "door"],
        ["Left", "खब्बा", "khabbaa"],
        ["Right", "सज्जा", "sajjaa"],
        ["Straight", "सीधा", "seedhaa"],
        ["Around", "चारों पासे", "chaaron paase"],
        ["Ahead", "अग्गे", "agge / aage"],
        ["Behind", "पिछे", "pichhe"],
        ["Together", "इकठ्ठे", "ikatthe"],
        ["Alone", "इकल्ला", "ikallaa"],
        ["Perhaps", "शायद", "shaayad"],
        ["Certainly", "जरूर", "jaroor / pakkaa"],
        ["Maybe", "हो सकदा", "ho sakdaa"],
        ["Again", "फेर", "pher"],
        ["Already", "पैह्लें ही", "paihlen hi"],
        ["Yet / still", "हले", "hale / phir vee"],
    ],
    612: [
        ["Potato", "आलू", "aaloo"],
        ["Onion", "गांदा", "gaandaa / pyaaz"],
        ["Tomato", "टमाटर", "tamaatar"],
        ["Brinjal / eggplant", "बैंगन", "baingan"],
        ["Cauliflower", "फूलगोभी", "phoolgobhee"],
        ["Cabbage", "गोभी", "gobhee"],
        ["Spinach", "पालक", "paalak"],
        ["Pumpkin", "कद्दू", "kaddoo"],
        ["Bottle gourd", "लौकी", "laukee"],
        ["Radish", "मूली", "moolee"],
        ["Carrot", "गाजर", "gaajar"],
        ["Peas", "मटर", "mattar"],
        ["Beans", "फलियां", "faliyaan"],
        ["Chilli", "मिर्च", "mirch"],
        ["Coriander", "धनिया", "dhaniyaa"],
        ["Garlic", "लहसुन", "lahasun"],
        ["Ginger", "अदरक", "adrak"],
        ["Turnip", "शलगम", "shalgam"],
        ["Lady's finger", "भिंडी", "bhinddee"],
        ["Cucumber", "खीरा", "kheeraa"],
    ],
    613: [
        ["Mango", "आम", "aam"],
        ["Banana", "केला", "kelaa"],
        ["Apple", "सेब", "seb"],
        ["Grapes", "अंगूर", "angoor"],
        ["Orange", "संतरा", "santraa"],
        ["Guava", "अमरूद", "amrood"],
        ["Pomegranate", "अनार", "anaar"],
        ["Watermelon", "तरबूज़", "tarbooz"],
        ["Muskmelon", "खरबूज़", "kharbooz"],
        ["Papaya", "पपीता", "papeetaa"],
        ["Pear", "नाशपाती", "naashpaatee"],
        ["Plum / jamun", "जामुन", "jaamun"],
        ["Lemon", "नींबू", "neemboo / limboo"],
        ["Coconut", "नारियल", "naariyal"],
        ["Lychee", "लीची", "leechee"],
        ["Sweet lime", "मौसंबी", "mausambee"],
        ["Fig", "अंजीर", "anjeer"],
        ["Cherry (loan)", "चेरी", "cheree"],
        ["Strawberry", "स्ट्रॉबेरी", "strauberee"],
        ["Ripe (fruit)", "पका", "pakaa"],
    ],
    614: [
        ["Crow", "काँव", "kaanv"],
        ["Sparrow", "चिड़ी", "chirdee"],
        ["Pigeon", "कबूतर", "kabootar"],
        ["Parrot", "तोता", "totaa"],
        ["Peacock", "मोर", "mor"],
        ["Eagle", "बाज़", "baaz"],
        ["Owl", "उल्लू", "ulloo"],
        ["Duck", "बतख", "batakh"],
        ["Hen", "मुर्गी", "murgee"],
        ["Rooster", "मुर्गा", "murgaa"],
        ["Swallow", "अबाबील", "abaabeel"],
        ["Koel", "कोयल", "koyal"],
        ["Myna", "मैना", "mainaa"],
        ["Crane (bird)", "बगुला", "bagulaa"],
        ["Woodpecker", "कठफोड़ा", "kathfoddaa"],
        ["Singing bird", "गायक पंछी", "gaayak panchee"],
        ["Nest", "घुल्ल", "ghull"],
        ["Wing", "पर", "par"],
        ["Feather", "पंख", "pankh"],
        ["Beak", "चुंज", "chunj"],
    ],
    615: [
        ["Ant", "कीड़ी", "keerree"],
        ["Bee", "मक्खी", "makkhee"],
        ["Fly", "मक्ख", "makk"],
        ["Mosquito", "मच्छर", "machchar"],
        ["Butterfly", "तितली", "titatlee"],
        ["Spider", "मकड़ी", "makadree"],
        ["Cockroach", "तिलचटा", "tilchattaa"],
        ["Worm", "कीड़", "keerr"],
        ["Louse", "जूं", "joon"],
        ["Bedbug", "खटमल", "khatmal"],
        ["Termite", "दीमक", "deemak"],
        ["Grasshopper", "टिड्डा", "tiddaa"],
        ["Beetle", "भुंड", "bhund"],
        ["Scorpion", "बिछू", "bichhoo"],
        ["Centipede", "कनखजूरा", "kankhajooraa"],
        ["Leech", "जोंक", "jonk"],
        ["Honey", "शहद", "shahad"],
        ["Hive", "छत्ता", "chattaa"],
        ["Bite (insect)", "काटना", "kattanaa"],
        ["Poisonous", "ज़हरीला", "zahereelaa"],
    ],
    616: [
        ["Red", "लाल", "laal"],
        ["Blue", "नीला", "neelaa"],
        ["Green", "हरा", "haraa"],
        ["Yellow", "पीला", "peelaa"],
        ["White", "सफेद", "safed"],
        ["Black", "काला", "kaalaa"],
        ["Brown", "भूरा", "bhooraa"],
        ["Orange (colour)", "नारंगी", "naarangee"],
        ["Pink", "गुलाबी", "gulaabee"],
        ["Purple", "बैंगनी", "bainganee"],
        ["Grey", "स्लेटी", "sletee / gre"],
        ["Golden", "सुनहरा", "sunaharaa"],
        ["Silver", "चांदी रंग", "chaandee rang"],
        ["Dark", "गढ़ा", "garrhaa / gaharaa"],
        ["Light (colour)", "हल्का", "halkaa"],
        ["Bright", "चमकदार", "chamakadaar"],
        ["Pale", "फिक्का", "fikkaa"],
        ["Colourful", "रंगदार", "rangadaar"],
        ["Stain", "दाग", "daag"],
        ["Dye", "रंग", "rang"],
    ],
    617: [
        ["Rose", "गुलाब", "gulaab"],
        ["Marigold", "गेंदा", "gendaa"],
        ["Jasmine", "चमेली", "chambelee"],
        ["Lotus", "कमल", "kamal"],
        ["Sunflower", "सूरजमुखी", "soorajmukhee"],
        ["Hibiscus", "गुड़हल", "gudahal"],
        ["Champa", "चंपा", "champaa"],
        ["Lily", "कुमुदनी", "kumudanee"],
        ["Tulip (loan)", "ट्यूलिप", "toolip"],
        ["Bouquet", "गुलदस्ता", "guldastaa"],
        ["Petals", "पंखुड़ियां", "pankhurriyaan"],
        ["Thorn", "कांटा", "kandaa"],
        ["Fragrance", "महक", "mahak"],
        ["Garden", "बाग", "baag"],
        ["Flower bed", "फूलों की क्यारी", "phoolaan dee kyaaree"],
        ["Wild flower", "जंगली फूल", "jangalee phool"],
        ["To bloom", "खिलना", "khilanaa"],
        ["Withered", "मुरझाया", "murjhaayaa"],
        ["Pollen", "पराग", "paraag"],
    ],
    618: [
        ["Dog", "कुत्ता", "kuttaa"],
        ["Cat", "बिल्ली", "billee"],
        ["Cow", "गां", "gaan"],
        ["Buffalo", "भैंस", "bhains"],
        ["Goat", "बकरी", "bakree"],
        ["Sheep", "भेड़", "bhedd"],
        ["Horse", "घोड़ा", "ghorraa"],
        ["Donkey", "खोता", "khotaa"],
        ["Elephant", "हाथी", "haathee"],
        ["Lion", "शेर", "sher"],
        ["Tiger", "बाघ", "baagh"],
        ["Monkey", "बंदर", "baandar"],
        ["Rabbit", "खरगोश", "khargosh"],
        ["Camel", "ऊंट", "oonth"],
        ["Bear", "रिछ", "richchh"],
        ["Deer", "हिरन", "hiran"],
        ["Squirrel", "गिलहरी", "gilaharee"],
        ["Rat", "चूहा", "choohaa"],
        ["Ox", "बैल", "bald"],
        ["Pig", "सूअर", "sooar"],
    ],
    619: [
        ["Friend", "दोस्त", "dost"],
        ["Guest", "मेहमान", "mehmaan"],
        ["Neighbour", "पड़ोसी", "parosee"],
        ["Money", "पैसा", "paisaa"],
        ["Work", "काम", "kam"],
        ["Time", "समां", "samaan"],
        ["News", "खबर", "khabar"],
        ["Problem", "मुसीबत", "museebat"],
        ["Help", "मदद", "madad"],
        ["Love", "प्यार", "piyaar"],
        ["Anger", "गुस्सा", "gussaa"],
        ["Peace", "सुकून", "sukoon"],
        ["Luck", "नसीब", "naseeb"],
        ["Pain", "दुख", "dukh"],
        ["Joy", "खुशी", "khushee"],
        ["Fear", "डर", "dar"],
        ["Hope", "उम्मीद", "ummeed"],
        ["Idea", "विचार", "vichaar"],
        ["Chance", "मौका", "maukaa"],
        ["Result", "नतीजा", "nateejaa"],
    ],
}
