# -*- coding: utf-8 -*-
"""Replace lesson tables 510–542 with longer natural English / Nepali / transliteration rows."""
import json
from copy import deepcopy
from pathlib import Path

ROOT = Path(__file__).resolve().parent
DATA = ROOT / "data_nepali.json"

# Lessons 513 (simple present) and 515 (present continuous) already use long sentences — leave unchanged.
SKIP = {513, 515}

# id -> list of [en, ne, tr]
ROWS: dict[int, list[list[str]]] = {
    510: [
        [
            "I always tell people clearly that I am still learning Nepali.",
            "म अझै नेपाली सिकिरहेको छु भनेर सबैलाई स्पष्ट भन्छु।",
            "ma ajhai nepālī sikiriheko chu bhanera sabailāī spaṣṭa bhan-chu",
        ],
        [
            "When you speak politely, you often use this respectful form of “you”.",
            "तपाईं विनम्रतापूर्वक बोल्दा यो सम्मानजनक “तपाईं” प्रयोग गर्नुहुन्छ।",
            "tapāīṃ vinamratāpūrvaka boldā yo sammānajanaka “tapāīṃ” prayog garnuhuncha",
        ],
        [
            "That famous writer lives in Pokhara, and everyone says he is very kind.",
            "उ प्रसिद्ध लेखक पोखरामा बस्छन् र सबैले उनलाई धेरै दयालु भन्छन्।",
            "u prasiddha lekhaka pokharāmā baschan ra sabaile unalāī dherai dayālu bhan-chan",
        ],
        [
            "We walk together to the temple every Saturday morning.",
            "हामी हरेक शनिबार बिहान मन्दिर सँगै जान्छौं।",
            "hāmī hareka śanibāra bihāna mandira saṃgai jān-chauṃ",
        ],
        [
            "They brought sweets for all the children in our street yesterday.",
            "उनीहरूले हिजो हाम्रो गल्लीका सबै बच्चाहरूलाई मिठाइ ल्याए।",
            "unīharūle hijo hāmro gallīkā sabai baccāharūlāī miṭhāi lyāe",
        ],
        [
            "This blue umbrella is mine, but that black one belongs to my brother.",
            "यो नीलो छाता मेरो हो, तर त्यो कालो भाइको हो।",
            "yo nīlo chātā mero ho, tara tyo kālo bhāiko ho",
        ],
        [
            "That old house on the hill looks empty every evening.",
            "डाँडामा रहेको त्यो पुरानो घर हरेक साँझ खाली देखिन्छ।",
            "ḍā~ḍāmā raheko tyo purāno ghara hareka sā~jha khālī dekhincha",
        ],
        [
            "My full name is on my passport, so please read it slowly.",
            "मेरो पूरा नाम राहदानीमा छ, कृपया ढिलो पढ्नुहोस्।",
            "mero pūrā nāma rāhadānīmā cha, kṛpayā ḍhilo paḍhnuhos",
        ],
        [
            "What is your name, and which village are you from originally?",
            "तपाईंको नाम के हो र मूलतः कुन गाउँका हुनुहुन्छ?",
            "tapāīṃko nāma ke ho ra mūlataḥ kuna gāu~kā hunuhuncha",
        ],
        [
            "After the long journey I am fine, but I still need a little rest.",
            "लामो यात्रापछि म ठिक छु, तर अलि आराम चाहिन्छ।",
            "lāmo yātrāpachi ma ṭhika cha, tara ali ārāma cāhincha",
        ],
        [
            "How are you today — did you sleep well last night?",
            "आज तपाईंलाई कस्तो छ — हिजो राम्रोसँग सुत्नुभयो?",
            "āja tapāīṃlāī kasto cha — hijo rāmrosa~ga sutnubhayo",
        ],
        [
            "This is my grammar book, and I read a few pages every day.",
            "यो मेरो व्याकरणको किताब हो, म हरेक दिन केही पृष्ठ पढ्छु।",
            "yo mero vyākaraṇako kitāba ho, ma hareka dina kehī pr̥ṣṭha paḍh-chu",
        ],
        [
            "That quiet man at the door is my friend from college.",
            "ढोकामा उभिएका त्यो शान्त मान्छे मेरो कलेजको साथी हो।",
            "ḍhokāmā ubhieka tyo śānta mānche mero kalejako sāthī ho",
        ],
        [
            "He is a math teacher who explains every problem very patiently.",
            "उहाँ गणित शिक्षक हुनुहुन्छ जसले हरेक प्रश्न धैर्यपूर्वक सम्झाउनुहुन्छ।",
            "uhā~ gaṇita śikṣaka hunuhuncha jasle hareka praśna dhairypūrvaka samjhāunuhuncha",
        ],
        [
            "She looks happy today because her sister finally arrived.",
            "उनी आज खुसी देखिन्छिन् किनभने उनकी बहिनी अन्त्यमा आइन्।",
            "unī āja khusī dekhin-chin kinabhane unakī bahinī antyamā āin",
        ],
        [
            "We are happy because our team won the match last night.",
            "हामी खुसी छौं किनभने हाम्रो टोलीले हिजो रात खेल जित्यो।",
            "hāmī khusī chauṃ kinabhane hāmro ṭolīle hijo rāta khela jityo",
        ],
        [
            "The children are playing football in the school yard right now.",
            "बच्चाहरू अहिले विद्यालयको मैदानमा फुटबल खेलिरहेका छन्।",
            "baccāharū ahile vidyālayako maidānamā phuṭbal khelirahekā chan",
        ],
    ],
    511: [
        [
            "When you address elders, you use this polite plural form of “you”.",
            "जेठो मानिसलाई सम्बोधन गर्दा तपाईं यस्तो सम्मानजनक बहुवचन प्रयोग गर्नुहुन्छ।",
            "jeṭho mānisalāī sambodhana gardā tapāīṃ yasto sammānajanaka bahuvacana prayog garnuhuncha",
        ],
        [
            "Those honoured guests smiled when we welcomed them at the gate.",
            "ती माननीय पाहुनाहरूले हामीले ढोकामा स्वागत गर्दा मुस्कुराए।",
            "tī mānanīya pāhunāharūle hāmīle ḍhokāmā svāgata gardā muskurāe",
        ],
        [
            "All of you please sit down; tea will be ready in five minutes.",
            "तपाईं सबै कृपया बस्नुहोस्; पाँच मिनेटमा चिया तयार हुन्छ।",
            "tapāīṃ sabai kṛpayā basnuhos; pāñca mineṭamā ciyā tayāra huncha",
        ],
        [
            "All people in this village help each other during the harvest.",
            "यस गाउँका सबै मानिसहरू बाली काट्दा एकअर्कालाई मद्दत गर्छन्।",
            "yasa gāu~kā sabai mānisaharū bālī kāṭdā ekarkālāī maddata gar-chan",
        ],
        [
            "Welcome to you all; we are glad you could come to our small party.",
            "सबैलाई स्वागत छ; हामी खुसी छौं तपाईंहरू हाम्रो सानो भेटघाटमा आउन सक्नुभयो।",
            "sabailāī svāgata cha; hāmī khusī chauṃ tapāīṃharū hāmro sāno bheṭghāṭamā āuna saknubhayo",
        ],
        [
            "Thank you to everyone who helped carry these heavy boxes upstairs.",
            "यी भारी बाकस माथि लैजान मद्दत गर्ने सबैलाई धन्यवाद।",
            "yī bhārī bākasa māthi laijāna maddata garne sabailāī dhanyavāda",
        ],
        [
            "How are you all feeling after such a long bus journey?",
            "यति लामो बस यात्रापछि तपाईंहरू सबैलाई कस्तो लागिरहेको छ?",
            "yati lāmo basa yātrāpachi tapāīṃharū sabailāī kasto lāgiriheko cha",
        ],
        [
            "We are all fine, and we hope your family is healthy too.",
            "हामी सबै सन्चै छौं, र तपाईंको परिवार पनि सन्चो होस् भन्ने कामना गर्छौं।",
            "hāmī sabai sancai chauṃ, ra tapāīṃko parivāra pani sanco hos bhanne kāmanā gar-chauṃ",
        ],
        [
            "The honoured guests arrived exactly when the programme began.",
            "माननीय पाहुनाहरू कार्यक्रम सुरु हुँदै गर्दा ठ्याक्कै आइपुग्नुभयो।",
            "mānanīya pāhunāharū kāryakrama suru hu~dai gardā ṭhyākkai āipugnubhayo",
        ],
        [
            "Please give your elders respect even when you disagree with them.",
            "तपाईंको विचार नमिल्दा पनि जेठो मानिसलाई सम्मान दिनुहोस्।",
            "tapāīṃko vicāra namildā pani jeṭho mānisalāī sammāna dinuhos",
        ],
        [
            "Both of my parents work, so both of us children help at home.",
            "मेरा आमाबुबा दुवै काम गर्नुहुन्छ, त्यसैले हामी दाजुभाइ घरमा मद्दत गर्छौं।",
            "merā āmābubā duvai kāma garnuhuncha, tyasaile hāmī dājubhāi gharamā maddata gar-chauṃ",
        ],
        [
            "Both of us will visit the doctor tomorrow morning together.",
            "हामी दुवै भोलि बिहान सँगै डाक्टरकहाँ जानेछौं।",
            "hāmī duvai bholi bihāna saṃgai ḍākṭarakahā~ jāne-chauṃ",
        ],
        [
            "You two should finish your homework before you turn on the TV.",
            "तपाईं दुईले टिभी खोल्नुअघि गृहकार्य सकाउनुहोस्।",
            "tapāīṃ duīle ṭibhī kholnuaghi gr̥hakārya sakāunuhos",
        ],
        [
            "Many people gathered in the square to hear the announcement.",
            "धेरै मानिसहरू घोषणा सुन्न चोकमा जम्मा भए।",
            "dherai mānisaharū ghoṣaṇā sunna cokamā jamā bhae",
        ],
        [
            "All human beings deserve kindness, no matter where they are born.",
            "जन्म कतै भए पनि सबै मानव जातिलाई दया र सम्मान पाउनुपर्छ।",
            "janma katai bhae pani sabai mānava jātilāī dayā ra sammāna pāunuparcha",
        ],
    ],
    512: [
        [
            "Every morning I do my exercises before I eat breakfast.",
            "म हरेक बिहान नास्ता खानुअघि व्यायाम गर्छु।",
            "ma hareka bihāna nāstā khānuaghi vyāyāma gar-chu",
        ],
        [
            "You eat fresh fruit every day because the doctor advised you.",
            "डाक्टरले सल्लाह दिएकाले तिमी हरेक दिन ताजा फलफूल खान्छौ।",
            "ḍākṭarale sallāha diekāle timī hareka dina tājā phalphūl khān-chau",
        ],
        [
            "He goes to work by bicycle when the weather is pleasant.",
            "मौसम राम्रो हुँदा ऊ साइकलमा काममा जान्छ।",
            "mausama rāmro hu~dā ū sāikalamā kāmamā jān-cha",
        ],
        [
            "She comes to our house every Dashain to meet my grandmother.",
            "उनी हरेक दशैं मेरी हजुरआमालाई भेट्न हाम्रो घर आउँछिन्।",
            "unī hareka daśai merī hajurāmālāī bheṭna hāmro ghara āu~chin",
        ],
        [
            "We see the mountains clearly from the roof of our school.",
            "हामी विद्यालयको छानाबाट पहाड स्पष्ट देख्छौं।",
            "hāmī vidyālayako chānābāṭa pahāḍa spaṣṭa dekh-chauṃ",
        ],
        [
            "The neighbours speak quietly in the yard after dinner.",
            "छिमेकीहरू बेलुका खानापछि आँगनमा शान्तिसँग बोल्छन्।",
            "chimekīharū belukā khānapachi ā~ganamā śāntisa~ga bol-chan",
        ],
        [
            "I read the news online before I start my homework.",
            "म गृहकार्य सुरु गर्नुअघि अनलाइनमा समाचार पढ्छु।",
            "ma gr̥hakārya suru garnuaghi analāinamā samācāra paḍh-chu",
        ],
        [
            "You write a long email when you want to explain something important.",
            "तिमी महत्त्वपूर्ण कुरा बुझाउन चाहँदा लामो इमेल लेख्छौ।",
            "timī mahattvapūrṇa kurā bujhāuna cāha~dā lāmo imela lekh-chau",
        ],
        [
            "We need to eat on time if we want to stay healthy.",
            "स्वस्थ रहन हामी समयमै खानुपर्छ।",
            "svastha rahana hāmī samayamai khānuparcha",
        ],
        [
            "They will go to Pokhara next month for a short holiday.",
            "उनीहरू अर्को महिना छोटो बिदामा पोखरा जानेछन्।",
            "unīharū arko mahinā choṭo bidāmā pokharā jāne-chan",
        ],
        [
            "I will come to your party if I finish work early.",
            "काम छिटो सकेमा म तपाईंको पार्टीमा आउनेछु।",
            "kāma chiṭo sakema ma tapāīṃko pārṭīmā āune-chu",
        ],
        [
            "Please come a little earlier so we can talk before the meeting.",
            "भेटघाटअघि कुरा गर्न कृपया अलि छिटो आउनुहोस्।",
            "bheṭghāṭaghi kurā garna kṛpayā ali chiṭo āunuhos",
        ],
        [
            "I want to see the Himalaya from the plane window one day.",
            "म एक दिन विमानको झ्यालबाट हिमाल हेर्न चाहन्छु।",
            "ma eka dina vimānako jhyālabāṭa himāla herna cāhan-chu",
        ],
        [
            "She likes to speak slowly when she teaches beginners.",
            "उनी सुरुवाती विद्यार्थीलाई पढाउँदा बिस्तारै बोल्छिन्।",
            "unī suruvātī vidyārthīlāī paḍhāu~dā bistārai bol-chin",
        ],
        [
            "Please give this packet to your sister when you meet her.",
            "उनलाई भेट्दा कृपया यो प्याकेट दिनुहोस्।",
            "unalāī bheṭdā kṛpayā yo pyākeṭa dinuhos",
        ],
    ],
    514: [
        ["I am a science student in grade ten at this school.", "म यस विद्यालयमा कक्षा दशको विज्ञान विद्यार्थी हुँ।", "ma yasa vidyālayamā kakṣā daśako vijñāna vidyārthī hu~"],
        ["Our principal is a kind teacher who listens to every student.", "हाम्रो प्रधानाध्यापक दयालु शिक्षक हुनुहुन्छ जसले हरेक विद्यार्थीको कुरा सुन्नुहुन्छ।", "hāmro pradhānādhyāpaka dayālu śikṣaka hunuhuncha jasle hareka vidyārthīko kurā sunnuhuncha"],
        ["The young guide is brave enough to cross the river on a rope bridge.", "युवा गाइडले डोरीको पुलबाट नदी तर्न साहस देखाउनुभएको छ।", "yuvā gāiḍale ḍorīko pulabāṭa nadī tarna sāhas dekhāunubhaeko cha"],
        ["My sister is happy because she passed her exam with high marks.", "मेरी दिदी खुसी छिन् किनभने उनले राम्रो नम्बरले परीक्षा पास गरिन्।", "merī didī khusī chin kinabhane unale rāmro nambarale parīkṣā pās garin"],
        ["This thick dictionary on my desk belongs to the library.", "मेरो टेबलमा रहेको यो मोटो शब्दकोश पुस्तकालयको हो।", "mero ṭebalamā raheko yo moṭo śabdakośa pustakālayako ho"],
        ["That stone house on the hill looks older than our village temple.", "डाँडामा रहेको त्यो ढुङ्गे घर हाम्रो गाउँको मन्दिरभन्दा पुरानो देखिन्छ।", "ḍā~ḍāmā raheko tyo ḍhu~ge ghara hāmro gāu~ko mandirabhandā purāno dekhincha"],
        ["We are close friends who have studied Nepali together for two years.", "हामी दुई वर्षदेखि सँगै नेपाली पढेका घनिष्ठ साथी हौं।", "hāmī duī varṣadekhi saṃgai nepālī paḍheka ghaniṣṭha sāthī hauṃ"],
        ["The neighbourhood children are playing cricket in the narrow lane.", "छिमेकीका बच्चाहरू पातलो गल्लीमा क्रिकेट खेलिरहेका छन्।", "chimekīkā baccāharū pātalo gallīmā krikeṭa khelirahekā chan"],
        ["After the long trek I am fine, though my legs still feel a little tired.", "लामो पैदल यात्रापछि म ठिक छु, तर खुट्टा अलि थाकेको अनुभव हुन्छ।", "lāmo paidala yātrāpachi ma ṭhika cha, tara khuṭṭā ali thākeko anubhava huncha"],
        ["This winter jacket is new, so it keeps me warm on cold mornings.", "यो जाडो कोट नयाँ छ, त्यसैले चिसो बिहान पनि न्यानो राख्छ।", "yo jāḍo koṭa nayā~ cha, tyasaile ciso bihāna pani nyāno rākh-cha"],
        ["Who is she — the woman in the blue sari near the stage?", "उनी को हुन् — मञ्च नजिक नीलो साडी लगाएकी महिला?", "unī ko hun — mañca najika nīlo sāḍī lagāekī mahilā"],
        ["Where is the clean toilet on this floor — I could not find the sign.", "यस तल्लामा सफा शौचालय कहाँ छ — मैले संकेत पाइन।", "yasa tallāmā safā śaucālaya kahā~ cha — maile saṅketa pāina"],
        ["There is no doubt that honest work always brings peace of mind.", "इमान्दार परिश्रमले मनमा शान्ति ल्याउँछ भन्नेमा कुनै शंका छैन।", "imāndāra pariśramale manamā śānti lyāu~cha bhanne-mā kunai śaṃkā chaina"],
        ["My father is tall, so he can easily reach the top shelf.", "मेरो बुबा अग्लो हुनुहुन्छ, त्यसैले माथिलो ताक सजिलै पुग्नुहुन्छ।", "mero bubā aglo hunuhuncha, tyasaile māthilo tāka sajilai pugnuhuncha"],
        ["She looks beautiful in the soft light of the evening sun.", "साँझको कोमल प्रकाशमा उनी सुन्दर देखिन्छिन्।", "sā~jhako komala prakāśamā unī sundara dekhin-chin"],
    ],
    516: [
        ["Tomorrow morning I will go to the bank before it opens.", "भोलि बिहान बैंक खुल्नुअघि म जानेछु।", "bholi bihāna baiṅk khulnuaghi ma jāne-chu"],
        ["You will come to our house for tea if the rain stops.", "पानी रोकियो भने तिमी चियाको लागि हाम्रो घर आउने छौ।", "pānī rokiyo bhane timī ciyāko lāgi hāmro ghara āune chau"],
        ["He will eat lunch with us after the meeting ends.", "बैठक सकेपछि उसले हामीसँग दिउँसो खाना खानेछ।", "baiṭhaka sakepachi usale hāmīsa~ga diuṃso khānā khāne-cha"],
        ["She will read the whole novel during the winter holiday.", "जाडो बिदामा उनी पूरै उपन्यास पढ्छिन्।", "jāḍo bidāmā unī pūrai upanyāsa paḍh-chin"],
        ["We will speak to the head teacher about the exam schedule.", "परीक्षाको समय तालिकाबारे हामी प्रधानाध्यापकसँग बोल्नेछौं।", "parīkṣāko samaya tālikābāre hāmī pradhānādhyāpakasa~ga bolne-chauṃ"],
        ["The students will play a friendly match on the school field on Saturday.", "शनिबार विद्यार्थीहरू विद्यालय मैदानमा मैत्रीपूर्ण खेल खेल्नेछन्।", "śanibāra vidyārthīharū vidyālaya maidānamā maitrīpūrṇa khela khelne-chan"],
        ["I will give my old books to the library when I clean my room.", "कोठा सफा गर्दा म पुराना किताब पुस्तकालयलाई दिनेछु।", "koṭhā safā gardā ma purānā kitāba pustakālayalāī dine-chu"],
        ["You will take this medicine twice a day until the fever goes.", "ज्वरो नघटेसम्म तपाईंले यो औषधि दिनमा दुई पटक लिनुहुन्छ।", "jvaro na ghaṭesamma tapāīṃle yo auṣadhi dinamā duī paṭaka linuhuncha"],
        ["Tomorrow I will come with fresh vegetables from our garden.", "भोलि म आफ्नो बारीबाट ताजा तरकारी लिएर आउनेछु।", "bholi ma āphno barībāṭa tājā tarkārī liera āune-chu"],
        ["Will it rain today, or will the sky stay clear for the festival?", "आज पानी पर्नेछ, कि चाडका लागि आकाश खुला रहनेछ?", "āja pānī parnecha, ki cāḍakā lāgi ākāśa khulā rahane-cha"],
        ["Will you go on a trip to Chitwan with your cousins next month?", "अर्को महिना तपाईं चितवन भ्रमणमा जानुहुन्छ?", "arko mahinā tapāīṃ citavana bhramaṇamā jānuhuncha"],
        ["Will she come to the station to see us off at six?", "उनी बजे हामीलाई बिदाइ दिन स्टेशन आउने हो?", "unī baje hāmīlāī bidāi dina sṭeśana āune ho"],
        ["I will stay for one night at my uncle’s house in Pokhara.", "म पोखरामा मामाको घरमा एक रात बस्नेछु।", "ma pokharāmā māmāko gharamā eka rāta basne-chu"],
        ["Get well soon and drink plenty of warm water.", "छिटो निको हुनुहोस् र न्यानो पानी धेरै पिउनुहोस्।", "chiṭo niko hunuhos ra nyāno pānī dherai piunuhos"],
        ["Good luck to you in your final examination this year.", "यस वर्षको अन्तिम परीक्षामा तपाईंलाई शुभकामना।", "yasa varṣako antima parīkṣāmā tapāīṃlāī śubhakāmanā"],
    ],
    517: [
        ["At noon I will be eating with my colleagues in the office canteen.", "दिउँसो म कार्यालयको क्यान्टिनमा सहकर्मीसँग खाँदै हुनेछु।", "diuṃso ma kāryālayako kyānṭināma sahakarmīsa~ga khā~dai hune-chu"],
        ["This time tomorrow you will be going to the airport by taxi.", "भोलि यसै बेला तपाईं ट्याक्सीमा विमानस्थल जाँदै हुनुहुन्छ।", "bholi yasai belā tapāīṃ ṭyāksīmā vimānasthala jā~dai hunuhuncha"],
        ["He will be reading the report while we wait in the lobby.", "हामी लबीमा पर्खँदा उसले प्रतिवेदन पढिरहेको हुनेछ।", "hāmī labīmā parkha~dā usale prativedana paḍhiraheko hune-cha"],
        ["She will be working from home because the roads are flooded.", "बाटो डुबेकाले उनी घरबाटै काम गरिरहेकी हुनेछिन्।", "bāṭo ḍubekāle unī gharabāṭai kāma garirahekī hune-chin"],
        ["We will be waiting at the bus stop until you send a message.", "तपाईंले सन्देश नपठाउनुसम्म हामी बस स्टपमा पर्खिरहने छौं।", "tapāīṃle sandeśa na paṭhāunusamma hāmī basa sṭapamā parkhirahane chauṃ"],
        ["The children will be playing indoors if the storm continues.", "आँधी जारी रहेमा बच्चाहरू भित्र खेल्दै हुनेछन्।", "ā~dhī jārī rahema baccāharū bhitra kheldai hune-chan"],
        ["At five I will be studying chemistry in the quiet reading room.", "पाँच बजे म शान्त पढ्ने कोठामा रसायन पढ्दै हुनेछु।", "pāñca baje ma śānta paḍhne koṭhāmā rasāyana paḍhdai hune-chu"],
        ["Tomorrow morning you will be travelling east toward Ilam.", "भोलि बिहान तपाईं इलामतर्फ पूर्व जाँदै हुनुहुन्छ।", "bholi bihāna tapāīṃ ilamatarpa pūrva jā~dai hunuhuncha"],
        ["Next week he will be here to sign the contract in person.", "अर्को हप्ता उनी अहिले सम्झौतामा हस्ताक्षर गर्न यहाँ हुनेछन्।", "arko haptā unī ahile samjhautāmā hastākṣara garna yahā~ hune-chan"],
        ["After dinner I will be sleeping early because I feel tired.", "बेलुका खानापछि म थाकेकाले छिटो सुत्नेछु।", "belukā khānapachi ma thākekāle chiṭo sutne-chu"],
        ["You will be writing the invitation cards while I buy the sweets.", "म मिठाइ किन्दा तिमी निम्तो कार्ड लेखिरहने छौ।", "ma miṭhāi kindā timī nimto kāḍa lekhirahane chau"],
        ["They will be eating together after the prayer ceremony ends.", "प्रार्थना समाप्त भएपछि तिनीहरू सँगै खाँदै हुनेछन्।", "prārthanā samāpta bhaepachi tinīharū saṃgai khā~dai hune-chan"],
        ["She will be singing the national song at the opening ceremony.", "उद्घाटन समारोहमा उनी राष्ट्रिय गीत गाउँदै हुनेछिन्।", "udghāṭana samārohamā unī rāṣṭriya gīta gāu~dai hune-chin"],
        ["We will be watching the match on the big screen in the hall.", "हामी हलमा ठूलो पर्दामा खेल हेर्दै हुनेछौं।", "hāmī halamā ṭhūlo pardāmā khela herdai hune-chauṃ"],
        ["He will be running the last lap while the crowd cheers loudly.", "भीड ठूलो स्वरले कराउँदा ऊ अन्तिम चक्कर दौडिरहेको हुनेछ।", "bhīḍ ṭhūlo svarale karāu~dā ū antima cakkara dauḍiraheko hune-cha"],
    ],
    518: [
        ["Yesterday I went to the market with my mother on foot.", "हिजो म आमासँग पैदल बजार गएँ।", "hijo ma āmāsa~ga paidala bajāra gae~"],
        ["You came just in time before the shop closed its shutters.", "पसल ढुकुटी लाउनु अघि तिमी ठ्याक्कै समयमा आयौ।", "pasala ḍhukuṭī lāunu aghi timī ṭhyākkai samayamā āyau"],
        ["He slept soundly after the long journey from Kathmandu.", "काठमाडौँबाट लामो यात्रापछि उनी गाढ निद्रामा सुते।", "kāṭhamāḍaũbāṭa lāmo yātrāpachi unī gāḍha nidramā sute"],
        ["She ran fast when she heard her name called on the loudspeaker.", "लाउडस्पीकरमा नाम बोलियो भन्ने सुनेपछि उनी छिटो दौडिइन्।", "lāuḍaspīkaramā nāma boliyo bhanne sunepachi unī chiṭo dauḍiin"],
        ["We arrived at the village before the sun went down.", "सूर्य अस्ताउनु अघि हामी गाउँ आइपुग्यौं।", "sūrya astāunu aghi hāmī gāu~ āipugyauṃ"],
        ["They left early so they could catch the first bus.", "पहिलो बस समात्न उनीहरूले बिहानै छोडे।", "pahilo basa samātnā unīharūle bihānai choḍe"],
        ["I fell on the slippery steps when I was carrying heavy bags.", "भारी झोला बोक्दा चिप्लो खुट्टामा म ढले।", "bhārī jholā bokdā ciplo khuṭṭāmā ma ḍhale"],
        ["You stood quietly in line until your number appeared on the screen.", "स्क्रिनमा नम्बर नआउँदासम्म तिमी लाममा शान्त उभियौ।", "skrinamā nambara nāu~dāsamma timī lāmamā śānta ubhiyau"],
        ["He died peacefully surrounded by his children and grandchildren.", "छोराछोरी र नातिनातिनाको बीचमा उनको शान्त मृत्यु भयो।", "chorāchorī ra nātinātināko bīcamā unako śānta mṛtyu bhayo"],
        ["She laughed loudly when her little brother told a silly joke.", "सानो भाइले मजाक गर्दा उनी ठूलो स्वरले हाँसिन्।", "sāno bhāile majāka gardā unī ṭhūlo svarale hā~sin"],
        ["Long time no see — I did not expect to meet you in this crowd.", "धेरै भयो देखेन — यति भीडमा भेट्ने अपेक्षा थिएन।", "dherai bhayo dekhena — yati bhīḍamā bheṭne apekṣā thiena"],
        ["I am lost in this new city, so please show me the way to the hotel.", "यो नयाँ सहरमा म हराएको छु, कृपया होटलको बाटो देखाइदिनुहोस्।", "yo nayā~ saharamā ma harāeko cha, kṛpayā hoṭalako bāṭo dekhāidinuhos"],
        ["He began to run when the stray dog suddenly barked behind him.", "आवारा कुकुर अचानक भुकेपछि उ दौडन थाल्यो।", "āvārā kukura acānaka bhukepachi u dauḍana thālyo"],
        ["She came last in the race but she still received warm applause.", "दौडमा उनी अन्तिममा आइन् तर ताली फेरि पाइन्।", "dauḍamā unī antimamā āin tara tālī pheri pāin"],
        ["The dog is dead; the neighbours buried it near the old tree.", "कुकुर मरेको छ; छिमेकीले पुरानो रूख नजिक गाडे।", "kukura mareko cha; chimekīle purāno rūkha najika gāḍe"],
    ],
    519: [
        ["Yesterday evening I ate rice and lentils with pickled vegetables at home.", "हिजो बेलुका मैले घरमा अचारसँग भात र दाल खाएँ।", "hijo belukā maile gharamā acārasa~ga bhāta ra dāla khāe~"],
        ["You saw me waving from the balcony, but the traffic was too loud.", "तपाईंले बाल्कोनबाट हात हल्लाउँदै मलाई देख्नुभयो, तर भीडले आवाज डुबायो।", "tapāīṃle bālakonabāṭa hāta hallāu~dai malāī dekhnubhayo, tara bhīḍale āvāja ḍubāyo"],
        ["He read the whole newspaper while he waited for his tea.", "चिया पर्खँदा उसले सम्पूर्ण समाचारपत्र पढ्यो।", "ciyā parkha~dā usale sampūrṇa samācārapatra paḍhyo"],
        ["She wrote a long letter to her brother who works abroad.", "विदेश काम गर्ने भाइलाई उनले लामो पत्र लेखिन्।", "videśa kāma garne bhāilāī unale lāmo patra lekhin"],
        ["We did the work together before the rain ruined the paint.", "पानीले रङ खराब नगर्दासम्म हामीले काम सकायौं।", "pānīle raṅa kharāba nagardāsamma hāmīle kāma sakāyauṃ"],
        ["They took it to the repair shop because it stopped working.", "काम नगर्दा उनीहरूले मर्मत गर्न लिए।", "kāma nagardā unīharūle marmata garna lie"],
        ["I gave water to the thirsty traveller who knocked on our door.", "ढोका ढकढक्याउने तिर्खाएको यात्रीलाई मैले पानी दिएँ।", "ḍhokā ḍhakaḍhakyāune tirkhāeko yātrīlāī maile pānī die~"],
        ["You bought a book about Nepali grammar from the small stall.", "तपाईंले सानो पसलबाट नेपाली व्याकरणको किताब किन्नुभयो।", "tapāīṃle sāno pasalabāṭa nepālī vyākaraṇako kitāba kinnubhayo"],
        ["He killed the snake that had entered our kitchen at night.", "राति भान्सामा पसेको सर्पलाई उनले मारे।", "rāti bhānsāmā paseko sarpalāī unale māre"],
        ["She broke the glass when she slipped on the wet floor.", "भिजेको फ्लोरमा चिप्लिएर उनले गिलास भाँचिन्।", "bhijeko phlōramā cipliera unale gilāsa bhā~cin"],
        ["I lost my bag in the crowded bus, so I filed a report at the station.", "भीडो बसमा झोला हराएपछि मैले स्टेशनमा उजुरी गरेँ।", "bhīḍo basamā jholā harāepachi maile sṭeśanamā ujurī gare~"],
        ["He did not speak during the meeting because he felt nervous.", "बैठकमा उनी घबराएकाले बोलेनन्।", "baiṭhakamā unī ghabarāekāle bolenan"],
        ["They stopped talking when the teacher entered the classroom.", "शिक्षक कक्षामा पसेपछि उनीहरुले बोल्न छोडे।", "śikṣaka kakṣāmā pasepachi unīharule bolna choḍe"],
        ["She admired him for helping the old woman cross the road.", "बुढी आमालाई बाटो काट्न मद्दत गरेकाले उनले उनको प्रशंसा गरिन्।", "buḍhī āmālāī bāṭo kāṭna maddata garekāle unale unako praśaṃsā garin"],
        ["You broke the rules, so the coach asked you to leave the field.", "नियम तोडेकाले प्रशिक्षकले मैदान छोड्न भन्यो।", "niyama toḍekāle praśikṣakale maidāna choḍna bhanyo"],
    ],
    520: [
        ["I was at home yesterday because the school declared a holiday.", "हिजो विद्यालय बिदा भएकाले म घरमै थिएँ।", "hijo vidyālaya bidā bhaekāle ma gharamai thie~"],
        ["You were right about the weather; the storm came exactly as you said.", "तपाईं मौसमको बारेमा सहि हुनुहुन्थ्यो; आँधी ठ्याक्कै आयो।", "tapāīṃ mausamako bāremā sahi hunuhunthyo; ā~dhī ṭhyākkai āyo"],
        ["He was alone in the office because everyone else had already left.", "सबै गइसकेपछि कार्यालयमा उनी एक्लै थिए।", "sabai gaisakepachi kāryālayamā unī eklai thie"],
        ["She was happy when she heard that her visa had been approved.", "भिसा पास भयो भन्ने सुनेपछि उनी खुसी भइन्।", "bhisā pās bhyo bhanne sunepachi unī khusī bhain"],
        ["The soup was delicious because my aunt cooked it with fresh herbs.", "काकीले ताजा जडीबुटीले पकाएकाले यो सूप स्वादिष्ट थियो।", "kākīle tājā jaḍībuṭīle pakāekāle yo sūpa svādiṣṭa thiyo"],
        ["Those shoes were really cheap at the fair, so we bought two pairs.", "मेलामा त्यो जुत्ता साँच्चै सस्तो थियो, त्यसैले हामीले दुई जोर किन्यौं।", "melāmā tyo juttā sā~ccai sasto thiyo, tyasaile hāmīle duī jora kinyauṃ"],
        ["The maths problem was very difficult, but we solved it together.", "गणितको प्रश्न धेरै गाह्रो थियो, तर हामीले सँगै समाधान गर्यौं।", "gaṇitako praśna dherai gāhro thiyo, tara hāmīle saṃgai samādhāna garyauṃ"],
        ["The ticket was not expensive, so we could afford the concert.", "टिकट महँगो थिएन, त्यसैले हामीले कन्सर्ट हेर्न सक्यौं।", "ṭikaṭa maha~go thiena, tyasaile hāmīle kansarṭa herna sakyauṃ"],
        ["His smile was good to see after so many days of worry.", "चिन्ताको दिनपछि उनको मुस्कान राम्रो थियो।", "cintāko dinapachi unako muskāna rāmro thiyo"],
        ["They got married in a small temple with only close relatives.", "नजिकका नातेदार मात्र भएको सानो मन्दिरमा उनीहरुले बिहे गरे।", "najikakā nātedāra mātra bhaeko sāno mandiramā unīharule bihe gare"],
        ["I was a child when my family moved to this green valley.", "परिवार यस हरियाली उपत्यकामा सर्दा म बच्चा थिएँ।", "parivāra yasa hariyālī upatyakāmā sardā ma baccā thie~"],
        ["You were late because the bridge was closed for repairs.", "पुल मर्मतका लागि बन्द भएकाले तिमी ढिलो थियौ।", "pula marmatakā lāgi banda bhaekāle timī ḍhilo thiyau"],
        ["That was a good idea, so we decided to follow your plan.", "त्यो राम्रो विचार थियो, त्यसैले हामीले तपाईंको योजना मान्यौं।", "tyo rāmro vicāra thiyo, tyasaile hāmīle tapāīṃko yojana mānyauṃ"],
        ["There was no problem with the documents when we checked them again.", "फेरि हेर्दा कागजातमा कुनै समस्या थिएन।", "pheri herdā kāgjātamā kunai samasyā thiena"],
        ["She was crying softly because she missed her friend who had moved away.", "साथी सरेपछि उनी शान्तसँग रोइरहेकी थिइन्।", "sāthī sarepachi unī śāntisa~ga roirahekī thiin"],
    ],
    521: [
        ["Last Dashain I went to my village and met all my cousins.", "गएको दशैं म गाउँ गएँ र सबै चिनजान भेटेँ।", "gaeko daśai ma gāu~ gae~ ra sabai cinajāna bheṭe~"],
        ["He came to the station with a bouquet when we returned from Pokhara.", "हामी पोखराबाट फर्कँदा उहाँ फूलको गuche लिएर स्टेशन आउनुभयो।", "hāmī pokharābāṭa pharka~dā uhā~ phūlako guccha liera sṭeśana āunubhayo"],
        ["I did my homework carefully before I watched the football match.", "फुटबल हेर्नुअघि मैले गृहकार्य ध्यानले गरे।", "phuṭbal hernuaghi maile gr̥hakārya dhyānale gare"],
        ["You gave your old coat to the man who was shivering in the cold.", "जाडोले काँपेको मानिसलाई तपाईंले पुरानो कोट दिनुभयो।", "jāḍole kā~peko mānisalāī tapāīṃle purāno koṭa dinubhayo"],
        ["She took the heavy bag from the old woman and carried it to the bus.", "बुढी आमाको भारी झोला उनले लिइन् र बससम्म पुर्‍याइन्।", "buḍhī āmāko bhārī jholā unale liin ra bassamma puryāin"],
        ["We saw a rainbow over the hills after the short afternoon rain.", "दिउँसोको छोटो पानीपछि पहाडमाथि इन्द्रेणी देख्यौं।", "diuṃsoko choṭo pānīpachi pahāḍamāthi indreṇī dekhyauṃ"],
        ["They knew nothing about the surprise party we had planned.", "हामीले योजना गरेको अचम्मको पार्टीबारे उनीहरुलाई थाहा थिएन।", "hāmīle yojanā gareko acammako pārṭībāre unīharulāī thāhā thiena"],
        ["I got a letter from the university on the day results were published.", "नतिजा आएको दिन विश्वविद्यालयबाट मैले पत्र पाएँ।", "natijā āeko dina viśvavidyālayabāṭa maile patra pāe~"],
        ["He became quiet after the doctor explained the serious news.", "डाक्टरले गम्भीर कुरा बुझाएपछि उनी शान्त बने।", "ḍākṭarale gambhīra kurā bujhāepachi unī śānta bane"],
        ["She could swim across the pool when she was only eight years old.", "आठ वर्षको उमेरमै उनी पौंड पार गर्न सक्छिन्।", "āṭha varṣako umeramai unī pauṇḍa pāra garna sak-chin"],
        ["I had to stay home because my little brother had a high fever.", "सानो भाइलाई ज्वरो आएकाले मैले घरमै बस्नु पर्यो।", "sāno bhāilāī jvaro āekāle maile gharamai basnu paryo"],
        ["You wanted to travel abroad, so you saved money every month.", "विदेश जान चाहन्थ्यौ, त्यसैले हरेक महिना पैसा जोगाउँथ्यौ।", "videśa jāna cāhanthyau, tyasaile hareka mahinā paisā jogāuthyau"],
        ["He brought fresh apples from Mustang in a big cardboard box.", "उसले ठूलो कार्टुनमा मुस्ताङबाट ताजा स्याउ ल्यायो।", "usale ṭhūlo kāṭunamā mustāṅabāṭa tājā syāu lyāyo"],
        ["We sent the parcel by courier so it would arrive before Friday.", "शुक्रबारअघि पुगोस् भनेर हामीले कुरियरबाट पठायौं।", "śukrabāraghi pugos bhanera hāmīle kuriyarabāṭa paṭhāyauṃ"],
        ["They built a small library for the children of this ward.", "यस वडाका बच्चाहरूका लागि तिनीहरूले सानो पुस्तकालय निर्माण गरे।", "yasa vaḍākā baccāharūkā lāgi tinīharūle sāno pustakālaya nirmāṇa gare"],
    ],
    522: [
        ["I was eating momos when you called me on the phone.", "तिमीले फोन गर्दा म म:म खाँदै थिएँ।", "timīle phona gardā ma momo khā~dai thie~"],
        ["You were going uphill with a heavy backpack when I saw you.", "मैले देख्दा तिमी भारी झोला बोकेर उकालो जाँदै थियौ।", "maile dekh-dā timī bhārī jholā bokera ukālo jā~dai thiyau"],
        ["He was reading under the tree while the children played nearby.", "बच्चाहरू नजिक खेल्दा उनी रूखमुनि पढ्दै थिए।", "baccāharū najika kheldā unī rūkhamuni paḍhdai thie"],
        ["She was writing the address on the envelope with a blue pen.", "उनी नीलो कलमले खाममा ठेगाना लेख्दै थिइन्।", "unī nīlo kalamale khāmamā ṭhegāna lekhdai thiin"],
        ["We were playing chess in the park until the street lights came on.", "बत्ती बल्नुसम्म हामी पार्कमा चेस खेलिरहेका थियौं।", "battī balnusamma hāmī pārkamā ces khelirahekā thiyauṃ"],
        ["They were speaking in low voices because the baby was asleep.", "बच्चा सुतेकाले उनीहरु बोल्दै थिए।", "baccā sutekāle unīharu boldai thie"],
        ["I was sleeping on the train when we crossed the long bridge.", "लामो पुल तर्दा म रेलमा सुतिरहेको थिएँ।", "lāmo pula tardā ma relamā sutiraheko thie~"],
        ["You were working on your laptop while the rain beat on the window.", "पानी झ्यालमा पर्दा तिमी ल्यापटपमा काम गर्दथ्यौ।", "pānī jhyālamā pardā timī lyāpaṭapamā kāma gardathyau"],
        ["He was running to catch the bus that was already moving.", "चलिसकेको बस समात्न उनी दौडिरहेका थिए।", "calisakeko basa samātnā unī dauḍirahekā thie"],
        ["She was cooking dal bhat when the guests rang the bell.", "पाहुनाले घण्टी बजाउँदा उनी दाल भात पकाउँदै थिइन्।", "pāhunāle ghaṇṭī bajāu~dā unī dāla bhāta pakāu~dai thiin"],
        ["When I was going to the shop, I met my old teacher.", "पसल जाँदा मैले पुरानो शिक्षक भेटेँ।", "pasala jā~dā maile purāno śikṣaka bheṭe~"],
        ["They were watching the same film for the second time that week.", "सो हप्ता दोस्रो पटक उनीहरू एउटै फिल्म हेरिरहेका थिए।", "so haptā dosro paṭaka unīharū euṭai philm herirahekā thie"],
        ["I was studying late at night because the exam was near.", "परीक्षा नजिक भएकाले राति ढिलोसम्म पढ्दै थिएँ।", "parīkṣā najika bhaekāle rāti ḍhilosamma paḍhdai thie~"],
        ["You were listening to the radio news while you cleaned the kitchen.", "भान्सा सफा गर्दा तिमी रेडियोको समाचार सुन्दै थियौ।", "bhānsā safā gardā timī reḍiyoko samācāra sundai thiyau"],
        ["He was waiting at the gate when the school bus finally arrived.", "स्कुल बस अन्त्यमा आइपुग्दा उनी ढोकामा पर्खिरहेका थिए।", "skula basa antyamā āipugdā unī ḍhokāmā parkhirahekā thie"],
    ],
    523: [
        ["I have eaten already, so please do not wait for me at lunch.", "मैले खाइसकेको छु, दिउँसो मेरो लागि नपर्खनुहोस्।", "maile khāisakeko chu, diuṃso mero lāgi naparkhanuhos"],
        ["You have come a long way; rest for a while and drink some water.", "तिमी टाढाबाट आएका छौ; अलि आराम गर र पानी पिउ।", "timī ṭāḍhabāṭa āekā chau; ali ārāma gara ra pānī piu"],
        ["He has gone to India for training and will return next month.", "तालिमका लागि उहाँ भारत जानुभएको छ, अर्को महिना फर्कनुहुन्छ।", "tālimakā lāgi uhā~ bhārata jānubhaeko cha, arko mahinā pharkanuhuncha"],
        ["She has read every novel in this small library twice.", "उनीले यस सानो पुस्तकालयका उपन्यास दुई पटक पढेकी छिन्।", "unīle yasa sāno pustakālayakā upanyāsa duī paṭaka paḍhekī chin"],
        ["We have done our best; now we must wait for the final result.", "हामीले पूर्ण प्रयास गरेका छौं; अब अन्तिम नतिजाको पर्खाइ।", "hāmīle pūrṇa prayāsa garekā chauṃ; aba antima natijāko parkhāi"],
        ["They have left for the airport, so we should hurry if we want to see them.", "उनीहरू विमानस्थल लागिसके; भेट्न हतार गर्नुपर्छ।", "unīharū vimānasthala lāgisake; bheṭna hatāra garnuparcha"],
        ["I had eaten before you arrived, but I can still join you for tea.", "तिमी आउनु अघि मैले खाइसकेको थिएँ, तर चियामा सँगै बस्न सक्छु।", "timī āunu aghi maile khāisakeko thie~, tara ciyāmā saṃgai basna sak-chu"],
        ["You had seen that film before, yet you laughed at the same joke.", "त्यो फिल्म तिमीले अघि नै देख्नु भएको थियो, तर एउटै जोकमा हाँस्यौ।", "tyo philm timīle aghi nai dekhnubhaeko thiyo, tara euṭai jokamā hā~syau"],
        ["He had written the report before the manager asked for it.", "म्यानेजरले माग्नुअघि नै उनले प्रतिवेदन लेखेका थिए।", "myānejara-le māgnuaghi nai unale prativedana lekhekā thie"],
        ["Have you eaten anything today, or should we order soup?", "आज केही खानु भयो, कि सूप मगाउँ?", "āja kehī khānu bhayo, ki sūpa magāu~"],
        ["I am finished with this chapter, so I will take a short walk.", "यो अध्याय सकिएको छु, अलि हिँडेर आउँछु।", "yo adhyāya sakieko chu, ali hiṃḍera āu~chu"],
        ["She has finished her homework and is playing with the cat.", "उनले गृहकार्य सकाइसकेकी छिन् र बिरालोसँग खेल्दै छिन्।", "unale gr̥hakārya sakāisakekī chin ra birālosa~ga kheldai chin"],
        ["They have married in a simple ceremony with family only.", "परिवार मात्र भएको साधारण विवाहमा उनीहरुले बिहे गरेका छन्।", "parivāra mātra bhaeko sādhāraṇa vivāhamā unīharule bihe garekā chan"],
        ["I have lost my umbrella somewhere on this crowded bus.", "यो भीडो बसमा कतै मैले छाता हारेको छु।", "yo bhīḍo basamā katai maile chātā hāreko chu"],
        ["You have understood the main idea, so we can move to exercises now.", "मुख्य कुरा बुझेका छौ, अब अभ्यासतर्फ जान सक्छौं।", "mukhya kurā bujhekā chau, aba abhyāsatarpa jāna sak-chauṃ"],
    ],
    524: [
        ["The old clock is still hanging in the hall of our house.", "हाम्रो घरको हलमा पुरानो घडी अझै झुन्डिएको छ।", "hāmro gharako halamā purāno ghaḍī ajhai jhuṃḍieko cha"],
        ["Your phone is lying on the wooden table next to the lamp.", "बत्ती नजिकको काठको टेबलमा तपाईंको फोन राखिएको छ।", "battī najikako kāṭhako ṭebalamā tapāīṃko phona rākhieko cha"],
        ["We walked home from the fair when the buses stopped running.", "बस नचलेपछि मेलाबाट हामी हिँडेर घर फर्क्यौं।", "bas na calepachi melābāṭa hāmī hiṃḍera ghara pharkyauṃ"],
        ["Tomorrow morning we will walk to the market to buy fresh fish.", "भोलि बिहान ताजा माछा किन्न हामी बजार हिँड्नेछौं।", "bholi bihāna tājā māchā kinna hāmī bajāra hiṃḍne-chauṃ"],
        ["That tall boy’s school bag is hanging behind the door.", "ढोकापछाडि लामो केटाको झोला झुन्डिएको छ।", "ḍhokāpachāḍi lāmo keṭāko jholā jhuṃḍieko cha"],
        ["Please walk with me to the station; I do not like to go alone.", "स्टेशनसम्म मसँग हिँड्नुहोस्; एक्लै जान मन लाग्दैन।", "sṭeśanasamma masa~ga hiṃḍnuhos; eklai jāna mana lāgdaina"],
        ["I cooked this rice for you because you said you were hungry.", "भोक लागेको भनेकाले मैले यो भात पकाएँ।", "bhoka lāgeko bhanekāle maile yo bhāta pakāe~"],
        ["We cannot live long without clean drinking water in this heat.", "यो गर्मीमा सफा पानी बिना धेरै बेर बाँच्न सकिँदैन।", "yo garmīmā safā pānī binā dherai bera bā~cna saki~daina"],
        ["This room looks exactly like the one in my grandmother’s old photo.", "हजुरआमाको पुरानो फोटोको कोठाजस्तै यो कोठा देखिन्छ।", "hajurāmāko purāno phoṭoko koṭhājastai yo koṭhā dekhincha"],
        ["I am sitting in the warm kitchen while my aunt fries bread.", "काकीले रोटी तल्दा म न्यानो भान्सामा बसेको छु।", "kākīle roṭī taldā ma nyāno bhānsāmā baseko cha"],
        ["The heavy book is on the table; please do not lean on it.", "भारी किताब टेबलमा छ; नछोइदिनुहोस्।", "bhārī kitāba ṭebalamā cha; na chhodnuhos"],
        ["Come from the side gate if the main gate is already locked.", "मुख्य ढोका बन्द भए छेउको ढोकाबाट आउनुहोस्।", "mukhya ḍhokā banda bhae cheuko ḍhokābāṭa āunuhos"],
        ["Go to the station quickly; your uncle is waiting with the tickets.", "छिटो स्टेशन जानुहोस्; मामाले टिकट बोकेर पर्खिरहनुभएको छ।", "chiṭo sṭeśana jānuhos; māmāle ṭikaṭa bokera parkhirahanubhaeko cha"],
        ["This basket of fruit is for you; take it to your hostel room.", "यो फलफूलको टोकरी तपाईंको लागि हो; होस्टेल कोठामा लैजानुहोस्।", "yo phalphūlako ṭokarī tapāīṃko lāgi ho; hosṭel koṭhāmā laijānuhos"],
        ["Fold the cloth neatly like this before you pack it in the suitcase.", "सूटकेसमा हाल्नुअघि कपडा यसरी मिलाएर फोल्ड गर्नुहोस्।", "sūṭakesamā hālnuaghi kapadā yasari milāera phoḍa garnuhos"],
    ],
    525: [
        ["Please give this money to me; I need to pay the shopkeeper.", "कृपया यो पैसा मलाई दिनुहोस्; पसलेलाई तिर्नु छ।", "kṛpayā yo paisā malāī dinuhos; pasalelāī tirnu cha"],
        ["I am going to school early today because we have a science test.", "आज विज्ञानको परीक्षा भएकाले म छिटो विद्यालय जाँदैछु।", "āja vijñānako parīkṣā bhaekāle ma chiṭo vidyālaya jā~daichu"],
        ["Come to my house on Saturday; my mother will cook special food.", "शनिबार मेरो घर आउनुहोस्; आमाले विशेष खाना पकाउनुहुन्छ।", "śanibāra mero ghara āunuhos; āmāle viśeṣa khānā pakāunuhuncha"],
        ["We work from early morning to late evening during the harvest.", "बाली काट्दा हामी बिहानैदेखि अबेरसम्म काम गर्छौं।", "bālī kāṭdā hāmī bihānaidekhi aberasamma kāma gar-chauṃ"],
        ["Walk with me only to the station; my cousin will take the train from there.", "स्टेशनसम्म मात्र सँगै हिँड्नुहोस्; त्यहाँबाट भिनाजु रेल चढ्नुहुन्छ।", "sṭeśanasamma mātra saṃgai hiṃḍnuhos; tyahā~bāṭa bhināju rela caḍhnuhuncha"],
        ["Give this parcel to him when you see him at the office.", "कार्यालयमा भेट्दा यो पार्सल उहाँलाई दिनुहोस्।", "kāryālayamā bheṭdā yo pārsal uhā~lāī dinuhos"],
        ["I will send the documents to you by email this evening.", "बेलुका कागजात इमेलमार्फत तपाईंलाई पठाउनेछु।", "belukā kāgjāt imelmārphata tapāīṃlāī paṭhāune-chu"],
        ["I said to her honestly that I could not come to the party.", "मैले उनलाई साँच्चै भनेँ कि पार्टीमा आउन सकिनँ।", "maile unalāī sā~ccai bhae~ ki pārṭīmā āuna saki~na~"],
        ["Welcome to Nepal; we hope you enjoy the mountains and the food.", "नेपालमा स्वागत छ; हिमाल र खाना रुचाउनुहोस्।", "nepālamā svāgata cha; himāla ra khānā rucāunuhos"],
        ["Take me to the hotel near the river; my bags are very heavy.", "नदी नजिकको होटलमा लैजानुहोस्; झोला धेरै भारी छ।", "nadī najikako hoṭalamā laijānuhos; jholā dherai bhārī cha"],
        ["The narrow road to the airport passes through small villages.", "एयरपोर्ट जाने बाटो साना गाउँहरूबाट गुज्रिन्छ।", "eyaraporṭa jāne bāṭo sānā gāu~harūbāṭa gujrincha"],
        ["From here to there is only ten minutes on foot.", "यताबाट उता पैदल दश मिनेट मात्र लाग्छ।", "yatābāṭa utā paidala daśa mineṭa mātra lāgcha"],
        ["I want to go to the market now before the vegetable stall closes.", "तरकारी पसल बन्द नहुँदै अहिले नै बजार जान चाहन्छु।", "tarkārī pasala banda nahu~dai ahile nai bajāra jāna cāhan-chu"],
        ["I wrote a long letter to my father about my exam results.", "परीक्षाको नतिजा बुबालाई लामो पत्र लेखेँ।", "parīkṣāko natijā bubālāī lāmo patra lekhe~"],
        ["Carry water to the plants on the roof every morning in summer.", "गर्मीमा हरेक बिहान छानामा रहेका बिरुवालाई पानी दिनुहोस्।", "garmīmā hareka bihāna chānāmā rahekā biruvālāī pānī dinuhos"],
    ],
    526: [
        ["I see you in the crowd every day, but we never have time to talk.", "भीडमा हरेक दिन तिमीलाई देख्छु, तर कुरा गर्न समय हुँदैन।", "bhīḍamā hareka dina timīlāī dekh-chu, tara kurā garna samaya hu~daina"],
        ["You called me last night when I was already asleep.", "म सुतिसकेपछि तिमीले मलाई फोन गर्नुभयो।", "ma sutisakepachi timīle malāī phona garnubhayo"],
        ["He met her at the conference and they talked for an hour.", "सम्मेलनमा उसले उनलाई भेट्यो र एक घन्टा कुरा गरे।", "sammelanamā usale unalāī bheṭyo ra eka ghanṭā kurā gare"],
        ["She helped him carry the boxes up the steep stairs.", "उकालो खुट्टामा उनले उनलाई बाकस बोक्न मद्दत गरिन्।", "ukālo khuṭṭāmā unale unalāī bākasa bokna maddata garin"],
        ["We invited them to dinner because they helped us in the flood.", "बाढीमा मद्दत गरेकाले हामीले उनीहरूलाई भोजमा निम्तो दियौं।", "bāḍhīmā maddata garekāle hāmīle unīharūlāī bhojamā nimto diyauṃ"],
        ["They follow us quietly when we walk home late at night.", "राति ढिलो घर फर्कँदा उनीहरूले हामीलाई चुपचाप पछ्याउँछन्।", "rāti ḍhilo ghara pharka~dā unīharūle hāmīlāī cupcāpa pachyāu~chan"],
        ["I love you and I will always stand by you in difficult times.", "म तिमीलाई माया गर्छु र गाह्रो बेलामा सँधै साथ दिनेछु।", "ma timīlāī māyā garchu ra gāhro belāmā saṃdhai sātha dine-chu"],
        ["Give him water first; he looks very tired after the journey.", "पहिले उसलाई पानी दिनुहोस्; यात्रापछि उ थाकेको देखिन्छ।", "pahile usalāī pānī dinuhos; yātrāpachi u thākeko dekhincha"],
        ["Tell her the truth gently; she is still worried about the news.", "उनलाई बिस्तारै साँचो भन्नुहोस्; समाचारले अझै चिन्ता छ।", "unalāī bistārai sā~co bhannuhos; samācārale ajhai cintā cha"],
        ["Ask the teacher after class if you did not understand the homework.", "गृहकार्य नबुझेमा कक्षा पछि शिक्षकलाई सोध्नुहोस्।", "gr̥hakārya nabujhema kakṣā pachi śikṣakalāī sodhnuhos"],
        ["I need a doctor now because my throat hurts badly.", "घाँटी धेरै दुखेकाले अहिले डाक्टर चाहिन्छ।", "ghā~ṭī dherai dukhekāle ahile ḍākṭara cāhincha"],
        ["Call the police if you see anything strange near the bank.", "बैंक नजिक अनौठो देख्नुभयो भने पुलिसलाई कल गर्नुहोस्।", "baiṅk najika anauṭho dekhnubhayo bhane pulisalāī kala garnuhos"],
        ["Meet my friend at the gate; he will give you the tickets.", "ढोकामा मेरो साथीलाई भेट्नुहोस्; उनले टिकट दिन्छन्।", "ḍhokāmā mero sāthīlāī bheṭnuhos; unale ṭikaṭa din-chan"],
        ["She avoids me in the corridor because we argued yesterday.", "हिजो झगडा भएकाले उनी करिडोरमा मलाई टाल्छिन्।", "hijo jhagaḍā bhaekāle unī kariḍoramā malāī ṭāl-chin"],
        ["Who built this beautiful wooden bridge across the small river?", "सानो नदीमाथि यो राम्रो काठे पुल कसले बनायो?", "sāno nadīmāthi yo rāmro kāṭhe pula kasale banāyo"],
    ],
    527: [
        ["My name is on the list, but yours is not there yet.", "मेरो नाम सूचीमा छ, तर तिम्रो अझै छैन।", "mero nāma sūcīmā cha, tara timro ajhai chaina"],
        ["Your house looks beautiful with the new flowers in the garden.", "बारीमा नयाँ फूल भएकाले तिम्रो घर राम्रो देखिन्छ।", "barīmā nayā~ phūla bhaekāle timro ghara rāmro dekhincha"],
        ["His book is full of notes from every chapter of the course.", "उनको पुस्तक पाठ्यक्रमका हरेक अध्यायका टिपोटले भरिएको छ।", "unako pustaka pāṭhyakramakā hareka adhyāyakā ṭipoṭle bharieko cha"],
        ["Her friend will travel with us to Lumbini next month.", "अर्को महिना उनको साथी हामीसँग लुम्बिनी जानेछिन्।", "arko mahinā unako sāthī hāmīsa~ga lumbinī jāne-chin"],
        ["My father drives the taxi, and my mother teaches small children.", "मेरो बुबा ट्याक्सी चलाउनुहुन्छ, आमाले साना बच्चालाई पढाउनुहुन्छ।", "mero bubā ṭyāksī calāunuhuncha, āmāle sānā baccālāī paḍhāunuhuncha"],
        ["Your mother called to ask if you had reached home safely.", "तिमी सुरक्षित घर पुगे कि भनेर तिम्रो आमाले फोन गर्नुभयो।", "timī surakṣita ghara puge ki bhanera timro āmāle phona garnubhayo"],
        ["Our home is small, but it is always full of laughter.", "हाम्रो घर सानो छ, तर सधै हाँसोले भरिएको छ।", "hāmro ghara sāno cha, tara sadhai hā~sole bharieko cha"],
        ["Their language sounds soft and musical when they sing folk songs.", "लोक गीत गाउँदा तिनीहरूको भाषा मिठो र मधुर सुनिन्छ।", "loka gīta gāu~dā tinīharūko bhāṣā miṭho ra madhura sunincha"],
        ["This is my book; I wrote my name on the first page.", "यो मेरो किताब हो; पहिलो पृष्ठमा नाम लेखेँ।", "yo mero kitāba ho; pahilo pr̥ṣṭhamā nāma lekhe~"],
        ["That is your pen; you left it on my desk yesterday.", "त्यो तिम्रो कलम हो; हिजो मेरो टेबलमा छोड्यौ।", "tyo timro kalama ho; hijo mero ṭebalamā choḍyau"],
        ["His eyes are blue like the clear sky on a winter morning.", "जाडो बिहानको खुला आकाशजस्तै उसका आँखा नीलो छन्।", "jāḍo bihānako khulā ākāśajastai usakā ā~khā nīlo chan"],
        ["My sister has a job at the bank near the main square.", "मेरी बहिनी मुख्य चोक नजिकको बैंकमा जागिर गर्छिन्।", "merī bahinī mukhya coka najikako baiṅkamā jāgira gar-chin"],
        ["Her name is on the certificate that hangs on the classroom wall.", "कक्षाको भित्तामा झुन्डिएको प्रमाणपत्रमा उनको नाम छ।", "kakṣāko bhittāmā jhuṃḍieko pramāṇapatramā unako nāma cha"],
        ["I miss you when you are away even for a few days.", "केही दिन बाहिर भए पनि म तिमीलाई सम्झन्छु।", "kehī dina bāhira bhae pani ma timīlāī samjhanchu"],
        ["Thanks for your help with my homework; I could not finish alone.", "गृहकार्यमा मद्दत गर्नुभएकोमा धन्यवाद; एक्लैले सकिनँ।", "gr̥hakāryamā maddata garnubhaekomā dhanyavāda; eklaile sakina~"],
    ],
    528: [
        ["What is your full name as it appears on your citizenship card?", "तपाईंको नागरिकतामा लेखिए अनुसार पूरा नाम के हो?", "tapāīṃko nāgarikatāmā lekhie anusāra pūrā nāma ke ho"],
        ["Who is she — the woman in the red sari who just entered?", "भर्खर भित्र पसेकी रातो साडी लगाएकी महिला को हुन्?", "bharakhara bhitra pasekī rāto sāḍī lagāekī mahilā ko hun"],
        ["Where are you staying tonight while you attend the workshop?", "कार्यशालामा हुँदा आज रात कहाँ बस्नुहुन्छ?", "kāryaśālamā hu~dā āja rāta kahā~ basnuhuncha"],
        ["When will you come back from Delhi if the flight stays on time?", "उडान समयमै भयो भने दिल्लीबाट कहिले फर्कनुहुन्छ?", "uḍāna samayamai bhayo bhane dillībāṭa kahile pharkanuhuncha"],
        ["How are you feeling now after taking the medicine for three days?", "तीन दिन औषधि खाइसकेपछि अहिले कस्तो लागिरहेको छ?", "tīna dina auṣadhi khāisakepachi ahile kasto lāgiriheko cha"],
        ["How much is this silk shawl — I did not see the price tag.", "यो रेशमी शालको मूल्य कति हो — मूल्य ट्याग देखिनँ।", "yo reśamī śālako mūlya kati ho — mūlya ṭyāga dekhina~"],
        ["What are you doing with those tools on the roof at this hour?", "यति बेला छानामा ती औजारले के गर्दै हुनुहुन्छ?", "yati belā chānāmā tī aujārale ke gardai hunuhuncha"],
        ["Who is that man talking loudly near the temple gate?", "मन्दिरको ढोकानजिक ठूलो स्वरले कुरा गर्ने मान्छे को हो?", "mandirako ḍhokānajika ṭhūlo svarale kurā garne mānche ko ho"],
        ["Where is the clean toilet on this floor — turn left or right?", "यस तल्लामा सफा शौचालय कहाँ छ — दायाँ कि बायाँ?", "yasa tallāmā safā śaucālaya kahā~ cha — dāyā~ ki bāyā~"],
        ["Why did you go to the office on Sunday if it was closed?", "आइतबार कार्यालय बन्द भएको थियो भने किन जानुभयो?", "āitabāra kāryālaya banda bhaeko thiyo bhane kina jānu-bhayo"],
        ["Which bag is yours among these three that look the same?", "एकै जस्तो देखिने यी तीन झोलामध्ये कुन तपाईंको हो?", "ekai jasto dekhine yī tīna jholāmadhye kuna tapāīṃko ho"],
        ["How many people are coming to dinner — should I cook extra rice?", "कति जना खान आउँदैछन् — थप भात पकाउँ?", "kati janā khāna āu~daichan — thapa bhāta pakāu~"],
        ["Do you speak Nepali every day at home with your children?", "तपाईंले घरमा बच्चाहरूसँग दैनिक नेपाली बोल्नुहुन्छ?", "tapāīṃle gharamā baccāharūsa~ga dainika nepālī bolnuhuncha"],
        ["Can you help me carry this box to the third floor?", "यो बाकस तेस्रो तल्लासम्म बोक्न मद्दत गर्न सक्नुहुन्छ?", "yo bākasa tesro tallāsamma bokna maddata garna saknuhuncha"],
        ["Whose idea was it to start the meeting so early in the morning?", "बिहानै यति छिटो बैठक सुरु गर्ने कसको विचार थियो?", "bihānai yati chiṭo baiṭhaka suru garne kasako vicāra thiyo"],
    ],
    529: [
        ["I do not know the answer yet because I have not read the chapter.", "अध्याय नपढेकाले मलाई अझै उत्तर थाहा छैन।", "adhyāya napaḍhekāle malāī ajhai uttara thāhā chaina"],
        ["You do not understand the rule if you skip the examples.", "उदाहरण छोडेर गएमा नियम बुझ्दैनौ।", "udāharaṇa choḍera gema niyama bujhdainau"],
        ["He does not eat meat, so we always cook separate dishes for him.", "उसले मासु खादैन, त्यसैले उनका लागि छुट्टै खाना पकाउँछौं।", "usale māsu khādaina, tyasaile unakā lāgi chuṭṭai khānā pakāu~chauṃ"],
        ["She does not go out alone after dark in this neighbourhood.", "अँध्यारो भएपछि यस छिमेकीमा उनी एक्लै बाहिर जाँदैनन्।", "a~dhyāro bhaepachi yasa chimekīmā unī eklai bāhira jā~dainan"],
        ["We do not want any trouble; please talk to us calmly.", "हामी झगडा चाहँदैनौं; कृपया शान्तिसँग कुरा गर्नुहोस्।", "hāmī jhagaḍā cāha~dainauṃ; kṛpayā śāntisa~ga kurā garnuhos"],
        ["No, there is no milk left in the fridge this morning.", "छैन, बिहान फ्रिजमा दूध बाँकी छैन।", "chaina, bihāna phrijamā dudha bā~kī chaina"],
        ["I do not understand this sentence; could you read it more slowly?", "मैले यो वाक्य बुझिन; अलि ढिलो पढ्नुहुन्छ?", "maile yo vākya bujhina; ali ḍhilo paḍhnuhuncha"],
        ["I am not a teacher; I am only a volunteer at this school.", "म शिक्षक होइन; यस विद्यालयमा म स्वयंसेवक मात्र हुँ।", "ma śikṣaka hoina; yasa vidyālayamā ma svayaṃsevaka mātra hu~"],
        ["There is no problem with your form; you can submit it today.", "तपाईंको फाराममा कुनै समस्या छैन; आजै पेश गर्न सक्नुहुन्छ।", "tapāīṃko phārāmamā kunai samasyā chaina; ājai peśa garna saknuhuncha"],
        ["No worries — we can finish this small repair in half an hour.", "कुनै चिन्ता छैन — आधा घन्टामा यो सानो मर्मत सकिन्छ।", "kunai cintā chaina — ādhā ghanṭāmā yo sāno marmata sakinch"],
        ["I cannot speak Nepali fluently yet, but I practise every evening.", "म नेपाली धाराप्रवाह बोल्न सक्दिन, तर हरेक बेलुका अभ्यास गर्छु।", "ma nepālī dhārāpravāha bolna sakdina, tara hareka belukā abhyāsa gar-chu"],
        ["I do not eat beef for personal reasons, but I respect your choice.", "व्यक्तिगत कारणले म गाईको मासु खाँदिन, तर तपाईंको रोजाइको सम्मान गर्छु।", "vyaktigata kāraṇale ma gāīko māsu khā~dina, tara tapāīṃko rojāiko sammāna gar-chu"],
        ["This shirt is not expensive; it was on sale last week.", "यो कमीज महँगो छैन; गएको हप्ता छुटमा थियो।", "yo kamīja maha~go chaina; gaeko hapta chuṭamā thiyo"],
        ["No way — we cannot cross the river while the water is this high.", "कुनै उपाय छैन — पानी यति उच्च हुँदा नदी तर्न सकिँदैन।", "kunai upāya chaina — pānī yati ucca hu~dā nadī tarna saki~daina"],
        ["I do not want this old chair; please take it to the scrap shop.", "मलाई यो पुरानो कुर्सी चाहिदैन; कबाडी पसलमा लैजानुहोस्।", "malāī yo purāno kursī cāhidaina; kabāḍī pasalamā laijānuhos"],
    ],
    530: [
        ["I did not go to school yesterday because I had a high fever.", "हिजो ज्वरो आएकाले म विद्यालय गएको छैन।", "hijo jvaro āekāle ma vidyālaya gaeko chaina"],
        ["You did not come to my party even though you promised.", "तिमीले वाचा गरे पनि मेरो पार्टीमा आएनौ।", "timīle vācā gare pani mero pārṭīmā āenau"],
        ["He did not speak during the meeting because he was new.", "उ नयाँ भएकाले बैठकमा उनी बोलेनन्।", "u nayā~ bhaekāle baiṭhakamā unī bolenan"],
        ["She did not eat anything after she heard the sad news.", "दुःखद समाचार सुनेपछि उनी केही खाइनन्।", "duḥkhada samācāra sunepachi unī kehī khāinan"],
        ["We did not see the leopard; only fresh footprints were on the path.", "हामीले चितुवा देखेका छैनौं; बाटोमा मात्र नयाँ पाउको छाप थियो।", "hāmīle cituvā dekhekā chainauṃ; bāṭomā mātra nayā~ pāuko chāpa thiyo"],
        ["They did not know that the road was closed for construction.", "बाटो निर्माणका लागि बन्द भएको उनीहरुलाई थाहा भएन।", "bāṭo nirmāṇakā lāgi banda bhaeko unīharulāī thāhā bhaena"],
        ["It was not necessary to print so many copies for one class.", "एक कक्षाका लागि यति धेरै प्रतिलिपि आवश्यक थिएन।", "eka kakṣākā lāgi yati dherai pratilipi āvaśyaka thiena"],
        ["The shoes were not expensive, but they are very comfortable.", "जुत्ता महँगो थिएन, तर धेरै आरामदायी छन्।", "juttā maha~go thiena, tara dherai ārāmadāyī chan"],
        ["I did not do it on purpose; the glass slipped from my hand.", "जानाजानी गरेको होइन; गिलास हातबाट चिप्लियो।", "jānājānī gareko hoina; gilāsa hātabāṭa cipliyo"],
        ["You did not tell me that the train time had changed.", "रेलको समय परिवर्तन भएको तिमीले मलाई भनेनौ।", "relako samaya parivartana bhaeko timīle malāī bhanenau"],
        ["He did not run in the race because his ankle was swollen.", "खुट्टा सुन्निएकाले उनी दौडेनन्।", "khuṭṭā sunniekāle unī dauḍenan"],
        ["She did not cry in front of the guests; she waited until they left.", "पाहुनाको अगाडि उनी रोइनन्; जानेबेलासम्म पर्खिन्।", "pāhunāko agāḍi unī roinan; jānebelāsamma parkhin"],
        ["I could not come earlier because the bus broke down on the way.", "बस बाटोमै बिग्रेकाले म छिटो आउन सकिन।", "bas bāṭomai bigrekāle ma chiṭo āuna sakina"],
        ["There was no doubt that she would pass after working so hard.", "यति मेहनत गरेपछि उनी पास हुन्छिन् भन्नेमा शंका थिएन।", "yati mehanata garepachi unī pās hunchin bhanne-mā śaṃkā thiena"],
        ["I had not eaten since morning, so I felt dizzy on the bus.", "बिहानदेखि केही नखाएकाले बसमा मलाई चक्कर लाग्यो।", "bihānadekhi kehī nakhāekāle basamā malāī cakkara lāgyo"],
    ],
    531: [
        ["I will not go to the party if I still have a fever tomorrow.", "भोलि पनि ज्वरो रह्यो भने पार्टीमा जाने छैन।", "bholi pani jvaro rahyo bhane pārṭīmā jāne chaina"],
        ["You will not come with us if you do not finish your work.", "काम नसकाउनुभयो भने हामीसँग आउने छैनौ।", "kāma nasakāunubhayo bhane hāmīsa~ga āune chainau"],
        ["He will not eat sweets until the doctor says it is safe.", "डाक्टरले सुरक्षित भन्नुअघि उसले मिठाइ खानेछैन।", "ḍākṭarale surakṣita bhannuaghi usale miṭhāi khānechaina"],
        ["She will not do it alone; we will help her with the heavy boxes.", "उनी एक्लैले गर्ने छैनन्; भारी बाकस हामीले सहयोग गर्छौं।", "unī eklaile garne chainan; bhārī bākasa hāmīle sahayoga gar-chauṃ"],
        ["We will not forget your kindness even after many years.", "धेरै वर्षपछि पनि हामी तपाईंको मद्दत बिर्सने छैनौं।", "dherai varṣapachi pani hāmī tapāīṃko maddata birsane chainauṃ"],
        ["They will not wait forever; please hurry if you want to join.", "सधै पर्खने छैनन्; सँगै जान चाहनुहुन्छ भने छिटो गर्नुहोस्।", "sadhai parkhane chainan; saṃgai jāna cāhanuhuncha bhane chiṭo garnuhos"],
        ["I will not tell anyone your secret; you can trust me.", "तपाईंको रहस्य कसैलाई भन्ने छैन; विश्वास गर्नुहोस्।", "tapāīṃko rahasya kasailāī bhanne chaina; viśvāsa garnuhos"],
        ["You will not need a visa if you only stay for two weeks.", "दुई हप्ता मात्र बस्नुहुन्छ भने भिसा आवश्यक पर्दैन।", "duī haptā mātra basnuhuncha bhane bhisā āvaśyaka pardaina"],
        ["No, I will eat later; the soup is still too hot for me.", "होइन, म पछि खान्छु; सूप अझै धेरै तातो छ।", "hoina, ma pachi khānchu; sūpa ajhai dherai tāto cha"],
        ["I cannot come tonight because I must finish this report.", "आज रात यो प्रतिवेदन सकाउनुपर्छ, आउन सक्दिन।", "āja rāta yo prativedana sakāunuparcha, āuna sakdina"],
        ["Do not go near the edge; the rocks are loose after the rain.", "किनार नजिक नजानुहोस्; पानीपछि ढुङ्गा लुज छ।", "kināra najika najānuhos; pānīpachi ḍhu~gā luja cha"],
        ["Will you not come to see us when you visit Kathmandu next time?", "अर्को पटक काठमाडौँ आउँदा हामीलाई भेट्न आउनुहुन्न?", "arko paṭaka kāṭhamāḍaũ āu~dā hāmīlāī bheṭna āununna"],
        ["It will not rain tomorrow according to the weather forecast.", "मौसम पूर्वानुमान अनुसार भोलि पानी पर्दैन।", "mausama pūrvānumāna anusāra bholi pānī pardaina"],
        ["I will not forget you even when I move to another city.", "अर्को सहर सरे पनि म तिमीलाई भुल्ने छैन।", "arko sahara sare pani ma timīlāī bhulne chaina"],
        ["They will not agree unless we change the last paragraph.", "अन्तिम अनुच्छेद नबदलेसम्म तिनीहरू सहमत हुनेछैनन्।", "antima anuccheda na badalesamma tinīharū sahamata hunechainan"],
    ],
    532: [
        ["Our stone house stays cool even when the sun is very strong.", "घाम धेरै तातो हुँदा पनि हाम्रो ढुङ्गे घर चिसो रहन्छ।", "ghāma dherai tāto hu~dā pani hāmro ḍhu~ge ghara ciso rahancha"],
        ["Many small houses in this lane were built more than fifty years ago.", "यस गल्लीका धेरै साना घर पचास वर्षभन्दा पुराना छन्।", "yasa gallīkā dherai sānā ghara pacāsa varṣabhandā purānā chan"],
        ["That brown horse runs fast across the wide field every morning.", "उ घोडा हरेक बिहान फराकिलो मैदानमा छिटो दौडन्छ।", "u ghoḍā hareka bihāna pharākilo maidānamā chiṭo dauḍancha"],
        ["The mare waits quietly near the stable while the children bring grass.", "बच्चाहरू घाँस ल्याउँदा घोडी बार्न नजिक शान्त बस्छिन्।", "baccāharū ghā~sa lyāu~dā ghoḍī bārna najika śānta bas-chin"],
        ["The boy carries a heavy school bag up the steep hill road.", "केटाले उकालो बाटोमा भारी झोला बोकेर स्कुल जान्छ।", "keṭāle ukālo bāṭomā bhārī jholā bokera skula jān-cha"],
        ["The girl draws beautiful flowers in her notebook during art class.", "केटीले कला कक्षामा कापीमा राम्रो फूल कोर्छिन्।", "keṭīle kalā kakṣāmā kāpīmā rāmro phūla kor-chin"],
        ["Many people gathered in the square to watch the cultural programme.", "सांस्कृतिक कार्यक्रम हेर्न चोकमा धेरै मानिस जम्मा भए।", "sāṃskṛtika kāryakrama herna cokamā dherai mānisa jamā bhae"],
        ["Two people can sit comfortably on this wide bench under the tree.", "रूखमुनि यो फराकिलो बेन्चमा दुई जना आरामले बस्न सक्छन्।", "rūkhamuni yo pharākilo benacamā duī janā ārāmale basna sak-chan"],
        ["There are many books on history in the corner of the library.", "पुस्तकालयको कुनामा इतिहासका धेरै किताबहरू छन्।", "pustakālayako kunāmā itihāsakā dherai kitābaharū chan"],
        ["All the children in our street came to see the puppet show.", "हाम्रो गल्लीका सबै बच्चाहरू कठपुतली नाटक हेर्न आए।", "hāmro gallīkā sabai baccāharū kaṭhputalī nāṭaka herna āe"],
        ["That house with the red roof is bigger than it looks from the road.", "रातो छानो भएको त्यो घर बाटोबाट हेर्दाभन्दा ठूलो छ।", "rāto chāno bhaeko tyo ghara bāṭobāṭa herdābhanda ṭhūlo cha"],
        ["They have only a few books at home, but they read every day.", "घरमा थोरै किताब छ, तर उनीहरू हरेक दिन पढ्छन्।", "gharamā thorai kitāba cha, tara unīharū hareka dina paḍh-chan"],
        ["My sister is famous in our town for her sweet singing voice.", "मेरी बहिनी मिठो गीत गाउन हाम्रो बजारमा प्रसिद्ध छिन्।", "merī bahinī miṭho gīta gāuna hāmro bajāramā prasiddha chin"],
        ["The wide river looks calm today, but it rises quickly in the monsoon.", "नदी आज शान्त देखिन्छ, तर मनसुनमा छिटै बढ्छ।", "nadī āja śānta dekhincha, tara manasunamā chiṭai baḍhcha"],
        ["People say she is a beautiful woman and a very kind neighbour.", "उनी सुन्दर महिला र असल छिमेकी भन्छन्।", "unī sundara mahilā ra asala chimekī bhan-chan"],
    ],
    533: [
        ["The keys are in the drawer inside the small wooden house.", "सानो काठको घर भित्र दराजमा चाबी छन्।", "sāno kāṭhako ghara bhitra darājāmā cābī chan"],
        ["A truck is moving slowly on the dusty road toward the hills.", "ढुङ्गे बाटोमा ट्रक बिस्तारै पहाडतर्फ जाँदैछ।", "ḍhu~ge bāṭomā ṭraka bistārai pahāḍatarpa jā~daicha"],
        ["We bought fresh vegetables from the market before the rain started.", "पानी नपर्दै बजारबाट ताजा तरकारी किन्यौं।", "pānī napardai bajārabāṭa tājā tarkārī kinyauṃ"],
        ["She walks to school every day along the narrow path by the river.", "उनी हरेक दिन नदीछेउको पातलो बाटो हिँडेर विद्यालय जान्छिन्।", "unī hareka dina nadīcheuko pātalo bāṭo hiṃḍera vidyālaya jān-chin"],
        ["This boy’s bicycle is leaning against the wall near the gate.", "ढोकानजिक भित्तामा यो केटाको साइकल टेकिरहेको छ।", "ḍhokānajika bhittāmā yo keṭāko sāikala ṭekiraheko cha"],
        ["We sat with the teacher on the bench and discussed the lesson.", "हामी शिक्षकसँग बेन्चमा बसेर पाठ छलफल गर्यौं।", "hāmī śikṣakasa~ga benacamā basera pāṭha chalaphala garyauṃ"],
        ["I cannot study well without enough sleep and quiet air.", "पर्याप्त निद्रा र शान्त वातावरण बिना राम्रो पढाइ हुँदैन।", "paryāpta nidrā ra śānta vātāvaraṇa binā rāmro paḍhāi hu~daina"],
        ["We saved money for months to buy a small gift for our mother.", "आमालाई सानो उपहार किन्न महिनौंसम्म पैसा जोगायौं।", "āmālāī sāno upahāra kinna mahinausamma paisā jogāyauṃ"],
        ["Wait here until the clock strikes five; I will come back soon.", "घडीले पाँच नबजेसम्म यहीँ पर्खनुहोस्; म छिटै फर्कन्छु।", "ghaḍīle pāñca na bajesamma yahī~ parkhanuhos; ma chiṭai pharkanchu"],
        ["The cat sleeps inside the warm basket under the wooden stairs.", "काठको भर्‍याङमुनि न्यानो टोकरीमा बिरालो सुतिरहेको छ।", "kāṭhako bharyaṅamuni nyāno ṭokarīmā birālo sutiraheko cha"],
        ["I am sitting in the library because the weather outside is too hot.", "बाहिर धेरै गर्मी भएकाले पुस्तकालयमा बसेको छु।", "bāhira dherai garmī bhaekāle pustakālayamā baseko cha"],
        ["The heavy dictionary is on the table near the open window.", "खुला झ्याल नजिकको टेबलमा भारी शब्दकोश छ।", "khulā jhāla najikako ṭebalamā bhārī śabdakośa cha"],
        ["Come back from the market before the street lights turn on.", "बत्ती बल्नुअघि बजारबाट फर्कनुहोस्।", "battī balnuaghi bajārabāṭa pharkanuhos"],
        ["Go to the station with your ticket; the train leaves in ten minutes.", "टिकट बोकेर स्टेशन जानुहोस्; दश मिनेटमा रेल छुट्छ।", "ṭikaṭa bokera sṭeśana jānuhos; daśa mineṭamā rela chuṭcha"],
        ["Bring water for the young plants on the terrace every evening.", "हरेक बेलुका छानामा रहेका बिरुवालाई पानी ल्याउनुहोस्।", "hareka belukā chānāmā rahekā biruvālāī pānī lyāunuhos"],
    ],
    534: [
        ["The colour of the house wall is similar to the sand on the beach.", "घरको पर्खालको रङ समुद्रको बालुवाजस्तै देखिन्छ।", "gharako parkhālako raṅa samudrakā bāluvājastai dekhincha"],
        ["We walked from here to the temple in less than twenty minutes.", "यहाँबाट मन्दिरसम्म बिस मिनेटभन्दा कममा हिँड्यौं।", "yahā~bāṭa mandirasamma bīsa mineṭabhandā kamamā hiṃḍyauṃ"],
        ["She went with her cousin to the fair and returned before dark.", "उनी भिनाजुसँग मेलामा गइन् र अँध्यारो अघि फर्किन्।", "unī bhinājusa~ga melāmā gain ra a~dhyāro aghi pharkin"],
        ["The books are in the room where we keep the old family photos.", "पुरानो पारिवारिक फोटो राख्ने कोठामा किताबहरू छन्।", "purāno pārivārika phoṭo rākhne koṭhāmā kitābaharū chan"],
        ["The cups are on the glass table under the bright ceiling lamp.", "उज्यालो पन्खामुनि काँचको टेबलमा कपहरू छन्।", "ujyālo paṅkhāmuni kā̃cako ṭebalamā kapaharū chan"],
        ["Please pass this message to me when you see me at the office.", "कार्यालयमा भेट्दा यो सन्देश मलाई दिनुहोस्।", "kāryālayamā bheṭdā yo sandeśa malāī dinuhos"],
        ["I bought this warm shawl for you because winter is coming soon.", "जाडो नजिक भएकाले तिम्रो लागि न्यानो शाल किनेँ।", "jāḍo najika bhaekāle timro lāgi nyāno śāl kine~"],
        ["We will stay here until today’s work is completely finished.", "आजको काम पूर्ण नसकुञ्जेल यहीँ बस्छौं।", "ājako kāma pūrṇa nasakuñjela yahī~ bas-chauṃ"],
        ["The birds fly toward the east every morning at sunrise.", "सूर्य उदाउँदा चराहरू पूर्वतिर उड्छन्।", "sūrya udāu~dā carāharū pūrvatira uḍ-chan"],
        ["He paints like his grandfather, with careful lines and soft colours.", "बुबाका बुबाजस्तै सावधान रेखा र कोमल रङले कोर्छ।", "bubākā bubājastai sāvadhāna rekhā ra komala raṅale kor-cha"],
        ["I cannot imagine a day without you in our small music group.", "हाम्रो सानो संगीत समूहमा तिमी बिना दिन कल्पना गर्न सक्दिन।", "hāmro sāno saṃgīta samūhamā timī binā dina kalpanā garna sakdina"],
        ["Sit between those two chairs so everyone can hear you clearly.", "दुई कुर्सी बीचमा बस्नुहोस् सबैले सुन्न सकोस्।", "duī kursī bīcamā basnuhos sabaile sunna sakos"],
        ["We will eat lunch after morning prayers at my grandmother’s house.", "बिहानको पूजापछि हजुरआमाको घरमा दिउँसो खाना खान्छौं।", "bihānako pūjāpachi hajurāmāko gharamā diuṃso khānā khān-chauṃ"],
        ["Finish your homework before evening cartoons start on TV.", "साँझ कार्टुन सुरु नहुँदै गृहकार्य सकाउनुहोस्।", "sā~jha kāṭūna suru nahu~dai gr̥hakārya sakāunuhos"],
        ["We talked for an hour about this plan and then chose the best option.", "यस योजनाबारे एक घन्टा कुरा गरेर उत्कृष्ट विकल्प छान्यौं।", "yasa yojanābāre eka ghanṭā kurā garera utkṛṣṭa vikalpa chānyauṃ"],
    ],
    535: [
        ["The boy threw the ball hard, and it rolled across the street.", "केटाले बल जोरले हान्यो र बाटोमा गुड्यो।", "keṭāle bala jorle hānyo ra bāṭomā guḍyo"],
        ["Please give this parcel to the boy waiting near the gate.", "ढोकानजिक पर्खिरहेका केटालाई यो पार्सल दिनुहोस्।", "ḍhokānajika parkhirahāka keṭālāī yo pārsal dinuhos"],
        ["The boy’s bicycle is new, but the tyres still need more air.", "केटाको साइकल नयाँ छ, तर टायरमा अझै हावा चाहिन्छ।", "keṭāko sāikala nayā~ cha, tara ṭāyaramā ajhai hāvā cāhincha"],
        ["Walk with the children; do not let them run on the busy road.", "बच्चाहरूसँग हिँड्नुहोस्; भीडो बाटोमा दौडाउनुहोस्।", "baccāharūsa~ga hiṃḍnuhos; bhīḍo bāṭomā dauḍāunuhos"],
        ["We keep our winter clothes in the trunk inside this room.", "यस कोठा भित्र डिब्बामा जाडो लुगा राख्छौं।", "yasa koṭhā bhitra ḍibbāmā jāḍo lugā rākh-chauṃ"],
        ["A black horse is standing on the grass near the river bank.", "नदी किनार घाँसमा कालो घोडा उभिएको छ।", "nadī kināra ghā~samā kālo ghoḍā ubhieko cha"],
        ["We came home from the hills when the first snow began to fall.", "पहिलो हिउँ पर्दा पहाडबाट घर फर्क्यौं।", "pahilo hiu~ pardā pahāḍabāṭa ghara pharkyauṃ"],
        ["I am the one who wrote this letter, not my brother.", "यो पत्र मैले लेखेको हुँ, मेरो भाइले होइन।", "yo patra maile lekheko hu~, mero bhāile hoina"],
        ["Give the sweets to me; I will share them fairly with everyone.", "मिठाइ मलाई दिनुहोस्; सबैलाई न्यायसँग बाँड्छु।", "miṭhāi malāī dinuhos; sabailāī nyāyasa~ga bā~ḍ-chu"],
        ["My coat is hanging behind the door because the room is warm.", "कोठा न्यानो भएकाले मेरो कोट ढोकापछाडि झुन्डिएको छ।", "koṭhā nyāno bhaekāle mero koṭa ḍhokāpachāḍi jhuṃḍieko cha"],
        ["Walk with me to the bus stop; I do not like to stand there alone.", "बस स्टपसम्म सँगै हिँड्नुहोस्; एक्लै उभिन मन लाग्दैन।", "bas sṭapasamma saṃgai hiṃḍnuhos; eklai ubhina mana lāgdaina"],
        ["He gave me a story book yesterday for my birthday.", "हिजो जन्मदिनमा उहाँले मलाई कथा किताब दिनुभयो।", "hijo janmadinamā uhā~le malāī kathā kitāba dinubhayo"],
        ["This is my house, and the small garden in front is also ours.", "यो मेरो घर हो, अगाडिको सानो बारी पनि हाम्रै हो।", "yo mero ghara ho, agāḍiko sāno bārī pani hāmrai ho"],
        ["Sit in the front row if you want to hear every word clearly.", "हरेक शब्द स्पष्ट सुन्न अगाडि पङ्क्तिमा बस्नुहोस्।", "hareka śabda spaṣṭa sunna agāḍi paṅktimā basnuhos"],
    ],
    536: [
        ["Please come in and take off your shoes before you enter the hall.", "हल भित्र पस्नुअघि जुत्ता उतारेर आउनुहोस्।", "hal bhitra pasnuaghi juttā utārera āunuhos"],
        ["Go straight and turn left at the second crossing to reach the hospital.", "सिधै जानुहोस्, दोस्रो चोकमा बायाँ मोड्नुहोस्।", "sidhai jānuhos, dosro cokamā bāyā~ moḍnuhos"],
        ["Stop the car here; the bridge ahead is too narrow for two vehicles.", "गाडी यहाँ रोक्नुहोस्; अगाडिको पुल दुई गाडीका लागि पातलो छ।", "gāḍī yahā~ roknuhos; agāḍiko pula duī gāḍīkā lāgi pātalo cha"],
        ["Listen carefully to the safety instructions before the plane takes off.", "जहाज उड्नुअघि सुरक्षा निर्देशन ध्यानले सुन्नुहोस्।", "jahāja uḍnuaghi surakṣā nirdeśana dhyānale sunnuhos"],
        ["Please come in; the floor is wet, so walk slowly near the door.", "कृपया भित्र आउनुहोस्; भुइँ भिजेकाले ढोकानजिक ढिलो हिँड्नुहोस्।", "kṛpayā bhitra āunuhos; bhuĩ bhijekāle ḍhokānajika ḍhilo hiṃḍnuhos"],
        ["Please give me a glass of water; I have been talking for an hour.", "कृपया मलाई पानीको गिलास दिनुहोस्; एक घन्टादेखि बोलिरहेको छु।", "kṛpayā malāī pānīko gilāsa dinuhos; eka ghanṭādekhi boliraheko chu"],
        ["Please speak slowly; the microphone is not working very well today.", "कृपया बिस्तारै बोल्नुहोस्; आज माइक राम्रोसँग चल्दैन।", "kṛpayā bistārai bolnuhos; āja maika rāmrosa~ga caldaina"],
        ["Do not go near the river today; the water is rising very fast.", "आज नदी नजिक नजानुहोस्; पानी छिटो बढिरहेको छ।", "āja nadī najika najānuhos; pānī chiṭo baḍhiriheko cha"],
        ["Do not cry; we will find your lost puppy before it gets dark.", "नरोऊ; अँध्यारो नहुँदै हराएको कुकुर फेला पार्छौं।", "naroū; a~dhyāro nahu~dai harāeko kukura phelā pār-chauṃ"],
        ["Do not be angry with him; he made a mistake but he is sorry.", "रिसाउनु हुँदैन; गल्ती भयो, उसले माफी मागिसक्यो।", "risāunu hu~daina; galtī bhayo, usale māphī māgisakyo"],
        ["Let me see the photograph; perhaps I know the person in it.", "मलाई फोटो हेर्न दिनुहोस्; सायद म चिन्छु।", "malāī phoṭo herna dinuhos; sāyada ma cin-chu"],
        ["Let me say a few words before we start the official programme.", "कार्यक्रम सुरु गर्नुअघि मलाई के शब्द भन्न दिनुहोस्।", "kāryakrama suru garnuaghi malāī ke śabda bhanna dinuhos"],
        ["Help! Someone has fallen into the river — bring a rope quickly!", "मद्दत गर्नुहोस्! कोही नदीमा खसेको छ — छिटो डोरी ल्याउनुहोस्!", "maddata garnuhos! kohī nadīmā khaseko cha — chiṭo ḍorī lyāunuhos"],
        ["Call the police immediately if you see smoke behind that house!", "घरपछाडि धुवाँ देख्नुभयो भने तुरुन्त पुलिसलाई कल गर्नुहोस्!", "gharapachāḍi dhuvā~ dekhnubhayo bhane turunta pulisalāī kala garnuhos"],
        ["Leave me alone for a while; I need quiet time to finish this letter.", "अलि एक्लै छोड्नुहोस्; यो पत्र सकाउन शान्त चाहिन्छ।", "ali eklai choḍnuhos; yo patra sakāuna śānta cāhincha"],
    ],
    537: [
        ["Right now the shop is closed, so we must wait outside.", "अहिले पसल बन्द छ, बाहिर पर्खनुपर्छ।", "ahile pasala banda cha, bāhira parkhanuparcha"],
        ["Today is a public holiday, so the streets look quieter than usual.", "आज सार्वजनिक बिदा भएकाले बाटो सामान्यभन्दा शान्त छ।", "āja sārvajanika bidā bhaekāle bāṭo sāmānyabhandā śānta cha"],
        ["Tomorrow we will climb the hill if the weather stays clear.", "मौसम खुला रह्यो भने भोलि डाँडा चढ्नेछौं।", "mausama khulā rahyo bhane bholi ḍā~ḍa caḍhne-chauṃ"],
        ["Yesterday I met your uncle at the market near the temple.", "हिजो मन्दिर नजिकको बजारमा तपाईंको काकासँग भेटेँ।", "hijo mandira najikako bajāramā tapāīṃko kākāsa~ga bheṭe~"],
        ["We drink hot tea every morning while we watch the sunrise.", "हरेक बिहान सूर्य उदाउँदा तातो चिया पिउँछौं।", "hareka bihāna sūrya udāu~dā tāto ciyā piu~chauṃ"],
        ["We eat lunch together at school after the second class.", "दोस्रो कक्षापछि विद्यालयमा सँगै दिउँसो खान्छौं।", "dosro kakṣāpachi vidyālayamā saṃgai diuṃso khān-chauṃ"],
        ["In the evening we walk along the river and watch the lights.", "साँझ नदीछेउ हिँडेर बत्ती हेर्छौं।", "sā~jha nadīcheu hiṃḍera battī her-chauṃ"],
        ["At night the mountain wind becomes cold, so wear a warm jacket.", "राति पहाडको हावा चिसो हुन्छ, न्यानो ज्याकेट लगाउनुहोस्।", "rāti pahāḍako hāvā ciso huncha, nyāno jyākeṭa lagāunuhos"],
        ["This day has been long, but we still have one more meeting.", "दिन लामो भयो, तर अझै एउटा बैठक बाँकी छ।", "dina lāmo bhayo, tara ajhai euṭā baiṭhaka bā~kī cha"],
        ["We will finish the project next week if everyone works hard.", "सबैले मेहनत गरे अर्को हप्ता परियोजना सकिन्छ।", "sabaile mehanata gare arko haptā pariyojana sakinch"],
        ["This month we saved enough money to buy a new school bag.", "यस महिना नयाँ झोला किन्न पर्याप्त पैसा जोगायौं।", "yasa mahinā nayā~ jholā kinna paryāpta paisā jogāyauṃ"],
        ["Next year my younger brother will start college in Kathmandu.", "अर्को वर्ष मेरो भाइ काठमाडौँमा कलेज पढ्नेछ।", "arko varṣa mero bhāi kāṭhamāḍaũmā kaleja paḍhne-cha"],
        ["What time is it now — we might miss the last bus to Patan.", "अहिले कति बज्यो — पाटनको अन्तिम बस छुट्ला जस्तो छ।", "ahile kati bajyo — pāṭanako antima basa chuṭlā jasto cha"],
        ["Come tomorrow before nine; we will start cooking early.", "भोलि नौ बजेभन्दा अघि आउनुहोस्; छिटो खाना पकाउँछौं।", "bholi nau bajebhandā aghi āunuhos; chiṭo khānā pakāu~chauṃ"],
        ["I will come later after I help my mother clean the kitchen.", "आमालाई भान्सा सफा गर्न मद्दत गरेर म पछि आउनेछु।", "āmālāī bhānsā safā garna maddata garera ma pachi āune-chu"],
    ],
    538: [
        ["I make him eat vegetables every day because he is still growing.", "उ बढिरहेकाले म उसलाई हरेक दिन तरकारी खान लगाउँछु।", "u baḍhirihe-kāle ma usalāī hareka dina tarkārī khāna lagāu~chu"],
        ["She teaches small children to read letters in the village school.", "उनी गाउँको विद्यालयमा साना बच्चालाई अक्षर पढाउँछिन्।", "unī gāu~ko vidyālayamā sānā baccālāī akṣara paḍhāu~chin"],
        ["Get this form signed today; the office will close early on Friday.", "आजै फाराममा दस्तखत गर्नुहोस्; शुक्रबार कार्यालय छिटो बन्द हुन्छ।", "ājai phārāmamā dastakhata garnuhos; śukrabāra kāryālaya chiṭo banda huncha"],
        ["I had him write the address clearly on both sides of the envelope.", "मैले उसलाई खाम दुवैतिर ठेगाना स्पष्ट लेख्न लगाएँ।", "maile usalāī khāma duvaitira ṭhegāna spaṣṭa lekhna lagāe~"],
        ["Feed the child warm rice; the doctor said he needs more energy.", "बच्चालाई न्यानो भात खुवाउनुहोस्; डाक्टरले ऊर्जा चाहिन्छ भने।", "baccālāī nyāno bhāta khuvāunuhos; ḍākṭarale ūrjā cāhincha bhane"],
        ["He got the roof repaired before the monsoon rain started.", "मनसुनको पानी सुरु नहुँदै उसले छाना मर्मत गरायो।", "manasunako pānī suru nahu~dai usale chānā marmata garāyo"],
        ["Show me the ticket; I need to check the seat number for you.", "टिकट देखाउनुहोस्; तपाईंको सिट नम्बर जाँच गर्नु छ।", "ṭikaṭa dekhāunuhos; tapāīṃko siṭa nambara jā̃ca garnu cha"],
        ["Let me know when you arrive so I can meet you at the gate.", "आइपुग्दा जानकारी दिनुहोस्; ढोकामा भेट्छु।", "āipugdā jānkārī dinuhos; ḍhokāmā bheṭ-chu"],
        ["I will make you understand the rule step by step with examples.", "उदाहरणसँगै नियम चरणबद्ध तरिकाले बुझाउनेछु।", "udāharaṇasa~gai niyama caraṇabaddha tarikāle bujhāune-chu"],
        ["She sent him to the shop with a list and enough money.", "उसलाई सूची र पैसा दिएर पसल पठाइन्।", "usalāī sūcī ra paisā dieera pasala paṭhāin"],
        ["Heavy rain can cause rocks to fall from the steep cliff.", "भारी पानीले उच्च चट्टानबाट ढुङ्गा झर्न सक्छ।", "bhārī pānīle ucca caṭṭānanabāṭa ḍhu~gā jharna sak-cha"],
        ["Bright sunlight can cause this room to feel very hot at noon.", "दिउँसो घामले यो कोठा धेरै तातो बनाउँछ।", "diuṃso ghāmale yo koṭhā dherai tāto banāu~cha"],
        ["Offer juice to the guests first; later we will serve the main meal.", "पहिले पाहुनालाई जुस दिनुहोस्; पछि मुख्य खाना।", "pahile pāhunālāī jusa dinuhos; pachi mukhya khānā"],
        ["They had us wait in the hall while they prepared the documents.", "कागजात तयार गर्दा उनीहरूले हामीलाई हलमा पर्खाइन्।", "kāgjāt tayāra gardā unīharūle hāmīlāī halamā parkhāin"],
        ["Do not make him cry; he is already nervous about the exam.", "उसलाई नरुवाउनुहोस्; परीक्षामा उ अझै घबराएको छ।", "usalāī naruvāunuhos; parīkṣāmā u ajhai ghabarāeko cha"],
    ],
    539: [
        ["The handsome actor looked confident on stage under the bright lights.", "उज्यालो बत्तीमुनि मञ्चमा सुन्दर अभिनेता आत्मविश्वासी देखिए।", "ujyālo battīmunimañcamā sundara abhinētā ātmaviśvāsī dekhie"],
        ["The talented actress sang softly while the rain tapped on the roof.", "छानामा पानी पर्दा प्रतिभाशाली अभिनेत्री मधुर गाइन्।", "chānāmā pānī pardā pratibhāśālī abhinetrī madhura gāin"],
        ["We live in a big house with a garden where my grandmother grows herbs.", "हामी ठूलो घरमा बस्छौं जहाँ हजुरआमाले जडीबुटी लगाउनुहुन्छ।", "hāmī ṭhūlo gharamā bas-chauṃ jahā̃ hajurāmāle jaḍībuṭī lagāunuhuncha"],
        ["That big tree gives shade to travellers who rest on the village path.", "त्यो ठूलो रूख गाउँको बाटोमा आराम गर्ने यात्रीलाई छहारी दिन्छ।", "yo ṭhūlo rūkha gāu~ko bāṭomā ārāma garne yātrīlāī chahārī din-cha"],
        ["My grammar book is on the desk next to your blue notebook.", "तिम्रो नीलो कापी नजिकको टेबलमा मेरो व्याकरणको किताब छ।", "timro nīlo kāpī najikako ṭebalamā mero vyākaraṇako kitāba cha"],
        ["Our house faces east, so the kitchen is bright every morning.", "हाम्रो घर पूर्व मुख भएकाले बिहान भान्सा उज्यालो हुन्छ।", "hāmro ghara pūrva mukha bhaekāle bihāna bhānsā ujyālo huncha"],
        ["The polite boy opened the door for the elderly woman.", "विनम्र केटाले बुढी आमाको लागि ढोका खोलिदिए।", "vinamra keṭāle buḍhī āmākā lāgi ḍhokā kholidie"],
        ["The clever girl solved the puzzle before anyone else in the class.", "कक्षामा अरूभन्दा पहिले चलाख केटीले पहेली सफा गरिन्।", "kakṣāmā arūbhanda pahile calākh keṭīle pahelī safā garin"],
        ["A white horse galloped across the field while the crowd cheered.", "भीड कराउँदा सेतो घोडा मैदानमा दौडियो।", "bhīḍ karāu~dā seto ghoḍā maidānamā dauḍiyo"],
        ["The black dog wags its tail when it sees children with biscuits.", "बिस्कुट बोकेर बच्चा देख्दा कालो कुकुर पुच्छर हल्लाउँछ।", "biskuṭa bokera bacca dekh-dā kālo kukura pucchara hallāu~cha"],
        ["She is beautiful inside and out, and everyone respects her.", "उनी भित्रबाहिर सुन्दर छिन्, सबैले सम्मान गर्छन्।", "unī bhitra-bāhira sundara chin, sabaile sammāna gar-chan"],
        ["He is tall enough to reach the top shelf without a stool.", "उहाँ अग्लो हुनुहुन्छ; स्टुल बिना माथिलो ताक पुग्नुहुन्छ।", "uhā~ aglo hunuhuncha; sṭula binā māthilo tāka pugnuhuncha"],
        ["That house is big, but it needs paint and a new roof soon.", "त्यो घर ठूलो छ, तर चाँडै रङ र नयाँ छानो चाहिन्छ।", "tyo ghara ṭhūlo cha, tara cā̃ḍai raṅa ra nayā~ chāno cāhincha"],
        ["I bought a new book about Nepali folk tales at the fair.", "मेलामा नेपाली लोक कथाको नयाँ किताब किनेँ।", "melāmā nepālī loka kathāko nayā~ kitāba kine~"],
        ["The old man sits in the sun and tells stories to the village children.", "बुढा मान्छे घाममा बसेर गाउँका बच्चालाई कथा सुनाउँछन्।", "buḍhā mānche ghāmamā basera gāu~kā baccālāī kathā sunāu~chan"],
    ],
    540: [
        ["I have eaten nothing since dawn, so I feel a little weak now.", "बिहानदेखि केही नखाएकाले अहिले अलि कमजोर लाग्छ।", "bihānadekhi kehī nakhāekāle ahile ali kamajora lāgcha"],
        ["You have come at the right moment; we were just about to start.", "ठ्याक्कै समयमा आउनुभयो; सुरु गर्न लाग्दै थियौं।", "ṭhyākkai samayamā āunubhayo; suru garna lāgdai thiyauṃ"],
        ["He has gone to the bank, but he will return before lunch.", "उहाँ बैंक जानुभएको छ; दिउँसो खानाअघि फर्कनुहुन्छ।", "uhā~ baiṅk jānubhaeko cha; diuṃso khānāaghi pharkanuhuncha"],
        ["Have you finished copying the notes, or do you need five more minutes?", "नोट कापी सक्नुभयो, कि अझै पाँच मिनेट चाहिन्छ?", "noṭa kāpī saknubhayo, ki ajhai pāñca mineṭa cāhincha"],
        ["I had eaten at home, so I only ordered tea at the restaurant.", "घरमा खाइसकेकाले रेस्टुरेन्टमा चिया मात्र मगाएँ।", "gharamā khāisakekāle resṭurenṭamā ciyā mātra magāe~"],
        ["She had left before we arrived, so we missed her at the station.", "हामी आइपुग्नुअघि नै उनी गइसकेकी थिइन्।", "hāmī āipugnuaghi nai unī gaisakekī thiin"],
        ["We will have done the work by Friday if nothing unexpected happens.", "अनपेक्षित केही नभए शुक्रबारसम्म काम सकिनेछ।", "anapekṣita kehī nabhae śukrabārasamma kāma sakine-cha"],
        ["They will have arrived by night if the bus does not break down.", "बस बिग्रेन भने रातिसम्म आइपुगेका हुनेछन्।", "bas bigrena bhane rātisamma āipugekā hune-chan"],
        ["I have understood the main points after reading the chapter twice.", "अध्याय दुई पटक पढेर मुख्य बुँदा बुझेको छु।", "adhyāya duī paṭaka paḍhera mukhya bu~dā bujheko chu"],
        ["You have seen this film before, but the ending still surprises me.", "यो फिल्म अघि नै देख्नु भएको छ, तर अन्त्य अझै अचम्म लाग्छ।", "yo philm aghi nai dekhnubhaeko cha, tara antya ajhai acamma lāgcha"],
        ["After having eaten, we walked slowly along the river bank.", "खाना खाइसकेपछि नदी किनार हिँड्यौं।", "khānā khāisakepachi nadī kināra hiṃḍyauṃ"],
        ["Having come so far, we cannot turn back without reaching the top.", "यति टाढा आएपछि शिखर नपुगी फर्कन मिल्दैन।", "yati ṭāḍā āepachi śikhara napugī pharkana mildaina"],
        ["I am finished with cleaning; now you can bring the boxes inside.", "सफाइ सकिएको छ; अब बाकस भित्र ल्याउनुहोस्।", "safāi sakieko cha; aba bākasa bhitra lyāunuhos"],
        ["She has written three pages about her village for the school magazine.", "विद्यालय पत्रिकाका लागि उनले गाउँबारे तीन पृष्ठ लेखेकी छिन्।", "vidyālaya patrikākā lāgi unale gāu~bāre tīna pr̥ṣṭha lekhekī chin"],
        ["They have played in every district tournament and won many cups.", "उनीहरुले जिल्लास्तरका हरेक प्रतियोगितामा खेलेका छन् र धेरै कप जितेका छन्।", "unīharule jillāstarakā hareka pratiyogitāmā khelekā chan ra dherai kapa jitekā chan"],
    ],
    541: [
        ["I have been eating small meals every two hours on the doctor’s advice.", "डाक्टरको सल्लाहमा दुई घन्टामा अलिअलि खाइरहेको छु।", "ḍākṭarako sallāhamā duī ghanṭāmā ali-ali khāiriheko chu"],
        ["You have been going to the gym regularly, and it really shows.", "नियमित जिम जाँदै हुनुहुन्छ, फरक देखिन्छ।", "niyamita jima jā~dai hunuhuncha, pharka dekhincha"],
        ["He has been reading the same novel for weeks because it is very long.", "हप्तौंदेखि उही लामो उपन्यास पढिरहेका छन्।", "haptau~dekhi uhī lāmo upanyāsa paḍhirahekā chan"],
        ["She has been working night shifts, so she looks tired this morning.", "रातको पालो काम गरिरहेकी छिन्, बिहान थाकेकी देखिन्छिन्।", "rātako pālo kāma garirahekī chin, bihāna thākekī dekhin-chin"],
        ["We have been waiting here since eight; the bus is very late.", "आठ बजेदेखि यहीँ पर्खिरहेका छौं; बस धेरै ढिलो।", "āṭha bajedekhi yahī~ parkhirahēkā chauṃ; basa dherai ḍhilo"],
        ["They have been playing music in the street to collect money for charity.", "दानका लागि उनीहरूले गल्लीमा संगीत बजाइरहेका छन्।", "dānakā lāgi unīharūle gallīmā saṃgīta bajāirahekā chan"],
        ["I had been studying all night, so I slept through the alarm.", "रातभरि पढ्दा अलार्म बज्दा पनि सुतिरहेँ।", "rātabhari paḍhdā alārma bajdā pani sutirahe~"],
        ["You had been sleeping when I called, so I did not wake you.", "फोन गर्दा तिमी सुतिरहेका थियौ, त्यसैले नउठाएँ।", "phona gardā timī sutirahekā thiyau, tyasaile na uṭhāe~"],
        ["He had been running before the race, so his muscles were warm.", "दौडअघि तयारी गर्दा मांसपेशी न्यानो थियो।", "dauḍaghi tayārī gardā māṃsameśī nyāno thiyo"],
        ["Since morning I have been waiting for the courier with my passport.", "बिहानैदेखि राहदानी ल्याउने कुरियर पर्खिरहेको छु।", "bihānaidekhi rāhadānī lyāune kuriyar parkhirheko chu"],
        ["For two hours she has been cooking for twenty guests in our kitchen.", "दुई घन्टादेखि उनी हाम्रो भान्सामा बीस जनाको लागि खाना पकाउँदै छिन्।", "duī ghanṭādekhi unī hāmro bhānsāmā bīsa janākā lāgi khānā pakāu~dai chin"],
        ["I have been thinking about your idea, and I agree with most of it.", "तपाईंको विचारबारे सोच्दै आएको छु; धेरै सहमत छु।", "tapāīṃko vicārabāre socdai āeko cha; dherai sahamata chu"],
        ["They had been talking for hours before they finally reached a decision.", "निर्णय हुन घन्टौं कुरा गरिरहेका थिए।", "nirṇaya huna ghanṭauṃ kurā garirahekā thie"],
        ["We will have been living in this city for ten years next spring.", "अर्को वसन्तमा यस सहरमा दस वर्ष बाँचिरहेका हुनेछौं।", "arko vasanta yasa saharama dasa varṣa bā~cirahekā hune-chauṃ"],
        ["It really takes time to learn a new language if you study alone.", "एक्लै सिक्दा नयाँ भाषा सिक्न साँच्चै समय लाग्छ।", "eklai sikdā nayā~ bhāṣā sikna sā~ccai samaya lāgcha"],
    ],
    542: [
        ["No, there is no sugar left in the jar on the kitchen shelf.", "छैन, भान्साको ताकमा भएको बट्टामा चिनी बाँकी छैन।", "chaina, bhānsāko tākama bhaeko baṭṭāmā cinī bā~kī chaina"],
        ["That is not my umbrella; mine has a blue stripe on the handle.", "त्यो मेरो छाता होइन; मेरोमा ह्यान्डलमा नीलो धर्को छ।", "tyo mero chātā hoina; meromā hyāṇḍalamā nīlo dharko cha"],
        ["I do not want any more rice; my stomach is already full.", "अझै भात चाहिँदैन; पेट भरिसक्यो।", "ajhai bhāt cāhi~daina; peṭ bharisakyo"],
        ["I do not want this old phone; I am saving for a better one.", "यो पुरानो फोन चाहिँदैन; राम्रो किन्न जोगाइरहेको छु।", "yo purāno phona cāhi~daina; rāmro kinna jogāiriheko chu"],
        ["No, thank you — I have already eaten dinner at my aunt’s house.", "होइन, धन्यवाद — काकीको घरमा खाना खाइसकेको छु।", "hoina, dhanyavāda — kākīko gharamā khānā khāisakeko chu"],
        ["I do not need another blanket; this one is warm enough for me.", "अर्को कम्बल चाहिँदैन; यो न्यानो छ।", "arko kamabala cāhi~daina; yo nyāno cha"],
        ["I do not want to go out tonight; the roads are slippery in the rain.", "आज बाहिर जान मन लाग्दैन; पानीले बाटो चिप्लो छ।", "āja bāhira jāna mana lāgdaina; pānīle bāṭo ciplo cha"],
        ["He does not want to sell the land; he hopes to build a house there.", "उ जग्गा बेच्न चाहँदैन; घर बनाउन आशा छ।", "u jaggā bechna cāha~daina; ghara banāuna āśā cha"],
        ["We do not want trouble with the neighbours over a small matter.", "सानो कुरामा छिमेकीसँग झगडा चाहँदैनौं।", "sāno kurāmā chimekīsa~ga jhagaḍā cāha~dainauṃ"],
        ["I am not interested in that job because the salary is too low.", "तलब कम भएकाले त्यो जागिरमा चासो छैन।", "talaba kama bhaekāle tyo jāgiramā cāso chaina"],
        ["It is not necessary to print everything; we can read on the screen.", "सबै छाप्न आवश्यक छैन; स्क्रिनमा पढ्न सकिन्छ।", "sabai chāpna āvaśyaka chaina; skrinamā paḍhna sakinch"],
        ["No problem — we can change the date if everyone agrees.", "कुनै समस्या छैन; सबै माने मिति बदल्न सकिन्छ।", "kunai samasyā chaina; sabai māne miti badalna sakinch"],
        ["I cannot afford this coat right now, but maybe next month.", "अहिले यो कोट किन्न सक्दिन; अर्को महिना हुन सक्छ।", "ahile yo koṭa kinna sakdina; arko mahinā huna sak-cha"],
        ["You do not have to wait for me; I might be very late tonight.", "मेरो लागि पर्खनु पर्दैन; आज रात धेरै ढिलो हुन सक्छ।", "mero lāgi parkhanu pardaina; āja rāta dherai ḍhilo huna sak-cha"],
        ["I do not want this cold drink; please bring hot tea instead.", "यो चिसो पेय चाहिँदैन; तातो चिया ल्याउनुहोस्।", "yo ciso peya cāhi~daina; tāto ciyā lyāunuhos"],
    ],
}


def apply_rows(data: list) -> None:
    for lesson in data:
        lid = lesson.get("id")
        if lid not in ROWS or lid in SKIP:
            continue
        new_rows = ROWS[lid]
        for block in lesson.get("blocks") or []:
            if block.get("type") != "table":
                continue
            if block.get("headers") != ["English", "Nepali", "Transliteration"]:
                continue
            if len(block.get("rows") or []) != len(new_rows):
                raise ValueError(
                    f"Lesson {lid}: row count mismatch "
                    f"(file has {len(block.get('rows') or [])}, "
                    f"script has {len(new_rows)})"
                )
            block["rows"] = [list(r) for r in new_rows]


def main() -> None:
    data = json.loads(DATA.read_text(encoding="utf-8"))
    data = deepcopy(data)
    apply_rows(data)
    DATA.write_text(
        json.dumps(data, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print("Updated section 2.1–2.33 lessons in", DATA)


if __name__ == "__main__":
    main()
