#!/usr/bin/env python3
"""Fix repeating sentences in Telugu conversation sublessons 5.2-5.27 (chapters 826-851).
Replace with 15+ unique genuine sentences from web research."""
import json

# [English, Telugu, Transliteration] - 15+ unique sentences per chapter
SENTENCES = {
    826: [  # Sankranti Festival
        ["Happy Sankranti!", "సంక్రాంతి శుభాకాంక్షలు!", "saṃkrāṃti śubhākāṃkṣalu!"],
        ["We fly kites on Sankranti.", "మేము సంక్రాంతి నాడు గాలిపటాలు ఎగురవేస్తాము.", "mēmu saṃkrāṃti nāḍu gālipaṭālu eguravēstāmu."],
        ["Eat pongal on Sankranti.", "సంక్రాంతి నాడు పొంగల్ తినండి.", "saṃkrāṃti nāḍu poṃgal tiṇaṇḍi."],
        ["Bhogi brings prosperity, Sankranti brings joy.", "భోగి మీకు భోగభాగ్యాలను, సంక్రాంతి మీకు సుఖసంతోషాలను.", "bhōgi mīku bhōgabhāgyālanu, saṃkrāṃti mīku sukhasaṃtōṣālanu."],
        ["May your home fill with happiness this Sankranti.", "సంక్రాంతి సందర్భంగా మీ ఇల్లు సుఖసంతోషాలతో నిండిపోవాలని కోరుకుంటూ.", "saṃkrāṃti saṃdarbhaṃgā mī illu sukhasaṃtōṣālatō niṇḍipōvālanī kōrukuṇṭū."],
        ["Makar Sankranti marks the sun's northward journey.", "మకర సంక్రాంతి సూర్యుడి ఉత్తరాయణ ప్రయాణాన్ని సూచిస్తుంది.", "makara saṃkrāṃti sūryuḍi uttarāyaṇa prayāṇānni sūcistundi."],
        ["May this Sankranti bring health and prosperity.", "ఈ సంక్రాంతి మీకు ఆయురారోగ్యాలు, ఆనందం తీసుకురావాలని.", "ī saṃkrāṃti mīku āyurārōgyālu, ānandaṃ tīsukuravālanī."],
        ["We prepare haridasu for Sankranti.", "మేము సంక్రాంతి కోసం హరిదాసు తయారు చేస్తాము.", "mēmu saṃkrāṃti kōsaṃ haridāsu tayāru cēstāmu."],
        ["Sankranti is a harvest festival.", "సంక్రాంతి సంత్సవ పండుగ.", "saṃkrāṃti saṃtsava paṇḍuga."],
        ["Children wear new clothes on Sankranti.", "పిల్లలు సంక్రాంతి నాడు కొత్త బట్టలు ధరిస్తారు.", "pillalu saṃkrāṃti nāḍu kotta baṭṭalu dharistāru."],
        ["We exchange til and jaggery.", "మేము నువ్వెలు మరియు బెల్లం మార్పుకోంటాము.", "mēmu nuvvelu mariyu bellaṃ mārpukōṇṭāmu."],
        ["May Lakshmi bless you this Sankranti.", "ఈ సంక్రాంతి లక్ష్మీదేవి మీకు ఆశీర్వదించాలి.", "ī saṃkrāṃti lakṣmīdēvi mīku āśīrvadin̄cāli."],
        ["Sankranti falls in January.", "సంక్రాంతి జనవరి లో వస్తుంది.", "saṃkrāṃti janavari lō vastundi."],
        ["We decorate the house with rangoli.", "మేము ఇంటిని రంగోలితో అలంకరిస్తాము.", "mēmu iṇṭini raṃgōlitō alaṃkaristāmu."],
        ["Happy Makar Sankranti to all.", "అందరికీ మకర సంక్రాంతి శుభాకాంక్షలు.", "andarikī makara saṃkrāṃti śubhākāṃkṣalu."],
    ],
    827: [  # Introduction/Salutation
        ["My name is Ravi.", "నా పేరు రవి.", "nā pēru ravi."],
        ["What is your name?", "మీ పేరు ఏమిటి?", "mī pēru ēmiṭi?"],
        ["Nice to meet you.", "మిమ్మల్ని కలవడం సంతోషం.", "mimmalni kalavaḍaṃ saṃtōṣaṃ."],
        ["I am from Hyderabad.", "నేను హైదరాబాద్ నుండి వచ్చాను.", "nēnu haidarābād nuṇḍi vaccānu."],
        ["How are you?", "మీరు ఎలా ఉన్నారు?", "mīru elā unnāru?"],
        ["I am fine. And you?", "నేను బాగానే ఉన్నాను. మరియు మీరు?", "nēnu bāgānē unnānu. mariyu mīru?"],
        ["Pleased to meet you.", "మిమ్మల్ని కలవడం నాకు సంతోషంగా ఉంది.", "mim'malni kalavaḍaṃ nāku saṃtōṣaṃgā undi."],
        ["Where are you from?", "నువ్వు ఎక్కడ నుంచి వచ్చావు?", "nuvvu ekkada nuṇci vaccāvu?"],
        ["Do you live here?", "మీరు ఇక్కడ ఉంటున్నారా?", "mīru ikkaḍa uṇṭunnārā?"],
        ["What is your occupation?", "మీ వృత్తి ఏమిటి?", "mī vr̥tti ēmiṭi?"],
        ["I am a student.", "నేను విద్యార్థిని.", "nēnu vidyārthini."],
        ["Keep in touch!", "సన్నిహితంగా ఉండండి!", "sannihitaṃgā uṇḍaṇḍi!"],
        ["It has been great meeting you.", "మిమ్మల్ని కలవడం చాలా బాగుంది.", "mim'malni kalavaḍaṃ cālā bāgundi."],
        ["Goodbye!", "వీడ్కోలు!", "vīḍkōlu!"],
        ["See you later.", "తర్వాత కలుద్దాం.", "tarvāta kaluddāṃ."],
        ["Do you have any hobbies?", "మీకు ఎందుకు ఇష్టమైన శ్రమలు ఉన్నాయా?", "mīku enduku iṣṭamaina śramalu unnāyā?"],
    ],
    828: [  # Time Related
        ["What time is it?", "ఇప్పుడు సమయం ఎంత?", "ippuḍu samayaṃ eṃta?"],
        ["It is five o'clock.", "ఐదు గంటలయింది.", "aidu gaṇṭalayindi."],
        ["I will come tomorrow.", "నేను రేపు వస్తాను.", "nēnu rēpu vastānu."],
        ["We meet every Sunday.", "మేము ప్రతి ఆదివారం కలుసుకుంటాము.", "mēmu prati ādivāraṃ kalusukuṃtāmu."],
        ["When does the bus leave?", "బస్సు ఏ సమయానికి బయలుదేరుతుంది?", "bassu ē samayāniki bayaludērutundi?"],
        ["What time does it arrive?", "ఎంత సమయానికి వస్తుంది?", "eṃta samayāniki vastundi?"],
        ["I wake up at six.", "నేను ఆరు గంటలకు లేస్తాను.", "nēnu āru gaṇṭalaku lēstānu."],
        ["Lunch is at one.", "భోజనం ఒక గంటకు.", "bhōjanaṃ oka gaṇṭaku."],
        ["The meeting is at 10 AM.", "మీటింగ్ ఉదయం పది గంటలకు.", "mīṭiṃg udayaṃ padi gaṇṭalaku."],
        ["Today is Monday.", "ఈ రోజు సోమవారం.", "ī rōju sōmavāraṃ."],
        ["Yesterday was holiday.", "నిన్న సెలవు.", "ninna selavu."],
        ["The train is at 3 PM.", "రైలు మధ్యాహ్నం మూడు గంటలకు.", "railu madhyāhnaṃ mūḍu gaṇṭalaku."],
        ["Wait for 10 minutes.", "పది నిమిషాలు వేచి ఉండండి.", "padi nimiṣālu vēci uṇḍaṇḍi."],
        ["It is late.", "ఆలస్యమైంది.", "ālasyamaindi."],
        ["This week I am busy.", "ఈ వారం నాకు బిజీగా ఉంది.", "ī vāraṃ nāku bijīgā undi."],
        ["I will finish by noon.", "నేను మధ్యాహ్నం వరకు పూర్తి చేస్తాను.", "nēnu madhyāhnaṃ varaku pūrti cēstānu."],
    ],
    829: [  # Where/Place Related
        ["Where is this place?", "ఈ చోటు ఎక్కడ ఉంది?", "ī cōṭu ekkada undi?"],
        ["How do I get to the hospital?", "నేను ఆసుపత్రికి ఎలా వెళ్ళగలను?", "nēnu āsupatrikī elā veḷḷagalanu?"],
        ["Can we get there by bus?", "ప్రజా రవాణా ద్వారా మనం అక్కడికి చేరుకోగలమా?", "prajā ravāṇā dvārā manaṃ akkaḍikī cērukōgalamā?"],
        ["Where is the bus stop?", "బస్టాప్ ఎక్కడ ఉంది?", "basṭāp ekkada undi?"],
        ["I want to get off here.", "నేను ఇక్కడ దిగాలనుకుంటున్నాను.", "nēnu ikkaḍa digālanukuṇṭunnānu."],
        ["Where can I buy a ticket?", "నేను టిక్కెట్ ఎక్కడ కొనుగోలు చేయవచ్చు?", "nēnu ṭikkeṭ ekkada konugōlu cēyavaccu?"],
        ["The shop is near the bank.", "షాప్ బ్యాంక్ దగ్గర ఉంది.", "ṣāp byāṃk daggara undi."],
        ["Go straight and turn left.", "నేరుగా వెళ్లి ఎడమవైపు తిరగండి.", "nērugā veḷḷi eḍamavaipu tiragaṇḍi."],
        ["Is this the right way?", "ఇది సరైన దారా?", "idi saraina dārā?"],
        ["The temple is behind the market.", "గుడి మార్కెట్ వెనుక ఉంది.", "guḍi mārkeṭ venuka undi."],
        ["Where is the nearest hospital?", "సమీప ఆసుపత్రి ఎక్కడ ఉంది?", "samīpa āsupatri ekkada undi?"],
        ["I am lost.", "నేను ఓడిపోయాను.", "nēnu ōḍipōyānu."],
        ["Can you show me the way?", "నాకు దారి చూపించగలరా?", "nāku dāri cūpin̄cagalarā?"],
        ["The post office is opposite the bank.", "పోస్ట్ ఆఫీస్ బ్యాంక్ ఎదురుగా ఉంది.", "pōsṭ āphīs byāṃk edurugā undi."],
        ["How far is it from here?", "ఇక్కడ నుండి ఎంత దూరం?", "ikkaḍa nuṇḍi eṃta dūraṃ?"],
    ],
    830: [  # In Hotel
        ["Where is a hotel?", "హోటల్ ఎక్కడ ఉంది?", "hōṭal ekkada undi?"],
        ["How much is it per night?", "ఒక రాత్రికి ఎంత?", "oka rātrikī eṃta?"],
        ["Is breakfast included?", "అల్పాహారం చేర్చబడిందా?", "alpāhāraṃ cērcabaḍindā?"],
        ["I would like to book a room.", "నేను గదిని బుక్ చేయాలనుకుంటున్నాను.", "nēnu gadini buk cēyālanukuṇṭunnānu."],
        ["I have a reservation for 2 nights.", "నాకు 2 రాత్రుల పాటు రిజర్వేషన్ ఉంది.", "nāku 2 rātrula pāṭu rijarvēṣan undi."],
        ["Do you have a double room?", "మీకు డబుల్ రూమ్ ఉందా?", "mīku ḍabul rūm undā?"],
        ["Can I see the room?", "నేను గదిని చూడగలనా?", "nēnu gadini cūḍagalanā?"],
        ["When is breakfast served?", "అల్పాహారం ఎప్పుడు వడ్డిస్తారు?", "alpāhāraṃ eppuḍu vaḍḍistāru?"],
        ["I am leaving now.", "నేను ఇప్పుడు వెళ్లిపోతున్నాను.", "nēnu ippuḍu veḷḷipōtunnānu."],
        ["What time is checkout?", "చెక్అవుట్ సమయం ఎంత?", "cekavuṭ samayaṃ eṃta?"],
        ["There is no hot water.", "వేడి నీటి సౌకర్యం లేదు.", "vēḍi nīṭi saukaryaṃ lēdu."],
        ["Can you call a taxi for me?", "మీరు నా కోసం టాక్సీని పిలవగలరా?", "mīru nā kōsaṃ ṭāksīni pilavagalarā?"],
        ["The air conditioner does not work.", "ఎయిర్ కండీషనర్ పనిచేయదు.", "eyir kaṇḍīṣanar panicēyadu."],
        ["Could I have my key, please?", "దయచేసి నా కీ ఇవ్వండి.", "dayacēsi nā kī ivvaṇḍi."],
        ["Is there wireless internet?", "ఇక్కడ వైర్‌లెస్ ఇంటర్నెట్ ఉందా?", "ikkaḍa vairles iṇṭarneṭ undā?"],
    ],
    831: [  # Weather related
        ["Today is hot.", "ఈ రోజు వేడిగా ఉంది.", "ī rōju vēḍigā undi."],
        ["It is raining.", "వర్షం పడుతోంది.", "varṣaṃ paḍutōndi."],
        ["The weather is nice.", "వాతావరణం బాగుంది.", "vātāvaraṇaṃ bāgundi."],
        ["It is very cold today.", "ఈ రోజు చాలా చలిగా ఉంది.", "ī rōju cālā caligā undi."],
        ["Will it rain tomorrow?", "రేపు వర్షం పడుతుందా?", "rēpu varṣaṃ paḍutundā?"],
        ["The sun is shining.", "సూర్యుడు ప్రకాశిస్తోంది.", "sūryuḍu prakāśistōndi."],
        ["It is a cloudy day.", "ఈ రోజు మేఘావృతం.", "ī rōju mēghāvr̥taṃ."],
        ["The wind is strong.", "గాలి బలంగా ఉంది.", "gāli balaṃgā undi."],
        ["Summer is very hot here.", "ఇక్కడ వేసవి చాలా వేడిగా ఉంటుంది.", "ikkaḍa vēsavi cālā vēḍigā uṇṭundi."],
        ["Winter is cold.", "శీతాకాలం చలిగా ఉంటుంది.", "śītākālaṃ caligā uṇṭundi."],
        ["What is the temperature?", "ఉష్ణోగ్రత ఎంత?", "uṣṇōgrata eṃta?"],
        ["It is humid.", "ఆర్ద్రత ఎక్కువ.", "ārdrata ekkuva."],
        ["Nice weather for a walk.", "నడకకు మంచి వాతావరణం.", "naḍakaku maṃci vātāvaraṇaṃ."],
        ["The storm is coming.", "తుఫాను వస్తోంది.", "tuphānu vastōndi."],
        ["Bring an umbrella.", "గొడుగు తీసుకురండి.", "goḍugu tīsukuraṇḍi."],
    ],
    832: [  # Traffic police
        ["Stop the vehicle.", "వాహనం ఆపండి.", "vāhanaṃ āpaṇḍi."],
        ["Show your licence.", "మీ లైసెన్స్ చూపించండి.", "mī laisen̄s cūpin̄caṇḍi."],
        ["Here is my licence.", "ఇది నా లైసెన్స్.", "idi nā laisen̄s."],
        ["I am sorry, I forgot to bring it.", "క్షమించండి, తీసుకురావడం మరిచిపోయాను.", "kṣamin̄caṇḍi, tīsukuravaḍaṃ maricipōyānu."],
        ["You have broken the signal.", "మీరు సిగ్నల్ ఉల్లంఘించారు.", "mīru signal ullaṃghin̄cāru."],
        ["You will have to pay a fine.", "మీరు జుర్మానా చెల్లించాలి.", "mīru jurmānā cellin̄cāli."],
        ["Where should I pay?", "నేను ఎక్కడ చెల్లించాలి?", "nēnu ekkada cellin̄cāli?"],
        ["Please don't repeat this.", "దయచేసి మళ్ళీ చేయకండి.", "dayacēsi maḷḷī cēyakaṇḍi."],
        ["I was in a hurry.", "నాకు తొందరగా ఉంది.", "nāku toṃdaragā undi."],
        ["I will be careful next time.", "తదుపరి సారి జాగ్రత్తగా ఉంటాను.", "tadupari sāri jāgrattagā uṇṭānu."],
        ["Slow down the car.", "బండి కొంచెం మెల్లగా నడపండి.", "baṇḍi konceṃ mellagā naḍapaṇḍi."],
        ["Wear your helmet.", "హెల్మెట్ ధరించండి.", "helmeṭ dharin̄caṇḍi."],
        ["The documents are in my bag.", "కాగితాలు నా బ్యాగ్ లో ఉన్నాయి.", "kāgitālu nā byāg lō unnāyi."],
        ["I did not see the signal.", "నాకు సిగ్నల్ కనిపించలేదు.", "nāku signal kanipin̄calēdu."],
        ["Thank you, officer.", "ధన్యవాదాలు సర్.", "dhanyavādālu sar."],
    ],
    833: [  # Auto/Taxi driver
        ["Where do you want to go?", "మీరు ఎక్కడికి వెళ్లాలనుకుంటున్నారు?", "mīru ekkadikī veḷḷālanukuṇṭunnāru?"],
        ["I want to go to the station.", "నాకు స్టేషన్ కి వెళ్లాలి.", "nāku sṭēṣan kī veḷḷāli."],
        ["How much will you take?", "ఎంత తీసుకుంటారు?", "eṃta tīsukuṇṭāru?"],
        ["Take me by meter.", "మీటర్ తో తీసుకెళ్లండి.", "mīṭar tō tīsukeḷḷaṇḍi."],
        ["Please go slowly.", "దయచేసి మెల్లగా నడపండి.", "dayacēsi mellagā naḍapaṇḍi."],
        ["Stop here.", "ఇక్కడ ఆగండి.", "ikkaḍa āgaṇḍi."],
        ["A little ahead.", "కొంచెం ముందుకు.", "konceṃ muṇduku."],
        ["I don't have change.", "నాదగ్గర ఖచ్చితంగా లేదు.", "nādaggara khaccitaṃgā lēdu."],
        ["Keep the change.", "మిగిలినది ఉంచుకోండి.", "migilinadi uṇcukōṇḍi."],
        ["Please take me to this address.", "దయచేసి నన్ను ఈ చిరునామా కి తీసుకెళ్లండి.", "dayacēsi nannu ī cirunāmā kī tīsukeḷḷaṇḍi."],
        ["Please turn on the meter.", "దయచేసి మీటర్ ఆన్ చేయండి.", "dayacēsi mīṭar ān cēyaṇḍi."],
        ["How long will it take?", "ఎంత సమయం పడుతుంది?", "eṃta samayaṃ paḍutundi?"],
        ["Can you give me a receipt?", "నాకు రెసిప్ట్ ఇవ్వగలరా?", "nāku resipṭ ivvagalarā?"],
        ["The traffic is heavy.", "ట్రాఫిక్ ఎక్కువ.", "ṭrāphik ekkuva."],
        ["Take the shortcut.", "సమీప మార్గం తీసుకెళ్లండి.", "samīpa mārgaṃ tīsukeḷḷaṇḍi."],
    ],
    834: [  # Software Engineers
        ["Are you free now?", "మీరు ఇప్పుడు ఖాళీగా ఉన్నారా?", "mīru ippuḍu khāḷīgā unnārā?"],
        ["We have a meeting at 11.", "మాకు 11 గంటలకు మీటింగ్ ఉంది.", "māku 11 gaṇṭalaku mīṭiṃg undi."],
        ["Which project are you working on?", "మీరు ఏ ప్రాజెక్ట్ పై పని చేస్తున్నారు?", "mīru ē prājekṭ pai pani cēstunnāru?"],
        ["I am working on a mobile app.", "నేను మొబైల్ యాప్ పై పని చేస్తున్నాను.", "nēnu mobail yāp pai pani cēstunnānu."],
        ["Did you finish the task?", "మీరు టాస్క్ పూర్తి చేశారా?", "mīru ṭāsk pūrti cēśārā?"],
        ["Deadline is tomorrow.", "డెడ్‌లైన్ రేపు.", "ḍeḍlain rēpu."],
        ["Please send me the file.", "దయచేసి నాకు ఫైల్ పంపండి.", "dayacēsi nāku phail paṃpaṇḍi."],
        ["Let's have tea in the break.", "బ్రేక్ లో టీ తీసుకుందాం.", "brēk lō ṭī tīsukuṃdāṃ."],
        ["The code has a bug.", "కోడ్ లో బగ్ ఉంది.", "kōḍ lō bag undi."],
        ["I need to deploy today.", "నేను ఈ రోజు డిప్లాయ్ చేయాలి.", "nēnu ī rōju ḍiplāy cēyāli."],
        ["Can we have a call?", "మనం కాల్ చేయవచ్చా?", "manaṃ kāl cēyavaccā?"],
        ["I will share the screen.", "నేను స్క్రీన్ షేర్ చేస్తాను.", "nēnu skrīn ṣēr cēstānu."],
        ["The build failed.", "బిల్డ్ ఫెయిల్ అయింది.", "bilḍ pheyil ayindi."],
        ["I am working from home.", "నేను ఇంటి నుండి పని చేస్తున్నాను.", "nēnu iṇṭi nuṇḍi pani cēstunnānu."],
        ["Let's schedule a meeting.", "మీటింగ్ షెడ్యూల్ చేద్దాం.", "mīṭiṃg ṣeḍyūl cēddāṃ."],
    ],
    835: [  # Grocery shop
        ["Give me one kilo rice.", "నాకు ఒక కిలో బియ్యం ఇవ్వండి.", "nāku oka kilō biyyaṃ ivvaṇḍi."],
        ["Half kilo sugar.", "అర కిలో చక్కెర.", "ara kilō cakkera."],
        ["Do you have wheat flour?", "మీకు గోధుమ పిండి ఉందా?", "mīku gōdhuma piṇḍi undā?"],
        ["I want fresh vegetables.", "నాకు తాజా కూరగాయలు కావాలి.", "nāku tājā kūragāyalu kāvāli."],
        ["How much is this?", "ఇది ఎంత?", "idi eṃta?"],
        ["Reduce the price a little.", "కొంచెం ధర తగ్గించండి.", "konceṃ dhara taggin̄caṇḍi."],
        ["Anything else?", "మరేమైనా?", "marēmainā?"],
        ["No, that's all.", "లేదు, అంతే.", "lēdu, aṃtē."],
        ["Please pack it.", "దయచేసి ప్యాక్ చేయండి.", "dayacēsi pyāk cēyaṇḍi."],
        ["Give me the bill.", "నాకు బిల్ ఇవ్వండి.", "nāku bil ivvaṇḍi."],
        ["Do you have oil?", "మీకు నూనె ఉందా?", "mīku nūne undā?"],
        ["I need dal.", "నాకు పప్పు కావాలి.", "nāku pappu kāvāli."],
        ["Is this fresh?", "ఇది తాజా?", "idi tājā?"],
        ["We accept cards.", "మేము కార్డ్ లు అంగీకరిస్తాము.", "mēmu kārḍlu aṃgīkaristāmu."],
        ["Thank you.", "ధన్యవాదాలు.", "dhanyavādālu."],
    ],
    836: [  # Doctor-Patient
        ["What is your problem?", "మీకు ఏ సమస్య?", "mīku ē samasya?"],
        ["I have fever.", "నాకు జ్వరం ఉంది.", "nāku jvaraṃ undi."],
        ["Since when?", "ఎప్పటి నుండి?", "eppaṭi nuṇḍi?"],
        ["Since yesterday.", "నిన్న నుండి.", "ninna nuṇḍi."],
        ["Do you have cough or cold?", "మీకు దగ్గు లేదా జలుబు ఉందా?", "mīku daggu lēdā jalubu undā?"],
        ["Yes, I have cough.", "అవును, నాకు దగ్గు ఉంది.", "avunu, nāku daggu undi."],
        ["Take this medicine twice a day.", "ఈ మందు రోజుకు రెండుసార్లు తీసుకోండి.", "ī maṃdu rōjuku reṇḍusārlu tīsukōṇḍi."],
        ["Do not eat oily food.", "నూనె పదార్థాలు తినకండి.", "nūne padārthālu tinakaṇḍi."],
        ["Drink plenty of water.", "ఎక్కువ నీరు త్రాగండి.", "ekkuva nīru trāgaṇḍi."],
        ["Come again after three days.", "మూడు రోజుల తర్వాత మళ్ళీ రండి.", "mūḍu rōjula tarvāta maḷḷī raṇḍi."],
        ["Where does it hurt?", "మీకు ఎక్కడ నొప్పి ఉంది?", "mīku ekkada noppi undi?"],
        ["I have a headache.", "నాకు తల నొప్పి ఉంది.", "nāku tala noppi undi."],
        ["I have been vomiting.", "నాకు వాంతులు అవుతున్నాయి.", "nāku vāṃtulu avutunnāyi."],
        ["I am allergic to penicillin.", "నాకు పెనీసిలిన్ అలెర్జీ ఉంది.", "nāku penīsilin alerjī undi."],
        ["I need a prescription.", "నాకు ప్రిస్క్రిప్షన్ కావాలి.", "nāku priskripṣan kāvāli."],
    ],
    837: [  # Teacher & Students
        ["Open your books.", "మీ పుస్తకాలు తెరవండి.", "mī pustakālu teravaṇḍi."],
        ["Read this paragraph.", "ఈ పేరా చదవండి.", "ī pērā cadavaṇḍi."],
        ["Listen carefully.", "జాగ్రత్తగా వినండి.", "jāgrattagā vinaṇḍi."],
        ["Do you understand?", "మీకు అర్థమైందా?", "mīku arthamaindā?"],
        ["Yes, madam.", "అవును మేడమ్.", "avunu mēḍam."],
        ["No, please explain again.", "లేదు, మళ్ళీ వివరించండి.", "lēdu, maḷḷī vivarin̄caṇḍi."],
        ["Complete your homework.", "మీ హోంవర్క్ పూర్తి చేయండి.", "mī hōṃvark pūrti cēyaṇḍi."],
        ["Come to the board.", "బోర్డ్ కి రండి.", "bōrḍ kī raṇḍi."],
        ["Sit down.", "కూర్చోండి.", "kūrcōṇḍi."],
        ["Thank you, teacher.", "ధన్యవాదాలు సర్.", "dhanyavādālu sar."],
        ["May I go to the bathroom?", "నేను బాత్రూమ్ కి వెళ్లవచ్చా?", "nēnu bātrūm kī veḷḷavaccā?"],
        ["I have a doubt.", "నాకు సందేహం ఉంది.", "nāku saṃdēhaṃ undi."],
        ["Please repeat.", "మళ్ళీ చెప్పండి.", "maḷḷī ceppaṇḍi."],
        ["Write this in your notebook.", "ఇది మీ నోట్ బుక్ లో రాయండి.", "idi mī nōṭ buk lō rāyaṇḍi."],
        ["Good job!", "బాగా చేశారు!", "bāgā cēśāru!"],
    ],
    838: [  # Informal phone conversation
        ["Hello, who is speaking?", "హలో, ఎవరు మాట్లాడుతున్నారు?", "halō, evaru māṭlāḍutunnāru?"],
        ["It is me, Raj.", "నేను రాజ్.", "nēnu rāj."],
        ["Where are you?", "మీరు ఎక్కడ ఉన్నారు?", "mīru ekkada unnāru?"],
        ["I am at home.", "నేను ఇంట్లో ఉన్నాను.", "nēnu iṇṭlō unnānu."],
        ["Are you free this evening?", "మీరు ఈ సాయంత్రం ఖాళీగా ఉన్నారా?", "mīru ī sāyantraṃ khāḷīgā unnārā?"],
        ["Yes, what is the plan?", "అవును, ప్లాన్ ఏమిటి?", "avunu, plān ēmiṭi?"],
        ["Shall we go for a movie?", "మనం సినిమా కి వెళ్ళదాం?", "manaṃ sinimā kī veḷḷadāṃ?"],
        ["Okay, at what time?", "ఓకే, ఎన్ని గంటలకు?", "ōkē, enni gaṇṭalaku?"],
        ["I will call you before I leave.", "నేను వెళ్లే ముందు మీకు కాల్ చేస్తాను.", "nēnu veḷḷē muṇdu mīku kāl cēstānu."],
        ["Bye, see you.", "బై, కలుద్దాం.", "bai, kaluddāṃ."],
        ["Can you hear me?", "మీకు నా వచనం వినిపిస్తోందా?", "mīku nā vacanaṃ vinipistōndā?"],
        ["The line is bad.", "లైన్ బాగా లేదు.", "lain bāgā lēdu."],
        ["I will call you back.", "నేను మళ్ళీ కాల్ చేస్తాను.", "nēnu maḷḷī kāl cēstānu."],
        ["Sorry, I am busy.", "క్షమించండి, నాకు బిజీగా ఉంది.", "kṣamin̄caṇḍi, nāku bijīgā undi."],
        ["Talk to you later.", "తర్వాత మాట్లాడుతాను.", "tarvāta māṭlāḍutānu."],
    ],
    839: [  # Vegetable Market
        ["Give me fresh tomatoes.", "నాకు తాజా టమాటాలు ఇవ్వండి.", "nāku tājā ṭamāṭālu ivvaṇḍi."],
        ["What is the price of potatoes?", "బంగాళాదుంప ఎంత?", "baṃgāḷāduṃpa eṃta?"],
        ["Forty rupees a kilo.", "కిలోకి నలభై రూపాయలు.", "kilōki nalabhai rūpāyalu."],
        ["It is very costly.", "చాలా ఖరీదు.", "cālā kharīdu."],
        ["Reduce a little.", "కొంచెం తగ్గించండి.", "konceṃ taggin̄caṇḍi."],
        ["Give me half kilo onions.", "నాకు అర కిలో ఉల్లిపాయలు ఇవ్వండి.", "nāku ara kilō ullipāyalu ivvaṇḍi."],
        ["Anything else?", "మరేమైనా?", "marēmainā?"],
        ["No, enough for today.", "లేదు, ఈ రోజుకు సరిపోతుంది.", "lēdu, ī rōjuku saripōtundi."],
        ["Pack everything together.", "అన్నీ కలిపి ప్యాక్ చేయండి.", "annī kalipi pyāk cēyaṇḍi."],
        ["Are the vegetables fresh?", "కూరగాయలు తాజా?", "kūragāyalu tājā?"],
        ["Give me two kilos of brinjal.", "నాకు రెండు కిలోల వంకాయ ఇవ్వండి.", "nāku reṇḍu kilōla vaṃkāya ivvaṇḍi."],
        ["How much for the spinach?", "పాలకూర ఎంత?", "pālakūra eṃta?"],
        ["I need coriander.", "నాకు కొత్తిమర్ర ఉంది.", "nāku kottimarra undi."],
        ["Do you have bitter gourd?", "మీకు కాకరకాయ ఉందా?", "mīku kākarakāya undā?"],
        ["Give me the bill.", "నాకు బిల్ ఇవ్వండి.", "nāku bil ivvaṇḍi."],
    ],
    840: [  # Bus stop and in bus
        ["Where does this bus go?", "ఈ బస్సు ఎక్కడికి వెళ్తుంది?", "ī bassu ekkadikī veḷtundi?"],
        ["Does this bus go to Secunderabad?", "ఈ బస్సు సికింద్రాబాద్ కి వెళ్తుందా?", "ī bassu sikiṃdrābād kī veḷtundā?"],
        ["When will the bus come?", "బస్సు ఎప్పుడు వస్తుంది?", "bassu eppuḍu vastundi?"],
        ["It will come in ten minutes.", "పది నిమిషాలలో వస్తుంది.", "padi nimiṣālalō vastundi."],
        ["Please give me one ticket.", "ఒక టికెట్ ఇవ్వండి.", "oka ṭikeṭ ivvaṇḍi."],
        ["Is this seat free?", "ఈ సీటు ఖాళీ?", "ī sīṭu khāḷī?"],
        ["Yes, please sit.", "అవును, కూర్చోండి.", "avunu, kūrcōṇḍi."],
        ["When will we reach?", "మనం ఎప్పుడు చేరుకుంటాము?", "manaṃ eppuḍu cērukuṇṭāmu?"],
        ["What is the next stop?", "తదుపరి స్టాప్ ఏమిటి?", "tadupari sṭāp ēmiṭi?"],
        ["I want to get off at the next stop.", "నేను తదుపరి స్టాప్ లో దిగాలనుకుంటున్నాను.", "nēnu tadupari sṭāp lō digālanukuṇṭunnānu."],
        ["Which bus goes to the station?", "ఏ బస్సు స్టేషన్ కి వెళ్తుంది?", "ē bassu sṭēṣan kī veḷtundi?"],
        ["How much is the ticket?", "టికెట్ ఎంత?", "ṭikeṭ eṃta?"],
        ["The bus is crowded.", "బస్సు నిండి ఉంది.", "bassu niṇḍi undi."],
        ["Please move inside.", "లోపలికి వెళ్లండి.", "lōpalikī veḷḷaṇḍi."],
        ["Stop the bus.", "బస్సు ఆపండి.", "bassu āpaṇḍi."],
    ],
    841: [  # Asking address
        ["Where do you live?", "మీరు ఎక్కడ ఉంటున్నారు?", "mīru ekkada uṇṭunnāru?"],
        ["What is your address?", "మీ చిరునామా ఏమిటి?", "mī cirunāmā ēmiṭi?"],
        ["Can you give me your address?", "మీ చిరునామా ఇవ్వగలరా?", "mī cirunāmā ivvagalarā?"],
        ["How do I get there?", "నేను అక్కడికి ఎలా వెళ్ళగలను?", "nēnu akkaḍikī elā veḷḷagalanu?"],
        ["Which street is it on?", "ఏ వీధిలో ఉంది?", "ē vīdhilō undi?"],
        ["Is it near the temple?", "గుడి దగ్గర ఉందా?", "guḍi daggara undā?"],
        ["What is the landmark?", "ల్యాండ్ మార్క్ ఏమిటి?", "lyāṇḍ mārk ēmiṭi?"],
        ["Go straight and turn left.", "నేరుగా వెళ్లి ఎడమవైపు తిరగండి.", "nērugā veḷḷi eḍamavaipu tiragaṇḍi."],
        ["It is opposite the bank.", "బ్యాంక్ ఎదురుగా ఉంది.", "byāṃk edurugā undi."],
        ["The house is near the park.", "ఇల్లు పార్క్ దగ్గర ఉంది.", "illu pārk daggara undi."],
        ["What is the pin code?", "పిన్ కోడ్ ఏమిటి?", "pin kōḍ ēmiṭi?"],
        ["Which floor?", "ఏ అంతస్తు?", "ē aṃtastu?"],
        ["It is on the second floor.", "రెండవ అంతస్తులో ఉంది.", "reṇḍava aṃtastulō undi."],
        ["Can you show me on the map?", "మ్యాప్ లో చూపించగలరా?", "myāp lō cūpin̄cagalarā?"],
        ["Thank you for the directions.", "దారి చూపించినందుకు ధన్యవాదాలు.", "dāri cūpin̄cinanduku dhanyavādālu."],
    ],
    842: [  # I Love you - Proposing
        ["I love you.", "నేను నిన్ను ప్రేమిస్తున్నాను.", "nēnu ninnu prēmistunnānu."],
        ["I love you so much.", "నేను నిన్ను చాలా ప్రేమిస్తున్నాను.", "nēnu ninnu cālā prēmistunnānu."],
        ["I like you.", "నేను నిన్ను ఇష్టపడుతున్నాను.", "nēnu ninnu iṣṭapaḍutunnānu."],
        ["Will you marry me?", "నువ్వు నన్ను పెళ్లి చేసుకుంటావా?", "nuvvu nannu peḷḷi cēsukuṇṭāvā?"],
        ["I miss you.", "నువ్వు లేని టపా తెలుస్తోంది.", "nuvvu lēni ṭapā telustōndi."],
        ["You are beautiful.", "నువ్వు అందంగా ఉన్నావు.", "nuvvu andaṃgā unnāvu."],
        ["I want to spend my life with you.", "నేను నా జీవితం నీతో గడపాలనుకుంటున్నాను.", "nēnu nā jīvitaṃ nītō gaḍapālanukuṇṭunnānu."],
        ["You mean everything to me.", "నా కోసం నువ్వే అంతా.", "nā kōsaṃ nuvvē aṃtā."],
        ["I cannot live without you.", "నువ్వు లేకుండా నేను బ్రతకలేను.", "nuvvu lēkuṇḍā nēnu bratakalēnu."],
        ["I have loved you for a long time.", "నేను నిన్ను చాలా కాలంగా ప్రేమిస్తున్నాను.", "nēnu ninnu cālā kālaṃgā prēmistunnānu."],
        ["Be mine.", "నాదగ్గర ఉండు.", "nādaggara uṇḍu."],
        ["You are my heart.", "నువ్వు నా హృదయం.", "nuvvu nā hr̥dayaṃ."],
        ["I am always yours.", "నేను ఎప్పుడూ నీది.", "nēnu eppuḍū nīdi."],
        ["Say yes.", "అవును అనండి.", "avunu anaṇḍi."],
        ["I will always love you.", "నేను ఎప్పుడూ నిన్ను ప్రేమిస్తాను.", "nēnu eppuḍū ninnu prēmistānu."],
    ],
    843: [  # Interview
        ["Tell me about yourself.", "మీ గురించి చెప్పండి.", "mī gurin̄ci ceppaṇḍi."],
        ["What are your strengths?", "మీ బలాలు ఏమిటి?", "mī balālu ēmiṭi?"],
        ["Why do you want this job?", "ఎందుకు ఈ ఉద్యోగం కావాలి?", "enduku ī udyōgaṃ kāvāli?"],
        ["What is your experience?", "మీ అనుభవం ఏమిటి?", "mī anubhavaṃ ēmiṭi?"],
        ["When can you join?", "మీరు ఎప్పుడు జాయిన్ అవుతారు?", "mīru eppuḍu jāyin avutāru?"],
        ["What are your salary expectations?", "మీ జీతంగా ఆశయాలు ఏమిటి?", "mī jītaṃgā āśayālu ēmiṭi?"],
        ["Why did you leave your last job?", "ఎందుకు గత ఉద్యోగం వదిలిపెట్టారు?", "enduku gata udyōgaṃ vadilipaṭṭāru?"],
        ["Where do you see yourself in five years?", "ఐదు సంవత్సరాలలో మిమ్మల్ని ఎక్కడ చూస్తారు?", "aidu saṃvatsarālalō mim'malni ekkada cūstāru?"],
        ["Do you have any questions?", "మీకు ఏమైనా ప్రశ్నలు ఉన్నాయా?", "mīku ēmainā praśnalu unnāyā?"],
        ["Thank you for the opportunity.", "అవకాశం ఇచ్చినందుకు ధన్యవాదాలు.", "avakāśaṃ iccinanduku dhanyavādālu."],
        ["I am a quick learner.", "నేను త్వరగా నేర్చుకుంటాను.", "nēnu tvaragā nērcukuṇṭānu."],
        ["I work well in a team.", "నేను టీమ్ లో బాగా పని చేస్తాను.", "nēnu ṭīm lō bāgā pani cēstānu."],
        ["I am available immediately.", "నేను వెంటనే అందుబాటులో ఉన్నాను.", "nēnu veṇṭanē aṃdubāṭulō unnānu."],
        ["I have three years of experience.", "నాకు మూడు సంవత్సరాల అనుభవం ఉంది.", "nāku mūḍu saṃvatsarāla anubhavaṃ undi."],
        ["I look forward to hearing from you.", "మీకు సమాధానం ఎదురుచూస్తున్నాను.", "mīku samādhānaṃ edurucūstunnānu."],
    ],
    844: [  # Housemaid
        ["Please clean the house.", "దయచేసి ఇంటిని శుభ్రం చేయండి.", "dayacēsi iṇṭini śubhraṃ cēyaṇḍi."],
        ["Wash the clothes.", "బట్టలు ఉతుక్కోండి.", "baṭṭalu utukkōṇḍi."],
        ["Cook lunch by 1 PM.", "మధ్యాహ్నం ఒక గంటకు భోజనం చేయండి.", "madhyāhnaṃ oka gaṇṭaku bhōjanaṃ cēyaṇḍi."],
        ["Sweep the floor.", "అంతస్తు ఊడ్చండి.", "aṃtastu ūḍcaṇḍi."],
        ["Do you need anything?", "మీకు ఏమైనా కావాలా?", "mīku ēmainā kāvālā?"],
        ["Take a break.", "విశ్రాంతి తీసుకోండి.", "viśrāṃti tīsukōṇḍi."],
        ["Tomorrow is your holiday.", "రేపు మీ సెలవు.", "rēpu mī selavu."],
        ["Please come early tomorrow.", "రేపు తొందరగా రండి.", "rēpu toṃdaragā raṇḍi."],
        ["The water is in the kitchen.", "నీరు వంటిల్లో ఉంది.", "nīru vaṇṭillō undi."],
        ["Buy vegetables from the market.", "మార్కెట్ నుండి కూరగాయలు కొనండి.", "mārkeṭ nuṇḍi kūragāyalu konaṇḍi."],
        ["Iron the clothes.", "బట్టలు ఉతుక్కోండి.", "baṭṭalu utukkōṇḍi."],
        ["Take care of the child.", "పిల్లల కథలు చూసుకోండి.", "pillala kathalu cūsukōṇḍi."],
        ["I will pay you on the first.", "నేను మొదటి తేదీని చెల్లిస్తాను.", "nēnu modaṭi tēdīni cellistānu."],
        ["Do not use the phone during work.", "పని సమయంలో ఫోన్ ఉపయోగించకండి.", "pani samayaṃlō phōn upayōgin̄cakaṇḍi."],
        ["Thank you for your help.", "సహాయం చేసినందుకు ధన్యవాదాలు.", "sahāyaṃ cēsinanduku dhanyavādālu."],
    ],
    845: [  # In Bank
        ["I want to open an account.", "నాకు అకౌంట్ తెరవాలి.", "nāku akauṇṭ teravāli."],
        ["What documents do I need?", "నాకు ఏ కాగితాలు కావాలి?", "nāku ē kāgitālu kāvāli?"],
        ["I want to deposit money.", "నాకు డబ్బు జమ చేయాలి.", "nāku ḍabbu jama cēyāli."],
        ["I want to withdraw cash.", "నాకు నగదు ఎత్తుకోవాలి.", "nāku nagadu ettukōvāli."],
        ["What is the interest rate?", "వడ్డి రేటు ఎంత?", "vaḍḍi rēṭu eṃta?"],
        ["I need a cheque book.", "నాకు చెక్ బుక్ కావాలి.", "nāku cek buk kāvāli."],
        ["Can I get a debit card?", "నాకు డెబిట్ కార్డ్ లభిస్తుందా?", "nāku ḍebiṭ kārḍ labhistundā?"],
        ["I want to transfer money.", "నాకు డబ్బు ట్రాన్స్ఫర్ చేయాలి.", "nāku ḍabbu ṭrānsphar cēyāli."],
        ["What is my balance?", "నా బ్యాలెన్స్ ఏమిటి?", "nā byālens ēmiṭi?"],
        ["I forgot my PIN.", "నా పిన్ మరిచిపోయాను.", "nā pin maricipōyānu."],
        ["I want to close my account.", "నా అకౌంట్ మూసివేయాలనుకుంటున్నాను.", "nā akauṇṭ mūsivēyālanukuṇṭunnānu."],
        ["Do you accept credit cards?", "మీరు క్రెడిట్ కార్డ్ తీసుకుంటారా?", "mīru kreḍiṭ kārḍ tīsukuṇṭārā?"],
        ["Please give me a receipt.", "నాకు రెసిప్ట్ ఇవ్వండి.", "nāku resipṭ ivvaṇḍi."],
        ["Where is the ATM?", "ఏటీఎమ్ ఎక్కడ ఉంది?", "ēṭīem ekkada undi?"],
        ["I need a loan.", "నాకు లోన్ కావాలి.", "nāku lōn kāvāli."],
    ],
    846: [  # Temple Visit
        ["I want to visit the temple.", "నాకు గుడి సందర్శించాలి.", "nāku guḍi saṃdarśin̄cāli."],
        ["What are the temple timings?", "గుడి సమయం ఏమిటి?", "guḍi samayaṃ ēmiṭi?"],
        ["Is the temple open today?", "ఈ రోజు గుడి తెరిచి ఉందా?", "ī rōju guḍi terici undā?"],
        ["Where is the main temple?", "ప్రధాన గుడి ఎక్కడ ఉంది?", "pradhāna guḍi ekkada undi?"],
        ["I need a darshan ticket.", "నాకు దర్శనం టికెట్ కావాలి.", "nāku darśanaṃ ṭikeṭ kāvāli."],
        ["What is the dress code?", "డ్రెస్ కోడ్ ఏమిటి?", "ḍres kōḍ ēmiṭi?"],
        ["Where can I leave my shoes?", "నా చెప్పులు ఎక్కడ ఉంచవచ్చు?", "nā ceppulu ekkada uṇcavaccu?"],
        ["Is photography allowed?", "ఫోటోగ్రఫీ అనుమతించబడుతుందా?", "phōṭōgraphī anumatin̄cabaḍutundā?"],
        ["When is the next darshan?", "తదుపరి దర్శనం ఎప్పుడు?", "tadupari darśanaṃ eppuḍu?"],
        ["I want to offer prasadam.", "నాకు ప్రసాదం అర్పించాలి.", "nāku prasādaṃ arpin̄cāli."],
        ["Where is the parking?", "పార్కింగ్ ఎక్కడ ఉంది?", "pārkiṃg ekkada undi?"],
        ["Are there lockers?", "లాకర్లు ఉన్నాయా?", "lākarlu unnāyā?"],
        ["How long is the queue?", "క్యూ ఎంత పొడవు?", "kyū eṃta poḍavu?"],
        ["I want to do abhishekam.", "నాకు అభిషేకం చేయాలి.", "nāku abhiṣēkaṃ cēyāli."],
        ["Thank you for the information.", "సమాచారం ఇచ్చినందుకు ధన్యవాదాలు.", "samācāraṃ iccinanduku dhanyavādālu."],
    ],
    847: [  # Friend's parents at lunch table
        ["The food is delicious.", "ఆహారం రుచిగా ఉంది.", "āhāraṃ rucigā undi."],
        ["You cook very well.", "మీరు చాలా బాగా వంట చేస్తారు.", "mīru cālā bāgā vaṇṭa cēstāru."],
        ["May I have some more?", "నాకు కొంచెం ఇంకా ఇవ్వండి.", "nāku konceṃ iṃkā ivvaṇḍi."],
        ["I am full, thank you.", "నాకు సరిపోయింది, ధన్యవాదాలు.", "nāku saripōyindi, dhanyavādālu."],
        ["What is this dish called?", "ఈ వంటకానికి ఏమంటారు?", "ī vaṇṭakāniki ēmaṇṭāru?"],
        ["It is a traditional recipe.", "ఇది సంప్రదాయ వంటకం.", "idi saṃpradāya vaṇṭakaṃ."],
        ["Please help yourself.", "స్వయంగా తీసుకోండి.", "svayaṃgā tīsukōṇḍi."],
        ["I will have a little.", "నాకు కొంచెం సరిపోతుంది.", "nāku konceṃ saripōtundi."],
        ["Your hospitality is wonderful.", "మీ ఆతిధ్యం అద్భుతం.", "mī ātidhyaṃ adbhutaṃ."],
        ["I have never tasted this before.", "ఇది నేను ఇంతకు ముందు రుచి చూడలేదు.", "idi nēnu iṃtaku muṇdu ruci cūḍalēdu."],
        ["What are the ingredients?", "ఏ పదార్థాలు వేశారు?", "ē padārthālu vēśāru?"],
        ["The curry is perfect.", "కూర పరిపూర్ణంగా ఉంది.", "kūra paripūrṇaṃgā undi."],
        ["I have had enough.", "నాకు సరిపోయింది.", "nāku saripōyindi."],
        ["Thank you for the meal.", "భోజనం ఇచ్చినందుకు ధన్యవాదాలు.", "bhōjanaṃ iccinanduku dhanyavādālu."],
        ["I enjoyed the food.", "ఆహారం ఆస్వాదించాను.", "āhāraṃ āsvādin̄cānu."],
    ],
    848: [  # Friends talking about food
        ["What did you have for lunch?", "మీరు భోజనానికి ఏమి తిన్నారు?", "mīru bhōjanāniki ēmi tinnāru?"],
        ["I had biryani.", "నేను బిర్యానీ తిన్నాను.", "nēnu biryānī tinnānu."],
        ["Let's go for dinner.", "మనం భోజనానికి వెళ్ళదాం.", "manaṃ bhōjanāniki veḷḷadāṃ."],
        ["Which restaurant do you prefer?", "మీకు ఏ రెస్టారెంట్ ఇష్టం?", "mīku ē resṭārenṭ iṣṭaṃ?"],
        ["The food was too spicy.", "ఆహారం చాలా మసాలా.", "āhāraṃ cālā masālā."],
        ["I am vegetarian.", "నేను శాకాహారి.", "nēnu śākāhāri."],
        ["Do you like Telugu food?", "మీకు తెలుగు భోజనం ఇష్టమా?", "mīku telugu bhōjanaṃ iṣṭamā?"],
        ["I love dosa.", "నాకు దోస ఇష్టం.", "nāku dōsa iṣṭaṃ."],
        ["Let's order something.", "ఏదైనా ఆర్డర్ చేద్దాం.", "ēdainā ārḍar cēddāṃ."],
        ["I am hungry.", "నాకు ఆకలిగా ఉంది.", "nāku ākaligā undi."],
        ["The service was slow.", "సర్వీస్ నెమ్మదిగా ఉంది.", "sarvīs nemmadigā undi."],
        ["Shall we split the bill?", "బిల్ భాగించుకుందాం?", "bil bhāgin̄cukuṃdāṃ?"],
        ["I will pay.", "నేను చెల్లిస్తాను.", "nēnu cellistānu."],
        ["Next time we will try that place.", "తదుపరి సారి ఆ చోటు ట్రై చేద్దాం.", "tadupari sāri ā cōṭu ṭrai cēddāṃ."],
        ["The dessert was amazing.", "డెజర్ట్ అద్భుతంగా ఉంది.", "ḍejarṭ adbhutaṃgā undi."],
    ],
    849: [  # Miscellaneous 1
        ["What is this?", "ఇది ఏమిటి?", "idi ēmiṭi?"],
        ["Where is it?", "అది ఎక్కడ ఉంది?", "adi ekkada undi?"],
        ["When will you come?", "మీరు ఎప్పుడు వస్తారు?", "mīru eppuḍu vastāru?"],
        ["Why did you do that?", "ఎందుకు అలా చేశారు?", "enduku alā cēśāru?"],
        ["How are you?", "మీరు ఎలా ఉన్నారు?", "mīru elā unnāru?"],
        ["Who is that?", "అతను ఎవరు?", "atanu evaru?"],
        ["Which one?", "ఏది?", "ēdi?"],
        ["No problem.", "సమస్య లేదు.", "samasya lēdu."],
        ["It's okay.", "సరే.", "sarē."],
        ["Of course.", "ఖచ్చితంగా.", "khaccitaṃgā."],
        ["Maybe.", "బహుశా.", "bahuśā."],
        ["I think so.", "నేను అలా అనుకుంటున్నాను.", "nēnu alā anukuṇṭunnānu."],
        ["I don't understand.", "నాకు అర్థం కాదు.", "nāku arthaṃ kādu."],
        ["Repeat please.", "మళ్ళీ చెప్పండి దయచేసి.", "maḷḷī ceppaṇḍi dayacēsi."],
        ["Speak in Telugu.", "తెలుగులో మాట్లాడండి.", "telugulō māṭlāḍaṇḍi."],
    ],
    850: [  # Miscellaneous 2
        ["I agree.", "నేను అంగీకరిస్తున్నాను.", "nēnu aṃgīkaristunnānu."],
        ["I disagree.", "నేను అంగీకరించను.", "nēnu aṃgīkarin̄canu."],
        ["That is correct.", "అది సరైనది.", "adi sarainadi."],
        ["That is wrong.", "అది తప్పు.", "adi tappu."],
        ["I am not sure.", "నాకు ఖచ్చితంగా తెలియదు.", "nāku khaccitaṃgā teliyadu."],
        ["Let me think.", "నాకు ఆలోచించండి.", "nāku ālōcin̄caṇḍi."],
        ["Wait a moment.", "ఒక్కటి వేచి ఉండండి.", "okkaṭi vēci uṇḍaṇḍi."],
        ["Hurry up.", "తొందరగా చేయండి.", "toṃdaragā cēyaṇḍi."],
        ["Take your time.", "మీ సమయం తీసుకోండి.", "mī samayaṃ tīsukōṇḍi."],
        ["I am sorry.", "క్షమించండి.", "kṣamin̄caṇḍi."],
        ["Never mind.", "పర్వాలేదు.", "parvālēdu."],
        ["Good idea.", "మంచి ఆలోచన.", "maṃci ālōcana."],
        ["Bad idea.", "చెడ్డ ఆలోచన.", "ceḍḍa ālōcana."],
        ["I have no idea.", "నాకు కల్పన లేదు.", "nāku kalpana lēdu."],
        ["What do you mean?", "మీరు ఏమి అర్థం?", "mīru ēmi arthaṃ?"],
    ],
    851: [  # Quarrel at home
        ["Why are you shouting?", "ఎందుకు అరుస్తున్నావు?", "enduku arustunnāvu?"],
        ["I am sorry.", "క్షమించండి.", "kṣamin̄caṇḍi."],
        ["Let us not fight.", "మనం పోరాడకూడదు.", "manaṃ pōrāḍakūḍadu."],
        ["Calm down.", "శాంతంగా ఉండండి.", "śāntaṃgā uṇḍaṇḍi."],
        ["We need to talk.", "మనం మాట్లాడాలి.", "manaṃ māṭlāḍāli."],
        ["This is not right.", "ఇది సరైనది కాదు.", "idi sarainadi kādu."],
        ["I did not mean that.", "నేను అలా అనుకోలేదు.", "nēnu alā anukōlēdu."],
        ["Please listen to me.", "దయచేసి నా మాట వినండి.", "dayacēsi nā māṭa vinaṇḍi."],
        ["You are wrong.", "మీరు తప్పు.", "mīru tappu."],
        ["I am right.", "నేను సరైనవాడిని.", "nēnu sarainavāḍini."],
        ["Let's forget it.", "మరిచిపోదాం.", "maricipōdāṃ."],
        ["I apologize.", "నేను క్షమాపణ చేస్తున్నాను.", "nēnu kṣamāpaṇa cēstunnānu."],
        ["Don't be angry.", "కోపంగా ఉండకండి.", "kōpaṃgā uṇḍakaṇḍi."],
        ["We should solve this.", "మనం ఇది పరిష్కరించాలి.", "manaṃ idi pariṣkaraṃcāli."],
        ["Let's make up.", "మనం సరిపెట్టుకుందాం.", "manaṃ saripeṭṭukuṃdāṃ."],
    ],
}

def main():
    with open("data_telugu.json", "r", encoding="utf-8") as f:
        data = json.load(f)

    for ch in data:
        cid = ch.get("id")
        if cid not in SENTENCES:
            continue
        rows = SENTENCES[cid]
        for table in ch.get("tables", []):
            if table.get("heading") == "Conversation":
                table["rows"] = rows
                break

    with open("data_telugu.json", "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"Fixed {len(SENTENCES)} conversation chapters (826-851) with 15+ unique sentences each")

if __name__ == "__main__":
    main()
