# -*- coding: utf-8 -*-
"""
Rich Hindi script lessons (501–509): Maithili-style grids — vowel/consonant charts,
barakhadi rows, pronunciation pairs, conjuncts. Pedagogy aligned with standard
Devanagari / Hindi primers (e.g. barakhadi matra sequences, dental vs retroflex).
"""

from __future__ import annotations


def chapter_501() -> dict:
    return {
        "content": "Hindi is written in Devanagari. Learn independent vowels (स्वर), consonants (व्यंजन), and example words as in standard वर्णमाला charts.",
        "intro": "Hindi uses the same Devanagari letters as many North Indian languages. Each consonant has an inherent short ‘a’ unless a matra or halant is added.",
        "tables": [
            {
                "heading": "Vowels in Hindi (स्वर)",
                "headers": ["Letter", "Transliteration"],
                "speakCol": 1,
                "rows": [
                    ["अ", "a"],
                    ["आ", "ā"],
                    ["इ", "i"],
                    ["ई", "ī"],
                    ["उ", "u"],
                    ["ऊ", "ū"],
                    ["ऋ", "ṛ"],
                    ["ए", "e"],
                    ["ऐ", "ai"],
                    ["ओ", "o"],
                    ["औ", "au"],
                    ["अं", "aṃ"],
                    ["अः", "aḥ"],
                ],
            },
            {
                "heading": "Vowel usage examples",
                "headers": ["English", "Hindi", "Transliteration"],
                "speakCol": 1,
                "rows": [
                    ["name", "नाम", "nām"],
                    ["water", "पानी", "pānī"],
                    ["milk", "दूध", "dūdh"],
                    ["house", "घर", "ghar"],
                    ["good", "अच्छा", "acchā"],
                    ["today", "आज", "āj"],
                    ["tomorrow", "कल", "kal"],
                    ["yes", "हाँ", "hā̃"],
                    ["no", "नहीं", "nahī̃"],
                    ["one", "एक", "ek"],
                    ["two", "दो", "do"],
                    ["tea", "चाय", "cāy"],
                    ["rice", "चावल", "cāwal"],
                    ["friend", "दोस्त", "dost"],
                    ["book", "किताब", "kitāb"],
                    ["school", "स्कूल", "skūl"],
                    ["thank you", "धन्यवाद", "dhanyavād"],
                    ["welcome", "स्वागत", "svāgat"],
                ],
            },
            {
                "heading": "Consonants in Hindi (व्यंजन)",
                "headers": ["Letter", "Transliteration"],
                "speakCol": 1,
                "rows": [
                    ["क", "ka"],
                    ["ख", "kha"],
                    ["ग", "ga"],
                    ["घ", "gha"],
                    ["ङ", "ṅa"],
                    ["च", "ca"],
                    ["छ", "cha"],
                    ["ज", "ja"],
                    ["झ", "jha"],
                    ["ञ", "ña"],
                    ["ट", "ṭa"],
                    ["ठ", "ṭha"],
                    ["ड", "ḍa"],
                    ["ढ", "ḍha"],
                    ["ण", "ṇa"],
                    ["त", "ta"],
                    ["थ", "tha"],
                    ["द", "da"],
                    ["ध", "dha"],
                    ["न", "na"],
                    ["प", "pa"],
                    ["फ", "pha"],
                    ["ब", "ba"],
                    ["भ", "bha"],
                    ["म", "ma"],
                    ["य", "ya"],
                    ["र", "ra"],
                    ["ल", "la"],
                    ["व", "va"],
                    ["श", "śa"],
                    ["ष", "ṣa"],
                    ["स", "sa"],
                    ["ह", "ha"],
                    ["ळ", "ḷa"],
                    ["क्ष", "kṣa"],
                    ["ज्ञ", "jña"],
                ],
            },
            {
                "heading": "Example sentences (alphabet practice)",
                "headers": ["English", "Hindi", "Transliteration"],
                "speakCol": 1,
                "rows": [
                    ["Hello", "नमस्ते", "namaste"],
                    ["How are you?", "आप कैसे हैं?", "āp kaise haiṃ?"],
                    ["I am fine", "मैं ठीक हूँ", "main ṭhīk hū̃"],
                    ["What is your name?", "आपका नाम क्या है?", "āpkā nām kyā hai?"],
                    ["My name is…", "मेरा नाम … है", "merā nām … hai"],
                    ["Thank you", "धन्यवाद", "dhanyavād"],
                    ["Please", "कृपया", "kripayā"],
                    ["Sorry", "माफ़ कीजिए", "māf kījie"],
                    ["Good morning", "सुप्रभात", "suprabhāt"],
                    ["Good night", "शुभ रात्रि", "śubh rātri"],
                    ["See you tomorrow", "कल मिलते हैं", "kal milte haiṃ"],
                    ["I am learning Hindi", "मैं हिन्दी सीख रहा हूँ", "main hindī sīkh rahā hū̃"],
                    ["This is my book", "यह मेरी किताब है", "yah merī kitāb hai"],
                    ["Where do you live?", "आप कहाँ रहते हैं?", "āp kahā̃ rahte haiṃ?"],
                    ["I live in India", "मैं भारत में रहता हूँ", "main bhārat mẽ rahatā hū̃"],
                ],
            },
        ],
    }


def chapter_502() -> dict:
    return {
        "content": "Hindi vowels and consonants: clear vowel length (अ vs आ), aspiration (क vs ख), and retroflex vs dental (त vs ट).",
        "intro": "Listen for the puff of air on aspirated letters (ख, घ, छ, झ, etc.) and for tongue position on ट-वर्ग vs त-वर्ग.",
        "blocks": [
            {
                "type": "paragraph",
                "heading": "Pronunciation notes",
                "content": "Short अ is like the ‘u’ in ‘sugar’; long आ is like ‘father’. Retroflex ट ठ ड ढ ण use the tongue curled back; dental त थ द ध न use the tip behind the teeth.",
            },
            {
                "type": "table",
                "heading": "Words showing vowel sounds",
                "headers": ["English", "Hindi", "Transliteration"],
                "speakCol": 1,
                "rows": [
                    ["milk", "दूध", "dūdh"],
                    ["door", "दरवाज़ा", "darvāzā"],
                    ["sun", "सूरज", "sūraj"],
                    ["moon", "चाँद", "cā̃d"],
                    ["fire", "आग", "āg"],
                    ["cold", "ठंड", "thaṃḍ"],
                    ["hot", "गर्मी", "garmī"],
                    ["night", "रात", "rāt"],
                    ["day", "दिन", "din"],
                    ["city", "शहर", "śahar"],
                    ["village", "गाँव", "gā̃w"],
                    ["river", "नदी", "nadī"],
                    ["mountain", "पहाड़", "pahāṛ"],
                    ["tree", "पेड़", "peṛ"],
                    ["flower", "फूल", "phūl"],
                    ["fruit", "फल", "phal"],
                    ["bread", "रोटी", "roṭī"],
                    ["sugar", "चीनी", "cīnī"],
                    ["salt", "नमक", "namak"],
                ],
            },
            {
                "type": "table",
                "heading": "Words showing consonant contrasts",
                "headers": ["English", "Hindi", "Transliteration"],
                "speakCol": 1,
                "rows": [
                    ["four (4)", "चार", "cār"],
                    ["four (phonology practice)", "चार / टार", "cār / ṭār"],
                    ["post (mail)", "डाक", "ḍāk"],
                    ["branch", "डाल", "ḍāl"],
                    ["give (imperative)", "दो", "do"],
                    ["God", "ईश्वर", "īśvar"],
                    ["work", "काम", "kām"],
                    ["time", "समय", "samay"],
                    ["letter", "पत्र", "patra"],
                    ["question", "प्रश्न", "praśn"],
                    ["answer", "उत्तर", "uttar"],
                    ["north", "उत्तर", "uttar"],
                    ["south", "दक्षिण", "dakṣiṇ"],
                    ["east", "पूरब", "pūrab"],
                    ["west", "पश्चिम", "paścim"],
                    ["listen", "सुनिए", "sunie"],
                    ["speak slowly", "धीरे बोलिए", "dhīre bolie"],
                    ["repeat", "दोहराइए", "dohrāie"],
                ],
            },
        ],
    }


def chapter_503() -> dict:
    return {
        "content": "Barakhadi (बारहखड़ी): each consonant combines with matras — the twelve vowel sounds after क are का, कि, की, कु, कू, के, कै, को, कौ, कं, कः (patterns follow क for all letters).",
        "intro": "The inherent vowel is schwa (short a). Matras are: ा ि ी ु ू े ै ो ौ ं ः. Same sequence is learned for ख, ग, … ह in school charts.",
        "blocks": [
            {
                "type": "paragraph",
                "heading": "क + matras (model barakhadi row)",
                "content": "क (ka), का (kā), कि (ki), की (kī), कु (ku), कू (kū), के (ke), कै (kai), को (ko), कौ (kau), कं (kaṃ), कः (kaḥ). Replace क with any consonant for a full barakhadi chart.",
            },
            {
                "type": "table",
                "heading": "क-barakhadi (क + vowel signs)",
                "headers": ["Form", "Hindi", "Transliteration"],
                "speakCol": 1,
                "rows": [
                    ["base", "क", "ka"],
                    ["+ आ", "का", "kā"],
                    ["+ इ", "कि", "ki"],
                    ["+ ई", "की", "kī"],
                    ["+ उ", "कु", "ku"],
                    ["+ ऊ", "कू", "kū"],
                    ["+ ए", "के", "ke"],
                    ["+ ऐ", "कै", "kai"],
                    ["+ ओ", "को", "ko"],
                    ["+ औ", "कौ", "kau"],
                    ["+ अं", "कं", "kaṃ"],
                    ["+ अः", "कः", "kaḥ"],
                ],
            },
            {
                "type": "table",
                "heading": "Words using matras (practice)",
                "headers": ["English", "Hindi", "Transliteration"],
                "speakCol": 1,
                "rows": [
                    ["pen", "कलम", "kalam"],
                    ["work", "काम", "kām"],
                    ["girl", "लड़की", "laṛkī"],
                    ["boy", "लड़का", "laṛkā"],
                    ["school", "स्कूल", "skūl"],
                    ["teacher", "शिक्षक", "śikṣak"],
                    ["student", "छात्र", "chātra"],
                    ["question", "सवाल", "sawāl"],
                    ["write", "लिखना", "likhnā"],
                    ["read", "पढ़ना", "paṛhnā"],
                    ["book", "किताब", "kitāb"],
                    ["page", "पन्ना", "pannā"],
                    ["blackboard", "श्यामपट", "śyāmapaṭ"],
                    ["homework", "गृहकार्य", "gṛhakārya"],
                    ["exam", "परीक्षा", "parīkṣā"],
                    ["class", "कक्षा", "kakṣā"],
                    ["lesson", "पाठ", "pāṭh"],
                    ["alphabet", "वर्णमाला", "varṇamālā"],
                ],
            },
        ],
    }


def chapter_504() -> dict:
    return {
        "content": "Common mistakes: mixing dental त and retroflex ट; aspiration (क vs ख); and nasal vowels vs अनुस्वार.",
        "intro": "Use minimal pairs below — same English gloss shows the contrast you should hear.",
        "blocks": [
            {
                "type": "paragraph",
                "heading": "Tips",
                "content": "Curl the tongue for ट ठ ड ढ ण. Keep the tongue forward for त थ द ध न. Practice slowly: तल (floor) vs टाल (postpone).",
            },
            {
                "type": "table",
                "heading": "Dental vs retroflex (minimal pairs / contrasts)",
                "headers": ["Gloss", "Hindi", "Transliteration"],
                "speakCol": 1,
                "rows": [
                    ["four", "चार", "cār"],
                    ["post / pillar sense", "टार", "ṭār"],
                    ["give!", "दो", "do"],
                    ["branch", "डाल", "ḍāl"],
                    ["walnut (illustration)", "अखरोट", "akhroṭ"],
                    ["postal", "डाक", "ḍāk"],
                    ["beat (music)", "ताल", "tāl"],
                    ["lock", "ताला", "tālā"],
                    ["until", "तक", "tak"],
                    ["then", "तब", "tab"],
                    ["ṭuk ṭuk (knock)", "टक टक", "ṭak ṭak"],
                    ["dental ‘ta’ family", "त थ द ध न", "ta tha da dha na"],
                    ["retroflex ‘ṭa’ family", "ट ठ ड ढ ण", "ṭa ṭha ḍa ḍha ṇa"],
                    ["practice: slow", "धीमा", "dhīmā"],
                    ["practice: fast", "तेज़", "tez"],
                    ["thin", "पतला", "patlā"],
                    ["thick", "मोटा", "moṭā"],
                    ["here", "यहाँ", "yahā̃"],
                    ["there", "वहाँ", "vahā̃"],
                ],
            },
            {
                "type": "table",
                "heading": "Practice sentences",
                "headers": ["English", "Hindi", "Transliteration"],
                "speakCol": 1,
                "rows": [
                    ["Speak clearly", "साफ़ बोलिए", "sāf bolie"],
                    ["I did not understand", "मेरी समझ में नहीं आया", "merī samajh mẽ nahī̃ āyā"],
                    ["Say it again", "फिर से कहिए", "phir se kahie"],
                    ["Listen carefully", "ध्यान से सुनिए", "dhyān se sunie"],
                    ["This letter is retroflex", "यह अक्षर मूर्धन्य है", "yah akṣar mūrdhanya hai"],
                    ["That is dental", "वह दंत्य है", "vah dantya hai"],
                    ["Practice every day", "हर दिन अभ्यास करें", "har din abhyās kareṃ"],
                    ["Read aloud", "ज़ोर से पढ़ें", "zor se paṛheṃ"],
                    ["The pronunciation is difficult", "उच्चारण कठिन है", "uccāraṇ kaṭhin hai"],
                    ["Do not mix the two", "दोनों को मत मिलाइए", "donõ ko mat milāie"],
                    ["Repeat after me", "मेरे पीछे दोहराइए", "mere pīche dohrāie"],
                    ["Open your mouth wide", "मुँह चौड़ा खोलिए", "mũh chauṛā kholie"],
                    ["I will practice more", "मैं और अभ्यास करूँगा", "main aur abhyās karū̃gā"],
                    ["Which sound is this?", "यह कौन सा स्वर है?", "yah kaun sā svar hai?"],
                    ["Nasal sounds matter", "अनुनासिक ध्वनियाँ महत्वपूर्ण हैं", "anunāsika dhvaniyā̃ mahatvpūrṇ haiṃ"],
                ],
            },
        ],
    }


def chapter_505() -> dict:
    return {
        "content": "Anusvār (अनुस्वार) ं nasalizes the vowel; before velars it sounds like ङ, before dentals like न, etc.",
        "intro": "In Hindi, ं often indicates nasalization (गंगा, संगीत) or homorganic nasal before a stop (अंक, लंबा).",
        "blocks": [
            {
                "type": "table",
                "heading": "Words with अनुस्वार / nasalization",
                "headers": ["English", "Hindi", "Transliteration"],
                "speakCol": 1,
                "rows": [
                    ["Ganges", "गंगा", "gaṅgā"],
                    ["music", "संगीत", "saṅgīt"],
                    ["together", "संग", "saṅg"],
                    ["number", "अंक", "aṅk"],
                    ["Hindi", "हिंदी", "hiṃdī"],
                    ["lamp", "दीपक", "dīpak"],
                    ["moment", "क्षण", "kṣaṇ"],
                    ["king", "राजा", "rājā"],
                    ["temple", "मंदिर", "mandir"],
                    ["country", "देश", "deś"],
                    ["language", "भाषा", "bhāṣā"],
                    ["student", "छात्र", "chātra"],
                    ["teacher", "शिक्षक", "śikṣak"],
                    ["book", "पुस्तक", "pustak"],
                    ["knowledge", "ज्ञान", "jñān"],
                    ["peace", "शांति", "śāṃti"],
                    ["morning", "प्रभात", "prabhāt"],
                    ["evening", "संध्या", "sandhyā"],
                ],
            },
            {
                "type": "table",
                "heading": "Practice sentences",
                "headers": ["English", "Hindi", "Transliteration"],
                "speakCol": 1,
                "rows": [
                    ["I sing devotional songs", "मैं भजन गाता हूँ", "main bhajan gātā hū̃"],
                    ["This is important", "यह महत्वपूर्ण है", "yah mahatvpūrṇ hai"],
                    ["We study Hindi", "हम हिन्दी पढ़ते हैं", "ham hindī paṛhte haiṃ"],
                    ["The temple is old", "मंदिर पुराना है", "mandir purānā hai"],
                    ["Good morning", "सुप्रभात", "suprabhāt"],
                    ["Good evening", "शुभ संध्या", "śubha sandhyā"],
                    ["See you in the morning", "सुबह मिलते हैं", "subah milte haiṃ"],
                    ["I need rest", "मुझे आराम चाहिए", "mujhe ārām cāhie"],
                    ["Time is short", "समय कम है", "samay kam hai"],
                    ["Listen to the pronunciation", "उच्चारण सुनिए", "uccāraṇ sunie"],
                    ["Repeat the word", "शब्द दोहराइए", "śabd dohrāie"],
                    ["Nasalization is clear", "अनुनासिकता स्पष्ट है", "anunāsikata spaṣṭ hai"],
                    ["Practice this sound", "इस ध्वनि का अभ्यास करें", "is dhvani kā abhyās kareṃ"],
                    ["Use anusvār correctly", "अनुस्वार का सही प्रयोग करें", "anusvār kā sahī prayog kareṃ"],
                    ["The word has anusvār", "शब्द में अनुस्वार है", "śabd mẽ anusvār hai"],
                ],
            },
        ],
    }


def chapter_506() -> dict:
    return {
        "content": "जोड़ाक्षर: use halant (्) to drop the inherent vowel so consonants join — क् + त = क्त, स् + क = स्क.",
        "intro": "Common clusters appear in स्कूल, प्रेम, स्त्री, अस्तित्व. Practice reading words left to right, one cluster at a time.",
        "blocks": [
            {
                "type": "table",
                "heading": "Sample conjuncts (reading practice)",
                "headers": ["Conjunct", "Hindi word", "Transliteration"],
                "speakCol": 1,
                "rows": [
                    ["स्क", "स्कूल", "skūl"],
                    ["स्त", "वस्तु", "vastu"],
                    ["प्र", "प्रेम", "prem"],
                    ["त्र", "पत्र", "patra"],
                    ["क्त", "शक्ति", "śakti"],
                    ["क्ष", "क्षमा", "kṣamā"],
                    ["ज्ञ", "ज्ञान", "jñān"],
                    ["श्र", "श्री", "śrī"],
                    ["द्ध", "युद्ध", "yuddha"],
                    ["त्त", "मत्त", "matta"],
                    ["न्न", "चिन्न", "cinna"],
                    ["म्प", "कम्प", "kampa"],
                    ["न्त", "अन्त", "anta"],
                    ["ष्ट", "दृष्टि", "dṛṣṭi"],
                    ["र्व", "सर्व", "sarva"],
                    ["ल्प", "अल्प", "alpa"],
                    ["स्प", "स्पष्ट", "spaṣṭ"],
                    ["र्श", "दर्शन", "darśan"],
                ],
            },
            {
                "type": "table",
                "heading": "Sentences with conjuncts",
                "headers": ["English", "Hindi", "Transliteration"],
                "speakCol": 1,
                "rows": [
                    ["I love Hindi", "मुझे हिन्दी प्रिय है", "mujhe hindī priya hai"],
                    ["This is a school", "यह विद्यालय है", "yah vidyālaya hai"],
                    ["Write clearly", "स्पष्ट लिखिए", "spaṣṭ likhie"],
                    ["Strength is necessary", "शक्ति आवश्यक है", "śakti āvaśyaka hai"],
                    ["Forgive me", "क्षमा कीजिए", "kṣamā kījie"],
                    ["Knowledge is power", "ज्ञान शक्ति है", "jñān śakti hai"],
                    ["We respect teachers", "हम शिक्षकों का सम्मान करते हैं", "ham śikṣkõ kā sammān karte haiṃ"],
                    ["Read the letter", "पत्र पढ़िए", "patr paṛhie"],
                    ["The train arrived", "ट्रेन आ गई", "ṭren ā gaī"],
                    ["Stop here", "यहीं रुकिए", "yahī̃ rukie"],
                    ["Police!", "पुलिस!", "pulis!"],
                    ["Help!", "मदद!", "madad!"],
                    ["Emergency", "आपातकाल", "āpātkāl"],
                    ["Hospital", "अस्पताल", "aspatāl"],
                    ["Doctor", "चिकित्सक", "cikitsak"],
                    ["Medicine", "दवा", "davā"],
                ],
            },
        ],
    }


def chapter_507() -> dict:
    return {
        "content": "र् (reph) sits above the line: र्क, र्म, र्प. Subscript र appears in क्र, प्र, त्र, ग्र, द्र.",
        "intro": "त्र is common (country, three). प्र begins many Sanskrit-Hindi words. Practice the flap र clearly.",
        "blocks": [
            {
                "type": "table",
                "heading": "र-conjuncts (examples)",
                "headers": ["Conjunct", "Hindi word", "Transliteration"],
                "speakCol": 1,
                "rows": [
                    ["प्र", "प्रश्न", "praśn"],
                    ["त्र", "त्रि", "tri"],
                    ["क्र", "क्रिकेट", "krikeṭ"],
                    ["ग्र", "ग्राम", "grām"],
                    ["द्र", "द्रव्य", "dravya"],
                    ["भ्र", "भ्रम", "bhram"],
                    ["श्र", "श्री", "śrī"],
                    ["र्क", "शर्करा", "śarkarā"],
                    ["र्म", "कर्म", "karma"],
                    ["र्प", "सर्प", "sarpa"],
                    ["र्ग", "दुर्ग", "durg"],
                    ["र्ज", "अर्जुन", "arjun"],
                    ["र्त", "तीर्थ", "tīrth"],
                    ["र्द", "मर्द", "mard"],
                    ["र्न", "वर्ण", "varṇ"],
                    ["र्प", "कर्पूर", "karpūr"],
                    ["र्व", "सर्व", "sarva"],
                    ["र्श", "वर्षा", "varṣā"],
                ],
            },
            {
                "type": "table",
                "heading": "Sentences (र in use)",
                "headers": ["English", "Hindi", "Transliteration"],
                "speakCol": 1,
                "rows": [
                    ["Turn left", "बाएँ मुड़िए", "bāẽ muṛie"],
                    ["Turn right", "दाएँ मुड़िए", "dāẽ muṛie"],
                    ["Go straight", "सीधे जाइए", "sīdhe jāie"],
                    ["Where is the road?", "सड़क कहाँ है?", "saṛak kahā̃ hai?"],
                    ["The path is long", "रास्ता लंबा है", "rāstā laṃbā hai"],
                    ["Train station", "रेलवे स्टेशन", "relve sṭeśan"],
                    ["Bus stop", "बस स्टॉप", "bas sṭॉp"],
                    ["Airport", "हवाई अड्डा", "havāī aḍḍā"],
                    ["I need a map", "मुझे नक्शा चाहिए", "mujhe nakśā cāhie"],
                    ["Three tickets", "तीन टिकट", "tīn ṭikaṭ"],
                    ["First platform", "पहला प्लेटफ़ॉर्म", "pahlā pleṭphॉrm"],
                    ["Please hurry", "जल्दी कीजिए", "jaldī kījie"],
                    ["Stop the car", "गाड़ी रोकिए", "gāṛī rokie"],
                    ["Traffic is heavy", "यातायात ज़्यादा है", "yātāyāt zyādā hai"],
                    ["Ring the bell", "घंटी बजाइए", "ghaṇṭī bajāie"],
                ],
            },
        ],
    }


def chapter_508() -> dict:
    return {
        "content": "Aspirates (ख, घ, छ, झ, थ, ध, फ, भ) use extra breath; ह combines in ह्न, ह्म, ह्व and appears in धन्यवाद, बहुत.",
        "intro": "Practice aspirated stops: compare क-ख, ग-घ, च-छ, ट-ठ, त-थ, प-फ.",
        "blocks": [
            {
                "type": "table",
                "heading": "Words with ह / aspirates",
                "headers": ["English", "Hindi", "Transliteration"],
                "speakCol": 1,
                "rows": [
                    ["thank you", "धन्यवाद", "dhanyavād"],
                    ["many / much", "बहुत", "bahut"],
                    ["happiness", "खुशी", "khushī"],
                    ["ghost", "भूत", "bhūt"],
                    ["effort", "प्रयास", "prayās"],
                    ["hope", "आशा", "āśā"],
                    ["laughter", "हँसी", "haṃsī"],
                    ["loss", "हानि", "hāni"],
                    ["profit", "लाभ", "lābh"],
                    ["today", "आज", "āj"],
                    ["tomorrow", "कल", "kal"],
                    ["yesterday", "कल", "kal"],
                    ["night", "रात", "rāt"],
                    ["morning", "सुबह", "subah"],
                    ["evening", "शाम", "śām"],
                    ["hour", "घंटा", "ghaṇṭā"],
                    ["minute", "मिनट", "minaṭ"],
                    ["birthday", "जन्मदिन", "janmadin"],
                ],
            },
            {
                "type": "table",
                "heading": "Practice sentences",
                "headers": ["English", "Hindi", "Transliteration"],
                "speakCol": 1,
                "rows": [
                    ["Thank you very much", "बहुत धन्यवाद", "bahut dhanyavād"],
                    ["I am very happy", "मैं बहुत खुश हूँ", "main bahut khush hū̃"],
                    ["Speak softly", "धीरे बोलिए", "dhīre bolie"],
                    ["This is difficult", "यह कठिन है", "yah kaṭhin hai"],
                    ["That is easy", "वह आसान है", "vah āsān hai"],
                    ["I hope so", "मुझे आशा है", "mujhe āśā hai"],
                    ["Good luck", "शुभकामनाएँ", "śubhakāmnāẽ"],
                    ["Have a nice day", "आपका दिन शुभ हो", "āpkā din śubh ho"],
                    ["Good night", "शुभ रात्रि", "śubh rātri"],
                    ["See you in the morning", "सुबह मिलेंगे", "subah mileṅge"],
                    ["The food was tasty", "खाना स्वादिष्ट था", "khānā svādiṣṭ thā"],
                    ["Bring water", "पानी लाइए", "pānī lāie"],
                    ["Open the window", "खिड़की खोलिए", "khiṛkī kholie"],
                    ["Close the door", "दरवाज़ा बंद कीजिए", "darvāzā band kījie"],
                    ["I need help", "मुझे मदद चाहिए", "mujhe madad cāhie"],
                ],
            },
        ],
    }


def chapter_509() -> dict:
    return {
        "content": "Special ligatures: क्ष (kṣa), त्र (tra), ज्ञ (jña) have fixed shapes; also ड़ ढ़ for flapped sounds in Hindi.",
        "intro": "क्ष appears in क्षमा, परक्षेत्र; त्र in त्रि, देश; ज्ञ in ज्ञान, योग्य.",
        "blocks": [
            {
                "type": "table",
                "heading": "Special conjuncts / letters",
                "headers": ["Form", "Example word", "Transliteration"],
                "speakCol": 1,
                "rows": [
                    ["क्ष", "क्षमा", "kṣamā"],
                    ["त्र", "त्रि", "tri"],
                    ["ज्ञ", "ज्ञान", "jñān"],
                    ["श्र", "श्री", "śrī"],
                    ["ड़", "गाड़ी", "gāṛī"],
                    ["ढ़", "पेढ़ा", "peṛhā"],
                    ["क्ष", "क्षेत्र", "kṣetra"],
                    ["त्र", "पत्र", "patra"],
                    ["ज्ञ", "योग्य", "yogya"],
                    ["क्ष", "लक्ष्मी", "lakṣmī"],
                    ["त्र", "राष्ट्र", "rāṣṭra"],
                    ["ज्ञ", "विज्ञान", "vijñān"],
                    ["क्ष", "क्षति", "kṣati"],
                    ["त्र", "मात्रा", "mātrā"],
                    ["ज्ञ", "अनजान", "anajān"],
                    ["क्ष", "पराक्रम", "parākram"],
                    ["त्र", "त्राण", "trāṇ"],
                    ["ज्ञ", "ज्ञात", "jñāt"],
                ],
            },
            {
                "type": "table",
                "heading": "Sentences for reading practice",
                "headers": ["English", "Hindi", "Transliteration"],
                "speakCol": 1,
                "rows": [
                    ["Forgive me", "क्षमा कीजिए", "kṣamā kījie"],
                    ["Knowledge is light", "ज्ञान ज्योति है", "jñān jyoti hai"],
                    ["India is a great country", "भारत महान देश है", "bhārat mahān deś hai"],
                    ["Science is useful", "विज्ञान उपयोगी है", "vijñān upayogī hai"],
                    ["Three books", "तीन किताबें", "tīn kitābeṃ"],
                    ["National flag", "राष्ट्रीय ध्वज", "rāṣṭrīya dhvaj"],
                    ["This region is famous", "यह क्षेत्र प्रसिद्ध है", "yah kṣetra prasiddh hai"],
                    ["She is qualified", "वह योग्य है", "vah yogya hai"],
                    ["The letter त्र is common", "त्र अक्षर सामान्य है", "tra akṣar sāmānya hai"],
                    ["Read the mantra slowly", "मंत्र धीरे पढ़ें", "mantra dhīre paṛheṃ"],
                    ["Respect everyone", "सबका सम्मान करें", "sabkā sammān kareṃ"],
                    ["Education is important", "शिक्षा महत्वपूर्ण है", "śikṣā mahatvpūrṇ hai"],
                    ["Culture is rich", "संस्कृति समृद्ध है", "saṃskṛti samṛddh hai"],
                    ["History teaches us", "इतिहास सिखाता है", "itihās sikhātā hai"],
                    ["Practice daily", "रोज़ अभ्यास करें", "roz abhyās kareṃ"],
                ],
            },
        ],
    }


def get_script_chapter(cid: int) -> dict | None:
    builders = {
        501: chapter_501,
        502: chapter_502,
        503: chapter_503,
        504: chapter_504,
        505: chapter_505,
        506: chapter_506,
        507: chapter_507,
        508: chapter_508,
        509: chapter_509,
    }
    fn = builders.get(cid)
    return fn() if fn else None
