# -*- coding: utf-8 -*-
"""
Title-aligned Kashmiri lesson banks. English lines are tagged by topic so the first rows
match each sublesson title; Kashmiri uses Devanagari + roman consistent with kashmiri_sentence_banks.py.
"""
from __future__ import annotations

T = tuple[str, str, str]


def _r(e: str, ks: str, ro: str) -> T:
    return (e, ks, ro)


# --- Lesson 3: Phrases & structures (543–596) — topic-first rows ---
KS_GOING_TO: list[T] = [
    _r('(Going to) I am going to eat now.', 'ब चुस आज खान यिम', 'B chus a:j kha:n yim'),
    _r('(Going to) We are going to leave early.', 'असि लवकर निकल यिम', 'Asi lavkar nikal yim'),
    _r('(Going to) He is going to read the book.', 'सु किताब पर यिम', 'Su kita:b par yim'),
    _r('(Going to) She is going to cook rice.', 'स शाल शिज यिम', 'S sha:l shij yim'),
    _r('(Going to) They are going to buy vegetables.', 'तिम सब्ज़ि ख़रीद यिम', 'Tim sabzi khari:d yim'),
    _r('(Going to) I am going to Srinagar tomorrow.', 'ब फालॅ श्रीनगर यिम', 'B fa:le Shri:nagar yim'),
    _r('(Going to) You are going to call me.', 'त्स मे फोन कर यिम', 'Ts me fon kar yim'),
    _r('(Going to) We are going to meet at the market.', 'असि बाज़ार मंज मिल यिम', 'Asi ba:zar manz mil yim'),
    _r('(Going to) He is going to sleep.', 'स सुत यिम', 'S sut yim'),
    _r('(Going to) I am going to study Kashmiri.', 'ब कॉशुर शिक यिम', 'B ko:shur shik yim'),
    _r('(Going to) She is going to wash clothes.', 'स कपड़ धो यिम', 'S kapaṛ dho yim'),
    _r('(Going to) We are going to pray.', 'असि दुआ कर यिम', 'Asi dua: kar yim'),
    _r('(Going to) They are going to return home.', 'तिम घर वापस यिम', 'Tim ghar va:pas yim'),
    _r('(Going to) I am going to drink tea.', 'ब चाय पी यिम', 'B cha:y pi yim'),
    _r('(Going to) It is going to rain.', 'पानी यिम', 'Pa:ni yim'),
    _r('(Going to) We are going to wait here.', 'असि यि ठाह यिम', 'Asi yi Tha:h yim'),
    _r('(Going to) You are going to help us.', 'त्स असि मदद कर यिम', 'Ts asi madad kar yim'),
    _r('(Going to) He is going to open the shop.', 'स दुकान खोल यिम', 'S duka:n khol yim'),
    _r('(Going to) I am going to write a letter.', 'ब चिट्ठी लिख यिम', 'B chiṭṭhi likh yim'),
    _r('(Going to) She is going to sing.', 'स गाव यिम', 'S ga:v yim'),
]

KS_USED_TO: list[T] = [
    _r('(Used to) I used to live in the village.', 'ब रॊव गांव मंज', 'B ro:v ga:̃v manz'),
    _r('(Used to) We used to walk to school.', 'असि स्कूल पॅथ चल', 'Asi sku:l pəth chal'),
    _r('(Used to) He used to read every day.', 'स हर दिन परान', 'S har din para:n'),
    _r('(Used to) She used to sing in the morning.', 'स सवेर गान', 'S savar ga:n'),
    _r('(Used to) They used to play here.', 'तिम यि खेळ', 'Tim yi kheḷ'),
    _r('(Used to) I used to eat at home.', 'ब घरि खान', 'B ghari kha:n'),
    _r('(Used to) You used to visit us.', 'त्स असि मिल', 'Ts asi mil'),
    _r('(Used to) We used to buy from this shop.', 'असि यि दुकान खॅ ख़रीद', 'Asi yi duka:n khə khari:d'),
    _r('(Used to) He used to work in town.', 'स शहर मंज काम', 'S shehar manz ka:m'),
    _r('(Used to) I used to fear the dark.', 'ब अंधेर खॅ डर', 'B andher khə ḍar'),
    _r('(Used to) She used to teach children.', 'स बच्च शिकाव', 'S bacca shika:v'),
    _r('(Used to) We used to listen to stories.', 'असि कहानि आशुन', 'Asi kaha:ni a:shun'),
    _r('(Used to) They used to come late.', 'तिम देर यि', 'Tim der yi'),
    _r('(Used to) I used to drink milk daily.', 'ब हर दिन दूध पी', 'B har din du:d pi'),
    _r('(Used to) You used to speak softly.', 'त्स नर्म उलाव', 'Ts narm ula:v'),
    _r('(Used to) He used to sleep early.', 'स लवकर सुत', 'S lavkar sut'),
    _r('(Used to) We used to share food.', 'असि खान वांट', 'Asi kha:n va:nṭ'),
    _r('(Used to) I used to forget keys.', 'ब चाबि विसर', 'B cha:bi visar'),
    _r('(Used to) She used to wash dishes.', 'स बर्तन धो', 'S bartan dho'),
    _r('(Used to) They used to pray together.', 'तिम एकठॅ दुआ', 'Tim ekathe dua:'),
]

KS_USED_TO_OLD: list[T] = [
    _r('(Old style / used to) Long ago I would sit under that tree.', 'पुरान वख्त ब ति रुख तॅ बस', 'Pura:n vakht b ti rukh tə bas'),
    _r('(Old style) People would gather in the courtyard.', 'लोक आंगन मंज इकठॅ', 'Lo:k a:ngan manz ikathe'),
    _r('(Old style) We would listen to elders.', 'असि बॅड आशुन', 'Asi bəḍ a:shun'),
    _r('(Old style) He would tell tales.', 'स कहानि सुनाव', 'S kaha:ni suna:v'),
    _r('(Old style) She would spin wool.', 'स ऊन कात', 'S u:n ka:t'),
    _r('(Old style) They would walk miles.', 'तिम मील चल', 'Tim mi:l chal'),
    _r('(Old style) I would fetch water.', 'ब आब आन', 'B a:b a:n'),
    _r('(Old style) You would not fear cold.', 'त्स सर्द न डर', 'Ts sard na ḍar'),
    _r('(Old style) We would cook on wood fire.', 'असि लॊकड़ पॅथ शिज', 'Asi lokaṛ pəth shij'),
    _r('(Old style) He would mend shoes.', 'स जूता ठीक', 'S ju:ta: thi:k'),
    _r('(Old style) She would sing folk songs.', 'स लोक गीत गाव', 'S lok gi:t ga:v'),
    _r('(Old style) They would trade at the fair.', 'तिम मॅला मंज सौदा', 'Tim məla: manz sauda:'),
    _r('(Old style) I would wake at dawn.', 'ब सवेर उठ', 'B savar uṭh'),
    _r('(Old style) We would respect guests.', 'असि मॅहमान इज़्ज़त', 'Asi məhma:n izzat'),
    _r('(Old style) You would help neighbours.', 'त्स पड़ोसि मदद', 'Ts paḍosi madad'),
    _r('(Old style) He would read by lamp.', 'स दिवॅ पॅथ पर', 'S dive pəth par'),
    _r('(Old style) She would knit in winter.', 'स सर्दि मंज बुन', 'S sardi manz bun'),
    _r('(Old style) We would save grain.', 'असि अन्न बचाव', 'Asi ann bacha:v'),
    _r('(Old style) They would cross the river.', 'तिम दरिया पार', 'Tim dariya: pa:r'),
    _r('(Old style) I would follow my father.', 'ब मॊज बॊब पॅथ', 'B moj bob pəth'),
]

KS_PREP_WITH_VERBS: list[T] = [
    _r('(Prep + verb) I work in the house.', 'ब घर मंज काम करान', 'B ghar manz ka:m kara:n'),
    _r('(Prep + verb) The book is on the table.', 'किताब मेज़ पॅथ', 'Kita:b mez pəth'),
    _r('(Prep + verb) He sits with friends.', 'स दोस्त सॅथ बस', 'S do:st səth bas'),
    _r('(Prep + verb) We go to the market.', 'असि बाज़ार गच', 'Asi ba:zar gach'),
    _r('(Prep + verb) She stands near the door.', 'स दरवाज़ लागि ठहर', 'S darva:z la:gi ṭeuhar'),
    _r('(Prep + verb) They sleep under the roof.', 'तिम छत तॅ सुत', 'Tim chat tə sut'),
    _r('(Prep + verb) I look at the moon.', 'ब चन्द्र पख', 'B chandra pakh'),
    _r('(Prep + verb) You walk on the road.', 'त्स रस्त पॅथ चल', 'Ts rast pəth chal'),
    _r('(Prep + verb) Water flows from the tap.', 'आब नलॅ पॅथ', 'A:b nalə pəth'),
    _r('(Prep + verb) We eat from a plate.', 'असि थालि मंज खा', 'Asi tha:li manz kha:'),
    _r('(Prep + verb) He comes from Srinagar.', 'स श्रीनगर पॅथ यि', 'S Shri:nagar pəth yi'),
    _r('(Prep + verb) She goes to school.', 'स स्कूल गच', 'S sku:l gach'),
    _r('(Prep + verb) I wait for the bus.', 'ब बस खॅ ठाह', 'B bas khə Tha:h'),
    _r('(Prep + verb) They talk about work.', 'तिम काम मुतलॅक कथ', 'Tim ka:m mutlək kath'),
    _r('(Prep + verb) The cat is under the bed.', 'बिलॅ बिस्तॅ तॅ', 'Bile bistə tə'),
    _r('(Prep + verb) We pray before food.', 'असि खान पॅहलॅ दुआ', 'Asi kha:n pəhle dua:'),
    _r('(Prep + verb) He runs after the ball.', 'स बॉल पॅथ दोर', 'S bo:l pəth dor'),
    _r('(Prep + verb) I write with a pen.', 'ब कलम सॅथ लिख', 'B kalam səth likh'),
    _r('(Prep + verb) She cuts with a knife.', 'स चाकू सॅथ काट', 'S cha:ku səth ka:ṭ'),
    _r('(Prep + verb) We meet after prayer.', 'असि नमाज़ पॅथ मिल', 'Asi nama:z pəth mil'),
]

KS_ADJECTIVE_SENTENCES: list[T] = [
    _r('(Adjective) The house is big.', 'घर चु बड़', 'Ghar chu baṛ'),
    _r('(Adjective) This boy is small.', 'यि लड़क चु लॊट', "Yi la:r'k chu loṭ"),
    _r('(Adjective) The water is cold.', 'आब चु थंड', 'A:b chu thaṇḍ'),
    _r('(Adjective) She is kind.', 'स छि नेक', 'S chi nek'),
    _r('(Adjective) He is brave.', 'स छु बहादुर', 'Su chu baha:dur'),
    _r('(Adjective) The food is tasty.', 'खाना चु लज़ीज़', 'Kha:na chu laziz'),
    _r('(Adjective) The road is long.', 'रस्त चु लंब', 'Rast chu lamb'),
    _r('(Adjective) This cloth is new.', 'यि कपड़ चु नव', 'Yi kapaṛ chu nav'),
    _r('(Adjective) The sky is clear.', 'आसमान चु साफ', 'A:asma:n chu sa:f'),
    _r('(Adjective) I am happy.', 'ब चुस ख़ुश', 'B chus kh>sh'),
    _r('(Adjective) You are tired.', 'त्स छुख थकल', 'Ts chukh thakal'),
    _r('(Adjective) They are ready.', 'तिम तैयार', 'Tim taiya:r'),
    _r('(Adjective) The fruit is sweet.', 'मेवॅ चि मिठ', 'Meve chi miṭh'),
    _r('(Adjective) His voice is loud.', 'सु आवाज़ चु उंच', 'Su a:wa:z chu unch'),
    _r('(Adjective) Her eyes are beautiful.', 'स अख चि ख़ूबसूरत', 'S akh chi khu:bsu:rat'),
    _r('(Adjective) The tea is hot.', 'चाय चु गरम', 'Cha:y chu garam'),
    _r('(Adjective) The night is dark.', 'रात चि कॊलॊ', 'Ra:t chi kolo'),
    _r('(Adjective) We are grateful.', 'असि शुकुरगुज़ार', 'Asi shukurguza:r'),
    _r('(Adjective) The child is clever.', 'बच्च चु हुशियार', 'Bacca chu hushiya:r'),
    _r('(Adjective) The book is old.', 'किताब चि पुरान', 'Kita:b chi pura:n'),
]

KS_CAN_ABLE: list[T] = [
    _r('(Can / able) I can read Kashmiri.', 'ब कॉशुर पर हेक', 'B ko:shur par hek'),
    _r('(Can / able) You can sit here.', 'त्स यि बस हेकिव', 'Ts yi bas hekiv'),
    _r('(Can / able) He can drive.', 'स गाड़ि चलाव हेक', 'S ga:ḍi chala:v hek'),
    _r('(Can / able) She can cook.', 'स शिज हेक', 'S shij hek'),
    _r('(Can / able) We can help.', 'असि मदद हेक', 'Asi madad hek'),
    _r('(Can / able) They can swim.', 'तिम तैराव हेक', 'Tim taira:v hek'),
    _r('(Can / able) I cannot lie.', 'ब झूठ न हेक', 'B jhu:ṭ na hek'),
    _r('(Can / able) Can you hear me?', 'त्स मे आश हेकिव?', 'Ts me a:sh hekiv?'),
    _r('(Can / able) He can lift this.', 'स यि उठाव हेक', 'S yi uṭha:v hek'),
    _r('(Can / able) She can write fast.', 'स तॅज़ लिख हेक', 'S təz likh hek'),
    _r('(Can / able) We can wait.', 'असि ठाह हेक', 'Asi Tha:h hek'),
    _r('(Can / able) They cannot come.', 'तिम न हेक यिव', 'Tim na hek yiv'),
    _r('(Can / able) I can see clearly.', 'ब साफ पख हेक', 'B sa:f pakh hek'),
    _r('(Can / able) You can try again.', 'त्स फिर कोशिश हेक', 'Ts phir koshish hek'),
    _r('(Can / able) He can fix the door.', 'स दरवाज़ ठीक हेक', 'S darva:z thi:k hek'),
    _r('(Can / able) She can sing well.', 'स बरो गाव हेक', 'S baro ga:v hek'),
    _r('(Can / able) We can understand.', 'असि समझ हेक', 'Asi samajh hek'),
    _r('(Can / able) I can pay tomorrow.', 'ब फालॅ दॅ हेक', 'B fa:le de hek'),
    _r('(Can / able) Can they leave now?', 'तिम आज़ि वच हेक?', 'Tim a:zi vach hek?'),
    _r('(Can / able) You can ask anything.', 'त्स कुछ पूछ हेक', 'Ts kuch pu:ch hek'),
]

KS_WANT_NEED: list[T] = [
    _r('(Want / need) I want water.', 'मे छु आब जाय', 'Me chhu a:b ja:y'),
    _r('(Want / need) I need rest.', 'मे कर विश्राम', 'Me kar vishra:m'),
    _r('(Want / need) He wants tea.', 'सु चाय जाय', 'Su cha:y ja:y'),
    _r('(Want / need) She needs medicine.', 'स दवा जाय', 'S dava: ja:y'),
    _r('(Want / need) We want peace.', 'असि अमन जाय', 'Asi aman ja:y'),
    _r('(Want / need) They need help.', 'तिम मदद जाय', 'Tim madad ja:y'),
    _r('(Want / need) You want to go.', 'त्स वचुन जाय', 'Ts vachun ja:y'),
    _r('(Want / need) I do not want trouble.', 'मे फिकिर न जाय', 'Me fikir na ja:y'),
    _r('(Want / need) She wants to learn.', 'स शिकुन जाय', 'S shikun ja:y'),
    _r('(Want / need) He needs money.', 'स पैसॅ जाय', 'S paise ja:y'),
    _r('(Want / need) We need time.', 'असि वख्त जाय', 'Asi vakht ja:y'),
    _r('(Want / need) I want my book.', 'मे म्योन किताब जाय', "Me m'on kita:b ja:y"),
    _r('(Want / need) They want food.', 'तिम खान जाय', 'Tim kha:n ja:y'),
    _r('(Want / need) Do you need anything?', 'त्स कुछ जाय?', 'Ts kuch ja:y?'),
    _r('(Want / need) I want to sleep.', 'मे सुतुन जाय', 'Me sutun ja:y'),
    _r('(Want / need) She wants to leave.', 'स वचुन जाय', 'S vachun ja:y'),
    _r('(Want / need) We want to meet.', 'मिलुन जाय असि', 'Milun ja:y asi'),
    _r('(Want / need) He needs a doctor.', 'स दक्तर जाय', 'S da:ktar ja:y'),
    _r('(Want / need) I want warmth.', 'मे गरमि जाय', 'Me garami ja:y'),
    _r('(Want / need) They want answers.', 'तिम जवाब जाय', 'Tim java:b ja:y'),
]

KS_BECOME_HAPPEN: list[T] = [
    _r('(Become / happen) It became cold.', 'सर्द गय', 'Sard gay'),
    _r('(Become / happen) He became a teacher.', 'स मॅश्टर गय', 'S məshṭar gay'),
    _r('(Become / happen) She became ill.', 'स बिमार गय', 'S bima:r gay'),
    _r('(Become / happen) Day broke.', 'दिन उजॊ', 'Din ujo'),
    _r('(Become / happen) What happened?', 'क्या गय?', 'Kya gay?'),
    _r('(Become / happen) Nothing happened.', 'कुछ न गय', 'Kuch na gay'),
    _r('(Become / happen) The child grew up.', 'बच्च वडॊ', 'Bacca vaḍo'),
    _r('(Become / happen) It will get better.', 'बरो यि', 'Baro yi'),
    _r('(Become / happen) The sky turned red.', 'आसमान सुर्ख', 'A:asma:n surkh'),
    _r('(Become / happen) We became friends.', 'असि दोस्त गय', 'Asi do:st gay'),
    _r('(Become / happen) He became angry.', 'स रुस गय', 'S rus gay'),
    _r('(Become / happen) She became quiet.', 'स शांत गय', 'S sha:nt gay'),
    _r('(Become / happen) Winter came.', 'सर्दि आय', 'Sardi a:y'),
    _r('(Become / happen) The work is done.', 'काम गय', 'Ka:m gay'),
    _r('(Become / happen) Night fell.', 'रात गय', 'Ra:t gay'),
    _r('(Become / happen) I became tired.', 'ब थक गय', 'B thak gay'),
    _r('(Become / happen) They became rich.', 'तिम अमीर गय', 'Tim ami:r gay'),
    _r('(Become / happen) It happened suddenly.', 'अचानक गय', 'Acha:nak gay'),
    _r('(Become / happen) She became famous.', 'स मॅशहूर गय', 'S məshhu:r gay'),
    _r('(Become / happen) We became worried.', 'असि फिकिर गय', 'Asi fikir gay'),
]

KS_SHOULD: list[T] = [
    _r('(Should) You should rest.', 'त्स आराम कर', 'Ts a:ra:m kar'),
    _r('(Should) We should go now.', 'असि आज़ि गच', 'Asi a:zi gach'),
    _r('(Should) He should eat.', 'स खा', 'S kha:'),
    _r('(Should) She should sleep.', 'स सुत', 'S sut'),
    _r('(Should) They should listen.', 'तिम आशुन', 'Tim a:shun'),
    _r('(Should) I should study.', 'ब शिक', 'B shik'),
    _r('(Should) You should not fear.', 'त्स न डर', 'Ts na ḍar'),
    _r('(Should) We should help.', 'असि मदद कर', 'Asi madad kar'),
    _r('(Should) He should tell the truth.', 'स सच उलाव', 'S sach ula:v'),
    _r('(Should) She should hurry.', 'स जल्दी', 'S jaldi'),
    _r('(Should) Children should respect elders.', 'बच्च बॅड इज़्ज़त', 'Bacca bəḍ izzat'),
    _r('(Should) We should save water.', 'असि आब बचाव', 'Asi a:b bacha:v'),
    _r('(Should) You should wash hands.', 'त्स हाथ धो', 'Ts ha:th dho'),
    _r('(Should) He should close the door.', 'स दरवाज़ बंद', 'S darva:z band'),
    _r('(Should) I should call home.', 'ब घर फोन', 'B ghar fon'),
    _r('(Should) They should wait.', 'तिम ठाह', 'Tim Tha:h'),
    _r('(Should) She should read more.', 'स होर पर', 'S hor par'),
    _r('(Should) We should be kind.', 'असि नेक', 'Asi nek'),
    _r('(Should) You should try.', 'त्स कोशिश', 'Ts koshish'),
    _r('(Should) He should apologize.', 'स माफ माग', 'S ma:f ma:g'),
]

KS_MUST_HAVE_TO: list[T] = [
    _r('(Must / have to) I must go.', 'ब वचुन', 'B vachun'),
    _r('(Must / have to) We have to work.', 'असि काम करुन', 'Asi ka:m karun'),
    _r('(Must / have to) He must pay.', 'स दॅन', 'S den'),
    _r('(Must / have to) She has to cook.', 'स शिजुन', 'S shijun'),
    _r('(Must / have to) They must leave.', 'तिम वचुन', 'Tim vachun'),
    _r('(Must / have to) You have to wait.', 'त्स ठाहुन', 'Ts Tha:hun'),
    _r('(Must / have to) I have to study.', 'ब शिकुन', 'B shikun'),
    _r('(Must / have to) We must hurry.', 'असि जल्दी', 'Asi jaldi'),
    _r('(Must / have to) He has to obey.', 'स फरमान मान', 'S farma:n ma:n'),
    _r('(Must / have to) She must take medicine.', 'स दवा खा', 'S dava: kha:'),
    _r('(Must / have to) I have to wake early.', 'ब लवकर उठुन', 'B lavkar uṭhun'),
    _r('(Must / have to) They must report.', 'तिम रिपोर्ट', 'Tim ripo:rṭ'),
    _r('(Must / have to) You must not lie.', 'त्स झूठ न', 'Ts jhu:ṭ na'),
    _r('(Must / have to) We have to save money.', 'असि पैसॅ बचाव', 'Asi paisə bacha:v'),
    _r('(Must / have to) He must fix this.', 'स यि ठीक', 'S yi thi:k'),
    _r('(Must / have to) She has to attend.', 'स हाज़िर', 'S ha:zi:r'),
    _r('(Must / have to) I must apologize.', 'ब माफ मागुन', 'B ma:f ma:gun'),
    _r('(Must / have to) They have to decide.', 'तिम फैसला', 'Tim faisla:'),
    _r('(Must / have to) You must sign.', 'त्स दसखत', 'Ts dasakhat'),
    _r('(Must / have to) We must try hard.', 'असि मेहनत', 'Asi mehnat'),
]

KS_KEEP_DOING: list[T] = [
    _r('(Keep doing) He keeps talking.', 'स उलाव चलान', 'S ula:v cala:n'),
    _r('(Keep doing) She keeps singing.', 'स गान चलान', 'S ga:n cala:n'),
    _r('(Keep doing) They keep arguing.', 'तिम बहस चलान', 'Tim bahas cala:n'),
    _r('(Keep doing) I keep thinking.', 'ब सोच चलान', 'B so:c cala:n'),
    _r('(Keep doing) We keep waiting.', 'असि ठाह चलान', 'Asi Tha:h cala:n'),
    _r('(Keep doing) The rain keeps falling.', 'पानी पॅ चलान', 'Pa:ni pe cala:n'),
    _r('(Keep doing) You keep forgetting.', 'त्स विसर चलान', 'Ts visar cala:n'),
    _r('(Keep doing) He keeps working.', 'स काम चलान', 'S ka:m cala:n'),
    _r('(Keep doing) She keeps smiling.', 'स मुस्कान चलान', 'S muska:n cala:n'),
    _r('(Keep doing) They keep asking.', 'तिम पूछ चलान', 'Tim pu:ch cala:n'),
    _r('(Keep doing) I keep trying.', 'ब कोशिश चलान', 'B koshish cala:n'),
    _r('(Keep doing) The baby keeps crying.', 'बच्च रोव चलान', 'Bacca ro:v cala:n'),
    _r('(Keep doing) We keep hoping.', 'असि उम्मीद चलान', 'Asi ummli:d cala:n'),
    _r('(Keep doing) He keeps reading.', 'स पर चलान', 'S par cala:n'),
    _r('(Keep doing) She keeps cooking.', 'स शिज चलान', 'S shij cala:n'),
    _r('(Keep doing) They keep playing.', 'तिम खेळ चलान', 'Tim kheḷ cala:n'),
    _r('(Keep doing) I keep watching.', 'ब पख चलान', 'B pakh cala:n'),
    _r('(Keep doing) You keep repeating.', 'त्स दोहराव चलान', 'Ts dohra:v cala:n'),
    _r('(Keep doing) The clock keeps ticking.', 'घड़ि चल चलान', 'Ghaṛi chal cala:n'),
    _r('(Keep doing) We keep meeting.', 'असि मिल चलान', 'Asi mil cala:n'),
]

KS_COMPARISON: list[T] = [
    _r('(Comparison) This is bigger than that.', 'यि ति पॅथ बड़', 'Yi ti pəth baṛ'),
    _r('(Comparison) He is taller than me.', 'स मॅ पॅथ लंब', 'S mə pəth lamb'),
    _r('(Comparison) She is the best.', 'स सबॅ बरो', 'S səbe baro'),
    _r('(Comparison) This is cheaper.', 'यि सस्त', 'Yi sast'),
    _r('(Comparison) That is more expensive.', 'तो महंग', 'To mahang'),
    _r('(Comparison) I am older than you.', 'ब तॅ पॅथ मॊट', 'B tə pəth moṭ'),
    _r('(Comparison) We are stronger.', 'असि मज़बूत', 'Asi mazbu:t'),
    _r('(Comparison) It is worse today.', 'आज खराब', 'A:j khara:b'),
    _r('(Comparison) This road is shorter.', 'यि रस्त लॊट', 'Yi rast loṭ'),
    _r('(Comparison) She sings better.', 'स बरो गाव', 'S baro ga:v'),
    _r('(Comparison) He runs faster.', 'स तॅज़ दोर', 'S təz dor'),
    _r('(Comparison) This is the smallest.', 'यि सबॅ लॊट', 'Yi səbe loṭ'),
    _r('(Comparison) That house is newer.', 'तो घर नव', 'To ghar nav'),
    _r('(Comparison) I feel better now.', 'आज़ि बरो', 'A:zi baro'),
    _r('(Comparison) They are richer.', 'तिम अमीर', 'Tim ami:r'),
    _r('(Comparison) This tea is sweeter.', 'यि चाय मिठ', 'Yi cha:y miṭh'),
    _r('(Comparison) He is wiser.', 'स हुशियार', 'S hushiya:r'),
    _r('(Comparison) We need more time.', 'असि होर वख्त', 'Asi hor vakht'),
    _r('(Comparison) She is younger.', 'स जवान', 'S java:n'),
    _r('(Comparison) It is the hardest.', 'सबॅ कठिन', 'Səbe kathin'),
]

KS_TO_KNOW: list[T] = [
    _r('(To know) I know this.', 'मे यि आस', 'Me yi a:s'),
    _r('(To know) Do you know him?', 'त्स सु जान?', 'Ts su ja:n?'),
    _r('(To know) She knows the answer.', 'स जवाब आस', 'S java:b a:s'),
    _r('(To know) We know the way.', 'असि रस्त आस', 'Asi rast a:s'),
    _r('(To know) They know nothing.', 'तिम कुछ न', 'Tim kuch na'),
    _r('(To know) I knew yesterday.', 'ब कल आस', 'B kal a:s'),
    _r('(To know) He will know tomorrow.', 'स फालॅ आस', 'S fa:le a:s'),
    _r('(To know) I want to know.', 'मे जानुन जाय', 'Me ja:nun ja:y'),
    _r('(To know) She does not know.', 'स न आस', 'S na a:s'),
    _r('(To know) We should know the truth.', 'असि सच आस', 'Asi sach a:s'),
    _r('(To know) You know my name.', 'त्स म्योन नाव आस', "Ts m'on na:v a:s"),
    _r('(To know) He knows Kashmiri.', 'स कॉशुर आस', 'S ko:shur a:s'),
    _r('(To know) I know how to cook.', 'मे शिज आस', 'Me shij a:s'),
    _r('(To know) They knew the risk.', 'तिम ख़तर आस', 'Tim khatar a:s'),
    _r('(To know) Let me know.', 'मे बॅ खबर', 'Me bə khabar'),
    _r('(To know) Who knows?', 'कुस आस?', 'Kus a:s?'),
    _r('(To know) I know her well.', 'मे स बरो आस', 'Me s baro a:s'),
    _r('(To know) We know the rules.', 'असि कायद आस', 'Asi ka:yda a:s'),
    _r('(To know) He knows the city.', 'स शहर आस', 'S shehar a:s'),
    _r('(To know) She knows music.', 'स मौसिकि आस', 'S mausiki a:s'),
]

KS_LET_SHALL: list[T] = [
    _r('(Let / shall we) Let us go.', 'गच', 'Gach'),
    _r('(Let / shall we) Let us eat.', 'खा', 'Kha:'),
    _r('(Let / shall we) Shall we sit?', 'बस?', 'Bas?'),
    _r('(Let / shall we) Let him speak.', 'स उलाव दॅ', 'S ula:v de'),
    _r('(Let / shall we) Let her rest.', 'स आराम दॅ', 'S a:ra:m de'),
    _r('(Let / shall we) Shall we start?', 'शुरू?', 'Shuru:?'),
    _r('(Let / shall we) Let them try.', 'तिम कोशिश दॅ', 'Tim koshish de'),
    _r('(Let / shall we) Let us wait.', 'ठाह', 'Tha:h'),
    _r('(Let / shall we) Shall we meet tomorrow?', 'फालॅ मिल?', 'Fa:le mil?'),
    _r('(Let / shall we) Let the child play.', 'बच्च खेळ दॅ', 'Bacca kheḷ de'),
    _r('(Let / shall we) Let us pray.', 'दुआ', 'Dua:'),
    _r('(Let / shall we) Shall we leave?', 'वच?', 'Vach?'),
    _r('(Let / shall we) Let it be.', 'रॊव दॅ', 'Ro:v de'),
    _r('(Let / shall we) Let us help.', 'मदद', 'Madad'),
    _r('(Let / shall we) Shall I come?', 'ब यिम?', 'B yim?'),
    _r('(Let / shall we) Let us read.', 'पर', 'Par'),
    _r('(Let / shall we) Shall we buy this?', 'यि ख़रीद?', 'Yi khari:d?'),
    _r('(Let / shall we) Let them decide.', 'तिम फैसला दॅ', 'Tim faisla: de'),
    _r('(Let / shall we) Let us sing.', 'गाव', 'Ga:v'),
    _r('(Let / shall we) Shall we call?', 'फोन?', 'Fon?'),
]

KS_WHICH_WHAT_THAT: list[T] = [
    _r('(Which/what/that) Which book is yours?', 'कुस किताब तुहन्द?', 'Kus kita:b tuhand?'),
    _r('(Which/what/that) What is this?', 'यि क्या छु?', 'Yi kya chu?'),
    _r('(Which/what/that) That is my house.', 'तो म्योन घर', "To m'on ghar"),
    _r('(Which/what/that) I know what you said.', 'मे आस त्स मॊल', 'Me a:s ts mol'),
    _r('(Which/what/that) Tell me which one.', 'वुच कुस', 'Vuch kus'),
    _r('(Which/what/that) This is the one I want.', 'यि मॅ जाय', 'Yi mə ja:y'),
    _r('(Which/what/that) That man who came.', 'तो मर्द यॊ आय', 'To mard yo a:y'),
    _r('(Which/what/that) What he said is true.', 'स मॊल सच', 'S mol sach'),
    _r('(Which/what/that) Which road goes there?', 'कुस रस्त यि?', 'Kus rast yi?'),
    _r('(Which/what/that) I forgot what she said.', 'ब विसर स मॊल', 'B visar s mol'),
    _r('(Which/what/that) That is why I came.', 'मॅह ब यिम', 'Məh b yim'),
    _r('(Which/what/that) What time is it?', 'वख्त कति?', 'Vakht kati?'),
    _r('(Which/what/that) This is what I meant.', 'यि मॅ मुराद', 'Yi mə mura:d'),
    _r('(Which/what/that) Which colour do you like?', 'कुस रंग पसंद?', 'Kus rang pasand?'),
    _r('(Which/what/that) That day was hard.', 'तो दिन कठिन', 'To din kathin'),
    _r('(Which/what/that) I know that place.', 'मे तो जाय आस', 'Me to ja:y a:s'),
    _r('(Which/what/that) What shall we do?', 'क्या कर?', 'Kya kar?'),
    _r('(Which/what/that) This and that are different.', 'यि ति फ़र्क', 'Yi ti fark'),
    _r('(Which/what/that) Tell me what happened.', 'वुच क्या गय', 'Vuch kya gay'),
    _r('(Which/what/that) Which bus leaves first?', 'कुस बस पॅहलॅ?', 'Kus bas pəhle?'),
]

KS_FORMAL_INSTRUCTIONS: list[T] = [
    _r('(Formal instruction) Please enter.', 'मेहरबानी अंदर यिव', 'Meharba:ni andar yiv'),
    _r('(Formal instruction) Kindly take a seat.', 'मेहरबानी बस', 'Meharba:ni bas'),
    _r('(Formal instruction) Please wait here.', 'मेहरबानी यि ठाह', 'Meharba:ni yi Tha:h'),
    _r('(Formal instruction) Do not smoke.', 'सिगरॅट न', 'Sigreṭ na'),
    _r('(Formal instruction) Please sign here.', 'मेहरबानी यि दसखत', 'Meharba:ni yi dasakhat'),
    _r('(Formal instruction) Kindly show your ID.', 'आईडी दॅखाव', 'A:iḍi de:kha:v'),
    _r('(Formal instruction) Please line up.', 'लाइन मंज', 'La:in manz'),
    _r('(Formal instruction) Maintain silence.', 'खामोश', 'Kha:mosh'),
    _r('(Formal instruction) Please switch off phones.', 'फोन बंद', 'Fon band'),
    _r('(Formal instruction) Report at nine.', 'नव वॅ हाज़िर', 'Nav ve ha:zi:r'),
    _r('(Formal instruction) Wear your uniform.', 'युनिफॉर्म पॅहन', 'Yunifo:rm pəhen'),
    _r('(Formal instruction) Please read the notice.', 'नोटिस पर', 'No:ṭis par'),
    _r('(Formal instruction) Kindly pay the fee.', 'फीस दॅ', 'Fi:s de'),
    _r('(Formal instruction) Do not run in the hall.', 'हॉल मंज न दोर', 'Ho:l manz na dor'),
    _r('(Formal instruction) Please submit the form.', 'फॉर्म जमा', 'Fo:rm jama:'),
    _r('(Formal instruction) Follow the rules.', 'कायद पॅथ', 'Ka:yda pəth'),
    _r('(Formal instruction) Please verify your name.', 'नाव चॅक', 'Na:v chek'),
    _r('(Formal instruction) Kindly cooperate.', 'तआवुन', "Ta'a:vun"),
    _r('(Formal instruction) Do not litter.', 'कचरा न', 'Kachara: na'),
    _r('(Formal instruction) Thank you for coming.', 'युन शुक्रिया', 'Yun shukriya'),
]

KS_TO_LIKE: list[T] = [
    _r('(To like) I like tea.', 'मे चाय आव', 'Me cha:y a:v'),
    _r('(To like) She likes music.', 'स मौसिकि आव', 'S mausiki a:v'),
    _r('(To like) He likes cricket.', 'स क्रिकॅट आव', 'S krikeṭ a:v'),
    _r('(To like) We like this place.', 'असि यि जाय आव', 'Asi yi ja:y a:v'),
    _r('(To like) They like sweets.', 'तिम मिठाइ आव', 'Tim miṭha:i a:v'),
    _r('(To like) Do you like rice?', 'त्स शाल आव?', 'Ts sha:l a:v?'),
    _r('(To like) I like your idea.', 'मे तुहन्द ख़्याल आव', 'Me tuhand khya:l a:v'),
    _r('(To like) She likes to read.', 'स परुन आव', 'S parun a:v'),
    _r('(To like) He likes cold weather.', 'स सर्द मौसम आव', 'S sard mausam a:v'),
    _r('(To like) We like your family.', 'असि तुहन्द कुटुंब आव', 'Asi tuhand kutumb a:v'),
    _r('(To like) I do not like lies.', 'मे झूठ न आव', 'Me jhu:ṭ na a:v'),
    _r('(To like) They like to travel.', 'तिम सफर आव', 'Tim safar a:v'),
    _r('(To like) She likes flowers.', 'स फूल आव', 'S phu:l a:v'),
    _r('(To like) I like helping.', 'मे मदद आव', 'Me madad a:v'),
    _r('(To like) He likes fish.', 'स मछि आव', 'S machi a:v'),
    _r('(To like) We like holidays.', 'असि छुट्टि आव', 'Asi chuṭṭi a:v'),
    _r('(To like) Do you like it?', 'त्स आव?', 'Ts a:v?'),
    _r('(To like) I like learning.', 'मे शिकुन आव', 'Me shikun a:v'),
    _r('(To like) She likes colours.', 'स रंग आव', 'S rang a:v'),
    _r('(To like) They like peace.', 'तिम अमन आव', 'Tim aman a:v'),
]

KS_WOULD: list[T] = [
    _r('(Would) I would come if I could.', 'ब यिम जॅ हेक', 'B yim jə hek'),
    _r('(Would) He would say that.', 'स तो मॊल', 'S to mol'),
    _r('(Would) She would help always.', 'स हमॅश मदद', 'S hame:sh madad'),
    _r('(Would) We would meet often.', 'असि अक्सर मिल', 'Asi aksar mil'),
    _r('(Would) They would not agree.', 'तिम न मान', 'Tim na ma:n'),
    _r('(Would) I would prefer tea.', 'मे चाय पसंद', 'Me cha:y pasand'),
    _r('(Would) You would like it.', 'त्स आव', 'Ts a:v'),
    _r('(Would) He would read aloud.', 'स उंच पर', 'S unch par'),
    _r('(Would) She would sing softly.', 'स नर्म गाव', 'S narm ga:v'),
    _r('(Would) We would wait.', 'असि ठाह', 'Asi Tha:h'),
    _r('(Would) I would never lie.', 'ब कदॅ न झूठ', 'B kade na jhu:ṭh'),
    _r('(Would) They would share food.', 'तिम खान वांट', 'Tim kha:n va:nṭ'),
    _r('(Would) He would visit yearly.', 'स हर साल', 'S har sa:l'),
    _r('(Would) She would teach for free.', 'स मुफ्त शिक', 'S muft shik'),
    _r('(Would) We would hope.', 'असि उम्मीद', 'Asi ummli:d'),
    _r('(Would) I would ask first.', 'ब पॅहलॅ पूछ', 'B pəhle pu:ch'),
    _r('(Would) You would understand.', 'त्स समझ', 'Ts samajh'),
    _r('(Would) He would forgive.', 'स माफ', 'S ma:f'),
    _r('(Would) They would listen.', 'तिम आशुन', 'Tim a:shun'),
    _r('(Would) I would try my best.', 'ब पूरी कोशिश', 'B pu:ri koshish'),
]

KS_UNDERSTAND: list[T] = [
    _r('(Understand / come to know) I understand you.', 'मे त्स समझ', 'Me ts samajh'),
    _r('(Understand / come to know) Do you understand?', 'त्स समझ?', 'Ts samajh?'),
    _r('(Understand / come to know) I came to know yesterday.', 'ब कल आख', 'B kal a:kh'),
    _r('(Understand / come to know) She understood the lesson.', 'स सबॅक समझ', 'S sabak samajh'),
    _r('(Understand / come to know) We finally understood.', 'असि आखिर समझ', 'Asi a:khir samajh'),
    _r('(Understand / come to know) He did not understand.', 'स न समझ', 'S na samajh'),
    _r('(Understand / come to know) I want to understand.', 'मे समझुन जाय', 'Me samajhun ja:y'),
    _r('(Understand / come to know) They understood the risk.', 'तिम ख़तर समझ', 'Tim khatar samajh'),
    _r('(Understand / come to know) Slowly I understood.', 'हलुई ब समझ', 'Halui b samajh'),
    _r('(Understand / come to know) Explain so I understand.', 'समझाव तॅ ब समझ', 'Samazha:v tə b samajh'),
    _r('(Understand / come to know) I understand Kashmiri a little.', 'ब थोड़ कॉशुर समझ', 'B tho:ṛ ko:shur samajh'),
    _r('(Understand / come to know) She understands children.', 'स बच्च समझ', 'S bacca samajh'),
    _r('(Understand / come to know) We understand the problem.', 'असि मसल समझ', 'Asi masal samajh'),
    _r('(Understand / come to know) I got to know through him.', 'ब स पॅथ आख', 'B s pəth a:kh'),
    _r('(Understand / come to know) Did you understand?', 'त्स समझ?', 'Ts samajh?'),
    _r('(Understand / come to know) Nobody understood.', 'कुस न समझ', 'Kus na samajh'),
    _r('(Understand / come to know) I understand your pain.', 'मे तुहन्द दुख समझ', 'Me tuhand dukh samajh'),
    _r('(Understand / come to know) He understands machines.', 'स मशीन समझ', 'S mashi:n samajh'),
    _r('(Understand / come to know) We came to know the truth.', 'असि सच आख', 'Asi sach a:kh'),
    _r('(Understand / come to know) She understands quickly.', 'स जल्दी समझ', 'S jaldi samajh'),
]

KS_QUESTION_TAG: list[T] = [
    _r('(Question tag) You are fine, aren\'t you?', 'त्स ठीक छुख, न?', 'Ts thi:k chukh, na?'),
    _r('(Question tag) He will come, won\'t he?', 'स यिम, न?', 'S yim, na?'),
    _r('(Question tag) She knows, doesn\'t she?', 'स आस, न?', 'S a:s, na?'),
    _r('(Question tag) We can go, can\'t we?', 'असि वच हेक, न?', 'Asi vach hek, na?'),
    _r('(Question tag) It is cold, isn\'t it?', 'सर्द, न?', 'Sard, na?'),
    _r('(Question tag) You will help, won\'t you?', 'त्स मदद, न?', 'Ts madad, na?'),
    _r('(Question tag) They left, didn\'t they?', 'तिम निकल, न?', 'Tim nikal, na?'),
    _r('(Question tag) I am right, am I not?', 'ब सही, न?', 'B sahi:, na?'),
    _r('(Question tag) This is yours, isn\'t it?', 'यि तुहन्द, न?', 'Yi tuhand, na?'),
    _r('(Question tag) She will sing, won\'t she?', 'स गाव, न?', 'S ga:v, na?'),
    _r('(Question tag) We are late, aren\'t we?', 'असि देर, न?', 'Asi der, na?'),
    _r('(Question tag) He eats meat, doesn\'t he?', 'स मास खा, न?', 'S ma:s kha:, na?'),
    _r('(Question tag) You remember, don\'t you?', 'त्स याद, न?', 'Ts ya:d, na?'),
    _r('(Question tag) It rained, didn\'t it?', 'पानी, न?', 'Pa:ni, na?'),
    _r('(Question tag) They know, don\'t they?', 'तिम आस, न?', 'Tim a:s, na?'),
    _r('(Question tag) I should go, shouldn\'t I?', 'ब वच, न?', 'B vach, na?'),
    _r('(Question tag) She is here, isn\'t she?', 'स यि, न?', 'S yi, na?'),
    _r('(Question tag) We tried, didn\'t we?', 'असि कोशिश, न?', 'Asi koshish, na?'),
    _r('(Question tag) He was there, wasn\'t he?', 'स तॊ, न?', 'S to, na?'),
    _r('(Question tag) You understand, don\'t you?', 'त्स समझ, न?', 'Ts samajh, na?'),
]

KS_REMEMBER: list[T] = [
    _r('(Remember) I remember you.', 'मे त्स याद', 'Me ts ya:d'),
    _r('(Remember) Do you remember?', 'त्स याद?', 'Ts ya:d?'),
    _r('(Remember) I forgot.', 'ब विसर', 'B visar'),
    _r('(Remember) She remembers everything.', 'स सब याद', 'S sab ya:d'),
    _r('(Remember) We remember that day.', 'असि तो दिन याद', 'Asi to din ya:d'),
    _r('(Remember) He forgot the key.', 'स चाबि विसर', 'S cha:bi visar'),
    _r('(Remember) I will remember.', 'ब याद यिम', 'B ya:d yim'),
    _r('(Remember) They remembered late.', 'तिम देर याद', 'Tim der ya:d'),
    _r('(Remember) Don\'t forget.', 'न विसर', 'Na visar'),
    _r('(Remember) I remember my promise.', 'मे वादॅ याद', 'Me va:de ya:d'),
    _r('(Remember) She forgot the name.', 'स नाव विसर', 'S na:v visar'),
    _r('(Remember) We remember our teacher.', 'असि मॅश्टर याद', 'Asi məshṭar ya:d'),
    _r('(Remember) I suddenly remembered.', 'ब अचानक याद', 'B acha:nak ya:d'),
    _r('(Remember) He remembers faces.', 'स मुख याद', 'S mukh ya:d'),
    _r('(Remember) Help me remember.', 'मे याद कर', 'Me ya:d kar'),
    _r('(Remember) I cannot remember.', 'ब न याद', 'B na ya:d'),
    _r('(Remember) They forgot the date.', 'तिम तारिख विसर', 'Tim ta:rikh visar'),
    _r('(Remember) Remember your duty.', 'फ़र्ज़ याद', 'Farz ya:d'),
    _r('(Remember) She remembers songs.', 'स गीत याद', 'S gi:t ya:d'),
    _r('(Remember) We shall always remember.', 'असि हमॅश याद', 'Asi hame:sh ya:d'),
]

KS_WANT_WITH_VERB: list[T] = [
    _r('(Want + verb) I want to eat.', 'मे खान जाय', 'Me kha:n ja:y'),
    _r('(Want + verb) She wants to sleep.', 'स सुतुन जाय', 'S sutun ja:y'),
    _r('(Want + verb) We want to leave.', 'असि वचुन जाय', 'Asi vachun ja:y'),
    _r('(Want + verb) He wants to read.', 'स परुन जाय', 'S parun ja:y'),
    _r('(Want + verb) They want to buy.', 'तिम ख़रीदुन जाय', 'Tim khari:dun ja:y'),
    _r('(Want + verb) I want to learn.', 'मे शिकुन जाय', 'Me shikun ja:y'),
    _r('(Want + verb) You want to go.', 'त्स वचुन जाय', 'Ts vachun ja:y'),
    _r('(Want + verb) She wants to cook.', 'स शिजुन जाय', 'S shijun ja:y'),
    _r('(Want + verb) We want to help.', 'मदद करुन जाय असि', 'Madad karun ja:y asi'),
    _r('(Want + verb) He wants to rest.', 'स आराम करुन जाय', 'S a:ra:m karun ja:y'),
    _r('(Want + verb) I do not want to fight.', 'मे लड़ुन न जाय', 'Me laḍun na ja:y'),
    _r('(Want + verb) They want to sing.', 'तिम गावुन जाय', 'Tim ga:vun ja:y'),
    _r('(Want + verb) She wants to call.', 'स फोन करुन जाय', 'S fon karun ja:y'),
    _r('(Want + verb) I want to ask.', 'मे पूछुन जाय', 'Me pu:chun ja:y'),
    _r('(Want + verb) We want to meet.', 'मिलुन जाय असि', 'Milun ja:y asi'),
    _r('(Want + verb) He wants to try.', 'स कोशिश करुन जाय', 'S koshish karun ja:y'),
    _r('(Want + verb) You want to see.', 'त्स पखुन जाय', 'Ts pakhun ja:y'),
    _r('(Want + verb) I want to write.', 'मे लिखुन जाय', 'Me likhun ja:y'),
    _r('(Want + verb) They want to wait.', 'तिम ठाहुन जाय', 'Tim Tha:hun ja:y'),
    _r('(Want + verb) She wants to drink.', 'स पीनुन जाय', 'S pi:nun ja:y'),
]

KS_WANT_OTHER_PERSON: list[T] = [
    _r('(Want for another) I want him to come.', 'मे चु स यि जाय', 'Me chu s yi ja:y'),
    _r('(Want for another) She wants us to stay.', 'स चि असि रॊव जाय', 'S chi asi ro:v ja:y'),
    _r('(Want for another) We want you to help.', 'असि चि त्स मदद जाय', 'Asi chi ts madad ja:y'),
    _r('(Want for another) He wants her to sing.', 'स चु स गाव जाय', 'Su chu s ga:v ja:y'),
    _r('(Want for another) They want me to go.', 'तिम चि ब वच जाय', 'Tim chi b vach ja:y'),
    _r('(Want for another) I want them to wait.', 'मे चि तिम ठाह जाय', 'Me chi tim Tha:h ja:y'),
    _r('(Want for another) She wants the child to study.', 'स चु बच्च शिक जाय', 'S chi bacca shik ja:y'),
    _r('(Want for another) We want him to rest.', 'असि चि स आराम जाय', 'Asi chi s a:ra:m ja:y'),
    _r('(Want for another) You want me to call?', 'त्स चि ब फोन जाय?', 'Ts chi b fon ja:y?'),
    _r('(Want for another) He wants everyone to eat.', 'स चि सब खा जाय', 'Su chi sab kha: ja:y'),
    _r('(Want for another) I want her to understand.', 'मे चि स समझ जाय', 'Me chi s samajh ja:y'),
    _r('(Want for another) They want us to leave.', 'तिम चि असि वच जाय', 'Tim chi asi vach ja:y'),
    _r('(Want for another) She wants you to read.', 'स चि त्स पर जाय', 'S chi ts par ja:y'),
    _r('(Want for another) We want the doctor to come.', 'असि चि दक्तर यि जाय', 'Asi chi da:ktar yi ja:y'),
    _r('(Want for another) I want my son to work.', 'मे चि म्योन पूत काम जाय', "Me chi m'on pu:t ka:m ja:y"),
    _r('(Want for another) He wants them to agree.', 'स चि तिम मान जाय', 'Su chi tim ma:n ja:y'),
    _r('(Want for another) She wants me to listen.', 'स चि ब आश जाय', 'S chi b a:sh ja:y'),
    _r('(Want for another) We want peace for all.', 'असि चि सब अमन जाय', 'Asi chi sab aman ja:y'),
    _r('(Want for another) I want you to be safe.', 'मे चि त्स सलामत जाय', 'Me chi ts sala:mat ja:y'),
    _r('(Want for another) They want her to return.', 'तिम चि स वापस जाय', 'Tim chi s va:pas ja:y'),
]

KS_SUPPOSED_TO: list[T] = [
    _r('(Supposed to) I am supposed to go.', 'ब वचुन आस', 'B vachun a:s'),
    _r('(Supposed to) We are supposed to meet at nine.', 'असि नव मंज मिलुन', 'Asi nav manz milun'),
    _r('(Supposed to) He was supposed to call.', 'स फोन करुन आस', 'S fon karun a:s'),
    _r('(Supposed to) She is supposed to teach.', 'स शिकावुन आस', 'S shika:vun a:s'),
    _r('(Supposed to) They are supposed to arrive.', 'तिम पहुंचुन आस', 'Tim pahuñchun a:s'),
    _r('(Supposed to) You were supposed to help.', 'त्स मदद करुन आस', 'Ts madad karun a:s'),
    _r('(Supposed to) I am not supposed to tell.', 'ब न उलावुन', 'B na ula:vun'),
    _r('(Supposed to) We are supposed to pay today.', 'असि आज दॅन', 'Asi a:j den'),
    _r('(Supposed to) He is supposed to be here.', 'स यि आस', 'S yi a:s'),
    _r('(Supposed to) She was supposed to sing.', 'स गावुन आस', 'S ga:vun a:s'),
    _r('(Supposed to) They are supposed to report.', 'तिम रिपोर्ट करुन', 'Tim ripo:rṭ karun'),
    _r('(Supposed to) I am supposed to rest.', 'ब आराम करुन', 'B a:ra:m karun'),
    _r('(Supposed to) We were supposed to wait.', 'असि ठाहुन आस', 'Asi Tha:hun a:s'),
    _r('(Supposed to) You are supposed to sign.', 'त्स दसखत करुन', 'Ts dasakhat karun'),
    _r('(Supposed to) He is supposed to know.', 'स आस', 'S a:s'),
    _r('(Supposed to) I am supposed to finish.', 'ब खतम करुन', 'B khatam karun'),
    _r('(Supposed to) They were supposed to come.', 'तिम युन आस', 'Tim yun a:s'),
    _r('(Supposed to) She is supposed to cook.', 'स शिजुन', 'S shijun'),
    _r('(Supposed to) We are supposed to be quiet.', 'असि खामोश', 'Asi kha:mosh'),
    _r('(Supposed to) I was supposed to leave early.', 'ब लवकर वचुन आस', 'B lavkar vachun a:s'),
]

KS_LIKE_WITH_VERB: list[T] = [
    _r('(Like + verb) I like to walk.', 'मे चलुन आव', 'Me chalun a:v'),
    _r('(Like + verb) She likes to read.', 'स परुन आव', 'S parun a:v'),
    _r('(Like + verb) He likes to swim.', 'स तैरावुन आव', 'S taira:vun a:v'),
    _r('(Like + verb) We like to cook together.', 'असि एकठॅ शिजुन आव', 'Asi ekathe shijun a:v'),
    _r('(Like + verb) They like to travel.', 'तिम सफर करुन आव', 'Tim safar karun a:v'),
    _r('(Like + verb) I like to listen.', 'मे आशुन आव', 'Me a:shun a:v'),
    _r('(Like + verb) You like to sing.', 'त्स गावुन आव', 'Ts ga:vun a:v'),
    _r('(Like + verb) She likes to draw.', 'स बनावुन आव', 'S bana:vun a:v'),
    _r('(Like + verb) He likes to sleep late.', 'स देर सुतुन आव', 'S der sutun a:v'),
    _r('(Like + verb) We like to pray.', 'असि दुआ करुन आव', 'Asi dua: karun a:v'),
    _r('(Like + verb) I do not like to argue.', 'मे बहस करुन न आव', 'Me bahas karun na a:v'),
    _r('(Like + verb) They like to play football.', 'तिम फुटबॉल खेळुन आव', 'Tim fuṭbol kheḷun a:v'),
    _r('(Like + verb) She likes to help.', 'स मदद करुन आव', 'S madad karun a:v'),
    _r('(Like + verb) I like to learn words.', 'मे शब्द शिकुन आव', 'Me shabd shikun a:v'),
    _r('(Like + verb) He likes to drive.', 'स गाड़ि चलावुन आव', 'S ga:ḍi chala:vun a:v'),
    _r('(Like + verb) We like to share food.', 'असि खान वांटुन आव', 'Asi kha:n va:nṭun a:v'),
    _r('(Like + verb) You like to rest.', 'त्स आराम करुन आव', 'Ts a:ra:m karun a:v'),
    _r('(Like + verb) I like to watch the stars.', 'मे तारॅ पखुन आव', 'Me ta:re pakhun a:v'),
    _r('(Like + verb) They like to dance.', 'तिम नाचुन आव', 'Tim na:chun a:v'),
    _r('(Like + verb) She likes to write poems.', 'स शायरि लिखुन आव', 'S sha:yri likhun a:v'),
]

KS_VERB_PREP_TO_OBJECT: list[T] = [
    _r('(Verb + to + object) I gave water to the child.', 'मे बच्च आब दित', 'Me bacca a:b dit'),
    _r('(Verb + to + object) She showed the book to him.', 'स स किताब दॅखाव', 'S su kita:b de:kha:v'),
    _r('(Verb + to + object) We sent food to them.', 'असि तिम खान धाड', 'Asi tim kha:n dha:ḍ'),
    _r('(Verb + to + object) He told the news to me.', 'स मे ख़बर वुच', 'S me khabar vuch'),
    _r('(Verb + to + object) They gave help to us.', 'तिम असि मदद दित', 'Tim asi madad dit'),
    _r('(Verb + to + object) I wrote a letter to her.', 'मे स चिट्ठी लिख', 'Me s chiṭṭhi likh'),
    _r('(Verb + to + object) She brought tea for you.', 'स त्स चाय आन', 'S ts cha:y a:n'),
    _r('(Verb + to + object) We explained to the students.', 'असि तॅलिम समझाव', 'Asi təlim samazha:v'),
    _r('(Verb + to + object) He asked a question to the teacher.', 'स मॅश्टर सवाल', 'S məshṭar sava:l'),
    _r('(Verb + to + object) I returned money to him.', 'मे स पैसॅ वापस', 'Me su paise va:pas'),
    _r('(Verb + to + object) She lent a pen to me.', 'स मे कलम दित', 'S me kalam dit'),
    _r('(Verb + to + object) They sold rice to us.', 'तिम असि शाल वेच', 'Tim asi sha:l vech'),
    _r('(Verb + to + object) I offered food to guests.', 'मे मॅहमान खान', 'Me məhma:n kha:n'),
    _r('(Verb + to + object) He teaches maths to children.', 'स बच्च हिसाब', 'S bacca hisa:b'),
    _r('(Verb + to + object) We sent a message to her.', 'असि स पॅगाम', 'Asi s pəga:m'),
    _r('(Verb + to + object) She read the story to them.', 'स तिम कहानि पर', 'S tim kaha:ni par'),
    _r('(Verb + to + object) I opened the door for him.', 'मे स दरवाज़ खोल', 'Me su darva:z khol'),
    _r('(Verb + to + object) They showed the way to me.', 'तिम मे रस्त दॅखाव', 'Tim me rast de:kha:v'),
    _r('(Verb + to + object) He paid money to the shop.', 'स दुकान पैसॅ', 'S duka:n paise'),
    _r('(Verb + to + object) We gave thanks to God.', 'असि ख़ुदा शुक्रिया', 'Asi khuda: shukriya'),
]

KS_SHORT_FORMS: list[T] = [
    _r('(Short spoken) Yes.', 'हो', 'Ho'),
    _r('(Short spoken) No.', 'ना', 'Na:'),
    _r('(Short spoken) OK.', 'ठीक', 'Thi:k'),
    _r('(Short spoken) Come.', 'यि', 'Yi'),
    _r('(Short spoken) Go.', 'गच', 'Gach'),
    _r('(Short spoken) Wait.', 'ठाह', 'Tha:h'),
    _r('(Short spoken) What?', 'क्या?', 'Kya?'),
    _r('(Short spoken) Where?', 'कति?', 'Kati?'),
    _r('(Short spoken) How much?', 'कति?', 'Kati?'),
    _r('(Short spoken) Later.', 'पॅथ', 'Pəth'),
    _r('(Short spoken) Now.', 'आज़ि', 'A:zi'),
    _r('(Short spoken) I don\'t know.', 'मे न', 'Me na'),
    _r('(Short spoken) Fine.', 'ठीक', 'Thi:k'),
    _r('(Short spoken) Thanks.', 'शुक्रिया', 'Shukriya'),
    _r('(Short spoken) Please.', 'मेहरबानी', 'Meharba:ni'),
    _r('(Short spoken) Water.', 'आब', 'A:b'),
    _r('(Short spoken) Food.', 'खाना', 'Kha:na'),
    _r('(Short spoken) Home.', 'घर', 'Ghar'),
    _r('(Short spoken) Bus.', 'बस', 'Bas'),
    _r('(Short spoken) Money.', 'पैसॅ', 'Paise'),
]

KS_GREETINGS_WISHES: list[T] = [
    _r('(Greeting) Peace be upon you.', 'अस्सलामु अलैकुम', 'Assalaamu alaikum'),
    _r('(Wish) Happy Eid.', 'ईद मुबारक', 'I:d muba:rak'),
    _r('(Wish) Happy new year.', 'नव साल मुबारक', 'Nav sa:l muba:rak'),
    _r('(Blessing) May you be well.', 'त्स ठीक रॊव', 'Ts thi:k ro:v'),
    _r('(Slogan) Long live Kashmir.', 'ज़िंदाबाद कशीर', 'Zinda:ba:d kashi:r'),
    _r('(Wish) Good journey.', 'सफर मुबारक', 'Safar muba:rak'),
    _r('(Greeting) Good morning.', 'सुप्रभात', 'Suprabha:t'),
    _r('(Wish) Get well soon.', 'जल्दी ठीक', 'Jaldi thi:k'),
    _r('(Blessing) May God protect you.', 'ख़ुदा हफ़ाज़त', 'Khuda: hafa:zat'),
    _r('(Wish) Happy wedding.', 'शादि मुबारक', 'Sha:di muba:rak'),
    _r('(Greeting) Welcome.', 'इस्तक़्बाल', 'Istiqba:l'),
    _r('(Wish) Congratulations.', 'मुबारक', 'Muba:rak'),
    _r('(Slogan) Education for all.', 'सब खॅ शिक्षा', 'Sab khə shiksha:'),
    _r('(Blessing) May there be peace.', 'अमन आस', 'Aman a:s'),
    _r('(Wish) Happy birthday.', 'सालगिरह मुबारक', 'Sa:lgirah muba:rak'),
    _r('(Greeting) Namaste.', 'नमस्तॅ', 'Namaste'),
    _r('(Wish) Safe travels.', 'सफर सलामत', 'Safar sala:mat'),
    _r('(Blessing) Bless your hands.', 'हाथ शुभ', 'Ha:th shubh'),
    _r('(Wish) Happy Diwali.', 'दिवालि मुबारक', 'Diva:li muba:rak'),
    _r('(Slogan) Unity is strength.', 'एकता बल', 'Ekata bal'),
]

KS_COMPOUND_VERBS_MAIN: list[T] = [
    _r('(Compound verb) I sat down.', 'ब बस गय', 'B bas gay'),
    _r('(Compound verb) He stood up.', 'स उठ गय', 'S uṭh gay'),
    _r('(Compound verb) She looked around.', 'स चारि पख', 'S cha:ri pakh'),
    _r('(Compound verb) We ate up.', 'असि खा गय', 'Asi kha: gay'),
    _r('(Compound verb) They ran away.', 'तिम दोर गय', 'Tim dor gay'),
    _r('(Compound verb) I woke up.', 'ब उठ गय', 'B uṭh gay'),
    _r('(Compound verb) He fell down.', 'स पॅ गय', 'S pe gay'),
    _r('(Compound verb) She came back.', 'स वापस आय', 'S va:pas a:y'),
    _r('(Compound verb) We set out.', 'असि निकल गय', 'Asi nikal gay'),
    _r('(Compound verb) They sat together.', 'तिम एकठॅ बस', 'Tim ekathe bas'),
    _r('(Compound verb) I gave up.', 'ब छोड़ गय', 'B choṛ gay'),
    _r('(Compound verb) He picked up.', 'स उठाव', 'S uṭha:v'),
    _r('(Compound verb) She put down.', 'स थॊव', 'S thov'),
    _r('(Compound verb) We looked back.', 'असि पॅठ पख', 'Asi pəṭh pakh'),
    _r('(Compound verb) They moved on.', 'तिम आगॅ गय', 'Tim a:ge gay'),
    _r('(Compound verb) I tried again.', 'ब फिर कोशिश', 'B phir koshish'),
    _r('(Compound verb) He closed his eyes.', 'स अख बंद', 'S akh band'),
    _r('(Compound verb) She opened the door.', 'स दरवाज़ खोल', 'S darva:z khol'),
    _r('(Compound verb) We held hands.', 'असि हाथ थाम', 'Asi ha:th tha:m'),
    _r('(Compound verb) They raised flags.', 'तिम झंडॅ उंच', 'Tim jhaṇḍe unch'),
]

KS_ADDRESSING: list[T] = [
    _r('(Addressing) Uncle (father\'s brother).', 'चाच', 'Cha:ch'),
    _r('(Addressing) Aunt.', 'चाचि', 'Cha:chi'),
    _r('(Addressing) Grandfather.', 'बॅड', 'Bəḍ'),
    _r('(Addressing) Grandmother.', 'बॅडि', 'Bəḍi'),
    _r('(Addressing) Elder brother.', 'भैया', 'Bhaiya:'),
    _r('(Addressing) Sister.', 'बॅहन', 'Bəhn'),
    _r('(Addressing) Respected sir.', 'जनाब', 'Jana:b'),
    _r('(Addressing) Teacher.', 'मॅश्टर', 'Məshṭar'),
    _r('(Addressing) Mother.', 'मॊज', 'Moj'),
    _r('(Addressing) Father.', 'बॊब', 'Bob'),
    _r('(Addressing) Friend.', 'दोस्त', 'Do:st'),
    _r('(Addressing) Son.', 'पूत', 'Pu:t'),
    _r('(Addressing) Daughter.', 'धिय', 'Dhiy'),
    _r('(Addressing) Young man.', 'जवान', 'Java:n'),
    _r('(Addressing) Young woman.', 'जवान ज़ॅन', 'Java:n zən'),
    _r('(Addressing) Listen, brother.', 'भैया आश', 'Bhaiya: a:sh'),
    _r('(Addressing) Sister-in-law.', 'भाभि', 'Bha:bhi'),
    _r('(Addressing) Neighbour.', 'पड़ोसि', 'Paḍosi'),
    _r('(Addressing) Guest.', 'मॅहमान', 'Məhma:n'),
    _r('(Addressing) Doctor sahib.', 'दक्तर साहब', 'Da:ktar sa:hob'),
]

KS_EXCLAMATIONS: list[T] = [
    _r('(Exclamation) Oh!', 'ओह!', 'Oh!'),
    _r('(Exclamation) Wow!', 'वाह!', 'Va:h!'),
    _r('(Exclamation) Alas!', 'हाय!', 'Ha:y!'),
    _r('(Exclamation) Hurry!', 'जल्दी!', 'Jaldi!'),
    _r('(Exclamation) Be careful!', 'सावधान!', 'Sa:vdha:n!'),
    _r('(Exclamation) What a pity!', 'क्या फिकिर!', 'Kya fikir!'),
    _r('(Exclamation) Thank God!', 'शुकर ख़ुदा!', 'Shukar khuda:!'),
    _r('(Exclamation) How beautiful!', 'क्या ख़ूबसूरत!', 'Kya khu:bsu:rat!'),
    _r('(Exclamation) Stop!', 'थांब!', 'Tha:mb!'),
    _r('(Exclamation) Help!', 'मदद!', 'Madad!'),
    _r('(Exclamation) Fire!', 'आग!', 'A:g!'),
    _r('(Exclamation) Quiet!', 'खामोश!', 'Kha:mosh!'),
    _r('(Exclamation) Bravo!', 'शाबाश!', 'Sha:ba:sh!'),
    _r('(Exclamation) What nonsense!', 'क्या बकवास!', 'Kya bakva:s!'),
    _r('(Exclamation) So cold!', 'क्या सर्द!', 'Kya sard!'),
    _r('(Exclamation) So hot!', 'क्या गरम!', 'Kya garam!'),
    _r('(Exclamation) I am tired!', 'ब थक गय!', 'B thak gay!'),
    _r('(Exclamation) Great!', 'बरो!', 'Baro!'),
    _r('(Exclamation) Really?', 'सच?', 'Sach?'),
    _r('(Exclamation) Ouch!', 'ओह!', 'Oh!'),
]

KS_REQUESTS_MAY_CAN: list[T] = [
    _r('(Request) May I come in?', 'मे यिम?', 'Me yim?'),
    _r('(Request) Can you help me?', 'त्स मे मदद?', 'Ts me madad?'),
    _r('(Request) Could you repeat?', 'त्स फिर उलाव?', 'Ts phir ula:v?'),
    _r('(Request) May I sit?', 'मे बस?', 'Me bas?'),
    _r('(Request) Can I have water?', 'मे आब?', 'Me a:b?'),
    _r('(Request) Would you close the door?', 'त्स दरवाज़ बंद?', 'Ts darva:z band?'),
    _r('(Request) Please speak slowly.', 'हलुई उलाव', 'Halui ula:v'),
    _r('(Request) May we go?', 'असि वच?', 'Asi vach?'),
    _r('(Request) Can you wait?', 'त्स ठाह?', 'Ts Tha:h?'),
    _r('(Request) Could you show me?', 'त्स मे दॅखाव?', 'Ts me de:kha:v?'),
    _r('(Request) May I ask?', 'मे पूछ?', 'Me pu:ch?'),
    _r('(Request) Can you hear me?', 'त्स मे आश?', 'Ts me a:sh?'),
    _r('(Request) Would you mind?', 'त्स फिकिर?', 'Ts fikir?'),
    _r('(Request) Please help.', 'मदद मेहरबानी', 'Madad mehraba:ni'),
    _r('(Request) May I borrow?', 'मे उधार?', 'Me udha:r?'),
    _r('(Request) Can you call?', 'त्स फोन?', 'Ts fon?'),
    _r('(Request) Could you write?', 'त्स लिख?', 'Ts likh?'),
    _r('(Request) May I take this?', 'मे यि घॅ?', 'Me yi ghe?'),
    _r('(Request) Can we meet?', 'असि मिल?', 'Asi mil?'),
    _r('(Request) Please forgive.', 'माफ मेहरबानी', 'Ma:f mehraba:ni'),
]

KS_UNCERTAINTY: list[T] = [
    _r('(Uncertainty) Maybe it will rain.', 'शायद पानी यि', 'Sha:yad pa:ni yi'),
    _r('(Uncertainty) He might come.', 'स शायद यि', 'S sha:yad yi'),
    _r('(Uncertainty) Perhaps she forgot.', 'शायद स विसर', 'Sha:yad s visar'),
    _r('(Uncertainty) I might be late.', 'ब शायद देर', 'B sha:yad der'),
    _r('(Uncertainty) They might not agree.', 'तिम शायद न मान', 'Tim sha:yad na ma:n'),
    _r('(Uncertainty) It might snow.', 'शायद बर्फ', 'Sha:yad barf'),
    _r('(Uncertainty) We might leave early.', 'असि शायद लवकर', 'Asi sha:yad lavkar'),
    _r('(Uncertainty) She might call.', 'स शायद फोन', 'S sha:yad fon'),
    _r('(Uncertainty) Maybe tomorrow.', 'शायद फालॅ', 'Sha:yad fa:le'),
    _r('(Uncertainty) I am not sure.', 'मे यकीन न', 'Me yaki:n na'),
    _r('(Uncertainty) Perhaps you are right.', 'शायद त्स सही', 'Sha:yad ts sahi:'),
    _r('(Uncertainty) It could be true.', 'सच हो सक', 'Sach ho sak'),
    _r('(Uncertainty) He might know.', 'स शायद आस', 'S sha:yad a:s'),
    _r('(Uncertainty) We might try.', 'असि शायद कोशिश', 'Asi sha:yad koshish'),
    _r('(Uncertainty) Maybe later.', 'शायद पॅथ', 'Sha:yad pəth'),
    _r('(Uncertainty) She might refuse.', 'स शायद न', 'S sha:yad na'),
    _r('(Uncertainty) They might help.', 'तिम शायद मदद', 'Tim sha:yad madad'),
    _r('(Uncertainty) I might stay.', 'ब शायद रॊव', 'B sha:yad ro:v'),
    _r('(Uncertainty) Possibly.', 'शायद', 'Sha:yad'),
    _r('(Uncertainty) Who knows?', 'कुस आस?', 'Kus a:s?'),
]

KS_ADJ_FROM_VERB: list[T] = [
    _r('(Adj from verb) The written word.', 'लिखनॅ शब्द', 'Likhənə shabd'),
    _r('(Adj from verb) Boiled water.', 'उकलॅ आब', 'Ukələ a:b'),
    _r('(Adj from verb) Fried potatoes.', 'तलनॅ आलू', 'Tələnə a:lu:'),
    _r('(Adj from verb) Broken chair.', 'तोड़नॅ कुर्सि', 'Toṛənə kursi'),
    _r('(Adj from verb) Open door.', 'खुलनॅ दरवाज़', 'Khulnə darva:z'),
    _r('(Adj from verb) Closed shop.', 'बंद दुकान', 'Band duka:n'),
    _r('(Adj from verb) Washed clothes.', 'धोनॅ कपड़', 'Dhonə kapaṛ'),
    _r('(Adj from verb) Cooked rice.', 'शिजनॅ शाल', 'Shijnə sha:l'),
    _r('(Adj from verb) Spoken Kashmiri.', 'उलनॅ कॉशुर', 'Ulnə ko:shur'),
    _r('(Adj from verb) Learned person.', 'शिकनॅ मर्द', 'Shikənə mard'),
    _r('(Adj from verb) Painted wall.', 'रंगनॅ दिवार', 'Rangənə diva:r'),
    _r('(Adj from verb) Cut fruit.', 'काटनॅ मेवॅ', 'Ka:ṭənə meve'),
    _r('(Adj from verb) Built house.', 'बननॅ घर', 'Bannə ghar'),
    _r('(Adj from verb) Read book.', 'परनॅ किताब', 'Parnə kita:b'),
    _r('(Adj from verb) Sung song.', 'गानॅ गीत', 'Ga:nə gi:t'),
    _r('(Adj from verb) Tired body.', 'थकनॅ जिस्म', 'Thakənə jism'),
    _r('(Adj from verb) Frozen water.', 'जमनॅ आब', 'Jamənə a:b'),
    _r('(Adj from verb) Saved money.', 'बचनॅ पैसॅ', 'Bachənə paise'),
    _r('(Adj from verb) Lost key.', 'गुमनॅ चाबि', 'Gumnə cha:bi'),
    _r('(Adj from verb) Found child.', 'मिलनॅ बच्च', 'Milnə bacca'),
]

KS_ADJ_FROM_PREP: list[T] = [
    _r('(Adj + prep sense) The boy from the village.', 'गांव पॅथ लड़क', "Ga:̃v pəth la:r'k"),
    _r('(Adj + prep sense) People in the city.', 'शहर मंज लोक', 'Shehar manz lo:k'),
    _r('(Adj + prep sense) Book on the table.', 'मेज़ पॅथ किताब', 'Mez pəth kita:b'),
    _r('(Adj + prep sense) Star in the sky.', 'आसमान मंज तारॅ', 'A:asma:n manj ta:re'),
    _r('(Adj + prep sense) Fish in the water.', 'आब मंज मछि', 'A:b manj machi'),
    _r('(Adj + prep sense) Man under the tree.', 'रुख तॅ मर्द', 'Rukh tə mard'),
    _r('(Adj + prep sense) Girl near the door.', 'दरवाज़ लागि कॊड़', 'Darva:z la:gi ko:r'),
    _r('(Adj + prep sense) Shop by the road.', 'रस्त लागि दुकान', 'Rast la:gi duka:n'),
    _r('(Adj + prep sense) House on the hill.', 'पहाड़ पॅथ घर', 'Paha:ṛ pəth ghar'),
    _r('(Adj + prep sense) Birds on the roof.', 'छत पॅथ परिंद', 'Chat pəth parind'),
    _r('(Adj + prep sense) Child behind mother.', 'मॊज पॅठ बच्च', 'Moj pəṭh bacca'),
    _r('(Adj + prep sense) Money in the pocket.', 'जॅब मंज पैसॅ', 'Jeb manj paise'),
    _r('(Adj + prep sense) Letter from father.', 'बॊब पॅथ चिट्ठी', 'Bob pəth chiṭṭhi'),
    _r('(Adj + prep sense) Friends among us.', 'असि मंज दोस्त', 'Asi manz do:st'),
    _r('(Adj + prep sense) Teacher before class.', 'क्लास पॅहलॅ मॅश्टर', 'Kla:s pəhle məshṭar'),
    _r('(Adj + prep sense) Sun above clouds.', 'बादल पॅथ सूरज', 'Ba:dal pəth su:raj'),
    _r('(Adj + prep sense) Shoes under the bed.', 'बिस्तॅ तॅ जूता', 'Bistə tə ju:ta:'),
    _r('(Adj + prep sense) Car on the bridge.', 'पुल पॅथ कार', 'Pul pəth ka:r'),
    _r('(Adj + prep sense) Shop across the street.', 'रस्त पार दुकान', 'Rast pa:r duka:n'),
    _r('(Adj + prep sense) Flag over the building.', 'इमारत पॅथ झंडा', 'Ima:rat pəth jhaṇḍa:'),
]

KS_WISH_MAY: list[T] = [
    _r('(Wish) May you live long.', 'त्स देर जीव', 'Ts der ji:v'),
    _r('(Wish) May peace prevail.', 'अमन आस', 'Aman a:s'),
    _r('(Wish) May God bless you.', 'ख़ुदा रहम', 'Khuda: raham'),
    _r('(Wish) May you succeed.', 'त्स कामयाब', 'Ts ka:ma:yab'),
    _r('(Wish) May the child be healthy.', 'बच्च सॅहतमंद', 'Bacca sehatmand'),
    _r('(Wish) May we meet again.', 'फिर मिल', 'Phir mil'),
    _r('(Wish) May it rain.', 'पानी आस', 'Pa:ni a:s'),
    _r('(Wish) May your dreams come true.', 'तुहन्द सोपण पूरॅ', 'Tuhand sopən pu:re'),
    _r('(Wish) May there be prosperity.', 'ख़ैर आस', 'Khair a:s'),
    _r('(Wish) May he recover.', 'स ठीक आस', 'S thi:k a:s'),
    _r('(Wish) May she win.', 'स जित', 'S jit'),
    _r('(Wish) May they return safely.', 'तिम सलामत', 'Tim sala:mat'),
    _r('(Wish) May I be forgiven.', 'मे माफ', 'Me ma:f'),
    _r('(Wish) May the festival bring joy.', 'सण ख़ुशि', 'San khushi'),
    _r('(Wish) May your journey be safe.', 'तुहन्द सफर सलामत', 'Tuhand safar sala:mat'),
    _r('(Wish) May our team win.', 'अमार टीम जित', 'Ama:r ṭi:m jit'),
    _r('(Wish) May truth win.', 'सच जित', 'Sach jit'),
    _r('(Wish) May you find peace.', 'त्स अमन मिल', 'Ts aman mil'),
    _r('(Wish) May the sick heal.', 'बिमार ठीक', 'Bima:r thi:k'),
    _r('(Wish) May kindness spread.', 'नेह फैल', 'Neh fail'),
]

KS_MAKE_SOMEONE_DO: list[T] = [
    _r('(Make someone do) I made him sit.', 'मे स बस करव', 'Me s bas karav'),
    _r('(Make someone do) She made me read.', 'स मे पर करव', 'S me par karav'),
    _r('(Make someone do) He made them work.', 'स तिम काम करव', 'S tim ka:m karav'),
    _r('(Make someone do) We made her sing.', 'असि स गाव करव', 'Asi s ga:v karav'),
    _r('(Make someone do) They made us wait.', 'तिम असि ठाह करव', 'Tim asi Tha:h karav'),
    _r('(Make someone do) Teacher made students write.', 'मॅश्टर तॅलिम लिख करव', 'Məshṭar təlim likh karav'),
    _r('(Make someone do) I let the child play.', 'ब बच्च खेळ दॅ', 'B bacca kheḷ de'),
    _r('(Make someone do) She got the food cooked.', 'स खान शिज करव', 'S kha:n shij karav'),
    _r('(Make someone do) He had the door opened.', 'स दरवाज़ खुल करव', 'S darva:z khul karav'),
    _r('(Make someone do) We made him understand.', 'असि स समझ करव', 'Asi s samajh karav'),
    _r('(Make someone do) Mother made me eat.', 'मॊज मे खा करव', 'Moj me kha: karav'),
    _r('(Make someone do) I made her laugh.', 'मे स हँस करव', 'Me s hãs karav'),
    _r('(Make someone do) They made him pay.', 'तिम स दॅ करव', 'Tim s de karav'),
    _r('(Make someone do) She sent me to buy.', 'स मे ख़रीद धाड', 'S me khari:d dha:ḍ'),
    _r('(Make someone do) We got the car fixed.', 'असि कार ठीक करव', 'Asi ka:r thi:k karav'),
    _r('(Make someone do) He made the dog run.', 'स कुकुर दोर करव', 'S kukur dor karav'),
    _r('(Make someone do) I had him call.', 'मे स फोन करव', 'Me s fon karav'),
    _r('(Make someone do) She made them leave.', 'स तिम वच करव', 'S tim vach karav'),
    _r('(Make someone do) We made bread at home.', 'असि घरि रोटि करव', 'Asi ghari ro:ṭi karav'),
    _r('(Make someone do) He made me promise.', 'स मे वाद करव', 'S me va:d karav'),
]

KS_GENERALIZING: list[T] = [
    _r('(Generalizing) Someone came.', 'कुस आय', 'Kus a:y'),
    _r('(Generalizing) Something fell.', 'कुछ पॅ', 'Kuch pe'),
    _r('(Generalizing) Somewhere nearby.', 'कति नज़दीक', 'Kati nazdi:k'),
    _r('(Generalizing) Somehow we managed.', 'कैनॅ असि हल', 'Kaine asi hal'),
    _r('(Generalizing) Anyone can try.', 'कुस हेक कोशिश', 'Kus hek koshish'),
    _r('(Generalizing) Anything is possible.', 'कुछ मुमकिन', 'Kuch mumkin'),
    _r('(Generalizing) Nowhere to go.', 'कति न वच', 'Kati na vach'),
    _r('(Generalizing) Nothing happened.', 'कुछ न गय', 'Kuch na gay'),
    _r('(Generalizing) Everyone knows.', 'सब आस', 'Sab a:s'),
    _r('(Generalizing) Sometimes it rains.', 'कदॅ पानी', 'Kade pa:ni'),
    _r('(Generalizing) Someday we will meet.', 'कदॅ मिल', 'Kade mil'),
    _r('(Generalizing) Any book will do.', 'कुस किताब', 'Kus kita:b'),
    _r('(Generalizing) Nobody came.', 'कुस न आय', 'Kus na a:y'),
    _r('(Generalizing) Anywhere is fine.', 'कति बरो', 'Kati baro'),
    _r('(Generalizing) Something is wrong.', 'कुछ गलत', 'Kuch galat'),
    _r('(Generalizing) Somehow it worked.', 'कैनॅ चल', 'Kaine chal'),
    _r('(Generalizing) Everyone was happy.', 'सब ख़ुश', 'Sab kh>sh'),
    _r('(Generalizing) Nothing is certain.', 'कुछ यकीन न', 'Kuch yaki:n na'),
    _r('(Generalizing) Someone is calling.', 'कुस बुलाव', 'Kus bula:v'),
    _r('(Generalizing) Any time is good.', 'कुस वख्त बरो', 'Kus vakht baro'),
]

KS_POSSESSION_RELATION: list[T] = [
    _r('(Have / relation) I have a brother.', 'मे छु भ्रात', 'Me chhu bhra:t'),
    _r('(Have / relation) She has two sons.', 'स छि दो पूत', 'S chi do pu:t'),
    _r('(Have / relation) We have parents.', 'असि छि मॊज बॊब', 'Asi chi moj bob'),
    _r('(Have / relation) He has no sister.', 'स न छि बॅहन', 'S na chi bəhn'),
    _r('(Have / relation) They have a big family.', 'तिम छि मॊट कुटुंब', 'Tim chi moṭ kutumb'),
    _r('(Have / relation) I have friends here.', 'मे छि दोस्त यि', 'Me chi do:st yi'),
    _r('(Have / relation) She has a kind heart.', 'स छि नेक दिल', 'S chi nek dil'),
    _r('(Have / relation) We have time.', 'असि छि वख्त', 'Asi chi vakht'),
    _r('(Have / relation) He has money.', 'स छु पैसॅ', 'Su chhu paise'),
    _r('(Have / relation) Do you have children?', 'त्स छि बच्च?', 'Ts chi bacca?'),
    _r('(Have / relation) I have no fear.', 'मे न छु डर', 'Me na chu ḍar'),
    _r('(Have / relation) She has a good name.', 'स छु बरो नाव', 'Su chhu baro na:v'),
    _r('(Have / relation) They have land.', 'तिम छि ज़मीन', 'Tim chi zami:n'),
    _r('(Have / relation) We have hope.', 'असि छि उम्मीद', 'Asi chi ummli:d'),
    _r('(Have / relation) He has a car.', 'स छु कार', 'Su chhu ka:r'),
    _r('(Have / relation) I have your book.', 'मे छु तुजॅ किताब', 'Me chhu tujə kita:b'),
    _r('(Have / relation) She has relatives in town.', 'स छि रिश्तॅदार शहर', 'S chi rishtəda:r shehar'),
    _r('(Have / relation) We have the same teacher.', 'असि छि एक मॅश्टर', 'Asi chi ek məshṭar'),
    _r('(Have / relation) They have problems.', 'तिम छि मसल', 'Tim chi masal'),
    _r('(Have / relation) I have faith.', 'मे छु यकीन', 'Me chhu yaki:n'),
]

KS_TO_MEAN_ASK: list[T] = [
    _r('(Meaning) What does this mean?', 'यि क्या मतलब?', 'Yi kya matlab?'),
    _r('(Meaning) I don\'t understand the meaning.', 'मे मतलब न समझ', 'Me matlab na samajh'),
    _r('(Meaning) Explain the word.', 'शब्द समझाव', 'Shabd samazha:v'),
    _r('(Meaning) What do you mean?', 'त्स क्या मुराद?', 'Ts kya mura:d?'),
    _r('(Meaning) This word means water.', 'यि शब्द आब', 'Yi shabd a:b'),
    _r('(Meaning) I meant to help.', 'मे मदद मुराद', 'Me madad mura:d'),
    _r('(Meaning) She asked the meaning.', 'स मतलब पूछ', 'S matlab pu:ch'),
    _r('(Meaning) The name means lion.', 'नाव मतलब शेर', 'Na:v matlab sher'),
    _r('(Meaning) Can you translate?', 'त्स तॅज़म कर?', 'Ts təzəm kar?'),
    _r('(Meaning) I need a dictionary.', 'मे डिक्शनरी जाय', 'Me dikśnəri ja:y'),
    _r('(Meaning) That sentence is hard.', 'तो जुमला कठिन', 'To jumla kathin'),
    _r('(Meaning) What is this called?', 'यि क्या नाव?', 'Yi kya na:v?'),
    _r('(Meaning) He explained clearly.', 'स साफ समझाव', 'S sa:f samazha:v'),
    _r('(Meaning) I mixed up the meanings.', 'मे मतलब मिलाव', 'Me matlab mila:v'),
    _r('(Meaning) Same word, different meaning.', 'एक शब्द, फ़र्क मतलब', 'Ek shabd, fark matlab'),
    _r('(Meaning) Tell me in Kashmiri.', 'कॉशुर मंज वुच', 'Ko:shur manz vuch'),
    _r('(Meaning) I want the exact meaning.', 'मे सही मतलब', 'Me sahi: matlab'),
    _r('(Meaning) She wrote the gloss.', 'स लिख नोट', 'S likh no:ṭ'),
    _r('(Meaning) We learned new words.', 'असि नव शब्द', 'Asi nav shabd'),
    _r('(Meaning) The teacher defined it.', 'मॅश्टर बयान', 'Məshṭar baya:n'),
]

KS_CONJ_PART1: list[T] = [
    _r('(And) I came and sat.', 'ब आय आ बस', 'B a:y a bas'),
    _r('(But) Small but strong.', 'लॊट पॅर मज़बूत', 'Loṭ pər mazbu:t'),
    _r('(Because) Because of rain.', 'पानि खात्रि', 'Pa:ni kha:tri'),
    _r('(So) So we left.', 'मॅह असि निकल', 'Məh asi nikal'),
    _r('(That) I know that.', 'मे तो आस', 'Me to a:s'),
    _r('(Although) Although tired, he worked.', 'थकल पॅर स काम', 'Thakal pər s ka:m'),
    _r('(Though) Though it was late.', 'देर आस पॅर', 'Der a:s pər'),
    _r('(Still) Still we hope.', 'फिर भी असि उम्मीद', 'Phir bhi asi ummli:d'),
    _r('(Yet) Not finished yet.', 'अख़िर न खतम', 'Akhir na khatam'),
    _r('(And) He ate and drank.', 'स खाद आ पिय', 'S kha:d a piy'),
    _r('(But) Expensive but good.', 'महंग पॅर बरो', 'Mahang pər baro'),
    _r('(Because) Because I was ill.', 'बिमार आस खात्रि', 'Bima:r a:s kha:tri'),
    _r('(So) So she cried.', 'मॅह स रोव', 'Məh s ro:v'),
    _r('(That) They said that.', 'तिम तो मॊल', 'Tim to mol'),
    _r('(Although) Although young, wise.', 'जवान पॅर हुशियार', 'Java:n pər hushiya:r'),
    _r('(And) She smiled and waved.', 'स हँस आ हिल', 'S hãs a hil'),
    _r('(But) Cheap but bad quality.', 'सस्त पॅर खराब', 'Sast pər khara:b'),
    _r('(Because) Because I promised.', 'वादॅ खात्रि', 'Va:de kha:tri'),
    _r('(So) So I stayed.', 'मॅह ब रॊव', 'Məh b ro:v'),
    _r('(That) I hope that you come.', 'मे उम्मीद त्स यिव', 'Me ummli:d ts yiv'),
]

KS_CONJ_PART2: list[T] = [
    _r('(Or) Tea or coffee?', 'चाय या कॉफी?', 'Cha:y ya ko:fi?'),
    _r('(Nor) Neither hot nor cold.', 'ना गरम न सर्द', 'Na: garam na sard'),
    _r('(If) If you come.', 'अगर त्स यिव', 'Agar ts yiv'),
    _r('(In case) In case it rains.', 'अगर पानी', 'Agar pa:ni'),
    _r('(Provided) Provided you agree.', 'जॅ त्स मान', 'Jə ts ma:n'),
    _r('(As) As I said.', 'जॅ ब मॊल', 'Jə b mol'),
    _r('(Or) This or that?', 'यि या ति?', 'Yi ya ti?'),
    _r('(Neither) Neither came.', 'न स न ति', 'Na s na ti'),
    _r('(If) If not today.', 'अगर न आज', 'Agar na a:j'),
    _r('(Or) Walk or ride?', 'चल या सवारि?', 'Chal ya sava:ri?'),
    _r('(Nor) Neither rich nor poor.', 'ना अमीर न गरीब', 'Na: ami:r na gari:b'),
    _r('(If) If possible.', 'अगर हो सक', 'Agar ho sak'),
    _r('(As) As before.', 'जॅ पॅहलॅ', 'Jə pəhle'),
    _r('(Or) Now or never.', 'आज या कदॅ न', 'A:j ya kade na'),
    _r('(If) If God wills.', 'अगर ख़ुदा', 'Agar khuda:'),
]

KS_CONJ_PART3: list[T] = [
    _r('(After) After eating.', 'खान पॅथ', 'Kha:n pəth'),
    _r('(Then) Then we went.', 'मॅह असि गय', 'Məh asi gay'),
    _r('(As far as) As far as I know.', 'जॅ ब आस', 'Jə b a:s'),
    _r('(As long as) As long as you stay.', 'जॅ त्स रॊव', 'Jə ts ro:v'),
    _r('(As if) As if he knew.', 'जॅ स आस', 'Jə s a:s'),
    _r('(After) After the rain.', 'पानि पॅथ', 'Pa:ni pəth'),
    _r('(Then) Then she smiled.', 'मॅह स हँस', 'Məh s hãs'),
    _r('(As far as) As far as here.', 'यि तॅक', 'Yi tək'),
    _r('(As long as) As long as it takes.', 'जॅ वख्त लाग', 'Jə vakht la:g'),
    _r('(As if) As if in a dream.', 'जॅ ख़्वाब', 'Jə khwa:b'),
    _r('(After) After school.', 'स्कूल पॅथ', 'Sku:l pəth'),
    _r('(Then) Then they understood.', 'मॅह तिम समझ', 'Məh tim samajh'),
    _r('(As far as) As far as the eye sees.', 'अख पॅथ', 'Akh pəth'),
    _r('(As long as) As long as we live.', 'जॅ असि जीव', 'Jə asi ji:v'),
    _r('(As if) As if nothing happened.', 'जॅ कुछ न गय', 'Jə kuch na gay'),
]

KS_CONJ_PART4: list[T] = [
    _r('(As soon as) As soon as he came.', 'स यि तॅ', 'S yi tə'),
    _r('(Once) Once upon a time.', 'एक वख्त', 'Ek vakht'),
    _r('(Rather than) Rather than fight.', 'लड़ाइ पॅ बॅ', 'Laṛa:i pəth bə'),
    _r('(Instead of) Instead of rice.', 'शाल पॅ बॅ', 'Sha:l pəth bə'),
    _r('(So that) So that we win.', 'तॅ असि जित', 'Tə asi jit'),
    _r('(As soon as) As soon as possible.', 'जल्दी तॅ', 'Jaldi tə'),
    _r('(Once) Once you try.', 'एक वार कोशिश', 'Ek va:r koshish'),
    _r('(Rather than) Rather than wait.', 'ठाह पॅ बॅ', 'Tha:h pəth bə'),
    _r('(Instead of) Instead of walking.', 'चलुन पॅ बॅ', 'Chalun pəth bə'),
    _r('(So that) So that they know.', 'तॅ तिम आस', 'Tə tim a:s'),
    _r('(As soon as) As soon as it opens.', 'खुल तॅ', 'Khul tə'),
    _r('(Once) Once in a while.', 'कदॅ कदॅ', 'Kade kade'),
    _r('(Rather than) Rather than lose.', 'हार पॅ बॅ', 'Ha:r pəth bə'),
    _r('(Instead of) Instead of talking.', 'उलाव पॅ बॅ', 'Ula:v pəth bə'),
    _r('(So that) So that I remember.', 'तॅ ब याद', 'Tə b ya:d'),
]

KS_CONJUNCTION_LIST: list[T] = [
    _r('(Conjunction word) And — आनी', 'आनी', 'A:ni'),
    _r('(Conjunction word) But — पॅर', 'पॅर', 'Pər'),
    _r('(Conjunction word) Because — खात्रि', 'खात्रि', 'Kha:tri'),
    _r('(Conjunction word) Or — या', 'या', 'Ya:'),
    _r('(Conjunction word) If — अगर', 'अगर', 'Agar'),
    _r('(Conjunction word) So — मॅह', 'मॅह', 'Məh'),
    _r('(Conjunction word) That — तॊ', 'तॊ', 'To'),
    _r('(Conjunction word) When — कॅ', 'कॅ', 'Ke'),
    _r('(Conjunction word) Until — तॅ', 'तॅ', 'Tə'),
    _r('(Conjunction word) Although — पॅर', 'पॅर', 'Pər'),
    _r('(Conjunction word) After — पॅथ', 'पॅथ', 'Pəth'),
    _r('(Conjunction word) Before — पॅहलॅ', 'पॅहलॅ', 'Pəhle'),
    _r('(Conjunction word) Since — खात्रि', 'खात्रि', 'Kha:tri'),
    _r('(Conjunction word) While — चलान', 'चलान', 'Cala:n'),
    _r('(Conjunction word) Unless — जॅ न', 'जॅ न', 'Jə na'),
    _r('(Conjunction word) Nor — न', 'न', 'Na'),
    _r('(Conjunction word) Yet — फिर', 'फिर', 'Phir'),
    _r('(Conjunction word) Then — मॅह', 'मॅह', 'Məh'),
    _r('(Conjunction word) Thus — मॅह', 'मॅह', 'Məh'),
    _r('(Conjunction word) Also — भी', 'भी', 'Bhi'),
]

KS_COMBINING_SENTENCES: list[T] = [
    _r('(Combine) I ate and I drank.', 'ब खाद आ पिय', 'B kha:d a piy'),
    _r('(Combine) She sang and danced.', 'स गाय आ नाच', 'S ga:y a na:c'),
    _r('(Combine) He came but stayed little.', 'स आय पॅर थोड़', 'S a:y pər tho:ṛ'),
    _r('(Combine) We left because it rained.', 'पानि खात्रि असि निकल', 'Pa:ni kha:tri asi nikal'),
    _r('(Combine) They ran and shouted.', 'तिम धांव आ चिल्ल', 'Tim dha:̃v a chill'),
    _r('(Combine) I read then slept.', 'ब पर मॅह सुत', 'B par məh sut'),
    _r('(Combine) She cooked so we ate.', 'स शिज मॅह असि खाद', 'S shij məh asi kha:d'),
    _r('(Combine) He was tired yet worked.', 'स थक पॅर काम', 'S thak pər ka:m'),
    _r('(Combine) Open the door and enter.', 'दरवाज़ खोल आ भितर', 'Darva:z khol a bhitur'),
    _r('(Combine) I called but nobody answered.', 'ब फोन पॅर कुस न', 'B fon pər kus na'),
    _r('(Combine) We study and we play.', 'असि शिक आ खेळ', 'Asi shik a kheḷ'),
    _r('(Combine) He forgot so he failed.', 'स विसर मॅह नापास', 'S visar məh naapa:s'),
    _r('(Combine) She smiled and left.', 'स हँस आ निकल', 'S hãs a nikal'),
    _r('(Combine) I waited until he came.', 'ब ठाह जॅ स आय', 'B Tha:h jə s a:y'),
    _r('(Combine) They shouted and ran.', 'तिम चिल्ल आ धांव', 'Tim chill a dha:̃v'),
]

KS_COMPOUND_VERBS_2: list[T] = [
    _r('(Compound) Give me water to drink.', 'मे आब पीन दॅ', 'Me a:b pi:n de'),
    _r('(Compound) Look and see.', 'पख आ दॅख', 'Pakh a de:kh'),
    _r('(Compound) Sit and rest.', 'बस आ आराम', 'Bas a a:ra:m'),
    _r('(Compound) Get up and go.', 'उठ आ गच', 'Uṭh a gach'),
    _r('(Compound) Eat and drink.', 'खा आ पी', 'Kha: a pi'),
    _r('(Compound) Read and write.', 'पर आ लिख', 'Par a likh'),
    _r('(Compound) Come and help.', 'यि आ मदद', 'Yi a madad'),
    _r('(Compound) Stop and listen.', 'थांब आ आशुन', 'Tha:mb a a:shun'),
    _r('(Compound) Think and answer.', 'सोच आ जवाब', 'So:c a java:b'),
    _r('(Compound) Wash and wear.', 'धो आ पॅहन', 'Dho a pəhen'),
    _r('(Compound) Ask and learn.', 'पूछ आ शिक', 'Pu:ch a shik'),
    _r('(Compound) Try and succeed.', 'कोशिश आ कामयाब', 'Koshish a ka:ma:yab'),
    _r('(Compound) Run and catch.', 'धांव आ पकड़', 'Dha:̃v a pakaṛ'),
    _r('(Compound) Sing and clap.', 'गाव आ तालि', 'Ga:v a ta:li'),
    _r('(Compound) Pack and leave.', 'बांद आ निकल', 'Ba:nd a nikal'),
    _r('(Compound) Pay and go.', 'दॅ आ गच', 'De a gach'),
    _r('(Compound) Sign and submit.', 'दसखत आ जमा', 'Dasakhat a jama:'),
    _r('(Compound) Lock and go.', 'ताला आ गच', 'Ta:la: a gach'),
    _r('(Compound) Pray and sleep.', 'दुआ आ सुत', 'Dua: a sut'),
    _r('(Compound) Smile and nod.', 'हँस आ सिर हिल', 'Hãs a sir hil'),
]

KS_PASSIVE_FOCUS: list[T] = [
    _r('(Passive) Rice was cooked.', 'शाल शिजॅ', 'Sha:l shije'),
    _r('(Passive) The door was opened.', 'दरवाज़ खुलॅ', 'Darva:z khule'),
    _r('(Passive) The letter was sent.', 'चिट्ठी धाडॅ', 'Chiṭṭhi dha:ḍe'),
    _r('(Passive) Work was finished.', 'काम खतम', 'Ka:m khatam'),
    _r('(Passive) Money was counted.', 'पैसॅ गिनॅ', 'Paise gine'),
    _r('(Passive) The house was built.', 'घर बनॅ', 'Ghar bane'),
    _r('(Passive) Songs were sung.', 'गीत गॅ', 'Gi:t gə'),
    _r('(Passive) News was heard.', 'ख़बर आशॅ', 'Khabar a:she'),
    _r('(Passive) The field was ploughed.', 'खॅत नांगरॅ', 'Khət na:ngare'),
    _r('(Passive) The exam was passed.', 'इम्तिहान पास', 'Imtiha:n pa:s'),
    _r('(Passive) Mistakes were made.', 'गलति गय', 'Galati gay'),
    _r('(Passive) Rules were broken.', 'कायद तोड़', 'Ka:yda toṛ'),
    _r('(Passive) Food was served.', 'खान वॅडॅ', 'Kha:n veḍe'),
    _r('(Passive) Windows were closed.', 'खिड़की बंद', "Khi:r'ki band"),
    _r('(Passive) The flag was raised.', 'झंडॅ उंच', 'Jhaṇḍe unch'),
    _r('(Passive) A speech was given.', 'भाषण दॅ', 'Bha:ṣən de'),
    _r('(Passive) The car was sold.', 'कार वेचॅ', 'Ka:r veche'),
    _r('(Passive) Questions were asked.', 'सवाल पूछॅ', 'Sava:l pu:che'),
    _r('(Passive) The well was dug.', 'कुआ खोदॅ', 'Kua: khode'),
    _r('(Passive) Trees were planted.', 'रूख लगॅ', 'Rukh lage'),
]

KS_PASSIVE_STYLE2: list[T] = [
    _r('(Passive style 2) It got done.', 'हो गय', 'Ho gay'),
    _r('(Passive style 2) The work got finished.', 'काम गय खतम', 'Ka:m gay khatam'),
    _r('(Passive style 2) The glass got broken.', 'गिलास टूट गय', 'Gila:s ṭu:ṭ gay'),
    _r('(Passive style 2) The letter got lost.', 'चिट्ठी गुम गय', 'Chiṭṭhi gum gay'),
    _r('(Passive style 2) Money got stolen.', 'पैसॅ चोर', 'Paise chor'),
    _r('(Passive style 2) The door got locked.', 'दरवाज़ बंद गय', 'Darva:z band gay'),
    _r('(Passive style 2) Food got cold.', 'खान ठंड गय', 'Kha:n thaṇḍ gay'),
    _r('(Passive style 2) He got hurt.', 'स दुख गय', 'S dukh gay'),
    _r('(Passive style 2) She got scared.', 'स डर गय', 'S ḍar gay'),
    _r('(Passive style 2) We got ready.', 'असि तैयार गय', 'Asi taiya:r gay'),
    _r('(Passive style 2) They got late.', 'तिम देर गय', 'Tim der gay'),
    _r('(Passive style 2) I got a letter.', 'ब चिट्ठी मिल', 'B chiṭṭhi mil'),
    _r('(Passive style 2) It got dark.', 'अंधेर गय', 'Andher gay'),
    _r('(Passive style 2) The bus got full.', 'बस भर गय', 'Bas bhar gay'),
    _r('(Passive style 2) The news spread.', 'ख़बर फैल', 'Khabar fail'),
    _r('(Passive style 2) The plan failed.', 'प्लॅन फेल', 'Plən fel'),
    _r('(Passive style 2) The match was won.', 'मॅच जित', 'Məch jit'),
    _r('(Passive style 2) The bill was paid.', 'बिल दॅ', 'Bill de'),
    _r('(Passive style 2) The room was cleaned.', 'कमरा साफ', 'Kamra: sa:f'),
    _r('(Passive style 2) The problem was solved.', 'मसल हल', 'Masal hal'),
]

KS_FEEL_THINK: list[T] = [
    _r('(Feel) I feel cold.', 'मे सर्द लाग', 'Me sard la:g'),
    _r('(Feel) She feels happy.', 'स ख़ुश लाग', 'S kh>sh la:g'),
    _r('(Feel) He feels pain.', 'स दुख लाग', 'S dukh la:g'),
    _r('(Feel) We feel tired.', 'असि थक लाग', 'Asi thak la:g'),
    _r('(Feel) I feel better today.', 'आज बरो लाग', 'A:j baro la:g'),
    _r('(Think) I think so.', 'ब सोच अ', 'B so:c a'),
    _r('(Think) What do you think?', 'त्स क्या सोच?', 'Ts kya so:c?'),
    _r('(Think) She thinks deeply.', 'स गहर सोच', 'S gahar so:c'),
    _r('(Think) He changed his mind.', 'स फिकिर बदल', 'S fikir badal'),
    _r('(Think) We think alike.', 'असि एक सोच', 'Asi ek so:c'),
    _r('(Feel) I feel nervous.', 'मे घबर लाग', 'Me ghabar la:g'),
    _r('(Feel) They feel hopeful.', 'तिम उम्मीद लाग', 'Tim ummli:d la:g'),
    _r('(Think) Do not think badly.', 'बुरा न सोच', 'Bura: na so:c'),
    _r('(Feel) I feel lonely.', 'मे तन्हा लाग', 'Me tanha: la:g'),
    _r('(Think) I think he is right.', 'ब सोच स सही', 'B so:c s sahi:'),
    _r('(Feel) She feels dizzy.', 'स चक्कर लाग', 'S chakkar la:g'),
    _r('(Think) Think before you speak.', 'उलाव पॅहलॅ सोच', 'Ula:v pəhle so:c'),
    _r('(Feel) We feel grateful.', 'असि शुकुर लाग', 'Asi shukur la:g'),
    _r('(Think) He thinks too much.', 'स ज़्याद सोच', 'S zya:d so:c'),
    _r('(Feel) I feel at home.', 'मे घर लाग', 'Me ghar la:g'),
]

KS_IDIOMS_1: list[T] = [
    _r('(Idiom) Heart to heart.', 'दिल सॅथ दिल', 'Dil səth dil'),
    _r('(Idiom) Hand in hand.', 'हाथ मंज हाथ', 'Ha:th manj ha:th'),
    _r('(Idiom) Eye to eye.', 'अख सॅथ अख', 'Akh səth akh'),
    _r('(Idiom) Word of mouth.', 'मुख सॅथ मुख', 'Mukh səth mukh'),
    _r('(Idiom) Step by step.', 'कदम हलुई', 'Kadam halui'),
    _r('(Idiom) Day and night.', 'दिन रात', 'Din ra:t'),
    _r('(Idiom) Once in a blue moon.', 'कदॅ कदॅ', 'Kade kade'),
    _r('(Idiom) To lose face.', 'मुख खोन', 'Mukh khon'),
    _r('(Idiom) To break the heart.', 'दिल तोड़', 'Dil toṛ'),
    _r('(Idiom) Cold feet.', 'पॅर सर्द', 'Pər sard'),
    _r('(Idiom) Hot head.', 'सर गरम', 'Sar garam'),
    _r('(Idiom) Clean hands.', 'हाथ साफ', 'Ha:th sa:f'),
    _r('(Idiom) Heavy heart.', 'दिल भारि', 'Dil bha:ri'),
    _r('(Idiom) Sweet tongue.', 'ज़बान मिठ', 'Zaba:n miṭh'),
    _r('(Idiom) Long road.', 'रस्त लंब', 'Rast lamb'),
    _r('(Idiom) Bright future.', 'भविष्य उजाल', 'Bhavish uja:l'),
    _r('(Idiom) Old habit.', 'पुरान आदत', 'Pura:n a:dat'),
    _r('(Idiom) New leaf.', 'नव पन्नॅ', 'Nav panne'),
    _r('(Idiom) True friend.', 'सच्च दोस्त', 'Sachcha do:st'),
    _r('(Idiom) False hope.', 'खोट उम्मीद', 'Khoṭ ummli:d'),
]

KS_IDIOMS_2: list[T] = [
    _r('(Idiom 2) Time flies.', 'वख्त पख', 'Vakht pakh'),
    _r('(Idiom 2) Patience pays.', 'सब्र फळ', 'Sabr phaḷ'),
    _r('(Idiom 2) Knowledge is power.', 'इल्म बल', 'Ilm bal'),
    _r('(Idiom 2) Health is wealth.', 'सॅहत दौलत', 'Sehat daulat'),
    _r('(Idiom 2) Unity wins.', 'एकता जित', 'Ekata jit'),
    _r('(Idiom 2) Honesty lasts.', 'ईमान रॊव', 'I:ma:n ro:v'),
    _r('(Idiom 2) Pride falls.', 'घमंड पॅ', 'Ghamaṇḍ pe'),
    _r('(Idiom 2) Kindness returns.', 'नेह वापस', 'Neh va:pas'),
    _r('(Idiom 2) Anger burns.', 'राग जल', 'Ra:g jal'),
    _r('(Idiom 2) Peace heals.', 'अमन ठीक', 'Aman thi:k'),
    _r('(Idiom 2) Work worship.', 'काम पूजा', 'Ka:m pu:ja:'),
    _r('(Idiom 2) Guest is God.', 'मॅहमान ख़ुदा', 'Məhma:n khuda:'),
    _r('(Idiom 2) Mother first.', 'मॊज पॅहलॅ', 'Moj pəhle'),
    _r('(Idiom 2) Father\'s blessing.', 'बॊब दुआ', 'Bob dua:'),
    _r('(Idiom 2) Teacher\'s word.', 'मॅश्टर मॊल', 'Məshṭar mol'),
    _r('(Idiom 2) Book is friend.', 'किताब दोस्त', 'Kita:b do:st'),
    _r('(Idiom 2) Home is heaven.', 'घर जन्नत', 'Ghar jannat'),
    _r('(Idiom 2) Road teaches.', 'रस्त शिकाव', 'Rast shika:v'),
    _r('(Idiom 2) Village life.', 'गांव ज़िंदगि', 'Ga:̃v zindagi'),
    _r('(Idiom 2) City noise.', 'शहर शोर', 'Shehar shor'),
]

KS_IF_THEN_STYLE2: list[T] = [
    _r('(If–then style 2) If cold, wear warm clothes.', 'अगर सर्द, गरम कपड़', 'Agar sard, garam kapaṛ'),
    _r('(If–then style 2) If late, hurry.', 'अगर देर, जल्दी', 'Agar der, jaldi'),
    _r('(If–then style 2) If rain, take umbrella.', 'अगर पानी, छाता', 'Agar pa:ni, cha:ta:'),
    _r('(If–then style 2) If sick, see doctor.', 'अगर बिमार, दक्तर', 'Agar bima:r, da:ktar'),
    _r('(If–then style 2) If tired, rest.', 'अगर थक, आराम', 'Agar thak, a:ra:m'),
    _r('(If–then style 2) If hungry, eat.', 'अगर भूख, खा', 'Agar bhu:kh, kha:'),
    _r('(If–then style 2) If lost, ask.', 'अगर गॅब, पूछ', 'Agar gəb, pu:ch'),
    _r('(If–then style 2) If unsure, wait.', 'अगर शक, ठाह', 'Agar shak, Tha:h'),
    _r('(If–then style 2) If yes, sign.', 'अगर हो, दसखत', 'Agar ho, dasakhat'),
    _r('(If–then style 2) If no, leave.', 'अगर न, वच', 'Agar na, vach'),
    _r('(If–then style 2) If possible, help.', 'अगर हो सक, मदद', 'Agar ho sak, madad'),
    _r('(If–then style 2) If needed, call.', 'अगर ज़रूर, फोन', 'Agar zaru:r, fon'),
    _r('(If–then style 2) If free, come.', 'अगर फारिग, यि', 'Agar fa:rig, yi'),
    _r('(If–then style 2) If busy, later.', 'अगर मशगूल, पॅथ', 'Agar mashgu:l, pəth'),
    _r('(If–then style 2) If wrong, sorry.', 'अगर गलत, माफ', 'Agar galat, ma:f'),
    _r('(If–then style 2) If right, continue.', 'अगर सही, जारि', 'Agar sahi:, ja:ri'),
    _r('(If–then style 2) If dark, light lamp.', 'अगर अंधेर, दिवॊ', 'Agar andher, divo'),
    _r('(If–then style 2) If early, good.', 'अगर लवकर, बरो', 'Agar lavkar, baro'),
    _r('(If–then style 2) If expensive, don\'t buy.', 'अगर महंग, न ख़रीद', 'Agar mahang, na khari:d'),
    _r('(If–then style 2) If cheap, buy.', 'अगर सस्त, ख़रीद', 'Agar sast, khari:d'),
]

TARGET_BANK_REGISTRY: dict[str, list[T]] = {
    'KS_GOING_TO': KS_GOING_TO,
    'KS_USED_TO': KS_USED_TO,
    'KS_USED_TO_OLD': KS_USED_TO_OLD,
    'KS_PREP_WITH_VERBS': KS_PREP_WITH_VERBS,
    'KS_ADJECTIVE_SENTENCES': KS_ADJECTIVE_SENTENCES,
    'KS_CAN_ABLE': KS_CAN_ABLE,
    'KS_WANT_NEED': KS_WANT_NEED,
    'KS_BECOME_HAPPEN': KS_BECOME_HAPPEN,
    'KS_SHOULD': KS_SHOULD,
    'KS_MUST_HAVE_TO': KS_MUST_HAVE_TO,
    'KS_KEEP_DOING': KS_KEEP_DOING,
    'KS_COMPARISON': KS_COMPARISON,
    'KS_TO_KNOW': KS_TO_KNOW,
    'KS_LET_SHALL': KS_LET_SHALL,
    'KS_WHICH_WHAT_THAT': KS_WHICH_WHAT_THAT,
    'KS_FORMAL_INSTRUCTIONS': KS_FORMAL_INSTRUCTIONS,
    'KS_TO_LIKE': KS_TO_LIKE,
    'KS_WOULD': KS_WOULD,
    'KS_UNDERSTAND': KS_UNDERSTAND,
    'KS_QUESTION_TAG': KS_QUESTION_TAG,
    'KS_REMEMBER': KS_REMEMBER,
    'KS_WANT_WITH_VERB': KS_WANT_WITH_VERB,
    'KS_WANT_OTHER_PERSON': KS_WANT_OTHER_PERSON,
    'KS_SUPPOSED_TO': KS_SUPPOSED_TO,
    'KS_LIKE_WITH_VERB': KS_LIKE_WITH_VERB,
    'KS_VERB_PREP_TO_OBJECT': KS_VERB_PREP_TO_OBJECT,
    'KS_SHORT_FORMS': KS_SHORT_FORMS,
    'KS_GREETINGS_WISHES': KS_GREETINGS_WISHES,
    'KS_COMPOUND_VERBS_MAIN': KS_COMPOUND_VERBS_MAIN,
    'KS_ADDRESSING': KS_ADDRESSING,
    'KS_EXCLAMATIONS': KS_EXCLAMATIONS,
    'KS_REQUESTS_MAY_CAN': KS_REQUESTS_MAY_CAN,
    'KS_UNCERTAINTY': KS_UNCERTAINTY,
    'KS_ADJ_FROM_VERB': KS_ADJ_FROM_VERB,
    'KS_ADJ_FROM_PREP': KS_ADJ_FROM_PREP,
    'KS_WISH_MAY': KS_WISH_MAY,
    'KS_MAKE_SOMEONE_DO': KS_MAKE_SOMEONE_DO,
    'KS_GENERALIZING': KS_GENERALIZING,
    'KS_POSSESSION_RELATION': KS_POSSESSION_RELATION,
    'KS_TO_MEAN_ASK': KS_TO_MEAN_ASK,
    'KS_CONJ_PART1': KS_CONJ_PART1,
    'KS_CONJ_PART2': KS_CONJ_PART2,
    'KS_CONJ_PART3': KS_CONJ_PART3,
    'KS_CONJ_PART4': KS_CONJ_PART4,
    'KS_CONJUNCTION_LIST': KS_CONJUNCTION_LIST,
    'KS_COMBINING_SENTENCES': KS_COMBINING_SENTENCES,
    'KS_COMPOUND_VERBS_2': KS_COMPOUND_VERBS_2,
    'KS_PASSIVE_FOCUS': KS_PASSIVE_FOCUS,
    'KS_PASSIVE_STYLE2': KS_PASSIVE_STYLE2,
    'KS_FEEL_THINK': KS_FEEL_THINK,
    'KS_IDIOMS_1': KS_IDIOMS_1,
    'KS_IDIOMS_2': KS_IDIOMS_2,
    'KS_IF_THEN_STYLE2': KS_IF_THEN_STYLE2,
}
