# -*- coding: utf-8 -*-
"""
Kashmiri (Devanagari + roman) aligned to English strings in _maithili_s2_english.json (same order, same count per lesson).
"""
from __future__ import annotations

# lesson_id -> [(kashmiri_devanagari, roman), ...]  — English column comes from Maithili data JSON
KS_RO: dict[int, list[tuple[str, str]]] = {
    510: [
        ("ब", "bə"),
        ("तोह", "toh'"),
        ("सُ / س", "su / sə"),
        ("असि", "asi"),
        ("तिम", "tim"),
        ("यि", "yi"),
        ("ति", "ti"),
        ("मे छु नाव …", "Ma chho naw …"),
        ("त्वहि क्या छु नाव?", "Twahi kyaa ch'u naav?"),
        ("मे छु ठीक", "Me chhu thi:k"),
        ("तोहय छिवा वारय?", "Tohy ch'ivaa vaarai?"),
        ("यि चु म्योन किताब", "Yi chu m'on kita:b"),
        ("ति चु म्योन दोस्त", "Ti chu m'on do:st"),
        ("सु चु मास्टर", "su chu ma:star"),
        ("स च ख़ूबसूरथ", "sə cha khu:bsu:rath"),
        ("असि चि ख़ुश", "asi chi kh>sh"),
        ("तिम चि खेळान", "tim chi khe:la:n"),
    ],
    511: [
        ("तोह (बहुवचन)", "toh' (bahuvachan)"),
        ("तिम (आदर)", "tim (a:dar)"),
        ("तोह सारे", "toh' sa:re"),
        ("सारे लोक", "sa:re lo:k"),
        ("तोह सारन्क इस्तक़्बाल", "toh' sa:ranak istiqba:l"),
        ("तोह सारन्क शुक्रिया", "toh' sa:ranak shukriya"),
        ("तोह सारे क्या छिव?", "toh' sa:re kya chiv?"),
        ("असि सारे चि ठीक", "asi sa:re chi thi:k"),
        ("तिम आव", "tim a:v"),
        ("तिमन दि इज्ज़त द्यिव", "timan di izzat dyiv"),
        ("दोयि", "doyi"),
        ("अमि दोयि", "ami doyi"),
        ("तुन्द दोयि", "tund doyi"),
        ("बुज़ लोक", "buz lo:k"),
        ("सारे इन्सान", "sa:re insa:n"),
    ],
    512: [
        ("ब चुस करान", "b chus kara:n"),
        ("त्स चुख खान", "ts chukh kha:n"),
        ("सु चु गतशान", "su chu gatsha:n"),
        ("स च यिवान", "s cha yiva:n"),
        ("असि चि वुचान", "asi chi vucha:n"),
        ("तिम चि कथ करान", "tim chi kath kara:n"),
        ("ब चुस परान", "b chus para:n"),
        ("त्स चुख लेखान", "ts chukh le:kha:n"),
        ("खानुक", "kha:nuk"),
        ("गसुन", "gasun"),
        ("युन", "yun"),
        ("वुचुन", "vuchun"),
        ("बोलुन", "bolun"),
        ("दुन", "dun"),
        ("लिन", "lin"),
    ],
    513: [
        ("ब चुस बात खान", "b chus ba:t kheva:n"),
        ("त्स चुख आब चेवान", "ts chukh a:b ceva:n"),
        ("सु चु स्कूल गतशान", "su chu sku:l gatsha:n"),
        ("स च किताब परान", "s cha kita:b para:n"),
        ("असि चि मैथिली बोलान", "asi chi maithili bola:n"),
        ("तिम चि खेळान", "tim chi khe:la:n"),
        ("ब चुस ठाह", "b chus Tha:h"),
        ("त्स चुख फिकिरि तरान", "ts chukh phikiri tara:n"),
        ("सु चु तैराव करान पसंद", "su chu taira:v kara:n pasand"),
        ("स च स्कूल गतशान", "s cha sku:l gatsha:n"),
        ("ब चुस काम करान", "b chus ka:m kara:n"),
        ("कुकुर चु दोरान", "kukur chu do:ra:n"),
        ("परिंद चि उड़ान", "parind chi u:ra:n"),
        ("आब चु बहान", "a:b chu baha:n"),
        ("सूरज चु उगान", "su:r'aj chu uga:n"),
    ],
    514: [
        ("ब चुस तलमीज", "b chus talmi:z"),
        ("तोह चुख मास्टर", "toh' chukh ma:star"),
        ("सु चु बहादुर", "su chu baha:dur"),
        ("स च ख़ुश", "s cha kh>sh"),
        ("यि चु म्योन किताब", "yi chu m'on kita:b"),
        ("ति कर चु बड़", "ti kar chu ba:r"),
        ("असि चि दोस्त", "asi chi do:st"),
        ("तिम चि खेळान", "tim chi khe:la:n"),
        ("मे छु ठीक", "me chhu thi:k"),
        ("यि चु नव", "yi chu nav"),
        ("क्या स चु?", "kya sə chu?"),
        ("टायलेट कति छु?", "Ṭaaylet kati chu?"),
        ("शक़ नहीं छु", "shaq nahi: chu"),
        ("म्योन बٕٛتٕ زَیت چھُ", "m'on bə:z zi:t chu"),
        ("स च ख़ूबसूरथ", "sə cha khu:bsu:rath"),
    ],
    515: [
        ("ब चुस खान", "b chus kheva:n"),
        ("त्स चुख गतशान", "ts chukh gatsha:n"),
        ("सु चु यिवान", "su chu yiva:n"),
        ("स च परान", "s cha para:n"),
        ("असि चि कथ करान", "asi chi kath kara:n"),
        ("तिम चि खेळान", "tim chi khe:la:n"),
        ("ब चुस लेखान", "b chus le:kha:n"),
        ("त्स चुख बुजान", "ts chukh buza:n"),
        ("सु चु दोरान", "su chu do:ra:n"),
        ("स च वदान", "s cha vada:n"),
        ("ब चुस परान", "b chus para:n"),
        ("त्वहि क्या करान छु?", "twahi kya kara:n chu?"),
        ("त्वहि कति गतशान छु?", "twahi kati gatsha:n chu?"),
        ("रुद पड़ान छु", "ru:d pa:ra:n chu"),
        ("शुर चु सोतान", "shur' chu sota:n"),
    ],
    516: [
        ("बि गत्शी", "bi gatshi"),
        ("तोह आसिव", "toh a:siv"),
        ("सु खाशि", "su kha:shi"),
        ("स परिथ", "s parith"),
        ("असि बोलि", "asi boli"),
        ("तिम खेळन", "tim khe:l'n"),
        ("बि द्यि", "bi dyi"),
        ("त्स लॅख", "ts ləkh"),
        ("पगाह बि आस", "paga:h bi a:s"),
        ("अज़ रुद पॅयि?", "az ru:d peyi?"),
        ("त्स सफ़र गत्शिव?", "ts safar gatshiv?"),
        ("स आसि?", "s a:si?"),
        ("बि एक रात रोज़ि", "bi ek ra:th ro:zi"),
        ("गचिव ठीक जल्द", "gachiv thi:k jald"),
        ("तुहन्द भाग भला", "tuhand bha:g bhala"),
    ],
    517: [
        ("बि खामि", "bi kh'ami"),
        ("त्स गत्शान आसि", "ts gatsha:n a:si"),
        ("सु परान आसि", "su para:n a:si"),
        ("स काम करान आसि", "s ka:m kara:n a:si"),
        ("असि प्रतीक्षा करान आसि", "asi prati:ksha: kara:n a:si"),
        ("तिम खेळान आसि", "tim khe:la:n a:si"),
        ("पाँच बजे बि परान आस", "pa:~ch baje bi para:n a:s"),
        ("पगाह सवेर तोह सफ़र आसि", "paga:h saver' toh safar a:si"),
        ("अगला हफ़्त सु यि आसि", "agla: haf't su yi a:si"),
        ("तमि बि सोतान आस", "tami bi sota:n a:s"),
        ("त्स लेखान आसि", "ts le:kha:n a:si"),
        ("तिम खान आसि", "tim kha:n a:si"),
        ("स गान आसि", "s ga:n a:si"),
        ("असि वुचान आसि", "asi vucha:n a:si"),
        ("सु दोरान आसि", "su do:ra:n a:si"),
    ],
    518: [
        ("बि गोस", "bi go:s"),
        ("त्स आयि", "ts a:yi"),
        ("सु सोत", "su sot"),
        ("स दोर", "s dor"),
        ("असि पहुंच", "asi pahu~ch"),
        ("तिम नेर", "tim ner"),
        ("बि लड़", "bi la:r"),
        ("त्स खड़", "ts kha:r"),
        ("स मर", "s mar"),
        ("स हस", "s has"),
        ("वरिया काल गव न म्येलनसि", "variya kaal gov na myelnasi"),
        ("बि लॅप", "bi ləp"),
        ("सु दोरान करुन लाग", "su do:ra:n karun la:g"),
        ("स आख़िर आयि", "s a:khir a:yi"),
        ("कुकुर मर", "kukur mar"),
    ],
    519: [
        ("बि बात खाद", "bi ba:t kha:d"),
        ("त्स मे वुच", "ts me vuch"),
        ("ताम पारिथ किताब", "tAm' pArith kita:b"),
        ("ताम लिच चिठ’", "tAm' li:ch ciTh'"),
        ("अमि काम कर", "ami ka:m kar"),
        ("तिमन लॅख", "timan ləkh"),
        ("बि आब दित", "bi a:b dit"),
        ("त्स किताब किन", "ts kita:b kin"),
        ("ताम सप दॅ मार", "tAm' sap də ma:r"),
        ("ताम शीश कुल", "tAm' shi:sh kul"),
        ("बि बॅग लॅप", "bi bəg ləp"),
        ("ताम हेक नी कथ", "tAm' hek nI kath"),
        ("तिम कथ बंद कर", "tim kath band kar"),
        ("तामिस वुच पसंद", "tAm'is vuch pasand"),
        ("त्स नियम तोड़", "ts niyam to:r"),
    ],
    520: [
        ("बि गरी आस", "bi garI a:s"),
        ("त्स ठीक आसि", "ts thi:k a:si"),
        ("स तनह आस", "s tanah a:s"),
        ("स ख़ुश आस", "s kh>sh a:s"),
        ("यि मज़ेदार आस", "yi maze:da:r a:s"),
        ("यि सस्त आस", "yi sast a:s"),
        ("यि मुश्किल आस", "yi mushkil a:s"),
        ("यि मॅंग न आस", "yi məng na a:s"),
        ("तामिस मुस्कान चु बॅ", "tAm'is muska:n chu bə"),
        ("तिम शादि कर", "tim sha:di kar"),
        ("बि लॊक आस", "bi lOk a:s"),
        ("त्स दॅर आसि", "ts də:r a:si"),
        ("ति चु बॅ हुनर", "ti chu bə hunar"),
        ("मसल न आस", "masal na a:s"),
        ("स वदान", "s vada:n"),
    ],
    521: [
        ("बि गोस", "bI go:s"),
        ("सु आव", "su a:v"),
        ("बि कर", "bi kar"),
        ("त्स दित", "ts dit"),
        ("स लॅख", "s ləkh"),
        ("असि वुच", "asi vuch"),
        ("तिम ठाह", "tim Tha:h"),
        ("बि मिल", "bi mil"),
        ("सु बन", "su ban"),
        ("स हेक", "s hek"),
        ("बि पॅड", "bi pəD"),
        ("त्स गॅछ", "ts gəch"),
        ("सु आन", "su a:n"),
        ("असि भॅज", "asi bhəj"),
        ("तिम बनॅ", "tim banə"),
    ],
    522: [
        ("बि खान आस", "bi kha:n a:s"),
        ("त्स गतशान आसि", "ts gatsha:n a:si"),
        ("सु परान आस", "su para:n a:s"),
        ("स लेखान आस", "s le:kha:n a:s"),
        ("असि खेळान आसि", "asi khe:la:n a:si"),
        ("तिम कथ करान आसि", "tim kath kara:n a:si"),
        ("बि सोतान आस", "bi sota:n a:s"),
        ("त्स काम करान आसि", "ts ka:m kara:n a:si"),
        ("सु दोरान आस", "su do:ra:n a:s"),
        ("स बनान आस", "s bana:n a:s"),
        ("बि गतशान गोस", "bi gatsha:n go:s"),
        ("तिम वुचान आसि", "tim vucha:n a:si"),
        ("बि परान आस", "bi para:n a:s"),
        ("त्स बुजान आसि", "ts buza:n a:si"),
        ("सु प्रतीक्षा करान आस", "su prati:ksha: kara:n a:s"),
    ],
    523: [
        ("बि खाद", "bi kha:d"),
        ("त्स आयि", "ts a:yi"),
        ("सु गव", "su gav"),
        ("स पारिथ", "s pArith"),
        ("असि कर", "ami kar"),
        ("तिम नेर", "tim ner"),
        ("बि खाद आस", "bi kha:d a:s"),
        ("त्स वुच", "ts vuch"),
        ("ताम लिच", "tAm' li:ch"),
        ("त्स खाद?", "ts kha:d?"),
        ("बि खतम", "bi khatam"),
        ("स खतम", "s khatam"),
        ("तिम शादि कर", "tim sha:di kar"),
        ("बि लॅप", "bi ləp"),
        ("त्स फिकिरि तर", "ts phikiri tar"),
    ],
    524: [
        ("कर मंज़", "kar manz"),
        ("मेज़स पेठ", "me:zas peTh"),
        ("गरि पॅथ", "garI peTh"),
        ("बाज़ार", "ba:zar"),
        ("लड़किस", "la:r'kis"),
        ("म्यॅ सॅथ", "mə səth"),
        ("तुहन्द खात्रि", "tuhand khA:trI"),
        ("पगाह तॅ", "paga:h tə"),
        ("आब बॅ नॅ", "a:b bə nə"),
        ("यिथॅ", "yithə"),
        ("ब चुस कर मंज़", "b chus kar manz"),
        ("किताब चु मेज़स पेठ", "kita:b chu me:zas peTh"),
        ("तॅथॅ यिव", "təthə yiv"),
        ("स्टॅशन गच", "sṭe:shan gach"),
        ("यि तुहन्द खात्रि", "yi tuhand khA:trI"),
    ],
    525: [
        ("मे द्यिव", "me dyiv"),
        ("ब चुस स्कूल गतशान", "b chus sku:l gatsha:n"),
        ("म्योन कर यिव", "m'on kar yiv"),
        ("सवेरॅ तॅ शाम", "savərə tə sha:m"),
        ("स्टॅशन", "sṭe:shan"),
        ("तामिस द्यिव", "tAm'is dyiv"),
        ("तुहन्द भॅज", "tuhand bhəj"),
        ("मे तामिस आख", "me tAm'is a:kh"),
        ("बिहार मंज़ शुकुर", "biha:r manz shukur"),
        ("मे होटल गतॅ", "me ho:tel gatə"),
        ("एयरपोर्ट हुन रस्त", "eyarpo:r't hun rast"),
        ("यॅथॅ तॅ तॅथॅ", "yəthə tə təthə"),
        ("बि बाज़ार गतॅ गॅछ", "bi ba:zar gatə gəch"),
        ("बٕٛتٕس ख़त", "bə:ts khat"),
        ("पौधन खात्रि आब", "pau'dhan khA:trI a:b"),
    ],
    526: [
        ("मे त्स वुच", "me ts vuch"),
        ("त्स मे बुलाय", "ts me bula:y"),
        ("सु ताम सॅथ मिल", "su tAm səth mil"),
        ("स तामिस मदद कर", "s tAm'is madad kar"),
        ("असि तिमन बुलाय", "asi timan bula:y"),
        ("तिम असि पॅथॅ", "tim asi pəthə"),
        ("मे त्स पसंद", "me ts pasand"),
        ("तामिस आब द्यिव", "tAm'is a:b dyiv"),
        ("तामिस वन", "tAm'is van"),
        ("मास्टर पॅथ प्रुत्श", "ma:star pəth prutsh"),
        ("मे दक्तर गॅछ", "me da:ktar gəch"),
        ("पुलिस बुलॅाव", "pulIs bulə:v"),
        ("म्योन दोस्त मिल", "m'on do:st mil"),
        ("स मे पॅथॅ न", "s me pəthə na"),
        ("कٮ۪ बनॅ?", "kə' banə?"),
    ],
    527: [
        ("म्योन नाव", "m'on na:v"),
        ("तुहन्द कर", "tuhand kar"),
        ("तामिस किताब", "tAm'is kita:b"),
        ("तामिस दोस्त", "tAm'is do:st"),
        ("म्योन बٕٛتٕ", "m'on bə:z"),
        ("तुहन्द मاج", "tuhand ma:j"),
        ("अमार कर", "ama:r kar"),
        ("तामन ज़बान", "taman zaba:n"),
        ("यि म्योन किताब", "yi m'on kita:b"),
        ("ति तुहन्द कलम", "ti tuhand kalam"),
        ("तामिस आँख नील", "tAm'is a:~kh ni:l"),
        ("म्योन बॅहन चु नौकरी", "m'on bəhn chu naukari:"),
        ("तामिस नाव …", "tAm'is na:v …"),
        ("मे त्स च्योन याद", "me ts chyon ya:d"),
        ("तुहन्द मदद खात्रि शुक्रिया", "tuhand madad khA:trI shukriya"),
    ],
    528: [
        ("त्वहि क्या छु नाव?", "twahi kya ch'u naav?"),
        ("क्या स चु?", "kya sə chu?"),
        ("त्वहि कति छु?", "twahi kati chu?"),
        ("त्स कॅर आसिव?", "ts kər a:siv?"),
        ("तोहय छिवा वारय?", "tohy ch'ivaa vaarai?"),
        ("यि का’तिस छु?", "yi ka:tis ch'u?"),
        ("त्वहि क्या करान छु?", "twahi kya kara:n chu?"),
        ("सु मर्द कुस छु?", "su mard kus chu?"),
        ("टायलेट कति छु?", "ṭaaylet kati chu?"),
        ("त्स क्या गॅछ गोस?", "ts kya gəch go:s?"),
        ("क्यॅ?", "kyə?"),
        ("कच?", "kach?"),
        ("त्स्के छुके मैथिली बोलान?", "tske chhuke maithili bolaan?"),
        ("त्स मे मदद हेकिव?", "ts me madad hekiv?"),
        ("यि किस हुनर?", "yi kis hunar?"),
    ],
    529: [
        ("मे छु ने पै", "me chhu ne pai"),
        ("त्स फिकिरि न तरान", "ts phikiri na tara:n"),
        ("सु न खान", "su na kha:n"),
        ("स न गतश", "s na gatsh"),
        ("असि न गॅछ", "asi na gəch"),
        ("ना", "na:"),
        ("ब’ छुस न’ ज़ानान", "bi ch'us niu zaana:n"),
        ("ब चुस न मास्टर", "b chus na ma:star"),
        ("मसल नहीं", "masal nahi:"),
        ("फिकिर न कर", "fikir na kar"),
        ("मे चुने मैथिली तगान", "me chune maithili taga:n"),
        ("बि चुस न गोमुत मॅज", "bi chus na go:mut məj"),
        ("यि मॅंग न", "yi məng na"),
        ("बिल्कुल न!", "bilkul na!"),
        ("मे न गॅछ", "me na gəch"),
    ],
    530: [
        ("बि गोस न", "bi go:s na"),
        ("त्स आयि न", "ts a:yi na"),
        ("ताम हेक नी कथ", "tAm' hek nI kath"),
        ("स खाद न", "s kha:d na"),
        ("असि वुच न", "asi vuch na"),
        ("तिम ठाह न", "tim Tha:h na"),
        ("ज़रूरत न आस", "zaru:rat na a:s"),
        ("मॅंग न आस", "məng na a:s"),
        ("बि कर न", "bi kar na"),
        ("त्स मे वन न", "ts me van na"),
        ("सु दोर न", "su dor na"),
        ("स वद न", "s vad na"),
        ("बि आस न", "bi a:s na"),
        ("शक़ न आस", "shaq na a:s"),
        ("बि खाद न आस", "bi kha:d na a:s"),
    ],
    531: [
        ("बि न गत्शी", "bi na gatshi"),
        ("तोह न आसिव", "toh na a:siv"),
        ("सु न खाशि", "su na kha:shi"),
        ("स न करि", "s na kari"),
        ("असि न बिसरॅ", "asi na bisərə"),
        ("तिम न प्रतीक्षा", "tim na prati:ksha:"),
        ("बि न वन", "bi na van"),
        ("त्स न गॅछ", "ts na gəch"),
        ("ना, बि पॅतॅ खामि", "na:, bi pətə kh'ami"),
        ("बि हेक न यिव", "bi hek na yiv"),
        ("मत गच", "mat gach"),
        ("त्स न आसिव?", "ts na a:siv?"),
        ("रुद न पॅयि", "ru:d na peyi"),
        ("बि त्स न बिसरॅ", "bi ts na bisərə"),
        ("तिम न मानॅ", "tim na ma:nə"),
    ],
    532: [
        ("कर", "kar"),
        ("कार", "ka:r"),
        ("घोड़", "gho:r"),
        ("घोड़नी", "gho:rni"),
        ("लड़क", "la:r'k"),
        ("कॊड़", "kO:r"),
        ("लोक", "lo:k"),
        ("दोयि लोक", "doyi lo:k"),
        ("बुज़ किताब", "buz kita:b"),
        ("सारॅ बचॅ", "sa:rə bachə"),
        ("ति कर चु बड़", "ti kar chu ba:r"),
        ("तिमन थोड़ किताब", "timan tho:r kita:b"),
        ("म्योन बॅहन चु मॅशहूर", "m'on bəhn chu məshhu:r"),
        ("दरिया चु पॅथलाम", "dariya: chu pəthla:m"),
        ("ख़ूबसूरथ कॊड़", "khu:bsu:rath kO:r"),
    ],
    533: [
        ("कर मंज़", "kar manz"),
        ("रस्तॅ पेठ", "rastə peTh"),
        ("बाज़ार पॅथ", "ba:zar peTh"),
        ("स्कूल", "sku:l"),
        ("लड़किस किताब", "la:r'kis kita:b"),
        ("मास्टर सॅथ", "ma:star səth"),
        ("पैसॅ बॅ नॅ", "paisə bə nə"),
        ("बचॅस खात्रि", "bachəs khA:trI"),
        ("स्टॅशन तॅ", "sṭe:shan tə"),
        ("कमरॅ मंज़", "kamərə manz"),
        ("ब चुस कर मंज़", "b chus kar manz"),
        ("किताब चु मेज़स पेठ", "kita:b chu me:zas peTh"),
        ("बाज़ार पॅथ यिव", "ba:zar peTh yiv"),
        ("स्टॅशन गच", "sṭe:shan gach"),
        ("पौधन खात्रि आब", "pau'dhan khA:trI a:b"),
    ],
    534: [
        ("करिस", "karis"),
        ("यॅथॅ पॅथ", "yəthə peTh"),
        ("तामिस सॅथ", "tAm'is səth"),
        ("कमरॅ मंज़", "kamərə manz"),
        ("मेज़स पेठ", "me:zas peTh"),
        ("मे", "me"),
        ("तुहन्द खात्रि", "tuhand khA:trI"),
        ("अज़ तॅ", "az tə"),
        ("मॅशॅरॅ", "məshərə"),
        ("तामिस पॅथ", "tAm'is pəth"),
        ("तुहॅ बॅ नॅ", "tuhə bə nə"),
        ("दोयन मंज़", "doyan manz"),
        ("सवेरॅ पॅतॅ", "savərə pətə"),
        ("शाम ब्रोह", "sha:m bro:h"),
        ("यि मुतलॅक", "yi mutlək"),
    ],
    535: [
        ("लड़क (कर्ता)", "la:r'k (karta:)"),
        ("लड़कस", "la:r'kas"),
        ("लड़किस", "la:r'kis"),
        ("लड़क सॅथ", "la:r'k səth"),
        ("कर मंज़", "kar manz"),
        ("घोड़ॅ पेठ", "gho:rə peTh"),
        ("गरि पॅथ", "garI peTh"),
        ("ब (कर्ता)", "b (karta:)"),
        ("मे", "me"),
        ("म्योन", "m'on"),
        ("म्यॅ सॅथ", "mə səth"),
        ("मे तामिस किताब दित", "me tAm'is kita:b dit"),
        ("यि म्योन कर", "yi m'on kar"),
        ("कमरॅ मंज़ बुठ", "kamərə manz bu':Th"),
    ],
    536: [
        ("यिव!", "yiv!"),
        ("गच!", "gach!"),
        ("ठहर!", "ṭeuhar!"),
        ("बुज़!", "buz!"),
        ("मेहरबॅानी यिव अंदर", "meharba:ni yiv andar"),
        ("मेहरबॅानी द्यिव", "meharba:ni dyiv"),
        ("मेहरबॅानी वार’ वॅनिव", "meharba:ni vaariu veuniv"),
        ("मत गच", "mat gach"),
        ("मत वद", "mat vad"),
        ("मत रुस", "mat rus"),
        ("मे वुचॅ द्यिव", "me vuchə dyiv"),
        ("मे वनॅ द्यिव", "me vanə dyiv"),
        ("मदथ करिव!", "madath kariv!"),
        ("पुलिस बुलॅाविव!", "pulIs bulə:viv!"),
        ("मे अकॅला छोड़!", "me akəla: cho:r!"),
    ],
    537: [
        ("वॅन", "ven"),
        ("अज़", "az"),
        ("पगाह", "paga:h"),
        ("कॅल", "kəl"),
        ("सवेर", "savar"),
        ("दॊपहर", "dOpahar"),
        ("शाम", "sha:m"),
        ("शब", "shab"),
        ("दॊह", "dOh"),
        ("हफ़्ता", "haf'ta:"),
        ("महिना", "mahina:"),
        ("वॊर", "vOr"),
        ("वखेत क्या आव?", "vakhet kya a:v?"),
        ("पगाह यिव", "paga:h yiv"),
        ("बि पॅतॅ आस", "bi pətə a:s"),
    ],
    538: [
        ("मे तामिस खॅलाव", "me tAm'is khəla:v"),
        ("स सलीमस परान कराव", "s sAli:mas para:n kara:v"),
        ("करॅ गॅछ", "karə gəch"),
        ("मे तामिस लिखाव", "me tAm'is likha:v"),
        ("बचॅ खॅलाव", "bachə khəla:v"),
        ("सु काम करॅ गॅछ", "su ka:m karə gəch"),
        ("मे वुचॅ", "me vuchə"),
        ("मे वनॅ द्यिव", "me vanə dyiv"),
        ("बि त्स फिकिरि तरॅ दॅम", "bi ts phikiri tarə dəm"),
        ("स ताम भॅज", "s tAm bhəj"),
        ("गिरॅ दॅम", "girə dəm"),
        ("उठॅ दॅम", "uṭhə dəm"),
        ("पॅयॅ दॅम", "peyə dəm"),
        ("तिम असि प्रतीक्षा कराव", "tim asi prati:ksha: kara:v"),
        ("तामिस वदान मत करॅ", "tAm'is vada:n mat karə"),
    ],
    539: [
        ("ख़ूबसूरथ (म.)", "khu:bsu:rath (m.)"),
        ("ख़ूबसूरथ (ज.)", "khu:bsu:rath (z.)"),
        ("बड़ कर", "ba:r kar"),
        ("बड़ दार", "ba:r da:r"),
        ("म्योन किताब", "m'on kita:b"),
        ("म्योन कर", "m'on kar"),
        ("बॅ लड़क", "bə la:r'k"),
        ("बॅ कॊड़", "bə kO:r"),
        ("सफ़ॅद घोड़", "safəd gho:r"),
        ("कॊह कुकुर", "kOh kukur"),
        ("स च ख़ूबसूरथ", "s cha khu:bsu:rath"),
        ("सु च ज़ीत", "su chu zi:t"),
        ("ति कर चु बड़", "ti kar chu ba:r"),
        ("नव किताब", "nav kita:b"),
        ("बॅड मर्द", "bə:r mard"),
    ],
    540: [
        ("बि खाद", "bi kha:d"),
        ("त्स आयि", "ts a:yi"),
        ("सु गव", "su gav"),
        ("त्स खतम कर?", "ts khatam kar?"),
        ("बि खाद आस", "bi kha:d a:s"),
        ("स नेर आस", "s ner a:s"),
        ("असि कर अॅस", "asi kar əs"),
        ("तिम पहुंच अॅस", "tim pahu~ch əs"),
        ("बि फिकिरि तर", "bi phikiri tar"),
        ("त्स वुच", "ts vuch"),
        ("खाद पॅतॅ", "kha:d pətə"),
        ("यिव पॅतॅ", "yiv pətə"),
        ("बि खतम", "bi khatam"),
        ("स लिच", "s li:ch"),
        ("तिम खेळ", "tim khe:l"),
    ],
    541: [
        ("बि खान चलान", "bi kha:n cala:n"),
        ("त्स गतशान चलान", "ts gatsha:n cala:n"),
        ("सु परान चलान", "su para:n cala:n"),
        ("स काम करान चलान", "s ka:m kara:n cala:n"),
        ("असि प्रतीक्षा चलान", "asi prati:ksha: cala:n"),
        ("तिम खेळान चलान", "tim khe:la:n cala:n"),
        ("बि परान चलान आस", "bi para:n cala:n a:s"),
        ("त्स सोतान चलान आस", "ts sota:n cala:n a:s"),
        ("सु दोरान चलान आस", "su do:ra:n cala:n a:s"),
        ("सवेरॅ पॅतॅ बि प्रतीक्षा चलान", "savərə pətə bi prati:ksha: cala:n"),
        ("दो गण्टॅ पॅतॅ स बनान चलान", "do ga:ṇṭə pətə s bana:n cala:n"),
        ("बि सोचान चलान", "bi so:cha:n cala:n"),
        ("तिम कथ चलान आस", "tim kath cala:n a:s"),
        ("असि रोज़ि चलान अॅस", "asi ro:zi cala:n əs"),
        ("यि वॅकॅ लागॅ", "yi vəkə la:gə"),
    ],
    542: [
        ("ना", "na:"),
        ("न", "na"),
        ("मे न गॅछ", "me na gəch"),
        ("मे यि न गॅछ", "me yi na gəch"),
        ("ना, शुक्रिया", "na:, shukriya"),
        ("मे न गॅछ", "me na gəch"),
        ("गतॅ न गॅछ", "gatə na gəch"),
        ("तामिस न गॅछ", "tAm'is na gəch"),
        ("असि मसल न गॅछ", "asi masal na gəch"),
        ("मे दिलचस्पी न", "me dilchaspi: na"),
        ("ज़रूरत न", "zaru:rat na"),
        ("मसल नहीं", "masal nahi:"),
        ("मे हेक न किन", "me hek na kin"),
        ("त्स न करॅ", "ts na karə"),
        ("यि न गॅछ", "yi na gəch"),
    ],
}
