// Auto-generated from lesson JSON — Phrases & Words tabs
const KASHMIRI_PHRASES = {
  greetings_1: {
    name: "Greetings",
    color: "#2B6CB0",
    icon: "👋",
    phrases: [
      { en: "I read a book at home.", mr: "ब चुस किताब परान घरि", roman: "B chus kita:b para:n ghari", hint: "" },
      { en: "Give me a little milk.", mr: "मे द्यिव थोड़ दूध", roman: "Me dyiv tho:r du:d", hint: "" },
      { en: "I hear the rain.", mr: "ब चुस पानी हुन आवाज़", roman: "B chus pa:ni hun a:wa:z", hint: "" },
      { en: "They walk — plural.", mr: "तिम चि चलान", roman: "Tim chi chala:n", hint: "" },
      { en: "Short a versus long aa.", mr: "अ आ फ़र्क", roman: "A a: fark", hint: "" },
      { en: "Watch lip shape for sounds.", mr: "ओठ हुन आवाज़", roman: "Oṭh hun a:wa:z", hint: "" },
      { en: "I eat with my hand.", mr: "ब चुस हाथ सॅथ खॆवान", roman: "B chus ha:th səth khevaa:n", hint: "" },
      { en: "The garden is green.", mr: "बाग चु हिरॊ", roman: "Ba:g chu hiro", hint: "" },
      { en: "The fruit is ripe.", mr: "मेवॅ पाक", roman: "Meve pa:k", hint: "" },
      { en: "The shop is far.", mr: "दुकान दूर", roman: "Duka:n du:r", hint: "" },
      { en: "The hand is clean.", mr: "हाथ साफ", roman: "Ha:th sa:f", hint: "" },
      { en: "Happiness in the heart.", mr: "दिल मंज ख़ुशि", roman: "Dil manz khushi", hint: "" },
      { en: "Consonant क is ‘ka’.", mr: "क चु अक्षर", roman: "K chu akshar", hint: "" },
      { en: "Retroflex ट — tongue back.", mr: "ट चु ज़बान पॅथ", roman: "Ṭ chu zaba:n pəth", hint: "" },
      { en: "We study at home.", mr: "असि चि घरि शिकान", roman: "Asi chi ghari shika:n", hint: "" },
      { en: "She writes a letter.", mr: "स च चिट्ठी लेखान", roman: "S cha chiṭṭhi le:kha:n", hint: "" },
    ]
  },
  travel_1: {
    name: "Travel",
    color: "#38A169",
    icon: "🚌",
    phrases: [
      { en: "He goes to school.", mr: "सु चु स्कूल गतशान", roman: "Su chu sku:l gatsha:n", hint: "" },
      { en: "Children play in the yard.", mr: "लड़कि चि आंगन मंज खेळान", roman: "La:r'ki chi a:ngan manz khe:la:n", hint: "" },
      { en: "I eat — hear the verb ending.", mr: "ब चुस शाल खॆवान", roman: "B chus sha:l khevaa:n", hint: "" },
      { en: "I write — first person.", mr: "ब चुस लेखान", roman: "B chus le:kha:n", hint: "" },
      { en: "Retroflex ṭ is not dental t.", mr: "ट त अलग", roman: "Ṭ ta alag", hint: "" },
      { en: "Sanskrit words keep full vowels.", mr: "संस्कृत स्वर पूरॅ", roman: "Sanskrit swar pu:re", hint: "" },
      { en: "The apple is sweet.", mr: "सॅब चु मिठ", roman: "Səb chu miṭh", hint: "" },
      { en: "Listen to the song.", mr: "गीत आशुन", roman: "Gi:t a:shun", hint: "" },
      { en: "The road is broken.", mr: "रस्त टूट", roman: "Rast ṭu:ṭ", hint: "" },
      { en: "They built a house.", mr: "तिम बन घर", roman: "Tim ban ghar", hint: "" },
      { en: "The heart is kind.", mr: "दिल मेहरबान", roman: "Dil mehraba:n", hint: "" },
      { en: "The road is dusty.", mr: "रस्त धुळ", roman: "Rast dhuḷ", hint: "" },
      { en: "Write ख and say ‘kha’.", mr: "ख लिख आ उच्चार", roman: "Kha likh a: uchcha:r", hint: "" },
      { en: "Do not mix ट and त.", mr: "ट त मत मिलाव", roman: "Ṭ ta mat mila:v", hint: "" },
      { en: "They work in the city.", mr: "तिम चि शहर मंज काम करान", roman: "Tim chi shehar manz ka:m kara:n", hint: "" },
      { en: "We learn new words.", mr: "असि चि नव शब्द शिकान", roman: "Asi chi nav shabd shika:n", hint: "" },
    ]
  },
  food_1: {
    name: "Food",
    color: "#DD6B20",
    icon: "🍛",
    phrases: [
      { en: "She sings a song.", mr: "स च गीत गान", roman: "S cha gi:t ga:n", hint: "" },
      { en: "We learn Kashmiri step by step.", mr: "असि चि कॉशुर हलुई हलुई शिकान", roman: "Asi chi ko:shur halui halui shika:n", hint: "" },
      { en: "You drink — familiar.", mr: "त्स चुख आब चेवान", roman: "Ts chukh a:b ceva:n", hint: "" },
      { en: "You come — habit.", mr: "त्स चुख यिवान", roman: "Ts chukh yiva:n", hint: "" },
      { en: "Stress the last syllable.", mr: "अख़ीर ज़ोर", roman: "Akhi:r zor", hint: "" },
      { en: "Your name? (nasal sounds).", mr: "तुहन्द नाव क्या?", roman: "Tuhand na:v kya?", hint: "" },
      { en: "The lamp gives light.", mr: "दिवॊ दॅ उजाल", roman: "Divo de uja:l", hint: "" },
      { en: "Question paper is hard.", mr: "पेपर कठिन", roman: "Pe:par kathin", hint: "" },
      { en: "He crossed the bridge.", mr: "सु पार पुल", roman: "Su pa:r pul", hint: "" },
      { en: "I trust my friend.", mr: "मे भरोस म्योन दोस्त", roman: "Me bharo:s m'on do:st", hint: "" },
      { en: "We heard the news.", mr: "असि आश ख़बर", roman: "Asi a:sh khabar", hint: "" },
      { en: "Do not fear ghosts.", mr: "भूत खॅ न डर", roman: "Bhu:t khə na ḍar", hint: "" },
      { en: "Nasal अं needs nose sound.", mr: "अं चु नाक हुन आवाज़", roman: "Aṃ chu na:k hun a:wa:z", hint: "" },
      { en: "Practice conjuncts: स्त, क्त.", mr: "जोड़ अक्षर स्त क्त", roman: "Joṛ akshar st kt", hint: "" },
      { en: "You come every day.", mr: "त्स चुख हर रोज़ यिवान", roman: "Ts chukh har ro:z yiva:n", hint: "" },
      { en: "What time is it?", mr: "वख्त कति छु?", roman: "Vakht kati chu?", hint: "" },
    ]
  },
  daily_1: {
    name: "Daily life",
    color: "#805AD5",
    icon: "🏠",
    phrases: [
      { en: "We live in Kashmir.", mr: "असि चि कशीर मंज", roman: "Asi chi kashi:r manz", hint: "" },
      { en: "Birds sit on the tree.", mr: "परिंद चि रुख हुन बसान", roman: "Parind chi rukh hun basa:n", hint: "" },
      { en: "He reads — third person.", mr: "सु चु किताब परान", roman: "Su chu kita:b para:n", hint: "" },
      { en: "Say ka and kha clearly.", mr: "क ख साफ", roman: "K kha sa:f", hint: "" },
      { en: "Repeat after the teacher.", mr: "मॅश्टर पॅथ दोहराव", roman: "Məshṭar pəth dohra:v", hint: "" },
      { en: "My name is short.", mr: "म्योन नाव छु लॊट", roman: "M'on na:v chu loṭ", hint: "" },
      { en: "I feel cold wind.", mr: "मे लाग सर्द हवा", roman: "Me la:g sard hava:", hint: "" },
      { en: "The field is wide.", mr: "खॅत चौड़", roman: "Khət chauṛ", hint: "" },
      { en: "She bought a frock.", mr: "स ख़रीद फ्रॉक", roman: "S khari:d fro:k", hint: "" },
      { en: "It is not there.", mr: "तॊ न छु", roman: "To na chu", hint: "" },
      { en: "The field is green.", mr: "खॅत हिरॊ", roman: "Khət hiro", hint: "" },
      { en: "Happiness spreads at home.", mr: "घर मंज ख़ुशि", roman: "Ghar manz khushi", hint: "" },
      { en: "Combine क + अ to read क.", mr: "क अ मिलि क", roman: "K a mili ka", hint: "" },
      { en: "Letter र changes in clusters.", mr: "र जोड़ मंज बदल", roman: "R joṛ manz badal", hint: "" },
      { en: "We play in the evening.", mr: "असि चि शाम खेळान", roman: "Asi chi sha:m khe:la:n", hint: "" },
      { en: "Where do you live?", mr: "त्स कति रावान छुख?", roman: "Ts kati ra:va:n chukh?", hint: "" },
    ]
  },
  shopping_1: {
    name: "Shopping",
    color: "#D69E2E",
    icon: "🛒",
    phrases: [
      { en: "I see the moon.", mr: "ब चुस चन्द्र पखान", roman: "B chus chandra pakha:n", hint: "" },
      { en: "I write my name.", mr: "ब चुस म्योन नाव लेखान", roman: "B chus m'on na:v le:kha:n", hint: "" },
      { en: "She cooks — feminine.", mr: "स च खाना शिजान", roman: "S cha kha:na shija:n", hint: "" },
      { en: "Do not mix ta and tha.", mr: "त थ अलग", roman: "Ta tha alag", hint: "" },
      { en: "Kashmiri keeps its own sounds.", mr: "कॉशुर अलग", roman: "Ko:shur alag", hint: "" },
      { en: "Srinagar is the capital.", mr: "श्रीनगर छु राजधानि", roman: "Shri:nagar chu ra:jdha:ni", hint: "" },
      { en: "The road is long.", mr: "रस्त चु लंब", roman: "Rast chu lamb", hint: "" },
      { en: "The nation is great.", mr: "मुल्क मॊट", roman: "Mulk moṭ", hint: "" },
      { en: "We saw the film.", mr: "असि दॅख फिल्म", roman: "Asi de:kh film", hint: "" },
      { en: "I do not want it.", mr: "मे न चु", roman: "Me na chu", hint: "" },
      { en: "She held the baby.", mr: "स थाम बच्च", roman: "S tha:m bacca", hint: "" },
      { en: "Practice vowel अ — short ‘a’.", mr: "अ चु पॅहलॅ स्वर", roman: "A chu pəhlə swar", hint: "" },
      { en: "Read slowly: क ख ग.", mr: "हलुई वाच क ख ग", roman: "Halui va:k k kh g", hint: "" },
      { en: "Stress often falls on last syllable.", mr: "ज़ोर अख़ीर अक्षर", roman: "Zor akhi:r akshar", hint: "" },
      { en: "They walk on the road.", mr: "तिम चि रस्त पॅथ चलान", roman: "Tim chi rast pəth chala:n", hint: "" },
      { en: "I live in Srinagar.", mr: "ब चुस श्रीनगर मंज रावान", roman: "B chus Shri:nagar manz ra:va:n", hint: "" },
    ]
  },
  emergency_1: {
    name: "Emergency",
    color: "#E53E3E",
    icon: "🚨",
    phrases: [
      { en: "The house is near the road.", mr: "घर चु रस्त हुन नज़दीक", roman: "Ghar chu rast hun nazdi:k", hint: "" },
      { en: "Good people help others.", mr: "नेक लोक चि मदद करान", roman: "Nek lo:k chi madad kara:n", hint: "" },
      { en: "We learn — plural.", mr: "असि चि शिकान", roman: "Asi chi shika:n", hint: "" },
      { en: "Listen: pa versus pha.", mr: "प फ फ़र्क", roman: "P ph fark", hint: "" },
      { en: "Calm speech is clearer.", mr: "शांत उलाव साफ", roman: "Sha:nt ula:v sa:f", hint: "" },
      { en: "The bell rings at the mosque.", mr: "मस्जिद मंज घंटॅ वाज", roman: "Masjid manz ghaṇṭe va:j", hint: "" },
      { en: "My mind is calm.", mr: "म्योन दिमाग शांत", roman: "M'on dima:g sha:nt", hint: "" },
      { en: "The letter is short.", mr: "चिट्ठी लॊट", roman: "Chiṭṭhi loṭ", hint: "" },
      { en: "I need a ticket.", mr: "मे छु टिकट", roman: "Me chhu ṭikaṭ", hint: "" },
      { en: "The story is nice.", mr: "कहानि बरि", roman: "Kaha:ni bari", hint: "" },
      { en: "I washed my face.", mr: "ब धो मुँह", roman: "B dho mũh", hint: "" },
      { en: "Practice vowel आ — long ‘aa’.", mr: "आ चु दीर्घ", roman: "A: chu di:rgh", hint: "" },
      { en: "Barakhadi links vowels to consonants.", mr: "बाराखडी जोड़ अक्षर", roman: "Ba:ra:khaṛi joṛ akshar", hint: "" },
      { en: "He reads a book.", mr: "सु चु किताब परान", roman: "Su chu kita:b para:n", hint: "" },
      { en: "I see the lake.", mr: "ब चुस झील पखान", roman: "B chus jhi:l pakha:n", hint: "" },
      { en: "I will come tomorrow.", mr: "ब यिम सुबह", roman: "B yim subah", hint: "" },
    ]
  },
};

const KASHMIRI_DICTIONARY = {
  basics_1: {
    name: "Basic words",
    words: [
      { en: "You drink water.", mr: "त्स चुख आब चेवान", roman: "Ts chukh a:b ceva:n" },
      { en: "The sun rises.", mr: "सूरज चु उगान", roman: "Su:r'aj chu uga:n" },
      { en: "We play.", mr: "असि चि खेळान", roman: "Asi chi khe:la:n" },
      { en: "He opens.", mr: "सु चु खोलान", roman: "Su chu khola:n" },
      { en: "I thank.", mr: "ब चुस शुक्रिया", roman: "B chus shukriya" },
      { en: "Practice every morning.", mr: "हर सुबह सराव", roman: "Har subah sarav" },
      { en: "We sing hymns.", mr: "असि गाव भजन", roman: "Asi ga:v bhajan" },
      { en: "Picture is clear.", mr: "तस्वीर साफ", roman: "Tasvi:r sa:f" },
      { en: "Trust is important.", mr: "भरोस ज़रूरी", roman: "Bharo:s zaru:ri" },
      { en: "The officer came.", mr: "ऑफिसर आय", roman: "O:fisar a:y" },
      { en: "The train arrived.", mr: "ट्रेन आय", roman: "Tre:n a:y" },
      { en: "The bus stopped.", mr: "बस थांब", roman: "Bas tha:mb" },
      { en: "Spring has come.", mr: "बहार आय", roman: "Baha:r a:y" },
      { en: "Breath is steady.", mr: "साँस थिर", roman: "Sã:s thir" },
      { en: "I (speaker, masc.)", mr: "ब", roman: "B" },
      { en: "We", mr: "असि", roman: "Asi" },
    ]
  },
  family_1: {
    name: "Family",
    words: [
      { en: "They work hard.", mr: "तिम चि मेहनत करान", roman: "Tim chi mehnat kara:n" },
      { en: "Close the window.", mr: "खिड़की बंद कर", roman: "Khi:r'ki band kar" },
      { en: "They work.", mr: "तिम चि काम करान", roman: "Tim chi ka:m kara:n" },
      { en: "She closes.", mr: "स च बंद करान", roman: "S cha band kara:n" },
      { en: "You help.", mr: "त्स चुख मदद", roman: "Ts chukh madad" },
      { en: "Ask if unsure.", mr: "शक हॅ तॊ पूछ", roman: "Shak hə to pu:ch" },
      { en: "The child runs.", mr: "बच्च दोर", roman: "Bacca dor" },
      { en: "Victory is ours.", mr: "ज़ित अमार", roman: "Zit ama:r" },
      { en: "The story spread.", mr: "कहानि फैल", roman: "Kaha:ni fail" },
      { en: "The student passed.", mr: "तॅलिम पास", roman: "Təlim pa:s" },
      { en: "I like cricket.", mr: "मे आव क्रिकॅट", roman: "Me a:v krikeṭ" },
      { en: "The child cried.", mr: "बच्च रोव", roman: "Bacca ro:v" },
      { en: "Laugh a little.", mr: "थोड़ हँस", roman: "Tho:r hãs" },
      { en: "He sighed deeply.", mr: "स लंब साँस", roman: "S lamb sã:s" },
      { en: "You (singular)", mr: "त्स", roman: "Ts" },
      { en: "You (plural / respect)", mr: "तिम", roman: "Tim" },
    ]
  },
  verbs_1: {
    name: "Common verbs",
    words: [
      { en: "Open the door.", mr: "दरवाज़ खोल", roman: "Darva:z khol" },
      { en: "He sleeps.", mr: "सु चु सोतान", roman: "Su chu sota:n" },
      { en: "I see.", mr: "ब चुस पखान", roman: "B chus pakha:n" },
      { en: "We meet.", mr: "असि चि मिलान", roman: "Asi chi mila:n" },
      { en: "Anusvara changes tone.", mr: "अं सॅथ आवाज़", roman: "Aṃ səth a:wa:z" },
      { en: "Kashmir is beautiful.", mr: "कशीर छु सॊन्द", roman: "Kashi:r chu sond" },
      { en: "Student reads.", mr: "तॅलिम चु परान", roman: "Təlim chu para:n" },
      { en: "Effort brings success.", mr: "मेहनत सॅथ कामयाबि", roman: "Mehnat səth ka:ma:ya:bi" },
      { en: "Practice makes perfect.", mr: "सराव सॅथ सही", roman: "Sara:v səth sahi:" },
      { en: "The nation celebrates.", mr: "मुल्क मनाव", roman: "Mulk mana:v" },
      { en: "Come back soon.", mr: "फिर लवकर यि", roman: "Phir lavkar yi" },
      { en: "We reached home.", mr: "असि पहुँच घर", roman: "Asi pahuñch ghar" },
      { en: "Cold water.", mr: "थंड आब", roman: "Thaṇḍ a:b" },
      { en: "Read aloud: घर.", mr: "उच्चार घर", roman: "Uchcha:r ghar" },
      { en: "He / that man", mr: "सु", roman: "Su" },
      { en: "They", mr: "तिम", roman: "Tim" },
    ]
  },
  nature_1: {
    name: "Nature",
    words: [
      { en: "Speak slowly.", mr: "हलुई उलाव", roman: "Halui ula:v" },
      { en: "She sings.", mr: "स च गान", roman: "S cha ga:n" },
      { en: "You listen.", mr: "त्स चुख आशुन", roman: "Ts chukh a:shun" },
      { en: "They wait.", mr: "तिम चि ठाहान", roman: "Tim chi Tha:ha:n" },
      { en: "Read slowly first.", mr: "पॅहलॅ हलुई", roman: "Pəhle halui" },
      { en: "Evening prayer time.", mr: "शाम नमाज़ वख्त", roman: "Sha:m nama:z vakht" },
      { en: "Temple looks fine.", mr: "मंदिर बरो", roman: "Mandir baro" },
      { en: "Science helps life.", mr: "साइंस मदद ज़िंदगि", roman: "Sa:ĩns madad zindagi" },
      { en: "The machine works.", mr: "मशीन चल", roman: "Mashi:n chal" },
      { en: "We pray together.", mr: "असि एकठॅ प्रार्थना", roman: "Asi ekathe pra:rthana:" },
      { en: "The price fell.", mr: "दाम घट", roman: "Da:m ghaṭ" },
      { en: "The star shines.", mr: "तारॅ चमक", roman: "Ta:re chamak" },
      { en: "Speak the truth.", mr: "सच उलाव", roman: "Sach ula:v" },
      { en: "Read aloud: नमस्तॅ.", mr: "उच्चार नमस्ते", roman: "Uchcha:r namaste" },
      { en: "She / that woman", mr: "स", roman: "S" },
      { en: "This", mr: "यि", roman: "Yi" },
    ]
  },
};
