# Curated Kashmiri triples [English, Devanagari, Roman] for lesson assembly.
# Sources: O. N. Koul (grammatical sketch), koshur.org learner materials, Omniglot / phrasebook patterns;
# Devanagari orthography as used in Kashmiri-in-Devanagari primers.

from kashmiri_targeted_banks import TARGET_BANK_REGISTRY

def target_row_count(chapter_id: int) -> int:
    return 15 + (chapter_id % 6)

ROWS_PER_LESSON = 18

GREETINGS = [
    ("Peace be upon you (Islamic greeting).", "अस्सलामु अलैकुम", "Assalaamu alaikum"),
    ("How are you? (to one person)", "तोहय छिवा वारय?", "Tohy ch'ivaa vaarai?"),
    ("I am fine.", "मे छु ठीक", "Me chhu thi:k"),
    ("My name is …", "मे छु नाव …", "Me chhu naav …"),
    ("What is your name?", "त्वहि क्या छु नाव?", "Twahi kya ch'u naav?"),
    ("Thank you.", "शुक्रिया", "Shukriya"),
    ("Please / have kindness.", "मेहरबानी", "Meharba:ni"),
    ("Good morning.", "सुप्रभात", "Suprabha:t"),
    ("Good night.", "शुभ रात्रि", "Shubh ra:tri"),
    ("Welcome.", "इस्तक़्बाल", "Istiqba:l"),
    ("See you again.", "फिर मिलन", "Phir milan"),
    ("Nice to meet you.", "मिलन ख़ुशी आस", "Milan khushi a:s"),
    ("Congratulations.", "मुबारक", "Muba:rak"),
    ("Happy Eid.", "ईद मुबारक", "I:d Muba:rak"),
    ("Goodbye.", "ख़ुदा हाफ़िज़", "Khuda: ha:fiz"),
    ("I am glad.", "मे छु ख़ुश", "Me chhu kh>sh"),
    ("You are kind.", "त्स छुख मेहरबान", "Ts chukh mehraba:n"),
    ("Many thanks.", "बहुत शुक्रिया", "Bahut shukriya"),
    ("God willing.", "इंशा अल्लाह", "Inshaa alla:h"),
    ("Bless you.", "ख़ुदा सलामत रखे", "Khuda: sala:mat rakhe"),
    ("Respectful greeting to elders.", "आदाब", "Ada:b"),
    ("I respect you.", "मे कर तुहन्द इज़्ज़त", "Me kar tuhand izzat"),
]

READING_DRILLS = [
    ("I read a book at home.", "ब चुस किताब परान घरि", "B chus kita:b para:n ghari"),
    ("You drink water.", "त्स चुख आब चेवान", "Ts chukh a:b ceva:n"),
    ("He goes to school.", "सु चु स्कूल गतशान", "Su chu sku:l gatsha:n"),
    ("She sings a song.", "स च गीत गान", "S cha gi:t ga:n"),
    ("We live in Kashmir.", "असि चि कशीर मंज", "Asi chi kashi:r manz"),
    ("They work hard.", "तिम चि मेहनत करान", "Tim chi mehnat kara:n"),
    ("I see the moon.", "ब चुस चन्द्र पखान", "B chus chandra pakha:n"),
    ("Open the door.", "दरवाज़ खोल", "Darva:z khol"),
    ("The house is near the road.", "घर चु रस्त हुन नज़दीक", "Ghar chu rast hun nazdi:k"),
    ("Give me a little milk.", "मे द्यिव थोड़ दूध", "Me dyiv tho:r du:d"),
    ("Children play in the yard.", "लड़कि चि आंगन मंज खेळान", "La:r'ki chi a:ngan manz khe:la:n"),
    ("We learn Kashmiri step by step.", "असि चि कॉशुर हलुई हलुई शिकान", "Asi chi ko:shur halui halui shika:n"),
    ("Speak slowly.", "हलुई उलाव", "Halui ula:v"),
    ("The sun rises.", "सूरज चु उगान", "Su:r'aj chu uga:n"),
    ("Birds sit on the tree.", "परिंद चि रुख हुन बसान", "Parind chi rukh hun basa:n"),
    ("I write my name.", "ब चुस म्योन नाव लेखान", "B chus m'on na:v le:kha:n"),
    ("Close the window.", "खिड़की बंद कर", "Khi:r'ki band kar"),
    ("Good people help others.", "नेक लोक चि मदद करान", "Nek lo:k chi madad kara:n"),
    ("I hear the rain.", "ब चुस पानी हुन आवाज़", "B chus pa:ni hun a:wa:z"),
    ("She cooks food with love.", "स च खाना शिजान मोहब्बत सॅथ", "S cha kha:na shija:n mohabbat səth"),
    ("We shall meet tomorrow.", "असि फिर सुबह मिली", "Asi phir subah mili"),
]

DAILY = [
    ("What time is it?", "वख्त कति छु?", "Vakht kati chu?"),
    ("Where do you live?", "त्स कति रावान छुख?", "Ts kati ra:va:n chukh?"),
    ("I live in Srinagar.", "ब चुस श्रीनगर मंज रावान", "B chus Shri:nagar manz ra:va:n"),
    ("I must go home.", "मे घर गचुन", "Me ghar gachun"),
    ("Come here.", "यि यिव", "Yi yiv"),
    ("Sit down.", "बस", "Bas"),
    ("Open the door.", "दरवाज़ खोल", "Darva:z khol"),
    ("Today is a holiday.", "आज चु छुट्टी", "A:j chu chuṭṭi"),
    ("Tomorrow I will come.", "सुबह ब यिम", "Subah b yim"),
    ("Yesterday was good.", "कल चु बरो आस", "Kal chu baro a:s"),
    ("I am tired.", "ब चुस थकावट", "B chus thaka:vat"),
    ("Let us go.", "गच", "Gach"),
    ("I am going to work.", "ब चुस काम करान", "B chus ka:m kara:n"),
    ("Close the window.", "खिड़की बंद कर", "Khi:r'ki band kar"),
    ("It is cold today.", "आज चु सर्द", "A:j chu sard"),
    ("I need rest.", "मे कर विश्राम", "Me kar vishra:m"),
    ("The bus is late.", "बस चु देर", "Bas chu der"),
    ("I forgot.", "बि बिसर", "Bi bisar"),
    ("Wait a moment.", "थोड़ वख्त ठाह", "Tho:r vakht Tha:h"),
    ("Everything is fine.", "सब ठीक", "Sab thi:k"),
    ("I am busy.", "ब चुस मशगूल", "B chus mashgu:l"),
]

FOOD = [
    ("I am hungry.", "मे छु भूख", "Me chhu bhu:kh"),
    ("Give me water.", "मे द्यिव आब", "Me dyiv a:b"),
    ("The food is tasty.", "खाना चु लज़ीज़", "Kha:na chu laziz"),
    ("I want tea.", "मे छु चाय", "Me chhu cha:y"),
    ("The food is spicy.", "खाना चु तीख", "Kha:na chu ti:kh"),
    ("I do not eat meat.", "ब चुस न मास खान", "B chus na ma:s kha:n"),
    ("What is this dish?", "यि क्या चु?", "Yi kya chu?"),
    ("I want to eat.", "मे छु खान", "Me chhu kha:n"),
    ("Enough food.", "बस खाना", "Bas kha:na"),
    ("I want rice.", "मे छु शाल", "Me chhu sha:l"),
    ("Bring the bill.", "बिल आन", "Bill a:n"),
    ("More food, please.", "मेहरबानी सॅथ होर खाना", "Meharba:ni səth hor kha:na"),
    ("The food is sweet.", "खाना चु मिठ", "Kha:na chu miṭh"),
    ("Give me bread.", "मे द्यिव रोटि", "Me dyiv ro:ṭi"),
    ("I want coffee.", "मे छु कॉफी", "Me chhu ko:fi"),
    ("I am vegetarian.", "ब चुस शाकाहारी", "B chus sha:ka:ha:ri"),
    ("I am thirsty.", "मे छु तिश्नगी", "Me chhu tishnagi:"),
    ("The tea is hot.", "चाय चु गरम", "Cha:y chu garam"),
]

PRONOUNS = [
    ("I (speaker, masc.)", "ब", "B"),
    ("You (singular)", "त्स", "Ts"),
    ("He / that man", "सु", "Su"),
    ("She / that woman", "स", "S"),
    ("We", "असि", "Asi"),
    ("You (plural / respect)", "तिम", "Tim"),
    ("They", "तिम", "Tim"),
    ("This", "यि", "Yi"),
    ("That", "ति", "Ti"),
    ("My", "म्योन", "M'on"),
    ("Your", "तुहन्द", "Tuhand"),
    ("Our", "अमार", "Ama:r"),
    ("Their", "तामन", "Taman"),
    ("Who?", "कुस?", "Kus?"),
    ("What?", "क्या?", "Kya?"),
    ("Where?", "कति?", "Kati?"),
    ("When?", "कति वख्त?", "Kati vakht?"),
    ("Why?", "क्या खात्रि?", "Kya kha:tri?"),
]

PRESENT = [
    ("I eat rice.", "ब चुस शाल खॆवान", "B chus sha:l khevaa:n"),
    ("You speak Kashmiri.", "त्स चुख कॉशुर बोलान", "Ts chukh ko:shur bola:n"),
    ("He reads a book.", "सु चु किताब परान", "Su chu kita:b para:n"),
    ("She cooks food.", "स च खाना शिजान", "S cha kha:na shija:n"),
    ("We study at home.", "असि चि घरि शिकान", "Asi chi ghari shika:n"),
    ("They work in the city.", "तिम चि शहर मंज काम करान", "Tim chi shehar manz ka:m kara:n"),
    ("I drink water.", "ब चुस आब पान", "B chus a:b pa:n"),
    ("You come every day.", "त्स चुख हर रोज़ यिवान", "Ts chukh har ro:z yiva:n"),
    ("He goes to school.", "सु चु स्कूल गतशान", "Su chu sku:l gatsha:n"),
    ("She sings well.", "स च बरो गान", "S cha baro ga:n"),
    ("We play in the evening.", "असि चि शाम खेळान", "Asi chi sha:m khe:la:n"),
    ("They walk on the road.", "तिम चि रस्त पॅथ चलान", "Tim chi rast pəth chala:n"),
    ("I see the lake.", "ब चुस झील पखान", "B chus jhi:l pakha:n"),
    ("You listen carefully.", "त्स चुख लक्ष दितॅ आशुन", "Ts chukh laksh dite a:shun"),
    ("He sleeps early.", "सु चु लवकर सोतान", "Su chu lavkar sota:n"),
    ("She writes a letter.", "स च चिट्ठी लेखान", "S cha chiṭṭhi le:kha:n"),
    ("We learn new words.", "असि चि नव शब्द शिकान", "Asi chi nav shabd shika:n"),
]

PAST = [
    ("I went home.", "ब गय घर", "B gay ghar"),
    ("You ate food.", "त्स खाद खाना", "Ts kha:d kha:na"),
    ("He came yesterday.", "सु आय कल", "Su a:y kal"),
    ("She spoke Kashmiri.", "स बोल कॉशुर", "S bol ko:shur"),
    ("We saw the mosque.", "असि दॅख मस्जिद", "Asi de:kh masjid"),
    ("They bought vegetables.", "तिम ख़रीद सब्ज़ि", "Tim khari:d sabzi"),
    ("I drank milk.", "ब पिय दूध", "B piy du:d"),
    ("You slept late.", "त्स सुत देर", "Ts sut der"),
    ("He wrote a letter.", "स लिख चिट्ठी", "S likh chiṭṭhi"),
    ("She opened the door.", "स खोल दरवाज़", "S khol darva:z"),
    ("We finished work.", "असि खतम काम", "Asi khatam ka:m"),
    ("They returned home.", "तिम वापस घर", "Tim va:pas ghar"),
    ("I was in Srinagar.", "ब आस श्रीनगर", "B a:s Shri:nagar"),
    ("It rained yesterday.", "कल पड़ पानी", "Kal paṛ pa:ni"),
    ("You helped me.", "त्स मदद मे", "Ts madad me"),
    ("He forgot the key.", "स बिसर चाबि", "S bisar cha:bi"),
    ("She liked the song.", "स पसंद गीत", "S pasand gi:t"),
]

FUTURE = [
    ("I will come tomorrow.", "ब यिम सुबह", "B yim subah"),
    ("You will eat later.", "त्स खाशि पतॅ", "Ts kha:shi pate"),
    ("He will go to school.", "स गत्श स्कूल", "S gatsh sku:l"),
    ("She will cook rice.", "स शिजाव शाल", "S shija:v sha:l"),
    ("We will meet again.", "असि मिल फिर", "Asi mil phir"),
    ("They will buy fruit.", "तिम ख़रीद मेवॅ", "Tim khari:d meve"),
    ("I will call you.", "ब फोन कर त्स", "B fon kar ts"),
    ("You will feel better.", "त्स ठीक यिव", "Ts thi:k yiv"),
    ("He will read the book.", "स पर किताब", "S par kita:b"),
    ("She will sing a song.", "स गाव गीत", "S ga:v gi:t"),
    ("We will travel to Jammu.", "असि सफर जम्मू", "Asi safar Jammu"),
    ("They will wait here.", "तिम ठाह यि", "Tim Tha:h yi"),
    ("I will learn Kashmiri.", "ब शिक कॉशुर", "B shik ko:shur"),
    ("You will understand.", "त्स समझ", "Ts samajh"),
    ("He will help us.", "स मदद असि", "S madad asi"),
    ("She will bring water.", "स आन आब", "S a:n a:b"),
    ("We will start now.", "असि शुरू कर आज़ि", "Asi shuru: kar a:zi"),
]

QUESTIONS = [
    ("What is this?", "यि क्या छु?", "Yi kya chu?"),
    ("Where is the bus?", "बस कति छु?", "Bas kati chu?"),
    ("When will you come?", "त्स कति यिव?", "Ts kati yiv?"),
    ("Why are you late?", "त्स देर क्या खात्रि?", "Ts der kya kha:tri?"),
    ("Who is he?", "सु कुस छु?", "Su kus chu?"),
    ("How much is this?", "यि कति दाम?", "Yi kati da:m?"),
    ("Which book?", "कुस किताब?", "Kus kita:b?"),
    ("Is this yours?", "यि तुहन्द?", "Yi tuhand?"),
    ("Can you help?", "त्स मदद कर हेकिव?", "Ts madad kar hekiv?"),
    ("Do you understand?", "त्स समझ?", "Ts samajh?"),
    ("Will you come?", "त्स यिव?", "Ts yiv?"),
    ("Did you eat?", "त्स खाद?", "Ts kha:d?"),
    ("Where do you work?", "त्स कति काम करान छुख?", "Ts kati ka:m kara:n chukh?"),
    ("What is your name?", "त्वहि क्या छु नाव?", "Twahi kya ch'u naav?"),
    ("How are you?", "तोहय छिवा वारय?", "Tohy ch'ivaa vaarai?"),
    ("May I sit?", "मे बस हेक?", "Me bas hek?"),
    ("Could you repeat?", "त्स फिर उलाव?", "Ts phir ula:v?"),
]

NEGATIVE = [
    ("I do not know.", "मे छु न' पय", "Me chhu ne pai"),
    ("I will not go.", "ब न गच", "B na gach"),
    ("You should not worry.", "त्स फिकिर न कर", "Ts fikir na kar"),
    ("He did not come.", "स न आय", "Su na a:y"),
    ("She is not here.", "स न यि", "S na yi"),
    ("We have no time.", "असि वख्त न", "Asi vakht na"),
    ("They are not ready.", "तिम तैयार न", "Tim taiya:r na"),
    ("I do not want this.", "मे न चु यि", "Me na chu yi"),
    ("Do not run.", "न दोर", "Na dor"),
    ("I never lie.", "ब न कर झूठ", "B na kar jhu:ṭh"),
    ("Nothing is wrong.", "कुछ गलत न", "Kuch galat na"),
    ("He does not eat meat.", "स न खान मास", "Su na kha:n ma:s"),
    ("She cannot swim.", "स न हेक तैराव", "S na hek taira:v"),
    ("We did not see him.", "असि न दॅख सु", "Asi na de:kh su"),
    ("They will not leave.", "तिम न वच", "Tim na vach"),
    ("I am not angry.", "ब न छु गुस्स", "B na chu guss"),
    ("This is not mine.", "यि म्योन न", "Yi m'on na"),
]

POSSESSION = [
    ("I have a book.", "मे छु किताब", "Me chhu kita:b"),
    ("Do you have money?", "त्स छु पैसॅ?", "Ts chhu paise?"),
    ("She has two brothers.", "स छि दोय भ्रात", "S chi doy bhra:t"),
    ("We have time today.", "असि छि वख्त आज", "Asi chi vakht a:j"),
    ("They have a new car.", "तिम छि नव कार", "Tim chi nav ka:r"),
    ("I have a headache.", "मे छु सर दुख", "Me chhu sar dukh"),
    ("He has no fear.", "स न छु डर", "Su na chu ḍar"),
    ("My house is small.", "म्योन घर छु लॊट", "M'on ghar chu loṭ"),
    ("Your idea is good.", "तुहन्द ख़्याल छु बरो", "Tuhand khya:l chu baro"),
    ("Our school is near.", "अमार स्कूल छु नज़दीक", "Ama:r sku:l chu nazdi:k"),
    ("Their shop is closed.", "तामन दुकान बंद", "Taman duka:n band"),
    ("I need help.", "मे कर मदद", "Me kar madad"),
    ("She needs rest.", "स कर विश्राम", "S kar vishra:m"),
    ("We need water.", "असि कर आब", "Asi kar a:b"),
    ("I have finished work.", "मे खतम काम", "Me khatam ka:m"),
    ("Do you have change?", "त्स छु खुल्ला?", "Ts chhu khulla?"),
    ("He has many friends.", "स छु बॊहुत दोस्त", "Su chu bohut do:st"),
]

SCRIPT_PRONUNCIATION = [
    ("Practice vowel अ — short ‘a’.", "अ चु पॅहलॅ स्वर", "A chu pəhlə swar"),
    ("Practice vowel आ — long ‘aa’.", "आ चु दीर्घ", "A: chu di:rgh"),
    ("Consonant क is ‘ka’.", "क चु अक्षर", "K chu akshar"),
    ("Write ख and say ‘kha’.", "ख लिख आ उच्चार", "Kha likh a: uchcha:r"),
    ("ग is voiced ‘ga’.", "ग चु मध्य", "G chu madhya"),
    ("Nasal अं needs nose sound.", "अं चु नाक हुन आवाज़", "Aṃ chu na:k hun a:wa:z"),
    ("Combine क + अ to read क.", "क अ मिलि क", "K a mili ka"),
    ("Read slowly: क ख ग.", "हलुई वाच क ख ग", "Halui va:k k kh g"),
    ("Barakhadi links vowels to consonants.", "बाराखडी जोड़ अक्षर", "Ba:ra:khaṛi joṛ akshar"),
    ("Retroflex ट — tongue back.", "ट चु ज़बान पॅथ", "Ṭ chu zaba:n pəth"),
    ("Do not mix ट and त.", "ट त मत मिलाव", "Ṭ ta mat mila:v"),
    ("Practice conjuncts: स्त, क्त.", "जोड़ अक्षर स्त क्त", "Joṛ akshar st kt"),
    ("Letter र changes in clusters.", "र जोड़ मंज बदल", "R joṛ manz badal"),
    ("ह at end of cluster is soft.", "ह अखर मंज नरम", "H akhar manz naram"),
    ("Read aloud: घर.", "उच्चार घर", "Uchcha:r ghar"),
    ("Read aloud: नमस्तॅ.", "उच्चार नमस्ते", "Uchcha:r namaste"),
    ("Stress often falls on last syllable.", "ज़ोर अख़ीर अक्षर", "Zor akhi:r akshar"),
]

SHOPPING = [
    ("How much is this?", "यि कति दाम?", "Yi kati da:m?"),
    ("That is too expensive.", "तो महंग", "To mahang"),
    ("Give me a discount.", "कम दाम कर", "Kam da:m kar"),
    ("I want to buy this.", "मे छु यि ख़रीद", "Me chhu yi khari:d"),
    ("Where is the shop?", "दुकान कति छु?", "Duka:n kati chu?"),
    ("Pack it well.", "बरो बॊरि", "Baro bo:ri"),
    ("I need fresh vegetables.", "मे छु ताज़ सब्ज़ि", "Me chhu ta:z sabzi"),
    ("One kilo, please.", "एक किलो मेहरबानी", "Ek kilo mehraba:ni"),
    ("Do you take cards?", "कार्ड लॅछिव?", "Ka:rḍ ləchiv?"),
    ("Give me the bag.", "मे द्यिव थैलि", "Me dyiv the:li"),
    ("This quality is good.", "यि माल चु बरो", "Yi ma:l chu baro"),
    ("I will come again.", "ब फिर यिम", "B phir yim"),
    ("Show me that one.", "तो दॅखाव", "To de:kha:v"),
    ("Any other colour?", "बॅ कुछ रंग?", "Bə kuch rang?"),
    ("Keep the change.", "खुल्ला रख", "Khulla rakh"),
    ("Is there a sale?", "सॅल छु?", "Sel chu?"),
    ("I like this cloth.", "मे आव यि कपड़", "Me a:v yi kapaṛ"),
]

HEALTH = [
    ("I need a doctor.", "मे दक्तर", "Me da:ktar"),
    ("Where is the hospital?", "हॉस्पिटल कति?", "Ho:sṭital kati?"),
    ("I have a fever.", "मे छु बुखार", "Me chhu bukha:r"),
    ("My head hurts.", "म्योन सर दुख", "M'on sar dukh"),
    ("My stomach hurts.", "म्योन पेट दुख", "M'on peṭ dukh"),
    ("Please help me.", "मेहरबानी मदद", "Meharba:ni madad"),
    ("Call an ambulance.", "एम्बुलन्स बुलाव", "Embulans bula:v"),
    ("I need medicine.", "मे छु दवा", "Me chhu dava:"),
    ("I am not feeling well.", "मे न छु ठीक", "Me na chu thi:k"),
    ("Rest for a day.", "एक दिन आराम", "Ek din a:ra:m"),
    ("Drink more water.", "होर आब पी", "Hor a:b pi"),
    ("Take this tablet.", "यि गोळि खा", "Yi goḷi kha:"),
    ("When did it start?", "कति शुरू?", "Kati shuru:?"),
    ("Do you have pain here?", "यि दुख?", "Yi dukh?"),
    ("I feel better now.", "आज़ि मे ठीक", "A:zi me thi:k"),
    ("She is recovering.", "स ठीक यिव", "S thi:k yiv"),
    ("We will wait outside.", "असि बाहर ठाह", "Asi ba:har Tha:h"),
]

TRAVEL = [
    ("Where is the bus stop?", "बस स्टॉप कति?", "Bas sṭo:p kati?"),
    ("One ticket to Srinagar.", "श्रीनगर एक टिकट", "Shri:nagar ek ṭikaṭ"),
    ("When does the bus leave?", "बस कति निकल?", "Bas kati nikal?"),
    ("Stop here, please.", "यि थांब मेहरबानी", "Yi tha:mb mehraba:ni"),
    ("How far is the lake?", "झील कति दूर?", "Jhi:l kati du:r?"),
    ("I am lost.", "ब गॅब रस्त", "B gəb rast"),
    ("Turn left.", "खबि वल", "Khabi val"),
    ("Turn right.", "रॅह वल", "Rəh val"),
    ("Go straight.", "सीध रव", "Si:dh rav"),
    ("Is this the right road?", "यि सही रस्त?", "Yi sahi: rast?"),
    ("Call a taxi.", "टॅक्सी बुलाव", "Ṭe:ksi bula:v"),
    ("The train is late.", "ट्रेन देर", "Tre:n der"),
    ("I need an auto.", "मे छु ऑटो", "Me chhu o:ṭo"),
    ("Drop me at the hotel.", "होटॅल सॅथ उतार", "Ho:tel səth uta:r"),
    ("How much is the fare?", "भाड़ा कति?", "Bha:ṛa kati?"),
    ("Keep the ticket.", "टिकट रख", "Ṭikaṭ rakh"),
    ("Where is the airport?", "हवाई अड्डा कति?", "Hava:i aḍḍa kati?"),
]

BODY = [
    ("My head hurts today.", "आज म्योन सर दुख", "A:j m'on sar dukh"),
    ("Open your eyes.", "अख खोल", "Akh khol"),
    ("Wash your hands.", "हाथ धो", "Ha:th dho"),
    ("I broke my leg.", "म्योन टांग टूट", "M'on ṭa:ng ṭu:ṭ"),
    ("She has a sweet voice.", "स छि मिठ आवाज़", "S chi miṭh a:wa:z"),
    ("Listen with both ears.", "दोन कान आशुन", "Don ka:n a:shun"),
    ("He smiled with his lips.", "स मुस्कान ओठ", "S muska:n oṭh"),
    ("My tooth aches.", "म्योन दाँत दुख", "M'on da:̃t dukh"),
    ("Cold air in the nose.", "नाक मंज सर्द हवा", "Na:k manz sard hava:"),
    ("Strong shoulders.", "मज़बूत कंध", "Mazbu:t kandh"),
    ("Fold your arms.", "बाज़ू मिल", "Ba:zu mil"),
    ("I cut my finger.", "म्योन उंगल कट", "M'on ungal kaṭ"),
    ("She painted her nails.", "स रंग नखुन", "S rang nakhun"),
    ("My neck is stiff.", "म्योन गर्दन अकड़", "M'on gardan akaṛ"),
    ("He has a broad chest.", "स छु चौड़ सीना", "Su chu chauṛ si:na:"),
    ("Walk on your feet.", "पॅर पॅथ चल", "Pər pəth chal"),
    ("The baby’s skin is soft.", "बच्च कि त्वचा नरम", "Bacca ki tvacha: naram"),
]

NUMBERS = [
    ("One", "अख", "Akh"),
    ("Two", "ज़ॅ", "Zə"),
    ("Three", "त्रॅ", "Trə"),
    ("Four", "चॊर", "Cho:r"),
    ("Five", "पॅंच", "Pəñch"),
    ("Six", "छॅ", "Chə"),
    ("Seven", "सॅथ", "Səth"),
    ("Eight", "आठ", "A:ṭh"),
    ("Nine", "नॊव", "Nov"),
    ("Ten", "दॅह", "Dəh"),
    ("Eleven", "कॅहवॅ", "Kəhve"),
    ("Twelve", "बॅहवॅ", "Bəhve"),
    ("Twenty", "वीह", "Vi:h"),
    ("Thirty", "त्रीह", "Tri:h"),
    ("Hundred", "हॅथ", "Həth"),
    ("I have fifty rupees.", "मे छु पंजाह रुपय", "Me chhu panja:h rupay"),
    ("Count from one to ten.", "अख तॅ दॅह गिन", "Akh tə dəh gin"),
]

FAMILY = [
    ("My father works hard.", "म्योन बॊब काम कर", "M'on bob ka:m kar"),
    ("My mother cooks well.", "म्योन मॊज खाना शिज", "M'on moj kha:na shij"),
    ("His brother studies.", "सु छु भ्रात शिक", "Su chu bhra:t shik"),
    ("Her sister sings.", "स छि बॅहन गान", "S chi bəhn ga:n"),
    ("Our grandparents are kind.", "अमार बॅड मॅहरबान", "Ama:r bəḍ mehraba:n"),
    ("Their son is small.", "तामन पॊत लॊट", "Taman po:t loṭ"),
    ("My friend helped me.", "म्योन दोस्त मदद", "M'on do:st madad"),
    ("We visit relatives.", "असि मिल रिश्तॅदार", "Asi mil rishtəda:r"),
    ("She is my wife.", "स छि म्योन ज़ॅन", "S chi m'on zən"),
    ("He is my husband.", "सु छु म्योन शौहर", "Su chu m'on shauhar"),
    ("The child is sleeping.", "बच्च सुत", "Bacca sut"),
    ("Respect your elders.", "बॅड इज़्ज़त", "Bəḍ izzat"),
    ("My uncle lives in town.", "म्योन माम शहर", "M'on ma:m shehar"),
    ("Her aunt brought sweets.", "स ख़ाला मिठाइ लॅय", "S kha:la miṭha:i ləy"),
    ("We are three siblings.", "असि छि त्रॅ भ्रात बॅहन", "Asi chi trə bhra:t bəhn"),
    ("His daughter is clever.", "सु छि धिय हुशियार", "Su chi dhiy hushiya:r"),
    ("Our parents bless us.", "अमार मॊज बॊब दुआ", "Ama:r moj bob dua:"),
]

IDIOMS = [
    ("Slowly we learn.", "हलुई हलुई शिक", "Halui halui shik"),
    ("Little by little it gets better.", "थोड़ थोड़ बरो", "Tho:r tho:r baro"),
    ("Heart is happy.", "दिल ख़ुश", "Dil kh>sh"),
    ("What to do now?", "आज़ि क्या कर?", "A:zi kya kar?"),
    ("Time will tell.", "वख्त बयान", "Vakht baya:n"),
    ("God willing.", "ख़ुदा ख़ैर", "Khuda: khair"),
    ("Come, let us sit.", "यि बस", "Yi bas"),
    ("The day went well.", "दिन गय बरो", "Din gay baro"),
    ("Keep courage.", "हिम्मत रख", "Himmat rakh"),
    ("Everything will be fine.", "सब ठीक यि", "Sab thi:k yi"),
    ("Do not fear.", "न डर", "Na ḍar"),
    ("Speak from the heart.", "दिल सॅथ उलाव", "Dil səth ula:v"),
    ("Patience is good.", "सब्र बरो", "Sabr baro"),
    ("This too shall pass.", "यि गुज़र", "Yi guzar"),
    ("Walk with love.", "मोहब्बत सॅथ चल", "Mohabbat səth chal"),
    ("Smile a little.", "थोड़ मुस्कान", "Tho:r muska:n"),
    ("Listen more than you speak.", "उलाव तॅ ज़्याद आशुन", "Ula:v tə zya:d a:shun"),
]

DIWALI = [
    ("Happy Diwali to you.", "तुहन्द दिवालि मुबारक", "Tuhand diva:li muba:rak"),
    ("Light lamps at home.", "घर मंज दिवॅ लग", "Ghar manz dive lag"),
    ("We share sweets.", "असि वांट मिठाइ", "Asi va:nṭ miṭha:i"),
    ("The house looks bright.", "घर चु उजाल", "Ghar chu uja:l"),
    ("Children burst crackers safely.", "लड़कि सुरक्षित फटाखॅ", "La:r'ki surakshiṭ faṭa:khe"),
    ("May there be prosperity.", "ख़ैर हो", "Khair ho"),
    ("We wear new clothes.", "असि पॅहन नव कपड़", "Asi pəhen nav kapaṛ"),
    ("Guests visit our home.", "मॅहमान यि घर", "Məhma:n yi ghar"),
    ("I bought a lantern.", "ब ख़रीद लॅंप", "B khari:d laṃp"),
    ("She made sweets.", "स बन मिठाइ", "S ban miṭha:i"),
    ("We pray together.", "असि दुआ एकठॅ", "Asi dua: ekathe"),
    ("The sky is full of lights.", "आसमान उजाल", "A:asma:n uja:l"),
    ("Happy faces everywhere.", "सब ख़ुश", "Sab kh>sh"),
    ("Turn off lights when you sleep.", "सुत वख्त दिव बंद", "Sut vakht div band"),
    ("Share joy with neighbours.", "पड़ोसि सॅथ ख़ुशि", "Paḍosi səth khushi"),
    ("Diwali is my favourite festival.", "दिवालि म्योन पसंद त्योहार", "Diva:li m'on pasand tyoha:r"),
    ("Come for dinner tonight.", "आज रात खान खॅ", "A:j ra:t kha:n khe"),
]

# --- Topic drills (script / grammar parallels) ---
ANUSVAR_DRILLS = [
    ("Your name? (nasal sounds).", "तुहन्द नाव क्या?", "Tuhand na:v kya?"),
    ("My name is short.", "म्योन नाव छु लॊट", "M'on na:v chu loṭ"),
    ("Kashmir is beautiful.", "कशीर छु सॊन्द", "Kashi:r chu sond"),
    ("Srinagar is the capital.", "श्रीनगर छु राजधानि", "Shri:nagar chu ra:jdha:ni"),
    ("The bell rings at the mosque.", "मस्जिद मंज घंटॅ वाज", "Masjid manz ghaṇṭe va:j"),
    ("I eat with my hand.", "ब चुस हाथ सॅथ खॆवान", "B chus ha:th səth khevaa:n"),
    ("The apple is sweet.", "सॅब चु मिठ", "Səb chu miṭh"),
    ("Evening prayer time.", "शाम नमाज़ वख्त", "Sha:m nama:z vakht"),
    ("The lamp gives light.", "दिवॊ दॅ उजाल", "Divo de uja:l"),
    ("I feel cold wind.", "मे लाग सर्द हवा", "Me la:g sard hava:"),
    ("The road is long.", "रस्त चु लंब", "Rast chu lamb"),
    ("We sing hymns.", "असि गाव भजन", "Asi ga:v bhajan"),
    ("The child runs.", "बच्च दोर", "Bacca dor"),
    ("My mind is calm.", "म्योन दिमाग शांत", "M'on dima:g sha:nt"),
    ("The garden is green.", "बाग चु हिरॊ", "Ba:g chu hiro"),
    ("Listen to the song.", "गीत आशुन", "Gi:t a:shun"),
    ("The shop is open.", "दुकान खुल्ल", "Duka:n khulla"),
    ("I need rest today.", "मे कर आराम आज", "Me kar a:ra:m a:j"),
    ("The sky is clear.", "आसमान साफ", "A:asma:n sa:f"),
    ("We thank everyone.", "असि शुक्रिया सब", "Asi shukriya sab"),
]

BARAKHADI_DRILLS = [
    ("I eat — hear the verb ending.", "ब चुस शाल खॆवान", "B chus sha:l khevaa:n"),
    ("You drink — familiar.", "त्स चुख आब चेवान", "Ts chukh a:b ceva:n"),
    ("He reads — third person.", "सु चु किताब परान", "Su chu kita:b para:n"),
    ("She cooks — feminine.", "स च खाना शिजान", "S cha kha:na shija:n"),
    ("We learn — plural.", "असि चि शिकान", "Asi chi shika:n"),
    ("They walk — plural.", "तिम चि चलान", "Tim chi chala:n"),
    ("I write — first person.", "ब चुस लेखान", "B chus le:kha:n"),
    ("You come — habit.", "त्स चुख यिवान", "Ts chukh yiva:n"),
    ("He sleeps.", "सु चु सोतान", "Su chu sota:n"),
    ("She sings.", "स च गान", "S cha ga:n"),
    ("We play.", "असि चि खेळान", "Asi chi khe:la:n"),
    ("They work.", "तिम चि काम करान", "Tim chi ka:m kara:n"),
    ("I see.", "ब चुस पखान", "B chus pakha:n"),
    ("You listen.", "त्स चुख आशुन", "Ts chukh a:shun"),
    ("He opens.", "सु चु खोलान", "Su chu khola:n"),
    ("She closes.", "स च बंद करान", "S cha band kara:n"),
    ("We meet.", "असि चि मिलान", "Asi chi mila:n"),
    ("They wait.", "तिम चि ठाहान", "Tim chi Tha:ha:n"),
    ("I thank.", "ब चुस शुक्रिया", "B chus shukriya"),
    ("You help.", "त्स चुख मदद", "Ts chukh madad"),
]

MINIMAL_PAIR_DRILLS = [
    ("Say ka and kha clearly.", "क ख साफ", "K kha sa:f"),
    ("Do not mix ta and tha.", "त थ अलग", "Ta tha alag"),
    ("Listen: pa versus pha.", "प फ फ़र्क", "P ph fark"),
    ("Short a versus long aa.", "अ आ फ़र्क", "A a: fark"),
    ("Retroflex ṭ is not dental t.", "ट त अलग", "Ṭ ta alag"),
    ("Anusvara changes tone.", "अं सॅथ आवाज़", "Aṃ səth a:wa:z"),
    ("Stress the last syllable.", "अख़ीर ज़ोर", "Akhi:r zor"),
    ("Read slowly first.", "पॅहलॅ हलुई", "Pəhle halui"),
    ("Repeat after the teacher.", "मॅश्टर पॅथ दोहराव", "Məshṭar pəth dohra:v"),
    ("Kashmiri keeps its own sounds.", "कॉशुर अलग", "Ko:shur alag"),
    ("Calm speech is clearer.", "शांत उलाव साफ", "Sha:nt ula:v sa:f"),
    ("Watch lip shape for sounds.", "ओठ हुन आवाज़", "Oṭh hun a:wa:z"),
    ("Practice every morning.", "हर सुबह सराव", "Har subah sarav"),
    ("Ask if unsure.", "शक हॅ तॊ पूछ", "Shak hə to pu:ch"),
    ("Sanskrit words keep full vowels.", "संस्कृत स्वर पूरॅ", "Sanskrit swar pu:re"),
    ("Record and compare.", "रेकॉर्ड कर तुलना", "Reko:rḍ kar tulna:"),
    ("Native rhythm matters.", "लहजॅ ज़रूरी", "Lahjə zaru:ri"),
]

CLUSTER_RA_DRILLS = [
    ("We pray together.", "असि एकठॅ प्रार्थना", "Asi ekathe pra:rthana:"),
    ("The train arrived.", "ट्रेन आय", "Tre:n a:y"),
    ("I like cricket.", "मे आव क्रिकॅट", "Me a:v krikeṭ"),
    ("The fruit is ripe.", "मेवॅ पाक", "Meve pa:k"),
    ("Come back soon.", "फिर लवकर यि", "Phir lavkar yi"),
    ("The road is broken.", "रस्त टूट", "Rast ṭu:ṭ"),
    ("He crossed the bridge.", "सु पार पुल", "Su pa:r pul"),
    ("The price fell.", "दाम घट", "Da:m ghaṭ"),
    ("She bought a frock.", "स ख़रीद फ्रॉक", "S khari:d fro:k"),
    ("We saw the film.", "असि दॅख फिल्म", "Asi de:kh film"),
    ("The bus stopped.", "बस थांब", "Bas tha:mb"),
    ("I need a ticket.", "मे छु टिकट", "Me chhu ṭikaṭ"),
    ("The shop is far.", "दुकान दूर", "Duka:n du:r"),
    ("They built a house.", "तिम बन घर", "Tim ban ghar"),
    ("The child cried.", "बच्च रोव", "Bacca ro:v"),
    ("We reached home.", "असि पहुँच घर", "Asi pahuñch ghar"),
    ("The star shines.", "तारॅ चमक", "Ta:re chamak"),
    ("I trust my friend.", "मे भरोस म्योन दोस्त", "Me bharo:s m'on do:st"),
    ("The river flows.", "दरिया वह", "Dariya: vah"),
    ("Please bring water.", "मेहरबानी आब आन", "Meharba:ni a:b a:n"),
]

CLUSTER_HA_DRILLS = [
    ("It is not there.", "तॊ न छु", "To na chu"),
    ("I do not want it.", "मे न चु", "Me na chu"),
    ("Spring has come.", "बहार आय", "Baha:r a:y"),
    ("The story is nice.", "कहानि बरि", "Kaha:ni bari"),
    ("Laugh a little.", "थोड़ हँस", "Tho:r hãs"),
    ("The hand is clean.", "हाथ साफ", "Ha:th sa:f"),
    ("Cold water.", "थंड आब", "Thaṇḍ a:b"),
    ("The heart is kind.", "दिल मेहरबान", "Dil mehraba:n"),
    ("Speak the truth.", "सच उलाव", "Sach ula:v"),
    ("We heard the news.", "असि आश ख़बर", "Asi a:sh khabar"),
    ("The field is green.", "खॅत हिरॊ", "Khət hiro"),
    ("She held the baby.", "स थाम बच्च", "S tha:m bacca"),
    ("I washed my face.", "ब धो मुँह", "B dho mũh"),
    ("Happiness in the heart.", "दिल मंज ख़ुशि", "Dil manz khushi"),
    ("The road is dusty.", "रस्त धुळ", "Rast dhuḷ"),
    ("Breath is steady.", "साँस थिर", "Sã:s thir"),
    ("Do not fear ghosts.", "भूत खॅ न डर", "Bhu:t khə na ḍar"),
    ("Happiness spreads at home.", "घर मंज ख़ुशि", "Ghar manz khushi"),
    ("He sighed deeply.", "स लंब साँस", "S lamb sã:s"),
    ("The hall is empty.", "हॉल ख़ालि", "Ho:l kha:li"),
]

CLUSTER_GENERAL_DRILLS = [
    ("Student reads.", "तॅलिम चु परान", "Təlim chu para:n"),
    ("Temple looks fine.", "मंदिर बरो", "Mandir baro"),
    ("Picture is clear.", "तस्वीर साफ", "Tasvi:r sa:f"),
    ("Question paper is hard.", "पेपर कठिन", "Pe:par kathin"),
    ("Victory is ours.", "ज़ित अमार", "Zit ama:r"),
    ("The field is wide.", "खॅत चौड़", "Khət chauṛ"),
    ("Effort brings success.", "मेहनत सॅथ कामयाबि", "Mehnat səth ka:ma:ya:bi"),
    ("The nation is great.", "मुल्क मॊट", "Mulk moṭ"),
    ("Science helps life.", "साइंस मदद ज़िंदगि", "Sa:ĩns madad zindagi"),
    ("The letter is short.", "चिट्ठी लॊट", "Chiṭṭhi loṭ"),
    ("Trust is important.", "भरोस ज़रूरी", "Bharo:s zaru:ri"),
    ("The story spread.", "कहानि फैल", "Kaha:ni fail"),
    ("Practice makes perfect.", "सराव सॅथ सही", "Sara:v səth sahi:"),
    ("The machine works.", "मशीन चल", "Mashi:n chal"),
    ("The officer came.", "ऑफिसर आय", "O:fisar a:y"),
    ("The student passed.", "तॅलिम पास", "Təlim pa:s"),
    ("The nation celebrates.", "मुल्क मनाव", "Mulk mana:v"),
    ("The question is easy.", "सवाल आसान", "Sava:l a:sa:n"),
    ("The field needs water.", "खॅत खॅ आब", "Khət khə a:b"),
    ("The picture fell.", "तस्वीर पॅ", "Tasvi:r pe"),
]

IF_THEN_DRILLS = [
    ("If it rains, I stay home.", "अगर पानी, ब रॊव घर", "Agar pa:ni, b ro:v ghar"),
    ("If you come, we eat.", "अगर त्स यिव, असि खा", "Agar ts yiv, asi kha:"),
    ("If he calls, answer.", "अगर सु फोन, जवाब", "Agar su fon, java:b"),
    ("If she is ready, we go.", "अगर स तैयार, असि गच", "Agar s taiya:r, asi gach"),
    ("If it is late, sleep.", "अगर देर, सुत", "Agar der, sut"),
    ("If you want, take it.", "अगर त्स चु, लॅ", "Agar ts chu, lə"),
    ("If they agree, we start.", "अगर तिम मान, असि शुरू", "Agar tim ma:n, asi shuru:"),
    ("If I am free, I come.", "अगर ब आज़ाद, ब यिम", "Agar b a:za:d, b yim"),
    ("If the bus leaves, run.", "अगर बस निकल, दोर", "Agar bas nikal, dor"),
    ("If food is ready, call me.", "अगर खाना तैयार, मे बुलाव", "Agar kha:na taiya:r, me bula:v"),
    ("If you understand, say yes.", "अगर समझ, हो मॊल", "Agar samajh, ho mol"),
    ("If it is hot, drink water.", "अगर गरम, आब पी", "Agar garam, a:b pi"),
    ("If we meet, we talk.", "अगर मिल, असि कथ", "Agar mil, asi kath"),
    ("If the shop is open, buy.", "अगर दुकान खुल्ल, ख़रीद", "Agar duka:n khulla, khari:d"),
    ("If you are tired, rest.", "अगर थक, आराम", "Agar thak, a:ra:m"),
    ("If the road is bad, go slow.", "अगर रस्त खराब, हलुई", "Agar rast khara:b, halui"),
    ("If help is needed, ask.", "अगर मदद, पूछ", "Agar madad, pu:ch"),
    ("If tomorrow is free, come.", "अगर सुबह फारिग, यि", "Agar subah fa:rig, yi"),
    ("If the child sleeps, be quiet.", "अगर बच्च सुत, शांत", "Agar bacca sut, sha:nt"),
]

CONJUNCTION_DRILLS = [
    ("I came and I sat.", "ब आय आ बस", "B a:y a bas"),
    ("He ate and he drank.", "स खाद आ पिय", "S kha:d a piy"),
    ("Small but strong.", "लॊट पॅर मज़बूत", "Loṭ pər mazbu:t"),
    ("Because of rain I stayed.", "पानि खात्रि ब रॊव", "Pa:ni kha:tri b ro:v"),
    ("So we left early.", "मॅह असि लवकर निकल", "Məh asi lavkar nikal"),
    ("He spoke and we listened.", "स उलाव असि आशुन", "S ula:v asi a:shun"),
    ("She cooked and we ate.", "स शिज खान असि खाद", "S shij kha:n asi kha:d"),
    ("Cold yet fresh.", "सर्द पॅर ताज़", "Sard pər ta:z"),
    ("Open the door and enter.", "दरवाज़ खोल आ भितर", "Darva:z khol a bhitur"),
    ("Read and write daily.", "हर दिन पर आ लिख", "Har din par a likh"),
    ("Neither hot nor cold.", "ना गरम न सर्द", "Na: garam na sard"),
    ("Before sleep, pray.", "सुत पॅहलॅ नमाज़", "Sut pəhle nama:z"),
    ("After eating, wash hands.", "खान पॅथ हाथ धो", "Kha:n pəth ha:th dho"),
    ("This and that.", "यि आ ति", "Yi a ti"),
    ("You or me?", "त्स या ब?", "Ts ya b?"),
    ("Neither this nor that.", "ना यि न ति", "Na yi na ti"),
]

PASSIVE_LIGHT_DRILLS = [
    ("The food was cooked.", "खाना शिजॅ", "Kha:na shije"),
    ("The door was opened.", "दरवाज़ खुलॅ", "Darva:z khule"),
    ("The letter was written.", "चिट्ठी लिखॅ", "Chiṭṭhi likhe"),
    ("The work was finished.", "काम खतम", "Ka:m khatam"),
    ("The lamp was lit.", "दिवॊ लगॅ", "Divo lage"),
    ("The house was cleaned.", "घर साफ", "Ghar sa:f"),
    ("The bus was stopped.", "बस थांबॅ", "Bas tha:mbə"),
    ("The ticket was given.", "टिकट दॅ", "Ṭikaṭ de"),
    ("The news was heard.", "ख़बर आशॅ", "Khabar a:she"),
    ("The book was read.", "किताब परॅ", "Kita:b pare"),
    ("The song was sung.", "गीत गॅ", "Gi:t gə"),
    ("The rice was served.", "शाल वॅडॅ", "Sha:l veḍe"),
    ("The window was closed.", "खिड़की बंद", "Khi:r'ki band"),
    ("The money was counted.", "पैसॅ गिनॅ", "Paise gine"),
    ("The path was cleared.", "रस्त साफ", "Rast sa:f"),
]

CAUSATIVE_LIGHT_DRILLS = [
    ("I got the work done.", "मे करव काम", "Me karav ka:m"),
    ("She made him sing.", "स करव गान", "S karav ga:n"),
    ("We had the house painted.", "असि करव घर रंग", "Asi karav ghar rang"),
    ("He made me sit.", "स करव बस", "S karav bas"),
    ("They got the car repaired.", "तिम करव कार ठीक", "Tim karav ka:r thi:k"),
    ("I let the child play.", "ब दॅ बच्च खेळ", "B de bacca kheḷ"),
    ("She sent me to buy.", "स पॅठ मे ख़रीद", "S pəṭh me khari:d"),
    ("We made them understand.", "असि समझाव तिम", "Asi samazha:v tim"),
    ("He got the door opened.", "स खुलाव दरवाज़", "S khula:v darva:z"),
    ("I had food cooked.", "मे शिजाव खाना", "Me shija:v kha:na"),
    ("They made her laugh.", "तिम हँसाव स", "Tim hãsa:v s"),
    ("He made me wait.", "स ठहराव मे", "S Thahra:v me"),
    ("She let us go.", "स दॅ असि वच", "S de asi vach"),
    ("We made him read.", "असि पराव सु", "Asi para:v su"),
    ("I got the key made.", "मे बनाव चाबि", "Me bana:v cha:bi"),
    ("They had the road fixed.", "तिम ठीक करव रस्त", "Tim thi:k karav rast"),
]

WOMENS_DAY_DRILLS = [
    ("Happy Women's Day.", "ख़वातिन दिवस मुबारक", "Khava:tin divas muba:rak"),
    ("Women strengthen the family.", "ज़ॅनॅ कुटुंब मज़बूत", "Zəne kutumb mazbu:t"),
    ("Respect every woman.", "हर ज़ॅन इज़्ज़त", "Har zən izzat"),
    ("Her courage inspires us.", "स हिम्मत प्रेरणा", "S himmat praerana:"),
    ("We celebrate equality.", "असि मनाव बराबरि", "Asi mana:v bara:bari"),
    ("Education for all girls.", "सब लड़कि शिक्षा", "Sab la:r'ki shiksha:"),
    ("Mother is our first teacher.", "मॊज छि पॅहलॅ मॅश्टर", "Moj chi pəhle məshṭar"),
    ("Sisters support each other.", "बॅहन मदद", "Bəhn madad"),
    ("She leads with kindness.", "स नेह सॅथ अगुवाइ", "S neh səth aguva:i"),
    ("Dreams know no gender.", "ख़्वाब बॅ लिंग", "Khwa:b bə ling"),
    ("We honour mothers today.", "आज मॊज इज़्ज़त", "A:j moj izzat"),
    ("Together we rise.", "एकठॅ उठ", "Ekathe uṭh"),
    ("Peace begins at home.", "अमन घर पॅथ", "Aman ghar pəth"),
    ("Gratitude to all women.", "शुक्रिया ख़वातिन", "Shukriya khava:tin"),
    ("We stand with women.", "असि सॅथ ज़ॅन", "Asi səth zən"),
]

ECLIPSE_DRILLS = [
    ("Today there is a solar eclipse.", "आज सूरज ग्रॅहण", "A:j su:raj grəhən"),
    ("Do not look at the sun directly.", "सूरज थेट न पख", "Su:raj theṭ na pakh"),
    ("Use safe glasses.", "सुरक्षित चश्मॅ", "Surakshiṭ cashme"),
    ("Children should stay indoors.", "लड़कि घर मंज", "La:r'ki ghar manz"),
    ("The sky will look dark.", "आसमान कॊलॊ", "A:asma:n kolo"),
    ("We pray for safety.", "असि दुआ सुरक्षा", "Asi dua: suraksha:"),
    ("Do not eat during the eclipse.", "ग्रॅहण वख्त न खा", "Grəhən vakht na kha:"),
    ("Science explains the eclipse.", "साइंस समझाव ग्रॅहण", "Sa:ĩns samazha:v grəhən"),
    ("Protect your eyes.", "अख रक्षा", "Akh raksha:"),
    ("May everyone be safe.", "सब सलामत", "Sab sala:mat"),
    ("Neighbours gather on the roof.", "पड़ोसि छत पॅथ", "Paḍosi chat pəth"),
    ("After eclipse, bathe.", "ग्रॅहण पॅथ न्हा", "Grəhən pəth nha:"),
    ("Elders tell old stories.", "बॅड सुनाव पुरान कहानि", "Bəḍ suna:v pura:n kaha:ni"),
    ("Birds grow quiet.", "परिंद शांत", "Parind sha:nt"),
    ("I read about eclipses.", "ब वाच ग्रॅहण बारॅ", "B va:ch grəhən ba:re"),
    ("Share correct information.", "सही मालूमात वांट", "Sahi ma:lu:ma:t va:nṭ"),
]

SOCIAL_MEDIA_DRILLS = [
    ("I posted a photo today.", "आज ब टाक फोटो", "A:j ba:ṭa:k fo:to"),
    ("She liked my comment.", "स पसंद म्योन कॊमॅन्ट", "S pasand m'on komeṇṭ"),
    ("Too much screen hurts eyes.", "स्क्रीन ज़्याद अख दुख", "Skri:n zya:d akh dukh"),
    ("We chat on the phone.", "असि गप फोन", "Asi gap fon"),
    ("Do not share passwords.", "पासवर्ड न वांट", "Pa:svo:rḍ na va:nṭ"),
    ("Turn off notifications at night.", "रात नोटिफिकॅशन बंद", "Ra:t noṭifike:shan band"),
    ("Talk politely in comments.", "कॊमॅन्ट मंज नर्मि", "Komeṇṭ manz narmi"),
    ("Balance life and screens.", "ज़िंदगि आ स्क्रीन", "Zindagi a skri:n"),
    ("He sent a voice note.", "स धाड वाइस नोट", "S dha:ḍ va:is noṭ"),
    ("The video went viral.", "विडियो वायरल", "Viḍiyo va:yral"),
    ("I follow good pages.", "ब फॉलो बरॅ पॅज", "B folo bare pej"),
    ("She blocked fake news.", "स ब्लॉक खोट ख़बर", "S blo:k khoṭ khabar"),
    ("We learn Kashmiri online too.", "असि शिक ऑनलाइन कॉशुर", "Asi shik onlain ko:shur"),
    ("My data should stay private.", "मॅ डॅटा ख़ास", "Mə ḍeṭa kha:s"),
    ("Parents guide children online.", "मॊज बच्च हुन ऑनलाइन", "Moj bacca hun onlain"),
    ("I deleted the app.", "ब काड ऐप", "B ka:aḍ aip"),
    ("Digital kindness matters.", "डिजिटल नेह ज़रूरी", "Diḳital neh zaru:ri"),
]

JOKES_LIGHT_DRILLS = [
    ("Why did the cat sit? — Rest.", "बिलॅ हॅ बस? — आराम", "Bile hə bas? — a:ra:m"),
    ("The crow said: caw!", "कॉव काँ!", "Ko:v kaã!"),
    ("Two friends, one apple — share!", "दो दोस्त, एक सॅब — वांट!", "Do do:st, ek səb — va:nṭ!"),
    ("Teacher: quiet. Student: yes!", "मॅश्टर: शांत. तॅलिम: हो!", "Məshṭar: sha:nt. təlim: ho!"),
    ("Laughter is good medicine.", "हँसि बरो दवा", "Hãsi baro dava:"),
    ("The mirror never lies.", "आइना सच", "A:i:na sach"),
    ("Small joke, big smile.", "लॊट लॅट हँसि", "Loṭ ləṭ hãsi"),
    ("Fun keeps the heart young.", "मज़ा दिल तॅज़", "Maza dil təz"),
    ("Grandpa tells the best jokes.", "बॅड सुनाव बरॊ लॅट", "Bəḍ suna:v baro ləṭ"),
    ("I forgot the punchline.", "ब विसर आख़िर", "B visar a:khir"),
    ("The dog chased its tail.", "कुकुर पॅठ दुम", "Kukur pəṭh dum"),
    ("Two plus two is four.", "दो आ दो चार", "Do a do cha:r"),
    ("Late for school again!", "स्कूल बॅ फिर देर!", "Sku:l bə phir der!"),
    ("That was a silly joke.", "हो आस सॊफ लॅट", "Ho a:s sof ləṭ"),
    ("Smile at strangers sometimes.", "कदॅ परायॅ हँसि", "Kade para:ye hãsi"),
]

QUARREL_HOME_DRILLS = [
    ("Please lower your voice.", "आवाज़ कम", "A:wa:z kam"),
    ("Let us not fight at home.", "घर मंज लड़ाइ न", "Ghar manz laṛa:i na"),
    ("I did not mean to hurt you.", "मे न चु दुख दॅ", "Me na chu dukh de"),
    ("Sit and talk calmly.", "बस आ शांत कथ", "Bas a sha:nt kath"),
    ("Sorry for my words.", "माफ मॅज उलाव", "Ma:f məz ula:v"),
    ("Listen before you shout.", "चिल्ल पॅहलॅ आशुन", "Chilla pəhle a:shun"),
    ("The children are scared.", "लड़कि डर", "La:r'ki ḍar"),
    ("Let us take a break.", "थोड़ आराम", "Tho:r a:ra:m"),
    ("Speak with respect.", "इज़्ज़त सॅथ उलाव", "Izzat səth ula:v"),
    ("Forgive and move on.", "माफ कर आ आगॅ", "Ma:f kar a a:ge"),
    ("Home should feel safe.", "घर सुरक्षित", "Ghar surakshiṭ"),
    ("We love this family.", "असि मोह कुटुंब", "Asi moh kutumb"),
    ("We can solve this together.", "हॅ असि एकठॅ हल", "Hə asi ekathe hal"),
    ("Anger cools with time.", "गुस्स वख्त सॅथ थंड", "Guss vakht səth thaṇḍ"),
    ("I understand your worry.", "मे समझ तुहन्द फिकिर", "Me samajh tuhand fikir"),
    ("Do not bring up old fights.", "पुरान लड़ाइ न सॅथ", "Pura:n laṛa:i na səth"),
    ("Tomorrow will be better.", "सुबह बरो", "Subah baro"),
]

REPUBLIC_DAY_DRILLS = [
    ("Happy Republic Day.", "गणतंत्र दिवस मुबारक", "Gantantra divas muba:rak"),
    ("We salute the flag.", "असि सलाम झंडॅ", "Asi sala:m jhaṇḍe"),
    ("We sing the national song.", "असि गाव क़ौमि गीत", "Asi ga:v qaumi gi:t"),
    ("India is diverse and united.", "हिंदुस्तान मुख़्तलिफ आ एक", "Hindustan mukhtalif a ek"),
    ("Honour the soldiers.", "सिपाहि इज़्ज़त", "Sipa:hi izzat"),
    ("The tricolour flies high.", "तिरंग उंच", "Tirang unch"),
    ("Unity is our strength.", "एकता अमार बल", "Ekata ama:r bal"),
    ("Respect every citizen.", "हर शहरी इज़्ज़त", "Har shahri izzat"),
    ("Jai Hind!", "जय हिंद!", "Jai Hind!"),
    ("We remember the Constitution.", "असि याद संविधान", "Asi ya:d sanvidha:n"),
    ("Children march in school.", "लड़कि स्कूल मंज परेड", "La:r'ki sku:l manz pareḍ"),
    ("Freedom brings responsibility.", "आज़ादि सॅथ ज़िम्मॅ", "A:za:di səth zimmə"),
    ("The parade is grand.", "परेड भॊय", "Pareḍ bhoy"),
    ("Schools hoist the flag.", "स्कूल झंडॅ उंचाव", "Sku:l jhaṇḍe uncha:v"),
    ("Youth serve the nation.", "जवान मुल्क खॅ", "Java:n mulk khə"),
    ("Patriots built the nation.", "दॅशभक्त बनाव मुल्क", "Deshbhakt bana:v mulk"),
    ("Peace and progress together.", "अमन आ तरक्कि एकठॅ", "Aman a tarkki ekathe"),
]

BANK_REGISTRY = {
    "GREETINGS": GREETINGS,
    "DAILY": DAILY,
    "FOOD": FOOD,
    "PRONOUNS": PRONOUNS,
    "PRESENT": PRESENT,
    "PAST": PAST,
    "FUTURE": FUTURE,
    "QUESTIONS": QUESTIONS,
    "NEGATIVE": NEGATIVE,
    "POSSESSION": POSSESSION,
    "SCRIPT_PRONUNCIATION": SCRIPT_PRONUNCIATION,
    "SHOPPING": SHOPPING,
    "HEALTH": HEALTH,
    "TRAVEL": TRAVEL,
    "BODY": BODY,
    "NUMBERS": NUMBERS,
    "FAMILY": FAMILY,
    "IDIOMS": IDIOMS,
    "DIWALI": DIWALI,
    "READING_DRILLS": READING_DRILLS,
    "ANUSVAR_DRILLS": ANUSVAR_DRILLS,
    "BARAKHADI_DRILLS": BARAKHADI_DRILLS,
    "MINIMAL_PAIR_DRILLS": MINIMAL_PAIR_DRILLS,
    "CLUSTER_RA_DRILLS": CLUSTER_RA_DRILLS,
    "CLUSTER_HA_DRILLS": CLUSTER_HA_DRILLS,
    "CLUSTER_GENERAL_DRILLS": CLUSTER_GENERAL_DRILLS,
    "IF_THEN_DRILLS": IF_THEN_DRILLS,
    "CONJUNCTION_DRILLS": CONJUNCTION_DRILLS,
    "PASSIVE_LIGHT_DRILLS": PASSIVE_LIGHT_DRILLS,
    "CAUSATIVE_LIGHT_DRILLS": CAUSATIVE_LIGHT_DRILLS,
    "WOMENS_DAY_DRILLS": WOMENS_DAY_DRILLS,
    "ECLIPSE_DRILLS": ECLIPSE_DRILLS,
    "SOCIAL_MEDIA_DRILLS": SOCIAL_MEDIA_DRILLS,
    "JOKES_LIGHT_DRILLS": JOKES_LIGHT_DRILLS,
    "QUARREL_HOME_DRILLS": QUARREL_HOME_DRILLS,
    "REPUBLIC_DAY_DRILLS": REPUBLIC_DAY_DRILLS,
}
BANK_REGISTRY.update(TARGET_BANK_REGISTRY)
from kashmiri_lesson5_banks import L5_BANK_REGISTRY  # noqa: E402 — after BANK_REGISTRY to avoid circular import

BANK_REGISTRY.update(L5_BANK_REGISTRY)
