# Per-sublesson bank priority (chapterId → bank names). Titles in lessons_structure_kashmiri.json.
# First banks fill rows first; pools align with each sublesson topic (grammar, script, phrases, vocab, dialogue).
from __future__ import annotations

CHAPTER_TO_BANKS: dict[int, tuple[str, ...]] = {
    # --- Lesson 1: Kashmiri Script (501–509) ---
    501: ("READING_DRILLS", "SCRIPT_PRONUNCIATION", "NUMBERS", "GREETINGS"),
    502: ("READING_DRILLS", "SCRIPT_PRONUNCIATION", "PRONOUNS", "PRESENT"),
    503: ("BARAKHADI_DRILLS", "READING_DRILLS", "PRESENT", "GREETINGS"),
    504: ("MINIMAL_PAIR_DRILLS", "QUESTIONS", "DAILY", "READING_DRILLS"),
    505: ("ANUSVAR_DRILLS", "SCRIPT_PRONUNCIATION", "GREETINGS", "READING_DRILLS"),
    506: ("CLUSTER_GENERAL_DRILLS", "READING_DRILLS", "PRESENT", "FOOD"),
    507: ("CLUSTER_RA_DRILLS", "READING_DRILLS", "TRAVEL", "DAILY"),
    508: ("CLUSTER_HA_DRILLS", "READING_DRILLS", "FAMILY", "GREETINGS"),
    509: ("SCRIPT_PRONUNCIATION", "CLUSTER_GENERAL_DRILLS", "READING_DRILLS", "IDIOMS"),
    # --- Lesson 2: Grammar (510–542) ---
    510: ("PRONOUNS", "POSSESSION", "QUESTIONS", "PRESENT"),
    511: ("PRONOUNS", "GREETINGS", "PRESENT", "FAMILY"),
    512: ("PRESENT", "PAST", "FUTURE", "QUESTIONS", "IDIOMS"),
    513: ("PRESENT", "DAILY", "FOOD", "READING_DRILLS"),
    514: ("PRESENT", "PRONOUNS", "DAILY", "QUESTIONS"),
    515: ("PRESENT", "DAILY", "FOOD", "TRAVEL"),
    516: ("FUTURE", "PRESENT", "DAILY", "QUESTIONS"),
    517: ("FUTURE", "PRESENT", "DAILY", "TRAVEL"),
    518: ("PAST", "PRESENT", "DAILY", "NEGATIVE"),
    519: ("PAST", "FOOD", "PRESENT", "POSSESSION"),
    520: ("PAST", "PRONOUNS", "PRESENT", "QUESTIONS"),
    521: ("PAST", "PRESENT", "IDIOMS", "NEGATIVE"),
    522: ("PAST", "PRESENT", "DAILY", "TRAVEL"),
    523: ("PAST", "FUTURE", "PRESENT", "QUESTIONS"),
    524: ("TRAVEL", "POSSESSION", "DAILY", "SHOPPING"),
    525: ("TRAVEL", "QUESTIONS", "DAILY", "PRESENT"),
    526: ("PRESENT", "PRONOUNS", "QUESTIONS", "FAMILY"),
    527: ("POSSESSION", "PRONOUNS", "FAMILY", "PRESENT"),
    528: ("QUESTIONS", "PRONOUNS", "PRESENT", "DAILY"),
    529: ("NEGATIVE", "PRESENT", "DAILY", "FOOD"),
    530: ("NEGATIVE", "PAST", "DAILY", "PRESENT"),
    531: ("NEGATIVE", "FUTURE", "PRESENT", "DAILY"),
    532: ("PRONOUNS", "FAMILY", "PRESENT", "FOOD"),
    533: ("TRAVEL", "POSSESSION", "DAILY", "BODY"),
    534: ("TRAVEL", "SHOPPING", "DAILY", "QUESTIONS"),
    535: ("POSSESSION", "PRONOUNS", "TRAVEL", "FAMILY"),
    536: ("DAILY", "QUESTIONS", "GREETINGS", "PRESENT"),
    537: ("DAILY", "NUMBERS", "PRESENT", "FUTURE"),
    538: ("CAUSATIVE_LIGHT_DRILLS", "PRESENT", "PAST", "IDIOMS"),
    539: ("PRONOUNS", "PRESENT", "PAST", "FAMILY"),
    540: ("PAST", "FUTURE", "PRESENT", "DAILY"),
    541: ("PAST", "PRESENT", "DAILY", "FUTURE"),
    542: ("NEGATIVE", "POSSESSION", "PRESENT", "DAILY"),
    # --- Lesson 3: Phrases & structures (543–596); first bank matches sublesson topic ---
    543: ("KS_GOING_TO", "FUTURE", "DAILY", "TRAVEL"),
    544: ("KS_USED_TO", "PAST", "DAILY", "IDIOMS"),
    545: ("KS_USED_TO_OLD", "PAST", "IDIOMS", "GREETINGS"),
    546: ("IF_THEN_DRILLS", "FUTURE", "QUESTIONS", "PRESENT"),
    547: ("KS_PREP_WITH_VERBS", "TRAVEL", "PRESENT", "DAILY"),
    548: ("KS_ADJECTIVE_SENTENCES", "PRESENT", "SHOPPING", "FOOD"),
    549: ("KS_CAN_ABLE", "QUESTIONS", "PRESENT", "NEGATIVE"),
    550: ("KS_WANT_NEED", "POSSESSION", "FOOD", "DAILY"),
    551: ("KS_BECOME_HAPPEN", "PRESENT", "IDIOMS", "FUTURE"),
    552: ("KS_SHOULD", "DAILY", "FUTURE", "NEGATIVE"),
    553: ("KS_MUST_HAVE_TO", "DAILY", "FUTURE", "NEGATIVE"),
    554: ("KS_KEEP_DOING", "PRESENT", "PAST", "DAILY"),
    555: ("KS_COMPARISON", "PRESENT", "SHOPPING", "FOOD"),
    556: ("KS_TO_KNOW", "QUESTIONS", "PRESENT", "NEGATIVE"),
    557: ("KS_LET_SHALL", "DAILY", "FUTURE", "GREETINGS"),
    558: ("KS_WHICH_WHAT_THAT", "QUESTIONS", "PRESENT", "PRONOUNS"),
    559: ("KS_FORMAL_INSTRUCTIONS", "GREETINGS", "DAILY", "QUESTIONS"),
    560: ("KS_TO_LIKE", "FOOD", "DAILY", "PRESENT"),
    561: ("KS_WOULD", "PAST", "FUTURE", "DAILY"),
    562: ("KS_UNDERSTAND", "QUESTIONS", "PRESENT", "IDIOMS"),
    563: ("KS_QUESTION_TAG", "QUESTIONS", "PRESENT", "NEGATIVE"),
    564: ("KS_REMEMBER", "PAST", "PRESENT", "DAILY"),
    565: ("KS_WANT_WITH_VERB", "POSSESSION", "PRESENT", "FOOD"),
    566: ("KS_WANT_OTHER_PERSON", "POSSESSION", "PRONOUNS", "DAILY"),
    567: ("KS_SUPPOSED_TO", "DAILY", "FUTURE", "NEGATIVE"),
    568: ("KS_LIKE_WITH_VERB", "FOOD", "PRESENT", "DAILY"),
    569: ("KS_VERB_PREP_TO_OBJECT", "TRAVEL", "QUESTIONS", "POSSESSION"),
    570: ("KS_SHORT_FORMS", "GREETINGS", "DAILY", "IDIOMS"),
    571: ("KS_GREETINGS_WISHES", "GREETINGS", "IDIOMS", "DIWALI"),
    572: ("KS_COMPOUND_VERBS_MAIN", "IDIOMS", "PRESENT", "DAILY"),
    573: ("KS_ADDRESSING", "FAMILY", "GREETINGS", "PRONOUNS"),
    574: ("KS_EXCLAMATIONS", "IDIOMS", "GREETINGS", "DAILY"),
    575: ("KS_REQUESTS_MAY_CAN", "QUESTIONS", "GREETINGS", "DAILY"),
    576: ("KS_UNCERTAINTY", "QUESTIONS", "FUTURE", "DAILY"),
    577: ("KS_ADJ_FROM_VERB", "PRESENT", "DAILY", "SHOPPING"),
    578: ("KS_ADJ_FROM_PREP", "PRESENT", "TRAVEL", "SHOPPING"),
    579: ("KS_WISH_MAY", "GREETINGS", "FUTURE", "IDIOMS"),
    580: ("KS_MAKE_SOMEONE_DO", "CAUSATIVE_LIGHT_DRILLS", "PRESENT", "IDIOMS"),
    581: ("KS_GENERALIZING", "TRAVEL", "QUESTIONS", "PRONOUNS"),
    582: ("KS_POSSESSION_RELATION", "POSSESSION", "FAMILY", "DAILY"),
    583: ("KS_TO_MEAN_ASK", "QUESTIONS", "PRESENT", "PRONOUNS"),
    584: ("KS_CONJ_PART1", "CONJUNCTION_DRILLS", "IDIOMS", "DAILY"),
    585: ("KS_CONJ_PART2", "CONJUNCTION_DRILLS", "QUESTIONS", "DAILY"),
    586: ("KS_CONJ_PART3", "CONJUNCTION_DRILLS", "TRAVEL", "PAST"),
    587: ("KS_CONJ_PART4", "CONJUNCTION_DRILLS", "FUTURE", "DAILY"),
    588: ("KS_CONJUNCTION_LIST", "IDIOMS", "PRESENT", "QUESTIONS"),
    589: ("KS_COMBINING_SENTENCES", "CONJUNCTION_DRILLS", "IDIOMS", "PRESENT"),
    590: ("KS_COMPOUND_VERBS_2", "IDIOMS", "PAST", "PRESENT"),
    591: ("KS_PASSIVE_FOCUS", "PASSIVE_LIGHT_DRILLS", "PAST", "NEGATIVE"),
    592: ("KS_PASSIVE_STYLE2", "PASSIVE_LIGHT_DRILLS", "NEGATIVE", "DAILY"),
    593: ("KS_FEEL_THINK", "HEALTH", "IDIOMS", "DAILY"),
    594: ("KS_IDIOMS_1", "IDIOMS", "GREETINGS", "DAILY"),
    595: ("KS_IDIOMS_2", "IDIOMS", "DAILY", "PRESENT"),
    596: ("KS_IF_THEN_STYLE2", "IF_THEN_DRILLS", "FUTURE", "QUESTIONS"),
    # --- Lesson 4: Vocabulary (597–619) ---
    597: ("BODY", "HEALTH", "DAILY"),
    598: ("DAILY", "FOOD", "TRAVEL", "IDIOMS"),
    599: ("FAMILY", "GREETINGS", "POSSESSION"),
    600: ("NUMBERS", "DAILY", "SHOPPING"),
    601: ("NUMBERS", "DAILY", "SHOPPING", "PRESENT"),
    602: ("NUMBERS", "SHOPPING", "DAILY", "FOOD"),
    603: ("PRESENT", "PAST", "DAILY"),
    604: ("PRESENT", "PAST", "FOOD"),
    605: ("PAST", "FUTURE", "DAILY"),
    606: ("FUTURE", "QUESTIONS", "PRESENT"),
    607: ("PRESENT", "PAST", "IDIOMS", "DAILY"),
    608: ("PRESENT", "PAST", "DAILY", "NEGATIVE"),
    609: ("PRESENT", "SHOPPING", "DAILY"),
    610: ("PRESENT", "DAILY", "QUESTIONS"),
    611: ("DAILY", "PRESENT", "QUESTIONS", "TRAVEL"),
    612: ("FOOD", "SHOPPING", "DAILY"),
    613: ("FOOD", "DAILY", "SHOPPING"),
    614: ("DAILY", "BODY", "NUMBERS"),
    615: ("DAILY", "BODY", "FOOD"),
    616: ("SHOPPING", "PRESENT", "DAILY"),
    617: ("DAILY", "FAMILY", "GREETINGS"),
    618: ("DAILY", "FAMILY", "BODY"),
    619: ("DAILY", "FOOD", "GREETINGS", "IDIOMS"),
    # --- Lesson 5: Conversation (620–662); one title-aligned bank per sublesson ---
    620: ("KS_CONV_620",),
    621: ("KS_CONV_621",),
    622: ("KS_CONV_622",),
    623: ("KS_CONV_623",),
    624: ("KS_CONV_624",),
    625: ("KS_CONV_625",),
    626: ("KS_CONV_626",),
    627: ("KS_CONV_627",),
    628: ("KS_CONV_628",),
    629: ("KS_CONV_629",),
    630: ("KS_CONV_630",),
    631: ("KS_CONV_631",),
    632: ("KS_CONV_632",),
    633: ("KS_CONV_633",),
    634: ("KS_CONV_634",),
    635: ("KS_CONV_635",),
    636: ("KS_CONV_636",),
    637: ("KS_CONV_637",),
    638: ("KS_CONV_638",),
    639: ("KS_CONV_639",),
    640: ("KS_CONV_640",),
    641: ("KS_CONV_641",),
    642: ("KS_CONV_642",),
    643: ("KS_CONV_643",),
    644: ("KS_CONV_644",),
    645: ("KS_CONV_645",),
    646: ("KS_CONV_646",),
    647: ("KS_CONV_647",),
    648: ("KS_CONV_648",),
    649: ("KS_CONV_649",),
    650: ("KS_CONV_650",),
    651: ("KS_CONV_651",),
    652: ("KS_CONV_652",),
    653: ("KS_CONV_653",),
    654: ("KS_CONV_654",),
    655: ("KS_CONV_655",),
    656: ("KS_CONV_656",),
    657: ("KS_CONV_657",),
    658: ("KS_CONV_658",),
    659: ("KS_CONV_659",),
    660: ("KS_CONV_660",),
    661: ("KS_CONV_661",),
    662: ("KS_CONV_662",),
}


def assert_all_chapters_covered(structure_path: str | None = None) -> None:
    import json
    from pathlib import Path

    p = Path(structure_path or Path(__file__).resolve().parent / "lessons_structure_kashmiri.json")
    data = json.loads(p.read_text(encoding="utf-8-sig"))
    ids: list[int] = []
    for ml in data["majorLessons"]:
        for sub in ml["sublessons"]:
            ids.append(sub["chapterId"])
    missing = [i for i in ids if i not in CHAPTER_TO_BANKS]
    extra = [i for i in CHAPTER_TO_BANKS if i not in ids]
    if missing or extra:
        raise AssertionError(f"missing routes {missing!r} extra {extra!r}")
