# Curated Konkani triples [English, Devanagari, Roman] for lesson assembly.
# Sources: common Goan Konkani (Devanagari), Wikibooks Konkani/Greetings, Wikivoyage phrasebook
# patterns, Saraswat grammar blog style examples (subject + object + verb), in-app phrase style.

def target_row_count(chapter_id: int) -> int:
    """Each sublesson uses 15–20 rows (spread by chapter id)."""
    return 15 + (chapter_id % 6)  # 15, 16, … 20


# Legacy default for callers that omit chapter id
ROWS_PER_LESSON = 18

# --- Shared pools (extend / combine per chapter) ---
GREETINGS = [
    ("May God give you a good day.", "देव बरो दीस दीय", "Dev boro dis diiy"),
    ("May God give grace (reply to greeting).", "देव कुर्पा दीय", "Dev kurpa diiy"),
    ("How are you? (to a male, familiar)", "तूं कोशो आसाय?", "Tum kosho aasaay?"),
    ("How are you? (respectful / female older)", "तुमी कशीं आसात?", "Tumi kasheen aasaat?"),
    ("I am fine (male).", "हांव बरो आसां", "Haanv baro aasaan"),
    ("I am fine (female).", "हांव बरी आसां", "Haanv bari aasaan"),
    ("Thank you.", "देव बरें करूं", "Dev barem karun"),
    ("Good morning.", "देव बरें करूं सकाळ", "Dev barem karun sakaal"),
    ("Good night.", "बरी रात", "Bori raat"),
    ("Welcome.", "येवकार", "Yevkaar"),
    ("What is your name?", "तुजें नांव कितें?", "Tujem naanv kitem?"),
    ("My name is Ravi.", "म्हजें नांव रवी", "Mhajem naanv Ravi"),
    ("See you later.", "उपरांत मेळया", "Upraant melyaa"),
    ("Nice to meet you.", "तुमकां मेळून बरें दिसलें", "Tumkaan mellun barem dislem"),
    ("Congratulations.", "अभिनंदन", "Abhinandan"),
    ("Happy Diwali.", "दिवाळीच्यो शुभकामना", "Divalichyo shubhkaamnaa"),
    ("Good evening.", "बरी सांज", "Bori saanj"),
    ("Hello / Namaskar.", "नमस्कार", "Namaskaar"),
]

# Full sentences for reading / script lessons (letter–sound practice in context)
READING_DRILLS = [
    ("I eat rice at home.", "हांव घरांत शीत खातां", "Haanv gharaant sheet khaataan"),
    ("You drink water now.", "तूं आतां उदक पीता", "Tum aataa udak peetaa"),
    ("He goes to the temple.", "तो देवळाक वता", "To devullaak vataa"),
    ("She sings a sweet song.", "ती गोड गीत गाता", "Ti god geet gaataa"),
    ("We live in Goa.", "आमी गोंयांत रावतात", "Aami Goanyaant raavtaat"),
    ("They work hard every day.", "ते दर दीस मेहनत करतात", "Te dar dis mehnat kartaat"),
    ("I see the moon at night.", "हांव राती चंद्र पळयतां", "Haanv raati chondro pallaytaan"),
    ("Open the book and read.", "पुस्तक उगड आनी वाच", "Pustak ugad aani vaach"),
    ("The house is near the road.", "घर वाटे लागीं आसा", "Ghor vaate laagim aasaa"),
    ("Give me a little milk.", "म्हाका थोडें दूद दी", "Mhaakaa thodem dud di"),
    ("The children play in the yard.", "भुरगीं आंगणांत खेळतात", "Bhurgim aangaant kheltaat"),
    ("I thank you with all my heart.", "हांव तुका काळीजांतल्यान देव बरें करतां", "Haanv tuka kaalijaantlyaan dev barem kartaan"),
    ("We learn Konkani step by step.", "आमी कोंकणी हळू हळू शिकतात", "Aami Konkani halu halu shiktaat"),
    ("Speak slowly and clearly.", "हळू आनी स्पष्ट उलय", "Halu aani spasht ulay"),
    ("The sun rises in the east.", "सूर्य उदेंत उगता", "Soorya udent ugataa"),
    ("Birds sit on the tree.", "सुकणीं रुकाचेर बसतात", "Suknim rukaacher basataat"),
    ("I write my name here.", "हांव म्हजें नांव हांगा बरोवतां", "Haanv mhajem naanv haangaa barovtaan"),
    ("Close the door quietly.", "दार आहिस्तां धांप", "Daar aahistaan dhaamp"),
    ("Good people help others.", "बरे मनीस दुसऱ्यांक मदत करतात", "Bare manis dusaryaank madat kartaat"),
    ("I hear the sound of rain.", "हांव पावसाचो आवाज आयकतां", "Haanv paavsaacho aawaaz aayaktaan"),
    ("She cooks food with love.", "ती मोगांनी जेवण शिजोवता", "Ti mogaanni jevan shijovtaa"),
    ("We shall meet again tomorrow.", "आमी फाल्यां परत मेळतले", "Aami faalyaan parat meltaale"),
]

DAILY = [
    ("What time is it?", "कितलो वेळ जालो?", "Kitlo vell zaalo?"),
    ("Where do you live?", "तूं खंय रावता?", "Tum khanay raavtaa?"),
    ("I live in Goa.", "हांव गोंयांत रावतां", "Haanv Goanyaant raavtaan"),
    ("I have to go home.", "म्हाका घरा वचूंक जाय", "Mhaakaa gharaa vochunk jaay"),
    ("Come here.", "हांगा ये", "Haangaa ye"),
    ("Sit down.", "बस", "Bas"),
    ("Open the door.", "दार उगड", "Daar ugad"),
    ("Today is a holiday.", "आयज सुटी", "Aayaj suti"),
    ("Tomorrow I will come.", "फाल्यां हांव येतलों", "Faalyaan haanv yetlon"),
    ("Yesterday was good.", "काल बरें आशिल्लें", "Kaal barem aashillem"),
    ("I am tired.", "हांव थकलों", "Haanv thaklon"),
    ("Let's go.", "चल वचूया", "Chal vochooyaa"),
    ("I am going to work.", "हांव कामाक वतां", "Haanv kaamaak vataan"),
    ("Close the window.", "जनेल धांप", "Janel dhaamp"),
    ("Switch on the light.", "दिवो पेटय", "Divo petay"),
    ("Where is the market?", "बाजार खंय आसा?", "Baazaar khanay aasaa?"),
    ("I need water.", "म्हाका उदक जाय", "Mhaakaa udak jaay"),
]

FOOD = [
    ("I am hungry.", "म्हाका भूक लागल्या", "Mhaakaa bhook laaglyaa"),
    ("Give me water.", "म्हाका उदक दी", "Mhaakaa udak di"),
    ("The food is tasty.", "जेवण रुचिक आसा", "Jevan ruchik aasaa"),
    ("I want tea.", "म्हाका चा जाय", "Mhaakaa chaa jaay"),
    ("The food is spicy.", "जेवण तिखट आसा", "Jevan tikhat aasaa"),
    ("I do not eat meat.", "हांव मास खायनां", "Haanv maas khaaynaan"),
    ("What is this dish?", "हें कितें जेवण?", "Hem kitem jevan?"),
    ("I want to eat.", "म्हाका जेवूंक जाय", "Mhaakaa jevunk jaay"),
    ("Enough food.", "जेवण पुरो", "Jevan puro"),
    ("I want rice.", "म्हाका शीत जाय", "Mhaakaa sheet jaay"),
    ("Bring the bill.", "बिल हाड", "Bill haad"),
    ("More food, please.", "आनीक जेवण दिवचें", "Aanik jevan divchem"),
    ("The food is sweet.", "जेवण गोड आसा", "Jevan god aasaa"),
    ("Give me roti.", "म्हाका पोळी दी", "Mhaakaa polli di"),
    ("I want coffee.", "म्हाका कॉफी जाय", "Mhaakaa coffee jaay"),
    ("I am vegetarian.", "हांव शाकाहारी", "Haanv shaakahaari"),
    ("I am thirsty.", "म्हाका तान लागल्या", "Mhaakaa taan laaglyaa"),
]

PRONOUNS = [
    ("I", "हांव", "Haanv"),
    ("You (familiar)", "तूं", "Tum"),
    ("You (polite / plural)", "तुमी", "Tumi"),
    ("He", "तो", "To"),
    ("She", "ती", "Ti"),
    ("We", "आमी", "Aami"),
    ("They", "ते", "Te"),
    ("This", "हें", "Hem"),
    ("That", "तें", "Tem"),
    ("My (before vowel sound)", "म्हजें", "Mhajem"),
    ("Your (familiar)", "तुजें", "Tujem"),
    ("Our", "आमचें", "Aamchem"),
    ("Their", "तांचें", "Taanchem"),
    ("Who?", "कोण?", "Kon?"),
    ("What?", "कितें?", "Kitem?"),
    ("Where?", "खंय?", "Khanay?"),
    ("When?", "केन्ना?", "Kennaa?"),
    ("Why?", "कित्याक?", "Kityaak?"),
]

PRESENT = [
    ("I eat rice.", "हांव शीत खातां", "Haanv sheet khaataan"),
    ("You speak Konkani.", "तूं कोंकणी उलयता", "Tum Konkani ulaytaa"),
    ("He reads a book.", "तो पुस्तक वाचता", "To pustak vaachtaa"),
    ("She cooks food.", "ती जेवण शिजोवता", "Ti jevan shijovtaa"),
    ("We study at home.", "आमी घरांत शिकतात", "Aami gharaant shiktaat"),
    ("They work in Goa.", "ते गोंयांत काम करतात", "Te Goanyaant kaam kartaat"),
    ("I drink water.", "हांव उदक पीतां", "Haanv udak peetaan"),
    ("You come every day.", "तूं दर दीस येता", "Tum dar dis yetaa"),
    ("He goes to school.", "तो इस्कोलाक वता", "To iskolaak vataa"),
    ("She sings well.", "ती बरें गाता", "Ti barem gaataa"),
    ("We play in the evening.", "आमी सांजे खेळतात", "Aami saanje kheltaat"),
    ("They walk on the road.", "ते वाटेर चलतात", "Te vaater chaltaat"),
    ("I see the sea.", "हांव दर्या पळयतां", "Haanv daryaa pallaytaan"),
    ("You listen carefully.", "तूं लक्ष दिवन आयकता", "Tum laksh divun aayaktaa"),
    ("He sleeps early.", "तो लवकर निदता", "To lavkar nidtaa"),
    ("She writes a letter.", "ती पत्र बरोवता", "Ti patr barovtaa"),
    ("We learn new words.", "आमी नवे शब्द शिकतात", "Aami nave shabd shiktaat"),
]

PAST = [
    ("I went home.", "हांव घरा वचलों", "Haanv gharaa vachlon"),
    ("You ate food.", "तूं जेवण खादलें", "Tum jevan khaadlem"),
    ("He came yesterday.", "तो काल आयलो", "To kaal aaylo"),
    ("She spoke Konkani.", "ती कोंकणी उलयली", "Ti Konkani ulayli"),
    ("We saw the temple.", "आमी देवळ पळयलो", "Aami devoll pallaylo"),
    ("They bought vegetables.", "ते भाजी घेतली", "Te bhaaji ghetli"),
    ("I drank milk.", "हांव दूद पियलों", "Haanv dud piyalon"),
    ("You slept late.", "तूं उशीरा निदलो", "Tum usheera nidlo"),
    ("He wrote a letter.", "तानें पत्र बरयलें", "Taanem patr baraylem"),
    ("She opened the door.", "तीनें दार उगडलें", "Tinem daar ugadle"),
    ("We finished work.", "आमी काम संपयलें", "Aami kaam sampaylem"),
    ("They returned home.", "ते घरा परत आयले", "Te gharaa parat aayle"),
    ("I was in Panaji.", "हांव पणजीत आशिल्लों", "Haanv Panjiit aashillon"),
    ("It rained yesterday.", "काल पावस पडलो", "Kaal paavas paddlo"),
    ("You helped me.", "तूं म्हाका मदत केली", "Tum mhaakaa madat keli"),
    ("He forgot the key.", "ताका चावी विसरली", "Taakaa chaavi visarli"),
    ("She liked the song.", "तिका गीत आवडलें", "Tikaa geet aavaddle"),
]

FUTURE = [
    ("I will come tomorrow.", "हांव फाल्यां येतलों", "Haanv faalyaan yetlon"),
    ("You will eat later.", "तूं उपरांत खातलो", "Tum upraant khaatlo"),
    ("He will go to school.", "तो इस्कोलाक वचतलो", "To iskolaak vochtalo"),
    ("She will cook rice.", "ती शीत शिजोवतली", "Ti sheet shijovtali"),
    ("We will meet again.", "आमी परत मेळतले", "Aami parat meltaale"),
    ("They will buy fruit.", "ते फळ घेतले", "Te fall ghetele"),
    ("I will call you.", "हांव तुका फोन करतलों", "Haanv tuka phone kartalon"),
    ("You will feel better.", "तुका बरें दिसतलें", "Tuka barem distalem"),
    ("He will read the book.", "तो पुस्तक वाचतलो", "To pustak vaachtalo"),
    ("She will sing a song.", "ती गीत गातली", "Ti geet gaatli"),
    ("We will travel to Goa.", "आमी गोंय वचतले", "Aami Goay vochtele"),
    ("They will wait here.", "ते हांगा रावतले", "Te haangaa raavtele"),
    ("I will learn Konkani.", "हांव कोंकणी शिकतलों", "Haanv Konkani shiktalon"),
    ("You will understand.", "तुका समजतलें", "Tuka samjatalem"),
    ("He will help us.", "तो आमकां मदत करतलो", "To aamkaan madat kartalo"),
    ("She will bring water.", "ती उदक हाडतली", "Ti udak haadtali"),
    ("We will start now.", "आमी आतां सुरवात करतले", "Aami aataa survaat kartale"),
]

QUESTIONS = [
    ("What is this?", "हें कितें?", "Hem kitem?"),
    ("Where is the bus?", "बस खंय आसा?", "Bas khanay aasaa?"),
    ("When will you come?", "तूं केन्ना येता?", "Tum kennaa yetaa?"),
    ("Why are you late?", "तूं उशीर का आसा?", "Tum usheer kaa aasaa?"),
    ("Who is he?", "तो कोण?", "To kon?"),
    ("How much is this?", "हाचो किती मोल?", "Haacho kiti mol?"),
    ("Which book?", "कितें पुस्तक?", "Kitem pustak?"),
    ("Is this yours?", "हें तुजें?", "Hem tujem?"),
    ("Can you help?", "तुमी मदत करूं शकता?", "Tumi madat karun shaktaa?"),
    ("Do you understand?", "तुका समजता?", "Tuka samjataa?"),
    ("Will you come?", "तूं येता?", "Tum yetaa?"),
    ("Did you eat?", "तूं जेवलो?", "Tum jevlo?"),
    ("Where do you work?", "तूं खंय काम करता?", "Tum khanay kaam kartaa?"),
    ("What is your name?", "तुजें नांव कितें?", "Tujem naanv kitem?"),
    ("How are you?", "तुमी कशे आसात?", "Tumi kashe aasaat?"),
    ("May I sit?", "म्हाका बसूं येता?", "Mhaakaa basun yetaa?"),
    ("Could you repeat?", "तुमी परत उलयता?", "Tumi parat ulaytaa?"),
]

NEGATIVE = [
    ("I do not know.", "म्हाका खबर ना", "Mhaakaa khabar naa"),
    ("I will not go.", "हांव वचनां", "Haanv vachnaan"),
    ("You should not worry.", "तुका काळजी करूंक ना", "Tuka kaalzi karunk naa"),
    ("He did not come.", "तो आयनां", "To aaynaan"),
    ("She is not here.", "ती हांगा ना", "Ti haangaa naa"),
    ("We have no time.", "आमकां वेळ ना", "Aamkaan vell naa"),
    ("They are not ready.", "ते तयार नात", "Te tayaar naat"),
    ("I do not want this.", "म्हाका हें नाका", "Mhaakaa hem naakaa"),
    ("Do not run.", "धांवनाका", "Dhaanvaakaa"),
    ("I never lie.", "हांव खोट उलयनां", "Haanv khot ulaynaan"),
    ("Nothing is wrong.", "कितें चूक ना", "Kitem chook naa"),
    ("He does not eat meat.", "तो मास खायनां", "To maas khaaynaan"),
    ("She cannot swim.", "ती पोहूंक शकना", "Ti pohunk shaknaa"),
    ("We did not see him.", "आमी ताका पळयनां", "Aami taaka pallaynaan"),
    ("They will not leave.", "ते वचनात", "Te vachnaat"),
    ("I am not angry.", "हांव रागी ना", "Haanv raagi naa"),
    ("This is not mine.", "हें म्हजें ना", "Hem mhajem naa"),
]

POSSESSION = [
    ("I have a book.", "म्हजें एक पुस्तक आसा", "Mhajem ek pustak aasaa"),
    ("Do you have money?", "तुजें पयशे आसात?", "Tujem payshe aasaat?"),
    ("She has two brothers.", "तिका दोन भाव आसात", "Tikaa don bhaav aasaat"),
    ("We have time today.", "आमकां आयज वेळ आसा", "Aamkaan aayaj vell aasaa"),
    ("They have a new car.", "तांचें नवें कार आसा", "Taanchem nave kaar aasaa"),
    ("I have a headache.", "म्हजें तकली दुखता", "Mhajem takli dukhtaa"),
    ("He has no fear.", "ताका भय ना", "Taakaa bhay naa"),
    ("My house is small.", "म्हजें घर ल्हान", "Mhajem ghor lhaan"),
    ("Your idea is good.", "तुजो विचार बरो", "Tujo vichaar baro"),
    ("Our school is near.", "आमचें इस्कोल लागीं", "Aamchem iskol laagim"),
    ("Their shop is closed.", "तांचें दुकान बंद", "Taanchem dukaan band"),
    ("I need help.", "म्हाका मदत जाय", "Mhaakaa madat jaay"),
    ("She needs rest.", "तिका विश्रांती जाय", "Tikaa vishraanti jaay"),
    ("We need water.", "आमकां उदक जाय", "Aamkaan udak jaay"),
    ("I have finished work.", "म्हजें काम संपलें", "Mhajem kaam samplem"),
    ("Do you have change?", "तुजें सुट्टे आसात?", "Tujem sutte aasaat?"),
    ("He has many friends.", "ताका खूब इश्ट आसात", "Taakaa khoob isht aasaat"),
]

SCRIPT_PRONUNCIATION = [
    ("Practice the vowel अ — it sounds like 'a' in 'about'.", "अ हें पयलें स्वर", "A hem paylem swar"),
    ("Practice the vowel आ — longer 'aa'.", "आ दीसता दीर्घ स्वर", "A deestaa deergh swar"),
    ("The consonant क is a guttural 'ka'.", "क म्हल्यार कान आसा", "K mhalyaar kaan aasaa"),
    ("Write ख and say it clearly: 'kha'.", "ख स्पष्ट उच्चार कर", "Kha spasht uchchaar kar"),
    ("ग is voiced 'ga' as in 'gun'.", "ग आवाज घालून बोल", "Ga aawaaz ghaalun bol"),
    ("Nasal अं needs a soft nose sound.", "अं नाकाचो आवाज", "An naakaacho aawaaz"),
    ("Combine क + अ to read क.", "क अ मेळून क", "K a melun ka"),
    ("Read slowly: क ख ग घ.", "हळू वाच: क ख ग घ", "Halu vaach: k kha ga gha"),
    ("Barakhadi links consonants with vowels.", "बाराखडी जोडाक्षरांत मेलटा", "Baarakodi jodakshraant meltaa"),
    ("Retroflex ट is made with the tongue curled back.", "ट जिभ फिरोवन", "T jibh firovon"),
    ("Do not mix ट and त — listen carefully.", "ट आनी त वेगळे", "T aani t vegle"),
    ("Practice जोडाक्षर: स्त, क्त.", "जोडाक्षर स्त क्त", "Jodakshar st kt"),
    ("The letter र changes shape in clusters.", "र जोडाक्षरांत बदलता", "Ra jodakshraant badaltaa"),
    ("ह at the end of a cluster is soft.", "ह शेवटी हलका", "Ha shevoti halkaa"),
    ("Read this word aloud: घर.", "हें उलय: घर", "Hem ulay: ghor"),
    ("Read this word aloud: नमस्कार.", "हें उलय: नमस्कार", "Hem ulay: namaskaar"),
    ("Stress usually falls on the last syllable.", "साधारणपणान शेवटचो शब्द जोर", "Saadhaaranpann shevatacho shabd zor"),
]

SHOPPING = [
    ("How much is this?", "हाचो किती मोल?", "Haacho kiti mol?"),
    ("That is too expensive.", "तें खूब म्हारग", "Tem khoob mhaarag"),
    ("Give me a discount.", "म्हाका सूट दी", "Mhaakaa soot di"),
    ("I want to buy this.", "म्हाका हें घेवंक जाय", "Mhaakaa hem ghevank jaay"),
    ("Where is the shop?", "दुकान खंय आसा?", "Dukaan khanay aasaa?"),
    ("Pack it well.", "बरें बांदून दी", "Barem baandun di"),
    ("I need fresh vegetables.", "म्हाका ताजी भाजी जाय", "Mhaakaa taaji bhaaji jaay"),
    ("One kilo, please.", "एक किलो दी", "Ek kilo di"),
    ("Do you take cards?", "कार्ड घेतात?", "Card ghetaat?"),
    ("Give me the bag.", "म्हाका पोतें दी", "Mhaakaa potem di"),
    ("This quality is good.", "हें बरें दर्जाचें", "Hem barem darjaachem"),
    ("I will come again.", "हांव परत येतलों", "Haanv parat yetlon"),
    ("Show me that one.", "म्हाका तें दाखय", "Mhaakaa tem daakhay"),
    ("Any other colour?", "दुसरो रंग आसा?", "Dusaro rang aasaa?"),
    ("Keep the change.", "सुट्टे दवरा", "Sutte davraa"),
    ("Is there a sale?", "सूट आसा?", "Soot aasaa?"),
    ("I like this cloth.", "म्हाका हो कपडो आवडटा", "Mhaakaa ho kapdo aavdataa"),
]

HEALTH = [
    ("I need a doctor.", "म्हाका दोतोर जाय", "Mhaakaa dotor jaay"),
    ("Where is the hospital?", "हॉस्पिटल खंय आसा?", "Hospital khanay aasaa?"),
    ("I have a fever.", "म्हाका ताप आयला", "Mhaakaa taap aaylaa"),
    ("My head hurts.", "म्हजें तकली दुखता", "Mhajem takli dukhtaa"),
    ("My stomach hurts.", "म्हजें पोट दुखता", "Mhajem pot dukhtaa"),
    ("Please help me.", "उपकार करून म्हाका मदत करा", "Upkaar karun mhaakaa madat karaa"),
    ("Call an ambulance.", "ॲम्ब्युलन्स आपय", "Ambulance aapay"),
    ("I need medicine.", "म्हाका वखद जाय", "Mhaakaa vakhad jaay"),
    ("I am not feeling well.", "म्हाका बरें दिसना", "Mhaakaa barem disnaa"),
    ("Rest for a day.", "एक दीस विश्रांत घे", "Ek dis vishraant ghe"),
    ("Drink more water.", "आनीक उदक पी", "Aanik udak pi"),
    ("Take this tablet.", "हें गोळी घे", "Hem goli ghe"),
    ("When did it start?", "केन्ना सुरू जालें?", "Kennaa suru zaalem?"),
    ("Do you have pain here?", "हांगा दुखता?", "Haangaa dukhtaa?"),
    ("I feel better now.", "आतां म्हाका बरें दिसता", "Aataa mhaakaa barem distaa"),
    ("She is recovering.", "ती बरी जाता", "Ti bori jaataa"),
    ("We will wait outside.", "आमी भायल्यां रावतले", "Aami bhaaylyaan raavtele"),
]

TRAVEL = [
    ("Where is the bus stop?", "बस स्टॉप खंय आसा?", "Bus stop khanay aasaa?"),
    ("One ticket to Panaji.", "पणजी एक तिकीट", "Panji ek ticket"),
    ("When does the bus leave?", "बस केन्ना निघता?", "Bas kennaa nighataa?"),
    ("Stop here, please.", "हांगा थांब", "Haangaa thaamb"),
    ("How far is the beach?", "समुद्र कितलें दूर?", "Samudr kitlem door?"),
    ("I am lost.", "हांव वाट चुकलों", "Haanv vaat chuklon"),
    ("Turn left.", "दावीकडेन वळ", "Daavikaden vall"),
    ("Turn right.", "उजवीकडेन वळ", "Ujvikaden vall"),
    ("Go straight.", "सरळ वच", "Sarall voch"),
    ("Is this the right road?", "ही वाट बरोबर?", "Hi vaat barobar?"),
    ("Call a taxi.", "टॅक्सी आपय", "Taxi aapay"),
    ("The train is late.", "ट्रेन उशीर आसा", "Train usheer aasaa"),
    ("I need an auto.", "म्हाका ऑटो जाय", "Mhaakaa auto jaay"),
    ("Drop me at the hotel.", "हॉटेलाक सोड", "Hotelaak sod"),
    ("How much is the fare?", "भाडें किती?", "Bhaadden kiti?"),
    ("Keep the ticket.", "तिकीट दवरा", "Ticket davraa"),
    ("Where is the airport?", "विमानतळ खंय?", "Vimaantall khanay?"),
]

# Vocabulary-style: word in context (English shows usage)
BODY = [
    ("My head hurts today.", "आयज म्हजें तकली दुखता", "Aaj mhajem takli dukhtaa"),
    ("Open your eyes.", "डोळे उगड", "Dolle ugad"),
    ("Wash your hands.", "हात धुवन घे", "Haat dhuvan ghe"),
    ("I broke my leg.", "म्हजो पाय फाटलो", "Mhajo paay faatlo"),
    ("She has a sweet voice.", "तिका गोड आवाज", "Tikaa god aawaaz"),
    ("Listen with both ears.", "दोन कानांनी आयक", "Don kaanaanni aayak"),
    ("He smiled with his lips.", "तानें ओठांनी हास्य केलें", "Taanem othaanni haasya kelem"),
    ("My tooth aches.", "म्हजें दात दुखता", "Mhajem daat dukhtaa"),
    ("Cold air in the nose.", "नाकांत थंड वारो", "Naakaant thand vaaro"),
    ("Strong shoulders.", "मजबूत खांदे", "Mazboot khaande"),
    ("Fold your arms.", "बाहू घुंडाळ", "Baahu ghundaall"),
    ("I cut my finger.", "म्हजो बोट कापलो", "Mhajo bot kaaplo"),
    ("She painted her nails.", "तीनें नखे रंग केले", "Tinem nakhe rang kele"),
    ("My neck is stiff.", "म्हजी मान कडक", "Mhaji maan kadak"),
    ("He has broad chest.", "ताका रुंद उरो", "Taakaa rund uro"),
    ("Walk on your feet.", "पायांनी चल", "Paayaanni chal"),
    ("The baby’s skin is soft.", "भुरग्याची त्वचा मऊ", "Bhurgyaachi tvachaa mau"),
]

NUMBERS = [
    ("One", "एक", "Ek"),
    ("Two", "दोन", "Don"),
    ("Three", "तीन", "Teen"),
    ("Four", "चार", "Chaar"),
    ("Five", "पांच", "Paanch"),
    ("Six", "सा", "Saa"),
    ("Seven", "सात", "Saat"),
    ("Eight", "आठ", "Aath"),
    ("Nine", "नव", "Nav"),
    ("Ten", "दहा", "Dahaa"),
    ("Eleven", "अकरा", "Aakraa"),
    ("Twelve", "बारा", "Baaraa"),
    ("Twenty", "वीस", "Vis"),
    ("Thirty", "तीस", "Tis"),
    ("Hundred", "शे", "She"),
    ("I have fifty rupees.", "म्हाका पन्नास रुपया आसात", "Mhaakaa pannaas rupaya aasaat"),
    ("Count from one to ten.", "एकापासून दहा पर्यंत मोज", "Ekaapaasun dahaa paryant moj"),
]

FAMILY = [
    ("My father works hard.", "म्हजो बापूय मेहनत करता", "Mhajo baapuy mehnat kartaa"),
    ("My mother cooks well.", "म्हजी आवय बरें शिजोवता", "Mhaji aavay barem shijovtaa"),
    ("His brother studies.", "ताचो भाव शिकता", "Taacho bhaav shiktaa"),
    ("Her sister sings.", "तिची भयण गाता", "Tichi bhayin gaataa"),
    ("Our grandparents are kind.", "आमचे आजो-आजी दयाळ", "Aamche aajo-aaji dayaal"),
    ("Their son is small.", "तांचो पूत ल्हान", "Taanco poot lhaan"),
    ("My friend helped me.", "म्हजो इश्ट म्हाका मदत केलो", "Mhajo isht mhaakaa madat kelo"),
    ("We visit relatives.", "आमी नातेवाईक मेळटात", "Aami naatevaik meltaat"),
    ("She is my wife.", "ती म्हजी बायल", "Ti mhaji baayil"),
    ("He is my husband.", "तो म्हजो घोव", "To mhajo ghov"),
    ("The child is sleeping.", "भुरगें निदता", "Bhurgem nidtaa"),
    ("Respect your elders.", "मोठ्यांचो मान दवर", "Mothyanchom maan davar"),
    ("My uncle lives in Margao.", "म्हजो मामो मडगांवांत रावता", "Mhajo maamo Madgaavant raavtaa"),
    ("Her aunt brought sweets.", "तिच्या मावशीन मिठाय घेतली", "Tichya maavshiin mithaay ghetli"),
    ("We are three siblings.", "आमी तीन भाव-भयण", "Aami teen bhaav-bhayin"),
    ("His daughter is clever.", "तिची धूव हुशार", "Tichi dhuv hushaar"),
    ("Our parents bless us.", "आमचे बापूय आवय आशीर्वाद दितात", "Aamche baapuy aavay aashirvaad ditaat"),
]

# Idioms / colourful lines (conversation flavour)
IDIOMS = [
    ("Slowly slowly we learn.", "हळू हळू शिकतात", "Halu halu shiktaat"),
    ("Little by little it gets better.", "थोडें थोडें बरें जाता", "Thodem thodem bere jaataa"),
    ("Heart is happy.", "काळीज आनंदी", "Kaaliz aanandi"),
    ("What to do now?", "आतां कितें करूं?", "Aataa kitem karun?"),
    ("Time will tell.", "वेळ सांगतलो", "Vell sangtalo"),
    ("God willing.", "देवाच्या मर्जीेन", "Devaachya marjien"),
    ("Come, let us sit.", "ये, बसूया", "Ye, basuyaa"),
    ("The day went well.", "दीस बरो गेलो", "Dis baro gelo"),
    ("Keep courage.", "धीर धर", "Dheer dhar"),
    ("Everything will be fine.", "सगळें बरें जातलें", "Saglem bere jatalem"),
    ("Do not fear.", "भी नाका", "Bhi naakaa"),
    ("Speak from the heart.", "काळीजांतल्यान उलय", "Kaalijaantlyaan ulay"),
    ("Patience is good.", "सय बरें", "Say barem"),
    ("This too shall pass.", "हें पण जातलें", "Hem pan jatalem"),
    ("Walk with love.", "मोगांनी चल", "Mogaanni chal"),
    ("Smile a little.", "थोडी हास्य कर", "Thodi haasya kar"),
    ("Listen more than you speak.", "उलयपेक्षा आयक", "Ulaypeksha aayak"),
]

# Script subtopics — words/sentences chosen to practise Devanagari (see Wikibooks Devanagari + Konkani orthography)
ANUSVAR_DRILLS = [
    ("Your name? (nasal in speech).", "तुजें नांव कितें?", "Tujem naanv kitem?"),
    ("My name is simple.", "म्हजें नांव सोपें", "Mhajem naanv sopem"),
    ("Goa is beautiful.", "गोंय सोंद आसा", "Goy sond aasaa"),
    ("Panaji is the capital.", "पणजी राजधानी", "Panji raajdhaani"),
    ("The bell rings at the temple.", "देवळाची घंट वाजता", "Devollaachi ghantt vaajtaa"),
    ("I eat with my hand.", "हांव हातांनी खातां", "Haanv haataanni khaataan"),
    ("The mango is sweet.", "आंबो गोड आसा", "Aambo god aasaa"),
    ("Evening prayer time.", "संध्याकाळी प्रार्थना", "Sandhyaakalli praarthanaa"),
    ("The lamp gives light.", "दिवो उजवाड दिता", "Divo ujwaad ditaa"),
    ("I feel cold wind.", "म्हाका थंड वारो लागता", "Mhaakaa thand vaaro laagtaa"),
    ("The road is long.", "वाट लांब आसा", "Vaat laamb aasaa"),
    ("We sing hymns.", "आमी भजन गातात", "Aami bhajan gaataat"),
    ("The child runs.", "भुरगें धांवता", "Bhurgem dhaanvtaa"),
    ("My mind is calm.", "म्हजें मन शांत", "Mhajem man shaant"),
    ("The garden is green.", "बाग हिरवी", "Baag hirvi"),
    ("Listen to the song.", "गीत आयक", "Geet aayak"),
    ("The shop is open.", "दुकान उगडें", "Dukaan ugadem"),
    ("I need rest today.", "म्हाका आयज विश्रांती जाय", "Mhaakaa aaj vishraanti jaay"),
    ("The sky is clear.", "आकाश साफ", "Aakaash saaf"),
    ("We thank everyone.", "आमी सगळ्यांक देव बरें करतात", "Aami saglyaank dev barem kartaat"),
]

BARAKHADI_DRILLS = [
    ("I eat — hear the verb ending.", "हांव शीत खातां", "Haanv sheet khaataan"),
    ("You drink — familiar form.", "तूं उदक पीता", "Tum udak peetaa"),
    ("He reads — third person.", "तो पुस्तक वाचता", "To pustak vaachtaa"),
    ("She cooks — feminine verb.", "ती जेवण शिजोवता", "Ti jevan shijovtaa"),
    ("We learn — plural verb.", "आमी शिकतात", "Aami shiktaat"),
    ("They walk — plural present.", "ते वाटेर चलतात", "Te vaater chaltaat"),
    ("I write — first person.", "हांव बरोवतां", "Haanv barovtaan"),
    ("You come — daily habit.", "तूं दर दीस येता", "Tum dar dis yetaa"),
    ("He sleeps — simple present.", "तो लवकर निदता", "To lavkar nidtaa"),
    ("She sings — present tense.", "ती गीत गाता", "Ti geet gaataa"),
    ("We play — we-form.", "आमी खेळतात", "Aami kheltaat"),
    ("They work — they-form.", "ते काम करतात", "Te kaam kartaat"),
    ("I see — visual verb.", "हांव पळयतां", "Haanv pallaytaan"),
    ("You listen — attention.", "तूं आयकता", "Tum aayaktaa"),
    ("He opens — transitive.", "तो दार उगडता", "To daar ugadataa"),
    ("She closes — opposite.", "ती दार धांपता", "Ti daar dhaamptaa"),
    ("We meet — social verb.", "आमी मेळतात", "Aami meltaat"),
    ("They wait — patient verb.", "ते रावतात", "Te raavtaat"),
    ("I thank — polite.", "हांव देव बरें करतां", "Haanv dev barem kartaan"),
    ("You help — kind act.", "तूं मदत करता", "Tum madat kartaa"),
]

MINIMAL_PAIR_DRILLS = [
    ("Say ka and kha clearly: ka.", "क स्पष्ट बोल", "K spasht bol"),
    ("Say ka and kha clearly: kha.", "ख स्पष्ट बोल", "Kha spasht bol"),
    ("Do not mix ta and tha.", "त आनी थ वेगळे", "T aani th vegle"),
    ("Do not mix da and dha.", "द आनी ध वेगळे", "D aani dh vegle"),
    ("Listen: pa versus pha.", "प आनी फ आयक", "P aani ph aayak"),
    ("Short a versus long aa.", "अ आनी आ वेगळे", "A aani aa vegle"),
    ("Retroflex ta is not dental ta.", "ट आनी त वेगळे", "Tt aani t vegle"),
    ("Nasal anusvara changes meaning.", "अं चो अर्थ वेगळो", "An cho arth veglo"),
    ("Stress the last syllable often.", "शेवटचो शब्द जोर", "Shevatacho shabd zor"),
    ("Read slowly first.", "हळू हळू वाच", "Halu halu vaach"),
    ("Repeat after the teacher.", "मास्तरां परत कर", "Maastaraan parat kar"),
    ("Record and compare.", "रेकॉर्ड कर आनी तुलना", "Record kar aani tulnaa"),
    ("Watch the lip shape.", "ओठांचो आकार पळय", "Othaanchom aakaar pallay"),
    ("Keep the tongue relaxed.", "जिभ शांत दवर", "Jibh shaant davar"),
    ("Practice every morning.", "दर सकाळ सराव", "Dar sakaal sarav"),
    ("Ask if unsure.", "शंका आसल्यार विचार", "Shankaa aslyaar vichaar"),
    ("Konkani keeps many Sanskrit sounds.", "कोंकणी संस्कृत ध्वनी दवरता", "Konkani Sanskrit dhvani davartaa"),
    ("Portuguese loans sound different.", "पुर्तगाली शब्द वेगळे", "Purrtagaali shabd vegle"),
    ("Calm speech is clearer.", "शांत उलय स्पष्ट", "Shaant ulay spasht"),
    ("Listen to native speakers.", "मूळ उलयपी आयक", "Mool ulaypi aayak"),
]

CLUSTER_RA_DRILLS = [
    ("We pray together.", "आमी एकठां प्रार्थना करतात", "Aami ekthaan praarthana kartaat"),
    ("The train arrived.", "ट्रेन आयली", "Train aayli"),
    ("I like cricket.", "म्हाका क्रिकेट आवडटा", "Mhaakaa cricket aavdataa"),
    ("The fruit is ripe.", "फळ पिकलें", "Fall piklem"),
    ("Come back soon.", "लवकर परत ये", "Lavkar parat ye"),
    ("The road is broken.", "वाट फाटली", "Vaat faatli"),
    ("He crossed the bridge.", "तानें पूल ओलांडलो", "Taanem pool olaandlo"),
    ("The price fell.", "भाव पडलो", "Bhav paddlo"),
    ("She bought a dress.", "तीनें फ्रॉक घेतली", "Tinem frock ghetli"),
    ("We saw the film.", "आमी फिल्म पळयली", "Aami film pallayli"),
    ("The bus stopped.", "बस थांबली", "Bas thaambli"),
    ("I need a ticket.", "म्हाका तिकीट जाय", "Mhaakaa ticket jaay"),
    ("The shop is far.", "दुकान दूर आसा", "Dukaan door aasaa"),
    ("They built a house.", "तेनें घर बांधलें", "Tenem ghor baandhlem"),
    ("The child cried.", "भुरगें रडलें", "Bhurgem radlem"),
    ("We reached home.", "आमी घरा पावलां", "Aami ghara paavlaan"),
    ("The star shines.", "तारो चमकता", "Taaro chamaktaa"),
    ("I trust my friend.", "हांव म्हज्या इश्टाचेर विश्वास दवरतां", "Haanv mhajya ishtaacher vishwaas davartaan"),
    ("The river flows.", "नदी वाहता", "Nadi vaahtaa"),
    ("Please bring water.", "उदक हाड", "Udak haad"),
]

CLUSTER_HA_DRILLS = [
    ("It is not there (common negative).", "तें ना", "Tem naa"),
    ("I do not want it.", "म्हाका नाका", "Mhaakaa naakaa"),
    ("Spring has come.", "बहर आयलो", "Bahar aaylo"),
    ("The story is nice.", "कहाणी बरी", "Khaanii bari"),
    ("Laugh a little.", "थोडें हास्य कर", "Thodem haasya kar"),
    ("The hand is clean.", "हात साफ", "Haat saaf"),
    ("Cold water.", "थंड उदक", "Thand udak"),
    ("The heart is kind.", "काळीज दयाळ", "Kaaliz dayaal"),
    ("Speak the truth.", "सत्य उलय", "Satya ulay"),
    ("The ghost story scared us.", "भूताची कहाणी लागली", "Bhutaachi khaanii laagli"),
    ("He lost courage.", "ताचें धैर्य गेलें", "Taachem dhairy gellem"),
    ("We heard the news.", "आमी बातमी आयकली", "Aami baatmi aayakli"),
    ("The field is green.", "शेत हिरवें", "Shet hirvem"),
    ("She held the baby.", "तीनें भुरगें धरलें", "Tinem bhurgem dharem"),
    ("The threshold is high.", "उदकाठ उंच", "Udkaath unch"),
    ("I washed my face.", "हांव मुख धुवलें", "Haanv mukh dhuvlem"),
    ("The breath is steady.", "श्वास स्थिर", "Shwaas sthir"),
    ("Do not fear ghosts.", "भूतांक भी नाका", "Bhutaank bhi naakaa"),
    ("Happiness in the heart.", "काळीजांत आनंद", "Kaalijaant aanand"),
    ("The road is dusty.", "वाट धुळीची", "Vaat dhulichi"),
]

CLUSTER_GENERAL_DRILLS = [
    ("Student (sa + ta).", "विद्यार्थी शिकता", "Vidyaarthi shiktaa"),
    ("Temple (complex cluster).", "देवळ बरें दिसता", "Devoll barem distaa"),
    ("Picture is clear.", "चित्र स्पष्ट", "Chitra spasht"),
    ("Question paper is hard.", "प्रश्नपत्रिका कठीण", "Prashnapatrikaa kathin"),
    ("Victory is ours.", "विजय आमचो", "Vijay aamcho"),
    ("The field is wide.", "शेत रुंद", "Shet rund"),
    ("Effort brings success.", "प्रयत्न यश दिता", "Prayatn yash ditaa"),
    ("The nation is great.", "राष्ट्र मोठें", "Rashtr mothem"),
    ("Science helps life.", "विज्ञान जीवनाक मदत", "Vigyaan jeevnaak madat"),
    ("The letter is short.", "पत्र ल्हान", "Patr lhaan"),
    ("The picture fell.", "चित्र पडलें", "Chitra paddlem"),
    ("Trust is important.", "विश्वास म्हत्वाचो", "Vishwaas mhatvaacho"),
    ("The story spread.", "कथा पसरली", "Kathaa pasarli"),
    ("Practice makes perfect.", "सराव परिपूर्ण करता", "Sarav paripoorn kartaa"),
    ("The machine works.", "यंत्र चालता", "Yantra chaaltaa"),
    ("The officer came.", "अधिकारी आयलो", "Adhikaari aaylo"),
    ("The nation celebrates.", "राष्ट्र सण मनाता", "Rashtr san manaataa"),
    ("The student passed.", "विद्यार्थी पास जालो", "Vidyaarthi paas zaalo"),
    ("The question is easy.", "प्रश्न सोपो", "Prashn sopo"),
    ("The field needs water.", "शेताक उदक जाय", "Shetak udak jaay"),
]

IF_THEN_DRILLS = [
    ("If it rains, I stay home.", "जर पावस पडटा तर हांव घरा रावतां", "Jar paavas paddtaa tar haanv ghara raavtaan"),
    ("If you come, we eat.", "जर तूं येता तर आमी जेवतात", "Jar tum yetaa tar aami jevtaat"),
    ("If he calls, answer.", "जर तो फोन करता तर उत्तर दी", "Jar to phone kartaa tar uttar di"),
    ("If she is ready, we go.", "जर ती तयार आसा तर आमी वचतात", "Jar ti tayaar aasaa tar aami vachataat"),
    ("If it is late, sleep.", "जर उशीर जालो तर निद", "Jar usheer zaalo tar nid"),
    ("If you want, take it.", "जर तुका जाय तर घे", "Jar tuka jaay tar ghe"),
    ("If they agree, we start.", "जर ते मानतात तर आमी सुरू करतात", "Jar te maantaat tar aami suru kartaat"),
    ("If I am free, I come.", "जर हांव मोकळो आसां तर हांव येतां", "Jar haanv mokallo aasaan tar haanv yetaan"),
    ("If the bus leaves, run.", "जर बस निघता तर धांव", "Jar bas nighataa tar dhaanv"),
    ("If food is ready, call me.", "जर जेवण तयार आसा तर म्हाका आपय", "Jar jevan tayaar aasaa tar mhaakaa aapay"),
    ("If you understand, say yes.", "जर तुका समजता तर हो म्हण", "Jar tuka samjataa tar ho mhon"),
    ("If it is hot, drink water.", "जर उष्ण आसा तर उदक पी", "Jar ushna aasaa tar udak pi"),
    ("If we meet, we talk.", "जर आमी मेळतात तर आमी उलयतात", "Jar aami meltaat tar aami ulaytaat"),
    ("If the shop is open, buy.", "जर दुकान उगडें आसा तर घे", "Jar dukaan ugadem aasaa tar ghe"),
    ("If you are tired, rest.", "जर तूं थकलो आसा तर विश्रांत घे", "Jar tum thaklo aasaa tar vishraant ghe"),
    ("If the road is bad, go slow.", "जर वाट खराब आसा तर हळू वच", "Jar vaat kharaab aasaa tar halu voch"),
    ("If help is needed, ask.", "जर मदत जाय तर विचार", "Jar madat jaay tar vichaar"),
    ("If tomorrow is free, come.", "जर फाल्यां मोकळें आसा तर ये", "Jar faalyaan mokalem aasaa tar ye"),
    ("If the child sleeps, be quiet.", "जर भुरगें निदता तर शांत", "Jar bhurgem nidtaa tar shaant"),
    ("If Konkani is easy, learn it.", "जर कोंकणी सोपी आसा तर शिक", "Jar Konkani sopi aasaa tar shik"),
]

CONJUNCTION_DRILLS = [
    ("I came and I sat.", "हांव आयलों आनी बसलों", "Haanv aaylon aani baslon"),
    ("He ate and he drank.", "तानें जेवलें आनी पियलें", "Taanem jevlem aani piyalem"),
    ("Small but strong.", "ल्हान पण मजबूत", "Lhaan pan mazboot"),
    ("I wanted to go but I stayed.", "हांव वचपाक इच्छीत आशिल्लों पण रावलों", "Haanv vochpaak ichchit aashillon pan raavlon"),
    ("Because of rain I stayed home.", "पावसाक लागून हांव घरा रावलों", "Paavsaaka laagun haanv ghara raavlon"),
    ("So we left early.", "म्हणून आमी लवकर निघलां", "Mhoon aami lavkar nighlaan"),
    ("He spoke and we listened.", "तानें उलयलें आनी आमी आयकलां", "Taanem ulaylem aani aami aayaklaan"),
    ("She cooked and we ate.", "तीनें शिजवलें आनी आमी जेवलां", "Tinem shijavlem aani aami jevlaan"),
    ("Cold yet refreshing.", "थंड पण ताजें", "Thand pan taajem"),
    ("I tried but failed.", "हांव प्रयत्न केलो पण नापास जालों", "Haanv prayatn kelo pan naapaas zaalon"),
    ("Open the door and enter.", "दार उगड आनी भितर ये", "Daar ugad aani bhitur ye"),
    ("Read and write daily.", "दर दीस वाच आनी बरोव", "Dar dis vaach aani barov"),
    ("Neither hot nor cold.", "न उष्ण न थंड", "Na ushna na thand"),
    ("If you agree, we proceed.", "जर तूं मानता तर आमी पुढें वचतात", "Jar tum maantaat tar aami pudem vachataat"),
    ("Although tired, he worked.", "थकलो आशिल्लो तरी तानें काम केलें", "Thaklo aashillo tari taanem kaam kelem"),
    ("Before sleep, pray.", "निदपाक आदीं प्रार्थना कर", "Nidpaak aadim praarthana kar"),
    ("After eating, wash hands.", "जेवून हात धुवन घे", "Jevun haat dhuvan ghe"),
    ("This and that.", "हें आनी तें", "Hem aani tem"),
    ("You or me?", "तूं वा हांव?", "Tum vaa haanv?"),
    ("Neither this nor that.", "न हें न तें", "Na hem na tem"),
]

PASSIVE_LIGHT_DRILLS = [
    ("The food was cooked.", "जेवण शिजवलें", "Jevan shijavlem"),
    ("The door was opened.", "दार उगडलें", "Daar ugadle"),
    ("The letter was written.", "पत्र बरयलें", "Patr baraylem"),
    ("The work was finished.", "काम संपलें", "Kaam samplem"),
    ("The lamp was lit.", "दिवो लावलो", "Divo laavlo"),
    ("The house was cleaned.", "घर साफ केलें", "Ghor saaf kelem"),
    ("The bus was stopped.", "बस थांबोवली", "Bas thaambovli"),
    ("The ticket was given.", "तिकीट दिलें", "Ticket dilem"),
    ("The news was heard.", "बातमी आयकली", "Baatmi aayakli"),
    ("The book was read.", "पुस्तक वाचलें", "Pustak vaachlem"),
    ("The song was sung.", "गीत गायलें", "Geet gaaylem"),
    ("The rice was served.", "शीत वाडलें", "Sheet vaadlem"),
    ("The window was closed.", "जनेल धांपलें", "Janel dhaamplem"),
    ("The money was counted.", "पयशे मोजले", "Payshe mojle"),
    ("The path was cleared.", "वाट साफ केली", "Vaat saaf keli"),
    ("The guest was welcomed.", "पावल्याचें येवकार केलें", "Paavlyaachem yevkaar kelem"),
    ("The medicine was taken.", "वखद घेतलें", "Vakhad ghetlem"),
    ("The mistake was seen.", "चूक पळयली", "Chook pallayli"),
    ("The answer was given.", "उत्तर दिलें", "Uttar dilem"),
    ("The field was ploughed.", "शेत नांगरलें", "Shet naangarlem"),
]

CAUSATIVE_LIGHT_DRILLS = [
    ("I got the work done.", "हांव काम दवरलें", "Haanv kaam davarlem"),
    ("She made him sing.", "तीनें ताका गावंक लायलें", "Tinem taaka gaavunk laaylem"),
    ("We had the house painted.", "आमी घर रंग दवरलें", "Aami ghor rang davarlem"),
    ("He made me sit.", "तानें म्हाका बसयलें", "Taanem mhaakaa basaylem"),
    ("They got the car repaired.", "तेनें कार रिपेअर दवरलें", "Tenem kaar repair davarlem"),
    ("I let the child play.", "हांव भुरग्याक खेळूंक दिलें", "Haanv bhurgyaak khelunk dilem"),
    ("She sent me to buy.", "तीनें म्हाका घेवंक धाडलें", "Tinem mhaakaa ghevunk dhaadlem"),
    ("We made them understand.", "आमी तांकां समजावलें", "Aami taankaan samjaavlem"),
    ("He got the door opened.", "तानें दार उगडयलें", "Taanem daar ugadaylem"),
    ("I had food cooked.", "हांव जेवण शिजवयलें", "Haanv jevan shijavaylem"),
    ("They made her laugh.", "तेनें तिका हास्य करयलें", "Tenem tikaa haasya karaylem"),
    ("We got the bill brought.", "आमी बिल हाडयलें", "Aami bill haadaylem"),
    ("He made me wait.", "तानें म्हाका रावयलें", "Taanem mhaakaa raavaylem"),
    ("She let us go.", "तीनें आमकां वचूंक दिलें", "Tinem aamkaan vochunk dilem"),
    ("I got the key made.", "हांव चावी बनयलें", "Haanv chaavi banaylem"),
    ("They had the road fixed.", "तेनें वाट बनयलें", "Tenem vaat banaylem"),
    ("We made him read.", "आमी ताका वाचयलें", "Aami taaka vaachaylem"),
    ("He got the shop closed.", "तानें दुकान बंद दवरलें", "Taanem dukaan band davarlem"),
    ("I let her rest.", "हांव तिका विश्रांत घेवंक दिलें", "Haanv tikaa vishraant ghevunk dilem"),
    ("She made the child study.", "तीनें भुरग्याक शिकयलें", "Tinem bhurgyaak shikaylem"),
]

WOMENS_DAY_DRILLS = [
    ("Happy Women's Day.", "स्त्री दिनाच्यो शुभेच्छा", "Stree dinaachyo shubhecchaa"),
    ("Women bring strength to the family.", "बायलां कुटुंबाक बळ दितात", "Baaylaan kutumbaak ball ditaat"),
    ("Respect every woman.", "दर स्त्रीक मान दी", "Dar streek maan di"),
    ("Her courage inspires us.", "तिचें धैर्य आमकां प्रेरणा दिता", "Tichem dhairy aamkaan praeranaa ditaa"),
    ("We celebrate equality.", "आमी समानतेचो सण मनोवतात", "Aami samaanatecho san manovtaat"),
    ("Education for all girls.", "सगळ्या भुरग्यांक शिक्षण", "Saglya bhurgyaank shikshan"),
    ("Mother is our first teacher.", "आवय आमची पयली शिक्षिका", "Aavay aamchi payli shikshikaa"),
    ("Sisters support each other.", "भयणी एकमेकांक मदत करतात", "Bhayini ekamekaank madat kartaat"),
    ("She leads with kindness.", "ती दयाळपणान नेतृत्व करता", "Ti dayaalpannaan netruttw kartaa"),
    ("Workplace respect matters.", "कामाचेर मान म्हत्वाचो", "Kaamaacher maan mhatvaacho"),
    ("Dreams have no gender.", "सोपणांक लिंग ना", "Sopnaank ling naa"),
    ("We honour mothers today.", "आयज आवयांक मान दिवन", "Aaj avaayank maan divun"),
    ("Her voice is powerful.", "तिचो आवाज बळी आसा", "Ticho aawaaz bali aasaa"),
    ("Together we rise.", "एकठां आमी वाडटात", "Ekthaan aami vaaddtaat"),
    ("Peace begins at home.", "शांती घरांतल्यान सुरू", "Shaanti gharaantlyaan suru"),
    ("Teach daughters confidence.", "धुवांक आत्मविश्वास शिकोव", "Dhuvaan kaatmavishwaas shikov"),
    ("Communities need women leaders.", "समाजाक बायल नेते जाय", "Samaajaak baayil nete jaay"),
    ("Gratitude to all women.", "सगळ्या स्त्रीक उपकार", "Saglya streek upkaar"),
    ("May her path be bright.", "तिची वाट उजवाड आसूं", "Tichi vaat ujwaad aasum"),
    ("We stand with women.", "आमी स्त्री सोबत आसात", "Aami stree sobat aasaat"),
]

ECLIPSE_DRILLS = [
    ("Today there is a solar eclipse.", "आयज सूर्यग्रास आसा", "Aaj sooryagraas aasaa"),
    ("Do not look at the sun directly.", "सूर्याक थेट पळयनाका", "Sooryaak thet pallaynaakaa"),
    ("Use safe glasses.", "सुरक्षित चष्मे वापर", "Surakshit chashme vaapar"),
    ("Children should stay indoors.", "भुरगीं घरांत रावूंक जाय", "Bhurgim gharaant raavunk jaay"),
    ("The sky will look dark.", "आकाश काळें दिसतलें", "Aakaash kaalem distalem"),
    ("People bathe after the eclipse.", "ग्रास उपरांत लोक न्हातात", "Graas upraant lok nhaataat"),
    ("We cook fresh food after.", "आमी उपरांत ताजें जेवण शिजोवतात", "Aami upraant taajem jevan shijovtaat"),
    ("Elders tell old stories.", "मोठ्यां जुण्यो कथा सांगतात", "Mothyaa junyo kathaa sangtaat"),
    ("Do not eat during the eclipse.", "ग्रासाच्या वेळार जेवनाका", "Graasaachya vellaar jevnaakaa"),
    ("The birds become quiet.", "सुकणीं शांत जातात", "Suknim shaant jaataat"),
    ("We pray for safety.", "आमी सुरक्षे खातीर प्रार्थना करतात", "Aami surakshye khatir praarthana kartaat"),
    ("The temple bells ring.", "देवळाची घंट वाजता", "Devollaachi ghantt vaajtaa"),
    ("I read about eclipses.", "हांव ग्रासाविशीं वाचतां", "Haanv graasaavishim vaachtaan"),
    ("Science explains the eclipse.", "विज्ञान ग्रास समजावता", "Vigyaan graas samjaavtaa"),
    ("Share correct information.", "बरोबर म्हायती वांट", "Barobar maayati vaant"),
    ("Protect your eyes.", "डोळ्यांची राखण कर", "Dolyaanchi raakhan kar"),
    ("The moon covers the sun.", "चंद्र सूर्याक झाकता", "Chondro sooryaak zhaaktaa"),
    ("Neighbours gather on the roof.", "पडोशी छताचेर एकठां", "Padoshi chataacher ekthaan"),
    ("After eclipse, clean the house.", "ग्रास उपरांत घर साफ कर", "Graas upraant ghor saaf kar"),
    ("May everyone be safe.", "सगळ्यांक सुरक्षा मेळूं", "Saglyaank surakshaa melum"),
]

SOCIAL_MEDIA_DRILLS = [
    ("I posted a photo today.", "हांव आयज फोटो टाकलो", "Haanv aaj photo taaklo"),
    ("She liked my comment.", "तीनें म्हजो टिप्पणी आवडलो", "Tinem mhajo tippanni aavaddlo"),
    ("Too much screen time hurts eyes.", "स्क्रीन वेळ डोळ्यांक दुखो दिता", "Screen vell dolyaank dukho ditaa"),
    ("We chat on the phone.", "आमी फोनाचेर गप्पा मारतात", "Aami fonaacher gappa maartaat"),
    ("Do not share passwords.", "पासवर्ड वांटनाका", "Password vaantnaakaa"),
    ("He sent a voice note.", "तानें व्हॉइस नोट धाडलो", "Taanem voice note dhaadlo"),
    ("The video went viral.", "व्हिडिओ व्हायरल जालो", "Video viral zaalo"),
    ("I follow good pages.", "हांव बरें पानां फॉलो करतां", "Haanv barem paanaan follow kartaan"),
    ("She blocked fake news.", "तीनें खोटी बातमी ब्लॉक केली", "Tinem khoti baatmi block keli"),
    ("We learn Konkani online too.", "आमी ऑनलायनय कोंकणी शिकतात", "Aami onliney Konkani shiktaat"),
    ("Turn off notifications at night.", "राती नोटिफिकेशन बंद कर", "Raati notification band kar"),
    ("Talk politely in comments.", "टिप्पणींत सभ्य उलय", "Tippannint sabhya ulay"),
    ("My data should stay private.", "म्हजो डेटा खाजगी रावूंक जाय", "Mhajo data khaajgi raavunk jaay"),
    ("He shared a helpful link.", "तानें उपकारी लिंक वांटली", "Taanem upkaari link vaantli"),
    ("We avoid toxic groups.", "आमी विषारी गट टाळतात", "Aami vishaari gatt taaltaat"),
    ("I deleted the app.", "हांव ॲप काडलो", "Haanv app kaadlo"),
    ("She uploaded a story.", "तीनें स्टोरी अपलोड केली", "Tinem story upload keli"),
    ("Parents guide children online.", "बापूय भुरग्यांक ऑनलायन मार्ग दितात", "Baapuy bhurgyaank online maarg ditaat"),
    ("Balance real life and screens.", "खरी जीवन आनी स्क्रीन संतुलन", "Khari jeevan aani screen santulan"),
    ("Digital kindness matters.", "डिजिटल दयाळपण म्हत्वाचें", "Digital dayaalpon mhatvaachem"),
]

JOKES_LIGHT_DRILLS = [
    ("Why did the cat sit? — For a nap.", "मांजर खंय बसलें? — निदाक.", "Maanjer khanay baslem? — Nidaak."),
    ("The crow said: caw!", "कावळ्यान म्हणलें: काँ!", "Kaavlyaan mhonlem: kaa!"),
    ("Two friends and one banana — sharing!", "दोन इश्ट आनी एक केळी — वांट!", "Don isht aani ek keli — vaant!"),
    ("Teacher: be quiet. Student: yes!", "मास्तर: शांत. विद्यार्थी: हो!", "Maastar: shaant. Vidyaarthi: ho!"),
    ("I forgot the joke halfway.", "हांव विनोद मध्येच विसरलों", "Haanv vinod madhyech visaron"),
    ("Grandpa tells the best jokes.", "आजो सगळ्यांत बरो विनोद सांगता", "Aajo saglyaat baro vinod sangtaa"),
    ("Laughter is good medicine.", "हास्य बरें वखद", "Haasya barem vakhad"),
    ("The mirror never lies.", "आरसो खोट उलयना", "Aaraso khot ulaynaa"),
    ("Small joke, big smile.", "ल्हान विनोद, मोठी हास्य", "Lhaan vinod, mothi haasya"),
    ("Do not joke in class.", "वर्गांत विनोद नाका", "Vargaant vinod naakaa"),
    ("He slipped on a peel — ouch!", "तो सुरी वर पडलो — अहो!", "To suri var paddlo — aho!"),
    ("The dog chased its tail.", "शुना आपलें शेपट धांवलो", "Shunaa aplem shepatt dhaanvlo"),
    ("Why is the sky blue? — Ask science!", "आकाश निळें खंय? — विज्ञानाक विचार!", "Aakaash nilem khanay? — vigyaanaak vichaar!"),
    ("Two plus two is four — not five!", "दोन आनी दोन चार — पांच ना!", "Don aani don chaar — paanch naa!"),
    ("The phone rang — it was mom.", "फोन वाजलो — आवय आशिल्ली", "Fon vaajlo — aavay aashilli"),
    ("Late for school again!", "स्कोलाक परत उशीर!", "Skolaak parat usheer!"),
    ("Grandma’s story never ends.", "आजीची कथा सोंपना", "Aajichi kathaa sompnaa"),
    ("Smile at strangers sometimes.", "कदाचित परक्यांक हास्य", "Kadaachit parakyaank haasya"),
    ("Fun keeps the heart young.", "मजा काळीज तरूण दवरता", "Maja kaaliz tarun davartaa"),
    ("That was a silly joke.", "हो मूर्खपणाचो विनोद", "Ho murkhapannaacho vinod"),
]

QUARREL_HOME_DRILLS = [
    ("Please lower your voice.", "उन्च आवाज कमी कर", "Unch aawaaz kami kar"),
    ("Let us not fight at home.", "घरांत भांडण नाका", "Gharaant bhaandan naakaa"),
    ("I did not mean to hurt you.", "म्हाका तुका दुखोवपाचो न्हय", "Mhaakaa tuka dukhovpacho nhay"),
    ("Sit and talk calmly.", "बसून शांत उलय", "Basun shaant ulay"),
    ("We can solve this together.", "हें आमी एकठां सोडोवंक शकतात", "Hem aami ekthaan sodovunk shaktaat"),
    ("Sorry for my words.", "म्हज्या उलयां खातीर माफी", "Mhajya ulayaank khatir maafi"),
    ("Listen before you shout.", "उलयपाक आदीं आयक", "Ulaypaak aadim aayak"),
    ("The children are scared.", "भुरगीं भीतर आसात", "Bhurgim bhitur aasaat"),
    ("Let us take a break.", "थोडी विश्रांत घेवया", "Thodi vishraant ghevoyaa"),
    ("I understand your worry.", "म्हाका तुजी काळजी समजता", "Mhaakaa tuji kaalzi samjataa"),
    ("Do not bring up old fights.", "जुणी भांडणी नाका", "Juni bhaandani naakaa"),
    ("We need patience.", "आमकां सय जाय", "Aamkaan say jaay"),
    ("Speak with respect.", "मानान उलय", "Maanan ulay"),
    ("I will help clean up.", "हांव साफ करपाक मदत करतलों", "Haanv saaf karapak madat kartalon"),
    ("Let the elders advise.", "मोठ्यां सल्लो दिवन द्या", "Mothyaa sallo divun dya"),
    ("Anger cools with time.", "राग वेळेन थंड जाता", "Raag velen thand jaataa"),
    ("Forgive and move on.", "माफ कर आनी पुढें वच", "Maaf kar aani pudem voch"),
    ("Home should feel safe.", "घर सुरक्षित दिसूंक जाय", "Ghor surakshit disunk jaay"),
    ("We love this family.", "आमी हो कुटुंब मोग करतात", "Aami ho kutumb mog kartaat"),
    ("Tomorrow will be better.", "फाल्यां बरें जातलें", "Faalyaan bere jatalem"),
]

REPUBLIC_DAY_DRILLS = [
    ("Happy Republic Day.", "प्रजासत्ताक दिनाच्यो शुभेच्छा", "Prajaasattaak dinaachyo shubhecchaa"),
    ("We salute the flag.", "आमी झाड्याक सलामी दितात", "Aami zhaadyaak salaami ditaat"),
    ("The parade is grand.", "परेड भव्य आसा", "Parade bhavya aasaa"),
    ("We sing the national song.", "आमी राष्ट्रगीत गातात", "Aami rashtrgeet gaataat"),
    ("India is diverse and united.", "भारत वैविध्यान एक", "Bharat vaividhyaan ek"),
    ("Children march in school.", "भुरगीं स्कोलांत परेड करतात", "Bhurgim skolaant parade kartaat"),
    ("We remember the Constitution.", "आमी राज्यघटना आठवतात", "Aami raajya ghattanaa aathavtaat"),
    ("Freedom brings responsibility.", "स्वातंत्र्य जबाबदारी दिता", "Swaatantry zabdaari ditaa"),
    ("Patriots built the nation.", "देशभक्तां राष्ट्र घडयलें", "Deshbhaktaan rashtr ghadaylem"),
    ("We celebrate 26 January.", "आमी २६ जानेवारी सण मनोवतात", "Aami 26 Janewari san manovtaat"),
    ("Honour the soldiers.", "सैनिकांक मान दी", "Sainikaank maan di"),
    ("Peace and progress together.", "शांती आनी प्रगती एकठां", "Shaanti aani pragati ekthaan"),
    ("The tricolour flies high.", "तिरंगा उंच उडटा", "Tirangaa unch uddtaa"),
    ("We pledge to work hard.", "आमी मेहनतीचो संकल्प करतात", "Aami mehnaticho sankalp kartaat"),
    ("Schools hoist the flag.", "स्कोलां झाडो उंचावतात", "Skolaan zhaado unchaavtaat"),
    ("Elders share freedom stories.", "मोठ्यां स्वातंत्र्याच्यो कथा", "Mothyaa swaantryaachyo kathaa"),
    ("Youth serve the nation.", "तरूण राष्ट्राक सेवा करतात", "Tarun rashtraak sevaa kartaat"),
    ("Unity is our strength.", "एकता आमचें बळ", "Ekata aamchem ball"),
    ("Respect every citizen.", "दर नागरिकाक मान दी", "Dar naagarikaak maan di"),
    ("Jai Hind!", "जय हिंद!", "Jai Hind!"),
]

DIWALI = [
    ("Happy Diwali to you.", "तुमकां दिवाळीच्यो शुभकामना", "Tumkaan divalichyo shubhkaamnaa"),
    ("Light lamps at home.", "घरांत दिवे लाव", "Gharaant dive laav"),
    ("We share sweets.", "आमी मिठाय वांटतात", "Aami mithaay vaanttaat"),
    ("The house looks bright.", "घर उजवाड दिसता", "Ghor ujwaad distaa"),
    ("Children burst crackers safely.", "भुरगीं सुरक्षित फटाळे फोडतात", "Bhurgim surakshit fataalle fodtaat"),
    ("May there be prosperity.", "समृद्धी आसूं", "Samruddhi aasum"),
    ("We wear new clothes.", "आमी नवे कपडे घालतात", "Aami nave kapde ghaltaat"),
    ("Guests visit our home.", "पावलां घरांत येतात", "Paavlaan gharaant yetaat"),
    ("I bought a lantern.", "हांव एक लॅंप घेतलों", "Haanv ek laamp ghetlon"),
    ("She made karanji.", "तीनें करांजी केली", "Tinem karaanji keli"),
    ("We pray together.", "आमी एकठां प्रार्थना करतात", "Aami ekthaan praarthana kartaat"),
    ("The sky is full of lights.", "आकाश दिव्यांनी भरलो", "Aakaash divyaanni bharlo"),
    ("Happy faces everywhere.", "सगळ्यांक आनंद", "Saglyaan kaanand"),
    ("Turn off lights when you sleep.", "निदताना दिवे बंद कर", "Nidtaana dive band kar"),
    ("Share joy with neighbours.", "पडोश्यांक आनंद वांट", "Padoshyaanka aanand vaant"),
    ("Diwali is my favourite festival.", "दिवाळी म्हजी आवडटी सण", "Divali mhaji aavddi san"),
    ("Come for dinner tonight.", "आयज राती जेवणाक ये", "Aaj raati jevnaak ye"),
]

BANK_REGISTRY = {
    "GREETINGS": GREETINGS,
    "DAILY": DAILY,
    "FOOD": FOOD,
    "PRONOUNS": PRONOUNS,
    "PRESENT": PRESENT,
    "PAST": PAST,
    "FUTURE": FUTURE,
    "QUESTIONS": QUESTIONS,
    "NEGATIVE": NEGATIVE,
    "POSSESSION": POSSESSION,
    "SCRIPT_PRONUNCIATION": SCRIPT_PRONUNCIATION,
    "SHOPPING": SHOPPING,
    "HEALTH": HEALTH,
    "TRAVEL": TRAVEL,
    "BODY": BODY,
    "NUMBERS": NUMBERS,
    "FAMILY": FAMILY,
    "IDIOMS": IDIOMS,
    "DIWALI": DIWALI,
    "READING_DRILLS": READING_DRILLS,
    "ANUSVAR_DRILLS": ANUSVAR_DRILLS,
    "BARAKHADI_DRILLS": BARAKHADI_DRILLS,
    "MINIMAL_PAIR_DRILLS": MINIMAL_PAIR_DRILLS,
    "CLUSTER_RA_DRILLS": CLUSTER_RA_DRILLS,
    "CLUSTER_HA_DRILLS": CLUSTER_HA_DRILLS,
    "CLUSTER_GENERAL_DRILLS": CLUSTER_GENERAL_DRILLS,
    "IF_THEN_DRILLS": IF_THEN_DRILLS,
    "CONJUNCTION_DRILLS": CONJUNCTION_DRILLS,
    "PASSIVE_LIGHT_DRILLS": PASSIVE_LIGHT_DRILLS,
    "CAUSATIVE_LIGHT_DRILLS": CAUSATIVE_LIGHT_DRILLS,
    "WOMENS_DAY_DRILLS": WOMENS_DAY_DRILLS,
    "ECLIPSE_DRILLS": ECLIPSE_DRILLS,
    "SOCIAL_MEDIA_DRILLS": SOCIAL_MEDIA_DRILLS,
    "JOKES_LIGHT_DRILLS": JOKES_LIGHT_DRILLS,
    "QUARREL_HOME_DRILLS": QUARREL_HOME_DRILLS,
    "REPUBLIC_DAY_DRILLS": REPUBLIC_DAY_DRILLS,
}

