# Curated Konkani triples [English, Devanagari, Roman] for lesson assembly.
# Sources: common Goan Konkani (Devanagari), Wikibooks Konkani/Greetings, Wikivoyage phrasebook
# patterns, Saraswat grammar blog style examples (subject + object + verb), in-app phrase style.

def target_row_count(chapter_id: int) -> int:
    """Each sublesson uses 15–20 rows (spread by chapter id)."""
    return 15 + (chapter_id % 6)  # 15, 16, … 20


# Legacy default for callers that omit chapter id
ROWS_PER_LESSON = 18

# --- Shared pools (extend / combine per chapter) ---
GREETINGS = [
    ("May God give you a good day.", "देव बरो दीस दीय", "Dev boro dis diiy"),
    ("May God give grace (reply to greeting).", "देव कुर्पा दीय", "Dev kurpa diiy"),
    ("How are you? (to a male, familiar)", "तूं कोशो आसाय?", "Tum kosho aasaay?"),
    ("How are you? (respectful / female older)", "तुमी कशीं आसात?", "Tumi kasheen aasaat?"),
    ("I am fine (male).", "हांव बरो आसां", "Haanv baro aasaan"),
    ("I am fine (female).", "हांव बरी आसां", "Haanv bari aasaan"),
    ("Thank you.", "देव बरें करूं", "Dev barem karun"),
    ("Good morning.", "देव बरें करूं सकाळ", "Dev barem karun sakaal"),
    ("Good night.", "बरी रात", "Bori raat"),
    ("Welcome.", "येवकार", "Yevkaar"),
    ("What is your name?", "तुजें नांव कितें?", "Tujem naanv kitem?"),
    ("My name is Ravi.", "म्हजें नांव रवी", "Mhajem naanv Ravi"),
    ("See you later.", "उपरांत मेळया", "Upraant melyaa"),
    ("Nice to meet you.", "तुमकां मेळून बरें दिसलें", "Tumkaan mellun barem dislem"),
    ("Congratulations.", "अभिनंदन", "Abhinandan"),
    ("Happy Diwali.", "दिवाळीच्यो शुभकामना", "Divalichyo shubhkaamnaa"),
    ("Good evening.", "बरी सांज", "Bori saanj"),
    ("Hello / Namaskar.", "नमस्कार", "Namaskaar"),
]

# Full sentences for reading / script lessons (letter–sound practice in context)
READING_DRILLS = [
    ("I eat rice at home.", "हांव घरांत शीत खातां", "Haanv gharaant sheet khaataan"),
    ("You drink water now.", "तूं आतां उदक पीता", "Tum aataa udak peetaa"),
    ("He goes to the temple.", "तो देवळाक वता", "To devullaak vataa"),
    ("She sings a sweet song.", "ती गोड गीत गाता", "Ti god geet gaataa"),
    ("We live in Goa.", "आमी गोंयांत रावतात", "Aami Goanyaant raavtaat"),
    ("They work hard every day.", "ते दर दीस मेहनत करतात", "Te dar dis mehnat kartaat"),
    ("I see the moon at night.", "हांव राती चंद्र पळयतां", "Haanv raati chondro pallaytaan"),
    ("Open the book and read.", "पुस्तक उगड आनी वाच", "Pustak ugad aani vaach"),
    ("The house is near the road.", "घर वाटे लागीं आसा", "Ghor vaate laagim aasaa"),
    ("Give me a little milk.", "म्हाका थोडें दूद दी", "Mhaakaa thodem dud di"),
    ("The children play in the yard.", "भुरगीं आंगणांत खेळतात", "Bhurgim aangaant kheltaat"),
    ("I thank you with all my heart.", "हांव तुका काळीजांतल्यान देव बरें करतां", "Haanv tuka kaalijaantlyaan dev barem kartaan"),
    ("We learn Konkani step by step.", "आमी कोंकणी हळू हळू शिकतात", "Aami Konkani halu halu shiktaat"),
    ("Speak slowly and clearly.", "हळू आनी स्पष्ट उलय", "Halu aani spasht ulay"),
    ("The sun rises in the east.", "सूर्य उदेंत उगता", "Soorya udent ugataa"),
    ("Birds sit on the tree.", "सुकणीं रुकाचेर बसतात", "Suknim rukaacher basataat"),
    ("I write my name here.", "हांव म्हजें नांव हांगा बरोवतां", "Haanv mhajem naanv haangaa barovtaan"),
    ("Close the door quietly.", "दार आहिस्तां धांप", "Daar aahistaan dhaamp"),
    ("Good people help others.", "बरे मनीस दुसऱ्यांक मदत करतात", "Bare manis dusaryaank madat kartaat"),
    ("I hear the sound of rain.", "हांव पावसाचो आवाज आयकतां", "Haanv paavsaacho aawaaz aayaktaan"),
    ("She cooks food with love.", "ती मोगांनी जेवण शिजोवता", "Ti mogaanni jevan shijovtaa"),
    ("We shall meet again tomorrow.", "आमी फाल्यां परत मेळतले", "Aami faalyaan parat meltaale"),
]

DAILY = [
    ("What time is it?", "कितलो वेळ जालो?", "Kitlo vell zaalo?"),
    ("Where do you live?", "तूं खंय रावता?", "Tum khanay raavtaa?"),
    ("I live in Goa.", "हांव गोंयांत रावतां", "Haanv Goanyaant raavtaan"),
    ("I have to go home.", "म्हाका घरा वचूंक जाय", "Mhaakaa gharaa vochunk jaay"),
    ("Come here.", "हांगा ये", "Haangaa ye"),
    ("Sit down.", "बस", "Bas"),
    ("Open the door.", "दार उगड", "Daar ugad"),
    ("Today is a holiday.", "आयज सुटी", "Aayaj suti"),
    ("Tomorrow I will come.", "फाल्यां हांव येतलों", "Faalyaan haanv yetlon"),
    ("Yesterday was good.", "काल बरें आशिल्लें", "Kaal barem aashillem"),
    ("I am tired.", "हांव थकलों", "Haanv thaklon"),
    ("Let's go.", "चल वचूया", "Chal vochooyaa"),
    ("I am going to work.", "हांव कामाक वतां", "Haanv kaamaak vataan"),
    ("Close the window.", "जनेल धांप", "Janel dhaamp"),
    ("Switch on the light.", "दिवो पेटय", "Divo petay"),
    ("Where is the market?", "बाजार खंय आसा?", "Baazaar khanay aasaa?"),
    ("I need water.", "म्हाका उदक जाय", "Mhaakaa udak jaay"),
]

FOOD = [
    ("I am hungry.", "म्हाका भूक लागल्या", "Mhaakaa bhook laaglyaa"),
    ("Give me water.", "म्हाका उदक दी", "Mhaakaa udak di"),
    ("The food is tasty.", "जेवण रुचिक आसा", "Jevan ruchik aasaa"),
    ("I want tea.", "म्हाका चा जाय", "Mhaakaa chaa jaay"),
    ("The food is spicy.", "जेवण तिखट आसा", "Jevan tikhat aasaa"),
    ("I do not eat meat.", "हांव मास खायनां", "Haanv maas khaaynaan"),
    ("What is this dish?", "हें कितें जेवण?", "Hem kitem jevan?"),
    ("I want to eat.", "म्हाका जेवूंक जाय", "Mhaakaa jevunk jaay"),
    ("Enough food.", "जेवण पुरो", "Jevan puro"),
    ("I want rice.", "म्हाका शीत जाय", "Mhaakaa sheet jaay"),
    ("Bring the bill.", "बिल हाड", "Bill haad"),
    ("More food, please.", "आनीक जेवण दिवचें", "Aanik jevan divchem"),
    ("The food is sweet.", "जेवण गोड आसा", "Jevan god aasaa"),
    ("Give me roti.", "म्हाका पोळी दी", "Mhaakaa polli di"),
    ("I want coffee.", "म्हाका कॉफी जाय", "Mhaakaa coffee jaay"),
    ("I am vegetarian.", "हांव शाकाहारी", "Haanv shaakahaari"),
    ("I am thirsty.", "म्हाका तान लागल्या", "Mhaakaa taan laaglyaa"),
]

PRONOUNS = [
    ("I", "हांव", "Haanv"),
    ("You (familiar)", "तूं", "Tum"),
    ("You (polite / plural)", "तुमी", "Tumi"),
    ("He", "तो", "To"),
    ("She", "ती", "Ti"),
    ("We", "आमी", "Aami"),
    ("They", "ते", "Te"),
    ("This", "हें", "Hem"),
    ("That", "तें", "Tem"),
    ("My (before vowel sound)", "म्हजें", "Mhajem"),
    ("Your (familiar)", "तुजें", "Tujem"),
    ("Our", "आमचें", "Aamchem"),
    ("Their", "तांचें", "Taanchem"),
    ("Who?", "कोण?", "Kon?"),
    ("What?", "कितें?", "Kitem?"),
    ("Where?", "खंय?", "Khanay?"),
    ("When?", "केन्ना?", "Kennaa?"),
    ("Why?", "कित्याक?", "Kityaak?"),
]

PRESENT = [
    ("I eat rice.", "हांव शीत खातां", "Haanv sheet khaataan"),
    ("You speak Konkani.", "तूं कोंकणी उलयता", "Tum Konkani ulaytaa"),
    ("He reads a book.", "तो पुस्तक वाचता", "To pustak vaachtaa"),
    ("She cooks food.", "ती जेवण शिजोवता", "Ti jevan shijovtaa"),
    ("We study at home.", "आमी घरांत शिकतात", "Aami gharaant shiktaat"),
    ("They work in Goa.", "ते गोंयांत काम करतात", "Te Goanyaant kaam kartaat"),
    ("I drink water.", "हांव उदक पीतां", "Haanv udak peetaan"),
    ("You come every day.", "तूं दर दीस येता", "Tum dar dis yetaa"),
    ("He goes to school.", "तो इस्कोलाक वता", "To iskolaak vataa"),
    ("She sings well.", "ती बरें गाता", "Ti barem gaataa"),
    ("We play in the evening.", "आमी सांजे खेळतात", "Aami saanje kheltaat"),
    ("They walk on the road.", "ते वाटेर चलतात", "Te vaater chaltaat"),
    ("I see the sea.", "हांव दर्या पळयतां", "Haanv daryaa pallaytaan"),
    ("You listen carefully.", "तूं लक्ष दिवन आयकता", "Tum laksh divun aayaktaa"),
    ("He sleeps early.", "तो लवकर निदता", "To lavkar nidtaa"),
    ("She writes a letter.", "ती पत्र बरोवता", "Ti patr barovtaa"),
    ("We learn new words.", "आमी नवे शब्द शिकतात", "Aami nave shabd shiktaat"),
]

PAST = [
    ("I went home.", "हांव घरा वचलों", "Haanv gharaa vachlon"),
    ("You ate food.", "तूं जेवण खादलें", "Tum jevan khaadlem"),
    ("He came yesterday.", "तो काल आयलो", "To kaal aaylo"),
    ("She spoke Konkani.", "ती कोंकणी उलयली", "Ti Konkani ulayli"),
    ("We saw the temple.", "आमी देवळ पळयलो", "Aami devoll pallaylo"),
    ("They bought vegetables.", "ते भाजी घेतली", "Te bhaaji ghetli"),
    ("I drank milk.", "हांव दूद पियलों", "Haanv dud piyalon"),
    ("You slept late.", "तूं उशीरा निदलो", "Tum usheera nidlo"),
    ("He wrote a letter.", "तानें पत्र बरयलें", "Taanem patr baraylem"),
    ("She opened the door.", "तीनें दार उगडलें", "Tinem daar ugadle"),
    ("We finished work.", "आमी काम संपयलें", "Aami kaam sampaylem"),
    ("They returned home.", "ते घरा परत आयले", "Te gharaa parat aayle"),
    ("I was in Panaji.", "हांव पणजीत आशिल्लों", "Haanv Panjiit aashillon"),
    ("It rained yesterday.", "काल पावस पडलो", "Kaal paavas paddlo"),
    ("You helped me.", "तूं म्हाका मदत केली", "Tum mhaakaa madat keli"),
    ("He forgot the key.", "ताका चावी विसरली", "Taakaa chaavi visarli"),
    ("She liked the song.", "तिका गीत आवडलें", "Tikaa geet aavaddle"),
]

FUTURE = [
    ("I will come tomorrow.", "हांव फाल्यां येतलों", "Haanv faalyaan yetlon"),
    ("You will eat later.", "तूं उपरांत खातलो", "Tum upraant khaatlo"),
    ("He will go to school.", "तो इस्कोलाक वचतलो", "To iskolaak vochtalo"),
    ("She will cook rice.", "ती शीत शिजोवतली", "Ti sheet shijovtali"),
    ("We will meet again.", "आमी परत मेळतले", "Aami parat meltaale"),
    ("They will buy fruit.", "ते फळ घेतले", "Te fall ghetele"),
    ("I will call you.", "हांव तुका फोन करतलों", "Haanv tuka phone kartalon"),
    ("You will feel better.", "तुका बरें दिसतलें", "Tuka barem distalem"),
    ("He will read the book.", "तो पुस्तक वाचतलो", "To pustak vaachtalo"),
    ("She will sing a song.", "ती गीत गातली", "Ti geet gaatli"),
    ("We will travel to Goa.", "आमी गोंय वचतले", "Aami Goay vochtele"),
    ("They will wait here.", "ते हांगा रावतले", "Te haangaa raavtele"),
    ("I will learn Konkani.", "हांव कोंकणी शिकतलों", "Haanv Konkani shiktalon"),
    ("You will understand.", "तुका समजतलें", "Tuka samjatalem"),
    ("He will help us.", "तो आमकां मदत करतलो", "To aamkaan madat kartalo"),
    ("She will bring water.", "ती उदक हाडतली", "Ti udak haadtali"),
    ("We will start now.", "आमी आतां सुरवात करतले", "Aami aataa survaat kartale"),
]

QUESTIONS = [
    ("What is this?", "हें कितें?", "Hem kitem?"),
    ("Where is the bus?", "बस खंय आसा?", "Bas khanay aasaa?"),
    ("When will you come?", "तूं केन्ना येता?", "Tum kennaa yetaa?"),
    ("Why are you late?", "तूं उशीर का आसा?", "Tum usheer kaa aasaa?"),
    ("Who is he?", "तो कोण?", "To kon?"),
    ("How much is this?", "हाचो किती मोल?", "Haacho kiti mol?"),
    ("Which book?", "कितें पुस्तक?", "Kitem pustak?"),
    ("Is this yours?", "हें तुजें?", "Hem tujem?"),
    ("Can you help?", "तुमी मदत करूं शकता?", "Tumi madat karun shaktaa?"),
    ("Do you understand?", "तुका समजता?", "Tuka samjataa?"),
    ("Will you come?", "तूं येता?", "Tum yetaa?"),
    ("Did you eat?", "तूं जेवलो?", "Tum jevlo?"),
    ("Where do you work?", "तूं खंय काम करता?", "Tum khanay kaam kartaa?"),
    ("What is your name?", "तुजें नांव कितें?", "Tujem naanv kitem?"),
    ("How are you?", "तुमी कशे आसात?", "Tumi kashe aasaat?"),
    ("May I sit?", "म्हाका बसूं येता?", "Mhaakaa basun yetaa?"),
    ("Could you repeat?", "तुमी परत उलयता?", "Tumi parat ulaytaa?"),
]

NEGATIVE = [
    ("I do not know.", "म्हाका खबर ना", "Mhaakaa khabar naa"),
    ("I will not go.", "हांव वचनां", "Haanv vachnaan"),
    ("You should not worry.", "तुका काळजी करूंक ना", "Tuka kaalzi karunk naa"),
    ("He did not come.", "तो आयनां", "To aaynaan"),
    ("She is not here.", "ती हांगा ना", "Ti haangaa naa"),
    ("We have no time.", "आमकां वेळ ना", "Aamkaan vell naa"),
    ("They are not ready.", "ते तयार नात", "Te tayaar naat"),
    ("I do not want this.", "म्हाका हें नाका", "Mhaakaa hem naakaa"),
    ("Do not run.", "धांवनाका", "Dhaanvaakaa"),
    ("I never lie.", "हांव खोट उलयनां", "Haanv khot ulaynaan"),
    ("Nothing is wrong.", "कितें चूक ना", "Kitem chook naa"),
    ("He does not eat meat.", "तो मास खायनां", "To maas khaaynaan"),
    ("She cannot swim.", "ती पोहूंक शकना", "Ti pohunk shaknaa"),
    ("We did not see him.", "आमी ताका पळयनां", "Aami taaka pallaynaan"),
    ("They will not leave.", "ते वचनात", "Te vachnaat"),
    ("I am not angry.", "हांव रागी ना", "Haanv raagi naa"),
    ("This is not mine.", "हें म्हजें ना", "Hem mhajem naa"),
]

POSSESSION = [
    ("I have a book.", "म्हजें एक पुस्तक आसा", "Mhajem ek pustak aasaa"),
    ("Do you have money?", "तुजें पयशे आसात?", "Tujem payshe aasaat?"),
    ("She has two brothers.", "तिका दोन भाव आसात", "Tikaa don bhaav aasaat"),
    ("We have time today.", "आमकां आयज वेळ आसा", "Aamkaan aayaj vell aasaa"),
    ("They have a new car.", "तांचें नवें कार आसा", "Taanchem nave kaar aasaa"),
    ("I have a headache.", "म्हजें तकली दुखता", "Mhajem takli dukhtaa"),
    ("He has no fear.", "ताका भय ना", "Taakaa bhay naa"),
    ("My house is small.", "म्हजें घर ल्हान", "Mhajem ghor lhaan"),
    ("Your idea is good.", "तुजो विचार बरो", "Tujo vichaar baro"),
    ("Our school is near.", "आमचें इस्कोल लागीं", "Aamchem iskol laagim"),
    ("Their shop is closed.", "तांचें दुकान बंद", "Taanchem dukaan band"),
    ("I need help.", "म्हाका मदत जाय", "Mhaakaa madat jaay"),
    ("She needs rest.", "तिका विश्रांती जाय", "Tikaa vishraanti jaay"),
    ("We need water.", "आमकां उदक जाय", "Aamkaan udak jaay"),
    ("I have finished work.", "म्हजें काम संपलें", "Mhajem kaam samplem"),
    ("Do you have change?", "तुजें सुट्टे आसात?", "Tujem sutte aasaat?"),
    ("He has many friends.", "ताका खूब इश्ट आसात", "Taakaa khoob isht aasaat"),
]

SCRIPT_PRONUNCIATION = [
    ("Practice the vowel अ — it sounds like 'a' in 'about'.", "अ हें पयलें स्वर", "A hem paylem swar"),
    ("Practice the vowel आ — longer 'aa'.", "आ दीसता दीर्घ स्वर", "A deestaa deergh swar"),
    ("The consonant क is a guttural 'ka'.", "क म्हल्यार कान आसा", "K mhalyaar kaan aasaa"),
    ("Write ख and say it clearly: 'kha'.", "ख स्पष्ट उच्चार कर", "Kha spasht uchchaar kar"),
    ("ग is voiced 'ga' as in 'gun'.", "ग आवाज घालून बोल", "Ga aawaaz ghaalun bol"),
    ("Nasal अं needs a soft nose sound.", "अं नाकाचो आवाज", "An naakaacho aawaaz"),
    ("Combine क + अ to read क.", "क अ मेळून क", "K a melun ka"),
    ("Read slowly: क ख ग घ.", "हळू वाच: क ख ग घ", "Halu vaach: k kha ga gha"),
    ("Barakhadi links consonants with vowels.", "बाराखडी जोडाक्षरांत मेलटा", "Baarakodi jodakshraant meltaa"),
    ("Retroflex ट is made with the tongue curled back.", "ट जिभ फिरोवन", "T jibh firovon"),
    ("Do not mix ट and त — listen carefully.", "ट आनी त वेगळे", "T aani t vegle"),
    ("Practice जोडाक्षर: स्त, क्त.", "जोडाक्षर स्त क्त", "Jodakshar st kt"),
    ("The letter र changes shape in clusters.", "र जोडाक्षरांत बदलता", "Ra jodakshraant badaltaa"),
    ("ह at the end of a cluster is soft.", "ह शेवटी हलका", "Ha shevoti halkaa"),
    ("Read this word aloud: घर.", "हें उलय: घर", "Hem ulay: ghor"),
    ("Read this word aloud: नमस्कार.", "हें उलय: नमस्कार", "Hem ulay: namaskaar"),
    ("Stress usually falls on the last syllable.", "साधारणपणान शेवटचो शब्द जोर", "Saadhaaranpann shevatacho shabd zor"),
]

SHOPPING = [
    ("How much is this?", "हाचो किती मोल?", "Haacho kiti mol?"),
    ("That is too expensive.", "तें खूब म्हारग", "Tem khoob mhaarag"),
    ("Give me a discount.", "म्हाका सूट दी", "Mhaakaa soot di"),
    ("I want to buy this.", "म्हाका हें घेवंक जाय", "Mhaakaa hem ghevank jaay"),
    ("Where is the shop?", "दुकान खंय आसा?", "Dukaan khanay aasaa?"),
    ("Pack it well.", "बरें बांदून दी", "Barem baandun di"),
    ("I need fresh vegetables.", "म्हाका ताजी भाजी जाय", "Mhaakaa taaji bhaaji jaay"),
    ("One kilo, please.", "एक किलो दी", "Ek kilo di"),
    ("Do you take cards?", "कार्ड घेतात?", "Card ghetaat?"),
    ("Give me the bag.", "म्हाका पोतें दी", "Mhaakaa potem di"),
    ("This quality is good.", "हें बरें दर्जाचें", "Hem barem darjaachem"),
    ("I will come again.", "हांव परत येतलों", "Haanv parat yetlon"),
    ("Show me that one.", "म्हाका तें दाखय", "Mhaakaa tem daakhay"),
    ("Any other colour?", "दुसरो रंग आसा?", "Dusaro rang aasaa?"),
    ("Keep the change.", "सुट्टे दवरा", "Sutte davraa"),
    ("Is there a sale?", "सूट आसा?", "Soot aasaa?"),
    ("I like this cloth.", "म्हाका हो कपडो आवडटा", "Mhaakaa ho kapdo aavdataa"),
]

HEALTH = [
    ("I need a doctor.", "म्हाका दोतोर जाय", "Mhaakaa dotor jaay"),
    ("Where is the hospital?", "हॉस्पिटल खंय आसा?", "Hospital khanay aasaa?"),
    ("I have a fever.", "म्हाका ताप आयला", "Mhaakaa taap aaylaa"),
    ("My head hurts.", "म्हजें तकली दुखता", "Mhajem takli dukhtaa"),
    ("My stomach hurts.", "म्हजें पोट दुखता", "Mhajem pot dukhtaa"),
    ("Please help me.", "उपकार करून म्हाका मदत करा", "Upkaar karun mhaakaa madat karaa"),
    ("Call an ambulance.", "ॲम्ब्युलन्स आपय", "Ambulance aapay"),
    ("I need medicine.", "म्हाका वखद जाय", "Mhaakaa vakhad jaay"),
    ("I am not feeling well.", "म्हाका बरें दिसना", "Mhaakaa barem disnaa"),
    ("Rest for a day.", "एक दीस विश्रांत घे", "Ek dis vishraant ghe"),
    ("Drink more water.", "आनीक उदक पी", "Aanik udak pi"),
    ("Take this tablet.", "हें गोळी घे", "Hem goli ghe"),
    ("When did it start?", "केन्ना सुरू जालें?", "Kennaa suru zaalem?"),
    ("Do you have pain here?", "हांगा दुखता?", "Haangaa dukhtaa?"),
    ("I feel better now.", "आतां म्हाका बरें दिसता", "Aataa mhaakaa barem distaa"),
    ("She is recovering.", "ती बरी जाता", "Ti bori jaataa"),
    ("We will wait outside.", "आमी भायल्यां रावतले", "Aami bhaaylyaan raavtele"),
]

TRAVEL = [
    ("Where is the bus stop?", "बस स्टॉप खंय आसा?", "Bus stop khanay aasaa?"),
    ("One ticket to Panaji.", "पणजी एक तिकीट", "Panji ek ticket"),
    ("When does the bus leave?", "बस केन्ना निघता?", "Bas kennaa nighataa?"),
    ("Stop here, please.", "हांगा थांब", "Haangaa thaamb"),
    ("How far is the beach?", "समुद्र कितलें दूर?", "Samudr kitlem door?"),
    ("I am lost.", "हांव वाट चुकलों", "Haanv vaat chuklon"),
    ("Turn left.", "दावीकडेन वळ", "Daavikaden vall"),
    ("Turn right.", "उजवीकडेन वळ", "Ujvikaden vall"),
    ("Go straight.", "सरळ वच", "Sarall voch"),
    ("Is this the right road?", "ही वाट बरोबर?", "Hi vaat barobar?"),
    ("Call a taxi.", "टॅक्सी आपय", "Taxi aapay"),
    ("The train is late.", "ट्रेन उशीर आसा", "Train usheer aasaa"),
    ("I need an auto.", "म्हाका ऑटो जाय", "Mhaakaa auto jaay"),
    ("Drop me at the hotel.", "हॉटेलाक सोड", "Hotelaak sod"),
    ("How much is the fare?", "भाडें किती?", "Bhaadden kiti?"),
    ("Keep the ticket.", "तिकीट दवरा", "Ticket davraa"),
    ("Where is the airport?", "विमानतळ खंय?", "Vimaantall khanay?"),
]

# Vocabulary-style: word in context (English shows usage)
BODY = [
    ("My head hurts today.", "आयज म्हजें तकली दुखता", "Aaj mhajem takli dukhtaa"),
    ("Open your eyes.", "डोळे उगड", "Dolle ugad"),
    ("Wash your hands.", "हात धुवन घे", "Haat dhuvan ghe"),
    ("I broke my leg.", "म्हजो पाय फाटलो", "Mhajo paay faatlo"),
    ("She has a sweet voice.", "तिका गोड आवाज", "Tikaa god aawaaz"),
    ("Listen with both ears.", "दोन कानांनी आयक", "Don kaanaanni aayak"),
    ("He smiled with his lips.", "तानें ओठांनी हास्य केलें", "Taanem othaanni haasya kelem"),
    ("My tooth aches.", "म्हजें दात दुखता", "Mhajem daat dukhtaa"),
    ("Cold air in the nose.", "नाकांत थंड वारो", "Naakaant thand vaaro"),
    ("Strong shoulders.", "मजबूत खांदे", "Mazboot khaande"),
    ("Fold your arms.", "बाहू घुंडाळ", "Baahu ghundaall"),
    ("I cut my finger.", "म्हजो बोट कापलो", "Mhajo bot kaaplo"),
    ("She painted her nails.", "तीनें नखे रंग केले", "Tinem nakhe rang kele"),
    ("My neck is stiff.", "म्हजी मान कडक", "Mhaji maan kadak"),
    ("He has broad chest.", "ताका रुंद उरो", "Taakaa rund uro"),
    ("Walk on your feet.", "पायांनी चल", "Paayaanni chal"),
    ("The baby’s skin is soft.", "भुरग्याची त्वचा मऊ", "Bhurgyaachi tvachaa mau"),
]

NUMBERS = [
    ("One", "एक", "Ek"),
    ("Two", "दोन", "Don"),
    ("Three", "तीन", "Teen"),
    ("Four", "चार", "Chaar"),
    ("Five", "पांच", "Paanch"),
    ("Six", "सा", "Saa"),
    ("Seven", "सात", "Saat"),
    ("Eight", "आठ", "Aath"),
    ("Nine", "नव", "Nav"),
    ("Ten", "दहा", "Dahaa"),
    ("Eleven", "अकरा", "Aakraa"),
    ("Twelve", "बारा", "Baaraa"),
    ("Twenty", "वीस", "Vis"),
    ("Thirty", "तीस", "Tis"),
    ("Hundred", "शे", "She"),
    ("I have fifty rupees.", "म्हाका पन्नास रुपया आसात", "Mhaakaa pannaas rupaya aasaat"),
    ("Count from one to ten.", "एकापासून दहा पर्यंत मोज", "Ekaapaasun dahaa paryant moj"),
]

FAMILY = [
    ("My father works hard.", "म्हजो बापूय मेहनत करता", "Mhajo baapuy mehnat kartaa"),
    ("My mother cooks well.", "म्हजी आवय बरें शिजोवता", "Mhaji aavay barem shijovtaa"),
    ("His brother studies.", "ताचो भाव शिकता", "Taacho bhaav shiktaa"),
    ("Her sister sings.", "तिची भयण गाता", "Tichi bhayin gaataa"),
    ("Our grandparents are kind.", "आमचे आजो-आजी दयाळ", "Aamche aajo-aaji dayaal"),
    ("Their son is small.", "तांचो पूत ल्हान", "Taanco poot lhaan"),
    ("My friend helped me.", "म्हजो इश्ट म्हाका मदत केलो", "Mhajo isht mhaakaa madat kelo"),
    ("We visit relatives.", "आमी नातेवाईक मेळटात", "Aami naatevaik meltaat"),
    ("She is my wife.", "ती म्हजी बायल", "Ti mhaji baayil"),
    ("He is my husband.", "तो म्हजो घोव", "To mhajo ghov"),
    ("The child is sleeping.", "भुरगें निदता", "Bhurgem nidtaa"),
    ("Respect your elders.", "मोठ्यांचो मान दवर", "Mothyanchom maan davar"),
    ("My uncle lives in Margao.", "म्हजो मामो मडगांवांत रावता", "Mhajo maamo Madgaavant raavtaa"),
    ("Her aunt brought sweets.", "तिच्या मावशीन मिठाय घेतली", "Tichya maavshiin mithaay ghetli"),
    ("We are three siblings.", "आमी तीन भाव-भयण", "Aami teen bhaav-bhayin"),
    ("His daughter is clever.", "तिची धूव हुशार", "Tichi dhuv hushaar"),
    ("Our parents bless us.", "आमचे बापूय आवय आशीर्वाद दितात", "Aamche baapuy aavay aashirvaad ditaat"),
]

# Idioms / colourful lines (conversation flavour)
IDIOMS = [
    ("Slowly slowly we learn.", "हळू हळू शिकतात", "Halu halu shiktaat"),
    ("Little by little it gets better.", "थोडें थोडें बरें जाता", "Thodem thodem bere jaataa"),
    ("Heart is happy.", "काळीज आनंदी", "Kaaliz aanandi"),
    ("What to do now?", "आतां कितें करूं?", "Aataa kitem karun?"),
    ("Time will tell.", "वेळ सांगतलो", "Vell sangtalo"),
    ("God willing.", "देवाच्या मर्जीेन", "Devaachya marjien"),
    ("Come, let us sit.", "ये, बसूया", "Ye, basuyaa"),
    ("The day went well.", "दीस बरो गेलो", "Dis baro gelo"),
    ("Keep courage.", "धीर धर", "Dheer dhar"),
    ("Everything will be fine.", "सगळें बरें जातलें", "Saglem bere jatalem"),
    ("Do not fear.", "भी नाका", "Bhi naakaa"),
    ("Speak from the heart.", "काळीजांतल्यान उलय", "Kaalijaantlyaan ulay"),
    ("Patience is good.", "सय बरें", "Say barem"),
    ("This too shall pass.", "हें पण जातलें", "Hem pan jatalem"),
    ("Walk with love.", "मोगांनी चल", "Mogaanni chal"),
    ("Smile a little.", "थोडी हास्य कर", "Thodi haasya kar"),
    ("Listen more than you speak.", "उलयपेक्षा आयक", "Ulaypeksha aayak"),
]

DIWALI = [
    ("Happy Diwali to you.", "तुमकां दिवाळीच्यो शुभकामना", "Tumkaan divalichyo shubhkaamnaa"),
    ("Light lamps at home.", "घरांत दिवे लाव", "Gharaant dive laav"),
    ("We share sweets.", "आमी मिठाय वांटतात", "Aami mithaay vaanttaat"),
    ("The house looks bright.", "घर उजवाड दिसता", "Ghor ujwaad distaa"),
    ("Children burst crackers safely.", "भुरगीं सुरक्षित फटाळे फोडतात", "Bhurgim surakshit fataalle fodtaat"),
    ("May there be prosperity.", "समृद्धी आसूं", "Samruddhi aasum"),
    ("We wear new clothes.", "आमी नवे कपडे घालतात", "Aami nave kapde ghaltaat"),
    ("Guests visit our home.", "पावलां घरांत येतात", "Paavlaan gharaant yetaat"),
    ("I bought a lantern.", "हांव एक लॅंप घेतलों", "Haanv ek laamp ghetlon"),
    ("She made karanji.", "तीनें करांजी केली", "Tinem karaanji keli"),
    ("We pray together.", "आमी एकठां प्रार्थना करतात", "Aami ekthaan praarthana kartaat"),
    ("The sky is full of lights.", "आकाश दिव्यांनी भरलो", "Aakaash divyaanni bharlo"),
    ("Happy faces everywhere.", "सगळ्यांक आनंद", "Saglyaan kaanand"),
    ("Turn off lights when you sleep.", "निदताना दिवे बंद कर", "Nidtaana dive band kar"),
    ("Share joy with neighbours.", "पडोश्यांक आनंद वांट", "Padoshyaanka aanand vaant"),
    ("Diwali is my favourite festival.", "दिवाळी म्हजी आवडटी सण", "Divali mhaji aavddi san"),
    ("Come for dinner tonight.", "आयज राती जेवणाक ये", "Aaj raati jevnaak ye"),
]

BANK_REGISTRY = {
    "GREETINGS": GREETINGS,
    "DAILY": DAILY,
    "FOOD": FOOD,
    "PRONOUNS": PRONOUNS,
    "PRESENT": PRESENT,
    "PAST": PAST,
    "FUTURE": FUTURE,
    "QUESTIONS": QUESTIONS,
    "NEGATIVE": NEGATIVE,
    "POSSESSION": POSSESSION,
    "SCRIPT_PRONUNCIATION": SCRIPT_PRONUNCIATION,
    "SHOPPING": SHOPPING,
    "HEALTH": HEALTH,
    "TRAVEL": TRAVEL,
    "BODY": BODY,
    "NUMBERS": NUMBERS,
    "FAMILY": FAMILY,
    "IDIOMS": IDIOMS,
    "DIWALI": DIWALI,
    "READING_DRILLS": READING_DRILLS,
}

