# -*- coding: utf-8 -*-
"""Phrase chapters 556–596 (Malayalam)."""
from malayalam_lesson_content import R, _pad


def D(*t):
    return _pad([R(e, m, r) for e, m, r in t])


DATA556 = D(
    ("I know Malayalam a little.", "എനിക്ക് മലയാളം കുറച്ച് അറിയാം.", "enikk malayāḷaṁ kureśś aṟiyāṁ."),
    ("She knows how to cook.", "അവൾക്ക് പാചകം അറിയാം.", "avaḷkku pācakaṁ aṟiyāṁ."),
    ("We do not know the answer yet.", "ഇനിയും ഉത്തരം ഞങ്ങൾക്ക് അറിയില്ല.", "iniyuṁ uttaraṁ ñaṅṅaḷkku aṟiyilla."),
    ("He knows everyone in the village.", "ഗ്രാമത്തിലെ എല്ലാവരെയും അവന് അറിയാം.", "grāmattile ellāvareyuṁ avan aṟiyāṁ."),
    ("Do you know her brother?", "അവളുടെ സഹോദരനെ നിനക്ക് അറിയാമോ?", "avaḷuṟe sahōdarane ninakku aṟiyāmō?"),
    ("I knew him from school.", "സ്കൂളിൽ നിന്ന് ഞാൻ അവനെ അറിഞ്ഞിരുന്നു.", "skūlil ninn njān avane aṟiññirunnu."),
    ("She will know tomorrow.", "നാളെ അവൾക്ക് അറിയും.", "nāḷe avaḷkku aṟiyuṁ."),
    ("We know that you are busy.", "നിങ്ങൾ തിരക്കിലാണെന്ന് ഞങ്ങൾക്ക് അറിയാം.", "niṅṅaḷ tiraṅṅkilāṇennu ñaṅṅaḷkku aṟiyāṁ."),
    ("He does not know the way.", "അവന് വഴി അറിയില്ല.", "avan vazhi aṟiyilla."),
    ("I want to know the truth.", "സത്യം അറിയണം.", "satyaṁ aṟiyaṇaṁ."),
    ("Let me know when you arrive.", "എത്തുമ്പോൾ അറിയിക്കുക.", "ettumbōḷ aṟiyikkuka."),
    ("She knows classical music.", "അവൾക്ക് ശാസ്ത്രീയ സംഗീതം അറിയാം.", "avaḷkku śāstrīya saṁgītaṁ aṟiyāṁ."),
    ("Nobody knows what will happen.", "എന്ത് സംഭവിക്കുമെന്ന് ആർക്കും അറിയില്ല.", "ent saṁbhavikumenn ārkkuṁ aṟiyilla."),
    ("I know it by heart.", "എനിക്ക് അത് മനഃപാഠമായി.", "enikk at manaḥpāṭhamāyi."),
    ("We knew the risks.", "അപായങ്ങൾ ഞങ്ങൾ അറിഞ്ഞിരുന്നു.", "apāyaṅṅaḷ ñaṅṅaḷ aṟiññirunnu."),
    ("\"aṟiyuka\" and \"manassilākuka\" differ slightly.", "“അറിയുക” അറിവ്; “മനസ്സിലാകുക” ഗ്രഹണം.", "“aṟiyuka” aṟivu; “manassilākuka” grahaṇaṁ."),
    ("Get to know your neighbours.", "അയൽക്കാരെ പരിചയപ്പെടുത്തുക.", "ayalkkāre paricayappeṭuttuka."),
    ("Knowledge grows with reading.", "വായനയോടെ അറിവ് വർദ്ധിക്കുന്നു.", "vāyanayōṭe aṟiv varddhikkunnu."),
)

DATA557 = D(
    ("Let us go to the temple.", "നമുക്ക് ക്ഷേത്രത്തിലേക്ക് പോകാം.", "namukku kṣētrattilēkk pōkāṁ."),
    ("Let him rest.", "അവനെ വിശ്രമിക്കാൻ അനുവദിക്കുക.", "avane viśramikkān anuvadiccuka."),
    ("Let them decide.", "അവർ തീരുമാനിക്കട്ടെ.", "avar tīrumānikkaṭṭe."),
    ("Shall we start?", "നമുക്ക് തുടങ്ങാമോ?", "namukku tuṭaṅṅāmō?"),
    ("Let me help you.", "ഞാൻ സഹായിക്കട്ടെ.", "njān sahāyikkaṭṭe."),
    ("Do not let the children go alone.", "കുട്ടികളെ ഒറ്റയ്ക്ക് പോകാൻ അനുവദിക്കരുത്.", "kuṭṭikaḷe oṭṭaykku pōkān anuvadiccarut."),
    ("Let us pray for peace.", "സമാധാനത്തിന് നമുക്ക് പ്രാർത്ഥിക്കാം.", "samādhānattin namukku prārththikkāṁ."),
    ("Let the water boil.", "വെള്ളം തിളയ്ക്കട്ടെ.", "veḷḷaṁ tiḷaykkaṭṭe."),
    ("Shall I open the window?", "ജനൽ തുറക്കട്ടെ?", "janal tuṟakkaṭṭe?"),
    ("Let us meet again.", "നമുക്ക് വീണ്ടും കാണാം.", "namukku vīṇṭuṁ kāṇāṁ."),
    ("Let her sing.", "അവൾ പാടട്ടെ.", "avaḷ pāṭaṭṭe."),
    ("We let the guests sit first.", "അതിഥികളെ ആദ്യം ഇരുത്തി.", "atithikaḷe ādyam irutti."),
    ("\"ākaṭṭe\" softens suggestions.", "ആലോചന മൃദുവാക്കാൻ “ആകട്ടെ”.", "ālōcana mr̥duvākkān “ākaṭṭe”."),
    ("Shall we order food?", "ഭക്ഷണം ഓർഡർ ചെയ്യാമോ?", "bhakṣaṇaṁ ōrḍar ceyyāmō?"),
    ("Let the children play.", "കുട്ടികൾ കളിക്കട്ടെ.", "kuṭṭikaḷ kaḷikkaṭṭe."),
    ("Do not let fear stop you.", "ഭയം നിന്നെ തടയാൻ അനുവദിക്കരുത്.", "bhayaṁ ninne taṭayān anuvadiccarut."),
    ("Let us hope for the best.", "ഏറ്റവും നല്ലത് പ്രതീക്ഷിക്കാം.", "ēṭṭavuṁ nallat pratīkṣikkāṁ."),
    ("Formal: please allow (dayavāyi anuvadiccuka).", "Please allow — ദയവായി അനുവദിക്കുക.", "dayavāyi anuvadiccuka."),
)

DATA558 = D(
    ("This is the book that I bought.", "ഞാൻ വാങ്ങിയ പുസ്തകം ഇതാണ്.", "njān vāṅṅiya pustakaṁ itāṇ."),
    ("That is the house where I was born.", "ഞാൻ ജനിച്ച വീട് അതാണ്.", "njān janicca vīṭ atāṇ."),
    ("I do not know what he said.", "അവൻ എന്ത് പറഞ്ഞുവെന്ന് എനിക്ക് അറിയില്ല.", "avan ent paṟaññuvennu enikk aṟiyilla."),
    ("Tell me which bus goes to the city.", "നഗരത്തിലേക്ക് ഏത് ബസ് പോകുന്നുവെന്ന് പറയുക.", "nagarattilēkk ēt bas pōkunnuvennu paṛayuka."),
    ("The girl who sang was my cousin.", "പാടിയ പെൺകുട്ടി എന്റെ സഹോദരിയാണ്.", "pāṭiya peṇkuṭṭi enṟe sahōdariyāṇ."),
    ("This is what I meant.", "എനിക്ക് ഉദ്ദേശിച്ചത് ഇതാണ്.", "enikk uddēśiccat itāṇ."),
    ("That is why I came late.", "അതുകൊണ്ടാണ് ഞാൻ വൈകി.", "atukoṇṭāṇ njān vaiki."),
    ("I remember the day when we met.", "നമ്മൾ കണ്ട ദിവസം ഓർമ്മയുണ്ട്.", "nammaḷ kaṇṭa divasaṁ ōrmmayuṇṭ."),
    ("Whatever you say, I will listen.", "നീ എന്ത് പറഞ്ഞാലും ഞാൻ കേൾക്കും.", "nī ent paṟaññāl uṁ njān kēḷkkuṁ."),
    ("Take whichever you like.", "നിനക്ക് ഇഷ്ടമുള്ളത് എടുക്കുക.", "ninakku iṣṭamuḷḷat eṭukkuka."),
    ("Relative clauses often use participles in Malayalam.", "ബന്ധവാക്യങ്ങൾ പലപ്പോഴും ക്രിയാവിശേഷണങ്ങൾ കൊണ്ട്.", "bandhavākyaṅṅaḷ palappōḻuṁ kriyāviśeṣaṇaṅṅaḷ koṇṭ."),
    ("The man that you saw is my uncle.", "നീ കണ്ട മനുഷ്യൻ എന്റെ അമ്മാവനാണ്.", "nī kaṇṭa manuṣyan enṟe ammāvanāṇ."),
    ("I forgot where I kept the file.", "ഫയൽ എവിടെ വെച്ചുവെന്ന് മറന്നു.", "phayal evide veccuvennu maṟannu."),
    ("Show me how you did it.", "എങ്ങനെ ചെയ്തുവെന്ന് കാണിക്കുക.", "eṅṅane ceytuvennu kāṇikkuka."),
    ("That is the reason why I refused.", "ഞാൻ നിരസിച്ച കാരണം അതാണ്.", "njān nirasicca kāraṇaṁ atāṇ."),
    ("Whatever happens, stay calm.", "എന്ത് സംഭവിച്ചാലും ശാന്തനായിരിക്കുക.", "ent saṁbhaviccal uṁ śāntanāyirikkuka."),
    ("I will buy what you recommend.", "നിർദ്ദേശിക്കുന്നത് ഞാൻ വാങ്ങും.", "nirddēśikkunnat njān vāṅṅuṁ."),
    ("Practice \"enna\", \"āya\" relative forms.", "“എന്ന”, “ആയ” ബന്ധരൂപങ്ങൾ പരിശീലിക്കുക.", "“enna”, “āya” bandharūpaṅṅaḷ pariśīlikkuka."),
)

DATA559 = D(
    ("Employees are requested to sign the register.", "ജീവനക്കാർ രജിസ്റ്ററിൽ ഒപ്പിടണമെന്ന് അഭ്യർത്ഥിക്കുന്നു.", "jīvana kkār rajisṭṭaril oppiṭaṇamenn abhyarththikkunnu."),
    ("Please maintain silence in the library.", "ലൈബ്രറിയിൽ നിശബ്ദത പാലിക്കുക.", "laibraṟiyil niśabdata pālikkuka."),
    ("Kindly submit documents before Friday.", "വെള്ളിയാഴ്ചയ്ക്ക് മുമ്പ് രേഖകൾ സമർപ്പിക്കുക.", "veḷḷiyāḻccakku mumpe rēkhakaḷ samarpikkuka."),
    ("Visitors must not touch the exhibits.", "സന്ദർശകർ പ്രദർശന വസ്തുക്കൾ തൊടരുത്.", "sandarśakar pradarśana vastukkaḷ toṭarut."),
    ("Please stand in queue.", "ദയവായി ക്യൂവിൽ നിൽക്കുക.", "dayavāyi kyūvil nilkkuka."),
    ("The management requests cooperation.", "ഭരണസമിതി സഹകരണം അഭ്യർത്ഥിക്കുന്നു.", "bharaṇasamiti sahakaraṇaṁ abhyarththikkunnu."),
    ("Do not litter in public places.", "പൊതുസ്ഥലങ്ങളിൽ മാലിന്യം ഇടരുത്.", "pōtusthalaṅṅaḷil mālinyaṁ iṭarut."),
    ("Please switch off mobile phones.", "മൊബൈൽ ഫോണുകൾ സ്വിച്ച് ഓഫ് ചെയ്യുക.", "mōbail phōṇukaḷ svicc ōph ceyyuka."),
    ("Passengers are advised to keep tickets ready.", "യാത്രക്കാർ ടിക്കറ്റ് തയ്യാറാക്കാൻ അറിയിപ്പ്.", "yātrakkār ṭikkaṭṭ tayyārākkān aṟiyipp."),
    ("Formal Malayalam uses passive and nominal style.", "ഔപചാരിക മലയാളത്തിൽ നാമവാക്യ ശൈലി.", "aupacārika malayāḷattil nāmavākya śaili."),
    ("Government notices use \"aṟiyikkunnu\".", "സർക്കാർ അറിയിപ്പുകൾ “അറിയിക്കുന്നു”.", "sarkkār aṟiyippukaḷ “aṟiyikkunnu”."),
    ("Please read the instructions carefully.", "നിർദ്ദേശങ്ങൾ ശ്രദ്ധയോടെ വായിക്കുക.", "nirddēśaṅṅaḷ śraddhayōṭe vāyikkuka."),
    ("Employees shall report at nine.", "ജീവനക്കാർ ഒമ്പത് മണിക്ക് റിപ്പോർട്ട് ചെയ്യണം.", "jīvana kkār ompatu maṇik rippōṭṭ ceyyaṇaṁ."),
    ("The public is informed that the office is closed.", "ഓഫീസ് അടച്ചിരിക്കുന്നതായി ജനങ്ങളെ അറിയിക്കുന്നു.", "ōphīs aṭaccirikkunatāyi janaṅṅaḷe aṟiyikkunnu."),
    ("Request: please cooperate (dayavāyi sahakarikkuka).", "Please cooperate — ദയവായി സഹകരിക്കുക.", "dayavāyi sahakarikkuka."),
    ("Avoid informal words in official letters.", "ഔപചാരിക കത്തിൽ അനൗപചാരിക പദങ്ങൾ ഒഴിവാക്കുക.", "aupacārika kattil anaupacārika padaṅṅaḷ oḻivākkuka."),
    ("Sign below after reading.", "വായിച്ച് താഴെ ഒപ്പിടുക.", "vāyicc tāḻe oppiṭuka."),
    ("Your cooperation is highly appreciated.", "നിങ്ങളുടെ സഹകരണം ഉന്നതമായി അഭിനന്ദിക്കുന്നു.", "niṅṅaḷuṭe sahakaraṇaṁ unnatamāyi abhinandikkunnu."),
)

DATA560 = D(
    ("I like Malayalam films.", "എനിക്ക് മലയാള സിനിമകൾ ഇഷ്ടമാണ്.", "enikk malayāḷa sinimakaḷ iṣṭamāṇ."),
    ("She likes spicy food.", "അവൾക്ക് മസാലയുള്ള ഭക്ഷണം ഇഷ്ടമാണ്.", "avaḷkku masālayuḷḷa bhakṣaṇaṁ iṣṭamāṇ."),
    ("We like walking on the beach.", "കടൽ തീരത്ത് നടക്കാൻ ഞങ്ങൾക്ക് ഇഷ്ടമാണ്.", "kaḍal tīratt naṭakkān ñaṅṅaḷkku iṣṭamāṇ."),
    ("He does not like crowds.", "അവന് കൂട്ടം ഇഷ്ടമല്ല.", "avan kūṭṭaṁ iṣṭamalla."),
    ("Do you like coffee?", "നിനക്ക് കാപ്പി ഇഷ്ടമാണോ?", "ninakk kāppi iṣṭamāṇō?"),
    ("I would like some water.", "കുറച്ച് വെള്ളം വേണം.", "kureśś veḷḷaṁ vēṇaṁ."),
    ("Children like sweets.", "കുട്ടികൾക്ക് മിഠായി ഇഷ്ടമാണ്.", "kuṭṭikaḷkku miṭhāyi iṣṭamāṇ."),
    ("She likes to read at night.", "അവൾക്ക് രാത്രി വായിക്കാൻ ഇഷ്ടമാണ്.", "avaḷkku rātri vāyikkān iṣṭamāṇ."),
    ("I like your suggestion.", "നിന്റെ നിർദ്ദേശം എനിക്ക് ഇഷ്ടമായി.", "ninṟe nirddēśaṁ enikk iṣṭamāyi."),
    ("We do not like dishonesty.", "അസത്യം ഞങ്ങൾക്ക് ഇഷ്ടമല്ല.", "asatyaṁ ñaṅṅaḷkku iṣṭamalla."),
    ("\"iṣṭaṁ\" noun; \"iṣṭappeṭuka\" verb.", "“ഇഷ്ടം” നാമം; “ഇഷ്ടപ്പെടുക” ക്രിയ.", "“iṣṭaṁ” nāmaṁ; “iṣṭappeṭuka” kriya."),
    ("I like listening to old songs.", "പഴയ പാട്ടുകൾ കേൾക്കാൻ ഇഷ്ടമാണ്.", "paḻaya pāṭṭukaḷ kēḷkkān iṣṭamāṇ."),
    ("They like travelling.", "അവർക്ക് യാത്ര ഇഷ്ടമാണ്.", "avarkk yātra iṣṭamāṇ."),
    ("She likes you very much.", "അവൾക്ക് നിന്നെ വളരെ ഇഷ്ടമാണ്.", "avaḷkku ninne vaḷare iṣṭamāṇ."),
    ("I do not like waiting.", "കാത്തിരിക്കാൻ എനിക്ക് ഇഷ്ടമല്ല.", "kāttirikkān enikk iṣṭamalla."),
    ("We like Kerala’s monsoon.", "കേരളത്തിലെ മൺസൂൺ ഞങ്ങൾക്ക് ഇഷ്ടമാണ്.", "kēraḷattile maṇsūṅ ñaṅṅaḷkku iṣṭamāṇ."),
    ("Expressing likes politely: \"enikk iṣṭamāṇ\".", "മര്യാദയോടെ “എനിക്ക് ഇഷ്ടമാണ്”.", "maryādayōṭe “enikk iṣṭamāṇ”."),
    ("Strong dislike: \"iṣṭamilla\".", "വിരോധം “ഇഷ്ടമില്ല”.", "virōdhaṁ “iṣṭamilla”."),
)

DATA561 = D(
    ("I would help if I could.", "കഴിയുമായിരുന്നെങ്കിൽ ഞാൻ സഹായിക്കുമായിരുന്നു.", "kaḻiyumāyirunneṅkiḷ njān sahāyikkumāyirunnu."),
    ("She would sing when she was young.", "ചെറുപ്പത്തിൽ അവൾ പാടുമായിരുന്നു.", "ceṛuppattil avaḷ pāṭumāyirunnu."),
    ("We would visit every summer.", "ഓരോ വേനലിലും ഞങ്ങൾ സന്ദർശിക്കുമായിരുന്നു.", "ōrō vēnaliluṁ ñaṅṅaḷ sandarśikkumāyirunnu."),
    ("He would read until midnight.", "അർദ്ധരാത്രി വരെ അവൻ വായിക്കുമായിരുന്നു.", "arddharātri vare avan vāyikkumāyirunnu."),
    ("I would like to thank everyone.", "എല്ലാവരെയും നന്ദി പറയാൻ ഞാൻ ആഗ്രഹിക്കുന്നു.", "ellāvareyuṁ nandi paṛayān njān āgrahikkunnu."),
    ("That would be wonderful.", "അത് മനോഹരമായിരിക്കും.", "at manōharamāyirikuṁ."),
    ("Would you close the window?", "ജനൽ അടയ്ക്കുമോ?", "janal aṭaykkumō?"),
    ("I would never lie to you.", "നിന്നോട് ഞാൻ ഒരിക്കലും കള്ളം പറയില്ല.", "ninōṭ njān orikkaluṁ kaḷḷaṁ paṛayilla."),
    ("They would wait for hours.", "അവർ മണിക്കൂറുകൾ കാത്തിരിക്കുമായിരുന്നു.", "avar maṇikkūrukaḷ kāttirikkumāyirunnu."),
    ("Hypothetical: I would go if invited.", "ക്ഷണം ലഭിച്ചാൽ പോകുമായിരുന്നു.", "kṣaṇaṁ labhiccāl pōkumāyirunnu."),
    ("Polite request: would you help?", "സഹായിക്കുമോ?", "sahāyikkumō?"),
    ("She would have come but she was ill.", "അവൾ വന്നേക്കുമായിരുന്നു പക്ഷേ അസുഖമായിരുന്നു.", "avaḷ vannekkumāyirunnu pakṣe asukhamāyirunnu."),
    ("We would prefer morning slots.", "പ്രഭാത സമയം ഞങ്ങൾക്ക് നന്ന്.", "prabhāta samayaṁ ñaṅṅaḷkku nan."),
    ("He would often walk by the river.", "അവൻ പലപ്പോഴും നദീതീരത്ത് നടക്കുമായിരുന്നു.", "avan palappōḷuṁ nadītīratt naṭakkumāyirunnu."),
    ("I would recommend this book.", "ഈ പുസ്തകം ഞാൻ ശുപാർശ ചെയ്യുന്നു.", "ī pustakaṁ njān śupārśa ceyyunnu."),
    ("Would that be enough?", "അത് മതിയാകുമോ?", "at matiyākumō?"),
    ("Would in Malayalam often uses conditional + past.", "“ആയിരിക്കും” “ആയിരുന്നു” എന്നിവയോട് കൂടി.", "“āyirikuṁ” “āyirunnu” ennivōṭ kūṭi."),
    ("Practice: I would have told you.", "ഞാൻ നിന്നെ അറിയിക്കുമായിരുന്നു.", "njān ninne aṟiyikkumāyirunnu."),
)

DATA562 = D(
    ("I understand the lesson.", "പാഠം എനിക്ക് മനസ്സിലായി.", "pāṭhaṁ enikk manassilāyi."),
    ("She does not understand Malayalam yet.", "ഇതുവരെ അവൾക്ക് മലയാളം മനസ്സിലായിട്ടില്ല.", "ituvare avaḷkku malayāḷaṁ manassilāyiṭṭilla."),
    ("Explain again so that we understand.", "മനസ്സിലാകുംവിധം വീണ്ടും വിശദീകരിക്കുക.", "manassilākuṁvidhaṁ vīṇṭuṁ viśadīkarikkuka."),
    ("I came to know the truth yesterday.", "ഇന്നലെ സത്യം എനിക്ക് മനസ്സിലായി.", "innale satyaṁ enikk manassilāyi."),
    ("Suddenly he understood the problem.", "പെട്ടെന്ന് പ്രശ്നം അവന് മനസ്സിലായി.", "peṭṭenn praśnaṁ avan manassilāyi."),
    ("We understand your difficulty.", "നിങ്ങളുടെ ബുദ്ധിമുട്ട് ഞങ്ങൾ മനസ്സിലാക്കുന്നു.", "niṅṅaḷuṭe buddhimuṭṭ ñaṅṅaḷ manassilākkunnu."),
    ("Did you understand?", "മനസ്സിലായോ?", "manassilāyō?"),
    ("I will make him understand.", "അവന് മനസ്സിലാക്കിക്കൊടുക്കും.", "avan manassilākkikoṭukkuṁ."),
    ("Gradually she understood the pattern.", "ക്രമേണ അവൾക്ക് മാതൃക മനസ്സിലായി.", "krameṇ avaḷkku mātṛka manassilāyi."),
    ("Understanding needs patience.", "മനസ്സിലാക്കാൻ ക്ഷമ വേണം.", "manassilākkān kṣama vēṇaṁ."),
    ("I understood without words.", "വാക്കുകളില്ലാതെ മനസ്സിലായി.", "vākkukaḷillāte manassilāyi."),
    ("They came to know through the news.", "വാർത്തയിലൂടെ അവർ അറിഞ്ഞു.", "vārtthayilūṭe avār aṟiññu."),
    ("\"manassilākuka\" and \"aṟiyuka\" overlap.", "രണ്ടും അറിവ്; സന്ദർഭം വ്യത്യാസം.", "raṇṭuṁ aṟivu; sandarbhaṁ vyatāsam."),
    ("I want to understand Kerala’s culture.", "കേരള സംസ്കാരം മനസ്സിലാക്കണം.", "kēraḷa saṁskāraṁ manassilākkkaṇaṁ."),
    ("She understood the hint.", "സൂചന അവൾക്ക് മനസ്സിലായി.", "sūjana avaḷkku manassilāyi."),
    ("We finally understood the rule.", "അവസാനം നിയമം ഞങ്ങൾ മനസ്സിലാക്കി.", "avasānaṁ niyamaṁ ñaṅṅaḷ manassilākki."),
    ("Listen carefully to understand.", "മനസ്സിലാക്കാൻ ശ്രദ്ധിച്ച് കേൾക്കുക.", "manassilākkān śraddhicc kēḷkkuka."),
    ("True understanding takes time.", "യഥാർത്ഥ മനസ്സിലാക്കൽ സമയം എടുക്കും.", "yāthārthya manassilākkaḷ samayaṁ eṭukkuṁ."),
)

DATA563 = D(
    ("You are coming, aren’t you?", "നീ വരുന്നല്ലേ?", "nī varunnallē?"),
    ("It is good, isn’t it?", "നല്ലതല്ലേ?", "nallatallē?"),
    ("She knows Malayalam, doesn’t she?", "അവൾക്ക് മലയാളം അറിയാമല്ലേ?", "avaḷkku malayāḷaṁ aṟiyām allē?"),
    ("We can sit here, can’t we?", "ഇവിടെ ഇരിക്കാമല്ലേ?", "ivide irikkām allē?"),
    ("He will come tomorrow, won’t he?", "അവൻ നാളെ വരുമല്ലേ?", "avan nāḷe varumallē?"),
    ("This is your book, isn’t it?", "ഇത് നിന്റെ പുസ്തകമല്ലേ?", "it ninṟe pustakam allē?"),
    ("They were late, weren’t they?", "അവർ വൈകിയല്ലേ?", "avar vaikiyallē?"),
    ("You understood, didn’t you?", "മനസ്സിലായല്ലേ?", "manassilāyallē?"),
    ("Tag questions use \"allē\", \"llē\".", "ചോദ്യ അടയാളങ്ങൾ “അല്ലേ”, “ല്ലേ”.", "cōdhya aṭayāḷaṅṅaḷ “allē”, “llē”."),
    ("Informal: pōkuvallē? (you are going, right?)", "You are going, right? — പോകുവല്ലേ?", "pōkuvallē?"),
    ("Softening: allē? (isn’t it?)", "isn’t it — അല്ലേ?", "allē?"),
    ("She isn’t angry, is she?", "അവൾ കോപിഷ്ഠയല്ലല്ലേ?", "avaḷ kōpiṣṭayallallē?"),
    ("We should leave now, shouldn’t we?", "ഇപ്പോൾ പോകണമല്ലേ?", "ippōḷ pōkaṇamallē?"),
    ("He can swim, can’t he?", "അവന് നീന്താനറിയാമല്ലേ?", "avan nīntān aṟiyām allē?"),
    ("Practice tags with rising intonation.", "ഉച്ചാരണത്തിൽ ഉയർന്ന സ്വരം പരിശീലിക്കുക.", "uccāraṇattil uyartta svaraṁ pariśīlikkuka."),
    ("Tags show shared assumptions in conversation.", "സംഭാഷണത്തിൽ പൊതു ധാരണ “അല്ലേ”.", "saṁbhāṣaṇattil pōta dhāraṇa “allē”."),
    ("Avoid tags in very formal speech.", "വളരെ ഔപചാരിക സംസാരത്തിൽ അടയാളം ഒഴിവാക്കുക.", "vaḷare aupacārika saṁsāraṭṭil aṭayāḷaṁ oḻivākkuka."),
    ("Listen to Malayalam films for natural tags.", "സ്വാഭാവിക അടയാളങ്ങൾക്ക് സിനിമ കേൾക്കുക.", "svābhāvika aṭayāḷaṅṅaḷkku sinima kēḷkkuka."),
)

DATA564 = D(
    ("I remember your name.", "നിന്റെ പേര് എനിക്ക് ഓർമ്മയുണ്ട്.", "ninṟe pēr enikk ōrmmayuṇṭ."),
    ("She forgot the appointment.", "അവൾ അപ്പോയിന്റ്മെന്റ് മറന്നു.", "avaḷ appoyinṭmeṇṭ maṟannu."),
    ("We remember our first visit to Kerala.", "കേരളത്തിലേക്കുള്ള ആദ്യയാത്ര ഓർക്കുന്നു.", "kēraḷattilēkkuḷḷa ādyayātra ōrkkunnu."),
    ("Try to remember these words.", "ഈ വാക്കുകൾ ഓർമ്മിക്കാൻ ശ്രമിക്കുക.", "ī vākkukaḷ ōrmmikkān śramikkuka."),
    ("I suddenly remembered.", "പെട്ടെന്ന് എനിക്ക് ഓർമ്മ വന്നു.", "peṭṭenn enikk ōrmma vannu."),
    ("He does not remember the password.", "അവന് പാസ്‌വേഡ് ഓർമ്മയില്ല.", "avan pāsveḍ ōrmmayilla."),
    ("Let us remember the martyrs.", "വീരമൃതരെ ഓർമ്മിക്കുക.", "vīramr̥tare ōrmmikkuka."),
    ("I will always remember your kindness.", "നിങ്ങളുടെ ദയ ഞാൻ എന്നും ഓർക്കും.", "niṅṅaḷuṭe daya njān ennuṁ ōrkuṁ."),
    ("Memory improves with repetition.", "ആവർത്തനം ഓർമ്മ ശക്തി വർദ്ധിപ്പിക്കുന്നു.", "āvarttanaṁ ōrmma śakti varddhippikkunnu."),
    ("She remembered to lock the door.", "വാതിൽ പൂട്ടാൻ അവൾ ഓർമ്മിച്ചു.", "vātil pūṭṭān avaḷ ōrmmiccu."),
    ("We forgot where we parked.", "പാർക്ക് ചെയ്ത സ്ഥലം മറന്നു.", "pārkk ceyta sthalaṁ maṟannu."),
    ("\"ōrmma\" noun; \"ōrkkuka\" verb.", "“ഓർമ്മ” നാമം; “ഓർക്കുക” ക്രിയ.", "“ōrmma” nāmaṁ; “ōrkkuka” kriya."),
    ("Photographs help us remember.", "ഫോട്ടോകൾ ഓർമ്മയ്ക്ക് സഹായം.", "phōṭṭōkaḷ ōrmmaykku sahāyaṁ."),
    ("I remember that day clearly.", "ആ ദിവസം വ്യക്തമായി ഓർക്കുന്നു.", "ā divasaṁ vyaktamāyi ōrkkunnu."),
    ("Do you remember me?", "എന്നെ ഓർമ്മയുണ്ടോ?", "enne ōrmmayuṇṭō?"),
    ("Childhood memories are precious.", "ബാല്യ ഓർമ്മകൾ വിലയേറിയവ.", "bālya ōrmmakaḷ vilayēṟiyava."),
    ("Write a diary to remember vocabulary.", "ഓർമ്മയ്ക്ക് വാക്കുകൾ ഡയറി എഴുതുക.", "ōrmmaykku vākkukaḷ ḍayari eḻutuka."),
    ("Forgive and forget for peace.", "മാപ്പും മറക്കലും സമാധാനത്തിന്.", "māppuṁ maṟakkaluṁ samādhānattin."),
)

DATA565 = D(
    ("I want to learn Malayalam.", "എനിക്ക് മലയാളം പഠിക്കണം.", "enikk malayāḷaṁ paṭhikkaṇaṁ."),
    ("She wants to sleep.", "അവൾക്ക് ഉറങ്ങണം.", "avaḷkku uṟaṅṅaṇaṁ."),
    ("We want to see the backwaters.", "ഞങ്ങൾ കായലുകൾ കാണണം.", "ñaṅṅaḷ kāyalukaḷ kāṇaṇaṁ."),
    ("He wants to buy a house.", "അവന് വീട് വാങ്ങണം.", "avan vīṭ vāṅṅaṇaṁ."),
    ("They want to help.", "അവർക്ക് സഹായിക്കണം.", "avarkk sahāyikkaṇaṁ."),
    ("I do not want to argue.", "തർക്കിക്കാൻ എനിക്ക് താൽപ്പര്യമില്ല.", "tarkkikkān enikk tālparyamilla."),
    ("She wants you to call.", "നിന്നെ വിളിക്കണമെന്ന് അവൾക്ക് തോന്നുന്നു.", "ninne viḷikkaṇamenn avaḷkku tōnnunnu."),
    ("We wanted to arrive early.", "നേരത്തെ എത്തണമെന്ന് ഞങ്ങൾ ആഗ്രഹിച്ചു.", "nērattē eṭṭaṇamenn ñaṅṅaḷ āgrahiccu."),
    ("Infinitive + \"vēṇaṁ\" expresses want to.", "അനന്തര ക്രിയ + “വേണം” ആഗ്രഹം.", "anantara kriya + “vēṇaṁ” āgrahaṁ."),
    ("I want you to be happy.", "നീ സന്തോഷവാനായിരിക്കണം.", "nī saṁtōṣavānāyirikaṇaṁ."),
    ("He wants the work finished today.", "ഇന്ന് ജോലി തീരണമെന്ന് അവൻ ആഗ്രഹിക്കുന്നു.", "inn jōli tīraṇamenn avan āgrahikkunnu."),
    ("Do you want tea or coffee?", "ചായ വേണോ കാപ്പി വേണോ?", "cāya vēṇō kāppi vēṇō?"),
    ("We want nothing more.", "ഞങ്ങൾക്ക് മറ്റൊന്നും വേണ്ട.", "ñaṅṅaḷkku maṭṭonnuṁ vēṇṭa."),
    ("She wants to visit the temple.", "ക്ഷേത്രം സന്ദർശിക്കണമെന്ന് അവൾക്ക് തോന്നുന്നു.", "kṣētraṁ sandarśikkaṇamenn avaḷkku tōnnunnu."),
    ("I want to thank everyone.", "എല്ലാവരെയും നന്ദി പറയണം.", "ellāvareyuṁ nandi paṛayaṇaṁ."),
    ("They want us to wait.", "ഞങ്ങൾ കാത്തിരിക്കണമെന്ന് അവർ പറയുന്നു.", "ñaṅṅaḷ kāttirikkkaṇamenn avār paṛayunnu."),
    ("Want + verb infinitive is very common.", "ആഗ്രഹം + ക്രിയ നാമം സാധാരണം.", "āgrahaṁ + kriya nāmaṁ sādhāraṇaṁ."),
    ("Polite: āgrahikkunnu (formal want).", "Formal want — ആഗ്രഹിക്കുന്നു.", "āgrahikkunnu."),
)

DATA566 = D(
    ("I want him to study harder.", "അവൻ കൂടുതൽ പഠിക്കണമെന്ന് ഞാൻ ആഗ്രഹിക്കുന്നു.", "avan kūtutal paṭhikkaṇamenn njān āgrahikkunnu."),
    ("She wants them to leave.", "അവർ പോകണമെന്ന് അവൾ ആഗ്രഹിക്കുന്നു.", "avar pōkaṇamenn avaḷ āgrahikkunnu."),
    ("We want you to be on time.", "സമയത്ത് വരണമെന്ന് ഞങ്ങൾ ആഗ്രഹിക്കുന്നു.", "samayatt varaṇamenn ñaṅṅaḷ āgrahikkunnu."),
    ("Parents want children to be honest.", "കുട്ടികൾ സത്യവാന്മാരായിരിക്കണമെന്ന് മാതാപിതാക്കൾ ആഗ്രഹിക്കുന്നു.", "kuṭṭikaḷ satyavānmārāyirikaṇamenn mātāpitākkaḷ āgrahikkunnu."),
    ("He wants me to call.", "എന്നെ വിളിക്കണമെന്ന് അവൻ പറയുന്നു.", "enne viḷikkaṇamenn avan paṛayunnu."),
    ("They want her to sing.", "അവൾ പാടണമെന്ന് അവർ ആഗ്രഹിക്കുന്നു.", "avaḷ pāṭaṇamenn avār āgrahikkunnu."),
    ("I do not want you to worry.", "നീ വിഷമിക്കരുതെന്ന് എനിക്ക് തോന്നുന്നു.", "nī viṣamikkarutenn enikk tōnnunnu."),
    ("She wants the room cleaned.", "മുറി വൃത്തിയാക്കണമെന്ന് അവൾ പറയുന്നു.", "muṛi vr̥ttiyākkaṇamenn avaḷ paṛayunnu."),
    ("We want everyone to participate.", "എല്ലാവരും പങ്കെടുക്കണമെന്ന് ഞങ്ങൾ ആഗ്രഹിക്കുന്നു.", "ellāvaruṁ paṅṅkeṭukkaṇamenn ñaṅṅaḷ āgrahikkunnu."),
    ("He wants his friend to succeed.", "സുഹൃത്ത് വിജയിക്കണമെന്ന് അവൻ ആഗ്രഹിക്കുന്നു.", "suhr̥tt vijayikkaṇamenn avan āgrahikkunnu."),
    ("Complex object clauses use \"enn\".", "ഉപവാക്യങ്ങൾ “എന്ന്” കൊണ്ട്.", "upavākyaṅṅaḷ “enn” koṇṭ."),
    ("I want the government to act.", "സർക്കാർ പ്രവർത്തിക്കണമെന്ന് ഞാൻ ആഗ്രഹിക്കുന്നു.", "sarkkār pravarttikkaṇamenn njān āgrahikkunnu."),
    ("They want us to sign.", "ഞങ്ങൾ ഒപ്പിടണമെന്ന് അവർ പറയുന്നു.", "ñaṅṅaḷ oppiṭaṇamenn avār paṛayunnu."),
    ("She wants her son to become a doctor.", "മകൻ ഡോക്ടറാകണമെന്ന് അവൾ ആഗ്രഹിക്കുന്നു.", "makan ḍōkṭarākaṇamenn avaḷ āgrahikkunnu."),
    ("We want rain for the crops.", "വിളകൾക്ക് മഴ വേണമെന്ന് ഞങ്ങൾ പ്രാർത്ഥിക്കുന്നു.", "viḷakaḷkku maḻa vēṇamenn ñaṅṅaḷ prārththikkunnu."),
    ("Reported want: he said he wanted (avan paṟaññu vēṇamenn).", "He said he wanted — അവൻ പറഞ്ഞു വേണമെന്ന്.", "avan paṞaññu vēṇamenn."),
    ("Distinguish want (āgrahaṁ) from need (āvaśyaṁ).", "ആഗ്രഹവും ആവശ്യവും വേറെ.", "āgrahavuṁ āvaśyavuṁ veṛe."),
    ("Polite: I hope you will please do (dayavāyi ceyyaṇamenn).", "Please do — ദയവായി ചെയ്യണമെന്ന്.", "dayavāyi ceyyaṇamenn."),
)

DATA567 = D(
    ("We are supposed to arrive by ten.", "പത്തുമണിക്കകം എത്തണമെന്നാണ് പ്രതീക്ഷ.", "pathumaṇikkakaṁ eṭṭaṇamennāṇ pratīkṣa."),
    ("He is supposed to be the leader.", "അവൻ നേതാവാണെന്ന് കരുതപ്പെടുന്നു.", "avan nētāvāṇenn karutappeṭunnu."),
    ("I am not supposed to tell anyone.", "ആർക്കും പറയാൻ പാടില്ലെന്നാണ്.", "ārkkuṁ paṛayān pāṭillennāṇ."),
    ("The train is supposed to leave now.", "ഇപ്പോൾ ട്രെയിൻ പുറപ്പെടണമെന്നാണ്.", "ippōḷ ṭreyin puṛappeṭaṇamennāṇ."),
    ("You are supposed to wear a mask.", "മാസ്ക് ധരിക്കണമെന്നാണ് നിർദ്ദേശം.", "māsk dharikkaṇamennāṇ nirddēśaṁ."),
    ("We were supposed to meet yesterday.", "ഇന്നലെ കാണണമെന്നായിരുന്നു.", "innale kāṇaṇamennāyirunnu."),
    ("It is supposed to rain.", "മഴ പെയ്യുമെന്ന് പ്രതീക്ഷ.", "maḻa peyymenn pratīkṣa."),
    ("They are supposed to report to the office.", "ഓഫീസിൽ റിപ്പോർട്ട് ചെയ്യണമെന്നാണ്.", "ōphīsil rippōṭṭ ceyyaṇamennāṇ."),
    ("\"ennāṇ tōnnunnat\" for supposed.", "പ്രതീക്ഷ “എന്നാണ് തോന്നുന്നത്”.", "pratīkṣa “ennāṇ tōnnunnat”."),
    ("I am supposed to finish this today.", "ഇന്ന് ഇത് പൂർത്തിയാക്കണമെന്നാണ്.", "inn it pūrttiyākkaṇamennāṇ."),
    ("She is supposed to be an expert.", "അവൾ വിദഗ്ധയാണെന്ന് പറയപ്പെടുന്നു.", "avaḷ vidagdhayāṇenn paṛayappeṭunnu."),
    ("The medicine is supposed to work fast.", "മരുന്ന് വേഗത്തിൽ പ്രവർത്തിക്കുമെന്ന്.", "marunn vēgattil pravarttikumenn."),
    ("We are not supposed to park here.", "ഇവിടെ പാർക്ക് ചെയ്യാൻ പാടില്ല.", "ivide pārkk ceyyān pāṭilla."),
    ("He was supposed to call.", "വിളിക്കണമെന്നായിരുന്നു.", "viḷikkaṇamennāyirunnu."),
    ("Official: it is directed (nirddēśiccirikkunnu).", "It is directed — നിർദ്ദേശിച്ചിരിക്കുന്നു.", "nirddēśiccirikkunnu."),
    ("Compare: expected vs obligated.", "പ്രതീക്ഷയും ബാധ്യതയും വേറെ.", "pratīkṣayuṁ bādhyatavuṁ veṛe."),
    ("The meeting is supposed to end at five.", "അഞ്ചുമണിക്ക് മീറ്റിംഗ് അവസാനിക്കുമെന്ന്.", "añcumaṇik mīṭiṅ avasānikkumenn."),
    ("I thought it was supposed to be easy.", "എളുപ്പമാണെന്ന് കരുതി.", "eḷuppamāṇenn karuti."),
)

DATA568 = D(
    ("I like to swim in the sea.", "കടലിൽ നീന്താൻ എനിക്ക് ഇഷ്ടമാണ്.", "kaḍalil nīntān enikk iṣṭamāṇ."),
    ("She likes to read novels.", "നോവലുകൾ വായിക്കാൻ അവൾക്ക് ഇഷ്ടമാണ്.", "nōvalukaḷ vāyikkān avaḷkku iṣṭamāṇ."),
    ("We like to walk in the rain.", "മഴയിൽ നടക്കാൻ ഞങ്ങൾക്ക് ഇഷ്ടമാണ്.", "maḻayil naṭakkān ñaṅṅaḷkku iṣṭamāṇ."),
    ("He does not like to wait.", "കാത്തിരിക്കാൻ അവന് ഇഷ്ടമല്ല.", "kāttirikkān avan iṣṭamalla."),
    ("They like to watch football.", "ഫുട്ബോൾ കാണാൻ അവർക്ക് ഇഷ്ടമാണ്.", "phuṭbōḷ kāṇān avarkk iṣṭamāṇ."),
    ("I would like to thank you.", "നന്ദി പറയാൻ ഞാൻ ആഗ്രഹിക്കുന്നു.", "nandi paṛayān njān āgrahikkunnu."),
    ("She likes listening to music.", "സംഗീതം കേൾക്കാൻ അവൾക്ക് ഇഷ്ടമാണ്.", "saṁgītaṁ kēḷkkān avaḷkku iṣṭamāṇ."),
    ("We do not like to argue.", "തർക്കിക്കാൻ ഞങ്ങൾക്ക് ഇഷ്ടമല്ല.", "tarkkikkān ñaṅṅaḷkku iṣṭamalla."),
    ("He likes to help others.", "മറ്റുള്ളവരെ സഹായിക്കാൻ അവന് ഇഷ്ടമാണ്.", "maṭṭuḷḷavare sahāyikkān avan iṣṭamāṇ."),
    ("Like + infinitive parallels English.", "ഇഷ്ടം + ക്രിയ നാമം.", "iṣṭaṁ + kriya nāmaṁ."),
    ("I like seeing children smile.", "കുട്ടികൾ ചിരിക്കുന്നത് കാണാൻ ഇഷ്ടമാണ്.", "kuṭṭikaḷ cirikkunna kāṇān iṣṭamāṇ."),
    ("She likes cooking for guests.", "അതിഥികൾക്ക് പാചകം ചെയ്യാൻ ഇഷ്ടമാണ്.", "atithikaḷkku pācakaṁ ceyyān iṣṭamāṇ."),
    ("We like to travel by train.", "ട്രെയിനിൽ യാത്ര ചെയ്യാൻ ഇഷ്ടമാണ്.", "ṭreyinil yātra ceyyān iṣṭamāṇ."),
    ("He likes to sleep early.", "നേരത്തെ ഉറങ്ങാൻ അവന് ഇഷ്ടമാണ്.", "nērattē uṟaṅṅān avan iṣṭamāṇ."),
    ("I do not like to waste food.", "ഭക്ഷണം പാഴാക്കാൻ എനിക്ക് ഇഷ്ടമല്ല.", "bhakṣaṇaṁ pāḻākkān enikk iṣṭamalla."),
    ("They like to celebrate festivals.", "ഉത്സവങ്ങൾ ആഘോഷിക്കാൻ ഇഷ്ടമാണ്.", "utsavaṅṅaḷ āghōṣikkān iṣṭamāṇ."),
    ("Expressing preference: rather than.", "ഇഷ്ടമില്ലാത്തത് വേണ്ട; മറ്റേത് എടുക്കുക.", "iṣṭamillātta vēṇṭa; maṭṭet eṭukkuka."),
    ("Polite: I prefer (iṣṭappeṭunnuṇṭ).", "I prefer — ഇഷ്ടപ്പെടുന്നുണ്ട്.", "iṣṭappeṭunnuṇṭ."),
)

DATA569 = D(
    ("I listen to the radio.", "ഞാൻ റേഡിയോ കേൾക്കുന്നു.", "njān rēḍiyō kēḷkkunnu."),
    ("She spoke to the manager.", "അവൾ മാനേജറോട് സംസാരിച്ചു.", "avaḷ mānejarōṭ saṁsāriccu."),
    ("We agree with the plan.", "ഞങ്ങൾ പദ്ധതിയോട് യോജിക്കുന്നു.", "ñaṅṅaḷ padhatiyōṭ yōjikkunnu."),
    ("He apologised to them.", "അവൻ അവരോട് മാപ്പ് പറഞ്ഞു.", "avan avarōṭ māpp paṟaññu."),
    ("I wrote to my uncle.", "ഞാൻ അമ്മാവന് കത്ത് എഴുതി.", "njān ammāvan katt eḻuti."),
    ("They laughed at the joke.", "അവർ തമാശയിൽ ചിരിച്ചു.", "avar tamāśayil ciriccu."),
    ("She depends on her salary.", "അവൾ ശമ്പളത്തിന് ആശ്രയിക്കുന്നു.", "avaḷ śampaḷattin āśrayikkunnu."),
    ("We care about the result.", "ഫലത്തെക്കുറിച്ച് ഞങ്ങൾ ശ്രദ്ധിക്കുന്നു.", "phalattēkkuricc ñaṅṅaḷ śraddhikkunnu."),
    ("He shouted at the crowd.", "അവൻ കൂട്ടത്തോട് കൂകി.", "avan kūṭṭattōṭ kūki."),
    ("I believe in honesty.", "സത്യത്തിൽ എനിക്ക് വിശ്വാസമുണ്ട്.", "satyattil enikk viśvāsamuṇṭ."),
    ("Verbs with fixed companions in English map to Malayalam postpositions.", "ഇംഗ്ലീഷിലെ നിശ്ചിത കൂട്ടുകൾ മലയാളത്തിൽ വ്യത്യസ്തം.", "iṅglīṣile niścita kūṭṭukaḷ malayāḷattil vyatystaṁ."),
    ("She succeeded in the interview.", "അവൾ ഇന്റർവ്യൂവിൽ വിജയിച്ചു.", "avaḷ iṇṭarvyūvil vijayiccu."),
    ("We arrived at the airport.", "ഞങ്ങൾ എയർപോർട്ടിൽ എത്തി.", "ñaṅṅaḷ eyarpōṭṭil etti."),
    ("He looked at the picture.", "അവൻ ചിത്രത്തിലേക്ക് നോക്കി.", "avan citrattilēkk nōkki."),
    ("I paid for the tickets.", "ഞാൻ ടിക്കറ്റിന് പണം കൊടുത്തു.", "njān ṭikkaṭṭin paṇaṁ koṭuttu."),
    ("They waited for the ferry.", "അവർ ഫെറിക്കായി കാത്തിരുന്നു.", "avar ferikkāyi kāttirunnu."),
    ("Learn verb + postposition pairs by reading.", "വായിച്ച് ക്രിയാ ജോഡികൾ പഠിക്കുക.", "vāyicc kriyā jōḍikaḷ paṭhikkuka."),
    ("Your teacher will correct preposition errors.", "പ്രിപോസിഷൻ പിശകുകൾ ട്യൂട്ടർ തിരുത്തും.", "pripōsiṣaṇ piśakukaḷ ṭyūṭṭar tiruttuṁ."),
)

DATA570 = D(
    ("I’m gonna go now (spoken).", "ഇപ്പോ ഞാൻ പോവാ.", "ippō njān pōvā."),
    ("Whatcha doing? (informal)", "എന്താ ചെയ്യുന്നേ?", "entā ceyyunnē?"),
    ("Gimme water (very informal).", "വെള്ളം താ.", "veḷḷaṁ tā."),
    ("Don’t worry (colloquial).", "വിഷമിക്കേണ്ട.", "viṣamikkēṇṭa."),
    ("It’s okay.", "കുഴപ്പമില്ല.", "kuḻappamilla."),
    ("See you (piṅṅe kāṇāṁ — see you later).", "പിന്നെ കാണാം.", "piṅṅe kāṇāṁ."),
    ("What’s up?", "എന്താ വിശേഷം?", "entā viśeṣaṁ?"),
    ("I dunno.", "അറിയില്ല.", "aṟiyilla."),
    ("Lemme see.", "ഒന്ന് കാണട്ടെ.", "onnu kāṇaṭṭe."),
    ("Gotta leave.", "പോകണം.", "pōkaṇaṁ."),
    ("Spoken Malayalam drops vowels in fast speech.", "വേഗത്തിൽ സ്വരങ്ങൾ വിട്ടുപോകും.", "vēgattil svaraṅṅaḷ viṭṭupōkuṁ."),
    ("Young people mix English words freely.", "യുവജനങ്ങൾ ഇംഗ്ലീഷ് വാക്കുകൾ കലർത്തുന്നു.", "yuvajanaṅṅaḷ iṅglīṣ vākkukaḷ kalarttunnu."),
    ("Learn colloquial forms after formal base.", "ഔപചാരികം കഴിഞ്ഞ് അനൗപചാരികം.", "aupacārikaṁ kaḻiññ anaupacārikaṁ."),
    ("Regional variants: Kozhikode vs Thiruvananthapuram.", "പ്രാദേശിക വ്യത്യാസം കോഴിക്കോടും തിരുവനന്തപുരവും.", "prādēśika vyatāsam kōḻikkōṭuṁ tiruvanantapuravuṁ."),
    ("Avoid slang in exams.", "പരീക്ഷയിൽ അനൗപചാരിക ഒഴിവാക്കുക.", "parīkṣayil anaupacārika oḻivākkuka."),
    ("Listen to Malayalam YouTube for short forms.", "ചെറു രൂപങ്ങൾക്ക് യൂട്യൂബ്.", "ceṛu rūpaṅṅaḷkku yūṭyūb."),
    ("Repeat after native speakers.", "മാതൃഭാഷക്കാരുടെ പിന്നാലെ പറയുക.", "mātṛbhāṣakkāruṭe piṅṅāle paṛayuka."),
    ("Balance formal and informal registers.", "ഔപചാരികയും അനൗപചാരികയും സന്തുലിതമാക്കുക.", "aupacārikayuṁ anaupacārikayuṁ santulitamākkuka."),
)
