# -*- coding: utf-8 -*-
"""Phrase-pattern chapters 543–580 for Malayalam lessons."""
from malayalam_lesson_content import R, _pad


def D(*t):
    return _pad([R(e, m, r) for e, m, r in t])


DATA543 = D(
    ("I am going to eat now.", "ഇപ്പോൾ ഞാൻ കഴിക്കാൻ പോകുന്നു.", "ippōḷ njān kaḻikkān pōkunnu."),
    ("She is going to sing at the school function.", "സ്കൂൾ അനുഷ്ഠാനത്തിൽ അവൾ പാടാൻ പോകുന്നു.", "skūḷ anuṣṭhānattil avaḷ pāṭān pōkunnu."),
    ("We are going to leave after tea.", "ചായ കഴിഞ്ഞ് ഞങ്ങൾ പോകാൻ പോകുന്നു.", "cāya kaḻiññ ñaṅṅaḷ pōkān pōkunnu."),
    ("He is going to read the report tonight.", "ഇന്ന് രാത്രി അവൻ റിപ്പോർട്ട് വായിക്കാൻ പോകുന്നു.", "inn rātri avan rippōṭṭ vāyikkān pōkunnu."),
    ("I am going to buy vegetables from the market.", "ഞാൻ ചന്തയിൽ നിന്ന് പച്ചക്കറി വാങ്ങാൻ പോകുന്നു.", "njān chantayil ninn paccakaṛi vāṅṅān pōkunnu."),
    ("They are going to play cricket in the evening.", "സായാഹ്നം അവർ ക്രിക്കറ്റ് കളിക്കാൻ പോകുന്നു.", "sāyāhnaṁ avār krikkeṭṭ kaḷikkān pōkunnu."),
    ("Are you going to come to our house tomorrow?", "നാളെ നീ ഞങ്ങളുടെ വീട്ടിലേക്ക് വരാൻ പോകുന്നുണ്ടോ?", "nāḷe nī ñaṅṅaḷuṭe vīṭṭilēkk varān pōkunnuṇṭō?"),
    ("I am going to call you after the meeting.", "മീറ്റിംഗ് കഴിഞ്ഞ് ഞാൻ നിന്നെ വിളിക്കാൻ പോകുന്നു.", "mīṭiṅ kaḻiññ njān ninne viḷikkān pōkunnu."),
    ("Mother is going to cook fish for lunch.", "ഉച്ചയ്ക്ക് അമ്മ മീൻ വറുത്തുകൊടുക്കാൻ പോകുന്നു.", "uccaykku amma mīṇ vaṛuttukoṭukkān pōkunnu."),
    ("We are going to meet near the bridge.", "ഞങ്ങൾ പാലത്തിനടുത്ത് കാണാൻ പോകുന്നു.", "ñaṅṅaḷ pālattinaṭutt kāṇān pōkunnu."),
    ("I am going to Thiruvananthapuram for two days.", "രണ്ടു ദിവസത്തേക്ക് ഞാൻ തിരുവനന്തപുരത്തേക്ക് പോകുന്നു.", "raṇṭu divasattēkk njān tiruvanantapurattēkk pōkunnu."),
    ("He is going to study harder this year.", "ഈ വർഷം അവൻ കൂടുതൽ പഠിക്കാൻ പോകുന്നു.", "ī varṣaṁ avan kūtutal paṭhikkān pōkunnu."),
    ("They are going to travel by night train.", "അവർ രാത്രി ട്രെയിനിൽ യാത്ര ചെയ്യാൻ പോകുന്നു.", "avar rātri ṭreyinil yātra ceyyān pōkunnu."),
    ("I am going to learn typing this month.", "ഈ മാസം ഞാൻ ടൈപ്പ് പഠിക്കാൻ പോകുന്നു.", "ī māsaṁ njān ṭaipp paṭhikkān pōkunnu."),
    ("She is going to visit her grandmother.", "അവൾ മുത്തശ്ശിയെ സന്ദർശിക്കാൻ പോകുന്നു.", "avaḷ muttaśśiye sandarśikkān pōkunnu."),
    ("We are going to plant trees on Sunday.", "ഞായറാഴ്ച ഞങ്ങൾ മരങ്ങൾ നടാൻ പോകുന്നു.", "ñāyaṟāḻcca ñaṅṅaḷ maraṅṅaḷ naṭān pōkunnu."),
    ("He is going to fix the roof tomorrow.", "നാളെ അവൻ മേൽക്കൂര നന്നാക്കാൻ പോകുന്നു.", "nāḷe avan mēlkkūra nannākkān pōkunnu."),
    ("I am going to write the exam in Malayalam.", "ഞാൻ പരീക്ഷ മലയാളത്തിൽ എഴുതാൻ പോകുന്നു.", "njān parīkṣa malayāḷattil eḻutān pōkunnu."),
)

DATA544 = D(
    ("I used to walk to school every day.", "പ്രതിദിനവും ഞാൻ സ്കൂളിലേക്ക് നടന്നുപോകുമായിരുന്നു.", "pratidinavuṁ njān skūlilēkk naṭannupōkumāyirunnu."),
    ("She used to sing in the church choir.", "അവൾ പള്ളിയിൽ ഗായകസംഘത്തിൽ പാടുമായിരുന്നു.", "avaḷ paḷḷiyil gāyakasaṁghattil pāṭumāyirunnu."),
    ("We used to visit grandparents during holidays.", "അവധിയിൽ ഞങ്ങൾ മുത്തച്ഛന്മാരെ കാണാൻ പോകുമായിരുന്നു.", "avadhiyil ñaṅṅaḷ muttacchanmāre kāṇān pōkumāyirunnu."),
    ("He used to work in a bank in Mumbai.", "അവൻ മുംബൈയിൽ ബാങ്കിൽ ജോലി ചെയ്യുമായിരുന്നു.", "avan mumba-yil bāṅkil jōli ceyyumāyirunnu."),
    ("They used to play in this street as children.", "കുട്ടികളായിരുന്നപ്പോൾ അവർ ഈ തെരുവിൽ കളിക്കുമായിരുന്നു.", "kuṭṭikaḷāyirunnappōḷ avār ī teruvil kaḷikkumāyirunnu."),
    ("I used to be afraid of darkness.", "എനിക്ക് ഇരുട്ടിനോട് പേടിയായിരുന്നു.", "enikk iruṭṭinōṭ pēṭiyāyirunnu."),
    ("She used to read Malayalam novels at night.", "അവൾ രാത്രി മലയാള നോവലുകൾ വായിക്കുമായിരുന്നു.", "avaḷ rātri malayāḷa nōvalukaḷ vāyikkumāyirunnu."),
    ("We used to buy milk from the cooperative.", "ഞങ്ങൾ സഹകരണ സംഘത്തിൽ നിന്ന് പാൽ വാങ്ങുമായിരുന്നു.", "ñaṅṅaḷ sahakaraṇa saṁghattil ninn pāl vāṅṅumāyirunnu."),
    ("He used to cycle to the office.", "അവൻ ഓഫീസിലേക്ക് സൈക്കിളിൽ പോകുമായിരുന്നു.", "avan ōphīsilēkk saikkiḷil pōkumāyirunnu."),
    ("Mother used to tell stories before sleep.", "ഉറങ്ങുന്നതിന് മുമ്പ് അമ്മ കഥ പറയുമായിരുന്നു.", "uṟaṅṅunnatin mumpe amma katha paṛayumāyirunnu."),
    ("I used to help my father in the shop.", "ഞാൻ അച്ഛന്റെ കടയിൽ സഹായിക്കുമായിരുന്നു.", "njān acchanṟe kaṭayil sahāyikkumāyirunnu."),
    ("We used to celebrate Onam with a big feast.", "ഞങ്ങൾ വലിയ വിരുന്നോടെ ഓണം ആഘോഷിക്കുമായിരുന്നു.", "ñaṅṅaḷ valiya virunnōṭe ōṇaṁ āghōṣikkumāyirunnu."),
    ("She used to teach in a primary school.", "അവൾ പ്രാഥമിക സ്കൂളിൽ പഠിപ്പിക്കുമായിരുന്നു.", "avaḷ prāthamika skūlil paṭhippikkumāyirunnu."),
    ("The river used to flood every monsoon.", "ഓരോ മൺസൂണിലും നദി വെള്ളം കവിയുമായിരുന്നു.", "ōrō maṇsūṇiluṁ nadi veḷḷaṁ kaviyumāyirunnu."),
    ("I used to listen to shortwave radio.", "ഞാൻ ഷോർട്ട് വേവ് റേഡിയോ കേൾക്കുമായിരുന്നു.", "njān śōṭṭ vēv rēḍiyō kēḷkkumāyirunnu."),
    ("He used to smoke but he quit.", "അവൻ പുകവലിച്ചിരുന്നു പക്ഷേ ഇപ്പോൾ നിർത്തി.", "avan pukavalicirunnu pakṣe ippōḷ nirtti."),
    ("We used to write letters before mobile phones.", "മൊബൈൽ വരുന്നതിന് മുമ്പ് ഞങ്ങൾ കത്ത് എഴുതുമായിരുന്നു.", "mōbail varunnatin mumpe ñaṅṅaḷ katt eḻutumāyirunnu."),
    ("They used to live in a joint family.", "അവർ സംയുക്ത കുടുംബത്തിൽ താമസിച്ചിരുന്നു.", "avar saṁyukta kuṭumbattil tāmasicirunnu."),
)

DATA545 = D(
    ("In older style people said \"pokumāyirunnu\" for habitual past.", "പഴയ ശൈലിയിൽ “പോകുമായിരുന്നു” എന്നത് പതിവായ ഭൂതകാലം കാണിക്കും.", "paḻaya śailiyil “pōkumāyirunnu” ennat pativāya bhūtakālaṁ kāṇikkuṁ."),
    ("Grandmother would sit in the veranda every evening.", "ഓരോ സായാഹ്നവും മുത്തശ്ശി വരാന്തയിൽ ഇരിക്കുമായിരുന്നു.", "ōrō sāyāhnavuṁ muttaśśi varāntayil irikkumāyirunnu."),
    ("The village used to be quieter twenty years ago.", "ഇരുപത് വർഷം മുമ്പ് ഗ്രാമം കൂടുതൽ ശാന്തമായിരുന്നു.", "irupat varṣaṁ mump grāmaṁ kūtutal śāntamāyirunnu."),
    ("Farmers used to depend on monsoon rains.", "കർഷകർ മൺസൂൺ മഴയെ ആശ്രയിച്ചിരുന്നു.", "karṣakar maṇsūṅ maḻaye āśrayicirunnu."),
    ("We would walk miles without buses then.", "അന്ന് ബസില്ലാതെ ഞങ്ങൾ മൈലുകൾ നടന്നിരുന്നു.", "ann basillāte ñaṅṅaḷ mailukaḷ naṭannirunnu."),
    ("He would read only by lamplight.", "അവൻ വിളക്കുവെളിച്ചത്തിൽ മാത്രം വായിക്കുമായിരുന്നു.", "avan viḷakkuviḷiccattil mātraṁ vāyikkumāyirunnu."),
    ("Stories used to travel orally between generations.", "കഥകൾ തലമുറകളിലൂടെ വായനയായി പരന്നിരുന്നു.", "kathakaḷ talamurakaḷilūṭe vāyanayāyi parannirunnu."),
    ("Women used to draw kolam at dawn.", "പ്രഭാതത്തിൽ സ്ത്രീകൾ കോലം വരയുമായിരുന്നു.", "prabhātattil strīkaḷ kōlaṁ varayumāyirunnu."),
    ("The temple bell would ring at six.", "ആറുമണിക്ക് ക്ഷേത്രത്തിൽ മണി മുഴങ്ങുമായിരുന്നു.", "āṛumaṇik kṣētrattil maṇi muḻaṅṅumāyirunnu."),
    ("Children used to swim in the pond.", "കുട്ടികൾ കുളത്തിൽ നീന്തുമായിരുന്നു.", "kuṭṭikaḷ kuḷattil nīntumāyirunnu."),
    ("We would share lunch at school.", "ഞങ്ങൾ സ്കൂളിൽ ഉച്ചഭക്ഷണം പങ്കിടുമായിരുന്നു.", "ñaṅṅaḷ skūlil uccabhakṣaṇaṁ paṅṅkiṭumāyirunnu."),
    ("He would carry milk in a brass vessel.", "അവൻ വെള്ളി പാത്രത്തിൽ പാൽ കൊണ്ടുവരുമായിരുന്നു.", "avan veḷḷi pātrattil pāl koṇṭuvarumāyirunnu."),
    ("Older Malayalam texts use fuller verb endings.", "പഴയ മലയാള ഗ്രന്ഥങ്ങളിൽ പൂർണ്ണ ക്രിയാരൂപങ്ങൾ കാണാം.", "paḻaya malayāḷa granthaṅṅaḷil pūrṇṇa kriyārūpaṅṅaḷ kāṇāṁ."),
    ("Compare literary and colloquial “used to”.", "സാഹിത്യഭാഷയും സംസാരഭാഷയും താരതമ്യം ചെയ്യുക.", "sāhityabhāṣayuṁ saṁsārabhāṣayuṁ tāratamyaṁ ceyyuka."),
    ("Your grandparents can share memories in this form.", "മുത്തച്ഛന്മാർ ഈ രൂപത്തിൽ ഓർമ്മകൾ പങ്കുവെക്കും.", "muttacchanmār ī rūpattil ōrmakaḷ paṅṅkuvekkuṁ."),
    ("Read old songs to hear habitual past.", "പഴയ പാട്ടുകൾ കേട്ട് പതിവ് ഭൂതകാലം അറിയുക.", "paḻaya pāṭṭukaḷ kēṭṭ pativ bhūtakālaṁ aṟiyuka."),
    ("Teachers explain when \"āyirunnu\" marks past habit.", "“ആയിരുന്നു” പതിവ് ഭൂതം എപ്പോൾ എന്ന് അധ്യാപകർ പറയും.", "“āyirunnu” pativ bhūtam epōḷ ennu adhyāpakar paṛayuṁ."),
    ("Write five sentences about your childhood using this style.", "ബാല്യകാലത്തെക്കുറിച്ച് ഈ ശൈലിയിൽ അഞ്ചു വാക്യങ്ങൾ എഴുതുക.", "bālyakālattēkkuricc ī śailiyil añcu vākyaṅṅaḷ eḻutuka."),
)

DATA546 = D(
    ("If it rains, we will stay at home.", "മഴ പെയ്താൽ ഞങ്ങൾ വീട്ടിൽ താമസിക്കും.", "maḻa peytāl ñaṅṅaḷ vīṭṭil tāmasikkuṁ."),
    ("If you call me, I will come.", "നീ എന്നെ വിളിച്ചാൽ ഞാൻ വരും.", "nī enne viḷiccāl njān varuṁ."),
    ("If she studies hard, she will pass.", "അവൾ കഠിനമായി പഠിച്ചാൽ ജയിക്കും.", "avaḷ kaṭhinamāyi paṭhiccāl jayikkuṁ."),
    ("If you are hungry, eat something.", "ആകലെങ്കിൽ എന്തെങ്കിലും കഴിക്കുക.", "ākaleṅkiḷ enteṅkiluṁ kaḻikkuka."),
    ("If the bus is late, we will take a taxi.", "ബസ് വൈകിയാൽ ഞങ്ങൾ ടാക്സി എടുക്കും.", "bas vaikiyāl ñaṅṅaḷ ṭāksi eṭukkuṁ."),
    ("If you do not understand, ask again.", "മനസ്സിലായില്ലെങ്കിൽ വീണ്ടും ചോദിക്കുക.", "manassilāyillenkiḷ vīṇṭuṁ cōdikkuka."),
    ("If they agree, we will sign the contract.", "അവർ സമ്മതിച്ചാൽ ഞങ്ങൾ കരാർ ഒപ്പിടും.", "avar sammaticcāl ñaṅṅaḷ karār oppiṭuṁ."),
    ("If I save money, I can travel next year.", "പണം സംരക്ഷിച്ചാൽ അടുത്ത വർഷം യാത്ര ചെയ്യാം.", "paṇaṁ saṁrakṣiccāl aṭutta varṣaṁ yātra ceyyāṁ."),
    ("If you see him, give him this letter.", "അവനെ കണ്ടാൽ ഈ കത്ത് കൊടുക്കുക.", "avane kaṇṭāl ī katt koṭukkuka."),
    ("If the shop is closed, come back tomorrow.", "കട അടഞ്ഞാൽ നാളെ വീണ്ടും വാ.", "kaṭa aṭaññāl nāḷe vīṇṭuṁ vā."),
    ("If we leave now, we will reach on time.", "ഇപ്പോൾ പുറപ്പെട്ടാൽ സമയത്ത് എത്തും.", "ippōḷ puṛappeṭṭāl samayatt ettum."),
    ("If you heat water, it will boil.", "വെള്ളം ചൂടാക്കിയാൽ അത് തിളക്കും.", "veḷḷaṁ cūṭākkiyāt at tiḷakkuṁ."),
    ("If you respect elders, they will bless you.", "മുതിർന്നവരെ ബഹുമാനിച്ചാൽ അവർ ആശീർവദിക്കും.", "mutirnnavare bahumāniccāl avār āśīrvadikkuṁ."),
    ("If the phone rings, answer it.", "ഫോൺ മുഴങ്ങിയാൽ എടുക്കുക.", "phōn muḻaṅṅiyāl eṭukkuka."),
    ("If you want help, tell me.", "സഹായം വേണമെങ്കിൽ എന്നോട് പറയുക.", "sahāyaṁ vēṇamenkiḷ ennōṭ paṛayuka."),
    ("If the road is blocked, take another route.", "റോഡ് തടസ്സപ്പെട്ടാൽ മറ്റൊരു വഴി എടുക്കുക.", "rōḍ tṭassappeṭṭā maṭṭoru vazhi eṭukkuka."),
    ("If you practice daily, you will improve.", "ദിവസവും പരിശീലിച്ചാൽ നല്ലതാകും.", "divasavuṁ pariśīlikcāl nallatākuṁ."),
    ("Malayalam often uses \"engil\" or \"āṇengkil\" in the apodosis.", "ഫലഭാഗത്തിൽ “എങ്കിൽ”, “ആണെങ്കിൽ” എന്നിവ ഉപയോഗിക്കാം.", "phalabhāgattil “eṅkiḷ”, “āṇenkiḷ” enniva upayōgikkāṁ."),
)

DATA547 = D(
    ("I agree with you on this point.", "ഈ കാര്യത്തിൽ ഞാൻ നിങ്ങളോട് യോജിക്കുന്നു.", "ī kāryattil njān niṅṅaḷōṭ yōjikkunnu."),
    ("She depends on her salary.", "അവൾ ശമ്പളത്തിന് ആശ്രയിക്കുന്നു.", "avaḷ śampaḷattin āśrayikkunnu."),
    ("We laughed at the joke.", "ഞങ്ങൾ തമാശയിൽ ചിരിച്ചു.", "ñaṅṅaḷ tamāśayil ciriccu."),
    ("He shouted at the driver.", "അവൻ ഡ്രൈവറോട് കൂകി.", "avan ḍraivarōṭ kūki."),
    ("I believe in hard work.", "എനിക്ക് കഠിനാധ്വാനത്തിൽ വിശ്വാസമുണ്ട്.", "enikk kaṭhinādhvānattil viśvāsamuṇṭ."),
    ("She succeeded in the exam.", "അവൾ പരീക്ഷയിൽ വിജയിച്ചു.", "avaḷ parīkṣayil vijayiccu."),
    ("We arrived at the station.", "ഞങ്ങൾ സ്റ്റേഷനിൽ എത്തി.", "ñaṅṅaḷ sṟṟēṣanil etti."),
    ("He looked at the sky.", "അവൻ ആകാശത്തിലേക്ക് നോക്കി.", "avan ākāśattilēkk nōkki."),
    ("She listened to the story.", "അവൾ കഥ കേട്ടു.", "avaḷ katha kēṭṭu."),
    ("I apologised for the mistake.", "പിശകിന് ഞാൻ മാപ്പ് പറഞ്ഞു.", "piśakin njān māpp paṟaññu."),
    ("They waited for the bus.", "അവർ ബസിനായി കാത്തിരുന്നു.", "avar basināyi kāttirunnu."),
    ("He paid for the tickets.", "അവൻ ടിക്കറ്റിന് പണം കൊടുത്തു.", "avan ṭikkaṭṭin paṇaṁ koṭuttu."),
    ("We care about the environment.", "ഞങ്ങൾ പരിസ്ഥിതിയെക്കുറിച്ച് സംരക്ഷിക്കുന്നു.", "ñaṅṅaḷ paristhitiyekkuricc saṁrakṣikkunnu."),
    ("She dreams of becoming a doctor.", "ഡോക്ടറാകണമെന്ന് അവൾ സ്വപ്നം കാണുന്നു.", "ḍōkṭarākaṇamenn avaḷ svapnaṁ kāṇunnu."),
    ("I differ from his opinion.", "അവന്റെ അഭിപ്രായത്തിൽ നിന്ന് ഞാൻ വ്യത്യസ്തനാണ്.", "avanṟe abhiprāyattil ninn njān vyatystanāṇ."),
    ("He escaped from the crowd.", "അവൻ കൂട്ടത്തിൽ നിന്ന് രക്ഷപ്പെട്ടു.", "avan kūṭṭattil ninn rakṣappeṭṭu."),
    ("We rely on public transport.", "ഞങ്ങൾ പൊതു ഗതാഗതത്തെ ആശ്രയിക്കുന്നു.", "ñaṅṅaḷ pōtu gatāgattatte āśrayikkunnu."),
    ("Verbs with fixed prepositions in English map to Malayalam case or postpositions.", "ഇംഗ്ലീഷിലെ നിശ്ചിത പ്രിപോസിഷൻ മലയാളത്തിൽ വിഭക്തിയോട് കൂടിയാണ് വരുന്നത്.", "iṅglīṣile niścita pripōsiṣaṇ malayāḷattil vibhakti yōṭ kūṭiyāṇ varunnat."),
)

DATA548 = D(
    ("This is a beautiful garden.", "ഇത് മനോഹരമായ ഒരു തോട്ടമാണ്.", "it manōharamāya oru tōṭṭamāṇ."),
    ("She is taller than her sister.", "അവൾ സഹോദരിയെക്കാൾ ഉയരമുണ്ട്.", "avaḷ sahōdariyekkāḷ uyaramuṇṭ."),
    ("The coffee is too hot.", "കാപ്പി വളരെ ചൂടാണ്.", "kāppi vaḷare cūṭāṇ."),
    ("We bought fresh fish.", "ഞങ്ങൾ പുതിയ മീൻ വാങ്ങി.", "ñaṅṅaḷ putiya mīṇ vāṅṅi."),
    ("He is a kind person.", "അവൻ ദയാലുവായ മനുഷ്യനാണ്.", "avan dayāluāya manuṣyanāṇ."),
    ("The road is narrow and winding.", "റോഡ് ഇടുങ്ങിയതും വളവുള്ളതുമാണ്.", "rōḷ iṭuṅṅiyatvuṁ vaḷavuḷḷatumāṇ."),
    ("Her voice is sweet.", "അവളുടെ ശബ്ദം മധുരമാണ്.", "avaḷuṭe śabdaṁ madhuramāṇ."),
    ("The exam was difficult.", "പരീക്ഷ കഠിനമായിരുന്നു.", "parīkṣa kaṭhinamāyirunnu."),
    ("I feel happy today.", "ഇന്ന് എനിക്ക് സന്തോഷമുണ്ട്.", "inn enikk saṁtōṣamuṇṭ."),
    ("The sky is clear after the rain.", "മഴയ്ക്ക് ശേഷം ആകാശം വെളുത്തിരിക്കുന്നു.", "maḻaykku śeṣaṁ ākāśaṁ veḷuttirikkunnu."),
    ("That is an old temple.", "അത് പഴയ ക്ഷേത്രമാണ്.", "at paḻaya kṣētramāṇ."),
    ("We need clean water.", "ഞങ്ങൾക്ക് ശുദ്ധമായ വെള്ളം വേണം.", "ñaṅṅaḷkku śuddhamāya veḷḷaṁ vēṇaṁ."),
    ("The child is afraid.", "കുട്ടിക്ക് പേടിയാണ്.", "kuṭṭikk pēṭiyāṇ."),
    ("He gave a honest answer.", "അവൻ നേര് ഉത്തരം നൽകി.", "avan nēr uttaraṁ nalki."),
    ("The food was delicious.", "ഭക്ഷണം രുചിയായിരുന്നു.", "bhakṣaṇaṁ ruciyāyirunnu."),
    ("She wore a bright sari.", "അവൾ തെളിഞ്ഞ നിറമുള്ള സാരി ഉടുത്തു.", "avaḷ teḷiñña niramuḷḷa sāri uṭuttu."),
    ("The mountain looks blue from here.", "ഇവിടെ നിന്ന് മല നീലയായി കാണപ്പെടുന്നു.", "ivide ninn mala nīlayāyi kāṇappeṭunnu."),
    ("Adjectives usually come before the noun in Malayalam.", "മലയാളത്തിൽ വിശേഷണങ്ങൾ പലപ്പോഴും നാമത്തിന് മുമ്പ് വരുന്നു.", "malayāḷattil viśeṣaṇaṅṅaḷ palappōḻuṁ nāmattin mump varunnu."),
)

DATA549 = D(
    ("I can swim in the river.", "ഞാൻ നദിയിൽ നീന്താൻ കഴിയും.", "njān nadiyil nīntān kaḻiyuṁ."),
    ("She can speak four languages.", "അവൾ നാല് ഭാഷകൾ സംസാരിക്കാൻ കഴിയും.", "avaḷ nāl bhāṣakaḷ saṁsārikkān kaḻiyuṁ."),
    ("We cannot come tomorrow.", "അടുത്ത നാളെ ഞങ്ങൾക്ക് വരാൻ കഴിയില്ല.", "aṭutta nāḷe ñaṅṅaḷkku varān kaḻiyilla."),
    ("He can fix the computer.", "അവന് കമ്പ്യൂട്ടർ നന്നാക്കാൻ കഴിയും.", "avan kampyūṭṭar nannākkān kaḻiyuṁ."),
    ("Can you help me?", "എന്നെ സഹായിക്കാൻ കഴിയുമോ?", "enne sahāyikkān kaḻiyumō?"),
    ("I could not sleep last night.", "ഇന്നലെ രാത്രി എനിക്ക് ഉറങ്ങാൻ കഴിഞ്ഞില്ല.", "innale rātri enikk uṟaṅṅān kaḻiññilla."),
    ("She can drive a car.", "അവൾക്ക് കാർ ഓടിക്കാൻ കഴിയും.", "avaḷkku kār ōṭikkān kaḻiyuṁ."),
    ("We can see the sea from the balcony.", "ബാല്കണിയിൽ നിന്ന് കടൽ കാണാൻ ഞങ്ങൾക്ക് കഴിയും.", "bālkaṇiyil ninn kaḍal kāṇān ñaṅṅaḷkku kaḻiyuṁ."),
    ("He cannot hear well.", "അവന് നന്നായി കേൾക്കാൻ കഴിയില്ല.", "avan nannāyi kēḷkkān kaḻiyilla."),
    ("I can read Malayalam slowly.", "എനിക്ക് മലയാളം മെല്ലെ വായിക്കാൻ കഴിയും.", "enikk malayāḷaṁ melle vāyikkān kaḻiyuṁ."),
    ("They can arrive before noon.", "ഉച്ചയ്ക്ക് മുമ്പ് അവർക്ക് എത്താൻ കഴിയും.", "uccaykku mumpe avarkk ettān kaḻiyuṁ."),
    ("She could sing when she was young.", "അവൾ ചെറുപ്പത്തിൽ പാടാൻ കഴിയുമായിരുന്നു.", "avaḷ ceṛuppattil pāṭān kaḻiyumāyirunnu."),
    ("We can walk this distance.", "ഈ ദൂരം ഞങ്ങൾക്ക് നടന്നുപോകാൻ കഴിയും.", "ī dūraṁ ñaṅṅaḷkku naṭannupōkān kaḻiyuṁ."),
    ("I cannot eat spicy food.", "എനിക്ക് മസാലകൂടുതലുള്ള ഭക്ഷണം കഴിക്കാൻ കഴിയില്ല.", "enikk masālakūtutaluḷḷa bhakṣaṇaṁ kaḻikkān kaḻiyilla."),
    ("He can lift this box.", "അവന് ഈ പെട്ടി ഉയർത്താൻ കഴിയും.", "avan ī peṭṭi uyarttān kaḻiyuṁ."),
    ("Can we sit here?", "ഇവിടെ ഇരിക്കാൻ ഞങ്ങൾക്ക് കഴിയുമോ?", "ivide irikkān ñaṅṅaḷkku kaḻiyumō?"),
    ("Ability in Malayalam often uses \"kaḻiyuka\" or \"peṭuka\".", "ക്ഷമത “കഴിയുക”, “പറ്റുക” എന്നിവ കൊണ്ട് പ്രകടിപ്പിക്കാം.", "kṣamata “kaḻiyuka”, “peṭuka” enniva koṇṭ prakaṭippikkāṁ."),
    ("\"śakti\" also expresses physical ability in formal style.", "ഔപചാരിക മലയാളത്തിൽ “ശക്തി” ശാരീരിക കഴിവ് കാണിക്കും.", "aupacārika malayāḷattil “śakti” śārīrika kaḻiv kāṇikkuṁ."),
)

DATA550 = D(
    ("I want water.", "എനിക്ക് വെള്ളം വേണം.", "enikk veḷḷaṁ vēṇaṁ."),
    ("She needs rest.", "അവൾക്ക് വിശ്രമം വേണം.", "avaḷkku viśramaṁ vēṇaṁ."),
    ("We want to visit Kerala.", "ഞങ്ങൾ കേരളം സന്ദർശിക്കണം.", "ñaṅṅaḷ kēraḷaṁ sandarśikkaṇaṁ."),
    ("He does not want money.", "അവന് പണം വേണ്ട.", "avan paṇaṁ vēṇṭa."),
    ("I need your signature.", "എനിക്ക് നിങ്ങളുടെ ഒപ്പ് വേണം.", "enikk niṅṅaḷuṭe opp vēṇaṁ."),
    ("They want to leave early.", "അവർ നേരത്തെ പോകാൻ ആഗ്രഹിക്കുന്നു.", "avar nērattē pōkān āgrahikkunnu."),
    ("I wanted to call you yesterday.", "ഇന്നലെ നിന്നെ വിളിക്കണമെന്ന് എനിക്ക് തോന്നി.", "innale ninne viḷikkaṇamenn enikk tōnni."),
    ("She needs help with Malayalam.", "അവൾക്ക് മലയാളത്തിൽ സഹായം വേണം.", "avaḷkku malayāḷattil sahāyaṁ vēṇaṁ."),
    ("We want peace in the family.", "ഞങ്ങൾ കുടുംബത്തിൽ സമാധാനം വേണം.", "ñaṅṅaḷ kuṭumbattil samādhānaṁ vēṇaṁ."),
    ("He wants a new job.", "അവന് പുതിയ ജോലി വേണം.", "avan putiya jōli vēṇaṁ."),
    ("Do you need anything?", "നിനക്ക് എന്തെങ്കിലും വേണോ?", "ninakku enteṅkiluṁ vēṇō?"),
    ("I do not need this.", "ഇത് എനിക്ക് വേണ്ട.", "it enikk vēṇṭa."),
    ("They needed food and shelter.", "അവർക്ക് ഭക്ഷണവും അഭയവും വേണമായിരുന്നു.", "avarkk bhakṣaṇavuṁ abhayavuṁ vēṇamāyirunnu."),
    ("We want to learn from you.", "ഞങ്ങൾ നിങ്ങളിൽ നിന്ന് പഠിക്കണം.", "ñaṅṅaḷ niṅṅaḷil ninn paṭhikkaṇaṁ."),
    ("The plant needs water.", "ചെടിക്ക് വെള്ളം വേണം.", "ceṭikk veḷḷaṁ vēṇaṁ."),
    ("I have been wanting to meet you.", "നിന്നെ കാണണമെന്ന് എനിക്ക് തോന്നിക്കൊണ്ടിരിക്കുന്നു.", "ninne kāṇaṇamenn enikk tōnnikkoṇṭirikkunnu."),
    ("\"vēṇaṁ\" is stronger than \"iṣṭaṁ\" for need.", "ആവശ്യത്തിന് “വേണം”; “ഇഷ്ടം” ഇഷ്ടം മാത്രം.", "āvaśyattin “vēṇaṁ”; “iṣṭaṁ” iṣṭaṁ mātraṁ."),
    ("\"āvaśyamuṇṭ\" is formal for need.", "ഔപചാരികമായി “ആവശ്യമുണ്ട്” ഉപയോഗിക്കാം.", "aupacārikamāyi “āvaśyamuṇṭ” upayōgikkāṁ."),
)

DATA551 = D(
    ("He became a doctor.", "അവൻ ഡോക്ടറായി.", "avan ḍōkṭarāyi."),
    ("The sky became dark.", "ആകാശം ഇരുണ്ടു.", "ākāśaṁ iruṇṭu."),
    ("She became famous.", "അവൾ പ്രസിദ്ധയായി.", "avaḷ prasiddhayāyi."),
    ("We became friends.", "ഞങ്ങൾ സുഹൃത്തുക്കളായി.", "ñaṅṅaḷ suhr̥uttukḷāyi."),
    ("It happened yesterday.", "ഇന്നലെ അത് സംഭവിച്ചു.", "innale at saṁbhaviccu."),
    ("What happened here?", "ഇവിടെ എന്ത് സംഭവിച്ചു?", "ivide ent saṁbhaviccu?"),
    ("The plan became successful.", "പദ്ധതി വിജയകരമായി.", "padhati vijayakaramāyi."),
    ("He became angry.", "അവൻ കോപിഷ്ഠനായി.", "avan kōpiṣṭhanāyi."),
    ("The child became quiet.", "കുഞ്ഞ് ശാന്തനായി.", "kuññ śāntanāyi."),
    ("Winter became colder.", "ശൈത്യകാലം കൂടുതൽ തണുപ്പായി.", "śaityakālaṁ kūtutal taṇuppāyi."),
    ("She became a teacher.", "അവൾ അധ്യാപികയായി.", "avaḷ adhyāpikayāyi."),
    ("We became worried.", "ഞങ്ങൾ ആശങ്കാകുലരായി.", "ñaṅṅaḷ āśaṅkākularāyi."),
    ("The road became slippery.", "റോഡ് വഴുതലായി.", "rōḍ vaḻutalāyi."),
    ("He became ill after the journey.", "യാത്രക്ക് ശേഷം അവൻ രോഗിയായി.", "yātrakk śeṣaṁ avan rōgiyāyi."),
    ("\"ākuka\" marks becoming; \"saṁbhavikuka\" marks events.", "“ആകുക” മാറ്റം; “സംഭവിക്കുക” സംഭവം.", "“ākuka” māṭṭaṁ; “saṁbhavikuka” saṁbhavaṁ."),
    ("Use \"peṭuka\" colloquially for happening.", "സംസാരത്തിൽ “പറ്റുക” സംഭവം കാണിക്കാം.", "saṁsāraṭṭil “peṭuka” saṁbhavaṁ kāṇikkāṁ."),
    ("The news became known everywhere.", "വാർത്ത എല്ലായിടത്തും അറിയപ്പെട്ടു.", "vārttha ellāyiṭattuṁ aṟiyappeṭṭu."),
    ("Life became easier with technology.", "സാങ്കേതികവിദ്യ കൊണ്ട് ജീവിതം എളുപ്പമായി.", "sāṅkētikavidya koṇṭ jīvitaṁ eḷuppamāyi."),
)

DATA552 = D(
    ("You should rest now.", "നീ ഇപ്പോൾ വിശ്രമിക്കണം.", "nī ippōḷ viśramikkaṇaṁ."),
    ("We should help the poor.", "ഞങ്ങൾ ദരിദ്രരെ സഹായിക്കണം.", "ñaṅṅaḷ daridrare sahāyikkaṇaṁ."),
    ("He should see a doctor.", "അവൻ ഡോക്ടറെ കാണണം.", "avan ḍōkṭṭare kāṇaṇaṁ."),
    ("I should have called earlier.", "മുമ്പ് വിളിക്കണമായിരുന്നു.", "mump viḷikkaṇamāyirunnu."),
    ("She should study more.", "അവൾ കൂടുതൽ പഠിക്കണം.", "avaḷ kūtutal paṭhikkaṇaṁ."),
    ("They should not waste water.", "അവർ വെള്ളം പാഴാക്കരുത്.", "avar veḷḷaṁ pāḻākkarut."),
    ("You should wear a helmet.", "ഹെൽമെറ്റ് ധരിക്കണം.", "helmeṭṭ dharikkaṇaṁ."),
    ("We should respect everyone.", "എല്ലാവരെയും ബഹുമാനിക്കണം.", "ellāvareyuṁ bahumānikkaṇaṁ."),
    ("He should apologise.", "അവൻ മാപ്പ് പറയണം.", "avan māpp paṛayaṇaṁ."),
    ("I should go home early.", "ഞാൻ നേരത്തെ വീട്ടിൽ പോകണം.", "njān nērattē vīṭṭil pōkaṇaṁ."),
    ("\"vēṇaṁ\" with obligation sense overlaps with should.", "ബാധ്യതയിൽ “വേണം” “ചെയ്യണം” എന്നിവ വരുന്നു.", "bādhyatayil “vēṇaṁ” “ceyyaṇaṁ” enniva varunnu."),
    ("Teachers say \"ceyuka\" for polite should.", "അധ്യാപകർ “ചെയ്യുക” എന്ന് മര്യാദയോടെ പറയും.", "adhyāpakar “ceyuka” ennu maryādayōṭe paṛayuṁ."),
    ("You should not tell lies.", "കള്ളം പറയരുത്.", "kaḷḷaṁ paṛayarut."),
    ("We should save electricity.", "വൈദ്യുതി ലാഭിക്കണം.", "vaidyuti lābhikkaṇaṁ."),
    ("She should check the answer key.", "അവൾ ഉത്തരക്കുറി പരിശോധിക്കണം.", "avaḷ uttarakṛi pariśōdhikkaṇaṁ."),
    ("He should have informed us.", "ഞങ്ങളെ അറിയിക്കണമായിരുന്നു.", "ñaṅṅaḷe aṟiyikkaṇamāyirunnu."),
    ("Moral advice often uses \"nannāyirikuṁ\".", "നൈതിക ഉപദേശത്തിൽ “നന്നായിരിക്കും” വരുന്നു.", "naithika upadēśattil “nannāyirikuṁ” varunnu."),
    ("Compare: must (stronger) vs should (softer).", "“ചെയ്യണം” ബലം കൂടുതൽ; “ചെയ്താൽ നന്ന്” മൃദു.", "“ceyyaṇaṁ” balaṁ kūtutal; “ceytāl nan” mr̥du."),
)

DATA553 = D(
    ("You must show your ticket.", "ടിക്കറ്റ് കാണിക്കണം.", "ṭikkaṭṭ kāṇikkaṇaṁ."),
    ("We must obey the law.", "നിയമം പാലിക്കണം.", "niyamaṁ pālikkaṇaṁ."),
    ("I must leave now.", "ഇപ്പോൾ എനിക്ക് പോകണം.", "ippōḷ enikk pōkaṇaṁ."),
    ("He must pay the fine.", "അവൻ പിഴ അടയ്ക്കണം.", "avan piḻ aṭaykkaṇaṁ."),
    ("Students must wear uniform.", "വിദ്യാർത്ഥികൾ യൂണിഫോം ധരിക്കണം.", "vidyārththikaḷ yūṇiphōṁ dharikkaṇaṁ."),
    ("You must not smoke here.", "ഇവിടെ പുകവലിക്കരുത്.", "ivide pukavalikkarut."),
    ("We must reach before six.", "ആറിന് മുമ്പ് എത്തണം.", "āṛin mumpe eṭṭaṇaṁ."),
    ("She must submit the form today.", "ഇന്ന് ഫോം സമർപ്പിക്കണം.", "inn phōm samarpikkaṇaṁ."),
    ("Drivers must carry licence.", "ഡ്രൈവർമാർ ലൈസൻസ് കൊണ്ടുവരണം.", "ḍraivar mār laisaṁs koṇṭuvaraṇaṁ."),
    ("\"nirbandhamāṇ\" expresses strong must.", "ശക്തമായ ബാധ്യത “നിർബന്ധമാണ്”.", "śaktamāya bādhyata “nirbandhamāṇ”."),
    ("Hospital rules: visitors must wash hands.", "ആശുപത്രി നിയമം: സന്ദർശകർ കൈ കഴുകണം.", "āśupatri niyamaṁ: sandarśakar kai kaḻukaṇaṁ."),
    ("You must fasten your seat belt.", "സീറ്റ് ബെൽറ്റ് കെട്ടണം.", "sīṭṭ belṭ keṭṭaṇaṁ."),
    ("We must protect nature.", "പ്രകൃതി സംരക്ഷിക്കണം.", "prakr̥ti saṁrakṣikkaṇaṁ."),
    ("He must answer honestly.", "നേര് ഉത്തരം പറയണം.", "nēr uttaraṁ paṛayaṇaṁ."),
    ("I must finish this today.", "ഇന്ന് ഇത് പൂർത്തിയാക്കണം.", "inn it pūrttiyākkaṇaṁ."),
    ("They must report the incident.", "സംഭവം റിപ്പോർട്ട് ചെയ്യണം.", "saṁbhaṁ rippōṭṭ ceyyaṇaṁ."),
    ("Legal must uses formal vocabulary.", "നിയമപരമായ “നിർബന്ധം” ഔപചാരിക പദങ്ങൾ.", "niyamaparāya “nirbandhaṁ” aupacārika padaṅṅaḷ."),
    ("Do not confuse must with should in tone.", "ശബ്ദത്തിൽ “ചെയ്യണം” “ചെയ്താൽ നന്ന്” വേറെ.", "śabdaṭṭil “ceyyaṇaṁ” “ceytāl nan” veṛe."),
)

DATA554 = D(
    ("She keeps reading all day.", "അവൾ ദിവസം മുഴുവൻ വായിച്ചുകൊണ്ടിരിക്കുന്നു.", "avaḷ divasaṁ muḻuvan vāyiccukoṇṭirikkunnu."),
    ("He keeps forgetting the keys.", "അവൻ ചാവി മറന്നുകൊണ്ടിരിക്കുന്നു.", "avan cāvi maṟannukoṇṭirikkunnu."),
    ("We keep hoping for rain.", "ഞങ്ങൾ മഴ പ്രതീക്ഷിച്ചുകൊണ്ടിരിക്കുന്നു.", "ñaṅṅaḷ maḻa pratīkṣiccukoṇṭirikkunnu."),
    ("The phone keeps ringing.", "ഫോൺ മുഴങ്ങിക്കൊണ്ടിരിക്കുന്നു.", "phōn muḻaṅṅikkoṇṭirikkunnu."),
    ("They keep arguing.", "അവർ തർക്കിച്ചുകൊണ്ടിരിക്കുന്നു.", "avar tarkkiccukoṇṭirikkunnu."),
    ("I keep thinking about the exam.", "പരീക്ഷയെക്കുറിച്ച് ഞാൻ ചിന്തിച്ചുകൊണ്ടിരിക്കുന്നു.", "parīkṣayekkuricc njān cinticcukoṇṭirikkunnu."),
    ("The baby keeps crying.", "കുഞ്ഞ് കരഞ്ഞുകൊണ്ടിരിക്കുന്നു.", "kuññ karaññukoṇṭirikkunnu."),
    ("We keep practising Malayalam.", "ഞങ്ങൾ മലയാളം പരിശീലിച്ചുകൊണ്ടിരിക്കുന്നു.", "ñaṅṅaḷ malayāḷaṁ pariśīliccukoṇṭirikkunnu."),
    ("He keeps his room clean.", "അവൻ മുറി വൃത്തിയായി വെച്ചിരിക്കുന്നു.", "avan muṛi vr̥ttiyāyi veccirikkunnu."),
    ("\"koṇṭirikkuka\" marks continuous aspect.", "തുടർച്ചയായ പ്രവർത്തനം “കൊണ്ടിരിക്കുക”.", "tuṭarccayāya pravarttanaṁ “koṇṭirikkuka”."),
    ("\"tuṭaruka\" also means to continue.", "“തുടരുക” തുടരുന്നതിന്.", "“tuṭaruka” tuṭarunnatin."),
    ("She keeps helping others.", "അവൾ മറ്റുള്ളവരെ സഹായിച്ചുകൊണ്ടിരിക്കുന്നു.", "avaḷ maṭṭuḷḷavare sahāyiccukoṇṭirikkunnu."),
    ("The clock keeps good time.", "ഘടികാരം കൃത്യമായ സമയം പാലിക്കുന്നു.", "ghaṭikāraṁ kr̥tyamāya samayaṁ pālikkunnu."),
    ("I keep a diary in Malayalam.", "ഞാൻ മലയാളത്തിൽ ഡയറി എഴുതിക്കൊണ്ടിരിക്കുന്നു.", "njān malayāḷattil ḍayari eḻuticcukoṇṭirikkunnu."),
    ("We keep the door locked at night.", "രാത്രി വാതിൽ പൂട്ടിക്കൊണ്ടിരിക്കുന്നു.", "rātri vātil pūṭṭikkoṇṭirikkunnu."),
    ("He keeps promising to come.", "വരാമെന്ന് അവൻ പറഞ്ഞുകൊണ്ടിരിക്കുന്നു.", "varāmenn avan paṟaññukoṇṭirikkunnu."),
    ("Negative: I am not keeping well.", "എനിക്ക് സുഖമില്ലാതെ കഴിയുന്നു.", "enikk sukhamillāte kaḻiyunnu."),
    ("Colloquial \"irikkunnu\" for ongoing state.", "സംസാരത്തിൽ നില “ഇരിക്കുന്നു”.", "saṁsāraṭṭil nila “irikkunnu”."),
)

DATA555 = D(
    ("This is better than that.", "ഇത് അതിനെക്കാൾ നല്ലത്.", "it atinekkāḷ nallat."),
    ("She is the tallest in the class.", "ക്ലാസിൽ ഏറ്റവും ഉയരമുള്ളവൾ അവൾ.", "klāsil ēṭṭavuṁ uyaramuḷḷavaḷ avaḷ."),
    ("This is the most expensive shop.", "ഇത് ഏറ്റവും വില കൂടിയ കട.", "it ēṭṭavuṁ vila kūṭiya kaṭa."),
    ("He runs faster than me.", "അവൻ എന്നെക്കാൾ വേഗത്തിൽ ഓടുന്നു.", "avan ennekkāḷ vēgattil ōṭunnu."),
    ("The second test was easier.", "രണ്ടാമത്തെ പരീക്ഷ എളുപ്പമായിരുന്നു.", "raṇṭāmatte parīkṣa eḷuppamāyirunnu."),
    ("This mango is sweeter.", "ഈ മാങ്ങ മധുരമേറിയത്.", "ī māṅṅa madhuramēṟiyat."),
    ("We need a bigger room.", "നമുക്ക് വലിയ മുറി വേണം.", "namukku valiya muṛi vēṇaṁ."),
    ("She speaks more clearly now.", "അവൾ ഇപ്പോൾ വ്യക്തമായി സംസാരിക്കുന്നു.", "avaḷ ippōḷ vyaktamāyi saṁsārikkunnu."),
    ("This is less important.", "ഇത് പ്രാധാന്യം കുറഞ്ഞത്.", "it prādhānyaṁ kuṛaññat."),
    ("He is as tall as his father.", "അവൻ അച്ഛനെപ്പോലെ ഉയരമുണ്ട്.", "avan accaneppōle uyaramuṇṭ."),
    ("Malayalam uses \"ekkāḷ\", \"kūtutal\" for comparison.", "താരതമ്യത്തിൽ “എക്കാൾ”, “കൂടുതൽ”.", "tāratamyattil “ekkāḷ”, “kūtutal”."),
    ("Superlative often with \"ēṭṭavuṁ\".", "ഉച്ചക്ക് “ഏറ്റവും”.", "uccakk “ēṭṭavuṁ”."),
    ("This road is safer than that one.", "ഈ റോഡ് ആയതിനെക്കാൾ സുരക്ഷിതമാണ്.", "ī rōḷ āyatinekkāḷ surakṣitamāṇ."),
    ("She is the best singer here.", "ഇവിടെ ഏറ്റവും നല്ല ഗായിക അവൾ.", "ivide ēṭṭavuṁ nalla gāyika avaḷ."),
    ("The price became higher.", "വില കൂടുതലായി.", "vila kūtutalāyi."),
    ("We chose the cheaper option.", "ഞങ്ങൾ വില കുറഞ്ഞത് തിരഞ്ഞെടുത്തു.", "ñaṅṅaḷ vila kuṛaññat tiraññeṭuttu."),
    ("He feels worse today.", "അവന് ഇന്ന് മോശമായി തോന്നുന്നു.", "avan inn mōśamāyi tōnnunnu."),
    ("Practice comparative sentences with adjectives.", "വിശേഷണങ്ങളോട് താരതമ്യ വാക്യങ്ങൾ പരിശീലിക്കുക.", "viśeṣaṇaṅṅaḷōṭ tāratamya vākyaṅṅaḷ pariśīlikkuka."),
)
