# -*- coding: utf-8 -*-
"""Phrase chapters 571–596 (Malayalam)."""
from malayalam_lesson_content import R, _pad


def D(*t):
    return _pad([R(e, m, r) for e, m, r in t])


DATA571 = D(
    ("Good morning; I hope you slept well.", "സുപ്രഭാതം; നന്നായി ഉറങ്ങിയോ?", "suprabhātaṁ; nannāyi uṟaṅṅiyō?"),
    ("Good evening; please come in and sit down.", "സായാഹ്നം; ദയവായി അകത്തേക്ക് വന്ന് ഇരിക്കൂ.", "sāyāhnaṁ; dayavāyi akattēkku vannu irikkhū."),
    ("Happy birthday; may you live a hundred years.", "ജന്മദിനാശംസകൾ; നൂറു വയസ്സ് ആയുസ്സ് ഉണ്ടാകട്ടെ.", "janmadināśaṁsakaḷ; nūṟu vayass āyuss uṇṭākaṭṭe."),
    ("Happy New Year; may this year bring peace.", "പുതുവർഷാശംസകൾ; ഈ വർഷം സമാധാനം നൽകട്ടെ.", "putuvarṣāśaṁsakaḷ; ī varṣaṁ samādhānaṁ nalkaṭṭe."),
    ("Congratulations on your wedding.", "വിവാഹാശംസകൾ.", "vivāhāśaṁsakaḷ."),
    ("Get well soon; take rest and medicine on time.", "വേഗം സുഖം പ്രാപിക്കുക; വിശ്രമവും മരുന്നും സമയത്ത്.", "vēgaṁ sukhaṁ prāpikkuka; viśramavuṁ marunnuṁ samayatt."),
    ("May God bless you (general blessing).", "ദൈവം നിന്നെ അനുഗ്രഹിക്കട്ടെ.", "daivaṁ ninne anugrahikkaṭṭe."),
    ("Farewell; travel safely and message when you arrive.", "യാത്രയാശംസകൾ; സുരക്ഷിതമായി എത്തി അറിയിക്കുക.", "yātrāśaṁsakaḷ; surakṣitamāyi etti aṟiyikkuka."),
    ("Welcome to Kerala; we are glad you came.", "കേരളത്തിലേക്ക് സ്വാഗതം; വന്നതിൽ സന്തോഷമുണ്ട്.", "kēraḷattilēkk svāgataṁ; vannatil saṁtōṣamuṇṭ."),
    ("Happy Onam; may your home overflow with prosperity.", "ഓണാശംസകൾ; വീട് സമൃദ്ധിയിൽ നിറയട്ടെ.", "ōṇāśaṁsakaḷ; vīṭ samr̥ddhiyil niṛayaṭṭe."),
    ("Happy Vishu; may the new year be bright.", "വിഷുശംസകൾ; പുതുവർഷം തെളിഞ്ഞതായിരിക്കട്ടെ.", "viṣuśaṁsakaḷ; putuvarṣaṁ teḷiññatāyirikkkaṭṭe."),
    ("Long live the nation (slogan style).", "രാഷ്ട്രം നിലനിൽക്കട്ടെ.", "rāṣṭraṁ nilanilkkkaṭṭe."),
    ("Education for all (campaign slogan).", "എല്ലാവർക്കും വിദ്യാഭ്യാസം.", "ellāvarkkuṁ vidyābhyāsaṁ."),
    ("Clean Kerala, beautiful Kerala (civic slogan).", "ശുചിത്വമുള്ള കേരളം, മനോഹരമായ കേരളം.", "śucitvamuḷḷa kēraḷaṁ, manōharamāya kēraḷaṁ."),
    ("Thank you for your hospitality.", "അതിഥിസത്കാരത്തിന് നന്ദി.", "atithisatkārattin nandi."),
    ("May your studies go well this year.", "ഈ വർഷം പഠനം നന്നായി പോകട്ടെ.", "ī varṣaṁ paṭhanaṁ nannāyi pōkaṭṭe."),
    ("Peace be upon everyone at this gathering.", "ഈ സമ്മേളനത്തിൽ എല്ലാവർക്കും സമാധാനം.", "ī sam'mēḷanattil ellāvarkkuṁ samādhānaṁ."),
    ("We wish you success in the examination.", "പരീക്ഷയിൽ വിജയം ആശംസിക്കുന്നു.", "parīkṣayil vijayaṁ āśaṁsikkunnu."),
)

DATA572 = D(
    ("I will try to finish the work today.", "ഇന്ന് ജോലി തീർക്കാൻ ശ്രമിക്കും.", "inn jōli tīrkkān śramikkuṁ."),
    ("She sat down after standing for a long time.", "നീണ്ട നിന്ന ശേഷം അവൾ ഇരുന്നു.", "nīṇṭa ninna śeṣaṁ avaḷ irunnu."),
    ("We looked carefully before crossing the road.", "റോഡ് കടക്കും മുമ്പ് ശ്രദ്ധിച്ചു നോക്കി.", "rōḷ kaṭakkum mump śraddhicc nōkki."),
    ("He opened the window and let fresh air in.", "ജനല്‍ തുറന്ന് പുതിയ കാറ്റ് അകത്തേക്ക് വിട്ടു.", "janal tuṟannu putiya kāṭṭ akattēkku viṭṭu."),
    ("They stood up when the teacher entered.", "അധ്യാപകൻ പ്രവേശിച്ചപ്പോൾ എഴുന്നേറ്റു.", "adhyāpakan praveśiccappōḷ eḻunnēṭṭu."),
    ("Compound style: get up early for exercise.", "പ്രഭാത വ്യായാമത്തിന് നേരത്തെ എഴുന്നേൽക്കുക.", "prabhāta vyāyāmattin nērattē eḻunnēlkkuka."),
    ("She picked up the child from school.", "സ്കൂളിൽ നിന്ന് കുഞ്ഞിനെ എടുത്തു.", "skūlil ninn kuññine eṭuttu."),
    ("We put away the books after class.", "ക്ലാസ് കഴിഞ്ഞ് പുസ്തകങ്ങൾ വെച്ചു.", "klās kaḻiññ pustakaṅṅaḷ veccu."),
    ("He looked up the word in the dictionary.", "നിഘണ്ടുവിൽ വാക്ക് തിരഞ്ഞു.", "nighaṇṭuvil vākku tiraññu."),
    ("Malayalam often chains light verbs with nouns.", "നാമവും ക്രിയയും ചേർന്ന് പുതിയ അർത്ഥം.", "nāmaṁ kriyayuṁ cērn putiya artthaṁ."),
    ("She went out to buy vegetables.", "പച്ചക്കറി വാങ്ങാൻ പുറത്തേക്ക് പോയി.", "paccakaṛi vāṅṅān puṟattēkk pōyi."),
    ("We came back home before it rained.", "മഴ പെയ്യും മുമ്പ് വീട്ടിൽ തിരിച്ചെത്തി.", "maḻa peyyum mump vīṭṭil tiriccetti."),
    ("He handed over the keys to the neighbour.", "ചാവി അയൽക്കാരന് കൊടുത്തു.", "cāvi ayalkkāran koṭuttu."),
    ("They moved the furniture to clean the room.", "മുറി വൃത്തിയാക്കി ഫർണിച്ചർ മാറ്റി.", "muṛi vr̥ttiyākki pharṇicar māṭṭi."),
    ("I wrote down the phone number carefully.", "ഫോൺ നമ്പർ ശ്രദ്ധിച്ച് എഴുതി.", "phōṇ nambar śraddhicc eḻuti."),
    ("We discussed the plan and then decided.", "പദ്ധതി ചർച്ച ചെയ്ത് പിന്നീട് തീരുമാനിച്ചു.", "padhati carcca ceytu piṇīṭ tīrumāniccu."),
    ("She turned off the lights before sleeping.", "ഉറങ്ങും മുമ്പ് വിളക്കുകൾ അണച്ചു.", "uṟaṅṅum mump viḷakkukaḷ aṇaccu."),
    ("Practice combining simple verbs in one sentence.", "ഒരു വാക്യത്തിൽ ലഘു ക്രിയകൾ ചേർക്കുക.", "oru vākyattil laghu kriyakaḷ cērkkuka."),
)

DATA573 = D(
    ("Excuse me, brother, which way is the bus stand?", "അയ്യോ ചേട്ടാ, ബസ് സ്റ്റാൻഡ് ഏതു വഴി?", "ayyō cēṭṭā, bas sṟṟāṇḍ ētu vazhi?"),
    ("Sister, could you help me carry this bag?", "ചേച്ചി, ഈ ബാഗ് എടുക്കാൻ സഹായിക്കുമോ?", "cēcci, ī bāk eṭukkān sahāyikkumō?"),
    ("Uncle, is this the correct stop for the temple?", "മാമാ, ക്ഷേത്രത്തിന് ഇവിടെയാണോ നിർത്തുന്നത്?", "māmā, kṣētrattin ivideyāṇō nirttunnat?"),
    ("Aunty, how much do these bananas cost?", "അമ്മായിക്ക് ഈ പഴത്തിന് എത്ര രൂപ?", "ammāyikk ī paḻattin etra rūpa?"),
    ("Sir, I would like two cups of tea, please.", "സാർ, രണ്ട് ചായ വേണം, ദയവായി.", "sār, raṇṭ cāya vēṇaṁ, dayavāyi."),
    ("Madam, may I use your phone for a moment?", "മാഡം, ഒരു നിമിഷം ഫോൺ ഉപയോഗിക്കാമോ?", "māḍaṁ, oru nimiṣaṁ phōṇ upayōgikkāmō?"),
    ("Grandfather, tell us a story from your youth.", "മുത്തച്ഛാ, യൗവനകാലത്തെ ഒരു കഥ പറയൂ.", "muttacchā, yauvanakālattē oru katha paṛayū."),
    ("Grandmother, this curry tastes wonderful.", "മുത്തശ്ശി, ഈ കറി അതിമനോഹരമാണ്.", "muttaśśi, ī kaṛi atimanōharamāṇ."),
    ("Friend, shall we meet tomorrow at the same place?", "സുഹൃത്തേ, നാളെ ഇതേ സ്ഥലത്ത് കാണാമോ?", "suhr̥uttē, nāḷe itē sthalatt kāṇāmō?"),
    ("Young man, drive slowly on this wet road.", "മോനേ, ഈ നനഞ്ഞ റോഡിൽ പതുക്കെ ഓടിക്കുക.", "mōnē, ī nanañña rōḷil patukkē ōṭikkuka."),
    ("Girl, don’t go alone after dark.", "മോളേ, ഇരുട്ടത്ത് ഒറ്റയ്ക്ക് പോകരുത്.", "mōḷē, iruṭṭatt oṭṭakk pōkarut."),
    ("We address elders with respectful plural forms.", "മുതിർന്നവരെ ബഹുമാനത്തോടെ വിളിക്കുന്നു.", "mutirnnavare bahumānattōṭe viḷikkunnu."),
    ("Using name plus \"acchā\" shows affection to father figures.", "പേരിനൊപ്പം “അച്ഛാ” സ്നേഹം കാണിക്കുന്നു.", "pērinoppaṁ “acchā” snēhaṁ kāṇikku."),
    ("\"ṭā\" is very informal; avoid with strangers.", "അപരിചിതരോട് “ടാ” ഉപയോഗിക്കരുത്.", "aparicitarōṭ “ṭā” upayōgikkarut."),
    ("Teacher, may I ask a doubt?", "ടീച്ചർ, ഒരു സംശയം ചോദിക്കാമോ?", "ṭīccar, oru saṁśayaṁ cōdikkāmō?"),
    ("Doctor, the pain has reduced a little.", "ഡോക്ടർ, വേദന കുറഞ്ഞു.", "ḍōkṭṭar, vēdana kuṛaññu."),
    ("Officer, here are my documents.", "ഓഫീസർ, എന്റെ രേഖകൾ ഇതാ.", "ōphīsar, enṟa rēkhakaḷ itā."),
    ("Neighbour, we will return your vessel tomorrow.", "അയൽക്കാരാ, നാളെ പാത്രം തിരിച്ചുതരാം.", "ayalkkārā, nāḷe pātraṁ tiriccutarāṁ."),
)

DATA574 = D(
    ("Oh no! I forgot my umbrella at home.", "അയ്യോ! കുട വീട്ടിൽ മറന്നു.", "ayyō! kuṭa vīṭṭil maṟannu."),
    ("Wow! The sunset over the backwaters is stunning.", "വാ! കായലിൽ സൂര്യാസ്തമയം അതിശയകരമാണ്.", "vā! kāyalil sūryāstamayaṁ atiśayakaramāṇ."),
    ("Alas! We missed the last bus.", "അയ്യോ! അവസാന ബസ് നഷ്ടപ്പെട്ടു.", "ayyō! avasāna bas naṣṭappeṭṭu."),
    ("Hey! Watch out for that cyclist.", "എയ്! ആ സൈക്കിൾ യാത്രക്കാരനെ നോക്ക്.", "ey! ā saikkal yātrakkāran nōkku."),
    ("Ouch! I stubbed my toe on the stone.", "അമ്മേ! കാല്‍ കല്ലിൽ തട്ടി.", "amme! kāl kallil taṭṭi."),
    ("Bravo! You solved the problem so quickly.", "ശബാഷ്! വേഗം പ്രശ്നം പരിഹരിച്ചു.", "śabāṣ! vēgaṁ praśnaṁ parihariccu."),
    ("Hmm, I am not sure about that answer.", "ഊം, ആ ഉത്തരത്തിൽ ഉറപ്പില്ല.", "ūm, ā uttarattil urappilla."),
    ("Ugh, this room smells damp.", "ഛെ, ഈ മുറി ഈർപ്പിന്റെ മണം.", "che, ī muṛi īrppinṟe maṇaṁ."),
    ("Yuck, I don’t like bitter gourd.", "ഛെ, കൈപ്പക്ക് ഇഷ്ടമില്ല.", "che, kaippakk iṣṭamilla."),
    ("Thank goodness! The train is on time.", "ദൈവത്തിന് നന്ദി! ട്രെയിൻ സമയത്താണ്.", "daivattin nandi! ṭreyin samayattāṇ."),
    ("What a surprise to see you here!", "ഇവിടെ കാണാൻ എന്തൊരു ആശ്ചര്യം!", "ivide kāṇān entoru āścaryaṁ!"),
    ("How beautiful the hills look in the mist!", "മൂടൽമഞ്ഞിൽ കുന്നുകൾ എത്ര മനോഹരം!", "mūṭalmaññil kunnukaḷ etra manōharaṁ!"),
    ("Spoken Malayalam uses many short exclamations.", "സംസാരത്തിൽ ചെറു ആശ്ചര്യവാക്കുകൾ.", "saṁsāraṭṭil ceṛu āścaryavākkukaḷ."),
    ("\"ayyō\" expresses worry or regret.", "“അയ്യോ” വിഷമമോ പശ്ചാത്താപമോ.", "“ayyō” viṣamamō paścāttāpamō."),
    ("\"śśō\" shows mild shock in some dialects.", "“śśō” ഭാഷാന്തരങ്ങളിൽ ലഘു ആഘാതം.", "“śśō” bhāṣāntaraṅṅaḷil laghu āghātaṁ."),
    ("Cheer at a match: goal!", "ഗോൾ! കാണികൾ ആർപ്പുവിളിക്കുന്നു.", "gōḷ! kāṇikaḷ ārppuviḷikkunnu."),
    ("Relief after exams: finished at last!", "അവസാനം പരീക്ഷ കഴിഞ്ഞു!", "avasānaṁ parīkṣa kaḻiññu!"),
    ("Joy when meeting old friends after years!", "വർഷങ്ങൾക്ക് ശേഷം പഴയ സുഹൃത്തുക്കളെ കണ്ടു!", "varṣaṅṅaḷkku śeṣaṁ paḻaya suhr̥uttukkaḷe kaṇṭu!"),
)

DATA575 = D(
    ("May I come in? I have brought the documents you asked for.", "അകത്തേക്ക് വരാമോ? ചോദിച്ച രേഖകൾ കൊണ്ടുവന്നു.", "akattekk varāmō? cōdicca rēkhakaḷ koṇṭuvannu."),
    ("Can you help me lift this heavy box to the car?", "ഈ ഭാരമുള്ള പെട്ടി കാറിലേക്ക് ഉയർത്താൻ സഹായിക്കുമോ?", "ī bhāramuḷḷa peṭṭi kārilēkk uyarttān sahāyikkumō?"),
    ("Could you speak a little more slowly, please?", "കുറച്ച് മെല്ലെ പറയാമോ, ദയവായി?", "kureśś melle paṛayāmō, dayavāyi?"),
    ("Would you mind closing the window? It is getting cold.", "ജനല്‍ അടയ്ക്കാമോ? തണുക്കുന്നുണ്ട്.", "janal aṭaykkāmō? taṇukkunnuṇṭ."),
    ("May I use your pen for a minute?", "ഒരു നിമിഷം നിന്റെ പേന ഉപയോഗിക്കാമോ?", "oru nimiṣaṁ ninṟa pēna upayōgikkāmō?"),
    ("Can you tell me where the nearest ATM is?", "അടുത്തുള്ള എടിഎം എവിടെയെന്ന് പറയാമോ?", "aṭutt uḷḷa eṭiem evideyenn paṛayāmō?"),
    ("Would you check this form before I submit it?", "സമർപ്പിക്കും മുമ്പ് ഈ ഫോം പരിശോധിക്കാമോ?", "samarpikkum mump ī phōṁ pariśōdhikkāmō?"),
    ("Could we meet after lunch to discuss the project?", "ഉച്ചയ്ക്ക് ശേഷം പദ്ധതി ചർച്ച ചെയ്യാൻ കാണാമോ?", "uccaykku śeṣaṁ padhati carcca ceyyān kāṇāmō?"),
    ("Can you reserve two seats for tonight’s show?", "ഇന്ന് രാത്രിയിലെ ഷോയ്ക്ക് രണ്ട് സീറ്റ് ബുക്ക് ചെയ്യാമോ?", "inn rātriyile śōykk raṇṭ sīṭṭ bukk ceyyāmō?"),
    ("May I ask why the meeting was postponed?", "യോഗം മാറ്റിവെച്ചതിന്റെ കാരണം ചോദിക്കാമോ?", "yōgaṁ māṭṭiveccatinṟe kāraṇaṁ cōdikkāmō?"),
    ("Could you send me the file by email today?", "ഇന്ന് ഫയൽ ഇമെയിലിൽ അയയ്ക്കാമോ?", "inn phayal imeyilil ayaykkāmō?"),
    ("Would you pass the salt, please?", "ഉപ്പ് എത്തിച്ചുതരാമോ?", "upp etticc tarāmō?"),
    ("Can you wait here until I return from the shop?", "ഞാൻ കടയിൽ നിന്ന് വരുന്നത് വരെ ഇവിടെ കാത്തിരിക്കാമോ?", "njān kaṭayil ninn varunnat vare ivide kāttirikkāmō?"),
    ("May I take a photograph of this monument?", "ഈ സ്മാരകത്തിന്റെ ഫോട്ടോ എടുക്കാമോ?", "ī smārakattinṟe phōṭṭō eṭukkāmō?"),
    ("Could you recommend a good vegetarian restaurant?", "നല്ല സസ്യാഹാര റെസ്റ്റോറന്റ് പറയാമോ?", "nalla sasyāhāra resṟṭōraṇṭ paṛayāmō?"),
    ("Polite requests often begin with \"dayavāyi\".", "മര്യാദയുള്ള അഭ്യർത്ഥന “ദയവായി” കൊണ്ട്.", "maryādayuḷḷa abhyarththana “dayavāyi” koṇṭ."),
    ("\"onnu\" softens: please move a little.", "“ഒന്ന്” മൃദുവാക്കുന്നു: ഒന്ന് മാറിക്കൊടുക്കൂ.", "“onnu” mr̥duvākkunnu: onnu māṟikkoṭukkhū."),
    ("Negative request: please do not smoke here.", "ഇവിടെ പുകവലിക്കരുത്, ദയവായി.", "ivide pukavalikkarut, dayavāyi."),
)

DATA576 = D(
    ("It might rain this evening; take an umbrella.", "ഈ സായാഹ്നം മഴ പെയ്തേക്കും; കുട കൊണ്ടുപോകുക.", "ī sāyāhnaṁ maḻa peytēkkuṁ; kuṭa koṇṭupōkuka."),
    ("She may arrive late because of traffic.", "ട്രാഫിക് കാരണം അവൾ വൈകിയേക്കും.", "ṭrāphik kāraṇaṁ avaḷ vaikiyēkkuṁ."),
    ("We might visit the museum if we have time.", "സമയമുണ്ടെങ്കിൽ മ്യൂസിയം സന്ദർശിച്ചേക്കാം.", "samayamuṇṭeṅkiḷ myūsiyaṁ sandarśiccekkāṁ."),
    ("The bus might be full at rush hour.", "തിരക്ക് സമയത്ത് ബസ് നിറഞ്ഞേക്കാം.", "tirakk samayatt bas niṛaññēkkāṁ."),
    ("He might not know that the rules changed.", "നിയമം മാറിയെന്ന് അവനറിയാതിരിക്കാം.", "niyamaṁ māṟiyenn avanaṟiyātirikkāṁ."),
    ("It may take longer than we expected.", "നമ്മുടെ പ്രതീക്ഷയിലും കൂടുതൽ സമയം എടുത്തേക്കാം.", "nammutē pratīkṣayiluṁ kūtutal samayaṁ eṭuttēkkāṁ."),
    ("They might cancel the match if it keeps raining.", "മഴ തുടർന്നാൽ മത്സരം റദ്ദാക്കിയേക്കും.", "maḻa tuṭarnnāl matsaraṁ rad'dhākkiyēkkuṁ."),
    ("I might have left my keys on the desk.", "ചാവി മേശയിൽ വെച്ചിട്ടുണ്ടായിരിക്കാം.", "cāvi meśayil vecciṭṭuṇṭāyirikkāṁ."),
    ("We use \"āyirikuṁ\" for uncertain future outcomes.", "അനിശ്ചിത ഭാവിയ്ക്ക് “ആയിരിക്കും”.", "aniścita bhāviykku “āyirikuṁ”."),
    ("\"pakṣe\" introduces a possible obstacle.", "“പക്ഷേ” സാധ്യമായ തടസ്സം.", "“pakṣe” sādhyamāya taḍassaṁ."),
    ("She might prefer tea over coffee today.", "ഇന്ന് ചായയ്ക്ക് പ്രാധാന്യമുണ്ടായിരിക്കാം.", "inn cāyaykku prādhānyamuṇṭāyirikkāṁ."),
    ("The shop might be closed on public holidays.", "പൊതു അവധി ദിവസങ്ങളിൽ കട അടഞ്ഞേക്കാം.", "pōta avadhi divasaṅṅaḷil kaṭa aṭaññēkkāṁ."),
    ("He might call you after the meeting ends.", "യോഗം അവസാനിച്ചാൽ വിളിച്ചേക്കും.", "yōgaṁ avasāniccā viḷiccēkkuṁ."),
    ("There might be a power cut during the storm.", "കൊടുങ്കാറ്റിൽ കറന്റ് പോയേക്കാം.", "koṭuṅkāṭṭil karaṇṭ pōyēkkāṁ."),
    ("We might need extra chairs for the guests.", "അതിഥികൾക്ക് അധിക സ്റ്റൂളുകൾ വേണ്ടിവന്നേക്കാം.", "atithikaḷkku adhika sṟṭūḷukaḷ vēṇṭivannēkkāṁ."),
    ("I might not attend if I feel unwell.", "സുഖമില്ലെങ്കിൽ പങ്കെടുക്കാതിരിക്കാം.", "sukhamilleṅkiḷ paṅṅkeṭukkātirikkāṁ."),
    ("The road might be slippery after the rain.", "മഴയ്ക്ക് ശേഷം റോഡ് വഴുതലായേക്കാം.", "maḻaykku śeṣaṁ rōḷ vaḻutalāyēkkāṁ."),
    ("Express doubt without blaming: it might be my mistake.", "എന്റെ പിശകായിരിക്കാം എന്ന് പറയാം.", "enṟe piśakāyirikkāṁ ennu paṛayāṁ."),
)

DATA577 = D(
    ("The written answer is clear and easy to read.", "എഴുതിയ ഉത്തരം വ്യക്തവും വായിക്കാൻ എളുപ്പവുമാണ്.", "eḻutiya uttaraṁ vyaktavuṁ vāyikkān eḷuppavumāṇ."),
    ("A broken chair cannot be used safely.", "ഒടിഞ്ഞ കസേര സുരക്ഷിതമായി ഉപയോഗിക്കാൻ പാടില്ല.", "oṭiñña kasēra surakṣitamāyi upayōgikkān pāṭilla."),
    ("Boiled water is safer for drinking.", "തിളച്ച വെള്ളം കുടിക്കാൻ സുരക്ഷിതമാണ്.", "tiḷacca veḷḷaṁ kuṭikkān surakṣitamāṇ."),
    ("She wore a washed cotton saree for the function.", "അനുഷ്ഠാനത്തിന് അലക്കിയ പരുത്ത് സാരി ധരിച്ചു.", "anuṣṭhānattin alakkiya parutt sāri dhariccu."),
    ("The closed shop had a notice on the door.", "അടഞ്ഞ കടയുടെ വാതിലിൽ അറിയിപ്പുണ്ടായിരുന്നു.", "aṭañña kaṭayuṭe vātilil aṟiyippuṇṭāyirunnu."),
    ("Malayalam past participles often work as adjectives before nouns.", "നാമത്തിന് മുമ്പ് ഭൂതകാല ക്രിയാരൂപങ്ങൾ വിശേഷണമായി.", "nāmattin mump bhūtakāla kriyārūpaṅṅaḷ viśeṣaṇamāyi."),
    ("\"ceyta\", \"eḻutiya\", \"vāyicca\" modify the following noun.", "“ചെയ്ത”, “എഴുതിയ”, “വായിച്ച” തുടർന്ന നാമത്തെ.", "“ceyta”, “eḻutiya”, “vāyicca” tuṭarnna nāmattē."),
    ("A smiling child brightens the whole room.", "ചിരിക്കുന്ന കുട്ടി മുഴുവൻ മുറിയും തെളിയിക്കുന്നു.", "cirikkunna kuṭṭi muḻuvan muṛiyuṁ teḷiyikkunnu."),
    ("The forgotten umbrella was still on the bus.", "മറന്ന കുട ബസിൽ തന്നെയുണ്ടായിരുന്നു.", "maṟanna kuṭa basil tannēyuṇṭāyirunnu."),
    ("We need a printed copy of the application.", "അപേക്ഷയുടെ അച്ചടിച്ച പകർപ്പ് വേണം.", "apēkṣayuṭe accaḍicca pakarpp vēṇaṁ."),
    ("The painted wall dried by evening.", "വർണ്ണം പൂശിയ മതിൽ സായാഹ്നത്തോടെ ഉണങ്ങി.", "varṇṇaṁ pūśiya matil sāyāhnattōṭe uṇaṅṅi."),
    ("A trained nurse assisted the doctor.", "പരിശീലനം നേടിയ നഴ്സ് ഡോക്ടറെ സഹായിച്ചു.", "pariśīlanaṁ nēṭiya naḻs ḍōkṭṭare sahāyiccu."),
    ("The cooked rice was still warm.", "ഉണ്ടാക്കിയ ചോറ് ഇനിയും ചൂടുണ്ടായിരുന്നു.", "uṇṭākki cōṟ iniyuṁ cūṭuṇṭāyirunnu."),
    ("Compare: interesting book vs book that interests me.", "താൽപര്യമുള്ള പുസ്തകം; എന്നെ താൽപര്യപ്പെടുത്തുന്ന പുസ്തകം.", "tālparyamuḷḷa pustakaṁ; enne tālparyappeṭuttunna pustakaṁ."),
    ("Practice turning verbs into modifiers before nouns.", "ക്രിയകൾ നാമത്തിന് മുമ്പ് വിശേഷണമാക്കുക.", "kriyakaḷ nāmattin mump viśeṣaṇamākkuka."),
    ("Avoid stacking too many participles in one phrase.", "ഒരു വാക്യത്തിൽ അധികം പങ്കെടുത്ത ക്രിയകൾ ഒഴിവാക്കുക.", "oru vākyattil adhikaṁ paṅṅkeṭutta kriyakaḷ oḻivākkuka."),
    ("A well-read person enjoys many kinds of books.", "നന്നായി വായിച്ചവൻ പല തരം പുസ്തകങ്ങൾ ആസ്വദിക്കും.", "nannāyi vāyiccavan pala taraṁ pustakaṅṅaḷ āsvadikkuṁ."),
    ("The injured bird was taken to a vet.", "പരിക്കേറ്റ പക്ഷി വൈദ്യന്റെ അടുത്തേക്ക് കൊണ്ടുപോയി.", "parikkēṭṭa pakṣi vaidyantē aṭuttēkk koṇṭupōyi."),
)

DATA578 = D(
    ("The cat is under the table.", "പൂച്ച മേശയ്ക്ക് താഴെയാണ്.", "pūcca meśayk tāḻeyāṇ."),
    ("The keys are on the shelf near the door.", "ചാവി വാതിലിനടുത്തുള്ള അലമാരയിൽ.", "cāvi vātilinaṭutt uḷḷa alamāriyil."),
    ("We walked along the river until sunset.", "സൂര്യാസ്തമയം വരെ നദീതീരത്ത് നടന്നു.", "sūryāstamayaṁ vare nadītīratt naṭannu."),
    ("The shop is across the street from the temple.", "ക്ഷേത്രത്തിന് എതിർവശത്താണ് കട.", "kṣētrattin etirvaśattāṇ kaṭa."),
    ("She sat beside her mother during the prayer.", "പ്രാർത്ഥനയ്ക്കിടെ അമ്മയുടെ അരികിൽ ഇരുന്നു.", "prārththanaykkiṭe ammayuṭe arikil irunnu."),
    ("The children ran behind the kite in the field.", "കുട്ടികൾ വയലിൽ പട്ടം പിന്നാലെ ഓടി.", "kuṭṭikaḷ vayalil paṭṭaṁ piṅṅāle ōṭi."),
    ("He hid the gift inside the cupboard.", "സമ്മാനം അലമാരിക്കുള്ളിൽ മറച്ചു.", "sam'mānaṁ alamārikkuḷḷil maṛaccu."),
    ("The bird flew over the coconut palms.", "പക്ഷി തെങ്ങിന് മുകളിലൂടെ പറന്നു.", "pakṣi teṅṅin mukaḷilūṭe paṟannu."),
    ("We waited outside the cinema hall.", "സിനിമാ ഹാളിന് പുറത്ത് കാത്തിരുന്നു.", "sinimā hāḷin puṟatt kāttirunnu."),
    ("The letter is between the two books.", "അക്ഷരം രണ്ട് പുസ്തകങ്ങൾക്കിടയിലാണ്.", "akṣaraṁ raṇṭ pustakaṅṅaḷkkiṭayilāṇ."),
    ("Preposition-like words in Malayalam often come as postpositions.", "മലയാളത്തിൽ “പുറം”, “അടുത്ത്” പോലുള്ള ശബ്ദങ്ങൾ പദത്തിന് ശേഷം.", "malayāḷattil “puṟaṁ”, “aṭutt” pōluḷḷa śabdagaḷ padattin śeṣaṁ."),
    ("\"mukaḷil\" means on top of something.", "“മുകളിൽ” മുകളിലുള്ള സ്ഥാനം.", "“mukaḷil” mukaḷil uḷḷa sthānaṁ."),
    ("\"kīḻe\" can mean below or downstairs.", "“കീഴെ” താഴെയോ താഴത്തെ നിലയോ.", "“kīḻe” tāḻeyō tāḻatte nilayō."),
    ("\"naṭuvil\" indicates the middle.", "“നടുവിൽ” മധ്യഭാഗം.", "“naṭuvil” madhyabhāgaṁ."),
    ("We say \"enṟe mumpil\" for in front of me.", "“എന്റെ മുമ്പിൽ” മുൻഭാഗം.", "“enṟe mumpil” muṉbhāgaṁ."),
    ("\"piṅṅāle\" follows the noun: dog behind me.", "“പിന്നാലെ” പിന്തുടരൽ.", "“piṅṅāle” pintuṭaral."),
    ("Describe position clearly in directions to strangers.", "അപരിചിതരോട് ദിശ പറയുമ്പോൾ സ്ഥാനം വ്യക്തമാക്കുക.", "aparicitarōṭ diśa paṛayumbōḷ sthānaṁ vyaktamākkuka."),
    ("Practice: the book under the bed is dusty.", "കട്ടിലിന് താഴെയുള്ള പുസ്തകം പൊടിയിട്ടിരിക്കുന്നു.", "kaṭṭilin tāḻeyuḷḷa pustakaṁ poḍiyiṭṭirikkunnu."),
)

DATA579 = D(
    ("May you live long and stay healthy.", "നീ ദീർഘായുസ്സോടെ സുഖമായി ജീവിക്കട്ടെ.", "nī dīrghāyussōṭe sukhamāyi jīvikkaṭṭe."),
    ("May peace spread in every home.", "എല്ലാ വീടുകളിലും സമാധാനം വ്യാപിക്കട്ടെ.", "ellā vīṭukaḷiluṁ samādhānaṁ vyāpikkaṭṭe."),
    ("May your dreams come true through hard work.", "പരിശ്രമത്തിലൂടെ സ്വപ്നങ്ങൾ സാക്ഷാത്ക്കാരമാകട്ടെ.", "pariśramattilūṭe svapnaṅṅaḷ sākṣātkkāramākkaṭṭe."),
    ("May the new year bring new opportunities.", "പുതുവർഷം പുതിയ അവസരങ്ങൾ കൊണ്ടുവരട്ടെ.", "putuvarṣaṁ putiya avasaraṅṅaḷ koṇṭuvarakkaṭṭe."),
    ("May the travellers reach home safely.", "യാത്രക്കാർ സുരക്ഷിതമായി വീട്ടിലെത്തട്ടെ.", "yātrakkār surakṣitamāyi vīṭṭilettaṭṭe."),
    ("May the farmers get good rain this monsoon.", "ഈ മൺസൂണിൽ കർഷകർക്ക് നല്ല മഴ ലഭിക്കട്ടെ.", "ī maṇsūṇil karṣakarkku nalla maḻa labhikkaṭṭe."),
    ("May the children study with joy.", "കുട്ടികൾ സന്തോഷത്തോടെ പഠിക്കട്ടെ.", "kuṭṭikaḷ saṁtōṣattōṭe paṭhikkaṭṭe."),
    ("May your parents be proud of you.", "നിന്റെ മാതാപിതാക്കൾക്ക് നിന്നെക്കുറിച്ച് അഭിമാനമുണ്ടാകട്ടെ.", "ninṟa mātāpitākkaḷkku ninnekuṛicc abhimānamuṇṭākaṭṭe."),
    ("We use \"ākaṭṭe\" after blessings in speech.", "ആശംസകളുടെ അവസാനം “ആകട്ടെ”.", "āśaṁsakaḷuṭe avasānaṁ “ākaṭṭe”."),
    ("\"vēṇaṁ\" can express a gentle wish about others.", "മറ്റുള്ളവരെക്കുറിച്ച് മൃദുവായ ആഗ്രഹം “വേണം”.", "maṭṭuḷḷavarekuṛicc mr̥duvāya āgrahaṁ “vēṇaṁ”."),
    ("May the sick recover quickly.", "രോഗികൾ വേഗം സുഖം പ്രാപിക്കട്ടെ.", "rōgikaḷ vēgaṁ sukhaṁ prāpikkaṭṭe."),
    ("May friendship between communities grow stronger.", "സമൂഹങ്ങൾക്കിടയിലെ സൗഹൃദ്ധം വർദ്ധിക്കട്ടെ.", "samūhaṅṅaḷkkiṭayile sauhr̥ddhaṁ varddhikkaṭṭe."),
    ("May no one go to bed hungry tonight.", "ഇന്ന് രാത്രി ആരും വിശപ്പോടെ ഉറങ്ങാതിരിക്കട്ടെ.", "inn rātri āruṁ viśappōṭe uṟaṅṅātirikkaṭṭe."),
    ("May your journey be pleasant and safe.", "യാത്ര സുഖകരവും സുരക്ഷിതവുമാകട്ടെ.", "yātra sukhakaravuṁ surakṣitavumākaṭṭe."),
    ("May the exam results reflect your effort.", "പരീക്ഷാഫലം പരിശ്രമം പ്രതിഫലിപ്പിക്കട്ടെ.", "parīkṣāphalaṁ pariśramaṁ pratiphalippikkaṭṭe."),
    ("May the festival unite every family in joy.", "ഉത്സവം എല്ലാ കുടുംബങ്ങളിലും സന്തോഷം പകരട്ടെ.", "utsavaṁ ellā kuṭumbaṅṅaḷiluṁ saṁtōṣaṁ pakaraṭṭe."),
    ("Formal speech: may this programme succeed.", "ഈ പരിപാടി വിജയകരമാകട്ടെ.", "ī paripāṭi vijayakaramākaṭṭe."),
    ("Poetic wish: may the lamp never go out.", "വിളക്ക് ഒരിക്കലും അണയാതിരിക്കട്ടെ.", "viḷakku orikkaluṁ aṇayātirikkaṭṭe."),
)

DATA580 = D(
    ("Mother made the child drink milk before school.", "അമ്മ കുട്ടിയെ സ്കൂളിന് മുമ്പ് പാൽ കുടിപ്പിച്ചു.", "amma kuṭṭiye skūlin mump pāl kuṭippiccu."),
    ("The teacher had the students write the essay again.", "അധ്യാപകൻ വിദ്യാർത്ഥികളോട് പ്രബന്ധം വീണ്ടും എഴുതിച്ചു.", "adhyāpakan vidyārththikaḷōṭ prabandhaṁ vīṇṭuṁ eḻuticcu."),
    ("I will get the mechanic to repair the scooter.", "മെക്കാനിക്കിന് സ്കൂട്ടർ നന്നാക്കാൻ പറയും.", "mekkānikkin skūṭṭar nannākkān paṛayuṁ."),
    ("She asked her brother to fetch water from the well.", "സഹോദരനോട് കിണറ്റിൽ നിന്ന് വെള്ളം കൊണ്ടുവരാൻ പറഞ്ഞു.", "sahōdaranōṭ kiṇaṭṭil ninn veḷḷaṁ koṇṭuvarān paṟaññu."),
    ("The officer ordered the clerk to file the report.", "ഓഫീസർ ക്ലാർക്കിന് റിപ്പോർട്ട് ഫയൽ ചെയ്യാൻ നിർദ്ദേശിച്ചു.", "ōphīsar klārkkin rippōṭṭ phayal ceyyān nirddēśiccu."),
    ("We persuaded him to join the health camp.", "ആരോഗ്യ ക്യാമ്പിൽ ചേരാൻ അവനെ സമ്മതിപ്പിച്ചു.", "ārōgya kyāmpil cērān avane sam'matippiccu."),
    ("Causative with \"ākkuka\": heat made the metal expand.", "ചൂട് ലോഹം വികസിപ്പിക്കുന്നു.", "cūṭ lōhaṁ vikasippikkunnu."),
    ("Polite causative: please have him call me back.", "അവനോട് എന്നെ വീണ്ടും വിളിക്കാൻ പറയൂ.", "avanōṭ enne vīṇṭuṁ viḷikkān paṛayū."),
    ("The rain forced us to cancel the picnic.", "മഴ ഞങ്ങൾക്ക് പിക്കനിക് റദ്ദാക്കാൻ നിർബന്ധിച്ചു.", "maḻa ñaṅṅaḷkku pikkanik rad'dhākkān nirbandhiccu."),
    ("She got the tailor to stitch a new blouse.", "ടെയിലറിന് പുതിയ ബ്ലൗസ് തയ്ക്കാൻ പറഞ്ഞു.", "ṭeylarin putiya blaus taykkān paṟaññu."),
    ("Parents teach children to respect elders.", "മാതാപിതാക്കൾ മുതിർന്നവരെ ബഹുമാനിക്കാൻ പഠിപ്പിക്കുന്നു.", "mātāpitākkaḷ mutirnnavare bahumānikkān paṭhippikkunnu."),
    ("I will have the electrician check the wiring.", "ഇലക്ട്രീഷ്യൻ വയറിംഗ് പരിശോധിക്കാൻ വിളിക്കും.", "ilekṭrīṣyan vayariṅ pariśōdhikkān viḷikkuṁ."),
    ("The coach made the team run extra laps.", "കോച്ച് ടീമിന് അധിക റൺ ഓടിച്ചു.", "kōc ṭīmin adhika raṇ ōṭiccu."),
    ("Negative: don’t force anyone to eat meat.", "മാംസം കഴിപ്പിക്കാൻ ആരെയും നിർബന്ധിക്കരുത്.", "māṁsaṁ kaḻippikkān āreyuṁ nirbandhikkarut."),
    ("Reflexive nuance: I got myself registered online.", "ഓൺലൈനിൽ രജിസ്റ്റർ ചെയ്തുകൊണ്ടു.", "ōnlainil rajisṟṭar ceytu koṇṭu."),
    ("Complex: the lawyer had the witness repeat the statement.", "വക്കീൽ സാക്ഷിയോട് മൊഴി വീണ്ടും പറയിച്ചു.", "vakkīl sākṣiyōṭ muḻi vīṇṭuṁ paṛayiccu."),
    ("Practice causative sentences with \"ākkuka\", \"ippikkuka\".", "“ആക്കുക”, “ഇപ്പിക്കുക” ഉപയോഗിച്ച് വാക്യങ്ങൾ.", "“ākkuka”, “ippikkuka” upayōgicc vākyaṅṅaḷ."),
    ("Gentle request: could you ask him to wait?", "അവനോട് കാത്തിരിക്കാൻ പറയാമോ?", "avanōṭ kāttirikkān paṛayāmō?"),
)

DATA581 = D(
    ("Someone left a bag somewhere on the bus.", "ഒരാൾ ബസിൽ എവിടെയോ ഒരു ബാഗ് വെച്ചുപോയി.", "orāḷ basil evideyō oru bāk veccupōyi."),
    ("We will find a solution somehow before Monday.", "തിങ്കളാഴ്ചയ്ക്ക് മുമ്പ് എങ്ങനെയോ ഒരു പരിഹാരം കണ്ടെത്തും.", "tiṅṅaḷāḻccaykku mump eṅṅaneyō oru parihāraṁ kaṇṭettuṁ."),
    ("If anything goes wrong, call me immediately.", "എന്തെങ്കിലും പിശക് സംഭവിച്ചാൽ ഉടൻ വിളിക്കുക.", "enteṅkiluṁ piśak saṁbhaviccuṭan viḷikkuka."),
    ("Anybody can join the class; no fee is required.", "ആർക്കും ക്ലാസിൽ ചേരാം; ഫീസ് വേണ്ട.", "ārkkuṁ klāsil cērāṁ; phīs vēṇṭa."),
    ("I did not see anybody at the station at dawn.", "പ്രഭാതത്തിൽ സ്റ്റേഷനിൽ ആരെയും കണ്ടില്ല.", "prabhātattil sṟṟēṣaṇil āreyuṁ kaṇṭilla."),
    ("Something sweet would be nice after the meal.", "ഭക്ഷണത്തിന് ശേഷം എന്തെങ്കിലും മധുരം നന്ന്.", "bhakṣaṇattin śeṣaṁ enteṅkiluṁ madhuraṁ nan."),
    ("Nothing is impossible if we work together.", "ഒന്നിച്ച് പരിശ്രമിച്ചാൽ ഒന്നും അസാധ്യമല്ല.", "onnicc pariśramiccā onnuṁ asādhyamalla."),
    ("Somewhere in this district there is a quiet beach.", "ഈ ജില്ലയിൽ എവിടെയോ ഒരു നിശ്ശബ്ദമായ കടൽത്തീരമുണ്ട്.", "ī jillayil evideyō oru niśśabdamāya kaḷattīramuṇṭ."),
    ("Somehow the lost ticket was found in the pocket.", "നഷ്ടപ്പെട്ട ടിക്കറ്റ് എങ്ങനെയോ കീശയിൽ കണ്ടെത്തി.", "naṣṭappeṭṭa ṭikkaṭṭ eṅṅaneyō kīśayil kaṇṭetti."),
    ("\"evideyō\" marks an indefinite place.", "തെളിഞ്ഞ സ്ഥാനമില്ലാത്തപ്പോൾ “എവിടെയോ”.", "teḷiñña sthānamillāteppōḷ “evideyō”."),
    ("\"āreyuṁ\" often appears in negative sentences.", "നിഷേധ വാക്യത്തിൽ “ആരെയും”.", "niṣēdha vākyattil “āreyuṁ”."),
    ("\"onnuṁ\" pairs with \"illa\" for nothing.", "“ഒന്നും ഇല്ല” ശൂന്യത.", "“onnuṁ illa” śūnyata."),
    ("Generalising: people gossip everywhere in small towns.", "ചെറിയ പട്ടണങ്ങളിൽ എല്ലായിടെയും പരദൂഷണമുണ്ട്.", "ceṛiya paṭṭaṇaṅṅaḷil ellāyiṭeyuṁ paradūṣaṇamuṇṭ."),
    ("Anything you need, ask without hesitation.", "വേണ്ടതെന്തും മടിക്കാതെ ചോദിക്കുക.", "vēṇṭatentuṁ maṭikkāte cōdikkuka."),
    ("Nobody answered though the phone rang many times.", "ഫോൺ പല തവണ മുഴങ്ങിയെങ്കിലും ആരും എടുത്തില്ല.", "phōṇ pala tavaṇa muḻaṅṅiyeṅkiluṁ āruṁ eṭuttuilla."),
    ("We can meet anywhere convenient for both of us.", "രണ്ടുപേർക്കും സൗകര്യമുള്ള സ്ഥലത്ത് കാണാം.", "raṇṭupērkkuṁ saukaryamuḷḷa sthalatt kāṇāṁ."),
    ("Somehow she finished the work before sunset.", "എങ്ങനെയോ സൂര്യാസ്തമയത്തിന് മുമ്പ് ജോലി തീർത്തു.", "eṅṅaneyō sūryāstamayattin mump jōli tīrttu."),
    ("If anything is unclear, write it in your notebook.", "എന്തെങ്കിലും വ്യക്തമല്ലെങ്കിൽ നോട്ടുപുസ്തകത്തിൽ എഴുതുക.", "enteṅkiluṁ vyaktamalleṅkiḷ nōṭṭupustakattil eḻutuka."),
)

DATA582 = D(
    ("I have two younger brothers and one elder sister.", "എനിക്ക് രണ്ട് അനുജന്മാരും ഒരു അക்கയുമുണ്ട്.", "enikk raṇṭ anujanmāruṁ oru akkayumuṇṭ."),
    ("She has a small house near the backwaters.", "കായലിനടുത്ത് അവൾക്ക് ചെറിയ വീടുണ്ട്.", "kāyalinaṭutt avaḷkku ceṛiya vīṭuṇṭ."),
    ("We have enough rice for the whole week.", "മുഴുവൻ ആഴ്ചയ്ക്കും നമുക്ക് ചോറ് മതിയാകും.", "muḻuvan āḻccaykkuṁ namukku cōṟ matiyākuṁ."),
    ("He has no vehicle; he uses the bus daily.", "വാഹനമില്ല; ദിവസവും ബസ് ഉപയോഗിക്കുന്നു.", "vāhanamilla; divasavuṁ bas upayōgikkunnu."),
    ("Do you have change for a hundred rupees?", "നൂറു രൂപയ്ക്ക് ചില്ലറയുണ്ടോ?", "nūṟu rūpaykku cillaṛayuṇṭō?"),
    ("Malayalam often uses \"uṇṭ\" for possession with dative.", "ഉടമസ്ഥത “എനിക്ക് ഉണ്ട്” രൂപത്തിൽ.", "uṭamasthata “enikk uṇṭ” rūpattil."),
    ("\"illa\" negates possession clearly.", "ഉടമയില്ലെങ്കിൽ “ഇല്ല”.", "uṭamayilleṅkiḷ “illa”."),
    ("They have many relatives in the Gulf.", "ഗൾഫിൽ അവർക്ക് ധാരാളം ബന്ധുക്കളുണ്ട്.", "gaḷfil avarkku dhārāḷaṁ bandhukkaḷuṇṭ."),
    ("I have a doubt about this grammar rule.", "ഈ വ്യാകരണ നിയമത്തിൽ എനിക്ക് സംശയമുണ്ട്.", "ī vyākaraṇa niyamattil enikk saṁśayamuṇṭ."),
    ("She has patience when teaching beginners.", "തുടക്കക്കാരെ പഠിപ്പിക്കുമ്പോൾ അവൾക്ക് ക്ഷമയുണ്ട്.", "tuṭakkakkāre paṭhippikkumbōḷ avaḷkku kṣamayuṇṭ."),
    ("We have faith in the fairness of the exam.", "പരീക്ഷയുടെ നീതിയിൽ ഞങ്ങൾക്ക് വിശ്വാസമുണ്ട്.", "parīkṣayuṭe nītiyil ñaṅṅaḷkku viśvāsamuṇṭ."),
    ("He has a cold; he should rest at home.", "ജലദോഷമുണ്ട്; വീട്ടിൽ വിശ്രമിക്കണം.", "jaladōṣamuṇṭ; vīṭṭil viśramikkaṇaṁ."),
    ("The family has lived here for three generations.", "മൂന്നു തലമുറകളായി ഇവിടെ കുടുംബം താമസിക്കുന്നു.", "mūnnu talamuraḷāyi ivide kuṭumbaṁ tāmasikkunnu."),
    ("I have nothing more to say on this topic.", "ഈ വിഷയത്തിൽ പറയാൻ മറ്റൊന്നുമില്ല.", "ī viṣayattil paṛayān maṭṭonnumilla."),
    ("She has permission to leave early today.", "ഇന്ന് നേരത്തെ പോകാൻ അവൾക്ക് അനുമതിയുണ്ട്.", "inn nērattē pōkān avaḷkku anumatiyuṇṭ."),
    ("We have completed the first chapter today.", "ഇന്ന് ഒന്നാം അദ്ധ്യായം പൂർത്തിയാക്കി.", "inn onnāṁ adhyāyaṁ pūrttiyākki."),
    ("Do you have time to read this article?", "ഈ ലേഖനം വായിക്കാൻ സമയമുണ്ടോ?", "ī lēkhanaṁ vāyikkān samayamuṇṭō?"),
    ("They have promised to donate books to the library.", "ലൈബ്രറിയിൽ പുസ്തകം സംഭാവന ചെയ്യാമെന്ന് വാഗ്ദാനം ചെയ്തു.", "laibraṟiyil pustakaṁ saṁbhāvana ceyyāmenn vāgdānaṁ ceytu."),
)

DATA583 = D(
    ("What does this Malayalam word mean?", "ഈ മലയാള വാക്കിന്റെ അർത്ഥം എന്താണ്?", "ī malayāḷa vākkinṟe artthaṁ entāṇ?"),
    ("This sign means “no parking”.", "ഈ അടയാളം “പാർക്ക് ചെയ്യരുത്” എന്നർത്ഥം.", "ī aṭayāḷaṁ “pārk ceyyarut” ennartthaṁ."),
    ("I did not mean to hurt your feelings.", "നിന്റെ മനസ്സ് വേദനിപ്പിക്കണമെന്ന് ഉദ്ദേശിച്ചില്ല.", "ninṟa manas vēdanippikkaṇamenn uddēśiccilla."),
    ("The colour red often means danger on roads.", "ചുവപ്പ് റോഡിൽ പലപ്പോഴും അപായം സൂചിപ്പിക്കുന്നു.", "cuvapp rōḷil palappōḷuṁ apāyaṁ sūcippikkunnu."),
    ("Could you explain what this proverb means?", "ഈ പഴഞ്ചൊല്ലിന്റെ അർത്ഥം വിശദീകരിക്കുമോ?", "ī paḻañcollinṟe artthaṁ viśadīkarikkumō?"),
    ("\"artthaṁ\" is the usual noun for meaning.", "വിശാലാർത്ഥത്തിൽ “അർത്ഥം”.", "viśālārthattil “artthaṁ”."),
    ("\"entāṇ\" asks for a gloss in conversation.", "ചോദ്യത്തിൽ “എന്താണ്” അർത്ഥം ചോദിക്കാൻ.", "cōdyattil “entāṇ” artthaṁ cōdikkān."),
    ("This gesture means “come here” in Kerala.", "ഈ ആംഗ്യം കേരളത്തിൽ “ഇവിടെ വാ” എന്നർത്ഥം.", "ī āṁgyaṁ kēraḷattil “ivide vā” ennartthaṁ."),
    ("The teacher asked what the poem meant.", "അധ്യാപകൻ കവിതയുടെ അർത്ഥം ചോദിച്ചു.", "adhyāpakan kavitayuṭe artthaṁ cōdiccu."),
    ("Symbols mean different things in different cultures.", "പല സംസ്കാരങ്ങളിൽ അടയാളങ്ങൾ വ്യത്യസ്തമാണ്.", "pala saṁskāraṅṅaḷil aṭayāḷaṅṅaḷ vyatystamāṇ."),
    ("I meant to call you yesterday but I was busy.", "ഇന്നലെ വിളിക്കണമെന്ന് ഉദ്ദേശിച്ചിരുന്നു; തിരക്കായിരുന്നു.", "innale viḷikkaṇamenn uddēśiccirunnu; tiraṅṅkāyirunnu."),
    ("If a sentence is ambiguous, ask for clarification.", "വാക്യം അസ്പഷ്ടമാണെങ്കിൽ വ്യക്തീകരണം ചോദിക്കുക.", "vākyaṁ aspaṣṭamāṇeṅkiḷ vyaktīkaraṇaṁ cōdikkuka."),
    ("The map legend explains what each colour means.", "മാപ്പിലെ ലജൻഡ് ഓരോ നിറത്തിന്റെയും അർത്ഥം പറയുന്നു.", "māppile lajeṇḍ ōrō niṛattinṟeyuṁ artthaṁ paṛayunnu."),
    ("Slang can mean something else to young people.", "യുവജനങ്ങൾക്ക് സ്ലാങ് വേറെ അർത്ഥമാകാം.", "yuvajanaṅṅaḷkku slāṅ vēṛe artthamākkāṁ."),
    ("Double meaning jokes need careful context.", "ഇരട്ട അർത്ഥമുള്ള തമാശകൾ സന്ദർഭം വേണം.", "iraṭṭa artthamuḷḷa tamāśakaḷ sandarbhaṁ vēṇaṁ."),
    ("The contract means we must finish by March.", "കരാർ മാർച്ചിന് മുമ്പ് തീർക്കണമെന്ന് അർത്ഥം.", "karār mārcin mump tīrkkaṇamenn artthaṁ."),
    ("I finally understood what she meant.", "അവൾ ഉദ്ദേശിച്ചതിന്റെ അർത്ഥം ഒടുവിൽ മനസ്സിലായി.", "avaḷ uddēśiccatinṟe artthaṁ oṭuvil manassilāyi."),
    ("Ask politely: I do not understand this word’s meaning.", "മര്യാദയോടെ: ഈ വാക്കിന്റെ അർത്ഥം മനസ്സിലായില്ല.", "maryādayōṭe: ī vākkinṟe artthaṁ manassilāyilla."),
)

DATA584 = D(
    ("I bought rice and vegetables at the market.", "ഞാൻ ചന്തയിൽ ചോറിനും പച്ചക്കറിക്കും വാങ്ങി.", "njān chantil cōṟinuṁ paccakaṛikkuṁ vāṅṅi."),
    ("She studied hard but the exam was difficult.", "കഠിനമായി പഠിച്ചു പക്ഷേ പരീക്ഷ കഠിനമായിരുന്നു.", "kaṭhinamāyi paṭhiccu pakṣe parīkṣa kaṭhinamāyirunnu."),
    ("We stayed home because it was raining heavily.", "കനത്ത മഴ പെയ്തതുകൊണ്ട് വീട്ടിൽ താമസിച്ചു.", "kanatta maḻa peytatukoṇṭ vīṭṭil tāmasiccu."),
    ("He was tired, so he slept early.", "അവൻ ക്ഷീണിച്ചു, അതുകൊണ്ട് നേരത്തെ ഉറങ്ങി.", "avan kṣīṇiccu, atukoṇṭ nērattē uṟaṅṅi."),
    ("I know that you are busy with your project.", "നിന്റെ പദ്ധതിയിൽ തിരക്കാണെന്ന് എനിക്കറിയാം.", "ninṟa padhatiyil tiraṅṅkilāṇenn enikkaṟiyāṁ."),
    ("Although it was late, we finished the chapter.", "താമസിച്ചെങ്കിലും അദ്ധ്യായം പൂർത്തിയാക്കി.", "tāmasicceṅkiluṁ adhyāyaṁ pūrttiyākki."),
    ("Though she is young, she speaks very clearly.", "പ്രായം കുറവാണെങ്കിലും വളരെ വ്യക്തമായി പറയുന്നു.", "prāyaṁ kuṛavāṇeṅkiluṁ vaḷare vyaktamāyi paṛayunnu."),
    ("He was unwell; still he attended the meeting.", "അസുഖമായിരുന്നു; എങ്കിലും യോഗത്തിൽ പങ്കെടുത്തു.", "asukhamāyirunnu; eṅkiluṁ yōgattil paṅṅkeṭuttu."),
    ("The task is hard; yet we will try our best.", "ജോലി കഠിനമാണ്; എങ്കിലും നമ്മുടെ കഴിവ് തീർക്കും.", "jōli kaṭhinamāṇ; eṅkiluṁ nammutē kaḻiv tīrkuṁ."),
    ("\"ennāl\" introduces a contrast between clauses.", "വാക്യഭാഗങ്ങൾക്കിടയിൽ വ്യത്യാസം “എന്നാൽ”.", "vākyabhāgaṅṅaḷkkiṭayil vyatāsam “ennāl”."),
    ("\"kāraṇaṁ\" gives a reason like \"because\".", "കാരണം വ്യക്തമാക്കാൻ “കാരണം”.", "kāraṇaṁ vyaktamākkān “kāraṇaṁ”."),
    ("\"atukoṇṭ\" shows result or \"so\".", "ഫലം “അതുകൊണ്ട്”.", "phalaṁ “atukoṇṭ”."),
    ("\"enn\" introduces reported speech or that-clauses.", "അടയാളപ്പെടുത്താൻ “എന്ന്”.", "aḍayāḷappeṭuttān “enn”."),
    ("\"eṅkiluṁ\" softens contrast like \"still\".", "എതിർക്കൊപ്പം “എങ്കിലും”.", "etirkkoppaṁ “eṅkiluṁ”."),
    ("We packed food and water for the journey.", "യാത്രയ്ക്ക് ഭക്ഷണവും വെള്ളവും പാക്ക് ചെയ്തു.", "yātraykku bhakṣaṇavuṁ veḷḷavuṁ pāk ceytu."),
    ("Because the bus was full, we took a taxi.", "ബസ് നിറഞ്ഞതുകൊണ്ട് ടാക്സി എടുത്തു.", "bas niṛaññatukoṇṭ ṭāksi eṭuttu."),
    ("Although the path was steep, we reached the top.", "കയറ്റം കടന്നെങ്കിലും മുകളിലെത്തി.", "kayaṭṭaṁ kaṭanneṅkiluṁ mukaḷiletti."),
    ("She practised daily so that she could win.", "ജയിക്കാൻ ദിവസവും പരിശീലിച്ചു.", "jayikkān divasavuṁ pariśīliccu."),
)

DATA585 = D(
    ("You can take tea or coffee, whichever you prefer.", "ചായയോ കാപ്പിയോ, ഇഷ്ടമുള്ളത് എടുക്കൂ.", "cāyayō kāppiyō, iṣṭamuḷḷat eṭukkhū."),
    ("Neither he nor she could answer the last question.", "അവനും അവളും അവസാന ചോദ്യത്തിന് ഉത്തരം പറഞ്ഞില്ല.", "avanuṁ avaḷuṁ avasāna cōdyattin uttaraṁ paṟaññilla."),
    ("If it rains, we will cancel the picnic.", "മഴ പെയ്താൽ പിക്കനിക് റദ്ദാക്കും.", "maḻa peytāl pikkanik rad'dhākkuṁ."),
    ("If you see him, give him this letter.", "അവനെ കണ്ടാൽ ഈ കത്ത് കൊടുക്കുക.", "avane kaṇṭāl ī katt koṭukkuka."),
    ("In case you forget, I will send a reminder.", "മറന്നാൽ ഞാൻ ഓർമ്മപ്പെടുത്തൽ അയയ്ക്കും.", "maṟannāl njān ōrm'mppeṭuttal ayaykkuṁ."),
    ("You may leave early provided you finish the task.", "ജോലി തീർത്താൽ നേരത്തെ പോകാം.", "jōli tīrttāl nērattē pōkāṁ."),
    ("As the sun rose, the mist disappeared.", "സൂര്യൻ ഉദിച്ചപ്പോൾ മൂടൽ മാഞ്ഞു.", "sūryan udiccappōḷ mūṭal māññu."),
    ("Neither this book nor that one is available now.", "ഈ പുസ്തകവും ആ പുസ്തകവും ഇപ്പോൾ ലഭ്യമല്ല.", "ī pustakavuṁ ā pustakavuṁ ippōḷ labhyamalla."),
    ("Either call today or message tomorrow morning.", "ഇന്ന് വിളിക്കുക അല്ലെങ്കിൽ നാളെ പ്രഭാതത്തിൽ മെസേജ് ചെയ്യുക.", "inn viḷikkuka alleṅkiḷ nāḷe prabhātattil mesēj ceyyuka."),
    ("If it is convenient, visit us this weekend.", "സൗകര്യമുണ്ടെങ്കിൽ ഈ ആഴ്ചാവസാനം വന്നുകൊള്ളുക.", "saukaryamuṇṭeṅkiḷ ī āḻccāvasānaṁ vannukoḷḷuka."),
    ("\"alleṅkil\" presents the alternative \"or\".", "വികല്പം “അല്ലെങ്കിൽ”.", "vikalpaṁ “alleṅkil”."),
    ("\"eṅkil\" begins many conditional clauses.", "ഉപാധി “എങ്കിൽ”.", "upādhi “eṅkil”."),
    ("\"pakṣe\" can contrast like \"but\" in speech.", "സംസാരത്തിൽ വിരോധം “പക്ഷേ”.", "saṁsāraṭṭil virōdhaṁ “pakṣe”."),
    ("Neither wind nor wave stopped the fishermen.", "കാറ്റോ തിരമാലയോ മത്സ്യബന്ധനത്തെ നിർത്തിയില്ല.", "kāṭṭō tiramālayō matsyabandhanatte nirttiyilla."),
    ("If you need help, ask without hesitation.", "സഹായം വേണമെങ്കിൽ മടിക്കാതെ ചോദിക്കുക.", "sahāyaṁ vēṇameṅkiḷ maṭikkāte cōdikkuka."),
    ("As long as you are honest, people will trust you.", "നീ നിഷ്കളങ്കനാണെങ്കിൽ ആളുകൾ വിശ്വസിക്കും.", "nī niṣkaḷaṅkaṇāṇeṅkiḷ āḷukaḷ viśvasikkuṁ."),
    ("Unless you practise, fluency will not come.", "പരിശീലിക്കാതെ പ്രാവീണ്യം വരില്ല.", "pariśīlikkāte prāvīṇyaṁ varilla."),
    ("Either we leave now or we miss the train.", "ഇപ്പോൾ പോകണം അല്ലെങ്കിൽ ട്രെയിൻ നഷ്ടപ്പെടും.", "ippōḷ pōkaṇaṁ alleṅkiḷ ṭreyin naṣṭappeṭuṁ."),
)

DATA586 = D(
    ("After we ate, we went for a short walk.", "ഭക്ഷണം കഴിഞ്ഞ് ഞങ്ങൾ കുറച്ച് നടന്നു.", "bhakṣaṇaṁ kaḻiññ ñaṅṅaḷ kureśś naṭannu."),
    ("Then she opened her book and began to read.", "പിന്നീട് അവൾ പുസ്തകം തുറന്ന് വായിക്കാൻ തുടങ്ങി.", "piṇīṭ avaḷ pustakaṁ tuṟannu vāyikkān tuṭaṅṅi."),
    ("As far as I know, the shop closes at eight.", "എനിക്കറിയാവുന്ന വരെ കട എട്ടുമണിക്ക് അടയ്ക്കും.", "enikkaṟiyāvunna vare kaṭa eṭṭumaṇik aṭaykkuṁ."),
    ("As long as you stay calm, we can solve this.", "നീ ശാന്തനായിരിക്കുന്നിടം വരെ ഇത് പരിഹരിക്കാം.", "nī śāntanāyirikkunniṭaṁ vare it pariharikkāṁ."),
    ("He behaved as if nothing had happened.", "ഒന്നും സംഭവിച്ചില്ലെന്ന പോലെ അവൻ പെരുമാറി.", "onnuṁ saṁbhavicillenna pōle avan perumāṛi."),
    ("After the bell rang, the students stood up.", "മണി മുഴങ്ങിയ ശേഷം വിദ്യാർത്ഥികൾ എഴുന്നേറ്റു.", "maṇi muḻaṅṅiya śeṣaṁ vidyārththikaḷ eḻunnēṭṭu."),
    ("First finish homework; then you may watch TV.", "ആദ്യം ഗൃഹപാഠം തീർക്കുക; പിന്നീട് ടിവി കാണാം.", "ādyaṁ gr̥hapāṭhaṁ tīrkkuka; piṇīṭ ṭivi kāṇāṁ."),
    ("As far as the report shows, sales increased.", "റിപ്പോർട്ട് കാണിക്കുന്ന വരെ വിൽപ്പന കൂടി.", "rippōṭṭ kāṇikkunna vare vilppana kūṭi."),
    ("She sang as if she were on a big stage.", "വലിയ വേദിയിലാണെന്ന പോലെ അവൾ പാടി.", "valiya vēdiyilāṇenna pōle avaḷ pāṭi."),
    ("We will wait as long as the doctor needs.", "ഡോക്ടർക്ക് വേണ്ടത്ര സമയം വരെ കാത്തിരിക്കും.", "ḍōkṭṭarkku vēṇṭatra samayaṁ vare kāttirikkuṁ."),
    ("After the storm passed, the sky cleared.", "കൊടുങ്കാറ്റ് കഴിഞ്ഞ് ആകാശം വ്യക്തമായി.", "koṭuṅkāṭṭ kaḻiññ ākāśaṁ vyaktamāyi."),
    ("\"kaḻiññ\" marks sequence: after finishing.", "ക്രമം “കഴിഞ്ഞ്” കൊണ്ട്.", "kramaṁ “kaḻiññ” koṇṭ."),
    ("\"piṇīṭ\" means then or afterwards.", "സമയക്രമത്തിൽ “പിന്നീട്”.", "samayakramattil “piṇīṭ”."),
    ("\"enna pōle\" builds as-if comparisons.", "ഉപമ “എന്ന പോലെ”.", "upama “enna pōle”."),
    ("As far as money is concerned, we are careful.", "പണകാര്യത്തിൽ ഞങ്ങൾ ശ്രദ്ധാപൂർവ്വമാണ്.", "paṇakāryattil ñaṅṅaḷ śraddhāpūrvvamāṇ."),
    ("After you sign, we can post the letter.", "ഒപ്പിട്ടാൽ കത്ത് പോസ്റ്റ് ചെയ്യാം.", "oppiṭṭāl katt pōsṭ ceyyāṁ."),
    ("He spoke as if he had seen everything himself.", "എല്ലാം സ്വയം കണ്ട പോലെ അവൻ സംസാരിച്ചു.", "ellāṁ svayaṁ kaṇṭa pōle avan saṁsāriccu."),
    ("As long as there is light, keep reading.", "വെളിച്ചമുണ്ടാകുന്നിടം വരെ വായിക്കുക.", "veḷiccamuṇṭākunniṭaṁ vare vāyikkuka."),
)

DATA587 = D(
    ("As soon as the train stopped, passengers rushed out.", "ട്രെയിൻ നിർത്തിയതും യാത്രക്കാർ പുറത്തേക്ക് ഓടി.", "ṭreyin nirttiyatuṁ yātrakkār puṟattēkk ōṭi."),
    ("Once you understand the rule, exercises become easy.", "നിയമം മനസ്സിലായാൽ അഭ്യാസങ്ങൾ എളുപ്പമാകും.", "niyamaṁ manassilāyāl abhyāsaṅṅaḷ eḷuppamākuṁ."),
    ("Rather than argue, let us ask the teacher.", "വാദിക്കുന്നതിന് പകരം അധ്യാപകനോട് ചോദിക്കുക.", "vādikkunnatin pakaraṁ adhyāpakanōṭ cōdikkuka."),
    ("Instead of taking a taxi, we walked to save money.", "ടാക്സി എടുക്കുന്നതിന് പകരം നടന്ന് പണം ലാഭിച്ചു.", "ṭāksi eṭukkunatin pakaraṁ naṭannu paṇaṁ lābhiccu."),
    ("Close the door so that mosquitoes do not enter.", "കൊതുകുകൾ അകത്ത് കയറാതിരിക്കാൻ വാതിൽ അടയ്ക്കുക.", "kotukukaḷ akatt kayaṟātirikkān vātil aṭaykkuka."),
    ("She studied hard so that she could pass the exam.", "പരീക്ഷ പാസാകാൻ അവൾ കഠിനമായി പഠിച്ചു.", "parīkṣa pāsākān avaḷ kaṭhinamāyi paṭhiccu."),
    ("As soon as I heard the news, I called home.", "വാർത്ത കേട്ടതും വീട്ടിലേക്ക് വിളിച്ചു.", "vārtta kēṭṭatuṁ vīṭṭilēkk viḷiccu."),
    ("Once the rain stops, we will start the match.", "മഴ നിർത്തിയാൽ മത്സരം തുടങ്ങും.", "maḻa nirttiyāl matsaraṁ tuṭaṅṅuṁ."),
    ("Rather than wait alone, join us in the hall.", "ഒറ്റയ്ക്ക് കാത്തിരിക്കുന്നതിന് പകരം ഹാളിൽ വന്ന് ചേരുക.", "oṭṭakk kāttirikkunnatin pakaraṁ hāḷil vann cēruka."),
    ("Instead of buying new, repair the old radio.", "പുതിയത് വാങ്ങുന്നതിന് പകരം പഴയ റേഡിയോ നന്നാക്കുക.", "putiyat vāṅṅunnatin pakaraṁ paḻaya rēḍiyō nannākkuka."),
    ("Speak clearly so that everyone can hear.", "എല്ലാവരും കേൾക്കാൻ വ്യക്തമായി സംസാരിക്കുക.", "ellāvaruṁ kēḷkkān vyaktamāyi saṁsārikkuka."),
    ("\"uṭane\" emphasises immediacy after an event.", "വേഗത്തിലുള്ള പ്രതികരണം “ഉടനെ”.", "vēgattiluḷḷa pratikaraṇaṁ “uṭane”."),
    ("\"orikkal\" begins \"once\" conditions.", "ഒരു തവണ സംഭവിച്ചാൽ “ഒരിക്കൽ”.", "oru tavaṇa saṁbhaviccuṭal “orikkal”."),
    ("\"alleṅkil\" can introduce alternatives rather than.", "തിരഞ്ഞെടുപ്പിൽ “അല്ലെങ്കിൽ”.", "tiraññeṭuppil “alleṅkil”."),
    ("Lock the gate so that the dog does not run out.", "നായ പുറത്തേക്ക് ഓടാതിരിക്കാൻ ഗേറ്റ് പൂട്ടുക.", "nāya puṟattēkk ōṭātirikkān gēṭṭ pūṭṭuka."),
    ("As soon as dawn broke, farmers went to the field.", "പ്രഭാതം പൊട്ടിയതും കർഷകർ വയലിലേക്ക് പോയി.", "prabhātaṁ poṭṭiyatuṁ karṣakar vayalilēkk pōyi."),
    ("Rather than complain, propose a practical solution.", "പരിഭവിക്കുന്നതിന് പകരം പ്രായോഗിക പരിഹാരം നിർദ്ദേശിക്കുക.", "paribhavikkunnatin pakaraṁ prāyōgika parihāraṁ nirddēśikkuka."),
    ("She saved money so that her daughter could study abroad.", "മകൾ വിദേശത്ത് പഠിക്കാൻ പണം സംരക്ഷിച്ചു.", "makaḷ vidēśatt paṭhikkān paṇaṁ saṁrakṣiccu."),
)

DATA588 = D(
    ("And", "ഒപ്പം", "oppaṁ"),
    ("But", "പക്ഷേ", "pakṣe"),
    ("Because", "കാരണം", "kāraṇaṁ"),
    ("So", "അതുകൊണ്ട്", "atukoṇṭ"),
    ("That", "എന്ന്", "enn"),
    ("Although", "എങ്കിലും", "eṅkiluṁ"),
    ("Though", "എങ്കിലും", "eṅkiluṁ"),
    ("Still", "എങ്കിലും", "eṅkiluṁ"),
    ("Yet", "എങ്കിലും", "eṅkiluṁ"),
    ("Or", "അല്ലെങ്കിൽ", "alleṅkil"),
    ("If", "എങ്കിൽ", "eṅkil"),
    ("As", "പോലെ", "pōle"),
    ("After", "കഴിഞ്ഞ്", "kaḻiññ"),
    ("Then", "പിന്നീട്", "piṇīṭ"),
    ("Before", "മുമ്പ്", "mump"),
    ("Until", "വരെ", "vare"),
    ("Unless", "ഇല്ലെങ്കിൽ", "illeṅkil"),
    ("While", "ഇരിക്കുമ്പോൾ", "irikkumbōḷ"),
)

DATA589 = D(
    ("I woke early. I finished my homework.", "ഞാൻ നേരത്തെ എഴുന്നേറ്റു. ഗൃഹപാഠം തീർത്തു.", "njān nērattē eḻunnēṭṭu. gr̥hapāṭhaṁ tīrttu."),
    ("Combine: I woke early and finished my homework.", "ഞാൻ നേരത്തെ എഴുന്നേറ്റ് ഗൃഹപാഠം തീർത്തു.", "njān nērattē eḻunnēṭṭ gr̥hapāṭhaṁ tīrttu."),
    ("She likes music. She practises every day.", "അവൾക്ക് സംഗീതം ഇഷ്ടമാണ്. ദിവസവും പരിശീലിക്കുന്നു.", "avaḷkku saṁgītaṁ iṣṭamāṇ. divasavuṁ pariśīlikkunnu."),
    ("Combine: She likes music, so she practises daily.", "സംഗീതം ഇഷ്ടമാണ്, അതുകൊണ്ട് ദിവസവും പരിശീലിക്കുന്നു.", "saṁgītaṁ iṣṭamāṇ, atukoṇṭ divasavuṁ pariśīlikkunnu."),
    ("The bus was late. We missed the meeting.", "ബസ് വൈകി. യോഗം നഷ്ടപ്പെട്ടു.", "bas vaiki. yōgaṁ naṣṭappeṭṭu."),
    ("Combine: The bus was late, so we missed the meeting.", "ബസ് വൈകിയതുകൊണ്ട് യോഗം നഷ്ടപ്പെട്ടു.", "bas vaikyatukoṇṭ yōgaṁ naṣṭappeṭṭu."),
    ("He studied well. He was nervous in the exam.", "നന്നായി പഠിച്ചു. പരീക്ഷയിൽ മനംകുഴഞ്ഞു.", "nannāyi paṭhiccu. parīkṣayil manaṁkuḻaññu."),
    ("Combine: Although he studied well, he was nervous.", "നന്നായി പഠിച്ചെങ്കിലും പരീക്ഷയിൽ മനംകുഴഞ്ഞു.", "nannāyi paṭhicceṅkiluṁ parīkṣayil manaṁkuḻaññu."),
    ("It rained. The match was postponed.", "മഴ പെയ്തു. മത്സരം മാറ്റിവെച്ചു.", "maḻa peytu. matsaraṁ māṭṭiveccu."),
    ("Combine: Because it rained, the match was postponed.", "മഴ പെയ്തതുകൊണ്ട് മത്സരം മാറ്റിവെച്ചു.", "maḻa peytatukoṇṭ matsaraṁ māṭṭiveccu."),
    ("Use relative clauses: the boy who won is my cousin.", "ജയിച്ച കുട്ടി എന്റെ മാമനാണ്.", "jayicca kuṭṭi enṟa māmanāṇ."),
    ("Use \"enn\" to join reported speech smoothly.", "പ്രസ്താവന “എന്ന്” കൊണ്ട് ബന്ധിക്കുക.", "prastāvana “enn” koṇṭ bandhikkuka."),
    ("Avoid repeating subjects; drop the second \"njān\".", "വിഷയം ആവർത്തിക്കാതെ രണ്ടാമത്തെ “ഞാൻ” ഒഴിവാക്കുക.", "viṣayaṁ āvarttikkāte raṇṭāmatte “njān” oḻivākkuka."),
    ("Link with participles: having eaten, we left.", "ഭക്ഷണം കഴിഞ്ഞ് ഞങ്ങൾ പോയി.", "bhakṣaṇaṁ kaḻiññ ñaṅṅaḷ pōyi."),
    ("Combine short choppy lines into one flowing sentence.", "ചെറിയ വാക്യങ്ങൾ ഒന്നാക്കി ഒഴുക്കോടെ പറയുക.", "ceṛiya vākyaṅṅaḷ onnākki oḻukkōṭe paṛayuka."),
    ("Formal writing prefers connectors over many full stops.", "ഔപചാരിക എഴുത്തിൽ ബന്ധകങ്ങൾ മുഴുവൻ വിരാമത്തിന് പകരം.", "aupacārika eḻutt bandhakaṅṅaḷ muḻuvan virāmattin pakaraṁ."),
    ("Read newspapers to see how editors combine ideas.", "ആശയങ്ങൾ ചേർക്കുന്ന രീതി പത്രങ്ങൾ വായിച്ച് പഠിക്കുക.", "āśayaṅṅaḷ cērkkunna rīti patraṅṅaḷ vāyicc paṭhikkuka."),
    ("Practice: merge two facts about your hometown.", "സ്വന്തം നാടിനെക്കുറിച്ച് രണ്ട് വസ്തുതകൾ ഒന്നാക്കുക.", "svantaṁ nāṭinekuṛicc raṇṭu vastutakaḷ onnākkuka."),
)

DATA590 = D(
    ("Light verb: I gave a call to my uncle.", "ഞാൻ മാമന് വിളിച്ചു.", "njān māman viḷiccu."),
    ("Light verb: she took a decision after discussion.", "ചർച്ചയ്ക്ക് ശേഷം അവൾ തീരുമാനമെടുത്തു.", "carccaykku śeṣaṁ avaḷ tīrumānam eṭuttu."),
    ("Conjunct: he got up and went out quickly.", "അവൻ എഴുന്നേറ്റ് വേഗത്തിൽ പുറത്തേക്ക് പോയി.", "avan eḻunnēṭṭ vēgattil puṟattēkk pōyi."),
    ("Conjunct: open the door and come in.", "വാതിൽ തുറന്ന് അകത്തേക്ക് വാ.", "vātil tuṟannu akattēkku vā."),
    ("\"koṭukkuka\" + noun: give a reply.", "ഉത്തരം കൊടുക്കുക.", "uttaraṁ koṭukkuka."),
    ("\"eṭukkuka\" + noun: take responsibility.", "ഉത്തരവാദിത്വം എടുക്കുക.", "uttaravādittvaṁ eṭukkuka."),
    ("\"ceyyuka\" + noun: do a favour.", "ഒരു അനുഗ്രഹം ചെയ്യുക.", "oru anugrahaṁ ceyyuka."),
    ("\"vekkuka\" + noun: place trust in someone.", "വിശ്വാസം വെക്കുക.", "viśvāsaṁ vekkuka."),
    ("\"ākkuka\" + adjective: make the room clean.", "മുറി വൃത്തിയാക്കുക.", "muṛi vr̥ttiyākkuka."),
    ("Compound: sit and read for an hour.", "ഒരു മണിക്കൂർ ഇരുന്ന് വായിക്കുക.", "oru maṇikkūr irunnu vāyikkuka."),
    ("Compound: get down and cross the road.", "ഇറങ്ങി റോഡ് കടക്കുക.", "iṟaṅṅi rōḷ kaṭakkuka."),
    ("Auxiliary-style: I went to see the doctor.", "ഡോക്ടറെ കാണാൻ പോയി.", "ḍōkṭṭare kāṇān pōyi."),
    ("Auxiliary-style: we came to learn Malayalam.", "മലയാളം പഠിക്കാൻ വന്നു.", "malayāḷaṁ paṭhikkān vannu."),
    ("Serial verbs: search and find the file.", "ഫയൽ തിരഞ്ഞെടുത്തു.", "phayal tiraññeṭuttu."),
    ("Avoid piling more than three verbs without pause.", "മൂന്നിൽ കൂടുതൽ ക്രിയകൾ ചേർക്കാതെ ഇടവെട്ട്.", "mūnnil kūtutal kriyakaḷ cērkkāte iṭaveṭṭ."),
    ("Colloquial: \"pōyi vā\" means go and come back.", "“പോയി വാ” പോയി തിരിച്ചുവാ.", "“pōyi vā” pōyi tiriccuvā."),
    ("Written style prefers explicit conjunctions between clauses.", "എഴുത്തിൽ വാക്യങ്ങൾ “ഒപ്പം”, “പിന്നീട്” കൊണ്ട്.", "eḻutt vākyakaḷ “oppaṁ”, “piṇīṭ” koṇṭ."),
    ("Practice one new compound verb pattern each day.", "ഓരോ ദിവസവും പുതിയ യോജിത ക്രിയാ മാതൃക.", "ōrō divasavuṁ putiya yōjita kriyā mātṛka."),
)

DATA591 = D(
    ("The teacher praised the students.", "അധ്യാപകൻ വിദ്യാർത്ഥികളെ പ്രശംസിച്ചു.", "adhyāpakan vidyārththikaḷe praśaṁsiccu."),
    ("The students were praised by the teacher.", "വിദ്യാർത്ഥികളെ അധ്യാപകൻ പ്രശംസിച്ചു.", "vidyārththikaḷe adhyāpakan praśaṁsiccu."),
    ("Kerala exports spices to many countries.", "കേരളം പല രാജ്യങ്ങളിലേക്ക് മസാലകൾ കയറ്റുമതി ചെയ്യുന്നു.", "kēraḷaṁ pala rājyaṅṅaḷilēkk masālakaḷ kayattumati ceyyunnu."),
    ("Spices are exported by Kerala to many countries.", "മസാലകൾ കേരളം പല രാജ്യങ്ങളിലേക്ക് കയറ്റുമതി ചെയ്യുന്നു.", "masālakaḷ kēraḷaṁ pala rājyaṅṅaḷilēkk kayattumati ceyyunnu."),
    ("They are building a new bridge.", "അവർ പുതിയ പാലം പണിയുന്നു.", "avar putiya pālaṁ paṇiyunnu."),
    ("A new bridge is being built by them.", "പുതിയ പാലം അവർ പണിയുന്നു.", "putiya pālaṁ avar paṇiyunnu."),
    ("Malayalam often keeps the same word order in passive-like sentences.", "നിഷ്ക്രിയ രൂപത്തിൽ വാക്യ ക്രമം മാറ്റാതെ പലപ്പോഴും.", "niṣkriya rūpattil vākya kramaṁ māṭṭāte palappōḷuṁ."),
    ("Use \"ākuka\" with past participle for formal passive.", "ഔപചാരിക നിഷ്ക്രിയത്തിൽ “ആകുക”.", "aupacārika niṣkriyattil “ākuka”."),
    ("Someone stole my bicycle yesterday.", "ഇന്നലെ എന്റെ സൈക്കിൾ ആരോ മോഷ്ടിച്ചു.", "innale enṟa saikkal ārō mōṣṭiccu."),
    ("My bicycle was stolen yesterday.", "ഇന്നലെ എന്റെ സൈക്കിൾ മോഷ്ടിച്ചു.", "innale enṟa saikkal mōṣṭiccu."),
    ("The chef cooked a delicious feast.", "അടുക്കളക്കാരൻ രുചികരമായ വിരുന്ന് ഉണ്ടാക്കി.", "aṭukkaḷakkāran rucikaramāya virunn uṇṭākki."),
    ("A delicious feast was cooked by the chef.", "രുചികരമായ വിരുന്ന് അടുക്കളക്കാരൻ ഉണ്ടാക്കി.", "rucikaramāya virunn aṭukkaḷakkāran uṇṭākki."),
    ("We will announce the results tomorrow.", "ഫലം നാളെ പ്രഖ്യാപിക്കും.", "phalaṁ nāḷe prakhyāpikkuṁ."),
    ("The results will be announced tomorrow.", "ഫലം നാളെ പ്രഖ്യാപിക്കും.", "phalaṁ nāḷe prakhyāpikkuṁ."),
    ("People celebrate Onam with flowers.", "ആളുകൾ പൂക്കളോടെ ഓണം ആഘോഷിക്കുന്നു.", "āḷukaḷ pūkkaḷōṭe ōṇaṁ āghōṣikkunnu."),
    ("Onam is celebrated with flowers.", "ഓണം പൂക്കളോടെ ആഘോഷിക്കുന്നു.", "ōṇaṁ pūkkaḷōṭe āghōṣikkunnu."),
    ("Practice rewriting active sentences in a neutral passive style.", "സജീവ വാക്യങ്ങൾ നിഷ്ക്രിയ ശൈലിയിലേക്ക് മാറ്റി പരിശീലിക്കുക.", "sajīva vākyaṅṅaḷ niṣkriya śailiyilēkk māṭṭi pariśīlikkuka."),
    ("Spoken Malayalam prefers agent + verb without “by”.", "സംസാരത്തിൽ “ആല്‍” പോലുള്ള പ്രത്യേക പ്രതി വിരളം.", "saṁsāraṭṭil “āl” pōluḷḷa pratyēka prati viraḷaṁ."),
)

DATA592 = D(
    ("The report must be submitted before Friday.", "വെള്ളിയാഴ്ചയ്ക്ക് മുമ്പ് റിപ്പോർട്ട് സമർപ്പിക്കണം.", "veḷḷiyāḻccaykku mump rippōṭṭ samarpikkaṇaṁ."),
    ("Everyone should read the notice on the board.", "ബോർഡിലെ അറിയിപ്പ് എല്ലാവരും വായിക്കണം.", "bōrilē aṟiyipp ellāvaruṁ vāyikkaṇaṁ."),
    ("The mistake was noticed during the review.", "പരിശോധനയിൽ പിശക് ശ്രദ്ധയിൽപ്പെട്ടു.", "pariśōdanayil piśak śraddhayilpeṭṭu."),
    ("New rules were introduced last month.", "കഴിഞ്ഞ മാസം പുതിയ നിയമങ്ങൾ കൊണ്ടുവന്നു.", "kaḻiñña māsaṁ putiya niyamaṅṅaḷ koṇṭuvannu."),
    ("The bridge will be inspected next year.", "അടുത്ത വർഷം പാലം പരിശോധിക്കും.", "aṭutta varṣaṁ pālaṁ pariśōdhikkuṁ."),
    ("Permission was granted after a long discussion.", "നീണ്ട ചർച്ചയ്ക്ക് ശേഷം അനുമതി ലഭിച്ചു.", "nīṇṭa carccaykku śeṣaṁ anumati labhiccu."),
    ("Formal letters are written in polite Malayalam.", "ഔപചാരിക കത്തുകൾ മര്യാദയുള്ള മലയാളത്തിൽ.", "aupacārika kathukaḷ maryādayuḷḷa malayāḷattil."),
    ("The song was composed by a famous musician.", "പാട്ട് പ്രശസ്ത സംഗീതജ്ഞൻ രചിച്ചു.", "pāṭṭ praśasta saṁgītajñaṁ raciccu."),
    ("Tickets can be booked online now.", "ടിക്കറ്റ് ഇപ്പോൾ ഓൺലൈനിൽ ബുക്ക് ചെയ്യാം.", "ṭikkaṭ ippōḷ ōnlainil bukk ceyyāṁ."),
    ("The hall had been cleaned before we arrived.", "ഞങ്ങൾ എത്തും മുമ്പ് ഹാൾ വൃത്തിയാക്കിയിരുന്നു.", "ñaṅṅaḷ ettum mump hāḷ vr̥ttiyākkirirunnu."),
    ("Passive style avoids naming the agent in news.", "വാർത്തകളിൽ പ്രവർത്തകനെ നേരിട്ട് പറയാതെ.", "vārttakaḷil pravarttakane nēriṭṭ paṛayāte."),
    ("Government orders are published in the gazette.", "സർക്കാർ ഉത്തരവുകൾ ഗസറ്റിൽ പ്രസിദ്ധീകരിക്കുന്നു.", "sarkkār uttaravukaḷ gasaṭṭil prasiddhīkarikkunnu."),
    ("The patient was examined carefully.", "രോഗിയെ ശ്രദ്ധാപൂർവ്വം പരിശോധിച്ചു.", "rōgiye śraddhāpūrvvaṁ pariśōdhiccu."),
    ("Your application has been received.", "നിങ്ങളുടെ അപേക്ഷ ലഭിച്ചു.", "niṅṅaḷuṭe apēkṣa labhiccu."),
    ("The work should have been finished yesterday.", "ഇന്നലെ ജോലി തീർക്കേണ്ടതായിരുന്നു.", "innale jōli tīrkkēṇṭatāyirunnu."),
    ("Mistakes may be corrected in the next edition.", "അടുത്ത പതിപ്പിൽ പിശകുകൾ തിരുത്താം.", "aṭutta patippil piśakukaḷ tiruttāṁ."),
    ("Formal passive often uses past participle + \"ākuka\".", "ഔപചാരിക നിഷ്ക്രിയ ഭൂതകൃദന്തം + “ആകുക”.", "aupacārika niṣkriya bhūtakr̥dantaṁ + “ākuka”."),
    ("Compare colloquial active with written passive in reports.", "റിപ്പോർട്ടുകളിൽ സംസാര ശൈലിയും എഴുത്ത് ശൈലിയും താരതമ്യം ചെയ്യുക.", "rippōṭṭukaḷil saṁsāra śailiyuṁ eḻutt śailiyuṁ tāratamyaṁ ceyyuka."),
)

DATA593 = D(
    ("I feel cold because the fan is on high.", "ഫാൻ വേഗത്തിൽ ഓടുന്നതുകൊണ്ട് തണുക്കുന്നു.", "phān vēgattil ōṭunnatukoṇṭ taṇukkunnu."),
    ("She feels proud of her daughter’s achievement.", "മകളുടെ നേട്ടത്തിൽ അവൾക്ക് അഭിമാനം തോന്നുന്നു.", "makaḷuṭe nēṭṭattil avaḷkku abhimānaṁ tōnnunnu."),
    ("We feel grateful for your timely help.", "സമയത്തുള്ള സഹായത്തിന് നന്ദി തോന്നുന്നു.", "samayatt uḷḷa sahāyattin nandi tōnnunnu."),
    ("He feels anxious before every examination.", "ഓരോ പരീക്ഷയ്ക്കും മുമ്പ് ആകുലം തോന്നുന്നു.", "ōrō parīkṣaykku mump ākulaṁ tōnnunnu."),
    ("I think this plan will work if we cooperate.", "സഹകരിച്ചാൽ ഈ പദ്ധതി വിജയിക്കുമെന്ന് തോന്നുന്നു.", "sahakariccā ī padhati vijayikkumenn tōnnunnu."),
    ("She thinks Malayalam literature is very rich.", "മലയാള സാഹിത്യം വളരെ സമൃദ്ധമാണെന്ന് അവൾ കരുതുന്നു.", "malayāḷa sāhityaṁ vaḷare samr̥ddhamāṇenn avaḷ karutunnu."),
    ("We think it might rain tonight.", "ഇന്ന് രാത്രി മഴ പെയ്തേക്കുമെന്ന് തോന്നുന്നു.", "inn rātri maḻa peytēkkumenn tōnnunnu."),
    ("They think the train will arrive on time.", "ട്രെയിൻ സമയത്ത് എത്തുമെന്ന് അവർ കരുതുന്നു.", "ṭreyin samayatt ettumenn avar karutunnu."),
    ("\"tōnnunnu\" covers feel and seem.", "അനുഭവം “തോന്നുന്നു”.", "anubhavaṁ “tōnnunnu”."),
    ("\"karutunnu\" leans toward think or believe.", "വിശ്വാസം “കരുതുന്നു”.", "viśvāsaṁ “karutunnu”."),
    ("I feel dizzy after skipping breakfast.", "പ്രാതൽ ഒഴിവാക്കിയതിന് ശേഷം തലകറക്കം.", "prātala oḻivākiyatin śeṣaṁ talakaṟakkaṁ."),
    ("She feels homesick in a new city.", "പുതിയ നഗരത്തിൽ നാട്ടിൽ നിന്നുള്ള വിരഹം.", "putiya nagarattil nāṭṭil ninnulla virahaṁ."),
    ("We think honesty is the best policy.", "നിഷ്കളങ്കത മികച്ച നയമെന്ന് കരുതുന്നു.", "niṣkaḷaṅkata mikacca nayamenn karutunnu."),
    ("He thinks before he speaks in meetings.", "യോഗത്തിൽ സംസാരിക്കും മുമ്പ് ആലോചിക്കുന്നു.", "yōgattil saṁsārikkum mump ālōcikkunnu."),
    ("I feel relieved after submitting the form.", "ഫോം സമർപ്പിച്ചതിന് ശേഷം ആശ്വാസം.", "phōṁ samarpiccatin śeṣaṁ āsvāsaṁ."),
    ("They think climate change is serious.", "കാലാവസ്ഥാ വ്യതിയാനം ഗുരുതരമെന്ന് കരുതുന്നു.", "kālavasthā vyatiyānaṁ gurutaramenn karutunnu."),
    ("Negative: I do not think that is correct.", "അത് ശരിയല്ലെന്ന് തോന്നുന്നില്ല.", "at śariyallen tōnnunnilla."),
    ("Practice expressing feelings without blaming others.", "മറ്റുള്ളവരെ കുറ്റപ്പെടുത്താതെ വികാരം പറയുക.", "maṭṭuḷḷavare kuṭṭappeṭuttāte vikāraṁ paṛayuka."),
)

DATA594 = D(
    ("To carry water on one’s head is an old idiom for needless worry.", "തലയിൽ വെള്ളം കൊണ്ടുപോകുക എന്നത് അനാവശ്യ ചിന്തയുടെ പഴഞ്ചൊല്ല്.", "talayil veḷḷaṁ koṇṭupōkuka ennat anāvaśya cintayuṭe paḻañcoll."),
    ("Every cloud has a silver lining: hope after trouble.", "ഓരോ മേഘത്തിനും വെളിച്ച വക്കുണ്ട്; കഷ്ടത്തിന് ശേഷം പ്രത്യാശ.", "ōrō mēghattinuṁ veḷicca vakkuṇṭ; kaṣṭattin śeṣaṁ pratyāśa."),
    ("Do not count your chickens before they hatch.", "മുട്ട വിരിയും മുമ്പ് കണക്ക് കൂട്ടരുത്.", "muṭṭa viriyum mump kaṇakku kūṭṭarut."),
    ("A stitch in time saves nine: fix problems early.", "സമയത്ത് തുന്നിയാൽ വലിയ കുഴപ്പം ഒഴിവാക്കാം.", "samayatt tuṅṅiyā valiya kuḻappaṁ oḻivākkāṁ."),
    ("Where there is a will, there is a way.", "ആഗ്രഹമുണ്ടെങ്കിൽ വഴിയുണ്ടാകും.", "āgrahamuṇṭeṅkiḷ vazhiyuṇṭākuṁ."),
    ("The early bird catches the worm.", "നേരത്തെ എഴുന്നേറ്റവൻ നേട്ടം കണ്ടെത്തും.", "nērattē eḻunnēṭṭavan nēṭṭaṁ kaṇṭettuṁ."),
    ("Malayalam proverbs often mention coconut and rice.", "തേങ്ങയും ചോറും പഴഞ്ചൊല്ലുകളിൽ സാധാരണ.", "tēṅṅavuṁ cōṟuṁ paḻañcollukaḷil sādhāraṇaṁ."),
    ("\"kaṇṇil karaṭ\" suggests irritation in the eye.", "അസൗകര്യം “കണ്ണിൽ കരട്” പോലെ.", "asaukaryaṁ “kaṇṇil karaṭ” pōle."),
    ("\"kai veṭṭi kāyil veccu\" for self-defeating acts.", "സ്വയം ദോഷം “കൈ വെട്ടി കാലിൽ വെച്ചു”.", "svayaṁ dōṣaṁ “kai veṭṭi kāyil veccu”."),
    ("\"vāyil appaṁ\" for someone who talks sweetly for gain.", "ലാഭത്തിന് മധുരഭാഷണം “വായിൽ അപ്പം”.", "lābhattin madhurabhāṣaṇaṁ “vāyil appaṁ”."),
    ("Learn idioms in context, not word by word.", "പഴഞ്ചൊല്ലുകൾ സന്ദർഭത്തിൽ പഠിക്കുക.", "paḻañcollukaḷ sandarbhattil paṭhikkuka."),
    ("Teachers use idioms to make lessons memorable.", "പാഠങ്ങൾ ഓർമ്മയിൽ നിർത്താൻ പഴഞ്ചൊല്ലുകൾ.", "pāṭhaṅṅaḷ ōrm'myil nirttān paḻañcollukaḷ."),
    ("Match the idiom’s tone: humorous or serious.", "പഴഞ്ചൊല്ലിന്റെ സ്വരം: ഹാസ്യമോ ഗൗരവമോ.", "paḻañcollinṟe svaraṁ: hāsyamō gauravamō."),
    ("Some idioms are shared across Indian languages.", "ഇന്ത്യൻ ഭാഷകൾ പങ്കിടുന്ന പഴഞ്ചൊല്ലുകൾ.", "intyan bhāṣakaḷ paṅṅkiṭunna paḻañcollukaḷ."),
    ("Avoid literal translation of colourful idioms.", "നിറമുള്ള പഴഞ്ചൊല്ലുകൾ നേരിട്ട് വിവർത്തനം ചെയ്യരുത്.", "niṛamuḷḷa paḻañcollukaḷ nēriṭṭ vivartanaṁ ceyyarut."),
    ("Practice: explain one idiom to a friend in Malayalam.", "ഒരു പഴഞ്ചൊല്ല് സുഹൃത്തിന് മലയാളത്തിൽ വിശദീകരിക്കുക.", "oru paḻañcoll suhr̥uttin malayāḷattil viśadīkarikkuka."),
    ("Collect idioms from Malayalam films and songs.", "സിനിമകളിലും പാട്ടുകളിലും നിന്ന് പഴഞ്ചൊല്ലുകൾ.", "sinimakaḷiluṁ pāṭṭukaḷiluṁ ninna paḻañcollukaḷ."),
    ("Respect regional variants of the same saying.", "ഒരേ ചൊല്ല് പ്രാദേശിക വ്യത്യാസങ്ങളോടെ.", "ore coll prādēśika vyatāsangoṭe."),
)

DATA595 = D(
    ("Too many cooks spoil the broth.", "അധിക അടുപ്പുകാർ കഞ്ഞി കുഴപ്പിക്കും.", "adhika aṭuppukār kaññi kuḻappikkuṁ."),
    ("Better late than never: start today.", "ഒരിക്കലും വൈകാതിരിക്കുന്നതിന് പകരം ഇന്ന് തുടങ്ങുക.", "orikkaluṁ vaikātirikkunatin pakaraṁ inn tuṭaṅṅuka."),
    ("Look before you leap.", "കുതിക്കും മുമ്പ് നോക്കുക.", "kutikkum mump nōkkuka."),
    ("Honesty is the best policy.", "നിഷ്കളങ്കത മികച്ച നയം.", "niṣkaḷaṅkata mikacca nayaṁ."),
    ("A friend in need is a friend indeed.", "ആപത്തില്‍ സഹായിക്കുന്നവന്‍ യഥാർത്ഥ സുഹൃത്ത്.", "āpatthil sahāyikkunnavan yathārththa suhr̥utt."),
    ("Necessity is the mother of invention.", "ആവശ്യം കണ്ടുപിടിത്തത്തിന്റെ അമ്മ.", "āvaśyaṁ kaṇṭipiṭittattinṟe amma."),
    ("Empty vessels make the most noise.", "കാലി പാത്രങ്ങൾ കൂടുതൽ ശബ്ദമുണ്ടാക്കും.", "kāli pātraṅṅaḷ kūtutal śabdamuṇṭākkuṁ."),
    ("Rome was not built in a day.", "ഒരു ദിവസം കൊണ്ട് റോം പണിതതല്ല.", "oru divasaṁ koṇṭ rōm paṇitatalla."),
    ("The pen is mightier than the sword.", "വാൾ എഴുത്തിനെക്കാൾ ബലം കുറഞ്ഞതാണ്.", "vāḷ eḻuttinekkāḷ balaṁ kuṛaññatāṇ."),
    ("Malayalam films popularise new idiomatic lines.", "പുതിയ പഴഞ്ചൊല്ലുകൾ സിനിമകൾ പ്രചരിപ്പിക്കുന്നു.", "putiya paḻañcollukaḷ sinimakaḷ pracarippikkunnu."),
    ("\"manassilāyō?\" checks understanding like \"got it?\".", "മനസ്സിലാക്കൽ “മനസ്സിലായോ?”.", "manassilākkaṁ “manassilāyō?”."),
    ("\"pōyikkō\" sends someone off casually.", "യാത്ര “പോയിക്കോ”.", "yātra “pōyikkō”."),
    ("\"onnu mati\" can mean enough or only one.", "പരിമിതി “ഒന്ന് മതി”.", "parimiti “onnu mati”."),
    ("Share idioms carefully across formal and informal speech.", "ഔപചാരികയും അനൗപചാരികയും തിരഞ്ഞെടുക്കുക.", "aupacārikayuṁ anaupacārikayuṁ tiraññeṭukkuka."),
    ("Some English idioms map loosely to Malayalam.", "ഇംഗ്ലീഷ് പഴഞ്ചൊല്ലുകൾ മലയാളത്തിൽ അർത്ഥസമാനം.", "iṅglīṣ paḻañcollukaḷ malayāḷattil artthasamānaṁ."),
    ("Children learn idioms faster through stories.", "കഥകളിലൂടെ പഴഞ്ചൊല്ലുകൾ വേഗം പഠിക്കും.", "kathakaḷilūṭe paḻañcollukaḷ vēgaṁ paṭhikkuṁ."),
    ("Write your favourite idiom and its Malayalam equivalent.", "ഇഷ്ടപ്പെട്ട പഴഞ്ചൊല്ലും മലയാള സമാനവും എഴുതുക.", "iṣṭappeṭṭa paḻañcolluṁ malayāḷa samānavuṁ eḻutuka."),
    ("Discuss how idioms reflect Kerala’s culture.", "കേരള സംസ്കാരം പഴഞ്ചൊല്ലുകളിൽ പ്രതിഫലിക്കുന്നു.", "kēraḷa saṁskāraṁ paḻañcollukaḷil pratiphalikkuṁ."),
)

DATA596 = D(
    ("If you heat ice, it melts.", "മഞ്ഞ് ചൂടാക്കിയാൽ അത് ഉരുകും.", "maññ cūṭākkiāl at urukuṁ."),
    ("If the bus is late, we will take a taxi.", "ബസ് വൈകിയാൽ ടാക്സി എടുക്കും.", "bas vaikyāl ṭāksi eṭukkuṁ."),
    ("If I had known, I would have come earlier.", "അറിഞ്ഞിരുന്നെങ്കിൽ നേരത്തെ വന്നേക്കുമായിരുന്നു.", "aṟiññirunneṅkil nērattē vannekkumāyirunnu."),
    ("If it does not rain, the crops may fail.", "മഴ പെയ്തില്ലെങ്കിൽ വിള നഷ്ടമാകാം.", "maḻa peytilleṅkiḷ viḷa naṣṭamākkāṁ."),
    ("If you practise daily, you will improve.", "ദിവസവും പരിശീലിച്ചാൽ മെച്ചപ്പെടും.", "divasavuṁ pariśīliccā meccappeṭuṁ."),
    ("If they invite us, we will attend the function.", "ക്ഷണിച്ചാൽ ഞങ്ങൾ അനുഷ്ഠാനത്തിൽ പങ്കെടുക്കും.", "kṣaṇiccā ñaṅṅaḷ anuṣṭhānattil paṅṅkeṭukkuṁ."),
    ("If you feel unwell, see a doctor.", "സുഖമില്ലെങ്കിൽ ഡോക്ടറെ കാണുക.", "sukhamilleṅkiḷ ḍōkṭṭare kāṇuka."),
    ("If the shop is closed, come back tomorrow.", "കട അടഞ്ഞാൽ നാളെ വന്നുകൊള്ളുക.", "kaṭa aṭaññāl nāḷe vannukoḷḷuka."),
    ("Style 2 uses \"eṅkil\" in the main clause too.", "“എങ്കിൽ” പ്രധാന വാക്യത്തിലും.", "“eṅkil” pradhāna vākyattiluṁ."),
    ("\"āyirunneṅkil\" builds unreal past conditions.", "കഴിഞ്ഞ കാല സാധ്യത “ആയിരുന്നെങ്കിൽ”.", "kaḻiñña kāla sādhyata “āyirunneṅkil”."),
    ("If you miss the turn, take the next road.", "തിരിഞ്ഞത് നഷ്ടപ്പെട്ടാൽ അടുത്ത റോഡ് എടുക്കുക.", "tiriññat naṣṭappeṭṭāl aṭutta rōḷ eṭukkuka."),
    ("If electricity fails, use the torch.", "കറന്റ് പോയാൽ ടോർച്ച് ഉപയോഗിക്കുക.", "karaṇṭ pōyāl ṭōrcc upayōgikkuka."),
    ("If guests arrive early, offer them water.", "അതിഥികൾ നേരത്തെ എത്തിയാൽ വെള്ളം നൽകുക.", "atithikaḷ nērattē ettiyā veḷḷaṁ nalkuka."),
    ("If the ticket is cheaper online, book there.", "ഓൺലൈനിൽ വില കുറഞ്ഞാൽ അവിടെ ബുക്ക് ചെയ്യുക.", "ōnlainil vila kuṛaññā aviṭe bukk ceyyuka."),
    ("If you agree, sign on the last page.", "സമ്മതമാണെങ്കിൽ അവസാന പേജിൽ ഒപ്പിടുക.", "sam'matamāṇeṅkil avasāna pējil oppiṭuka."),
    ("If nothing works, ask the help desk.", "ഒന്നും ഫലിക്കാതെ പോയാൽ ഹെൽപ് ഡെസ്ക് ചോദിക്കുക.", "onnuṁ phalikkhāte pōyāl help desk cōdikkuka."),
    ("Practice mixing \"āṇenkiḷ\" and \"āyāl\" in speech.", "സംസാരത്തിൽ “ആണെങ്കിൽ”, “ആയാൽ” കലർത്തുക.", "saṁsāraṭṭil “āṇeṅkil”, “āyāl” kalarttuka."),
    ("Formal Malayalam may front the condition clause.", "ഔപചാരികത്തിൽ ഉപാധി വാക്യം മുമ്പിൽ.", "aupacārikattil upādhi vākyaṁ mumpil."),
)
