# -*- coding: utf-8 -*-
"""(English, Malayalam, transliteration) tuples for chapters 518–590. Part 2 in malayalam_remainder_data2.py"""
from malayalam_lesson_content import R, _pad


def D(*triples):
    return _pad([R(e, m, r) for e, m, r in triples], n=20)


# 518 Simple Past – verbs without object
DATA518 = D(
    ("I went to the temple yesterday.", "ഞാൻ ഇന്നലെ ക്ഷേത്രത്തിലേക്ക് പോയി.", "njān innale kṣētrattilēkk pōyi."),
    ("She slept early last night.", "അവൾ ഇന്നലെ രാത്രി നേരത്തെ ഉറങ്ങി.", "avaḷ innale rātri nērattē uṟaṅṅi."),
    ("We walked along the beach at dawn.", "ഞങ്ങൾ പ്രഭാതത്തിൽ കടൽ തീരത്ത് നടന്നു.", "ñaṅṅaḷ prabhātattil kaḍal tīratt naṭannu."),
    ("He ran to catch the bus.", "അവൻ ബസ് പിടിക്കാൻ ഓടി.", "avan bas piṭikkān ōṭi."),
    ("They arrived before noon.", "അവർ ഉച്ചയ്ക്ക് മുമ്പ് എത്തി.", "avar uccaykku mumpe etti."),
    ("I wrote a letter to my uncle.", "ഞാൻ അമ്മാവന് കത്ത് എഴുതി.", "njān ammāvan katt eḻuti."),
    ("The bird flew away when we approached.", "ഞങ്ങൾ അടുത്തപ്പോൾ പക്ഷി പറന്നുപോയി.", "ñaṅṅaḷ aṭuttappōḷ pakṣi paṟannupōyi."),
    ("We laughed a lot during the comedy show.", "കോമഡി ഷോയിൽ ഞങ്ങൾ നന്നായി ചിരിച്ചു.", "kōmaḍi śōyil ñaṅṅaḷ nannāyi ciriccu."),
    ("He coughed all night because of the cold.", "തണുപ്പുകൊണ്ട് അവൻ രാത്രി മുഴുവൻ ഇക്കിളി ചെയ്തു.", "taṇuppukoṇṭ avan rātri muḻuvan ikkili ceytu."),
    ("I studied Malayalam for two hours.", "ഞാൻ രണ്ടു മണിക്കൂർ മലയാളം പഠിച്ചു.", "njān raṇṭu maṇikkūr malayāḷaṁ paṭhiccu."),
    ("She danced beautifully on stage.", "അവൾ വേദിയിൽ മനോഹരമായി നൃത്തം ചെയ്തു.", "avaḷ vēdiyil manōharamāyi nr̥ttaṁ ceytu."),
    ("We prayed silently before the lamp.", "ഞങ്ങൾ വിളക്കിന് മുമ്പ് നിശബ്ദമായി പ്രാർത്ഥിച്ചു.", "ñaṅṅaḷ viḷakkin mumpe niśabdamāyi prārththiccu."),
    ("The dog barked when strangers passed.", "അപരിചിതർ കടന്നുപോകുമ്പോൾ നായ കുരച്ചു.", "aparicitar kaṭannupōkumbōḷ nāya kuraccu."),
    ("I drank warm water after yoga.", "യോഗയ്ക്ക് ശേഷം ഞാൻ ചൂടുവെള്ളം കുടിച്ചു.", "yōgaykku śeṣaṁ njān cūṭaveḷḷaṁ kuṭiccu."),
    ("He fell down but was not hurt.", "അവൻ വീണു പക്ഷേ പരിക്കേണ്ടിവന്നില്ല.", "avan vīṇu pakṣe parikkēṇṭivannilla."),
    ("We listened to the radio news.", "ഞങ്ങൾ റേഡിയോ വാർത്ത കേട്ടു.", "ñaṅṅaḷ rēḍiyō vārttha kēṭṭu."),
    ("The bell rang when class ended.", "ക്ലാസ് അവസാനിച്ചപ്പോൾ മണി മുഴങ്ങി.", "klās avasāniccappōḷ maṇi muḻaṅṅi."),
    ("I forgot the umbrella at the shop.", "ഞാൻ കടയിൽ കുട മറന്നു.", "njān kaṭayil kuṭa maṟannu."),
    ("The dog ran in and the cat ran out.", "നായ അകത്തേക്ക് ഓടി; പൂച്ച പുറത്തേക്ക് ഓടി.", "nāya akattēkk ōṭi; pūcca puṟattēkk ōṭi."),
    ("We sat in the shade and talked for an hour.", "ഞങ്ങൾ നിഴലിൽ ഇരുന്ന് ഒരു മണിക്കൂർ സംസാരിച്ചു.", "ñaṅṅaḷ niḻalil irunn oru maṇikkūr saṁsāriccu."),
)

# 519 Simple Past – with object
DATA519 = D(
    ("I ate the rice mother had kept for me.", "അമ്മ എനിക്ക് വെച്ചിരുന്ന ചോറ് ഞാൻ കഴിച്ചു.", "amma enikk veccirunna cōṟ njān kaḻiccu."),
    ("She read the novel in one week.", "അവൾ നോവൽ ഒരാഴ്ചക്കുള്ളിൽ വായിച്ചു.", "avaḷ nōval orāḻccakkuḷḷil vāyiccu."),
    ("We bought vegetables from the market.", "ഞങ്ങൾ ചന്തയിൽ പച്ചക്കറികൾ വാങ്ങി.", "ñaṅṅaḷ chantayil paccakaṛikaḷ vāṅṅi."),
    ("He opened the window to let fresh air in.", "പുതിയ കാറ്റ് വരാൻ അവൻ ജനൽ തുറന്നു.", "putiya kāṭṭ varān avan janal tuṟannu."),
    ("They watched the match on television.", "അവർ ടെലിവിഷനിൽ മത്സരം കണ്ടു.", "avar ṭeliviṣanil matsaraṁ kaṇṭu."),
    ("I cleaned the room before the guests came.", "അതിഥികൾ വരുന്നതിന് മുമ്പ് ഞാൻ മുറി വൃത്തിയാക്കി.", "atithikaḷ varunnatin mumpe njān muṛi vr̥ttiyākki."),
    ("She closed the door quietly.", "അവൾ വാതിൽ നിശബ്ദമായി അടച്ചു.", "avaḷ vātil niśabdamāyi aṭaccu."),
    ("We planted ten saplings in the school compound.", "ഞങ്ങൾ സ്കൂൾ മുറ്റത്ത് പത്തു തൈകൾ നട്ടു.", "ñaṅṅaḷ skūḷ muṟṭatt pathu taikaḷ naṭṭu."),
    ("He answered every question in the exam.", "പരീക്ഷയിലെ എല്ലാ ചോദ്യങ്ങൾക്കും അവൻ ഉത്തരം നൽകി.", "parīkṣayile ellā cōdhyaṅṅaḷkkuṁ avan uttaraṁ nalki."),
    ("I sent the document by email.", "ഞാൻ രേഖാപത്രം ഇമെയിലായി അയച്ചു.", "njān rēkhāpatraṁ imeyilāyi ayaccu."),
    ("Mother packed lunch in a steel box.", "അമ്മ ഉച്ചഭക്ഷണം സ്റ്റീൽ പെട്ടിയിൽ പാക്ക് ചെയ്തു.", "amma uccabhakṣaṇaṁ sṟṭīl peṭṭiyil pāk ceytu."),
    ("The cat drank the milk from the bowl.", "പൂച്ച പാത്രത്തിലെ പാൽ കുടിച്ചു.", "pūcca pātrattile pāl kuṭiccu."),
    ("We heard the thunder during the storm.", "കാറ്റും മഴയും ഉള്ളപ്പോൾ ഞങ്ങൾ ഇടി കേട്ടു.", "kāṭṭuṁ maḻayuṁ uḷḷappōḷ ñaṅṅaḷ iṭi kēṭṭu."),
    ("I chose the blue shirt for the function.", "അനുഷ്ഠാനത്തിന് ഞാൻ നീല ഷർട്ട് തിരഞ്ഞെടുത്തു.", "anuṣṭhānattin njān nīl śarṭṭ tiraññeṭuttu."),
    ("She taught the children a folk song.", "അവൾ കുട്ടികൾക്ക് നാടൻ പാട്ട് പഠിപ്പിച്ചു.", "avaḷ kuṭṭikaḷkku nāṭan pāṭṭ paṭhippiccu."),
    ("We paid the bill at the counter.", "ഞങ്ങൾ കൗണ്ടറിൽ ബിൽ അടച്ചു.", "ñaṅṅaḷ kauṇṭaril bil aṭaccu."),
    ("He repaired the leaking tap.", "അവൻ ചോരുന്ന ടാപ്പ് നന്നാക്കി.", "avan cōrunna ṭāpp nannākki."),
    ("I remembered your advice during the meeting.", "മീറ്റിംഗിൽ നിങ്ങളുടെ ഉപദേശം ഞാൻ ഓർമ്മിച്ചു.", "mīṭiṅgil niṅṅaḷuṭe upadēśaṁ njān ōrmiccu."),
    ("She posted the letter and paid the fee.", "അവൾ കത്ത് പോസ്റ്റ് ചെയ്ത് ഫീസ് അടച്ചു.", "avaḷ katt pōsṭ ceytu phīs aṭaccu."),
    ("We chose the best mango from the basket.", "ഞങ്ങൾ കൊട്ടയിൽ നിന്ന് മികച്ച മാങ്ങ തിരഞ്ഞെടുത്തു.", "ñaṅṅaḷ koṭṭayil ninn mikacca māṅṅa tiraññeṭuttu."),
)

# 520 Past tense of "to be"
DATA520 = D(
    ("I was at home when you called.", "നിങ്ങൾ വിളിച്ചപ്പോൾ ഞാൻ വീട്ടിലായിരുന്നു.", "niṅṅaḷ viḷiccappōḷ njān vīṭṭilāyirunnu."),
    ("She was a nurse before she moved here.", "ഇവിടെ വരുന്നതിന് മുമ്പ് അവൾ നഴ്സായിരുന്നു.", "ivide varunnatin mumpe avaḷ narssāyirunnu."),
    ("We were tired after the long journey.", "ദീർഘമായ യാത്രക്ക് ശേഷം ഞങ്ങൾ ക്ഷീണിതരായിരുന്നു.", "dīrghamāya yātrakk śeṣaṁ ñaṅṅaḷ kṣīṇitarāyirunnu."),
    ("They were happy with the exam results.", "പരീക്ഷാഫലത്തിൽ അവർ സന്തോഷവാന്മാരായിരുന്നു.", "parīkṣāphalattil avar saṁtōṣavānmārāyirunnu."),
    ("It was raining when we left.", "ഞങ്ങൾ പുറപ്പെട്ടപ്പോൾ മഴ പെയ്യുകയായിരുന്നു.", "ñaṅṅaḷ puṛappeṭṭappōḷ maḻa peyyukayāyirunnu."),
    ("The hall was full during the speech.", "പ്രസംഗ സമയത്ത് ഹാൾ നിറഞ്ഞിരുന്നു.", "prasaṁga samayatt hāḷ niṟaññirunnu."),
    ("I was not aware of the rule change.", "നിയമം മാറിയ വിവരം എനിക്ക് അറിയില്ലായിരുന്നു.", "niyamaṁ māṟiya vivaraṁ enikk aṟiyillāyirunnu."),
    ("He was absent because of fever.", "ജ്വരം കൊണ്ട് അവൻ അവധിയിലായിരുന്നു.", "jvaraṁ koṇṭ avan avadhiyilāyirunnu."),
    ("We were classmates in school.", "ഞങ്ങൾ സ്കൂളിൽ ഒരേ ക്ലാസുകാരായിരുന്നു.", "ñaṅṅaḷ skūlil orē klāsukārāyirunnu."),
    ("The keys were on the table.", "ചാവികൾ മേശയ്ക്ക് മുകളിലായിരുന്നു.", "cāvikaḷ mēśaykku mukaḷilāyirunnu."),
    ("The shop was closed on Sunday.", "ഞായറാഴ്ച കട അടച്ചിരുന്നു.", "ñāyaṟāḻcca kaṭa aṭaccirunnu."),
    ("I was learning Malayalam last year.", "കഴിഞ്ഞ വർഷം ഞാൻ മലയാളം പഠിച്ചുകൊണ്ടിരിക്കുകയായിരുന്നു.", "kaḻiñña varṣaṁ njān malayāḷaṁ paṭhiccukoṇṭirikkukayāyirunnu."),
    ("She was reading when the power went off.", "കറന്റ് പോയപ്പോൾ അവൾ വായിക്കുകയായിരുന്നു.", "karanṭ pōyappōḷ avaḷ vāyikkukayāyirunnu."),
    ("The children were playing in the rain.", "കുട്ടികൾ മഴയിൽ കളിക്കുകയായിരുന്നു.", "kuṭṭikaḷ maḻayil kaḷikkukayāyirunnu."),
    ("We were lucky to get tickets.", "ടിക്കറ്റ് കിട്ടിയത് ഞങ്ങൾ ഭാഗ്യവാന്മാരായിരുന്നു.", "ṭikkaṭṭ kiṭṭiyat ñaṅṅaḷ bhāgyavānmārāyirunnu."),
    ("He was the first to reach the summit.", "ശിഖരത്തിൽ എത്തിയ ആദ്യ വ്യക്തി അവനായിരുന്നു.", "śikharattil ettiya ādya vyakti avanāyirunnu."),
    ("The roads were slippery after the drizzle.", "തൂറൽ മഴയ്ക്ക് ശേഷം റോഡുകൾ വഴുതലായിരുന്നു.", "tūṟal maḻaykku śeṣaṁ rōṭukaḷ vaḻutalāyirunnu."),
    ("I was grateful for your patience.", "നിങ്ങളുടെ ക്ഷമയ്ക്ക് ഞാൻ നന്ദിയുള്ളവനായിരുന്നു.", "niṅṅaḷuṭe kṣamaykku njān nandiyuḷḷavanāyirunnu."),
    ("The sky was clear before the storm.", "കൊടുങ്കാറ്റിന് മുമ്പ് ആകാശം വ്യക്തമായിരുന്നു.", "koṭuṅkāṟṟin mump ākāśaṁ vyaktamāyirunnu."),
    ("They were strangers then; now they are close friends.", "അന്ന് അവർ അപരിചിതരായിരുന്നു; ഇപ്പോൾ അടുത്ത സുഹൃത്തുക്കൾ.", "annu avar aparicitarāyirunnu; ippōḷ aṭutta suhr̥uttukkaḷ."),
)

DATA521 = D(
    ("She went home before me.", "അവൾ എനിക്ക് മുമ്പ് വീട്ടിൽ പോയി.", "avaḷ enikk mump vīṭṭil pōyi."),
    ("He came early.", "അവൻ നേരത്തെ വന്നു.", "avan nērattē vannu."),
    ("I saw your brother.", "ഞാൻ നിന്റെ സഹോദരനെ കണ്ടു.", "njān ninṟe sahōdarane kaṇṭu."),
    ("Mother gave me fruit.", "അമ്മ എനിക്ക് പഴം തന്നു.", "amma enikk paḻaṁ tannu."),
    ("We did the work together.", "ഞങ്ങൾ ഒരുമിച്ച് ജോലി ചെയ്തു.", "ñaṅṅaḷ orumicc jōli ceytu."),
    ("She said she would come.", "അവൾ വരാമെന്ന് പറഞ്ഞു.", "avaḷ varāmenn paṟaññu."),
    ("They ate at our house.", "അവർ ഞങ്ങളുടെ വീട്ടിൽ ചോറ് കഴിച്ചു.", "avar ñaṅṅaḷuṭe vīṭṭil cōṟ kaḻiccu."),
    ("I drank two cups of tea.", "ഞാൻ രണ്ടു കപ്പ് ചായ കുടിച്ചു.", "njān raṇṭu kapp cāya kuṭiccu."),
    ("He wrote a long letter.", "അവൻ നീണ്ട കത്ത് എഴുതി.", "avan nīṇṭa katt eḻuti."),
    ("We read the notice carefully.", "ഞങ്ങൾ അറിയിപ്പ് ശ്രദ്ധിച്ച് വായിച്ചു.", "ñaṅṅaḷ aṟiyipp śraddhicc vāyiccu."),
    ("She walked to the bus stop.", "അവൾ സ്റ്റോപ്പിലേക്ക് നടന്നു.", "avaḷ sṟṟōppilēkk naṭannu."),
    ("The children ran to the field.", "കുട്ടികൾ വയലിലേക്ക് ഓടി.", "kuṭṭikaḷ vayalilēkk ōṭi."),
    ("I heard your name on the radio.", "റേഡിയോയിൽ നിന്റെ പേര് ഞാൻ കേട്ടു.", "rēḍiyōyil ninṟe pēr njān kēṭṭu."),
    ("I heard the announcement clearly.", "അറിയിപ്പ് വ്യക്തമായി ഞാൻ കേട്ടു.", "aṟiyipp vyaktamāyi njān kēṭṭu."),
    ("She put sugar in the tea.", "അവൾ ചായയിൽ പഞ്ചസാര ഇട്ടു.", "avaḷ cāyayil pañcasāra iṭṭu."),
    ("He gave money to the driver.", "അവൻ ഡ്രൈവർക്ക് പണം കൊടുത്തു.", "avan ḍraivarikku paṇaṁ koṭuttu."),
    ("It became dark outside.", "ഇരുട്ടായി.", "iruṭṭāyi."),
    ("Many past verbs do not match the present form.", "എല്ലാ ക്രിയകൾക്കും “ന്നു” മാത്രം ചേർക്കുന്നില്ല.", "ellā kriyakaḷkkuṁ “nnu” mātraṁ cērkkunnilla."),
    ("He went and I came on the same road.", "അവൻ പോയ വഴിയിൽ ഞാൻ വന്നു.", "avan pōya vazhiyil njān vannu."),
    ("I looked up more past forms in the textbook.", "പാഠപുസ്തകത്തിലെ പട്ടികയിൽ കൂടുതൽ ഭൂതരൂപങ്ങൾ കാണാം.", "pāṭhapustakattile paṭṭikayil kūtutal bhūtarūpaṅṅaḷ kāṇāṁ."),
)

DATA522 = D(
    ("At eight I was still having breakfast.", "എട്ടുമണിക്ക് ഞാൻ ഇനിയും പ്രാതൽ കഴിക്കുകയായിരുന്നു.", "eṭṭumaṇik njān iniyuṁ prātal kaḻikkukayāyirunnu."),
    ("She was typing when the power failed.", "കറന്റ് പോയപ്പോൾ അവൾ ടൈപ്പ് ചെയ്യുകയായിരുന്നു.", "karanṭ pōyappōḷ avaḷ ṭaipp ceyyukayāyirunnu."),
    ("We were walking when it started to rain.", "മഴ തുടങ്ങിയപ്പോൾ ഞങ്ങൾ നടക്കുകയായിരുന്നു.", "maḻa tuṭaṅṅiyappōḷ ñaṅṅaḷ naṭakkukayāyirunnu."),
    ("They were arguing loudly in the corridor.", "കോറിഡോറിൽ അവർ ഉച്ചത്തിൽ തർക്കിക്കുകയായിരുന്നു.", "kōriḍōril avar uccattil tarkkikkukayāyirunnu."),
    ("I was thinking about the exam all morning.", "മുഴുവൻ പ്രഭാതവും ഞാൻ പരീക്ഷയെക്കുറിച്ച് ചിന്തിക്കുകയായിരുന്നു.", "muḻuvan prabhātavuṁ njān parīkṣayekkuṛicc cintikkukayāyirunnu."),
    ("The musicians were tuning their instruments.", "സംഗീതജ്ഞർ ഉപകരണങ്ങൾ ക്രമീകരിക്കുകയായിരുന്നു.", "saṁgītajñar upakaraṇaṅṅaḷ kramīkarikkukayāyirunnu."),
    ("The baby was crying because she was hungry.", "കുഞ്ഞിന് വിശപ്പുണ്ടായിരുന്നതിനാൽ അവൾ കരയുകയായിരുന്നു.", "kuññin viśappuṇṭāyirunnatināl avaḷ karayukayāyirunnu."),
    ("We were waiting for the ferry at the jetty.", "ജെട്ടിയിൽ ഫെറി കാത്തിരിക്കുകയായിരുന്നു ഞങ്ങൾ.", "jeṭṭiyil feri kāttirikkukayāyirunnu ñaṅṅaḷ."),
    ("He was driving carefully through the fog.", "മൂടൽമഞ്ഞിൽ അവൻ ശ്രദ്ധയോടെ വാഹനമോടിക്കുകയായിരുന്നു.", "mūṭalmaññil avan śraddhayōṭe vāhanamōṭikkukayāyirunnu."),
    ("The crowd was cheering when the goal came.", "ഗോൾ വന്നപ്പോൾ കൂട്ടം ആർപ്പുവിളിക്കുകയായിരുന്നു.", "gōl vannappōḷ kūṭṭaṁ ārppuviḷikkukayāyirunnu."),
    ("I was not listening because I was tired.", "ക്ഷീണം കൊണ്ട് ഞാൻ ശ്രദ്ധിക്കുകയായിരുന്നില്ല.", "kṣīṇaṁ koṇṭ njān śraddhikkukayāyirunnilla."),
    ("She was painting the wall light green.", "ചുവര് വെളുപ്പും പച്ചയും കലർന്ന് അവൾ വർണ്ണിക്കുകയായിരുന്നു.", "cuvar veḷuppuṁ pacayuṁ kalarnnu avaḷ varṇṇikkukayāyirunnu."),
    ("The teachers were correcting answer papers.", "അധ്യാപകർ ഉത്തരക്കടലാസുകൾ തിരുത്തുകയായിരുന്നു.", "adhyāpakar uttarakaṭalāsukaḷ tiruttukayāyirunnu."),
    ("We were hoping for good news from the hospital.", "ആശുപത്രിയിൽ നിന്ന് നല്ല വാർത്ത പ്രതീക്ഷിക്കുകയായിരുന്നു ഞങ്ങൾ.", "āśupatriyil ninn nalla vārttha pratīkṣikkukayāyirunnu ñaṅṅaḷ."),
    ("The wind was shaking the coconut palms.", "കാറ്റ് തെങ്ങുകൾ കുലുക്കുകയായിരുന്നു.", "kāṭṭ teṅṅukaḷ kulukkukayāyirunnu."),
    ("I was chatting with neighbours on the porch.", "മുറ്റത്ത് അയൽക്കാരുമായി ഞാൻ സംസാരിക്കുകയായിരുന്നു.", "muṟṭatt ayalkkārumāyi njān saṁsārikkukayāyirunnu."),
    ("They were loading sacks onto the truck.", "ലോറിയിൽ ചാക്കുകൾ കയറ്റുകയായിരുന്നു അവർ.", "lōriyil cākkuḷ kayṟukayāyirunnu avar."),
    ("The kettle was whistling in the kitchen.", "അടുപ്പിൽ കേറ്റിൽ ചൂടുകൊണ്ട് വിളിക്കുകയായിരുന്നു.", "aṭuppil kēṭṭil cūṭṭukoṇṭ viḷikkukayāyirunnu."),
)

DATA523 = D(
    ("I have finished my homework.", "ഞാൻ ഹോംവർക്ക് പൂർത്തിയാക്കിയിരിക്കുന്നു.", "njān hōmvarkk pūrttiyākkirikkunnu."),
    ("She has lived in Kerala for ten years.", "അവൾ പത്തു വർഷമായി കേരളത്തിൽ താമസിക്കുകയാണ്.", "avaḷ pathu varṣamāyi kēraḷattil tāmasikkukayāṇ."),
    ("We have never seen such a flood.", "ഇതുപോലുള്ള വെള്ളപ്പൊക്കം ഞങ്ങൾ കണ്ടിട്ടില്ല.", "itupōluḷḷa veḷḷappokkaṁ ñaṅṅaḷ kaṇṭiṭṭilla."),
    ("He has already submitted the form.", "അവൻ ഫോം ഇതിനകം സമർപ്പിച്ചു കഴിഞ്ഞു.", "avan phōm itinakaṁ samarpiccu kaḻiññu."),
    ("They have built a new house near the river.", "അവർ നദിക്കരികിൽ പുതിയ വീട് പണിതിരിക്കുന്നു.", "avar nadikkrikil putiya vīṭ paṇitirikkunnu."),
    ("I have lost my umbrella somewhere.", "എവിടെയോ എന്റെ കുട നഷ്ടപ്പെട്ടിരിക്കുന്നു.", "evideyō enṟe kuṭa naṣṭappeṭṭirikkunnu."),
    ("She has read all the books in this series.", "ഈ ശ്രേണിയിലെ എല്ലാ പുസ്തകങ്ങളും അവൾ വായിച്ചിരിക്കുന്നു.", "ī śrēṇiyile ellā pustakaṅṅaḷuṁ avaḷ vāyiccirikkunnu."),
    ("We have invited everyone for the wedding.", "വിവാഹത്തിന് ഞങ്ങൾ എല്ലാവരെയും ക്ഷണിച്ചിരിക്കുന്നു.", "vivāhattin ñaṅṅaḷ ellāvareyuṁ kṣaṇiccirikkunnu."),
    ("He has forgotten to lock the door.", "വാതിൽ പൂട്ടാൻ അവൻ മറന്നിരിക്കുന്നു.", "vātil pūṭṭān avan maṟannirikkunnu."),
    ("The committee has announced the results.", "കമ്മിറ്റി ഫലം പ്രഖ്യാപിച്ചിരിക്കുന്നു.", "kammiṭṭi phalaṁ prakhyāpiccirikkunnu."),
    ("I have paid the electricity bill online.", "വൈദ്യുതി ബിൽ ഞാൻ ഓൺലൈനിൽ അടച്ചിരിക്കുന്നു.", "vaidyuti bil njān ōṇlainil aṭaccirikkunnu."),
    ("She has cooked enough food for everyone.", "എല്ലാവർക്കും മതിയായ ഭക്ഷണം അവൾ ഉണ്ടാക്കിയിരിക്കുന്നു.", "ellāvarkkuṁ matiyāya bhakṣaṇaṁ avaḷ uṇṭākkirikkunnu."),
    ("We have seen that movie twice.", "ആ സിനിമ ഞങ്ങൾ രണ്ടു പ്രാവശ്യം കണ്ടിരിക്കുന്നു.", "ā sinima ñaṅṅaḷ raṇṭu prāvaśyaṁ kaṇṭirikkunnu."),
    ("The garden has grown lush after the rain.", "മഴയ്ക്ക് ശേഷം തോട്ടം സമൃദ്ധമായി വളർന്നിരിക്കുന്നു.", "maḻaykku śeṣaṁ tōṭṭaṁ samr̥ddhamāyi vaḷarnnirikkunnu."),
    ("I have promised to help them tomorrow.", "നാളെ അവരെ സഹായിക്കാമെന്ന് ഞാൻ വാഗ്ദാനം ചെയ്തിരിക്കുന്നു.", "nāḷe avare sahāyikkāmennu njān vāgdānaṁ ceytirikkunnu."),
    ("He has travelled to many countries.", "അവൻ പല രാജ്യങ്ങളും സഞ്ചരിച്ചിരിക്കുന്നു.", "avan pala rājyaṅṅaḷuṁ sañcariccirikkunnu."),
    ("We have saved money for our daughter’s education.", "മകളുടെ വിദ്യാഭ്യാസത്തിന് ഞങ്ങൾ പണം സംരക്ഷിച്ചിരിക്കുന്നു.", "makuḷuṭe vidyābhyāsattin ñaṅṅaḷ paṇaṁ saṁrakṣiccirikkunnu."),
    ("The phone has rung three times already.", "ഫോൺ ഇതിനകം മൂന്നു പ്രാവശ്യം മുഴങ്ങിയിരിക്കുന്നു.", "phōn itinakaṁ mūnnu prāvaśyaṁ muḻaṅṅiyirikkunnu."),
)

DATA524 = D(
    ("The book is on the table.", "പുസ്തകം മേശയ്ക്ക് മുകളിലാണ്.", "pustakaṁ mēśaykku mukaḷilāṇ."),
    ("We walked through the paddy field.", "ഞങ്ങൾ നെൽവയലിലൂടെ നടന്നു.", "ñaṅṅaḷ nelvayalilūṭe naṭannu."),
    ("She sat beside her grandmother.", "അവൾ മുത്തശ്ശിക്ക് അടുത്തിരുന്നു.", "avaḷ muttaśśikk aṭuttirunnu."),
    ("The cat hid under the bed.", "പൂച്ച കട്ടിലിന് ചുവട്ടിൽ ഒളിച്ചു.", "pūcca kaṭṭilin cuvaṭṭil oḷiccu."),
    ("He waited in front of the shop.", "അവൻ കടയുടെ മുമ്പിൽ കാത്തിരുന്നു.", "avan kaṭayuṭe mumpil kāttirunnu."),
    ("Birds flew over the lake.", "തടാകത്തിന് മുകളിലൂടെ പക്ഷികൾ പറന്നു.", "taṭākattin mukaḷilūṭe pakṣikaḷ paṟannu."),
    ("I put the keys inside the drawer.", "ചാവി അലമാരിയുടെ അകത്ത് വെച്ചു.", "cāvi alamāriyuṭe akatt veccu."),
    ("We drove along the coastal road.", "ഞങ്ങൾ തീരപാതയിലൂടെ വാഹനമോടിച്ചു.", "ñaṅṅaḷ tīrapātayilūṭe vāhanamōṭiccu."),
    ("The school is behind the temple.", "സ്കൂൾ ക്ഷേത്രത്തിന് പിന്നിലാണ്.", "skūḷ kṣētrattin piṉnilāṇ."),
    ("She jumped into the water.", "അവൾ വെള്ളത്തിലേക്ക് ചാടി.", "avaḷ veḷḷattilēkk cāṭi."),
    ("Children ran around the playground.", "കുട്ടികൾ കളിക്കളത്തിന് ചുറ്റും ഓടി.", "kuṭṭikaḷ kaḷikkaḷattin cuṟṟuṁ ōṭi."),
    ("The picture hangs above the sofa.", "ചിത്രം സോഫയ്ക്ക് മുകളിലാണ് തൂങ്ങിക്കിടക്കുന്നത്.", "citraṁ sōphaykku mukaḷilāṇ tūṅṅikkikaṭakkunnat."),
    ("I stood between two tall trees.", "എന്നെ രണ്ടു ഉയരമുള്ള മരങ്ങൾക്കിടയിൽ നിർത്തി.", "enne raṇṭu uyaramuḷḷa maraṅṅaḷkkiṭayil nirtti."),
    ("We rested under the bridge for a while.", "കുറച്ചുനേരം പാലത്തിന് ചുവട്ടിൽ ഞങ്ങൾ വിശ്രമിച്ചു.", "kureśśanēraṁ pālattin cuvaṭṭil ñaṅṅaḷ viśramiccu."),
    ("The shop is near the bus stand.", "കട ബസ് സ്റ്റാൻഡിന് അടുത്താണ്.", "kaṭa bas sṟṟāṇṭin aṭuttāṇ."),
    ("He walked toward the station.", "അവൻ സ്റ്റേഷൻ ലക്ഷ്യമാക്കി നടന്നു.", "avan sṟṟēṣaṇ lakṣyamākki naṭannu."),
    ("The letter fell from my hand.", "എന്റെ കൈയിൽ നിന്ന് കത്ത് വീണു.", "enṟe kaiyil ninn katt vīṇu."),
    ("We picnicked by the riverside.", "ഞങ്ങൾ നദീതീരത്ത് പിക്കനിക് നടത്തി.", "ñaṅṅaḷ nadītīratt pikkanik naṭatti."),
)

DATA525 = D(
    ("I am going to the market.", "ഞാൻ ചന്തയിലേക്ക് പോകുന്നു.", "njān chantayilēkk pōkunnu."),
    ("She gave the book to her brother.", "അവൾ പുസ്തകം സഹോദരന് നൽകി.", "avaḷ pustakaṁ sahōdaran nalki."),
    ("We explained the matter to the officer.", "ഞങ്ങൾ ഉദ്യോഗസ്ഥന് കാര്യം വിശദീകരിച്ചു.", "ñaṅṅaḷ udyōgasthann kāryaṁ viśadīkariccu."),
    ("He lied to his parents.", "അവൻ മാതാപിതാക്കളോട് കള്ളം പറഞ്ഞു.", "avan mātāpitākkaḷōṭ kaḷḷaṁ paṟaññu."),
    ("Listen to this song carefully.", "ഈ പാട്ട് ശ്രദ്ധിച്ച് കേൾക്കുക.", "ī pāṭṭ śraddhicc kēḷkkuka."),
    ("I apologised to them sincerely.", "ഞാൻ അവർക്ക് സത്യസന്ധമായി മാപ്പ് പറഞ്ഞു.", "njān avarkk satyasandhamāyi māpp paṟaññu."),
    ("She waved to the children.", "അവൾ കുട്ടികളെ കൈകാണിച്ചു.", "avaḷ kuṭṭikaḷe kaikāṇiccu."),
    ("We donated money to the school.", "ഞങ്ങൾ സ്കൂളിന് പണം സംഭാവന ചെയ്തു.", "ñaṅṅaḷ skūlin paṇaṁ saṁbhāvana ceytu."),
    ("He shouted to the boatman.", "അവൻ തോണിക്കാരനെ വിളിച്ചു.", "avan tōṇikkāraṇe viḷiccu."),
    ("Write to me when you arrive.", "നിങ്ങൾ എത്തുമ്പോൾ എനിക്ക് എഴുതുക.", "niṅṅaḷ ettumbōḷ enikk eḻutuka."),
    ("Mother told a story to the baby.", "അമ്മ കുഞ്ഞിന് കഥ പറഞ്ഞു.", "amma kuññin katha paṟaññu."),
    ("I showed the way to the tourist.", "സഞ്ചാരിക്ക് വഴി ഞാൻ കാണിച്ചു.", "sañcārikk vazhi njān kāṇiccu."),
    ("She sang to herself while cooking.", "അവൾ അടുപ്പിൽ പാട്ട് പാടിക്കൊണ്ടിരുന്നു.", "avaḷ aṭuppil pāṭṭ pāṭikoṇṭirunnu."),
    ("We promised help to the flood victims.", "വെള്ളപ്പൊക്കത്തിന് ഇരയായവർക്ക് സഹായം വാഗ്ദാനം ചെയ്തു.", "veḷḷappokkattin irayāyavarkk sahāyaṁ vāgdānaṁ ceytu."),
    ("He teaches mathematics to college students.", "അവൻ കോളേജ് വിദ്യാർത്ഥികൾക്ക് ഗണിതം പഠിപ്പിക്കുന്നു.", "avan kōḷēj vidyārththikaḷkku gaṇitaṁ paṭhippikkunnu."),
    ("I sent sweets to my neighbours.", "അയൽക്കാർക്ക് മിഠായി ഞാൻ അയച്ചു.", "ayalkkārkk miṭhāyi njān ayaccu."),
    ("They listened to the lecture attentively.", "അവർ പ്രഭാഷണം ശ്രദ്ധയോടെ കേട്ടു.", "avar prabhāṣaṇaṁ śraddhayōṭe kēṭṭu."),
    ("Please pass the salt to me.", "ഉപ്പ് എനിക്ക് തരൂ.", "upp enikk tarū."),
)

DATA526 = D(
    ("I saw him at the temple.", "ക്ഷേത്രത്തിൽ ഞാൻ അവനെ കണ്ടു.", "kṣētrattil njān avane kaṇṭu."),
    ("She called her friend on the phone.", "അവൾ സുഹൃത്തിനെ ഫോണിൽ വിളിച്ചു.", "avaḷ suhr̥uttine phōṇil viḷiccu."),
    ("We helped the old woman cross the road.", "മുതിർന്ന സ്ത്രീയെ റോഡ് കടക്കാൻ ഞങ്ങൾ സഹായിച്ചു.", "mutirnna strīye rōṭ kaṭakkān ñaṅṅaḷ sahāyiccu."),
    ("The teacher praised the diligent student.", "അധ്യാപകൻ മിടുക്കനായ വിദ്യാർത്ഥിയെ പ്രശംസിച്ചു.", "adhyāpakan miṭukkannāya vidyārththiye praśaṁsiccu."),
    ("He fed the stray dog near the gate.", "ഗേറ്റിനടുത്ത് അവൻ തെരുവുനായയ്ക്ക് ഭക്ഷണം നൽകി.", "gēṭṭinaṭutt avan teruvunāyaykku bhakṣaṇaṁ nalki."),
    ("I introduced my colleague to the guests.", "അതിഥികൾക്ക് സഹപ്രവർത്തകനെ ഞാൻ പരിചയപ്പെടുത്തി.", "atithikaḷkku sahapravarttakane njān paricayappeṭutti."),
    ("She photographed the dancer on stage.", "വേദിയിലെ നർത്തകിയെ അവൾ ഫോട്ടോ എടുത്തു.", "vēdiyile narttakiye avaḷ phōṭṭo eṭuttu."),
    ("We invited the doctor for dinner.", "ഉച്ചയ്ക്ക് ഡോക്ടറെ ഞങ്ങൾ ക്ഷണിച്ചു.", "uccaykku ḍōkṭṭare ñaṅṅaḷ kṣaṇiccu."),
    ("The child hugged his grandmother.", "കുഞ്ഞ് മുത്തശ്ശിയെ കെട്ടിപ്പിടിച്ചു.", "kuññ muttaśśiye keṭṭippiṭiccu."),
    ("He thanked the driver for a safe journey.", "സുരക്ഷിതമായ യാത്രയ്ക്ക് ഡ്രൈവർക്ക് അവൻ നന്ദി പറഞ്ഞു.", "surakṣitamāya yātraykku ḍraivarikku avan nandi paṟaññu."),
    ("I met your sister at the library.", "ലൈബ്രറിയിൽ നിന്റെ സഹോദരിയെ ഞാൻ കണ്ടുമുട്ടി.", "laibraṟiyil ninṟe sahōdariye njān kaṇṭumuṭṭi."),
    ("She taught the parrot to speak.", "കിളിയെ സംസാരിപ്പിക്കാൻ അവൾ പഠിപ്പിച്ചു.", "kiḷiye saṁsārippikkān avaḷ paṭhippiccu."),
    ("We congratulated the winning team.", "ജയിച്ച ടീമിന് ഞങ്ങൾ അഭിനന്ദനം അറിയിച്ചു.", "jayicca ṭīmin ñaṅṅaḷ abhinandanaṁ aṟiyiccu."),
    ("The police questioned the witness.", "സാക്ഷിയെ പോലീസ് ചോദ്യം ചെയ്തു.", "sākṣiye pōlīs cōdhyaṁ ceytu."),
    ("Mother blessed the children before school.", "സ്കൂളിന് പോകും മുമ്പ് അമ്മ കുട്ടികളെ ആശീർവദിച്ചു.", "skūlin pōkum mumpe amma kuṭṭikaḷe āśīrvadiccu."),
    ("I recognised my teacher after many years.", "വർഷങ്ങൾക്ക് ശേഷം അധ്യാപകനെ ഞാൻ തിരിച്ചറിഞ്ഞു.", "varṣaṅṅaḷkku śeṣaṁ adhyāpakane njān tiriccaṟiññu."),
    ("She nursed her father during his illness.", "അച്ഛൻ രോഗിയായിരുന്നപ്പോൾ അവൾ പരിചരിച്ചു.", "acchan rōgiyāyirunnappōḷ avaḷ paricariccu."),
    ("We elected a new leader for the association.", "സംഘടനയ്ക്ക് പുതിയ നേതാവിനെ ഞങ്ങൾ തിരഞ്ഞെടുത്തു.", "saṁghaṭanaykku putiya nētāvine ñaṅṅaḷ tiraññeṭuttu."),
)

DATA527 = D(
    ("This is my book.", "ഇത് എന്റെ പുസ്തകമാണ്.", "it enṟe pustakamāṇ."),
    ("That is his umbrella.", "അത് അവന്റെ കുടയാണ്.", "at avanṟe kuṭayāṇ."),
    ("Her house is near the river.", "അവളുടെ വീട് നദിക്കരികിലാണ്.", "avaḷuṭe vīṭ nadikkrikilāṇ."),
    ("Our school has a big playground.", "ഞങ്ങളുടെ സ്കൂളിൽ വലിയ കളിക്കളമുണ്ട്.", "ñaṅṅaḷuṭe skūlil valiya kaḷikkaḷamuṇṭ."),
    ("Their farm grows organic vegetables.", "അവരുടെ കൃഷിയിടത്തിൽ സജീവവ്യവസായ പച്ചക്കറികൾ വളരുന്നു.", "avaruṭe kr̥ṣiyiṭattil sajīvavyavāya paccakaṛikaḷ vaḷarunnu."),
    ("My sister is a nurse.", "എന്റെ സഹോദരി നഴ്സാണ്.", "enṟe sahōdari narssāṇ."),
    ("His opinion was different from mine.", "എന്റെ അഭിപ്രായത്തിൽ നിന്ന് അവന്റേത് വ്യത്യസ്തമായിരുന്നു.", "enṟe abhiprāyattil ninn avanṟēt vyatystamāyirunnu."),
    ("Her voice is very sweet.", "അവളുടെ ശബ്ദം വളരെ മധുരമാണ്.", "avaḷuṭe śabdaṁ vaḷare madhuramāṇ."),
    ("We sold our old car.", "ഞങ്ങൾ പഴയ കാർ വിറ്റു.", "ñaṅṅaḷ paḻaya kār viṭṭu."),
    ("They forgot their bags on the bus.", "ബസിൽ അവരുടെ ബാഗുകൾ മറന്നു.", "basil avaruṭe bāgukaḷ maṟannu."),
    ("I took my phone from the table.", "മേശയിൽ നിന്ന് എന്റെ ഫോൺ ഞാൻ എടുത്തു.", "mēśayil ninn enṟe phōn njān eṭuttu."),
    ("She wore her new sari for the function.", "അനുഷ്ഠാനത്തിന് അവൾ പുതിയ സാരി ഉടുത്തു.", "anuṣṭhānattin avaḷ putiya sāri uṭuttu."),
    ("Our guests liked the payasam.", "അതിഥികൾ പായസം ഇഷ്ടപ്പെട്ടു.", "atithikaḷ pāyasaṁ iṣṭappeṭṭu."),
    ("His handwriting is neat.", "അവന്റെ കൈയ്യെഴുത്ത് വൃത്തിയാണ്.", "avanṟe kaiyeḻutt vr̥ttiyāṇ."),
    ("Her parents live in Dubai.", "അവളുടെ മാതാപിതാക്കൾ ദുബായിലാണ്.", "avaḷuṭe mātāpitākkaḷ dubāyilāṇ."),
    ("My keys are missing.", "എന്റെ ചാവികൾ കാണാനില്ല.", "enṟe cāvikaḷ kāṇānilla."),
    ("Their team won the trophy.", "അവരുടെ ടീം ട്രോഫി നേടി.", "avaruṭe ṭīṁ ṭrōphi nēṭi."),
    ("We respect our teachers.", "ഞങ്ങൾ അധ്യാപകരെ ബഹുമാനിക്കുന്നു.", "ñaṅṅaḷ adhyāpakare bahumānikkunnu."),
)

DATA528 = D(
    ("What is your name?", "നിന്റെ പേരെന്താണ്?", "ninṟe pēr entāṇ?"),
    ("Where do you live?", "നീ എവിടെ താമസിക്കുന്നു?", "nī evide tāmasikkunnu?"),
    ("When will the train arrive?", "ട്രെയിൻ എപ്പോൾ എത്തും?", "ṭreyin epōḷ ettum?"),
    ("Why are you late today?", "ഇന്ന് നീ വൈകിയത് എന്തുകൊണ്ട്?", "inn nī vaikiyat entukoṇṭ?"),
    ("How much does this cost?", "ഇതിന് എന്തു വിലയാണ്?", "itinu entu vilayāṇ?"),
    ("Which bus goes to the airport?", "ഏത് ബസ് എയർപോർട്ടിലേക്ക് പോകുന്നു?", "ēt bas eyarpōṭṭilēkk pōkunnu?"),
    ("Who called you just now?", "ഇപ്പോൾ നിന്നെ ആരാണ് വിളിച്ചത്?", "ippōḷ ninne ārāṇ viḷicc-at?"),
    ("Whose pen is this?", "ഇത് ആരുടെ പേനയാണ്?", "it āruṭe pēnayāṇ?"),
    ("How many people came?", "എത്ര പേർ വന്നു?", "etra pēr vannu?"),
    ("What time does the shop open?", "കട എപ്പോൾ തുറക്കും?", "kaṭa epōḷ tuṟakkuṁ?"),
    ("Where can I find a good hotel?", "നല്ല ഹോട്ടൽ എവിടെ കിട്ടും?", "nalla hōṭṭal evide kiṭṭuṁ?"),
    ("Why did you change your plan?", "നീ പ്ലാൻ മാറ്റിയത് എന്തുകൊണ്ട്?", "nī plān māṭṭiyat entukoṇṭ?"),
    ("How do you say “thank you” in Malayalam?", "“നന്ദി” മലയാളത്തിൽ എങ്ങനെ പറയുന്നു?", "“nandi” malayāḷattil eṅṅane paṛayunnu?"),
    ("Which road leads to the beach?", "കടൽ തീരത്തേക്ക് ഏത് വഴി പോകണം?", "kaḍal tīrattēkk ēt vazhi pōkaṇaṁ?"),
    ("Who is the head of this office?", "ഈ ഓഫീസിന്റെ തലവൻ ആരാണ്?", "ī ōphīsin talavan ārāṇ?"),
    ("What are you doing now?", "ഇപ്പോൾ നീ എന്ത് ചെയ്യുന്നു?", "ippōḷ nī ent ceyyunnu?"),
    ("When did you reach Kerala?", "നീ കേരളത്തിലെത്തിയത് എപ്പോൾ?", "nī kēraḷattiletiyat epōḷ?"),
    ("How long will you stay here?", "നീ ഇവിടെ എത്ര നാൾ താമസിക്കും?", "nī ivide etra nāḷ tāmasikkuṁ?"),
)

DATA529 = D(
    ("I do not eat meat.", "ഞാൻ മാംസം കഴിക്കുന്നില്ല.", "njān māṁsaṁ kaḻikkunnilla."),
    ("She does not like coffee.", "അവൾ കാപ്പി ഇഷ്ടപ്പെടുന്നില്ല.", "avaḷ kāppi iṣṭappeṭunnilla."),
    ("We do not work on Sundays.", "ഞങ്ങൾ ഞായറാഴ്ച ജോലി ചെയ്യുന്നില്ല.", "ñaṅṅaḷ ñāyaṟāḻcca jōli ceyyunnilla."),
    ("He does not speak Malayalam fluently yet.", "അവൻ ഇതുവരെ മലയാളം നന്നായി സംസാരിക്കുന്നില്ല.", "avan ituvare malayāḷaṁ nannāyi saṁsārikkunnilla."),
    ("They do not live in this city.", "അവർ ഈ നഗരത്തിൽ താമസിക്കുന്നില്ല.", "avar ī nagarattil tāmasikkunnilla."),
    ("I do not know the answer.", "എനിക്ക് ഉത്തരം അറിയില്ല.", "enikk uttaraṁ aṟiyilla."),
    ("She does not drive at night.", "അവൾ രാത്രി വാഹനമോടിക്കുന്നില്ല.", "avaḷ rātri vāhanamōṭikkunnilla."),
    ("We do not waste water.", "ഞങ്ങൾ വെള്ളം പാഴാക്കുന്നില്ല.", "ñaṅṅaḷ veḷḷaṁ pāḻākkunnilla."),
    ("He does not tell lies.", "അവൻ കള്ളം പറയുന്നില്ല.", "avan kaḷḷaṁ paṛayunnilla."),
    ("I do not remember his name.", "എനിക്ക് അവന്റെ പേര് ഓർമ്മയില്ല.", "enikk avanṟe pēr ōrmmayilla."),
    ("She does not watch horror films.", "അവൾ ഭയാനക സിനിമകൾ കാണുന്നില്ല.", "avaḷ bhayānaka sinimakaḷ kāṇunnilla."),
    ("We do not accept cash after six.", "ആറിന് ശേഷം ഞങ്ങൾ പണം സ്വീകരിക്കുന്നില്ല.", "āṛin śeṣaṁ ñaṅṅaḷ paṇaṁ svīkarikkunnilla."),
    ("The shop does not open before nine.", "ഒമ്പത് മുമ്പ് കട തുറക്കുന്നില്ല.", "ompatu mumpe kaṭa tuṟakkunnilla."),
    ("I do not feel well today.", "ഇന്ന് എനിക്ക് സുഖമില്ല.", "inn enikk sukhamilla."),
    ("She does not work here anymore.", "അവൾ ഇവിടെ ഇനി ജോലി ചെയ്യുന്നില്ല.", "avaḷ ivide ini jōli ceyyunnilla."),
    ("We do not agree with that decision.", "ആ തീരുമാനവുമായി ഞങ്ങൾ യോജിക്കുന്നില്ല.", "ā tīrumānavumāyi ñaṅṅaḷ yōjikkunnilla."),
    ("He does not use plastic bags.", "അവൻ പ്ലാസ്റ്റിക് കവറുകൾ ഉപയോഗിക്കുന്നില്ല.", "avan plāsṭṭik kavaruḷ upayōgikkunnilla."),
    ("I do not want to argue now.", "ഇപ്പോൾ തർക്കിക്കാൻ എനിക്ക് താൽപ്പര്യമില്ല.", "ippōḷ tarkkikkān enikk tālparyamilla."),
)

DATA530 = D(
    ("I did not see him yesterday.", "ഇന്നലെ ഞാൻ അവനെ കണ്ടില്ല.", "innale njān avane kaṇṭilla."),
    ("She did not attend the meeting.", "അവൾ മീറ്റിംഗിൽ പങ്കെടുത്തില്ല.", "avaḷ mīṭiṅgil paṅṅkeṭuttuilla."),
    ("We did not buy anything from that shop.", "ആ കടയിൽ നിന്ന് ഞങ്ങൾ ഒന്നും വാങ്ങിയില്ല.", "ā kaṭayil ninn ñaṅṅaḷ onnuṁ vāṅṅiyilla."),
    ("He did not answer the phone.", "അവൻ ഫോൺ എടുത്തില്ല.", "avan phōn eṭuttuilla."),
    ("They did not know about the change.", "മാറ്റത്തെക്കുറിച്ച് അവർക്ക് അറിയില്ലായിരുന്നു.", "māṭṭattekkuricc avarkk aṟiyillāyirunnu."),
    ("I did not sleep well last night.", "ഇന്നലെ രാത്രി എനിക്ക് നന്നായി ഉറങ്ങാനായില്ല.", "innale rātri enikk nannāyi uṟaṅṅānāyilla."),
    ("Mother did not cook fish today.", "അമ്മ ഇന്ന് മീൻ വറുത്തില്ല.", "amma inn mīṇ vaṛuttilla."),
    ("We did not reach on time.", "ഞങ്ങൾ സമയത്ത് എത്തിയില്ല.", "ñaṅṅaḷ samayatt ettiyilla."),
    ("The train did not stop at our station.", "ട്രെയിൻ നമ്മുടെ സ്റ്റേഷനിൽ നിർത്തിയില്ല.", "ṭreyin nammuṭe sṟṟēṣanil nirtiyilla."),
    ("She did not forget your birthday.", "നിന്റെ ജന്മദിനം അവൾ മറന്നില്ല.", "ninṟe janmadinaṁ avaḷ maṟannilla."),
    ("I did not mean to hurt you.", "നിന്നെ വേദനിപ്പിക്കണമെന്ന് ഞാൻ ഉദ്ദേശിച്ചില്ല.", "ninne vēdanippikkaṇamenn njān uddēśiccilla."),
    ("He did not pass the exam.", "അവന് പരീക്ഷ ജയിക്കാനായില്ല.", "avan parīkṣa jayikkānāyilla."),
    ("We did not cancel the trip.", "യാത്ര ഞങ്ങൾ റദ്ദാക്കിയില്ല.", "yātra ñaṅṅaḷ raḍḍākkiyilla."),
    ("They did not inform us earlier.", "മുമ്പ് അവർ ഞങ്ങളെ അറിയിച്ചില്ല.", "mump avar ñaṅṅaḷe aṟiyiccilla."),
    ("I did not bring my umbrella.", "ഞാൻ കുട കൊണ്ടുവന്നില്ല.", "njān kuṭa koṇṭuvannilla."),
    ("She did not agree to the proposal.", "അവൾ നിർദ്ദേശം അംഗീകരിച്ചില്ല.", "avaḷ nirddēśaṁ aṅgīkariccilla."),
    ("We did not expect rain.", "ഞങ്ങൾ മഴ പ്രതീക്ഷിച്ചില്ല.", "ñaṅṅaḷ maḻa pratīkṣiccilla."),
    ("He did not look happy.", "അവൻ സന്തോഷവാനായി തോന്നിയില്ല.", "avan saṁtōṣavānāyi tōnniyilla."),
)

DATA531 = D(
    ("I will not come tomorrow.", "ഞാൻ നാളെ വരില്ല.", "njān nāḷe varilla."),
    ("She will not leave without permission.", "അനുമതിയില്ലാതെ അവൾ പോകില്ല.", "anumati illāte avaḷ pōkilla."),
    ("We will not forget this kindness.", "ഈ ദയ മറക്കുകയില്ല ഞങ്ങൾ.", "ī daya maṟakkukayilla ñaṅṅaḷ."),
    ("He will not drive if it rains heavily.", "കനത്ത മഴ പെയ്താൽ അവൻ വാഹനമോടിക്കുകയില്ല.", "kanatta maḻa peytāl avan vāhanamōṭikkukayilla."),
    ("They will not arrive before noon.", "ഉച്ചയ്ക്ക് മുമ്പ് അവർ എത്തുകയില്ല.", "uccaykku mumpe avār ettukayilla."),
    ("I will not pay extra for this.", "ഇതിന് കൂടുതൽ പണം നൽകുകയില്ല.", "itin kūtutal paṇaṁ nalkukayilla."),
    ("She will not speak in public.", "പൊതുവേദിയിൽ അവൾ സംസാരിക്കുകയില്ല.", "pōtuvēdiyil avaḷ saṁsārikkukayilla."),
    ("We will not sell this land.", "ഈ ഭൂമി വിറ്റുകൊടുക്കുകയില്ല.", "ī bhūmi viṭṭukoṭukkukayilla."),
    ("The shop will not open on holiday.", "അവധി ദിവസം കട തുറക്കുകയില്ല.", "avadhi divasaṁ kaṭa tuṟakkukayilla."),
    ("He will not repeat that mistake.", "ആ പിശക് ആവർത്തിക്കുകയില്ല.", "ā piśak āvarttikkukayilla."),
    ("I will not disturb you now.", "ഇപ്പോൾ നിന്നെ ബുദ്ധിമുട്ടിക്കുകയില്ല.", "ippōḷ ninne buddhimuṭṭikkukayilla."),
    ("She will not join the trip.", "യാത്രയിൽ അവൾ ചേരുകയില്ല.", "yātrayil avaḷ cērukayilla."),
    ("We will not accept damaged goods.", "തകർന്ന സാധനങ്ങൾ സ്വീകരിക്കുകയില്ല.", "takarna sādhanakaḷ svīkarikkukayilla."),
    ("They will not build without a permit.", "അനുമതിയില്ലാതെ അവർ പണിയുകയില്ല.", "anumati illāte avār paṇiyukayilla."),
    ("I will not share your secret.", "നിന്റെ രഹസ്യം വെളിപ്പെടുത്തുകയില്ല.", "ninṟe rahasyaṁ veḷippeṭuttukayilla."),
    ("The train will not stop at this station.", "ട്രെയിൻ ഈ സ്റ്റേഷനിൽ നിർത്തുകയില്ല.", "ṭreyin ī sṟṟēṣanil nirtukayilla."),
    ("We will not compromise on quality.", "ഗുണനിലവാരത്തിൽ ഞങ്ങൾ വിട്ടുവീഴ്ച ചെയ്യുകയില്ല.", "guṇanilavārattil ñaṅṅaḷ viṭṭuvīḻca ceyyukayilla."),
    ("He will not return before evening.", "സായാഹ്നത്തിന് മുമ്പ് അവൻ തിരിച്ചെത്തുകയില്ല.", "sāyāhnattin mumpe avan tiriccettukayilla."),
)

DATA532 = D(
    ("The girl is reading quietly.", "പെൺകുട്ടി നിശബ്ദമായി വായിക്കുന്നു.", "peṇkuṭṭi niśabdamāyi vāyikkunnu."),
    ("The boys are playing football.", "ആൺകുട്ടികൾ ഫുട്ബോൾ കളിക്കുന്നു.", "āṇkuṭṭikaḷ phuṭbōḷ kaḷikkunnu."),
    ("Women farmers work in the fields.", "സ്ത്രീ കർഷകർ വയലിൽ പണിയെടുക്കുന്നു.", "strī karṣakar vayil paṇiyeṭukkunnu."),
    ("Many students passed the exam.", "ധാരാളം വിദ്യാർത്ഥികൾ പരീക്ഷ ജയിച്ചു.", "dhārāḷaṁ vidyārththikaḷ parīkṣa jayiccu."),
    ("The children are happy with their gifts.", "കുട്ടികൾ സമ്മാനങ്ങളിൽ സന്തോഷവാന്മാരാണ്.", "kuṭṭikaḷ sammānaṅṅaḷil saṁtōṣavānmārāṇ."),
    ("Elderly people need rest.", "മുതിർന്നവർക്ക് വിശ്രമം വേണം.", "mutirnnavarkk viśramaṁ vēṇaṁ."),
    ("The dog wagged its tail.", "നായ വാലാടിച്ചു.", "nāya vālāṭiccu."),
    ("Those books belong to the library.", "ആ പുസ്തകങ്ങൾ ലൈബ്രറിയുടേതാണ്.", "ā pustakaṅṅaḷ laibraṟiyuṭetāṇ."),
    ("New houses were built near the lake.", "തടാകത്തിനടുത്ത് പുതിയ വീടുകൾ പണിയപ്പെട്ടു.", "taṭākattinaṭutt putiya vīṭukaḷ paṇiyappeṭṭu."),
    ("Several birds nest on that tree.", "ആ മരത്തിൽ പല പക്ഷികളും കൂടുകൂട്ടുന്നു.", "ā marattil pala pakṣikaḷuṁ kūṭukaṭṭunnu."),
    ("The teachers are experienced.", "അധ്യാപകർ പരിചയസമ്പന്നരാണ്.", "adhyāpakar paricayasampannarāṇ."),
    ("Young musicians performed well.", "യുവ സംഗീതജ്ഞർ നന്നായി അവതരിപ്പിച്ചു.", "yuva saṁgītajñar nannāyi avatari ppiccu."),
    ("The cat caught a mouse.", "പൂച്ച എലിയെ പിടിച്ചു.", "pūcca eliye piṭiccu."),
    ("Wild elephants entered the village.", "കാട്ടാനകൾ ഗ്രാമത്തിൽ പ്രവേശിച്ചു.", "kāṭṭānakal grāmattil praveśiccu."),
    ("Domestic workers deserve fair wages.", "വീട്ടുജോലിക്കാർക്ക് നീതിയായ കൂലി ലഭിക്കണം.", "vīṭṭujōlikkārkk nītiyāya kūli labhikkaṇaṁ."),
    ("The flowers in the garden are colourful.", "തോട്ടത്തിലെ പൂക്കൾ വർണ്ണശബളമാണ്.", "tōṭṭattile pūkkaḷ varṇṇaśabaḷamāṇ."),
    ("Several languages are spoken in India.", "ഇന്ത്യയിൽ പല ഭാഷകളും സംസാരിക്കപ്പെടുന്നു.", "intyayil pala bhāṣakaḷuṁ saṁsārikkappeṭunnu."),
    ("The news spread quickly in the town.", "വാർത്ത പട്ടണത്തിൽ വേഗത്തിൽ പരന്നു.", "vārttha paṇṇattil vēgattil parannu."),
)

DATA533 = D(
    ("The keys are in the drawer.", "ചാവി അലമാരിയുടെ അകത്താണ്.", "cāvi alamāriyuṭe akattāṇ."),
    ("She sat on the chair.", "അവൾ കസേരയിൽ ഇരുന്നു.", "avaḷ kasērayil irunnu."),
    ("We walked across the bridge.", "ഞങ്ങൾ പാലം കടന്നു.", "ñaṅṅaḷ pālaṁ kaṭannu."),
    ("The picture hangs on the wall.", "ചിത്രം ചുവരിൽ തൂങ്ങിക്കിടക്കുന്നു.", "citraṁ cuvaril tūṅṅikkikaṭakkunnu."),
    ("He hid behind the door.", "അവൻ വാതിലിന് പിന്നിൽ ഒളിച്ചു.", "avan vātilin piṉnil oḷiccu."),
    ("Birds perch on the wire.", "പക്ഷികൾ വയറിൽ കയറിനിരിക്കുന്നു.", "pakṣikaḷ vayaṟil kayṟinirikkunnu."),
    ("We live near the temple.", "ഞങ്ങൾ ക്ഷേത്രത്തിന് അടുത്താണ് താമസിക്കുന്നത്.", "ñaṅṅaḷ kṣētrattin aṭuttāṇ tāmasikkunnat."),
    ("The boat floated on the river.", "തോണി നദിയിൽ ഒഴുകി.", "tōṇi nadiyil oḻuki."),
    ("She kept the fruits inside the fridge.", "പഴങ്ങൾ ഫ്രിഡ്ജിന് അകത്ത് അവൾ വെച്ചു.", "paḻaṅṅaḷ phriḍjin akatt avaḷ veccu."),
    ("He stood beside his friend.", "അവൻ സുഹൃത്തിന് അടുത്ത് നിന്നു.", "avan suhr̥uttin aṭutt ninnu."),
    ("We drove through the tunnel.", "ഞങ്ങൾ തുരങ്കത്തിലൂടെ വാഹനമോടിച്ചു.", "ñaṅṅaḷ turaṅṅattilūṭe vāhanamōṭiccu."),
    ("The cat jumped onto the wall.", "പൂച്ച ചുവരിൽ ചാടി.", "pūcca cuvaril cāṭi."),
    ("They camped under the stars.", "അവർ നക്ഷത്രങ്ങൾക്ക് ചുവട്ടിൽ ക്യാമ്പ് ചെയ്തു.", "avar nakṣatraṅṅaḷkku cuvaṭṭil kyāmp ceytu."),
    ("I found a coin under the mat.", "പായക്ക് ചുവട്ടിൽ നിന്ന് ഞാൻ നാണയം കണ്ടെത്തി.", "pāyakku cuvaṭṭil ninn njān nāṇayaṁ kaṇṭetti."),
    ("The office is above the bank.", "ബാങ്കിന് മുകളിലാണ് ഓഫീസ്.", "bāṅkin mukaḷilāṇ ōphīs."),
    ("We met during the interval.", "ഇന്റർവെലിൽ ഞങ്ങൾ കണ്ടുമുട്ടി.", "iṇṭarvelil ñaṅṅaḷ kaṇṭumuṭṭi."),
    ("He spoke about the plan for an hour.", "ഒരു മണിക്കൂർ അവൻ പദ്ധതിയെക്കുറിച്ച് സംസാരിച്ചു.", "oru maṇikkūr avan padhatiyekkuricc saṁsāriccu."),
    ("She travelled by night train.", "അവൾ രാത്രി ട്രെയിനിൽ യാത്ര ചെയ്തു.", "avaḷ rātri ṭreyinil yātra ceytu."),
)

DATA534 = D(
    ("Put the book on the shelf, not under the bed.", "പുസ്തകം അലമാരിയിൽ വെക്കുക, കട്ടിലിന് ചുവട്ടിലല്ല.", "pustakaṁ alamāriyil vekku kaṭṭilin cuvaṭṭilalla."),
    ("The book is in the bag; I cut the paper with scissors.", "പുസ്തകം ബാഗിനുള്ളിൽ; കത്തി കൊണ്ട് കടലാസ് മുറിച്ചു.", "pustakaṁ bāginuḷḷil; katti koṇṭ kaṭalās muṛiccu."),
    ("The children play outside and eat inside.", "കുട്ടികൾ പുറത്ത് കളിക്കുകയും അകത്ത് ഭക്ഷണം കഴിക്കുകയും ചെയ്യുന്നു.", "kuṭṭikaḷ puṛatt kaḷikkukayuṁ akatt bhakṣaṇaṁ kaḻikkukayuṁ ceyyunnu."),
    ("The book is on the shelf; the shoes are below.", "പുസ്തകം അലമാരിയിൽ; ചെരുപ്പുകൾ താഴെയാണ്.", "pustakaṁ alamāriyil; ceruppuḷ tāḻeyāṇ."),
    ("I bought rice from the shop.", "ഞാൻ കടയിൽ നിന്ന് ചോറ് വാങ്ങി.", "njān kaṭayil ninn cōṟ vāṅṅi."),
    ("We walked from here to the bus stop.", "ഞങ്ങൾ ഇവിടെ മുതൽ ബസ് സ്റ്റോപ്പ് വരെ നടന്നു.", "ñaṅṅaḷ ivide mutal bas sṟṟōpp vare naṭannu."),
    ("He stayed home because of the rain.", "മഴ കൊണ്ട് അവൻ വീട്ടിൽ താമസിച്ചു.", "maḻa koṇṭ avan vīṭṭil tāmasiccu."),
    ("My uncle became a writer after retirement.", "റിട്ടയർമെന്റിന് ശേഷം അമ്മാവൻ എഴുത്തുകാരനായി.", "riṭṭayarmentin śeṣaṁ ammāvan eḻuttukāranāyi."),
    ("Mother cooked lunch for the children.", "അമ്മ കുട്ടികൾക്ക് ഉച്ചഭക്ഷണം ഉണ്ടാക്കി.", "amma kuṭṭikaḷkku uccabhakṣaṇaṁ uṇṭākki."),
    ("My friend came with me to the station.", "സുഹൃത്ത് എന്റെ കൂടെ സ്റ്റേഷനിലേക്ക് വന്നു.", "suhr̥utt enṟe kūṭe sṟṟēṣanilēkk vannu."),
    ("Her necklace shines like gold.", "അവളുടെ നെക്ലസ് സ്വർണ്ണം പോലെ മിന്നുന്നു.", "avaḷuṭe neklas svarṇṇaṁ pōle minnunnu."),
    ("I can stay only today.", "എനിക്ക് ഇന്ന് മാത്രം താമസിക്കാം.", "enikk inn mātraṁ tāmasikkāᮂ."),
    ("We worked until evening.", "ഞങ്ങൾ സായാഹ്നം വരെ ജോലി ചെയ്തു.", "ñaṅṅaḷ sāyāhnaᮂ vare jōli ceytu."),
    ("The shop is between the bank and the post office.", "ബാങ്കിനും പോസ്റ്റ് ഓഫീസിനും ഇടയിലാണ് കട.", "bāṅkinuᮂ pōsṭ ṭōphisinuᮂ iṭayilāṇ kaṭa."),
    ("The book is on the table.", "മേശയ്ക്ക് മുകളിൽ പുസ്തകം.", "mēśaykku mukaḷil pustakaᮂ."),
    ("Walk behind the vehicle.", "വാഹനത്തിന് പിന്നിൽ നടക്കുക.", "vāhanattin piṉnil naṭakkuka."),
    ("Please wait in front of the gate.", "ഗേറ്റിന് മുന്നിൽ നിൽക്കുക.", "gēṭṭin munnil nilkkuka."),
    ("I pack my bag before every trip.", "ഓരോ യാത്രയ്ക്കും മുമ്പ് ഞാൻ ബാഗ് പാക്ക് ചെയ്യുന്നു.", "ōrō yātraykkuᮂ mumpe njān bāk pāk ceyyunnu."),
)

DATA535 = D(
    ("I gave him a book (dative sense).", "ഞാൻ അവന് ഒരു പുസ്തകം നൽകി.", "njān avan oru pustakaṁ nalki."),
    ("Mother made curry for us.", "അമ്മ ഞങ്ങൾക്ക് കറി ഉണ്ടാക്കി.", "amma ñaṅṅaḷkku kaṛi uṇṭākki."),
    ("The teacher explained the lesson to the class.", "അധ്യാപകൻ ക്ലാസിന് പാഠം വിശദീകരിച്ചു.", "adhyāpakan klāsin pāṭhaṁ viśadīkariccu."),
    ("We bought vegetables from the farmer.", "ഞങ്ങൾ കർഷകനിൽ നിന്ന് പച്ചക്കറി വാങ്ങി.", "ñaṅṅaḷ karṣakanil ninn paccakaṛi vāṅṅi."),
    ("He ran away from danger.", "അവൻ അപായത്തിൽ നിന്ന് ഓടി.", "avan apāyattil ninn ōṭi."),
    ("She wrote a letter with a pen.", "അവൾ പേന കൊണ്ട് കത്ത് എഴുതി.", "avaḷ pēna koṇṭ katt eḻuti."),
    ("The bird sat on the branch.", "പക്ഷി കൊമ്പിൽ ഇരുന്നു.", "pakṣi kompil irunnu."),
    ("We travelled by bus.", "ഞങ്ങൾ ബസിൽ യാത്ര ചെയ്തു.", "ñaṅṅaḷ basil yātra ceytu."),
    ("I cut the rope with a knife.", "ഞാൻ കത്തി കൊണ്ട് കയർ മുറിച്ചു.", "njān katti koṇṭ kayar muṛiccu."),
    ("They came for the meeting.", "അവർ മീറ്റിംഗിന് വന്നു.", "avar mīṭiṅin vannu."),
    ("The child is afraid of dogs.", "കുട്ടിക്ക് നായകളോട് പേടിയാണ്.", "kuṭṭikk nāyakaḷōṭ pēṭiyāṇ."),
    ("We are proud of our culture.", "ഞങ്ങൾ നമ്മുടെ സംസ്കാരത്തിൽ അഭിമാനമുള്ളവരാണ്.", "ñaṅṅaḷ nammuṭe saṁskārattil abhimānamuḷḷavarāṇ."),
    ("He spoke about the environment.", "അവൻ പരിസ്ഥിതിയെക്കുറിച്ച് സംസാരിച്ചു.", "avan paristhitiyekkuricc saṁsāriccu."),
    ("She succeeded through hard work.", "അവൾ കഠിനാധ്വാനം കൊണ്ട് വിജയിച്ചു.", "avaḷ kaṭhinādhvānaṁ koṇṭ vijayiccu."),
    ("I waited until evening.", "ഞാൻ സായാഹ്നം വരെ കാത്തിരുന്നു.", "njān sāyāhnaṁ vare kāttirunnu."),
    ("We walked along the river.", "ഞങ്ങൾ നദീതീരത്തിലൂടെ നടന്നു.", "ñaṅṅaḷ nadītīrattilūṭe naṭannu."),
    ("The gift is for you.", "സമ്മാനം നിനക്ക് വേണ്ടിയതാണ്.", "sammānaṁ ninakk vēṇṭiyatāṇ."),
    ("Cases in Malayalam often use postpositions rather than endings alone.", "മലയാളത്തിൽ വിഭക്തി പലപ്പോഴും നാമത്തിന് ശേഷം വരുന്ന പദങ്ങളോട് കൂടിയാണ് പ്രകടമാകുന്നത്.", "malayāḷattil vibhakti palappōḻuṁ nāmattin śeṣaṁ varunna padaṅṅaḷōṭ kūṭiyāṇ prakaṭamākunnat."),
)

DATA536 = D(
    ("Come here quickly.", "വേഗം ഇവിടെ വാ.", "vēgaṁ ivide vā."),
    ("Please sit down.", "ദയവായി ഇരിക്കൂ.", "dayavāyi irikkhū."),
    ("Do not make noise.", "ശബ്ദം പുറപ്പെടുത്തരുത്.", "śabdaṁ puṛappeṭuttarut."),
    ("Let us go together.", "നമുക്ക് ഒരുമിച്ച് പോകാം.", "namukku orumicc pōkāṁ."),
    ("Bring two cups of tea.", "രണ്ടു കപ്പ് ചായ കൊണ്ടുവാ.", "raṇṭu kapp cāya koṇṭuvā."),
    ("Close the window.", "ജനൽ അടയ്ക്കുക.", "janal aṭaykkuka."),
    ("Remember to lock the door.", "വാതിൽ പൂട്ടാൻ മറക്കരുത്.", "vātil pūṭṭān maṟakkarut."),
    ("Help your younger sister.", "ഇളയ സഹോദരിയെ സഹായിക്കുക.", "iḷaya sahōdariye sahāyikkuka."),
    ("Read this paragraph aloud.", "ഈ പേരാ ഉച്ചത്തിൽ വായിക്കുക.", "ī pērā uccattil vāyikkuka."),
    ("Do not waste electricity.", "വൈദ്യുതി പാഴാക്കരുത്.", "vaidyuti pāḻākkarut."),
    ("Call me when you reach.", "എത്തുമ്പോൾ വിളിക്കുക.", "ettumbōḷ viḷikkuka."),
    ("Take care of your health.", "ആരോഗ്യം ശ്രദ്ധിക്കുക.", "ārōgyaṁ śraddhikkuka."),
    ("Stand in a queue.", "ക്യൂവിൽ നിൽക്കുക.", "kyūvil nilkkuka."),
    ("Give way to ambulances.", "ആംബുലൻസിന് വഴി കൊടുക്കുക.", "āmbulansin vazhi koṭukkuka."),
    ("Plant more trees in the compound.", "മുറ്റത്ത് കൂടുതൽ മരങ്ങൾ നടുക.", "muṟṭatt kūtutal maraṅṅaḷ naṭuka."),
    ("Smile when you greet elders.", "മുതിർന്നവരെ കാണുമ്പോൾ ചിരിച്ച് വന്ദിക്കുക.", "mutirnnavare kāṇumbōḷ ciricc vandikkuka."),
    ("Never tell lies.", "ഒരിക്കലും കള്ളം പറയരുത്.", "orikkaluṁ kaḷḷaṁ paṛayarut."),
    ("Formal Malayalam uses polite particles with imperatives in speech.", "ഔപചാരിക മലയാളത്തിൽ ആജ്ഞകൾക്കൊപ്പം ബഹുമാന സൂചകങ്ങൾ ചേർക്കുന്നു.", "aupacārika malayāḷattil āññakaḷkoppaṁ bahumāna sūcakaṅṅaḷ cērkkunnu."),
)

DATA537 = D(
    ("I will call you tomorrow morning at seven.", "നാളെ ഏഴുമണിക്ക് പ്രഭാതത്തിൽ ഞാൻ നിന്നെ വിളിക്കും.", "nāḷe ēḻumaṇik prabhātattil njān ninne viḷikkuṁ."),
    ("We usually have lunch at one o’clock.", "ഒരു മണിക്ക് സാധാരണയായി ഞങ്ങൾ ഉച്ചയ്ക്ക് ഭക്ഷണം കഴിക്കും.", "oru maṇik sādhāraṇayāyi ñaṅṅaḷ uccaykku bhakṣaṇaṁ kaḻikkuṁ."),
    ("The train leaves in fifteen minutes.", "പതിനഞ്ചു മിനിറ്റിൽ ട്രെയിൻ പുറപ്പെടും.", "pathinañcu miṇiṭṭil ṭreyin puṛappeṭuṁ."),
    ("She was born in nineteen ninety.", "അവൾ ഒന്നൊന്നൊന്നൊന്ന് തൊന്നൂറിൽ ജനിച്ചു.", "avaḷ onnonnonnonn tōnnūril janiccu."),
    ("Winter is mild on the Kerala coast.", "കേരള തീരത്ത് ശൈത്യകാലം മൃദുവാണ്.", "kēraḷa tīratt śaityakālaṁ mr̥duvāṇ."),
    ("We celebrate Onam in August–September.", "ഓണം ഓഗസ്റ്റ്–സെപ്റ്റംബറിൽ ആഘോഷിക്കുന്നു.", "ōṇaṁ ōgasṭ–sepṭaṁbaril āghōṣikkunnu."),
    ("The shop opens at nine and closes at nine in the evening.", "കട ഒമ്പത് മണിക്ക് തുറക്കും രാത്രി ഒമ്പത് മണിക്ക് അടയ്ക്കും.", "kaṭa ompatu maṇik tuṟakkuṁ rātri ompatu maṇik aṭaykkuṁ."),
    ("I have been waiting since morning.", "പ്രഭാതം മുതൽ ഞാൻ കാത്തിരിക്കുന്നു.", "prabhātaṁ mutal njān kāttirikkunnu."),
    ("The meeting will last for two hours.", "മീറ്റിംഗ് രണ്ടു മണിക്കൂർ നീണ്ടുനിൽക്കും.", "mīṭiṅ raṇṭu maṇikkūr nīṇṭunilkuṁ."),
    ("We met after a long time.", "വളരെ നാളുകൾക്ക് ശേഷം ഞങ്ങൾ കണ്ടുമുട്ടി.", "vaḷare nāḷukaḷkku śeṣaṁ ñaṅṅaḷ kaṇṭumuṭṭi."),
    ("Sunrise here is beautiful.", "ഇവിടെ സൂര്യോദയം മനോഹരമാണ്.", "ivide sūryōdayaṁ manōharamāṇ."),
    ("Do not forget the appointment next Friday.", "അടുത്ത വെള്ളിയാഴ്ചയിലെ അപ്പോയിന്റ്മെന്റ് മറക്കരുത്.", "aṭutta veḷḷiyāḻcayile appoyinṭmeṇṭ maṟakkarut."),
    ("The festival lasts three days.", "ഉത്സവം മൂന്നു ദിവസം നീണ്ടുനിൽക്കും.", "utsavaṁ mūnnu divasaṁ nīṇṭunilkuṁ."),
    ("I work from nine to five on weekdays.", "വർക്കിംഗ് ദിവസങ്ങളിൽ ഒമ്പത് മുതൽ അഞ്ചുവരെ ഞാൻ ജോലി ചെയ്യുന്നു.", "varkiṅ divasaṅṅaḷil ompatu mutal añcuvare njān jōli ceyyunnu."),
    ("We arrived just before sunset.", "സൂര്യാസ്തമയത്തിന് തൊട്ടുമുമ്പ് ഞങ്ങൾ എത്തി.", "sūryāstamayattin toṭṭumump ñaṅṅaḷ etti."),
    ("The baby sleeps during the day.", "കുഞ്ഞ് പകൽ ഉറങ്ങുന്നു.", "kuññ pakal uṟaṅṅunnu."),
    ("I usually say the time first when I plan my day.", "പലപ്പോഴും ദിവസം ആസൂത്രണം ചെയ്യുമ്പോൾ ഞാൻ ആദ്യം സമയം പറയും.", "palappōḷuṁ divasaṁ āsūtrāṇaṁ ceyyumbōḷ njān ādyaṁ samayaṁ paṛayuᮂ."),
    ("Today is Monday; yesterday was Sunday; tomorrow is Tuesday.", "ഇന്ന് തിങ്കളാഴ്ച; ഇന്നലെ ഞായറാഴ്ച; നാളെ ചൊവ്വാഴ്ച.", "inn tiṅṅaḷāḻca; innale ñāyaṟāḻca; nāḷe covvāḻca."),
)

DATA538 = D(
    ("Mother made the child drink milk.", "അമ്മ കുഞ്ഞിന് പാൽ കുടിപ്പിച്ചു.", "amma kuññin pāl kuṭippiccu."),
    ("The teacher made the students write an essay.", "അധ്യാപകൻ വിദ്യാർത്ഥികൾക്ക് പ്രബന്ധം എഴുതിച്ചു.", "adhyāpakan vidyārththikaḷkku prabandhaṁ eḻuticcu."),
    ("I got the car repaired.", "ഞാൻ കാർ നന്നാക്കിച്ചു.", "njān kār nannākiccu."),
    ("She had her hair cut at the salon.", "അവൾ സലൂണിൽ മുടി വെട്ടിച്ചു.", "avaḷ salūnil muṭi veṭṭiccu."),
    ("We got the house painted last month.", "കഴിഞ്ഞ മാസം ഞങ്ങൾ വീട് വർണ്ണം പൂശിച്ചു.", "kaḻiñña māsaṁ ñaṅṅaḷ vīṭ varṇṇaṁ pūśiccu."),
    ("He made them wait for an hour.", "അവൻ അവർക്ക് ഒരു മണിക്കൂർ കാത്തിരുത്തി.", "avan avarkk oru maṇikkūr kāttirutti."),
    ("The boss let the staff leave early.", "മേലധികാരി ജീവനക്കാരെ നേരത്തെ പോകാൻ അനുവദിച്ചു.", "mēladhikāri jīvana kkāre nērattē pōkān anuvadiccu."),
    ("I will get the documents photocopied.", "രേഖാപത്രങ്ങൾ പകർപ്പ് എടുപ്പിക്കും.", "rēkhāpatraṅṅaḷ pakarpp eṭuppikkuṁ."),
    ("She fed the stray cat.", "അവൾ തെരുവുപൂച്ചയ്ക്ക് ഭക്ഷണം കൊടുത്തു.", "avaḷ teruvupūccaykku bhakṣaṇaṁ koṭuttu."),
    ("We had the garden cleaned before the guests came.", "അതിഥികൾ വരുന്നതിന് മുമ്പ് ഞങ്ങൾ തോട്ടം വൃത്തിയാക്കി.", "atithikaḷ varunnatin mumpe ñaṅṅaḷ tōṭṭaṁ vr̥ttiyākki."),
    ("The coach made the team run five rounds.", "പരിശീലകൻ ടീമിന് അഞ്ചു റൗണ്ട് ഓടിച്ചു.", "pariśīlakaṇ ṭīmin añcu rauṇṭ ōṭiccu."),
    ("I got my phone screen replaced.", "ഫോൺ സ്ക്രീൻ മാറ്റിച്ചു.", "phōn skrīn māṭṭiccu."),
    ("He made his son study every evening.", "അവൻ മകന് ഓരോ സായാഹ്നവും പഠിപ്പിച്ചു.", "avan makan ōrō sāyāhnavuṁ paṭhippiccu."),
    ("We had the well cleaned before summer.", "വേനലിന് മുമ്പ് കിണർ വൃത്തിയാക്കി.", "vēnalin mumpe kiṇar vr̥ttiyākki."),
    ("She got the invitation cards printed.", "ക്ഷണക്കത്തുകൾ അച്ചടിപ്പിച്ചു.", "kṣaṇakkathukaḷ accaṭippiccu."),
    ("The police made him sign the statement.", "പോലീസ് അവനെ മൊഴി ഒപ്പിടാൻ നിർബന്ധിച്ചു.", "pōlīs avane mŏḻi oppiṭān nirbandhiccu."),
    ("I will have lunch packed for the journey.", "യാത്രയ്ക്ക് ഉച്ചഭക്ഷണം പാക്ക് ചെയ്യിപ്പിക്കും.", "yātraykku uccabhakṣaṇaṁ pāk ceyyippikkuṁ."),
    ("Mother made the child finish the homework.", "അമ്മ കുട്ടിയെ ഹോംവർക്ക് തീർക്കാൻ നിർബന്ധിച്ചു.", "amma kuṭṭiye hōmvarkk tīrkkān nirbandhiccu."),
)

DATA539 = D(
    ("The boy opened the door.", "ആൺകുട്ടി വാതിൽ തുറന്നു.", "āṇkuṭṭi vātil tuṟannu."),
    ("The girl opened the door.", "പെൺകുട്ടി വാതിൽ തുറന്നു.", "peṇkuṭṭi vātil tuṟannu."),
    ("Those boys are playing.", "ആ ആൺകുട്ടികൾ കളിക്കുന്നു.", "ā āṇkuṭṭikaḷ kaḷikkunnu."),
    ("Those girls are singing.", "ആ പെൺകുട്ടികൾ പാടുന്നു.", "ā peṇkuṭṭikaḷ pāṭunnu."),
    ("The teacher spoke to us kindly.", "അധ്യാപകർ നമ്മോട് ദയയോടെ പറഞ്ഞു.", "adhyāpakar nammoṭ dayayōṭe paṟaññu."),
    ("The dog wagged its tail; the dogs barked.", "നായ വാലാടിച്ചു; നായകൾ കുരച്ചു.", "nāya vālāṭiccu; nāyakaḷ kuraccu."),
    ("One book is on the table; many books are on the shelf.", "ഒരു പുസ്തകം മേശയിലാണ്; ധാരാളം പുസ്തകങ്ങൾ അലമാരിയിലാണ്.", "oru pustakaṁ mēśayilāṇ; dhārāḷaṁ pustakaṅṅaḷ alamāriyilāṇ."),
    ("He speaks fast; she speaks slowly.", "അവൻ വേഗത്തിൽ സംസാരിക്കുന്നു; അവൾ മെല്ലെ സംസാരിക്കുന്നു.", "avan vēgattil saṁsārikkunnu; avaḷ melle saṁsārikkunnu."),
    ("We respect plural agreement when addressing elders.", "മുതിർന്നവരോട് ബഹുവചന ധാരണ പാലിക്കുന്നു.", "mutirnnavarōṭ bahuvacaṇa dhāraṇa pālikkunnu."),
    ("The child is sleeping; the children are playing.", "കുഞ്ഞ് ഉറങ്ങുന്നു; കുട്ടികൾ കളിക്കുന്നു.", "kuññ uṟaṅṅunnu; kuṭṭikaḷ kaḷikkunnu."),
    ("That man came; those men helped.", "ആ മനുഷ്യൻ വന്നു; ആ മനുഷ്യർ സഹായിച്ചു.", "ā manuṣyan vannu; ā manuṣyar sahāyiccu."),
    ("This woman teaches; these women teach.", "ഈ സ്ത്രീ പഠിപ്പിക്കുന്നു; ഈ സ്ത്രീകൾ പഠിപ്പിക്കുന്നു.", "ī strī paṭhippikkunnu; ī strīkaḷ paṭhippikkunnu."),
    ("Formal speech follows strict rules for verbs and subjects.", "ഔപചാരിക പ്രസംഗത്തിൽ ക്രിയയും കർത്താവും കർശനമായി പാലിക്കുന്നു.", "aupacārika prasaṅgattil kriyayuṁ karttāvuᮂ karśanamāyi pālikkuᮂ."),
    ("The book lies on the table; the books lie on the shelf.", "പുസ്തകം മേശയിലുണ്ട്; പുസ്തകങ്ങൾ അലമാരിയിലുണ്ട്.", "pustakaᮂ mēśayiluṇṭ; pustakaṅṅaḷ alamāriyiluṇṭ."),
    ("Honorific plural can refer to one respected person.", "ഒരാളെ ബഹുമാനിക്കുമ്പോൾ ബഹുവചനം ഉപയോഗിക്കാം.", "orāḷe bahumānikkumbōḷ bahuvacaṇaṁ upayōgikkāṁ."),
    ("Adjectives often agree with the noun in informal speech.", "അനൗപചാരിക സംസാരത്തിൽ വിശേഷണങ്ങൾ നാമവുമായി പൊരുത്തപ്പെടുന്നു.", "anaupacārika saṁsāraṭṭil viśeṣaṇaṅṅaḷ nāmavumāyi poruttappeṭunnu."),
    ("The boy runs fast; the girl runs fast; the children run fast.", "ആൺകുട്ടി വേഗത്തിൽ ഓടുന്നു; പെൺകുട്ടി വേഗത്തിൽ ഓടുന്നു; കുട്ടികൾ വേഗത്തിൽ ഓടുന്നു.", "āṇkuṭṭi vēgattil ōṭunnu; peṇkuṭṭi vēgattil ōṭunnu; kuṭṭikaḷ vēgattil ōṭunnu."),
    ("I read the newspaper to learn new words.", "പുതിയ വാക്കുകൾ പഠിക്കാൻ ഞാൻ പത്രം വായിക്കുന്നു.", "putiya vākkukaḷ paṭhikkān njān patraᮂ vāyikkuᮂ."),
)

DATA540 = D(
    ("I have finished the work.", "ഞാൻ ജോലി പൂർത്തിയാക്കിയിരിക്കുന്നു.", "njān jōli pūrttiyākkirikkunnu."),
    ("She had already left when we arrived.", "ഞങ്ങൾ എത്തിയപ്പോൾ അവൾ പോയിക്കഴിഞ്ഞിരുന്നു.", "ñaṅṅaḷ ettiyappōḷ avaḷ pōyikkaḻiññirunnu."),
    ("By next year we will have built the house.", "അടുത്ത വർഷം വരെ ഞങ്ങൾ വീട് പണിതിരിക്കും.", "aṭutta varṣaṁ vare ñaṅṅaḷ vīṭ paṇitirikuṁ."),
    ("They had never seen the sea before.", "മുമ്പ് അവർ കടൽ കണ്ടിട്ടില്ലായിരുന്നു.", "mump avar kaḍal kaṇṭiṭṭillāyirunnu."),
    ("I will have submitted the form by Monday.", "തിങ്കളാഴ്ചയ്ക്കകം ഞാൻ ഫോം സമർപ്പിച്ചിരിക്കും.", "tiṅṅaḷāḻccakkaṁ njān phōm samarpiccirikuṁ."),
    ("She has been teaching here for five years.", "അവൾ ഇവിടെ അഞ്ചു വർഷമായി പഠിപ്പിക്കുകയാണ്.", "avaḷ ivide añcu varṣamāyi paṭhippikkukayāṇ."),
    ("We had waited for an hour before the bus came.", "ബസ് വരുന്നതിന് മുമ്പ് ഞങ്ങൾ ഒരു മണിക്കൂർ കാത്തിരുന്നു.", "bas varunnatin mumpe ñaṅṅaḷ oru maṇikkūr kāttirunnu."),
    ("He will have reached by now.", "ഇപ്പോൾ അവൻ എത്തിയിരിക്കും.", "ippōḷ avan ettiyirikuṁ."),
    ("I had forgotten to call you.", "നിന്നെ വിളിക്കാൻ ഞാൻ മറന്നിരുന്നു.", "ninne viḷikkān njān maṟannirunnu."),
    ("They have completed the project ahead of schedule.", "അവർ സമയത്തിന് മുമ്പ് പദ്ധതി പൂർത്തിയാക്കിയിരിക്കുന്നു.", "avar samayattin mumpe padhati pūrttiyākkirikkunnu."),
    ("By evening she will have cooked everything.", "സായാഹ്നത്തിനകം അവൾ എല്ലാം ഉണ്ടാക്കിയിരിക്കും.", "sāyāhnattinakaṁ avaḷ ellāṁ uṇṭākkirikuṁ."),
    ("We had not heard the news until today.", "ഇന്നുവരെ ആ വാർത്ത ഞങ്ങൾ കേട്ടിരുന്നില്ല.", "innuvare ā vārttha ñaṅṅaḷ kēṭṭirunnilla."),
    ("I have been waiting here for an hour.", "ഒരു മണിക്കൂറായി ഞാൻ ഇവിടെ കാത്തിരിക്കുകയാണ്.", "oru maṇikkūrāyi njān ivide kāttirikkukayāṇ."),
    ("I have eaten; I had eaten before you came.", "ഞാൻ കഴിച്ചിരിക്കുന്നു; നീ വരുന്നതിന് മുമ്പ് ഞാൻ കഴിച്ചിരുന്നു.", "njān kaḻiccirikkunnu; nī varunnatin mumpe njān kaḻiccirunnu."),
    ("The situation tells you which tense sounds natural.", "ഏത് കാലം പ്രകൃതമെന്ന് സന്ദർഭം പറയും.", "ēt kālaᮂ prakr̥tamenn sandarbhaᮂ paṛayuᮂ."),
    ("I read the poem aloud to hear the rhythm.", "ലയം കേൾക്കാൻ ഞാൻ കവിത ഉച്ചരിച്ച് വായിച്ചു.", "layaᮂ kēḷkkān njān kavita uccaricc vāyiccu."),
    ("I have finished my homework before dinner today.", "ഇന്ന് അത്താഴത്തിന് മുമ്പ് ഞാൻ ഹോംവർക്ക് പൂർത്തിയാക്കിയിരിക്കുന്നു.", "inn attāḻattin mumpe njān hōmvarkk pūrttiyākkirikkunnu."),
    ("I checked my answers against the answer key.", "ഉത്തരക്കടലാസുമായി ഉത്തരങ്ങൾ ഞാൻ പരിശോധിച്ചു.", "uttarakaṭalāsumāyi uttaraṅṅaḷ njān pariśōdhiccu."),
)

DATA541 = D(
    ("I have been studying Malayalam for six months.", "ആറു മാസമായി ഞാൻ മലയാളം പഠിക്കുകയാണ്.", "āṛu māsamāyi njān malayāḷaṁ paṭhikkukayāṇ."),
    ("She had been working there before she moved.", "മാറുന്നതിന് മുമ്പ് അവൾ അവിടെ ജോലി ചെയ്തുകൊണ്ടിരുന്നു.", "māṟunnatin mumpe avaḷ avite jōli ceytu koṇṭirunnu."),
    ("We will have been living here ten years next June.", "അടുത്ത ജൂണിൽ പത്തു വർഷമായി ഞങ്ങൾ ഇവിടെ താമസിക്കുകയായിരിക്കും.", "aṭutta jūṇil pathu varṣamāyi ñaṅṅaḷ ivide tāmasikkukayāyirikuṁ."),
    ("They had been waiting since morning.", "പ്രഭാതം മുതൽ അവർ കാത്തിരിക്കുകയായിരുന്നു.", "prabhātaṁ mutal avār kāttirikkukayāyirunnu."),
    ("It has been raining for three days.", "മൂന്നു ദിവസമായി മഴ പെയ്യുകയാണ്.", "mūnnu divasamāyi maḻa peyyukayāṇ."),
    ("He has been reading without a break.", "അവൻ ഇടവിടാതെ വായിക്കുകയാണ്.", "avan iṭaviṭāte vāyikkukayāṇ."),
    ("We have been saving money for the trip.", "യാത്രയ്ക്ക് പണം സംരക്ഷിക്കുകയാണ് ഞങ്ങൾ.", "yātraykku paṇaṁ saṁrakṣikkukayāṇ ñaṅṅaḷ."),
    ("The baby has been crying for an hour.", "ഒരു മണിക്കൂറായി കുഞ്ഞ് കരയുകയാണ്.", "oru maṇikkūrāyi kuññ karayukayāṇ."),
    ("I had been feeling unwell before I saw the doctor.", "ഡോക്ടറെ കാണുന്നതിന് മുമ്പ് എനിക്ക് സുഖമില്ലായിരുന്നു.", "ḍōkṭṭare kāṇunnatin mumpe enikk sukhamillāyirunnu."),
    ("She will have been teaching twenty years soon.", "ഉടൻ ഇരുപത് വർഷമായി അവൾ പഠിപ്പിക്കുകയായിരിക്കും.", "uṭan irupat varṣamāyi avaḷ paṭhippikkukayāyirikuṁ."),
    ("The wind had been howling for hours before the storm broke.", "കൊടുങ്കാറ്റ് പൊട്ടുന്നതിന് മണിക്കൂറുകളോളം കാറ്റ് മുറവെടുത്തുകൊണ്ടിരുന്നു.", "koṭuṅkāṟṭ poṭṭunnatin maṇikkūṟukaḷōḷaṁ kāṟṭ muṛaveṭuttukoṇṭirunnu."),
    ("I have lived in this city for six years.", "ഈ നഗരത്തിൽ ആറു വർഷമായി ഞാൻ താമസിക്കുകയാണ്.", "ī nagarattil āṛu varṣamāyi njān tāmasikkukayāṇ."),
    ("The rain had stopped before we left.", "ഞങ്ങൾ പോകുന്നതിന് മുമ്പ് മഴ നിന്നിരുന്നു.", "ñaṅṅaḷ pōkunatin mumpe maḻa ninnirunnu."),
    ("I listen to the radio in the evening.", "വൈകുന്നേരം ഞാൻ റേഡിയോ കേൾക്കുന്നു.", "vaikunnēraṁ njān rēḍiyō kēḷkkunnu."),
    ("I wrote down what I did each day last week.", "കഴിഞ്ഞ ആഴ്ച ഓരോ ദിവസവും ഞാൻ എന്ത് ചെയ്തുവെന്ന് എഴുതി.", "kaḻiñña āḻca ōrō divasavuᮂ njān ent ceytuvennu eḻuti."),
    ("The teacher explained the grammar point very clearly.", "അധ്യാപകൻ ഗ്രാമർ ഭാഗം വളരെ വ്യക്തമായി വിശദീകരിച്ചു.", "adhyāpakan grāmar bhāgaṁ vaḷare vyaktamāyi viśadīkariccu."),
    ("Different towns use slightly different words for the same idea.", "പ്രാദേശിക വ്യത്യാസം പല സ്ഥലങ്ങളിലും കാണാം.", "prādēśika vyatāsam pala sthalangaḷiluṁ kāṇāᮂ."),
    ("I wrote a few lines in my diary in Malayalam.", "മലയാളത്തിൽ കുറച്ച് വാക്യങ്ങൾ ഡയറിയിൽ എഴുതി.", "malayāḷattil kuṛacca vākyaṅṅaḷ ḍayariyil eḻuti."),
)

DATA542 = D(
    ("I do not want rice right now.", "ഇപ്പോൾ എനിക്ക് ചോറ് വേണ്ട.", "ippōḷ enikk cōṟ vēṇṭa."),
    ("I do not need this book.", "ഈ പുസ്തകം എനിക്ക് വേണ്ടാ.", "ī pustakaṁ enikk vēṇṭā."),
    ("There is no water in the pot.", "ചട്ടിയിൽ വെള്ളമില്ല.", "caṭṭiyil veḷḷamilla."),
    ("There is no bus at this hour.", "ഈ സമയത്ത് ബസില്ല.", "ī samayatt basilla."),
    ("He is not at home.", "അവൻ വീട്ടിലില്ല.", "avan vīṭṭililla."),
    ("We do not have time today.", "ഇന്ന് ഞങ്ങൾക്ക് സമയമില്ല.", "inn ñaṅṅaḷkku samayamilla."),
    ("She does not want to go there.", "അവൾക്ക് അവിടെ പോകാൻ വേണ്ട.", "avaḷkku avite pōkān vēṇṭa."),
    ("I do not know the answer.", "എനിക്ക് ഉത്തരം അറിയില്ല.", "enikk uttaraṁ aṟiyilla."),
    ("They are not coming.", "അവർ വരുന്നില്ല.", "avar varunnilla."),
    ("No, thank you, I do not want tea.", "വേണ്ട, നന്ദി, ചായ വേണ്ട.", "vēṇṭa, nandi, cāya vēṇṭa."),
    ("Is there milk? No, there is not.", "പാലുണ്ടോ? ഇല്ല.", "pāluṇṭō? illa."),
    ("The children said they do not want sweets.", "കുട്ടികൾ മിഠായി വേണ്ടെന്ന് പറഞ്ഞു.", "kuṭṭikaḷ miṭhāyi vēṇṭenn paṟaññu."),
    ("I do not eat meat.", "ഞാൻ മാംസം കഴിക്കുന്നില്ല.", "njān māṁsaṁ kaḻikkunnilla."),
    ("There was no one in the room.", "മുറിയിൽ ആരുമില്ലായിരുന്നു.", "muṛiyil ārumillāyirunnu."),
    ("This is not my umbrella.", "ഇത് എന്റെ കുടയല്ല.", "it enṟe kuṭayalla."),
    ("I do not need your help.", "നിന്റെ സഹായം എനിക്ക് വേണ്ടാ.", "ninṟe sahāyaṁ enikk vēṇṭā."),
    ("They are not hungry.", "അവർക്ക് വിശപ്പില്ല.", "avarkk viśappilla."),
    ("I do not want to wait any longer.", "ഇനിയും കാത്തിരിക്കാൻ എനിക്ക് വേണ്ട.", "iniyuṁ kāttirikkān enikk vēṇṭa."),
    ("We did not find any mistakes in the report.", "റിപ്പോർട്ടിൽ പിശകൊന്നും ഞങ്ങൾ കണ്ടില്ല.", "rippōṭṭil piśakonnuṁ ñaṅṅaḷ kaṇṭilla."),
    ("I already said I do not want it.", "വേണ്ടെന്ന് ഞാൻ നേരത്തെ പറഞ്ഞു.", "vēṇṭenn njān nērattē paṟaññu."),
)
