// Auto-generated from lesson JSON — Phrases & Words tabs
const NEPALI_PHRASES = {
  greetings_1: {
    name: "Greetings",
    color: "#2B6CB0",
    icon: "👋",
    phrases: [
      { en: "What is your name?", mr: "तिम्रो नाम के हो?", roman: "timro nāma ke ho?", hint: "" },
      { en: "How much is this?", mr: "यो कति हो?", roman: "yo kati ho?", hint: "" },
      { en: "Can I use your phone?", mr: "के म तपाईको फोन प्रयोग गर्न सक्छु?", roman: "ke ma tapāīko phona prayoga garna sakchu?", hint: "" },
      { en: "Can you show me on the map?", mr: "के तपाईं मलाई नक्सामा देखाउन सक्नुहुन्छ?", roman: "ke tapāīṃ malāī naksāmā dekhāuna saknuhuncha?", hint: "" },
      { en: "They brought sweets for all the children in our street yesterday.", mr: "उनीहरूले हिजो हाम्रो गल्लीका सबै बच्चाहरूलाई मिठाइ ल्याए।", roman: "unīharūle hijo hāmro gallīkā sabai baccāharūlāī miṭhāi lyāe", hint: "" },
      { en: "How are you today — did you sleep well last night?", mr: "आज तपाईंलाई कस्तो छ — हिजो राम्रोसँग सुत्नुभयो?", roman: "āja tapāīṃlāī kasto cha — hijo rāmrosa~ga sutnubhayo", hint: "" },
      { en: "The children are playing football in the school yard right now.", mr: "बच्चाहरू अहिले विद्यालयको मैदानमा फुटबल खेलिरहेका छन्।", roman: "baccāharū ahile vidyālayako maidānamā phuṭbal khelirahekā chan", hint: "" },
      { en: "Thank you to everyone who helped carry these heavy boxes upstairs.", mr: "यी भारी बाकस माथि लैजान मद्दत गर्ने सबैलाई धन्यवाद।", roman: "yī bhārī bākasa māthi laijāna maddata garne sabailāī dhanyavāda", hint: "" },
      { en: "Both of us will visit the doctor tomorrow morning together.", mr: "हामी दुवै भोलि बिहान सँगै डाक्टरकहाँ जानेछौं।", roman: "hāmī duvai bholi bihāna saṃgai ḍākṭarakahā~ jāne-chauṃ", hint: "" },
      { en: "He goes to work by bicycle when the weather is pleasant.", mr: "मौसम राम्रो हुँदा ऊ साइकलमा काममा जान्छ।", roman: "mausama rāmro hu~dā ū sāikalamā kāmamā jān-cha", hint: "" },
      { en: "We need to eat on time if we want to stay healthy.", mr: "स्वस्थ रहन हामी समयमै खानुपर्छ।", roman: "svastha rahana hāmī samayamai khānuparcha", hint: "" },
      { en: "Please give this packet to your sister when you meet her.", mr: "उनलाई भेट्दा कृपया यो प्याकेट दिनुहोस्।", roman: "unalāī bheṭdā kṛpayā yo pyākeṭa dinuhos", hint: "" },
      { en: "They play football in the field after school.", mr: "उनीहरू स्कूल पछि मैदानमा फुटबल खेल्छन्", roman: "unīharū skūl pachi maidānamā phuṭbal khelchan", hint: "" },
      { en: "The dog runs quickly along the narrow street.", mr: "कुकुर पातलो बाटोमा छिटो दौडन्छ", roman: "kukura pātalo bāṭomā chiṭo dauḍancha", hint: "" },
      { en: "The young guide is brave enough to cross the river on a rope bridge.", mr: "युवा गाइडले डोरीको पुलबाट नदी तर्न साहस देखाउनुभएको छ।", roman: "yuvā gāiḍale ḍorīko pulabāṭa nadī tarna sāhas dekhāunubhaeko cha", hint: "" },
      { en: "After the long trek I am fine, though my legs still feel a little tired.", mr: "लामो पैदल यात्रापछि म ठिक छु, तर खुट्टा अलि थाकेको अनुभव हुन्छ।", roman: "lāmo paidala yātrāpachi ma ṭhika cha, tara khuṭṭā ali thākeko anubhava huncha", hint: "" },
    ]
  },
  travel_1: {
    name: "Travel",
    color: "#38A169",
    icon: "🚌",
    phrases: [
      { en: "Can you help me?", mr: "के तपाईं मलाई मद्दत गर्न सक्नुहुन्छ?", roman: "ke tapāīṃ malāī maddata garna saknuhuncha?", hint: "" },
      { en: "Do you speak English?", mr: "के तपाई अंग्रेजी बोल्नुहुन्छ?", roman: "ke tapāī aṃgrejī bolnuhuncha?", hint: "" },
      { en: "I haven't done anything wrong", mr: "मैले कुनै गल्ती गरेको छैन", roman: "maile kunai galtī gareko chaina", hint: "" },
      { en: "One language is never enough", mr: "एक भाषा कहिल्यै पर्याप्त छैन", roman: "eka bhāṣā kahilyai paryāpta chaina", hint: "" },
      { en: "This blue umbrella is mine, but that black one belongs to my brother.", mr: "यो नीलो छाता मेरो हो, तर त्यो कालो भाइको हो।", roman: "yo nīlo chātā mero ho, tara tyo kālo bhāiko ho", hint: "" },
      { en: "This is my grammar book, and I read a few pages every day.", mr: "यो मेरो व्याकरणको किताब हो, म हरेक दिन केही पृष्ठ पढ्छु।", roman: "yo mero vyākaraṇako kitāba ho, ma hareka dina kehī pr̥ṣṭha paḍh-chu", hint: "" },
      { en: "When you address elders, you use this polite plural form of “you”.", mr: "जेठो मानिसलाई सम्बोधन गर्दा तपाईं यस्तो सम्मानजनक बहुवचन प्रयोग गर्नुहुन्छ।", roman: "jeṭho mānisalāī sambodhana gardā tapāīṃ yasto sammānajanaka bahuvacana prayog garnuhuncha", hint: "" },
      { en: "How are you all feeling after such a long bus journey?", mr: "यति लामो बस यात्रापछि तपाईंहरू सबैलाई कस्तो लागिरहेको छ?", roman: "yati lāmo basa yātrāpachi tapāīṃharū sabailāī kasto lāgiriheko cha", hint: "" },
      { en: "You two should finish your homework before you turn on the TV.", mr: "तपाईं दुईले टिभी खोल्नुअघि गृहकार्य सकाउनुहोस्।", roman: "tapāīṃ duīle ṭibhī kholnuaghi gr̥hakārya sakāunuhos", hint: "" },
      { en: "She comes to our house every Dashain to meet my grandmother.", mr: "उनी हरेक दशैं मेरी हजुरआमालाई भेट्न हाम्रो घर आउँछिन्।", roman: "unī hareka daśai merī hajurāmālāī bheṭna hāmro ghara āu~chin", hint: "" },
      { en: "They will go to Pokhara next month for a short holiday.", mr: "उनीहरू अर्को महिना छोटो बिदामा पोखरा जानेछन्।", roman: "unīharū arko mahinā choṭo bidāmā pokharā jāne-chan", hint: "" },
      { en: "I eat rice at home almost every day.", mr: "म प्रायः हरेक दिन घरमा भात खान्छु", roman: "ma prāyaḥ hareka dina gharamā bhāta khānchu", hint: "" },
      { en: "I know the answer to this difficult question.", mr: "मलाई यो गाह्रो प्रश्नको उत्तर थाहा छ", roman: "malāī yo gāhro prasnako uttara thāhā cha", hint: "" },
      { en: "Birds fly high above the trees in the morning.", mr: "चराहरू बिहान रूखमाथि माथि उड्छन्", roman: "carāharū bihāna rūkhamāthi māthi uḍchan", hint: "" },
      { en: "My sister is happy because she passed her exam with high marks.", mr: "मेरी दिदी खुसी छिन् किनभने उनले राम्रो नम्बरले परीक्षा पास गरिन्।", roman: "merī didī khusī chin kinabhane unale rāmro nambarale parīkṣā pās garin", hint: "" },
      { en: "This winter jacket is new, so it keeps me warm on cold mornings.", mr: "यो जाडो कोट नयाँ छ, त्यसैले चिसो बिहान पनि न्यानो राख्छ।", roman: "yo jāḍo koṭa nayā~ cha, tyasaile ciso bihāna pani nyāno rākh-cha", hint: "" },
    ]
  },
  food_1: {
    name: "Food",
    color: "#DD6B20",
    icon: "🍛",
    phrases: [
      { en: "That is a good idea", mr: "त्यो राम्रो विचार हो", roman: "tyo rāmro vicāra ho", hint: "" },
      { en: "Is there someone who speaks English?", mr: "अंग्रेजी बोल्ने कोही छ?", roman: "aṃgrejī bolne kohī cha?", hint: "" },
      { en: "I want to talk to a lawyer", mr: "म वकिलसँग कुरा गर्न चाहन्छु", roman: "ma vakilasa~ga kurā garna cāhanchu", hint: "" },
      { en: "I always tell people clearly that I am still learning Nepali.", mr: "म अझै नेपाली सिकिरहेको छु भनेर सबैलाई स्पष्ट भन्छु।", roman: "ma ajhai nepālī sikiriheko chu bhanera sabailāī spaṣṭa bhan-chu", hint: "" },
      { en: "That old house on the hill looks empty every evening.", mr: "डाँडामा रहेको त्यो पुरानो घर हरेक साँझ खाली देखिन्छ।", roman: "ḍā~ḍāmā raheko tyo purāno ghara hareka sā~jha khālī dekhincha", hint: "" },
      { en: "That quiet man at the door is my friend from college.", mr: "ढोकामा उभिएका त्यो शान्त मान्छे मेरो कलेजको साथी हो।", roman: "ḍhokāmā ubhieka tyo śānta mānche mero kalejako sāthī ho", hint: "" },
      { en: "Those honoured guests smiled when we welcomed them at the gate.", mr: "ती माननीय पाहुनाहरूले हामीले ढोकामा स्वागत गर्दा मुस्कुराए।", roman: "tī mānanīya pāhunāharūle hāmīle ḍhokāmā svāgata gardā muskurāe", hint: "" },
      { en: "We are all fine, and we hope your family is healthy too.", mr: "हामी सबै सन्चै छौं, र तपाईंको परिवार पनि सन्चो होस् भन्ने कामना गर्छौं।", roman: "hāmī sabai sancai chauṃ, ra tapāīṃko parivāra pani sanco hos bhanne kāmanā gar-chauṃ", hint: "" },
      { en: "Many people gathered in the square to hear the announcement.", mr: "धेरै मानिसहरू घोषणा सुन्न चोकमा जम्मा भए।", roman: "dherai mānisaharū ghoṣaṇā sunna cokamā jamā bhae", hint: "" },
      { en: "We see the mountains clearly from the roof of our school.", mr: "हामी विद्यालयको छानाबाट पहाड स्पष्ट देख्छौं।", roman: "hāmī vidyālayako chānābāṭa pahāḍa spaṣṭa dekh-chauṃ", hint: "" },
      { en: "I will come to your party if I finish work early.", mr: "काम छिटो सकेमा म तपाईंको पार्टीमा आउनेछु।", roman: "kāma chiṭo sakema ma tapāīṃko pārṭīmā āune-chu", hint: "" },
      { en: "You drink water when you feel thirsty.", mr: "तिमीलाई तिर्खा लाग्दा तिमी पानी पिउछौ", roman: "timīlāī tirkhā lāgdā timī pānī piuchau", hint: "" },
      { en: "You understand what the teacher says in class.", mr: "तपाईंले कक्षामा शिक्षकले भनेको कुरा बुझ्नुहुन्छ", roman: "tapāīṃle kakṣāmā śikṣakale bhaneko kurā bujhnuhuncha", hint: "" },
      { en: "Water flows fast in the river during heavy rain.", mr: "पानी भारी पर्दा नदीमा छिटो बग्छ", roman: "pānī bhārī pardā nadīmā chiṭo bagcha", hint: "" },
      { en: "This thick dictionary on my desk belongs to the library.", mr: "मेरो टेबलमा रहेको यो मोटो शब्दकोश पुस्तकालयको हो।", roman: "mero ṭebalamā raheko yo moṭo śabdakośa pustakālayako ho", hint: "" },
      { en: "Who is she — the woman in the blue sari near the stage?", mr: "उनी को हुन् — मञ्च नजिक नीलो साडी लगाएकी महिला?", roman: "unī ko hun — mañca najika nīlo sāḍī lagāekī mahilā", hint: "" },
    ]
  },
  daily_1: {
    name: "Daily life",
    color: "#805AD5",
    icon: "🏠",
    phrases: [
      { en: "Do you speak Nepali?", mr: "नेपाली बोल्नुहुन्छ ?", roman: "nepālī bolnuhuncha ?", hint: "" },
      { en: "Where is the toilet?", mr: "शौचालय कहाँ छ?", roman: "śaucālaya kahā~ cha?", hint: "" },
      { en: "How do I get to _____?", mr: "म कसरी _____ मा पुग्न सक्छु?", roman: "ma kasarī _____ mā pugna sakchu?", hint: "" },
      { en: "When you speak politely, you often use this respectful form of “you”.", mr: "तपाईं विनम्रतापूर्वक बोल्दा यो सम्मानजनक “तपाईं” प्रयोग गर्नुहुन्छ।", roman: "tapāīṃ vinamratāpūrvaka boldā yo sammānajanaka “tapāīṃ” prayog garnuhuncha", hint: "" },
      { en: "My full name is on my passport, so please read it slowly.", mr: "मेरो पूरा नाम राहदानीमा छ, कृपया ढिलो पढ्नुहोस्।", roman: "mero pūrā nāma rāhadānīmā cha, kṛpayā ḍhilo paḍhnuhos", hint: "" },
      { en: "He is a math teacher who explains every problem very patiently.", mr: "उहाँ गणित शिक्षक हुनुहुन्छ जसले हरेक प्रश्न धैर्यपूर्वक सम्झाउनुहुन्छ।", roman: "uhā~ gaṇita śikṣaka hunuhuncha jasle hareka praśna dhairypūrvaka samjhāunuhuncha", hint: "" },
      { en: "All of you please sit down; tea will be ready in five minutes.", mr: "तपाईं सबै कृपया बस्नुहोस्; पाँच मिनेटमा चिया तयार हुन्छ।", roman: "tapāīṃ sabai kṛpayā basnuhos; pāñca mineṭamā ciyā tayāra huncha", hint: "" },
      { en: "The honoured guests arrived exactly when the programme began.", mr: "माननीय पाहुनाहरू कार्यक्रम सुरु हुँदै गर्दा ठ्याक्कै आइपुग्नुभयो।", roman: "mānanīya pāhunāharū kāryakrama suru hu~dai gardā ṭhyākkai āipugnubhayo", hint: "" },
      { en: "All human beings deserve kindness, no matter where they are born.", mr: "जन्म कतै भए पनि सबै मानव जातिलाई दया र सम्मान पाउनुपर्छ।", roman: "janma katai bhae pani sabai mānava jātilāī dayā ra sammāna pāunuparcha", hint: "" },
      { en: "The neighbours speak quietly in the yard after dinner.", mr: "छिमेकीहरू बेलुका खानापछि आँगनमा शान्तिसँग बोल्छन्।", roman: "chimekīharū belukā khānapachi ā~ganamā śāntisa~ga bol-chan", hint: "" },
      { en: "Please come a little earlier so we can talk before the meeting.", mr: "भेटघाटअघि कुरा गर्न कृपया अलि छिटो आउनुहोस्।", roman: "bheṭghāṭaghi kurā garna kṛpayā ali chiṭo āunuhos", hint: "" },
      { en: "He goes to school by bus every morning.", mr: "ऊ हरेक बिहान बसमा स्कुल जान्छ", roman: "ū hareka bihāna basamā skula jāncha", hint: "" },
      { en: "He likes to swim in the river on hot days.", mr: "उनलाई गर्मी दिनमा नदीमा पौडी खेल्न मन पर्छ", roman: "unalāī garmī dinamā nadīmā pauḍī khelna mana parcha", hint: "" },
      { en: "The sun rises early behind the eastern hills.", mr: "सूर्य पूर्वी पहाडपछाडि बिहानै उदाउँछ", roman: "sūrya pūrvī pahāḍapachāḍi bihānai udāu~cha", hint: "" },
      { en: "That stone house on the hill looks older than our village temple.", mr: "डाँडामा रहेको त्यो ढुङ्गे घर हाम्रो गाउँको मन्दिरभन्दा पुरानो देखिन्छ।", roman: "ḍā~ḍāmā raheko tyo ḍhu~ge ghara hāmro gāu~ko mandirabhandā purāno dekhincha", hint: "" },
      { en: "Where is the clean toilet on this floor — I could not find the sign.", mr: "यस तल्लामा सफा शौचालय कहाँ छ — मैले संकेत पाइन।", roman: "yasa tallāmā safā śaucālaya kahā~ cha — maile saṅketa pāina", hint: "" },
    ]
  },
  shopping_1: {
    name: "Shopping",
    color: "#D69E2E",
    icon: "🛒",
    phrases: [
      { en: "Speak to me in Nepali", mr: "मसँग नेपालीमा कुरा गर्नुहोस्", roman: "masa~ga nepālīmā kurā garnuhos", hint: "" },
      { en: "I will stay for one night", mr: "म एक रात बस्नेछु", roman: "ma eka rāta basnechu", hint: "" },
      { en: "Where can I find hotels?", mr: "म कहाँ होटल पाउन सक्छु?", roman: "ma kahā~ hoṭala pāuna sakchu?", hint: "" },
      { en: "That famous writer lives in Pokhara, and everyone says he is very kind.", mr: "उ प्रसिद्ध लेखक पोखरामा बस्छन् र सबैले उनलाई धेरै दयालु भन्छन्।", roman: "u prasiddha lekhaka pokharāmā baschan ra sabaile unalāī dherai dayālu bhan-chan", hint: "" },
      { en: "What is your name, and which village are you from originally?", mr: "तपाईंको नाम के हो र मूलतः कुन गाउँका हुनुहुन्छ?", roman: "tapāīṃko nāma ke ho ra mūlataḥ kuna gāu~kā hunuhuncha", hint: "" },
      { en: "She looks happy today because her sister finally arrived.", mr: "उनी आज खुसी देखिन्छिन् किनभने उनकी बहिनी अन्त्यमा आइन्।", roman: "unī āja khusī dekhin-chin kinabhane unakī bahinī antyamā āin", hint: "" },
      { en: "All people in this village help each other during the harvest.", mr: "यस गाउँका सबै मानिसहरू बाली काट्दा एकअर्कालाई मद्दत गर्छन्।", roman: "yasa gāu~kā sabai mānisaharū bālī kāṭdā ekarkālāī maddata gar-chan", hint: "" },
      { en: "Please give your elders respect even when you disagree with them.", mr: "तपाईंको विचार नमिल्दा पनि जेठो मानिसलाई सम्मान दिनुहोस्।", roman: "tapāīṃko vicāra namildā pani jeṭho mānisalāī sammāna dinuhos", hint: "" },
      { en: "Every morning I do my exercises before I eat breakfast.", mr: "म हरेक बिहान नास्ता खानुअघि व्यायाम गर्छु।", roman: "ma hareka bihāna nāstā khānuaghi vyāyāma gar-chu", hint: "" },
      { en: "I read the news online before I start my homework.", mr: "म गृहकार्य सुरु गर्नुअघि अनलाइनमा समाचार पढ्छु।", roman: "ma gr̥hakārya suru garnuaghi analāinamā samācāra paḍh-chu", hint: "" },
      { en: "I want to see the Himalaya from the plane window one day.", mr: "म एक दिन विमानको झ्यालबाट हिमाल हेर्न चाहन्छु।", roman: "ma eka dina vimānako jhyālabāṭa himāla herna cāhan-chu", hint: "" },
      { en: "She reads a book quietly in her room.", mr: "उनी आफ्नो कोठामा शान्तिसँग किताब पढ्छिन्", roman: "unī āphno koṭhāmā śāntisaṃga kitāba paḍhchin", hint: "" },
      { en: "She goes to school with her younger sister.", mr: "उनी सानो बहिनीसँग विद्यालय जान्छिन्", roman: "unī sāno bahinīsaṃga vidyālaya jānchin", hint: "" },
      { en: "I am a science student in grade ten at this school.", mr: "म यस विद्यालयमा कक्षा दशको विज्ञान विद्यार्थी हुँ।", roman: "ma yasa vidyālayamā kakṣā daśako vijñāna vidyārthī hu~", hint: "" },
      { en: "We are close friends who have studied Nepali together for two years.", mr: "हामी दुई वर्षदेखि सँगै नेपाली पढेका घनिष्ठ साथी हौं।", roman: "hāmī duī varṣadekhi saṃgai nepālī paḍheka ghaniṣṭha sāthī hauṃ", hint: "" },
      { en: "There is no doubt that honest work always brings peace of mind.", mr: "इमान्दार परिश्रमले मनमा शान्ति ल्याउँछ भन्नेमा कुनै शंका छैन।", roman: "imāndāra pariśramale manamā śānti lyāu~cha bhanne-mā kunai śaṃkā chaina", hint: "" },
    ]
  },
  emergency_1: {
    name: "Emergency",
    color: "#E53E3E",
    icon: "🚨",
    phrases: [
      { en: "How do you say ... in Nepali?", mr: "नेपालीमा कसरी भन्नु हुन्छ...?", roman: "nepālīmā kasarī bhannu huncha...?", hint: "" },
      { en: "What time is breakfast?", mr: "बिहानको खाजा कति बजे हो?", roman: "bihānako khājā kati baje ho?", hint: "" },
      { en: "Where can I find restaurants?", mr: "म रेस्टुरेन्टहरू कहाँ पाउन सक्छु?", roman: "ma resṭurenṭaharū kahā~ pāuna sakchu?", hint: "" },
      { en: "We walk together to the temple every Saturday morning.", mr: "हामी हरेक शनिबार बिहान मन्दिर सँगै जान्छौं।", roman: "hāmī hareka śanibāra bihāna mandira saṃgai jān-chauṃ", hint: "" },
      { en: "After the long journey I am fine, but I still need a little rest.", mr: "लामो यात्रापछि म ठिक छु, तर अलि आराम चाहिन्छ।", roman: "lāmo yātrāpachi ma ṭhika cha, tara ali ārāma cāhincha", hint: "" },
      { en: "We are happy because our team won the match last night.", mr: "हामी खुसी छौं किनभने हाम्रो टोलीले हिजो रात खेल जित्यो।", roman: "hāmī khusī chauṃ kinabhane hāmro ṭolīle hijo rāta khela jityo", hint: "" },
      { en: "Welcome to you all; we are glad you could come to our small party.", mr: "सबैलाई स्वागत छ; हामी खुसी छौं तपाईंहरू हाम्रो सानो भेटघाटमा आउन सक्नुभयो।", roman: "sabailāī svāgata cha; hāmī khusī chauṃ tapāīṃharū hāmro sāno bheṭghāṭamā āuna saknubhayo", hint: "" },
      { en: "Both of my parents work, so both of us children help at home.", mr: "मेरा आमाबुबा दुवै काम गर्नुहुन्छ, त्यसैले हामी दाजुभाइ घरमा मद्दत गर्छौं।", roman: "merā āmābubā duvai kāma garnuhuncha, tyasaile hāmī dājubhāi gharamā maddata gar-chauṃ", hint: "" },
      { en: "You eat fresh fruit every day because the doctor advised you.", mr: "डाक्टरले सल्लाह दिएकाले तिमी हरेक दिन ताजा फलफूल खान्छौ।", roman: "ḍākṭarale sallāha diekāle timī hareka dina tājā phalphūl khān-chau", hint: "" },
      { en: "You write a long email when you want to explain something important.", mr: "तिमी महत्त्वपूर्ण कुरा बुझाउन चाहँदा लामो इमेल लेख्छौ।", roman: "timī mahattvapūrṇa kurā bujhāuna cāha~dā lāmo imela lekh-chau", hint: "" },
      { en: "She likes to speak slowly when she teaches beginners.", mr: "उनी सुरुवाती विद्यार्थीलाई पढाउँदा बिस्तारै बोल्छिन्।", roman: "unī suruvātī vidyārthīlāī paḍhāu~dā bistārai bol-chin", hint: "" },
      { en: "We speak Nepali with our friends and family.", mr: "हामी साथी र परिवारसँग नेपाली बोल्छौं", roman: "hāmī sāthī ra parivārsaṃga nepālī bolchauṃ", hint: "" },
      { en: "I work in an office from Monday to Friday.", mr: "म सोमबारदेखि शुक्रबारसम्म कार्यालयमा काम गर्छु", roman: "ma somabāradekhi śukrabārasamma kāryālayamā kāma garchu", hint: "" },
      { en: "Our principal is a kind teacher who listens to every student.", mr: "हाम्रो प्रधानाध्यापक दयालु शिक्षक हुनुहुन्छ जसले हरेक विद्यार्थीको कुरा सुन्नुहुन्छ।", roman: "hāmro pradhānādhyāpaka dayālu śikṣaka hunuhuncha jasle hareka vidyārthīko kurā sunnuhuncha", hint: "" },
      { en: "The neighbourhood children are playing cricket in the narrow lane.", mr: "छिमेकीका बच्चाहरू पातलो गल्लीमा क्रिकेट खेलिरहेका छन्।", roman: "chimekīkā baccāharū pātalo gallīmā krikeṭa khelirahekā chan", hint: "" },
      { en: "My father is tall, so he can easily reach the top shelf.", mr: "मेरो बुबा अग्लो हुनुहुन्छ, त्यसैले माथिलो ताक सजिलै पुग्नुहुन्छ।", roman: "mero bubā aglo hunuhuncha, tyasaile māthilo tāka sajilai pugnuhuncha", hint: "" },
    ]
  },
};

const NEPALI_DICTIONARY = {
  basics_1: {
    name: "Basic words",
    words: [
      { en: "soul", mr: "आत्मा", roman: "ātmā" },
      { en: "rice", mr: "चामल", roman: "cāmala" },
      { en: "today", mr: "आज", roman: "āja" },
      { en: "two", mr: "दुई", roman: "duī" },
      { en: "Thank you", mr: "धन्यवाद", roman: "dhanyavāda" },
      { en: "My name is...", mr: "मेरो नाम हो...", roman: "mero nāma ho..." },
      { en: "Goodbye", mr: "अलविदा", roman: "alavidā" },
      { en: "I am a student", mr: "म एक विद्यार्थी हुँ", roman: "ma eka vidyārthī hu~" },
      { en: "We are happy", mr: "हामी खुसी छौं", roman: "hāmī khusī chauṃ" },
      { en: "Good idea", mr: "राम्रो विचार", roman: "rāmro vicāra" },
      { en: "Please come in", mr: "कृपया भित्र आउनुहोस्", roman: "kṛpayā bhitra āunuhos" },
      { en: "I miss you", mr: "म तिमीलाई सम्झन्छु", roman: "ma timīlāī samjhanchu" },
      { en: "Congratulations", mr: "बधाई छ", roman: "badhāī cha" },
      { en: "I don't understand", mr: "मैले बुझिन", roman: "maile bujhina" },
      { en: "Yes, a little", mr: "हो, थोरै", roman: "ho, thorai" },
      { en: "I'm so sorry", mr: "मलाई धेरै माफ गर्नुहोस्", roman: "malāī dherai māpha garnuhos" },
    ]
  },
  family_1: {
    name: "Family",
    words: [
      { en: "food", mr: "खाना", roman: "khānā" },
      { en: "day", mr: "दिन", roman: "dina" },
      { en: "come", mr: "आउनुहोस्", roman: "āunuhos" },
      { en: "body", mr: "शरीर", roman: "śarīra" },
      { en: "Hello (formal)", mr: "नमस्कार (औपचारिक)", roman: "namaskāra (aupacārika)" },
      { en: "No", mr: "छैन", roman: "chaina" },
      { en: "Good morning", mr: "शुभ प्रभात", roman: "śubha prabhāta" },
      { en: "You are a teacher", mr: "तपाई शिक्षक हुनुहुन्छ", roman: "tapāī śikṣaka hunuhuncha" },
      { en: "She is beautiful", mr: "उनी सुन्दर छिन्", roman: "unī sundara chin" },
      { en: "Very good", mr: "धेरै राम्रो", roman: "dherai rāmro" },
      { en: "Have you eaten?", mr: "खानु भयो ?", roman: "khānu bhayo ?" },
      { en: "No problem", mr: "कुनै समस्या छैन", roman: "kunai samasyā chaina" },
      { en: "Good luck", mr: "शुभकामना", roman: "śubhakāmanā" },
      { en: "Please speak slowly", mr: "कृपया बिस्तारै बोल्नुहोस्", roman: "kṛpayā bistārai bolnuhos" },
      { en: "Excuse me", mr: "मलाई माफ गर्नुहोस्", roman: "malāī māpha garnuhos" },
      { en: "Please speak more slowly", mr: "कृपया अझ बिस्तारै बोल्नुहोस्", roman: "kṛpayā ajha bistārai bolnuhos" },
    ]
  },
  verbs_1: {
    name: "Common verbs",
    words: [
      { en: "name", mr: "नाम", roman: "nāma" },
      { en: "house", mr: "घर", roman: "ghara" },
      { en: "tea", mr: "चिया", roman: "ciyā" },
      { en: "yes", mr: "हो", roman: "ho" },
      { en: "How are you?", mr: "कस्तो छ ?", roman: "kasto cha ?" },
      { en: "Please", mr: "कृपया", roman: "kṛpayā" },
      { en: "Good night", mr: "शुभ रात्रि", roman: "śubha rātri" },
      { en: "This is my book", mr: "यो मेरो किताब हो", roman: "yo mero kitāba ho" },
      { en: "He was brave", mr: "उनी बहादुर थिए", roman: "unī bahādura thie" },
      { en: "Well done", mr: "राम्रो भयो", roman: "rāmro bhayo" },
      { en: "I'm hungry", mr: "मलाई भोक लागेको छ", roman: "malāī bhoka lāgeko cha" },
      { en: "Get well soon", mr: "छिट्टै निको हुनुहोस्", roman: "chiṭṭai niko hunuhos" },
      { en: "See you", mr: "भेटौँला", roman: "bheṭau~lā" },
      { en: "Please say that again", mr: "कृपया फेरि भन्नुहोस्", roman: "kṛpayā pheri bhannuhos" },
      { en: "Sorry", mr: "माफ गर्नुहोस्", roman: "māpha garnuhos" },
      { en: "Look out!", mr: "हेर!", roman: "hera!" },
    ]
  },
  nature_1: {
    name: "Nature",
    words: [
      { en: "water", mr: "पानी", roman: "pānī" },
      { en: "good", mr: "राम्रो", roman: "rāmro" },
      { en: "one", mr: "एउटा", roman: "euṭā" },
      { en: "Welcome", mr: "स्वागत छ", roman: "svāgata cha" },
      { en: "I am fine", mr: "म ठिक छु", roman: "ma ṭhika chu" },
      { en: "I love you", mr: "म तिमीलाई माया गर्छु", roman: "ma timīlāī māyā garchu" },
      { en: "Help!", mr: "मद्दत गर्नुहोस्!", roman: "maddata garnuhos!" },
      { en: "This is my friend", mr: "यो मेरो साथी हो", roman: "yo mero sāthī ho" },
      { en: "I'm so happy", mr: "म धेरै खुसी छु", roman: "ma dherai khusī chu" },
      { en: "Come in", mr: "भित्र आउनुहोस्", roman: "bhitra āunuhos" },
      { en: "Take care", mr: "ख्याल गर्नु होला", roman: "khyāla garnu holā" },
      { en: "No worries", mr: "कुनै चिन्ता छैन", roman: "kunai cintā chaina" },
      { en: "I'm sorry", mr: "मलाई माफ गर्नुहोस्", roman: "malāī māpha garnuhos" },
      { en: "Please write it down", mr: "कृपया यसलाई लेख्नुहोस्", roman: "kṛpayā yasalāī lekhnuhos" },
      { en: "You're welcome", mr: "तपाईंलाई स्वागत छ", roman: "tapāīṃlāī svāgata cha" },
      { en: "Good evening", mr: "शुभ साँझ", roman: "śubha sā~jha" },
    ]
  },
};
