import json

DATA_FILE = "data_odia.json"

lessons = {
    579: {
        "url": "\"Excuse me...\" polite phrases in Odia",
        "rows": [
            ["Excuse me", "କ୍ଷମା କରନ୍ତୁ", "kshama karantu"],
            ["Excuse me, where is the bus stop?", "କ୍ଷମା କରନ୍ତୁ, ବସ୍ ଷ୍ଟପ୍ କେଉଁଠି?", "kshama karantu, bas sthap keunthi?"],
            ["Excuse me, can you help me?", "କ୍ଷମା କରନ୍ତୁ, ଆପଣ ମୋତେ ସାହାଯ୍ୟ କରିପାରିବେ କି?", "kshama karantu, aapana mote sahaayya kariparibe ki?"],
            ["Excuse me, what time is it?", "କ୍ଷମା କରନ୍ତୁ, ବେଳ କେତେ ହେଲା?", "kshama karantu, bela kete helaa?"],
            ["Excuse me, I didn't understand", "କ୍ଷମା କରନ୍ତୁ, ମୁଁ ବୁଝିଲି ନାହିଁ", "kshama karantu, mun bujhili naahiin"],
            ["Excuse me, may I sit here?", "କ୍ଷମା କରନ୍ତୁ, ମୁଁ ଏଠି ବସିପାରିବି କି?", "kshama karantu, mun ethi basipaaribi ki?"],
            ["Excuse me, I need to go", "କ୍ଷମା କରନ୍ତୁ, ମୋତେ ଯିବାକୁ ହେବ", "kshama karantu, mote jibaaku heba"],
            ["Excuse me, is this seat taken?", "କ୍ଷମା କରନ୍ତୁ, ଏହି ଆସନ ଖାଲି ଅଛି କି?", "kshama karantu, ehi aasana khaali achhi ki?"],
            ["Excuse me, where is the hospital?", "କ୍ଷମା କରନ୍ତୁ, ଡାକ୍ତରଖାନା କେଉଁଠି?", "kshama karantu, daaktarakhaanaa keunthi?"],
            ["Excuse me, I am looking for this address", "କ୍ଷମା କରନ୍ତୁ, ମୁଁ ଏହି ଠିକଣା ଖୋଜୁଛି", "kshama karantu, mun ehi thikanaa khojuchhi"],
            ["Pardon me", "ମାଫ କରନ୍ତୁ", "maaph karantu"],
            ["Excuse me, could you repeat that?", "କ୍ଷମା କରନ୍ତୁ, ଆପଣ ସେଇଟା ପୁଣିଥରେ କହିପାରିବେ କି?", "kshama karantu, aapana seitaa punithare kahiparibe ki?"],
            ["Excuse me, how much does this cost?", "କ୍ଷମା କରନ୍ତୁ, ଏହାର ଦାମ କେତେ?", "kshama karantu, ehaara daama kete?"],
            ["Excuse me, I have a question", "କ୍ଷମା କରନ୍ତୁ, ମୋର ଏକ ପ୍ରଶ୍ନ ଅଛି", "kshama karantu, mora eka prashna achhi"],
            ["Excuse me, is anyone sitting here?", "କ୍ଷମା କରନ୍ତୁ, ଏଠି କେହି ବସିଛନ୍ତି କି?", "kshama karantu, ethi kehi basichhanti ki?"],
            ["Excuse me, which way to the station?", "କ୍ଷମା କରନ୍ତୁ, ଷ୍ଟେସନ୍ କେଉଁ ପଟେ?", "kshama karantu, stesan keun pate?"],
            ["Excuse me, I'm sorry to bother you", "କ୍ଷମା କରନ୍ତୁ, ଆପଣଙ୍କୁ ବିରକ୍ତ କଲି", "kshama karantu, aapananku birakta kali"],
            ["Excuse me, may I pass?", "କ୍ଷମା କରନ୍ତୁ, ମୁଁ ଯାଇପାରିବି କି?", "kshama karantu, mun jaaipaaribi ki?"],
        ],
    },
    580: {
        "url": "\"May I...?\" permission patterns in Odia",
        "rows": [
            ["May I come in?", "ମୁଁ ଭିତରକୁ ଆସିପାରିବି କି?", "mun bhitaraku aasipaaribi ki?"],
            ["May I sit here?", "ମୁଁ ଏଠି ବସିପାରିବି କି?", "mun ethi basipaaribi ki?"],
            ["May I speak?", "ମୁଁ କଥା କହିପାରିବି କି?", "mun kathaa kahipaaribi ki?"],
            ["May I go now?", "ମୁଁ ଏବେ ଯାଇପାରିବି କି?", "mun ebe jaaipaaribi ki?"],
            ["May I use your phone?", "ମୁଁ ଆପଣଙ୍କ ଫୋନ୍ ବ୍ୟବହାର କରିପାରିବି କି?", "mun aapananka phon byabahaar karipaaribi ki?"],
            ["May I ask you something?", "ମୁଁ ଆପଣଙ୍କୁ କିଛି ପଚାରିପାରିବି କି?", "mun aapananku kichhi pachaaripaaribi ki?"],
            ["May I borrow your pen?", "ମୁଁ ଆପଣଙ୍କ କଲମ ନେଇପାରିବି କି?", "mun aapananka kalama neipaaribi ki?"],
            ["May I open the window?", "ମୁଁ ଝରକା ଖୋଲିପାରିବି କି?", "mun jharakaa kholipaaribi ki?"],
            ["May I take a photo?", "ମୁଁ ଏକ ଫଟୋ ନେଇପାରିବି କି?", "mun eka photo neipaaribi ki?"],
            ["May I have some water?", "ମୁଁ ଟିକେ ପାଣି ପାଇପାରିବି କି?", "mun tike paani paaipaaribi ki?"],
            ["May I leave early today?", "ମୁଁ ଆଜି ଛୁଟିରେ ଯାଇପାରିବି କି?", "mun aaji chhutiire jaaipaaribi ki?"],
            ["May I see your book?", "ମୁଁ ଆପଣଙ୍କ ବହି ଦେଖିପାରିବି କି?", "mun aapananka bahi dekhipaaribi ki?"],
            ["May I say something?", "ମୁଁ କିଛି କହିପାରିବି କି?", "mun kichhi kahipaaribi ki?"],
            ["May I help you?", "ମୁଁ ଆପଣଙ୍କୁ ସାହାଯ୍ୟ କରିପାରିବି କି?", "mun aapananku sahaayya karipaaribi ki?"],
            ["May I close the door?", "ମୁଁ କବାଟ ବନ୍ଦ କରିପାରିବି କି?", "mun kabaata banda karipaaribi ki?"],
            ["May I take your leave?", "ମୁଁ ଆପଣଙ୍କ ବିଦାୟ ନେଇପାରିବି କି?", "mun aapananka bidaay neipaaribi ki?"],
            ["May I know your name?", "ମୁଁ ଆପଣଙ୍କ ନାମ ଜାଣିପାରିବି କି?", "mun aapananka naama jaanipaaribi ki?"],
            ["May I try this?", "ମୁଁ ଏହା ଚେଷ୍ଟା କରିପାରିବି କି?", "mun ehaa cheshtaa karipaaribi ki?"],
        ],
    },
    581: {
        "url": "\"Could you please...?\" request patterns in Odia",
        "rows": [
            ["Could you please help me?", "ଦୟାକରି ଆପଣ ମୋତେ ସାହାଯ୍ୟ କରିପାରିବେ କି?", "dayaakari aapana mote sahaayya kariparibe ki?"],
            ["Could you please speak slowly?", "ଦୟାକରି ଧୀରେ କୁହନ୍ତୁ", "dayaakari dhiire kuhantu"],
            ["Could you please repeat that?", "ଦୟାକରି ପୁଣିଥରେ କୁହନ୍ତୁ", "dayaakari punithare kuhantu"],
            ["Could you please wait a moment?", "ଦୟାକରି ଟିକେ ଅପେକ୍ଷା କରନ୍ତୁ", "dayaakari tike apekshaa karantu"],
            ["Could you please show me the way?", "ଦୟାକରି ମୋତେ ରାସ୍ତା ଦେଖାନ୍ତୁ", "dayaakari mote raastaa dekhaantu"],
            ["Could you please pass the salt?", "ଦୟାକରି ଲୁଣ ଦିଅନ୍ତୁ", "dayaakari luna diantu"],
            ["Could you please close the door?", "ଦୟାକରି କବାଟ ବନ୍ଦ କରନ୍ତୁ", "dayaakari kabaata banda karantu"],
            ["Could you please call me later?", "ଦୟାକରି ମୋତେ ପରେ ଫୋନ୍ କରନ୍ତୁ", "dayaakari mote pare phon karantu"],
            ["Could you please write it down?", "ଦୟାକରି ଏହା ଲେଖିଦିଅନ୍ତୁ", "dayaakari ehaa lekhidiantu"],
            ["Could you please explain this?", "ଦୟାକରି ଏହା ବୁଝାନ୍ତୁ", "dayaakari ehaa bujhaantu"],
            ["Could you please send me the details?", "ଦୟାକରି ମୋତେ ବିବରଣୀ ପଠାନ୍ତୁ", "dayaakari mote bibaranee pathaantu"],
            ["Could you please open the window?", "ଦୟାକରି ଝରକା ଖୋଲନ୍ତୁ", "dayaakari jharakaa kholantu"],
            ["Could you please turn off the light?", "ଦୟାକରି ବତୀ ଲିଭାନ୍ତୁ", "dayaakari batee libhaantu"],
            ["Could you please give me some time?", "ଦୟାକରି ମୋତେ ଟିକେ ସମୟ ଦିଅନ୍ତୁ", "dayaakari mote tike samaya diantu"],
            ["Could you please lend me your book?", "ଦୟାକରି ମୋତେ ଆପଣଙ୍କ ବହି ଦିଅନ୍ତୁ", "dayaakari mote aapananka bahi diantu"],
            ["Could you please tell me the time?", "ଦୟାକରି ମୋତେ ସମୟ କୁହନ୍ତୁ", "dayaakari mote samaya kuhantu"],
            ["Could you please come here?", "ଦୟାକରି ଏଠିକୁ ଆସନ୍ତୁ", "dayaakari ethiku aasantu"],
            ["Could you please check this?", "ଦୟାକରି ଏହା ଯାଞ୍ଚ କରନ୍ତୁ", "dayaakari ehaa jaancha karantu"],
        ],
    },
    582: {
        "url": "\"I think...\" opinion patterns in Odia",
        "rows": [
            ["I think this is right", "ମୁଁ ଭାବୁଛି ଏହା ଠିକ୍", "mun bhaabuchhi ehaa thik"],
            ["I think he will come", "ମୁଁ ଭାବୁଛି ସେ ଆସିବ", "mun bhaabuchhi se aasiba"],
            ["I think it will rain today", "ମୁଁ ଭାବୁଛି ଆଜି ବର୍ଷା ହେବ", "mun bhaabuchhi aaji barshaa heba"],
            ["I think she is very kind", "ମୁଁ ଭାବୁଛି ସେ ବହୁତ ଦୟାଳୁ", "mun bhaabuchhi se bahut dayaalu"],
            ["I think we should go now", "ମୁଁ ଭାବୁଛି ଆମେ ଏବେ ଯିବା ଉଚିତ", "mun bhaabuchhi aame ebe jibaa uchita"],
            ["I think this is not correct", "ମୁଁ ଭାବୁଛି ଏହା ଠିକ୍ ନୁହେଁ", "mun bhaabuchhi ehaa thik nuhein"],
            ["I think they are happy", "ମୁଁ ଭାବୁଛି ସେମାନେ ଖୁସି ଅଛନ୍ତି", "mun bhaabuchhi semaane khushi achhanti"],
            ["I don't think so", "ମୁଁ ଏମିତି ଭାବୁ ନାହିଁ", "mun emiti bhaabu naahiin"],
            ["I think you are right", "ମୁଁ ଭାବୁଛି ଆପଣ ଠିକ୍ କହୁଛନ୍ତି", "mun bhaabuchhi aapana thik kahuchhanti"],
            ["I think this food is delicious", "ମୁଁ ଭାବୁଛି ଏହି ଖାଦ୍ୟ ସ୍ୱାଦିଷ୍ଟ", "mun bhaabuchhi ehi khaadya swaadishta"],
            ["I think it's too late", "ମୁଁ ଭାବୁଛି ବହୁତ ବିଳମ୍ବ ହୋଇଗଲା", "mun bhaabuchhi bahut bilamba hoigalaa"],
            ["I think we need more time", "ମୁଁ ଭାବୁଛି ଆମକୁ ଅଧିକ ସମୟ ଦରକାର", "mun bhaabuchhi aamaku adhika samaya darakaara"],
            ["I think he is a good person", "ମୁଁ ଭାବୁଛି ସେ ଜଣେ ଭଲ ମଣିଷ", "mun bhaabuchhi se jane bhala manisha"],
            ["I think she will pass the exam", "ମୁଁ ଭାବୁଛି ସେ ପରୀକ୍ଷାରେ ଉତ୍ତୀର୍ଣ ହେବ", "mun bhaabuchhi se parikshaare utteerna heba"],
            ["I think the weather is nice", "ମୁଁ ଭାବୁଛି ପାଣିପାଗ ଭଲ ଅଛି", "mun bhaabuchhi paanipaaga bhala achhi"],
            ["I think we can do it", "ମୁଁ ଭାବୁଛି ଆମେ ଏହା କରିପାରିବା", "mun bhaabuchhi aame ehaa karipaaribaa"],
            ["I think this is enough", "ମୁଁ ଭାବୁଛି ଏତିକି ଯଥେଷ୍ଟ", "mun bhaabuchhi etiki yatheshta"],
            ["I think so too", "ମୁଁ ମଧ୍ୟ ସେମିତି ଭାବୁଛି", "mun madhya semiti bhaabuchhi"],
        ],
    },
    583: {
        "url": "\"I feel...\" emotion patterns in Odia",
        "rows": [
            ["I feel happy", "ମୋତେ ଖୁସି ଲାଗୁଛି", "mote khushi laaguchhi"],
            ["I feel sad", "ମୋତେ ଦୁଃଖ ଲାଗୁଛି", "mote duhkha laaguchhi"],
            ["I feel tired", "ମୋତେ ଥକା ଲାଗୁଛି", "mote thakaa laaguchhi"],
            ["I feel hungry", "ମୋତେ ଭୋକ ଲାଗୁଛି", "mote bhoka laaguchhi"],
            ["I feel thirsty", "ମୋତେ ତୃଷା ଲାଗୁଛି", "mote trushaa laaguchhi"],
            ["I feel cold", "ମୋତେ ଥଣ୍ଡା ଲାଗୁଛି", "mote thandaa laaguchhi"],
            ["I feel hot", "ମୋତେ ଗରମ ଲାଗୁଛି", "mote garama laaguchhi"],
            ["I feel scared", "ମୋତେ ଡର ଲାଗୁଛି", "mote dara laaguchhi"],
            ["I feel lonely", "ମୋତେ ଏକୁଟିଆ ଲାଗୁଛି", "mote ekutiaa laaguchhi"],
            ["I feel angry", "ମୋତେ ରାଗ ଲାଗୁଛି", "mote raaga laaguchhi"],
            ["I feel nervous", "ମୋତେ ଘାବରା ଲାଗୁଛି", "mote ghaabaraa laaguchhi"],
            ["I feel excited", "ମୋତେ ଉତ୍ସାହ ଲାଗୁଛି", "mote utsaaha laaguchhi"],
            ["I feel proud", "ମୋତେ ଗର୍ବ ଲାଗୁଛି", "mote garba laaguchhi"],
            ["I feel embarrassed", "ମୋତେ ଲଜ୍ଜା ଲାଗୁଛି", "mote lajjaa laaguchhi"],
            ["I feel grateful", "ମୋତେ କୃତଜ୍ଞ ଲାଗୁଛି", "mote krutajnya laaguchhi"],
            ["I feel sick", "ମୋତେ ଅସୁସ୍ଥ ଲାଗୁଛି", "mote asustha laaguchhi"],
            ["I feel better now", "ମୋତେ ଏବେ ଭଲ ଲାଗୁଛି", "mote ebe bhala laaguchhi"],
            ["I feel relieved", "ମୋତେ ଆରାମ ଲାଗୁଛି", "mote aaraama laaguchhi"],
        ],
    },
    584: {
        "url": "\"I remember...\" / \"I forgot...\" memory patterns in Odia",
        "rows": [
            ["I remember you", "ମୁଁ ତୁମକୁ ମନେ ରଖିଛି", "mun tumaku mane rakhichhi"],
            ["I remember that day", "ମୁଁ ସେହି ଦିନଟି ମନେ ରଖିଛି", "mun sehi dinati mane rakhichhi"],
            ["I remember everything", "ମୁଁ ସବୁକିଛି ମନେ ରଖିଛି", "mun sabukichhi mane rakhichhi"],
            ["I remember his face", "ମୁଁ ତାଙ୍କ ମୁହଁ ମନେ ରଖିଛି", "mun taanka muhaan mane rakhichhi"],
            ["I remember the address", "ମୁଁ ଠିକଣାଟି ମନେ ରଖିଛି", "mun thikanaati mane rakhichhi"],
            ["I don't remember", "ମୋତେ ମନେ ନାହିଁ", "mote mane naahiin"],
            ["I forgot", "ମୁଁ ଭୁଲିଗଲି", "mun bhuliyaali"],
            ["I forgot his name", "ମୁଁ ତାଙ୍କ ନାମ ଭୁଲିଗଲି", "mun taanka naama bhuliyaali"],
            ["I forgot to call you", "ମୁଁ ତୁମକୁ ଫୋନ୍ କରିବାକୁ ଭୁଲିଗଲି", "mun tumaku phon karibaaku bhuliyaali"],
            ["I forgot to bring the book", "ମୁଁ ବହି ଆଣିବାକୁ ଭୁଲିଗଲି", "mun bahi aanibaaku bhuliyaali"],
            ["I forgot the password", "ମୁଁ ପାସୱାର୍ଡ ଭୁଲିଗଲି", "mun paasward bhuliyaali"],
            ["I forgot my keys at home", "ମୁଁ ଘରେ ଚାବି ଭୁଲିଗଲି", "mun ghare chaabi bhuliyaali"],
            ["Do you remember me?", "ଆପଣ ମୋତେ ମନେ ରଖିଛନ୍ତି କି?", "aapana mote mane rakhichhanti ki?"],
            ["I will always remember this", "ମୁଁ ଏହା ସବୁବେଳେ ମନେ ରଖିବି", "mun ehaa sabubele mane rakhibi"],
            ["I forgot where I put it", "ମୁଁ ଏହା କେଉଁଠି ରଖିଲି ଭୁଲିଗଲି", "mun ehaa keunthi rakhili bhuliyaali"],
            ["I remember our childhood", "ମୁଁ ଆମ ପିଲାଦିନ ମନେ ରଖିଛି", "mun aama pilaadina mane rakhichhi"],
            ["I almost forgot", "ମୁଁ ପ୍ରାୟ ଭୁଲିଯାଇଥିଲି", "mun praaya bhuliyaaithili"],
            ["I completely forgot about the meeting", "ମୁଁ ସଭା ବିଷୟରେ ସମ୍ପୂର୍ଣ ଭୁଲିଗଲି", "mun sabhaa bishayare sampurna bhuliyaali"],
        ],
    },
    585: {
        "url": "\"It's better to...\" advice patterns in Odia",
        "rows": [
            ["It's better to go early", "ଅଗରୁ ଯିବା ଭଲ", "agaru jibaa bhala"],
            ["It's better to stay home", "ଘରେ ରହିବା ଭଲ", "ghare rahibaa bhala"],
            ["It's better to be honest", "ସତ ରହିବା ଭଲ", "sata rahibaa bhala"],
            ["It's better to ask first", "ପ୍ରଥମେ ପଚାରିବା ଭଲ", "prathame pachaaribaa bhala"],
            ["It's better to study regularly", "ନିୟମିତ ପଢ଼ିବା ଭଲ", "niyamita padhibaa bhala"],
            ["It's better to eat healthy food", "ସ୍ୱାସ୍ଥ୍ୟକର ଖାଦ୍ୟ ଖାଇବା ଭଲ", "swaasthyakara khaadya khaaibaa bhala"],
            ["It's better to sleep early", "ଅଗରୁ ଶୋଇବା ଭଲ", "agaru shoibaa bhala"],
            ["It's better to save money", "ଟଙ୍କା ସଞ୍ଚୟ କରିବା ଭଲ", "tankaa sanchaya karibaa bhala"],
            ["It's better to take a taxi", "ଟ୍ୟାକ୍ସି ନେବା ଭଲ", "tyaaksi nebaa bhala"],
            ["It's better to wait", "ଅପେକ୍ଷା କରିବା ଭଲ", "apekshaa karibaa bhala"],
            ["It's better to be careful", "ସାବଧାନ ରହିବା ଭଲ", "saabadhaana rahibaa bhala"],
            ["It's better to keep quiet", "ଚୁପ୍ ରହିବା ଭଲ", "chup rahibaa bhala"],
            ["It's better to tell the truth", "ସତ କହିବା ଭଲ", "sata kahibaa bhala"],
            ["It's better to drink warm water", "ଗରମ ପାଣି ପିଇବା ଭଲ", "garama paani piibaa bhala"],
            ["It's better to forgive", "କ୍ଷମା କରିବା ଭଲ", "kshamaa karibaa bhala"],
            ["It's better to think before speaking", "କହିବା ପୂର୍ବରୁ ଭାବିବା ଭଲ", "kahibaa purbaru bhaabibaa bhala"],
            ["It's better to walk than drive", "ଗାଡ଼ି ଚଲାଇବା ଅପେକ୍ଷା ଚାଲିବା ଭଲ", "gaadi chalaaibaa apekshaa chaalibaa bhala"],
            ["It's better not to argue", "ଝଗଡ଼ା ନ କରିବା ଭଲ", "jhagadaa na karibaa bhala"],
        ],
    },
    586: {
        "url": "\"You should...\" suggestion patterns in Odia",
        "rows": [
            ["You should study hard", "ଆପଣ ଭଲ ଭାବରେ ପଢ଼ିବା ଉଚିତ", "aapana bhala bhaabare padhibaa uchita"],
            ["You should eat on time", "ଆପଣ ସମୟରେ ଖାଇବା ଉଚିତ", "aapana samayare khaaibaa uchita"],
            ["You should take rest", "ଆପଣ ବିଶ୍ରାମ ନେବା ଉଚିତ", "aapana bishraama nebaa uchita"],
            ["You should see a doctor", "ଆପଣ ଡାକ୍ତରଙ୍କୁ ଦେଖାଇବା ଉଚିତ", "aapana daaktaranku dekhaaibaa uchita"],
            ["You should drink more water", "ଆପଣ ଅଧିକ ପାଣି ପିଇବା ଉଚିତ", "aapana adhika paani piibaa uchita"],
            ["You should exercise daily", "ଆପଣ ପ୍ରତିଦିନ ବ୍ୟାୟାମ କରିବା ଉଚିତ", "aapana pratidina byaayaama karibaa uchita"],
            ["You should be polite", "ଆପଣ ଭଦ୍ର ହେବା ଉଚିତ", "aapana bhadra hebaa uchita"],
            ["You should learn Odia", "ଆପଣ ଓଡ଼ିଆ ଶିଖିବା ଉଚିତ", "aapana odiaa shiikhibaa uchita"],
            ["You should call your parents", "ଆପଣ ନିଜ ବାପା ମାଙ୍କୁ ଫୋନ୍ କରିବା ଉଚିତ", "aapana nija baapaa maanku phon karibaa uchita"],
            ["You should apologize", "ଆପଣ କ୍ଷମା ମାଗିବା ଉଚିତ", "aapana kshamaa maagibaa uchita"],
            ["You should not lie", "ଆପଣ ମିଛ କହିବା ଉଚିତ ନୁହେଁ", "aapana michha kahibaa uchita nuhein"],
            ["You should arrive on time", "ଆପଣ ସମୟରେ ପହଞ୍ଚିବା ଉଚିତ", "aapana samayare pahanchibaa uchita"],
            ["You should read books", "ଆପଣ ବହି ପଢ଼ିବା ଉଚିତ", "aapana bahi padhibaa uchita"],
            ["You should wear a helmet", "ଆପଣ ହେଲ୍ମେଟ୍ ପିନ୍ଧିବା ଉଚିତ", "aapana helmet pindhibaa uchita"],
            ["You should not waste food", "ଆପଣ ଖାଦ୍ୟ ନଷ୍ଟ କରିବା ଉଚିତ ନୁହେଁ", "aapana khaadya nashta karibaa uchita nuhein"],
            ["You should respect elders", "ଆପଣ ବଡ଼ ଲୋକଙ୍କୁ ସମ୍ମାନ କରିବା ଉଚିତ", "aapana bada lokanku sammaana karibaa uchita"],
            ["You should save electricity", "ଆପଣ ବିଦ୍ୟୁତ ସଞ୍ଚୟ କରିବା ଉଚିତ", "aapana bidyut sanchaya karibaa uchita"],
            ["You should not give up", "ଆପଣ ହାରି ନ ଯିବା ଉଚିତ", "aapana haari na jibaa uchita"],
        ],
    },
    587: {
        "url": "\"I'm sorry for...\" apology patterns in Odia",
        "rows": [
            ["I'm sorry", "ମୁଁ ଦୁଃଖିତ", "mun duhkhita"],
            ["I'm sorry for being late", "ବିଳମ୍ବ ପାଇଁ ମୁଁ ଦୁଃଖିତ", "bilamba paain mun duhkhita"],
            ["I'm sorry for the trouble", "ଅସୁବିଧା ପାଇଁ ମୁଁ ଦୁଃଖିତ", "asubidhaa paain mun duhkhita"],
            ["I'm sorry for my mistake", "ମୋ ଭୁଲ ପାଇଁ ମୁଁ ଦୁଃଖିତ", "mo bhula paain mun duhkhita"],
            ["I'm sorry for hurting you", "ତୁମକୁ କଷ୍ଟ ଦେବା ପାଇଁ ମୁଁ ଦୁଃଖିତ", "tumaku kashta debaa paain mun duhkhita"],
            ["I'm sorry for not calling", "ଫୋନ୍ ନ କରିବା ପାଇଁ ମୁଁ ଦୁଃଖିତ", "phon na karibaa paain mun duhkhita"],
            ["I'm sorry for forgetting", "ଭୁଲିଯିବା ପାଇଁ ମୁଁ ଦୁଃଖିତ", "bhuliyibaa paain mun duhkhita"],
            ["I'm sorry for the delay", "ବିଳମ୍ବ ପାଇଁ ମୁଁ ଦୁଃଖିତ", "bilamba paain mun duhkhita"],
            ["I'm sorry for disturbing you", "ଆପଣଙ୍କୁ ବିରକ୍ତ କରିବା ପାଇଁ ମୁଁ ଦୁଃଖିତ", "aapananku birakta karibaa paain mun duhkhita"],
            ["I'm sorry for the misunderstanding", "ଭୁଲ ବୁଝାମଣା ପାଇଁ ମୁଁ ଦୁଃଖିତ", "bhula bujhaamanaa paain mun duhkhita"],
            ["I'm sorry, I didn't mean it", "ମୁଁ ଦୁଃଖିତ, ମୋର ସେମିତି ଅର୍ଥ ନଥିଲା", "mun duhkhita, mora semiti artha nathilaa"],
            ["I'm sorry for your loss", "ଆପଣଙ୍କ କ୍ଷତି ପାଇଁ ମୁଁ ଦୁଃଖିତ", "aapananka kshati paain mun duhkhita"],
            ["I'm sorry for breaking it", "ଏହା ଭାଙ୍ଗିବା ପାଇଁ ମୁଁ ଦୁଃଖିତ", "ehaa bhaangibaa paain mun duhkhita"],
            ["I'm sorry for lying", "ମିଛ କହିବା ପାଇଁ ମୁଁ ଦୁଃଖିତ", "michha kahibaa paain mun duhkhita"],
            ["I'm sorry for not helping", "ସାହାଯ୍ୟ ନ କରିବା ପାଇଁ ମୁଁ ଦୁଃଖିତ", "sahaayya na karibaa paain mun duhkhita"],
            ["I'm really sorry", "ମୁଁ ସତରେ ଦୁଃଖିତ", "mun satare duhkhita"],
            ["Please forgive me", "ଦୟାକରି ମୋତେ କ୍ଷମା କରନ୍ତୁ", "dayaakari mote kshamaa karantu"],
            ["I'm sorry, it won't happen again", "ମୁଁ ଦୁଃଖିତ, ଏହା ପୁଣି ହେବ ନାହିଁ", "mun duhkhita, ehaa puni heba naahiin"],
        ],
    },
    588: {
        "url": "\"Congratulations on...\" patterns in Odia",
        "rows": [
            ["Congratulations!", "ଅଭିନନ୍ଦନ!", "abhinandana!"],
            ["Congratulations on your success", "ଆପଣଙ୍କ ସଫଳତା ପାଇଁ ଅଭିନନ୍ଦନ", "aapananka saphalataa paain abhinandana"],
            ["Congratulations on your wedding", "ଆପଣଙ୍କ ବିବାହ ପାଇଁ ଅଭିନନ୍ଦନ", "aapananka bibaaha paain abhinandana"],
            ["Congratulations on the new baby", "ନୂଆ ଶିଶୁ ପାଇଁ ଅଭିନନ୍ଦନ", "nuaa shishu paain abhinandana"],
            ["Congratulations on your promotion", "ଆପଣଙ୍କ ପଦୋନ୍ନତି ପାଇଁ ଅଭିନନ୍ଦନ", "aapananka padonnati paain abhinandana"],
            ["Congratulations on passing the exam", "ପରୀକ୍ଷାରେ ଉତ୍ତୀର୍ଣ ହେବା ପାଇଁ ଅଭିନନ୍ଦନ", "parikshaare utteerna hebaa paain abhinandana"],
            ["Congratulations on your new job", "ଆପଣଙ୍କ ନୂଆ ଚାକିରୀ ପାଇଁ ଅଭିନନ୍ଦନ", "aapananka nuaa chaakiree paain abhinandana"],
            ["Congratulations on your graduation", "ଆପଣଙ୍କ ସ୍ନାତକ ପାଇଁ ଅଭିନନ୍ଦନ", "aapananka snaataka paain abhinandana"],
            ["Congratulations on your achievement", "ଆପଣଙ୍କ ସଫଳତା ପାଇଁ ଅଭିନନ୍ଦନ", "aapananka saphalataa paain abhinandana"],
            ["Congratulations on winning the prize", "ପୁରସ୍କାର ଜିତିବା ପାଇଁ ଅଭିନନ୍ଦନ", "puraskaara jitibaa paain abhinandana"],
            ["Congratulations on your new house", "ଆପଣଙ୍କ ନୂଆ ଘର ପାଇଁ ଅଭିନନ୍ଦନ", "aapananka nuaa ghara paain abhinandana"],
            ["Congratulations on your engagement", "ଆପଣଙ୍କ ସାଗାଇ ପାଇଁ ଅଭିନନ୍ଦନ", "aapananka saagaai paain abhinandana"],
            ["Congratulations on the anniversary", "ବାର୍ଷିକୀ ପାଇଁ ଅଭିନନ୍ଦନ", "baarshikee paain abhinandana"],
            ["Congratulations to both of you", "ଆପଣ ଦୁହିଁଙ୍କୁ ଅଭିନନ୍ଦନ", "aapana duhiinku abhinandana"],
            ["Heartfelt congratulations", "ହୃଦୟରୁ ଅଭିନନ୍ଦନ", "hrudayaru abhinandana"],
            ["Well done!", "ବହୁତ ଭଲ!", "bahut bhala!"],
            ["I'm so happy for you", "ମୁଁ ଆପଣଙ୍କ ପାଇଁ ବହୁତ ଖୁସି", "mun aapananka paain bahut khushi"],
            ["You deserve it, congratulations!", "ଆପଣ ଏହାର ଯୋଗ୍ୟ, ଅଭିନନ୍ଦନ!", "aapana ehaara yogya, abhinandana!"],
        ],
    },
    589: {
        "url": "\"I'm looking forward to...\" patterns in Odia",
        "rows": [
            ["I'm looking forward to it", "ମୁଁ ଏହା ପାଇଁ ଅପେକ୍ଷା କରୁଛି", "mun ehaa paain apekshaa karuchhi"],
            ["I'm looking forward to meeting you", "ମୁଁ ଆପଣଙ୍କୁ ଭେଟିବାକୁ ଅପେକ୍ଷା କରୁଛି", "mun aapananku bhetibaaku apekshaa karuchhi"],
            ["I'm looking forward to the vacation", "ମୁଁ ଛୁଟି ପାଇଁ ଅପେକ୍ଷା କରୁଛି", "mun chhuti paain apekshaa karuchhi"],
            ["I'm looking forward to the festival", "ମୁଁ ପର୍ବ ପାଇଁ ଅପେକ୍ଷା କରୁଛି", "mun parba paain apekshaa karuchhi"],
            ["I'm looking forward to your reply", "ମୁଁ ଆପଣଙ୍କ ଉତ୍ତର ପାଇଁ ଅପେକ୍ଷା କରୁଛି", "mun aapananka uttara paain apekshaa karuchhi"],
            ["I'm looking forward to the trip", "ମୁଁ ଯାତ୍ରା ପାଇଁ ଅପେକ୍ଷା କରୁଛି", "mun yaatraa paain apekshaa karuchhi"],
            ["I'm looking forward to the results", "ମୁଁ ଫଳାଫଳ ପାଇଁ ଅପେକ୍ଷା କରୁଛି", "mun phalaaphala paain apekshaa karuchhi"],
            ["I'm looking forward to working with you", "ମୁଁ ଆପଣଙ୍କ ସହ କାମ କରିବାକୁ ଅପେକ୍ଷା କରୁଛି", "mun aapananka saha kaama karibaaku apekshaa karuchhi"],
            ["I'm looking forward to the weekend", "ମୁଁ ସପ୍ତାହ ଶେଷ ପାଇଁ ଅପେକ୍ଷା କରୁଛି", "mun saptaaha shesha paain apekshaa karuchhi"],
            ["I'm looking forward to the concert", "ମୁଁ ସଙ୍ଗୀତ ଅନୁଷ୍ଠାନ ପାଇଁ ଅପେକ୍ଷା କରୁଛି", "mun sangeeta anushthaana paain apekshaa karuchhi"],
            ["I'm looking forward to seeing you", "ମୁଁ ଆପଣଙ୍କୁ ଦେଖିବାକୁ ଅପେକ୍ଷା କରୁଛି", "mun aapananku dekhibaaku apekshaa karuchhi"],
            ["I'm looking forward to the new year", "ମୁଁ ନୂଆ ବର୍ଷ ପାଇଁ ଅପେକ୍ଷା କରୁଛି", "mun nuaa barsha paain apekshaa karuchhi"],
            ["I'm looking forward to your visit", "ମୁଁ ଆପଣଙ୍କ ଆଗମନ ପାଇଁ ଅପେକ୍ଷା କରୁଛି", "mun aapananka aagamana paain apekshaa karuchhi"],
            ["I'm eagerly waiting", "ମୁଁ ଆଗ୍ରହର ସହ ଅପେକ୍ଷା କରୁଛି", "mun aagrahara saha apekshaa karuchhi"],
            ["I can't wait", "ମୁଁ ଅପେକ୍ଷା କରିପାରୁ ନାହିଁ", "mun apekshaa karipaaru naahiin"],
            ["We are all looking forward to it", "ଆମେ ସମସ୍ତେ ଏହା ପାଇଁ ଅପେକ୍ଷା କରୁଛୁ", "aame samaste ehaa paain apekshaa karuchhu"],
            ["I'm looking forward to the celebration", "ମୁଁ ଉତ୍ସବ ପାଇଁ ଅପେକ୍ଷା କରୁଛି", "mun utsaba paain apekshaa karuchhi"],
            ["I'm looking forward to learning more", "ମୁଁ ଅଧିକ ଶିଖିବାକୁ ଅପେକ୍ଷା କରୁଛି", "mun adhika shikhibaaku apekshaa karuchhi"],
        ],
    },
    590: {
        "url": "\"It depends on...\" patterns in Odia",
        "rows": [
            ["It depends", "ଏହା ନିର୍ଭର କରେ", "ehaa nirbhara kare"],
            ["It depends on you", "ଏହା ଆପଣଙ୍କ ଉପରେ ନିର୍ଭର କରେ", "ehaa aapananka upare nirbhara kare"],
            ["It depends on the weather", "ଏହା ପାଣିପାଗ ଉପରେ ନିର୍ଭର କରେ", "ehaa paanipaaga upare nirbhara kare"],
            ["It depends on the situation", "ଏହା ପରିସ୍ଥିତି ଉପରେ ନିର୍ଭର କରେ", "ehaa paristhiti upare nirbhara kare"],
            ["It depends on the price", "ଏହା ଦାମ ଉପରେ ନିର୍ଭର କରେ", "ehaa daama upare nirbhara kare"],
            ["It depends on the time", "ଏହା ସମୟ ଉପରେ ନିର୍ଭର କରେ", "ehaa samaya upare nirbhara kare"],
            ["It depends on your decision", "ଏହା ଆପଣଙ୍କ ନିଷ୍ପତ୍ତି ଉପରେ ନିର୍ଭର କରେ", "ehaa aapananka nishpatti upare nirbhara kare"],
            ["It depends on the result", "ଏହା ଫଳାଫଳ ଉପରେ ନିର୍ଭର କରେ", "ehaa phalaaphala upare nirbhara kare"],
            ["It depends on many things", "ଏହା ଅନେକ ଜିନିଷ ଉପରେ ନିର୍ଭର କରେ", "ehaa aneka jinisha upare nirbhara kare"],
            ["It depends on the budget", "ଏହା ବଜେଟ ଉପରେ ନିର୍ଭର କରେ", "ehaa bajet upare nirbhara kare"],
            ["It depends on the distance", "ଏହା ଦୂରତା ଉପରେ ନିର୍ଭର କରେ", "ehaa durataa upare nirbhara kare"],
            ["It depends on your health", "ଏହା ଆପଣଙ୍କ ସ୍ୱାସ୍ଥ୍ୟ ଉପରେ ନିର୍ଭର କରେ", "ehaa aapananka swaasthya upare nirbhara kare"],
            ["It depends on the availability", "ଏହା ଉପಲବ୍ଧତା ଉପରେ ନିର୍ଭର କରେ", "ehaa upalabdhataa upare nirbhara kare"],
            ["It all depends on luck", "ଏହା ସବୁ ଭାଗ୍ୟ ଉପରେ ନିର୍ଭର କରେ", "ehaa sabu bhaagya upare nirbhara kare"],
            ["It depends on his answer", "ଏହା ତାଙ୍କ ଉତ୍ତର ଉପରେ ନିର୍ଭର କରେ", "ehaa taanka uttara upare nirbhara kare"],
            ["It depends on the teacher", "ଏହା ଶିକ୍ଷକ ଉପରେ ନିର୍ଭର କରେ", "ehaa shikshaka upare nirbhara kare"],
            ["It depends on circumstances", "ଏହା ପରିସ୍ଥିତି ଉପରେ ନିର୍ଭର କରେ", "ehaa paristhiti upare nirbhara kare"],
            ["Everything depends on effort", "ସବୁକିଛି ପରିଶ୍ରମ ଉପରେ ନିର୍ଭର କରେ", "sabukichhi parishrama upare nirbhara kare"],
        ],
    },
    591: {
        "url": "\"As far as I know...\" patterns in Odia",
        "rows": [
            ["As far as I know", "ମୁଁ ଯେତିକି ଜାଣେ", "mun jetiki jaane"],
            ["As far as I know, he is honest", "ମୁଁ ଯେତିକି ଜାଣେ, ସେ ସଚ୍ଚୋଟ", "mun jetiki jaane, se sachchota"],
            ["As far as I know, the shop is open", "ମୁଁ ଯେତିକି ଜାଣେ, ଦୋକାନ ଖୋଲା ଅଛି", "mun jetiki jaane, dokaana kholaa achhi"],
            ["As far as I know, she lives here", "ମୁଁ ଯେତିକି ଜାଣେ, ସେ ଏଠି ରହନ୍ତି", "mun jetiki jaane, se ethi rahanti"],
            ["As far as I know, the train is on time", "ମୁଁ ଯେତିକି ଜାଣେ, ଟ୍ରେନ୍ ସମୟରେ ଅଛି", "mun jetiki jaane, tren samayare achhi"],
            ["As far as I know, he hasn't arrived", "ମୁଁ ଯେତିକି ଜାଣେ, ସେ ଆସି ନାହାନ୍ତି", "mun jetiki jaane, se aasi naahaanti"],
            ["As far as I know, they are friends", "ମୁଁ ଯେତିକି ଜାଣେ, ସେମାନେ ବନ୍ଧୁ", "mun jetiki jaane, semaane bandhu"],
            ["As far as I know, it's free", "ମୁଁ ଯେତିକି ଜାଣେ, ଏହା ମାଗଣା", "mun jetiki jaane, ehaa maaganaa"],
            ["As far as I know, the exam is tomorrow", "ମୁଁ ଯେତିକି ଜାଣେ, ପରୀକ୍ଷା କାଲି", "mun jetiki jaane, pariikshaa kaali"],
            ["As far as I know, he is a teacher", "ମୁଁ ଯେତିକି ଜାଣେ, ସେ ଜଣେ ଶିକ୍ଷକ", "mun jetiki jaane, se jane shikshaka"],
            ["As far as I know, the road is good", "ମୁଁ ଯେତିକି ଜାଣେ, ରାସ୍ତା ଭଲ ଅଛି", "mun jetiki jaane, raastaa bhala achhi"],
            ["As far as I know, there's no problem", "ମୁଁ ଯେତିକି ଜାଣେ, କୌଣସି ସମସ୍ୟା ନାହିଁ", "mun jetiki jaane, kaunasi samasyaa naahiin"],
            ["As far as I know, it's correct", "ମୁଁ ଯେତିକି ଜାଣେ, ଏହା ଠିକ୍", "mun jetiki jaane, ehaa thik"],
            ["As far as I know, they haven't decided", "ମୁଁ ଯେତିକି ଜାଣେ, ସେମାନେ ନିଷ୍ପତ୍ତି ନେଇ ନାହାନ୍ତି", "mun jetiki jaane, semaane nishpatti nei naahaanti"],
            ["As far as I know, this is the last bus", "ମୁଁ ଯେତିକି ଜାଣେ, ଏହା ଶେଷ ବସ୍", "mun jetiki jaane, ehaa shesha bas"],
            ["As far as I know, he is in the office", "ମୁଁ ଯେତିକି ଜାଣେ, ସେ ଅଫିସ୍‌ରେ ଅଛନ୍ତି", "mun jetiki jaane, se aphisre achhanti"],
            ["As far as I know, the movie is good", "ମୁଁ ଯେତିକି ଜାଣେ, ସିନେମା ଭଲ", "mun jetiki jaane, sinemaa bhala"],
            ["As far as I know, nobody complained", "ମୁଁ ଯେତିକି ଜାଣେ, କେହି ଅଭିଯୋଗ କରି ନାହାନ୍ତି", "mun jetiki jaane, kehi abhiyoga kari naahaanti"],
        ],
    },
    592: {
        "url": "\"In my opinion...\" patterns in Odia",
        "rows": [
            ["In my opinion", "ମୋ ମତରେ", "mo matare"],
            ["In my opinion, this is right", "ମୋ ମତରେ, ଏହା ଠିକ୍", "mo matare, ehaa thik"],
            ["In my opinion, he is talented", "ମୋ ମତରେ, ସେ ପ୍ରତିଭାବାନ", "mo matare, se pratibhaabaan"],
            ["In my opinion, this plan is good", "ମୋ ମତରେ, ଏହି ଯୋଜନା ଭଲ", "mo matare, ehi yojanaa bhala"],
            ["In my opinion, we should wait", "ମୋ ମତରେ, ଆମେ ଅପେକ୍ଷା କରିବା ଉଚିତ", "mo matare, aame apekshaa karibaa uchita"],
            ["In my opinion, education is important", "ମୋ ମତରେ, ଶିକ୍ଷା ଗୁରୁତ୍ୱପୂର୍ଣ", "mo matare, shikshaa gurutwapurna"],
            ["In my opinion, it's too expensive", "ମୋ ମତରେ, ଏହା ବହୁତ ମହଙ୍ଗା", "mo matare, ehaa bahut mahangaa"],
            ["In my opinion, she did well", "ମୋ ମତରେ, ସେ ଭଲ କରିଛନ୍ତି", "mo matare, se bhala karichhanti"],
            ["In my opinion, health comes first", "ମୋ ମତରେ, ସ୍ୱାସ୍ଥ୍ୟ ପ୍ରଥମ", "mo matare, swaasthya prathama"],
            ["In my opinion, this movie is boring", "ମୋ ମତରେ, ଏହି ସିନେମା ବିରକ୍ତିକର", "mo matare, ehi sinemaa biraktikara"],
            ["In my opinion, they need more practice", "ମୋ ମତରେ, ସେମାନଙ୍କୁ ଅଧିକ ଅଭ୍ୟାସ ଦରକାର", "mo matare, semaananku adhika abhyaasa darakaara"],
            ["In my opinion, Odia food is delicious", "ମୋ ମତରେ, ଓଡ଼ିଆ ଖାଦ୍ୟ ସ୍ୱାଦିଷ୍ଟ", "mo matare, odiaa khaadya swaadishta"],
            ["In my opinion, honesty is the best policy", "ମୋ ମତରେ, ସତ୍ୟ ହିଁ ସର୍ବୋତ୍ତମ ନୀତି", "mo matare, satya hiin sarbottama neeti"],
            ["In my opinion, this is not fair", "ମୋ ମତରେ, ଏହା ଉଚିତ ନୁହେଁ", "mo matare, ehaa uchita nuhein"],
            ["In my opinion, both are correct", "ମୋ ମତରେ, ଦୁଇଟି ଠିକ୍", "mo matare, duiti thik"],
            ["In my opinion, we should try again", "ମୋ ମତରେ, ଆମେ ପୁଣିଥରେ ଚେଷ୍ଟା କରିବା ଉଚିତ", "mo matare, aame punithare cheshtaa karibaa uchita"],
            ["In my opinion, reading is a good habit", "ମୋ ମତରେ, ପଢ଼ିବା ଏକ ଭଲ ଅଭ୍ୟାସ", "mo matare, padhibaa eka bhala abhyaasa"],
            ["In my opinion, kindness matters most", "ମୋ ମତରେ, ଦୟା ସବୁଠାରୁ ଗୁରୁତ୍ୱପୂର୍ଣ", "mo matare, dayaa sabuthaaru gurutwapurna"],
        ],
    },
    593: {
        "url": "\"To tell the truth...\" patterns in Odia",
        "rows": [
            ["To tell the truth", "ସତ କହିବାକୁ ଗଲେ", "sata kahibaaku gale"],
            ["To tell the truth, I don't like it", "ସତ କହିବାକୁ ଗଲେ, ମୋତେ ଏହା ଭଲ ଲାଗେ ନାହିଁ", "sata kahibaaku gale, mote ehaa bhala laage naahiin"],
            ["To tell the truth, I was afraid", "ସତ କହିବାକୁ ଗଲେ, ମୁଁ ଡରିଥିଲି", "sata kahibaaku gale, mun darithili"],
            ["To tell the truth, I made a mistake", "ସତ କହିବାକୁ ଗଲେ, ମୁଁ ଭୁଲ କରିଥିଲି", "sata kahibaaku gale, mun bhula karithili"],
            ["To tell the truth, it's difficult", "ସତ କହିବାକୁ ଗଲେ, ଏହା କଷ୍ଟକର", "sata kahibaaku gale, ehaa kashtakara"],
            ["To tell the truth, I don't know", "ସତ କହିବାକୁ ଗଲେ, ମୁଁ ଜାଣେ ନାହିଁ", "sata kahibaaku gale, mun jaane naahiin"],
            ["To tell the truth, I forgot", "ସତ କହିବାକୁ ଗଲେ, ମୁଁ ଭୁଲିଗଲି", "sata kahibaaku gale, mun bhuliyaali"],
            ["To tell the truth, I was late", "ସତ କହିବାକୁ ଗଲେ, ମୁଁ ବିଳମ୍ବ ହୋଇଥିଲି", "sata kahibaaku gale, mun bilamba hoithili"],
            ["To tell the truth, I haven't finished", "ସତ କହିବାକୁ ଗଲେ, ମୁଁ ସାରି ନାହିଁ", "sata kahibaaku gale, mun saari naahiin"],
            ["To tell the truth, I was wrong", "ସତ କହିବାକୁ ଗଲେ, ମୁଁ ଭୁଲ ଥିଲି", "sata kahibaaku gale, mun bhula thili"],
            ["To tell the truth, she doesn't agree", "ସତ କହିବାକୁ ଗଲେ, ସେ ରାଜି ନୁହନ୍ତି", "sata kahibaaku gale, se raaji nuhanti"],
            ["To tell the truth, I need help", "ସତ କହିବାକୁ ଗଲେ, ମୋତେ ସାହାଯ୍ୟ ଦରକାର", "sata kahibaaku gale, mote sahaayya darakaara"],
            ["To tell the truth, I was disappointed", "ସତ କହିବାକୁ ଗଲେ, ମୁଁ ନିରାଶ ହୋଇଥିଲି", "sata kahibaaku gale, mun niraasha hoithili"],
            ["To tell the truth, I haven't read it", "ସତ କହିବାକୁ ଗଲେ, ମୁଁ ଏହା ପଢ଼ି ନାହିଁ", "sata kahibaaku gale, mun ehaa padhi naahiin"],
            ["To tell the truth, I prefer this one", "ସତ କହିବାକୁ ଗଲେ, ମୁଁ ଏହାକୁ ପସନ୍ଦ କରେ", "sata kahibaaku gale, mun ehaaku pasanda kare"],
            ["To tell the truth, it's not easy", "ସତ କହିବାକୁ ଗଲେ, ଏହା ସହଜ ନୁହେଁ", "sata kahibaaku gale, ehaa sahaja nuhein"],
            ["To tell the truth, I am tired", "ସତ କହିବାକୁ ଗଲେ, ମୁଁ ଥକି ଯାଇଛି", "sata kahibaaku gale, mun thaki jaaichhi"],
            ["Honestly speaking, I don't agree", "ସତ କହିବାକୁ ଗଲେ, ମୁଁ ରାଜି ନୁହେଁ", "sata kahibaaku gale, mun raaji nuhein"],
        ],
    },
    594: {
        "url": "\"By the way...\" patterns in Odia",
        "rows": [
            ["By the way", "ଅଳ୍ପ କଥା", "alpa kathaa"],
            ["By the way, I met your friend", "ଅଳ୍ପ କଥା, ମୁଁ ତୁମ ବନ୍ଧୁଙ୍କୁ ଭେଟିଲି", "alpa kathaa, mun tuma bandhunku bhetili"],
            ["By the way, are you free tomorrow?", "ଅଳ୍ପ କଥା, ଆପଣ କାଲି ଖାଲି ଅଛନ୍ତି କି?", "alpa kathaa, aapana kaali khaali achhanti ki?"],
            ["By the way, did you eat?", "ଅଳ୍ପ କଥା, ଆପଣ ଖାଇଲେ କି?", "alpa kathaa, aapana khaaile ki?"],
            ["By the way, your phone was ringing", "ଅଳ୍ପ କଥା, ଆପଣଙ୍କ ଫୋନ୍ ବାଜୁଥିଲା", "alpa kathaa, aapananka phon baajuthilaa"],
            ["By the way, I have something to tell you", "ଅଳ୍ପ କଥା, ମୋର ଆପଣଙ୍କୁ କିଛି କହିବାର ଅଛି", "alpa kathaa, mora aapananku kichhi kahibaara achhi"],
            ["By the way, happy birthday!", "ଅଳ୍ପ କଥା, ଜନ୍ମଦିନ ଶୁଭେଚ୍ଛା!", "alpa kathaa, janmadina shubhechchhaa!"],
            ["By the way, where are you going?", "ଅଳ୍ପ କଥା, ଆପଣ କେଉଁଠି ଯାଉଛନ୍ତି?", "alpa kathaa, aapana keunthi jaauchhanti?"],
            ["By the way, I changed my number", "ଅଳ୍ପ କଥା, ମୁଁ ମୋ ନମ୍ବର ବଦଳାଇଛି", "alpa kathaa, mun mo nambar badalaaichhi"],
            ["By the way, how is your family?", "ଅଳ୍ପ କଥା, ଆପଣଙ୍କ ପରିବାର କେମିତି ଅଛନ୍ତି?", "alpa kathaa, aapananka paribaara kemiti achhanti?"],
            ["By the way, the meeting is postponed", "ଅଳ୍ପ କଥା, ସଭା ସ୍ଥଗିତ ହୋଇଛି", "alpa kathaa, sabhaa sthagita hoichhi"],
            ["By the way, I forgot to mention", "ଅଳ୍ପ କଥା, ମୁଁ କହିବାକୁ ଭୁଲିଗଲି", "alpa kathaa, mun kahibaaku bhuliyaali"],
            ["By the way, the bus has arrived", "ଅଳ୍ପ କଥା, ବସ୍ ଆସିଗଲା", "alpa kathaa, bas aasigalaa"],
            ["By the way, do you know him?", "ଅଳ୍ପ କଥା, ଆପଣ ତାଙ୍କୁ ଚିହ୍ନନ୍ତି କି?", "alpa kathaa, aapana taanku chihnanti ki?"],
            ["By the way, I brought some sweets", "ଅଳ୍ପ କଥା, ମୁଁ ଟିକେ ମିଠା ଆଣିଛି", "alpa kathaa, mun tike mithaa aanichhi"],
            ["By the way, it's raining outside", "ଅଳ୍ପ କଥା, ବାହାରେ ବର୍ଷା ହେଉଛି", "alpa kathaa, baahaare barshaa heuchhi"],
            ["By the way, have you seen this?", "ଅଳ୍ପ କଥା, ଆପଣ ଏହା ଦେଖିଛନ୍ତି କି?", "alpa kathaa, aapana ehaa dekhichhanti ki?"],
            ["By the way, thanks for your help", "ଅଳ୍ପ କଥା, ଆପଣଙ୍କ ସାହାଯ୍ୟ ପାଇଁ ଧନ୍ୟବାଦ", "alpa kathaa, aapananka sahaayya paain dhanyabaada"],
        ],
    },
    595: {
        "url": "\"As a matter of fact...\" patterns in Odia",
        "rows": [
            ["As a matter of fact", "ବାସ୍ତବରେ", "baastabare"],
            ["As a matter of fact, I agree with you", "ବାସ୍ତବରେ, ମୁଁ ଆପଣଙ୍କ ସହ ରାଜି", "baastabare, mun aapananka saha raaji"],
            ["As a matter of fact, I was thinking the same", "ବାସ୍ତବରେ, ମୁଁ ସେମିତି ଭାବୁଥିଲି", "baastabare, mun semiti bhaabuthili"],
            ["As a matter of fact, she is my sister", "ବାସ୍ତବରେ, ସେ ମୋ ଭଉଣୀ", "baastabare, se mo bhaunee"],
            ["As a matter of fact, I have been there", "ବାସ୍ତବରେ, ମୁଁ ସେଠିକୁ ଯାଇଛି", "baastabare, mun sethiku jaaichhi"],
            ["As a matter of fact, it's true", "ବାସ୍ତବରେ, ଏହା ସତ", "baastabare, ehaa sata"],
            ["As a matter of fact, he is right", "ବାସ୍ତବରେ, ସେ ଠିକ୍ କହୁଛନ୍ତି", "baastabare, se thik kahuchhanti"],
            ["As a matter of fact, I already knew", "ବାସ୍ତବରେ, ମୁଁ ଆଗରୁ ଜାଣିଥିଲି", "baastabare, mun aagaru jaanithili"],
            ["As a matter of fact, this is better", "ବାସ୍ତବରେ, ଏହା ଅଧିକ ଭଲ", "baastabare, ehaa adhika bhala"],
            ["As a matter of fact, I like it", "ବାସ୍ତବରେ, ମୋତେ ଏହା ଭଲ ଲାଗେ", "baastabare, mote ehaa bhala laage"],
            ["As a matter of fact, we won", "ବାସ୍ତବରେ, ଆମେ ଜିତିଲୁ", "baastabare, aame jitilu"],
            ["As a matter of fact, he didn't come", "ବାସ୍ତବରେ, ସେ ଆସି ନଥିଲେ", "baastabare, se aasi nathile"],
            ["As a matter of fact, it was my idea", "ବାସ୍ତବରେ, ଏହା ମୋ ଧାରଣା ଥିଲା", "baastabare, ehaa mo dhaaranaa thilaa"],
            ["As a matter of fact, the food was great", "ବାସ୍ତବରେ, ଖାଦ୍ୟ ବହୁତ ଭଲ ଥିଲା", "baastabare, khaadya bahut bhala thilaa"],
            ["As a matter of fact, I enjoy teaching", "ବାସ୍ତବରେ, ମୁଁ ପଢ଼ାଇବାକୁ ଭଲ ପାଏ", "baastabare, mun padhaabaaku bhala paae"],
            ["As a matter of fact, it's cheaper here", "ବାସ୍ତବରେ, ଏଠି ସସ୍ତା", "baastabare, ethi sastaa"],
            ["As a matter of fact, I do remember", "ବାସ୍ତବରେ, ମୋତେ ମନେ ଅଛି", "baastabare, mote mane achhi"],
            ["As a matter of fact, I was about to call you", "ବାସ୍ତବରେ, ମୁଁ ଆପଣଙ୍କୁ ଫୋନ୍ କରିବାକୁ ଯାଉଥିଲି", "baastabare, mun aapananku phon karibaaku jaauthori"],
        ],
    },
    596: {
        "url": "\"All in all...\" summary patterns in Odia",
        "rows": [
            ["All in all", "ସବୁ ମିଳାଇ", "sabu milaai"],
            ["All in all, it was a good day", "ସବୁ ମିଳାଇ, ଏହା ଏକ ଭଲ ଦିନ ଥିଲା", "sabu milaai, ehaa eka bhala dina thilaa"],
            ["All in all, the trip was wonderful", "ସବୁ ମିଳାଇ, ଯାତ୍ରା ବହୁତ ସୁନ୍ଦର ଥିଲା", "sabu milaai, yaatraa bahut sundara thilaa"],
            ["All in all, we learned a lot", "ସବୁ ମିଳାଇ, ଆମେ ଅନେକ ଶିଖିଲୁ", "sabu milaai, aame aneka shikhilu"],
            ["All in all, the event was successful", "ସବୁ ମିଳାଇ, ଅନୁଷ୍ଠାନ ସଫଳ ଥିଲା", "sabu milaai, anushthaana saphala thilaa"],
            ["All in all, I'm satisfied", "ସବୁ ମିଳାଇ, ମୁଁ ସନ୍ତୁଷ୍ଟ", "sabu milaai, mun santushta"],
            ["All in all, it was worth it", "ସବୁ ମିଳାଇ, ଏହା ଯୋଗ୍ୟ ଥିଲା", "sabu milaai, ehaa yogya thilaa"],
            ["All in all, the food was great", "ସବୁ ମିଳାଇ, ଖାଦ୍ୟ ବହୁତ ଭଲ ଥିଲା", "sabu milaai, khaadya bahut bhala thilaa"],
            ["All in all, everyone enjoyed", "ସବୁ ମିଳାଇ, ସମସ୍ତେ ଆନନ୍ଦ କରିଲେ", "sabu milaai, samaste aananda karile"],
            ["All in all, the movie was okay", "ସବୁ ମିଳାଇ, ସିନେମା ଠିକ୍‌ଠାକ୍ ଥିଲା", "sabu milaai, sinemaa thikthaak thilaa"],
            ["All in all, I had a great time", "ସବୁ ମିଳାଇ, ମୁଁ ବହୁତ ଆନନ୍ଦ କଲି", "sabu milaai, mun bahut aananda kali"],
            ["All in all, it could have been better", "ସବୁ ମିଳାଇ, ଏହା ଆଉ ଭଲ ହୋଇପାରିଥାନ୍ତା", "sabu milaai, ehaa aau bhala hoipaarithaantaa"],
            ["All in all, it was a memorable experience", "ସବୁ ମିଳାଇ, ଏହା ଏକ ସ୍ମରଣୀୟ ଅନୁଭବ ଥିଲା", "sabu milaai, ehaa eka smaraneey anubhaba thilaa"],
            ["All in all, the project was completed", "ସବୁ ମିଳାଇ, ପ୍ରକଳ୍ପ ସମ୍ପୂର୍ଣ ହେଲା", "sabu milaai, prakalpa sampurna helaa"],
            ["All in all, we did our best", "ସବୁ ମିଳାଇ, ଆମେ ଆମର ସର୍ବୋତ୍ତମ ଚେଷ୍ଟା କଲୁ", "sabu milaai, aame aamara sarbottama cheshtaa kalu"],
            ["All in all, life is good", "ସବୁ ମିଳାଇ, ଜୀବନ ଭଲ", "sabu milaai, jeebana bhala"],
            ["All in all, I have no complaints", "ସବୁ ମିଳାଇ, ମୋର କୌଣସି ଅଭିଯୋଗ ନାହିଁ", "sabu milaai, mora kaunasi abhiyoga naahiin"],
            ["To sum up, everything went well", "ସବୁ ମିଳାଇ, ସବୁକିଛି ଠିକ୍ ହେଲା", "sabu milaai, sabukichhi thik helaa"],
        ],
    },
}

with open(DATA_FILE, "r", encoding="utf-8") as f:
    data = json.load(f)

updated = 0
for item in data:
    if item["id"] in lessons:
        lesson = lessons[item["id"]]
        item["url"] = lesson["url"]
        item["blocks"] = [
            {
                "type": "table",
                "columns": ["English", "Odia", "Transliteration"],
                "rows": lesson["rows"],
            }
        ]
        updated += 1

with open(DATA_FILE, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Updated {updated} lessons (IDs 579-596) in {DATA_FILE}")
for lid in sorted(lessons.keys()):
    row_count = len(lessons[lid]["rows"])
    print(f"  ID {lid}: {lessons[lid]['url']} — {row_count} rows")
print("Done!")
