import json
d = json.load(open('data_odia.json','r',encoding='utf-8'))
L = {}

L[620] = [
    ["Happy Diwali!","ଶୁଭ ଦୀପାବଳୀ!","Shubha Dipabali!"],
    ["We celebrate Diwali with joy","ଆମେ ଖୁସିରେ ଦୀପାବଳୀ ପାଳନ କରୁ","Ame khusire Dipabali palana karu"],
    ["We light lamps at home","ଆମେ ଘରେ ଦୀପ ଜଳାଉ","Ame ghare dipa jalau"],
    ["Children burst firecrackers","ପିଲାମାନେ ପଟାଖ ଫୁଟାନ୍ତି","Pilamane patakha phutanti"],
    ["Mother makes sweets","ମା ମିଠା ତିଆରି କରନ୍ତି","Maa mitha tiari karanti"],
    ["We clean the house before Diwali","ଦୀପାବଳୀ ଆଗରୁ ଆମେ ଘର ସଫା କରୁ","Dipabali agaru ame ghara sapha karu"],
    ["The whole village is decorated","ସାରା ଗାଁ ସଜାଯାଇଛି","Sara gaan sajayaichhi"],
    ["We wear new clothes","ଆମେ ନୂଆ ଲୁଗା ପିନ୍ଧୁ","Ame nua luga pindhu"],
    ["Friends and family come together","ବନ୍ଧୁ ଓ ପରିବାର ଏକାଠି ହୁଅନ୍ତି","Bandhu o paribar ekathi huanti"],
    ["We share sweets with neighbours","ଆମେ ପଡ଼ୋଶୀଙ୍କୁ ମିଠା ବାଣ୍ଟୁ","Ame padoshinku mitha bantu"],
    ["Diwali is the festival of lights","ଦୀପାବଳୀ ହେଉଛି ଆଲୋକର ପର୍ବ","Dipabali heuchhi alokara parba"],
    ["We pray for prosperity","ଆମେ ସମୃଦ୍ଧି ପାଇଁ ପ୍ରାର୍ଥନା କରୁ","Ame samruddhi pain prarthana karu"],
    ["The sky is full of fireworks","ଆକାଶ ପଟାଖରେ ଭରି ଯାଇଛି","Akasha patakhare bhari jaichhi"],
    ["We eat together as a family","ଆମେ ପରିବାର ସହ ଏକାଠି ଖାଉ","Ame paribar saha ekathi khau"],
    ["May this Diwali bring happiness","ଏହି ଦୀପାବଳୀ ସୁଖ ଆଣୁ","Ehi Dipabali sukha anu"],
    ["Rangoli is made at the door","ଦ୍ୱାରରେ ରଙ୍ଗୋଳି ତିଆରି ହୋଇଛି","Dwarare rangoli tiari hoichhi"],
    ["Diwali comes every year","ଦୀପାବଳୀ ପ୍ରତିବର୍ଷ ଆସେ","Dipabali pratibarsha ase"],
    ["We enjoy Diwali very much","ଆମେ ଦୀପାବଳୀ ବହୁତ ଉପଭୋଗ କରୁ","Ame Dipabali bahut upabhoga karu"]
]
L[621] = [
    ["Hello! Greetings!","ନମସ୍କାର!","Namaskaar!"],
    ["How are you?","ଆପଣ କେମିତି ଅଛନ୍ତି?","Apana kemiti achhanti?"],
    ["I am fine","ମୁଁ ଭଲ ଅଛି","Mun bhala achhi"],
    ["What is your name?","ଆପଣଙ୍କ ନାମ କଣ?","Apananka naama kana?"],
    ["My name is Suren","ମୋ ନାମ ସୁରେନ","Mo naama Suren"],
    ["Where are you from?","ଆପଣ କେଉଁଠୁ ଆସିଛନ୍ତି?","Apana keunthu asichhanti?"],
    ["I am from Odisha","ମୁଁ ଓଡ଼ିଶାରୁ","Mun Odisharu"],
    ["Nice to meet you","ଆପଣଙ୍କୁ ଭେଟି ଖୁସି ଲାଗିଲା","Apananku bheti khusi lagila"],
    ["Please come in","ଦୟାକରି ଭିତରକୁ ଆସନ୍ତୁ","Dayakari bhitaraku asantu"],
    ["Please sit down","ଦୟାକରି ବସନ୍ତୁ","Dayakari basantu"],
    ["How is your family?","ଆପଣଙ୍କ ପରିବାର କେମିତି?","Apananka paribar kemiti?"],
    ["Everyone is well","ସମସ୍ତେ ଭଲ ଅଛନ୍ତି","Samaste bhala achhanti"],
    ["What do you do?","ଆପଣ କଣ କରନ୍ତି?","Apana kana karanti?"],
    ["I am a teacher","ମୁଁ ଜଣେ ଶିକ୍ଷକ","Mun jane shikshaka"],
    ["Thank you very much","ବହୁତ ଧନ୍ୟବାଦ","Bahut dhanyabad"],
    ["Goodbye","ନମସ୍କାର, ଆସନ୍ତୁ","Namaskaar, asantu"],
    ["See you again","ଆଉ ଭେଟିବା","Au bhetiba"],
    ["May you be well","ଆପଣ ଭଲରେ ଥାଆନ୍ତୁ","Apana bhala re thaantu"]
]
L[622] = [
    ["What time is it?","କେତେ ବେଳେ ହେଲା?","Kete bele hela?"],
    ["It is morning","ସକାଳ ହୋଇଛି","Sakala hoichhi"],
    ["It is afternoon","ଅପରାହ୍ଣ ହୋଇଛି","Aparahna hoichhi"],
    ["It is evening now","ଏବେ ସନ୍ଧ୍ୟା ହୋଇଛି","Ebe sandhya hoichhi"],
    ["I wake up early in the morning","ମୁଁ ସକାଳୁ ଉଠେ","Mun sakalu uthe"],
    ["I go to school at 8","ମୁଁ ଆଠଟାରେ ସ୍କୁଲ ଯାଏ","Mun aathatare skul yae"],
    ["Lunch is at noon","ଦୁପହରେ ଖାଇବା","Dupahare khaiba"],
    ["I come home at 5","ମୁଁ ପାଞ୍ଚଟାରେ ଘରକୁ ଆସେ","Mun paanchatare gharaku ase"],
    ["I sleep at night","ମୁଁ ରାତିରେ ଶୋଏ","Mun ratire shoe"],
    ["Today is Monday","ଆଜି ସୋମବାର","Aji sombar"],
    ["Tomorrow is a holiday","କାଲି ଛୁଟି","Kali chhuti"],
    ["Yesterday I went to the market","ଗତକାଲି ମୁଁ ବଜାର ଯାଇଥିଲି","Gatakali mun bajar jaithili"],
    ["It's getting late","ବହୁତ ଲେଟ ହେଉଛି","Bahut let heuchhi"],
    ["Come on time","ଠିକ ସମୟରେ ଆସନ୍ତୁ","Thik samayare asantu"],
    ["I don't have time today","ଆଜି ମୋର ସମୟ ନାହିଁ","Aji mora samaya nahin"],
    ["Wait a moment","ଟିକେ ଅପେକ୍ଷା କରନ୍ତୁ","Tike apeksha karantu"],
    ["How long will it take?","କେତେ ସମୟ ଲାଗିବ?","Kete samaya lagiba?"],
    ["Time is very important","ସମୟ ବହୁତ ଗୁରୁତ୍ୱପୂର୍ଣ୍ଣ","Samaya bahut gurutwa purna"]
]
L[623] = [
    ["Where are you going?","ଆପଣ କେଉଁଠି ଯାଉଛନ୍ତି?","Apana keunthi yauchanti?"],
    ["I am going home","ମୁଁ ଘରକୁ ଯାଉଛି","Mun gharaku yauchhi"],
    ["Where is the market?","ବଜାର କେଉଁଠି?","Bajar keunthi?"],
    ["The market is near the school","ବଜାର ସ୍କୁଲ ପାଖରେ","Bajar skul pakhare"],
    ["Where is the hospital?","ଡାକ୍ତରଖାନା କେଉଁଠି?","Daktarkhana keunthi?"],
    ["Go straight then turn left","ସିଧା ଯାଆନ୍ତୁ ତାପରେ ବାମକୁ ମୋଡ଼ନ୍ତୁ","Sidha yaantu tapare bamaku modantu"],
    ["How far is the village?","ଗାଁ କେତେ ଦୂର?","Gaan kete dur?"],
    ["It is very close","ବହୁତ ନିକଟରେ","Bahut nikatare"],
    ["It is far from here","ଏଠାରୁ ବହୁତ ଦୂର","Etharu bahut dur"],
    ["Is there a bus stop nearby?","ନିକଟରେ ବସ୍ ଷ୍ଟପ୍ ଅଛି?","Nikatare bas stop achhi?"],
    ["Where do you live?","ଆପଣ କେଉଁଠି ରହନ୍ତି?","Apana keunthi rahanti?"],
    ["I live in Bhubaneswar","ମୁଁ ଭୁବନେଶ୍ୱରରେ ରହେ","Mun Bhubanesware rahe"],
    ["This place is very beautiful","ଏହି ଜାଗା ବହୁତ ସୁନ୍ଦର","Ehi jaga bahut sundar"],
    ["Which road goes to the station?","ଷ୍ଟେସନ ଯାଇବାକୁ କେଉଁ ରାସ୍ତା?","Stesan jaibaku keun rasta?"],
    ["The temple is on the hill","ମନ୍ଦିର ପାହାଡ଼ ଉପରେ","Mandira pahada upare"],
    ["There is a river behind the village","ଗାଁ ପଛପଟେ ନଦୀ ଅଛି","Gaan pachhapate nadi achhi"],
    ["I have never been there","ମୁଁ ସେଠାକୁ କେବେ ଯାଇନାହିଁ","Mun sethaku kebe yainahin"],
    ["Show me the way","ମୋତେ ରାସ୍ତା ଦେଖାନ୍ତୁ","Mote rasta dekhantu"]
]
L[624] = [
    ["Do you have a room available?","ଆପଣଙ୍କ ପାଖରେ ରୁମ ଖାଲି ଅଛି?","Apananka pakhare room khali achhi?"],
    ["I need a room for one night","ମୋତେ ଗୋଟିଏ ରାତି ପାଇଁ ରୁମ ଦରକାର","Mote gotie rati pain room darkar"],
    ["How much is the room charge?","ରୁମ ଭଡ଼ା କେତେ?","Room bhada kete?"],
    ["Please give me the key","ଦୟାକରି ଚାବି ଦିଅନ୍ତୁ","Dayakari chabi diantu"],
    ["Is breakfast included?","ସକାଳ ଜଳଖିଆ ସାମିଲ ଅଛି?","Sakala jalakhia samil achhi?"],
    ["The room is clean","ରୁମଟି ସଫା ଅଛି","Room ti sapha achhi"],
    ["Please bring water","ଦୟାକରି ପାଣି ଆଣନ୍ତୁ","Dayakari pani anantu"],
    ["I want to order food","ମୁଁ ଖାଦ୍ୟ ଅର୍ଡର କରିବାକୁ ଚାହେଁ","Mun khadya order karibaku chahen"],
    ["Please give me the menu","ଦୟାକରି ମେନୁ ଦିଅନ୍ତୁ","Dayakari menu diantu"],
    ["I want rice and vegetables","ମୋତେ ଭାତ ଓ ତରକାରୀ ଦିଅନ୍ତୁ","Mote bhata o tarakari diantu"],
    ["The food was very tasty","ଖାଦ୍ୟ ବହୁତ ସ୍ୱାଦିଷ୍ଟ ଥିଲା","Khadya bahut swadishta thila"],
    ["Please bring the bill","ଦୟାକରି ବିଲ ଆଣନ୍ତୁ","Dayakari bil anantu"],
    ["I am checking out tomorrow","ମୁଁ କାଲି ଚେକଆଉଟ କରିବି","Mun kali checkout karibi"],
    ["Is there WiFi here?","ଏଠାରେ ୱାଇଫାଇ ଅଛି?","Ethare WiFi achhi?"],
    ["Can I get an extra blanket?","ମୋତେ ଆଉ ଗୋଟିଏ କମ୍ବଳ ମିଳିବ?","Mote au gotie kambal miliba?"],
    ["Please clean the room","ଦୟାକରି ରୁମ ସଫା କରନ୍ତୁ","Dayakari room sapha karantu"],
    ["Thank you for the service","ସେବା ପାଇଁ ଧନ୍ୟବାଦ","Seba pain dhanyabad"],
    ["I had a good stay","ମୋର ରହିବା ଭଲ ହେଲା","Mora rahiba bhala hela"]
]
L[625] = [
    ["How is the weather today?","ଆଜି ପାଗ କେମିତି?","Aji paga kemiti?"],
    ["It is very hot today","ଆଜି ବହୁତ ଗରମ","Aji bahut garama"],
    ["It is cold today","ଆଜି ଶୀତ ଲାଗୁଛି","Aji shita laguchhi"],
    ["It is raining","ବର୍ଷା ହେଉଛି","Barsha heuchhi"],
    ["The rain has stopped","ବର୍ଷା ବନ୍ଦ ହୋଇଗଲା","Barsha banda hoigala"],
    ["The sky is cloudy","ଆକାଶ ମେଘୁଆ","Akasha meghua"],
    ["The sun is shining","ସୂର୍ଯ୍ୟ ଚମକୁଛି","Surya chamakuchhi"],
    ["The wind is blowing strongly","ଜୋରରେ ବାୟୁ ବହୁଛି","Jorare bayu bahuchhi"],
    ["It might rain tomorrow","କାଲି ବର୍ଷା ହୋଇପାରେ","Kali barsha hoipare"],
    ["Take an umbrella","ଛତା ନିଅନ୍ତୁ","Chhata niantu"],
    ["Summer is very hot here","ଏଠାରେ ଗ୍ରୀଷ୍ମ ବହୁତ ଗରମ","Ethare grishma bahut garama"],
    ["Winter is approaching","ଶୀତ ଆସୁଛି","Shita asuchhi"],
    ["I like rainy season","ମୋତେ ବର୍ଷା ଋତୁ ଭଲ ଲାଗେ","Mote barsha rutu bhala lage"],
    ["It is pleasant weather","ପାଗ ବହୁତ ସୁନ୍ଦର","Paga bahut sundar"],
    ["There was a storm yesterday","ଗତକାଲି ଝଡ଼ ହୋଇଥିଲା","Gatakali jhada hoithila"],
    ["The river floods in monsoon","ବର୍ଷାରେ ନଦୀ ବନ୍ୟା ହୁଏ","Barshare nadi banya hue"],
    ["Wear warm clothes","ଗରମ ଲୁଗା ପିନ୍ଧନ୍ତୁ","Garama luga pindhantu"],
    ["The fog is thick this morning","ଆଜି ସକାଳେ ଘନ କୁହୁଡ଼ି","Aji sakale ghana kuhudi"]
]
L[626] = [
    ["Good morning, officer","ନମସ୍କାର ସାର","Namaskaar sar"],
    ["Please show your license","ଦୟାକରି ଲାଇସେନ୍ସ ଦେଖାନ୍ତୁ","Dayakari license dekhantu"],
    ["Here is my driving license","ଏହା ମୋ ଡ୍ରାଇଭିଂ ଲାଇସେନ୍ସ","Eha mo driving license"],
    ["You were driving too fast","ଆପଣ ବହୁତ ଜୋରରେ ଚଲାଉଥିଲେ","Apana bahut jorare chalauthile"],
    ["I am sorry, I will be careful","କ୍ଷମା କରନ୍ତୁ, ମୁଁ ସାବଧାନ ହେବି","Kshama karantu, mun sabadhan hebi"],
    ["Where is the traffic signal?","ଟ୍ରାଫିକ ସିଗନାଲ କେଉଁଠି?","Traffic signal keunthi?"],
    ["Stop at the red light","ଲାଲ ବତୀରେ ଅଟକନ୍ତୁ","Lal batire atakantu"],
    ["Wear your helmet","ହେଲମେଟ ପିନ୍ଧନ୍ତୁ","Helmet pindhantu"],
    ["Wear your seatbelt","ସିଟବେଲ୍ଟ ଲଗାନ୍ତୁ","Seatbelt lagantu"],
    ["This road is one-way","ଏହା ଏକମୁଖୀ ରାସ୍ତା","Eha ekamukhi rasta"],
    ["You cannot park here","ଆପଣ ଏଠାରେ ପାର୍କ କରିପାରିବେ ନାହିଁ","Apana ethare park karibe nahin"],
    ["The road is blocked","ରାସ୍ତା ବନ୍ଦ ଅଛି","Rasta banda achhi"],
    ["Take the alternative route","ଅନ୍ୟ ରାସ୍ତା ନିଅନ୍ତୁ","Anya rasta niantu"],
    ["How much is the fine?","ଜୋରିମାନା କେତେ?","Jorimana kete?"],
    ["I will not break the rule again","ମୁଁ ଆଉ ନିୟମ ଭାଙ୍ଗିବି ନାହିଁ","Mun au niyama bhangibini nahin"],
    ["Drive safely","ସାବଧାନରେ ଚଲାନ୍ତୁ","Sabadhanare chalantu"],
    ["Follow the traffic rules","ଟ୍ରାଫିକ ନିୟମ ମାନନ୍ତୁ","Traffic niyama manantu"],
    ["Thank you officer","ଧନ୍ୟବାଦ ସାର","Dhanyabad sar"]
]
L[627] = [
    ["I need a rickshaw","ମୋତେ ଗୋଟିଏ ରିକ୍ସା ଦରକାର","Mote gotie riksa darkar"],
    ["Where do you want to go?","ଆପଣ କେଉଁଠି ଯିବାକୁ ଚାହୁଁଛନ୍ତି?","Apana keunthi yibaku chahunchanti?"],
    ["Take me to the bus stand","ମୋତେ ବସ ଷ୍ଟାଣ୍ଡକୁ ନିଅନ୍ତୁ","Mote bas stand ku niantu"],
    ["How much will you charge?","କେତେ ଟଙ୍କା ନେବେ?","Kete tanka nebe?"],
    ["That is too much","ଏହା ବହୁତ ବେଶୀ","Eha bahut beshi"],
    ["Please go faster","ଦୟାକରି ଜୋରରେ ଯାଆନ୍ତୁ","Dayakari jorare yaantu"],
    ["Please drive slowly","ଦୟାକରି ଧୀରେ ଚଲାନ୍ତୁ","Dayakari dhire chalantu"],
    ["Stop here please","ଦୟାକରି ଏଠାରେ ଅଟକନ୍ତୁ","Dayakari ethare atakantu"],
    ["Turn right at the next crossing","ପରବର୍ତ୍ତୀ ମୋଡ଼ରେ ଡାହାଣକୁ ଯାଆନ୍ତୁ","Parabarti modare dahanaku yaantu"],
    ["How far is the station?","ଷ୍ଟେସନ କେତେ ଦୂର?","Stesan kete dur?"],
    ["It will take 15 minutes","ପନ୍ଦର ମିନିଟ ଲାଗିବ","Pandara minit lagiba"],
    ["Can you wait here?","ଆପଣ ଏଠାରେ ଅପେକ୍ଷା କରିପାରିବେ?","Apana ethare apeksha karibe?"],
    ["I will come back in 10 minutes","ମୁଁ ଦଶ ମିନିଟରେ ଫେରିବି","Mun dasa minitare pheribi"],
    ["Keep the change","ବାକି ରଖନ୍ତୁ","Baki rakhantu"],
    ["Thank you for the ride","ଯାତ୍ରା ପାଇଁ ଧନ୍ୟବାଦ","Yatra pain dhanyabad"],
    ["The road has a lot of traffic","ରାସ୍ତାରେ ବହୁତ ଟ୍ରାଫିକ","Rastare bahut traffic"],
    ["Take the shortcut","ସଂକ୍ଷିପ୍ତ ରାସ୍ତା ନିଅନ୍ତୁ","Sankshipta rasta niantu"],
    ["We have reached, stop here","ଆମେ ପହଞ୍ଚିଗଲୁ, ଏଠାରେ ଅଟକନ୍ତୁ","Ame pahanchigalu, ethare atakantu"]
]
L[628] = [
    ["I work in a software company","ମୁଁ ସଫ୍ଟୱେର କମ୍ପାନୀରେ କାମ କରେ","Mun software company re kama kare"],
    ["What project are you working on?","ଆପଣ କେଉଁ ପ୍ରୋଜେକ୍ଟରେ କାମ କରୁଛନ୍ତି?","Apana keun project re kama karuchanti?"],
    ["I am a developer","ମୁଁ ଜଣେ ଡେଭେଲପର","Mun jane developer"],
    ["The deadline is tomorrow","ଡେଡଲାଇନ କାଲି","Deadline kali"],
    ["Let us have a meeting","ଆସନ୍ତୁ ମିଟିଂ କରିବା","Asantu meeting kariba"],
    ["I need to fix this bug","ମୋତେ ଏହି ବଗ ଠିକ କରିବାକୁ ହେବ","Mote ehi bug thik karibaku heba"],
    ["The code is working now","କୋଡ ଏବେ କାମ କରୁଛି","Code ebe kama karuchhi"],
    ["Can you review my code?","ଆପଣ ମୋ କୋଡ ରିଭିଉ କରିପାରିବେ?","Apana mo code review karipare?"],
    ["I will deploy it today","ମୁଁ ଆଜି ଡିପ୍ଲୋୟ କରିବି","Mun aji deploy karibi"],
    ["Work from home is convenient","ଘରୁ କାମ ସୁବିଧାଜନକ","Gharu kama subidhajanak"],
    ["I have a team meeting at 3","ମୋର ତିନିଟାରେ ଟିମ ମିଟିଂ","Mora tinitare team meeting"],
    ["The server is down","ସର୍ଭର ବନ୍ଦ ଅଛି","Server banda achhi"],
    ["I am learning a new technology","ମୁଁ ନୂଆ ଟେକ୍ନୋଲୋଜି ଶିଖୁଛି","Mun nua technology shikhuchhi"],
    ["Let me check the database","ମୋତେ ଡେଟାବେସ ଯାଞ୍ଚ କରିବାକୁ ଦିଅ","Mote database yancha karibaku dia"],
    ["The client is happy with the work","କ୍ଲାଏଣ୍ଟ କାମରେ ଖୁସି","Client kamare khusi"],
    ["I need a laptop for coding","ମୋତେ କୋଡିଂ ପାଇଁ ଲାପଟପ ଦରକାର","Mote coding pain laptop darkar"],
    ["What is your salary?","ଆପଣଙ୍କ ଦରମା କେତେ?","Apananka darma kete?"],
    ["I love my job","ମୋତେ ମୋ କାମ ଭଲ ଲାଗେ","Mote mo kama bhala lage"]
]
L[629] = [
    ["I need some rice","ମୋତେ କିଛି ଚାଉଳ ଦରକାର","Mote kichhi chaula darkar"],
    ["Give me one kilo of sugar","ଗୋଟିଏ କିଲୋ ଚିନି ଦିଅନ୍ତୁ","Gotie kilo chini diantu"],
    ["How much is the oil?","ତେଲ ଦାମ କେତେ?","Tela dama kete?"],
    ["Give me half kilo of salt","ଅଧା କିଲୋ ଲୁଣ ଦିଅନ୍ତୁ","Adha kilo luna diantu"],
    ["I need tea leaves","ମୋତେ ଚା ପତି ଦରକାର","Mote cha pati darkar"],
    ["Do you have turmeric?","ଆପଣଙ୍କ ପାଖରେ ହଳଦୀ ଅଛି?","Apananka pakhare haladi achhi?"],
    ["Give me two packets of biscuits","ଦୁଇ ପ୍ୟାକେଟ ବିସ୍କୁଟ ଦିଅନ୍ତୁ","Dui packet biscuit diantu"],
    ["How much is the total?","ମୋଟ କେତେ ହେଲା?","Mot kete hela?"],
    ["Do you have change?","ଆପଣଙ୍କ ପାଖରେ ଖୁଚୁରା ଅଛି?","Apananka pakhare khuchura achhi?"],
    ["Give me fresh milk","ତାଜା କ୍ଷୀର ଦିଅନ୍ତୁ","Taja kshira diantu"],
    ["I need soap and toothpaste","ମୋତେ ସାବୁନ ଓ ଟୁଥପେଷ୍ଟ ଦରକାର","Mote sabun o toothpaste darkar"],
    ["Is this fresh?","ଏହା ତାଜା?","Eha taja?"],
    ["Give me a bag","ଗୋଟିଏ ଥଳି ଦିଅନ୍ତୁ","Gotie thali diantu"],
    ["I need matchsticks","ମୋତେ ଦିଆସିଲି ଦରକାର","Mote diasili darkar"],
    ["Do you sell eggs?","ଆପଣ ଅଣ୍ଡା ବିକନ୍ତି?","Apana anda bikanti?"],
    ["Give me one dozen eggs","ଗୋଟିଏ ଡଜନ ଅଣ୍ଡା ଦିଅନ୍ତୁ","Gotie dozen anda diantu"],
    ["Here is the money","ଏହା ଟଙ୍କା","Eha tanka"],
    ["Thank you, goodbye","ଧନ୍ୟବାଦ, ନମସ୍କାର","Dhanyabad, namaskaar"]
]
L[630] = [
    ["Doctor, I am not feeling well","ଡାକ୍ତର, ମୋତେ ଭଲ ଲାଗୁନାହିଁ","Daktar, mote bhala lagunahi"],
    ["What is the problem?","କଣ ସମସ୍ୟା?","Kana samasya?"],
    ["I have a headache","ମୋର ମୁଣ୍ଡ ବିନ୍ଧୁଛି","Mora munda bindhuchhi"],
    ["I have a fever","ମୋର ଜ୍ୱର ଅଛି","Mora jwara achhi"],
    ["I have a stomach ache","ମୋର ପେଟ ବିନ୍ଧୁଛି","Mora peta bindhuchhi"],
    ["Since when are you sick?","କେବେଠୁ ଅସୁସ୍ଥ?","Kebethu asustha?"],
    ["Since two days","ଦୁଇ ଦିନ ହେଲା","Dui dina hela"],
    ["Let me check your temperature","ମୋତେ ଆପଣଙ୍କ ଜ୍ୱର ଯାଞ୍ଚ କରିବାକୁ ଦିଅ","Mote apananka jwara yancha karibaku dia"],
    ["Take this medicine three times a day","ଏହି ଔଷଧ ଦିନକୁ ତିନିଥର ଖାଆନ୍ତୁ","Ehi aushadh dinaku tinithara khaantu"],
    ["Drink plenty of water","ବହୁତ ପାଣି ପିଅନ୍ତୁ","Bahut pani piantu"],
    ["Take rest for two days","ଦୁଇ ଦିନ ବିଶ୍ରାମ ନିଅନ୍ତୁ","Dui dina bishram niantu"],
    ["Do I need any tests?","ମୋତେ କିଛି ଟେଷ୍ଟ ଦରକାର?","Mote kichhi test darkar?"],
    ["Yes, get a blood test done","ହଁ, ରକ୍ତ ପରୀକ୍ଷା କରାନ୍ତୁ","Han, rakta pariksha karantu"],
    ["I have cough and cold","ମୋର ଥଣ୍ଡା ଓ କାଶ ଅଛି","Mora thanda o kash achhi"],
    ["Avoid oily food","ତେଲିଆ ଖାଦ୍ୟ ଛାଡ଼ନ୍ତୁ","Telia khadya chhadantu"],
    ["Come back after three days","ତିନି ଦିନ ପରେ ଆସନ୍ତୁ","Tini dina pare asantu"],
    ["You will get better soon","ଆପଣ ଶୀଘ୍ର ଭଲ ହୋଇଯିବେ","Apana shighra bhala hoiyibe"],
    ["Thank you doctor","ଧନ୍ୟବାଦ ଡାକ୍ତର","Dhanyabad daktar"]
]
L[631] = [
    ["Good morning teacher","ନମସ୍କାର ସାର","Namaskaar sar"],
    ["Good morning children","ନମସ୍କାର ପିଲାମାନେ","Namaskaar pilamane"],
    ["Open your books to page 10","ଦଶ ପୃଷ୍ଠାରେ ବହି ଖୋଲନ୍ତୁ","Dasa prusthare bahi kholantu"],
    ["Read this lesson carefully","ଏହି ପାଠ ଭଲରେ ପଢ଼ନ୍ତୁ","Ehi patha bhala re padhantu"],
    ["Who knows the answer?","ଉତ୍ତର କିଏ ଜାଣେ?","Uttara kie jane?"],
    ["I know teacher!","ମୁଁ ଜାଣେ ସାର!","Mun jane sar!"],
    ["Very good! Well done!","ବହୁତ ଭଲ! ଶାବାସ!","Bahut bhala! Shabas!"],
    ["Write this in your notebook","ଏହା ଖାତାରେ ଲେଖନ୍ତୁ","Eha khatare lekhantu"],
    ["Do you understand?","ବୁଝିଲେ?","Bujhile?"],
    ["Yes teacher, we understand","ହଁ ସାର, ଆମେ ବୁଝିଲୁ","Han sar, ame bujhilu"],
    ["Complete your homework","ଗୃହକାର୍ଯ୍ୟ ସମ୍ପୂର୍ଣ୍ଣ କରନ୍ତୁ","Gruhakary sampurna karantu"],
    ["The exam is next week","ପରୀକ୍ଷା ଆସନ୍ତା ସପ୍ତାହରେ","Pariksha asanta saptahare"],
    ["Study well for the exam","ପରୀକ୍ଷା ପାଇଁ ଭଲରେ ପଢ଼ନ୍ତୁ","Pariksha pain bhala re padhantu"],
    ["Raise your hand to answer","ଉତ୍ତର ଦେବାକୁ ହାତ ଉଠାନ୍ତୁ","Uttara debaku hata uthantu"],
    ["Please be quiet","ଦୟାକରି ଚୁପ ରହନ୍ତୁ","Dayakari chupa rahantu"],
    ["The class is over","କ୍ଲାସ ସରିଲା","Class sarila"],
    ["Thank you teacher","ଧନ୍ୟବାଦ ସାର","Dhanyabad sar"],
    ["See you tomorrow","କାଲି ଭେଟିବା","Kali bhetiba"]
]
L[632] = [
    ["Hello, who is speaking?","ହେଲୋ, କିଏ କହୁଛନ୍ତି?","Hello, kie kahuchanti?"],
    ["It's me, Suren","ମୁଁ ସୁରେନ କହୁଛି","Mun Suren kahuchhi"],
    ["How are you?","ତୁମେ କେମିତି ଅଛ?","Tume kemiti achha?"],
    ["I am good, what about you?","ମୁଁ ଭଲ, ତୁମେ?","Mun bhala, tume?"],
    ["Where are you now?","ଏବେ କେଉଁଠି ଅଛ?","Ebe keunthi achha?"],
    ["I am at home","ମୁଁ ଘରେ ଅଛି","Mun ghare achhi"],
    ["Can we meet tomorrow?","କାଲି ଭେଟିବା?","Kali bhetiba?"],
    ["Yes, let's meet at the market","ହଁ, ବଜାରରେ ଭେଟିବା","Han, bajare bhetiba"],
    ["What time should I come?","ମୁଁ କେତେ ବେଳେ ଆସିବି?","Mun kete bele asibi?"],
    ["Come at 4 o'clock","ଚାରିଟାରେ ଆସ","Charitare asa"],
    ["Okay, I will come","ଠିକ ଅଛି, ଆସିବି","Thik achhi, asibi"],
    ["Did you eat?","ଖାଇଲ?","Khaila?"],
    ["Not yet, I will eat now","ଏପର୍ଯ୍ୟନ୍ତ ନାହିଁ, ଏବେ ଖାଇବି","Eparyanta nahin, ebe khaibi"],
    ["I called to tell you something","ତୋତେ କିଛି କହିବାକୁ ଫୋନ କଲି","Tote kichhi kahibaku phone kali"],
    ["Tell me, what is it?","କୁହ, କଣ?","Kuha, kana?"],
    ["I will tell you when we meet","ଭେଟିଲେ କହିବି","Bhetile kahibi"],
    ["Okay, bye then","ଠିକ ଅଛି, ବାଇ","Thik achhi, bye"],
    ["Bye, take care","ବାଇ, ଭଲରେ ଥାଅ","Bye, bhala re thaa"]
]
L[633] = [
    ["How much are the potatoes?","ଆଳୁ ଦାମ କେତେ?","Alu dama kete?"],
    ["Give me two kilos of onion","ଦୁଇ କିଲୋ ପିଆଜ ଦିଅନ୍ତୁ","Dui kilo piaj diantu"],
    ["These tomatoes are fresh","ଏହି ଟମାଟୋ ତାଜା","Ehi tomato taja"],
    ["Give me half kilo spinach","ଅଧା କିଲୋ ପାଳଙ୍ଗ ଦିଅନ୍ତୁ","Adha kilo palanga diantu"],
    ["Do you have green chillies?","କଞ୍ଚା ଲଙ୍କା ଅଛି?","Kancha lanka achhi?"],
    ["The brinjal is very nice","ବାଇଗଣ ବହୁତ ଭଲ","Baigana bahut bhala"],
    ["Is this cabbage fresh?","ଏହି ବନ୍ଧାକୋବି ତାଜା?","Ehi bandhakobi taja?"],
    ["Give me some coriander leaves","କିଛି ଧନିଆ ପତ୍ର ଦିଅନ୍ତୁ","Kichhi dhania patra diantu"],
    ["How much for all of this?","ସବୁ ମିଳାଇ କେତେ?","Sabu milai kete?"],
    ["That is too expensive","ଏହା ବହୁତ ମହଙ୍ଗା","Eha bahut mahanga"],
    ["Please give a good price","ଭଲ ଦାମ ଦିଅନ୍ତୁ","Bhala dama diantu"],
    ["Give me some ginger too","କିଛି ଅଦା ମଧ୍ୟ ଦିଅନ୍ତୁ","Kichhi ada madhya diantu"],
    ["I also need garlic","ମୋତେ ରସୁଣ ମଧ୍ୟ ଦରକାର","Mote rasuna madhya darkar"],
    ["Put it in the bag","ଥଳିରେ ଦିଅନ୍ତୁ","Thalire diantu"],
    ["Here is the money","ଏହା ଟଙ୍କା","Eha tanka"],
    ["Give me the change","ଖୁଚୁରା ଦିଅନ୍ତୁ","Khuchura diantu"],
    ["I will come again tomorrow","କାଲି ଆଉ ଆସିବି","Kali au asibi"],
    ["Thank you brother","ଧନ୍ୟବାଦ ଭାଇ","Dhanyabad bhai"]
]
L[634] = [
    ["Which bus goes to Puri?","ପୁରୀ ଯାଉଥିବା ବସ କେଉଁଟି?","Puri yauthiba bas keunti?"],
    ["When does the next bus come?","ପରବର୍ତ୍ତୀ ବସ କେବେ ଆସିବ?","Parabarti bas kebe asiba?"],
    ["One ticket to Cuttack please","ଗୋଟିଏ ଟିକେଟ କଟକ ପାଇଁ","Gotie ticket Cuttack pain"],
    ["How much is the fare?","ଭଡ଼ା କେତେ?","Bhada kete?"],
    ["Is this seat empty?","ଏହି ସିଟ ଖାଲି ଅଛି?","Ehi seat khali achhi?"],
    ["Yes, please sit","ହଁ, ବସନ୍ତୁ","Han, basantu"],
    ["Where does this bus stop?","ଏହି ବସ କେଉଁଠି ରହେ?","Ehi bas keunthi rahe?"],
    ["Please tell me when Cuttack comes","କଟକ ଆସିଲେ ମୋତେ କୁହନ୍ତୁ","Cuttack asile mote kuhantu"],
    ["The bus is very crowded","ବସରେ ବହୁତ ଭିଡ଼","Basare bahut bhida"],
    ["How long is the journey?","ଯାତ୍ରା କେତେ ସମୟ ଲାଗିବ?","Yatra kete samaya lagiba?"],
    ["About three hours","ପ୍ରାୟ ତିନି ଘଣ୍ଟା","Praya tini ghanta"],
    ["The bus has arrived","ବସ ଆସିଗଲା","Bas asigala"],
    ["Let's get on the bus","ଆସନ୍ତୁ ବସରେ ଚଢ଼ିବା","Asantu basare chadiba"],
    ["Please move inside","ଦୟାକରି ଭିତରକୁ ଯାଆନ୍ତୁ","Dayakari bhitaraku yaantu"],
    ["Stop, I need to get off here","ଅଟକନ୍ତୁ, ମୋତେ ଏଠାରେ ଓହ୍ଲାଇବାକୁ ହେବ","Atakantu, mote ethare ohlaibaku heba"],
    ["We have reached Cuttack","ଆମେ କଟକ ପହଞ୍ଚିଗଲୁ","Ame Cuttack pahanchigalu"],
    ["The bus is late today","ଆଜି ବସ ଲେଟ","Aji bas late"],
    ["Is there a direct bus?","ସିଧା ବସ ଅଛି?","Sidha bas achhi?"]
]
L[635] = [
    ["Excuse me, can you help me?","କ୍ଷମା କରନ୍ତୁ, ଆପଣ ମୋତେ ସାହାଯ୍ୟ କରିପାରିବେ?","Kshama karantu, apana mote sahayya karipare?"],
    ["I am looking for this address","ମୁଁ ଏହି ଠିକଣା ଖୋଜୁଛି","Mun ehi thikana khojuchhi"],
    ["Where is this place?","ଏହି ଜାଗା କେଉଁଠି?","Ehi jaga keunthi?"],
    ["Go straight from here","ଏଠାରୁ ସିଧା ଯାଆନ୍ତୁ","Etharu sidha yaantu"],
    ["Turn left at the crossing","ମୋଡ଼ରେ ବାମକୁ ଯାଆନ୍ତୁ","Modare bamaku yaantu"],
    ["Turn right after the temple","ମନ୍ଦିର ପରେ ଡାହାଣକୁ ଯାଆନ୍ତୁ","Mandira pare dahanaku yaantu"],
    ["It is about 500 meters ahead","ପ୍ରାୟ ପାଞ୍ଚଶହ ମିଟର ଆଗରେ","Praya paanchsaha mitar agare"],
    ["It is near the school","ସ୍କୁଲ ପାଖରେ","Skul pakhare"],
    ["Is it far from here?","ଏଠାରୁ ଦୂର?","Etharu dur?"],
    ["No, it is very close","ନାଁ, ବହୁତ ନିକଟରେ","Naan, bahut nikatare"],
    ["You can walk there","ଆପଣ ପାଦରେ ଯାଇପାରିବେ","Apana padare yaipare"],
    ["Ask anyone, they will tell you","ଯେ କାହାକୁ ପଚାରନ୍ତୁ, ସେ କହିବେ","Je kahaku pacharantu, se kahibe"],
    ["The blue house on the right","ଡାହାଣ ପଟେ ନୀଳ ଘର","Dahana pate nila ghara"],
    ["I can see it now","ମୁଁ ଏବେ ଦେଖୁଛି","Mun ebe dekhuchhi"],
    ["Thank you for your help","ଆପଣଙ୍କ ସାହାଯ୍ୟ ପାଇଁ ଧନ୍ୟବାଦ","Apananka sahayya pain dhanyabad"],
    ["You are welcome","ଆପଣଙ୍କୁ ସ୍ୱାଗତ","Apananku swagat"],
    ["Can you write the address for me?","ଆପଣ ମୋ ପାଇଁ ଠିକଣା ଲେଖିପାରିବେ?","Apana mo pain thikana lekhipare?"],
    ["Take the first lane on the left","ବାମ ପଟେ ପ୍ରଥମ ଗଳି ନିଅନ୍ତୁ","Bama pate prathama gali niantu"]
]
L[636] = [
    ["I love you","ମୁଁ ତୋତେ ଭଲ ପାଏ","Mun tote bhala pae"],
    ["You are very beautiful","ତୁମେ ବହୁତ ସୁନ୍ଦର","Tume bahut sundar"],
    ["I think about you always","ମୁଁ ସବୁବେଳେ ତୋ କଥା ଭାବେ","Mun sabubele to katha bhabe"],
    ["Will you be my friend?","ତୁମେ ମୋ ବନ୍ଧୁ ହେବ?","Tume mo bandhu heba?"],
    ["You make me happy","ତୁମେ ମୋତେ ଖୁସି କର","Tume mote khusi kara"],
    ["I cannot live without you","ମୁଁ ତୁମ ବିନା ବଞ୍ଚି ପାରିବି ନାହିଁ","Mun tuma bina banchi paribi nahin"],
    ["You are my life","ତୁମେ ମୋ ଜୀବନ","Tume mo jibana"],
    ["I love you from my heart","ମୁଁ ହୃଦୟରୁ ତୋତେ ଭଲ ପାଏ","Mun hrudayaru tote bhala pae"],
    ["Will you marry me?","ତୁମେ ମୋ ସହ ବିବାହ କରିବ?","Tume mo saha bibaha kariba?"],
    ["My heart beats for you","ମୋ ହୃଦୟ ତୋ ପାଇଁ ଧଡ଼କେ","Mora hrudaya to pain dhadake"],
    ["You are very special to me","ତୁମେ ମୋ ପାଇଁ ବହୁତ ବିଶେଷ","Tume mo pain bahut bishesha"],
    ["I miss you","ମୁଁ ତୋତେ ମନେ ପକାଉଛି","Mun tote mane pakauchhi"],
    ["Your smile is beautiful","ତୁମ ହସ ବହୁତ ସୁନ୍ଦର","Tuma hasa bahut sundar"],
    ["I have loved you for a long time","ମୁଁ ବହୁ ଦିନ ହେଲା ତୋତେ ଭଲ ପାଏ","Mun bahu dina hela tote bhala pae"],
    ["Do you love me?","ତୁମେ ମୋତେ ଭଲ ପାଅ?","Tume mote bhala paa?"],
    ["I will always be with you","ମୁଁ ସବୁବେଳେ ତୋ ସହ ଥିବି","Mun sabubele to saha thibi"],
    ["You are the moon of my life","ତୁମେ ମୋ ଜୀବନର ଚନ୍ଦ୍ର","Tume mo jibanara chandra"],
    ["I promise to love you forever","ମୁଁ ସବୁଦିନ ତୋତେ ଭଲ ପାଇବାର ପ୍ରତିଜ୍ଞା କରେ","Mun sabudina tote bhala paibara pratijna kare"]
]
L[637] = [
    ["Good morning, please have a seat","ନମସ୍କାର, ଦୟାକରି ବସନ୍ତୁ","Namaskaar, dayakari basantu"],
    ["Tell me about yourself","ଆପଣଙ୍କ ବିଷୟରେ କୁହନ୍ତୁ","Apananka bishayare kuhantu"],
    ["My name is Mohan","ମୋ ନାମ ମୋହନ","Mo naama Mohan"],
    ["What is your qualification?","ଆପଣଙ୍କ ଶିକ୍ଷାଗତ ଯୋଗ୍ୟତା କଣ?","Apananka shikshagata yogyata kana?"],
    ["I have completed my graduation","ମୁଁ ସ୍ନାତକ ସମ୍ପୂର୍ଣ୍ଣ କରିଛି","Mun snataka sampurna karichhi"],
    ["Do you have any experience?","ଆପଣଙ୍କର ଅଭିଜ୍ଞତା ଅଛି?","Apanankara abhijnata achhi?"],
    ["I have two years of experience","ମୋର ଦୁଇ ବର୍ଷର ଅଭିଜ୍ଞତା ଅଛି","Mora dui barshara abhijnata achhi"],
    ["Why do you want this job?","ଆପଣ ଏହି ଚାକିରୀ କାହିଁକି ଚାହୁଁଛନ୍ତି?","Apana ehi chakiri kahinki chahunchanti?"],
    ["I want to grow in my career","ମୁଁ ମୋ କ୍ୟାରିୟରରେ ବୃଦ୍ଧି ଚାହେଁ","Mun mo career re bruddhi chahen"],
    ["What are your strengths?","ଆପଣଙ୍କ ଶକ୍ତି କଣ?","Apananka shakti kana?"],
    ["I am hardworking and honest","ମୁଁ ପରିଶ୍ରମୀ ଓ ସଚ୍ଚୋଟ","Mun parishramee o sachchota"],
    ["Can you speak English?","ଆପଣ ଇଂରାଜୀ କହିପାରିବେ?","Apana Ingraji kahipare?"],
    ["Yes, I can speak English and Odia","ହଁ, ମୁଁ ଇଂରାଜୀ ଓ ଓଡ଼ିଆ କହିପାରେ","Han, mun Ingraji o Odia kahipare"],
    ["When can you start?","ଆପଣ କେବେ ଆରମ୍ଭ କରିପାରିବେ?","Apana kebe arambha karipare?"],
    ["I can start immediately","ମୁଁ ଏବେଠୁ ଆରମ୍ଭ କରିପାରିବି","Mun ebethu arambha karibi"],
    ["We will let you know the result","ଆମେ ଆପଣଙ୍କୁ ଫଳାଫଳ ଜଣାଇବୁ","Ame apananku phalaphala janaibu"],
    ["Thank you for the opportunity","ସୁଯୋଗ ପାଇଁ ଧନ୍ୟବାଦ","Suyoga pain dhanyabad"],
    ["I hope to hear from you soon","ଆପଣଙ୍କ ଉତ୍ତର ଆଶା କରୁଛି","Apananka uttara asha karuchhi"]
]
L[638] = [
    ["Please come on time every day","ପ୍ରତିଦିନ ଠିକ ସମୟରେ ଆସନ୍ତୁ","Pratidina thik samayare asantu"],
    ["Clean the floor first","ପ୍ରଥମେ ଚଟାଣ ସଫା କରନ୍ତୁ","Prathame chatana sapha karantu"],
    ["Wash the dishes","ବାସନ ଧୋଅନ୍ତୁ","Basana dhoantu"],
    ["Please wash the clothes","ଦୟାକରି ଲୁଗା ଧୋଅନ୍ତୁ","Dayakari luga dhoantu"],
    ["Cook the rice","ଭାତ ରାନ୍ଧନ୍ତୁ","Bhata randhantu"],
    ["Sweep the courtyard","ଅଗଣା ଝାଡ଼ୁ ମାରନ୍ତୁ","Agana jhadu marantu"],
    ["Bring water from the well","କୂଅରୁ ପାଣି ଆଣନ୍ତୁ","Kuaru pani anantu"],
    ["Did you finish the work?","କାମ ସରିଲା?","Kama sarila?"],
    ["Yes, I have finished everything","ହଁ, ସବୁ ସରିଗଲା","Han, sabu sarigala"],
    ["Please iron the clothes","ଦୟାକରି ଲୁଗା ଇସ୍ତ୍ରୀ କରନ୍ତୁ","Dayakari luga istri karantu"],
    ["You may go now","ଆପଣ ଏବେ ଯାଇପାରିବେ","Apana ebe yaipare"],
    ["I will come tomorrow also","ମୁଁ କାଲି ମଧ୍ୟ ଆସିବି","Mun kali madhya asibi"],
    ["Take your salary","ଆପଣଙ୍କ ଦରମା ନିଅନ୍ତୁ","Apananka darma niantu"],
    ["Tomorrow is a holiday, don't come","କାଲି ଛୁଟି, ଆସିବେ ନାହିଁ","Kali chhuti, asibe nahin"],
    ["Clean the rooms properly","ରୁମ ଭଲରେ ସଫା କରନ୍ତୁ","Room bhala re sapha karantu"],
    ["The kitchen needs cleaning","ରୋଷେଇ ଘର ସଫା ଦରକାର","Rosei ghara sapha darkar"],
    ["Please water the plants","ଦୟାକରି ଗଛକୁ ପାଣି ଦିଅନ୍ତୁ","Dayakari gachhaku pani diantu"],
    ["Thank you for your work","ଆପଣଙ୍କ କାମ ପାଇଁ ଧନ୍ୟବାଦ","Apananka kama pain dhanyabad"]
]
L[639] = [
    ["I want to link my AADHAR to mobile","ମୁଁ ଆଧାରକୁ ମୋବାଇଲ ସହ ଯୋଡ଼ିବାକୁ ଚାହେଁ","Mun aadharku mobile saha yodibaku chahen"],
    ["Please come to the centre","ଦୟାକରି ସେଣ୍ଟରରେ ଆସନ୍ତୁ","Dayakari centre re asantu"],
    ["Bring your AADHAR card","ଆପଣଙ୍କ ଆଧାର କାର୍ଡ ଆଣନ୍ତୁ","Apananka aadhar card anantu"],
    ["What is your mobile number?","ଆପଣଙ୍କ ମୋବାଇଲ ନମ୍ବର କଣ?","Apananka mobile number kana?"],
    ["Give me your AADHAR number","ଆପଣଙ୍କ ଆଧାର ନମ୍ବର ଦିଅନ୍ତୁ","Apananka aadhar number diantu"],
    ["Place your finger on the scanner","ସ୍କାନରରେ ଆଙ୍ଗୁଠି ରଖନ୍ତୁ","Scanner re anguthi rakhantu"],
    ["Your fingerprint was verified","ଆପଣଙ୍କ ଫିଙ୍ଗରପ୍ରିଣ୍ଟ ଯାଞ୍ଚ ହୋଇଗଲା","Apananka fingerprint yancha hoigala"],
    ["You will receive an OTP","ଆପଣଙ୍କୁ ଓଟିପି ଆସିବ","Apananku OTP asiba"],
    ["Please enter the OTP","ଦୟାକରି ଓଟିପି ଦିଅନ୍ତୁ","Dayakari OTP diantu"],
    ["Your AADHAR is now linked","ଆପଣଙ୍କ ଆଧାର ଏବେ ଯୋଡ଼ି ହୋଇଗଲା","Apananka aadhar ebe yodi hoigala"],
    ["Is there any charge for this?","ଏଥିପାଇଁ କିଛି ଖର୍ଚ୍ଚ ଅଛି?","Ethipain kichhi kharcha achhi?"],
    ["No, it is free of cost","ନାଁ, ଏହା ମାଗଣା","Naan, eha magana"],
    ["How long does it take?","କେତେ ସମୟ ଲାଗିବ?","Kete samaya lagiba?"],
    ["It takes only five minutes","ମାତ୍ର ପାଞ୍ଚ ମିନିଟ ଲାଗିବ","Matra pancha minit lagiba"],
    ["Keep this receipt safely","ଏହି ରସିଦ ସୁରକ୍ଷିତ ରଖନ୍ତୁ","Ehi rasid surakshit rakhantu"],
    ["Thank you for your help","ଆପଣଙ୍କ ସାହାଯ୍ୟ ପାଇଁ ଧନ୍ୟବାଦ","Apananka sahayya pain dhanyabad"],
    ["Now my mobile is linked to AADHAR","ଏବେ ମୋ ମୋବାଇଲ ଆଧାର ସହ ଯୋଡ଼ି ହୋଇଗଲା","Ebe mo mobile aadhar saha yodi hoigala"],
    ["Do I need to come again?","ମୋତେ ଆଉ ଆସିବାକୁ ହେବ?","Mote au asibaku heba?"]
]
L[640] = [
    ["I need to update my mobile number","ମୋତେ ମୋ ମୋବାଇଲ ନମ୍ବର ଅପଡେଟ କରିବାକୁ ହେବ","Mote mo mobile number update karibaku heba"],
    ["My old number is not working","ମୋ ପୁରୁଣା ନମ୍ବର କାମ କରୁନାହିଁ","Mo puruna number kama karunahin"],
    ["Please bring your AADHAR card","ଦୟାକରି ଆଧାର କାର୍ଡ ଆଣନ୍ତୁ","Dayakari aadhar card anantu"],
    ["Bring the new SIM card","ନୂଆ ସିମ କାର୍ଡ ଆଣନ୍ତୁ","Nua SIM card anantu"],
    ["Fill this form","ଏହି ଫର୍ମ ପୂରଣ କରନ୍ତୁ","Ehi form purana karantu"],
    ["Write your new mobile number here","ଏଠାରେ ନୂଆ ମୋବାଇଲ ନମ୍ବର ଲେଖନ୍ତୁ","Ethare nua mobile number lekhantu"],
    ["Place your thumb for verification","ଯାଞ୍ଚ ପାଇଁ ବୁଢ଼ା ଆଙ୍ଗୁଠି ରଖନ୍ତୁ","Yancha pain budha anguthi rakhantu"],
    ["Your identity has been verified","ଆପଣଙ୍କ ପରିଚୟ ଯାଞ୍ଚ ହୋଇଗଲା","Apananka parichaya yancha hoigala"],
    ["An OTP will be sent to new number","ନୂଆ ନମ୍ବରରେ ଓଟିପି ଆସିବ","Nua number re OTP asiba"],
    ["Enter the OTP here","ଏଠାରେ ଓଟିପି ଦିଅନ୍ତୁ","Ethare OTP diantu"],
    ["Your number has been updated","ଆପଣଙ୍କ ନମ୍ବର ଅପଡେଟ ହୋଇଗଲା","Apananka number update hoigala"],
    ["It will take 24 hours to activate","ସକ୍ରିୟ ହେବାକୁ ୨୪ ଘଣ୍ଟା ଲାଗିବ","Sakriya hebaku 24 ghanta lagiba"],
    ["Keep the acknowledgment slip","ସ୍ୱୀକୃତି ସ୍ଲିପ ରଖନ୍ତୁ","Swikruti slip rakhantu"],
    ["Is there any problem?","କିଛି ସମସ୍ୟା ଅଛି?","Kichhi samasya achhi?"],
    ["No problem, it is simple","କୌଣସି ସମସ୍ୟା ନାହିଁ, ଏହା ସହଜ","Kounasi samasya nahin, eha sahaja"],
    ["Can I do it online?","ମୁଁ ଅନଲାଇନରେ କରିପାରିବି?","Mun online re karibi?"],
    ["Yes, from the website","ହଁ, ୱେବସାଇଟରୁ","Han, website ru"],
    ["Thank you for the information","ସୂଚନା ପାଇଁ ଧନ୍ୟବାଦ","Suchana pain dhanyabad"]
]
L[641] = [
    ["Happy Republic Day!","ସୁଖ ଗଣତନ୍ତ୍ର ଦିବସ!","Sukha Ganatantra Dibas!"],
    ["Today is 26th January","ଆଜି ୨୬ ଜାନୁଆରୀ","Aji 26 January"],
    ["We celebrate Republic Day every year","ଆମେ ପ୍ରତିବର୍ଷ ଗଣତନ୍ତ୍ର ଦିବସ ପାଳନ କରୁ","Ame pratibarsha Ganatantra Dibas palana karu"],
    ["The flag is hoisted in school","ସ୍କୁଲରେ ପତାକା ଉତ୍ତୋଳନ ହୁଏ","Skul re pataka uttolana hue"],
    ["Children sing the national anthem","ପିଲାମାନେ ରାଷ୍ଟ୍ରଗୀତ ଗାଇନ୍ତି","Pilamane rashtragita gainti"],
    ["There is a parade in Delhi","ଦିଲ୍ଲୀରେ ପରେଡ ହୁଏ","Dilli re parade hue"],
    ["Our Constitution was adopted on this day","ଏହି ଦିନ ସମ୍ବିଧାନ ଗ୍ରହଣ ହୋଇଥିଲା","Ehi dina sambidhana grahana hoithila"],
    ["We are proud of our country","ଆମେ ଆମ ଦେଶ ପାଇଁ ଗର୍ବିତ","Ame ama desha pain garbita"],
    ["India became a republic in 1950","ଭାରତ ୧୯୫୦ରେ ଗଣତନ୍ତ୍ର ହୋଇଥିଲା","Bharat 1950 re ganatantra hoithila"],
    ["Sweets are distributed in school","ସ୍କୁଲରେ ମିଠା ବାଣ୍ଟା ହୁଏ","Skul re mitha banta hue"],
    ["We should love our country","ଆମେ ଆମ ଦେଶକୁ ଭଲ ପାଇବା ଉଚିତ","Ame ama deshaku bhala paiba uchita"],
    ["Freedom fighters sacrificed for us","ସ୍ୱାଧୀନତା ସଂଗ୍ରାମୀମାନେ ଆମ ପାଇଁ ବଳିଦାନ ଦେଲେ","Swadhinata sangramimane ama pain balidana dele"],
    ["Students give cultural performances","ଛାତ୍ରମାନେ ସାଂସ୍କୃତିକ ଅନୁଷ୍ଠାନ ଦିଅନ୍ତି","Chhatramane sanskrutik anushthana dianti"],
    ["Let us salute our nation","ଆସନ୍ତୁ ଆମ ଦେଶକୁ ସଲାମ କରିବା","Asantu ama deshaku salaam kariba"],
    ["Unity in diversity is our strength","ବିଭିନ୍ନତାରେ ଏକତା ଆମ ଶକ୍ତି","Bibhinnatare ekata ama shakti"],
    ["Jai Hind! Long live India!","ଜୟ ହିନ୍ଦ! ଭାରତ ଚିରଜୀବୀ ହେଉ!","Jai Hind! Bharat chirajeebi heu!"],
    ["We celebrate with pride and joy","ଆମେ ଗର୍ବ ଓ ଖୁସିରେ ପାଳନ କରୁ","Ame garba o khusire palana karu"],
    ["May our country always prosper","ଆମ ଦେଶ ସବୁବେଳେ ଉନ୍ନତି କରୁ","Ama desha sabubele unnati karu"]
]

for ch in d:
    if ch['id'] in L:
        ch['blocks'] = [{"type":"table","columns":["English","Odia","Transliteration"],"rows":L[ch['id']]}]
open('data_odia.json','w',encoding='utf-8').write(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
print('Odia S5a (620-641) populated - 22 lessons')
