#!/usr/bin/env python3
"""
Populate Section 2 (IDs 510-542) of data_odia.json with 33 Grammar lessons.
Each lesson has 18 rows of [English, Odia, Transliteration].
"""
import json
from pathlib import Path

BASE = Path(__file__).parent.resolve()

LESSONS = {

# ━━━ 510: Gender in Odia (ପୁଲିଙ୍ଗ/ସ୍ତ୍ରୀଲିଙ୍ଗ) ━━━
510: [
    ["Boy", "ପୁଅ", "pua"],
    ["Girl", "ଝିଅ", "jhia"],
    ["Man", "ପୁରୁଷ", "purusha"],
    ["Woman", "ସ୍ତ୍ରୀ", "stri"],
    ["King", "ରାଜା", "raja"],
    ["Queen", "ରାଣୀ", "rani"],
    ["Lion", "ସିଂହ", "simha"],
    ["Lioness", "ସିଂହୀ", "simhi"],
    ["God", "ଦେବତା", "debata"],
    ["Goddess", "ଦେବୀ", "debi"],
    ["Actor", "ଅଭିନେତା", "abhineta"],
    ["Actress", "ଅଭିନେତ୍ରୀ", "abhinetri"],
    ["Horse", "ଘୋଡ଼ା", "ghoda"],
    ["Mare", "ଘୋଡ଼ୀ", "ghodi"],
    ["The boy is tall", "ପୁଅଟି ଲମ୍ବା", "puati lamba"],
    ["The girl is smart", "ଝିଅଟି ଚତୁର", "jhiati chatura"],
    ["He is a good man", "ସେ ଜଣେ ଭଲ ପୁରୁଷ", "se jane bhala purusha"],
    ["She is a brave woman", "ସେ ଜଣେ ସାହସୀ ସ୍ତ୍ରୀ", "se jane sahasi stri"],
],

# ━━━ 511: Singular and Plural ━━━
511: [
    ["Book", "ବହି", "bahi"],
    ["Books", "ବହିଗୁଡ଼ିକ", "bahigudika"],
    ["Child", "ପିଲା", "pila"],
    ["Children", "ପିଲାମାନେ", "pilamane"],
    ["Tree", "ଗଛ", "gachha"],
    ["Trees", "ଗଛଗୁଡ଼ିକ", "gachhagudika"],
    ["Flower", "ଫୁଲ", "phula"],
    ["Flowers", "ଫୁଲଗୁଡ଼ିକ", "phulagudika"],
    ["Bird", "ପକ୍ଷୀ", "pakshi"],
    ["Birds", "ପକ୍ଷୀମାନେ", "pakshimane"],
    ["The boy came", "ପୁଅଟି ଆସିଲା", "puati asila"],
    ["The boys came", "ପୁଅମାନେ ଆସିଲେ", "puamane asile"],
    ["The dog is running", "କୁକୁରଟି ଦୌଡ଼ୁଛି", "kukurati dauduchhi"],
    ["The dogs are running", "କୁକୁରଗୁଡ଼ିକ ଦୌଡ଼ୁଛନ୍ତି", "kukuragudika dauduchanti"],
    ["Give me a pen", "ମୋତେ ଗୋଟିଏ କଲମ ଦିଅ", "mote gotie kalama dia"],
    ["Give me the pens", "ମୋତେ କଲମଗୁଡ଼ିକ ଦିଅ", "mote kalamagudika dia"],
    ["The star shines", "ତାରାଟି ଜଳୁଛି", "tarati jaluchhi"],
    ["The stars shine", "ତାରାଗୁଡ଼ିକ ଜଳୁଛନ୍ତି", "taragudika jaluchanti"],
],

# ━━━ 512: Case markers in Odia ━━━
512: [
    ["Nominative: The boy reads", "ପୁଅଟି ପଢ଼େ", "puati padhe"],
    ["Accusative: I see him", "ମୁଁ ତାକୁ ଦେଖୁଛି", "mun taku dekhuchhi"],
    ["Instrumental: He writes with a pen", "ସେ କଲମରେ ଲେଖେ", "se kalamare lekhe"],
    ["Dative: Give the book to me", "ମୋତେ ବହିଟି ଦିଅ", "mote bahiti dia"],
    ["Ablative: He came from the village", "ସେ ଗାଁରୁ ଆସିଲା", "se ganru asila"],
    ["Genitive: This is my house", "ଏହା ମୋ ଘର", "eha mo ghara"],
    ["Locative: The cat is on the roof", "ବିଲେଇ ଛାତ ଉପରେ ଅଛି", "bilei chhata upare achhi"],
    ["I gave money to him", "ମୁଁ ତାକୁ ଟଙ୍କା ଦେଲି", "mun taku tanka deli"],
    ["She came by bus", "ସେ ବସ୍‌ରେ ଆସିଲା", "se basre asila"],
    ["The pen is in the box", "କଲମଟି ବାକ୍ସ ଭିତରେ ଅଛି", "kalamati baksa bhitare achhi"],
    ["Father's shirt is white", "ବାପାଙ୍କ ସାର୍ଟ ଧଳା", "bapanka sarta dhala"],
    ["He hit me with a stick", "ସେ ମୋତେ ବାଡ଼ିରେ ମାରିଲା", "se mote badire marila"],
    ["Water flows from the hill", "ପାହାଡ଼ରୁ ପାଣି ଗଡ଼େ", "pahadru pani gade"],
    ["I am going to the market", "ମୁଁ ବଜାରକୁ ଯାଉଛି", "mun bajaraku jauchhi"],
    ["The bird is on the tree", "ପକ୍ଷୀଟି ଗଛ ଉପରେ ଅଛି", "pakshiti gachha upare achhi"],
    ["This is Rama's book", "ଏହା ରାମର ବହି", "eha Ramara bahi"],
    ["I went with my friend", "ମୁଁ ମୋ ସାଙ୍ଗ ସହିତ ଗଲି", "mun mo sanga sahita gali"],
    ["Sit on the chair", "ଚେୟାର ଉପରେ ବସ", "cheyara upare basa"],
],

# ━━━ 513: Pronoun forms ━━━
513: [
    ["I", "ମୁଁ", "mun"],
    ["You (informal)", "ତୁ", "tu"],
    ["You (formal)", "ଆପଣ", "apana"],
    ["He / She", "ସେ", "se"],
    ["We", "ଆମେ", "ame"],
    ["They", "ସେମାନେ", "semane"],
    ["This", "ଏହା", "eha"],
    ["That", "ସେହା", "seha"],
    ["Who", "କିଏ", "kie"],
    ["What", "କ'ଣ", "kana"],
    ["My name is Sita", "ମୋ ନାମ ସୀତା", "mo nama Sita"],
    ["You are my friend", "ତୁ ମୋ ସାଙ୍ଗ", "tu mo sanga"],
    ["He is a teacher", "ସେ ଜଣେ ଶିକ୍ଷକ", "se jane shikshaka"],
    ["We are students", "ଆମେ ଛାତ୍ର", "ame chatra"],
    ["They went home", "ସେମାନେ ଘରକୁ ଗଲେ", "semane gharaku gale"],
    ["This is mine", "ଏହା ମୋର", "eha mora"],
    ["Who came yesterday?", "ଗତକାଲି କିଏ ଆସିଥିଲା?", "gatakali kie asithila?"],
    ["What do you want?", "ତୁ କ'ଣ ଚାହୁଁଛ?", "tu kana chahunchha?"],
],

# ━━━ 514: Verb conjugation Present tense ━━━
514: [
    ["I eat rice", "ମୁଁ ଭାତ ଖାଏ", "mun bhata khae"],
    ["You eat fruit", "ତୁ ଫଳ ଖାଉଛ", "tu phala khauchha"],
    ["He reads a book", "ସେ ବହି ପଢ଼େ", "se bahi padhe"],
    ["She writes a letter", "ସେ ଚିଠି ଲେଖେ", "se chithi lekhe"],
    ["We go to school", "ଆମେ ସ୍କୁଲ ଯାଉ", "ame skula jau"],
    ["They play cricket", "ସେମାନେ କ୍ରିକେଟ୍ ଖେଳନ୍ତି", "semane kriket khelanti"],
    ["I drink water", "ମୁଁ ପାଣି ପିଏ", "mun pani pie"],
    ["You speak Odia", "ତୁ ଓଡ଼ିଆ କହୁଛ", "tu odia kahuchha"],
    ["He works daily", "ସେ ପ୍ରତିଦିନ କାମ କରେ", "se pratidina kama kare"],
    ["She sings well", "ସେ ଭଲ ଗାଏ", "se bhala gae"],
    ["We live in Odisha", "ଆମେ ଓଡ଼ିଶାରେ ରହୁ", "ame odishare rahu"],
    ["They come every day", "ସେମାନେ ପ୍ରତିଦିନ ଆସନ୍ତି", "semane pratidina asanti"],
    ["I know the answer", "ମୁଁ ଉତ୍ତର ଜାଣେ", "mun uttara jane"],
    ["He teaches children", "ସେ ପିଲାମାନଙ୍କୁ ପଢ଼ାଏ", "se pilamanunku padhae"],
    ["She cooks food", "ସେ ଖାଦ୍ୟ ରାନ୍ଧେ", "se khadya randhe"],
    ["We study Odia", "ଆମେ ଓଡ଼ିଆ ପଢ଼ୁ", "ame odia padhu"],
    ["I love my mother", "ମୁଁ ମୋ ମାଆକୁ ଭଲ ପାଏ", "mun mo maaku bhala pae"],
    ["He sells vegetables", "ସେ ପରିବା ବିକେ", "se pariba bike"],
],

# ━━━ 515: Verb conjugation Past tense ━━━
515: [
    ["I ate rice", "ମୁଁ ଭାତ ଖାଇଲି", "mun bhata khaili"],
    ["You went to school", "ତୁ ସ୍କୁଲ ଗଲୁ", "tu skula galu"],
    ["He came yesterday", "ସେ ଗତକାଲି ଆସିଲା", "se gatakali asila"],
    ["She wrote a letter", "ସେ ଚିଠି ଲେଖିଲା", "se chithi lekhila"],
    ["We played football", "ଆମେ ଫୁଟ୍‌ବଲ୍ ଖେଳିଲୁ", "ame phutbal khelilu"],
    ["They sang a song", "ସେମାନେ ଗୀତ ଗାଇଲେ", "semane gita gaile"],
    ["I drank water", "ମୁଁ ପାଣି ପିଇଲି", "mun pani piili"],
    ["He read the book", "ସେ ବହିଟି ପଢ଼ିଲା", "se bahiti padhila"],
    ["She cooked food", "ସେ ଖାଦ୍ୟ ରାନ୍ଧିଲା", "se khadya randhila"],
    ["We saw a movie", "ଆମେ ସିନେମା ଦେଖିଲୁ", "ame sinema dekhilu"],
    ["They went home", "ସେମାନେ ଘରକୁ ଗଲେ", "semane gharaku gale"],
    ["I slept early", "ମୁଁ ଲଗେ ଶୋଇଲି", "mun lage soili"],
    ["He bought a shirt", "ସେ ଗୋଟିଏ ସାର୍ଟ କିଣିଲା", "se gotie sarta kinila"],
    ["She told a story", "ସେ ଗୋଟିଏ କାହାଣୀ କହିଲା", "se gotie kahani kahila"],
    ["We finished the work", "ଆମେ କାମ ସାରିଲୁ", "ame kama sarilu"],
    ["They arrived today", "ସେମାନେ ଆଜି ପହଞ୍ଚିଲେ", "semane aji pahanchile"],
    ["I gave him money", "ମୁଁ ତାକୁ ଟଙ୍କା ଦେଲି", "mun taku tanka deli"],
    ["He ran very fast", "ସେ ବହୁତ ଜୋରରେ ଦୌଡ଼ିଲା", "se bahuta jorare daudila"],
],

# ━━━ 516: Verb conjugation Future tense ━━━
516: [
    ["I will go tomorrow", "ମୁଁ କାଲି ଯିବି", "mun kali jibi"],
    ["You will eat", "ତୁ ଖାଇବୁ", "tu khaibu"],
    ["He will come", "ସେ ଆସିବ", "se asiba"],
    ["She will read", "ସେ ପଢ଼ିବ", "se padhiba"],
    ["We will play", "ଆମେ ଖେଳିବୁ", "ame khelibu"],
    ["They will sing", "ସେମାନେ ଗାଇବେ", "semane gaibe"],
    ["I will write a letter", "ମୁଁ ଚିଠି ଲେଖିବି", "mun chithi lekhibi"],
    ["He will go to Puri", "ସେ ପୁରୀ ଯିବ", "se Puri jiba"],
    ["She will cook dinner", "ସେ ରାତି ଖାଣା ରାନ୍ଧିବ", "se rati khana randhiba"],
    ["We will study hard", "ଆମେ କଠିନ ପରିଶ୍ରମ କରିବୁ", "ame kathina parishrama karibu"],
    ["They will come back", "ସେମାନେ ଫେରି ଆସିବେ", "semane pheri asibe"],
    ["I will drink tea", "ମୁଁ ଚା ପିଇବି", "mun cha piibi"],
    ["You will understand", "ତୁ ବୁଝିବୁ", "tu bujibu"],
    ["He will finish the work", "ସେ କାମ ସାରିବ", "se kama sariba"],
    ["She will buy vegetables", "ସେ ପରିବା କିଣିବ", "se pariba kiniba"],
    ["Will you come with me?", "ତୁ ମୋ ସହ ଆସିବୁ କି?", "tu mo saha asibu ki?"],
    ["I will learn Odia", "ମୁଁ ଓଡ଼ିଆ ଶିଖିବି", "mun odia shikhibi"],
    ["We will meet tomorrow", "ଆମେ କାଲି ଭେଟିବୁ", "ame kali bhetibu"],
],

# ━━━ 517: Imperative mood ━━━
517: [
    ["Come!", "ଆସ!", "asa!"],
    ["Go!", "ଯାଅ!", "jaa!"],
    ["Sit down!", "ବସ!", "basa!"],
    ["Eat!", "ଖାଅ!", "khaa!"],
    ["Drink water!", "ପାଣି ପିଅ!", "pani pia!"],
    ["Read the book!", "ବହି ପଢ଼!", "bahi padha!"],
    ["Write your name!", "ତୁମ ନାମ ଲେଖ!", "tuma nama lekha!"],
    ["Open the door!", "କବାଟ ଖୋଲ!", "kabata khola!"],
    ["Close the window!", "ଝରକା ବନ୍ଦ କର!", "jharaka banda kara!"],
    ["Run fast!", "ଜୋରରେ ଦୌଡ଼!", "jorare dauda!"],
    ["Please come (formal)", "ଦୟାକରି ଆସନ୍ତୁ", "dayakari asantu"],
    ["Please sit (formal)", "ଦୟାକରି ବସନ୍ତୁ", "dayakari basantu"],
    ["Listen carefully!", "ଧ୍ୟାନରେ ଶୁଣ!", "dhyanare shuna!"],
    ["Don't go!", "ଯାଅ ନାହିଁ!", "jaa nahin!"],
    ["Speak the truth!", "ସତ କୁହ!", "sata kuha!"],
    ["Give me the pen!", "ମୋତେ କଲମ ଦିଅ!", "mote kalama dia!"],
    ["Stop here!", "ଏଠାରେ ଅଟକ!", "ethare ataka!"],
    ["Let us go together!", "ଆସ ଏକାଠି ଯିବା!", "asa ekathi jiba!"],
],

# ━━━ 518: Negative sentences ━━━
518: [
    ["I don't eat meat", "ମୁଁ ମାଂସ ଖାଏ ନାହିଁ", "mun mansa khae nahin"],
    ["He doesn't go to school", "ସେ ସ୍କୁଲ ଯାଏ ନାହିଁ", "se skula jae nahin"],
    ["She doesn't read", "ସେ ପଢ଼େ ନାହିଁ", "se padhe nahin"],
    ["We don't play today", "ଆମେ ଆଜି ଖେଳୁ ନାହିଁ", "ame aji khelu nahin"],
    ["They didn't come", "ସେମାନେ ଆସିଲେ ନାହିଁ", "semane asile nahin"],
    ["I don't know", "ମୁଁ ଜାଣେ ନାହିଁ", "mun jane nahin"],
    ["He didn't eat food", "ସେ ଖାଦ୍ୟ ଖାଇଲା ନାହିଁ", "se khadya khaila nahin"],
    ["She will not go", "ସେ ଯିବ ନାହିଁ", "se jiba nahin"],
    ["I don't understand", "ମୁଁ ବୁଝୁ ନାହିଁ", "mun buju nahin"],
    ["He is not at home", "ସେ ଘରେ ନାହିଁ", "se ghare nahin"],
    ["Don't tell anyone", "କାହାକୁ କୁହ ନାହିଁ", "kahaku kuha nahin"],
    ["This is not correct", "ଏହା ଠିକ୍ ନୁହେଁ", "eha thik nuhen"],
    ["I didn't sleep well", "ମୁଁ ଭଲରେ ଶୋଇଲି ନାହିଁ", "mun bhalore soili nahin"],
    ["She is not a doctor", "ସେ ଡାକ୍ତର ନୁହଁନ୍ତି", "se daktara nuhanti"],
    ["We will not forget", "ଆମେ ଭୁଲିବୁ ନାହିଁ", "ame bhulibu nahin"],
    ["He never lies", "ସେ କେବେ ମିଛ କହେ ନାହିଁ", "se kebe michha kahe nahin"],
    ["I have no money", "ମୋ ପାଖରେ ଟଙ୍କା ନାହିଁ", "mo pakhare tanka nahin"],
    ["There is no water", "ପାଣି ନାହିଁ", "pani nahin"],
],

# ━━━ 519: Question formation ━━━
519: [
    ["What is your name?", "ତୁମ ନାମ କ'ଣ?", "tuma nama kana?"],
    ["Where are you going?", "ତୁ କେଉଁଠି ଯାଉଛ?", "tu keunthi jauchha?"],
    ["When did he come?", "ସେ କେବେ ଆସିଲା?", "se kebe asila?"],
    ["Why are you late?", "ତୁ ଡେରି କାହିଁକି?", "tu deri kahinki?"],
    ["How are you?", "ତୁମେ କେମିତି ଅଛ?", "tume kemiti achha?"],
    ["Who is he?", "ସେ କିଏ?", "se kie?"],
    ["How much does this cost?", "ଏହାର ଦାମ କେତେ?", "ehara dama kete?"],
    ["Which book do you want?", "ତୁ କେଉଁ ବହି ଚାହୁଁଛ?", "tu keun bahi chahunchha?"],
    ["Is he a teacher?", "ସେ ଶିକ୍ଷକ କି?", "se shikshaka ki?"],
    ["Do you understand Odia?", "ତୁ ଓଡ଼ିଆ ବୁଝୁଛ କି?", "tu odia bujuchha ki?"],
    ["Where is the hospital?", "ଡାକ୍ତରଖାନା କେଉଁଠି?", "daktarakhana keunthi?"],
    ["How many children are there?", "କେତେ ପିଲା ଅଛନ୍ତି?", "kete pila achhanti?"],
    ["Whose pen is this?", "ଏହା କାହାର କଲମ?", "eha kahara kalama?"],
    ["Can you speak English?", "ତୁ ଇଂରାଜୀ କହିପାରୁଛ କି?", "tu ingraji kahiparuchha ki?"],
    ["What time is it?", "ବର୍ତ୍ତମାନ କେତେ ବେଳ?", "bartamana kete bela?"],
    ["Where do you live?", "ତୁ କେଉଁଠି ରହୁଛ?", "tu keunthi rahuchha?"],
    ["Did you eat food?", "ତୁ ଖାଇଲୁ କି?", "tu khailu ki?"],
    ["Will you come tomorrow?", "ତୁ କାଲି ଆସିବୁ କି?", "tu kali asibu ki?"],
],

# ━━━ 520: Postpositions (re, ru, ku, etc.) ━━━
520: [
    ["In the house (re)", "ଘରେ", "ghare"],
    ["From the village (ru)", "ଗାଁରୁ", "ganru"],
    ["To the market (ku)", "ବଜାରକୁ", "bajaraku"],
    ["On the table (upare)", "ଟେବୁଲ ଉପରେ", "tebula upare"],
    ["Under the tree (talare)", "ଗଛ ତଳରେ", "gachha talare"],
    ["Near the river (pakhare)", "ନଦୀ ପାଖରେ", "nadi pakhare"],
    ["With my friend (saha)", "ମୋ ସାଙ୍ଗ ସହ", "mo sanga saha"],
    ["Without water (bina)", "ପାଣି ବିନା", "pani bina"],
    ["In front of the school (agare)", "ସ୍କୁଲ ଆଗରେ", "skula agare"],
    ["Behind the house (pachhare)", "ଘର ପଛରେ", "ghara pachhare"],
    ["I am going to school", "ମୁଁ ସ୍କୁଲକୁ ଯାଉଛି", "mun skulaku jauchhi"],
    ["He came from Delhi", "ସେ ଦିଲ୍ଲୀରୁ ଆସିଲା", "se Dilliru asila"],
    ["The book is on the shelf", "ବହିଟି ତାକରେ ଅଛି", "bahiti takare achhi"],
    ["Sit beside me", "ମୋ ପାଖରେ ବସ", "mo pakhare basa"],
    ["The cat is inside the room", "ବିଲେଇ ରୁମ୍ ଭିତରେ ଅଛି", "bilei rum bhitare achhi"],
    ["He is standing outside", "ସେ ବାହାରେ ଠିଆ ହୋଇଛି", "se bahare thia hoichhi"],
    ["The temple is across the river", "ମନ୍ଦିର ନଦୀ ପାରିରେ ଅଛି", "mandira nadi parire achhi"],
    ["I went for his sake", "ମୁଁ ତା ପାଇଁ ଗଲି", "mun ta pain gali"],
],

# ━━━ 521: Adjectives ━━━
521: [
    ["Big house", "ବଡ଼ ଘର", "bada ghara"],
    ["Small child", "ସାନ ପିଲା", "sana pila"],
    ["Good boy", "ଭଲ ପୁଅ", "bhala pua"],
    ["Bad habit", "ଖରାପ ଅଭ୍ୟାସ", "kharapa abhyasa"],
    ["Beautiful flower", "ସୁନ୍ଦର ଫୁଲ", "sundara phula"],
    ["Old man", "ବୁଢ଼ା ଲୋକ", "budha loka"],
    ["New clothes", "ନୂଆ ଲୁଗା", "nua luga"],
    ["Hot water", "ଗରମ ପାଣି", "garama pani"],
    ["Cold milk", "ଥଣ୍ଡା କ୍ଷୀର", "thanda kshira"],
    ["Sweet mango", "ମିଠା ଆମ୍ବ", "mitha amba"],
    ["The tall tree is green", "ଲମ୍ବା ଗଛଟି ସବୁଜ", "lamba gachhati sabuja"],
    ["She has long hair", "ତାର ଲମ୍ବା ଚୁଟି ଅଛି", "tara lamba chuti achhi"],
    ["This road is wide", "ଏ ରାସ୍ତା ଚଉଡ଼ା", "e rasta chauda"],
    ["That river is deep", "ସେ ନଦୀ ଗଭୀର", "se nadi gabhira"],
    ["He is a brave soldier", "ସେ ଜଣେ ସାହସୀ ସୈନିକ", "se jane sahasi sainika"],
    ["The red flower is beautiful", "ଲାଲ ଫୁଲଟି ସୁନ୍ଦର", "lala phulati sundara"],
    ["I want fresh vegetables", "ମୁଁ ତାଜା ପରିବା ଚାହେଁ", "mun taja pariba chahen"],
    ["This is an easy question", "ଏହା ଏକ ସହଜ ପ୍ରଶ୍ନ", "eha eka sahaja prashna"],
],

# ━━━ 522: Comparatives and Superlatives ━━━
522: [
    ["He is taller than me", "ସେ ମୋଠାରୁ ଲମ୍ବା", "se motharu lamba"],
    ["She is smarter than him", "ସେ ତା'ଠାରୁ ଚତୁର", "se ta'tharu chatura"],
    ["This book is better", "ଏ ବହି ଅଧିକ ଭଲ", "e bahi adhika bhala"],
    ["Mango is sweeter than guava", "ଆମ୍ବ ପେଅରାଠାରୁ ମିଠା", "amba pearatharu mitha"],
    ["The elephant is bigger than the horse", "ହାତୀ ଘୋଡ଼ାଠାରୁ ବଡ଼", "hati ghodatharu bada"],
    ["Today is hotter than yesterday", "ଆଜି ଗତକାଲିଠାରୁ ଅଧିକ ଗରମ", "aji gatakalitharu adhika garama"],
    ["He runs faster than you", "ସେ ତୁମଠାରୁ ଜୋରରେ ଦୌଡ଼େ", "se tumatharu jorare daude"],
    ["This is the tallest building", "ଏହା ସବୁଠାରୁ ଲମ୍ବା ଅଟ୍ଟାଳିକା", "eha sabutharu lamba attalika"],
    ["She is the best student", "ସେ ସବୁଠାରୁ ଭଲ ଛାତ୍ରୀ", "se sabutharu bhala chhatri"],
    ["This is the oldest temple", "ଏହା ସବୁଠାରୁ ପୁରୁଣା ମନ୍ଦିର", "eha sabutharu puruna mandira"],
    ["Iron is harder than wood", "ଲୁହା କାଠଠାରୁ ଶକ୍ତ", "luha kathatharu shakta"],
    ["The Ganges is the longest river", "ଗଙ୍ଗା ସବୁଠାରୁ ଲମ୍ବା ନଦୀ", "Ganga sabutharu lamba nadi"],
    ["He is less patient", "ସେ କମ୍ ଧୈର୍ଯ୍ୟଶୀଳ", "se kama dhairyashila"],
    ["This pen is cheaper", "ଏ କଲମ ଅଧିକ ସସ୍ତା", "e kalama adhika sasta"],
    ["She sings the most beautifully", "ସେ ସବୁଠାରୁ ସୁନ୍ଦର ଗାଏ", "se sabutharu sundara gae"],
    ["My house is farther", "ମୋ ଘର ଅଧିକ ଦୂର", "mo ghara adhika dura"],
    ["He is the youngest child", "ସେ ସବୁଠାରୁ ସାନ ପିଲା", "se sabutharu sana pila"],
    ["This road is the widest", "ଏ ରାସ୍ତା ସବୁଠାରୁ ଚଉଡ଼ା", "e rasta sabutharu chauda"],
],

# ━━━ 523: Adverbs ━━━
523: [
    ["He walks slowly", "ସେ ଧୀରେ ଚାଲେ", "se dhire chale"],
    ["She speaks softly", "ସେ ଧୀରେ କହେ", "se dhire kahe"],
    ["He runs quickly", "ସେ ଜୋରରେ ଦୌଡ଼େ", "se jorare daude"],
    ["I will come soon", "ମୁଁ ଶୀଘ୍ର ଆସିବି", "mun shighra asibi"],
    ["She always helps others", "ସେ ସବୁବେଳେ ଅନ୍ୟକୁ ସାହାଯ୍ୟ କରେ", "se sabubelе anyaku sahayya kare"],
    ["He never tells lies", "ସେ କେବେ ମିଛ କହେ ନାହିଁ", "se kebe michha kahe nahin"],
    ["She sings very well", "ସେ ବହୁତ ଭଲ ଗାଏ", "se bahuta bhala gae"],
    ["I go there daily", "ମୁଁ ସେଠି ପ୍ରତିଦିନ ଯାଏ", "mun sethi pratidina jae"],
    ["He came here yesterday", "ସେ ଗତକାଲି ଏଠି ଆସିଲା", "se gatakali ethi asila"],
    ["She suddenly started crying", "ସେ ହଠାତ୍ କାନ୍ଦିବା ଆରମ୍ଭ କଲା", "se hathat kandiba arambha kala"],
    ["He still lives here", "ସେ ଏବେ ବି ଏଠି ରହେ", "se ebe bi ethi rahe"],
    ["We often go to the temple", "ଆମେ ପ୍ରାୟ ମନ୍ଦିରକୁ ଯାଉ", "ame praya mandiraku jau"],
    ["He works very hard", "ସେ ବହୁତ କଠିନ ପରିଶ୍ରମ କରେ", "se bahuta kathina parishrama kare"],
    ["She immediately agreed", "ସେ ସଙ୍ଗେ ସଙ୍ଗେ ରାଜି ହେଲା", "se sange sange raji hela"],
    ["I just came now", "ମୁଁ ବର୍ତ୍ତମାନ ଆସିଲି", "mun bartamana asili"],
    ["He almost fell down", "ସେ ପ୍ରାୟ ପଡ଼ିଯାଇଥିଲା", "se praya padijaithi la"],
    ["She certainly knows this", "ସେ ନିଶ୍ଚୟ ଏହା ଜାଣେ", "se nishchaya eha jane"],
    ["They together did the work", "ସେମାନେ ଏକାଠି କାମ କଲେ", "semane ekathi kama kale"],
],

# ━━━ 524: Conjunctions ━━━
524: [
    ["He and I went", "ସେ ଓ ମୁଁ ଗଲୁ", "se o mun galu"],
    ["Tea or coffee?", "ଚା କି କଫି?", "cha ki kaphi?"],
    ["He came but she didn't", "ସେ ଆସିଲା କିନ୍ତୁ ସେ ଆସିଲା ନାହିଁ", "se asila kintu se asila nahin"],
    ["I am tired so I will rest", "ମୁଁ ଥକିଛି ତେଣୁ ବିଶ୍ରାମ ନେବି", "mun thakichhi tenu bishrama nebi"],
    ["Study hard otherwise you will fail", "କଠିନ ପଢ଼ ନଚେତ୍ ଫେଲ ହେବୁ", "kathina padha nachet phela hebu"],
    ["He is poor but honest", "ସେ ଗରୀବ କିନ୍ତୁ ସଚ୍ଚୋଟ", "se gariba kintu sachchota"],
    ["Both Ram and Sita came", "ରାମ ଓ ସୀତା ଦୁହେଁ ଆସିଲେ", "Rama o Sita duhen asile"],
    ["I will go if you come", "ତୁ ଆସିଲେ ମୁଁ ଯିବି", "tu asile mun jibi"],
    ["He is smart as well as kind", "ସେ ଚତୁର ଏବଂ ଦୟାଳୁ", "se chatura ebam dayalu"],
    ["Either he or she will go", "ସେ କିମ୍ବା ସେ ଯିବ", "se kimba se jiba"],
    ["He studied so he passed", "ସେ ପଢ଼ିଲା ତେଣୁ ସେ ପାସ କଲା", "se padhila tenu se pasa kala"],
    ["Wait until I come", "ମୁଁ ଆସିବା ପର୍ଯ୍ୟନ୍ତ ଅପେକ୍ଷା କର", "mun asiba paryanta apeksha kara"],
    ["I went although it rained", "ବର୍ଷା ହେଲା ସତ୍ତ୍ୱେ ମୁଁ ଗଲି", "barsha hela sattwe mun gali"],
    ["He works so that he can earn", "ସେ ଉପାର୍ଜନ ପାଇଁ କାମ କରେ", "se uparjana pain kama kare"],
    ["Unless you try, you won't succeed", "ଚେଷ୍ଟା ନ କଲେ ସଫଳ ହେବୁ ନାହିଁ", "cheshta na kale saphala hebu nahin"],
    ["While eating, don't talk", "ଖାଉଥିବା ବେଳେ କଥା କହ ନାହିଁ", "khauthi ba bele katha kaha nahin"],
    ["He is neither tall nor short", "ସେ ଲମ୍ବା ନୁହେଁ ଖାଟୋ ବି ନୁହେଁ", "se lamba nuhen khato bi nuhen"],
    ["As soon as he came, I left", "ସେ ଆସିବା ମାତ୍ରେ ମୁଁ ଚାଲିଗଲି", "se asiba matre mun chaligali"],
],

# ━━━ 525: Relative clauses ━━━
525: [
    ["The boy who came is my friend", "ଯେଉଁ ପୁଅ ଆସିଲା ସେ ମୋ ସାଙ୍ଗ", "jeun pua asila se mo sanga"],
    ["The book that I read is good", "ଯେଉଁ ବହି ମୁଁ ପଢ଼ିଲି ତାହା ଭଲ", "jeun bahi mun padhili taha bhala"],
    ["The girl who sings is my sister", "ଯେଉଁ ଝିଅ ଗାଏ ସେ ମୋ ଭଉଣୀ", "jeun jhia gae se mo bhauni"],
    ["The place where I was born", "ଯେଉଁ ସ୍ଥାନରେ ମୁଁ ଜନ୍ମ ହୋଇଥିଲି", "jeun sthanare mun janma hoithili"],
    ["The teacher who teaches us is kind", "ଯେଉଁ ଶିକ୍ଷକ ଆମକୁ ପଢ଼ାନ୍ତି ସେ ଦୟାଳୁ", "jeun shikshaka amaku padhanti se dayalu"],
    ["The man whom I met is a doctor", "ଯାହାକୁ ମୁଁ ଭେଟିଲି ସେ ଡାକ୍ତର", "jahaku mun bhetili se daktara"],
    ["The house which is red is mine", "ଯେଉଁ ଘର ଲାଲ ସେ ମୋର", "jeun ghara lala se mora"],
    ["Whoever works hard will succeed", "ଯିଏ ପରିଶ୍ରମ କରେ ସେ ସଫଳ ହେବ", "jie parishrama kare se saphala heba"],
    ["Whatever you say is true", "ତୁମେ ଯାହା କହ ସେ ସତ", "tume jaha kaha se sata"],
    ["The day when he came was Monday", "ଯେଉଁ ଦିନ ସେ ଆସିଲା ସେ ସୋମବାର", "jeun dina se asila se somabara"],
    ["I know the reason why he left", "ସେ କାହିଁକି ଗଲା ମୁଁ ଜାଣେ", "se kahinki gala mun jane"],
    ["The way in which he spoke was good", "ଯେଉଁ ଢଙ୍ଗରେ ସେ କହିଲା ଭଲ ଥିଲା", "jeun dhangare se kahila bhala thila"],
    ["Those who study will pass", "ଯେଉଁମାନେ ପଢ଼ନ୍ତି ସେମାନେ ପାସ ହେବେ", "jeunmane padhanti semane pasa hebe"],
    ["The food that she cooks is tasty", "ଯେଉଁ ଖାଦ୍ୟ ସେ ରାନ୍ଧେ ତାହା ସ୍ୱାଦିଷ୍ଟ", "jeun khadya se randhe taha swadishta"],
    ["The pen which I lost was expensive", "ଯେଉଁ କଲମ ମୁଁ ହରାଇଲି ସେ ମହଙ୍ଗା ଥିଲା", "jeun kalama mun haraili se mahanga thila"],
    ["The village where I grew up is small", "ଯେଉଁ ଗାଁରେ ମୁଁ ବଢ଼ିଲି ସେ ଛୋଟ", "jeun ganre mun badhili se chhota"],
    ["He who is honest is respected", "ଯିଏ ସଚ୍ଚୋଟ ତାକୁ ସମ୍ମାନ ମିଳେ", "jie sachchota taku sammana mile"],
    ["The time when we met was special", "ଯେଉଁ ସମୟରେ ଆମେ ଭେଟିଲୁ ସେ ବିଶେଷ ଥିଲା", "jeun samayare ame bhetilu se bishesha thila"],
],

# ━━━ 526: Conditional sentences ━━━
526: [
    ["If it rains, I will stay home", "ଯଦି ବର୍ଷା ହୁଏ, ମୁଁ ଘରେ ରହିବି", "jadi barsha hue, mun ghare rahibi"],
    ["If you study, you will pass", "ଯଦି ପଢ଼ିବ, ପାସ ହେବୁ", "jadi padhiba, pasa hebu"],
    ["If he comes, tell me", "ଯଦି ସେ ଆସେ, ମୋତେ କୁହ", "jadi se ase, mote kuha"],
    ["If I had money, I would buy it", "ଯଦି ମୋ ପାଖରେ ଟଙ୍କା ଥାନ୍ତା, ମୁଁ କିଣିଥାନ୍ତି", "jadi mo pakhare tanka thanta, mun kinithanti"],
    ["If she had studied, she would have passed", "ଯଦି ସେ ପଢ଼ିଥାନ୍ତା, ପାସ ହୋଇଥାନ୍ତା", "jadi se padhithanta, pasa hoithanta"],
    ["If you help me, I will be grateful", "ଯଦି ତୁ ସାହାଯ୍ୟ କରିବ, ମୁଁ କୃତଜ୍ଞ ହେବି", "jadi tu sahayya kariba, mun krutajna hebi"],
    ["If we go early, we can get seats", "ଯଦି ଆମେ ଲଗେ ଯିବୁ, ସିଟ୍ ପାଇବୁ", "jadi ame lage jibu, sit paibu"],
    ["If they invite me, I will go", "ଯଦି ସେମାନେ ନିମନ୍ତ୍ରଣ କରନ୍ତି, ମୁଁ ଯିବି", "jadi semane nimantrana karanti, mun jibi"],
    ["If the weather is good, we will play", "ଯଦି ପାଗ ଭଲ ହୁଏ, ଆମେ ଖେଳିବୁ", "jadi paga bhala hue, ame khelibu"],
    ["If you don't hurry, you will miss the bus", "ଯଦି ଶୀଘ୍ର ନ କର, ବସ୍ ଛୁଟିଯିବ", "jadi shighra na kara, bas chhutijiba"],
    ["Had I known, I would have come", "ଯଦି ଜାଣିଥାନ୍ତି, ଆସିଥାନ୍ତି", "jadi janithanti, asithanti"],
    ["If he works hard, he will succeed", "ଯଦି ସେ ପରିଶ୍ରମ କରେ, ସଫଳ ହେବ", "jadi se parishrama kare, saphala heba"],
    ["If you eat too much, you will fall sick", "ଯଦି ଅଧିକ ଖାଇବ, ଅସୁସ୍ଥ ହେବୁ", "jadi adhika khaiba, asustha hebu"],
    ["If I were a bird, I would fly", "ଯଦି ମୁଁ ପକ୍ଷୀ ହୋଇଥାନ୍ତି, ଉଡ଼ିଥାନ୍ତି", "jadi mun pakshi hoithanti, udithanti"],
    ["If she calls, answer the phone", "ଯଦି ସେ ଫୋନ୍ କରେ, ଉତ୍ତର ଦିଅ", "jadi se phon kare, uttara dia"],
    ["If we save money, we can travel", "ଯଦି ଟଙ୍କା ବଞ୍ଚାଇବୁ, ବୁଲିପାରିବୁ", "jadi tanka banchaibu, buliparibu"],
    ["If it had not rained, we would have gone", "ଯଦି ବର୍ଷା ନ ହୋଇଥାନ୍ତା, ଯାଇଥାନ୍ତୁ", "jadi barsha na hoithanta, jaithanta"],
    ["If you want, you can stay", "ଯଦି ଚାହୁଁଛ, ରହିପାରିବ", "jadi chahunchha, rahipariba"],
],

# ━━━ 527: Passive voice ━━━
527: [
    ["The book was read by me", "ବହିଟି ମୋ ଦ୍ୱାରା ପଢ଼ାଗଲା", "bahiti mo dwara padhagala"],
    ["Food is cooked by mother", "ଖାଦ୍ୟ ମାଆ ଦ୍ୱାରା ରନ୍ଧାଯାଏ", "khadya maa dwara randhajae"],
    ["The letter was written by him", "ଚିଠିଟି ତା ଦ୍ୱାରା ଲେଖାଗଲା", "chithiti ta dwara lekhagala"],
    ["The song is sung by her", "ଗୀତଟି ସେ ଦ୍ୱାରା ଗାଆଯାଏ", "gitati se dwara gaajae"],
    ["Rice is eaten", "ଭାତ ଖିଆଯାଏ", "bhata khiajae"],
    ["The door was opened", "କବାଟ ଖୋଲାଗଲା", "kabata kholagala"],
    ["The work will be done", "କାମ କରାଯିବ", "kama karajiba"],
    ["He was called by the teacher", "ସେ ଶିକ୍ଷକଙ୍କ ଦ୍ୱାରା ଡକାଗଲା", "se shikshakanka dwara dakagala"],
    ["The thief was caught by police", "ଚୋରଟି ପୋଲିସ ଦ୍ୱାରା ଧରାଗଲା", "chorati polisa dwara dharagala"],
    ["Odia is spoken in Odisha", "ଓଡ଼ିଶାରେ ଓଡ଼ିଆ କୁହାଯାଏ", "odishare odia kuhajae"],
    ["The game was won by our team", "ଖେଳ ଆମ ଦଳ ଦ୍ୱାରା ଜିତାଗଲା", "khela ama dala dwara jitagala"],
    ["Mangoes are sold in summer", "ଗ୍ରୀଷ୍ମରେ ଆମ୍ବ ବିକାଯାଏ", "grishmre amba bikajae"],
    ["The homework was completed", "ଗୃହକାର୍ଯ୍ୟ ସମ୍ପନ୍ନ ହେଲା", "gruhakaryya sampanna hela"],
    ["Trees are planted in monsoon", "ବର୍ଷାରେ ଗଛ ଲଗାଯାଏ", "barshare gachha lagajae"],
    ["The bridge was built last year", "ସେତୁ ଗତ ବର୍ଷ ତିଆରି ହୋଇଥିଲା", "setu gata barsha tiari hoithila"],
    ["Children are taught by teachers", "ପିଲାମାନଙ୍କୁ ଶିକ୍ଷକ ପଢ଼ାନ୍ତି", "pilamanunku shikshaka padhanti"],
    ["The news was heard by everyone", "ଖବର ସମସ୍ତଙ୍କ ଦ୍ୱାରା ଶୁଣାଗଲା", "khabara samastanka dwara shunagala"],
    ["This poem was composed by Sarala Das", "ଏ କବିତା ସାରଳା ଦାସ ଦ୍ୱାରା ରଚିତ", "e kabita Sarala Dasa dwara rachita"],
],

# ━━━ 528: Causative verbs ━━━
528: [
    ["I eat → I make him eat", "ମୁଁ ଖାଏ → ମୁଁ ତାକୁ ଖୁଆଏ", "mun khae → mun taku khuae"],
    ["He reads → I make him read", "ସେ ପଢ଼େ → ମୁଁ ତାକୁ ପଢ଼ାଏ", "se padhe → mun taku padhae"],
    ["She sleeps → I make her sleep", "ସେ ଶୋଏ → ମୁଁ ତାକୁ ଶୋଇଆଏ", "se shoe → mun taku shoiae"],
    ["He writes → I make him write", "ସେ ଲେଖେ → ମୁଁ ତାକୁ ଲେଖାଏ", "se lekhe → mun taku lekhae"],
    ["Mother feeds the child", "ମାଆ ପିଲାକୁ ଖୁଆଏ", "maa pilaku khuae"],
    ["The teacher makes students read", "ଶିକ୍ଷକ ଛାତ୍ରମାନଙ୍କୁ ପଢ଼ାନ୍ତି", "shikshaka chhatramanunku padhanti"],
    ["I got the house built", "ମୁଁ ଘର ତିଆରି କରାଇଲି", "mun ghara tiari karaili"],
    ["She got the clothes washed", "ସେ ଲୁଗା ଧୋଇଆଇଲା", "se luga dhoiaila"],
    ["He got the letter written", "ସେ ଚିଠି ଲେଖାଇଲା", "se chithi lekhaila"],
    ["Father made the son study", "ବାପା ପୁଅକୁ ପଢ଼ାଇଲେ", "bapa puaku padhaile"],
    ["I will get the work done", "ମୁଁ କାମ କରାଇବି", "mun kama karaibi"],
    ["She made the children sit", "ସେ ପିଲାମାନଙ୍କୁ ବସାଇଲା", "se pilamanunku basaila"],
    ["He made me laugh", "ସେ ମୋତେ ହସାଇଲା", "se mote hasaila"],
    ["Mother put the baby to sleep", "ମାଆ ଶିଶୁକୁ ଶୋଇଆଇଲା", "maa shishuku shoiaila"],
    ["I got the car washed", "ମୁଁ ଗାଡ଼ି ଧୋଇଆଇଲି", "mun gadi dhoiaili"],
    ["The doctor made him drink medicine", "ଡାକ୍ତର ତାକୁ ଔଷଧ ପିଆଇଲେ", "daktara taku aushadha piaile"],
    ["He got the field ploughed", "ସେ ଜମି ଚଷାଇଲା", "se jami chashaila"],
    ["She made them understand", "ସେ ସେମାନଙ୍କୁ ବୁଝାଇଲା", "se semanunku bujaila"],
],

# ━━━ 529: Compound verbs ━━━
529: [
    ["He fell down", "ସେ ପଡ଼ିଗଲା", "se padigala"],
    ["She woke up", "ସେ ଉଠିଗଲା", "se uthigala"],
    ["I ran away", "ମୁଁ ପଳାଇଗଲି", "mun palaigali"],
    ["He sat down", "ସେ ବସିପଡ଼ିଲା", "se basipadi la"],
    ["The food got burnt", "ଖାଦ୍ୟ ଜଳିଗଲା", "khadya jaligala"],
    ["He broke down and cried", "ସେ ଭାଙ୍ଗିପଡ଼ିଲା ଓ କାନ୍ଦିଲା", "se bhangipadi la o kandila"],
    ["She went away", "ସେ ଚାଲିଗଲା", "se chaligala"],
    ["The flower bloomed", "ଫୁଲ ଫୁଟିଗଲା", "phula phutigala"],
    ["He finished eating", "ସେ ଖାଇସାରିଲା", "se khaisarila"],
    ["She kept on reading", "ସେ ପଢ଼ିଚାଲିଲା", "se padhichalila"],
    ["He began to speak", "ସେ କହିବା ଆରମ୍ଭ କଲା", "se kahiba arambha kala"],
    ["The glass broke into pieces", "ଗ୍ଲାସ ଭାଙ୍ଗିଗଲା", "glasa bhangigala"],
    ["I wrote it down", "ମୁଁ ଲେଖିରଖିଲି", "mun lekhirakhili"],
    ["She put on her shoes", "ସେ ଜୋତା ପିନ୍ଧିନେଲା", "se jota pindhinela"],
    ["He picked it up", "ସେ ଉଠାଇନେଲା", "se uthainela"],
    ["The river dried up", "ନଦୀ ଶୁଖିଗଲା", "nadi shukhigala"],
    ["He threw it away", "ସେ ଫୋପାଡ଼ିଦେଲା", "se phopadidela"],
    ["She came running", "ସେ ଦୌଡ଼ି ଆସିଲା", "se daudi asila"],
],

# ━━━ 530: Honorific forms ━━━
530: [
    ["You (informal)", "ତୁ", "tu"],
    ["You (semi-formal)", "ତୁମେ", "tume"],
    ["You (formal/respectful)", "ଆପଣ", "apana"],
    ["Please come (formal)", "ଦୟାକରି ଆସନ୍ତୁ", "dayakari asantu"],
    ["Please sit (formal)", "ଦୟାକରି ବସନ୍ତୁ", "dayakari basantu"],
    ["He goes (informal)", "ସେ ଯାଏ", "se jae"],
    ["He goes (respectful)", "ସେ ଯାଆନ୍ତି", "se jaanti"],
    ["What do you want? (informal)", "ତୁ କ'ଣ ଚାହୁଁଛ?", "tu kana chahunchha?"],
    ["What do you want? (formal)", "ଆପଣ କ'ଣ ଚାହାନ୍ତି?", "apana kana chahanti?"],
    ["Teacher came (respectful)", "ଶିକ୍ଷକ ଆସିଲେ", "shikshaka asile"],
    ["Father said (respectful)", "ବାପା କହିଲେ", "bapa kahile"],
    ["Mother cooked (respectful)", "ମାଆ ରାନ୍ଧିଲେ", "maa randhile"],
    ["Grandfather told a story", "ଅଜା ଗୋଟିଏ କାହାଣୀ କହିଲେ", "aja gotie kahani kahile"],
    ["Please speak slowly", "ଦୟାକରି ଧୀରେ କୁହନ୍ତୁ", "dayakari dhire kuhantu"],
    ["Respected sir/madam", "ମାନ୍ୟବର / ମାନ୍ୟବରୀ", "manyabara / manyabari"],
    ["Please tell me (formal)", "ଦୟାକରି ମୋତେ କୁହନ୍ତୁ", "dayakari mote kuhantu"],
    ["He is eating (respectful)", "ସେ ଖାଉଛନ୍ତି", "se khauchhanti"],
    ["Thank you very much (formal)", "ଆପଣଙ୍କୁ ବହୁତ ଧନ୍ୟବାଦ", "apanunku bahuta dhanyabada"],
],

# ━━━ 531: Tense markers ━━━
531: [
    ["Present: I go", "ମୁଁ ଯାଏ", "mun jae"],
    ["Present continuous: I am going", "ମୁଁ ଯାଉଛି", "mun jauchhi"],
    ["Past: I went", "ମୁଁ ଗଲି", "mun gali"],
    ["Past continuous: I was going", "ମୁଁ ଯାଉଥିଲି", "mun jauthili"],
    ["Future: I will go", "ମୁଁ ଯିବି", "mun jibi"],
    ["Present perfect: I have gone", "ମୁଁ ଯାଇଛି", "mun jaichhi"],
    ["Past perfect: I had gone", "ମୁଁ ଯାଇଥିଲି", "mun jaithili"],
    ["He eats (habitual present)", "ସେ ଖାଏ", "se khae"],
    ["He is eating (present continuous)", "ସେ ଖାଉଛି", "se khauchhi"],
    ["He ate (simple past)", "ସେ ଖାଇଲା", "se khaila"],
    ["He was eating (past continuous)", "ସେ ଖାଉଥିଲା", "se khauthila"],
    ["He will eat (simple future)", "ସେ ଖାଇବ", "se khaiba"],
    ["He has eaten (present perfect)", "ସେ ଖାଇସାରିଛି", "se khaisarichhi"],
    ["He had eaten (past perfect)", "ସେ ଖାଇସାରିଥିଲା", "se khaisarithila"],
    ["I was reading when he came", "ସେ ଆସିବାବେଳେ ମୁଁ ପଢ଼ୁଥିଲି", "se asibabele mun padhuthili"],
    ["She has been singing since morning", "ସେ ସକାଳୁ ଗାଉଛି", "se sakalu gauchhi"],
    ["They will have finished by then", "ସେମାନେ ସେତେବେଳକୁ ସାରିଥିବେ", "semane setebel aku sarithibe"],
    ["I had already left before he arrived", "ସେ ପହଞ୍ଚିବା ଆଗରୁ ମୁଁ ଯାଇଥିଲି", "se pahanchiba agaru mun jaithili"],
],

# ━━━ 532: Modal verbs ━━━
532: [
    ["I can speak Odia", "ମୁଁ ଓଡ଼ିଆ କହି ପାରେ", "mun odia kahi pare"],
    ["He can swim", "ସେ ପହଁରି ପାରେ", "se pahanri pare"],
    ["She must go now", "ସେ ବର୍ତ୍ତମାନ ଯିବା ଉଚିତ", "se bartamana jiba uchita"],
    ["You should study daily", "ତୁ ପ୍ରତିଦିନ ପଢ଼ିବା ଉଚିତ", "tu pratidina padhiba uchita"],
    ["May I come in?", "ମୁଁ ଭିତରକୁ ଆସିପାରିବି କି?", "mun bhitaraku asipaaribi ki?"],
    ["He may come tomorrow", "ସେ କାଲି ଆସିପାରେ", "se kali asipare"],
    ["I want to eat", "ମୁଁ ଖାଇବାକୁ ଚାହେଁ", "mun khaibaku chahen"],
    ["She has to go to school", "ସେ ସ୍କୁଲ ଯିବାକୁ ହେବ", "se skula jibaku heba"],
    ["You need not worry", "ତୁ ଚିନ୍ତା କରିବା ଦରକାର ନାହିଁ", "tu chinta kariba darakara nahin"],
    ["I could not come yesterday", "ମୁଁ ଗତକାଲି ଆସିପାରିଲି ନାହିଁ", "mun gatakali asiparili nahin"],
    ["He might have left", "ସେ ଯାଇଥାଇପାରେ", "se jaithaipare"],
    ["We must respect elders", "ଆମେ ବୟସ୍କମାନଙ୍କୁ ସମ୍ମାନ କରିବା ଉଚିତ", "ame bayaskamanunku sammana kariba uchita"],
    ["Can you help me?", "ତୁ ମୋତେ ସାହାଯ୍ୟ କରିପାରିବ କି?", "tu mote sahayya karipariba ki?"],
    ["She ought to apologize", "ସେ କ୍ଷମା ମାଗିବା ଉଚିତ", "se kshama magiba uchita"],
    ["I am able to understand", "ମୁଁ ବୁଝି ପାରୁଛି", "mun buji paruchhi"],
    ["He used to play here", "ସେ ଏଠି ଖେଳୁଥିଲା", "se ethi kheluthila"],
    ["You may take a seat", "ଆପଣ ବସି ପାରନ୍ତି", "apana basi paranti"],
    ["We should help the poor", "ଆମେ ଗରୀବମାନଙ୍କୁ ସାହାଯ୍ୟ କରିବା ଉଚିତ", "ame garibamanunku sahayya kariba uchita"],
],

# ━━━ 533: Reported speech ━━━
533: [
    ["He said, 'I am going'", "ସେ କହିଲା, 'ମୁଁ ଯାଉଛି'", "se kahila, 'mun jauchhi'"],
    ["He said that he was going", "ସେ କହିଲା ଯେ ସେ ଯାଉଛି", "se kahila je se jauchhi"],
    ["She said, 'I will come'", "ସେ କହିଲା, 'ମୁଁ ଆସିବି'", "se kahila, 'mun asibi'"],
    ["She told me that she would come", "ସେ ମୋତେ କହିଲା ଯେ ସେ ଆସିବ", "se mote kahila je se asiba"],
    ["He asked, 'Where are you going?'", "ସେ ପଚାରିଲା, 'ତୁ କେଉଁଠି ଯାଉଛ?'", "se pacharila, 'tu keunthi jauchha?'"],
    ["He asked me where I was going", "ସେ ମୋତେ ପଚାରିଲା ମୁଁ କେଉଁଠି ଯାଉଛି", "se mote pacharila mun keunthi jauchhi"],
    ["Teacher said, 'Study well'", "ଶିକ୍ଷକ କହିଲେ, 'ଭଲ ପଢ଼'", "shikshaka kahile, 'bhala padha'"],
    ["Teacher told us to study well", "ଶିକ୍ଷକ ଆମକୁ ଭଲ ପଢ଼ିବାକୁ କହିଲେ", "shikshaka amaku bhala padhibaku kahile"],
    ["Mother said, 'Eat your food'", "ମାଆ କହିଲେ, 'ତୁମ ଖାଣା ଖାଅ'", "maa kahile, 'tuma khana khaa'"],
    ["Mother told me to eat my food", "ମାଆ ମୋତେ ଖାଣା ଖାଇବାକୁ କହିଲେ", "maa mote khana khaibaku kahile"],
    ["He said, 'I did not go'", "ସେ କହିଲା, 'ମୁଁ ଯାଇ ନଥିଲି'", "se kahila, 'mun jai nathili'"],
    ["He said that he had not gone", "ସେ କହିଲା ଯେ ସେ ଯାଇ ନଥିଲା", "se kahila je se jai nathila"],
    ["She asked, 'Can I help you?'", "ସେ ପଚାରିଲା, 'ମୁଁ ସାହାଯ୍ୟ କରିପାରିବି କି?'", "se pacharila, 'mun sahayya karipaaribi ki?'"],
    ["She asked if she could help me", "ସେ ପଚାରିଲା ସେ ମୋତେ ସାହାଯ୍ୟ କରିପାରିବ କି", "se pacharila se mote sahayya karipariba ki"],
    ["He exclaimed that it was beautiful", "ସେ ଆଶ୍ଚର୍ଯ୍ୟ ହୋଇ କହିଲା ଏହା ସୁନ୍ଦର", "se ashcharyya hoi kahila eha sundara"],
    ["They said they would come", "ସେମାନେ କହିଲେ ସେମାନେ ଆସିବେ", "semane kahile semane asibe"],
    ["Father told me not to lie", "ବାପା ମୋତେ ମିଛ ନ କହିବାକୁ କହିଲେ", "bapa mote michha na kahibaku kahile"],
    ["She replied that she was fine", "ସେ ଉତ୍ତର ଦେଲା ଯେ ସେ ଭଲ ଅଛି", "se uttara dela je se bhala achhi"],
],

# ━━━ 534: Participles ━━━
534: [
    ["Running boy", "ଦୌଡ଼ୁଥିବା ପୁଅ", "dauduthiba pua"],
    ["Singing girl", "ଗାଉଥିବା ଝିଅ", "gauthiba jhia"],
    ["Written letter", "ଲେଖା ଚିଠି", "lekha chithi"],
    ["Broken glass", "ଭାଙ୍ଗିଯାଇଥିବା ଗ୍ଲାସ", "bhangijaithi ba glasa"],
    ["Sleeping child", "ଶୋଇଥିବା ପିଲା", "shoithiba pila"],
    ["Cooked food", "ରନ୍ଧା ଖାଦ୍ୟ", "randha khadya"],
    ["Having eaten, he went", "ଖାଇସାରି ସେ ଗଲା", "khaisari se gala"],
    ["Having read, she slept", "ପଢ଼ିସାରି ସେ ଶୋଇଲା", "padhisari se soila"],
    ["The fallen leaves are dry", "ଝଡ଼ିଯାଇଥିବା ପତ୍ର ଶୁଖିଲା", "jhadijaithi ba patra shukhila"],
    ["The boiling water is hot", "ଫୁଟୁଥିବା ପାଣି ଗରମ", "phututhiba pani garama"],
    ["A learned person", "ଶିକ୍ଷିତ ବ୍ୟକ୍ତି", "shikshita byakti"],
    ["A broken heart", "ଭାଙ୍ଗିଯାଇଥିବା ହୃଦୟ", "bhangijaithi ba hrudaya"],
    ["While walking, I saw a bird", "ଚାଲୁଥିଲାବେଳେ ମୁଁ ଏକ ପକ୍ଷୀ ଦେଖିଲି", "chaluthilabele mun eka pakshi dekhili"],
    ["Being tired, he rested", "ଥକି ସେ ବିଶ୍ରାମ ନେଲା", "thaki se bishrama nela"],
    ["The washed clothes are clean", "ଧୋଇଥିବା ଲୁଗା ସଫା", "dhoithiba luga sapha"],
    ["A flying bird", "ଉଡ଼ୁଥିବା ପକ୍ଷୀ", "uduthiba pakshi"],
    ["The completed work", "ସମ୍ପୂର୍ଣ୍ଣ ହୋଇଥିବା କାମ", "sampurna hoithiba kama"],
    ["Having arrived, he called me", "ପହଞ୍ଚି ସେ ମୋତେ ଡାକିଲା", "pahanchi se mote dakila"],
],

# ━━━ 535: Infinitives ━━━
535: [
    ["I want to eat", "ମୁଁ ଖାଇବାକୁ ଚାହେଁ", "mun khaibaku chahen"],
    ["She wants to go", "ସେ ଯିବାକୁ ଚାହେଁ", "se jibaku chahen"],
    ["He likes to read", "ସେ ପଢ଼ିବାକୁ ଭଲ ପାଏ", "se padhibaku bhala pae"],
    ["I need to study", "ମୋତେ ପଢ଼ିବାକୁ ଦରକାର", "mote padhibaku darakara"],
    ["They decided to go", "ସେମାନେ ଯିବାକୁ ନିଷ୍ପତ୍ତି ନେଲେ", "semane jibaku nishpatti nele"],
    ["To err is human", "ଭୁଲ କରିବା ମାନବ ସ୍ୱଭାବ", "bhula kariba manaba swabhaba"],
    ["To swim is good exercise", "ପହଁରିବା ଭଲ ବ୍ୟାୟାମ", "pahanriba bhala byayama"],
    ["I came here to learn Odia", "ମୁଁ ଓଡ଼ିଆ ଶିଖିବାକୁ ଆସିଛି", "mun odia shikhibaku asichhi"],
    ["He went to buy vegetables", "ସେ ପରିବା କିଣିବାକୁ ଗଲା", "se pariba kinibaku gala"],
    ["She started to cry", "ସେ କାନ୍ଦିବାକୁ ଲାଗିଲା", "se kandibaku lagila"],
    ["It is easy to learn", "ଶିଖିବା ସହଜ", "shikhiba sahaja"],
    ["It is difficult to understand", "ବୁଝିବା କଷ୍ଟକର", "bujhiba kashtakara"],
    ["I forgot to bring the book", "ମୁଁ ବହି ଆଣିବାକୁ ଭୁଲିଗଲି", "mun bahi anibaku bhuligali"],
    ["He promised to come", "ସେ ଆସିବାକୁ ପ୍ରତିଜ୍ଞା କଲା", "se asibaku pratijna kala"],
    ["She asked me to wait", "ସେ ମୋତେ ଅପେକ୍ଷା କରିବାକୁ କହିଲା", "se mote apeksha karibaku kahila"],
    ["He refused to help", "ସେ ସାହାଯ୍ୟ କରିବାକୁ ମନା କଲା", "se sahayya karibaku mana kala"],
    ["I hope to see you again", "ମୁଁ ତୁମକୁ ପୁଣି ଦେଖିବାକୁ ଆଶା କରେ", "mun tumaku puni dekhibaku asha kare"],
    ["We plan to travel next month", "ଆମେ ଆସନ୍ତା ମାସରେ ଘୂରିବାକୁ ଯୋଜନା କରୁଛୁ", "ame asanta masare ghuribaku yojana karuchhu"],
],

# ━━━ 536: Reduplication ━━━
536: [
    ["Slowly slowly", "ଧୀରେ ଧୀରେ", "dhire dhire"],
    ["Each and every house", "ଘରେ ଘରେ", "ghare ghare"],
    ["Sometimes sometimes", "କେବେ କେବେ", "kebe kebe"],
    ["Hot hot (very hot)", "ଗରମ ଗରମ", "garama garama"],
    ["One by one", "ଗୋଟିଏ ଗୋଟିଏ", "gotie gotie"],
    ["Day by day", "ଦିନେ ଦିନେ", "dine dine"],
    ["Big big trees", "ବଡ଼ ବଡ଼ ଗଛ", "bada bada gachha"],
    ["Small small children", "ସାନ ସାନ ପିଲା", "sana sana pila"],
    ["Walk slowly slowly", "ଧୀରେ ଧୀରେ ଚାଲ", "dhire dhire chala"],
    ["Various types", "ବିଭିନ୍ନ ବିଭିନ୍ନ ପ୍ରକାର", "bibhinna bibhinna prakara"],
    ["Here and there", "ଏଠି ସେଠି", "ethi sethi"],
    ["Now and then", "ମାଝେ ମାଝେ", "majhe majhe"],
    ["Little by little", "ଅଳ୍ପ ଅଳ୍ପ", "alpa alpa"],
    ["Sweet sweet mangoes", "ମିଠା ମିଠା ଆମ୍ବ", "mitha mitha amba"],
    ["Red red flowers", "ଲାଲ ଲାଲ ଫୁଲ", "lala lala phula"],
    ["Early in the morning", "ସକାଳ ସକାଳ", "sakala sakala"],
    ["Again and again", "ବାରମ୍ବାର", "barambara"],
    ["Each and every person", "ଜଣେ ଜଣେ ଲୋକ", "jane jane loka"],
],

# ━━━ 537: Echo words ━━━
537: [
    ["Tea and snacks (cha-pani)", "ଚା-ପାଣି", "cha-pani"],
    ["Food and such (khana-pina)", "ଖାଣା-ପିଣା", "khana-pina"],
    ["Clothes etc (luga-pata)", "ଲୁଗାପଟା", "lugapata"],
    ["Fruits etc (phala-mula)", "ଫଳମୂଳ", "phalamula"],
    ["Reading-writing (padha-lekha)", "ପଢ଼ା-ଲେଖା", "padha-lekha"],
    ["Hustle-bustle", "ହଲ୍‌ଚଲ୍", "halchal"],
    ["Bit by bit (thoda-bahut)", "ଟିକେ-ଟୁକେ", "tike-tuke"],
    ["Give me some tea etc", "ମୋତେ ଚା-ପାଣି ଦିଅ", "mote cha-pani dia"],
    ["Bring fruits etc", "ଫଳମୂଳ ଆଣ", "phalamula ana"],
    ["Rice and such (bhata-tarkari)", "ଭାତ-ତରକାରୀ", "bhata-tarakari"],
    ["Come-go (aasa-jiba)", "ଆସା-ଯିବା", "asa-jiba"],
    ["Big and small (bada-sana)", "ବଡ଼-ସାନ", "bada-sana"],
    ["Good and bad (bhala-manda)", "ଭଲ-ମନ୍ଦ", "bhala-manda"],
    ["Pots and pans", "ହାଣ୍ଡି-କୁଣ୍ଡି", "handi-kundi"],
    ["Relatives and such", "ଆତ୍ମୀୟ-ସ୍ୱଜନ", "atmiya-swajana"],
    ["Here and there (ethi-sethi)", "ଏଠି-ସେଠି", "ethi-sethi"],
    ["Buy groceries etc", "ବଜାର-ସଉଦା କିଣ", "bajara-sauda kina"],
    ["Do household work etc", "ଘର-ସଂସାର ସମ୍ଭାଳ", "ghara-samsara sambhala"],
],

# ━━━ 538: Classifiers ━━━
538: [
    ["One person (jana)", "ଜଣେ ଲୋକ", "jane loka"],
    ["One thing/item (gotie)", "ଗୋଟିଏ ଜିନିଷ", "gotie jinisha"],
    ["One piece (khanda)", "ଖଣ୍ଡେ କପଡ଼ା", "khande kapada"],
    ["One glass of water", "ଗ୍ଲାସେ ପାଣି", "glase pani"],
    ["One cup of tea", "ଏକ କପ୍ ଚା", "eka kap cha"],
    ["Two people", "ଦୁଇ ଜଣ", "dui jana"],
    ["Three books", "ତିନୋଟି ବହି", "tinoti bahi"],
    ["Four fruits", "ଚାରୋଟି ଫଳ", "charoti phala"],
    ["Five flowers", "ପାଞ୍ଚଟି ଫୁଲ", "panchati phula"],
    ["A bunch of bananas", "ଏକ କନ୍ଦି କଦଳୀ", "eka kandi kadali"],
    ["A pair of shoes", "ଏକ ଯୋଡ଼ା ଜୋତା", "eka joda jota"],
    ["A group of students", "ଏକ ଦଳ ଛାତ୍ର", "eka dala chhatra"],
    ["Give me two mangoes", "ମୋତେ ଦୁଇଟି ଆମ୍ବ ଦିଅ", "mote duiti amba dia"],
    ["I bought one kilogram of rice", "ମୁଁ ଏକ କିଲୋ ଚାଉଳ କିଣିଲି", "mun eka kilo chaula kinili"],
    ["A flock of birds", "ଏକ ଝୁଣ୍ଡ ପକ୍ଷୀ", "eka jhunda pakshi"],
    ["A piece of bread", "ଏକ ଖଣ୍ଡ ରୁଟି", "eka khanda ruti"],
    ["A bottle of milk", "ଏକ ବୋତଲ କ୍ଷୀର", "eka botala kshira"],
    ["Several people came", "ଅନେକ ଜଣ ଆସିଲେ", "aneka jana asile"],
],

# ━━━ 539: Emphasis particles ━━━
539: [
    ["I only will go", "ମୁଁ ହିଁ ଯିବି", "mun hin jibi"],
    ["He himself did it", "ସେ ନିଜେ କଲା", "se nije kala"],
    ["Even he came", "ସେ ମଧ୍ୟ ଆସିଲା", "se madhya asila"],
    ["Only you can do this", "କେବଳ ତୁ ଏହା କରିପାରିବ", "kebala tu eha karipariba"],
    ["He too went there", "ସେ ବି ସେଠିକୁ ଗଲା", "se bi sethiku gala"],
    ["Just give me one", "ମୋତେ ବସ୍ ଗୋଟିଏ ଦିଅ", "mote bas gotie dia"],
    ["I really liked it", "ମୋତେ ସତରେ ଭଲ ଲାଗିଲା", "mote satare bhala lagila"],
    ["Even children know this", "ପିଲାମାନେ ମଧ୍ୟ ଏହା ଜାଣନ୍ତି", "pilamane madhya eha jananti"],
    ["Indeed he is honest", "ସତରେ ସେ ସଚ୍ଚୋଟ", "satare se sachchota"],
    ["Only this much", "ଏତିକି ହିଁ", "etiki hin"],
    ["He especially came for you", "ସେ ବିଶେଷ କରି ତୁମ ପାଇଁ ଆସିଲା", "se bishesha kari tuma pain asila"],
    ["That very book", "ସେହି ବହି", "sehi bahi"],
    ["At least come once", "ଅନ୍ତତଃ ଥରେ ଆସ", "antatah thare asa"],
    ["He alone did all the work", "ସେ ଏକୁଟିଆ ସମସ୍ତ କାମ କଲା", "se ekutia samasta kama kala"],
    ["Definitely I will come", "ନିଶ୍ଚୟ ମୁଁ ଆସିବି", "nishchaya mun asibi"],
    ["I myself saw it", "ମୁଁ ନିଜେ ଦେଖିଲି", "mun nije dekhili"],
    ["Surely he knows", "ନିଶ୍ଚିତ ସେ ଜାଣେ", "nishchita se jane"],
    ["This only is the truth", "ଏହା ହିଁ ସତ", "eha hin sata"],
],

# ━━━ 540: Sentence connectors ━━━
540: [
    ["Therefore, he went home", "ତେଣୁ ସେ ଘରକୁ ଗଲା", "tenu se gharaku gala"],
    ["However, she stayed", "ତଥାପି ସେ ରହିଲା", "tathapi se rahila"],
    ["Moreover, he is smart", "ଏତଦ୍‌ବ୍ୟତୀତ ସେ ଚତୁର", "etadbyatita se chatura"],
    ["Meanwhile, I waited", "ଏହି ସମୟରେ ମୁଁ ଅପେକ୍ଷା କଲି", "ehi samayare mun apeksha kali"],
    ["First he ate, then he left", "ପ୍ରଥମେ ସେ ଖାଇଲା, ତା'ପରେ ଚାଲିଗଲା", "prathame se khaila, ta'pare chaligala"],
    ["In addition, she is kind", "ଏହା ସହିତ ସେ ଦୟାଳୁ", "eha sahita se dayalu"],
    ["On the other hand", "ଅନ୍ୟ ପକ୍ଷରେ", "anya pakshare"],
    ["For example, Puri is beautiful", "ଉଦାହରଣ ସ୍ୱରୂପ, ପୁରୀ ସୁନ୍ଦର", "udaharana swarupa, Puri sundara"],
    ["In conclusion, he agreed", "ଶେଷରେ ସେ ରାଜି ହେଲା", "sheshare se raji hela"],
    ["As a result, he passed", "ଫଳସ୍ୱରୂପ ସେ ପାସ କଲା", "phalaswarupa se pasa kala"],
    ["In other words", "ଅର୍ଥାତ୍", "arthat"],
    ["Similarly, she also won", "ସେହିପରି ସେ ମଧ୍ୟ ଜିତିଲା", "sehipari se madhya jitila"],
    ["Afterwards, we went home", "ପରେ ଆମେ ଘରକୁ ଗଲୁ", "pare ame gharaku galu"],
    ["In fact, this is true", "ବାସ୍ତବରେ ଏହା ସତ", "bastabare eha sata"],
    ["Besides, it is cheap", "ଏହା ସହିତ ଏହା ସସ୍ତା", "eha sahita eha sasta"],
    ["Consequently, they lost", "ଫଳରେ ସେମାନେ ହାରିଲେ", "phalare semane harile"],
    ["Finally, he arrived", "ଶେଷରେ ସେ ପହଞ୍ଚିଲା", "sheshare se pahanchila"],
    ["Nevertheless, he tried", "ତଥାପି ସେ ଚେଷ୍ଟା କଲା", "tathapi se cheshta kala"],
],

# ━━━ 541: Formal vs informal speech ━━━
541: [
    ["Come (informal)", "ଆସ", "asa"],
    ["Come (formal)", "ଆସନ୍ତୁ", "asantu"],
    ["Sit (informal)", "ବସ", "basa"],
    ["Sit (formal)", "ବସନ୍ତୁ", "basantu"],
    ["Tell me (informal)", "ମୋତେ କୁହ", "mote kuha"],
    ["Tell me (formal)", "ମୋତେ କୁହନ୍ତୁ", "mote kuhantu"],
    ["What's your name? (informal)", "ତୋ ନାମ କ'ଣ?", "to nama kana?"],
    ["What is your name? (formal)", "ଆପଣଙ୍କ ନାମ କ'ଣ?", "apananka nama kana?"],
    ["How are you? (informal)", "ତୁ କେମିତି ଅଛୁ?", "tu kemiti achhu?"],
    ["How are you? (formal)", "ଆପଣ କେମିତି ଅଛନ୍ତି?", "apana kemiti achhanti?"],
    ["Eat food (informal)", "ଖାଣା ଖାଅ", "khana khaa"],
    ["Please eat (formal)", "ଦୟାକରି ଖାଆନ୍ତୁ", "dayakari khaantu"],
    ["Go now (informal)", "ଏବେ ଯାଅ", "ebe jaa"],
    ["Please go now (formal)", "ଦୟାକରି ଏବେ ଯାଆନ୍ତୁ", "dayakari ebe jaantu"],
    ["Listen (informal)", "ଶୁଣ", "shuna"],
    ["Please listen (formal)", "ଦୟାକରି ଶୁଣନ୍ତୁ", "dayakari shunantu"],
    ["You did well (informal)", "ତୁ ଭଲ କଲୁ", "tu bhala kalu"],
    ["You did well (formal)", "ଆପଣ ଭଲ କଲେ", "apana bhala kale"],
],

# ━━━ 542: Common grammar mistakes ━━━
542: [
    ["Wrong: ମୁଁ ଯାଇଛେ → Right: ମୁଁ ଯାଇଛି", "ମୁଁ ଯାଇଛି (I have gone)", "mun jaichhi"],
    ["Wrong: ସେ ଆସିଲି → Right: ସେ ଆସିଲା", "ସେ ଆସିଲା (He came)", "se asila"],
    ["Wrong: ମୋର ଯାଇଛି → Right: ମୁଁ ଯାଇଛି", "ମୁଁ ଯାଇଛି (I have gone)", "mun jaichhi"],
    ["Wrong: ତୁମେ ଯାଅ → Right: ତୁ ଯାଅ / ଆପଣ ଯାଆନ୍ତୁ", "ତୁ ଯାଅ (You go, informal)", "tu jaa"],
    ["Don't mix tu/tume/apana forms", "ତୁ/ତୁମେ/ଆପଣ ସଠିକ ବ୍ୟବହାର କର", "tu/tume/apana sathika byabahara kara"],
    ["Wrong verb ending with subject", "କର୍ତ୍ତା ସହ କ୍ରିୟାର ମେଳ ରଖ", "kartta saha kriyara mela rakha"],
    ["Wrong: ମୁଁ ଯାଏ → Right: ମୁଁ ଯାଏ / ଯାଉଛି", "ମୁଁ ଯାଉଛି (I am going)", "mun jauchhi"],
    ["Wrong postposition: ଘରକୁ ଯାଏ vs ଘରେ ଅଛି", "ଘରକୁ ଯାଏ (going to) vs ଘରେ ଅଛି (is at)", "gharaku jae vs ghare achhi"],
    ["Wrong: ସେମାନେ ଆସିଲା → Right: ସେମାନେ ଆସିଲେ", "ସେମାନେ ଆସିଲେ (They came)", "semane asile"],
    ["Honorific mismatch with elders", "ବଡ଼ ଲୋକଙ୍କ ସହ ସମ୍ମାନ ସୂଚକ ଶବ୍ଦ ବ୍ୟବହାର କର", "bada lokanka saha sammana suchaka shabda byabahara kara"],
    ["Wrong: ମୋତେ ବହି ଦେ → Right: ମୋତେ ବହି ଦିଅ", "ମୋତେ ବହି ଦିଅ (Give me the book)", "mote bahi dia"],
    ["Wrong plural: ବହିସବୁ → Right: ବହିଗୁଡ଼ିକ", "ବହିଗୁଡ଼ିକ (The books)", "bahigudika"],
    ["Wrong: ସେ ଖାଇଲା ଖାଣା → Right: ସେ ଖାଣା ଖାଇଲା", "ସେ ଖାଣା ଖାଇଲା (He ate food)", "se khana khaila"],
    ["Subject-Object-Verb is Odia word order", "ଓଡ଼ିଆରେ କର୍ତ୍ତା-କର୍ମ-କ୍ରିୟା କ୍ରମ", "odiare kartta-karma-kriya krama"],
    ["Wrong: ମୁଁ ତାର ସାଙ୍ଗ → Right: ମୁଁ ତା ସାଙ୍ଗ", "ମୁଁ ତା ସାଙ୍ଗ (I am his friend)", "mun ta sanga"],
    ["Wrong negation: ମୁଁ ନାହିଁ ଯାଏ → Right: ମୁଁ ଯାଏ ନାହିଁ", "ମୁଁ ଯାଏ ନାହିଁ (I don't go)", "mun jae nahin"],
    ["Wrong: ମୋ ପାଖରେ ଦୁଇ ବହି → Right: ମୋ ପାଖରେ ଦୁଇଟି ବହି", "ମୋ ପାଖରେ ଦୁଇଟି ବହି (I have two books)", "mo pakhare duiti bahi"],
    ["Always use classifiers with numbers", "ସଂଖ୍ୟା ସହ ସର୍ବଦା ବିଭକ୍ତି ବ୍ୟବହାର କର", "sankhya saha sarbada bibhakti byabahara kara"],
],

}  # end LESSONS


def main():
    path = BASE / "data_odia.json"
    data = json.loads(path.read_text(encoding="utf-8"))

    updated = 0
    for ch in data:
        cid = ch["id"]
        if cid not in LESSONS:
            continue

        ch["blocks"] = [{
            "type": "table",
            "columns": ["English", "Odia", "Transliteration"],
            "rows": LESSONS[cid],
        }]
        updated += 1

    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Updated {updated} grammar lessons (510-542) in data_odia.json")


if __name__ == "__main__":
    main()
