import json
d = json.load(open('data_odia.json','r',encoding='utf-8'))
L = {}

L[642] = [
    ["I want to open a bank account","ମୁଁ ବ୍ୟାଙ୍କ ଆକାଉଣ୍ଟ ଖୋଲିବାକୁ ଚାହେଁ","Mun bank account kholibaku chahen"],
    ["Please fill this form","ଦୟାକରି ଏହି ଫର୍ମ ପୂରଣ କରନ୍ତୁ","Dayakari ehi form purana karantu"],
    ["I need a savings account","ମୋତେ ସେଭିଂ ଆକାଉଣ୍ଟ ଦରକାର","Mote saving account darkar"],
    ["What documents are required?","କେଉଁ କାଗଜ ଦରକାର?","Keun kagaj darkar?"],
    ["Bring your AADHAR and PAN card","ଆଧାର ଓ ପାନ କାର୍ଡ ଆଣନ୍ତୁ","Aadhar o PAN card anantu"],
    ["I want to deposit money","ମୁଁ ଟଙ୍କା ଜମା କରିବାକୁ ଚାହେଁ","Mun tanka jama karibaku chahen"],
    ["I want to withdraw money","ମୁଁ ଟଙ୍କା ଉଠାଇବାକୁ ଚାହେଁ","Mun tanka uthaibaku chahen"],
    ["Please check my balance","ଦୟାକରି ମୋ ବ୍ୟାଲାନ୍ସ ଯାଞ୍ଚ କରନ୍ତୁ","Dayakari mo balance yancha karantu"],
    ["I need a cheque book","ମୋତେ ଚେକବୁକ ଦରକାର","Mote chequebook darkar"],
    ["My ATM card is blocked","ମୋ ଏଟିଏମ କାର୍ଡ ବ୍ଲକ ହୋଇଗଲା","Mo ATM card block hoigala"],
    ["I want to transfer money","ମୁଁ ଟଙ୍କା ଟ୍ରାନ୍ସଫର କରିବାକୁ ଚାହେଁ","Mun tanka transfer karibaku chahen"],
    ["What is the interest rate?","ସୁଧ ହାର କେତେ?","Sudh hara kete?"],
    ["I want a fixed deposit","ମୋତେ ଫିକ୍ସଡ ଡିପୋଜିଟ ଦରକାର","Mote fixed deposit darkar"],
    ["Please update my passbook","ଦୟାକରି ମୋ ପାସବୁକ ଅପଡେଟ କରନ୍ତୁ","Dayakari mo passbook update karantu"],
    ["Where is the ATM?","ଏଟିଏମ କେଉଁଠି?","ATM keunthi?"],
    ["I want a loan for my house","ମୋତେ ଘର ପାଇଁ ଋଣ ଦରକାର","Mote ghara pain runa darkar"],
    ["Sign here please","ଦୟାକରି ଏଠାରେ ସହି କରନ୍ତୁ","Dayakari ethare sahi karantu"],
    ["Thank you for your help","ଆପଣଙ୍କ ସାହାଯ୍ୟ ପାଇଁ ଧନ୍ୟବାଦ","Apananka sahayya pain dhanyabad"]
]
L[643] = [
    ["Where is the nearest temple?","ନିକଟତମ ମନ୍ଦିର କେଉଁଠି?","Nikatatama mandira keunthi?"],
    ["How do we get there?","ଆମେ ସେଠାକୁ କିପରି ଯିବା?","Ame sethaku kipari yiba?"],
    ["What time does the temple open?","ମନ୍ଦିର କେତେ ବେଳେ ଖୋଲେ?","Mandira kete bele khole?"],
    ["The temple opens at 6 in the morning","ମନ୍ଦିର ସକାଳ ଛଅଟାରେ ଖୋଲେ","Mandira sakala chhaatare khole"],
    ["Is photography allowed?","ଫଟୋ ତୋଳିବା ଅନୁମତି ଅଛି?","Photo toliba anumati achhi?"],
    ["Remove your shoes before entering","ଭିତରେ ଯିବା ଆଗରୁ ଜୋତା ଖୋଲନ୍ତୁ","Bhitare yiba agaru jota kholantu"],
    ["The temple is on top of the hill","ମନ୍ଦିର ପାହାଡ଼ ଉପରେ","Mandira pahada upare"],
    ["How many steps are there?","କେତୋଟି ସିଡ଼ି ଅଛି?","Ketoti sidi achhi?"],
    ["About 200 steps","ପ୍ରାୟ ଦୁଇଶହ ସିଡ଼ି","Praya duisaha sidi"],
    ["When is the festival here?","ଏଠାରେ ପର୍ବ କେବେ?","Ethare parba kebe?"],
    ["Many people come to pray","ବହୁ ଲୋକ ପୂଜା କରିବାକୁ ଆସନ୍ତି","Bahu loka puja karibaku asanti"],
    ["The temple is very beautiful","ମନ୍ଦିର ବହୁତ ସୁନ୍ଦର","Mandira bahut sundar"],
    ["We should respect all sacred places","ଆମେ ସବୁ ପବିତ୍ର ସ୍ଥାନକୁ ସମ୍ମାନ କରିବା ଉଚିତ","Ame sabu pabitra sthanaku sammana kariba uchita"],
    ["Is there water available there?","ସେଠାରେ ପାଣି ମିଳିବ?","Sethare pani miliba?"],
    ["Let us go early morning","ଆସନ୍ତୁ ସକାଳୁ ଯିବା","Asantu sakalu yiba"],
    ["This visit was very peaceful","ଏହି ଯାତ୍ରା ବହୁତ ଶାନ୍ତ ଥିଲା","Ehi yatra bahut shanta thila"],
    ["The prasad was delicious","ପ୍ରସାଦ ସ୍ୱାଦିଷ୍ଟ ଥିଲା","Prasad swadishta thila"],
    ["Jagannath temple is world famous","ଜଗନ୍ନାଥ ମନ୍ଦିର ବିଶ୍ୱ ପ୍ରସିଦ୍ଧ","Jagannath mandira bishwa prasiddha"]
]
L[644] = [
    ["Greetings uncle and aunty","ନମସ୍କାର କାକା ଓ କାକୀ","Namaskaar kaka o kaki"],
    ["Please sit down and eat","ଦୟାକରି ବସନ୍ତୁ ଓ ଖାଆନ୍ତୁ","Dayakari basantu o khaantu"],
    ["The food looks delicious","ଖାଦ୍ୟ ବହୁତ ସ୍ୱାଦିଷ୍ଟ ଦେଖାଯାଉଛି","Khadya bahut swadishta dekhayauchhi"],
    ["Thank you for inviting me","ମୋତେ ଡାକିଥିବାରୁ ଧନ୍ୟବାଦ","Mote dakithibaru dhanyabad"],
    ["Do you like rice or roti?","ଆପଣ ଭାତ ପସନ୍ଦ କରନ୍ତି ନା ରୁଟି?","Apana bhata pasanda karanti na ruti?"],
    ["I will have rice please","ମୁଁ ଭାତ ଖାଇବି","Mun bhata khaibi"],
    ["Please have some more dal","ଦୟାକରି ଆଉ କିଛି ଡାଲ ନିଅନ୍ତୁ","Dayakari au kichhi dal niantu"],
    ["The vegetables are very tasty","ତରକାରୀ ବହୁତ ସ୍ୱାଦିଷ୍ଟ","Tarakari bahut swadishta"],
    ["Aunty cooks very well","କାକୀ ବହୁତ ଭଲ ରାନ୍ଧନ୍ତି","Kaki bahut bhala randhanti"],
    ["Have some more, don't be shy","ଆଉ କିଛି ନିଅନ୍ତୁ, ଲାଜ କରନ୍ତୁ ନାହିଁ","Au kichhi niantu, laj karantu nahin"],
    ["No thank you, I am full","ନାଁ ଧନ୍ୟବାଦ, ମୋ ପେଟ ଭରିଗଲା","Naan dhanyabad, mo peta bharigala"],
    ["Would you like water?","ପାଣି ପିଇବେ?","Pani piibe?"],
    ["Yes please, give me some water","ହଁ, କିଛି ପାଣି ଦିଅନ୍ତୁ","Han, kichhi pani diantu"],
    ["What grade is your son in?","ଆପଣଙ୍କ ପୁଅ କେଉଁ କ୍ଲାସରେ?","Apananka pua keun class re?"],
    ["He is in 10th grade","ସେ ଦଶମ ଶ୍ରେଣୀରେ","Se dashama shrenire"],
    ["You have a lovely home","ଆପଣଙ୍କ ଘର ବହୁତ ସୁନ୍ଦର","Apananka ghara bahut sundar"],
    ["Thank you for the wonderful meal","ସ୍ୱାଦିଷ୍ଟ ଖାଦ୍ୟ ପାଇଁ ଧନ୍ୟବାଦ","Swadishta khadya pain dhanyabad"],
    ["Please come to our house too","ଆପଣ ମଧ୍ୟ ଆମ ଘରକୁ ଆସନ୍ତୁ","Apana madhya ama gharaku asantu"]
]
L[645] = [
    ["Did you watch the match yesterday?","ଗତକାଲି ମ୍ୟାଚ ଦେଖିଲ?","Gatakali match dekhila?"],
    ["Yes! It was an amazing game","ହଁ! ବହୁତ ଭଲ ଖେଳ ଥିଲା","Han! Bahut bhala khela thila"],
    ["Who scored the first goal?","ପ୍ରଥମ ଗୋଲ କିଏ କଲା?","Prathama goal kie kala?"],
    ["The striker scored a brilliant goal","ଷ୍ଟ୍ରାଇକର ସୁନ୍ଦର ଗୋଲ କଲା","Striker sundar goal kala"],
    ["The goalkeeper saved many shots","ଗୋଲକିପର ବହୁ ସଟ ବଞ୍ଚାଇଲା","Goalkeeper bahu shot banchila"],
    ["What was the final score?","ଶେଷ ସ୍କୋର କେତେ?","Shesha score kete?"],
    ["It was 2-1","ଦୁଇ-ଏକ ଥିଲା","Dui-ek thila"],
    ["Which team do you support?","ତୁମେ କେଉଁ ଟିମ ସମର୍ଥନ କର?","Tume keun team samarthana kara?"],
    ["I support East Bengal","ମୁଁ ଇଷ୍ଟ ବେଙ୍ଗଲ ସମର୍ଥନ କରେ","Mun East Bengal samarthana kare"],
    ["The referee gave a penalty","ରେଫେରୀ ପେନାଲ୍ଟି ଦେଲେ","Referee penalty dele"],
    ["That was a red card foul","ସେଟା ରେଡ କାର୍ଡ ଫାଉଲ ଥିଲା","Seta red card foul thila"],
    ["The crowd was very excited","ଦର୍ଶକ ବହୁତ ଉତ୍ସାହିତ ଥିଲେ","Darshaka bahut utsahita thile"],
    ["Let's go watch the next match","ଆସ ପରବର୍ତ୍ତୀ ମ୍ୟାଚ ଦେଖିବା","Asa parabarti match dekhiba"],
    ["Football is my favourite sport","ଫୁଟବଲ ମୋ ପ୍ରିୟ ଖେଳ","Football mo priya khela"],
    ["I play football every evening","ମୁଁ ପ୍ରତିଦିନ ସନ୍ଧ୍ୟାରେ ଫୁଟବଲ ଖେଳେ","Mun pratidina sandhyare football khele"],
    ["The match was very thrilling","ମ୍ୟାଚ ବହୁତ ରୋମାଞ୍ଚକର ଥିଲା","Match bahut romanchakara thila"],
    ["We should play more sports","ଆମେ ଅଧିକ ଖେଳ ଖେଳିବା ଉଚିତ","Ame adhika khela kheliba uchita"],
    ["The stadium was full","ଷ୍ଟେଡିୟମ ଭରି ଯାଇଥିଲା","Stadium bhari jaithila"]
]
L[646] = [
    ["Let's go watch a movie","ଆସ ସିନେମା ଦେଖିବା","Asa cinema dekhiba"],
    ["Which movie should we watch?","ଆମେ କେଉଁ ସିନେମା ଦେଖିବା?","Ame keun cinema dekhiba?"],
    ["The new action movie is good","ନୂଆ ଆକ୍ସନ ଫିଲ୍ମ ଭଲ","Nua action film bhala"],
    ["What time does the show start?","ସୋ କେତେ ବେଳେ ଆରମ୍ଭ?","Show kete bele arambha?"],
    ["The show is at 6 in the evening","ସନ୍ଧ୍ୟା ଛଅଟାରେ ସୋ","Sandhya chhaatare show"],
    ["How much is the ticket?","ଟିକେଟ କେତେ?","Ticket kete?"],
    ["Let's book online","ଅନଲାଇନରେ ବୁକ କରିବା","Online re book kariba"],
    ["I'll buy the popcorn","ମୁଁ ପପକର୍ଣ୍ଣ କିଣିବି","Mun popcorn kinibi"],
    ["The movie has good reviews","ଫିଲ୍ମର ଭଲ ରିଭିଉ","Filmara bhala review"],
    ["Let's meet at the mall at 5","ପାଞ୍ଚଟାରେ ମଲରେ ଭେଟିବା","Paanchatare mall re bhetiba"],
    ["Don't be late","ଲେଟ ହୁଅ ନାହିଁ","Late hua nahin"],
    ["The movie was amazing!","ସିନେମା ବହୁତ ଭଲ ଥିଲା!","Cinema bahut bhala thila!"],
    ["The hero acted very well","ନାୟକ ବହୁତ ଭଲ ଅଭିନୟ କଲେ","Nayak bahut bhala abhinaya kale"],
    ["Let's come again next week","ଆସନ୍ତା ସପ୍ତାହରେ ଆଉ ଆସିବା","Asanta saptahare au asiba"],
    ["That was a fun evening","ସେ ସନ୍ଧ୍ୟା ବହୁତ ମଜା ଥିଲା","Se sandhya bahut maja thila"],
    ["The songs were beautiful","ଗୀତ ବହୁତ ସୁନ୍ଦର ଥିଲା","Gita bahut sundar thila"],
    ["I like Odia movies","ମୋତେ ଓଡ଼ିଆ ସିନେମା ଭଲ ଲାଗେ","Mote Odia cinema bhala lage"],
    ["Which is your favourite actor?","ତୋର ପ୍ରିୟ ଅଭିନେତା କିଏ?","Tora priya abhineta kie?"]
]
L[647] = [
    ["The FIFA World Cup is starting soon","ଫିଫା ୱାର୍ଲ୍ଡ କପ ଶୀଘ୍ର ଆରମ୍ଭ ହେବ","FIFA World Cup shighra arambha heba"],
    ["Which team will win?","କେଉଁ ଟିମ ଜିତିବ?","Keun team jitiba?"],
    ["I think Brazil will win","ମୋ ମତରେ ବ୍ରାଜିଲ ଜିତିବ","Mo matare Brazil jitiba"],
    ["Argentina is also very strong","ଆର୍ଜେଣ୍ଟିନା ମଧ୍ୟ ବହୁତ ଶକ୍ତିଶାଳୀ","Argentina madhya bahut shaktishali"],
    ["Messi is the best player","ମେସି ସର୍ବଶ୍ରେଷ୍ଠ ଖେଳାଳି","Messi sarbashreshtha khelali"],
    ["The matches are at night","ମ୍ୟାଚ ରାତିରେ ହୁଏ","Match ratire hue"],
    ["Let's watch it together","ଆସ ଏକାଠି ଦେଖିବା","Asa ekathi dekhiba"],
    ["India has not qualified yet","ଭାରତ ଏପର୍ଯ୍ୟନ୍ତ ଯୋଗ୍ୟ ହୋଇନାହିଁ","Bharat eparyanta yogya hoinahin"],
    ["Maybe one day India will play","ଦିନେ ଭାରତ ମଧ୍ୟ ଖେଳିବ","Dine Bharat madhya kheliba"],
    ["The World Cup comes every 4 years","ୱାର୍ଲ୍ଡ କପ ଚାରି ବର୍ଷରେ ଆସେ","World Cup chari barshare ase"],
    ["The final will be exciting","ଫାଇନାଲ ବହୁତ ରୋମାଞ୍ଚକର ହେବ","Final bahut romanchakara heba"],
    ["Many goals were scored today","ଆଜି ବହୁ ଗୋଲ ହୋଇଛି","Aji bahu goal hoichhi"],
    ["The match went to penalty shootout","ମ୍ୟାଚ ପେନାଲ୍ଟି ସୁଟଆଉଟକୁ ଗଲା","Match penalty shootout ku gala"],
    ["What a thrilling match!","କଣ ରୋମାଞ୍ଚକର ମ୍ୟାଚ!","Kana romanchakara match!"],
    ["Football unites the whole world","ଫୁଟବଲ ସାରା ବିଶ୍ୱକୁ ଏକ କରେ","Football sara bishwaku eka kare"],
    ["Let's celebrate the victory","ଆସ ବିଜୟ ପାଳନ କରିବା","Asa bijaya palana kariba"],
    ["I cannot wait for the next match","ମୁଁ ପରବର୍ତ୍ତୀ ମ୍ୟାଚ ପାଇଁ ଅପେକ୍ଷା କରିପାରୁ ନାହିଁ","Mun parabarti match pain apeksha kariparu nahin"],
    ["Sports brings people together","ଖେଳ ଲୋକଙ୍କୁ ଏକାଠି କରେ","Khela lokanku ekathi kare"]
]
L[648] = [
    ["Welcome to Odisha!","ଓଡ଼ିଶାକୁ ସ୍ୱାଗତ!","Odishaku swagat!"],
    ["This is a very ancient place","ଏହା ଏକ ବହୁ ପୁରାତନ ସ୍ଥାନ","Eha eka bahu puratana sthana"],
    ["This temple is 800 years old","ଏହି ମନ୍ଦିର ଆଠଶହ ବର୍ଷ ପୁରୁଣା","Ehi mandira aathasaha barsha puruna"],
    ["Please follow me","ଦୟାକରି ମୋ ସହ ଆସନ୍ତୁ","Dayakari mo saha asantu"],
    ["Do not touch the statues","ମୂର୍ତ୍ତି ଛୁଅଁନ୍ତୁ ନାହିଁ","Murti chhuantu nahin"],
    ["You can take photos here","ଆପଣ ଏଠାରେ ଫଟୋ ତୋଳି ପାରିବେ","Apana ethare photo toli parebe"],
    ["The Chilika lake is very beautiful","ଚିଲିକା ହ୍ରଦ ବହୁତ ସୁନ୍ଦର","Chilika hrada bahut sundar"],
    ["Odisha has rich culture and traditions","ଓଡ଼ିଶାର ସମୃଦ୍ଧ ସଂସ୍କୃତି ଅଛି","Odishara samruddha sanskruti achhi"],
    ["The view from here is amazing","ଏଠାରୁ ଦୃଶ୍ୟ ବହୁତ ସୁନ୍ଦର","Etharu drishya bahut sundar"],
    ["We will stop here for lunch","ଆମେ ଏଠାରେ ଖାଇବା ପାଇଁ ଅଟକିବା","Ame ethare khaiba pain atakiba"],
    ["Do you have any questions?","ଆପଣଙ୍କର କିଛି ପ୍ରଶ୍ନ ଅଛି?","Apanankara kichhi prashna achhi?"],
    ["The bus will leave at 4 pm","ଚାରିଟାରେ ବସ ଛାଡ଼ିବ","Charitare bas chhadiba"],
    ["Please be on time","ଦୟାକରି ଠିକ ସମୟରେ ଆସନ୍ତୁ","Dayakari thik samayare asantu"],
    ["I hope you enjoyed the tour","ଆଶା କରୁଛି ଯାତ୍ରା ଆପଣଙ୍କୁ ଭଲ ଲାଗିଲା","Asha karuchhi yatra apananku bhala lagila"],
    ["Konark Sun Temple is a UNESCO site","କୋଣାର୍କ ସୂର୍ଯ୍ୟ ମନ୍ଦିର ୟୁନେସ୍କୋ ସ୍ଥାନ","Konark Surya mandira UNESCO sthana"],
    ["Thank you for visiting","ଆସିଥିବାରୁ ଧନ୍ୟବାଦ","Asithibaru dhanyabad"],
    ["Puri beach is very famous","ପୁରୀ ସମୁଦ୍ର ତଟ ବହୁତ ପ୍ରସିଦ୍ଧ","Puri samudra tata bahut prasiddha"],
    ["Please come again!","ଦୟାକରି ଆଉ ଆସନ୍ତୁ!","Dayakari au asantu!"]
]
L[649] = [
    ["I am here for the language test","ମୁଁ ଭାଷା ପରୀକ୍ଷା ପାଇଁ ଆସିଛି","Mun bhasha pariksha pain asichhi"],
    ["Please show your admit card","ଦୟାକରି ଆଡମିଟ କାର୍ଡ ଦେଖାନ୍ତୁ","Dayakari admit card dekhantu"],
    ["The test is in Odia language","ପରୀକ୍ଷା ଓଡ଼ିଆ ଭାଷାରେ","Pariksha Odia bhashare"],
    ["Can you read Odia script?","ଆପଣ ଓଡ଼ିଆ ଲିପି ପଢ଼ିପାରିବେ?","Apana Odia lipi padhipare?"],
    ["Yes, I can read and write Odia","ହଁ, ମୁଁ ଓଡ଼ିଆ ପଢ଼ି ଓ ଲେଖିପାରେ","Han, mun Odia padhi o lekhipare"],
    ["Write a letter in Odia","ଓଡ଼ିଆରେ ଗୋଟିଏ ଚିଠି ଲେଖନ୍ତୁ","Odia re gotie chithi lekhantu"],
    ["Translate this sentence to Odia","ଏହି ବାକ୍ୟ ଓଡ଼ିଆରେ ଅନୁବାଦ କରନ୍ତୁ","Ehi bakya Odia re anubad karantu"],
    ["Read this paragraph aloud","ଏହି ଅନୁଚ୍ଛେଦ ଜୋରରେ ପଢ଼ନ୍ତୁ","Ehi anuchchheda jorare padhantu"],
    ["The test has reading and writing","ପରୀକ୍ଷାରେ ପଢ଼ିବା ଓ ଲେଖିବା ଅଛି","Parikshare padhiba o lekhiba achhi"],
    ["You have one hour to complete","ସମ୍ପୂର୍ଣ୍ଣ କରିବାକୁ ଏକ ଘଣ୍ଟା ଅଛି","Sampurna karibaku eka ghanta achhi"],
    ["Fill in the blanks","ଖାଲି ଜାଗା ପୂରଣ କରନ୍ତୁ","Khali jaga purana karantu"],
    ["Choose the correct answer","ସଠିକ ଉତ୍ତର ବାଛନ୍ତୁ","Sathik uttara bachhantu"],
    ["This is a speaking test","ଏହା ଏକ ମୌଖିକ ପରୀକ୍ଷା","Eha eka moukhik pariksha"],
    ["Speak clearly and slowly","ସ୍ପଷ୍ଟ ଓ ଧୀରେ କୁହନ୍ତୁ","Spashta o dhire kuhantu"],
    ["Your test is complete","ଆପଣଙ୍କ ପରୀକ୍ଷା ସମ୍ପୂର୍ଣ୍ଣ","Apananka pariksha sampurna"],
    ["The results will come in a week","ଫଳାଫଳ ଏକ ସପ୍ତାହରେ ଆସିବ","Phalaphala eka saptahare asiba"],
    ["I passed the language test!","ମୁଁ ଭାଷା ପରୀକ୍ଷା ପାସ କଲି!","Mun bhasha pariksha pass kali!"],
    ["Language skills are important for banking","ବ୍ୟାଙ୍କ ପାଇଁ ଭାଷା ଜ୍ଞାନ ଗୁରୁତ୍ୱପୂର୍ଣ୍ଣ","Bank pain bhasha jnana gurutwapurna"]
]
L[650] = [
    ["I am hungry","ମୋତେ ଭୋକ ଲାଗୁଛି","Mote bhoka laguchhi"],
    ["What will you eat today?","ଆଜି କଣ ଖାଇବ?","Aji kana khaiba?"],
    ["I will eat rice and dal","ମୁଁ ଭାତ ଓ ଡାଲ ଖାଇବି","Mun bhata o dal khaibi"],
    ["The food is very delicious","ଖାଦ୍ୟ ବହୁତ ସ୍ୱାଦିଷ୍ଟ","Khadya bahut swadishta"],
    ["I like fish curry","ମୋତେ ମାଛ ଝୋଳ ଭଲ ଲାଗେ","Mote machha jhola bhala lage"],
    ["Mother cooks very well","ମା ବହୁତ ଭଲ ରାନ୍ଧନ୍ତି","Maa bahut bhala randhanti"],
    ["Shall we eat together?","ଆମେ ଏକାଠି ଖାଇବା?","Ame ekathi khaiba?"],
    ["Wash your hands before eating","ଖାଇବା ଆଗରୁ ହାତ ଧୋଅ","Khaiba agaru hata dhoa"],
    ["The chicken curry is spicy","ମୁର୍ଗୀ ଝୋଳ ଝାଳ","Murgi jhola jhala"],
    ["Give me some more rice","ଆଉ କିଛି ଭାତ ଦିଅ","Au kichhi bhata dia"],
    ["I don't eat meat","ମୁଁ ମାଂସ ଖାଏ ନାହିଁ","Mun mansa khae nahin"],
    ["The vegetables are fresh","ତରକାରୀ ତାଜା","Tarakari taja"],
    ["I want some pickle","ମୋତେ ଆଚାର ଦରକାର","Mote achara darkar"],
    ["Drink water after eating","ଖାଇବା ପରେ ପାଣି ପିଅ","Khaiba pare pani pia"],
    ["The rice is not cooked properly","ଭାତ ଠିକରେ ରାନ୍ଧି ହୋଇନାହିଁ","Bhata thik re randhi hoinahin"],
    ["I am full now","ମୋ ପେଟ ଭରିଗଲା","Mo peta bharigala"],
    ["Let's have tea after lunch","ଖାଇବା ପରେ ଚା ପିଇବା","Khaiba pare cha piiba"],
    ["I will cook dinner tonight","ଆଜି ରାତିରେ ମୁଁ ରାନ୍ଧିବି","Aji ratire mun randhibi"]
]
L[651] = [
    ["What is your hobby?","ଆପଣଙ୍କ ଶୌଖ କଣ?","Apananka shoukha kana?"],
    ["I like painting","ମୋତେ ଚିତ୍ର ଆଙ୍କିବା ଭଲ ଲାଗେ","Mote chitra ankiba bhala lage"],
    ["I joined a music class","ମୁଁ ସଙ୍ଗୀତ କ୍ଲାସରେ ଯୋଗ ଦେଲି","Mun sangita class re yoga deli"],
    ["Dancing is fun","ନାଚ ବହୁତ ମଜା","Nacha bahut maja"],
    ["I play guitar in my free time","ଖାଲି ସମୟରେ ମୁଁ ଗିଟାର ବଜାଏ","Khali samayare mun guitar bajae"],
    ["She teaches classical dance","ସେ ସାସ୍ତ୍ରୀୟ ନୃତ୍ୟ ଶିଖାନ୍ତି","Se shastriya nrutya shikhanti"],
    ["I want to learn singing","ମୁଁ ଗୀତ ଶିଖିବାକୁ ଚାହେଁ","Mun gita shikhbaku chahen"],
    ["The class is every Saturday","କ୍ଲାସ ପ୍ରତି ଶନିବାର","Class prati shanibar"],
    ["I love reading books","ମୋତେ ବହି ପଢ଼ିବା ଭଲ ଲାଗେ","Mote bahi padhiba bhala lage"],
    ["Gardening is relaxing","ବଗିଚା କାମ ଶାନ୍ତି ଦେଏ","Bagicha kama shanti dee"],
    ["Photography is my passion","ଫଟୋଗ୍ରାଫି ମୋ ନିଶା","Photography mo nisha"],
    ["I swim every morning","ମୁଁ ପ୍ରତିଦିନ ସକାଳେ ପହଁରେ","Mun pratidina sakale pahanre"],
    ["Cooking new dishes is exciting","ନୂଆ ଖାଦ୍ୟ ରାନ୍ଧିବା ରୋମାଞ୍ଚକର","Nua khadya randhiba romanchakara"],
    ["I collect old coins","ମୁଁ ପୁରୁଣା ମୁଦ୍ରା ସଂଗ୍ରହ କରେ","Mun puruna mudra sangraha kare"],
    ["Everyone should have a hobby","ସମସ୍ତଙ୍କର ଗୋଟିଏ ଶୌଖ ଥିବା ଉଚିତ","Samastankara gotie shoukha thiba uchita"],
    ["Hobbies reduce stress","ଶୌଖ ଚାପ କମାଏ","Shoukha chapa kamae"],
    ["I enjoy my hobby class","ମୁଁ ଶୌଖ କ୍ଲାସ ଉପଭୋଗ କରେ","Mun shoukha class upabhoga kare"],
    ["Odissi dance is world famous","ଓଡ଼ିଶୀ ନୃତ୍ୟ ବିଶ୍ୱ ପ୍ରସିଦ୍ଧ","Odissi nrutya bishwa prasiddha"]
]
L[652] = [
    ["Please help me","ଦୟାକରି ମୋତେ ସାହାଯ୍ୟ କରନ୍ତୁ","Dayakari mote sahayya karantu"],
    ["I don't understand","ମୁଁ ବୁଝୁନାହିଁ","Mun bujhunahin"],
    ["Please say that again","ଦୟାକରି ଆଉ ଥରେ କୁହନ୍ତୁ","Dayakari au thare kuhantu"],
    ["I am sorry","ମୁଁ ଦୁଃଖିତ","Mun dukhita"],
    ["It's okay, no problem","ଠିକ ଅଛି, କୌଣସି ସମସ୍ୟା ନାହିଁ","Thik achhi, kounasi samasya nahin"],
    ["Thank you very much","ବହୁତ ଧନ୍ୟବାଦ","Bahut dhanyabad"],
    ["What is the price?","ଦାମ କେତେ?","Dama kete?"],
    ["I need water","ମୋତେ ପାଣି ଦରକାର","Mote pani darkar"],
    ["Where is the bathroom?","ବାଥରୁମ କେଉଁଠି?","Bathroom keunthi?"],
    ["I am lost","ମୁଁ ରାସ୍ତା ହରାଇଛି","Mun rasta haraichhi"],
    ["Can you speak slowly?","ଆପଣ ଧୀରେ କହିପାରିବେ?","Apana dhire kahipare?"],
    ["I am a student","ମୁଁ ଜଣେ ଛାତ୍ର","Mun jane chhatra"],
    ["I am learning Odia","ମୁଁ ଓଡ଼ିଆ ଶିଖୁଛି","Mun Odia shikhuchhi"],
    ["This is beautiful","ଏହା ସୁନ୍ଦର","Eha sundar"],
    ["Be careful","ସାବଧାନ ରହନ୍ତୁ","Sabadhan rahantu"],
    ["Come quickly","ଶୀଘ୍ର ଆସନ୍ତୁ","Shighra asantu"],
    ["I will try","ମୁଁ ଚେଷ୍ଟା କରିବି","Mun cheshta karibi"],
    ["God bless you","ଭଗବାନ ଆପଣଙ୍କୁ ଆଶୀର୍ବାଦ କରନ୍ତୁ","Bhagaban apananku ashirbad karantu"]
]
L[653] = [
    ["What happened?","କଣ ହେଲା?","Kana hela?"],
    ["Nothing happened","କିଛି ହୋଇନାହିଁ","Kichhi hoinahin"],
    ["I am happy today","ଆଜି ମୁଁ ଖୁସି","Aji mun khusi"],
    ["I am tired","ମୁଁ ଥକିଗଲି","Mun thakigali"],
    ["Let's go together","ଆସ ଏକାଠି ଯିବା","Asa ekathi yiba"],
    ["Don't worry","ଚିନ୍ତା କର ନାହିଁ","Chinta kara nahin"],
    ["I will come back soon","ମୁଁ ଶୀଘ୍ର ଫେରିବି","Mun shighra pheribi"],
    ["Take care of yourself","ନିଜକୁ ସମ୍ଭାଳ","Nijaku sambhala"],
    ["Have a good day","ଶୁଭ ଦିନ ହେଉ","Shubha dina heu"],
    ["It is very nice","ଏହା ବହୁତ ଭଲ","Eha bahut bhala"],
    ["I don't know","ମୁଁ ଜାଣେ ନାହିଁ","Mun jane nahin"],
    ["Do you know?","ତୁମେ ଜାଣ?","Tume jana?"],
    ["Tell me the truth","ମୋତେ ସତ କୁହ","Mote sata kuha"],
    ["I promise","ମୁଁ ପ୍ରତିଜ୍ଞା କରୁଛି","Mun pratijna karuchhi"],
    ["Never give up","କେବେ ହାର ମାନ ନାହିଁ","Kebe hara mana nahin"],
    ["Time heals everything","ସମୟ ସବୁ ଭଲ କରେ","Samaya sabu bhala kare"],
    ["Believe in yourself","ନିଜ ଉପରେ ବିଶ୍ୱାସ ରଖ","Nija upare bishwasa rakha"],
    ["Hard work pays off","ପରିଶ୍ରମ ଫଳ ଦିଏ","Parishrama phala die"]
]
L[654] = [
    ["Can you teach me Odia?","ଆପଣ ମୋତେ ଓଡ଼ିଆ ଶିଖାଇ ପାରିବେ?","Apana mote Odia shikhai parebe?"],
    ["Yes, let's start with greetings","ହଁ, ନମସ୍କାରରୁ ଆରମ୍ଭ କରିବା","Han, namaskaarru arambha kariba"],
    ["How do you say 'water' in Odia?","ଓଡ଼ିଆରେ water କଣ କୁହନ୍ତି?","Odia re water kana kuhanti?"],
    ["Water is called 'pani' in Odia","ଓଡ଼ିଆରେ water କୁ ପାଣି କୁହନ୍ତି","Odia re water ku pani kuhanti"],
    ["Practice speaking every day","ପ୍ରତିଦିନ କହିବା ଅଭ୍ୟାସ କରନ୍ତୁ","Pratidina kahiba abhyasa karantu"],
    ["Talk to Odia speakers","ଓଡ଼ିଆ ଭାଷୀଙ୍କ ସହ କଥା ହୁଅନ୍ତୁ","Odia bhashinka saha katha huantu"],
    ["Listen to Odia songs","ଓଡ଼ିଆ ଗୀତ ଶୁଣନ୍ତୁ","Odia gita shunantu"],
    ["Read Odia books","ଓଡ଼ିଆ ବହି ପଢ଼ନ୍ତୁ","Odia bahi padhantu"],
    ["Write sentences in Odia","ଓଡ଼ିଆରେ ବାକ୍ୟ ଲେଖନ୍ତୁ","Odia re bakya lekhantu"],
    ["Repeat after me","ମୋ ପରେ କୁହନ୍ତୁ","Mo pare kuhantu"],
    ["You are improving quickly","ଆପଣ ଶୀଘ୍ର ଉନ୍ନତି କରୁଛନ୍ତି","Apana shighra unnati karuchanti"],
    ["Don't be afraid to make mistakes","ଭୁଲ କରିବାକୁ ଭୟ କରନ୍ତୁ ନାହିଁ","Bhul karibaku bhaya karantu nahin"],
    ["Language learning takes time","ଭାଷା ଶିଖିବାକୁ ସମୟ ଲାଗେ","Bhasha shikhbaku samaya lage"],
    ["You speak Odia very well now","ଆପଣ ଏବେ ଭଲ ଓଡ଼ିଆ କହନ୍ତି","Apana ebe bhala Odia kahanti"],
    ["Keep practising daily","ପ୍ରତିଦିନ ଅଭ୍ୟାସ କରନ୍ତୁ","Pratidina abhyasa karantu"],
    ["I enjoy learning this language","ମୋତେ ଏହି ଭାଷା ଶିଖିବା ଭଲ ଲାଗେ","Mote ehi bhasha shikhiba bhala lage"],
    ["Odia is a beautiful language","ଓଡ଼ିଆ ଏକ ସୁନ୍ଦର ଭାଷା","Odia eka sundar bhasha"],
    ["Odia is one of the classical languages","ଓଡ଼ିଆ ଏକ ଶାସ୍ତ୍ରୀୟ ଭାଷା","Odia eka shastriya bhasha"]
]
L[655] = [
    ["The sun rises in the east","ସୂର୍ଯ୍ୟ ପୂର୍ବରେ ଉଦୟ ହୁଏ","Surya purbare udaya hue"],
    ["The bird is sitting on the tree","ଚଢ଼େଇ ଗଛ ଉପରେ ବସିଛି","Chadei gachha upare basichhi"],
    ["The river flows through the village","ନଦୀ ଗାଁ ମଧ୍ୟ ଦେଇ ବହୁଛି","Nadi gaan madhya dei bahuchhi"],
    ["Children play in the field","ପିଲାମାନେ ମଇଦାନରେ ଖେଳନ୍ତି","Pilamane maidanare khelanti"],
    ["The farmer ploughs the field","ଚାଷୀ ଜମିରେ ହଳ ଚଲାଏ","Chashi jamire hala chalae"],
    ["I read a book every day","ମୁଁ ପ୍ରତିଦିନ ବହି ପଢ଼େ","Mun pratidina bahi padhe"],
    ["She sings very well","ସେ ବହୁତ ଭଲ ଗୀତ ଗାଏ","Se bahut bhala gita gae"],
    ["The cow gives milk","ଗାଈ କ୍ଷୀର ଦିଏ","Gai kshira die"],
    ["We go to school","ଆମେ ସ୍କୁଲ ଯାଉ","Ame skul yau"],
    ["The dog is barking","କୁକୁର ଭୁକୁଛି","Kukura bhukuchhi"],
    ["Mother is cooking food","ମା ଖାଦ୍ୟ ରାନ୍ଧୁଛନ୍ତି","Maa khadya randhuchanti"],
    ["Father is working in the field","ବାପା ଜମିରେ କାମ କରୁଛନ୍ତି","Bapa jamire kama karuchanti"],
    ["The sky is very blue","ଆକାଶ ବହୁତ ନୀଳ","Akasha bahut nila"],
    ["I like mangoes very much","ମୋତେ ଆମ୍ବ ବହୁତ ଭଲ ଲାଗେ","Mote amba bahut bhala lage"],
    ["The flower is red","ଫୁଲ ଲାଲ","Phula lala"],
    ["The fish lives in water","ମାଛ ପାଣିରେ ରହେ","Machha panire rahe"],
    ["My house is near the river","ମୋ ଘର ନଦୀ ପାଖରେ","Mo ghara nadi pakhare"],
    ["The moon comes at night","ରାତିରେ ଚନ୍ଦ୍ର ଦେଖାଯାଏ","Ratire chandra dekhayae"]
]
L[656] = [
    ["The book is on the table","ବହି ଟେବୁଲ ଉପରେ","Bahi table upare"],
    ["The cat is under the bed","ବିଲେଇ ବିଛଣା ତଳେ","Bilei bichhana tale"],
    ["The ball is inside the box","ବଲ ବାକ୍ସ ଭିତରେ","Ball box bhitare"],
    ["The bird flew above the house","ଚଢ଼େଇ ଘର ଉପରେ ଉଡ଼ିଲା","Chadei ghara upare udila"],
    ["The tree is behind the school","ଗଛ ସ୍କୁଲ ପଛରେ","Gachha skul pachhare"],
    ["The market is in front of the temple","ବଜାର ମନ୍ଦିର ଆଗରେ","Bajar mandira agare"],
    ["He is standing between two trees","ସେ ଦୁଇ ଗଛ ମଝିରେ ଠିଆ","Se dui gachha majhire thia"],
    ["The pen is beside the notebook","କଲମ ଖାତା ପାଖରେ","Kalama khata pakhare"],
    ["Walk along the river","ନଦୀ ଧାରରେ ଚାଲ","Nadi dharare chala"],
    ["The shop is across the road","ଦୋକାନ ରାସ୍ତା ଆଡ଼େ","Dokana rasta ade"],
    ["Come towards me","ମୋ ଆଡ଼କୁ ଆସ","Mo adaku asa"],
    ["Go away from here","ଏଠାରୁ ଦୂରକୁ ଯାଅ","Etharu duraku yaa"],
    ["The picture is on the wall","ଛବି କାନ୍ଥରେ ଅଛି","Chhabi kanthare achhi"],
    ["The water is in the pot","ପାଣି ହାଣ୍ଡିରେ ଅଛି","Pani handire achhi"],
    ["He jumped over the fence","ସେ ବାଡ଼ ଉପରୁ ଡେଇଁଲା","Se bada uparu deinla"],
    ["Sit near me","ମୋ ପାଖରେ ବସ","Mo pakhare basa"],
    ["The child is among the flowers","ପିଲା ଫୁଲ ମଝିରେ","Pila phul majhire"],
    ["We walked through the forest","ଆମେ ଜଙ୍ଗଲ ମଧ୍ୟ ଦେଇ ଚାଲିଲୁ","Ame jangal madhya dei chalilu"]
]
L[657] = [
    ["Let me tell you a funny story","ମୋତେ ଗୋଟିଏ ହସ ଗପ କହିବାକୁ ଦିଅ","Mote gotie hasa gapa kahibaku dia"],
    ["A boy asked his father for money","ପୁଅ ବାପାଙ୍କୁ ଟଙ୍କା ମାଗିଲା","Pua bapanku tanka magila"],
    ["Father said, money doesn't grow on trees","ବାପା କହିଲେ, ଟଙ୍କା ଗଛରେ ଫଳେ ନାହିଁ","Bapa kahile, tanka gachhare phale nahin"],
    ["The boy replied, then why do banks have branches?","ପୁଅ କହିଲା, ତେବେ ବ୍ୟାଙ୍କର ବ୍ରାଞ୍ଚ ଅଛି କାହିଁକି?","Pua kahila, tebe bankara branch achhi kahinki?"],
    ["Everyone laughed!","ସମସ୍ତେ ହସିଲେ!","Samaste hasile!"],
    ["Teacher asked, what comes after Tuesday?","ଶିକ୍ଷକ ପଚାରିଲେ, ମଙ୍ଗଳବାର ପରେ କଣ ଆସେ?","Shikshaka pacharile, mangalbar pare kana ase?"],
    ["Student said, Wednesday!","ଛାତ୍ର କହିଲା, ବୁଧବାର!","Chhatra kahila, budhbar!"],
    ["Teacher said, I meant after 2?","ଶିକ୍ଷକ କହିଲେ, ଦୁଇ ପରେ?","Shikshaka kahile, dui pare?"],
    ["Student replied, 3!","ଛାତ୍ର କହିଲା, ତିନି!","Chhatra kahila, tini!"],
    ["Laughter is the best medicine","ହସ ସର୍ବଶ୍ରେଷ୍ଠ ଔଷଧ","Hasa sarbashreshtha aushadh"],
    ["Always smile and be happy","ସବୁବେଳେ ହସ ଓ ଖୁସି ରୁହ","Sabubele hasa o khusi ruha"],
    ["A man went to buy a clock","ଜଣେ ଲୋକ ଘଣ୍ଟା କିଣିବାକୁ ଗଲେ","Jane loka ghanta kinibaku gale"],
    ["Does this clock work well?","ଏହି ଘଣ୍ଟା ଭଲ ଚାଲେ?","Ehi ghanta bhala chale?"],
    ["Shopkeeper said, it can't walk, no legs!","ଦୋକାନୀ କହିଲେ, ଚାଲିବ କିପରି, ଗୋଡ଼ ନାହିଁ!","Dokani kahile, chaliba kipari, goda nahin!"],
    ["Did you like the joke?","ହସ ଗପ ଭଲ ଲାଗିଲା?","Hasa gapa bhala lagila?"],
    ["Share jokes with friends","ବନ୍ଧୁଙ୍କ ସହ ହସ ଗପ କୁହ","Bandhunka saha hasa gapa kuha"],
    ["Humor keeps life happy","ହାସ୍ୟ ଜୀବନକୁ ଖୁସି ରଖେ","Hasya jibanaku khusi rakhe"],
    ["Odia jokes are very funny","ଓଡ଼ିଆ ହସ ଗପ ବହୁତ ମଜା","Odia hasa gapa bahut maja"]
]
L[658] = [
    ["Knowledge is power","ଜ୍ଞାନ ହେଉଛି ଶକ୍ତି","Jnana heuchhi shakti"],
    ["Unity is strength","ଏକତା ହେଉଛି ଶକ୍ତି","Ekata heuchhi shakti"],
    ["Education is the key to success","ଶିକ୍ଷା ସଫଳତାର ଚାବି","Shiksha saphalatara chabi"],
    ["Respect your elders","ବଡ଼ଙ୍କୁ ସମ୍ମାନ କର","Badanku sammana kara"],
    ["Love your language","ନିଜ ଭାଷାକୁ ଭଲ ପାଅ","Nija bhashaku bhala paa"],
    ["Nature is our mother","ପ୍ରକୃତି ଆମ ମା","Prakruti ama maa"],
    ["Honesty is the best policy","ସଚ୍ଚୋଟତା ସର୍ବଶ୍ରେଷ୍ଠ ନୀତି","Sachchotata sarbashreshtha niti"],
    ["Work hard, dream big","ଦୃଢ଼ ପରିଶ୍ରମ କର, ବଡ଼ ସ୍ୱପ୍ନ ଦେଖ","Drudha parishram kara, bada swapna dekha"],
    ["Together we can achieve anything","ଏକାଠି ଆମେ ସବୁ କରିପାରିବା","Ekathi ame sabu karipariба"],
    ["Save water, save life","ପାଣି ବଞ୍ଚାଅ, ଜୀବନ ବଞ୍ଚାଅ","Pani banchaa, jibana banchaa"],
    ["Plant trees for the future","ଭବିଷ୍ୟତ ପାଇଁ ଗଛ ଲଗାଅ","Bhabishyata pain gachha lagaa"],
    ["Every child has the right to education","ପ୍ରତ୍ୟେକ ଶିଶୁର ଶିକ୍ଷା ଅଧିକାର ଅଛି","Pratyeka shishura shiksha adhikara achhi"],
    ["A smile costs nothing","ହସର କୌଣସି ଦାମ ନାହିଁ","Hasara kounasi dama nahin"],
    ["Actions speak louder than words","କାମ କଥା ଠାରୁ ଜୋରରେ କହେ","Kama katha tharu jorare kahe"],
    ["Peace begins with a smile","ଶାନ୍ତି ହସରୁ ଆରମ୍ଭ ହୁଏ","Shanti hasaru arambha hue"],
    ["Read daily, grow daily","ପ୍ରତିଦିନ ପଢ଼, ପ୍ରତିଦିନ ବଢ଼","Pratidina padha, pratidina badha"],
    ["Your language is your identity","ତୁମ ଭାଷା ତୁମ ପରିଚୟ","Tuma bhasha tuma parichaya"],
    ["Odia language is our pride","ଓଡ଼ିଆ ଭାଷା ଆମ ଗର୍ବ","Odia bhasha ama garba"]
]
L[659] = [
    ["I use social media every day","ମୁଁ ପ୍ରତିଦିନ ସୋସିଆଲ ମିଡ଼ିଆ ବ୍ୟବହାର କରେ","Mun pratidina social media byabahara kare"],
    ["I have accounts on Facebook and Instagram","ମୋର ଫେସବୁକ ଓ ଇନଷ୍ଟାଗ୍ରାମ ଆକାଉଣ୍ଟ ଅଛି","Mora Facebook o Instagram account achhi"],
    ["I share photos of my village","ମୁଁ ମୋ ଗାଁର ଫଟୋ ସେୟାର କରେ","Mun mo gaanra photo share kare"],
    ["Social media connects people","ସୋସିଆଲ ମିଡ଼ିଆ ଲୋକଙ୍କୁ ଯୋଡ଼େ","Social media lokanku yode"],
    ["I watch Odia videos online","ମୁଁ ଅନଲାଇନରେ ଓଡ଼ିଆ ଭିଡିଓ ଦେଖେ","Mun online re Odia video dekhe"],
    ["Don't share personal information","ବ୍ୟକ୍ତିଗତ ସୂଚନା ସେୟାର କର ନାହିଁ","Byaktigata suchana share kara nahin"],
    ["Fake news is dangerous","ଝୁଠ ଖବର ବିପଦଜନକ","Jhutha khabara bipadajanak"],
    ["Use social media wisely","ବୁଦ୍ଧିମତ୍ତାରେ ସୋସିଆଲ ମିଡ଼ିଆ ବ୍ୟବହାର କର","Buddhimattare social media byabahara kara"],
    ["Too much screen time is bad","ଅଧିକ ସ୍କ୍ରିନ ସମୟ ଖରାପ","Adhik screen samaya kharap"],
    ["I post in Odia script","ମୁଁ ଓଡ଼ିଆ ଲିପିରେ ପୋଷ୍ଟ କରେ","Mun Odia lipire post kare"],
    ["Many Odia groups are on Facebook","ଫେସବୁକରେ ବହୁ ଓଡ଼ିଆ ଗ୍ରୁପ ଅଛି","Facebook re bahu Odia group achhi"],
    ["I read Odia news online","ମୁଁ ଅନଲାଇନରେ ଓଡ଼ିଆ ଖବର ପଢ଼େ","Mun online re Odia khabara padhe"],
    ["Children should limit screen time","ପିଲାମାନେ ସ୍କ୍ରିନ ସମୟ କମାଇବା ଉଚିତ","Pilamane screen samaya kamaiba uchita"],
    ["Be careful of online scams","ଅନଲାଇନ ଠକେଇରୁ ସାବଧାନ ରୁହ","Online thakeiru sabadhan ruha"],
    ["Social media is good for learning","ସୋସିଆଲ ମିଡ଼ିଆ ଶିଖିବାକୁ ଭଲ","Social media shikhbaku bhala"],
    ["Don't believe everything online","ଅନଲାଇନରେ ସବୁ ବିଶ୍ୱାସ କର ନାହିଁ","Online re sabu bishwasa kara nahin"],
    ["Use the internet for good purposes","ଭଲ କାମ ପାଇଁ ଇଣ୍ଟରନେଟ ବ୍ୟବହାର କର","Bhala kama pain internet byabahara kara"],
    ["I made many friends online","ମୁଁ ଅନଲାଇନରେ ବହୁ ବନ୍ଧୁ ପାଇଲି","Mun online re bahu bandhu paili"]
]
L[660] = [
    ["Did you see the eclipse today?","ଆଜି ଗ୍ରହଣ ଦେଖିଲ?","Aji grahana dekhila?"],
    ["Yes, it was a solar eclipse","ହଁ, ସୂର୍ଯ୍ୟ ଗ୍ରହଣ ଥିଲା","Han, surya grahana thila"],
    ["The sun was covered by the moon","ସୂର୍ଯ୍ୟକୁ ଚନ୍ଦ୍ର ଢାଙ୍କି ଦେଲା","Suryaku chandra dhanki dela"],
    ["It became dark in daytime","ଦିନରେ ଅନ୍ଧାର ହୋଇଗଲା","Dinare andhara hoigala"],
    ["Don't look at the eclipse directly","ଗ୍ରହଣକୁ ସିଧା ଦେଖ ନାହିଁ","Grahanaku sidha dekha nahin"],
    ["Use special glasses to watch","ଦେଖିବାକୁ ବିଶେଷ ଚଷମା ବ୍ୟବହାର କର","Dekhbaku bishesha chashma byabahara kara"],
    ["The eclipse lasted for two hours","ଗ୍ରହଣ ଦୁଇ ଘଣ୍ଟା ଚାଲିଲା","Grahana dui ghanta chalila"],
    ["It is a natural phenomenon","ଏହା ଏକ ପ୍ରାକୃତିକ ଘଟଣା","Eha eka prakrutik ghatana"],
    ["Scientists study eclipses","ବୈଜ୍ଞାନିକମାନେ ଗ୍ରହଣ ଅଧ୍ୟୟନ କରନ୍ତି","Baijnanikamane grahana adhyayana karanti"],
    ["The next eclipse will come next year","ପରବର୍ତ୍ତୀ ଗ୍ରହଣ ଆସନ୍ତା ବର୍ଷ ଆସିବ","Parabarti grahana asanta barsha asiba"],
    ["A lunar eclipse happens at night","ଚନ୍ଦ୍ର ଗ୍ରହଣ ରାତିରେ ହୁଏ","Chandra grahana ratire hue"],
    ["Old people tell stories about eclipses","ବଡ଼ ଲୋକ ଗ୍ରହଣ ବିଷୟରେ ଗପ କୁହନ୍ତି","Bada loka grahana bishayare gapa kuhanti"],
    ["I took photos of the eclipse","ମୁଁ ଗ୍ରହଣର ଫଟୋ ତୋଳିଲି","Mun grahanara photo tolili"],
    ["It was a wonderful experience","ସେ ଏକ ଅଦ୍ଭୁତ ଅନୁଭବ ଥିଲା","Se eka adbhut anubhaba thila"],
    ["The birds went quiet during the eclipse","ଗ୍ରହଣ ସମୟରେ ଚଢ଼େଇ ଚୁପ ହୋଇଗଲେ","Grahana samayare chadei chup hoigale"],
    ["Eclipse is not something to fear","ଗ୍ରହଣ ଡରିବା କଥା ନୁହେଁ","Grahana dariba katha nuhen"],
    ["Science explains everything","ବିଜ୍ଞାନ ସବୁ ବୁଝାଏ","Bijnana sabu bujhae"],
    ["Nature is full of wonders","ପ୍ରକୃତି ଆଶ୍ଚର୍ଯ୍ୟରେ ଭରା","Prakruti ashcharyare bhara"]
]
L[661] = [
    ["Happy Women's Day!","ସୁଖ ନାରୀ ଦିବସ!","Sukha Nari Dibas!"],
    ["Women are the strength of society","ନାରୀ ସମାଜର ଶକ୍ତି","Nari samajara shakti"],
    ["We celebrate Women's Day on March 8","ଆମେ ମାର୍ଚ ୮ ରେ ନାରୀ ଦିବସ ପାଳନ କରୁ","Ame March 8 re Nari Dibas palana karu"],
    ["Every girl should go to school","ପ୍ରତ୍ୟେକ ଝିଅ ସ୍କୁଲ ଯିବା ଉଚିତ","Pratyeka jhia skul yiba uchita"],
    ["Women can do anything","ନାରୀ ସବୁ କରିପାରେ","Nari sabu karipare"],
    ["Respect all women","ସମସ୍ତ ନାରୀଙ୍କୁ ସମ୍ମାନ କର","Samasta narinku sammana kara"],
    ["My mother is my hero","ମୋ ମା ମୋ ନାୟକ","Mo maa mo nayak"],
    ["Women work twice as hard","ନାରୀ ଦୁଇଗୁଣ ପରିଶ୍ରମ କରନ୍ତି","Nari duiguna parishrama karanti"],
    ["Girls should be educated","ଝିଅମାନେ ଶିକ୍ଷିତ ହେବା ଉଚିତ","Jhiamane shikshita heba uchita"],
    ["Women are leaders too","ନାରୀ ମଧ୍ୟ ନେତା","Nari madhya neta"],
    ["Equal rights for men and women","ପୁରୁଷ ଓ ନାରୀଙ୍କ ସମାନ ଅଧିକାର","Purusha o narinka samana adhikara"],
    ["Odia women are very hardworking","ଓଡ଼ିଆ ମହିଳା ବହୁତ ପରିଶ୍ରମୀ","Odia mahila bahut parishramee"],
    ["Support women's education","ନାରୀ ଶିକ୍ଷାକୁ ସମର୍ଥନ କର","Nari shikshaku samarthana kara"],
    ["Women are the backbone of the family","ନାରୀ ପରିବାରର ମୂଳ ଆଧାର","Nari paribarara mul adhara"],
    ["Let us all celebrate together","ଆସନ୍ତୁ ସମସ୍ତେ ଏକାଠି ପାଳନ କରିବା","Asantu samaste ekathi palana kariba"],
    ["Women bring change in society","ନାରୀ ସମାଜରେ ପରିବର୍ତ୍ତନ ଆଣନ୍ତି","Nari samajare paribartana ananti"],
    ["Salute to all the women!","ସମସ୍ତ ନାରୀଙ୍କୁ ନମସ୍କାର!","Samasta narinku namaskaar!"],
    ["Women empower the nation","ନାରୀ ଦେଶକୁ ସଶକ୍ତ କରନ୍ତି","Nari deshaku sashakta karanti"]
]
L[662] = [
    ["Why are you shouting?","କାହିଁକି ଚିତ୍କାର କରୁଛ?","Kahinki chitkara karuchha?"],
    ["Please stop fighting","ଦୟାକରି ଝଗଡ଼ା ବନ୍ଦ କର","Dayakari jhagada banda kara"],
    ["You always blame me","ତୁମେ ସବୁବେଳେ ମୋତେ ଦୋଷ ଦିଅ","Tume sabubele mote dosha dia"],
    ["I didn't do anything wrong","ମୁଁ କିଛି ଭୁଲ କରିନାହିଁ","Mun kichhi bhul karinahin"],
    ["Let's talk calmly","ଆସ ଶାନ୍ତରେ କଥା ହେବା","Asa shantare katha heba"],
    ["Don't raise your voice","ସ୍ୱର ଉଠାଅ ନାହିଁ","Swara uthaa nahin"],
    ["I am sorry for what I said","ମୁଁ କହିଥିବା ପାଇଁ ଦୁଃଖିତ","Mun kahithiba pain dukhita"],
    ["It was a misunderstanding","ସେ ଏକ ଭୁଲବୁଝାମଣା ଥିଲା","Se eka bhulbujhamana thila"],
    ["We should not fight","ଆମେ ଝଗଡ଼ା କରିବା ଉଚିତ ନୁହେଁ","Ame jhagada kariba uchita nuhen"],
    ["Fighting hurts everyone","ଝଗଡ଼ା ସମସ୍ତଙ୍କୁ ଦୁଃଖ ଦିଏ","Jhagada samastanku dukha die"],
    ["Forgive me please","ଦୟାକରି ମୋତେ କ୍ଷମା କର","Dayakari mote kshama kara"],
    ["I forgive you","ମୁଁ ତୋତେ କ୍ଷମା କଲି","Mun tote kshama kali"],
    ["Let's not argue about this","ଏ ବିଷୟରେ ତର୍କ ନ କରିବା","E bishayare tarka na kariba"],
    ["Children get scared when we fight","ଆମେ ଝଗଡ଼ା କଲେ ପିଲାମାନେ ଡରନ୍ତି","Ame jhagada kale pilamane daranti"],
    ["We should solve problems peacefully","ଆମେ ଶାନ୍ତିରେ ସମସ୍ୟା ସମାଧାନ କରିବା ଉଚିତ","Ame shantire samasya samadhan kariba uchita"],
    ["I will try to be more patient","ମୁଁ ଅଧିକ ଧୈର୍ଯ୍ୟ ଧରିବାକୁ ଚେଷ୍ଟା କରିବି","Mun adhika dhairya dharibaku cheshta karibi"],
    ["Family should stay united","ପରିବାର ଏକ ଥିବା ଉଚିତ","Paribar eka thiba uchita"],
    ["Let's hug and make up","ଆସ ଆଲିଙ୍ଗନ କରି ଭଲ ହେବା","Asa alingana kari bhala heba"]
]

for ch in d:
    if ch['id'] in L:
        ch['blocks'] = [{"type":"table","columns":["English","Odia","Transliteration"],"rows":L[ch['id']]}]
open('data_odia.json','w',encoding='utf-8').write(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
print('Odia S5b (642-662) populated - 21 lessons')
