import json

DATA_FILE = "data_odia.json"

lessons = {
    561: {
        "url": "\"Because...\" Reason Patterns in Odia",
        "rows": [
            ["Because it is raining, I will stay home.", "ବର୍ଷା ହେଉଥିବାରୁ, ମୁଁ ଘରେ ରହିବି।", "Barshaa heuthihaaru, mun ghare rahibi."],
            ["Because he was late, he missed the bus.", "ସେ ଡେରି ହୋଇଥିବାରୁ, ବସ୍ ଛାଡ଼ି ଦେଲା।", "Se deri hoithibaaru, bas chhaadi delaa."],
            ["Because she studied hard, she passed.", "ସେ କଠିନ ପଢ଼ିଥିବାରୁ, ପାସ୍ କଲା।", "Se kathina padhithibaaru, paas kalaa."],
            ["Because of the heat, we stayed inside.", "ଗରମ ଯୋଗୁଁ, ଆମେ ଭିତରେ ରହିଲୁ।", "Garama yogun, aame bhitare rahilu."],
            ["Because I was hungry, I ate early.", "ମୁଁ ଭୋକିଲା ଥିବାରୁ, ଜଲଦି ଖାଇଲି।", "Mun bhokila thibaaru, jaladi khaaili."],
            ["Because the road was bad, we walked slowly.", "ରାସ୍ତା ଖରାପ ଥିବାରୁ, ଆମେ ଧୀରେ ଚାଲିଲୁ।", "Raastaa kharaap thibaaru, aame dhire chaalilu."],
            ["Because you helped me, I succeeded.", "ତୁମେ ମୋତେ ସାହାଯ୍ୟ କରିଥିବାରୁ, ମୁଁ ସଫଳ ହେଲି।", "Tume mote saahajya karithibaaru, mun saphala heli."],
            ["Because of illness, he could not come.", "ଅସୁସ୍ଥତା ଯୋଗୁଁ, ସେ ଆସି ପାରିଲା ନାହିଁ।", "Asusthata yogun, se aasi paarilaa naahiin."],
            ["Because the shop was closed, I returned.", "ଦୋକାନ ବନ୍ଦ ଥିବାରୁ, ମୁଁ ଫେରିଆସିଲି।", "Dokaan banda thibaaru, mun pheriaasili."],
            ["Because it was dark, I turned on the light.", "ଅନ୍ଧାର ଥିବାରୁ, ମୁଁ ଲାଇଟ୍ ଜଳାଇଲି।", "Andhaar thibaaru, mun laait jalaaili."],
            ["Because of the festival, schools are closed.", "ପର୍ବ ଯୋଗୁଁ, ସ୍କୁଲ ବନ୍ଦ ଅଛି।", "Parba yogun, skul banda achhi."],
            ["Because he lied, nobody trusts him.", "ସେ ମିଛ କହିଥିବାରୁ, କେହି ତାକୁ ବିଶ୍ୱାସ କରନ୍ତି ନାହିଁ।", "Se michha kahithibaaru, kehi taaku bishwaas karanti naahiin."],
            ["Because I love you, I am telling you the truth.", "ମୁଁ ତୁମକୁ ଭଲ ପାଉଥିବାରୁ, ସତ କହୁଛି।", "Mun tumaku bhala paauthibaaru, sata kahuchhi."],
            ["Because of traffic, we were delayed.", "ଟ୍ରାଫିକ ଯୋଗୁଁ, ଆମେ ଡେରି ହେଲୁ।", "Traffic yogun, aame deri helu."],
            ["Because the water was dirty, we did not drink.", "ପାଣି ମଇଳା ଥିବାରୁ, ଆମେ ପିଇଲୁ ନାହିଁ।", "Paani maila thibaaru, aame piilu naahiin."],
            ["Because of your advice, I made the right decision.", "ତୁମ ପରାମର୍ଶ ଯୋଗୁଁ, ମୁଁ ଠିକ୍ ନିଷ୍ପତ୍ତି ନେଲି।", "Tuma paraamarsha yogun, mun thik nishpatti neli."],
            ["Because the teacher was absent, there was no class.", "ଶିକ୍ଷକ ନ ଥିବାରୁ, କ୍ଲାସ ହେଲା ନାହିଁ।", "Shikshaka na thibaaru, class helaa naahiin."],
            ["Because of hard work, he became successful.", "କଠିନ ପରିଶ୍ରମ ଯୋଗୁଁ, ସେ ସଫଳ ହେଲା।", "Kathina parishrama yogun, se saphala helaa."],
        ]
    },
    562: {
        "url": "\"If...then...\" Conditional Patterns in Odia",
        "rows": [
            ["If it rains, then I will not go.", "ଯଦି ବର୍ଷା ହୁଏ, ତେବେ ମୁଁ ଯିବି ନାହିଁ।", "Jadi barshaa hue, tebe mun jibi naahiin."],
            ["If you study, then you will pass.", "ଯଦି ତୁମେ ପଢ଼, ତେବେ ପାସ ହେବ।", "Jadi tume padha, tebe paas heba."],
            ["If he comes, then we will go together.", "ଯଦି ସେ ଆସେ, ତେବେ ଆମେ ଏକାଠି ଯିବା।", "Jadi se aase, tebe aame ekaathi jibaa."],
            ["If you want, then I can help.", "ଯଦି ତୁମେ ଚାହଁ, ତେବେ ମୁଁ ସାହାଯ୍ୟ କରିପାରିବି।", "Jadi tume chaahan, tebe mun saahajya karipaaribii."],
            ["If the weather is good, then we will go out.", "ଯଦି ପାଗ ଭଲ ଥାଏ, ତେବେ ଆମେ ବାହାରକୁ ଯିବା।", "Jadi paag bhala thaae, tebe aame baaharaku jibaa."],
            ["If I had money, then I would buy a car.", "ଯଦି ମୋ ପାଖରେ ଟଙ୍କା ଥାଆନ୍ତା, ତେବେ ଗାଡ଼ି କିଣି ନେଇଥାନ୍ତି।", "Jadi mo paakhare tankaa thaaantaa, tebe gaadi kini neithanti."],
            ["If she calls, then tell her I am busy.", "ଯଦି ସେ ଫୋନ କରେ, ତେବେ କୁହ ମୁଁ ବ୍ୟସ୍ତ।", "Jadi se phone kare, tebe kuha mun byasta."],
            ["If you eat too much, then you will feel sick.", "ଯଦି ତୁମେ ଅଧିକ ଖାଅ, ତେବେ ଅସୁସ୍ଥ ଲାଗିବ।", "Jadi tume adhika khaao, tebe asustha laagiba."],
            ["If we leave now, then we will reach on time.", "ଯଦି ଆମେ ଏବେ ବାହାରିବା, ତେବେ ସମୟରେ ପହଞ୍ଚିବା।", "Jadi aame ebe baaharibaa, tebe samayare pahanchiba."],
            ["If you don't listen, then you will regret.", "ଯଦି ତୁମେ ନ ଶୁଣ, ତେବେ ପଛତାପ କରିବ।", "Jadi tume na shuna, tebe pachhatapa kariba."],
            ["If the price is low, then I will buy it.", "ଯଦି ଦାମ କମ ହୁଏ, ତେବେ ମୁଁ କିଣିବି।", "Jadi daam kama hue, tebe mun kinibi."],
            ["If you are free, then come to my house.", "ଯଦି ତୁମେ ଖାଲି ଅଛ, ତେବେ ମୋ ଘରକୁ ଆସ।", "Jadi tume khaali achha, tebe mo gharaku aasa."],
            ["If I were you, then I would not do this.", "ଯଦି ମୁଁ ତୁମ ଜାଗାରେ ଥାଆନ୍ତି, ତେବେ ଏହା କରନ୍ତି ନାହିଁ।", "Jadi mun tuma jaagaare thaaanti, tebe ehaa karanti naahiin."],
            ["If the train is late, then we will take a bus.", "ଯଦି ଟ୍ରେନ ଡେରି ହୁଏ, ତେବେ ଆମେ ବସ ନେବା।", "Jadi train deri hue, tebe aame bas nebaa."],
            ["If you practice daily, then you will improve.", "ଯଦି ତୁମେ ପ୍ରତିଦିନ ଅଭ୍ୟାସ କର, ତେବେ ଉନ୍ନତି ହେବ।", "Jadi tume pratidina abhyaas kara, tebe unnati heba."],
            ["If he apologizes, then I will forgive him.", "ଯଦି ସେ କ୍ଷମା ମାଗେ, ତେବେ ମୁଁ ତାକୁ କ୍ଷମା କରିବି।", "Jadi se kshamaa maage, tebe mun taaku kshamaa karibi."],
            ["If you need anything, then let me know.", "ଯଦି ତୁମର କିଛି ଦରକାର, ତେବେ ମୋତେ ଜଣାଅ।", "Jadi tumara kichhi darakaar, tebe mote janaao."],
            ["If we work together, then we will finish quickly.", "ଯଦି ଆମେ ଏକାଠି କାମ କରିବା, ତେବେ ଜଲଦି ସରିଯିବ।", "Jadi aame ekaathi kaama karibaa, tebe jaladi sarijiba."],
        ]
    },
    563: {
        "url": "\"Even though...\" Concessive Patterns in Odia",
        "rows": [
            ["Even though it was raining, he went out.", "ବର୍ଷା ହେଉଥିଲେ ବି, ସେ ବାହାରକୁ ଗଲା।", "Barshaa heuthile bi, se baaharaku galaa."],
            ["Even though she was tired, she kept working.", "ସେ ଥକିଥିଲେ ବି, କାମ ଜାରି ରଖିଲା।", "Se thakithile bi, kaama jaari rakhilaa."],
            ["Even though I told him, he didn't listen.", "ମୁଁ ତାକୁ କହିଥିଲେ ବି, ସେ ଶୁଣିଲା ନାହିଁ।", "Mun taaku kahithile bi, se shunilaa naahiin."],
            ["Even though the food was spicy, I ate it.", "ଖାଦ୍ୟ ଝାଳ ଥିଲେ ବି, ମୁଁ ଖାଇଲି।", "Khaadya jhala thile bi, mun khaaili."],
            ["Even though he is rich, he is not happy.", "ସେ ଧନୀ ହୋଇଥିଲେ ବି, ଖୁସି ନୁହେଁ।", "Se dhani hoithile bi, khusi nuhein."],
            ["Even though the exam was difficult, she passed.", "ପରୀକ୍ଷା କଠିନ ଥିଲେ ବି, ସେ ପାସ କଲା।", "Parikshaa kathina thile bi, se paas kalaa."],
            ["Even though I was sick, I went to work.", "ମୁଁ ଅସୁସ୍ଥ ଥିଲେ ବି, କାମକୁ ଗଲି।", "Mun asustha thile bi, kaamaku gali."],
            ["Even though they tried hard, they lost the match.", "ସେମାନେ ଖୁବ ଚେଷ୍ଟା କଲେ ବି, ମ୍ୟାଚ ହାରିଗଲେ।", "Semaane khub cheshtaa kale bi, match haarigale."],
            ["Even though the price was high, she bought it.", "ଦାମ ଅଧିକ ଥିଲେ ବି, ସେ କିଣିନେଲା।", "Daam adhika thile bi, se kininelaa."],
            ["Even though he apologized, she was still angry.", "ସେ କ୍ଷମା ମାଗିଥିଲେ ବି, ସେ ତଥାପି ରାଗି ଥିଲା।", "Se kshamaa maagithile bi, se tathaapi raagi thilaa."],
            ["Even though the movie was long, it was interesting.", "ସିନେମା ଲମ୍ବା ଥିଲେ ବି, ଆକର୍ଷଣୀୟ ଥିଲା।", "Sinemaa lambaa thile bi, aakarshaniiya thilaa."],
            ["Even though we ran fast, we missed the train.", "ଆମେ ଜୋରରେ ଦୌଡ଼ିଥିଲେ ବି, ଟ୍ରେନ ଛୁଟିଗଲା।", "Aame jorare daudithile bi, train chhuti galaa."],
            ["Even though he is young, he is very wise.", "ସେ ଯୁବ ଥିଲେ ବି, ବହୁତ ବୁଦ୍ଧିମାନ।", "Se juba thile bi, bahut buddhimaan."],
            ["Even though it was cold, the children played outside.", "ଥଣ୍ଡା ଥିଲେ ବି, ପିଲାମାନେ ବାହାରେ ଖେଳିଲେ।", "Thandaa thile bi, pilaamaane baahare khelile."],
            ["Even though I don't like it, I will do it.", "ମୋତେ ପସନ୍ଦ ନ ଥିଲେ ବି, ମୁଁ କରିବି।", "Mote pasanda na thile bi, mun karibi."],
            ["Even though the road was rough, we continued driving.", "ରାସ୍ତା ଖରାପ ଥିଲେ ବି, ଆମେ ଗାଡ଼ି ଚଳାଇଲୁ।", "Raastaa kharaap thile bi, aame gaadi chalaailu."],
            ["Even though she sings well, she is shy.", "ସେ ଭଲ ଗାଏ ଥିଲେ ବି, ଲାଜୁଆ।", "Se bhala gaae thile bi, laajuaa."],
            ["Even though they invited me, I did not go.", "ସେମାନେ ମୋତେ ଡାକିଥିଲେ ବି, ମୁଁ ଗଲି ନାହିଁ।", "Semaane mote daakithile bi, mun gali naahiin."],
        ]
    },
    564: {
        "url": "\"As soon as...\" Patterns in Odia",
        "rows": [
            ["As soon as I reached home, it started raining.", "ମୁଁ ଘରେ ପହଞ୍ଚିବା ମାତ୍ରେ, ବର୍ଷା ଆରମ୍ଭ ହେଲା।", "Mun ghare pahanchibaa maatre, barshaa aarambha helaa."],
            ["As soon as he saw me, he smiled.", "ସେ ମୋତେ ଦେଖିବା ମାତ୍ରେ, ହସିଲା।", "Se mote dekhibaa maatre, hasilaa."],
            ["As soon as the bell rang, students left.", "ଘଣ୍ଟି ବାଜିବା ମାତ୍ରେ, ଛାତ୍ରମାନେ ଚାଲିଗଲେ।", "Ghanti baajibaa maatre, chhaatra maane chaaligale."],
            ["As soon as she finished cooking, guests arrived.", "ସେ ରାନ୍ଧି ସାରିବା ମାତ୍ରେ, ଅତିଥିମାନେ ଆସିଲେ।", "Se raandhi saaribaa maatre, atithimaane aasile."],
            ["As soon as the sun rose, birds started singing.", "ସୂର୍ଯ୍ୟ ଉଦୟ ହେବା ମାତ୍ରେ, ପକ୍ଷୀମାନେ ଗାଇବାକୁ ଲାଗିଲେ।", "Surya udaya hebaa maatre, pakshiimaane gaaibaku laagile."],
            ["As soon as I got the message, I called you.", "ମୁଁ ମେସେଜ ପାଇବା ମାତ୍ରେ, ତୁମକୁ ଫୋନ କଲି।", "Mun mesej paaibaa maatre, tumaku phone kali."],
            ["As soon as the movie started, the power went off.", "ସିନେମା ଆରମ୍ଭ ହେବା ମାତ୍ରେ, ବିଜୁଳି ଚାଲିଗଲା।", "Sinemaa aarambha hebaa maatre, bijuli chaaligalaa."],
            ["As soon as the baby slept, the mother rested.", "ପିଲା ଶୋଇବା ମାତ୍ରେ, ମା ବିଶ୍ରାମ ନେଲା।", "Pilaa shoibaa maatre, maa bishraam nelaa."],
            ["As soon as I opened the door, the dog ran in.", "ମୁଁ କବାଟ ଖୋଲିବା ମାତ୍ରେ, କୁକୁର ଭିତରକୁ ଦୌଡ଼ିଲା।", "Mun kabaata kholibaa maatre, kukura bhitaraku daudiilaa."],
            ["As soon as the teacher entered, everyone became quiet.", "ଶିକ୍ଷକ ପ୍ରବେଶ କରିବା ମାତ୍ରେ, ସମସ୍ତେ ଚୁପ୍ ହୋଇଗଲେ।", "Shikshaka prabesh karibaa maatre, samaste chup hoigale."],
            ["As soon as I sat down, the phone rang.", "ମୁଁ ବସିବା ମାତ୍ରେ, ଫୋନ ବାଜିଲା।", "Mun basibaa maatre, phone baajilaa."],
            ["As soon as the rain stopped, children went out to play.", "ବର୍ଷା ବନ୍ଦ ହେବା ମାତ୍ରେ, ପିଲାମାନେ ଖେଳିବାକୁ ଗଲେ।", "Barshaa banda hebaa maatre, pilaamaane khelibaku gale."],
            ["As soon as I ate, I felt better.", "ମୁଁ ଖାଇବା ମାତ୍ରେ, ଭଲ ଲାଗିଲା।", "Mun khaaibaa maatre, bhala laagila."],
            ["As soon as the meeting ended, he left.", "ସଭା ଶେଷ ହେବା ମାତ୍ରେ, ସେ ଚାଲିଗଲା।", "Sabhaa shesha hebaa maatre, se chaaligalaa."],
            ["As soon as the alarm rang, I woke up.", "ଆଲାର୍ମ ବାଜିବା ମାତ୍ରେ, ମୁଁ ଉଠିଗଲି।", "Alarm baajibaa maatre, mun uthigali."],
            ["As soon as she heard the news, she cried.", "ସେ ଖବର ଶୁଣିବା ମାତ୍ରେ, କାନ୍ଦିଲା।", "Se khabara shunibaa maatre, kaandilaa."],
            ["As soon as I entered the office, the boss called me.", "ମୁଁ ଅଫିସରେ ପ୍ରବେଶ କରିବା ମାତ୍ରେ, ବସ୍ ମୋତେ ଡାକିଲେ।", "Mun office re prabesh karibaa maatre, boss mote daakile."],
            ["As soon as the market opened, people rushed in.", "ବଜାର ଖୋଲିବା ମାତ୍ରେ, ଲୋକମାନେ ଭିଡ଼ କଲେ।", "Bajaar kholibaa maatre, lokamaane bhida kale."],
        ]
    },
    565: {
        "url": "\"While...\" Simultaneous Patterns in Odia",
        "rows": [
            ["While I was eating, the phone rang.", "ମୁଁ ଖାଉଥିବା ବେଳେ, ଫୋନ ବାଜିଲା।", "Mun khaauthibaa bele, phone baajilaa."],
            ["While she was reading, the baby started crying.", "ସେ ପଢ଼ୁଥିବା ବେଳେ, ପିଲା କାନ୍ଦିବାକୁ ଲାଗିଲା।", "Se padhuthibaa bele, pilaa kaandibaku laagila."],
            ["While walking on the road, I met my friend.", "ରାସ୍ତାରେ ଚାଲୁଥିବା ବେଳେ, ମୋ ବନ୍ଧୁ ସହ ଭେଟ ହେଲା।", "Raastare chaaluthibaa bele, mo bandhu saha bheta helaa."],
            ["While cooking, she listens to music.", "ରାନ୍ଧୁଥିବା ବେଳେ, ସେ ଗୀତ ଶୁଣେ।", "Raandhuthibaa bele, se giita shune."],
            ["While he was sleeping, someone knocked on the door.", "ସେ ଶୋଇଥିବା ବେଳେ, କେହି କବାଟ ଠକଠକ କଲା।", "Se shoithibaa bele, kehi kabaata thakathaka kalaa."],
            ["While studying, don't use the phone.", "ପଢ଼ୁଥିବା ବେଳେ, ଫୋନ ବ୍ୟବହାର କର ନାହିଁ।", "Padhuthibaa bele, phone byabahaar kara naahiin."],
            ["While traveling, I saw beautiful scenery.", "ଯାତ୍ରା କରୁଥିବା ବେଳେ, ମୁଁ ସୁନ୍ଦର ଦୃଶ୍ୟ ଦେଖିଲି।", "Jaatraa karuthibaa bele, mun sundara drushya dekhili."],
            ["While waiting for the bus, it started raining.", "ବସ ଅପେକ୍ଷା କରୁଥିବା ବେଳେ, ବର୍ଷା ଆରମ୍ଭ ହେଲା।", "Bas apekshaa karuthibaa bele, barshaa aarambha helaa."],
            ["While we were talking, the time passed quickly.", "ଆମେ କଥା ହେଉଥିବା ବେଳେ, ସମୟ ଜଲଦି ଚାଲିଗଲା।", "Aame kathaa heuthibaa bele, samaya jaladi chaaligalaa."],
            ["While playing, the child fell down.", "ଖେଳୁଥିବା ବେଳେ, ପିଲାଟି ପଡ଼ିଗଲା।", "Kheluthibaa bele, pilaati padigalaa."],
            ["While driving, keep your eyes on the road.", "ଗାଡ଼ି ଚଳାଉଥିବା ବେଳେ, ରାସ୍ତା ଉପରେ ନଜର ରଖ।", "Gaadi chalaauthibaa bele, raastaa upare najara rakha."],
            ["While I was working, my colleague helped me.", "ମୁଁ କାମ କରୁଥିବା ବେଳେ, ମୋ ସହକର୍ମୀ ମୋତେ ସାହାଯ୍ୟ କଲେ।", "Mun kaama karuthibaa bele, mo sahakarmii mote saahajya kale."],
            ["While washing clothes, I found a coin.", "କପଡ଼ା ଧୋଉଥିବା ବେଳେ, ମୁଁ ଏକ ମୁଦ୍ରା ପାଇଲି।", "Kapadaa dhouthibaa bele, mun eka mudraa paaili."],
            ["While singing, she forgot the lyrics.", "ଗାଉଥିବା ବେଳେ, ସେ ଗୀତର କଥା ଭୁଲିଗଲା।", "Gaauthibaa bele, se giitara kathaa bhuligalaa."],
            ["While exercising, drink plenty of water.", "ବ୍ୟାୟାମ କରୁଥିବା ବେଳେ, ପ୍ରଚୁର ପାଣି ପିଅ।", "Byaayaam karuthibaa bele, prachura paani pia."],
            ["While the teacher was explaining, students took notes.", "ଶିକ୍ଷକ ବୁଝାଉଥିବା ବେଳେ, ଛାତ୍ରମାନେ ନୋଟ ନେଲେ।", "Shikshaka bujhaauthibaa bele, chhaatra maane note nele."],
            ["While shopping, I lost my wallet.", "କିଣାକିଣି କରୁଥିବା ବେଳେ, ମୋ ପର୍ସ ହଜିଗଲା।", "Kinaakini karuthibaa bele, mo purse hajigalaa."],
            ["While crossing the road, be careful.", "ରାସ୍ତା ପାର ହେଉଥିବା ବେଳେ, ସାବଧାନ ରୁହ।", "Raastaa paara heuthibaa bele, saabadhaana ruha."],
        ]
    },
    566: {
        "url": "\"Before...\" / \"After...\" Patterns in Odia",
        "rows": [
            ["Before eating, wash your hands.", "ଖାଇବା ପୂର୍ବରୁ, ହାତ ଧୋଅ।", "Khaaibaa purbaaru, haata dhoa."],
            ["After eating, brush your teeth.", "ଖାଇବା ପରେ, ଦାନ୍ତ ମାଜ।", "Khaaibaa pare, daanta maaja."],
            ["Before going to bed, read a book.", "ଶୋଇବା ପୂର୍ବରୁ, ଏକ ବହି ପଢ଼।", "Shoibaa purbaaru, eka bahi padha."],
            ["After finishing work, he went home.", "କାମ ସାରିବା ପରେ, ସେ ଘରକୁ ଗଲା।", "Kaama saaribaa pare, se gharaku galaa."],
            ["Before the exam, I revised all chapters.", "ପରୀକ୍ଷା ପୂର୍ବରୁ, ମୁଁ ସବୁ ଅଧ୍ୟାୟ ରିଭାଇଜ କଲି।", "Parikshaa purbaaru, mun sabu adhyaaya revise kali."],
            ["After the rain, the weather became pleasant.", "ବର୍ଷା ପରେ, ପାଗ ସୁନ୍ଦର ହେଲା।", "Barshaa pare, paag sundara helaa."],
            ["Before leaving, lock the door.", "ଯିବା ପୂର୍ବରୁ, କବାଟ ବନ୍ଦ କର।", "Jibaa purbaaru, kabaata banda kara."],
            ["After graduation, she got a job.", "ସ୍ନାତକ ହେବା ପରେ, ସେ ଚାକିରି ପାଇଲା।", "Snaataka hebaa pare, se chaakiri paailaa."],
            ["Before sunrise, the farmer went to the field.", "ସୂର୍ଯ୍ୟ ଉଦୟ ପୂର୍ବରୁ, ଚାଷୀ ଜମିକୁ ଗଲା।", "Surya udaya purbaaru, chaashii jamiku galaa."],
            ["After the meeting, we discussed the plan.", "ସଭା ପରେ, ଆମେ ଯୋଜନା ବିଷୟରେ ଆଲୋଚନା କଲୁ।", "Sabhaa pare, aame yojanaa bishayare aalochanaa kalu."],
            ["Before buying, check the quality.", "କିଣିବା ପୂର୍ବରୁ, ଗୁଣବତ୍ତା ଯାଞ୍ଚ କର।", "Kinibaa purbaaru, gunabattaa jaancha kara."],
            ["After learning Odia, I can talk to locals.", "ଓଡ଼ିଆ ଶିଖିବା ପରେ, ମୁଁ ସ୍ଥାନୀୟ ଲୋକଙ୍କ ସହ କଥା ହୋଇପାରୁଛି।", "Odiaa shiikhibaa pare, mun sthaaniiya lokanka saha kathaa hoipaaruchhi."],
            ["Before cooking, prepare all the ingredients.", "ରାନ୍ଧିବା ପୂର୍ବରୁ, ସବୁ ସାମଗ୍ରୀ ପ୍ରସ୍ତୁତ କର।", "Raandhibaa purbaaru, sabu saamagrii prastuta kara."],
            ["After the accident, he became more careful.", "ଦୁର୍ଘଟଣା ପରେ, ସେ ଅଧିକ ସାବଧାନ ହେଲା।", "Durghatanaa pare, se adhika saabadhaana helaa."],
            ["Before speaking, think carefully.", "କହିବା ପୂର୍ବରୁ, ଭଲ ଭାବେ ଭାବ।", "Kahibaa purbaaru, bhala bhaabe bhaaba."],
            ["After watching the movie, we went for dinner.", "ସିନେମା ଦେଖିବା ପରେ, ଆମେ ଖାଇବାକୁ ଗଲୁ।", "Sinemaa dekhibaa pare, aame khaaibaku galu."],
            ["Before the storm, the sky turned dark.", "ଝଡ଼ ପୂର୍ବରୁ, ଆକାଶ ଅନ୍ଧାର ହୋଇଗଲା।", "Jhada purbaaru, aakaash andhaar hoigalaa."],
            ["After years of practice, he became an expert.", "ବର୍ଷ ବର୍ଷ ଅଭ୍ୟାସ ପରେ, ସେ ବିଶେଷଜ୍ଞ ହେଲା।", "Barsha barsha abhyaas pare, se bisheshagnya helaa."],
        ]
    },
    567: {
        "url": "\"Instead of...\" Patterns in Odia",
        "rows": [
            ["Instead of complaining, find a solution.", "ଅଭିଯୋଗ କରିବା ବଦଳରେ, ସମାଧାନ ଖୋଜ।", "Abhiyog karibaa badalare, samaadhaan khoja."],
            ["Instead of walking, let's take a rickshaw.", "ଚାଲିବା ବଦଳରେ, ରିକ୍ସା ନେବା ଚାଲ।", "Chaalibaa badalare, riksaa nebaa chaal."],
            ["Instead of tea, I will have coffee.", "ଚା ବଦଳରେ, ମୁଁ କଫି ପିଇବି।", "Chaa badalare, mun coffee piibi."],
            ["Instead of watching TV, read a book.", "ଟିଭି ଦେଖିବା ବଦଳରେ, ଏକ ବହି ପଢ଼।", "TV dekhibaa badalare, eka bahi padha."],
            ["Instead of arguing, let's discuss calmly.", "ବାଦାନୁବାଦ କରିବା ବଦଳରେ, ଶାନ୍ତ ଭାବରେ ଆଲୋଚନା କରିବା।", "Baadaanubaad karibaa badalare, shaanta bhaavare aalochanaa karibaa."],
            ["Instead of buying new, repair the old one.", "ନୂଆ କିଣିବା ବଦଳରେ, ପୁରୁଣାଟିକୁ ମରାମତି କର।", "Nuaa kinibaa badalare, purunaatiku maraamati kara."],
            ["Instead of rice, I ate bread today.", "ଭାତ ବଦଳରେ, ମୁଁ ଆଜି ରୁଟି ଖାଇଲି।", "Bhaata badalare, mun aaji ruti khaaili."],
            ["Instead of crying, be brave.", "କାନ୍ଦିବା ବଦଳରେ, ସାହସୀ ହୁଅ।", "Kaandibaa badalare, saahasi hua."],
            ["Instead of driving, he took the train.", "ଗାଡ଼ି ଚଳାଇବା ବଦଳରେ, ସେ ଟ୍ରେନରେ ଗଲା।", "Gaadi chalaibaa badalare, se train re galaa."],
            ["Instead of sleeping late, wake up early.", "ଡେରିରେ ଶୋଇବା ବଦଳରେ, ସକାଳେ ଉଠ।", "Derire shoibaa badalare, sakaale utha."],
            ["Instead of blaming others, improve yourself.", "ଅନ୍ୟକୁ ଦୋଷ ଦେବା ବଦଳରେ, ନିଜକୁ ଉନ୍ନତ କର।", "Anyaku dosha debaa badalare, nijaku unnata kara."],
            ["Instead of spending money, save it.", "ଟଙ୍କା ଖର୍ଚ୍ଚ କରିବା ବଦଳରେ, ସଞ୍ଚୟ କର।", "Tankaa kharchcha karibaa badalare, sanchaya kara."],
            ["Instead of sugar, use honey.", "ଚିନି ବଦଳରେ, ମହୁ ବ୍ୟବହାର କର।", "Chini badalare, mahu byabahaar kara."],
            ["Instead of going alone, take someone with you.", "ଏକୁଟିଆ ଯିବା ବଦଳରେ, କାହାକୁ ସାଥିରେ ନିଅ।", "Ekutiaa jibaa badalare, kaahaku saathire nia."],
            ["Instead of worrying, take action.", "ଚିନ୍ତା କରିବା ବଦଳରେ, କାର୍ଯ୍ୟ କର।", "Chintaa karibaa badalare, kaarya kara."],
            ["Instead of fast food, eat home-cooked food.", "ଫାଷ୍ଟ ଫୁଡ ବଦଳରେ, ଘରେ ରନ୍ଧା ଖାଦ୍ୟ ଖାଅ।", "Fast food badalare, ghare randhaa khaadya khaao."],
            ["Instead of being angry, be patient.", "ରାଗିବା ବଦଳରେ, ଧୈର୍ଯ୍ୟ ଧର।", "Raagibaa badalare, dhairya dhara."],
            ["Instead of talking, listen more.", "କହିବା ବଦଳରେ, ଅଧିକ ଶୁଣ।", "Kahibaa badalare, adhika shuna."],
        ]
    },
    568: {
        "url": "\"According to...\" Patterns in Odia",
        "rows": [
            ["According to the news, it will rain tomorrow.", "ଖବର ଅନୁସାରେ, କାଲି ବର୍ଷା ହେବ।", "Khabara anusaare, kaali barshaa heba."],
            ["According to the doctor, you need rest.", "ଡାକ୍ତର ଅନୁସାରେ, ତୁମକୁ ବିଶ୍ରାମ ଦରକାର।", "Daaktar anusaare, tumaku bishraam darakaar."],
            ["According to the rules, this is not allowed.", "ନିୟମ ଅନୁସାରେ, ଏହା ଅନୁମତି ନାହିଁ।", "Niyama anusaare, ehaa anumati naahiin."],
            ["According to my opinion, this plan is good.", "ମୋ ମତ ଅନୁସାରେ, ଏହି ଯୋଜନା ଭଲ।", "Mo mata anusaare, ehi yojanaa bhala."],
            ["According to the schedule, the train arrives at 5.", "ସମୟସୂଚୀ ଅନୁସାରେ, ଟ୍ରେନ ୫ଟାରେ ଆସେ।", "Samayasuuchii anusaare, train 5 taare aase."],
            ["According to the teacher, the exam is next week.", "ଶିକ୍ଷକ ଅନୁସାରେ, ପରୀକ୍ଷା ଆସନ୍ତା ସପ୍ତାହରେ।", "Shikshaka anusaare, parikshaa aasantaa saptaahare."],
            ["According to tradition, we celebrate this festival.", "ପରମ୍ପରା ଅନୁସାରେ, ଆମେ ଏହି ପର୍ବ ପାଳନ କରୁ।", "Paramparaa anusaare, aame ehi parba paalana karu."],
            ["According to the map, the temple is nearby.", "ନକ୍ସା ଅନୁସାରେ, ମନ୍ଦିର ପାଖରେ ଅଛି।", "Nakshaa anusaare, mandira paakhare achhi."],
            ["According to the weather report, today will be hot.", "ପାଗ ରିପୋର୍ଟ ଅନୁସାରେ, ଆଜି ଗରମ ରହିବ।", "Paag report anusaare, aaji garama rahiba."],
            ["According to him, the work will be done by evening.", "ତାଙ୍କ ଅନୁସାରେ, କାମ ସନ୍ଧ୍ୟା ସୁଦ୍ଧା ହୋଇଯିବ।", "Taanka anusaare, kaama sandhyaa suddhaa hoijiba."],
            ["According to the law, everyone is equal.", "ଆଇନ ଅନୁସାରେ, ସମସ୍ତେ ସମାନ।", "Aaina anusaare, samaste samaana."],
            ["According to the recipe, add two spoons of salt.", "ରେସିପି ଅନୁସାରେ, ଦୁଇ ଚାମଚ ଲୁଣ ମିଶାଅ।", "Recipe anusaare, dui chaamacha luna mishaao."],
            ["According to my experience, patience is important.", "ମୋ ଅଭିଜ୍ଞତା ଅନୁସାରେ, ଧୈର୍ଯ୍ୟ ଗୁରୁତ୍ୱପୂର୍ଣ୍ଣ।", "Mo abhignyataa anusaare, dhairya gurutwapurna."],
            ["According to the elders, respect is earned.", "ବୟସ୍କ ମାନଙ୍କ ଅନୁସାରେ, ସମ୍ମାନ ଅର୍ଜନ କରିବାର ଜିନିଷ।", "Bayaska maananka anusaare, sammaana arjana karibara jinisha."],
            ["According to the report, sales have increased.", "ରିପୋର୍ଟ ଅନୁସାରେ, ବିକ୍ରି ବଢ଼ିଛି।", "Report anusaare, bikri badhichhi."],
            ["According to the calendar, tomorrow is a holiday.", "କ୍ୟାଲେଣ୍ଡର ଅନୁସାରେ, କାଲି ଛୁଟି।", "Calendar anusaare, kaali chhuti."],
            ["According to scientists, exercise is essential.", "ବୈଜ୍ଞାନିକ ମାନଙ୍କ ଅନୁସାରେ, ବ୍ୟାୟାମ ଅତ୍ୟନ୍ତ ଜରୁରୀ।", "Baignyaanika maananka anusaare, byaayaam atyanta jaruri."],
            ["According to the plan, we will start tomorrow.", "ଯୋଜନା ଅନୁସାରେ, ଆମେ କାଲି ଆରମ୍ଭ କରିବା।", "Yojanaa anusaare, aame kaali aarambha karibaa."],
        ]
    },
    569: {
        "url": "\"In order to...\" Purpose Patterns in Odia",
        "rows": [
            ["In order to pass, you must study hard.", "ପାସ ହେବା ପାଇଁ, ତୁମକୁ କଠିନ ପଢ଼ିବାକୁ ହେବ।", "Paas hebaa paain, tumaku kathina padhibaku heba."],
            ["In order to stay healthy, eat good food.", "ସୁସ୍ଥ ରହିବା ପାଇଁ, ଭଲ ଖାଦ୍ୟ ଖାଅ।", "Sustha rahibaa paain, bhala khaadya khaao."],
            ["In order to learn Odia, practice daily.", "ଓଡ଼ିଆ ଶିଖିବା ପାଇଁ, ପ୍ରତିଦିନ ଅଭ୍ୟାସ କର।", "Odiaa shikhibaa paain, pratidina abhyaas kara."],
            ["In order to save money, reduce expenses.", "ଟଙ୍କା ସଞ୍ଚୟ କରିବା ପାଇଁ, ଖର୍ଚ୍ଚ କମାଅ।", "Tankaa sanchaya karibaa paain, kharchcha kamaao."],
            ["In order to reach on time, leave early.", "ସମୟରେ ପହଞ୍ଚିବା ପାଇଁ, ଜଲଦି ବାହାର।", "Samayare pahanchibaa paain, jaladi baahara."],
            ["In order to get a job, learn new skills.", "ଚାକିରି ପାଇବା ପାଇଁ, ନୂଆ ଦକ୍ଷତା ଶିଖ।", "Chaakiri paaibaa paain, nuaa dakshataa shikha."],
            ["In order to cook well, follow the recipe.", "ଭଲ ରାନ୍ଧିବା ପାଇଁ, ରେସିପି ଅନୁସରଣ କର।", "Bhala raandhibaa paain, recipe anusarana kara."],
            ["In order to win, you need to practice.", "ଜିତିବା ପାଇଁ, ତୁମକୁ ଅଭ୍ୟାସ କରିବାକୁ ହେବ।", "Jitibaa paain, tumaku abhyaas karibaku heba."],
            ["In order to understand, listen carefully.", "ବୁଝିବା ପାଇଁ, ଧ୍ୟାନ ଦେଇ ଶୁଣ।", "Bujhibaa paain, dhyaan dei shuna."],
            ["In order to buy a house, he saved for years.", "ଘର କିଣିବା ପାଇଁ, ସେ ବର୍ଷ ବର୍ଷ ସଞ୍ଚୟ କଲା।", "Ghara kinibaa paain, se barsha barsha sanchaya kalaa."],
            ["In order to improve English, read newspapers.", "ଇଂରାଜୀ ଉନ୍ନତ କରିବା ପାଇଁ, ଖବର କାଗଜ ପଢ଼।", "English unnata karibaa paain, khabara kaagaja padha."],
            ["In order to be respected, respect others first.", "ସମ୍ମାନ ପାଇବା ପାଇଁ, ପ୍ରଥମେ ଅନ୍ୟକୁ ସମ୍ମାନ ଦିଅ।", "Sammaana paaibaa paain, prathame anyaku sammaana dia."],
            ["In order to sleep well, avoid screen time at night.", "ଭଲ ଶୋଇବା ପାଇଁ, ରାତିରେ ସ୍କ୍ରିନ ଦେଖ ନାହିଁ।", "Bhala shoibaa paain, raatire screen dekha naahiin."],
            ["In order to grow crops, the farmer needs water.", "ଫସଲ ଫଳାଇବା ପାଇଁ, ଚାଷୀକୁ ପାଣି ଦରକାର।", "Phasala phalaibaa paain, chaashiiku paani darakaar."],
            ["In order to make friends, be kind to everyone.", "ବନ୍ଧୁ ତିଆରି କରିବା ପାଇଁ, ସମସ୍ତଙ୍କ ପ୍ରତି ଦୟାଳୁ ହୁଅ।", "Bandhu tiaari karibaa paain, samastanka prati dayaalu hua."],
            ["In order to travel abroad, you need a passport.", "ବିଦେଶ ଯାତ୍ରା କରିବା ପାଇଁ, ତୁମକୁ ପାସପୋର୍ଟ ଦରକାର।", "Bidesha jaatraa karibaa paain, tumaku passport darakaar."],
            ["In order to drive, you need a license.", "ଗାଡ଼ି ଚଳାଇବା ପାଇଁ, ତୁମକୁ ଲାଇସେନ୍ସ ଦରକାର।", "Gaadi chalaibaa paain, tumaku license darakaar."],
            ["In order to succeed, never give up.", "ସଫଳ ହେବା ପାଇଁ, କେବେ ହାର ମାନ ନାହିଁ।", "Saphala hebaa paain, kebe haar maana naahiin."],
        ]
    },
    570: {
        "url": "\"It seems like...\" Patterns in Odia",
        "rows": [
            ["It seems like it will rain today.", "ମନେ ହେଉଛି ଆଜି ବର୍ଷା ହେବ।", "Mane heuchhi aaji barshaa heba."],
            ["It seems like he is angry.", "ମନେ ହେଉଛି ସେ ରାଗି ଅଛି।", "Mane heuchhi se raagi achhi."],
            ["It seems like she is not coming.", "ମନେ ହେଉଛି ସେ ଆସୁ ନାହିଁ।", "Mane heuchhi se aasu naahiin."],
            ["It seems like the shop is closed.", "ମନେ ହେଉଛି ଦୋକାନ ବନ୍ଦ ଅଛି।", "Mane heuchhi dokaan banda achhi."],
            ["It seems like he has forgotten.", "ମନେ ହେଉଛି ସେ ଭୁଲିଯାଇଛି।", "Mane heuchhi se bhuli jaaichhi."],
            ["It seems like the food is ready.", "ମନେ ହେଉଛି ଖାଦ୍ୟ ପ୍ରସ୍ତୁତ ହୋଇଛି।", "Mane heuchhi khaadya prastuta hoichhi."],
            ["It seems like they had a fight.", "ମନେ ହେଉଛି ସେମାନଙ୍କ ଝଗଡ଼ା ହୋଇଛି।", "Mane heuchhi semaananka jhagadaa hoichhi."],
            ["It seems like the bus is late.", "ମନେ ହେଉଛି ବସ ଡେରି ହୋଇଛି।", "Mane heuchhi bas deri hoichhi."],
            ["It seems like she is very happy.", "ମନେ ହେଉଛି ସେ ବହୁତ ଖୁସି।", "Mane heuchhi se bahut khusi."],
            ["It seems like he doesn't understand.", "ମନେ ହେଉଛି ସେ ବୁଝୁ ନାହିଁ।", "Mane heuchhi se bujhu naahiin."],
            ["It seems like the road is blocked.", "ମନେ ହେଉଛି ରାସ୍ତା ବନ୍ଦ ଅଛି।", "Mane heuchhi raastaa banda achhi."],
            ["It seems like they are lost.", "ମନେ ହେଉଛି ସେମାନେ ହଜିଯାଇଛନ୍ତି।", "Mane heuchhi semaane hajijaaichhanti."],
            ["It seems like the child is sleepy.", "ମନେ ହେଉଛି ପିଲାଟିର ନିଦ ଆସୁଛି।", "Mane heuchhi pilaatira nida aasuchhi."],
            ["It seems like there was a misunderstanding.", "ମନେ ହେଉଛି ଭୁଲ ବୁଝାମଣା ହୋଇଛି।", "Mane heuchhi bhula bujhaamanaa hoichhi."],
            ["It seems like the project is delayed.", "ମନେ ହେଉଛି ପ୍ରକଳ୍ପ ଡେରି ହୋଇଛି।", "Mane heuchhi prakalpa deri hoichhi."],
            ["It seems like he is telling the truth.", "ମନେ ହେଉଛି ସେ ସତ କହୁଛି।", "Mane heuchhi se sata kahuchhi."],
            ["It seems like the water is hot.", "ମନେ ହେଉଛି ପାଣି ଗରମ ଅଛି।", "Mane heuchhi paani garama achhi."],
            ["It seems like we are going in the wrong direction.", "ମନେ ହେଉଛି ଆମେ ଭୁଲ ଦିଗରେ ଯାଉଛୁ।", "Mane heuchhi aame bhula digare jaauchhuu."],
        ]
    },
    571: {
        "url": "\"I used to...\" Habitual Past Patterns in Odia",
        "rows": [
            ["I used to play cricket every day.", "ମୁଁ ପ୍ରତିଦିନ କ୍ରିକେଟ ଖେଳୁଥିଲି।", "Mun pratidina cricket kheluthili."],
            ["She used to sing in the morning.", "ସେ ସକାଳେ ଗାଉଥିଲା।", "Se sakaale gaautilaa."],
            ["We used to live in a village.", "ଆମେ ଏକ ଗାଁରେ ରହୁଥିଲୁ।", "Aame eka gaanre rahuthilu."],
            ["He used to walk to school.", "ସେ ପାଦରେ ସ୍କୁଲକୁ ଯାଉଥିଲା।", "Se paadare skulku jaautilaa."],
            ["I used to drink milk every night.", "ମୁଁ ପ୍ରତି ରାତିରେ କ୍ଷୀର ପିଉଥିଲି।", "Mun prati raatire kshiira piuthili."],
            ["They used to visit us on festivals.", "ସେମାନେ ପର୍ବରେ ଆମ ପାଖକୁ ଆସୁଥିଲେ।", "Semaane parbere aama paakhku aasuthile."],
            ["Grandmother used to tell us stories.", "ଜେଜେମା ଆମକୁ ଗପ କହୁଥିଲେ।", "Jejemaa aamaku gapa kahuthile."],
            ["I used to ride a bicycle to work.", "ମୁଁ ସାଇକେଲରେ କାମକୁ ଯାଉଥିଲି।", "Mun saikelre kaamaku jaautili."],
            ["She used to cook for the whole family.", "ସେ ସମସ୍ତ ପରିବାର ପାଇଁ ରାନ୍ଧୁଥିଲା।", "Se samasta paribaar paain raandhutilaa."],
            ["We used to play in the river.", "ଆମେ ନଦୀରେ ଖେଳୁଥିଲୁ।", "Aame nadiire kheluthilu."],
            ["He used to read the newspaper every morning.", "ସେ ପ୍ରତିଦିନ ସକାଳେ ଖବର କାଗଜ ପଢ଼ୁଥିଲା।", "Se pratidina sakaale khabara kaagaja padhutilaa."],
            ["I used to study under a lamp.", "ମୁଁ ଲ୍ୟାମ୍ପ ତଳେ ପଢ଼ୁଥିଲି।", "Mun lamp tale padhuthili."],
            ["Children used to play in the fields.", "ପିଲାମାନେ ଜମିରେ ଖେଳୁଥିଲେ।", "Pilaamaane jamire kheluthile."],
            ["She used to wear sarees every day.", "ସେ ପ୍ରତିଦିନ ଶାଢ଼ୀ ପିନ୍ଧୁଥିଲା।", "Se pratidina shaadhi pindhutilaa."],
            ["We used to eat together as a family.", "ଆମେ ପରିବାର ସହ ଏକାଠି ଖାଉଥିଲୁ।", "Aame paribaar saha ekaathi khaauthorilu."],
            ["He used to help everyone in the village.", "ସେ ଗାଁର ସମସ୍ତଙ୍କୁ ସାହାଯ୍ୟ କରୁଥିଲା।", "Se gaanra samastanku saahajya karutilaa."],
            ["I used to wake up at 5 AM.", "ମୁଁ ସକାଳ ୫ଟାରେ ଉଠୁଥିଲି।", "Mun sakaala 5 taare uthuthili."],
            ["They used to celebrate every festival grandly.", "ସେମାନେ ପ୍ରତି ପର୍ବ ଧୂମଧାମରେ ପାଳନ କରୁଥିଲେ।", "Semaane prati parba dhuumadhaamare paalana karuthile."],
        ]
    },
    572: {
        "url": "\"I have been...\" Continuous Patterns in Odia",
        "rows": [
            ["I have been waiting for you since morning.", "ମୁଁ ସକାଳୁ ତୁମ ପାଇଁ ଅପେକ୍ଷା କରୁଛି।", "Mun sakaalu tuma paain apekshaa karuchhi."],
            ["She has been studying for three hours.", "ସେ ତିନି ଘଣ୍ଟା ଧରି ପଢ଼ୁଛି।", "Se tini ghantaa dhari padhuchhi."],
            ["He has been working here for five years.", "ସେ ପାଞ୍ଚ ବର୍ଷ ଧରି ଏଠାରେ କାମ କରୁଛି।", "Se paancha barsha dhari ethaare kaama karuchhi."],
            ["We have been living in this city since 2010.", "ଆମେ ୨୦୧୦ ମସିହାରୁ ଏହି ସହରରେ ରହୁଛୁ।", "Aame 2010 masiharu ehi shaharare rahuchhu."],
            ["I have been learning Odia for six months.", "ମୁଁ ଛଅ ମାସ ଧରି ଓଡ଼ିଆ ଶିଖୁଛି।", "Mun chhaa maas dhari Odiaa shikhuchhi."],
            ["They have been playing since afternoon.", "ସେମାନେ ଅପରାହ୍ନରୁ ଖେଳୁଛନ୍ତି।", "Semaane aparaahnaru kheluchhanti."],
            ["It has been raining since last night.", "ଗତ ରାତିରୁ ବର୍ଷା ହେଉଛି।", "Gata raatiru barshaa heuchhi."],
            ["She has been cooking since 5 o'clock.", "ସେ ୫ଟାରୁ ରାନ୍ଧୁଛି।", "Se 5 taaru raandhuchhi."],
            ["He has been driving for four hours.", "ସେ ଚାରି ଘଣ୍ଟା ଧରି ଗାଡ଼ି ଚଳାଉଛି।", "Se chaari ghantaa dhari gaadi chalauchhi."],
            ["I have been reading this book for a week.", "ମୁଁ ଏକ ସପ୍ତାହ ଧରି ଏହି ବହି ପଢ଼ୁଛି।", "Mun eka saptaaha dhari ehi bahi padhuchhi."],
            ["We have been trying to contact you.", "ଆମେ ତୁମ ସହ ଯୋଗାଯୋଗ କରିବାକୁ ଚେଷ୍ଟା କରୁଛୁ।", "Aame tuma saha yogaayog karibaku cheshtaa karuchhu."],
            ["She has been singing since childhood.", "ସେ ପିଲାଦିନୁ ଗାଉଛି।", "Se pilaadinu gauchhi."],
            ["They have been building this house for two years.", "ସେମାନେ ଦୁଇ ବର୍ଷ ଧରି ଏହି ଘର ତିଆରି କରୁଛନ୍ତି।", "Semaane dui barsha dhari ehi ghara tiaari karuchhanti."],
            ["I have been feeling unwell since yesterday.", "ମୁଁ ଗତକାଲିଠୁ ଅସୁସ୍ଥ ଅନୁଭବ କରୁଛି।", "Mun gatakaalithu asustha anubhaba karuchhi."],
            ["He has been teaching at this school for ten years.", "ସେ ଦଶ ବର୍ଷ ଧରି ଏହି ସ୍କୁଲରେ ପଢ଼ାଉଛି।", "Se dasha barsha dhari ehi skulre padhauchhi."],
            ["We have been planning this trip for months.", "ଆମେ ମାସ ମାସ ଧରି ଏହି ଯାତ୍ରା ଯୋଜନା କରୁଛୁ।", "Aame maas maas dhari ehi jaatraa yojanaa karuchhu."],
            ["She has been writing her novel for a year.", "ସେ ଏକ ବର୍ଷ ଧରି ତା ଉପନ୍ୟାସ ଲେଖୁଛି।", "Se eka barsha dhari taa upanyaas lekhuchhi."],
            ["I have been exercising every morning.", "ମୁଁ ପ୍ରତିଦିନ ସକାଳେ ବ୍ୟାୟାମ କରୁଛି।", "Mun pratidina sakaale byaayaam karuchhi."],
        ]
    },
    573: {
        "url": "\"I wish...\" Desire Patterns in Odia",
        "rows": [
            ["I wish I could fly.", "ମୁଁ ଇଚ୍ଛା କରେ ମୁଁ ଉଡ଼ି ପାରନ୍ତି।", "Mun ichchhaa kare mun udi paaranti."],
            ["I wish it would stop raining.", "ମୁଁ ଇଚ୍ଛା କରେ ବର୍ଷା ବନ୍ଦ ହୋଇଯାଆନ୍ତା।", "Mun ichchhaa kare barshaa banda hoijaaantaa."],
            ["I wish I had more time.", "ମୁଁ ଇଚ୍ଛା କରେ ମୋ ପାଖରେ ଅଧିକ ସମୟ ଥାଆନ୍ତା।", "Mun ichchhaa kare mo paakhare adhika samaya thaaantaa."],
            ["I wish she were here.", "ମୁଁ ଇଚ୍ଛା କରେ ସେ ଏଠାରେ ଥାଆନ୍ତା।", "Mun ichchhaa kare se ethaare thaaantaa."],
            ["I wish I could speak Odia fluently.", "ମୁଁ ଇଚ୍ଛା କରେ ମୁଁ ଓଡ଼ିଆ ସରଳ ଭାବରେ କହି ପାରନ୍ତି।", "Mun ichchhaa kare mun Odiaa sarala bhaavare kahi paaranti."],
            ["I wish you would listen to me.", "ମୁଁ ଇଚ୍ଛା କରେ ତୁମେ ମୋ କଥା ଶୁଣନ୍ତ।", "Mun ichchhaa kare tume mo kathaa shunanta."],
            ["I wish the exam were easy.", "ମୁଁ ଇଚ୍ଛା କରେ ପରୀକ୍ଷା ସହଜ ହୋଇଥାଆନ୍ତା।", "Mun ichchhaa kare parikshaa sahaja hoithaantaa."],
            ["I wish I could go back to my childhood.", "ମୁଁ ଇଚ୍ଛା କରେ ମୁଁ ପିଲାଦିନକୁ ଫେରିଯାଇ ପାରନ୍ତି।", "Mun ichchhaa kare mun pilaadinaku pheriyaai paaranti."],
            ["I wish we had a bigger house.", "ମୁଁ ଇଚ୍ଛା କରେ ଆମର ଏକ ବଡ଼ ଘର ଥାଆନ୍ତା।", "Mun ichchhaa kare aamara eka bada ghara thaaantaa."],
            ["I wish he would apologize.", "ମୁଁ ଇଚ୍ଛା କରେ ସେ କ୍ଷମା ମାଗନ୍ତା।", "Mun ichchhaa kare se kshamaa maagantaa."],
            ["I wish the traffic were less.", "ମୁଁ ଇଚ୍ଛା କରେ ଟ୍ରାଫିକ କମ ଥାଆନ୍ତା।", "Mun ichchhaa kare traffic kama thaaantaa."],
            ["I wish I knew the answer.", "ମୁଁ ଇଚ୍ଛା କରେ ମୁଁ ଉତ୍ତର ଜାଣିଥାନ୍ତି।", "Mun ichchhaa kare mun uttara jaanithanti."],
            ["I wish everyone were happy.", "ମୁଁ ଇଚ୍ଛା କରେ ସମସ୍ତେ ଖୁସି ଥାଆନ୍ତେ।", "Mun ichchhaa kare samaste khusi thaaante."],
            ["I wish I could travel the world.", "ମୁଁ ଇଚ୍ଛା କରେ ମୁଁ ସାରା ଦୁନିଆ ବୁଲି ପାରନ୍ତି।", "Mun ichchhaa kare mun saaraa duniaa buli paaranti."],
            ["I wish you were with me right now.", "ମୁଁ ଇଚ୍ଛା କରେ ତୁମେ ଏବେ ମୋ ସାଥିରେ ଥାଆନ୍ତ।", "Mun ichchhaa kare tume ebe mo saathire thaaanta."],
            ["I wish it were not so hot.", "ମୁଁ ଇଚ୍ଛା କରେ ଏତେ ଗରମ ନ ଥାଆନ୍ତା।", "Mun ichchhaa kare ete garama na thaaantaa."],
            ["I wish the power would come back.", "ମୁଁ ଇଚ୍ଛା କରେ ବିଜୁଳି ଫେରିଆସନ୍ତା।", "Mun ichchhaa kare bijuli pheriaasantaa."],
            ["I wish my parents were proud of me.", "ମୁଁ ଇଚ୍ଛା କରେ ମୋ ବାପା ମା ମୋ ଉପରେ ଗର୍ବ ଅନୁଭବ କରନ୍ତେ।", "Mun ichchhaa kare mo baapaa maa mo upare garba anubhaba karante."],
        ]
    },
    574: {
        "url": "\"Compared to...\" Comparison Patterns in Odia",
        "rows": [
            ["Compared to summer, winter is more pleasant.", "ଗ୍ରୀଷ୍ମ ତୁଳନାରେ, ଶୀତ ଅଧିକ ସୁଖଦ।", "Griishma tulanare, shiita adhika sukhada."],
            ["Compared to tea, I prefer coffee.", "ଚା ତୁଳନାରେ, ମୁଁ କଫି ପସନ୍ଦ କରେ।", "Chaa tulanare, mun coffee pasanda kare."],
            ["Compared to last year, prices have increased.", "ଗତ ବର୍ଷ ତୁଳନାରେ, ଦାମ ବଢ଼ିଛି।", "Gata barsha tulanare, daam badhichhi."],
            ["Compared to him, she is more hardworking.", "ତାଙ୍କ ତୁଳନାରେ, ସେ ଅଧିକ ପରିଶ୍ରମୀ।", "Taanka tulanare, se adhika parishramii."],
            ["Compared to the city, the village is quiet.", "ସହର ତୁଳନାରେ, ଗାଁ ଶାନ୍ତ।", "Shahara tulanare, gaan shaanta."],
            ["Compared to English, Odia grammar is different.", "ଇଂରାଜୀ ତୁଳନାରେ, ଓଡ଼ିଆ ବ୍ୟାକରଣ ଭିନ୍ନ।", "English tulanare, Odiaa byaakarana bhinna."],
            ["Compared to bus, train is faster.", "ବସ ତୁଳନାରେ, ଟ୍ରେନ ଅଧିକ ଦ୍ରୁତ।", "Bas tulanare, train adhika druta."],
            ["Compared to yesterday, today is cooler.", "ଗତକାଲି ତୁଳନାରେ, ଆଜି ଅଧିକ ଥଣ୍ଡା।", "Gatakaali tulanare, aaji adhika thandaa."],
            ["Compared to the old house, the new one is bigger.", "ପୁରୁଣା ଘର ତୁଳନାରେ, ନୂଆ ଘର ବଡ଼।", "Purunaa ghara tulanare, nuaa ghara bada."],
            ["Compared to cooking, baking is harder.", "ରାନ୍ଧିବା ତୁଳନାରେ, ବେକିଂ ଅଧିକ କଠିନ।", "Raandhibaa tulanare, baking adhika kathina."],
            ["Compared to my brother, I am taller.", "ମୋ ଭାଇ ତୁଳନାରେ, ମୁଁ ଅଧିକ ଲମ୍ବା।", "Mo bhaai tulanare, mun adhika lambaa."],
            ["Compared to reading, writing is more difficult.", "ପଢ଼ିବା ତୁଳନାରେ, ଲେଖିବା ଅଧିକ କଠିନ।", "Padhibaa tulanare, lekhibaa adhika kathina."],
            ["Compared to morning, evening is busier.", "ସକାଳ ତୁଳନାରେ, ସନ୍ଧ୍ୟା ଅଧିକ ବ୍ୟସ୍ତ।", "Sakaala tulanare, sandhyaa adhika byasta."],
            ["Compared to cats, dogs are more loyal.", "ବିଲେଇ ତୁଳନାରେ, କୁକୁର ଅଧିକ ବିଶ୍ୱସ୍ତ।", "Bilei tulanare, kukura adhika bishwasta."],
            ["Compared to his singing, her singing is better.", "ତାଙ୍କ ଗାଇବା ତୁଳନାରେ, ତାଙ୍କର ଗାଇବା ଭଲ।", "Taanka gaaibaa tulanare, taankara gaaibaa bhala."],
            ["Compared to walking, cycling is faster.", "ଚାଲିବା ତୁଳନାରେ, ସାଇକେଲ ଚଳାଇବା ଅଧିକ ଦ୍ରୁତ।", "Chaalibaa tulanare, saikel chalaibaa adhika druta."],
            ["Compared to online shopping, I like going to the store.", "ଅନଲାଇନ ସପିଂ ତୁଳନାରେ, ମୁଁ ଦୋକାନକୁ ଯିବା ପସନ୍ଦ କରେ।", "Online shopping tulanare, mun dokaanaku jibaa pasanda kare."],
            ["Compared to cotton, silk is more expensive.", "କପା ତୁଳନାରେ, ରେଶମ ଅଧିକ ମହଙ୍ଗା।", "Kapaa tulanare, reshama adhika mahangaa."],
        ]
    },
    575: {
        "url": "\"Not only...but also...\" Patterns in Odia",
        "rows": [
            ["Not only he studies, but also works.", "ସେ କେବଳ ପଢ଼େ ନାହିଁ, ବରଂ କାମ ମଧ୍ୟ କରେ।", "Se kebala padhe naahiin, barang kaama madhya kare."],
            ["Not only is she beautiful, but also intelligent.", "ସେ କେବଳ ସୁନ୍ଦରୀ ନୁହେଁ, ବରଂ ବୁଦ୍ଧିମାନ ମଧ୍ୟ।", "Se kebala sundarii nuhein, barang buddhimaan madhya."],
            ["Not only did he apologize, but also corrected his mistake.", "ସେ କେବଳ କ୍ଷମା ମାଗିଲା ନାହିଁ, ବରଂ ଭୁଲ ମଧ୍ୟ ଠିକ କଲା।", "Se kebala kshamaa maagilaa naahiin, barang bhula madhya thika kalaa."],
            ["Not only children, but also adults enjoy this.", "କେବଳ ପିଲାମାନେ ନୁହେଁ, ବରଂ ବଡ଼ ଲୋକ ମଧ୍ୟ ଏହା ଉପଭୋଗ କରନ୍ତି।", "Kebala pilaamaane nuhein, barang bada loka madhya ehaa upabhoga karanti."],
            ["Not only is the food delicious, but also healthy.", "ଖାଦ୍ୟ କେବଳ ସ୍ୱାଦିଷ୍ଟ ନୁହେଁ, ବରଂ ସ୍ୱାସ୍ଥ୍ୟକର ମଧ୍ୟ।", "Khaadya kebala swaadishta nuhein, barang swaasthyakara madhya."],
            ["Not only does she sing, but also dances.", "ସେ କେବଳ ଗାଏ ନାହିଁ, ବରଂ ନାଚେ ମଧ୍ୟ।", "Se kebala gaae naahiin, barang naache madhya."],
            ["Not only is he a teacher, but also a writer.", "ସେ କେବଳ ଶିକ୍ଷକ ନୁହେଁ, ବରଂ ଲେଖକ ମଧ୍ୟ।", "Se kebala shikshaka nuhein, barang lekhaka madhya."],
            ["Not only did it rain, but also hailed.", "କେବଳ ବର୍ଷା ହେଲା ନାହିଁ, ବରଂ ଶିଳାବୃଷ୍ଟି ମଧ୍ୟ ହେଲା।", "Kebala barshaa helaa naahiin, barang shilaabrishti madhya helaa."],
            ["Not only is he strong, but also kind.", "ସେ କେବଳ ବଳବାନ ନୁହେଁ, ବରଂ ଦୟାଳୁ ମଧ୍ୟ।", "Se kebala balabaan nuhein, barang dayaalu madhya."],
            ["Not only the house, but also the garden is beautiful.", "କେବଳ ଘର ନୁହେଁ, ବରଂ ବଗିଚା ମଧ୍ୟ ସୁନ୍ଦର।", "Kebala ghara nuhein, barang bagichaa madhya sundara."],
            ["Not only did she help, but also inspired others.", "ସେ କେବଳ ସାହାଯ୍ୟ କଲା ନାହିଁ, ବରଂ ଅନ୍ୟମାନଙ୍କୁ ପ୍ରେରଣା ମଧ୍ୟ ଦେଲା।", "Se kebala saahajya kalaa naahiin, barang anyamaanankku preranaa madhya delaa."],
            ["Not only is Puri famous for temples, but also for beaches.", "ପୁରୀ କେବଳ ମନ୍ଦିର ପାଇଁ ପ୍ରସିଦ୍ଧ ନୁହେଁ, ବରଂ ସମୁଦ୍ର ତଟ ପାଇଁ ମଧ୍ୟ।", "Puri kebala mandira paain prasiddha nuhein, barang samudra tata paain madhya."],
            ["Not only does he earn well, but also saves wisely.", "ସେ କେବଳ ଭଲ ରୋଜଗାର କରେ ନାହିଁ, ବରଂ ବୁଦ୍ଧିମାନ ଭାବରେ ସଞ୍ଚୟ ମଧ୍ୟ କରେ।", "Se kebala bhala rojagaar kare naahiin, barang buddhimaan bhaavare sanchaya madhya kare."],
            ["Not only is this book informative, but also entertaining.", "ଏହି ବହି କେବଳ ସୂଚନାମୂଳକ ନୁହେଁ, ବରଂ ମନୋରଞ୍ଜନକାରୀ ମଧ୍ୟ।", "Ehi bahi kebala suuchanamuulaka nuhein, barang manoranjanakaaree madhya."],
            ["Not only students, but also parents attended the meeting.", "କେବଳ ଛାତ୍ରମାନେ ନୁହେଁ, ବରଂ ଅଭିଭାବକ ମଧ୍ୟ ସଭାରେ ଯୋଗ ଦେଲେ।", "Kebala chhaatra maane nuhein, barang abhibhaabaka madhya sabhaare yoga dele."],
            ["Not only does he speak Odia, but also Hindi.", "ସେ କେବଳ ଓଡ଼ିଆ କହେ ନାହିଁ, ବରଂ ହିନ୍ଦୀ ମଧ୍ୟ କହେ।", "Se kebala Odiaa kahe naahiin, barang Hindi madhya kahe."],
            ["Not only is she my friend, but also my guide.", "ସେ କେବଳ ମୋ ବନ୍ଧୁ ନୁହେଁ, ବରଂ ମୋ ପଥପ୍ରଦର୍ଶକ ମଧ୍ୟ।", "Se kebala mo bandhu nuhein, barang mo pathapradarshaka madhya."],
            ["Not only is the view good, but also the air is fresh.", "କେବଳ ଦୃଶ୍ୟ ଭଲ ନୁହେଁ, ବରଂ ବାୟୁ ମଧ୍ୟ ସଫା।", "Kebala drushya bhala nuhein, barang baayu madhya saphaa."],
        ]
    },
    576: {
        "url": "\"Either...or...\" Patterns in Odia",
        "rows": [
            ["Either come now or don't come at all.", "ଏବେ ଆସ ନଚେତ ଆଦୌ ଆସ ନାହିଁ।", "Ebe aasa nacheta aadau aasa naahiin."],
            ["Either you study or you fail.", "ତୁମେ ପଢ଼ ନଚେତ ଫେଲ ହେବ।", "Tume padha nacheta fail heba."],
            ["Either take the bus or walk.", "ବସ ନିଅ ନଚେତ ଚାଲ।", "Bas nia nacheta chaala."],
            ["Either she will call or send a message.", "ସେ ଫୋନ କରିବ ନଚେତ ମେସେଜ ପଠାଇବ।", "Se phone kariba nacheta mesej pathaiba."],
            ["Either eat rice or bread.", "ଭାତ ଖାଅ ନଚେତ ରୁଟି ଖାଅ।", "Bhaata khaao nacheta ruti khaao."],
            ["Either he is lying or confused.", "ସେ ମିଛ କହୁଛି ନଚେତ ବିଭ୍ରାନ୍ତ ଅଛି।", "Se michha kahuchhi nacheta bibhraanta achhi."],
            ["Either we leave now or we'll be late.", "ଏବେ ବାହାରିବା ନଚେତ ଡେରି ହେବ।", "Ebe baaharibaa nacheta deri heba."],
            ["Either apologize or face the consequences.", "କ୍ଷମା ମାଗ ନଚେତ ପରିଣାମ ଭୋଗ।", "Kshamaa maaga nacheta parinaama bhoga."],
            ["Either he is at home or at the office.", "ସେ ଘରେ ଅଛି ନଚେତ ଅଫିସରେ ଅଛି।", "Se ghare achhi nacheta office re achhi."],
            ["Either buy this one or that one.", "ଏଇଟି କିଣ ନଚେତ ସେଇଟି କିଣ।", "Eiti kina nacheta seiti kina."],
            ["Either finish your homework or no TV.", "ହୋମୱାର୍କ ସାର ନଚେତ ଟିଭି ନାହିଁ।", "Homework saara nacheta TV naahiin."],
            ["Either speak the truth or remain silent.", "ସତ କୁହ ନଚେତ ଚୁପ୍ ରୁହ।", "Sata kuha nacheta chup ruha."],
            ["Either she is happy or pretending.", "ସେ ଖୁସି ଅଛି ନଚେତ ଆଭାସ କରୁଛି।", "Se khusi achhi nacheta aabhaas karuchhi."],
            ["Either help me or let me do it alone.", "ମୋତେ ସାହାଯ୍ୟ କର ନଚେତ ମୋତେ ଏକୁଟିଆ କରିବାକୁ ଦିଅ।", "Mote saahajya kara nacheta mote ekutiaa karibaku dia."],
            ["Either we go by car or by train.", "ଆମେ ଗାଡ଼ିରେ ଯିବା ନଚେତ ଟ୍ରେନରେ ଯିବା।", "Aame gaadire jibaa nacheta train re jibaa."],
            ["Either it is true or false.", "ଏହା ସତ ନଚେତ ମିଛ।", "Ehaa sata nacheta michha."],
            ["Either drink water or juice.", "ପାଣି ପିଅ ନଚେତ ଜୁସ୍ ପିଅ।", "Paani pia nacheta juice pia."],
            ["Either today or tomorrow, I will come.", "ଆଜି ନଚେତ କାଲି, ମୁଁ ଆସିବି।", "Aaji nacheta kaali, mun aasibi."],
        ]
    },
    577: {
        "url": "\"Neither...nor...\" Patterns in Odia",
        "rows": [
            ["Neither he came nor called.", "ସେ ଆସିଲା ନାହିଁ ଏବଂ ଫୋନ ମଧ୍ୟ କଲା ନାହିଁ।", "Se aasilaa naahiin ebam phone madhya kalaa naahiin."],
            ["Neither the food was good nor the service.", "ଖାଦ୍ୟ ଭଲ ଥିଲା ନାହିଁ ଏବଂ ସେବା ମଧ୍ୟ ଭଲ ଥିଲା ନାହିଁ।", "Khaadya bhala thilaa naahiin ebam sebaa madhya bhala thilaa naahiin."],
            ["I neither like tea nor coffee.", "ମୋତେ ଚା ପସନ୍ଦ ନୁହେଁ ଏବଂ କଫି ମଧ୍ୟ ପସନ୍ଦ ନୁହେଁ।", "Mote chaa pasanda nuhein ebam coffee madhya pasanda nuhein."],
            ["Neither she sings nor dances.", "ସେ ଗାଏ ନାହିଁ ଏବଂ ନାଚେ ମଧ୍ୟ ନାହିଁ।", "Se gaae naahiin ebam naache madhya naahiin."],
            ["Neither the bus nor the train was on time.", "ବସ ସମୟରେ ଆସିଲା ନାହିଁ ଏବଂ ଟ୍ରେନ ମଧ୍ୟ ସମୟରେ ଆସିଲା ନାହିଁ।", "Bas samayare aasilaa naahiin ebam train madhya samayare aasilaa naahiin."],
            ["He is neither rich nor poor.", "ସେ ଧନୀ ନୁହେଁ ଏବଂ ଗରିବ ମଧ୍ୟ ନୁହେଁ।", "Se dhani nuhein ebam gariba madhya nuhein."],
            ["Neither the teacher nor the students were present.", "ଶିକ୍ଷକ ଉପସ୍ଥିତ ଥିଲେ ନାହିଁ ଏବଂ ଛାତ୍ର ମଧ୍ୟ ଉପସ୍ଥିତ ଥିଲେ ନାହିଁ।", "Shikshaka upasthita thile naahiin ebam chhaatra madhya upasthita thile naahiin."],
            ["Neither I agreed nor disagreed.", "ମୁଁ ରାଜି ହେଲି ନାହିଁ ଏବଂ ଅସମ୍ମତ ମଧ୍ୟ ହେଲି ନାହିଁ।", "Mun raaji heli naahiin ebam asammata madhya heli naahiin."],
            ["Neither hot nor cold, the weather is perfect.", "ଗରମ ନୁହେଁ ଏବଂ ଥଣ୍ଡା ମଧ୍ୟ ନୁହେଁ, ପାଗ ଠିକ ଅଛି।", "Garama nuhein ebam thandaa madhya nuhein, paag thik achhi."],
            ["Neither my mother nor my father was at home.", "ମୋ ମା ଘରେ ଥିଲେ ନାହିଁ ଏବଂ ବାପା ମଧ୍ୟ ଘରେ ଥିଲେ ନାହିଁ।", "Mo maa ghare thile naahiin ebam baapaa madhya ghare thile naahiin."],
            ["She neither smiled nor spoke.", "ସେ ହସିଲା ନାହିଁ ଏବଂ କଥା ମଧ୍ୟ କହିଲା ନାହିଁ।", "Se hasilaa naahiin ebam kathaa madhya kahilaa naahiin."],
            ["Neither the movie was good nor the acting.", "ସିନେମା ଭଲ ଥିଲା ନାହିଁ ଏବଂ ଅଭିନୟ ମଧ୍ୟ ଭଲ ଥିଲା ନାହିଁ।", "Sinemaa bhala thilaa naahiin ebam abhinaya madhya bhala thilaa naahiin."],
            ["He neither eats meat nor fish.", "ସେ ମାଂସ ଖାଏ ନାହିଁ ଏବଂ ମାଛ ମଧ୍ୟ ଖାଏ ନାହିଁ।", "Se maansa khaae naahiin ebam maachha madhya khaae naahiin."],
            ["Neither the pen nor the pencil is working.", "କଲମ କାମ କରୁନାହିଁ ଏବଂ ପେନସିଲ ମଧ୍ୟ କାମ କରୁନାହିଁ।", "Kalama kaama karunaahiin ebam pencil madhya kaama karunaahiin."],
            ["I will neither forgive nor forget.", "ମୁଁ କ୍ଷମା କରିବି ନାହିଁ ଏବଂ ଭୁଲିବି ମଧ୍ୟ ନାହିଁ।", "Mun kshamaa karibi naahiin ebam bhulibi madhya naahiin."],
            ["Neither his words nor actions matched.", "ତାଙ୍କ କଥା ମେଳ ଖାଇଲା ନାହିଁ ଏବଂ କାର୍ଯ୍ୟ ମଧ୍ୟ ମେଳ ଖାଇଲା ନାହିଁ।", "Taanka kathaa mela khaailaa naahiin ebam kaarya madhya mela khaailaa naahiin."],
            ["Neither money nor fame brought him happiness.", "ଟଙ୍କା ତାକୁ ଖୁସି ଦେଲା ନାହିଁ ଏବଂ ଯଶ ମଧ୍ୟ ଖୁସି ଦେଲା ନାହିଁ।", "Tankaa taaku khusi delaa naahiin ebam yasha madhya khusi delaa naahiin."],
            ["Neither this book nor that one is mine.", "ଏହି ବହି ମୋର ନୁହେଁ ଏବଂ ସେହି ବହି ମଧ୍ୟ ମୋର ନୁହେଁ।", "Ehi bahi mora nuhein ebam sehi bahi madhya mora nuhein."],
        ]
    },
    578: {
        "url": "\"The more...the more...\" Patterns in Odia",
        "rows": [
            ["The more you practice, the more you improve.", "ଯେତେ ଅଧିକ ଅଭ୍ୟାସ କରିବ, ସେତେ ଅଧିକ ଉନ୍ନତି ହେବ।", "Jete adhika abhyaas kariba, sete adhika unnati heba."],
            ["The more you eat, the more you gain weight.", "ଯେତେ ଅଧିକ ଖାଇବ, ସେତେ ଅଧିକ ଓଜନ ବଢ଼ିବ।", "Jete adhika khaaiba, sete adhika ojana badhiba."],
            ["The more I read, the more I learn.", "ଯେତେ ଅଧିକ ମୁଁ ପଢ଼େ, ସେତେ ଅଧିକ ଶିଖେ।", "Jete adhika mun padhe, sete adhika shikhe."],
            ["The more you share, the more you receive.", "ଯେତେ ଅଧିକ ବାଣ୍ଟିବ, ସେତେ ଅଧିକ ପାଇବ।", "Jete adhika baantiba, sete adhika paaiba."],
            ["The more he works, the more tired he feels.", "ଯେତେ ଅଧିକ ସେ କାମ କରେ, ସେତେ ଅଧିକ ଥକି ଯାଏ।", "Jete adhika se kaama kare, sete adhika thaki jaae."],
            ["The more you worry, the more problems increase.", "ଯେତେ ଅଧିକ ଚିନ୍ତା କରିବ, ସେତେ ଅଧିକ ସମସ୍ୟା ବଢ଼ିବ।", "Jete adhika chintaa kariba, sete adhika samasyaa badhiba."],
            ["The more you save, the more secure your future.", "ଯେତେ ଅଧିକ ସଞ୍ଚୟ କରିବ, ସେତେ ଅଧିକ ଭବିଷ୍ୟତ ସୁରକ୍ଷିତ।", "Jete adhika sanchaya kariba, sete adhika bhabishhyata surakshita."],
            ["The more she smiled, the more everyone liked her.", "ଯେତେ ଅଧିକ ସେ ହସେ, ସେତେ ଅଧିକ ସମସ୍ତେ ତାକୁ ପସନ୍ଦ କରନ୍ତି।", "Jete adhika se hase, sete adhika samaste taaku pasanda karanti."],
            ["The more you travel, the more you understand the world.", "ଯେତେ ଅଧିକ ଯାତ୍ରା କରିବ, ସେତେ ଅଧିକ ଦୁନିଆକୁ ବୁଝିବ।", "Jete adhika jaatraa kariba, sete adhika duniaaku bujhiba."],
            ["The more he spoke, the more confused I became.", "ଯେତେ ଅଧିକ ସେ କହିଲା, ସେତେ ଅଧିକ ମୁଁ ବିଭ୍ରାନ୍ତ ହେଲି।", "Jete adhika se kahilaa, sete adhika mun bibhraanta heli."],
            ["The more we waited, the longer it took.", "ଯେତେ ଅଧିକ ଆମେ ଅପେକ୍ଷା କଲୁ, ସେତେ ଅଧିକ ସମୟ ଲାଗିଲା।", "Jete adhika aame apekshaa kalu, sete adhika samaya laagila."],
            ["The more kindness you show, the more you get in return.", "ଯେତେ ଅଧିକ ଦୟା ଦେଖାଇବ, ସେତେ ଅଧିକ ଫେରି ପାଇବ।", "Jete adhika dayaa dekhaiba, sete adhika pheri paaiba."],
            ["The more I think, the more confused I get.", "ଯେତେ ଅଧିକ ମୁଁ ଭାବେ, ସେତେ ଅଧିକ ବିଭ୍ରାନ୍ତ ହୁଏ।", "Jete adhika mun bhaabe, sete adhika bibhraanta hue."],
            ["The more you listen, the more you understand.", "ଯେତେ ଅଧିକ ଶୁଣିବ, ସେତେ ଅଧିକ ବୁଝିବ।", "Jete adhika shuniba, sete adhika bujhiba."],
            ["The more you give, the more blessed you feel.", "ଯେତେ ଅଧିକ ଦିଅ, ସେତେ ଅଧିକ ଧନ୍ୟ ଅନୁଭବ ହୁଏ।", "Jete adhika dia, sete adhika dhanya anubhaba hue."],
            ["The more it rained, the more the river rose.", "ଯେତେ ଅଧିକ ବର୍ଷା ହେଲା, ସେତେ ଅଧିକ ନଦୀ ବଢ଼ିଲା।", "Jete adhika barshaa helaa, sete adhika nadii badhilaa."],
            ["The more patient you are, the better the result.", "ଯେତେ ଅଧିକ ଧୈର୍ଯ୍ୟ ଧରିବ, ସେତେ ଭଲ ଫଳାଫଳ ମିଳିବ।", "Jete adhika dhairya dhariba, sete bhala phalaphal milibaa."],
            ["The more you laugh, the healthier you stay.", "ଯେତେ ଅଧିକ ହସିବ, ସେତେ ଅଧିକ ସୁସ୍ଥ ରହିବ।", "Jete adhika hasiba, sete adhika sustha rahiba."],
        ]
    },
}

with open(DATA_FILE, "r", encoding="utf-8") as f:
    data = json.load(f)

updated_count = 0
for entry in data:
    eid = entry["id"]
    if eid in lessons:
        lesson = lessons[eid]
        entry["url"] = lesson["url"]
        entry["blocks"] = [
            {
                "type": "table",
                "columns": ["English", "Odia", "Transliteration"],
                "rows": lesson["rows"]
            }
        ]
        updated_count += 1
        print(f"  [OK] ID {eid}: {lesson['url']} — {len(lesson['rows'])} rows")

with open(DATA_FILE, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"\nDone! Updated {updated_count}/18 lessons (IDs 561-578) in {DATA_FILE}.")
