// Auto-generated from lesson JSON — Phrases & Words tabs
const PUNJABI_PHRASES = {
  greetings_1: {
    name: "Greetings",
    color: "#2B6CB0",
    icon: "👋",
    phrases: [
      { en: "The road is broken.", mr: "ਸੜਕ ਟੁੱਟ ਗਈ ਹੈ।", roman: "saṛak ṭuṭ gaī hai.", hint: "" },
      { en: "This village is small.", mr: "ਇਹ ਪਿੰਡ ਛੋਟਾ ਹੈ।", roman: "ih piṇḍ chhoṭā hai.", hint: "" },
      { en: "We will work today.", mr: "ਅੱਜ ਅਸੀਂ ਕੰਮ ਕਰਾਂਗੇ।", roman: "ajj asī̃ kam karā̃gē.", hint: "" },
      { en: "He got good health.", mr: "ਉਸ ਦੀ ਸਿਹਤ ਚੰਗੀ ਹੈ।", roman: "us dī sihat changī hai.", hint: "" },
      { en: "Service to others is good.", mr: "ਦੂਜਿਆਂ ਦੀ ਸੇਵਾ ਚੰਗੀ ਹੈ।", roman: "dūjiā̃ dī sēvā changī hai.", hint: "" },
      { en: "Close the door softly.", mr: "ਦਰਵਾਜ਼ਾ ਹੌਲੀ ਹੌਲੀ ਬੰਦ ਕਰ।", roman: "darvāzā haulī haulī band kar.", hint: "" },
      { en: "The ghost is only a story.", mr: "ਭੂਤ ਸਿਰਫ਼ ਕਹਾਣੀ ਹੈ।", roman: "bhūt sirf kahāṇī hai.", hint: "" },
      { en: "Efforts never go waste.", mr: "ਯਤਨ ਕਦੇ ਵਿਅਰਥ ਨਹੀਂ ਜਾਂਦੇ।", roman: "yatan kadē viarth nahī̃ jāndē.", hint: "" },
      { en: "You (polite) are my teacher.", mr: "ਤੁਸੀਂ ਮੇਰੇ ਅਧਿਆਪਕ ਹੋ।", roman: "tusī̃ mērē adhiāpək ho.", hint: "" },
      { en: "That is your house.", mr: "ਉਹ ਤੇਰਾ ਘਰ ਹੈ।", roman: "uh tērā ghar hai.", hint: "" },
      { en: "Those are the same people.", mr: "ਉਹਨਾਂ ਓਹੀ ਲੋਕ ਹਨ।", roman: "uhnān ohī lōk han.", hint: "" },
      { en: "Sir, where are you from?", mr: "ਸਰ, ਤੁਸੀਂ ਕਿੱਥੋਂ ਹੋ?", roman: "sar, tusī̃ kithō̃ ho?", hint: "" },
      { en: "Sir, will you come tomorrow?", mr: "ਸਰ, ਤੁਸੀਂ ਕੱਲ੍ਹ ਆਵੋਗੇ?", roman: "sar, tusī̃ kallh āvōgē?", hint: "" },
      { en: "We eat food together.", mr: "ਅਸੀਂ ਇਕੱਠੇ ਖਾਣਾ ਖਾਂਦੇ ਹਾਂ।", roman: "asī̃ ikaṭṭhē khāṇā khā̃dē hā̃.", hint: "" },
      { en: "I see that house.", mr: "ਮੈਂ ਉਹ ਘਰ ਦੇਖਦਾ ਹਾਂ।", roman: "maĩ uh ghar dēkhdā hā̃.", hint: "" },
      { en: "She lives in that village.", mr: "ਉਹ ਉਸ ਪਿੰਡ ਵਿੱਚ ਰਹਿੰਦੀ ਹੈ।", roman: "uh us piṇḍ vich rahindī hai.", hint: "" },
    ]
  },
  travel_1: {
    name: "Travel",
    color: "#38A169",
    icon: "🚌",
    phrases: [
      { en: "The ladder is long.", mr: "ਸੀੜ੍ਹੀ ਲੰਮੀ ਹੈ।", roman: "sīṛhī laṃmī hai.", hint: "" },
      { en: "The city is big.", mr: "ਸ਼ਹਿਰ ਵੱਡਾ ਹੈ।", roman: "śahar vaḍḍā hai.", hint: "" },
      { en: "The company is big.", mr: "ਕੰਪਨੀ ਵੱਡੀ ਹੈ।", roman: "kampanī vaḍḍī hai.", hint: "" },
      { en: "God's grace is great.", mr: "ਵਾਹਿਗੁਰੂ ਦੀ ਕਿਰਪਾ ਵੱਡੀ ਹੈ।", roman: "vāhigurū dī kirpā vaḍḍī hai.", hint: "" },
      { en: "He showed great courage.", mr: "ਉਸ ਨੇ ਵੱਡੀ ਹਿੰਮਤ ਦਿਖਾਈ।", roman: "us nē vaḍḍī himmat dikhāī.", hint: "" },
      { en: "The elephant is big.", mr: "ਹਾਥੀ ਵੱਡਾ ਹੈ।", roman: "hāthī vaḍḍā hai.", hint: "" },
      { en: "Our family is big.", mr: "ਸਾਡਾ ਪਰਿਵਾਰ ਵੱਡਾ ਹੈ।", roman: "sāḍā parivār vaḍḍā hai.", hint: "" },
      { en: "He sent a message.", mr: "ਉਸ ਨੇ ਸੰਦੇਸ਼ ਭੇਜਿਆ।", roman: "us nē sandēś bhējīā.", hint: "" },
      { en: "He is my brother.", mr: "ਉਹ ਮੇਰਾ ਭਰਾ ਹੈ।", roman: "uh mērā bhrā hai.", hint: "" },
      { en: "These are our children.", mr: "ਇਹਨਾਂ ਸਾਡੇ ਬੱਚੇ ਹਨ।", roman: "ihnān sāḍē bachē han.", hint: "" },
      { en: "You were at home.", mr: "ਤੂੰ ਘਰ ਸੀ।", roman: "ਤੁਸੀਂ ਘਰ ਸਨ।", hint: "" },
      { en: "Grandmother, have you eaten?", mr: "ਦਾਦੀ ਜੀ, ਤੁਸੀਂ ਖਾਣਾ ਖਾਦਾ?", roman: "dādī jī, tusī̃ khāṇā khādā?", hint: "" },
      { en: "Madam, do you need help?", mr: "ਮੈਡਮ, ਤੁਹਾਨੂੰ ਮਦਦ ਚਾਹੀਦੀ ਹੈ?", roman: "maeḍam, tuhānū̃ madad cāhīdī hai?", hint: "" },
      { en: "He drinks milk in the morning.", mr: "ਉਹ ਸਵੇਰੇ ਦੁੱਧ ਪੀਂਦਾ ਹੈ।", roman: "uh savērē duddh pī̃dā hai.", hint: "" },
      { en: "They take the bus.", mr: "ਉਹਨਾਂ ਬੱਸ ਲੈਂਦੇ ਹਨ।", roman: "uhnān bass laĩdē han.", hint: "" },
      { en: "We study every day.", mr: "ਅਸੀਂ ਹਰ ਰੋਜ਼ ਪੜ੍ਹਦੇ ਹਾਂ।", roman: "asī̃ har rōz paṛhḍē hā̃.", hint: "" },
    ]
  },
  food_1: {
    name: "Food",
    color: "#DD6B20",
    icon: "🍛",
    phrases: [
      { en: "The boy is clever.", mr: "ਮੁੰਡਾ ਸਿਆਣਾ ਹੈ।", roman: "muṇḍā siyāṇā hai.", hint: "" },
      { en: "The heart is strong.", mr: "ਦਿਲ ਮਜ਼ਬੂਤ ਹੈ।", roman: "dil mazbūt hai.", hint: "" },
      { en: "The stone is heavy.", mr: "ਪੱਥਰ ਭਾਰੀ ਹੈ।", roman: "pathar bhārī hai.", hint: "" },
      { en: "The teacher is strict.", mr: "ਅਧਿਆਪਕ ਸਖ਼ਤ ਹੈ।", roman: "adhiāpək sakhat hai.", hint: "" },
      { en: "This is a big blessing.", mr: "ਇਹ ਵੱਡਾ ਵਰਦਾਨ ਹੈ।", roman: "ih vaḍḍā vardān hai.", hint: "" },
      { en: "The field is green.", mr: "ਖੇਤ ਹਰੇ ਹਨ।", roman: "khēt harē han.", hint: "" },
      { en: "The government made a decision.", mr: "ਸਰਕਾਰ ਨੇ ਫੈਸਲਾ ਕੀਤਾ ਹੈ।", roman: "sarkār nē phaislā kītā hai.", hint: "" },
      { en: "They have strong relations.", mr: "ਉਹਨਾਂ ਦੇ ਮਜ਼ਬੂਤ ਸੰਬੰਧ ਹਨ।", roman: "uhnān dē mazbūt sambandh han.", hint: "" },
      { en: "She is my sister.", mr: "ਉਹ ਮੇਰੀ ਭੈਣ ਹੈ।", roman: "uh mērī bhaiਣ hai.", hint: "" },
      { en: "Those are their friends.", mr: "ਉਹਨਾਂ ਉਹਨਾਂ ਦੇ ਦੋਸਤ ਹਨ।", roman: "uhnān uhnān dē dōst han.", hint: "" },
      { en: "You did this work.", mr: "ਤੂੰ ਇਹ ਕੰਮ ਕੀਤਾ।", roman: "ਤੁਸੀਂ ਇਹ ਕੰਮ ਕੀਤਾ ਹੈ।", hint: "" },
      { en: "Uncle, are you fine?", mr: "ਚਾਚਾ ਜੀ, ਤੁਸੀਂ ਠੀਕ ਹੋ?", roman: "cācā jī, tusī̃ ṭhīk ho?", hint: "" },
      { en: "Elder brother, please listen.", mr: "ਵੱਡੇ ਭਰਾ, ਤੁਸੀਂ ਸੁਣੋ ਜੀ।", roman: "vaḍḍē bhrā, tusī̃ suṇō jī.", hint: "" },
      { en: "They read books at night.", mr: "ਉਹਨਾਂ ਰਾਤ ਨੂੰ ਕਿਤਾਬਾਂ ਪੜ੍ਹਦੇ ਹਨ।", roman: "uhnān rāt nū̃ kitābā̃ paṛhḍē han.", hint: "" },
      { en: "I wake up at six.", mr: "ਮੈਂ ਛੇ ਵਜੇ ਜਾਗਦਾ ਹਾਂ।", roman: "maĩ chhē vajē jāgdā hā̃.", hint: "" },
      { en: "They watch TV at night.", mr: "ਉਹਨਾਂ ਰਾਤ ਨੂੰ ਟੀਵੀ ਵੇਖਦੇ ਹਨ।", roman: "uhnān rāt nū̃ ṭīvī vēkhdē han.", hint: "" },
    ]
  },
  daily_1: {
    name: "Daily life",
    color: "#805AD5",
    icon: "🏠",
    phrases: [
      { en: "My teeth are hurting.", mr: "ਮੇਰੇ ਦੰਦ ਦਰਦ ਕਰ ਰਹੇ ਹਨ।", roman: "mērē dand dard kar rahē han.", hint: "" },
      { en: "I live in this village.", mr: "ਮੈਂ ਇਸ ਪਿੰਡ ਵਿਚ ਰਹਿੰਦਾ ਹਾਂ।", roman: "maĩ is piṇḍ vic rahindā hā̃.", hint: "" },
      { en: "I study in this school.", mr: "ਮੈਂ ਇਸ ਸਕੂਲ ਵਿੱਚ ਪੜ੍ਹਦਾ ਹਾਂ।", roman: "maĩ is sakūl vich paṛhdā hā̃.", hint: "" },
      { en: "Close the door slowly.", mr: "ਦਰਵਾਜ਼ਾ ਹੌਲੀ ਹੌਲੀ ਬੰਦ ਕਰ।", roman: "darvāzā haulī haulī band kar.", hint: "" },
      { en: "The work started with God's name.", mr: "ਕੰਮ ਵਾਹਿਗੁਰੂ ਦੇ ਨਾਮ ਨਾਲ ਸ਼ੁਰੂ ਹੋਇਆ।", roman: "kam vāhigurū dē nām nāl śurū hōiā.", hint: "" },
      { en: "The price is high.", mr: "ਦਾਮ ਜ਼ਿਆਦਾ ਹੈ।", roman: "dām ziyādā hai.", hint: "" },
      { en: "Hard work brings progress.", mr: "ਮਿਹਨਤ ਤਰੱਕੀ ਲਿਆਉਂਦੀ ਹੈ।", roman: "mihanat tarakkī liāũdī hai.", hint: "" },
      { en: "he / she / that person", mr: "ਉਹ", roman: "uh", hint: "" },
      { en: "We are from this village.", mr: "ਅਸੀਂ ਇਸ ਪਿੰਡ ਤੋਂ ਹਾਂ।", roman: "asī̃ is piṇḍ tō̃ hā̃.", hint: "" },
      { en: "This is a pen.", mr: "ਇਹ ਇੱਕ ਕਲਮ ਹੈ।", roman: "ih ikk kalam hai.", hint: "" },
      { en: "He was sitting here.", mr: "ਉਹ ਇੱਥੇ ਬੈਠਾ ਸੀ।", roman: "ਉਹਨਾਂ ਇੱਥੇ ਬੈਠੇ ਸਨ।", hint: "" },
      { en: "Teacher, please sit here.", mr: "ਅਧਿਆਪਕ ਜੀ, ਤੁਸੀਂ ਇੱਥੇ ਬੈਠੋ।", roman: "adhiāpək jī, tusī̃ ithē baiṭhō.", hint: "" },
      { en: "Doctor, what should we do?", mr: "ਡਾਕਟਰ ਸਾਹਿਬ, ਅਸੀਂ ਕੀ ਕਰੀਏ?", roman: "ḍākṭar sāhib, asī̃ kī karīē?", hint: "" },
      { en: "I write in Punjabi.", mr: "ਮੈਂ ਪੰਜਾਬੀ ਵਿੱਚ ਲਿਖਦਾ ਹਾਂ।", roman: "maĩ pañjābī vich likhdā hā̃.", hint: "" },
      { en: "I (m) go / I (f) go", mr: "ਮੈਂ ਜਾਂਦਾ ਹਾਂ / ਮੈਂ ਜਾਂਦੀ ਹਾਂ", roman: "maĩ jāndā hā̃ / maĩ jāndī hā̃", hint: "" },
      { en: "You (pl) come here daily.", mr: "ਤੁਸੀਂ ਹਰ ਰੋਜ਼ ਇੱਥੇ ਆਉਂਦੇ ਹੋ।", roman: "tusī̃ har rōz ithē āũdē ho.", hint: "" },
    ]
  },
  shopping_1: {
    name: "Shopping",
    color: "#D69E2E",
    icon: "🛒",
    phrases: [
      { en: "The weather is very cold.", mr: "ਮੌਸਮ ਬਹੁਤ ਠੰਢਾ ਹੈ।", roman: "mausam bahut ṭhaṇḍā hai.", hint: "" },
      { en: "My nose is blocked.", mr: "ਮੇਰੀ ਨੱਕ ਬੰਦ ਹੈ।", roman: "mērī nakk band hai.", hint: "" },
      { en: "We respect our elders.", mr: "ਅਸੀਂ ਆਪਣੇ ਵੱਡਿਆਂ ਦਾ ਆਦਰ ਕਰਦੇ ਹਾਂ।", roman: "asī̃ āpṇē vaḍḍiā̃ dā ādar kardē hā̃.", hint: "" },
      { en: "This street is narrow.", mr: "ਇਹ ਗਲੀ ਤੰਗ ਹੈ।", roman: "ih galī taṅg hai.", hint: "" },
      { en: "to tie / to sneeze", mr: "ਬੰਨ੍ਹਣਾ", roman: "bannhṇā", hint: "" },
      { en: "The bridge is long.", mr: "ਪੁੱਲ ਲੰਮਾ ਹੈ।", roman: "pull laṃmā hai.", hint: "" },
      { en: "We should respect elders.", mr: "ਸਾਨੂੰ ਬਜ਼ੁਰਗਾਂ ਦੀ ਸ੍ਰਧਾ ਕਰਨੀ ਚਾਹੀਦੀ ਹੈ।", roman: "sānū̃ bazurgā̃ dī sraddhā karnī cāhīdī hai.", hint: "" },
      { en: "I am a student.", mr: "ਮੈਂ ਵਿਦਿਆਰਥੀ ਹਾਂ।", roman: "maĩ vidiārthī hā̃.", hint: "" },
      { en: "They are in that city.", mr: "ਉਹਨਾਂ ਉਸ ਸ਼ਹਿਰ ਵਿੱਚ ਹਨ।", roman: "uhnān us śahar vich han.", hint: "" },
      { en: "That is a school.", mr: "ਉਹ ਇੱਕ ਸਕੂਲ ਹੈ।", roman: "uh ikk sakūl hai.", hint: "" },
      { en: "He will go tomorrow.", mr: "ਉਹ ਕੱਲ੍ਹ ਜਾਵੇਗਾ।", roman: "ਉਹਨਾਂ ਕੱਲ੍ਹ ਜਾਣਗੇ।", hint: "" },
      { en: "Where did you all study?", mr: "ਤੁਸੀਂ ਕਿੱਥੇ ਪੜ੍ਹੇ ਹੋ?", roman: "tusī̃ kithē paṛhē ho?", hint: "" },
      { en: "I go to school every day.", mr: "ਮੈਂ ਹਰ ਰੋਜ਼ ਸਕੂਲ ਜਾਂਦਾ ਹਾਂ।", roman: "maĩ har rōz sakūl jāndā hā̃.", hint: "" },
      { en: "The children sit here.", mr: "ਬੱਚੇ ਇੱਥੇ ਬੈਠਦੇ ਹਨ।", roman: "bachē ithē baiṭhdē han.", hint: "" },
      { en: "He goes / She goes", mr: "ਉਹ ਜਾਂਦਾ ਹੈ / ਉਹ ਜਾਂਦੀ ਹੈ", roman: "uh jāndā hai / uh jāndī hai", hint: "" },
      { en: "The shop opens at nine.", mr: "ਦੁਕਾਨ ਨੌਂ ਵਜੇ ਖੁੱਲਦੀ ਹੈ।", roman: "dukān naũ vajē khulldī hai.", hint: "" },
    ]
  },
  emergency_1: {
    name: "Emergency",
    color: "#E53E3E",
    icon: "🚨",
    phrases: [
      { en: "The lock is old.", mr: "ਤਾਲਾ ਪੁਰਾਣਾ ਹੈ।", roman: "tālā purāṇā hai.", hint: "" },
      { en: "The colour is dark.", mr: "ਰੰਗ ਗੂੜ੍ਹਾ ਹੈ।", roman: "raṅg gūṛhā hai.", hint: "" },
      { en: "He is making progress.", mr: "ਉਹ ਤਰੱਕੀ ਕਰ ਰਿਹਾ ਹੈ।", roman: "uh tarakkī kar rihā hai.", hint: "" },
      { en: "Have faith in yourself.", mr: "ਆਪਣੇ ਉੱਤੇ ਭਰੋਸਾ ਰੱਖ।", roman: "āpaṇē uttē bharōsā rakh.", hint: "" },
      { en: "He is very hungry.", mr: "ਉਹ ਬਹੁਤ ਭੁੱਖਾ ਹੈ।", roman: "uh bahut bhukkhā hai.", hint: "" },
      { en: "He got an injury.", mr: "ਉਹਨੂੰ ਘਾਅ ਲੱਗਿਆ।", roman: "uhnū̃ ghāa laggiā.", hint: "" },
      { en: "This is God's blessing.", mr: "ਇਹ ਵਾਹਿਗੁਰੂ ਦਾ ਪ੍ਰਸਾਦ ਹੈ।", roman: "ih vāhigurū dā prasād hai.", hint: "" },
      { en: "You are my friend.", mr: "ਤੂੰ ਮੇਰਾ ਦੋਸਤ ਹੈਂ।", roman: "tū̃ mērā dōst haĩ.", hint: "" },
      { en: "This is my book.", mr: "ਇਹ ਮੇਰੀ ਕਿਤਾਬ ਹੈ।", roman: "ih mērī kitāਬ hai.", hint: "" },
      { en: "This is the same car.", mr: "ਇਹ ਓਹੀ ਗੱਡੀ ਹੈ।", roman: "ih ohī gaḍḍī hai.", hint: "" },
      { en: "He is our teacher.", mr: "ਉਹ ਸਾਡਾ ਅਧਿਆਪਕ ਹੈ।", roman: "ਉਹਨਾਂ ਸਾਡੇ ਅਧਿਆਪਕ ਹਨ।", hint: "" },
      { en: "Have you all seen this?", mr: "ਤੁਸੀਂ ਇਹ ਦੇਖਿਆ ਹੈ?", roman: "tusī̃ ih dēkhiā hai?", hint: "" },
      { en: "She comes home in the evening.", mr: "ਉਹ ਸ਼ਾਮ ਨੂੰ ਘਰ ਆਉਂਦੀ ਹੈ।", roman: "uh śām nū̃ ghar āũdī hai.", hint: "" },
      { en: "He works in the city.", mr: "ਉਹ ਸ਼ਹਿਰ ਵਿੱਚ ਕੰਮ ਕਰਦਾ ਹੈ।", roman: "uh śahar vich kam kardā hai.", hint: "" },
      { en: "I live in this city.", mr: "ਮੈਂ ਇਸ ਸ਼ਹਿਰ ਵਿੱਚ ਰਹਿੰਦਾ ਹਾਂ।", roman: "maĩ is śahar vich rahindā hā̃.", hint: "" },
      { en: "The bus arrives on time.", mr: "ਬੱਸ ਸਮੇਂ ਤੇ ਆਉਂਦੀ ਹੈ।", roman: "bass samē̃ tē āũdī hai.", hint: "" },
    ]
  },
};

const PUNJABI_DICTIONARY = {
  basics_1: {
    name: "Basic words",
    words: [
      { en: "God (Waheguru)", mr: "ਵਾਹਿਗੁਰੂ", roman: "vāhigurū" },
      { en: "flying", mr: "ਉੱਡਣਾ", roman: "uḍṇā" },
      { en: "room", mr: "ਕਮਰਾ", roman: "kamrā" },
      { en: "city", mr: "ਸ਼ਹਿਰ", roman: "śahar" },
      { en: "girl", mr: "ਕੁੜੀ", roman: "kuṛī" },
      { en: "school", mr: "ਸਕੂਲ", roman: "sakūl" },
      { en: "work", mr: "ਕੰਮ", roman: "kam" },
      { en: "hand", mr: "ਹੱਥ", roman: "hath" },
      { en: "equal", mr: "ਸਮਾਨ", roman: "samān" },
      { en: "head", mr: "ਸਿਰ", roman: "sir" },
      { en: "drink", mr: "ਪੀਣਾ", roman: "pīṇā" },
      { en: "buffalo", mr: "ਭੈਸ", roman: "bhais" },
      { en: "daughter", mr: "ਧੀ", roman: "dhī" },
      { en: "tooth", mr: "ਦੰਦ", roman: "dand" },
      { en: "ladder", mr: "ਸੀੜ੍ਹੀ", roman: "sīṛhī" },
      { en: "moment", mr: "ਪਲੰਕ", roman: "pałaṅk" },
    ]
  },
  family_1: {
    name: "Family",
    words: [
      { en: "come", mr: "ਆਓ", roman: "āo" },
      { en: "camel", mr: "ਊਠ", roman: "ūṭh" },
      { en: "crow", mr: "ਕਾਂ", roman: "kā̃" },
      { en: "river", mr: "ਨਦੀ", roman: "nadī" },
      { en: "home", mr: "ਘਰ", roman: "ghar" },
      { en: "water", mr: "ਪਾਣੀ", roman: "pāṇī" },
      { en: "market", mr: "ਬਾਜ਼ਾਰ", roman: "bāzār" },
      { en: "eye", mr: "ਅੱਖ", roman: "akh" },
      { en: "path", mr: "ਰਾਹ", roman: "rāh" },
      { en: "write", mr: "ਲਿਖਣਾ", roman: "likhṇā" },
      { en: "sleep", mr: "ਸੌਣਾ", roman: "sauṇā" },
      { en: "cloth", mr: "ਕੱਪੜਾ", roman: "kappaṛā" },
      { en: "language", mr: "ਭਾਸ਼ਾ", roman: "bhāśā" },
      { en: "number three", mr: "ਤਿੰਨ", roman: "tinn" },
      { en: "okra (lady finger)", mr: "ਭਿੰਡੀ", roman: "bhiṇḍī" },
      { en: "company", mr: "ਕੰਪਨੀ", roman: "kampanī" },
    ]
  },
  verbs_1: {
    name: "Common verbs",
    words: [
      { en: "this", mr: "ਇਹ", roman: "ih" },
      { en: "country", mr: "ਦੇਸ਼", roman: "dēś" },
      { en: "noise", mr: "ਸ਼ੋਰ", roman: "śōr" },
      { en: "flower", mr: "ਫੁੱਲ", roman: "phull" },
      { en: "door", mr: "ਦਰਵਾਜ਼ਾ", roman: "darvāzā" },
      { en: "milk", mr: "ਦੂਧ", roman: "dūdh" },
      { en: "road", mr: "ਸੜਕ", roman: "saṛak" },
      { en: "crow (with k sound)", mr: "ਕਾਂ", roman: "kā̃" },
      { en: "king", mr: "ਰਾਜਾ", roman: "rājā" },
      { en: "read", mr: "ਪੜ੍ਹਣਾ", roman: "paṛhṇā" },
      { en: "paper", mr: "ਕਾਗਜ਼", roman: "kāgaz" },
      { en: "kitchen", mr: "ਰਸੋਈ", roman: "rasōī" },
      { en: "teacher", mr: "ਅਧਿਆਪਕ", roman: "adhiāpək" },
      { en: "pond", mr: "ਟੱਲਾ", roman: "ṭallā" },
      { en: "heart", mr: "ਦਿਲ", roman: "dil" },
      { en: "inside", mr: "ਅੰਦਰੋਂ", roman: "andarō̃" },
    ]
  },
  nature_1: {
    name: "Nature",
    words: [
      { en: "sugarcane juice", mr: "ਈਖ ਦਾ ਰਸ", roman: "īkh dā ras" },
      { en: "elder sister", mr: "ਐਨੀ", roman: "ainī" },
      { en: "village", mr: "ਪਿੰਡ", roman: "piṇḍ" },
      { en: "boy", mr: "ਮੁੰਡਾ", roman: "muṇḍā" },
      { en: "book", mr: "ਕਿਤਾਬ", roman: "kitāb" },
      { en: "friend", mr: "ਦੋਸਤ", roman: "dōst" },
      { en: "time", mr: "ਸਮਾਂ", roman: "samā̃" },
      { en: "grass (with kh sound)", mr: "ਖਾਹ", roman: "khāh" },
      { en: "body", mr: "ਸਰੀਰ", roman: "sarīr" },
      { en: "eat", mr: "ਖਾਣਾ", roman: "khāṇā" },
      { en: "farm", mr: "ਖੇਤ", roman: "khēt" },
      { en: "weather", mr: "ਮੌਸਮ", roman: "mausam" },
      { en: "cold (weather)", mr: "ਠੰਢ", roman: "ṭhaṇḍh" },
      { en: "lock", mr: "ਤਾਲਾ", roman: "tālā" },
      { en: "Close the door.", mr: "ਦਰਵਾਜ਼ਾ ਬੰਦ ਕਰ।", roman: "darvāzā band kar." },
      { en: "colour", mr: "ਰੰਗ", roman: "rang" },
    ]
  },
};
