# Sanskrit Lesson 2 — chunk B (chapter IDs 527–542).

LESSONS_S2B = {
    527: [
        ["my book", "मम पुस्तकम्", "mama pustakam"],
        ["your (sg.) book", "तव पुस्तकम्", "tava pustakam"],
        ["his house", "तस्य गृहम्", "tasya gṛham"],
        ["her mother", "तस्याः माता", "tasyāḥ mātā"],
        ["our school", "अस्माकं विद्यालयः", "asmākaṃ vidyālayaḥ"],
        ["their field", "तेषां क्षेत्रम्", "teṣāṃ kṣetram"],
        ["my father", "मम पिता", "mama pitā"],
        ["your (respect) work", "भवतः कार्यम्", "bhavataḥ kāryam"],
        ["his name", "तस्य नाम", "tasya nāma"],
        ["her friend", "तस्याः मित्रम्", "tasyāḥ mitram"],
        ["This is mine", "इदं मम अस्ति", "idaṃ mama asti"],
        ["That is yours", "तत् तव अस्ति", "tat tava asti"],
        ["Possessive pronouns agree in sense", "मम तव शब्दाः अर्थे युज्यन्ते", "mama tava śabdāḥ arthe yujyante"],
        ["Our teacher is kind", "अस्माकं आचार्यः दयालुः अस्ति", "asmākaṃ ācāryaḥ dayāluḥ asti"],
        ["Their village is far", "तेषां ग्रामः दूरम् अस्ति", "teṣāṃ grāmaḥ dūram asti"],
        ["Whose pen is this?", "इदं कस्य लेखनी अस्ति?", "idaṃ kasya lekhanī asti?"],
    ],
    528: [
        ["What is this?", "इदं किम्?", "idaṃ kim?"],
        ["Who is he?", "सः कः?", "saḥ kaḥ?"],
        ["Where is the book?", "कुत्र पुस्तकम्?", "kutra pustakam?"],
        ["When will you come?", "कदा आगमिष्यसि?", "kadā āgamiṣyasi?"],
        ["Why are you sad?", "किमर्थं दुःखी भवसि?", "kimarthaṃ duḥkhī bhavasi?"],
        ["How do you read?", "कथं पठसि?", "kathaṃ paṭhasi?"],
        ["Which is your seat?", "कियत् तव आसनम्?", "kiyat tava āsanam?"],
        ["How many boys?", "कति बालकाः?", "kati bālakāḥ?"],
        ["Tell me where", "कुत्र इति वदतु", "kutra iti vadata"],
        ["I do not know why", "न जानामि किमर्थम्", "na jānāmi kimartham"],
        ["Is this true?", "इदं सत्यम्?", "idaṃ satyam?"],
        ["Who came?", "कः आगच्छत्?", "kaḥ āgacchat?"],
        ["What did you say?", "किम् अवदः?", "kim avadaḥ?"],
        ["Where shall we go?", "कुत्र गमिष्यामः?", "kutra gamiṣyāmaḥ?"],
        ["Question words take sandhi", "प्रश्नशब्दाः सन्धिं गृह्णन्ति", "praśnaśabdāḥ sandhiṃ gṛhṇanti"],
        ["Practice question intonation", "प्रश्नस्य उच्चारणं अभ्यस्यतु", "praśnasya uccāraṇaṃ abhyasyatu"],
    ],
    529: [
        ["I do not go", "अहं न गच्छामि", "ahaṃ na gacchāmi"],
        ["he does not speak", "सः न वदति", "saḥ na vadati"],
        ["she does not eat", "सा न अश्नाति", "sā na aśnāti"],
        ["we do not know", "वयं न जानीमः", "vayaṃ na jānīmaḥ"],
        ["they do not come", "ते न आगच्छन्ति", "te na āgacchanti"],
        ["There is no water", "जलं न अस्ति", "jalaṃ na asti"],
        ["I never lie", "अहं न अनृतं वदामि", "ahaṃ na anṛtaṃ vadāmi"],
        ["Do not run", "मा धाव", "mā dhāva"],
        ["He is not here", "सः इह न अस्ति", "saḥ iha na asti"],
        ["We are not afraid", "वयं न बिभीमः", "vayaṃ na bibhīmaḥ"],
        ["No one came", "कोऽपि न आगच्छत्", "ko'pi na āgacchat"],
        ["She does not like it", "सा न रोचते", "sā na rocate"],
        ["I need nothing", "मम किञ्चित् न आवश्यकम्", "mama kiñcit na āvaśyakam"],
        ["They do not agree", "ते न सम्मन्यन्ते", "te na sammanyante"],
        ["Not today", "न अद्य", "na adya"],
        ["Negation with न is most common", "न-निषेधः सर्वाधिकः", "na-niṣedhaḥ sarvādhikaḥ"],
    ],
    530: [
        ["I did not see", "अहं न अपश्यम्", "ahaṃ na apaśyam"],
        ["he did not come", "सः न आगच्छत्", "saḥ na āgacchat"],
        ["we did not go", "वयं न अगच्छाम", "vayaṃ na agacchāma"],
        ["they did not listen", "ते न अशृण्वन्", "te na aśṛṇvan"],
        ["she did not write", "सा न अलिखत्", "sā na alikhat"],
        ["There was no time", "समयः न आसीत्", "samayaḥ na āsīt"],
        ["I knew nothing", "अहं किञ्चित् न अजानाम्", "ahaṃ kiñcit na ajānām"],
        ["He could not walk", "सः न अगच्छत्", "saḥ na agacchat"],
        ["We did not finish", "वयं न समाप्तवन्तः", "vayaṃ na samāptavantaḥ"],
        ["Nobody helped", "कोऽपि न साहाय्यम् अकरोत्", "ko'pi na sāhāyyam akarot"],
        ["It did not rain", "वर्षणं न आसीत्", "varṣaṇaṃ na āsīt"],
        ["I did not say that", "अहं तत् न अवदम्", "ahaṃ tat na avadam"],
        ["They were not there", "ते तत्र न आसन्", "te tatra na āsan"],
        ["She did not agree", "सा न अङ्गीकरोत्", "sā na aṅgīkarot"],
        ["Past negation with न + past verb", "न + लुङ्/लङ्", "na + luṅ/laṅ"],
        ["Practice: न अगमम्, न अपश्यम्", "न अगमम् न अपश्यम्", "na agamam na apaśyam"],
    ],
    531: [
        ["I will not go", "अहं न गमिष्यामि", "ahaṃ na gamiṣyāmi"],
        ["he will not come", "सः न आगमिष्यति", "saḥ na āgamiṣyati"],
        ["we will not fail", "वयं न विफलिष्यामः", "vayaṃ na viphaliṣyāmaḥ"],
        ["they will not leave", "ते न गमिष्यन्ति", "te na gamiṣyanti"],
        ["There will be no class", "पाठः न भविष्यति", "pāṭhaḥ na bhaviṣyati"],
        ["I shall not forget", "अहं न विस्मरिष्यामि", "ahaṃ na vismariṣyāmi"],
        ["Do not worry (future sense)", "चिन्तां मा कर्षीः", "cintāṃ mā karṣīḥ"],
        ["She will not sing", "सा न गास्यति", "sā na gāsyati"],
        ["We will not wait long", "वयं चिरं न प्रतीक्षिष्यामः", "vayaṃ ciraṃ na pratīkṣiṣyāmaḥ"],
        ["He will never lie", "सः कदापि न अनृतं वक्ष्यति", "saḥ kadāpi na anṛtaṃ vakṣyati"],
        ["No one will stop us", "नः कोऽपि न निवारयिष्यति", "naḥ ko'pi na nivārayiṣyati"],
        ["It will not happen", "तत् न भविष्यति", "tat na bhaviṣyati"],
        ["I will not buy it", "अहं तत् न क्रीणीय", "ahaṃ tat na krīṇīya"],
        ["They will not return today", "ते अद्य न प्रत्यागमिष्यन्ति", "te adya na pratyāgamiṣyanti"],
        ["Future negative with न + future", "न + लृट्", "na + lṛṭ"],
        ["May there be no suffering", "दुःखं मा भूत्", "duḥkhaṃ mā bhūt"],
    ],
    532: [
        ["boy (masc.)", "बालकः", "bālakaḥ"],
        ["girl (fem.)", "बालिका", "bālikā"],
        ["tree (masc.)", "वृक्षः", "vṛkṣaḥ"],
        ["river (fem.)", "नदी", "nadī"],
        ["book (neut.)", "पुस्तकम्", "pustakam"],
        ["Two boys", "बालकौ", "bālakau"],
        ["Many girls", "बालिकाः", "bālikāḥ"],
        ["The men work", "पुरुषाः कार्यं कुर्वन्ति", "puruṣāḥ kāryaṃ kurvanti"],
        ["Women sing", "महिलाः गायन्ति", "mahilāḥ gāyanti"],
        ["Books are on the table", "पुस्तकानि फलके सन्ति", "pustakāni phalake santi"],
        ["Gender affects adjective agreement", "लिङ्गं विशेषणेन सह मेलते", "liṅgaṃ viśeṣaṇena sah melate"],
        ["Plural of neuter words often end in णि", "नपुंसकबहुवचनानि", "napuṃsakabahuvacanāni"],
        ["Learn the three genders", "त्रीणि लिङ्गानि अधीत्स्व", "trīṇi liṅgānī adhītsva"],
        ["This is a big tree", "अयं महान् वृक्षः अस्ति", "ayam mahān vṛkṣaḥ asti"],
        ["These are fresh fruits", "इमानि ताजानि फलानि सन्ति", "imāni tājāni phalāni santi"],
        ["Agreement in sentence", "वाक्ये सर्वं समेति", "vākye sarvaṃ sameti"],
    ],
    533: [
        ["The book is on the table", "पुस्तकं फलकस्य उपरि अस्ति", "pustakaṃ phalakasya upari asti"],
        ["He sits in the hall", "सः सभायां उपविशति", "saḥ sabhāyāṃ upaviśati"],
        ["We walk by the river", "वयं नद्या तटेन गच्छामः", "vayaṃ nadyā taṭena gacchāmaḥ"],
        ["Birds fly in the sky", "पक्षिणः आकाशे उड्डयन्ति", "pakṣiṇaḥ ākāśe uḍḍayanti"],
        ["The cat is under the chair", "विडालः आसनस्य अधः अस्ति", "viḍālaḥ āsanasya adhaḥ asti"],
        ["She lives near the temple", "सा देवालयस्य समीपे वसति", "sā devālayasya samīpe vasati"],
        ["Children play in the field", "बालकाः क्षेत्रे क्रीडन्ति", "bālakāḥ kṣetre krīḍanti"],
        ["The sun rises from the east", "सूर्यः पूर्वात् उदेति", "sūryaḥ pūrvāt udeti"],
        ["I put flowers in water", "अहं जले पुष्पाणि निक्षिपामि", "ahaṃ jale puṣpāṇi nikṣipāmi"],
        ["They study at home", "ते गृहे अधीयन्ते", "te gṛhe adhīyante"],
        ["Prepositions often merge as case endings", "उपसर्गाः विभक्त्या मिलन्ति", "upasargāḥ vibhaktyā milanti"],
        ["Behind the house", "गृहस्य पृष्ठे", "gṛhasya pṛṣṭhe"],
        ["In front of the school", "विद्यालयस्य अग्रे", "vidyālayasya agre"],
        ["Between two trees", "वृक्षयोः मध्ये", "vṛkṣayoḥ madhye"],
        ["Without a book", "पुस्तकम् विना", "pustakam vinā"],
        ["Use seventh and fifth cases for ‘in/on’", "सप्तमी पञ्चमी च", "saptamī pañcamī ca"],
    ],
    534: [
        ["Near — समीपे / अन्तिके", "समीपे", "samīpe"],
        ["Far — दूरम् / विप्रकृष्टम्", "दूरम्", "dūram"],
        ["Above — उपरि / अधिः", "उपरि", "upari"],
        ["Below — अधः / अधस्तात्", "अधः", "adhaḥ"],
        ["Inside — अन्तः / अभ्यन्तरे", "अन्तः", "antaḥ"],
        ["Outside — बहिः / बहिःस्थाने", "बहिः", "bahiḥ"],
        ["Before — पूर्वम् / अग्रे", "पूर्वम्", "pūrvam"],
        ["After — पश्चात् / अनन्तरम्", "पश्चात्", "paścāt"],
        ["Do not confuse अधिः and अधः", "अधिः अधः च भेदं रक्षतु", "adhiḥ adhaḥ ca bhedaṃ rakṣatu"],
        ["Same sound, different meaning: इह / इह?", "अर्थभेदः शब्देषु", "arthabhedaḥ śabdeṣu"],
        ["Context clarifies preposition", "प्रकरणं स्पष्टं करोति", "prakaraṇaṃ spaṣṭaṃ karoti"],
        ["The village is near", "ग्रामः समीपे अस्ति", "grāmaḥ samīpe asti"],
        ["The star is above", "तारा उपरि अस्ति", "tārā upari asti"],
        ["Fish live below water", "मीनाः जलस्य अधः जीवन्ति", "mīnāḥ jalasya adhaḥ jīvanti"],
        ["He sits inside", "सः अन्तः उपविशति", "saḥ antaḥ upaviśati"],
        ["Compare usage in sentences daily", "प्रतिदिनं वाक्येषु तुलयतु", "pratidinaṃ vākyeṣu tulayatu"],
    ],
    535: [
        ["Nominative — subject", "प्रथमा — कर्ता", "prathamā — kartā"],
        ["Accusative — object", "द्वितीया — कर्म", "dvitīyā — karma"],
        ["Instrumental — with / by", "तृतीया — करणम्", "tṛtīyā — karaṇam"],
        ["Dative — to / for", "चतुर्थी — सम्प्रदानम्", "caturthī — sampradānam"],
        ["Ablative — from / because", "पञ्चमी — अपादानम्", "pañcamī — apādānam"],
        ["Genitive — of", "षष्ठी — सम्बन्धः", "ṣaṣṭhī — sambandhaḥ"],
        ["Locative — in / on / at", "सप्तमी — अधिकरणम्", "saptamī — adhikaraṇam"],
        ["Vocative — O …!", "सम्बोधनम्", "sambodhanam"],
        ["Rām goes to the forest", "रामः वनं गच्छति", "rāmaḥ vanaṃ gacchati"],
        ["With a stick", "दण्डेन", "daṇḍena"],
        ["From the village", "ग्रामात्", "grāmāt"],
        ["Of the king", "राज्ञः", "rājñaḥ"],
        ["In the city", "नगरे", "nagare"],
        ["O friend!", "हे मित्र!", "he mitra!"],
        ["Learn the case endings by pattern", "विभक्त्यन्ताः अनुस्मरतु", "vibhaktyantāḥ anusmaratu"],
        ["Decline राम / फल / नदी", "राम-फल-नदी रूपाणि", "rāma-phala-nadī rūpāṇi"],
    ],
    536: [
        ["Go!", "गच्छ!", "gaccha!"],
        ["Read!", "पठ!", "paṭha!"],
        ["Sit!", "उपविश!", "upaviśa!"],
        ["Speak slowly!", "शनैः वद!", "śanaiḥ vada!"],
        ["Do not fear!", "मा भैषीः!", "mā bhaiṣīḥ!"],
        ["Let us go", "गच्छामः", "gacchāmaḥ"],
        ["Please come (respect)", "आगच्छतु", "āgacchatu"],
        ["Give water", "जलं ददातु", "jalaṃ dadātu"],
        ["Write clearly", "स्पष्टं लिखतु", "spaṣṭaṃ likhatu"],
        ["Listen to the teacher", "आचार्यं शृणुत", "ācāryaṃ śṛṇuta"],
        ["Open the door", "द्वारं उद्घाटयतु", "dvāraṃ udghāṭayatu"],
        ["Do not run here", "इह मा धाव", "iha mā dhāva"],
        ["Be quiet", "मौनं भवतु", "maunaṃ bhavatu"],
        ["Help him", "तस्मै साहाय्यं कुरुत", "tasmai sāhāyyaṃ kuruta"],
        ["Imperative uses second person forms", "आज्ञायां द्वितीयपुरुषः", "ājñāyāṃ dvitīyapuruṣaḥ"],
        ["Polite imperative with -तु", "-तु अनुनयेन", "-tu anunayena"],
    ],
    537: [
        ["Today", "अद्य", "adya"],
        ["Tomorrow", "श्वः", "śvaḥ"],
        ["Yesterday", "ह्यः", "hyaḥ"],
        ["Morning", "प्रभातम्", "prabhātam"],
        ["Evening", "सायङ्कालः", "sāyaṅkālaḥ"],
        ["Night", "रात्रिः", "rātriḥ"],
        ["Day", "दिनम् / अहः", "dinam / ahaḥ"],
        ["Week", "सप्ताहः", "saptāhaḥ"],
        ["Month", "मासः", "māsaḥ"],
        ["Year", "संवत्सरः", "saṃvatsaraḥ"],
        ["Now", "अधुना", "adhunā"],
        ["Then", "तदा", "tadā"],
        ["Always", "सदा", "sadā"],
        ["Sometimes", "कदाचित्", "kadācit"],
        ["Early", "प्रातः", "prātaḥ"],
        ["Late", "दीर्घायुषः काले", "dīrghāyuṣaḥ kāle"],
    ],
    538: [
        ["He makes someone read", "सः पाठयति", "saḥ pāṭhayati"],
        ["I cause to go", "अहं गमयामि", "ahaṃ gamayāmi"],
        ["Teacher makes students write", "आचार्यः छात्रान् लिखयति", "ācāryaḥ chātrān likhayati"],
        ["Mother feeds the child", "अम्बा बालकं भोजयति", "ambā bālakaṃ bhojayati"],
        ["Causative adds -य or -अय", "णिजन्तः धातुः", "ṇijantaḥ dhātuḥ"],
        ["They show the way", "ते मार्गं दर्शयन्ति", "te mārgaṃ darśayanti"],
        ["I had the letter written", "अहं पत्रं लिखितवान्", "ahaṃ patraṃ likhitavān"],
        ["She makes him sit", "सा तम् उपवेशयति", "sā tam upaveśayati"],
        ["We teach Sanskrit", "वयं संस्कृतं शिक्षयामः", "vayaṃ saṃskṛtaṃ śikṣayāmaḥ"],
        ["The king sends messengers", "राजा दूतान् प्रेषयति", "rājā dūtān preṣayati"],
        ["Cause and effect in grammar", "कारण-कार्ये व्याकरणे", "kāraṇa-kārye vyākaraṇe"],
        ["Do not force anyone", "कंचित् बलात् मा कार्षीत्", "kañcit balāt mā kārṣīt"],
        ["He opens the shop", "सः आपणं उद्घाटयति", "saḥ āpaṇaṃ udghāṭayati"],
        ["I illuminate the room", "अहं कक्ष्यां प्रकाशयामि", "ahaṃ kakṣyāṃ prakāśayāmi"],
        ["Causative is common in classical prose", "णिजन्तः साहित्ये बहवः", "ṇijantaḥ sāhitye bahavaḥ"],
        ["Practice: गमयति, पाठयति", "गमयति पाठयति", "gamayati pāṭhayati"],
    ],
    539: [
        ["The boy reads his book", "बालकः स्वपुस्तकं पठति", "bālakaḥ svapustakaṃ paṭhati"],
        ["The girl reads her book", "बालिका स्वपुस्तकं पठति", "bālikā svapustakaṃ paṭhati"],
        ["Two boys read their books", "बालकौ स्वपुस्तके पठतः", "bālakau svapustake paṭhataḥ"],
        ["Adjective agrees with noun", "विशेषणं नाम्ना सह मेलते", "viśeṣaṇaṃ nāmnā sah melate"],
        ["Good boys (masc. pl.)", "शिष्टाः बालकाः", "śiṣṭāḥ bālakāḥ"],
        ["Good girls (fem. pl.)", "शिष्टाः बालिकाः", "śiṣṭāḥ bālikāḥ"],
        ["Great deeds (neut. pl.)", "महान्ति कर्माणि", "mahānti karmāṇi"],
        ["The horse runs fast", "अश्वः शीघ्रं धावति", "aśvaḥ śīghraṃ dhāvati"],
        ["The mares run fast", "अश्वाः शीघ्रं धावन्ति", "aśvāḥ śīghraṃ dhāvanti"],
        ["Verb agrees with subject in number", "क्रियाः कर्तृसङ्ख्यया सह", "kriyāḥ kartṛsaṅkhyayā sah"],
        ["She is wise; he is wise", "सा विदुषी; सः विद्वान्", "sā viduṣī; saḥ vidvān"],
        ["They (fem.) are wise", "ताः विदुष्यः", "tāḥ viduṣyaḥ"],
        ["Neuter subject: phalam patati", "फलं पतति", "phalaṃ patati"],
        ["Dual subjects take dual verb", "द्विवचने द्विवचनम्", "dvivacane dvivacanam"],
        ["Memorize agreement patterns", "मेलनरूपाणि स्मरतु", "melanarūpāṇi smaratu"],
        ["Gender-number-case — three features", "लिङ्ग-संख्या-विभक्ति — त्रयः", "liṅga-saṅkhyā-vibhakti — trayaḥ"],
    ],
    540: [
        ["I have done (periphrastic perfect)", "अहं कृतवान् अस्मि", "ahaṃ kṛtavān asmi"],
        ["he had gone before", "सः पूर्वं गतवान् आसीत्", "saḥ pūrvaṃ gatavān āsīt"],
        ["Alternative style with auxiliary", "सहायकक्रियया अन्या शैली", "sahāyakakriyayā anyā śailī"],
        ["By then we had finished", "तदा वयं समाप्तवन्तः आसाम", "tadā vayaṃ samāptavantaḥ āsāma"],
        ["She had already eaten", "सा पूर्वमेव अश्नात्", "sā pūrvam eva aśnāt"],
        ["They will have arrived", "ते आगतवन्तः भविष्यन्ति", "te āgatavantaḥ bhaviṣyanti"],
        ["Perfect sense with past participle", "भूतकृदन्तेन समाप्तिः", "bhūtakṛdantena samāptiḥ"],
        ["I was about to leave", "अहं गन्तुं प्रवृत्तवान्", "ahaṃ gantuṃ pravṛttavān"],
        ["Work had been done", "कार्यं कृतम् आसीत्", "kāryaṃ kṛtam āsīt"],
        ["Style varies by text tradition", "शैली ग्रन्थानुसारं भिन्ना", "śailī granthānusāraṃ bhinnā"],
        ["Read examples in epics", "इतिहासेषु उदाहरणानि पठतु", "itihāseṣu udāharaṇāni paṭhatu"],
        ["He had not seen", "सः न दृष्टवान् आसीत्", "saḥ na dṛṣṭavān āsīt"],
        ["We had hoped", "वयं आशंसितवन्तः आसाम", "vayaṃ āśaṃsitavantaḥ āsāma"],
        ["Compound verbs in perfect sense", "समासक्रियाः समाप्तौ", "samāsakriyāḥ samāptau"],
        ["Compare with simple past", "लुङ् सह तुलयतु", "luṅ saha tulayatu"],
        ["Practice translation both styles", "अनुवादं द्वाभ्यां शैलीभ्याम्", "anuvādaṃ dvābhyāṃ śailībhyām"],
    ],
    541: [
        ["I have been reading", "अहं पठन् आसम् अद्यापि", "ahaṃ paṭhan āsam adyāpi"],
        ["he had been walking", "सः गच्छन् आसीत्", "saḥ gacchan āsīt"],
        ["Continuous perfect (periphrastic)", "निरन्तरसमाप्तिः", "nirantarasamāptiḥ"],
        ["We had been waiting long", "वयं चिरं प्रतीक्षमाणाः आसाम", "vayaṃ ciraṃ pratīkṣamāṇāḥ āsāma"],
        ["They will have been studying", "ते अधीयानाः भविष्यन्ति", "te adhīyānāḥ bhaviṣyanti"],
        ["She has been singing", "सा गायन्ती अस्ति", "sā gāyantī asti"],
        ["Rain had been falling", "वर्षं पतत् आसीत्", "varṣaṃ patat āsīt"],
        ["I was still thinking", "अहं चिन्तयन् एव आसम्", "ahaṃ cintayan eva āsam"],
        ["Work was being done", "कार्यं क्रियते स्म", "kāryaṃ kriyate sma"],
        ["Use participle + auxiliary", "कृदन्तः सहायकेन", "kṛdantaḥ sahāyakena"],
        ["Classical prose prefers participles", "साहित्ये कृदन्ताः प्राधान्यम्", "sāhitye kṛdantāḥ prādhānyam"],
        ["He had been ill", "सः रोगी आसीत्", "saḥ rogī āsīt"],
        ["We have been happy", "वयं सुखिनः अस्मः", "vayaṃ sukhinaḥ asmaḥ"],
        ["Not common in Vedic style", "वैदिकशैल्यां दुर्लभम्", "vaidikaśailyāṃ durlabham"],
        ["Compare with English perfect continuous", "आङ्ग्लभाषया तुलनम्", "āṅgla-bhāṣayā tulanam"],
        ["Drill: कर्तुं, गन्तुं with अस्", "कर्तुं गन्तुं अस्", "kartuṃ gantuṃ as"],
    ],
    542: [
        ["I do not want", "मे न इच्छा अस्ति", "me na icchā asti"],
        ["I do not eat (simple negation)", "अहं न अश्नामि", "ahaṃ na aśnāmi"],
        ["There is no sugar", "शर्करा न अस्ति", "śarkarā na asti"],
        ["He does not wish to go", "तस्य गन्तुं इच्छा न अस्ति", "tasya gantuṃ icchā na asti"],
        ["We need nothing", "नः किञ्चित् आवश्यकम्", "naḥ kiñcit āvaśyakam"],
        ["She has no fear", "तस्याः भयं न अस्ति", "tasyāḥ bhayaṃ na asti"],
        ["Not vs do-not-want distinction", "न इच्छा च न क्रिया च", "na icchā ca na kriyā ca"],
        ["I refuse to speak", "अहं वक्तुं न इच्छामि", "ahaṃ vaktuṃ na icchāmi"],
        ["He lacks money", "तस्य धनं न अस्ति", "tasya dhanaṃ na asti"],
        ["We do not desire wealth", "वयं धनं न इच्छामः", "vayaṃ dhanaṃ na icchāmaḥ"],
        ["Simple न negates the verb", "न क्रियां निषेधति", "na kriyāṃ niṣedhati"],
        ["Absence uses न अस्ति", "अभावे न अस्ति", "abhāve na asti"],
        ["Desiderative uses इच्छ्", "इच्छ् धातुः", "icch dhātuḥ"],
        ["I want to learn", "अहं अधीतुम् इच्छामि", "ahaṃ adhītum icchāmi"],
        ["He does not want trouble", "सः क्लेशं न इच्छति", "saḥ kleśaṃ na icchati"],
        ["Compare: न पिबामि / पातुं न इच्छामि", "न पिबामि पातुं न इच्छामि", "na pibāmi pātuṃ na icchāmi"],
    ],
}
