# Sanskrit Lesson 2 — chunk A (chapter IDs 510–526).

LESSONS_S2A = {
    510: [
        ["I", "अहम्", "aham"],
        ["you (singular, familiar)", "त्वम्", "tvam"],
        ["he / that one", "सः", "saḥ"],
        ["she / that one", "सा", "sā"],
        ["it / that (neuter)", "तत्", "tat"],
        ["we", "वयम्", "vayam"],
        ["you (plural)", "यूयम्", "yūyam"],
        ["they (masc.)", "ते", "te"],
        ["they (fem.)", "ताः", "tāḥ"],
        ["this (masc.)", "अयम्", "ayam"],
        ["this (fem.)", "इयम्", "iyam"],
        ["this (neut.)", "इदम्", "idam"],
        ["my book", "मम पुस्तकम्", "mama pustakam"],
        ["your (fem. object) form", "तव / भवतः", "tava / bhavataḥ"],
        ["the boy (with article sense)", "बालकः", "bālakaḥ"],
        ["who is he?", "सः कः?", "saḥ kaḥ?"],
    ],
    511: [
        ["You (respect) are learned", "भवान् विद्वान् अस्ति", "bhavān vidvān asti"],
        ["You (respect) go", "भवान् गच्छति", "bhavān gacchati"],
        ["Honourable teacher speaks", "आचार्यः वदति", "ācāryaḥ vadati"],
        ["Mother cooks (honorific style)", "अम्बा पचति", "ambā pacati"],
        ["Father reads", "पिता पठति", "pitā paṭhati"],
        ["The elders are seated", "वृद्धाः उपविष्टाः सन्ति", "vṛddhāḥ upaviṣṭāḥ santi"],
        ["We greet you (respect)", "वयं भवन्तं नमामः", "vayaṃ bhavantaṃ namāmaḥ"],
        ["Please sit (formal)", "उपविशतु", "upaviśatu"],
        ["Please tell me", "माम् वदतु", "mām vadata"],
        ["They (hon.) have arrived", "ते आगताः", "te āgatāḥ"],
        ["The king is wise", "राजा विद्वान् अस्ति", "rājā vidvān asti"],
        ["Grandfather tells a story", "पितामहः कथां वदति", "pitāmahaḥ kathāṃ vadati"],
        ["You will go (polite)", "भवान् गमिष्यति", "bhavān gamiṣyati"],
        ["We respect teachers", "वयम् आचार्यान् पूजयामः", "vayam ācāryān pūjayāmaḥ"],
        ["Thank you (formal)", "धन्यवादः", "dhanyavādaḥ"],
        ["May I leave? (to elder)", "अनुज्ञां ददातु?", "anujñāṃ dadātu?"],
    ],
    512: [
        ["to go", "गम् (गच्छति)", "gam (gacchati)"],
        ["to read", "पठ् (पठति)", "paṭh (paṭhati)"],
        ["to write", "लिख् (लिखति)", "likh (likhati)"],
        ["to speak", "वद् (वदति)", "vad (vadati)"],
        ["to see", "दृश् (पश्यति)", "dṛś (paśyati)"],
        ["to do", "कृ (करोति)", "kṛ (karoti)"],
        ["to eat", "अश् (अश्नाति)", "aś (aśnāti)"],
        ["to sit", "सद् (सीदति)", "sad (sīdati)"],
        ["to stand", "स्था (तिष्ठति)", "sthā (tiṣṭhati)"],
        ["to give", "दा (ददाति)", "dā (dadāti)"],
        ["I read a book", "अहं पुस्तकं पठामि", "ahaṃ pustakaṃ paṭhāmi"],
        ["The boy runs", "बालकः धावति", "bālakaḥ dhāvati"],
        ["She writes letters", "सा पत्राणि लिखति", "sā patrāṇi likhati"],
        ["We study Sanskrit", "वयं संस्कृतं अधीमहे", "vayaṃ saṃskṛtam adhīmahe"],
        ["They play in the field", "ते क्षेत्रे क्रीडन्ति", "te kṣetre krīḍanti"],
        ["The teacher teaches", "आचार्यः शिक्षयति", "ācāryaḥ śikṣayati"],
    ],
    513: [
        ["I go", "अहं गच्छामि", "ahaṃ gacchāmi"],
        ["you go", "त्वं गच्छसि", "tvaṃ gacchasi"],
        ["he goes", "सः गच्छति", "saḥ gacchati"],
        ["she goes", "सा गच्छति", "sā gacchati"],
        ["we go", "वयं गच्छामः", "vayaṃ gacchāmaḥ"],
        ["you (pl.) go", "यूयं गच्छथ", "yūyaṃ gacchatha"],
        ["they go", "ते गच्छन्ति", "te gacchanti"],
        ["I read daily", "अहं प्रतिदिनं पठामि", "ahaṃ pratidinaṃ paṭhāmi"],
        ["The sun rises", "सूर्यः उदेति", "sūryaḥ udeti"],
        ["Birds fly", "पक्षिणः उड्डयन्ति", "pakṣiṇaḥ uḍḍayanti"],
        ["Children play", "बालकाः क्रीडन्ति", "bālakāḥ krīḍanti"],
        ["Mother cooks food", "अम्बा भोजनं पचति", "ambā bhojanaṃ pacati"],
        ["I know this", "अहमेतत् जानामि", "aham etat jānāmi"],
        ["You understand the lesson", "त्वं पाठं अवगच्छसि", "tvaṃ pāṭhaṃ avagacchasi"],
        ["He works in the city", "सः नगरे कार्यं करोति", "saḥ nagare kāryaṃ karoti"],
        ["We live in the village", "वयं ग्रामे वसामः", "vayaṃ grāme vasāmaḥ"],
    ],
    514: [
        ["I am", "अहम् अस्मि", "aham asmi"],
        ["you are", "त्वम् असि", "tvam asi"],
        ["he is", "सः अस्ति", "saḥ asti"],
        ["she is", "सा अस्ति", "sā asti"],
        ["it is", "तत् अस्ति", "tat asti"],
        ["we are", "वयम् अस्मः", "vayam asmaḥ"],
        ["you (pl.) are", "यूयम् स्थ", "yūyam stha"],
        ["they are", "ते सन्ति", "te santi"],
        ["This is a book", "इदं पुस्तकम् अस्ति", "idaṃ pustakam asti"],
        ["That is a tree", "तत् वृक्षः अस्ति", "tat vṛkṣaḥ asti"],
        ["I am a student", "अहं छात्रः अस्मि", "ahaṃ chātraḥ asmi"],
        ["She is a teacher", "सा शिक्षिका अस्ति", "sā śikṣikā asti"],
        ["We are ready", "वयं सिद्धाः अस्मः", "vayaṃ siddhāḥ asmaḥ"],
        ["They are friends", "ते मित्राणि सन्ति", "te mitrāṇi santi"],
        ["The water is cold", "जलं शीतलम् अस्ति", "jalaṃ śītalam asti"],
        ["The sky is clear", "आकाशः निर्मलः अस्ति", "ākāśaḥ nirmalaḥ asti"],
    ],
    515: [
        ["I am reading", "अहं पठामि (वर्तमाने)", "ahaṃ paṭhāmi (vartamāne)"],
        ["he is writing", "सः लिखति स्म", "saḥ likhati sma"],
        ["Classical present also covers continuous sense", "वर्तमानः कालः निरन्तरं द्योतयति", "vartamānaḥ kālaḥ nirantaraṃ dyotayati"],
        ["She is singing", "सा गायति", "sā gāyati"],
        ["We are learning", "वयं अधीमहे", "vayaṃ adhīmahe"],
        ["They are playing", "ते क्रीडन्ति", "te krīḍanti"],
        ["The river is flowing", "नदी वहति", "nadī vahati"],
        ["Sun is shining", "सूर्यः प्रकाशते", "sūryaḥ prakāśate"],
        ["I am eating now", "अहमद्य अश्नामि", "aham adya aśnāmi"],
        ["Children are laughing", "बालकाः हसन्ति", "bālakāḥ hasanti"],
        ["Who is calling?", "कः आह्वयति?", "kaḥ āhvayati?"],
        ["We are waiting", "वयं प्रतीक्षामहे", "vayaṃ pratīkṣāmahe"],
        ["He is thinking", "सः चिन्तयति", "saḥ cintayati"],
        ["Birds are flying", "पक्षिणः उड्डयन्ति", "pakṣiṇaḥ uḍḍayanti"],
        ["The lesson is going on", "पाठः प्रवर्तते", "pāṭhaḥ pravartate"],
        ["Stay seated (continuous command)", "उपविशत नित्यम्", "upaviśata nityam"],
    ],
    516: [
        ["I will go", "अहं गमिष्यामि", "ahaṃ gamiṣyāmi"],
        ["you will read", "त्वं पठिष्यसि", "tvaṃ paṭhiṣyasi"],
        ["he will come", "सः आगमिष्यति", "saḥ āgamiṣyati"],
        ["we will meet", "वयं मिलिष्यामः", "vayaṃ miliṣyāmaḥ"],
        ["they will study", "ते अधीयिष्यन्ति", "te adhīṣyanti"],
        ["Tomorrow I will travel", "श्वः अहं यास्यामि", "śvaḥ ahaṃ yāsyāmi"],
        ["She will sing", "सा गास्यति", "sā gāsyati"],
        ["It will rain (may rain)", "वर्षिष्यति", "varṣiṣyati"],
        ["We shall help", "वयं साहाय्यं करिष्यामः", "vayaṃ sāhāyyaṃ kariṣyāmaḥ"],
        ["He will not lie", "सः अनृतं न वक्ष्यति", "saḥ anṛtaṃ na vakṣyati"],
        ["You will succeed", "त्वं सफलः भविष्यसि", "tvaṃ safalaḥ bhaviṣyasi"],
        ["The train will depart", "रेलः प्रस्थास्यति", "relaḥ prasthāsyati"],
        ["I will try again", "अहं पुनः प्रयतिष्ये", "ahaṃ punaḥ prayatiṣye"],
        ["They will return", "ते प्रत्यागमिष्यन्ति", "te pratyāgamiṣyanti"],
        ["Winter will come", "शिशिरऋतुः आगमिष्यति", "śiśirartuḥ āgamiṣyati"],
        ["We hope for peace", "वयं शान्तिं आशंसामहे", "vayaṃ śāntiṃ āśaṃsāmahe"],
    ],
    517: [
        ["Future continuous sense with present participle", "भविष्यति निरन्तरं भूत्वा वर्तमानकृदन्तः", "bhaviṣyati nirantaraṃ bhūtvā vartamānakṛdantaḥ"],
        ["He will be reading", "सः पठिष्यन् भविष्यति", "saḥ paṭhiṣyan bhaviṣyati"],
        ["We will be waiting", "वयं प्रतीक्षमाणाः भविष्यामः", "vayaṃ pratīkṣamāṇāḥ bhaviṣyāmaḥ"],
        ["They will be travelling", "ते गच्छन्तः भविष्यन्ति", "te gacchantaḥ bhaviṣyanti"],
        ["I shall be studying", "अहं अध्ययनं करिष्यन् अस्मि", "aham adhyayanaṃ kariṣyan asmi"],
        ["She will be cooking", "सा पचन्ती भविष्यति", "sā pacantī bhaviṣyati"],
        ["Rain will be falling", "वर्षं पतत् भविष्यति", "varṣaṃ patat bhaviṣyati"],
        ["The sun will be shining", "सूर्यः प्रकाशन् भविष्यति", "sūryaḥ prakāśan bhaviṣyati"],
        ["Children will be playing", "बालकाः क्रीडन्तः भविष्यन्ति", "bālakāḥ krīḍantaḥ bhaviṣyanti"],
        ["We will be listening", "वयं शृण्वन्तः भविष्यामः", "vayaṃ śṛṇvantaḥ bhaviṣyāmaḥ"],
        ["He will be working then", "तदा सः कार्यं कुर्वन् भविष्यति", "tadā saḥ kāryaṃ kurvan bhaviṣyati"],
        ["You will be walking", "त्वं गच्छन् भविष्यसि", "tvaṃ gacchan bhaviṣyasi"],
        ["Birds will be flying", "पक्षिणः उड्डयन्तः भविष्यन्ति", "pakṣiṇaḥ uḍḍayantaḥ bhaviṣyanti"],
        ["Night will be advancing", "रात्रिः वर्धमाना भविष्यति", "rātriḥ vardhamānā bhaviṣyati"],
        ["I will be resting", "अहं विश्रामं लप्स्ये", "ahaṃ viśrāmaṃ lapsye"],
        ["They will be discussing", "ते चर्चां कुर्वन्तः भविष्यन्ति", "te carcāṃ kurvantaḥ bhaviṣyanti"],
    ],
    518: [
        ["I went", "अहं अगच्छम्", "ahaṃ agaccham"],
        ["you spoke", "त्वं अवदः", "tvam avadaḥ"],
        ["he stood", "सः अतिष्ठत्", "saḥ atiṣṭhat"],
        ["we saw", "वयं अपश्याम", "vayam apaśyāma"],
        ["they came", "ते आगच्छन्", "te āgacchan"],
        ["I slept", "अहं अस्वापम्", "ahaṃ asvāpam"],
        ["she smiled", "सा अहसत्", "sā ahasat"],
        ["The bird flew", "पक्षी अड्डीत्", "pakṣī aḍḍīt"],
        ["We sat down", "वयं उपविष्टवन्तः", "vayaṃ upaviṣṭavantaḥ"],
        ["He ran fast", "सः शीघ्रं अधावत्", "saḥ śīghram adhāvat"],
        ["I did not go", "अहं न अगमम्", "ahaṃ na agamam"],
        ["You did not come", "त्वं न आगमः", "tvaṃ na āgamaḥ"],
        ["They laughed", "ते अहसन्", "te ahasan"],
        ["It rained", "वर्षत् आसीत्", "varṣat āsīt"],
        ["We studied yesterday", "ह्यः वयं अधीतवन्तः", "hyaḥ vayam adhītavantaḥ"],
        ["He woke early", "सः प्रभाते उत्थितवान्", "saḥ prabhāte utthitavān"],
    ],
    519: [
        ["I saw the boy", "अहं बालकं अपश्यम्", "ahaṃ bālakam apaśyam"],
        ["you read the book", "त्वं पुस्तकं अपठः", "tvaṃ pustakam apaṭhaḥ"],
        ["he wrote a letter", "सः पत्रं अलिखत्", "saḥ patram alikhat"],
        ["she made food", "सा भोजनं अपचत्", "sā bhojanam apacat"],
        ["we bought fruit", "वयं फलं अक्रीण्म", "vayaṃ phalam akrīṇma"],
        ["they opened the door", "ते द्वारं अविवृतन्", "te dvāram avivṛtan"],
        ["I gave him water", "अहं तस्मै जलं अददम्", "ahaṃ tasmai jalam adadam"],
        ["she told the truth", "सा सत्यं अवदत्", "sā satyam avadat"],
        ["he forgot the way", "सः मार्गं अविस्मरत्", "saḥ mārgaṃ avismarat"],
        ["we heard the news", "वयं वार्तां अश्रौष्म", "vayaṃ vārtāṃ aśrauṣma"],
        ["they closed the shop", "ते आपणं अपिदधुः", "te āpaṇam apidadhuḥ"],
        ["I did not see him", "अहं तं न अपश्यम्", "ahaṃ taṃ na apaśyam"],
        ["You helped me", "त्वं माम् असाहायः", "tvaṃ mām asāhāyaḥ"],
        ["He carried the bag", "सः पेटिकां अवहत्", "saḥ peṭikām avahat"],
        ["She washed clothes", "सा वस्त्राणि अक्षालयत्", "sā vastrāṇi akṣālayat"],
        ["We finished the work", "वयं कार्यं समाप्तवन्तः", "vayaṃ kāryaṃ samāptavantaḥ"],
    ],
    520: [
        ["I was", "अहम् आसम्", "aham āsam"],
        ["you were", "त्वम् आसीः", "tvam āsīḥ"],
        ["he was", "सः आसीत्", "saḥ āsīt"],
        ["she was", "सा आसीत्", "sā āsīt"],
        ["it was", "तत् आसीत्", "tat āsīt"],
        ["we were", "वयम् आसाम", "vayam āsāma"],
        ["they were", "ते आसन्", "te āsan"],
        ["There was a tree", "वृक्षः आसीत्", "vṛkṣaḥ āsīt"],
        ["It was cold", "शीतलम् आसीत्", "śītalam āsīt"],
        ["We were happy", "वयं सुखिनः आसाम", "vayaṃ sukhinaḥ āsāma"],
        ["He was tired", "सः क्लान्तः आसीत्", "saḥ klāntaḥ āsīt"],
        ["The door was open", "द्वारं उद्घाटितम् आसीत्", "dvāraṃ udghāṭitam āsīt"],
        ["I was not there", "अहं तत्र न आसम्", "ahaṃ tatra na āsam"],
        ["They were students", "ते छात्राः आसन्", "te chātrāḥ āsan"],
        ["The field was green", "क्षेत्रं हरितम् आसीत्", "kṣetraṃ haritam āsīt"],
        ["Night was dark", "रात्रिः तमस्विनी आसीत", "rātriḥ tamasvinī āsīta"],
    ],
    521: [
        ["Some verbs have irregular past stems", "केचिद् धातवः अनियमिताः", "kecid dhātavaḥ aniyamitāḥ"],
        ["I went (gam) — अगच्छम्", "अगच्छम्", "agaccham"],
        ["he gave — अदात्", "अदात्", "adāt"],
        ["we saw — अपश्याम", "अपश्याम", "apaśyāma"],
        ["I said — अवदम्", "अवदम्", "avadam"],
        ["you took — अजहृथाः", "अजहृथाः", "ajahṛthāḥ"],
        ["they knew — अजानन्", "अजानन्", "ajānan"],
        ["she sat — आसीत् (आस्)", "असदत्", "asadat"],
        ["Learn principal parts from grammar", "धातुरूपाणि व्याकरणात्", "dhāturūpāṇi vyākaraṇāt"],
        ["Practice: अगम्, अभूत्, अकरोत्", "अगम् अभूत् अकरोत्", "agam abhūt akarot"],
        ["I became — अभवम्", "अभवम्", "abhavam"],
        ["it happened — अभवत्", "अभवत्", "abhavat"],
        ["we heard — अश्रावाम", "अश्रावाम", "aśrāvāma"],
        ["he read — अपठत्", "अपठत्", "apaṭhat"],
        ["Memorize common suppletive forms", "सामान्यरूपाणि तादृशानि स्मरतु", "sāmānyarūpāṇi tādṛśāni smaratu"],
        ["Consult the verb list daily", "प्रतिदिनं धातुसूचिं पठतु", "pratidinaṃ dhātusūciṃ paṭhatu"],
    ],
    522: [
        ["While I was reading…", "अहं पठन् आसम् यदा…", "ahaṃ paṭhan āsam yadā…"],
        ["he was walking", "सः गच्छन् आसीत्", "saḥ gacchan āsīt"],
        ["they were playing", "ते क्रीडन्तः आसन्", "te krīḍantaḥ āsan"],
        ["The wind was blowing", "वायुः वहन् आसीत्", "vāyuḥ vahan āsīt"],
        ["We were waiting", "वयं प्रतीक्षमाणाः आसाम", "vayaṃ pratīkṣamāṇāḥ āsāma"],
        ["She was singing", "सा गायन्ती आसीत्", "sā gāyantī āsīt"],
        ["Rain was falling", "वर्षं पतत् आसीत्", "varṣaṃ patat āsīt"],
        ["I was thinking", "अहं चिन्तयन् आसम्", "ahaṃ cintayan āsam"],
        ["Birds were chirping", "पक्षिणः कूजन्तः आसन्", "pakṣiṇaḥ kūjantaḥ āsan"],
        ["Night was advancing", "रात्रिः वर्धमाना आसीत्", "rātriḥ vardhamānā āsīt"],
        ["He was not listening", "सः न श‍ृण्वन् आसीत्", "saḥ na śṛṇvan āsīt"],
        ["Children were studying", "बालकाः अधीयानाः आसन्", "bālakāḥ adhīyānāḥ āsan"],
        ["The river was flowing", "नदी वहन्ती आसीत्", "nadī vahantī āsīt"],
        ["We were eating", "वयं अश्नन्तः आसाम", "vayaṃ aśnantaḥ āsāma"],
        ["Then the bell rang", "तदा घण्टा अनादिष्ट", "tadā ghaṇṭā anādiṣṭa"],
        ["While studying, silence", "अध्ययने मौनम्", "adhyayane maunam"],
    ],
    523: [
        ["I have done", "अहं कृतवान् अस्मि", "ahaṃ kṛtavān asmi"],
        ["he has gone", "सः गतवान् अस्ति", "saḥ gatavān asti"],
        ["we have seen", "वयं दृष्टवन्तः अस्मः", "vayaṃ dṛṣṭavantaḥ asmaḥ"],
        ["she has written", "सा लिखितवती अस्ति", "sā likhitavatī asti"],
        ["they have arrived", "ते आगतवन्तः सन्ति", "te āgatavantaḥ santi"],
        ["I had known", "अहं ज्ञातवान् आसम्", "ahaṃ jñātavān āsam"],
        ["By then he had left", "तदा सः गतवान् आसीत्", "tadā saḥ gatavān āsīt"],
        ["Future perfect sense (periphrastic)", "भविष्यति समाप्तिः पर्यायवाक्येन", "bhaviṣyati samāptiḥ paryāyavākyena"],
        ["Work will have finished", "कार्यं समाप्तं भविष्यति", "kāryaṃ samāptaṃ bhaviṣyati"],
        ["I shall have read", "अहं पठितवान् भविष्यामि", "ahaṃ paṭhitavān bhaviṣyāmi"],
        ["They had not come", "ते न आगतवन्तः आसन्", "te na āgatavantaḥ āsan"],
        ["She has learned well", "सा सुष्ठु शिक्षितवती अस्ति", "sā suṣṭhu śikṣitavatī asti"],
        ["We have lived here long", "वयं चिरं इह वसितवन्तः अस्मः", "vayaṃ ciraṃ iha vasitavantaḥ asmaḥ"],
        ["He has forgotten", "सः विस्मृतवान् अस्ति", "saḥ vismṛtavān asti"],
        ["Perfect participle agrees in gender", "कृदन्तः लिङ्गेन सह समेति", "kṛdantaḥ liṅgena sah sameti"],
        ["Practice: कृतवान्, गतवती, पठितम्", "कृतवान् गतवती पठितम्", "kṛtavān gatavatī paṭhitam"],
    ],
    524: [
        ["in the village", "ग्रामे", "grāme"],
        ["in the city", "नगरे", "nagare"],
        ["on the road", "मार्गे", "mārge"],
        ["under the tree", "वृक्षस्य अधः", "vṛkṣasya adhaḥ"],
        ["near the river", "नद्याः समीपे", "nadyāḥ samīpe"],
        ["before sunset", "अस्तमनात् पूर्वम्", "astamanāt pūrvam"],
        ["after meal", "भोजनात् परम्", "bhojanāt param"],
        ["with a friend", "मित्रेण सह", "mitreṇa saha"],
        ["without fear", "भयम् विना", "bhayam vinā"],
        ["towards the temple", "देवालयं प्रति", "devālayaṃ prati"],
        ["from home", "गृहात्", "gṛhāt"],
        ["until evening", "सायङ्कालं यावत्", "sāyaṅkālaṃ yāvat"],
        ["between two hills", "द्वयोः पर्वतयोः मध्ये", "dvayoḥ parvatayoḥ madhye"],
        ["I sit in the hall", "अहं सभायां उपविशामि", "ahaṃ sabhāyāṃ upaviśāmi"],
        ["The book is on the table", "पुस्तकं फलकस्य उपरि अस्ति", "pustakaṃ phalakasya upari asti"],
        ["They walk along the bank", "ते तटेन गच्छन्ति", "te taṭena gacchanti"],
    ],
    525: [
        ["to the teacher", "आचार्याय", "ācāryāya"],
        ["to the village", "ग्रामाय", "grāmāya"],
        ["to the city", "नगराय", "nagarāya"],
        ["to the student", "छात्राय", "chātrāya"],
        ["I go to school", "अहं विद्यालयं गच्छामि", "ahaṃ vidyālayaṃ gacchāmi"],
        ["Give to him", "तस्मै ददातु", "tasmai dadātu"],
        ["She writes to her mother", "सा मात्रे लिखति", "sā mātre likhati"],
        ["We speak to friends", "वयं मित्रेभ्यः वदामः", "vayaṃ mitrebhyaḥ vadāmaḥ"],
        ["Listen to the elders", "वृद्धेभ्यः शृणुत", "vṛddhebhyaḥ śṛṇuta"],
        ["He sends a letter to the king", "सः राज्ञे पत्रं प्रेषयति", "saḥ rājñe patraṃ preṣayati"],
        ["Come to me", "माम् प्रति आगच्छ", "mām prati āgaccha"],
        ["Show the way to us", "अस्मान् मार्गं दर्शयतु", "asmān mārgaṃ darśayatu"],
        ["I gave water to the guest", "अहं अतिथये जलं अददम्", "ahaṃ atithaye jalam adadam"],
        ["Not to everyone", "सर्वेभ्यः न", "sarvebhyaḥ na"],
        ["Dative of purpose is common", "प्रयोजनार्थे चतुर्थी", "prayojanārthe caturthī"],
        ["Study the fourth case endings", "चतुर्थीविभक्तिं पठतु", "caturthīvibhaktiṃ paṭhatu"],
    ],
    526: [
        ["I see the boy", "अहं बालकं पश्यामि", "ahaṃ bālakaṃ paśyāmi"],
        ["you help the friend", "त्वं मित्रं साहाय्यं करोषि", "tvaṃ mitraṃ sāhāyyaṃ karoṣi"],
        ["he teaches the students", "सः छात्रान् शिक्षयति", "saḥ chātrān śikṣayati"],
        ["she calls the child", "सा बालकम् आह्वयति", "sā bālakam āhvayati"],
        ["we remember the teacher", "वयं आचार्यम् स्मरामः", "vayaṃ ācāryam smarāmaḥ"],
        ["they serve the guests", "ते अतिथीन् सेवन्ते", "te atithīn sevante"],
        ["Accusative for living object", "प्राणिनि कर्मणि द्वितीया", "prāṇini karmaṇi dvitīyā"],
        ["I found the dog", "अहं शुनकं अलभे", "ahaṃ śunakam alabhe"],
        ["He led the horse", "सः अश्वम् अनीत्", "saḥ aśvam anīt"],
        ["She fed the birds", "सा पक्षिणः अभोजयत्", "sā pakṣiṇaḥ abhojayat"],
        ["We saw the deer", "वयं मृगं अपश्याम", "vayaṃ mṛgam apaśyāma"],
        ["Do not hurt animals", "प्राणिनः मा हिंसीत", "prāṇinaḥ mā hinsīta"],
        ["The boy respects elders", "बालकः वृद्धान् पूजयति", "bālakaḥ vṛddhān pūjayati"],
        ["I gave him a book", "अहं तस्मै पुस्तकं अददम्", "ahaṃ tasmai pustakam adadam"],
        ["Tell me the truth", "माम् सत्यं वदतु", "mām satyaṃ vadata"],
        ["Living beings take appropriate case", "प्राणिषु विभक्तिः यथायोगम्", "prāṇiṣu vibhaktiḥ yathāyogam"],
    ],
}
