# Sanskrit Lesson 5 — Conversation practice A (chapter IDs 620–641).

LESSONS_S5A = {
    620: [
        ["Happy Deepavali!", "दीपावल्याः शुभाः!", "dīpāvalyāḥ śubhāḥ!"],
        ["Light lamps at home", "गृहे दीपान् ज्वालयतु", "gṛhe dīpān jvālayatu"],
        ["We worship Lakṣmī", "लक्ष्मीं पूजयामः", "lakṣmīṃ pūjayāmaḥ"],
        ["Sweets are prepared", "मधुराणि सिद्ध्यन्ति", "madhurāṇi siddhyanti"],
        ["Children burst crackers", "बालकाः दीपगर्जनान् भिन्दन्ति", "bālakāḥ dīpagarjanān bhindanti"],
        ["May light conquer darkness", "ज्योतिः तमः जयतु", "jyotiḥ tamaḥ jayatu"],
        ["Wear new clothes", "नवीनानि वस्त्राणि धारयतु", "navīnāni vastrāṇi dhārayatu"],
        ["Visit friends and family", "मित्राणि बान्धवांश्च पश्यतु", "mitrāṇi bāndhavāṃśca paśyatu"],
        ["The market is crowded", "बाजारः जनैः पूर्णः", "bājaāraḥ janaiḥ pūrṇaḥ"],
        ["Fireworks at night", "रात्रौ दीपगर्जनानि", "rātrau dīpagarjanāni"],
        ["Happy festival to you", "भवतः उत्सवः शुभः", "bhavataḥ utsavaḥ śubhaḥ"],
        ["We share sweets", "मधुराणि वयं वितरामः", "madhurāṇi vayaṃ vitarāmaḥ"],
        ["Rangoli at the door", "द्वारि रङ्गावलिः", "dvāri raṅgāvaliḥ"],
        ["Pray for prosperity", "समृद्ध्यै प्रार्थयतु", "samṛddhyai prārthayatu"],
        ["See you on the next festival", "अग्रिमे उत्सवे पश्यामः", "agrime utsave paśyāmaḥ"],
    ],
    621: [
        ["Namaste", "नमस्ते", "namaste"],
        ["Good morning", "सुप्रभातम्", "suprabhātam"],
        ["How are you?", "कथमसि?", "katham asi?"],
        ["I am well", "अहं कुशली अस्मि", "ahaṃ kuśalī asmi"],
        ["What is your name?", "भवतः नाम किम्?", "bhavataḥ nāma kim?"],
        ["My name is Rāma", "मम नाम रामः", "mama nāma rāmaḥ"],
        ["Where do you live?", "कुत्र निवससि?", "kutra nivasasi?"],
        ["I live in Delhi", "दिल्ल्याम् अहं निवसामि", "dillyām ahaṃ nivāsāmi"],
        ["Nice to meet you", "भवन्तं मिलित्वा प्रसन्नः अस्मि", "bhavantaṃ militvā prasannaḥ asmi"],
        ["Goodbye", "पुनर्दर्शनम्", "punardarśanam"],
        ["See you again", "पुनः मिलामहे", "punaḥ milāmahe"],
        ["Welcome to our home", "स्वागतम् अस्माकं गृहे", "svāgatam asmākaṃ gṛhe"],
        ["Please sit", "उपविशतु", "upaviśatu"],
        ["Thank you", "धन्यवादः", "dhanyavādaḥ"],
        ["You are kind", "भवान् दयालुः", "bhavān dayāluḥ"],
    ],
    622: [
        ["What time is it?", "कियत् समयः?", "kiyat samayaḥ?"],
        ["It is eight o'clock", "अष्टवादनम्", "aṣṭavādanam"],
        ["Morning", "प्रभातम्", "prabhātam"],
        ["Afternoon", "अपराह्णः", "aparāhṇaḥ"],
        ["Evening", "सायङ्कालः", "sāyaṅkālaḥ"],
        ["Night", "रात्रिः", "rātriḥ"],
        ["Today", "अद्य", "adya"],
        ["Tomorrow", "श्वः", "śvaḥ"],
        ["Yesterday", "ह्यः", "hyaḥ"],
        ["I will come at six", "षड्वादने आगमिष्यामि", "ṣaḍvādane āgamiṣyāmi"],
        ["Wait five minutes", "पञ्च निमेषान् प्रतीक्षताम्", "pañca nimeṣān pratīkṣatām"],
        ["The train is late", "रथयानं विलम्बते", "rathayānaṃ vilambate"],
        ["We leave early", "वयं प्रातः गच्छामः", "vayaṃ prātaḥ gacchāmaḥ"],
        ["After lunch", "उपहारात् परम्", "upahārāt param"],
        ["Before sunset", "सूर्यास्तात् पूर्वम्", "sūryāstāt pūrvam"],
    ],
    623: [
        ["Where is the station?", "स्थानकं कुत्र?", "sthānakaṃ kutra?"],
        ["Go straight", "ऋजु गच्छतु", "ṛju gacchatu"],
        ["Turn left", "वामं वर्ततु", "vāmaṃ vartatu"],
        ["Turn right", "दक्षिणं वर्ततु", "dakṣiṇaṃ vartatu"],
        ["Near the temple", "देवालयस्य समीपे", "devālayasya samīpe"],
        ["Opposite the park", "उद्यानस्य सम्मुखे", "udyānasya sammukhe"],
        ["It is far", "दूरम् अस्ति", "dūram asti"],
        ["It is near", "समीपे अस्ति", "samīpe asti"],
        ["How many kilometres?", "कियत् किलोमीटराणि?", "kiyat kilomīṭarāṇi?"],
        ["This is my village", "अयं मम ग्रामः", "ayaṃ mama grāmaḥ"],
        ["Map on the phone", "दूरवाण्यां नक्शः", "dūravāṇyāṃ nakśaḥ"],
        ["I am lost", "अहं मार्गं न जानामि", "ahaṃ mārgaṃ na jānāmi"],
        ["Show the way", "मार्गं दर्शयतु", "mārgaṃ darśayatu"],
        ["Thank you for help", "साहाय्याय धन्यवादः", "sāhāyyāya dhanyavādaḥ"],
        ["Here we are", "इह अस्मः", "iha asmaḥ"],
    ],
    624: [
        ["I need a room", "मे कक्षा आवश्यका", "me kakṣā āvaśyakā"],
        ["For one night", "एकायां रात्रौ", "ekāyāṃ rātrau"],
        ["What is the rent?", "भाटकं कियत्?", "bhāṭakaṃ kiyat?"],
        ["Is breakfast included?", "प्रातर्भोजनं सम्मिलितम्?", "prātarbhojanaṃ sammilitam?"],
        ["Hot water please", "उष्णं जलं कृपया", "uṣṇaṃ jalaṃ kṛpayā"],
        ["The key please", "कुञ्चिकां देहि", "kuñcikāṃ dehi"],
        ["I will check out tomorrow", "श्वः निर्गमिष्यामि", "śvaḥ nirgamiṣyāmi"],
        ["The room is clean", "कक्षा शुचिः", "kakṣā śuciḥ"],
        ["Air conditioning?", "वायुशीतलम् अस्ति वा?", "vāyuśītalam asti vā?"],
        ["Wi-Fi password?", "वाइफाइ गुप्तपदम्?", "vāifāi guptapadam?"],
        ["Call reception", "स्वागतकक्षां आह्वयतु", "svāgatakakṣām āhvayatu"],
        ["Towels in the bathroom", "स्नानगृहे शणवस्त्राणि", "snānagṛhe śaṇavastrāṇi"],
        ["Quiet floor please", "शान्ततलम् इच्छामि", "śāntatalam icchāmi"],
        ["The lift is there", "लघुयानः तत्र", "laghuyānaḥ tatra"],
        ["Have a pleasant stay", "सुखं निवसतु", "sukhaṃ nivasatu"],
    ],
    625: [
        ["It is hot today", "अद्य उष्णम् अस्ति", "adya uṣṇam asti"],
        ["It is cold", "शीतलम् अस्ति", "śītalām asti"],
        ["It is raining", "वर्षति", "varṣati"],
        ["It will rain", "वर्षिष्यति", "varṣiṣyati"],
        ["Strong wind", "बलवान् वायुः", "balavān vāyuḥ"],
        ["Clear sky", "निर्मलं आकाशम्", "nirmalaṃ ākāśam"],
        ["Thunder", "अनिर्ह्रादः", "anirhrādaḥ"],
        ["Lightning", "विद्युत्", "vidyut"],
        ["Fog in the morning", "प्रभाते कुहरम्", "prabhāte kuharam"],
        ["Take an umbrella", "छत्रं गृहाण", "chatraṃ gṛhāṇa"],
        ["Wear warm clothes", "उष्णवस्त्राणि धारय", "uṣṇavastrāṇi dhāraya"],
        ["The weather is pleasant", "वातावरणम् रमणीयम्", "vātāvaraṇam ramaṇīyam"],
        ["Summer season", "ग्रीष्मऋतुः", "grīṣmaṛtuḥ"],
        ["Rainy season", "वर्षाऋतुः", "varṣāṛtuḥ"],
        ["Winter season", "शिशिरऋतुः", "śiśiraṛtuḥ"],
    ],
    626: [
        ["Sir, documents please", "भोः, लेखाः दर्शयतु", "bhoḥ, lekhāḥ darśayatu"],
        ["Driving licence", "चालनानुमतिः", "chālanānumatiḥ"],
        ["I was not speeding", "अहं वेगं न अवर्धयम्", "ahaṃ vegaṃ na avardhayam"],
        ["Seat belt is on", "आसनबन्धनं बद्धम्", "āsanabandhanaṃ baddham"],
        ["Where is the parking?", "वाहनस्थानं कुत्र?", "vāhanasthānaṃ kutra?"],
        ["Pay the fine", "दण्डं ददातु", "daṇḍaṃ dadātu"],
        ["This is one-way", "एकमार्गः अयम्", "ekamārgaḥ ayam"],
        ["Slow down", "मन्दं चालयतु", "mandaṃ chālayatu"],
        ["Helmet for two-wheeler", "द्विचक्रवाहने शिरस्त्राणम्", "dvichakravāhane śirastrāṇam"],
        ["Signal is red", "सङ्केतः रक्तः अस्ति", "saṅketaḥ raktaḥ asti"],
        ["No entry", "प्रवेशः न अस्ति", "praveśaḥ na asti"],
        ["Accident ahead", "अग्रे दुर्घटना", "agre durghaṭanā"],
        ["Take care", "अपेक्षां कुरु", "apekṣāṃ kuru"],
        ["Thank you, officer", "धन्यवादः अधिकारिन्", "dhanyavādaḥ adhikārin"],
        ["Drive safely", "सुरक्षया चालयतु", "surakṣayā chālayatu"],
    ],
    627: [
        ["Take me to the station", "मां स्थानकं नयतु", "māṃ sthānakaṃ nayatu"],
        ["How much fare?", "भाटकं कियत्?", "bhāṭakaṃ kiyat?"],
        ["By meter", "मापकेन", "māpakena"],
        ["Please hurry", "शीघ्रम् कुरु", "śīghram kuru"],
        ["Stop here", "इह स्थापयतु", "iha sthāpayatu"],
        ["Keep the change", "परिवर्तनं रक्षतु", "parivartanaṃ rakṣatu"],
        ["Turn at the crossing", "चतुष्पथे वर्ततु", "catuṣpathe vartatu"],
        ["Avoid traffic", "यानजटिलतां परिहरतु", "yānajaṭilatāṃ pariharatu"],
        ["Is this the shortest route?", "अयं लघिष्ठः मार्गः?", "ayaṃ laghiṣṭhaḥ mārgaḥ?"],
        ["My bag is in the boot", "मम सङ्ग्रहः पृष्ठभागे", "mama saṅgrahaḥ pṛṣṭhabhāge"],
        ["Drop me at the gate", "मां द्वारि अवतारयतु", "māṃ dvāri avatārayatu"],
        ["Call when you arrive", "आगच्छति स्मारयतु", "āgacchati smārayatu"],
        ["Shared ride?", "सहयानम्?", "sahayānam?"],
        ["Receipt please", "रसीदं देहि", "rasīdaṃ dehi"],
        ["Thanks, drive safely", "धन्यवादः सुरक्षया चालयतु", "dhanyavādaḥ surakṣayā chālayatu"],
    ],
    628: [
        ["The build failed", "निर्माणं विफलम् अभवत्", "nirmāṇaṃ viphalam abhavat"],
        ["Check the logs", "अभिलेखान् पश्यतु", "abhilekhān paśyatu"],
        ["Push the code", "संहितां प्रेषयतु", "saṃhitāṃ preṣayatu"],
        ["Pull latest changes", "नवीनतमान् परिवर्तनान् आनयतु", "navīnatamān parivartanān ānayatu"],
        ["Open a ticket", "पत्रिकाम् उद्घाटयतु", "patrikām udghāṭayatu"],
        ["The server is down", "सेवकः अधः अस्ति", "sevakaḥ adhaḥ asti"],
        ["Restart the service", "सेवां पुनः आरभतु", "sevāṃ punaḥ ārabhatu"],
        ["Bug in production", "उत्पादने दोषः", "utpādane doṣaḥ"],
        ["Meeting at ten", "दशवादने सभा", "daśavādane sabhā"],
        ["I will send the patch", "परिष्कारं प्रेषयिष्यामि", "pariṣkāraṃ preṣayiṣyāmi"],
        ["Code review pending", "संहितापरीक्षा प्रलम्बते", "saṃhitāparīkṣā pralambate"],
        ["Deploy tomorrow", "श्वः विसर्पणम्", "śvaḥ visarpaṇam"],
        ["Branch merged", "शाखा मिलिता", "śākhā militā"],
        ["Database backup", "आधारसञ्चिका पृष्ठबन्धनम्", "ādhārasañcikā pṛṣṭhabandhanam"],
        ["Let us pair-program", "युग्मसंहितां कुर्मः", "yugmasaṃhitāṃ kurmaḥ"],
    ],
    629: [
        ["Half kilogram rice", "अर्धकिलो व्रीहिः", "ardhakilo vrīhiḥ"],
        ["One litre oil", "एकलिटर् तैलम्", "ekaliṭar tailam"],
        ["What is the price?", "मूल्यं कियत्?", "mūlyaṃ kiyat?"],
        ["Give discount", "छूटं देहि", "chūṭaṃ dehi"],
        ["Fresh vegetables", "ताजानि शाकानि", "tājāni śākāni"],
        ["Do you have milk?", "क्षीरम् अस्ति वा?", "kṣīram asti vā?"],
        ["Total amount", "समष्टिमूल्यम्", "samaṣṭimūlyam"],
        ["I need a carry bag", "वहनपेटिकां देहि", "vahanapeṭikāṃ dehi"],
        ["Bill please", "प्रणालीं देहि", "praṇālīṃ dehi"],
        ["Sugar and salt", "शर्करा लवणं च", "śarkarā lavaṇaṃ ca"],
        ["Organic produce", "जैविकं फलम्", "jaivikaṃ phalam"],
        ["Card or cash?", "पत्रिका उत नकदम्?", "patrikā uta nakadam?"],
        ["Home delivery?", "गृहप्रेषणम्?", "gṛhapreṣaṇam?"],
        ["This is stale", "इदं नवीनं न अस्ति", "idaṃ navīnaṃ na asti"],
        ["See you next week", "अग्रिमे सप्ताहे पश्यामः", "agrime saptāhe paśyāmaḥ"],
    ],
    630: [
        ["What is the problem?", "कः समस्या?", "kaḥ samasyā?"],
        ["I have fever", "मे ज्वरः अस्ति", "me jvaraḥ asti"],
        ["Since three days", "त्रिभिः दिनैः", "tribhiḥ dinaiḥ"],
        ["Take this medicine", "एतत् औषधं गृहाण", "etat auṣadhaṃ gṛhāṇa"],
        ["Twice a day", "द्विवारं दिने", "divivāraṃ dine"],
        ["After food", "भोजनात् परम्", "bhojanāt param"],
        ["Rest well", "सुष्ठु विश्रामं कुरु", "suṣṭhu viśrāmaṃ kuru"],
        ["Drink more water", "बहु जलं पिब", "bahu jalaṃ piba"],
        ["Blood test needed", "रक्तपरीक्षा आवश्यका", "raktaparīkṣā āvaśyakā"],
        ["No allergy", "प्रतिक्रिया न अस्ति", "pratikriyā na asti"],
        ["When to come again?", "पुनः कदा आगन्तव्यम्?", "punaḥ kadā āgantavyam?"],
        ["Get well soon", "शीघ्रं स्वस्थः भव", "śīghraṃ svasthaḥ bhava"],
        ["Emergency", "आपद्", "āpad"],
        ["Prescription here", "लेखः अत्र", "lekhaḥ atra"],
        ["Thank you, doctor", "धन्यवादः वैद्य", "dhanyavādaḥ vaidya"],
    ],
    631: [
        ["Open your books", "पुस्तकानि उद्घाटयतु", "pustakāni udghāṭayatu"],
        ["Read page ten", "दशमं पृष्ठं पठतु", "daśamaṃ pṛṣṭhaṃ paṭhatu"],
        ["Any questions?", "काः प्रश्नाः?", "kāḥ praśnāḥ?"],
        ["Raise your hand", "हस्तं उन्नयतु", "hastaṃ unnayatu"],
        ["Homework for tomorrow", "श्वः गृहकार्यम्", "śvaḥ gṛhakāryam"],
        ["Sit quietly", "मौने उपविशतु", "maune upaviśatu"],
        ["Excellent answer", "उत्तमम् उत्तरम्", "uttamam uttaram"],
        ["Try again", "पुनः यतताम्", "punaḥ yatatām"],
        ["Group discussion", "समूहचर्चा", "samūhacarcā"],
        ["Exam next week", "अग्रिमे सप्ताहे परीक्षा", "agrime saptāhe parīkṣā"],
        ["Do not copy", "न अनुकरणं कुरु", "na anukaraṇaṃ kuru"],
        ["Library books", "पुस्तकालयग्रन्थाः", "pustakālayagranthāḥ"],
        ["Recess time", "विरामसमयः", "virāmasamayaḥ"],
        ["Bell rang", "घण्टा अनादिता", "ghaṇṭā anāditā"],
        ["Class dismissed", "कक्षा विसर्जिता", "kakṣā visarjitā"],
    ],
    632: [
        ["Hello, is this Rāma?", "हलो, अयं रामः वा?", "halo, ayaṃ rāmaḥ vā?"],
        ["Speaking", "वदामि", "vadāmi"],
        ["Call you back", "पुनः आह्वयिष्यामि", "punaḥ āhvayiṣyāmi"],
        ["Signal is weak", "सङ्केतः दुर्बलः", "saṅketaḥ durbalaḥ"],
        ["Can you hear me?", "श‍ृणोषि वा?", "śṛṇoṣi vā?"],
        ["Wrong number", "मिथ्या सङ्ख्या", "mithyā saṅkhyā"],
        ["Text me the address", "सङ्केतं लिखित्वा प्रेषयतु", "saṅketam likhitvā preṣayatu"],
        ["I am busy now", "अधुना व्यस्तः अस्मि", "adhunā vyastaḥ asmi"],
        ["Talk later", "पश्चात् वदामः", "paścāt vadāmaḥ"],
        ["Battery low", "कोशः न्यूनः", "kośaḥ nyūnaḥ"],
        ["Where are you?", "कुत्र असि?", "kutra asi?"],
        ["On my way", "मार्गे अस्मि", "mārge asmi"],
        ["Got it", "गृहीतम्", "gṛhītam"],
        ["Bye", "पुनर्मिलामहे", "punarmilāmahe"],
        ["Take care", "स्वस्थः भव", "svasthaḥ bhava"],
    ],
    633: [
        ["How much per kilo?", "प्रतिकिलो कियत्?", "pratikilo kiyat?"],
        ["These tomatoes", "एते रक्तफलानि", "ete raktaphalāni"],
        ["Too expensive", "अतिमहत् मूल्यम्", "atimahat mūlyam"],
        ["Give fresh ones", "ताजानि देहि", "tājāni dehi"],
        ["I need coriander", "मे धान्यकम् आवश्यकम्", "me dhānyakam āvaśyakam"],
        ["Weigh it", "तोलयतु", "tolayatu"],
        ["Carry bag", "वहनपेटिका", "vahanapeṭikā"],
        ["Change please", "परिवर्तनं देहि", "parivartanaṃ dehi"],
        ["Organic vegetables", "जैविकानि शाकानि", "jaivikāni śākāni"],
        ["No plastic", "प्लास्टिकम् न इच्छामि", "plāṣṭikam na icchāmi"],
        ["Market closes at eight", "अष्टवादने बाजारः बध्यते", "aṣṭavādane bājaāraḥ badhyate"],
        ["Good quality", "उत्तमगुणः", "uttamaguṇaḥ"],
        ["I will take two kilos", "द्वौ किलौ ग्रहिष्यामि", "dvau kilau grahṣyāmi"],
        ["See you tomorrow", "श्वः पश्यामः", "śvaḥ paśyāmaḥ"],
        ["Thanks", "धन्यवादः", "dhanyavādaḥ"],
    ],
    634: [
        ["Which bus goes to the fort?", "कः बसः दुर्गं गच्छति?", "kaḥ basaḥ durgaṃ gacchati?"],
        ["Platform number?", "मञ्चसङ्ख्या?", "mañcasaṅkhyā?"],
        ["When does it leave?", "कदा प्रस्थाति?", "kadā prasthāti?"],
        ["Is this seat free?", "इदम् आसनं मुक्तम्?", "idam āsanaṃ muktam?"],
        ["Ticket to city centre", "नगरमध्यस्य टिकटम्", "nagaramadhyasya ṭikaṭam"],
        ["Conductor", "याननियन्ता", "yānaniyantā"],
        ["Next stop", "अग्रिमं स्थानकम्", "agrimaṃ sthānakam"],
        ["I will get down here", "अत्र अवतरिष्यामि", "atra avatarṣyāmi"],
        ["Traffic jam", "यानजटिलता", "yānajaṭilatā"],
        ["Stand in line", "पङ्क्तौ स्थीयताम्", "paṅktau sthīyatām"],
        ["Lost my pass", "मम पत्रं नष्टम्", "mama patraṃ naṣṭam"],
        ["Is there Wi-Fi?", "वाइफाइ अस्ति वा?", "vāifāi asti vā?"],
        ["Rough ride", "कठोरा यात्रा", "kaṭhorā yātrā"],
        ["Arrival time", "आगमनसमयः", "āgamanasamayaḥ"],
        ["Thank you", "धन्यवादः", "dhanyavādaḥ"],
    ],
    635: [
        ["Excuse me, where is Lane 4?", "क्षम्यताम्, चतुर्थपथः कुत्र?", "kṣamyatām, caturthapathaḥ kutra?"],
        ["Near the post office", "पत्रालयस्य समीपे", "patrālayasya samīpe"],
        ["Opposite the school", "विद्यालयस्य सम्मुखे", "vidyālayasya sammukhe"],
        ["Second building", "द्वितीयं भवनम्", "dvitīyaṃ bhavanam"],
        ["Ask that shopkeeper", "तम् आपणिकं पृच्छतु", "tam āpaṇikaṃ pṛcchatu"],
        ["I cannot find it", "न लभे", "na labhe"],
        ["Is it far?", "दूरम् वा?", "dūram vā?"],
        ["About five minutes walk", "पञ्चनिमेषपदयात्रा", "pañcanimeṣapadayātrā"],
        ["Map on phone", "दूरवाण्यां नक्शः", "dūravāṇyāṃ nakśaḥ"],
        ["Landmark?", "सीमाचिह्नम्?", "sīmācihnam?"],
        ["Behind the temple", "देवालयस्य पृष्ठे", "devālayasya pṛṣṭhe"],
        ["Straight then left", "ऋजु ततो वामम्", "ṛju tato vāmam"],
        ["You reached", "आगताः", "āgatāḥ"],
        ["Thank you so much", "बहु धन्यवादः", "bahu dhanyavādaḥ"],
        ["Have a good day", "शुभं दिनम्", "śubhaṃ dinam"],
    ],
    636: [
        ["I like you very much", "त्वां बहु प्रियं करोमि", "tvāṃ bahu priyaṃ karomi"],
        ["Will you walk with me?", "मया सह गन्तुम् इच्छसि वा?", "mayā saha gantum icchasi vā?"],
        ["You are special to me", "त्वं मे विशिष्टः", "tvaṃ me viśiṣṭaḥ"],
        ["May I meet your parents?", "भवतः पितरौ द्रष्टुम् शक्नोमि वा?", "bhavataḥ pitarau draṣṭum śaknomi vā?"],
        ["I respect your feelings", "भावान् गौरवयामि", "bhāvān gauravayāmi"],
        ["Take your time", "भवतः समयः अस्तु", "bhavataḥ samayaḥ astu"],
        ["No pressure", "न कोऽपि दण्डः", "na ko'pi daṇḍaḥ"],
        ["Whatever you decide", "यत् निश्चिनोषि", "yat niścinoṣi"],
        ["I will wait", "प्रतीक्षे", "pratīkṣe"],
        ["Thank you for honesty", "सत्यस्य कृते धन्यवादः", "satyasya kṛte dhanyavādaḥ"],
        ["Friendship first", "मैत्री प्रथमा", "maitrī prathamā"],
        ["Can we talk?", "वदामः वा?", "vadāmaḥ vā?"],
        ["You make me happy", "त्वं मे सुखं करोषि", "tvaṃ me sukhaṃ karoṣi"],
        ["Good night", "शुभ रात्रिः", "śubha rātriḥ"],
        ["Sweet dreams", "मधुरा स्वप्नाः", "madhurā svapnāḥ"],
    ],
    637: [
        ["Tell me about yourself", "स्वविषये वदतु", "svaviṣaye vadata"],
        ["My education", "मम शिक्षा", "mama śikṣā"],
        ["Work experience", "कार्यानुभवः", "kāryānubhavaḥ"],
        ["Why this company?", "किमर्थम् एतत् संस्था?", "kimartham etat saṃsthā?"],
        ["Strengths and weaknesses", "बलानि दौर्बल्यानि च", "balāni daurbalyāni ca"],
        ["Salary expectation", "वेतनप्रत्याशा", "vetanapratyāśā"],
        ["Notice period", "सूचनाकालः", "sūcanākālaḥ"],
        ["I can join next month", "अग्रिमे मासि प्रवेशिष्यामि", "agrime māsi praveṣiṣyāmi"],
        ["Thank you for the opportunity", "अवसराय धन्यवादः", "avasarāya dhanyavādaḥ"],
        ["Questions for us?", "अस्माकं प्रश्नाः?", "asmākaṃ praśnāḥ?"],
        ["Team player", "दलस्य सदस्यः", "dalasya sadasyaḥ"],
        ["Remote work", "दूरकार्यम्", "dūrakāryam"],
        ["Deadline pressure", "अन्तिमदिनदण्डः", "antimadinadaṇḍaḥ"],
        ["I look forward to hearing", "श‍ृणोमि इति प्रतीक्षे", "śṛṇomi iti pratīkṣe"],
        ["Goodbye", "पुनर्मिलामहे", "punarmilāmahe"],
    ],
    638: [
        ["Please clean the kitchen", "रसोदं शोधयतु", "rasodaṃ śodhayatu"],
        ["Wash the dishes", "भाण्डानि धावयतु", "bhāṇḍāni dhāvayatu"],
        ["Sweep the floor", "भूमिं समार्जयतु", "bhūmiṃ samārjayatu"],
        ["Garbage outside", "मलम् बहिः क्षिपतु", "malam bahiḥ kṣipatu"],
        ["Iron the clothes", "वस्त्राणि प्रेसयतु", "vastrāṇi presayatu"],
        ["Buy vegetables", "शाकानि क्रीणीतु", "śākāni krīṇītu"],
        ["Water the plants", "वृक्षान् सिञ्चतु", "vṛkṣān siñcatu"],
        ["Lock the door", "द्वारं बध्नातु", "dvāraṃ badhnātu"],
        ["I will pay monthly", "मासिकं दास्यामि", "māsikaṃ dāsyāmi"],
        ["Day off on Sunday", "रविवासरे विरामः", "ravivāsare virāmaḥ"],
        ["Call if anything needed", "आवश्यकते आह्वयतु", "āvaśyakate āhvayatu"],
        ["The guests are coming", "अतिथयः आगच्छन्ति", "atithayaḥ āgacchanti"],
        ["Be careful with glass", "काचे अपेक्षां कुरु", "kāce apekṣāṃ kuru"],
        ["Thank you for your help", "साहाय्याय धन्यवादः", "sāhāyyāya dhanyavādaḥ"],
        ["Take rest", "विश्रामं कुरु", "viśrāmaṃ kuru"],
    ],
    639: [
        ["I want to link Aadhaar to mobile", "आधारं दूरवाण्यै सन्धातुम् इच्छामि", "ādhāraṃ dūravāṇyai sandhātum icchāmi"],
        ["OTP came", "एककालिकः संकेतः आगतः", "ekakālikaḥ saṃketaḥ āgataḥ"],
        ["Enter the number", "सङ्ख्यां निवेशयतु", "saṅkhyāṃ niveśayatu"],
        ["Verify identity", "परिचयं सत्यापयतु", "paricayaṃ satyāpayatu"],
        ["Store is crowded", "आपणः जनैः पूर्णः", "āpaṇaḥ janaiḥ pūrṇaḥ"],
        ["Take a token", "लक्षणं गृहाण", "lakṣaṇaṃ gṛhāṇa"],
        ["Biometric failed", "जैवमापनं विफलम्", "jaivamāpanaṃ viphalam"],
        ["Try again", "पुनः यतताम्", "punaḥ yatatām"],
        ["Bring original card", "मूलपत्रिकां आनयतु", "mūlapatrikām ānayatu"],
        ["Process takes time", "प्रक्रिया कालं गृह्णाति", "prakriyā kālaṃ gṛhṇāti"],
        ["SMS confirmation", "संदेशदृढीकरणम्", "sandeadṛḍhīkaraṇam"],
        ["Help desk there", "साहाय्यमेजा तत्र", "sāhāyyamejā tatra"],
        ["Link successful", "सन्धिः सफलः", "sandhiḥ safalaḥ"],
        ["Any charges?", "शुल्कम् अस्ति वा?", "śulkam asti vā?"],
        ["Thank you", "धन्यवादः", "dhanyavādaḥ"],
    ],
    640: [
        ["Link mobile to Aadhaar", "दूरवाणिं आधाराय सन्धत्ताम्", "dūravāṇim ādhārāya sandhattām"],
        ["Same as before", "पूर्ववत्", "pūrvavat"],
        ["Update number in bank", "वाण्यां सङ्ख्यां नवीकरोतु", "vāṇyāṃ saṅkhyāṃ navīkarotu"],
        ["OTP to phone", "दूरवाण्यै एककालिकः", "dūravāṇyai ekakālikaḥ"],
        ["Valid ID proof", "मान्यं परिचयपत्रम्", "mānyaṃ paricayapatram"],
        ["Photocopy needed", "प्रतिलिखनम् आवश्यकम्", "pratilikhanam āvaśyakam"],
        ["Sign here", "अत्र हस्ताक्षरम्", "atra hastākṣaram"],
        ["Wait for SMS", "संदेशाय प्रतीक्षताम्", "sandeśāya pratīkṣatām"],
        ["Server slow", "सेवकः मन्दः", "sevakaḥ mandaḥ"],
        ["Try later", "पश्चात् यतताम्", "paścāt yatatām"],
        ["Customer care number", "ग्राहकसेवासङ्ख्या", "grāhakasevāsaṅkhyā"],
        ["Complaint book", "अभियोगपुस्तकम्", "abhiyogapustakam"],
        ["Done", "समाप्तम्", "samāptam"],
        ["Receipt", "रसीदः", "rasīdaḥ"],
        ["Thanks", "धन्यवादः", "dhanyavādaḥ"],
    ],
    641: [
        ["Happy Republic Day", "गणतन्त्रदिनस्य शुभाः", "gaṇatantradinasya śubhāḥ"],
        ["Flag hoisting at eight", "अष्टवादने ध्वजारोहणम्", "aṣṭavādane dhvajārohaṇam"],
        ["National anthem", "राष्ट्रगीतम्", "rāṣṭragītam"],
        ["March past", "परेड्", "pareḍ"],
        ["Chief guest speech", "मुख्यातिथिवचनम्", "mukhyātithivacanam"],
        ["Children’s programme", "बालकानां कार्यक्रमः", "bālakānāṃ kāryakramaḥ"],
        ["Distribution of sweets", "मधुरवितरणम्", "madhuravitarṇam"],
        ["Patriotic songs", "देशभक्तिगीतानि", "deśabhaktigītāni"],
        ["Remember the Constitution", "संविधानं स्मरतु", "saṃvidhānaṃ smaratu"],
        ["Unity in diversity", "विविधतायां एकता", "vividhatāyāṃ ekatā"],
        ["Wear tricolour", "त्रिवर्णं धारयतु", "tivarṇaṃ dhārayatu"],
        ["School holiday", "विद्यालये विरामः", "vidyālaye virāmaḥ"],
        ["Watch parade on TV", "दूरदर्शने परेड् पश्यतु", "dūradarśane pareḍ paśyatu"],
        ["Jai Hind", "जय हिन्द्", "jaya hind"],
        ["Proud to be Indian", "भारतीयः भवितुम् गर्वः", "bhāratīyaḥ bhavitum garvaḥ"],
    ],
}
