# Sanskrit Lesson 5 — Conversation practice B (chapter IDs 642–662).

LESSONS_S5B = {
    642: [
        ["I need to withdraw cash", "नकदं निष्कासयितुम् इच्छामि", "nakadaṃ niṣkāsayitum icchāmi"],
        ["What is the balance?", "शेषं कियत्?", "śeṣaṃ kiyat?"],
        ["Fill this form", "एतत् पत्रं पूरयतु", "etat patraṃ pūrayatu"],
        ["Account number", "गणनासङ्ख्या", "gaṇanāsaṅkhyā"],
        ["Cheque deposit", "लेखां निक्षिपतु", "lekhāṃ nikṣipatu"],
        ["Passbook update", "पासपुस्तकं नवीकरोतु", "pāsapustakaṃ navīkarotu"],
        ["Token for counter", "मञ्चाय लक्षणम्", "mañcāya lakṣaṇam"],
        ["Locker facility", "लॉकरसुविधा", "lŏkarasuvidhā"],
        ["Net banking help", "जालबैङ्किङ्गसाहाय्यम्", "jālabaiṅkingasāhāyyam"],
        ["Minimum balance", "न्यूनतमशेषम्", "nyūnatamaśeṣam"],
        ["Loan enquiry", "ऋणपरीक्षा", "ṛṇaparīkṣā"],
        ["Interest rate", "वृद्धिदरः", "vṛddhidaraḥ"],
        ["Working hours", "कार्यसमयः", "kāryasamayaḥ"],
        ["Thank you", "धन्यवादः", "dhanyavādaḥ"],
        ["Goodbye", "पुनर्मिलामहे", "punarmilāmahe"],
    ],
    643: [
        ["When does the temple open?", "देवालयः कदा उद्घाट्यते?", "devālayaḥ kadā udghāṭyate?"],
        ["Dress code?", "वस्त्रनियमः?", "vastraniyamaḥ?"],
        ["Photography allowed?", "छायाचित्रणम् अनुमतम्?", "chāyāchitaraṇam anumatam?"],
        ["Prasad time", "प्रसादसमयः", "prāsādasamayaḥ"],
        ["Footwear outside", "पादुके बहिः", "pāduke bahiḥ"],
        ["Guided tour?", "मार्गदर्शनम्?", "mārgadarśanam?"],
        ["How old is this temple?", "अयं देवालयः कियत् पुरातनः?", "ayaṃ devālayaḥ kiyat purātanaḥ?"],
        ["Special festival today?", "अद्य विशेषोत्सवः?", "adya viśeṣotsavaḥ?"],
        ["Donation box", "दानपेटिका", "dānapeṭikā"],
        ["Aarti at six", "षड्वादने आरात्रिकम्", "ṣaḍvādane ārātrikam"],
        ["Quiet please", "मौनं कुरु", "maunaṃ kuru"],
        ["Parking area", "वाहनस्थानम्", "vāhanasthānam"],
        ["Thank you for information", "विज्ञानाय धन्यवादः", "vijñānāya dhanyavādaḥ"],
        ["Beautiful architecture", "सुन्दरं वास्तुशिल्पम्", "sundaraṃ vāstuśilpam"],
        ["Om Shanti", "ॐ शान्तिः", "oṃ śāntiḥ"],
    ],
    644: [
        ["Please pass the rice", "व्रीहीन् प्रेरयतु", "vrīhīn prerayatu"],
        ["This curry is tasty", "एतत् शाकं स्वादु अस्ति", "etat śākaṃ svādu asti"],
        ["A little more", "अल्पं अधिकम्", "alpaṃ adhikam"],
        ["I am vegetarian", "अहं शाकाहारी अस्मि", "ahaṃ śākāhārī asmi"],
        ["No onion for me", "मे पलाण्डुः न", "me palāṇḍuḥ na"],
        ["Your parents are kind", "भवतः पितरौ दयालू", "bhavataḥ pitarau dayālū"],
        ["Thank you for the meal", "भोजनाय धन्यवादः", "bhojanāya dhanyavādaḥ"],
        ["May I have water?", "जलं लब्धुम् शक्नोमि वा?", "jalaṃ labdhum śaknomi vā?"],
        ["Everything was delicious", "सर्वं स्वादु आसीत्", "sarvaṃ svādu āsīt"],
        ["Homemade pickle", "गृहनिर्मितं लवणम्", "gṛhanirmitaṃ lavaṇam"],
        ["Second helping", "द्वितीयं परिमाणम्", "dvitīyaṃ parimāṇam"],
        ["I am full", "अहं पूर्णः अस्मि", "ahaṃ pūrṇaḥ asmi"],
        ["Compliments to the cook", "पाचकाय साधु", "pācakāya sādhu"],
        ["Lovely hospitality", "रमणीयं अतिथिसत्कारम्", "ramaṇīyaṃ atithisatkāram"],
        ["Hope to visit again", "पुनः आगमिष्यामि इति आशा", "punaḥ āgamiṣyāmi iti āśā"],
    ],
    645: [
        ["Did you see the match?", "क्रीडां दृष्टवान् वा?", "krīḍāṃ dṛṣṭavān vā?"],
        ["What was the score?", "अङ्कः कः आसीत्?", "aṅkaḥ kaḥ āsīt?"],
        ["Last-minute goal", "अन्तिमनिमेषगोलः", "antimanimeṣagolaḥ"],
        ["The referee was wrong", "निर्णायकः मिथ्या आसीत्", "nirṇāyakaḥ mithyā āsīt"],
        ["Our team won", "अस्माकं दलं जितवत्", "asmākaṃ dalaṃ jitavat"],
        ["Penalty missed", "दण्डः विहीनः", "daṇḍaḥ vihīnaḥ"],
        ["Stadium was full", "क्रीडाङ्गणं पूर्णम् आसीत्", "krīḍāṅgaṇaṃ pūrṇam āsīt"],
        ["Next match on Sunday", "अग्रिमा क्रीडा रविवासरे", "agrimā krīḍā ravivāsare"],
        ["Best player", "श्रेष्ठः क्रीडकः", "śreṣṭhaḥ krīḍakaḥ"],
        ["Injury time", "आघातसमयः", "āghātasamayaḥ"],
        ["VAR decision", "दूरदर्शिनिर्णयः", "dūradarśinirṇayaḥ"],
        ["I recorded highlights", "प्रमुखांशान् अभिलिखम्", "pramukhāṃśān abhilikham"],
        ["Unbelievable", "अविश्वसनीयम्", "aviśvāsanīyam"],
        ["Rematch soon", "पुनःक्रीडा शीघ्रम्", "punaḥkrīḍā śīghram"],
        ["Let’s watch together", "सह पश्यामः", "saha paśyāmaḥ"],
    ],
    646: [
        ["New movie this Friday", "नवीनं चलचित्रम् अस्मिन् शुक्रवासरे", "navīnaṃ calacitram asmin śukravāsare"],
        ["Evening show?", "सायङ्कालप्रदर्शनम्?", "sāyaṅkālapradarśanam?"],
        ["Book tickets online", "जालेन टिकटानि क्रीणीतु", "jālena ṭikaṭāni krīṇītu"],
        ["Popcorn and drink", "भृष्टशिम्बाः पानं च", "bhṛṣṭaśimbāḥ pānaṃ ca"],
        ["Seats in the middle", "मध्ये आसनानि", "madhye āsanāni"],
        ["Subtitles on", "उपशीर्षकाः सन्ति", "upaśīrṣakāḥ santi"],
        ["Interval now", "अन्तरालम् अधुना", "antarālam adhunā"],
        ["Great direction", "उत्तमं निर्देशनम्", "uttamaṃ nirdeśanam"],
        ["Boring first half", "प्रथमार्धं नीरसम्", "prathamārdhaṃ nīrasam"],
        ["Climax was thrilling", "पराकाष्ठा रोमाञ्चकारिणी", "parākāṣṭhā romāñcakāriṇī"],
        ["Let’s leave early", "शीघ्रं गच्छामः", "śīghraṃ gacchāmaḥ"],
        ["Parking trouble", "वाहनस्थाने क्लेशः", "vāhanasthāne kleśaḥ"],
        ["Review tomorrow", "श्वः समीक्षा", "śvaḥ samīkṣā"],
        ["Worth watching", "द्रष्टव्यम्", "draṣṭavyam"],
        ["Plan next weekend", "अग्रिमे सप्ताहान्ते योजयामः", "agrime saptāhānte yojayāmaḥ"],
    ],
    647: [
        ["Which teams in the final?", "अन्तिमक्रीडायां के दलौ?", "antimakrīḍāyāṃ ke dalau?"],
        ["World cup schedule", "जगत्कपकार्यक्रमः", "jagatkapakāryakramaḥ"],
        ["Time zone trouble", "कालवलयक्लेशः", "kālavalayakleśaḥ"],
        ["Penalty shootout", "दण्डप्रहाराः", "daṇḍaprahārāḥ"],
        ["Offside trap", "अपसारणजालम्", "apasāraṇajālam"],
        ["Red card", "रक्तपत्रिका", "raktapatrikā"],
        ["Extra time", "अतिरिक्तसमयः", "atiriktasamayaḥ"],
        ["Fans are loud", "प्रशंसकाः उच्चैः", "praśaṃsakāḥ uccaiḥ"],
        ["Stadium atmosphere", "क्रीडाङ्गणवातावरणम्", "krīḍāṅgaṇavātāvaraṇam"],
        ["Historic win", "ऐतिहासिकं जयम्", "aitihāsikaṃ jayam"],
        ["Highlights reel", "प्रमुखदृश्यावलिः", "pramukhadṛśyāvaliḥ"],
        ["Interview after match", "क्रीडायाः पश्चात् साक्षात्कारः", "krīḍāyāḥ paścāt sākṣātkāraḥ"],
        ["Injured star player", "आघातितः प्रमुखक्रीडकः", "āghātitaḥ pramukhakrīḍakaḥ"],
        ["Fair play", "न्याय्यक्रीडा", "nyāyyakrīḍā"],
        ["See you at final", "अन्तिमे मिलामहे", "antime milāmahe"],
    ],
    648: [
        ["Welcome to our city", "अस्माकं नगरं स्वागतम्", "asmākaṃ nagaraṃ svāgatam"],
        ["This fort is five hundred years old", "अयं दुर्गः पञ्चशतवर्षीयः", "ayaṃ durgaḥ pañcaśatavarṣīyaḥ"],
        ["Photography allowed here?", "इह छायाचित्रणम् अनुमतम्?", "iha chāyāchitaraṇam anumatam?"],
        ["Best time to visit", "द्रष्टुम् उत्तमः समयः", "draṣṭum uttamaḥ samayaḥ"],
        ["Local food to try", "स्थानीयमन्नं चेतयितव्यम्", "sthānīyamannaṃ cetayitavyam"],
        ["Souvenir shops there", "स्मृतिवस्तुक्रयणानि तत्र", "smṛtivastukrayaṇāni tatra"],
        ["Mind your belongings", "स्वसामग्रीं रक्षतु", "svasāmagrīṃ rakṣatu"],
        ["Stay hydrated", "जलं पिबतु", "jalaṃ pibatu"],
        ["Tomorrow we visit the lake", "श्वः सरसम् द्रक्ष्यामः", "śvaḥ sarasam drakṣyāmaḥ"],
        ["Wear comfortable shoes", "सुखकारिणौ पादुकौ धारयतु", "sukhakāriṇau pādukau dhārayatu"],
        ["Guide fee included?", "मार्गदर्शनशुल्कः सम्मिलितः?", "mārgadarśanaśulkaḥ sammilitaḥ?"],
        ["History in brief", "संक्षिप्ता इतिहासः", "saṃkṣiptā itihāsaḥ"],
        ["Thank you for visiting", "आगमनाय धन्यवादः", "āgamānāya dhanyavādaḥ"],
        ["Hope you enjoyed", "रमणीयम् आसीत् इति आशा", "ramaṇīyam āsīt iti āśā"],
        ["Safe journey", "सुरक्षिता यात्रा", "surakṣitā yātrā"],
    ],
    649: [
        ["Good morning, please sit", "सुप्रभातम् उपविशतु", "suprabhātam upaviśatu"],
        ["Read this passage", "एतत् अंशं पठतु", "etat aṃśaṃ paṭhatu"],
        ["Answer in Sanskrit", "संस्कृते उत्तरं देहि", "saṃskṛte uttaraṃ dehi"],
        ["Simple present tense", "वर्तमानकालः", "vartamānakālaḥ"],
        ["Translate to English", "आङ्ग्लभाषां अन्वादयतु", "āṅglabhāṣāṃ anvādayatu"],
        ["Five minutes left", "पञ्च निमेषाः शेषाः", "pañca nimeṣāḥ śeṣāḥ"],
        ["Spelling matters", "वर्णविन्यासः महत्त्वपूर्णः", "varṇavinyāsaḥ mahattvapūrṇaḥ"],
        ["Speak clearly", "स्पष्टं वदतु", "spaṣṭaṃ vadata"],
        ["Next candidate", "अग्रिमः अभ्यर्थी", "agrimaḥ abhyarthī"],
        ["Thank you, results by email", "धन्यवादः फलम् ईमेलद्वारा ज्ञास्यते", "dhanyavādaḥ phalam īmailadvārā jñāsyate"],
        ["Do you have other languages?", "अन्याः भाषाः अस्ति वा?", "anyāḥ bhāṣāḥ asti vā?"],
        ["Why learn Sanskrit?", "किमर्थम् संस्कृतम्?", "kimartham saṃskṛtam?"],
        ["Reading comprehension", "पठनावगमनम्", "paṭhanāvagamanam"],
        ["Confidence is key", "विश्वासः मुख्यः", "viśvāsaḥ mukhyaḥ"],
        ["All the best", "शुभास्तु", "śubhāstu"],
    ],
    650: [
        ["What shall we eat?", "किम् भोक्ष्यामः?", "kim bhokṣyāmaḥ?"],
        ["I prefer rice", "व्रीहिः मे प्रियः", "vrīhiḥ me priyaḥ"],
        ["Less spice please", "लवणं अल्पम्", "lavaṇaṃ alpam"],
        ["Is this vegan?", "एतत् निरामिषम्?", "etat nirāmiṣam?"],
        ["Allergic to nuts", "फलेभ्यः अलर्जी", "phalebhyaḥ alarjī"],
        ["Order two plates", "द्वे प्लेटे आदिशतु", "dve pleṭe ādiśatu"],
        ["Water without ice", "जलं निःहिमम्", "jalaṃ niḥhimam"],
        ["Bill please", "प्रणालीं देहि", "praṇālīṃ dehi"],
        ["Split equally", "समं विभजतु", "samaṃ vibhajatu"],
        ["Tip included?", "भृतिः सम्मिलिता?", "bhṛtiḥ sammilitā?"],
        ["Packed for home", "गृहाय पुरीतम्", "gṛhāya purītam"],
        ["Too salty", "अतिलवणम्", "atilavaṇam"],
        ["Delicious dessert", "स्वादु पर्यन्तम्", "svādu paryantam"],
        ["I am full", "पूर्णः अस्मि", "pūrṇaḥ asmi"],
        ["Thanks, lovely meal", "धन्यवादः रमणीयं भोजनम्", "dhanyavādaḥ ramaṇīyaṃ bhojanam"],
    ],
    651: [
        ["Hobby class timings?", "अवकाशकक्षासमयाः?", "avakāśakakṣāsamayāḥ?"],
        ["Painting on Saturdays", "शनिवासरे चित्रणम्", "śanivāsare citraṇam"],
        ["Monthly fee", "मासिकशुल्कः", "māsikaśulkaḥ"],
        ["Materials included?", "सामग्री सम्मिलिता?", "sāmagrī sammilitā?"],
        ["Beginner batch", "प्रारम्भिकवर्गः", "prārambhikavargaḥ"],
        ["Certificate at end", "अन्ते प्रमाणपत्रम्", "ante prāmaṇapatram"],
        ["Trial class available?", "परीक्षाकक्षा उपलभ्यते?", "parīkṣākakṣā upalabhyate?"],
        ["I want to join", "प्रवेशं कर्तुम् इच्छामि", "praveśaṃ kartum icchāmi"],
        ["Bring your own brush", "स्वचित्रकूर्चम् आनयतु", "svacitrakūrcam ānayatu"],
        ["Class is full", "कक्षा पूर्णा", "kakṣā pūrṇā"],
        ["Waitlist option", "प्रतीक्षासूचिः", "pratīkṣāsūciḥ"],
        ["Online option too", "जालविकल्पोऽपि", "jālavikalpo'pi"],
        ["Teacher is inspiring", "आचार्यः प्रेरकः", "ācāryaḥ prerakaḥ"],
        ["See you next week", "अग्रिमे सप्ताहे", "agrime saptāhe"],
        ["Thank you", "धन्यवादः", "dhanyavādaḥ"],
    ],
    652: [
        ["Where is the washroom?", "शौचालयः कुत्र?", "śaucālayaḥ kutra?"],
        ["I need help", "मे साहाय्यम् आवश्यकम्", "me sāhāyyam āvaśyakam"],
        ["Call this number", "एतां सङ्ख्यां आह्वयतु", "etāṃ saṅkhyām āhvayatu"],
        ["Lost my bag", "मम पेटिका नष्टा", "mama peṭikā naṣṭā"],
        ["How much does it cost?", "कियत् मूल्यम्?", "kiyat mūlyam?"],
        ["Too expensive", "अतिमहत्", "atimahat"],
        ["Open the window", "कवाटम् उद्घाटयतु", "kavāṭam udghāṭayatu"],
        ["Close the door", "द्वारं पिदधातु", "dvāraṃ pidadhātu"],
        ["Slow down", "मन्दं कुरु", "mandaṃ kuru"],
        ["I do not understand", "न अवगच्छामि", "na avagacchāmi"],
        ["Speak again", "पुनः वदतु", "punaḥ vadata"],
        ["Wait here", "इह प्रतीक्षताम्", "iha pratīkṣatām"],
        ["Emergency", "आपद्", "āpad"],
        ["Thank you very much", "बहु धन्यवादः", "bahu dhanyavādaḥ"],
        ["Good night", "शुभ रात्रिः", "śubha rātriḥ"],
    ],
    653: [
        ["See you tomorrow", "श्वः पश्यामः", "śvaḥ paśyāmaḥ"],
        ["Traffic was bad", "यानजटिलता कठिना आसीत्", "yānajaṭilatā kaṭhinā āsīt"],
        ["Flight delayed", "विमानं विलम्बितम्", "vimānaṃ vilambitam"],
        ["Send me the link", "सम्बन्धं प्रेषयतु", "sambandhaṃ preṣayatu"],
        ["Password reset", "गुप्तपदं पुनः स्थापयतु", "guptapadaṃ punaḥ sthāpayatu"],
        ["Meeting moved online", "सभा जाले स्थापिता", "sabhā jāle sthāpitā"],
        ["Happy birthday", "जन्मदिनस्य शुभाः", "janmadinasya śubhāḥ"],
        ["Congratulations", "अभिनन्दनम्", "abhinandanam"],
        ["Get well soon", "शीघ्रं स्वस्थः भव", "śīghraṃ svasthaḥ bhava"],
        ["Safe journey", "सुरक्षिता यात्रा", "surakṣitā yātrā"],
        ["Call when free", "विमुक्तः सन् आह्वयतु", "vimuktaḥ san āhvayatu"],
        ["Text me", "लिखित्वा प्रेषयतु", "likhitvā preṣayatu"],
        ["No problem", "किञ्चित् दोषः न", "kiñcit doṣaḥ na"],
        ["Understood", "अवगतम्", "avagatam"],
        ["Talk soon", "शीघ्रं वदामः", "śīghraṃ vadāmaḥ"],
    ],
    654: [
        ["Greeting: how are you?", "नमस्ते कथमसि?", "namaste katham asi?"],
        ["I want water", "मे जलम् इच्छते", "me jalam icchate"],
        ["Where is the book?", "पुस्तकं कुत्र?", "pustakaṃ kutra?"],
        ["Read aloud", "उच्चैः पठतु", "uccaiḥ paṭhatu"],
        ["Repeat after me", "मम अनन्तरं पुनः वदतु", "mama anantaraṃ punaḥ vadatu"],
        ["What is this?", "इदं किम्?", "idaṃ kim?"],
        ["I like Sanskrit", "मे संस्कृतम् रोचते", "me saṃskṛtam rocate"],
        ["Let us practice", "अभ्यस्यामः", "abhyasyāmaḥ"],
        ["Slowly please", "शनैः कृपया", "śanaiḥ kṛpayā"],
        ["Very good", "अति उत्तमम्", "ati uttamam"],
        ["Try again", "पुनः यतताम्", "punaḥ yatatām"],
        ["Thank you, teacher", "धन्यवादः आचार्य", "dhanyavādaḥ ācārya"],
        ["See you", "पुनः मिलामहे", "punaḥ milāmahe"],
        ["Goodbye", "शुभं भवतु", "śubhaṃ bhavatu"],
        ["Om", "ॐ", "oṃ"],
    ],
    655: [
        ["The book is on the table", "पुस्तकं फलके अस्ति", "pustakaṃ phalake asti"],
        ["Cat under the chair", "विडालः आसनस्य अधः", "viḍālaḥ āsanasya adhaḥ"],
        ["Come from the market", "बाजारात् आगच्छ", "bājaārāt āgaccha"],
        ["Go to school", "विद्यालयं गच्छ", "vidyālayaṃ gaccha"],
        ["Sit beside me", "मम पार्श्वे उपविश", "mama pārśve upaviśa"],
        ["River near the village", "ग्रामस्य समीपे नदी", "grāmasya samīpe nadī"],
        ["Temple behind the tree", "वृक्षस्य पृष्ठे देवालयः", "vṛkṣasya pṛṣṭhe devālayaḥ"],
        ["Keys in the bag", "पेटिकायां चाबिकाः", "peṭikāyāṃ cābikāḥ"],
        ["Picture on the wall", "भित्तौ चित्रम्", "bhittau citram"],
        ["Walk through the gate", "द्वारेण गच्छ", "dvāreṇa gaccha"],
        ["Between two houses", "द्वयोः गृहयोः मध्ये", "dvayoḥ gṛhayoḥ madhye"],
        ["Until evening", "सायङ्कालं यावत्", "sāyaṅkālaṃ yāvat"],
        ["After lunch", "उपहारात् परम्", "upahārāt param"],
        ["Before sunrise", "सूर्योदयात् पूर्वम्", "sūryodayāt pūrvam"],
        ["Practice these sentences", "एतानि वाक्यानि अभ्यस्यतु", "etāni vākyāni abhyasyatu"],
    ],
    656: [
        ["In front of — अग्रे", "देवालयस्य अग्रे", "devālayasya agre"],
        ["Behind — पृष्ठे", "गृहस्य पृष्ठे", "gṛhasya pṛṣṭhe"],
        ["Above — उपरि", "फलके उपरि", "phalake upari"],
        ["Below — अधः", "मेघः अधः", "meghaḥ adhaḥ"],
        ["Inside — अन्तः", "गृहस्य अन्तः", "gṛhasya antaḥ"],
        ["Outside — बहिः", "द्वारस्य बहिः", "dvārasya bahiḥ"],
        ["Near — समीपे", "विद्यालयस्य समीपे", "vidyālayasya samīpe"],
        ["Far — दूरे", "नगरात् दूरे", "nagarāt dūre"],
        ["Between — मध्ये", "द्वयोः वृक्षयोः मध्ये", "dvayoḥ vṛkṣayoḥ madhye"],
        ["From — आरभ्य", "ग्रामात्", "grāmāt"],
        ["To — प्रति", "नगरं प्रति", "nagaraṃ prati"],
        ["With — सह", "मित्रेण सह", "mitreṇa saha"],
        ["Without — विना", "जलं विना", "jalaṃ vinā"],
        ["Until — यावत्", "सायङ्कालं यावत्", "sāyaṅkālaṃ yāvat"],
        ["After — पश्चात्", "भोजनात् पश्चात्", "bhojanāt paścāt"],
    ],
    657: [
        ["Teacher: Why late?", "आचार्यः कुतः विलम्बः?", "ācāryaḥ kutaḥ vilambaḥ?"],
        ["Student: Traffic jam", "छात्रः यानजटिलता", "chātraḥ yānajaṭilatā"],
        ["Teacher: Sit down", "उपविशतु", "upaviśatu"],
        ["Student: May I drink water?", "जलं पातुम् शक्नोमि वा?", "jalaṃ pātum śaknomi vā?"],
        ["Teacher: Yes", "आम्", "ām"],
        ["Student: I forgot homework", "गृहकार्यं विस्मृतवान्", "gṛhakāryaṃ vismṛtavān"],
        ["Teacher: Bring tomorrow", "श्वः आनयतु", "śvaḥ ānayatu"],
        ["Student: Sorry", "क्षम्यताम्", "kṣamyatām"],
        ["Teacher: Read the verse", "ऋचं पठतु", "ṛcaṃ paṭhatu"],
        ["Student: Beautiful poetry", "सुन्दरं काव्यम्", "sundaraṃ kāvyam"],
        ["Teacher: Well done", "साधु", "sādhu"],
        ["Class laughs", "कक्षा हसति", "kakṣā hasati"],
        ["Bell rings", "घण्टा वाद्यते", "ghaṇṭā vādyate"],
        ["Everyone leaves", "सर्वे गच्छन्ति", "sarve gacchanti"],
        ["Happy learning", "सुखं पठनम्", "sukhaṃ paṭhanam"],
    ],
    658: [
        ["Truth alone wins", "सत्यमेव जयते", "satyameva jayate"],
        ["Knowledge is power", "विद्या बलम्", "vidyā balam"],
        ["Practice makes perfect", "अभ्यासात् सिद्धिः", "abhyāsāt siddhiḥ"],
        ["Speak less, listen more", "अल्पं वदतु बहु श‍ृणुतु", "alpaṃ vadatu bahu śṛṇutu"],
        ["Time is precious", "कालः मूल्यवान्", "kālaḥ mūlyavān"],
        ["Health is wealth", "आरोग्यं धनम्", "ārogyaṃ dhanam"],
        ["Helping others helps you", "परसाहाय्यं स्वसाहाय्यम्", "parasāhāyyaṃ svasāhāyyam"],
        ["Start early", "प्रातः आरभत", "prātaḥ ārabhata"],
        ["Never give up", "कदापि मा त्यज", "kadāpi mā tyaja"],
        ["Respect teachers", "आचार्यान् गौरवयतु", "ācāryān gauravayatu"],
        ["Read good books", "शुभानि ग्रन्थानि पठतु", "śubhān granthān paṭhatu"],
        ["Smile often", "अनेकशः हसतु", "anekaśaḥ hasatu"],
        ["Dream big", "महान् स्वप्नं दृशतु", "mahān svapnaṃ dṛśatu"],
        ["Work hard", "कठोरं कार्यं कुरु", "kaṭhoraṃ kāryaṃ kuru"],
        ["Be kind", "दयालुः भव", "dayāluḥ bhava"],
    ],
    659: [
        ["I scroll too much", "अहं अतिबहु सर्पणं करोमि", "ahaṃ atibahu sarpaṇaṃ karomi"],
        ["Screen time hurts eyes", "पटलसमयः अक्ष्णोः हानिः", "paṭalasamayaḥ akṣṇoḥ hāniḥ"],
        ["Notifications distract", "सूचनाः विचलन्ति", "sūcanāḥ vicalanti"],
        ["I will limit usage", "उपयोगं सीमां करिष्यामि", "upayogaṃ sīmāṃ kariṣyāmi"],
        ["Real friends matter", "वास्तविकाः मित्राणि महत्त्वपूर्णाः", "vāstavikāḥ mitrāṇi mahattvapūrṇāḥ"],
        ["Cyber bullying is wrong", "जालदुर्व्यवहारः अयुक्तः", "jāladurvyavahāraḥ ayuktaḥ"],
        ["Privacy settings", "गोपनीयता व्यवस्थाः", "gopanīyatā vyavasthāḥ"],
        ["Take a digital break", "अङ्कीयविरामं गृहाण", "aṅkīyavirāmaṃ gṛhāṇa"],
        ["Family time first", "कुटुम्बसमयः प्रथमः", "kuṭumbasamayaḥ prathamaḥ"],
        ["Sleep before midnight", "मध्यरात्रेः पूर्वम् स्वपिहि", "madhyarātreḥ pūrvam svapihi"],
        ["Good content only", "शुभसामग्री एव", "śubhasāmagrī eva"],
        ["Report harmful posts", "हानिकरान् लेखान् निवेदयतु", "hānikarān lekhān nivedayatu"],
        ["Balance is key", "सन्तुलनं मुख्यम्", "santulanaṃ mukhyam"],
        ["I feel better offline", "जालात् बहिः सुखं भवति", "jālāt bahiḥ sukhaṃ bhavati"],
        ["Wise use of technology", "तन्त्रज्ञानस्य बुद्धिमान् उपयोगः", "tantrajñānasya buddhimān upayogaḥ"],
    ],
    660: [
        ["When is the eclipse?", "ग्रहणं कदा?", "grahaṇaṃ kadā?"],
        ["Partial or total?", "खण्डम् सम्पूर्णं वा?", "khaṇḍam sampūrṇaṃ vā?"],
        ["Do not look directly", "साक्षात् मा पश्यतु", "sākṣāt mā paśyatu"],
        ["Use certified glasses", "प्रमाणितानि काचानि उपयुञ्जतु", "pramāṇitāni kācāni upayuñjatu"],
        ["Myths about food", "अन्नविषये मिथ्याः", "annaviṣaye mithyāḥ"],
        ["Scientific explanation", "वैज्ञानिकं व्याख्यानम्", "vaijñānikaṃ vyākhyānam"],
        ["Children are curious", "बालकाः जिज्ञासवः", "bālakāḥ jijñāsavaḥ"],
        ["Live stream online", "जाले प्रत्यक्षप्रवाहः", "jāle pratyakṣapravāhaḥ"],
        ["Next eclipse after years", "वर्षैः पश्चात् अग्रिमं ग्रहणम्", "varṣaiḥ paścāt agrimaṃ grahaṇam"],
        ["Traditional prayers", "परम्परागता प्रार्थनाः", "paramparāgatāḥ prārthanāḥ"],
        ["Stay safe", "सुरक्षितः भव", "surakṣitaḥ bhava"],
        ["Share photos carefully", "छायाचित्राणि सावधानं वितरतु", "chāyāchitrāṇi sāvadhaānaṃ vitaratu"],
        ["Beautiful phenomenon", "सुन्दरं घटनम्", "sundaraṃ ghaṭanam"],
        ["I watched with family", "कुटुम्बेन सह दृष्टवान्", "kuṭumbena saha dṛṣṭavān"],
        ["Amazing universe", "आश्चर्यजगत्", "āścaryajagat"],
    ],
    661: [
        ["Happy Women’s Day", "महिलादिनस्य शुभाः", "mahilādivasya śubhāḥ"],
        ["Equality for all", "सर्वेषां समानता", "sarveṣāṃ samānatā"],
        ["Education for girls", "बालिकानां शिक्षा", "bālikānāṃ śikṣā"],
        ["Respect at workplace", "कार्यस्थले गौरवम्", "kāryasthale gauravam"],
        ["Break the bias", "पक्षपातं भिन्दतु", "pakṣapātaṃ bhindatu"],
        ["Celebrate achievements", "उपलब्धीः मनयतु", "upalabdhīḥ manayatu"],
        ["Support mothers", "मातॄन् आधारयतु", "mātṝn ādhārayatu"],
        ["Health and safety", "आरोग्यं सुरक्षा च", "ārogyaṃ surakṣā ca"],
        ["Mentorship matters", "मार्गदर्शनं महत्त्वपूर्णम्", "mārgadarśanaṃ mahattvapūrṇam"],
        ["Women in science", "विज्ञाने महिलाः", "vijñāne mahilāḥ"],
        ["Fair pay", "न्याय्यं वेतनम्", "nyāyyaṃ vetanam"],
        ["Speak up", "उच्चैः वदतु", "uccaiḥ vadatu"],
        ["Together we rise", "सह वयं उन्नमामः", "saha vayaṃ unnamāmaḥ"],
        ["Thank the women in your life", "जीवने महिलाः धन्यवादं कुरु", "jīvane mahilāḥ dhanyavādaṃ kuru"],
        ["Hope for a better world", "श्रेष्ठस्य जगतः आशा", "śreṣṭhasya jagataḥ āśā"],
    ],
    662: [
        ["Why did you shout?", "कुतः उच्चैः अवदः?", "kutaḥ uccaiḥ avadaḥ?"],
        ["I am tired of this mess", "अस्य व्यग्रतायाः क्लान्तः अस्मि", "asya vyagratāyāḥ klāntaḥ asmi"],
        ["Please lower your voice", "स्वरं न्यूनं कुरु", "svaraṃ nyūnaṃ kuru"],
        ["I did not mean to hurt", "पीडां न अभिप्रेतवान्", "pīḍāṃ na abhipretavān"],
        ["Let us calm down", "शाम्यामः", "śāmyāmaḥ"],
        ["We can talk tomorrow", "श्वः वदामः", "śvaḥ vadāmaḥ"],
        ["Sorry for my words", "मम वचनानां क्षमा", "mama vacānāṃ kṣamā"],
        ["Family should support", "कुटुम्बं साहाय्यं करोतु", "kuṭumbaṃ sāhāyyaṃ karotu"],
        ["I need space", "मे विवेकः आवश्यकः", "me vivekaḥ āvaśyakaḥ"],
        ["Listen first", "प्रथमं श‍ृणु", "prathamaṃ śṛṇu"],
        ["We will solve this", "एतत् समाधास्यामः", "etat samādhāsyāmaḥ"],
        ["No more arguing", "न अधिकं वादम्", "na adhikaṃ vādam"],
        ["Hug and forgive", "आलिङ्ग्य क्षमस्व", "āliṅgya kṣamasva"],
        ["Peace at home", "गृहे शान्तिः", "gṛhe śāntiḥ"],
        ["Love stays", "स्नेहः तिष्ठति", "snehaḥ tiṣṭhati"],
    ],
}
