# Sanskrit Lesson 3 — chunk A (chapter IDs 543–565).

LESSONS_S3A = {
    543: [
        ["I am about to eat", "अहं भोक्तुं प्रवृत्तः अस्मि", "ahaṃ bhoktuṃ pravṛttaḥ asmi"],
        ["She will read", "सा पठिष्यति", "sā paṭhiṣyati"],
        ["We shall go tomorrow", "श्वः वयं गमिष्यामः", "śvaḥ vayaṃ gamiṣyāmaḥ"],
        ["He will call you", "सः त्वाम् आह्वयिष्यति", "saḥ tvām āhvayiṣyati"],
        ["They will depart", "ते प्रस्थास्यन्ति", "te prasthāsyanti"],
        ["Today it may rain", "अद्य वर्षिष्यति", "adya varṣiṣyati"],
        ["I shall try", "अहं प्रयतिष्ये", "ahaṃ prayatiṣye"],
        ["Will you come?", "आगमिष्यसि?", "āgamiṣyasi?"],
        ["What will you do?", "किं करिष्यसि?", "kiṃ kariṣyasi?"],
        ["I will sleep early", "प्रभाते अहं स्वप्स्यामि", "prabhāte ahaṃ svapsyāmi"],
        ["The chariot will move", "रथः चलिष्यति", "rathaḥ caliṣyati"],
        ["I shall buy vegetables", "अहं शाकानि क्रीणीय", "ahaṃ śākānī krīṇīya"],
        ["She will cook rice", "सा ओदनं पचिष्यति", "sā odanaṃ paciṣyati"],
        ["We shall meet at the temple", "देवालये वयं मिलिष्यामः", "devālaye vayaṃ miliṣyāmaḥ"],
        ["He will not speak falsely", "सः अनृतं न वक्ष्यति", "saḥ anṛtaṃ na vakṣyati"],
        ["I will learn Sanskrit", "अहं संस्कृतम् अधीयिष्ये", "ahaṃ saṃskṛtam adhīṣye"],
    ],
    544: [
        ["Formerly I played here", "पूर्वम् अहं इह क्रीडामि", "pūrvam ahaṃ iha krīḍāmi"],
        ["He used to walk at dawn", "प्रातः सः अटति स्म", "prātaḥ saḥ aṭati sma"],
        ["We lived in the village", "ग्रामे वयं वसाम स्म", "grāme vayaṃ vasāma sma"],
        ["She sang sweetly", "सा मधुरं गायति स्म", "sā madhuraṃ gāyati sma"],
        ["They often visited us", "ते अस्मान् अकस्मात् आगच्छन्", "te asmān akasmāt āgacchan"],
        ["I feared darkness", "अहं तमसः भीतः आसम्", "ahaṃ tamasaḥ bhītaḥ āsam"],
        ["Mother rose early", "अम्बा प्रभाते उत्थितवती", "ambā prabhāte utthitavatī"],
        ["He worked in the field", "सः क्षेत्रे कार्यं अकरोत्", "saḥ kṣetre kāryam akarot"],
        ["We ate together", "सह वयं अश्नीमहि", "saha vayaṃ aśnīmahi"],
        ["It was cold here", "इह शीतलम् आसीत्", "iha śītalam āsīt"],
        ["I read the news", "अहं वार्तां पठति स्म", "ahaṃ vārtāṃ paṭhati sma"],
        ["You helped everyone", "त्वं सर्वान् साहाय्यम् अकरः", "tvaṃ sarvān sāhāyyam akaraḥ"],
        ["The shop opened late", "आपणः दीर्घायुषः उद्घाटितः", "āpaṇaḥ dīrghāyuṣaḥ udghāṭitaḥ"],
        ["Children played outside", "बालकाः बहिः क्रीडन्", "bālakāḥ bahiḥ krīḍan"],
        ["I went by cart", "अहं शकटेन अगच्छम्", "ahaṃ śakaṭena agaccham"],
    ],
    545: [
        ["Long ago I studied here", "पुरा अहं इह अध्यैषम्", "purā ahaṃ iha adhyaiṣam"],
        ["In old days he travelled on foot", "पूर्वकाले सः पादाभ्यां याति स्म", "pūrvakāle saḥ pādābhyāṃ yāti sma"],
        ["People honoured elders", "जनाः वृद्धान् पूजयन्ति स्म", "janāḥ vṛddhān pūjayanti sma"],
        ["We sat under this tree", "वयम् एतस्य वृक्षस्य अधः आसाम", "vayam etasya vṛkṣasya adhaḥ āsāma"],
        ["The fair came yearly", "वार्षिकी मेला आगच्छत्", "vārṣikī melā āgacchat"],
        ["I feared examinations", "अहं परीक्षां भीतः आसम्", "ahaṃ parīkṣāṃ bhītaḥ āsam"],
        ["She wore white garments", "सा शुक्लानि वस्त्राणि धरति स्म", "sā śuklāni vastrāṇi dharati sma"],
        ["They ploughed this land", "ते एतत् क्षेत्रं जोतयन्ति स्म", "te etat kṣetraṃ jotayanti sma"],
        ["Winter was harsher", "शिशिरऋतुः तीव्रः आसीत्", "śiśirartuḥ tīvraḥ āsīt"],
        ["I knew him from childhood", "अहं बाल्यात् तम् जानामि स्म", "ahaṃ bālyāt tam jānāmi sma"],
        ["We drew water from the well", "कूपात् वयं जलं आहराम स्म", "kūpāt vayaṃ jalaṃ āharāma sma"],
        ["The teacher was strict", "आचार्यः कठोरः आसीत्", "ācāryaḥ kaṭhoraḥ āsīt"],
        ["I listened to the Veda", "अहं वेदं श‍ृणोमि स्म", "ahaṃ vedaṃ śṛṇomi sma"],
        ["Villages were peaceful", "ग्रामाः शान्ताः आसन्", "grāmāḥ śāntāḥ āsan"],
        ["He returned before sunset", "सः अस्तमनात् पूर्वं प्रत्यागच्छत्", "saḥ astamanāt pūrvaṃ pratyāgacchat"],
    ],
    546: [
        ["If it rains, I stay", "यदि वर्षति तर्हि अहं तिष्ठामि", "yadi varṣati tarhi ahaṃ tiṣṭhāmi"],
        ["If you come, we go together", "यदि त्वम् आगच्छसि तर्हि सह गच्छामः", "yadi tvam āgacchasi tarhi saha gacchāmaḥ"],
        ["If he studies, he passes", "यदि सः अधीयते तर्हि सः उत्तीर्णः भवति", "yadi saḥ adhīyate tarhi saḥ uttīrṇaḥ bhavati"],
        ["If tired, rest", "यदि क्लान्तः तर्हि विश्रामं कुरु", "yadi klāntaḥ tarhi viśrāmaṃ kuru"],
        ["If she calls, tell her I am busy", "यदि सा आह्वयति तर्हि तस्यै वद — व्यस्तः अस्मि", "yadi sā āhvayati tarhi tasyai vada — vyastaḥ asmi"],
        ["If we leave now, we are on time", "यदि अधुना गच्छामः तर्हि समये भवामः", "yadi adhunā gacchāmaḥ tarhi samaye bhavāmaḥ"],
        ["If the cart is late, take another", "यदि शकटः दीर्घायुषः तर्हि अन्यत् गृहाण", "yadi śakaṭaḥ dīrghāyuṣḥ tarhi anyat gṛhāṇa"],
        ["If help is needed, ask me", "यदि साहाय्यम् आवश्यकम् तर्हि माम् पृच्छ", "yadi sāhāyyam āvaśyakam tarhi mām pṛccha"],
        ["If I had money, I would buy a house", "यदि मे धनम् अभविष्यत् तर्हि गृहं क्रीणीयम्", "yadi me dhanam abhaviṣyat tarhi gṛhaṃ krīṇīyam"],
        ["If they agree, begin work", "यदि ते सम्मन्यन्ते तर्हि कार्यं आरभत", "yadi te sammanyante tarhi kāryam ārabhata"],
        ["If you eat too much, you fall ill", "यदि अतिभोजनं करोषि तर्हि रोगी भवसि", "yadi atibhojanaṃ karoṣi tarhi rogī bhavasi"],
        ["If the road is bad, go slowly", "यदि मार्गः दुष्टः तर्हि शनैः गच्छ", "yadi mārgaḥ duṣṭaḥ tarhi śanaiḥ gaccha"],
        ["If winter comes, wear warm clothes", "यदि शिशिरः आगच्छति तर्हि उष्णानि वस्त्राणि धारय", "yadi śiśiraḥ āgacchati tarhi uṣṇāni vastrāṇi dhāraya"],
        ["If you lie, none trusts", "यदि अनृतं वदसि तर्हि कोऽपि न विश्वसति", "yadi anṛtaṃ vadasi tarhi ko'pi na viśvasati"],
        ["If I see him, I inform you", "यदि तम् पश्यामि तर्हि तुभ्यं निवेदयामि", "yadi tam paśyāmi tarhi tubhyaṃ nivedayāmi"],
    ],
    547: [
        ["I wait for you", "अहं त्वदर्थं प्रतीक्षे", "ahaṃ tvad-arthaṃ pratīkṣe"],
        ["She depends on parents", "सा मातापित्रोः आश्रयति", "sā mātāpitroḥ āśrayati"],
        ["Listen to the teacher", "आचार्यस्य वचनं श‍ृणु", "ācāryasya vacanaṃ śṛṇu"],
        ["He laughed at the joke", "सः परिहासं हसत्", "saḥ parihāsaṃ hasat"],
        ["We trust in effort", "वयं उद्यमे विश्वसिमः", "vayaṃ udyame viśvasimaḥ"],
        ["Think of the future", "भविष्यत् चिन्तय", "bhaviṣyat cintaya"],
        ["She is angry with her brother", "सा स्वस्रोः क्रोधिनी", "sā svasroḥ krodhinī"],
        ["I agree with you", "अहं त्वया सह सम्मतः", "ahaṃ tvayā saha sammataḥ"],
        ["They ran toward the gate", "ते द्वारं प्रति धावन्ति", "te dvāraṃ prati dhāvanti"],
        ["Sit on this seat", "अस्मिन् आसने उपविश", "asmin āsane upaviśa"],
        ["The cat hid under the bed", "विडालः शय्यायाः अधः लुप्तः", "viḍālaḥ śayyāyāḥ adhaḥ luptaḥ"],
        ["Put the book on the table", "फलके पुस्तकं निधेहि", "phalake pustakaṃ nidhehi"],
        ["He jumped into water", "सः जले अप्लवत्", "saḥ jale aplavat"],
        ["We walked along the river", "नद्या तटेन वयं अटामहि", "nadyā taṭena vayaṃ aṭāmahi"],
        ["She looked at the sky", "सा आकाशं ऐक्षत", "sā ākāśam aikṣata"],
    ],
    548: [
        ["This is a big house", "इदं महत् गृहम् अस्ति", "idaṃ mahat gṛham asti"],
        ["That is a small room", "तत् अल्पं कक्षम् अस्ति", "tat alpaṃ kakṣam asti"],
        ["She is a good teacher", "सा शिष्टा शिक्षिका अस्ति", "sā śiṣṭā śikṣikā asti"],
        ["The water is cold", "जलं शीतलम् अस्ति", "jalaṃ śītalam asti"],
        ["The milk is sweet", "क्षीरं मधुरम् अस्ति", "kṣīraṃ madhuram asti"],
        ["He is taller than his brother", "सः स्वस्रः अपेक्षया दीर्घः अस्ति", "saḥ svasraḥ apekṣayā dīrghaḥ asti"],
        ["This road is dangerous", "अयं मार्गः सङ्कटपूर्णः अस्ति", "ayaṃ mārgaḥ saṅkaṭapūrṇaḥ asti"],
        ["The sky is clear today", "अद्य आकाशः निर्मलः अस्ति", "adya ākāśaḥ nirmalaḥ asti"],
        ["Her voice is soft", "तस्याः स्वरः मृदुः अस्ति", "tasyāḥ svaraḥ mṛduḥ asti"],
        ["The fruit is ripe", "फलं पक्वम् अस्ति", "phalaṃ pakvam asti"],
        ["We are ready to go", "गन्तुं वयं सिद्धाः अस्मः", "gantuṃ vayaṃ siddhāḥ asmaḥ"],
        ["The child is afraid", "बालकः भीतः अस्ति", "bālakaḥ bhītaḥ asti"],
        ["This book is interesting", "इदं पुस्तकम् आकर्षकम् अस्ति", "idaṃ pustakam ākarṣakam asti"],
        ["The food is hot", "भोजनं उष्णम् अस्ति", "bhojanaṃ uṣṇam asti"],
        ["He looks tired", "सः क्लान्तः दृश्यते", "saḥ klāntaḥ dṛśyate"],
    ],
    549: [
        ["I can swim", "अहं तरणं शक्नोमि", "ahaṃ taraṇaṃ śaknomi"],
        ["Can you help?", "त्वं साहाय्यं कर्तुं शक्नोषि?", "tvaṃ sāhāyyaṃ kartuṃ śaknoṣi?"],
        ["He cannot come today", "सः अद्य आगन्तुं न शक्नोति", "saḥ adya āgantuṃ na śaknoti"],
        ["She can sing well", "सा सुष्ठु गातुं शक्नोति", "sā suṣṭhu gātuṃ śaknoti"],
        ["We can finish this", "इदं वयं समाप्तुं शक्नुमः", "idaṃ vayaṃ samāptuṃ śaknumaḥ"],
        ["May I sit?", "उपविष्टुं शक्नोमि वा?", "upaviṣṭuṃ śaknomi vā?"],
        ["They understand Sanskrit", "ते संस्कृतं अवगच्छन्ति", "te saṃskṛtam avagacchanti"],
        ["I could not sleep", "अहं न स्वप्नं शक्नोम्", "ahaṃ na svapnaṃ śaknom"],
        ["You will be able to drive", "त्वं रथं चालयितुं शक्ष्यसि", "tvaṃ rathaṃ chālayituṃ śakṣyasi"],
        ["Nobody could open it", "केनापि उद्घाटयितुं न शक्यते", "kenāpi udghāṭayituṃ na śakyate"],
        ["Can she cook?", "सा पक्तुं शक्नोति वा?", "sā paktuṃ śaknoti vā?"],
        ["I can try again", "अहं पुनः प्रयतितुं शक्नोमि", "ahaṃ punaḥ prayatituṃ śaknomi"],
        ["He can lift this", "इदं सः उत्थापयितुं शक्नोति", "idaṃ saḥ utthāpayituṃ śaknoti"],
        ["We could not find the way", "मार्गं वयं न अलभामहि", "mārgaṃ vayaṃ na alabhāmahi"],
        ["Can you repeat?", "पुनः वदितुं शक्नोषि?", "punaḥ vadituṃ śaknoṣi?"],
    ],
    550: [
        ["I want water", "मे जलस्य इच्छा अस्ति", "me jalasya icchā asti"],
        ["I need rest today", "अद्य विश्रामस्य आवश्यकता मे अस्ति", "adya viśrāmasya āvaśyakatā me asti"],
        ["She wishes to study abroad", "सा विदेशे अध्येतुम् इच्छति", "sā videśe adhyetum icchati"],
        ["We need your permission", "भवतः अनुज्ञायाः आवश्यकता अस्माकम्", "bhavataḥ anujñāyāḥ āvaśyakatā asmākam"],
        ["He does not wish to fight", "सः योद्धुम् न इच्छति", "saḥ yoddhum na icchati"],
        ["Do you want tea?", "भवतः चायाः इच्छा अस्ति वा?", "bhavataḥ chāyāḥ icchā asti vā?"],
        ["I need a little time", "मे अल्पस्य कालस्य आवश्यकता अस्ति", "me alpasya kālasya āvaśyakatā asti"],
        ["They want to meet tomorrow", "श्वः मिलितुं ते इच्छन्ति", "śvaḥ milituṃ te icchanti"],
        ["The plant needs water", "वृक्षाय जलस्य आवश्यकता अस्ति", "vṛkṣāya jalasya āvaśyakatā asti"],
        ["I want to learn music", "अहं सङ्गीतम् अधीतुम् इच्छामि", "ahaṃ saṅgītam adhītum icchāmi"],
        ["She needs medicine", "तस्याः औषधस्य आवश्यकता अस्ति", "tasyāḥ auṣadhasya āvaśyakatā asti"],
        ["We do not want quarrel", "वयं कलहं न इच्छामः", "vayaṃ kalahaṃ na icchāmaḥ"],
        ["He wants a new cloth", "सः नवं वस्त्रम् इच्छति", "saḥ navaṃ vastram icchati"],
        ["I need your advice", "मे भवतः उपदेशस्य आवश्यकता अस्ति", "me bhavataḥ upadeśasya āvaśyakatā asti"],
        ["The child wants to play", "बालकः क्रीडितुम् इच्छति", "bālakaḥ krīḍitum icchati"],
    ],
    551: [
        ["It will become cold", "शीतलं भविष्यति", "śītalaṃ bhaviṣyati"],
        ["He became a physician", "सः चिकित्सकः अभवत्", "saḥ cikitsakaḥ abhavat"],
        ["What happened?", "किम् अभवत्?", "kim abhavat?"],
        ["The milk turned sour", "क्षीरं अम्लीभूतम्", "kṣīraṃ amlībhūtam"],
        ["She became famous", "सा प्रसिद्धा अभवत्", "sā prasiddhā abhavat"],
        ["Do not become lazy", "आलस्यं मा कृध्वम्", "ālasyaṃ mā kṛdhvam"],
        ["The sky became cloudy", "आकाशः मेघाच्छन्नः अभवत्", "ākāśaḥ meghācchannaḥ abhavat"],
        ["We became friends", "वयं मित्राणि अभवाम", "vayaṃ mitrāṇi abhavāma"],
        ["It happens daily", "प्रतिदिनं भवति", "pratidinaṃ bhavati"],
        ["The child became silent", "बालकः मौनः अभवत्", "bālakaḥ maunaḥ abhavat"],
        ["Things will improve", "वस्तूनि श्रेयांसि भविष्यन्ति", "vastūni śreyāṃsi bhaviṣyanti"],
        ["He became angry suddenly", "सः अकस्मात् क्रुद्धः अभवत्", "saḥ akasmāt kruddhaḥ abhavat"],
        ["Winter comes; leaves fall", "शिशिरः आगच्छति पर्णानि पतन्ति", "śiśiraḥ āgacchati parṇāni patanti"],
        ["She wants to become a teacher", "सा शिक्षिका भवितुम् इच्छति", "sā śikṣikā bhavitum icchati"],
        ["Nothing happened without cause", "कारणम् विना किञ्चित् न अभवत्", "kāraṇam vinā kiñcit na abhavat"],
    ],
    552: [
        ["You should rest", "भवान् विश्रामं करोतु", "bhavān viśrāmaṃ karotu"],
        ["We should help the poor", "दरिद्रान् साहाय्यं कर्तव्यम्", "daridrān sāhāyyaṃ kartavyam"],
        ["He should speak truth", "सः सत्यम् वदेत्", "saḥ satyam vadet"],
        ["Children should respect elders", "बालकाः वृद्धान् पूजयेयुः", "bālakāḥ vṛddhān pūjayeyuḥ"],
        ["You should not waste food", "भवान् अन्नं न उत्सृजेत्", "bhavān annaṃ na utsṛjet"],
        ["I should leave early", "प्रभाते अहं गन्तव्यः", "prabhāte ahaṃ gantavyaḥ"],
        ["She should see a physician", "सा चिकित्सकं द्रष्टव्या", "sā cikitsakaṃ draṣṭavyā"],
        ["We should save water", "जलं रक्षितव्यम्", "jalaṃ rakṣitavyam"],
        ["They should apologize", "ते क्षमां याचेयुः", "te kṣamāṃ yāceyuḥ"],
        ["You should wear a helmet", "शिरस्त्राणं धारयतु", "śirastrāṇaṃ dhārayatu"],
        ["One should speak gently", "मृदु वदितव्यम्", "mṛdu veditavyam"],
        ["We should not spread rumours", "असत्यवार्ताः न प्रसारयेम", "asatyavārtāḥ na prasārayema"],
        ["He should finish homework", "सः गृहकार्यं समाप्नुयात्", "saḥ gṛhakāryaṃ samāpnuyāt"],
        ["Call before coming", "आगमनात् पूर्वं आह्वयतु", "āgamanāt pūrvaṃ āhvayatu"],
        ["I should have told you", "त्वाम् अहं वदितवान् आसम्", "tvām ahaṃ veditavān āsam"],
    ],
    553: [
        ["I must go now", "अधुना मे गन्तव्यम्", "adhunā me gantavyam"],
        ["You must bring identity proof", "परिचयपत्रं आनयितव्यम्", "paricayapatraṃ ānayitavyam"],
        ["We must follow rules", "नियमान् अनुसर्तव्यम्", "niyamān anusartavyam"],
        ["She must take medicine", "तस्याः औषधं ग्रहीतव्यम्", "tasyāḥ auṣadhaṃ grahītavyam"],
        ["They must report", "तेभ्यः निवेदनं कर्तव्यम्", "tebhyaḥ nivedanaṃ kartavyam"],
        ["The form must be filled", "पत्रिका पूरणीया", "patrikā pūrṇīyā"],
        ["I must not be late", "दीर्घायुषः न भवितव्यम् मे", "dīrghāyuṣḥ na bhavitavyam me"],
        ["You must tell truth in court", "सभायां सत्यम् वक्तव्यम्", "sabhāyāṃ satyam vaktavyam"],
        ["We must save electricity", "विद्युत् रक्षणीया", "vidyut rakṣaṇīyā"],
        ["He must pay the fine", "सः दण्डं दातव्यः", "saḥ daṇḍaṃ dātavyaḥ"],
        ["Students must attend class", "छात्रैः कक्षा गन्तव्या", "chātraiḥ kakṣā gantavyā"],
        ["I must call mother", "मातरम् आह्वयितव्यम् मे", "mātaram āhvayitavyam me"],
        ["Do not skip breakfast", "प्रातर्भोजनं मा त्यज", "prātarbhojanaṃ mā tyaja"],
        ["We must leave before dark", "तमसः पूर्वं गन्तव्यम्", "tamasaḥ pūrvaṃ gantavyam"],
        ["The door must be locked", "द्वारं बद्धं कर्तव्यम्", "dvāraṃ baddhaṃ kartavyam"],
    ],
    554: [
        ["He keeps speaking", "सः वदन् एव तिष्ठति", "saḥ vadan eva tiṣṭhati"],
        ["She keeps forgetting", "सा विस्मरति स्म", "sā vismarati sma"],
        ["The baby keeps crying", "शिशुः रोदिति एव", "śiśuḥ roditi eva"],
        ["They keep asking", "ते पृच्छन्ति एव", "te pṛcchanti eva"],
        ["I keep thinking of you", "अहं त्वां चिन्तयामि नित्यम्", "ahaṃ tvāṃ cintayāmi nityam"],
        ["The bell keeps ringing", "घण्टा नादं करोति निरन्तरम्", "ghaṇṭā nādaṃ karoti nirantaram"],
        ["It keeps raining", "वर्षति निरन्तरम्", "varṣati nirantaram"],
        ["We keep trying", "वयं प्रयत्नं कुर्मः नित्यम्", "vayaṃ prayatnaṃ kurmaḥ nityam"],
        ["Do not keep arguing", "विवादं मा कुर्वन्तम्", "vivādaṃ mā kurvantam"],
        ["He keeps changing his mind", "सः मतिं परिवर्तयति", "saḥ matiṃ parivartayati"],
        ["She keeps the house clean", "सा गृहं शुचि रक्षति", "sā gṛhaṃ śuci rakṣati"],
        ["The fan makes noise", "व्यजनः शब्दं करोति", "vyjanaḥ śabdaṃ karoti"],
        ["I keep telling you", "अहं त्वाम् वदामि पुनः पुनः", "ahaṃ tvām vadāmi punaḥ punaḥ"],
        ["They keep postponing", "ते कालं स्थगयन्ति", "te kālaṃ sthagayanti"],
        ["Water keeps dripping", "जलं स्रवति", "jalaṃ sravati"],
    ],
    555: [
        ["This tree is taller", "अयं वृक्षः दीर्घतरः अस्ति", "ayaṃ vṛkṣaḥ dīrghataraḥ asti"],
        ["She is the best singer", "सा श्रेष्ठा गायिका अस्ति", "sā śreṣṭhā gāyikā asti"],
        ["This path is shorter", "अयं मार्गः ह्रस्वतरः अस्ति", "ayaṃ mārgaḥ hrasvataraḥ asti"],
        ["He runs faster than I", "सः मत्तः शीघ्रतरं धावति", "saḥ mattaḥ śīghrataraṃ dhāvati"],
        ["This book is more useful", "इदं पुस्तकम् उपयुक्ततरम्", "idaṃ pustakam upayuktataram"],
        ["Winter is colder this year", "अस्मिन् वर्षे शिशिरः शीतलतरः", "asmin varṣe śiśiraḥ śītalataraḥ"],
        ["She speaks more gently", "सा मृदुतरं वदति", "sā mṛdutaraṃ vadati"],
        ["This is the biggest market", "अयं सर्वाधिकः पण्यः अस्ति", "ayaṃ sarvādhikaḥ paṇyaḥ asti"],
        ["My house is nearer", "मम गृहं निकटतरम्", "mama gṛhaṃ nikaṭataram"],
        ["He is as wise as his father", "सः पित्रा समानः विद्वान् अस्ति", "saḥ pitrā samānaḥ vidvān asti"],
        ["This sweet is sweeter", "इदं मिष्टम् अधिकमधुरम्", "idaṃ miṣṭam adhikamadhuram"],
        ["The second question is harder", "द्वितीयः प्रश्नः कठिनतरः", "dvitīyaḥ praśnaḥ kaṭhinataraḥ"],
        ["She is younger than her sister", "सा स्वस्रः अपेक्षया कनिष्ठा", "sā svasraḥ apekṣayā kaniṣṭhā"],
        ["This cloth is softer", "इदं वस्त्रम् मृदुतरम्", "idaṃ vastram mṛdutaram"],
        ["He earns less than before", "सः पूर्वात् न्यूनम् अर्जति", "saḥ pūrvāt nyūnam arjati"],
    ],
    556: [
        ["I know this boy", "अहं एतं बालकं जानामि", "ahaṃ etaṃ bālakaṃ jānāmi"],
        ["Do you know her name?", "तस्याः नाम जानासि वा?", "tasyāḥ nāma jānāsi vā?"],
        ["He knows how to drive", "सः रथं चालयितुं जानाति", "saḥ rathaṃ chālayituṃ jānāti"],
        ["I do not know the answer", "उत्तरम् अहं न जानामि", "uttaram ahaṃ na jānāmi"],
        ["We know the truth", "वयं सत्यं जानीमः", "vayaṃ satyaṃ jānīmaḥ"],
        ["She knows three languages", "सा त्रयः भाषाः जानाति", "sā trayaḥ bhāṣāḥ jānāti"],
        ["Nobody knows what will happen", "किम् भविष्यति इति कोऽपि न जानाति", "kim bhaviṣyati iti ko'pi na jānāti"],
        ["I knew him from school", "विद्यालयात् तम् अहं जानामि स्म", "vidyālāt tam ahaṃ jānāmi sma"],
        ["You should know your duty", "भवतः कर्तव्यम् ज्ञातव्यम्", "bhavataḥ kartavyam jñātavyam"],
        ["Let me know when you arrive", "यदा आगच्छसि तदा माम् वद", "yadā āgacchasi tadā mām vada"],
        ["I want to know the reason", "कारणम् ज्ञातुम् इच्छामि", "kāraṇam jñātum icchāmi"],
        ["Does he know cooking?", "सः पाकं जानाति वा?", "saḥ pākaṃ jānāti vā?"],
        ["We knew they would come", "ते आगमिष्यन्ति इति वयं जानीम स्म", "te āgamiṣyanti iti vayaṃ jānīma sma"],
        ["I know it by heart", "इदं हृदि स्थितम् अस्ति मे", "idaṃ hṛdi sthitam asti me"],
        ["She knows the way", "सा मार्गं जानाति", "sā mārgaṃ jānāti"],
    ],
    557: [
        ["Let him speak", "सः वदतु", "saḥ vadatu"],
        ["Let us go now", "अधुना गच्छामः", "adhunā gacchāmaḥ"],
        ["Let her rest", "सा विश्रामं करोतु", "sā viśrāmaṃ karotu"],
        ["Let us eat together", "सह भुञ्जीमहि", "saha bhuñjīmahi"],
        ["Let the children play", "बालकाः क्रीडन्तु", "bālakāḥ krīḍantu"],
        ["Shall we begin?", "आरभामहे वा?", "ārabhāmahe vā?"],
        ["Shall I open the door?", "द्वारं उद्घाटयामि वा?", "dvāraṃ udghāṭayāmi vā?"],
        ["Let us wait five minutes", "पञ्चनिमेषान् प्रतीक्षामहे", "pañcanimeṣān pratīkṣāmahe"],
        ["Do not let him go alone", "तम् एकाकिनं मा गमय", "tam ekākinaṃ mā gamaya"],
        ["Let the water boil", "जलं तप्तं भवतु", "jalaṃ taptaṃ bhavatu"],
        ["Shall we meet tomorrow?", "श्वः मिलामहे वा?", "śvaḥ milāmahe vā?"],
        ["Let me try once", "एकवारम् अहं प्रयतिषे", "ekavāram ahaṃ prayatiṣe"],
        ["Let us take a photo", "चित्रं गृह्णीमहि", "citraṃ gṛhṇīmahi"],
        ["Let them decide", "ते निश्चिन्वन्तु", "te niścinvantu"],
        ["Leave it; do not worry", "तत् त्यज चिन्तां च", "tat tyaja cintāṃ ca"],
    ],
    558: [
        ["The book that I bought is good", "यत् पुस्तकं क्रीणामि तत् शिष्टम् अस्ति", "yat pustakaṃ krīṇāmi tat śiṣṭam asti"],
        ["The man who came is my uncle", "यः आगच्छत् सः मम पितुः भ्राता", "yaḥ āgacchat saḥ mama pituḥ bhrātā"],
        ["What you said is true", "यत् अवदः तत् सत्यम् अस्ति", "yat avadaḥ tat satyam asti"],
        ["I know where he lives", "कुत्र सः वसति इति अहं जानामि", "kutra saḥ vasati iti ahaṃ jānāmi"],
        ["Tell me which bus goes", "कः रथः गच्छति इति वद", "kaḥ rathaḥ gacchati iti vada"],
        ["That is the house I want", "तत् एव गृहम् यत् इच्छामि", "tat eva gṛham yat icchāmi"],
        ["The girl whose bag this is stood", "यस्याः पेटिका इयम् सा उत्थिता", "yasyāḥ peṭikā iyam sā utthitā"],
        ["I forgot what he asked", "यत् सः अपृच्छत् तत् विस्मृतवान्", "yat saḥ apṛcchat tat vismṛtavān"],
        ["Show what you wrote", "यत् लिखः तत् दर्शय", "yat likhaḥ tat darśaya"],
        ["This is the road to the temple", "एषः मार्गः यः देवालयं गच्छति", "eṣaḥ mārgaḥ yaḥ devālayaṃ gacchati"],
        ["I like the song she sang", "या गीतं गायति सा मे रोचते", "yā gītaṃ gāyati sā me rocate"],
        ["Whoever comes, welcome", "यः आगच्छति तम् स्वागतं कुरु", "yaḥ āgacchati tam svāgataṃ kuru"],
        ["Whatever happens, stay calm", "यत् भवति तत् अवेक्षस्व शान्तः", "yat bhavati tat avekṣasva śāntaḥ"],
        ["The reason why he left is unclear", "किमर्थं सः अगच्छत् इति अस्पष्टम्", "kimarthaṃ saḥ agacchat iti aspaṣṭam"],
        ["That is not what I meant", "यत् अहं अभिप्रैमि तत् न एतत्", "yat ahaṃ abhipraimi tat na etat"],
    ],
    559: [
        ["Please read the notice carefully", "सूचनां सावधानं पठतु", "sūcānāṃ sāvadhaānaṃ paṭhatu"],
        ["Submit the form by Friday", "शुक्रवासरे पत्रिकां समर्पयतु", "śukravāsare patrikāṃ samarpayatu"],
        ["Employees must wear badges", "कर्मकरैः परिचयपत्राणि धार्याणि", "karmakaraiḥ paricayapatrāṇi dhāryāṇi"],
        ["Do not use mobiles here", "इह मोबाइलं मा उपयुञ्जध्वम्", "iha mobailaṃ mā upayuñjadhvam"],
        ["Maintain silence in the library", "पुस्तकालये मौनं रक्षतु", "pustakālaye maunaṃ rakṣatu"],
        ["Visitors should register at the gate", "द्वारि पञ्जीकरणं करोतु", "dvāri pañjīkaraṇaṃ karotu"],
        ["Follow safety instructions", "रक्षानिर्देशान् अनुसरतु", "rakṣānirdeśān anusaratu"],
        ["Stand in a line", "पङ्क्तौ स्थातु", "paṅktau sthātu"],
        ["Do not touch the exhibits", "प्रदर्शनानि मा स्पृशतु", "pradarśanāni mā spṛśatu"],
        ["Report suspicious baggage", "शङ्कास्पदं भारं निवेदयतु", "śaṅkāspadaṃ bhāraṃ nivedayatu"],
        ["Switch off lights when leaving", "गच्छन् दीपान् निर्वापयतु", "gacchan dīpān nirvāpayatu"],
        ["Staff must not share passwords", "गुप्तशब्दान् मा प्रकाशयतु", "guptaśabdān mā prakāśayatu"],
        ["Keep the passage clear", "मार्गं शुद्धं रक्षतु", "mārgaṃ śuddhaṃ rakṣatu"],
        ["Patients take tokens first", "रोगिणः प्रथमं तोकनं गृह्णन्तु", "rogiṇaḥ prathamaṃ tokanaṃ gṛhṇantu"],
        ["Sign here and here", "इह च इह च हस्ताक्षरं कुरुत", "iha ca iha ca hastākṣaraṃ kuruta"],
    ],
    560: [
        ["I like mangoes", "मे आम्राणि रोचन्ते", "me āmrāṇi rocante"],
        ["She likes to dance", "तस्याः नृत्यं रोचते", "tasyāḥ nṛtyaṃ rocate"],
        ["We like this place", "नः इयम् स्थानम् रोचते", "naḥ iyam sthānam rocate"],
        ["Do you like spicy food?", "तीक्ष्णम् अन्नम् रोचते वा?", "tīkṣṇam annam rocate vā?"],
        ["He does not like crowds", "तस्य जनसमूहः न रोचते", "tasya janasamūhaḥ na rocate"],
        ["Children like sweets", "बालकानां मिष्टानि रोचन्ते", "bālakānāṃ miṣṭāni rocante"],
        ["I would like some tea", "मे चायाः इच्छा अस्ति", "me chāyāḥ icchā asti"],
        ["She likes reading novels", "तस्याः उपन्यासाः रोचन्ते", "tasyāḥ upanyāsāḥ rocante"],
        ["We like your company", "नः भवतः सहवासः रोचते", "naḥ bhavataḥ sahavāsaḥ rocate"],
        ["I do not like falsehood", "मे अनृतं न रोचते", "me anṛtaṃ na rocate"],
        ["He likes cold weather", "तस्य शीतलः पावकः रोचते", "tasya śītalaḥ pāvakaḥ rocate"],
        ["Do you like Sanskrit plays?", "संस्कृतनाटकानि रोचन्ते वा?", "saṃskṛtanāṭakāni rocante vā?"],
        ["I like morning walks", "प्रभाते अटनम् मे रोचते", "prabhāte aṭanam me rocate"],
        ["She likes helping others", "परेषां साहाय्यम् तस्यै रोचते", "pareṣāṃ sāhāyyam tasyai rocate"],
        ["We liked the programme", "नः कार्यक्रमः अरोचत", "naḥ kāryakramaḥ arocata"],
    ],
    561: [
        ["I would help if I could", "यदि शक्नोमि तर्हि साहाय्यं करोमि", "yadi śaknomi tarhi sāhāyyaṃ karomi"],
        ["Would you like water?", "भवतः जलस्य इच्छा अस्ति वा?", "bhavataḥ jalasya icchā asti vā?"],
        ["He would come every Sunday", "प्रतिवारम् आगच्छत् सः", "prativāram āgacchat saḥ"],
        ["We would sit under the tree", "वृक्षस्य अधः आसाम स्म", "vṛkṣasya adhaḥ āsāma sma"],
        ["I would read before sleep", "स्वप्नात् पूर्वम् अहं पठामि स्म", "svapnāt pūrvam ahaṃ paṭhāmi sma"],
        ["She would sing softly", "सा मृदु गायति स्म", "sā mṛdu gāyati sma"],
        ["They would play in the street", "मार्गे ते क्रीडन्ति स्म", "mārge te krīḍanti sma"],
        ["It would rain in monsoon", "वर्षासु वर्षति स्म", "varṣāsu varṣati sma"],
        ["I would rather walk", "अहं पादाभ्यां गन्तुम् इच्छामि", "ahaṃ pādābhyāṃ gantum icchāmi"],
        ["Would you mind closing the door?", "द्वारं पिदधातु भवान्?", "dvāraṃ pidadhātu bhavān?"],
        ["He would never lie", "सः कदापि अनृतं न अवदत्", "saḥ kadāpi anṛtaṃ na avadat"],
        ["We would share our lunch", "मध्याह्नभोजनं वयं वितराम स्म", "madhyāhnabhojanaṃ vayaṃ vitarāma sma"],
        ["Mother would wake early", "अम्बा प्रभाते उत्थितवती स्म", "ambā prabhāte utthitavatī sma"],
        ["I would feel afraid at night", "रात्रौ अहं भीतः आसम्", "rātrau ahaṃ bhītaḥ āsam"],
        ["That would be fine", "तत् उचितम् भविष्यति", "tat ucitam bhaviṣyati"],
    ],
    562: [
        ["I understand your problem", "तव समस्याम् अहं अवगच्छामि", "tava samasyām ahaṃ avagacchāmi"],
        ["Did you understand the lesson?", "पाठम् अवगतवान् वा?", "pāṭham avagatavān vā?"],
        ["I suddenly understood", "अकस्मात् अहं अवगतवान्", "akasmāt ahaṃ avagatavān"],
        ["She does not understand well", "सा सुष्ठु न अवगच्छति", "sā suṣṭhu na avagacchati"],
        ["Help me understand this map", "एतत् नक्शम् अवगन्तुं माम् साहाय्यं कुरु", "etat nakśam avagantuṃ mām sāhāyyaṃ kuru"],
        ["I came to know yesterday", "ह्यः अहं अजानाम्", "hyaḥ ahaṃ ajānām"],
        ["How did you come to know?", "कथम् ज्ञातवान्?", "katham jñātavān?"],
        ["We learnt through the news", "वार्तया वयं जानीम", "vārtayā vayaṃ jānīma"],
        ["He learnt the truth later", "पश्चात् सः सत्यम् अजानात्", "paścāt saḥ satyam ajānāt"],
        ["I understand; do not worry", "अवगतम् चिन्तां मा कृध्वम्", "avagatam cintāṃ mā kṛdhvam"],
        ["Little children understand slowly", "बालकाः धीरम् अवगच्छन्ति", "bālakāḥ dhīram avagacchanti"],
        ["I could not understand his accent", "तस्य उच्चारणम् अहं न अवगतवान्", "tasya uccāraṇam ahaṃ na avagatavān"],
        ["She understood without words", "वचनम् विना सा अवगतवती", "vacanam vinā sā avagatavatī"],
        ["Tell me if you understand", "यदि अवगच्छसि तदा वद", "yadi avagacchasi tadā vada"],
        ["I understand the situation now", "अधुना स्थितिम् अहं अवगच्छामि", "adhunā sthitim ahaṃ avagacchāmi"],
    ],
    563: [
        ["You are coming, aren't you?", "त्वम् आगच्छसि न वा?", "tvam āgacchasi na vā?"],
        ["He is at home, isn't he?", "सः गृहे अस्ति न?", "saḥ gṛhe asti na?"],
        ["She can read, can't she?", "सा पठितुं शक्नोति न?", "sā paṭhituṃ śaknoti na?"],
        ["We shall go, shall we not?", "वयं गमिष्यामः न वा?", "vayaṃ gamiṣyāmaḥ na vā?"],
        ["It is cold today, isn't it?", "अद्य शीतलम् अस्ति न?", "adya śītalam asti na?"],
        ["You do not eat meat, do you?", "त्वं मांसं न अश्नासि किम्?", "tvaṃ māṃsaṃ na aśnāsi kim?"],
        ["They have not come yet, have they?", "ते अद्यापि न आगताः किम्?", "te adyāpi na āgatāḥ kim?"],
        ["This is your book, isn't it?", "इदं भवतः पुस्तकम् अस्ति न?", "idaṃ bhavataḥ pustakam asti na?"],
        ["You were there, weren't you?", "त्वम् तत्र आसीः न वा?", "tvam tatra āsīḥ na vā?"],
        ["Let us go, shall we?", "गच्छामहे न वा?", "gacchāmahe na vā?"],
        ["He will not agree, will he?", "सः न सम्मन्यते किम्?", "saḥ na sammanyate kim?"],
        ["She likes sweets, doesn't she?", "तस्यै मिष्टम् रोचते न?", "tasyai miṣṭam rocate na?"],
        ["You can swim, can't you?", "त्वं तरणं शक्नोषि न वा?", "tvaṃ taraṇaṃ śaknoṣi na vā?"],
        ["It will not rain, will it?", "न वर्षिष्यति किम्?", "na varṣiṣyati kim?"],
        ["We should leave, shouldn't we?", "गन्तव्यम् न वा अस्माकम्?", "gantavyam na vā asmākam?"],
    ],
    564: [
        ["I remember your name", "भवतः नाम स्मरामि", "bhavataḥ nāma smarāmi"],
        ["I forgot where I kept the keys", "कुत्र चाबिकाः स्थापिताः इति विस्मृतवान्", "kutra cābikāḥ sthāpitāḥ iti vismṛtavān"],
        ["Try to remember the date", "तिथिम् स्मरतु", "tithim smaratu"],
        ["I suddenly remembered the promise", "प्रतिज्ञाम् अकस्मात् स्मृतवान्", "pratijñām akasmāt smṛtavān"],
        ["She remembers everything", "सा सर्वम् स्मरति", "sā sarvam smarati"],
        ["Do you remember me?", "माम् स्मरसि वा?", "mām smarasi vā?"],
        ["I cannot remember that word", "तत् पदम् अहं न स्मरामि", "tat padam ahaṃ na smarāmi"],
        ["We remember our teachers", "वयं आचार्यान् स्मरामः", "vayaṃ ācāryān smarāmaḥ"],
        ["Remember to lock the door", "द्वारं बद्धं कर्तुम् स्मरतु", "dvāraṃ baddhaṃ kartum smaratu"],
        ["He remembered the way", "मार्गम् सः स्मृतवान्", "mārgaṃ saḥ smṛtavān"],
        ["Childhood memories are sweet", "बाल्यस्मृतयः मधुराः", "bālyasmṛtayaḥ madhurāḥ"],
        ["I will never forget this help", "एतत् साहाय्यम् न विस्मरिष्यामि", "etat sāhāyyam na vismariṣyāmi"],
        ["Please remind me tomorrow", "श्वः माम् स्मारयतु", "śvaḥ mām smārayatu"],
        ["She forgot to bring the file", "पत्रिकां आनेतुम् सा विस्मृतवती", "patrikām ānetum sā vismṛtavatī"],
        ["Memories fade with time", "कालेन स्मृतयः म्लीयन्ते", "kālena smṛtayaḥ mlīyante"],
    ],
    565: [
        ["I want to go home", "अहं गृहं गन्तुम् इच्छामि", "ahaṃ gṛhaṃ gantum icchāmi"],
        ["She wants to sleep early", "सा प्रभाते स्वप्तुम् इच्छति", "sā prabhāte svaptum icchati"],
        ["We want to watch the match", "द्यूतम् द्रष्टुम् वयं इच्छामः", "dyūtaṃ draṣṭum vayaṃ icchāmaḥ"],
        ["He wants to buy a phone", "सः दूरवाणीं क्रीणातुम् इच्छति", "saḥ dūravāṇīṃ krīṇātum icchati"],
        ["They want to learn English", "आङ्ग्लभाषाम् अधीतुम् ते इच्छन्ति", "āṅgla-bhāṣām adhītum te icchanti"],
        ["I do not want to quarrel", "कलहं कर्तुम् अहं न इच्छामि", "kalahaṃ kartum ahaṃ na icchāmi"],
        ["Do you want to come along?", "सह आगन्तुम् इच्छसि वा?", "saha āgantum icchasi vā?"],
        ["She wants to help her mother", "सा मातरं साहाय्यं कर्तुम् इच्छति", "sā mātaraṃ sāhāyyaṃ kartum icchati"],
        ["We want peace", "वयं शान्तिम् इच्छामः", "vayaṃ śāntim icchāmaḥ"],
        ["He wants to leave work", "सः कार्यं त्यक्तुम् इच्छति", "saḥ kāryaṃ tyaktum icchati"],
        ["I want to drink cold water", "शीतलं जलं पातुम् इच्छामि", "śītalaṃ jalaṃ pātum icchāmi"],
        ["Children want to play", "बालकाः क्रीडितुम् इच्छन्ति", "bālakāḥ krīḍitum icchanti"],
        ["She wants to become a nurse", "सा चिकित्सिका भवितुम् इच्छति", "sā cikitsikā bhavitum icchati"],
        ["We want to visit Kashi", "काशीं द्रष्टुम् वयं इच्छामः", "kāśīṃ draṣṭum vayaṃ icchāmaḥ"],
        ["He wants to save money", "धनं रक्षितुम् सः इच्छति", "dhanaṃ rakṣitum saḥ icchati"],
    ],
}
