# Sanskrit Lesson 1 — Script & pronunciation (chapter IDs 501–509).
# Columns: English, Sanskrit (Devanagari), Transliteration (IAST-style).

LESSONS_S1 = {
    501: [
        ["Sanskrit has thirteen vowels (svarāḥ)", "संस्कृते त्रयोदश स्वराः सन्ति", "saṃskṛte trayodaśa svarāḥ santi"],
        ["Short अ (a)", "अ", "a"],
        ["Long आ (ā)", "आ", "ā"],
        ["Short इ (i)", "इ", "i"],
        ["Long ई (ī)", "ई", "ī"],
        ["Short उ (u)", "उ", "u"],
        ["Long ऊ (ū)", "ऊ", "ū"],
        ["Vowel ऋ (ṛ)", "ऋ", "ṛ"],
        ["Vowel ॠ (ṝ)", "ॠ", "ṝ"],
        ["Vowel ऌ (ḷ)", "ऌ", "ḷ"],
        ["Diphthong ए (e)", "ए", "e"],
        ["Diphthong ऐ (ai)", "ऐ", "ai"],
        ["Diphthong ओ (o)", "ओ", "o"],
        ["Diphthong औ (au)", "औ", "au"],
        ["The vowels are written first in the alphabet", "वर्णमालायां स्वराः प्रथमं लिख्यन्ते", "varṇamālāyāṃ svarāḥ prathamaṃ likhyante"],
        ["Practice writing अ आ इ ई", "अ आ इ ई लिखतु", "a ā i ī likhatu"],
    ],
    502: [
        ["Consonants are called vyañjanāni", "व्यञ्जनानि वर्णाः सन्ति", "vyañjanāni varṇāḥ santi"],
        ["Velar क ख ग घ ङ", "क ख ग घ ङ", "ka kha ga gha ṅa"],
        ["Palatal च छ ज झ ञ", "च छ ज झ ञ", "ca cha ja jha ña"],
        ["Retroflex ट ठ ड ढ ण", "ट ठ ड ढ ण", "ṭa ṭha ḍa ḍha ṇa"],
        ["Dental त थ द ध न", "त थ द ध न", "ta tha da dha na"],
        ["Labial प फ ब भ म", "प फ ब भ म", "pa pha ba bha ma"],
        ["Semi-vowel य र ल व", "य र ल व", "ya ra la va"],
        ["Sibilants श ष स", "श ष स", "śa ṣa sa"],
        ["Aspirated sounds need extra breath", "महाप्राणाः उच्चारणे वायुः अधिकः", "mahāprāṇāḥ uccāraṇe vāyuḥ adhikaḥ"],
        ["Unaspirated क is light", "अल्पप्राणः ककारः", "alpaprāṇaḥ kakāraḥ"],
        ["Practice: क-ग, च-ज, ट-ड", "क-ग च-ज ट-ड अभ्यस्यतु", "ka-ga ca-ja ṭa-ḍa abhyasyatu"],
        ["ṅa is nasal after velars", "अनुनासिकः ङ् कवर्गे", "anunāsikaḥ ṅ kavarge"],
        ["ña follows palatals", "ञ् पलटलवर्गे", "ñ palatalavarge"],
        ["Clear retroflex vs dental: ट त", "मूर्धन्यः दन्त्यः च भेदः", "mūrdhanyaḥ dantyaḥ ca bhedaḥ"],
        ["Read syllables slowly first", "प्रथमं धीरं पठतु", "prathamaṃ dhīraṃ paṭhatu"],
        ["Repeat after the teacher", "आचार्यस्य अनन्तरं पुनः वदतु", "ācāryasya anantaraṃ punaḥ vadatu"],
    ],
    503: [
        ["Barakhadi: consonant + vowel signs", "व्यञ्जनैः सह स्वरचिह्नानि", "vyañjanaiḥ saha svaracihnāni"],
        ["क + अ = क (ka)", "क", "ka"],
        ["क + आ = का (kā)", "का", "kā"],
        ["क + इ = कि (ki)", "कि", "ki"],
        ["क + ई = की (kī)", "की", "kī"],
        ["क + उ = कु (ku)", "कु", "ku"],
        ["क + ऊ = कू (kū)", "कू", "kū"],
        ["क + ए = के (ke)", "के", "ke"],
        ["क + ऐ = कै (kai)", "कै", "kai"],
        ["क + ओ = को (ko)", "को", "ko"],
        ["क + औ = कौ (kau)", "कौ", "kau"],
        ["Similarly: गा गि गु गे...", "एवं गादिः लिख्यताम्", "evaṃ gādiḥ likhyatām"],
        ["Each consonant has twelve forms with vowels", "प्रत्येकस्य व्यञ्जनस्य द्वादश रूपाणि", "pratyekasya vyañjanasya dvādaśa rūpāṇi"],
        ["Practice row: ख खा खि...", "ख-वर्गं पठतु", "kha-vargaṃ paṭhatu"],
        ["Write from memory: च चा चि...", "स्मरणात् लिखतु", "smaraṇāt likhatu"],
        ["Read words: कमलम्, पत्रम्", "पदानि पठतु: कमलम् पत्रम्", "padāni paṭhatu: kamalam patram"],
    ],
    504: [
        ["Aspiration: kh is not k+h together", "प्राणः एकः न द्वौ वर्णौ", "prāṇaḥ ekaḥ na dvau varṇau"],
        ["Retroflex ṭ is tongue-tip back", "मूर्धन्यः जिह्वामूलम् उर्ध्वम्", "mūrdhanyaḥ jihvāmūlam ūrdhvam"],
        ["Dental t is near teeth", "दन्त्यः दन्तान् स्पृशति", "dantyaḥ dentān spṛśati"],
        ["Do not confuse श (palatal) and ष (retroflex)", "श ष योः भेदं रक्षतु", "śa ṣayoḥ bhedaṃ rakṣatu"],
        ["Visargaḥ sounds like echo of preceding vowel", "विसर्गः पूर्वस्वरस्य अनुकृतिः", "visargaḥ pūrvasvarasya anukṛtiḥ"],
        ["Long vowels need double duration", "दीर्घाः स्वराः द्विगुणं कालम्", "dīrghāḥ svarāḥ dviguṇaṃ kālam"],
        ["Anusvāra follows vowel in same syllable", "अनुस्वारः स्वरेण सह एकस्मिन् अक्षरे", "anusvāraḥ svareṇa saha ekasmin akṣare"],
        ["Avoid English r for Sanskrit र", "आङ्ग्लीयम् ‘r’ मा प्रयुञ्जीत", "āṅglīyam ‘r’ mā prayuñjīta"],
        ["Practice minimal pairs: प फ, ब भ", "साधर्म्ये भिन्नानि पठतु", "sādharmye bhinnāni paṭhatu"],
        ["Listen and repeat three times", "त्रिवारं शृणुत पुनः वदतु", "trivāraṃ śṛṇuta punaḥ vadatu"],
        ["Stress is usually on first long syllable", "दीर्घे अक्षरे बलम् अधिकम्", "dīrghākṣare balam adhikam"],
        ["Nasalization is light, not full ‘n’", "अनुनासिकता मृदुः", "anunāsikatā mṛduḥ"],
        ["Record yourself and compare", "स्वस्य उच्चारणं रेकॉर्ड कृत्वा तुलयतु", "svasya uccāraṇaṃ rekŏrḍa kṛtvā tulayatu"],
        ["Read this: रामः सीतां पश्यति", "वाक्यं पठतु", "vākyaṃ paṭhatu"],
        ["Clear articulation is more important than speed", "स्पष्टता वेगात् प्रधाना", "spaṣṭatā vegāt pradānā"],
    ],
    505: [
        ["Anusvāra (ं) is nasalization of the class", "अनुस्वारः वर्गीयानुनासिकता", "anusvāraḥ vargīyānunāsikatā"],
        ["Before क ख ग घ → ङ् sound", "कवर्गे पूर्वं ङ्", "kavarge pūrvaṃ ṅ"],
        ["Before च छ ज झ → ञ् sound", "चवर्गे पूर्वं ञ्", "cavarge pūrvaṃ ñ"],
        ["Before ट ठ ड ढ → ण् sound", "टवर्गे पूर्वं ण्", "ṭavarge pūrvaṃ ṇ"],
        ["Before त थ द ध → न् sound", "तवर्गे पूर्वं न्", "tavarge pūrvaṃ n"],
        ["Before प फ ब भ → म् sound", "पवर्गे पूर्वं म्", "pavarge pūrvaṃ m"],
        ["Example: संस्कृतम् (saṃskṛtam)", "संस्कृतम्", "saṃskṛtam"],
        ["Example: गङ्गा (gaṅgā)", "गङ्गा", "gaṅgā"],
        ["Example: अञ्जनम् (añjanam)", "अञ्जनम्", "añjanam"],
        ["Sometimes written as bindu in manuscripts", "हस्तलेखेषु बिन्दुरूपेण अपि", "hastalekheṣu bindurūpeṇa api"],
        ["Pronounce with soft nasal hum", "मृदु नादेन उच्चारयतु", "mṛdu nādena uccārayatu"],
        ["Contrast: अं vs अन् at word end", "अन्ते अनुस्वार-अनुनासिकयोः भेदः", "ante anusvāra-anunāsikayoḥ bhedaḥ"],
        ["Practice: संगीतम्, पण्डितः", "पदानि पठतु", "padāni paṭhatu"],
        ["Do not drop the nasal completely", "अनुस्वारं न त्यजतु", "anusvāraṃ na tyajatu"],
        ["Listen to verse recitation for models", "श्लोकपाठं शृणुत", "ślokapāṭhaṃ śṛṇuta"],
        ["Read: वंदे मातरम्", "वन्दे मातरम्", "vande mātaram"],
    ],
    506: [
        ["Conjunct letters join consonants without intervening vowel", "संयुक्ताक्षराणि अन्तरा स्वरं विना", "saṃyuktākṣarāṇi antarā svaraṃ vinā"],
        ["क् + त = क्त (kta)", "क्त", "kta"],
        ["प् + त = प्त (pta)", "प्त", "pta"],
        ["न् + त = न्त (nta)", "न्त", "nta"],
        ["स् + त = स्त (sta)", "स्त", "sta"],
        ["म् + प = म्प (mpa)", "म्प", "mpa"],
        ["द् + द = द्द (dda)", "द्द", "dda"],
        ["ग् + ग = ग्ग (gga)", "ग्ग", "gga"],
        ["Split conjuncts left to right when reading", "वामतः दक्षिणं पठतु", "vāmataḥ dakṣiṇaṃ paṭhatu"],
        ["Practice: प्र, ट्र, क्ष", "प्र ट्र क्ष लिखतु", "pra ṭra kṣa likhatu"],
        ["Common cluster: स्त, स्प, स्म", "स्पर्शाः बहवः", "sparśāḥ bahavaḥ"],
        ["Write: विद्या, सत्यम्", "विद्या सत्यम्", "vidyā satyam"],
        ["Read slowly: अस्ति", "अस्ति", "asti"],
        ["Double consonants need clear release", "द्विवर्णयोः विमोचनं स्पष्टम्", "dvivarṇayoḥ vimocanaṃ spaṣṭam"],
        ["Example word: पुस्तकम्", "पुस्तकम्", "pustakam"],
        ["Example word: संस्कृतम्", "संस्कृतम्", "saṃskṛtam"],
    ],
    507: [
        ["र् combines forward: प्र, त्र, क्र", "र् अग्रे योजयति", "r agre yojayati"],
        ["प्र is p + ra vowel", "प्र = प् + र", "pra = p + ra"],
        ["त्र is t + ra", "त्र", "tra"],
        ["क्र is k + ra", "क्र", "kra"],
        ["ग्र is g + ra", "ग्र", "gra"],
        ["द्र is d + ra", "द्र", "dra"],
        ["श्र is ś + ra", "श्र", "śra"],
        ["When र is first: र्क र्ग (rka, rga)", "र्क र्ग", "rka rga"],
        ["Practice: प्रथमम्, त्रयः", "प्रथमम् त्रयः", "prathamam trayaḥ"],
        ["Read: गुरुः, श्रीः", "गुरुः श्रीः", "guruḥ śrīḥ"],
        ["Do not pronounce extra vowel after र्", "र् पश्चात् अतिरिक्तं स्वरं मा कुरुत", "r paścāt atiriktaṃ svaramā kuruta"],
        ["Contrast: र vs ड़ (Hindi) — Sanskrit uses र only", "संस्कृते केवलं रः", "saṃskṛte kevalaṃ raḥ"],
        ["Write five words with प्र", "प्र-युक्तानि पञ्च पदानि", "pra-yuktāni pañca padāni"],
        ["Recite: प्रकृतिः, प्रकाशः", "प्रकृतिः प्रकाशः", "prakṛtiḥ prakāśaḥ"],
        ["Cluster drill: ब्र, भ्र, म्र", "ब्र भ्र म्र", "bra bhra mra"],
    ],
    508: [
        ["ह् combines: ख, थ, फ + ह", "ह् अन्ते योगः", "h ante yogaḥ"],
        ["क्ष is k + ṣa (special)", "क्ष", "kṣa"],
        ["ज्ञ is j + ña (special)", "ज्ञ", "jña"],
        ["ह is pronounced from throat", "हः कण्ठ्यः", "haḥ kaṇṭhyaḥ"],
        ["छ is aspirated ca", "छः महाप्राणः चः", "chaḥ mahāprāṇaḥ caḥ"],
        ["Practice: महत्, वहति", "महत् वहति", "mahat vahati"],
        ["Read: साहित्यम्, बाह्यम्", "साहित्यम् बाह्यम्", "sāhityam bāhyam"],
        ["ह at end of word is light", "अन्ते हलन्तः हः", "ante halantaḥ haḥ"],
        ["Contrast ह vs हा", "ह हा योः भेदः", "ha hāyoḥ bhedaḥ"],
        ["Write: अनुभवः, स्नेहः", "अनुभवः स्नेहः", "anubhavaḥ snehaḥ"],
        ["Common: नमः, दुःखम्", "नमः दुःखम्", "namaḥ duḥkham"],
        ["Pronounce ह clearly, not silent", "हः स्पष्टः", "haḥ spaṣṭaḥ"],
        ["Drill: योगः, रोगः", "योगः रोगः", "yogaḥ rogaḥ"],
        ["Sanskrit ह is voiced glottal", "हः घोषवान्", "haḥ ghoṣavān"],
        ["Example verse line with ह", "श्लोकांशः पठतु", "ślokāṃśaḥ paṭhatu"],
    ],
    509: [
        ["Some clusters use special ligatures", "केचित् संयोगाः विशिष्टलिपिभिः", "kecit saṃyogāḥ viśiṣṭalipibhiḥ"],
        ["क्ष ज्ञ are taught as single letters in some traditions", "क्ष ज्ञ एकवर्णवत् पठ्येते", "kṣa jña ekavarṇavat paṭhyete"],
        ["Print vs handwriting shapes may differ", "मुद्रणे लेखने च भेदः", "mudraṇe lekhane ca bhedaḥ"],
        ["Old manuscripts: stacked conjuncts", "पुराणहस्तलेखाः ऊर्ध्वरचनाः", "purāṇahastalekhāḥ ūrdhvaracanāḥ"],
        ["Modern fonts: horizontal stacking", "आधुनिकेषु अक्षरेषु तुल्यम्", "ādhunikeṣu akṣareṣu tulyam"],
        ["Rare clusters need careful copying", "दुर्लभाः संयोगाः सावधानम्", "durlabhāḥ saṃyogāḥ sāvadhānam"],
        ["Consult a teacher for regional variants", "पारम्परिकभेदान् गुरोः पृच्छतु", "pāramparikabhedān guroḥ pṛcchatu"],
        ["Practice: कर्मन्, धर्मः", "कर्मन् धर्मः", "karman dharmaḥ"],
        ["Read: संयुक्ताक्षराणि सूची", "सूचीम् अवलोकयतु", "sūcīm avalokayatu"],
        ["Write your name in Devanagari", "स्वनाम देवनागरीलिप्यां लिखतु", "svanāma devanāgarīlipyāṃ likhatu"],
        ["Double-check dot positions for ं ः", "बिन्दु-विसर्गयोः स्थानम्", "bindu-visargayoḥ sthānam"],
        ["Virāma (्) removes inherent vowel", "विरामः स्वरहरणम् करोति", "virāmaḥ svaraharaṇam karoti"],
        ["Example: नमस्ते (namaste)", "नमस्ते", "namaste"],
        ["Example: हरिः ॐ (hariḥ om)", "हरिः ॐ", "hariḥ om"],
        ["Keep practicing daily", "प्रतिदिनं अभ्यस्यतु", "pratidinaṃ abhyasyatu"],
    ],
}
