# Sanskrit Lesson 3 — chunk B (chapter IDs 566–596).

LESSONS_S3B = {
    566: [
        ["I want him to study", "तस्य अध्ययनम् इच्छामि", "tasya adhyayanam icchāmi"],
        ["She wants us to wait", "सा अस्मान् प्रतीक्षते", "sā asmān pratīkṣate"],
        ["They want me to sing", "ते मे गानम् इच्छन्ति", "te me gānam icchanti"],
        ["We want you to be careful", "त्वां सावधानं भवितुम् इच्छामः", "tvāṃ sāvadhaānaṃ bhavitum icchāmaḥ"],
        ["He wants his son to work", "सः पुत्रं कार्यं कर्तुम् इच्छति", "saḥ putraṃ kāryaṃ kartum icchati"],
        ["Mother wants me to marry", "माता मां विवाहं कर्तुम् इच्छति", "mātā māṃ vivāhaṃ kartum icchati"],
        ["I do not want them to fight", "ते कलहं कर्तुम् अहं न इच्छामि", "te kalahaṃ kartum ahaṃ na icchāmi"],
        ["Teacher wants silence", "आचार्यः मौनम् इच्छति", "ācāryaḥ maunam icchati"],
        ["She wants the physician to come", "सा चिकित्सकम् आगन्तुम् इच्छति", "sā cikitsakam āgantum icchati"],
        ["I want you to understand", "त्वाम् अवगन्तुम् इच्छामि", "tvām avagantum icchāmi"],
        ["We want the king to help", "राज्ञा साहाय्यम् कर्तुम् इच्छामः", "rājñā sāhāyyam kartum icchāmaḥ"],
        ["He wants his friend to go", "सः मित्रं गन्तुम् इच्छति", "saḥ mitraṃ gantum icchati"],
        ["Do you want me to call?", "माम् आह्वातुम् इच्छसि वा?", "mām āhvātum icchasi vā?"],
        ["Parents want children to learn", "पितरः बालकान् अधीतुम् इच्छन्ति", "pitaraḥ bālakān adhītum icchanti"],
    ],
    567: [
        ["I should arrive by nine", "नववादने आगन्तव्यम् मे", "navavādane āgantavyam me"],
        ["You should wear uniform", "एकरूपवस्त्रं धारयितव्यम्", "ekarūpavastraṃ dhārayitavyam"],
        ["He should pay today", "अद्य दातव्यम् सः", "adya dātavyaṃ saḥ"],
        ["We should attend the assembly", "सभां गन्तव्यम् अस्माभिः", "sabhāṃ gantavyam asmābhiḥ"],
        ["The chariot should arrive now", "अधुना रथः आगन्तव्यः", "adhunā rathaḥ āgantavyaḥ"],
        ["I was to call yesterday", "ह्यः आह्वातव्यम् आसीत् मे", "hyaḥ āhvātavyam āsīt me"],
        ["Students should bring books", "छात्रैः पुस्तकानि आनेतव्यानि", "chātraiḥ pustakāni ānetavyāni"],
        ["She should rest", "तस्याः विश्रामः कर्तव्यः", "tasyāḥ viśrāmaḥ kartavyaḥ"],
        ["You were to inform me", "माम् निवेदयितव्यम् आसीत्", "mām nivedayitavyam āsīt"],
        ["The shop should open at ten", "दशवादने आपणः उद्घाटनीयः", "daśavādane āpaṇaḥ udghāṭanīyaḥ"],
        ["I must not tell anyone", "कस्मैचित् न वक्तव्यम् मे", "kasmaicit na vaktavyam me"],
        ["They should report early", "प्रभाते निवेदनं कर्तव्यम्", "prabhāte nivedanaṃ kartavyam"],
        ["What should I do?", "किम् कर्तव्यम् मे?", "kim kartavyam me?"],
        ["Medicine should act quickly", "औषधं शीघ्रं कार्यं करोतु", "auṣadhaṃ śīghraṃ kāryaṃ karotu"],
    ],
    568: [
        ["I like walking in rain", "वर्षे अटनम् मे रोचते", "varṣe aṭanam me rocate"],
        ["She likes reading before sleep", "स्वप्नात् पूर्वम् पठनम् रोचते", "svapnāt pūrvam paṭhanam rocate"],
        ["We like eating together", "सह भोजनम् नः रोचते", "saha bhojanaṃ naḥ rocate"],
        ["He dislikes waiting", "प्रतीक्षा तस्य न रोचते", "pratīkṣā tasya na rocate"],
        ["Children like questions", "बालकानां प्रश्नाः रोचन्ते", "bālakānāṃ praśnāḥ rocante"],
        ["I would like to see your village", "भवतः ग्रामं द्रष्टुम् इच्छामि", "bhavataḥ grāmaṃ draṣṭum icchāmi"],
        ["She likes helping in kitchen", "रसोदे साहाय्यम् रोचते तस्यै", "rasode sāhāyyam rocate tasyai"],
        ["Do you like to sing?", "गातुम् रोचते वा?", "gātum rocate vā?"],
        ["We like watching news", "वार्ताः द्रष्टुम् नः रोचते", "vārtāḥ draṣṭum naḥ rocate"],
        ["I dislike quarrel", "कलहः न मे रोचते", "kalahaḥ na me rocate"],
        ["They like travel by chariot", "रथेन यात्रा ते रोचते", "rathena yātrā te rocate"],
        ["Grandmother likes stories", "पितामह्याः कथाः रोचन्ते", "pitāmahyāḥ kathāḥ rocante"],
        ["I like hot milk", "उष्णं क्षीरम् मे रोचते", "uṣṇaṃ kṣīram me rocate"],
        ["She likes neat dress", "शुचि वस्त्रम् तस्यै रोचते", "śuci vastram tasyai rocate"],
    ],
    569: [
        ["I listen to the teacher", "आचार्यं श‍ृणोमि", "ācāryaṃ śṛṇomi"],
        ["She looks at the moon", "चन्द्रम् ऐक्षत", "candram aikṣata"],
        ["We agree with the plan", "योजनया सह सम्मताः वयम्", "yojanayā saha sammatāḥ vayam"],
        ["He answered the letter", "पत्रस्य उत्तरम् अदात्", "patrasya uttaram adāt"],
        ["They objected to the rule", "नियमस्य विरोधं कृतवन्तः", "niyamasya virodhaṃ kṛtavantaḥ"],
        ["I belong to this village", "अस्मिन् ग्रामे अहम् अस्मि", "asmin grāme aham asmi"],
        ["She listens to mother", "मातरम् श‍ृणोति", "mātaram śṛṇoti"],
        ["We pray to the Lord", "ईश्वरं प्रार्थयामहे", "īśvaraṃ prārthayāmahe"],
        ["He called to the crowd", "जनसमूहम् आह्वयत्", "janasamūham āhvayat"],
        ["I wrote to my brother", "भ्रात्रे पत्रं अलिखम्", "bhrātre patraṃ alikham"],
        ["She waved to the children", "बालकान् हस्तेन अलम्बत्", "bālakān hasten alambat"],
        ["We bow to the teacher", "आचार्यं नमामः", "ācāryaṃ namāmaḥ"],
        ["He pointed to the map", "नक्शम् दर्शयति स्म", "nakśam darśayati sma"],
        ["I explained to guests", "अतिथिभ्यः व्याख्यातवान्", "atithibhyaḥ vyākhyātavān"],
    ],
    570: [
        ["I am well", "अहं कुशली अस्मि", "ahaṃ kuśalī asmi"],
        ["What happened?", "किम् अभवत्?", "kim abhavat?"],
        ["Come here", "इह आगच्छ", "iha āgaccha"],
        ["I do not know", "न जानामि", "na jānāmi"],
        ["Yes / agreed", "आम् / सम्मतः", "ām / sammataḥ"],
        ["Where do you go?", "कुत्र गच्छसि?", "kutra gacchasi?"],
        ["See you again", "पुनः मिलामहे", "punaḥ milāmahe"],
        ["No difficulty", "किञ्चित् दुःखम् न अस्ति", "kiñcit duḥkham na asti"],
        ["Hurry", "शीघ्रम्", "śīghram"],
        ["Leave it", "तत् त्यज", "tat tyaja"],
        ["Really?", "सत्यम्?", "satyam?"],
        ["I shall come", "आगमिष्यामि", "āgamiṣyāmi"],
        ["Do not worry", "चिन्तां मा कृध्वम्", "cintāṃ mā kṛdhvam"],
        ["That is enough", "एतावत् अलम्", "etāvat alam"],
    ],
    571: [
        ["Good morning", "सुप्रभातम्", "suprabhātam"],
        ["Good evening", "शुभ सायङ्कालः", "śubha sāyaṅkālaḥ"],
        ["Salutation with namaste", "नमस्ते", "namaste"],
        ["Happy birthday", "जन्मदिनस्य शुभेच्छाः", "janmadinasya śubhecchāḥ"],
        ["Happy new year", "नववर्षस्य शुभाः", "navavarṣasya śubhāḥ"],
        ["Congratulations", "अभिनन्दनम्", "abhinandanam"],
        ["Get well soon", "शीघ्रं स्वस्थः भव", "śīghraṃ svasthaḥ bhava"],
        ["May the Lord protect you", "ईश्वरः त्वां रक्षतु", "īśvaraḥ tvāṃ rakṣatu"],
        ["Long live!", "चिरं जीव!", "ciraṃ jīva!"],
        ["Welcome", "स्वागतम्", "svāgatam"],
        ["Farewell", "पुनर्दर्शनम्", "punardarśanam"],
        ["Happy Deepavali", "दीपावल्याः शुभाः", "dīpāvalyāḥ śubhāḥ"],
        ["Festival greetings", "उत्सवस्य शुभकामनाः", "utsavasya śubhakāmanāḥ"],
        ["May you prosper", "भव श्रीमान्", "bhava śrīmān"],
        ["Thank you", "धन्यवादः", "dhanyavādaḥ"],
    ],
    572: [
        ["Eat and go", "भुक्त्वा गच्छ", "bhuktvā gaccha"],
        ["Sit and rest", "उपविश्य विश्रामं कुरु", "upaviśya viśrāmaṃ kuru"],
        ["He rose and spoke", "सः उत्थाय अवदत्", "saḥ utthāy avadat"],
        ["Come and see", "आगत्य पश्य", "āgatya paśya"],
        ["She wept and slept", "सा रुदित्वा स्वपिति स्म", "sā ruditvā svapiti sma"],
        ["We read and discussed", "वयं पठित्वा चर्चाम् कृतवन्तः", "vayaṃ paṭhitvā carcām kṛtavantaḥ"],
        ["Open and enter", "उद्घाट्य प्रविश", "udghāṭya praviśa"],
        ["Think and answer", "चिन्तयित्वा उत्तरं देहि", "cintayitvā uttaraṃ dehi"],
        ["Finish work and go home", "कार्यं समाप्य गृहं गच्छ", "kāryaṃ samāpya gṛhaṃ gaccha"],
        ["Wash hands and eat", "हस्तौ धौत्वा अश्नीहि", "hastau dhautvā aśnīhi"],
        ["He ran and caught", "सः धावित्वा अगृह्णात्", "saḥ dhāvitvaṃ agṛhṇāt"],
        ["Listen and write", "श‍ृणुति लिख", "śṛṇuti likha"],
        ["We met and decided", "वयं मिलित्वा निश्चिनुमः", "vayaṃ militvaṃ niścinumaḥ"],
        ["Pack and leave", "परिपाकं कृत्वा गच्छ", "paripākaṃ kṛtvā gaccha"],
    ],
    573: [
        ["Brother", "भ्राता", "bhrātā"],
        ["Sister", "भगिनी", "bhaginī"],
        ["Uncle", "पितुः भ्राता", "pituḥ bhrātā"],
        ["Aunt", "मातुः भगिनी", "mātuḥ bhaginī"],
        ["Grandfather", "पितामहः", "pitāmahaḥ"],
        ["Grandmother", "पितामही", "pitāmahī"],
        ["Respected sir", "भोः महोदय", "bhoḥ mahodaya"],
        ["Listen, friend", "श‍ृणु मित्र", "śṛṇu mitra"],
        ["Son", "पुत्रः", "putraḥ"],
        ["Daughter", "दुहिता", "duhitā"],
        ["Sir / madam", "भवान् / भवती", "bhavān / bhavatī"],
        ["Teacher", "आचार्यः", "ācāryaḥ"],
        ["Physician", "चिकित्सकः", "cikitsakaḥ"],
        ["Young man", "युवा", "yuvā"],
    ],
    574: [
        ["Oh! what surprise!", "अहो आश्चर्यम्!", "aho āścaryam!"],
        ["Alas! he left", "हा सः अगच्छत्!", "hā saḥ agacchat!"],
        ["Wonderful!", "अद्भुतम्!", "adbhutam!"],
        ["It hurts!", "पीडा अस्ति!", "pīḍā asti!"],
        ["Hey! stop!", "हं रुध्यताम्!", "haṃ rudhyatām!"],
        ["Bravo!", "साधु!", "sādhu!"],
        ["What nonsense!", "किम् अयुक्तम्!", "kim ayuktam!"],
        ["Thank heaven!", "देवान् नमः!", "devān namaḥ!"],
        ["How sad!", "किम् दुःखम्!", "kim duḥkham!"],
        ["So sweet!", "किम् मधुरम्!", "kim madhuram!"],
        ["What noise!", "किम् शब्दः!", "kim śabdaḥ!"],
        ["Impossible!", "अशक्यम्!", "aśakyam!"],
        ["Silence!", "मौनम्!", "maunam!"],
        ["Look out!", "अपेक्षस्व!", "apekṣasva!"],
    ],
    575: [
        ["May I enter?", "प्रवेष्टुम् शक्नोमि वा?", "praveṣṭum śaknomi vā?"],
        ["Can you help?", "साहाय्यं कर्तुं शक्नोषि वा?", "sāhāyyaṃ kartuṃ śaknoṣi vā?"],
        ["Pass the salt", "लवणं देहि", "lavaṇaṃ dehi"],
        ["Please sit", "उपविशतु", "upaviśatu"],
        ["May I use your phone?", "भवतः दूरवाणीम् उपयोक्तुम् शक्नोमि वा?", "bhavataḥ dūravāṇīm upayoktum śaknomi vā?"],
        ["Repeat that", "पुनः वदतु", "punaḥ vadata"],
        ["Would you wait?", "प्रतीक्षसे वा?", "pratīkṣase vā?"],
        ["May I ask?", "पृच्छामि वा?", "pṛcchāmi vā?"],
        ["Show the way", "मार्गं दर्शयतु", "mārgaṃ darśayatu"],
        ["Speak slowly", "शनैः वदतु", "śanaiḥ vadata"],
        ["May I take this seat?", "इदम् आसनं ग्रहीतुम् शक्नोमि वा?", "idam āsanaṃ grahītum śaknomi vā?"],
        ["Call a chariot", "रथम् आह्वयतु", "ratham āhvayatu"],
        ["Would you like milk?", "क्षीरस्य इच्छा अस्ति वा?", "kṣīrasya icchā asti vā?"],
        ["Leave early today", "अद्य शीघ्रं गच्छतु", "adya śīghraṃ gacchatu"],
    ],
    576: [
        ["It might rain tomorrow", "श्वः वर्षेत्", "śvaḥ varṣet"],
        ["He may come late", "सः दीर्घायुषः आगमिष्यति", "saḥ dīrghāyuṣḥ āgamiṣyati"],
        ["We might take the chariot", "रथं ग्रहिष्यामः", "rathaṃ grahṣyāmaḥ"],
        ["She might not agree", "सा न सम्मन्यते", "sā na sammanyate"],
        ["It may be true", "सत्यम् भवेत्", "satyam bhavet"],
        ["Remind me — I might forget", "स्मारय — विस्मरिष्यामि", "smāraya — vismariṣyāmi"],
        ["Keys might be inside", "चाबिकाः अन्तः स्युः", "cābikāḥ antaḥ syuḥ"],
        ["They might have left", "ते गताः स्युः", "te gatāḥ syuḥ"],
        ["This might help", "इदं साहाय्यं करोति", "idaṃ sāhāyyaṃ karoti"],
        ["You might feel tired", "त्वं क्लान्तः भवेः", "tvaṃ klāntaḥ bhaveḥ"],
        ["Shop might be closed", "आपणः बद्धः स्यात्", "āpaṇaḥ baddhaḥ syāt"],
        ["Rain might fall", "वर्षः पतेत्", "varṣaḥ patet"],
    ],
    577: [
        ["written letter", "लिखितम् पत्रम्", "likhitam patram"],
        ["boiled water", "उष्णं जलम्", "uṣṇaṃ jalam"],
        ["fried bread", "भृष्टम् रोटिकम्", "bhṛṣṭaṃ roṭikam"],
        ["broken chair", "भग्नम् आसनम्", "bhagnam āsanam"],
        ["closed door", "बद्धं द्वारम्", "baddhaṃ dvāram"],
        ["open window", "उद्घाटितः कवाटः", "udghāṭitaḥ kavāṭaḥ"],
        ["lost keys", "नष्टाः चाबिकाः", "naṣṭāḥ cābikāḥ"],
        ["tired traveller", "क्लान्तः यात्री", "klāntaḥ yātrī"],
        ["cooked food", "पक्तम् अन्नम्", "paktam annam"],
        ["washed clothes", "धौतानि वस्त्राणि", "dhautāni vastrāṇi"],
        ["painted wall", "रङ्गितः भित्तिः", "raṅgitaḥ bhittiḥ"],
        ["signed form", "हस्ताक्षरिता पत्रिका", "hastākṣaritā patrikā"],
        ["packed bundle", "परिपकम् स्थूलकम्", "paripakam sthūlakam"],
    ],
    578: [
        ["boy inside the house", "गृहस्य अन्तः बालकः", "gṛhasya antaḥ bālakaḥ"],
        ["shop near the bridge", "सेतुः समीपे आपणः", "setuḥ samīpe āpaṇaḥ"],
        ["people from the village", "ग्रामात् जनाः", "grāmāt janāḥ"],
        ["road to the city", "नगरं प्रति मार्गः", "nagaraṃ prati mārgaḥ"],
        ["trees along the river", "नद्या तटे वृक्षाः", "nadyā taṭe vṛkṣāḥ"],
        ["cat under the bed", "शय्यायाः अधः विडालः", "śayyāyāḥ adhaḥ viḍālaḥ"],
        ["book on the table", "फलके पुस्तकम्", "phalake pustakam"],
        ["friends behind us", "अस्मत् पृष्ठे मित्राणि", "asmat pṛṣṭhe mitrāṇi"],
        ["school opposite park", "उद्यानस्य सम्मुखे विद्यालयः", "udyānasya sammukhe vidyālayaḥ"],
        ["water in the pot", "घटे जलम्", "ghaṭe jalam"],
        ["first house after crossing", "तीरणात् परम् प्रथमं गृहम्", "tīraṇāt param prathamaṃ gṛham"],
    ],
    579: [
        ["May you live long", "दीर्घायुः भव", "dīrghāyuḥ bhava"],
        ["May God protect", "देवः रक्षतु", "devaḥ rakṣatu"],
        ["May peace prevail", "शान्तिः भवतु", "śāntiḥ bhavatu"],
        ["May wishes be fulfilled", "कामनाः सिद्धाः भवन्तु", "kāmanāḥ siddhāḥ bhavantu"],
        ["May the festival bring joy", "उत्सवः आनन्दं नयतु", "utsavaḥ ānandaṃ nayatu"],
        ["May you succeed", "सफलः भव", "safalaḥ bhava"],
        ["May farmers get rain", "कृषकेभ्यः वर्षः भवतु", "kṛṣakebhyaḥ varṣaḥ bhavatu"],
        ["May the sick recover", "रोगिणः स्वस्थाः भवन्तु", "rogiṇaḥ svasthāḥ bhavantu"],
        ["May friendship last", "मैत्री चिरं स्थिरा भवतु", "maitrī ciraṃ sthirā bhavatu"],
        ["May none go hungry", "कोऽपि क्षुधितः मा भूत्", "ko'pi kṣudhitaḥ mā bhūt"],
        ["May children study well", "बालकाः सुष्ठु अधीयन्ताम्", "bālakāḥ suṣṭhu adhīyantām"],
        ["May journey be safe", "यात्रा सुरक्षिता भवतु", "yātrā surakṣitā bhavatu"],
    ],
    580: [
        ["Mother put the child to sleep", "अम्बा बालकं सुप्तवती", "ambā bālakaṃ suptavatī"],
        ["He got the cart repaired", "सः रथं ठीकम् अकारयत्", "saḥ rathaṃ ṭhīkam akārayat"],
        ["She had him write", "तया सः लिखितः", "tayā saḥ likhitaḥ"],
        ["I will get the room painted", "कक्ष्यां रङ्गयिष्यामि", "kakṣyāṃ raṅgayiṣyāmi"],
        ["They made us wait", "ते अस्मान् प्रतीक्षयामासुः", "te asmān pratīkṣayāmāsuḥ"],
        ["Teacher made students read", "आचार्यः छात्रान् पाठयति", "ācāryaḥ chātrān pāṭhayati"],
        ["Get this work done", "एतत् कार्यं समाप्नुहि", "etat kāryaṃ samāpnuhi"],
        ["She had food cooked", "सा भोजनं पाचयति स्म", "sā bhojanaṃ pācayati sma"],
        ["He drove the dog away", "सः शुनकं अपासर्पयत्", "saḥ śunakam apāsarpayat"],
        ["I cannot make him understand", "तम् अवगमयितुं न शक्नोमि", "tam avagamayituṃ na śaknomi"],
        ["We shall get a new gate built", "नवं द्वारं कारयिष्यामः", "navaṃ dvāraṃ kārayiṣyāmaḥ"],
        ["Boss had report typed", "प्रभुः रिपोर्टम् टङ्कयितवान्", "prabhuḥ ripoṭam ṭaṅkayitavān"],
    ],
    581: [
        ["Someone is at the door", "कश्चित् द्वारि अस्ति", "kaścid dvāri asti"],
        ["I left something in the room", "किञ्चित् कक्ष्यायाम् त्यक्तवान्", "kiñcit kakṣyāyām tyaktavān"],
        ["Nothing is impossible", "किञ्चित् अशक्यम् न अस्ति", "kiñcit aśakyam na asti"],
        ["Anyone may try", "कश्चित् प्रयत्नं करोतु", "kaścit prayatnaṃ karotu"],
        ["Somewhere in the city", "नगरे क्वचित्", "nagare kvacit"],
        ["Somehow we managed", "कथञ्चित् वयं निर्वृताः", "kathañcit vayaṃ nirvṛtāḥ"],
        ["Everyone was happy", "सर्वे सुखिनः आसन्", "sarve sukhinaḥ āsan"],
        ["Nowhere is safe without care", "अप्रमादेन न कुत्रापि सुरक्षितम्", "apramādena na kutrāpi surakṣitam"],
        ["Anything can happen", "किञ्चित् भवितुम् शक्नोति", "kiñcit bhavitum śaknoti"],
        ["Someone called you", "कश्चित् त्वाम् आह्वयत्", "kaścit tvām āhvayat"],
        ["I need something to eat", "भोक्तुम् मे किञ्चित् आवश्यकम्", "bhoktum me kiñcit āvaśyakam"],
        ["Nobody came", "कोऽपि न आगच्छत्", "ko'pi na āgacchat"],
        ["Everywhere was decorated", "सर्वत्र अलङ्कृतम् आसीत्", "sarvatra alaṅkṛtam āsīt"],
    ],
    582: [
        ["I have two brothers", "मे द्वौ भ्रातरौ स्तः", "me dvau bhrātarau staḥ"],
        ["She has fever", "तस्याः ज्वरः अस्ति", "tasyāḥ jvaraḥ asti"],
        ["We have a small house", "नः अल्पं गृहम् अस्ति", "naḥ alpaṃ gṛham asti"],
        ["He has no money today", "अद्य तस्य धनं न अस्ति", "adya tasya dhanaṃ na asti"],
        ["Do you have children?", "भवतः पुत्राः सन्ति वा?", "bhavataḥ putrāḥ santi vā?"],
        ["I have an idea", "मे मतिः अस्ति", "me matiḥ asti"],
        ["The tree has many branches", "वृक्षस्य बहवः शाखाः सन्ति", "vṛkṣasya bahavaḥ śākhāḥ santi"],
        ["She has long hair", "तस्याः दीर्घाः कचाः सन्ति", "tasyāḥ dīrghāḥ kacāḥ santi"],
        ["We have time until evening", "सायङ्कालं यावत् अस्माकम् समयः अस्ति", "sāyaṅkālaṃ yāvat asmākam samayaḥ asti"],
        ["He has a kind heart", "तस्य दयालुः हृदयम् अस्ति", "tasya dayāluḥ hṛdayam asti"],
        ["I have nothing to say", "वक्तुम् मे किञ्चित् न अस्ति", "vaktum me kiñcit na asti"],
        ["They have three chariots", "तेषां त्रयः रथाः सन्ति", "teṣāṃ trayaḥ rathāḥ santi"],
        ["The bag has a hole", "पेटिकायाः छिद्रम् अस्ति", "peṭikāyāḥ chidram asti"],
    ],
    583: [
        ["What does this word mean?", "इदं पदं किमर्थम्?", "idaṃ padaṃ kimartham?"],
        ["I do not understand the meaning", "अर्थम् अहं न अवगच्छामि", "artham ahaṃ na avagacchāmi"],
        ["This sentence means peace", "एतत् वाक्यं शान्तिं द्योतयति", "etat vākyaṃ śāntiṃ dyotayati"],
        ["What do you mean?", "किम् अभिप्रैषि?", "kim abhipraiṣi?"],
        ["I meant to help", "साहाय्यम् अभिप्रेतवान्", "sāhāyyam abhipretavān"],
        ["Words can have many meanings", "पदानि बहून् अर्थान् धारयन्ति", "padāni bahūn arthān dhārayanti"],
        ["Explain the meaning", "अर्थं व्याख्यातु", "arthaṃ vyākhyātu"],
        ["That name means ‘light’", "तत् नाम प्रकाशम् अर्थयति", "tat nāma prakāśam arthayati"],
        ["I did not mean to hurt", "पीडां अभिप्रेतवान् न अस्मि", "pīḍāṃ abhipretavān na asmi"],
        ["What is meant by this sign?", "एतस्य चिह्नस्य कः अर्थः?", "etasya cihnasya kaḥ arthaḥ?"],
        ["Teacher explained the meaning", "आचार्यः अर्थम् व्याख्यातवान्", "ācāryaḥ artham vyākhyātavān"],
        ["Double meaning", "द्विगुणः अर्थः", "dviguṇaḥ arthaḥ"],
        ["Look up in dictionary", "शब्दकोशे अन्विष्यताम्", "śabdakośe anviṣyatām"],
    ],
    584: [
        ["I came and he left", "अहम् आगच्छम् सः अगच्छत्", "aham āgaccham saḥ agacchat"],
        ["But it is raining", "किन्तु वर्षति", "kintu varṣati"],
        ["Because I was ill", "यतो अहम् अस्वस्थः आसम्", "yato aham asvasthaḥ āsam"],
        ["So we stayed home", "तस्मात् गृहे स्थितवन्तः", "tasmāt gṛhe sthitavantaḥ"],
        ["He said that he will come", "सः आगमिष्यति इति अवदत्", "saḥ āgamiṣyati iti avadat"],
        ["Although it was late", "यद्यपि दीर्घायुषः आसीत्", "yadyapi dīrghāyuṣḥ āsīt"],
        ["Though tired, she worked", "क्लान्ता अपि सा कार्यम् अकरोत्", "klāntā api sā kāryam akarot"],
        ["Still I hope", "तथापि आशा अस्ति मे", "tathāpi āśā asti me"],
        ["Yet nobody came", "तथापि कोऽपि न आगच्छत्", "tathāpi ko'pi na āgacchat"],
        ["Bread and butter", "रोटिका च माक्षिकम् च", "roṭikā ca mākṣikam ca"],
        ["Slow but steady", "मन्दः तु स्थिरः", "mandaḥ tu sthiraḥ"],
        ["Because of rain the match stopped", "वर्षणात् क्रीडा स्थगिता", "varṣaṇāt krīḍā sthagitā"],
        ["So that children may learn", "येन बालकाः अधीयन्ते", "yena bālakāḥ adhīyante"],
    ],
    585: [
        ["As you wish", "यथा भवान् इच्छति", "yathā bhavān icchati"],
        ["Tea or milk?", "चायः उत क्षीरम्?", "cāyaḥ uta kṣīram?"],
        ["Neither he nor she", "न सः न सा", "na saḥ na sā"],
        ["Neither time nor money", "न समयः न धनम्", "na samayaḥ na dhanam"],
        ["If it rains", "यदि वर्षति", "yadi varṣati"],
        ["In case of need", "आवश्यकतायाम्", "āvaśyakatāyām"],
        ["Provided you agree", "यदि त्वं सम्मन्यसे", "yadi tvaṃ sammanyase"],
        ["Or else we cancel", "अन्यथा वयं रद्दं कुर्मः", "anyathā vayaṃ raddaṃ kurmaḥ"],
        ["Neither this nor that", "न इदम् न तत्", "na idam na tat"],
        ["As I said", "यथा अहम् अवदम्", "yathā aham avadam"],
        ["If not today, tomorrow", "न अद्य श्वः", "na adya śvaḥ"],
        ["Either come or send word", "आगच्छ वा सन्देशं प्रेषय", "āgaccha vā sandeśaṃ preṣaya"],
    ],
    586: [
        ["After dinner we walked", "भोजनानन्तरं वयं चरामः", "bhojanānantaraṃ vayaṃ carāmaḥ"],
        ["Then he spoke", "ततः सः अवदत्", "tataḥ saḥ avadat"],
        ["As far as I know", "यावत् अहं जानामि", "yāvat ahaṃ jānāmi"],
        ["As long as you stay", "यावत् त्वं तिष्ठसि", "yāvat tvaṃ tiṣṭhasi"],
        ["As if nothing happened", "यथा किञ्चित् न अभवत्", "yathā kiñcit na abhavat"],
        ["After exam we rested", "परीक्षायाः अनन्तरं विश्रामम् कृतवन्तः", "parīkṣāyāḥ anantaraṃ viśrāmam kṛtavantaḥ"],
        ["Then the chariot arrived", "ततः रथः आगच्छत्", "tataḥ rathaḥ āgacchat"],
        ["As far as the eye sees", "यावत् अक्ष्णा पश्यति", "yāvat akṣṇā paśyati"],
        ["As long as life lasts", "यावत् जीवनम्", "yāvat jīvanam"],
        ["He looked as if afraid", "सः भीतः इव दृष्टः", "saḥ bhītaḥ iva dṛṣṭaḥ"],
        ["When you finish, call me", "यदा समाप्नोषि तदा माम् आह्वय", "yadā samāpnoṣi tadā mām āhvaya"],
    ],
    587: [
        ["As soon as I reached, it rained", "यदा आगच्छम् तदा वर्षत्", "yadā āgaccham tadā varṣat"],
        ["Once you try, you will like", "एकवारम् यतस्व रोचिष्यते", "ekavāram yatasva rociṣyate"],
        ["Rather than fight, talk", "कलहात् वदनम् श्रेयः", "kalahāt vadanam śreyaḥ"],
        ["Instead of chariot, walk", "रथस्य अपेक्षया पद्भ्याम् गच्छ", "rathasya apekṣayā padbhyām gaccha"],
        ["So that none may suffer", "येन कोऽपि न दुःखितः", "yena ko'pi na duḥkhitaḥ"],
        ["As soon as bell rang, class began", "घण्टायाः नादे सभा आरब्धा", "ghaṇṭāyāḥ nāde sabhā ārabdhā"],
        ["Once I know, I will tell", "यदा जानामि तदा वदामि", "yadā jānāmi tadā vadāmi"],
        ["Rather than wait, go", "प्रतीक्षायाः गमनम् श्रेयः", "pratīkṣāyāḥ gamanaṃ śreyaḥ"],
        ["Study so that you pass", "उत्तीर्णः भवितुम् अधीयस्व", "uttīrṇaḥ bhavitum adhīyasva"],
    ],
    588: [
        ["and — च", "रोटिका च क्षीरम् च", "roṭikā ca kṣīram ca"],
        ["but — किन्तु", "मन्दः किन्तु स्थिरः", "mandaḥ kintu sthiraḥ"],
        ["because — यतः", "वर्षात् यतः स्थगितम्", "varṣāt yataḥ sthagitam"],
        ["so — तस्मात्", "तस्मात् वयं गताः", "tasmāt vayaṃ gatāḥ"],
        ["that — इति", "सः आगमिष्यति इति", "saḥ āgamiṣyati iti"],
        ["although — यद्यपि", "यद्यपि क्लान्तः", "yadyapi klāntaḥ"],
        ["if — यदि", "यदि वर्षति", "yadi varṣati"],
        ["or — वा", "चायः वा क्षीरम्", "cāyaḥ vā kṣīram"],
        ["neither… nor — न… न", "न सः न सा", "na saḥ na sā"],
        ["after — पश्चात्", "भोजनात् पश्चात्", "bhojanāt paścāt"],
        ["before — पूर्वम्", "सूर्योदयात् पूर्वम्", "sūryodayāt pūrvam"],
        ["until — यावत्", "सायङ्कालं यावत्", "sāyaṅkālaṃ yāvat"],
    ],
    589: [
        ["The sun rose. Birds sang.", "सूर्यः उदतिष्ठत् पक्षिणः अगायन्", "sūryaḥ udatiṣṭhat pakṣiṇaḥ agāyan"],
        ["Combined: sun rose and birds sang", "सूर्ये उदिते पक्षिणः अगायन्", "sūrye udite pakṣiṇaḥ agāyan"],
        ["He was tired. He slept.", "सः क्लान्तः आसीत् सः अस्वापीत्", "saḥ klāntaḥ āsīt saḥ asvāpīt"],
        ["Tired from work, he slept", "कार्यक्लान्तः सः अस्वापीत्", "kāryaklāntaḥ saḥ asvāpīt"],
        ["It rained. We stayed.", "वर्षत् आसीत् वयं स्थितवन्तः", "varṣat āsīt vayaṃ sthitavantaḥ"],
        ["Because it rained, we stayed", "वर्षणात् वयं स्थितवन्तः", "varṣaṇāt vayaṃ sthitavantaḥ"],
        ["She opened the book and read", "सा पुस्तकं उद्घाट्य पठति स्म", "sā pustakaṃ udghāṭya paṭhati sma"],
        ["Opening the book, she read", "पुस्तकं उद्घाट्य सा पठति स्म", "pustakaṃ udghāṭya sā paṭhati sma"],
    ],
    590: [
        ["Go and see", "गत्वा पश्य", "gatvā paśya"],
        ["Eat and drink", "भुक्त्वा पिब", "bhuktvā piba"],
        ["He read and understood", "सः पठित्वा अवगतवान्", "saḥ paṭhitvā avagatavān"],
        ["Come and sit", "आगत्य उपविश", "āgatya upaviśa"],
        ["She stood and left", "सा उत्थाय अगच्छत्", "sā utthāy agacchat"],
        ["We laughed and talked", "वयं हसित्वा अवदाम", "vayaṃ hasitvā avadāma"],
        ["Take and give", "गृहीत्वा देहि", "gṛhītvā dehi"],
        ["Wash and wear", "धौत्वा धारय", "dhautvā dhāraya"],
        ["Open and read", "उद्घाट्य पठ", "udghāṭya paṭha"],
    ],
    591: [
        ["Rāma wrote the letter", "रामः पत्रं लिखति", "rāmaḥ patraṃ likhati"],
        ["Passive: letter was written by Rāma", "रामेण पत्रं लिखितम्", "rāmeṇa patraṃ likhitam"],
        ["The dog bit the man", "शुनकः पुरुषं दशति", "śunakaḥ puruṣaṃ daśati"],
        ["The man was bitten", "पुरुषः दष्टः", "puruṣaḥ daṣṭaḥ"],
        ["They built the bridge", "ते सेतुं निर्मितवन्तः", "te setuṃ nirmitavantaḥ"],
        ["The bridge was built", "सेतुः निर्मितः", "setuḥ nirmitaḥ"],
        ["She cooks food", "सा भोजनं पचति", "sā bhojanaṃ pacati"],
        ["Food is cooked by her", "तया भोजनं पक्तम्", "tayā bhojanaṃ paktam"],
        ["Open the door", "द्वारं उद्घाटय", "dvāraṃ udghāṭaya"],
        ["The door was opened", "द्वारं उद्घाटितम्", "dvāraṃ udghāṭitam"],
    ],
    592: [
        ["Someone stole my chariot", "कश्चित् मम रथं अचौरयत्", "kaścit mama rathaṃ acaurayat"],
        ["My chariot was stolen", "मम रथः अपहृतः", "mama rathaḥ apahṛtaḥ"],
        ["Water fills the pot", "जलं घटं पूरयति", "jalaṃ ghaṭaṃ pūrayati"],
        ["The pot is filled", "घटः पूर्णः", "ghaṭaḥ pūrṇaḥ"],
        ["They elected him leader", "ते तम् नेता चितवन्तः", "te tam netā citavantaḥ"],
        ["He was elected", "सः चितः", "saḥ citaḥ"],
        ["We must finish work", "कार्यं समाप्तव्यम्", "kāryaṃ samāptavyam"],
        ["The work must be done", "कार्यं कर्तव्यम्", "kāryaṃ kartavyam"],
        ["He is reading", "सः पठति", "saḥ paṭhati"],
        ["The book is being read", "पुस्तकं पठ्यते", "pustakaṃ paṭhyate"],
    ],
    593: [
        ["I feel cold", "मे शीतलता अनुभूयते", "me śītalatā anubhūyate"],
        ["She feels happy today", "अद्य तस्यै सुखम् अनुभूयते", "adya tasyai sukham anubhūyate"],
        ["I think it will rain", "मन्ये वर्षिष्यति", "manye varṣiṣyati"],
        ["What do you think?", "किं मन्यसे?", "kiṃ manyase?"],
        ["She thinks before speaking", "वदति पूर्वम् चिन्तयति", "vadati pūrvam cintayati"],
        ["We feel proud", "नः गर्वः अनुभूयते", "naḥ garvaḥ anubhūyate"],
        ["He feels pain in the leg", "जङ्घायाम् पीडा तस्य", "jaṅghāyām pīḍā tasya"],
        ["I thought you knew", "मन्ये त्वं जानासि इति", "manye tvaṃ jānāsi iti"],
        ["They think we are wrong", "ते मन्यन्ते वयं मिथ्या इति", "te manyante vayaṃ mithyā iti"],
    ],
    594: [
        ["Kill two birds with one stone", "एकेन प्रहारेण द्वौ उद्दीपयतु", "ekena prahāreṇa dvau uddīpayatu"],
        ["After long time", "दीर्घकालात् परम्", "dīrghakālāt param"],
        ["Heart to heart", "हृदयात् हृदयम्", "hṛdayāt hṛdayam"],
        ["Better late than never", "दीर्घायुषः आगमनम् अपि श्रेयः", "dīrghāyuṣḥ āgamanam api śreyaḥ"],
        ["All that glitters is not gold", "यत् सर्वं दीप्यते न सुवर्णम्", "yat sarvaṃ dīpyate na suvarṇam"],
        ["Once in a blue moon", "दुर्लभकाले", "durlabhakāle"],
        ["Early bird catches worm", "प्रभाते उत्तिष्ठन् लभते", "prabhāte uttiṣṭhan labhate"],
    ],
    595: [
        ["Burn midnight oil", "मध्यरात्रौ तैलं दीप्यते", "madhyarātrau tailaṃ dīpyate"],
        ["Smell a rat", "शुनकम् अन्विष्यते", "śunakam anviṣyate"],
        ["Break the ice", "हिमं भिन्दि", "himaṃ bhindi"],
        ["Cost an arm and leg", "बहु मूल्यम्", "bahu mūlyam"],
        ["Let the cat out", "विडालम् बहिः कुरु", "viḍālam bahiḥ kuru"],
        ["Beat about the bush", "वृक्षस्य परितः मा गम", "vṛkṣasya paritaḥ mā gama"],
        ["Piece of cake", "सुलभम्", "sulabham"],
    ],
    596: [
        ["If you hurry, you catch the chariot", "यदि शीघ्रं गच्छसि तर्हि रथं गृह्णासि", "yadi śīghraṃ gacchasi tarhi rathaṃ gṛhṇāsi"],
        ["If I were rich, I would help", "यदि धनवान् अभविष्यम् अहं साहाय्यं कुर्याम्", "yadi dhanavān abhaviṣyam ahaṃ sāhāyyaṃ kuryām"],
        ["Unless you try, you will not learn", "यदि न यतसे तर्हि न अधीषे", "yadi na yatase tarhi na adhīṣe"],
        ["Provided you pay, take it", "यदि ददासि तर्हि गृहाण", "yadi dadāsi tarhi gṛhāṇa"],
        ["If it had rained, crops would have grown", "यदि वर्षिष्यत् तर्हि शस्यानि वर्धिष्यन्त", "yadi varṣiṣyat tarhi śasyāni vardhiṣyanta"],
        ["If she had called, I would have come", "यदि सा आह्वयिष्यत् अहम् आगमिष्यम्", "yadi sā āhvayiṣyat aham āgamiṣyam"],
        ["If they agree, deal is fixed", "यदि ते सम्मन्यन्ते तर्हि सौदः निश्चितः", "yadi te sammanyante tarhi saudaḥ niścitaḥ"],
        ["If not today, tomorrow for sure", "न अद्य श्वः निश्चितम्", "na adya śvaḥ niścitam"],
        ["If lightning flashes, stay inside", "यदि विद्युत् चमत्करोति तर्हि अन्तः स्थीयताम्", "yadi vidyut camatkaroti tarhi antaḥ sthīyatām"],
    ],
}
