# Sanskrit Lesson 4 — Vocabulary (chapter IDs 597–619).

LESSONS_S4 = {
    597: [
        ["Head", "शिरः", "śiraḥ"],
        ["Hair", "केशाः", "keśāḥ"],
        ["Eye", "अक्षि", "akṣi"],
        ["Ear", "कर्णः", "karṇaḥ"],
        ["Nose", "नासिका", "nāsikā"],
        ["Mouth", "मुखम्", "mukham"],
        ["Tooth", "दन्तः", "dantaḥ"],
        ["Tongue", "जिह्वा", "jihvā"],
        ["Neck", "ग्रीवा", "grīvā"],
        ["Shoulder", "स्कन्धः", "skandhaḥ"],
        ["Arm", "बाहुः", "bāhuḥ"],
        ["Hand", "हस्तः", "hastaḥ"],
        ["Finger", "अङ्गुलिः", "aṅguliḥ"],
        ["Chest", "उरः", "uraḥ"],
        ["Heart", "हृदयम्", "hṛdayam"],
        ["Stomach", "उदरम्", "udaram"],
        ["Leg", "जङ्घा", "jaṅghā"],
        ["Foot", "पादः", "pādaḥ"],
    ],
    598: [
        ["Thing", "वस्तु", "vastu"],
        ["Place", "स्थानम्", "sthānam"],
        ["Time", "कालः", "kālaḥ"],
        ["Day", "दिनम्", "dinam"],
        ["Night", "रात्रिः", "rātriḥ"],
        ["Morning", "प्रभातम्", "prabhātam"],
        ["Evening", "सायङ्कालः", "sāyaṅkālaḥ"],
        ["Today", "अद्य", "adya"],
        ["Tomorrow", "श्वः", "śvaḥ"],
        ["Yesterday", "ह्यः", "hyaḥ"],
        ["Now", "अधुना", "adhunā"],
        ["Soon", "शीघ्रम्", "śīghram"],
        ["Always", "सदा", "sadā"],
        ["Never", "न कदापि", "na kadāpi"],
        ["Perhaps", "कदाचित्", "kadācit"],
        ["Certainly", "निश्चितम्", "niścitam"],
        ["Maybe", "सम्भवतः", "sambhavataḥ"],
    ],
    599: [
        ["Father", "पिता", "pitā"],
        ["Mother", "माता", "mātā"],
        ["Son", "पुत्रः", "putraḥ"],
        ["Daughter", "दुहिता", "duhitā"],
        ["Brother", "भ्राता", "bhrātā"],
        ["Sister", "भगिनी", "bhaginī"],
        ["Husband", "पतिः", "patiḥ"],
        ["Wife", "पत्नी", "patnī"],
        ["Grandfather", "पितामहः", "pitāmahaḥ"],
        ["Grandmother", "पितामही", "pitāmahī"],
        ["Uncle (father’s brother)", "पितृव्यः", "pitṛvyaḥ"],
        ["Aunt", "मातुला", "mātulā"],
        ["Son-in-law", "जामाता", "jāmātā"],
        ["Daughter-in-law", "स्नुषा", "snuṣā"],
        ["Friend", "मित्रम्", "mitram"],
        ["Neighbour", "अन्तिकवासी", "antikavāsī"],
    ],
    600: [
        ["One", "एकः / एकम्", "ekaḥ / ekam"],
        ["Two", "द्वौ / द्वे", "dvau / dve"],
        ["Three", "त्रयः / तिस्रः", "trayaḥ / tisraḥ"],
        ["Four", "चत्वारः", "catvāraḥ"],
        ["Five", "पञ्च", "pañca"],
        ["Six", "षट्", "ṣaṭ"],
        ["Seven", "सप्त", "sapta"],
        ["Eight", "अष्ट", "aṣṭa"],
        ["Nine", "नव", "nava"],
        ["Ten", "दश", "daśa"],
        ["Eleven", "एकादश", "ekādaśa"],
        ["Twelve", "द्वादश", "dvādaśa"],
        ["Thirteen", "त्रयोदश", "trayodaśa"],
        ["Fourteen", "चतुर्दश", "caturdaśa"],
        ["Fifteen", "पञ्चदश", "pañcadaśa"],
        ["Sixteen", "षोडश", "ṣoḍaśa"],
        ["Seventeen", "सप्तदश", "saptadaśa"],
        ["Eighteen", "अष्टादश", "aṣṭādaśa"],
        ["Nineteen", "नवदश", "navadaśa"],
        ["Twenty", "विंशति", "viṃśati"],
    ],
    601: [
        ["Twenty-one", "एकविंशति", "ekaviṃśati"],
        ["Thirty", "त्रिंशत्", "triṃśat"],
        ["Forty", "चत्वारिंशत्", "catvāriṃśat"],
        ["Fifty", "पञ्चाशत्", "pañcāśat"],
        ["Sixty", "षष्टिः", "ṣaṣṭiḥ"],
        ["Seventy", "सप्ततिः", "saptatiḥ"],
        ["Eighty", "अशीतिः", "aśītiḥ"],
        ["Ninety", "नवतिः", "navatiḥ"],
        ["Hundred", "शतम्", "śatam"],
        ["Two hundred", "द्विशतम्", "dviśatam"],
        ["Thousand", "सहस्रम्", "sahasram"],
        ["Ten thousand", "अयुतम्", "ayutam"],
        ["Lakh (hundred thousand)", "लक्षम्", "lakṣam"],
        ["First", "प्रथमः", "prathamaḥ"],
        ["Second", "द्वितीयः", "dvitīyaḥ"],
        ["Third", "तृतीयः", "tṛtīyaḥ"],
        ["Last", "अन्तिमः", "antimaḥ"],
    ],
    602: [
        ["Half", "अर्धम्", "ardham"],
        ["Quarter", "पादः (fourth part)", "pādaḥ"],
        ["One third", "तृतीयभागः", "tṛtīyabhāgaḥ"],
        ["Twice", "द्विगुणम्", "dviguṇam"],
        ["Thrice", "त्रिगुणम्", "triguṇam"],
        ["Pair", "युगम्", "yugam"],
        ["Dozen", "द्वादशकम्", "dvādaśakam"],
        ["Percent", "प्रतिशतम्", "pratiśatam"],
        ["Sequence", "अनुक्रमः", "anukramaḥ"],
        ["First (in order)", "प्रथमम्", "prathamam"],
        ["Next", "अग्रिमः", "agrimaḥ"],
        ["Previous", "पूर्वः", "pūrvaḥ"],
        ["Total", "समष्टिः", "samaṣṭiḥ"],
        ["Average", "मध्यमम्", "madhyamam"],
        ["Approximately", "प्रायेण", "prāyeṇa"],
        ["Exactly", "यथार्थतः", "yathārthataḥ"],
    ],
    603: [
        ["To go", "गन्तुम्", "gantum"],
        ["To come", "आगन्तुम्", "āgantum"],
        ["To see", "द्रष्टुम्", "draṣṭum"],
        ["To hear", "श्रोतुम्", "śrotum"],
        ["To speak", "वक्तुम्", "vaktum"],
        ["To read", "पठितुम्", "paṭhitum"],
        ["To write", "लिखितुम्", "likhitum"],
        ["To eat", "भोक्तुम्", "bhoktum"],
        ["To drink", "पातुम्", "pātum"],
        ["To sleep", "स्वपितुम्", "svapitum"],
        ["To sit", "उपविष्टुम्", "upaviṣṭum"],
        ["To stand", "स्थातुम्", "sthātum"],
        ["To give", "दातुम्", "dātum"],
        ["To take", "ग्रहीतुम्", "grahītum"],
        ["To do", "कर्तुम्", "kartum"],
        ["To know", "ज्ञातुम्", "jñātum"],
    ],
    604: [
        ["To ask", "पृच्छितुम्", "pṛcchitum"],
        ["To answer", "उत्तरितुम्", "uttaritum"],
        ["To help", "साहाय्यं कर्तुम्", "sāhāyyaṃ kartum"],
        ["To wait", "प्रतीक्षितुम्", "pratīkṣitum"],
        ["To buy", "क्रीणातुम्", "krīṇātum"],
        ["To sell", "विक्रीणातुम्", "vikrīṇātum"],
        ["To open", "उद्घाटयितुम्", "udghāṭayitum"],
        ["To close", "पिदधातुम्", "pidadhātum"],
        ["To begin", "आरभ्य", "ārabhya"],
        ["To finish", "समापयितुम्", "samāpayitum"],
        ["To learn", "अधीतुम्", "adhītum"],
        ["To teach", "पाठयितुम्", "pāṭhayitum"],
        ["To run", "धावितुम्", "dhāvitum"],
        ["To walk", "चरितुम्", "caritum"],
        ["To laugh", "हसितुम्", "hasitum"],
        ["To cry", "रोदितुम्", "roditum"],
    ],
    605: [
        ["To love", "स्नेहं कर्तुम्", "snehaṃ kartum"],
        ["To hate", "द्वेष्टुम्", "dveṣṭum"],
        ["To like", "रुच्", "ruc"],
        ["To think", "चिन्तयितुम्", "cintayitum"],
        ["To feel", "अनुभवितुम्", "anubhavitum"],
        ["To remember", "स्मरितुम्", "smaritum"],
        ["To forget", "विस्मरितुम्", "vismaritum"],
        ["To understand", "अवगन्तुम्", "avagantum"],
        ["To explain", "व्याख्यातुम्", "vyākhyātum"],
        ["To choose", "वृणीतुम्", "vṛṇītum"],
        ["To send", "प्रेषयितुम्", "preṣayitum"],
        ["To receive", "प्राप्नु", "prāpnu"],
        ["To pay", "दातुम् (दानम्)", "dātum"],
        ["To win", "जेतुम्", "jetum"],
        ["To lose", "हारयितुम्", "hārayitum"],
        ["To try", "यत्नं कर्तुम्", "yatnaṃ kartum"],
    ],
    606: [
        ["To build", "निर्मातुम्", "nirmātum"],
        ["To break", "भञ्जितुम्", "bhañjitum"],
        ["To cut", "छिन्दितुम्", "chinditum"],
        ["To wash", "धावितुम् (धौतुम्)", "dhāvitum"],
        ["To cook", "पचितुम्", "pacitum"],
        ["To clean", "शोधयितुम्", "śodhayitum"],
        ["To sing", "गातुम्", "gātum"],
        ["To dance", "नृत्यितुम्", "nṛtyitum"],
        ["To play", "क्रीडितुम्", "krīḍitum"],
        ["To work", "कार्यं कर्तुम्", "kāryaṃ kartum"],
        ["To rest", "विश्रामं कर्तुम्", "viśrāmaṃ kartum"],
        ["To pray", "प्रार्थयितुम्", "prārthayitum"],
        ["To promise", "प्रतिज्ञातुम्", "pratijñātum"],
        ["To refuse", "निराकर्तुम्", "nirākartum"],
        ["To agree", "सम्मतुम्", "sammatum"],
        ["To disagree", "विरुद्धं भवितुम्", "viruddhaṃ bhavitum"],
    ],
    607: [
        ["करोति — does / makes", "सः कार्यं करोति", "saḥ kāryaṃ karoti"],
        ["करोति — cooks", "सा भोजनं करोति", "sā bhojanaṃ karoti"],
        ["करोति — prepares", "सः सज्जां करोति", "saḥ sajjāṃ karoti"],
        ["करोति — earns", "सः धनं करोति", "saḥ dhanaṃ karoti"],
        ["ददाति — gives", "सः पुस्तकं ददाति", "saḥ pustakaṃ dadāti"],
        ["ददाति — grants", "देवः वरं ददाति", "devaḥ varaṃ dadāti"],
        ["ददाति — pays", "सः मूल्यं ददाति", "saḥ mūlyaṃ dadāti"],
        ["ददाति — offers", "सः नैवेद्यं ददाति", "saḥ naivedyaṃ dadāti"],
        ["भवति — becomes", "सः विद्वान् भवति", "saḥ vidvān bhavati"],
        ["भवति — happens", "घटना भवति", "ghaṭanā bhavati"],
        ["भवति — is (often)", "अयं पुस्तकम् भवति", "ayaṃ pustakam bhavati"],
        ["गच्छति — goes", "सः ग्रामं गच्छति", "saḥ grāmaṃ gacchati"],
        ["गच्छति — moves", "कालः गच्छति", "kālaḥ gacchati"],
        ["गच्छति — fits", "वस्त्रं न गच्छति", "vastraṃ na gacchati"],
        ["पिबति — drinks", "सः जलं पिबति", "saḥ jalaṃ pibati"],
        ["पिबति — absorbs", "वृक्षः जलं पिबति", "vṛkṣaḥ jalaṃ pibati"],
    ],
    608: [
        ["लगति — sticks", "सामग्री लगति", "sāmagrī lagati"],
        ["लगति — begins", "वर्षा लगति", "varṣā lagati"],
        ["लगति — suits", "वस्त्रं लगति", "vastraṃ lagati"],
        ["लगति — costs", "मूल्यं लगति", "mūlyaṃ lagati"],
        ["मिलति — meets", "वयं मिलामः", "vayaṃ milāmaḥ"],
        ["मिलति — matches", "रङ्गः मिलति", "raṅgaḥ milati"],
        ["मिलति — is found", "पुस्तकं मिलति", "pustakaṃ milati"],
        ["मिलति — joins", "द्वारं मिलति", "dvāraṃ milati"],
        ["पतति — falls", "पत्रं पतति", "patraṃ patati"],
        ["पतति — drops", "मूल्यं पतति", "mūlyaṃ patati"],
        ["पतति — sets (sun)", "सूर्यः पतति", "sūryaḥ patati"],
        ["बध्नाति — ties", "सः रज्जुं बध्नाति", "saḥ rajjuṃ badhnāti"],
        ["बध्नाति — fastens", "द्वारं बध्नाति", "dvāraṃ badhnāti"],
        ["बध्नाति — builds", "सेतुं बध्नाति", "setuṃ badhnāti"],
        ["छिनत्ति — cuts", "सः फलं छिनत्ति", "saḥ phalaṃ chinatti"],
        ["छिनत्ति — interrupts", "वाक्यं छिनत्ति", "vākyaṃ chinatti"],
    ],
    609: [
        ["Big", "महान्", "mahān"],
        ["Small", "अल्पः", "alpaḥ"],
        ["Good", "शुभः / साधुः", "śubhaḥ / sādhuḥ"],
        ["Bad", "अशुभः", "aśubhaḥ"],
        ["New", "नवः", "navaḥ"],
        ["Old", "पुराणः", "purāṇaḥ"],
        ["Hot", "उष्णः", "uṣṇaḥ"],
        ["Cold", "शीतलः", "śītalaḥ"],
        ["Heavy", "गुरुः", "guruḥ"],
        ["Light (weight)", "लघुः", "laghuḥ"],
        ["Beautiful", "सुन्दरः", "sundaraḥ"],
        ["Ugly", "विरूपः", "virūpaḥ"],
        ["Clean", "शुचिः", "śuciḥ"],
        ["Dirty", "मलिनः", "malinaḥ"],
        ["Easy", "सुलभः", "sulabhaḥ"],
        ["Difficult", "दुष्करः", "duṣkaraḥ"],
    ],
    610: [
        ["Quickly", "शीघ्रम्", "śīghram"],
        ["Slowly", "शनैः", "śanaiḥ"],
        ["Here", "इह", "iha"],
        ["There", "तत्र", "tatra"],
        ["Where", "कुत्र", "kutra"],
        ["When", "कदा", "kadā"],
        ["How", "कथम्", "katham"],
        ["Why", "कुतः", "kutaḥ"],
        ["Very", "अति", "ati"],
        ["Too much", "अतिशयेन", "atiśayena"],
        ["Little", "अल्पम्", "alpam"],
        ["Much", "बहु", "bahu"],
        ["Again", "पुनः", "punaḥ"],
        ["Once", "एकवारम्", "ekavāram"],
        ["Twice", "द्विवारम्", "dvivāram"],
        ["Together", "सह", "saha"],
    ],
    611: [
        ["Certainly", "निश्चितम्", "niścitam"],
        ["Perhaps", "कदाचित्", "kadācit"],
        ["Never", "न कदापि", "na kadāpi"],
        ["Always", "सदा", "sadā"],
        ["Often", "अनेकशः", "anekaśaḥ"],
        ["Rarely", "दुर्लभतः", "durlabhataḥ"],
        ["Today", "अद्य", "adya"],
        ["Tomorrow", "श्वः", "śvaḥ"],
        ["Yesterday", "ह्यः", "hyaḥ"],
        ["Now", "अधुना", "adhunā"],
        ["Soon", "शीघ्रम्", "śīghram"],
        ["Late", "चिराय", "cirāya"],
        ["Early", "प्रातः", "prātaḥ"],
        ["Inside", "अन्तः", "antaḥ"],
        ["Outside", "बहिः", "bahiḥ"],
        ["Upwards", "ऊर्ध्वम्", "ūrdhvam"],
    ],
    612: [
        ["Potato", "आलुकम्", "ālukam"],
        ["Onion", "पलाण्डुः", "palāṇḍuḥ"],
        ["Tomato", "रक्तफलम्", "raktaphalam"],
        ["Brinjal", "वृन्ताकम्", "vṛntākam"],
        ["Cabbage", "केम्बुकम्", "kembukam"],
        ["Carrot", "कन्दम्", "kandam"],
        ["Cucumber", "त्रपुसम्", "trapusam"],
        ["Pumpkin", "कूष्माण्डम्", "kūṣmāṇḍam"],
        ["Spinach", "पालक्यम्", "pālakyam"],
        ["Peas", "कलायः", "kalāyaḥ"],
        ["Beans", "शिम्बिः", "śimbiḥ"],
        ["Garlic", "लशुनम्", "laśunam"],
        ["Ginger", "शृङ्गवेरम्", "śṛṅgaveram"],
        ["Chilli", "मरिचम्", "maricam"],
        ["Coriander", "धान्यकम्", "dhānyakam"],
        ["Radish", "मूलकम्", "mūlakam"],
    ],
    613: [
        ["Mango", "आम्रम्", "āmram"],
        ["Banana", "कदलीफलम्", "kadalīphalam"],
        ["Apple", "सेवफलम्", "sevaphalam"],
        ["Grapes", "द्राक्षा", "drākṣā"],
        ["Orange", "नारङ्गम्", "nāraṅgam"],
        ["Pomegranate", "दाडिमम्", "dāḍimam"],
        ["Coconut", "नारिकेलम्", "nārikelam"],
        ["Guava", "अमृतफलम्", "amṛtaphalam"],
        ["Papaya", "पपीतकम्", "papītakam"],
        ["Watermelon", "तरङ्गिणी", "taraṅgiṇī"],
        ["Sweet lime", "जम्बीरम्", "jambīram"],
        ["Lemon", "जम्बीरम् (नीबू)", "jambīram"],
        ["Pear", "अमृतफलम्", "amṛtaphalam"],
        ["Plum", "आर्द्राकम्", "ārdrākam"],
        ["Fig", "उदुम्बरम्", "udumbaram"],
        ["Cherry", "प्रच्छेदफलम्", "pracchedaphalam"],
    ],
    614: [
        ["Crow", "काकः", "kākaḥ"],
        ["Parrot", "शुकः", "śukaḥ"],
        ["Peacock", "मयूरः", "mayūraḥ"],
        ["Swan", "हंसः", "haṃsaḥ"],
        ["Sparrow", "चटकः", "caṭakaḥ"],
        ["Pigeon", "कपोतः", "kapotaḥ"],
        ["Eagle", "श्येनः", "śyenaḥ"],
        ["Owl", "उलूकः", "ulūkaḥ"],
        ["Crane", "बकः", "bakaḥ"],
        ["Duck", "कादम्बः", "kādambaḥ"],
        ["Hen", "कुक्कुटी", "kukkuṭī"],
        ["Rooster", "कुक्कुटः", "kukkuṭaḥ"],
        ["Cuckoo", "कोकिलः", "kokilaḥ"],
        ["Woodpecker", "दार्वाघाटः", "dārvāghāṭaḥ"],
        ["Myna", "सारिका", "sārikā"],
        ["Kingfisher", "मीनरङ्कः", "mīnaraṅkaḥ"],
    ],
    615: [
        ["Ant", "पिपीलिका", "pipīlikā"],
        ["Bee", "मधुकरः", "madhukaraḥ"],
        ["Butterfly", "चित्रपतङ्गः", "citrapataṅgaḥ"],
        ["Mosquito", "मशकः", "maśakaḥ"],
        ["Fly", "मक्षिका", "makṣikā"],
        ["Spider", "लूता", "lūtā"],
        ["Worm", "कृमिः", "kṛmiḥ"],
        ["Grasshopper", "पतङ्गः", "pataṅgaḥ"],
        ["Beetle", "गोमयचरः", "gomayacaraḥ"],
        ["Cockroach", "शरटः", "śaraṭaḥ"],
        ["Louse", "यूकः", "yūkaḥ"],
        ["Termite", "दीपिका", "dīpikā"],
        ["Firefly", "खद्योतः", "khadyotaḥ"],
        ["Moth", "शलभः", "śalabhaḥ"],
        ["Leech", "जलौकाः", "jalaukāḥ"],
        ["Scorpion", "वृश्चिकः", "vṛścikaḥ"],
    ],
    616: [
        ["Red", "रक्तवर्णः", "raktavarṇaḥ"],
        ["Blue", "नीलः", "nīlaḥ"],
        ["Green", "हरितः", "haritaḥ"],
        ["Yellow", "पीतः", "pītaḥ"],
        ["White", "शुक्लः", "śuklaḥ"],
        ["Black", "कृष्णः", "kṛṣṇaḥ"],
        ["Brown", "पिङ्गलः", "piṅgalaḥ"],
        ["Orange (colour)", "नारङ्गवर्णः", "nāraṅgavarṇaḥ"],
        ["Pink", "पाटलः", "pāṭalaḥ"],
        ["Grey", "धूसरः", "dhūsaraḥ"],
        ["Golden", "सुवर्णः", "suvarṇaḥ"],
        ["Silver", "रजतवर्णः", "rajatavarṇaḥ"],
        ["Dark", "अन्धकारः", "andhakāraḥ"],
        ["Light (colour)", "प्रकाशः", "prakāśaḥ"],
        ["Bright", "दीप्तः", "dīptaḥ"],
        ["Pale", "विवर्णः", "vivarṇaḥ"],
    ],
    617: [
        ["Lotus", "पद्मम्", "padmam"],
        ["Rose", "शतपत्रम्", "śatapatram"],
        ["Jasmine", "मल्लिका", "mallikā"],
        ["Marigold", "जपापुष्पम्", "japāpuṣpam"],
        ["Sunflower", "सूर्यकान्तिः", "sūryakāntiḥ"],
        ["Hibiscus", "जपापुष्पम्", "japāpuṣpam"],
        ["Champa", "चम्पकः", "campakaḥ"],
        ["Lily", "कुमुदम्", "kumudam"],
        ["Tulip", "कन्दपुष्पम्", "kandapuṣpam"],
        ["Daisy", "श्वेतपुष्पम्", "śvetapuṣpam"],
        ["Oleander", "करवीरः", "karavīraḥ"],
        ["Bougainvillea", "रक्तपुष्पम्", "raktapuṣpam"],
        ["Chrysanthemum", "सेवन्तिका", "sevantikā"],
        ["Violet", "नीलपुष्पम्", "nīlapuṣpam"],
        ["Carnation", "विचित्रपुष्पम्", "vicitrapuṣpam"],
        ["Peony", "पिण्डपुष्पम्", "piṇḍapuṣpam"],
    ],
    618: [
        ["Dog", "शुनकः", "śunakaḥ"],
        ["Cat", "विडालः", "viḍālaḥ"],
        ["Cow", "गौः", "gauḥ"],
        ["Buffalo", "महिषः", "mahiṣaḥ"],
        ["Horse", "अश्वः", "aśvaḥ"],
        ["Elephant", "गजः", "gajaḥ"],
        ["Lion", "सिंहः", "siṃhaḥ"],
        ["Tiger", "व्याघ्रः", "vyāghraḥ"],
        ["Monkey", "वानरः", "vānaraḥ"],
        ["Rabbit", "शशः", "śaśaḥ"],
        ["Deer", "मृगः", "mṛgaḥ"],
        ["Camel", "उष्ट्रः", "uṣṭraḥ"],
        ["Goat", "अजा", "ajā"],
        ["Sheep", "मेषः", "meṣaḥ"],
        ["Donkey", "गर्दभः", "gardabhaḥ"],
        ["Rat", "मूषकः", "mūṣakaḥ"],
    ],
    619: [
        ["Hello / namaste", "नमस्ते", "namaste"],
        ["Thank you", "धन्यवादः", "dhanyavādaḥ"],
        ["Please", "कृपया", "kṛpayā"],
        ["Sorry", "क्षम्यताम्", "kṣamyatām"],
        ["Yes", "आम्", "ām"],
        ["No", "न", "na"],
        ["Good", "शुभम्", "śubham"],
        ["Bad", "अशुभम्", "aśubham"],
        ["Help", "साहाय्यम्", "sāhāyyam"],
        ["Water", "जलम्", "jalam"],
        ["Food", "अन्नम्", "annam"],
        ["House", "गृहम्", "gṛham"],
        ["Road", "मार्गः", "mārgaḥ"],
        ["Money", "धनम्", "dhanam"],
        ["Friend", "मित्रम्", "mitram"],
        ["Work", "कार्यम्", "kāryam"],
        ["Time", "समयः", "samayaḥ"],
        ["Love", "स्नेहः", "snehaḥ"],
    ],
}
