const SINDHI_PHRASES = {
  greetings_1: {
    name: "Greetings Set 1",
    color: "#2B6CB0",
    icon: "👋",
    phrases: [
      { en: "Hello", mr: "سلام", roman: "Salaam", hint: "" },
      { en: "Good morning", mr: "صبح جو سلام", roman: "Subha jo salaam", hint: "" },
      { en: "Good afternoon", mr: "ٻپهر جو سلام", roman: "Bapahir jo salaam", hint: "" },
      { en: "Good evening", mr: "شام جو سلام", roman: "Shaam jo salaam", hint: "" },
      { en: "Good night", mr: "رات جو سلام", roman: "Raat jo salaam", hint: "" },
      { en: "Welcome", mr: "ڀلي ڪري آيا", roman: "Bhali kari aayaa", hint: "" },
      { en: "How are you?", mr: "توهان ڪيئن آهيو؟", roman: "Tawhan kiyan aahiyo?", hint: "" },
      { en: "I am fine", mr: "مان ٺيڪ آهيان", roman: "Maan theek aahiyaan", hint: "" },
      { en: "What is your name?", mr: "توهان جو نالو ڇا آهي؟", roman: "Tawhan jo naalo chhaa aahi?", hint: "" },
      { en: "My name is...", mr: "منهنجو نالو ... آهي", roman: "Muhhinjo naalo ... aahi", hint: "" },
      { en: "Nice to meet you", mr: "توهان سان ملي خوشي ٿيو", roman: "Tawhan saan mili khushi thiyo", hint: "" },
      { en: "Thank you", mr: "مهرباني", roman: "Meherbaani", hint: "" },
      { en: "Please", mr: "مهرباني ڪري", roman: "Meherbaani kari", hint: "" },
      { en: "Sorry", mr: "معاف ڪجو", roman: "Maaf kajo", hint: "" },
      { en: "Goodbye", mr: "الوداع", roman: "Alwidaa", hint: "" },
      { en: "See you", mr: "وري ملنداسين", roman: "Wari milandaasin", hint: "" },
      { en: "Take care", mr: "پنهنجو خيال رکجو", roman: "Panhinjo khiyaal rakhjo", hint: "" },
      { en: "Happy Birthday", mr: "ڄم ڏينهن جون واڌايون", roman: "Janam dinhan joon waadhaayoon", hint: "" },
      { en: "Happy Diwali", mr: "ديوارين جون واڌايون", roman: "Diwaalien joon waadhaayoon", hint: "" },
      { en: "I love you", mr: "مان توهان سان پيار ڪيان ٿو", roman: "Maan tawhan saan pyaar kiyaan tho", hint: "" },
      { en: "Get well soon", mr: "جلدي صحتياب ٿيو", roman: "Jaldi sehatiyaab thiyo", hint: "" },
      { en: "Good day", mr: "سٺو ڏينهن", roman: "Sutho dinhan", hint: "" },
      { en: "How do you do?", mr: "ڪيئن ٿي هلو؟", roman: "Kiyan thi halo?", hint: "" },
      { en: "Pleased to meet you", mr: "ملي خوشي ٿيو", roman: "Mili khushi thiyo", hint: "" },
      { en: "Excuse me", mr: "معاف ڪجو", roman: "Maaf kajo", hint: "" },
      { en: "Congratulations", mr: "واڌايون", roman: "Waadhaayoon", hint: "" },
      { en: "Happy New Year", mr: "نئين سال جون واڌايون", roman: "Naeen saal joon waadhaayoon", hint: "" },
      { en: "Best wishes", mr: "نيڪ خواهشون", roman: "Nek khwaahishoon", hint: "" },
      { en: "Take care of yourself", mr: "پنهنجو خيال رکجو", roman: "Panhinjo khiyaal rakhjo", hint: "" }
    ]
  },
  travel_1: {
    name: "Travel Set 1",
    color: "#E53E3E",
    icon: "✈️",
    phrases: [
      { en: "Where is the bus stop?", mr: "بس اسٽاپ ڪٿي آهي؟", roman: "Bus stop kithe aahi?", hint: "" },
      { en: "I want to go to the station", mr: "مان اسٽيشن وڃڻ چاهيان ٿو", roman: "Maan station wachhan chaahiyaan tho", hint: "" },
      { en: "How much is the ticket?", mr: "ٽڪيٽ جو قيمت ڪيترو آهي؟", roman: "Ticket jo qeemat kitro aahi?", hint: "" },
      { en: "Where is the airport?", mr: "ايئرپورٽ ڪٿي آهي؟", roman: "Airport kithe aahi?", hint: "" },
      { en: "Turn left", mr: "کاٻي طرف مُڙو", roman: "Khaabi taraf muro", hint: "" },
      { en: "Turn right", mr: "ساڄي طرف مُڙو", roman: "Saaji taraf muro", hint: "" },
      { en: "Go straight", mr: "سڌو وڃو", roman: "Sidho wacho", hint: "" },
      { en: "Stop here", mr: "هتي بند ڪريو", roman: "Hite band kariyo", hint: "" },
      { en: "Is this the right way?", mr: "ڇا هيءُ صحيح رستو آهي؟", roman: "Chhaa hiyu sahih rasto aahi?", hint: "" },
      { en: "I am lost", mr: "مان رستو وسري ويس", roman: "Maan rasto wisri wis", hint: "" },
      { en: "Can you help me?", mr: "ڇا توهان منهنجي مدد ڪري سگهو ٿا؟", roman: "Chhaa tawhan muhhinji madad kari sagho thaa?", hint: "" },
      { en: "How far is it?", mr: "اهو ڪيتري پري آهي؟", roman: "Aho kitri pari aahi?", hint: "" },
      { en: "I need a taxi", mr: "مون کي ٽيڪسي گهرجي", roman: "Moon khe taxi ghuruji", hint: "" },
      { en: "Where is the hotel?", mr: "هوٽل ڪٿي آهي؟", roman: "Hotel kithe aahi?", hint: "" },
      { en: "One ticket please", mr: "هڪ ٽڪيٽ ڏيو مهرباني", roman: "Hik ticket diyo meherbaani", hint: "" },
      { en: "When does the train arrive?", mr: "ٽرين ڪڏهن ايندي؟", roman: "Train kadhan aindi?", hint: "" },
      { en: "Where is the market?", mr: "بازار ڪٿي آهي؟", roman: "Bazaar kithe aahi?", hint: "" },
      { en: "Take me there", mr: "مون کي اتي وٺي هلو", roman: "Moon khe ute wuthi halo", hint: "" },
      { en: "I want to buy something", mr: "مان ڪجهه خريد ڪرڻ چاهيان ٿو", roman: "Maan kujh khareed karan chaahiyaan tho", hint: "" },
      { en: "Thank you for your help", mr: "توهان جي مدد لاءِ مهرباني", roman: "Tawhan ji madad laai meherbaani", hint: "" }
    ]
  },
  food_1: {
    name: "Food & Dining Set 1",
    color: "#38A169",
    icon: "🍽️",
    phrases: [
      { en: "I am hungry", mr: "مون کي بک لڳي آهي", roman: "Moon khe bhuk lagi aahi", hint: "" },
      { en: "I am thirsty", mr: "مون کي تمان لڳي آهي", roman: "Moon khe tamaan lagi aahi", hint: "" },
      { en: "Give me water", mr: "مون کي پاڻي ڏيو", roman: "Moon khe paani diyo", hint: "" },
      { en: "The food is delicious", mr: "کاڌو مزيدار آهي", roman: "Khaadho mazidaar aahi", hint: "" },
      { en: "What is this dish?", mr: "هي ڪهڙي ماني آهي؟", roman: "Hee kahri maani aahi?", hint: "" },
      { en: "I want tea", mr: "مون کي چانهه گهرجي", roman: "Moon khe chaanhh ghuruji", hint: "" },
      { en: "I want rice", mr: "مون کي چانور گهرجي", roman: "Moon khe chaanwar ghuruji", hint: "" },
      { en: "Bring the bill", mr: "بل آڻيو", roman: "Bill aaniyo", hint: "" },
      { en: "More food please", mr: "وڌيڪ کاڌو ڏيو مهرباني", roman: "Wadhik khaadho diyo meherbaani", hint: "" },
      { en: "The food is spicy", mr: "کاڌو تيکهو آهي", roman: "Khaadho teekho aahi", hint: "" },
      { en: "I don't eat meat", mr: "مان ماس نٿو کائان", roman: "Maan maas natho khaaiyaan", hint: "" },
      { en: "Give me bread", mr: "مون کي ماني ڏيو", roman: "Moon khe maani diyo", hint: "" },
      { en: "I want milk", mr: "مون کي کير گهرجي", roman: "Moon khe kheer ghuruji", hint: "" },
      { en: "This is sweet", mr: "هي مٺو آهي", roman: "Hee mitho aahi", hint: "" },
      { en: "This is sour", mr: "هي کٽو آهي", roman: "Hee khato aahi", hint: "" },
      { en: "I want fruit", mr: "مون کي ميوو گهرجي", roman: "Moon khe mewo ghuruji", hint: "" },
      { en: "Give me sugar", mr: "مون کي کنڊ ڏيو", roman: "Moon khe khand diyo", hint: "" },
      { en: "The tea is hot", mr: "چانهه گرم آهي", roman: "Chaanhh garam aahi", hint: "" },
      { en: "I like this food", mr: "مون کي هي کاڌو پسند آهي", roman: "Moon khe hee khaadho pasand aahi", hint: "" },
      { en: "Give me salt", mr: "مون کي لوڻ ڏيو", roman: "Moon khe loon diyo", hint: "" }
    ]
  },
  daily_1: {
    name: "Daily Life Set 1",
    color: "#D69E2E",
    icon: "🏠",
    phrases: [
      { en: "What time is it?", mr: "ڪيترا وڳا ٿيا آهن؟", roman: "Kitraa waga thiyaa aahan?", hint: "" },
      { en: "Where do you live?", mr: "توهان ڪٿي رهو ٿا؟", roman: "Tawhan kithe raho thaa?", hint: "" },
      { en: "I live in India", mr: "مان هندستان ۾ رهان ٿو", roman: "Maan Hindustan me rahaan tho", hint: "" },
      { en: "What do you do?", mr: "توهان ڇا ڪريو ٿا؟", roman: "Tawhan chhaa kariyo thaa?", hint: "" },
      { en: "I am a student", mr: "مان شاگرد آهيان", roman: "Maan shaagird aahiyaan", hint: "" },
      { en: "I am a teacher", mr: "مان استاد آهيان", roman: "Maan ustaad aahiyaan", hint: "" },
      { en: "Today is Monday", mr: "اڄ سومر آهي", roman: "Aaj somar aahi", hint: "" },
      { en: "What is the date today?", mr: "اڄ ڪهڙي تاريخ آهي؟", roman: "Aaj kahri taarikh aahi?", hint: "" },
      { en: "It is raining", mr: "مينهن پئي آهي", roman: "Meenhan paee aahi", hint: "" },
      { en: "It is very hot", mr: "ڏاڍي گرمي آهي", roman: "Ddaadhi garmi aahi", hint: "" },
      { en: "It is cold", mr: "ٿڌ آهي", roman: "Thadh aahi", hint: "" },
      { en: "I have to go", mr: "مون کي وڃڻو آهي", roman: "Moon khe wachano aahi", hint: "" },
      { en: "Come here", mr: "هتي اچو", roman: "Hite acho", hint: "" },
      { en: "Sit down", mr: "ويهي رهو", roman: "Wehi raho", hint: "" },
      { en: "Stand up", mr: "بيٺا ٿيو", roman: "Bethaa thiyo", hint: "" },
      { en: "Open the door", mr: "دروازو کوليو", roman: "Darwazo kholiyo", hint: "" },
      { en: "Close the window", mr: "دري بند ڪريو", roman: "Dari band kariyo", hint: "" },
      { en: "I am going home", mr: "مان گهر وڃان ٿو", roman: "Maan ghar wachaan tho", hint: "" },
      { en: "Call me tomorrow", mr: "سڀاڻي مون کي فون ڪريو", roman: "Sabhaani moon khe phone kariyo", hint: "" },
      { en: "I will come back", mr: "مان واپس ايندس", roman: "Maan waapas aindas", hint: "" }
    ]
  },
  shopping_1: {
    name: "Shopping Set 1",
    color: "#805AD5",
    icon: "🛒",
    phrases: [
      { en: "How much does this cost?", mr: "هن جي قيمت ڪيتري آهي؟", roman: "Han ji qeemat kitri aahi?", hint: "" },
      { en: "It is too expensive", mr: "هيءُ ڏاڍو مهانگو آهي", roman: "Hiyu ddaadho mahaango aahi", hint: "" },
      { en: "Give me a discount", mr: "مون کي ڪجهه گهٽ ڪريو", roman: "Moon khe kujh ghat kariyo", hint: "" },
      { en: "I want to buy this", mr: "مان هي خريد ڪرڻ چاهيان ٿو", roman: "Maan hee khareed karan chaahiyaan tho", hint: "" },
      { en: "Show me that", mr: "مون کي اهو ڏيکاريو", roman: "Moon khe aho dikhariyo", hint: "" },
      { en: "Do you have this in another color?", mr: "ڇا هن ٻئي رنگ ۾ آهي؟", roman: "Chhaa han bee rang me aahi?", hint: "" },
      { en: "Where is the shop?", mr: "دڪان ڪٿي آهي؟", roman: "Dukaan kithe aahi?", hint: "" },
      { en: "I am just looking", mr: "مان فقط ڏسان ٿو", roman: "Maan faqat disaan tho", hint: "" },
      { en: "This is very nice", mr: "هيءُ ڏاڍو سٺو آهي", roman: "Hiyu ddaadho sutho aahi", hint: "" },
      { en: "I don't want this", mr: "مون کي هيءُ نه گهرجي", roman: "Moon khe hiyu na ghuruji", hint: "" },
      { en: "Pack this for me", mr: "هي مون لاءِ ڀاڙي ڏيو", roman: "Hee moon laai bhaari diyo", hint: "" },
      { en: "Do you accept cards?", mr: "ڇا توهان ڪارڊ وٺو ٿا؟", roman: "Chhaa tawhan card wutho thaa?", hint: "" },
      { en: "Give me the receipt", mr: "مون کي رسيد ڏيو", roman: "Moon khe raseed diyo", hint: "" },
      { en: "Is this fresh?", mr: "ڇا هيءُ تازو آهي؟", roman: "Chhaa hiyu taazo aahi?", hint: "" },
      { en: "I need a bag", mr: "مون کي ٿيلهو گهرجي", roman: "Moon khe thailho ghuruji", hint: "" },
      { en: "The market is crowded", mr: "بازار ۾ ڪافي ڀيڙ آهي", roman: "Bazaar me kaafi bhir aahi", hint: "" },
      { en: "I will pay cash", mr: "مان نقد ڏيندس", roman: "Maan naqad dindas", hint: "" },
      { en: "What is the final price?", mr: "آخري قيمت ڇا آهي؟", roman: "Aakhri qeemat chhaa aahi?", hint: "" },
      { en: "I bought vegetables", mr: "مان ڀاڄيون خريد ڪيون", roman: "Maan bhaajiyoon khareed kiyoon", hint: "" },
      { en: "The quality is good", mr: "معيار سٺو آهي", roman: "Miyaar sutho aahi", hint: "" }
    ]
  },
  emergency_1: {
    name: "Emergency & Health Set 1",
    color: "#E53E3E",
    icon: "🏥",
    phrases: [
      { en: "Help!", mr: "مدد!", roman: "Madad!", hint: "" },
      { en: "Call the police", mr: "پوليس کي سڏيو", roman: "Police khe sadiyo", hint: "" },
      { en: "Call an ambulance", mr: "ايمبولينس سڏيو", roman: "Ambulance sadiyo", hint: "" },
      { en: "I am sick", mr: "مان بيمار آهيان", roman: "Maan beemaar aahiyaan", hint: "" },
      { en: "I need a doctor", mr: "مون کي ڊاڪٽر گهرجي", roman: "Moon khe doctor ghuruji", hint: "" },
      { en: "Where is the hospital?", mr: "اسپتال ڪٿي آهي؟", roman: "Aspataal kithe aahi?", hint: "" },
      { en: "I have a headache", mr: "منهنجو مٿو ڏکي ٿو", roman: "Muhhinjo matho dukhi tho", hint: "" },
      { en: "I have a fever", mr: "مون کي بخار آهي", roman: "Moon khe bukhaar aahi", hint: "" },
      { en: "My stomach hurts", mr: "منهنجو پيٽ ڏکي ٿو", roman: "Muhhinjo pet dukhi tho", hint: "" },
      { en: "I need medicine", mr: "مون کي دوا گهرجي", roman: "Moon khe dawaa ghuruji", hint: "" },
      { en: "Where is the pharmacy?", mr: "دواخانو ڪٿي آهي؟", roman: "Dawakhaano kithe aahi?", hint: "" },
      { en: "I am allergic", mr: "مون کي الرجي آهي", roman: "Moon khe allergy aahi", hint: "" },
      { en: "Call the fire brigade", mr: "فائر بريگيڊ کي سڏيو", roman: "Fire brigade khe sadiyo", hint: "" },
      { en: "There is an emergency", mr: "ايمرجنسي آهي", roman: "Emergency aahi", hint: "" },
      { en: "I feel dizzy", mr: "مون کي چڪر اچن ٿا", roman: "Moon khe chakar achan thaa", hint: "" },
      { en: "I cannot breathe", mr: "مان ساهه نٿو کڻي سگهان", roman: "Maan saah natho khini saghaan", hint: "" },
      { en: "I need help", mr: "مون کي مدد گهرجي", roman: "Moon khe madad ghuruji", hint: "" },
      { en: "It is an accident", mr: "حادثو ٿيو آهي", roman: "Haadso thiyo aahi", hint: "" },
      { en: "I am injured", mr: "مان زخمي آهيان", roman: "Maan zakhmi aahiyaan", hint: "" },
      { en: "Take me to the hospital", mr: "مون کي اسپتال وٺي هلو", roman: "Moon khe aspataal wuthi halo", hint: "" }
    ]
  }
};

const SINDHI_DICTIONARY = [
  { en: "Water", mr: "پاڻي", roman: "Paani" },
  { en: "Food", mr: "کاڌو", roman: "Khaadho" },
  { en: "House", mr: "گهر", roman: "Ghar" },
  { en: "Mother", mr: "ماءُ", roman: "Maau" },
  { en: "Father", mr: "پيءُ", roman: "Piyu" },
  { en: "Brother", mr: "ڀاءُ", roman: "Bhaau" },
  { en: "Sister", mr: "ڀيڻ", roman: "Bhain" },
  { en: "Child", mr: "ٻار", roman: "Baar" },
  { en: "Friend", mr: "دوست", roman: "Dost" },
  { en: "Teacher", mr: "استاد", roman: "Ustaad" },
  { en: "Student", mr: "شاگرد", roman: "Shaagird" },
  { en: "Book", mr: "ڪتاب", roman: "Kitaab" },
  { en: "School", mr: "اسڪول", roman: "School" },
  { en: "Sun", mr: "سج", roman: "Suju" },
  { en: "Moon", mr: "چنڊ", roman: "Chand" },
  { en: "Star", mr: "تارو", roman: "Taaro" },
  { en: "Tree", mr: "وڻ", roman: "Wann" },
  { en: "Flower", mr: "گل", roman: "Gul" },
  { en: "Earth", mr: "ڌرتي", roman: "Dharti" },
  { en: "Sky", mr: "آسمان", roman: "Aasmaan" },
  { en: "River", mr: "ندي", roman: "Nadi" },
  { en: "Mountain", mr: "جبل", roman: "Jabal" },
  { en: "Sea", mr: "سمنڊ", roman: "Samundar" },
  { en: "Rain", mr: "مينهن", roman: "Meenhan" },
  { en: "Wind", mr: "واءُ", roman: "Waau" },
  { en: "Fire", mr: "باهه", roman: "Baahh" },
  { en: "Day", mr: "ڏينهن", roman: "Dinhan" },
  { en: "Night", mr: "رات", roman: "Raat" },
  { en: "Morning", mr: "صبح", roman: "Subha" },
  { en: "Evening", mr: "شام", roman: "Shaam" },
  { en: "Today", mr: "اڄ", roman: "Aaj" },
  { en: "Tomorrow", mr: "سڀاڻي", roman: "Sabhaani" },
  { en: "Yesterday", mr: "ڪالهه", roman: "Kaalh" },
  { en: "One", mr: "هڪ", roman: "Hik" },
  { en: "Two", mr: "ٻه", roman: "Ba" },
  { en: "Three", mr: "ٽي", roman: "Tee" },
  { en: "Four", mr: "چار", roman: "Chaar" },
  { en: "Five", mr: "پنج", roman: "Panj" },
  { en: "Ten", mr: "ڏهه", roman: "Dah" },
  { en: "Hundred", mr: "سو", roman: "So" },
  { en: "Man", mr: "ماڻهو", roman: "Maanho" },
  { en: "Woman", mr: "عورت", roman: "Aurat" },
  { en: "Boy", mr: "ڇوڪرو", roman: "Chhokro" },
  { en: "Girl", mr: "ڇوڪري", roman: "Chhokri" },
  { en: "Eye", mr: "اک", roman: "Akh" },
  { en: "Hand", mr: "هٿ", roman: "Hath" },
  { en: "Foot", mr: "پير", roman: "Peer" },
  { en: "Head", mr: "مٿو", roman: "Matho" },
  { en: "Heart", mr: "دل", roman: "Dil" },
  { en: "Road", mr: "رستو", roman: "Rasto" },
  { en: "Car", mr: "ڪار", roman: "Kaar" },
  { en: "Money", mr: "پئسا", roman: "Paisa" },
  { en: "Work", mr: "ڪم", roman: "Kamu" },
  { en: "Time", mr: "وقت", roman: "Waqt" },
  { en: "Village", mr: "ڳوٺ", roman: "Goth" },
  { en: "City", mr: "شهر", roman: "Shahar" },
  { en: "Country", mr: "ملڪ", roman: "Mulk" },
  { en: "King", mr: "بادشاهه", roman: "Baadshaah" },
  { en: "God", mr: "خدا", roman: "Khudaa" },
  { en: "Love", mr: "پيار", roman: "Pyaar" },
  { en: "Life", mr: "زندگي", roman: "Zindagi" },
  { en: "Death", mr: "موت", roman: "Maut" },
  { en: "Milk", mr: "کير", roman: "Kheer" },
  { en: "Bread", mr: "ماني", roman: "Maani" },
  { en: "Rice", mr: "چانور", roman: "Chaanwar" },
  { en: "Fish", mr: "مڇي", roman: "Machhi" },
  { en: "Meat", mr: "ماس", roman: "Maas" },
  { en: "Salt", mr: "لوڻ", roman: "Loon" },
  { en: "Sugar", mr: "کنڊ", roman: "Khand" },
  { en: "Oil", mr: "تيل", roman: "Tel" },
  { en: "Color", mr: "رنگ", roman: "Rang" },
  { en: "Red", mr: "ڳاڙهو", roman: "Garrho" },
  { en: "Blue", mr: "نيرو", roman: "Neero" },
  { en: "Green", mr: "سائو", roman: "Saao" },
  { en: "White", mr: "اڇو", roman: "Achho" },
  { en: "Black", mr: "ڪارو", roman: "Kaaro" },
  { en: "Big", mr: "وڏو", roman: "Waddo" },
  { en: "Small", mr: "ننڍو", roman: "Nandho" },
  { en: "Good", mr: "سٺو", roman: "Sutho" },
  { en: "Bad", mr: "خراب", roman: "Kharaab" },
  { en: "New", mr: "نئون", roman: "Naon" },
  { en: "Old", mr: "پراڻو", roman: "Paraano" },
  { en: "True", mr: "سچ", roman: "Sach" },
  { en: "False", mr: "ڪُوڙ", roman: "Koorr" },
  { en: "Happy", mr: "خوش", roman: "Khush" },
  { en: "Sad", mr: "اداس", roman: "Udaas" },
  { en: "Come", mr: "اچو", roman: "Acho" },
  { en: "Go", mr: "وڃو", roman: "Wacho" },
  { en: "Eat", mr: "کائو", roman: "Khaaio" },
  { en: "Drink", mr: "پيو", roman: "Piyo" },
  { en: "Sit", mr: "ويهو", roman: "Weiho" },
  { en: "Sleep", mr: "سمهو", roman: "Sumho" },
  { en: "Walk", mr: "هلو", roman: "Halo" },
  { en: "Run", mr: "ڊوڙو", roman: "Ddoro" },
  { en: "Read", mr: "پڙهو", roman: "Parho" },
  { en: "Write", mr: "لکو", roman: "Likho" },
  { en: "Speak", mr: "ڳالهايو", roman: "Gaalhaaio" },
  { en: "Listen", mr: "ٻُڌو", roman: "Budho" },
  { en: "See", mr: "ڏسو", roman: "Diso" },
  { en: "Give", mr: "ڏيو", roman: "Diyo" },
  { en: "Take", mr: "وٺو", roman: "Wutho" }
];
