# Urdu Lesson 5 — Conversation practice chunk B (chapter IDs 642–662).

LESSONS_S5B = {
    642: [
        ["I want to open an account", "میں اکاؤنٹ کھولنا چاہتا ہوں", "main account kholna chahta hoon"],
        ["Please fill this form", "براہِ کرم یہ فارم بھریں", "baraahe karam yeh form bharein"],
        ["I need a cheque book", "مجھے چیک بک چاہیے", "mujhe cheque book chahiye"],
        ["What is the minimum balance?", "کم از کم بیلنس کیا ہے؟", "kam az kam balance kya hai?"],
        ["I want to deposit cash", "میں نقد جمع کرانا چاہتا ہوں", "main naqd jama karaana chahta hoon"],
        ["Please count the notes", "نوٹ گن لیجیے", "note gin lijiye"],
        ["I forgot my PIN", "میرا پن بھول گیا", "mera PIN bhool gaya"],
        ["Block my card", "کارڈ بلاک کر دیں", "card block kar dein"],
        ["Transfer to this account", "اس اکاؤنٹ میں ٹرانسفر", "is account mein transfer"],
        ["Service charges?", "سروس چارجز؟", "service charges?"],
        ["Home loan enquiry", "ہوم لون کی دریافت", "home loan ki diryaft"],
        ["EMI starts next month", "ای ایم آئ اگلے مہینے", "EMI agle maheene"],
        ["Update mobile number", "موبائل نمبر اپ ڈیٹ", "mobile number update"],
        ["The queue is long", "قطار لمبی ہے", "qataar lambi hai"],
        ["Thank you, good day", "شکریہ، اچھا دن", "shukriya, achchha din"],
    ],
    643: [
        ["What time does the temple open?", "مندر کب کھلتا ہے؟", "mandir kab khulta hai?"],
        ["Is photography allowed?", "فوٹو لینا درست ہے؟", "photo lena durust hai?"],
        ["Where do we keep shoes?", "جوتے کہاں رکھیں؟", "joote kahaan rakhein?"],
        ["Is there prasad today?", "آج پرشاد ہے؟", "aaj prasaad hai?"],
        ["How old is this temple?", "یہ مندر کتنا پرانا ہے؟", "yeh mandir kitna puraana hai?"],
        ["Tell me the history", "تاریخ بتائیں", "taareekh bataiyein"],
        ["Parking nearby?", "قریب پارکنگ؟", "qareeb parking?"],
        ["We came for darshan", "ہم درشن کے لیے آئے", "hum darshan ke liye aaye"],
        ["Evening aarti", "شام کی آرتی", "shaam ki aarti"],
        ["Dress modestly", "سلیقے سے لباس", "saleeqe se libaas"],
        ["Donations box", "دان کا صندوق", "daan ka sandooq"],
        ["Festival crowd", "تہوار کی بھیڑ", "tehwaar ki bheed"],
        ["Guide available?", "گائیڈ دستیاب؟", "guide dastiyaab?"],
        ["Bell three times", "گھنٹی تین بار", "ghanti teen baar"],
        ["Peaceful atmosphere", "پرسکون ماحول", "pur-sukoon maahaul"],
    ],
    644: [
        ["Namaste, uncle and aunty", "نمسکار، چچا چچی", "namaskaar, chacha chachi"],
        ["Thank you for inviting us", "دعوت کا شکریہ", "daawat ka shukriya"],
        ["The food is delicious", "کھانا لذیذ ہے", "khaana lazeez hai"],
        ["Please have more roti", "مزید روٹی لیجیے", "mazeed roti lijiye"],
        ["I'm full; thank you", "پیٹ بھر گیا؛ شکریہ", "peṭ bhar gaya; shukriya"],
        ["Your home is beautiful", "آپ کا گھر خوبصورت ہے", "aap ka ghar khoobsurat hai"],
        ["May I help in the kitchen?", "کیا باورچی خانے میں مدد کروں؟", "kya bawarchi khaane mein madad karoon?"],
        ["The garden is lovely", "باغ پیارا ہے", "baagh pyaara hai"],
        ["We should leave before dark", "اندھیرے سے پہلے چلیں", "andhere se pehle chalein"],
        ["Our parents send regards", "والدین کی طرف سے سلام", "walideen ki taraf se salaam"],
        ["It was a pleasure", "خوشی ہوئی", "khushi hui"],
        ["Next time at our place", "اگلی بار ہمارے یہاں", "agli baar hamare yahaan"],
        ["Drive safely", "محفوظ ڈرائیو", "mehfooz drive"],
        ["Thanks for hospitality", "مہمان نوازی کا شکریہ", "mehmaan nawaazi ka shukriya"],
        ["Good night all", "سب کو شب بخیر", "sab ko shab bakhair"],
    ],
    645: [
        ["Did you watch the match?", "میچ دیکھا؟", "match dekha?"],
        ["What a goal!", "کیا گول!", "kya goal!"],
        ["Offside!", "آف سائڈ!", "offside!"],
        ["Our team played well", "ہماری ٹیم اچھی کھیلی", "hamari team achchi kheli"],
        ["Referee decision", "ریفری کا فیصلہ", "referee ka faisla"],
        ["Penalty shootout", "پینلٹی شوٹ آؤٹ", "penalty shoot-out"],
        ["Extra time", "اضافی وقت", "izaafi waqt"],
        ["Next match on Sunday", "اگلا میچ اتوار کو", "agla match itwaar ko"],
        ["Stadium atmosphere", "اسٹیڈیم کا ماحول", "stadium ka maahaul"],
        ["Favourite player", "پسندیدہ کھلاڑی", "pasandida khilaari"],
        ["Fair play", "منصفانہ کھیل", "munsaafana khel"],
        ["Injury substitution", "انجری سبسٹی ٹیوٹ", "injury substitution"],
        ["We won!", "ہم جیت گئے!", "hum jeet gaye!"],
        ["Hard luck", "بدقسمتی", "badqismati"],
        ["See you at the final", "فائنل میں ملتے ہیں", "final mein milte hain"],
    ],
    646: [
        ["Which movie tonight?", "آج رات کون سی فلم؟", "aaj raat kaun si film?"],
        ["Show timings", "شو کے اوقات", "show ke awqaat"],
        ["Tickets booked online", "ٹکٹ آن لائن بک", "ticket online book"],
        ["Popcorn and cold drink", "پاپ کارن اور کولڈرنک", "popcorn aur cold drink"],
        ["Seat in the middle", "بیچ کی سیٹ", "beech ki seat"],
        ["Subtitles OK?", "سب ٹائٹل؟", "subtitle?"],
        ["Interval in twenty minutes", "انٹرول بیس منٹ میں", "interval bees minute mein"],
        ["The plot was weak", "کہانی کمزور تھی", "kahaani kamzoor thi"],
        ["Great acting", "بہترین اداکاری", "behtareen adaakaari"],
        ["Let's discuss after", "بعد میں بات کرتے ہیں", "baad mein baat karte hain"],
        ["Rating on the app", "ایپ پر ریٹنگ", "app par rating"],
        ["Spoiler alert!", "اسپوائلر!", "spoiler!"],
        ["Sequel coming", "سلسلہ جاری", "silsla jaari"],
        ["Too loud sound", "آواز بہت تیز", "aawaaz bohat tez"],
        ["Home streaming also fine", "گھر پر سٹریمنگ", "ghar par streaming"],
    ],
    647: [
        ["World cup fever!", "ورلڈ کپ کا بخار!", "World Cup ka bukhaar!"],
        ["Which team do you support?", "کس ٹیم کی حمایت؟", "kis team ki himaayat?"],
        ["Group stage match", "گروپ اسٹیج", "group stage"],
        ["Semi-final nerves", "سیمی فائنل کی گھبراہٹ", "semi-final ki ghabraahat"],
        ["Penalty in final", "فائنل میں پینلٹی", "final mein penalty"],
        ["VAR check", "وی اے آر چیک", "VAR check"],
        ["Stadium chant", "اسٹیڈیم نعرہ", "stadium na'ra"],
        ["Fair fans", "منصفانہ شائقین", "munsaafana shaaqeen"],
        ["Match fixed? (rumour)", "فکس تو نہیں؟", "fix to nahin?"],
        ["Injuries list", "انجری لسٹ", "injury list"],
        ["Coach interview", "کوچ کا انٹرویو", "coach ka interview"],
        ["Proud moment for country", "ملک کے لیے فخر", "mulk ke liye fakhr"],
        ["Street celebrations", "گلیوں میں جشن", "galiyon mein jashn"],
        ["Next tournament", "اگلا ٹورنامنٹ", "agla tournament"],
        ["Let's watch together", "ساتھ دیکھتے ہیں", "saath dekhte hain"],
    ],
    648: [
        ["Welcome to Delhi", "دہلی میں خوش آمدید", "Dilli mein khush aamdeed"],
        ["This fort was built…", "یہ قلعہ بنایا گیا…", "yeh qila banaaya gaya…"],
        ["Follow the group", "گروپ کے ساتھ رہیں", "group ke saath rahein"],
        ["Photos allowed here", "یہاں فوٹو درست", "yahaan photo durust"],
        ["Mind your belongings", "سامان سنبھالیں", "samaan sambhaalein"],
        ["Restroom that way", "واش روم اس طرف", "washroom is taraf"],
        ["Souvenir shop", "سوغات کی دکان", "saugaat ki dukaan"],
        ["History in brief", "مختصر تاریخ", "mukhtasar taareekh"],
        ["Any questions?", "کوئی سوال؟", "koi sawaal?"],
        ["Meeting point in ten minutes", "دس منٹ میں ملاقاتی مقام", "das minute mein milaaqaati maqaam"],
        ["Stay hydrated", "پانی پیتے رہیں", "paani peete rahein"],
        ["Wear comfortable shoes", "آرام دہ جوتے", "aaraam deh joote"],
        ["Thank you, guide", "شکریہ، گائیڈ", "shukriya, guide"],
        ["Tip is optional", "ٹپ اختیاری", "tip ikhtiyaari"],
        ["Enjoy your stay", "قیام خوشگوار", "qiyaam khushgawaar"],
    ],
    649: [
        ["Language test for banks", "بینک زبان کا امتحان", "bank zabaan ka imtihaan"],
        ["Read this paragraph", "یہ پیراگراف پڑھیں", "yeh paragraph padhein"],
        ["Answer in Urdu", "اردو میں جواب", "Urdu mein jawaab"],
        ["Formal email sample", "رسمی ای میل نمونہ", "rasmi email namoona"],
        ["Customer scenario", "گاہک کا منظرنامہ", "gaahak ka manzarnaama"],
        ["Time limit twenty minutes", "وقت کی حد بیس منٹ", "waqt ki had bees minute"],
        ["No dictionary", "لغت نہیں", "lughat nahin"],
        ["Clear handwriting", "صاف خط", "saaf khat"],
        ["Review your answers", "جوابات دوبارہ دیکھیں", "jawaabaat dobara dekhein"],
        ["Submit the sheet", "شیٹ جمع کرائیں", "sheet jama karaayein"],
        ["Results by email", "نتیجہ ای میل پر", "nateeja email par"],
        ["Preparation tips", "تیاری کے مشورے", "tiyaari ke mashware"],
        ["Practice past papers", "پرانے پیپر", "puraane paper"],
        ["Stay calm", "پرسکون رہیں", "pur-sukoon rahein"],
        ["Thank you", "شکریہ", "shukriya"],
    ],
    650: [
        ["What's for lunch?", "دوپہر میں کیا ہے؟", "dopehar mein kya hai?"],
        ["I prefer mild spice", "ہلکی مرچ پسند", "halki mirch pasand"],
        ["Vegetarian thali", "سبزی تھالی", "sabzi thaali"],
        ["Order water first", "پہلے پانی", "pehle paani"],
        ["Bill please", "بل لائیں", "bill laayein"],
        ["Split equally", "برابر تقسیم", "baraabar taqseem"],
        ["This dish is salty", "یہ نمکین ہے", "yeh namkeen hai"],
        ["Pack leftovers", "بچا لونا پیک", "bacha khana pack"],
        ["No onion garlic today", "آج بغیر پیاز لہسن", "aaj baghair piyaaz lehsan"],
        ["Dessert after meal", "کھانے کے بعد میٹھا", "khaane ke baad meetha"],
        ["Tip for staff", "ملازم کو ٹپ", "mulaaazim ko tip"],
        ["Hygiene matters", "صفائی اہم", "safaai ahem"],
        ["Food allergy note", "الرجی کی نوٹ", "allergy ki note"],
        ["Thanks for hosting", "مہمان نوازی کا شکریہ", "mehmaan nawaazi ka shukriya"],
        ["Lovely meal", "زبردست کھانا", "zabardast khaana"],
    ],
    651: [
        ["I joined a music class", "میں نے موسیقی کلاس جوائن کی", "main ne mausiqi class join ki"],
        ["Class on Saturdays", "ہفتہ کو کلاس", "hafta ko class"],
        ["Fee per month", "ماہانہ فیس", "maahaana fees"],
        ["Bring your instrument", "اپنا ساز لائیں", "apna saaz laayein"],
        ["Practice fifteen minutes daily", "روز پندرہ منٹ مشق", "roz pandrah minute mashq"],
        ["Teacher's feedback", "استاد کی رائے", "ustaad ki raa'e"],
        ["Missed two classes", "دو کلاس چھوٹ گئیں", "do class chhoot gain"],
        ["I want to learn tabla", "میں تبلہ سیکھنا چاہتا ہوں", "main tablah seekhna chahta hoon"],
        ["Recital next month", "اگلے ماہ ری سائٹل", "agle maah recital"],
        ["Sheet music", "نوتے والی کاپی", "note waali copy"],
        ["Metronome use", "میٹرونوم استعمال", "metronome istemaal"],
        ["Warm up exercises", "گرم مشق", "garm mashq"],
        ["Performance anxiety", "پرفارمنس کی گھبراہٹ", "performance ki ghabraahat"],
        ["Enjoy the process", "عمل سے لطف اٹھائیں", "amal se lutf uthaayein"],
        ["Thank you, teacher", "شکریہ، استاد", "shukriya, ustaad"],
    ],
    652: [
        ["Please wait a moment", "ذرا انتظار کریں", "zara intizaar karein"],
        ["I don't understand", "مجھے سمجھ نہیں آیا", "mujhe samajh nahin aaya"],
        ["Can you repeat?", "دہرائیں گے؟", "dohraayeinge?"],
        ["Speak slowly", "آہستہ بولیں", "aahista bolein"],
        ["How much is this?", "یہ کتنے کا ہے؟", "yeh kitne ka hai?"],
        ["Where is the exit?", "باہر نکلنے کا راستہ؟", "baahar nikalne ka raasta?"],
        ["I need help", "مدد چاہیے", "madad chahiye"],
        ["Call the police", "پولیس کو بلائیں", "police ko bulaayein"],
        ["I'm lost", "راستہ بھول گیا", "raasta bhool gaya"],
        ["Emergency!", "ایمرجنسی!", "emergency!"],
        ["Water please", "پانی دیجیے", "paani dijiye"],
        ["No problem", "کوئی بات نہیں", "koi baat nahin"],
        ["See you", "ملتے ہیں", "milte hain"],
        ["Congratulations", "مبارک ہو", "mubaarak ho"],
        ["Good luck", "نصیب اچھا", "naseeb achchha"],
    ],
    653: [
        ["As soon as possible", "جتنا جلد ممکن", "jitna jald mumkin"],
        ["By the way", "ویسے", "waise"],
        ["Actually…", "دراصل…", "darasl…"],
        ["I mean…", "میرا مطلب…", "mera matlab…"],
        ["Let me think", "سوچنے دیں", "sochne dein"],
        ["Sounds good", "اچھا لگا", "achchha laga"],
        ["I'm not sure", "یقین نہیں", "yaqeen nahin"],
        ["Probably", "شاید", "shayad"],
        ["Definitely", "یقینی طور پر", "yaqeeni tor par"],
        ["Maybe later", "شاید بعد میں", "shayad baad mein"],
        ["Right now", "ابھی", "abhi"],
        ["Same here", "یہیں", "yahin"],
        ["Never mind", "کوئی بات نہیں", "koi baat nahin"],
        ["Take care", "خیال رکھیں", "khayaal rakhein"],
        ["God willing", "ان شاء اللہ", "in shaa Allah"],
    ],
    654: [
        ["Learn by speaking", "بول کر سیکھیں", "bol kar seekhein"],
        ["Don't fear mistakes", "غلطی سے نہ ڈریں", "ghalti se na darein"],
        ["Listen to audio daily", "روزانہ آڈیو سنیں", "rozaana audio sunein"],
        ["Write a diary in Urdu", "اردو میں ڈائری", "Urdu mein diary"],
        ["Find a language partner", "زبان ساتھی تلاش", "zabaan saathi talaash"],
        ["Label objects at home", "گھر پر لیبل", "ghar par label"],
        ["Watch Urdu dramas", "اردو ڈرامے", "Urdu drama"],
        ["Read simple news", "آسان خبریں", "asaan khabrein"],
        ["Record your voice", "آواز ریکارڈ", "aawaaz record"],
        ["Celebrate small wins", "چھوٹی کامیابیاں", "chhoti kaamyaabiyaan"],
        ["Stay consistent", "مسلسل رہیں", "musalsal rahein"],
        ["Ask 'why' in Urdu", "اردو میں کیوں پوچھیں", "Urdu mein kyun poochhein"],
        ["Immerse in culture", "ثقافت میں", "saqaafat mein"],
        ["Review weekly", "ہفتہ وار دہرائیں", "haftawaar dohraayein"],
        ["Enjoy the journey", "سفر سے لطف", "safar se lutf"],
    ],
    655: [
        ["I wake up early", "میں جلدی اٹھتا ہوں", "main jaldi uthta hoon"],
        ["I brush my teeth", "دانت صاف کرتا ہوں", "daant saaf karta hoon"],
        ["I have breakfast", "ناشتہ کرتا ہوں", "nashta karta hoon"],
        ["I go to work", "کام پر جاتا ہوں", "kaam par jaata hoon"],
        ["I return in the evening", "شام کو واپس آتا ہوں", "shaam ko waapas aata hoon"],
        ["I read before sleep", "سونے سے پہلے پڑھتا ہوں", "sone se pehle padhta hoon"],
        ["Weekend I rest", "ہفتہ وار آرام", "haftawaar aaraam"],
        ["I call my parents", "والدین کو فون", "walideen ko phone"],
        ["I pay bills online", "بل آن لائن", "bill online"],
        ["I exercise sometimes", "کبھی ورزش", "kabhi warzish"],
        ["I cook on Sundays", "اتوار کو پکاتا ہوں", "itwaar ko pakaata hoon"],
        ["I help at home", "گھر میں مدد", "ghar mein madad"],
        ["I plan the week", "ہفتہ منصوبہ", "hafta mansooba"],
        ["I sleep by eleven", "گیارہ بجے تک سو جاتا ہوں", "gyaarah baje tak so jaata hoon"],
        ["That's my routine", "یہ میرا معمول ہے", "yeh mera maamool hai"],
    ],
    656: [
        ["The book is on the table", "کتاب میز پر ہے", "kitaab mez par hai"],
        ["The keys are in the bag", "چابی بیگ میں ہے", "chaabi bag mein hai"],
        ["He came from Mumbai", "ممبئی سے آیا", "Mumbai se aaya"],
        ["She went to school", "اسکول گئی", "school gayi"],
        ["We walked through the park", "پارک سے گزرے", "park se guzre"],
        ["Sit beside me", "میرے پاس بیٹھو", "mere paas baitho"],
        ["Wait under the tree", "درخت کے نیچے انتظار", "darakht ke neeche intizaar"],
        ["The shop is near the bank", "دکان بینک کے قریب", "dukaan bank ke qareeb"],
        ["Without you I can't", "تمہارے بغیر نہیں", "tumhare baghair nahin"],
        ["Until tomorrow", "کل تک", "kal tak"],
        ["Since Monday", "پیر سے", "Peer se"],
        ["During the meeting", "میٹنگ کے دوران", "meeting ke dauraan"],
        ["Among friends", "دوستوں میں", "doston mein"],
        ["Against the wall", "دیوار کے سامنے", "deewaar ke saamne"],
        ["Practice makes perfect", "مشق کامل بناتی ہے", "mashq kaamil banaati hai"],
    ],
    657: [
        ["Teacher: Why are you late?", "استاد: دیر کیوں؟", "ustaad: der kyun?"],
        ["Student: Bus missed", "طالب علم: بس چھوٹ گئی", "taalib ilm: bus chhoot gayi"],
        ["Teacher: Sit down", "استاد: بیٹھ جاؤ", "ustaad: baith jao"],
        ["Student: Sorry", "طالب علم: معاف", "taalib ilm: maaf"],
        ["Punchline: Actually…", "اصل بات…", "asl baat…"],
        ["Friend: Listen…", "دوست: سنو…", "dost: suno…"],
        ["Wordplay on مچھلی", "لفظی کھیل", "lafzi khel"],
        ["Doctor joke setup", "ڈاکٹر لطیفہ", "doctor lateefa"],
        ["Keep it kind", "مہربان مزاح", "meherbaan mazaah"],
        ["Cultural context", "سیاق ثقافتی", "siyaq saqaafi"],
        ["Don't mock people", "لوگوں کا مذاق نہ", "logon ka mazaaq na"],
        ["Share a smile", "مسکراہٹ بانٹیں", "muskuraahat baantein"],
        ["Short and sweet", "مختصر اور میٹھا", "mukhtasar aur meetha"],
        ["Audience laughs", "حاضرین ہنستے ہیں", "haazireen hanste hain"],
        ["End with shukriya", "آخر میں شکریہ", "aakhir mein shukriya"],
    ],
    658: [
        ["A thought for the day: work honestly", "آج کی سوچ: ایمانداری سے کام", "aaj ki soch: imaandaari se kaam"],
        ["Small steps bring big change", "چھوٹے قدم بڑی تبدیلی", "chhote qadam baṛi tabdeeli"],
        ["Kind words cost nothing", "نرم الفاظ مفت", "narm alfaaz muft"],
        ["Read one page before sleep", "سونے سے پہلے ایک صفحہ", "sone se pehle ek safha"],
        ["Share a joke with a friend", "دوست سے لطیفہ", "dost se lateefa"],
        ["Quote: unity is strength", "اتحاد طاقت", "ittehaad taaqat"],
        ["Smile at strangers", "اجنبی پر مسکراہٹ", "ajnabi par muskuraahat"],
        ["Help someone quietly today", "آج خاموشی سے مدد", "aaj khaamoshi se madad"],
        ["Write three new words", "تین نئے الفاظ لکھیں", "teen naye alfaaz likhein"],
        ["Listen to a short story", "مختصر کہانی سنیں", "mukhtasar kahaani sunein"],
        ["Repeat a proverb aloud", "کہاوت زور سے", "kahawat zor se"],
        ["Note one good habit", "ایک اچھی عادت نوٹ", "ek achchi aadat note"],
        ["Avoid one bad habit today", "آج ایک بری عادت چھوڑیں", "aaj ek buri aadat chhorein"],
        ["Thank three people mentally", "تین لوگوں کا شکریہ دل سے", "teen logon ka shukriya dil se"],
        ["Sleep with a calm mind", "پرسکون ذہن سے سوئیں", "pur-sukoon zehn se soein"],
        ["Tomorrow read again", "کل پھر پڑھیں", "kal phir padhein"],
    ],
    659: [
        ["I spend less time online now", "اب آن لائن کم وقت", "ab online kam waqt"],
        ["Social media can distract", "سوشل میڈیا بٹکا سکتا ہے", "social media bhatka sakta hai"],
        ["I follow news pages", "خبریں فالو", "khabrein follow"],
        ["Too many notifications", "بہت نوٹیفیکیشن", "bohat notification"],
        ["I mute groups at night", "رات گروپ میوٹ", "raat group mute"],
        ["Video calls with relatives", "رشتہ داروں سے ویڈیو کال", "rishta daron se video call"],
        ["I learn Urdu from short reels", "مختصر ریلز سے اردو", "mukhtasar reels se Urdu"],
        ["Cyber safety is important", "سائبر حفاظت ضروری", "cyber hifaazat zaroori"],
        ["Don't share OTP publicly", "او ٹی پی عام نہ", "OTP aam na"],
        ["Take breaks from the screen", "اسکرین سے وقفہ", "screen se waqfa"],
        ["Real friends meet offline", "اصلی دوست آف لائن", "asli dost offline"],
        ["I deleted unused apps", "غیر استعمال ایپ ڈیلیٹ", "ghair istemaal app delete"],
        ["Good posts spread positivity", "اچھی پوسٹ مثبت", "achchi post musbat"],
        ["Limit scrolling before sleep", "سونے سے پہلے سکرول کم", "sone se pehle scroll kam"],
        ["Balance screen and family", "اسکرین اور خاندان", "screen aur khaandaan"],
        ["Digital discipline helps studies", "ڈیجیٹل نظام پڑھائی میں", "digital nizaam padhaai mein"],
    ],
    660: [
        ["Today there is a solar eclipse", "آج سورج گرہن ہے", "aaj sooraj grahan hai"],
        ["Do not look at the sun directly", "سورج سیدھا نہ دیکھیں", "sooraj seedha na dekhein"],
        ["Use certified glasses", "تصدیق شدہ چشمے", "tasdeeq shuda chashme"],
        ["Children should be supervised", "بچوں کی نگرانی", "bachchon ki nigraani"],
        ["Myth: food turns poisonous — false", "غلط فہمی: کھانا زہر — غلط", "ghalat fehmi: khaana zehar — ghalat"],
        ["Temples may have special prayers", "مندروں میں خاص پوجا", "mandiron mein khaas pooja"],
        ["Scientists explain the eclipse", "سائنسدان گرہن سمجھاتے", "sciencedaan grahan samjhaate"],
        ["The sky becomes dim", "آسمان مدھم", "aasamaan madham"],
        ["Birds return to nests", "پرندے گھونسلوں میں", "parinde ghonslon mein"],
        ["Temperature may drop slightly", "درجہ حرارت تھوڑا گھٹ", "darja haraarat thoda ghat"],
        ["Photograph with proper filter", "مناسب فلٹر سے فوٹو", "munaasib filter se photo"],
        ["After eclipse, normal routine", "گرہن کے بعد معمول", "grahan ke baad maamool"],
        ["Share correct information online", "درست معلومات آن لائن", "durust maaloomaat online"],
        ["Children ask many questions", "بچے بہت سوالات", "bachche bohat sawaalat"],
        ["Nature is amazing", "فطرت حیرت انگیز", "fitrat hairat angez"],
        ["Let's watch the next eclipse safely", "اگلا گرہن محفوظ دیکھیں", "agla grahan mehfooz dekhein"],
    ],
    661: [
        ["Happy Women's Day!", "خواتین کا دن مبارک!", "khawaateen ka din mubaarak!"],
        ["We honour women's contributions", "خواتین کے تعاون کا احترام", "khawaateen ke ta'aawun ka ihtiraam"],
        ["Equal opportunity for all", "سب کے لیے برابر موقع", "sab ke liye baraabar mauqa"],
        ["Education empowers girls", "تعلیم لڑکیوں کو طاقت دیتی", "ta'leem larkiyon ko taaqat deti"],
        ["Respect at home and work", "گھر اور کام پر احترام", "ghar aur kaam par ihtiraam"],
        ["Say no to discrimination", "امتیاز سے انکار", "imtiyaaz se inkaar"],
        ["Mothers shape society", "ماں معاشرہ بناتی ہیں", "maa muashra banaati hain"],
        ["Sisters deserve support", "بہنوں کی حمایت", "behenon ki himaayat"],
        ["Women lead in every field", "ہر شعبے میں خواتین", "har shobay mein khawaateen"],
        ["Safety is everyone's duty", "حفاظت سب کی ذمہ داری", "hifaazat sab ki zimmedaari"],
        ["Celebrate achievements loudly", "کامیابیاں زور سے منائیں", "kaamyaabiyaan zor se manaayein"],
        ["Listen to women's voices", "خواتین کی آواز سنیں", "khawaateen ki aawaaz sunein"],
        ["Share household work fairly", "گھر کا کام برابر", "ghar ka kaam baraabar"],
        ["Healthcare access for all", "سب کے لیے صحت کی سہولت", "sab ke liye sehat ki sahoolat"],
        ["Together we build equality", "مل کر برابری", "mil kar baraabari"],
        ["Proud of the women in my life", "اپنی زندگی کی خواتین پر فخر", "apni zindagi ki khawaateen par fakhr"],
    ],
    662: [
        ["Why didn't you clean the room?", "کمرہ صاف کیوں نہیں کیا؟", "kamra saaf kyun nahin kiya?"],
        ["I was tired after office", "آفس کے بعد تھک گیا", "office ke baad thak gaya"],
        ["That is not an excuse", "یہ بہانہ نہیں", "yeh bahaana nahin"],
        ["The guests are coming tomorrow", "کل مہمان آ رہے ہیں", "kal mehmaan aa rahe hain"],
        ["Please understand my workload", "میرے کام کا بوجھ سمجھیں", "mere kaam ka bojh samjhein"],
        ["Lower your voice", "آواز نیچی کریں", "aawaaz neechi karein"],
        ["I am not arguing for fun", "میں مذاق میں بحث نہیں", "main mazaaq mein behas nahin"],
        ["Let's solve this calmly", "پرسکوتی سے حل کریں", "pur-skooni se hal karein"],
        ["Sorry, I spoke harshly", "معاف، سخت بولا", "maaf, sakht bola"],
        ["We are a family; we adjust", "ہم خاندان ہیں؛ ڈھل جاتے ہیں", "hum khaandaan hain; dhal jaate hain"],
        ["Divide chores fairly", "کام برابر بانٹیں", "kaam baraabar baantein"],
        ["Children are listening", "بچے سن رہے ہیں", "bachche sun rahe hain"],
        ["Let's talk after dinner", "کھانے کے بعد بات", "khaane ke baad baat"],
        ["I need respect too", "مجھے بھی احترام چاہیے", "mujhe bhi ihtiraam chahiye"],
        ["Hug and make peace", "گلے لگ کر صلح", "gale lag kar sulah"],
        ["Tomorrow will be better", "کل بہتر ہو گا", "kal behtar ho ga"],
    ],
}
