# Urdu Lesson 5 — Conversation practice chunk A (chapter IDs 620–641).

LESSONS_S5A = {
    620: [
        ["Happy Diwali!", "دیوالی مبارک!", "Diwali mubaarak!"],
        ["Light the lamps", "دیاں جلائیں", "diyan jalaayein"],
        ["We worship Lakshmi", "ہم لکشمی کی پوجا کرتے ہیں", "hum Lakshmi ki pooja karte hain"],
        ["Sweets are distributed", "مٹھائیاں بانٹی جاتی ہیں", "mithaiyaan baanti jaati hain"],
        ["Firecrackers (use safely)", "پٹاخے (احتیاط سے)", "pataakhe (ehtiyaat se)"],
        ["Family gathers at home", "گھر پر خاندان جمع ہوتا ہے", "ghar par khaandaan jama hota hai"],
        ["New clothes", "نئے کپڑے", "naye kapre"],
        ["May light triumph over darkness", "روشنی ظلمت پر غالب آئے", "roshni zulmat par ghaalib aaye"],
        ["We visit relatives", "رشتہ داروں سے ملتے ہیں", "rishta daron se milte hain"],
        ["Happy Deepawali to you all", "آپ سب کو دیپاولی مبارک", "aap sab ko Deepawali mubaarak"],
        ["Traditional sweets: لڈو، جلیبی", "لڈو، جلیبی", "ladoo, jalebi"],
        ["Clean the house first", "پہلے گھر صاف کریں", "pehle ghar saaf karein"],
        ["Rangoli at the door", "دروازے پر رنگولی", "darwaaze par rangoli"],
        ["Thank you for the invitation", "دعوت کا شکریہ", "daawat ka shukriya"],
        ["Celebrate with care", "احتیاط سے منائیں", "ehtiyaat se manaayein"],
    ],
    621: [
        ["Peace be upon you", "السلام علیکم", "Assalamu alaikum"],
        ["And upon you peace", "وعلیکم السلام", "Wa alaikum assalam"],
        ["How are you? (polite)", "آپ کیسے ہیں؟", "aap kaise hain?"],
        ["I am fine", "میں ٹھیک ہوں", "main theek hoon"],
        ["What is your name?", "آپ کا نام کیا ہے؟", "aap ka naam kya hai?"],
        ["My name is…", "میرا نام… ہے", "mera naam… hai"],
        ["Nice to meet you", "آپ سے مل کر خوشی ہوئی", "aap se mil kar khushi hui"],
        ["Where are you from?", "آپ کہاں سے ہیں؟", "aap kahaan se hain?"],
        ["I am from Lucknow", "میں لکھنؤ سے ہوں", "main Lucknow se hoon"],
        ["Welcome!", "خوش آمدید!", "khush aamdeed!"],
        ["Please sit", "براہِ کرم بیٹھیں", "baraahe karam baithein"],
        ["Thank you", "شکریہ", "shukriya"],
        ["Goodbye", "اللہ حافظ", "Allah haafiz"],
        ["See you again", "پھر ملیں گے", "phir milenge"],
        ["Have a good day", "آپ کا دن اچھا گزرے", "aap ka din achchha guzre"],
    ],
    622: [
        ["What time is it?", "کتنے بجے ہیں؟", "kitne baje hain?"],
        ["It is five o'clock", "پانچ بجے ہیں", "paanch baje hain"],
        ["Half past six", "ساڑھے چھ بجے", "saadhe chh baje"],
        ["Quarter to nine", "نو بجے میں پندرہ منٹ", "nau baje mein pandrah minute"],
        ["I will come at noon", "میں دوپہر آؤں گا", "main dopehar aaunga"],
        ["Morning appointment", "صبح کی ملاقات", "subah ki mulaaqaat"],
        ["Are you free tonight?", "کیا آپ آج شام فارغ ہیں؟", "kya aaj shaam faarigh hain?"],
        ["Sorry, I'm late", "معاف کیجیے، دیر ہو گئی", "maaf kijiye, der ho gayi"],
        ["Let's meet tomorrow", "کل ملتے ہیں", "kal milte hain"],
        ["Sharp at eight", "بالکل آٹھ بجے", "bilqul aath baje"],
        ["Since morning", "صبح سے", "subah se"],
        ["Until evening", "شام تک", "shaam tak"],
        ["Busy schedule", "مصروف دن", "masroof din"],
        ["Alarm didn't ring", "الارم نہیں بجا", "alarm nahin baja"],
        ["Time flies", "وقت تیزی سے گزرتا ہے", "waqt tezi se guzarta hai"],
    ],
    623: [
        ["Where is the station?", "اسٹیشن کہاں ہے؟", "station kahaan hai?"],
        ["How do I go there?", "وہاں کیسے جاؤں؟", "wahaan kaise jaoon?"],
        ["Turn left", "بائیں مڑیں", "baayein murein"],
        ["Turn right", "دائیں مڑیں", "daayein murein"],
        ["Go straight", "سیدھا جائیں", "seedha jayein"],
        ["It's near the mosque", "مسجد کے قریب ہے", "masjid ke qareeb hai"],
        ["Far from here", "یہاں سے دور", "yahaan se door"],
        ["Map on phone", "فون پر نقشہ", "phone par naqsha"],
        ["I'm lost", "راستہ بھول گیا", "raasta bhool gaya"],
        ["Ask the policeman", "سپاہی سے پوچھیں", "sipahi se poochhein"],
        ["This way", "اس طرف", "is taraf"],
        ["Opposite the bank", "بینک کے سامنے", "bank ke saamne"],
        ["Behind the school", "اسکول کے پیچھے", "school ke peechhe"],
        ["How far by walk?", "پیدل کتنا دور؟", "paidal kitna door?"],
        ["Thank you for directions", "راستہ بتانے کا شکریہ", "raasta bataane ka shukriya"],
    ],
    624: [
        ["I booked a room", "میں نے کمرہ بک کیا", "main ne kamra book kiya"],
        ["Check-in please", "چیک اِن کریں", "check-in karein"],
        ["Room key", "کمرے کی چابی", "kamre ki chaabi"],
        ["AC is not working", "اے سی نہیں چل رہی", "AC nahin chal rahi"],
        ["Hot water please", "گرم پانی چاہیے", "garm paani chahiye"],
        ["Wi‑Fi password?", "وائی فائی پاس ورڈ؟", "Wi-Fi password?"],
        ["Breakfast timing", "ناشتہ کا وقت", "nashta ka waqt"],
        ["Call reception", "ریسپشن کو بلائیں", "reception ko bulaayein"],
        ["Checkout at noon", "چیک آؤٹ دوپہر تک", "checkout dopehar tak"],
        ["Bill please", "بل لائیں", "bill laayein"],
        ["Luggage help", "سامان میں مدد", "samaan mein madad"],
        ["Is parking available?", "پارکنگ ہے؟", "parking hai?"],
        ["Quiet room please", "پرسکون کمرہ چاہیے", "pur-sukoon kamra chahiye"],
        ["Extra blanket", "اضافی کمبل", "izaafi kambal"],
        ["Thank you, good service", "شکریہ، اچھی خدمت", "shukriya, achchi khidmat"],
    ],
    625: [
        ["Nice weather today", "آج موسم اچھا ہے", "aaj mausam achchha hai"],
        ["It's very hot", "بہت گرمی ہے", "bohat garmi hai"],
        ["It's cold", "سردی ہے", "sardi hai"],
        ["It may rain", "بارش ہو سکتی ہے", "baarish ho sakti hai"],
        ["Strong wind", "تیز ہوا", "tez hava"],
        ["Humid day", "نمی والا دن", "nami wala din"],
        ["Take an umbrella", "چھتری لے جائیں", "chhatri le jaayein"],
        ["Fog in winter", "سردی میں دھند", "sardi mein dhund"],
        ["Pollution today", "آلودگی آج", "aloodgi aaj"],
        ["Forecast says…", "پیشن گوئی ہے…", "peshin goi hai…"],
        ["Wear warm clothes", "گرم کپڑے پہنیں", "garm kapre pahnein"],
        ["Stay hydrated", "پانی پیتے رہیں", "paani peete rahein"],
        ["Heatwave warning", "گرمی کی لہر", "garmi ki lehar"],
        ["Pleasant evening", "خوشگوار شام", "khushgawaar shaam"],
        ["Climate is changing", "موسم بدل رہا ہے", "mausam badal raha hai"],
    ],
    626: [
        ["Good morning, sir", "صبح بخیر، صاحب", "subah bakhair, sahab"],
        ["Driving licence please", "ڈرائیونگ لائسنس دیجیے", "driving licence dijiye"],
        ["I was within speed limit", "میں رفتار حد میں تھا", "main raftaar had mein tha"],
        ["Helmet is on", "ہیلمٹ لگایا ہوا ہے", "helmet lagaya hua hai"],
        ["Seat belt", "سیٹ بیلٹ", "seat belt"],
        ["This is a one-way", "یہ ون وے ہے", "yeh one-way hai"],
        ["Fine receipt", "چالان کی رسید", "chalaan ki raseed"],
        ["I'll pay online", "آن لائن ادا کروں گا", "online ada karunga"],
        ["Sorry, won't repeat", "معاف، دوبارہ نہیں", "maaf, dobara nahin"],
        ["Documents are valid", "دستاویز درست ہیں", "dastaaweez durust hain"],
        ["Where is the traffic office?", "ٹریفک آفس کہاں؟", "traffic office kahaan?"],
        ["Signal was green", "سگنل سبز تھا", "signal sabz tha"],
        ["Emergency vehicle", "ایمبولنس کو راستہ", "ambulance ko raasta"],
        ["Thank you, officer", "شکریہ، افسر", "shukriya, afser"],
        ["Drive safely", "محفوظ ڈرائیو", "mehfooz drive"],
    ],
    627: [
        ["How much to the station?", "اسٹیشن کتنا کرایہ؟", "station kitna kiraya?"],
        ["Please use the meter", "میٹر لگائیے", "meter lagaaiye"],
        ["Stop here", "یہاں رکیں", "yahaan rukein"],
        ["Turn at the signal", "سگنل پر مڑیں", "signal par murein"],
        ["I'm in a hurry", "جلدی ہے", "jaldi hai"],
        ["Keep the change", "باقی رکھ لیں", "baaqi rakh lein"],
        ["Faster please", "تھوڑا تیز", "thoda tez"],
        ["Avoid the jam", "جم سے بچیں", "jam se bachein"],
        ["Drop me at the gate", "گیٹ پر اتار دیں", "gate par utaar dein"],
        ["Is this the shortest route?", "یہی مختصر راستہ؟", "yahi mukhtasar raasta?"],
        ["Rickshaw fare", "ریکشا کرایہ", "riksha kiraya"],
        ["Ola/Uber works too", "اولا/اوبر بھی", "Ola/Uber bhi"],
        ["Night charges?", "رات کا اضافہ؟", "raat ka izaafa?"],
        ["Receipt please", "رسید دیجیے", "raseed dijiye"],
        ["Thank you, safe trip", "شکریہ، سفر بخیر", "shukriya, safar bakhair"],
    ],
    628: [
        ["The build failed on CI", "سی آئی پر بلڈ فیل ہو گیا", "CI par build fail ho gaya"],
        ["I'll push a fix", "میں فکس پش کروں گا", "main fix push karunga"],
        ["Please review my PR", "میرا پی آر دیکھ لیں", "mera PR dekh lein"],
        ["Merge conflict", "مرج کانفلکٹ", "merge conflict"],
        ["Stand-up at ten", "سٹینڈ اپ دس بجے", "stand-up das baje"],
        ["Deploy to staging", "اسٹیجنگ پر ڈپلائے", "staging par deploy"],
        ["Bug is reproduced", "بگ ری پروڈیوس ہو گیا", "bug reproduce ho gaya"],
        ["Log shows timeout", "لاگ میں ٹائم آؤٹ", "log mein timeout"],
        ["Restart the server", "سرور ری اسٹارٹ", "server restart"],
        ["Client needs a hotfix", "کلائنٹ کو ہاٹ فکس چاہیے", "client ko hotfix chahiye"],
        ["Documentation updated", "دستاویز اپ ڈیٹ", "dastaweez update"],
        ["API rate limit", "اے پی آئی ریٹ لمٹ", "API rate limit"],
        ["I'll ping you on Slack", "سلیک پر پیغام کروں گا", "Slack par paighaam karunga"],
        ["VPN issue", "وی پی این مسئلہ", "VPN masla"],
        ["Let's pair-program", "پیئر پروگرامنگ کریں", "pair-programming karein"],
    ],
    629: [
        ["Half a kilo of rice", "آدھا کلو چاول", "aadha kilo chaawal"],
        ["Fresh vegetables?", "تازہ سبزیاں؟", "taaza sabziyaan?"],
        ["What's the rate today?", "آج کیا بھاؤ ہے؟", "aaj kya bhaao hai?"],
        ["Give a discount", "چھوٹ دیجیے", "chhoot dijiye"],
        ["Total amount", "کل رقم", "kul raqam"],
        ["Carry bag", "تھیلا", "thela"],
        ["Organic section", "ارگانک سیکشن", "organic section"],
        ["Weigh accurately", "ٹھیک تولیں", "theek tolein"],
        ["Return policy?", "واپسی کی پالیسی؟", "waapsi ki policy?"],
        ["Card payment OK?", "کارڈ سے ہو جائے گا؟", "card se ho jaayega?"],
        ["Bill please", "بل دیجیے", "bill dijiye"],
        ["This looks stale", "یہ پرانا لگتا ہے", "yeh puraana lagta hai"],
        ["Any offer on oil?", "تیل پر آفر؟", "tel par offer?"],
        ["Home delivery?", "گھر ڈیلیوری؟", "ghar delivery?"],
        ["Thanks, see you weekly", "شکریہ، ہفتہ وار ملاقات", "shukriya, haftawaar mulaaqaat"],
    ],
    630: [
        ["What are your symptoms?", "علامات کیا ہیں؟", "alaamaat kya hain?"],
        ["Since when?", "کب سے؟", "kab se?"],
        ["Take this prescription", "یہ نسخہ لیں", "yeh nuskha lein"],
        ["Blood test needed", "بلڈ ٹیسٹ ضروری", "blood test zaroori"],
        ["Any allergies?", "الرجی؟", "allergy?"],
        ["Rest and fluids", "آرام اور مائعات", "aaraam aur maiaat"],
        ["Follow-up after three days", "تین دن بعد چیک اپ", "teen din baad check-up"],
        ["Hospital timing", "ہسپتال کا وقت", "hospital ka waqt"],
        ["Emergency?", "ایمرجنسی؟", "emergency?"],
        ["Take medicine after food", "کھانے کے بعد دوا", "khaane ke baad dawa"],
        ["Don't skip doses", "خورد دوا نہ چھوڑیں", "khurd dawa na chhorein"],
        ["BP is normal", "بی پی نارمل", "BP normal"],
        ["I'll note your history", "تاریخ لکھ لیتا ہوں", "taareekh likh leta hoon"],
        ["Get well soon", "جلد صحت یاب ہوں", "jald sehat yaab hon"],
        ["Thank you, doctor", "شکریہ، ڈاکٹر صاحب", "shukriya, doctor sahab"],
    ],
    631: [
        ["Open your books", "کتابیں کھولیں", "kitaaben kholein"],
        ["Who will read first?", "پہلے کون پڑھے گا؟", "pehle kaun padhega?"],
        ["Do the homework", "ہوم ورک کریں", "homework karein"],
        ["Any questions?", "کوئی سوال؟", "koi sawaal?"],
        ["Be quiet, please", "خاموش رہیں", "khaamosh rahein"],
        ["Excellent answer", "بہترین جواب", "behtareen jawaab"],
        ["Try again", "دوبارہ کوشش کریں", "dobara koshish karein"],
        ["Exam next week", "اگلے ہفتے امتحان", "agle hafte imtihaan"],
        ["Respect everyone", "سب کا احترام", "sab ka ihtiraam"],
        ["Don't use phones in class", "کلاس میں فون نہ", "class mein phone na"],
        ["Group project", "گروپ پروجیکٹ", "group project"],
        ["Library rules", "لائبریری کے قوانین", "library ke qawaaneen"],
        ["Parent meeting Friday", "جمعہ کو والدین کی میٹنگ", "Juma ko walideen ki meeting"],
        ["Discipline matters", "نظام و ضبط ضروری", "nizaam-o-zabt zaroori"],
        ["Class dismissed", "کلاس ختم", "class khatm"],
    ],
    632: [
        ["Hello, it's me", "ہیلو، میں ہوں", "hello, main hoon"],
        ["Can you hear me?", "آواز آ رہی ہے؟", "aawaaz aa rahi hai?"],
        ["I'll call back", "واپس کال کروں گا", "waapas call karunga"],
        ["Signal is weak", "سگنل کمزور ہے", "signal kamzoor hai"],
        ["Where are you now?", "اب کہاں ہو؟", "ab kahaan ho?"],
        ["See you soon", "جلد ملتے ہیں", "jald milte hain"],
        ["Send the location", "لوکیشن بھیج دو", "location bhej do"],
        ["On WhatsApp", "واٹس ایپ پر", "WhatsApp par"],
        ["Battery dying", "بیٹری ختم", "battery khatm"],
        ["Talk later", "بعد میں بات", "baad mein baat"],
        ["Wrong number", "غلط نمبر", "ghalat number"],
        ["Speaker on", "اسپیکر آن", "speaker on"],
        ["Can't talk now", "اب بات نہیں", "ab baat nahin"],
        ["Text me", "میسج کر دینا", "message kar dena"],
        ["Bye!", "بائے!", "bye!"],
    ],
    633: [
        ["How much per kg?", "کلو کتنا؟", "kilo kitna?"],
        ["This is expensive", "یہ مہنگا ہے", "yeh mehnga hai"],
        ["Give coriander", "دھنیا دے دیجیے", "dhaniya de dijiye"],
        ["Fresh okra?", "تازہ بھنڈی؟", "taaza bhindi?"],
        ["I'll take two kilos", "دو کلو لے لیتا ہوں", "do kilo le leta hoon"],
        ["Any discount for bulk?", "زیادہ لینے پر چھوٹ؟", "zyada lene par chhoot?"],
        ["Quality is good", "معیار اچھا ہے", "miyaar achchha hai"],
        ["Weigh again", "دوبارہ تولیں", "dobara tolein"],
        ["Carry to the car", "گاڑی تک لے جائیں", "gaadi tak le jaayein"],
        ["Morning stock is fresh", "صبح کا مال تازہ", "subah ka maal taaza"],
        ["No plastic bag", "پلاسٹک تھیلا نہیں", "plastic thela nahin"],
        ["Change please", "خود واپس کریں", "khud waapas karein"],
        ["I'll come next Sunday", "اگلے اتوار آؤں گا", "agle itwaar aaunga"],
        ["Competitor's rate?", "دوسرے کا بھاؤ؟", "doosre ka bhaao?"],
        ["Thanks, brother", "شکریہ، بھائی", "shukriya, bhai"],
    ],
    634: [
        ["Which bus goes to…?", "کون سی بس جاتی ہے…؟", "kaun si bus jaati hai…?"],
        ["Where is the stop?", "اسٹاپ کہاں؟", "stop kahaan?"],
        ["Ticket please", "ٹکٹ دیجیے", "ticket dijiye"],
        ["Conductor", "کنڈکٹر", "conductor"],
        ["Window seat", "کھڑکی کی سیٹ", "khiṛki ki seat"],
        ["Next stop is…", "اگلا اسٹاپ…", "agla stop…"],
        ["Pull the cord to stop", "رکنے کے لیے تار کھینچیں", "rukne ke liye taar kheenchiye"],
        ["Crowded bus", "بھیڑ والی بس", "bheed wali bus"],
        ["Hold the rod", "ڈنڈا پکڑیں", "danda pakṛiye"],
        ["Mind your wallet", "بٹوا سنبھالیں", "batwa sambhaalein"],
        ["Get down carefully", "احتیاط سے اتریں", "ehtiyaat se utrein"],
        ["Missed my stop", "اسٹاپ چھوٹ گیا", "stop chhoot gaya"],
        ["Return ticket?", "ریٹرن ٹکٹ؟", "return ticket?"],
        ["Metro is faster", "میٹرو تیز ہے", "metro tez hai"],
        ["Safe journey", "سفر بخیر", "safar bakhair"],
    ],
    635: [
        ["What's your address?", "پتہ کیا ہے؟", "pata kya hai?"],
        ["House number", "مکان نمبر", "makaan number"],
        ["Street name", "گلی کا نام", "gali ka naam"],
        ["Near which landmark?", "کس نشان کے پاس؟", "kis nishaan ke paas?"],
        ["PIN code", "پن کوڈ", "PIN code"],
        ["Landmark: opposite park", "پارک کے سامنے", "park ke saamne"],
        ["Second floor", "دوسری منزل", "doosri manzil"],
        ["Ring the bell", "گھنٹی بجائیں", "ghanti bajaayein"],
        ["I'll share location", "لوکیشن بھیج دیتا ہوں", "location bhej deta hoon"],
        ["Can't find the lane", "گلی نہیں مل رہی", "gali nahin mil rahi"],
        ["Ask the guard", "گارڈ سے پوچھیں", "guard se poochhein"],
        ["GPS says…", "جی پی ایس کہتا ہے…", "GPS kehta hai…"],
        ["Correct pin on map", "نقشے پر صحیح پن", "naqshe par sahi pin"],
        ["Delivery instructions", "ڈیلیوری ہدایات", "delivery hidaayaat"],
        ["Thanks, found it", "شکریہ، مل گیا", "shukriya, mil gaya"],
    ],
    636: [
        ["I love you", "میں تم سے محبت کرتا ہوں", "main tum se mohabbat karta hoon"],
        ["You mean a lot to me", "تم میرے لیے خاص ہو", "tum mere liye khaas ho"],
        ["Will you marry me? (context)", "کیا تم… (سیاق)", "kya tum… (siyaq)"],
        ["I respect you deeply", "میں آپ کا گہرا احترام کرتا ہوں", "main aap ka gehra ihtiraam karta hoon"],
        ["Let's meet for coffee", "چائے/کافی پر ملیں", "chai/coffee par milen"],
        ["I miss you", "مجھے تمہاری یاد آتی ہے", "mujhe tumhari yaad aati hai"],
        ["Thinking of you", "تمہیں یاد کر رہا ہوں", "tumhein yaad kar raha hoon"],
        ["Kind and caring", "مہربان اور فکر مند", "meherbaan aur fikarmand"],
        ["Take your time", "اپنا وقت لو", "apna waqt lo"],
        ["No pressure", "دباؤ نہیں", "dabaao nahin"],
        ["Honest feelings", "سچی محسوسات", "sachi mehsoosaat"],
        ["Friendship first", "پہلے دوستی", "pehle dostee"],
        ["Clear communication", "واضح بات", "waazeh baat"],
        ["Cultural sensitivity", "ثقافتی لحاظ", "saqaafi lehaaz"],
        ["Thank you for understanding", "سمجھنے کا شکریہ", "samajhne ka shukriya"],
    ],
    637: [
        ["Tell me about yourself", "اپنے بارے میں بتائیں", "apne baare mein bataiyein"],
        ["Why should we hire you?", "ہم آپ کو کیوں رکھیں؟", "hum aap ko kyon rakhein?"],
        ["My strengths are…", "میری طاقتیں…", "meri taaqatein…"],
        ["I handled a project…", "میں نے ایک منصوبہ…", "main ne ek mansooba…"],
        ["Salary expectation", "تنخواہ کی توقع", "tankhaah ki towaqqo"],
        ["Notice period", "نوٹس پیریڈ", "notice period"],
        ["Available from…", "سے دستیاب", "se dastiyaab"],
        ["Questions for us?", "ہمارے لیے سوالات؟", "hamare liye sawaalat?"],
        ["Thank you for your time", "وقت کا شکریہ", "waqt ka shukriya"],
        ["Follow-up email", "فالو اپ ای میل", "follow-up email"],
        ["Dress formally", "رسمی لباس", "rasmi libaas"],
        ["Arrive on time", "وقت پر پہنچیں", "waqt par pahunchein"],
        ["Resume highlights", "ریزیومے کی اہم باتیں", "resume ki ahem baatein"],
        ["Team player", "ٹیم پلیئر", "team player"],
        ["Goodbye for now", "اب کے لیے خدا حافظ", "ab ke liye khuda haafiz"],
    ],
    638: [
        ["Please clean the kitchen", "براہِ کرم باورچی خانہ صاف کریں", "baraahe karam bawarchi khaana saaf karein"],
        ["Washing is in the machine", "کپڑے مشین میں ہیں", "kapre machine mein hain"],
        ["Don't use harsh chemicals", "سخت کیمیکل نہ", "sakht chemical na"],
        ["Children's room", "بچوں کا کمرہ", "bachchon ka kamra"],
        ["Garbage bags outside", "کچرے کے تھیلے باہر", "kachre ke thele baahar"],
        ["Market list on the fridge", "فریج پر فہرست", "fridge par fehrist"],
        ["Salary on the fifth", "تنخواہ پانچ کو", "tankhaah paanch ko"],
        ["Take Sunday off", "اتوار چھٹی", "itwaar chhutti"],
        ["Call if urgent", "ضروری ہو تو فون", "zaroori ho to phone"],
        ["Keys on the hook", "چابی کھونٹی پر", "chaabi khonti par"],
        ["Respect and safety", "احترام اور حفاظت", "ihtiraam aur hifaazat"],
        ["Any problem, tell me", "مسئلہ ہو تو بتائیں", "masla ho to bataiyein"],
        ["Thank you for your work", "کام کا شکریہ", "kaam ka shukriya"],
        ["Festival bonus", "تہوار بونس", "tehwaar bonus"],
        ["See you tomorrow", "کل ملیں گے", "kal milenge"],
    ],
    639: [
        ["Link Aadhaar to mobile", "آدھار موبائل سے لنک کریں", "Aadhaar mobile se link karein"],
        ["OTP came", "او ٹی پی آ گیا", "OTP aa gaya"],
        ["Enter last four digits", "آخری چار ہندسے", "aakhiri chaar hindse"],
        ["SIM verification", "سم کی تصدیق", "SIM ki tasdeeq"],
        ["Store executive", "اسٹور کے ملازم", "store ke mulaaazim"],
        ["ID proof", "شناخت", "shinaakht"],
        ["Fingerprint scan", "انگلی کا سکین", "ungli ka scan"],
        ["Process takes minutes", "چند منٹ میں", "chand minute mein"],
        ["Confirmation SMS", "تصدیقی میسج", "tasdeeqi message"],
        ["Keep receipt", "رسید سنبھالیں", "raseed sambhaalein"],
        ["Any charges?", "کوئی فیس؟", "koi fees?"],
        ["Customer care number", "کسٹمر کیئر", "customer care"],
        ["Done successfully", "کامیابی سے ہو گیا", "kaamyaabi se ho gaya"],
        ["Privacy note", "رازداری", "raazdaari"],
        ["Thank you", "شکریہ", "shukriya"],
    ],
    640: [
        ["Update mobile on Aadhaar", "آدھار پر موبائل اپ ڈیٹ", "Aadhaar par mobile update"],
        ["Visit UIDAI site", "یو آئی ڈی اے آئی سائٹ", "UIDAI site"],
        ["OTP to registered number", "رجسٹرڈ نمبر پر او ٹی پی", "registered number par OTP"],
        ["Biometric at centre", "سینٹر پر بائیو میٹرک", "centre par biometric"],
        ["Appointment slot", "اپائنٹمنٹ سلاٹ", "appointment slot"],
        ["Carry original Aadhaar", "اصل آدھار ساتھ", "asl Aadhaar saath"],
        ["Helpline 1947", "ہیلپ لائن ۱۹۴۷", "helpline 1947"],
        ["Avoid agents", "ایجنٹ سے بچیں", "agent se bachein"],
        ["Official fee only", "صرف سرکاری فیس", "sirf sarkaari fees"],
        ["Download e-Aadhaar", "ای آدھار ڈاؤن لوڈ", "e-Aadhaar download"],
        ["Mask number on copy", "کاپی پر نمبر ماسک", "copy par number mask"],
        ["Secure your PIN", "پن محفوظ رکھیں", "PIN mehfooz rakhein"],
        ["Takes a few days", "چند دن لگتے ہیں", "chand din lagte hain"],
        ["Track status online", "آن لائن اسٹیٹس", "online status"],
        ["Thanks for guidance", "رہنمائی کا شکریہ", "rehnumai ka shukriya"],
    ],
    641: [
        ["Happy Republic Day!", "جمہوریہ دن مبارک!", "Jamhooriya Din mubaarak!"],
        ["Flag hoisting", "جھنڈا لہرانا", "jhanda lehraana"],
        ["National anthem", "قومی ترانہ", "qaumi taraana"],
        ["Parade on TV", "پریڈ ٹی وی پر", "parade TV par"],
        ["Tribute to martyrs", "شہداء کو خراج", "shuhada ko khiraaj"],
        ["Constitution values", "آئین کی قدروں", "aaeen ki qadron"],
        ["Unity in diversity", "یکجہتی میں تنوع", "yakjehti mein tanoo'"],
        ["Children's programme", "بچوں کا پروگرام", "bachchon ka programme"],
        ["Sweets at home", "گھر پر مٹھائی", "ghar par mithai"],
        ["Wear tricolour", "ترنگا پہنیں", "tiranga pahnein"],
        ["Responsible citizen", "ذمہ دار شہری", "zimmedaar shehri"],
        ["Clean public places", "عوامی جگہیں صاف", "awaami jagaen saaf"],
        ["Peace and progress", "امن و ترقی", "aman-o-taraqqi"],
        ["Jai Hind!", "جے ہند!", "Jai Hind!"],
        ["Proud of India", "بھارت پر فخر", "Bharat par fakhr"],
    ],
}
