# Urdu Lesson 2 — Grammar chunk A (chapter IDs 510–526).
# Columns: English, Urdu, Transliteration.

LESSONS_S2A = {
    510: [
        ["I", "میں", "main"],
        ["you (informal)", "تم", "tum"],
        ["you (polite)", "آپ", "aap"],
        ["he / she / it (proximal)", "یہ", "yeh"],
        ["that (distal)", "وہ", "woh"],
        ["we", "ہم", "hum"],
        ["they / those", "وہ لوگ", "woh log"],
        ["the (definite; context)", "(سیاق و سباق)", "(siyaq-o-sabaq)"],
        ["a / one (indefinite)", "ایک", "ek"],
        ["this book", "یہ کتاب", "yeh kitaab"],
        ["that house", "وہ گھر", "woh ghar"],
        ["my book", "میری کتاب", "meri kitaab"],
        ["your house (polite)", "آپ کا گھر", "aap ka ghar"],
        ["his pen", "اس کا قلم", "us ka qalam"],
        ["her bag", "اس کا بیگ", "us ka bag"],
        ["our school", "ہمارا اسکول", "hamara school"],
        ["their car", "ان کی گاڑی", "unki gaadi"],
        ["who is he?", "وہ کون ہے؟", "woh kaun hai?"],
        ["what is this?", "یہ کیا ہے؟", "yeh kya hai?"],
    ],
    511: [
        ["Use plural verb with 'aap' (respect)", "آپ کے ساتھ فعل جمع", "Aap ke saath fe'l jama'"],
        ["You are welcome (polite)", "خوش آمدید", "khush aamdeed"],
        ["Sir, please sit", "جناب، براہِ کرم بیٹھیں", "janaab, baraahe karam baithein"],
        ["They (honorific) have arrived", "وہ تشریف لائے", "woh tashreef laaye"],
        ["Respected elders speak first", "بزرگ پہلے بولتے ہیں", "buzurg pehle bolte hain"],
        ["We — can mean 'I' formally", "ہم کبھی 'میں' کے لیے", "hum kabhi 'main' ke liye"],
        ["Please come in", "تشریف لائیے", "tashreef laaiye"],
        ["May I go? (polite)", "کیا میں چلوں؟", "kya main chaloon?"],
        ["Your health? (respect)", "آپ کی طبیعت؟", "aap ki tabiyat?"],
        ["They (for one elder)", "وہ (احتراماً)", "woh (ihtiraaman)"],
        ["We humbly request", "عرض ہے", "arz hai"],
        ["Kindly note", "مہربانی فرمائیں", "meherbaani farmaiyein"],
        ["Your order, sir", "آپ کا حکم", "aap ka hukm"],
        ["The guests are respected", "مہمان کی عزت", "mehmaan ki izzat"],
        ["Teachers are addressed as 'aap'", "استاد کو آپ کہیں", "ustaad ko aap kahein"],
        ["Plural pronoun for respect: آپ لوگ", "آپ لوگ", "aap log"],
        ["Avoid 'tum' with elders", "بزرگوں سے 'تم' نہ", "buzurgon se 'tum' na"],
    ],
    512: [
        ["Verb root (masdar): کَھانَا", "کھانا", "khana"],
        ["Infinitive ending: ـنَا", "نا", "-na"],
        ["to read: پَڑھنَا", "پڑھنا", "padhna"],
        ["to go: جَانَا", "جانا", "jaana"],
        ["to come: آنَا", "آنا", "aana"],
        ["to do: کَرنَا", "کرنا", "karna"],
        ["to drink: پِینَا", "پینا", "peena"],
        ["to write: لِکھنَا", "لکھنا", "likhna"],
        ["Transitive vs intransitive", "متعدی اور لازم", "muta'addi aur laazim"],
        ["Gender agreement with object (past)", "ماضی میں جنس", "maazi mein jins"],
        ["Auxiliary: ہے، تھے، ہوں", "ہے، تھے، ہوں", "hai, the, hoon"],
        ["Compound verbs: دیکھ لینا", "دیکھ لینا", "dekh lena"],
        ["Causative: پڑھوانا", "پڑھوانا", "padhwaana"],
        ["Practice: میں کھانا چاہتا ہوں", "میں کھانا چاہتا ہوں", "main khaana chahta hoon"],
        ["She wants to sing", "وہ گانا چاہتی ہے", "woh gaana chahti hai"],
        ["We try to learn", "ہم سیکھنے کی کوشش کرتے ہیں", "hum seekhne ki koshish karte hain"],
    ],
    513: [
        ["I eat (m.)", "میں کھاتا ہوں", "main khaata hoon"],
        ["I eat (f.)", "میں کھاتی ہوں", "main khaati hoon"],
        ["you eat (informal m.)", "تم کھاتے ہو", "tum khaate ho"],
        ["he eats", "وہ کھاتا ہے", "woh khaata hai"],
        ["she eats", "وہ کھاتی ہے", "woh khaati hai"],
        ["we eat", "ہم کھاتے ہیں", "hum khaate hain"],
        ["they eat", "وہ کھاتے ہیں", "woh khaate hain"],
        ["you (polite) eat", "آپ کھاتے ہیں", "aap khaate hain"],
        ["Negative: I don't eat", "میں نہیں کھاتا", "main nahin khaata"],
        ["Question: Do you read?", "کیا تم پڑھتے ہو؟", "kya tum padhte ho?"],
        ["He works in Delhi", "وہ دہلی میں کام کرتا ہے", "woh Dilli mein kaam karta hai"],
        ["It rains", "بارش ہوتی ہے", "baarish hoti hai"],
        ["Birds fly", "پرندے اڑتے ہیں", "parinde udte hain"],
        ["I know Urdu", "مجھے اردو آتی ہے", "mujhe Urdu aati hai"],
        ["We live here", "ہم یہاں رہتے ہیں", "hum yahaan rehte hain"],
        ["They speak softly", "وہ آہستہ بولتے ہیں", "woh aahista bolte hain"],
    ],
    514: [
        ["I am (m.)", "میں ہوں", "main hoon"],
        ["I am (f.)", "میں ہوں", "main hoon"],
        ["you are (informal)", "تم ہو", "tum ho"],
        ["you are (polite)", "آپ ہیں", "aap hain"],
        ["he is", "وہ ہے", "woh hai"],
        ["she is", "وہ ہے", "woh hai"],
        ["we are", "ہم ہیں", "hum hain"],
        ["they are", "وہ ہیں", "woh hain"],
        ["it is cold", "سردی ہے", "sardi hai"],
        ["this is a book", "یہ کتاب ہے", "yeh kitaab hai"],
        ["that was yesterday", "وہ کل تھا", "woh kal tha"],
        ["I am tired", "میں تھکا ہوا ہوں", "main thaka hua hoon"],
        ["We are ready", "ہم تیار ہیں", "hum taiyaar hain"],
        ["Negative: I am not angry", "میں ناراض نہیں ہوں", "main naraz nahin hoon"],
        ["Where are you? (polite)", "آپ کہاں ہیں؟", "aap kahaan hain?"],
        ["Who is there?", "وہاں کون ہے؟", "wahaan kaun hai?"],
    ],
    515: [
        ["I am eating", "میں کھا رہا ہوں", "main khaa raha hoon"],
        ["she is reading", "وہ پڑھ رہی ہے", "woh padh rahi hai"],
        ["they are talking", "وہ بات کر رہے ہیں", "woh baat kar rahe hain"],
        ["we are waiting", "ہم انتظار کر رہے ہیں", "hum intizaar kar rahe hain"],
        ["it is raining", "بارش ہو رہی ہے", "baarish ho rahi hai"],
        ["he is not coming", "وہ نہیں آ رہا", "woh nahin aa raha"],
        ["Are you going? (informal)", "کیا تم جا رہے ہو؟", "kya tum jaa rahe ho?"],
        ["I am studying Urdu", "میں اردو پڑھ رہا ہوں", "main Urdu padh raha hoon"],
        ["The train is leaving", "ریل جا رہی ہے", "rail jaa rahi hai"],
        ["Children are playing", "بچے کھیل رہے ہیں", "bachche khel rahe hain"],
        ["She is cooking", "وہ کھانا بنا رہی ہے", "woh khaana bana rahi hai"],
        ["We are listening", "ہم سن رہے ہیں", "hum sun rahe hain"],
        ["Progressive negative", "نہیں کر رہا", "nahin kar raha"],
        ["Also with 'tha': was doing", "کر رہا تھا", "kar raha tha"],
        ["Emphasis: ابھی پڑھ رہا ہوں", "ابھی پڑھ رہا ہوں", "abhi padh raha hoon"],
    ],
    516: [
        ["I will go", "میں جاؤں گا", "main jaaunga"],
        ["she will come", "وہ آئے گی", "woh aayegi"],
        ["we will meet", "ہم ملیں گے", "hum milenge"],
        ["they will leave", "وہ جائیں گے", "woh jaayenge"],
        ["it will rain tomorrow", "کل بارش ہوگی", "kal baarish hogi"],
        ["I will not forget", "میں نہیں بھولوں گا", "main nahin bhoolunga"],
        ["Will you help? (polite)", "کیا آپ مدد کریں گے؟", "kya aap madad karenge?"],
        ["He will call", "وہ فون کرے گا", "woh phone karega"],
        ["We shall try", "ہم کوشش کریں گے", "hum koshish karenge"],
        ["Future of 'hona': ہوگا، ہوگی", "ہو گا، ہو گی", "hoga, hogi"],
        ["Plan: میں کل پڑھوں گا", "میں کل پڑھوں گا", "main kal padhunga"],
        ["Polite request future: کریں گے", "کریں گے", "karenge"],
        ["Probability: شاید آئے گا", "شاید آئے گا", "shayad aayega"],
        ["Negative future: نہیں جائے گی", "نہیں جائے گی", "nahin jaayegi"],
        ["Sentence: وقت بتائے گا", "وقت بتائے گا", "waqt batayega"],
    ],
    517: [
        ["I will be reading", "میں پڑھ رہا ہوں گا", "main padh raha hoonga"],
        ["she will be working", "وہ کام کر رہی ہو گی", "woh kaam kar rahi hogi"],
        ["they will be travelling", "وہ سفر کر رہے ہوں گے", "woh safar kar rahe honge"],
        ["this time tomorrow", "کل اس وقت", "kal is waqt"],
        ["I'll be at home", "میں گھر پر ہوں گا", "main ghar par hoonga"],
        ["Future progressive (less common in speech)", "مستقبل جاری", "mustaqbil jaari"],
        ["Often simple future preferred", "عام بول چال میں سادہ مستقبل", "aam bol chaal mein saada mustaqbil"],
        ["By evening I will be free", "شام تک میں فارغ ہوں گا", "shaam tak main faarigh hoonga"],
        ["Train will be arriving", "ٹرین آ رہی ہو گی", "train aa rahi hogi"],
        ["We will be waiting", "ہم منتظر ہوں گے", "hum muntazir honge"],
        ["Negative: نہیں رہوں گا", "نہیں رہوں گا", "nahin rahunga"],
        ["Question: کیا تم سو رہے ہو گے؟", "کیا تم سو رہے ہو گے؟", "kya tum so rahe hoge?"],
        ["Literary nuance", "ادبی استعمال", "adabi istemaal"],
        ["Compare: جاؤں گا vs جا رہا ہوں گا", "فرق", "farq"],
        ["Practice one paragraph", "ایک پیراگراف مشق", "ek paragraph mashq"],
    ],
    518: [
        ["I went", "میں گیا", "main gaya"],
        ["I went (f.)", "میں گئی", "main gayi"],
        ["he came", "وہ آیا", "woh aaya"],
        ["she slept", "وہ سوئی", "woh soyi"],
        ["we sat", "ہم بیٹھے", "hum baithe"],
        ["they laughed", "وہ ہنسے", "woh hanse"],
        ["it fell", "وہ گر گیا", "woh gir gaya"],
        ["yesterday I studied", "کل میں نے پڑھا", "kal main ne padha"],
        ["No object — verb agrees with subject", "فاعل کے مطابق", "faa'il ke mutabiq"],
        ["Past marker on verb", "ماضی کا نشان", "maazi ka nishaan"],
        ["Negative: نہیں گیا", "نہیں گیا", "nahin gaya"],
        ["Question: کیا تم گئے؟", "کیا تم گئے؟", "kya tum gaye?"],
        ["Suddenly it rained", "اچانک بارش ہوئی", "achaanak baarish hui"],
        ["I felt cold", "مجھے سردی لگی", "mujhe sardi lagi"],
        ["We returned home", "ہم گھر لوٹے", "hum ghar laute"],
    ],
    519: [
        ["I read the book (m. subject)", "میں نے کتاب پڑھی", "main ne kitaab padhi"],
        ["he opened the door", "اس نے دروازہ کھولا", "us ne darwaaza khola"],
        ["she wrote a letter", "اس نے خط لکھا", "us ne khat likha"],
        ["we saw the film", "ہم نے فلم دیکھی", "hum ne film dekhi"],
        ["they helped him", "انہوں نے اس کی مدد کی", "unhon ne us ki madad ki"],
        ["Object marks gender/number in past", "مفعول کے مطابق فعل", "mafoo'l ke mutabiq fe'l"],
        ["ne ergative: نے", "نے", "ne"],
        ["I did not eat rice", "میں نے چاول نہیں کھائے", "main ne chaawal nahin khaaye"],
        ["Did you call? (polite)", "کیا آپ نے فون کیا؟", "kya aap ne phone kiya?"],
        ["He bought fruit", "اس نے پھل خریدے", "us ne phal khareede"],
        ["She taught the lesson", "اس نے سبق پڑھایا", "us ne sabak padhaaya"],
        ["We forgot the keys", "ہم نے چابیاں بھولیں", "hum ne chaabiyaan bhoolein"],
        ["Transitive past pattern", "متعدی ماضی کا ڈھانچہ", "muta'addi maazi ka dhaancha"],
        ["Intransitive: no نے on subject", "لازم میں نے نہیں", "laazim mein ne nahin"],
        ["Practice: اس نے، ہم نے، تم نے", "اس نے، ہم نے، تم نے", "us ne, hum ne, tum ne"],
    ],
    520: [
        ["I was (m.)", "میں تھا", "main tha"],
        ["I was (f.)", "میں تھی", "main thi"],
        ["you were (informal)", "تم تھے", "tum the"],
        ["he was", "وہ تھا", "woh tha"],
        ["she was", "وہ تھی", "woh thi"],
        ["we were", "ہم تھے", "hum the"],
        ["they were", "وہ تھے", "woh the"],
        ["it was hot", "گرمی تھی", "garmi thi"],
        ["there was a problem", "ایک مسئلہ تھا", "ek masla tha"],
        ["I was at school", "میں اسکول میں تھا", "main school mein tha"],
        ["Negative: نہیں تھا", "نہیں تھا", "nahin tha"],
        ["Were you tired? (polite)", "کیا آپ تھکے ہوئے تھے؟", "kya aap thake hue the?"],
        ["Past + progressive: کر رہا تھا", "کر رہا تھا", "kar raha tha"],
        ["She was ill", "وہ بیمار تھی", "woh bimaar thi"],
        ["We were friends", "ہم دوست تھے", "hum dost the"],
    ],
    521: [
        ["to go — گیا / گئے (irregular pattern)", "جانا — گیا", "jaana — gaya"],
        ["to come — آیا / آئیں", "آنا — آیا", "aana — aaya"],
        ["to take — لیا", "لینا — لیا", "lena — liya"],
        ["to give — دیا", "دینا — دیا", "dena — diya"],
        ["to sit — بیٹھا", "بیٹھنا — بیٹھا", "baithna — baitha"],
        ["Some verbs use neuter forms", "کچھ فعل غیر معمولی", "kuch fe'l ghair ma'mooli"],
        ["'dekhna' — دیکھا", "دیکھنا — دیکھا", "dekhna — dekha"],
        ["'sunna' — سنا", "سننا — سنا", "sunna — suna"],
        ["Memorize common past stems", "ماضی کے روٹ یاد کریں", "maazi ke root yaad karein"],
        ["I went — میں گیا", "میں گیا", "main gaya"],
        ["they came — وہ آئے", "وہ آئے", "woh aaye"],
        ["she gave — اس نے دیا", "اس نے دیا", "us ne diya"],
        ["Practice sentences", "جملے بنائیں", "jumle banayein"],
        ["Listen for vowel changes", "حرکات پر دھیان", "harakaat par dhyaan"],
        ["Drill: گیا، گئی، گئے", "گیا، گئی، گئے", "gaya, gayi, gaye"],
    ],
    522: [
        ["I was reading", "میں پڑھ رہا تھا", "main padh raha tha"],
        ["she was cooking", "وہ کھانا بنا رہی تھی", "woh khaana bana rahi thi"],
        ["they were talking", "وہ بات کر رہے تھے", "woh baat kar rahe the"],
        ["it was raining", "بارش ہو رہی تھی", "baarish ho rahi thi"],
        ["we were waiting", "ہم انتظار کر رہے تھے", "hum intizaar kar rahe the"],
        ["he was not listening", "وہ نہیں سن رہا تھا", "woh nahin sun raha tha"],
        ["Were you sleeping?", "کیا تم سو رہے تھے؟", "kya tum so rahe the?"],
        ["Background in story", "کہانی میں پس منظر", "kahaani mein pas manzar"],
        ["Interrupted action", "درمیان میں ٹوٹا کام", "darmiyaan mein toota kaam"],
        ["While I was reading…", "جب میں پڑھ رہا تھا…", "jab main padh raha tha…"],
        ["Past progressive + past", "ماضی جاری + ماضی", "maazi jaari + maazi"],
        ["She was singing then", "وہ گا رہی تھی", "woh gaa rahi thi"],
        ["Negative: نہیں کر رہے تھے", "نہیں کر رہے تھے", "nahin kar rahe the"],
        ["Politeness unchanged", "ادب برقرار", "adab barqaraar"],
        ["Practice paragraph", "مشق پیراگراف", "mashq paragraph"],
    ],
    523: [
        ["I have eaten", "میں کھا چکا ہوں", "main khaa chuka hoon"],
        ["she has gone", "وہ جا چکی ہے", "woh ja chuki hai"],
        ["they had arrived", "وہ پہنچ چکے تھے", "woh pahunch chuke the"],
        ["we will have finished", "ہم ختم کر چکے ہوں گے", "hum khatm kar chuke honge"],
        ["Present perfect use", "مکمل حال", "mukammal haal"],
        ["Past perfect: before another past", "ماضی قریب از ماضی", "maazi qareeb az maazi"],
        ["Future perfect (formal)", "مستقبل مکمل", "mustaqbil mukammal"],
        ["I had seen him", "میں اسے مل چکا تھا", "main use mil chuka tha"],
        ["Have you read? (polite)", "کیا آپ پڑھ چکے ہیں؟", "kya aap padh chuke hain?"],
        ["Auxiliary: ہے، تھے، ہوں گے", "ہے، تھے، ہوں گے", "hai, the, honge"],
        ["Negative: نہیں کیا", "نہیں کیا", "nahin kiya"],
        ["Since morning I have worked", "صبح سے کام کیا ہے", "subah se kaam kiya hai"],
        ["By then she had left", "تب تک وہ جا چکی تھی", "tab tak woh ja chuki thi"],
        ["Common in news / writing", "خبروں میں عام", "khabron mein aam"],
        ["Practice: چکا، چکی، چکے", "چکا، چکی، چکے", "chuka, chuki, chuke"],
    ],
    524: [
        ["in", "میں", "mein"],
        ["on", "پر", "par"],
        ["under", "کے نیچے", "ke neeche"],
        ["with", "کے ساتھ", "ke saath"],
        ["from", "سے", "se"],
        ["to / toward", "کو / کی طرف", "ko / ki taraf"],
        ["for", "کے لیے", "ke liye"],
        ["between", "کے درمیان", "ke darmiyaan"],
        ["behind", "کے پیچھے", "ke peechhe"],
        ["before / front", "کے سامنے", "ke saamne"],
        ["after", "کے بعد", "ke baad"],
        ["near", "کے پاس", "ke paas"],
        ["inside", "کے اندر", "ke andar"],
        ["outside", "کے باہر", "ke baahar"],
        ["without", "کے بغیر", "ke baghair"],
        ["The book is on the table", "کتاب میز پر ہے", "kitaab mez par hai"],
    ],
    525: [
        ["to me", "مجھ کو / مجھے", "mujh ko / mujhe"],
        ["to him / her", "اس کو / اسے", "us ko / use"],
        ["to us", "ہم کو / ہمیں", "hum ko / hamein"],
        ["to you (polite)", "آپ کو", "aap ko"],
        ["Give water to me", "مجھے پانی دو", "mujhe paani do"],
        ["I went to Lahore", "میں لاہور گیا", "main Lahore gaya"],
        ["She came to the party", "وہ پارٹی میں آئی", "woh party mein aayi"],
        ["Send this to him", "یہ اسے بھیجیں", "yeh use bhejein"],
        ["'ko' marks dative / goal", "کو کا استعمال", "ko ka istemaal"],
        ["Talk to the teacher", "استاد سے بات کریں", "ustaad se baat karein"],
        ["I agree with you", "میں آپ سے متفق ہوں", "main aap se muttafiq hoon"],
        ["Difference: میں vs کو", "میں اور کو", "mein aur ko"],
        ["He gave it to them", "اس نے وہ انہیں دیا", "us ne woh unhein diya"],
        ["Don't lie to elders", "بزرگوں سے جھوٹ نہ بولیں", "buzurgon se jhoot na bolein"],
        ["Practice dative sentences", "مجھے، تمہیں، انہیں", "mujhe, tumhein, unhein"],
    ],
    526: [
        ["I saw him", "میں نے اسے دیکھا", "main ne use dekha"],
        ["You called her (informal)", "تم نے اسے بلایا", "tum ne use bulaaya"],
        ["He helped them", "اس نے ان کی مدد کی", "us ne un ki madad ki"],
        ["She loves her mother", "وہ اپنی ماں سے پیار کرتی ہے", "woh apni maa se pyaar karti hai"],
        ["We invited the guests", "ہم نے مہمانوں کو بلایا", "hum ne mehmaanon ko bulaaya"],
        ["They thanked the teacher", "انہوں نے استاد کا شکریہ ادا کیا", "unhon ne ustaad ka shukriya ada kiya"],
        ["I gave the child a sweet", "میں نے بچے کو مٹھائی دی", "main ne bachche ko mithai di"],
        ["Tell us the story", "ہمیں کہانی سنائیں", "hamein kahaani sunaayein"],
        ["He sent me a message", "اس نے مجھے پیغام بھیجا", "us ne mujhe paighaam bheja"],
        ["She showed me the photo", "اس نے مجھے تصویر دکھائی", "us ne mujhe tasweer dikhaayi"],
        ["Find the boy", "لڑکے کو ڈھونڈیں", "larke ko dhoondhein"],
        ["Call the doctor", "ڈاکٹر کو بلائیں", "doctor ko bulaayein"],
        ["Respect elders", "بزرگوں کا احترام کریں", "buzurgon ka ihtiraam karein"],
        ["I met my friend", "میں اپنے دوست سے ملا", "main apne dost se mila"],
        ["Person as object takes کو / سے", "شخص مفعول", "shakhs mafoo'l"],
        ["Animate objects with نے + کو", "جان دار مفعول", "jaan daar mafoo'l"],
    ],
}
