# Urdu Lesson 4 — Vocabulary (chapter IDs 597–619).

LESSONS_S4 = {
    597: [
        ["Head", "سر", "sar"],
        ["Hair", "بال", "baal"],
        ["Eye", "آنکھ", "aankh"],
        ["Ear", "کان", "kaan"],
        ["Nose", "ناک", "naak"],
        ["Mouth", "منہ", "munh"],
        ["Tooth", "دانت", "daant"],
        ["Tongue", "زبان", "zubaan"],
        ["Neck", "گردن", "gardan"],
        ["Shoulder", "کندھا", "kandha"],
        ["Arm", "بازو", "baazu"],
        ["Hand", "ہاتھ", "haath"],
        ["Finger", "انگلی", "ungli"],
        ["Chest", "سینہ", "seenah"],
        ["Stomach", "پیٹ", "peṭ"],
        ["Back", "پیٹھ", "peeṭh"],
        ["Leg", "ٹانگ", "taang"],
        ["Foot", "پاؤں", "paon"],
        ["Skin", "جلد", "jild"],
        ["Bone", "ہڈّی", "haḍḍi"],
    ],
    598: [
        ["House", "گھر", "ghar"],
        ["Door", "دروازہ", "darwaaza"],
        ["Window", "کھڑکی", "khiṛki"],
        ["Road", "سڑک", "sadak"],
        ["Water", "پانی", "paani"],
        ["Fire", "آگ", "aag"],
        ["Sky", "آسمان", "aasamaan"],
        ["Earth / ground", "زمین", "zameen"],
        ["Sun", "سورج", "sooraj"],
        ["Moon", "چاند", "chaand"],
        ["Star", "ستارہ", "sitaarah"],
        ["Wind", "ہوا", "hava"],
        ["Rain", "بارش", "baarish"],
        ["Day", "دن", "din"],
        ["Night", "رات", "raat"],
        ["Morning", "صبح", "subah"],
        ["Evening", "شام", "shaam"],
        ["Market", "بازار", "bazaar"],
        ["Shop", "دکان", "dukaan"],
        ["School", "اسکول", "school"],
    ],
    599: [
        ["Father", "والد / ابّو", "walid / abbu"],
        ["Mother", "والدہ / امی", "walida / ammi"],
        ["Brother", "بھائی", "bhai"],
        ["Sister", "بہن", "behan"],
        ["Son", "بیٹا", "beta"],
        ["Daughter", "بیٹی", "beti"],
        ["Husband", "شوہر", "shohar"],
        ["Wife", "بیوی", "biwi"],
        ["Grandfather", "دادا", "daada"],
        ["Grandmother", "دادی", "daadi"],
        ["Uncle (paternal)", "چچا", "chacha"],
        ["Aunt (paternal)", "چچی", "chachi"],
        ["Maternal uncle", "ماموں", "maamu"],
        ["Maternal aunt", "خالہ", "khaala"],
        ["Father-in-law", "سسر", "sasur"],
        ["Mother-in-law", "ساس", "saas"],
        ["Nephew", "بھانجا", "bhaanja"],
        ["Niece", "بھانجی", "bhaanji"],
        ["Cousin", "کزن / چچا زاد", "cousin"],
        ["Friend", "دوست", "dost"],
    ],
    600: [
        ["One", "ایک", "ek"],
        ["Two", "دو", "do"],
        ["Three", "تین", "teen"],
        ["Four", "چار", "chaar"],
        ["Five", "پانچ", "paanch"],
        ["Six", "چھ", "chh"],
        ["Seven", "سات", "saat"],
        ["Eight", "آٹھ", "aaṭh"],
        ["Nine", "نو", "nau"],
        ["Ten", "دس", "das"],
        ["Eleven", "گیارہ", "gyaarah"],
        ["Twelve", "بارہ", "baarah"],
        ["Thirteen", "تیرہ", "teerah"],
        ["Fourteen", "چودہ", "chaudah"],
        ["Fifteen", "پندرہ", "pandrah"],
        ["Sixteen", "سولہ", "solah"],
        ["Seventeen", "سترہ", "satrah"],
        ["Eighteen", "اٹھارہ", "aṭhaarah"],
        ["Nineteen", "انیس", "unees"],
        ["Twenty", "بیس", "bees"],
    ],
    601: [
        ["Twenty-one", "اکیس", "ikkis"],
        ["Thirty", "تیس", "tees"],
        ["Forty", "چالیس", "chaalees"],
        ["Fifty", "پچاس", "pachaas"],
        ["Sixty", "ساٹھ", "saath"],
        ["Seventy", "ستر", "sattar"],
        ["Eighty", "اسی", "assi"],
        ["Ninety", "نوے", "nave"],
        ["One hundred", "سو", "sau"],
        ["Two hundred", "دو سو", "do sau"],
        ["One thousand", "ایک ہزار", "ek hazaar"],
        ["Ten thousand", "دس ہزار", "das hazaar"],
        ["One lakh", "ایک لاکھ", "ek laakh"],
        ["One crore", "ایک کروڑ", "ek karoṛ"],
        ["First", "پہلا", "pehla"],
        ["Second", "دوسرا", "doosra"],
        ["Third", "تیسرا", "teesra"],
        ["Last", "آخری", "aakhiri"],
        ["Next", "اگلا", "agla"],
        ["Previous", "پچھلا", "pichhla"],
    ],
    602: [
        ["Half", "آدھا", "aadha"],
        ["Quarter", "چوتھائی", "chauthaai"],
        ["One third", "ایک تہائی", "ek tihaai"],
        ["Percent", "فیصد", "fee s'd"],
        ["Double", "دوگنا", "doguna"],
        ["Twice", "دو بار", "do baar"],
        ["Thrice", "تین بار", "teen baar"],
        ["Sequence", "ترتیب", "tarteeb"],
        ["Number one", "نمبر ایک", "number ek"],
        ["Page five", "صفحہ پانچ", "safha paanch"],
        ["Row", "قطار", "qataar"],
        ["Pair", "جوڑا", "joraa"],
        ["Single", "اکیلا", "akeela"],
        ["Even number", "جفت عدد", "juft adad"],
        ["Odd number", "طاق عدد", "taaq adad"],
        ["Average", "اوسط", "ausat"],
        ["Total", "کل", "kul"],
        ["Remainder", "باقی", "baaqi"],
        ["Approximately", "تقریباً", "taqreeban"],
        ["Exact", "بالکل درست", "bilqul durust"],
    ],
    603: [
        ["to go", "جانا", "jaana"],
        ["to come", "آنا", "aana"],
        ["to eat", "کھانا", "khaana"],
        ["to drink", "پینا", "peena"],
        ["to sleep", "سونا", "sona"],
        ["to wake", "جاگنا", "jaagna"],
        ["to sit", "بیٹھنا", "baithna"],
        ["to stand", "کھڑا ہونا", "khaṛa hona"],
        ["to walk", "چلنا", "chalna"],
        ["to run", "دوڑنا", "doṛna"],
        ["to see", "دیکھنا", "dekhna"],
        ["to hear", "سننا", "sunna"],
        ["to speak", "بولنا", "bolna"],
        ["to read", "پڑھنا", "padhna"],
        ["to write", "لکھنا", "likhna"],
        ["to learn", "سیکھنا", "seekhna"],
        ["to teach", "پڑھانا", "padhaana"],
        ["to give", "دینا", "dena"],
        ["to take", "لینا", "lena"],
        ["to buy", "خریدنا", "khareedna"],
    ],
    604: [
        ["to sell", "بیچنا", "bechna"],
        ["to open", "کھولنا", "kholna"],
        ["to close", "بند کرنا", "band karna"],
        ["to start", "شروع کرنا", "shuru karna"],
        ["to finish", "ختم کرنا", "khatm karna"],
        ["to help", "مدد کرنا", "madad karna"],
        ["to ask", "پوچھنا", "poochna"],
        ["to answer", "جواب دینا", "jawaab dena"],
        ["to think", "سوچنا", "sochna"],
        ["to understand", "سمجھنا", "samajhna"],
        ["to forget", "بھولنا", "bhoolna"],
        ["to remember", "یاد رکھنا", "yaad rakhna"],
        ["to like", "پسند کرنا", "pasand karna"],
        ["to love", "محبت کرنا", "mohabbat karna"],
        ["to hate", "نفرت کرنا", "nafrat karna"],
        ["to wait", "انتظار کرنا", "intizaar karna"],
        ["to try", "کوشش کرنا", "koshish karna"],
        ["to use", "استعمال کرنا", "istemaal karna"],
        ["to wash", "دھونا", "dhona"],
        ["to cook", "پکانا", "pakaana"],
    ],
    605: [
        ["to clean", "صفائی کرنا", "safaai karna"],
        ["to cut", "کاٹنا", "kaaṭna"],
        ["to break", "توڑنا", "toṛna"],
        ["to mend", "مرمت کرنا", "marammat karna"],
        ["to send", "بھیجنا", "bhejna"],
        ["to receive", "وصول کرنا", "wusool karna"],
        ["to pay", "ادا کرنا", "ada karna"],
        ["to borrow", "ادھار لینا", "udhaar lena"],
        ["to return", "واپس کرنا", "waapas karna"],
        ["to call", "بلانا", "bulaana"],
        ["to meet", "ملنا", "milna"],
        ["to leave", "جانا / چھوڑنا", "jaana / chhorna"],
        ["to arrive", "پہنچنا", "pahunchna"],
        ["to stay", "رہنا", "rehna"],
        ["to live", "رہنا / زندہ ہونا", "rehna / zinda hona"],
        ["to die", "مرنا", "marna"],
        ["to play", "کھیلنا", "khelna"],
        ["to sing", "گانا", "gaana"],
        ["to dance", "ناچنا", "naachna"],
        ["to swim", "تیرنا", "tairna"],
    ],
    606: [
        ["to drive", "چلانا", "chalaana"],
        ["to fly", "اڑنا", "uṛna"],
        ["to fall", "گرنا", "girna"],
        ["to climb", "چڑھنا", "chaṛhna"],
        ["to carry", "اٹھانا", "uthaana"],
        ["to push", "دھکیلنا", "dhakelna"],
        ["to pull", "کھینچنا", "kheenchana"],
        ["to throw", "پھینکنا", "pheinkna"],
        ["to catch", "پکڑنا", "pakṛna"],
        ["to hold", "پکڑے رکھنا", "pakṛe rakhna"],
        ["to build", "بنانا", "banaana"],
        ["to dig", "کھودنا", "khodna"],
        ["to plant", "لگانا", "lagaana"],
        ["to grow", "اُگنا", "ugna"],
        ["to choose", "چننا", "chunna"],
        ["to change", "بدلنا", "badalna"],
        ["to turn", "مڑنا", "muṛna"],
        ["to stop", "رکنا", "rukna"],
        ["to continue", "جاری رکھنا", "jaari rakhna"],
        ["to repeat", "دہرانا", "dohraana"],
    ],
    607: [
        ["to give — دینا (give grant)", "دینا", "dena"],
        ["to take — لینا (take receive)", "لینا", "lena"],
        ["Give me water", "پانی دو", "paani do"],
        ["Take this book", "یہ کتاب لو", "yeh kitaab lo"],
        ["He gave a speech", "اس نے تقریر کی", "us ne taqreer ki"],
        ["Take care", "خیال رکھنا", "khayaal rakhna"],
        ["It takes time", "وقت لگتا ہے", "waqt lagta hai"],
        ["Give up — ہار ماننا", "ہار ماننا", "haar maanna"],
        ["Take part — حصّہ لینا", "حصّہ لینا", "hissa lena"],
        ["Give way — راستہ دینا", "راستہ دینا", "raasta dena"],
        ["Take away — لے جانا", "لے جانا", "le jaana"],
        ["Idiomatic pairs", "محاورے والے جوڑے", "mahaawre waale jore"],
        ["Context fixes meaning", "سیاق سے معنی", "siyaq se maani"],
        ["Practice sentences", "جملے", "jumle"],
        ["Review", "دہرائیں", "dohraayein"],
    ],
    608: [
        ["to feel — لگنا (lagna feel)", "لگنا", "lagna"],
        ["to seem — لگنا (seem)", "لگنا", "lagna"],
        ["It seems good", "اچھا لگتا ہے", "achchha lagta hai"],
        ["I feel cold", "مجھے سردی لگ رہی ہے", "mujhe sardi lag rahi hai"],
        ["This looks expensive", "یہ مہنگا لگتا ہے", "yeh mehnga lagta hai"],
        ["Attach to body / sense", "جسم / حِس سے", "jism / hiss se"],
        ["lagna + ko dative", "کو لگنا", "ko lagna"],
        ["Compare: محسوس کرنا", "محسوس کرنا", "mehsoos karna"],
        ["Colloquial: کیا لگا؟", "کیا لگا؟", "kya laga?"],
        ["Different from 'touch'", "چھونے سے فرق", "chhoone se farq"],
        ["Practice", "مشق", "mashq"],
        ["Review", "دہرائیں", "dohraayein"],
    ],
    609: [
        ["big", "بڑا", "baṛa"],
        ["small", "چھوٹا", "chhota"],
        ["good", "اچھا", "achchha"],
        ["bad", "برا", "bura"],
        ["new", "نیا", "naya"],
        ["old", "پرانا", "puraana"],
        ["hot", "گرم", "garm"],
        ["cold", "ٹھنڈا", "thanda"],
        ["easy", "آسان", "asaan"],
        ["difficult", "مشکل", "mushkil"],
        ["beautiful", "خوبصورت", "khoobsurat"],
        ["ugly", "بدصورت", "badsurat"],
        ["clean", "صاف", "saaf"],
        ["dirty", "گندا", "ganda"],
        ["heavy", "بھاری", "bhaari"],
        ["light (weight)", "ہلکا", "halka"],
        ["long", "لمبا", "lamba"],
        ["short", "چھوٹا", "chhota"],
        ["wide", "چوڑا", "chauṛa"],
        ["narrow", "تنگ", "tang"],
    ],
    610: [
        ["quickly", "جلدی سے", "jaldi se"],
        ["slowly", "آہستہ", "aahista"],
        ["always", "ہمیشہ", "hamesha"],
        ["never", "کبھی نہیں", "kabhi nahin"],
        ["often", "اکثر", "aksar"],
        ["sometimes", "کبھی کبھی", "kabhi kabhi"],
        ["today", "آج", "aaj"],
        ["tomorrow", "کل", "kal"],
        ["yesterday", "کل", "kal"],
        ["now", "اب", "ab"],
        ["then", "پھر", "phir"],
        ["early", "جلدی", "jaldi"],
        ["late", "دیر سے", "der se"],
        ["together", "ایک ساتھ", "ek saath"],
        ["alone", "اکیلے", "akele"],
        ["here", "یہاں", "yahaan"],
        ["there", "وہاں", "wahaan"],
        ["everywhere", "ہر جگہ", "har jagah"],
        ["nowhere", "کہیں نہیں", "kahin nahin"],
        ["upstairs", "اوپر", "oopar"],
    ],
    611: [
        ["downstairs", "نیچے", "neeche"],
        ["inside", "اندر", "andar"],
        ["outside", "باہر", "baahar"],
        ["far", "دور", "door"],
        ["near", "قریب", "qareeb"],
        ["very", "بہت", "bohat"],
        ["too much", "بہت زیادہ", "bohat zyada"],
        ["little", "تھوڑا", "thoda"],
        ["enough", "کافی", "kaafi"],
        ["maybe", "شاید", "shayad"],
        ["certainly", "یقیناً", "yaqeenan"],
        ["probably", "غالباً", "ghaaliban"],
        ["suddenly", "اچانک", "achaanak"],
        ["finally", "آخرکار", "aakhirkaar"],
        ["already", "پہلے سے", "pehle se"],
        ["yet", "ابھی تک", "abhi tak"],
        ["again", "پھر", "phir"],
        ["once", "ایک بار", "ek baar"],
        ["twice", "دو بار", "do baar"],
        ["daily", "روزانہ", "rozaana"],
    ],
    612: [
        ["Potato", "آلو", "aaloo"],
        ["Onion", "پیاز", "piyaaz"],
        ["Tomato", "ٹماٹر", "tamaaṭar"],
        ["Brinjal", "بینگن", "baingan"],
        ["Cauliflower", "پھول گوبھی", "phool gobhi"],
        ["Cabbage", "بند گوبھی", "band gobhi"],
        ["Spinach", "پالک", "paalak"],
        ["Carrot", "گاجر", "gaajar"],
        ["Radish", "مولی", "mooli"],
        ["Cucumber", "کھیرا", "kheera"],
        ["Pumpkin", "کدو", "kaddu"],
        ["Ladyfinger", "بھنڈی", "bhindi"],
        ["Peas", "مٹر", "maṭar"],
        ["Beans", "پھلی", "phali"],
        ["Garlic", "لہسن", "lehsan"],
        ["Ginger", "ادرک", "adrak"],
        ["Green chilli", "ہری مرچ", "hari mirch"],
        ["Coriander", "دھنیا", "dhaniya"],
        ["Mint", "پودینہ", "podeena"],
        ["Lemon", "لیموں", "leemu"],
    ],
    613: [
        ["Mango", "آم", "aam"],
        ["Banana", "کیلا", "keela"],
        ["Apple", "سیب", "seb"],
        ["Orange", "سنترا", "santra"],
        ["Grapes", "انگور", "angoor"],
        ["Watermelon", "تربوز", "tarbooz"],
        ["Melon", "خربوزہ", "kharbooza"],
        ["Papaya", "پپیتا", "papeeta"],
        ["Guava", "امرود", "amrood"],
        ["Pomegranate", "انار", "anaar"],
        ["Pear", "ناشپاتی", "naashpaati"],
        ["Peach", "آڑو", "aṛoo"],
        ["Cherry", "چیری", "cherry"],
        ["Sweet", "میٹھا", "meetha"],
        ["Sour", "کھٹا", "khaṭṭa"],
        ["Ripe", "پکا", "paka"],
        ["Raw", "کچا", "kachcha"],
        ["Juice", "رس / جوس", "rus / juice"],
        ["Fruit seller", "فروٹ والا", "fruit waala"],
        ["Seasonal fruits", "موسمی پھل", "mausami phal"],
    ],
    614: [
        ["Crow", "کوا", "kauwa"],
        ["Sparrow", "چڑیا", "chiriya"],
        ["Pigeon", "کبوتر", "kabootar"],
        ["Parrot", "طوطا", "tootaa"],
        ["Eagle", "عقاب", "uqaab"],
        ["Peacock", "مور", "mor"],
        ["Duck", "بطخ", "batakh"],
        ["Hen", "مرغی", "murghi"],
        ["Rooster", "مرغا", "murgha"],
        ["Swan", "ہنس", "hans"],
        ["Owl", "الو", "ullu"],
        ["Woodpecker", "کٹھ پھوڑوا", "kaṭh phoṛwa"],
        ["Koel", "کوئل", "koyal"],
        ["Nest", "گھونسلا", "ghonsla"],
        ["Wing", "پر", "par"],
        ["Beak", "چونچ", "chonch"],
        ["Feather", "پر", "par"],
        ["Sky bird", "آسمان پرندہ", "aasamaan parinda"],
        ["Chirp", "چہچہانا", "chehchahaana"],
        ["Fly", "اُڑنا", "uṛna"],
    ],
    615: [
        ["Ant", "چیونٹی", "cheenti"],
        ["Bee", "مکھی", "makhi"],
        ["Fly (insect)", "مکھی", "makhi"],
        ["Mosquito", "مچھر", "machchhar"],
        ["Butterfly", "تتلی", "titli"],
        ["Spider", "مکڑی", "makṛi"],
        ["Cockroach", "علاقہ / کاکروچ", "cockroach"],
        ["Worm", "کیڑا", "keṛa"],
        ["Louse", "جوئیں", "juein"],
        ["Bedbug", "کھٹمل", "khaṭmal"],
        ["Snail", "گھونگا", "ghoṅga"],
        ["Grasshopper", "ٹڈا", "ṭiḍda"],
        ["Insect", "کیڑا", "keṛa"],
        ["Bite", "کاٹنا", "kaaṭna"],
        ["Sting", "ڈنک", "ḍank"],
        ["Hive", "چھتّا", "chhaṭṭa"],
        ["Honey", "شہد", "shehad"],
        ["Pest", "آفت", "aafat"],
        ["Spray", "چھڑکاؤ", "chhiṛkaa'o"],
        ["Net", "جالی", "jaali"],
    ],
    616: [
        ["Red", "لال", "laal"],
        ["Blue", "نیلا", "neela"],
        ["Green", "ہرا", "hara"],
        ["Yellow", "پیلا", "peela"],
        ["Black", "کالا", "kaala"],
        ["White", "سفید", "safed"],
        ["Brown", "بھورا", "bhoora"],
        ["Orange (colour)", "نارنجی", "naaranji"],
        ["Pink", "گلابی", "gulaabi"],
        ["Purple", "جامنی", "jaamni"],
        ["Grey", "سرمئی", "surmai"],
        ["Golden", "سنہرا", "sunahra"],
        ["Silver", "چاندی جیسا", "chaandi jaisa"],
        ["Dark", "گہرا", "gehra"],
        ["Light (colour)", "ہلکا", "halka"],
        ["Bright", "چمکیلا", "chamkeela"],
        ["Pale", "پھیکا", "pheeka"],
        ["Colour", "رنگ", "rang"],
        ["Paint", "رنگ کرنا", "rang karna"],
        ["Rainbow", "قوسِ قزح", "qaus-e quzah"],
    ],
    617: [
        ["Rose", "گلاب", "gulaab"],
        ["Jasmine", "چنبیلی", "chanbeli"],
        ["Marigold", "گیندا", "gainda"],
        ["Lotus", "کنول", "kanwal"],
        ["Sunflower", "سورج مکھی", "sooraj makhi"],
        ["Hibiscus", "گُڑھل", "guṛhal"],
        ["Chrysanthemum", "گُلِ داؤدی", "gul-e daudi"],
        ["Lily", "نرگس", "nargis"],
        ["Tulip", "ٹیولپ", "tulip"],
        ["Petals", "پنکھڑی", "pankhaṛi"],
        ["Fragrance", "خوشبو", "khushboo"],
        ["Thorn", "کانٹا", "kaanṭa"],
        ["Garden", "باغ", "baagh"],
        ["Vase", "گلدان", "guldaan"],
        ["Bouquet", "گلدستہ", "guldasta"],
        ["Wild flower", "جنگلی پھول", "jangli phool"],
        ["Bloom", "کھلنا", "khilna"],
        ["Wilt", "مرجھانا", "murjhaana"],
        ["Pollen", "پراغ", "paraagh"],
        ["Florist", "پھول بیچنے والا", "phool bechne wala"],
    ],
    618: [
        ["Dog", "کتا", "kutta"],
        ["Cat", "بلی", "billi"],
        ["Cow", "گائے", "gaaye"],
        ["Buffalo", "بھینس", "bhains"],
        ["Goat", "بکری", "bakri"],
        ["Sheep", "بھیڑ", "bheṛ"],
        ["Horse", "گھوڑا", "ghoṛa"],
        ["Donkey", "گدھا", "gadha"],
        ["Camel", "اونٹ", "oṅṭ"],
        ["Elephant", "ہاتھی", "haathi"],
        ["Lion", "شیر", "sher"],
        ["Tiger", "چیتا", "cheeta"],
        ["Monkey", "بندر", "bandar"],
        ["Rabbit", "خرگوش", "khargosh"],
        ["Rat", "چوہا", "chuhaa"],
        ["Snake", "سانپ", "saanp"],
        ["Frog", "مینڈک", "meṇḍak"],
        ["Fish", "مچھلی", "machhli"],
        ["Tail", "دُم", "dum"],
        ["Horn", "سینگ", "seeng"],
    ],
    619: [
        ["Thing", "چیز", "cheez"],
        ["Place", "جگہ", "jagah"],
        ["Time", "وقت", "waqt"],
        ["Work", "کام", "kaam"],
        ["Problem", "مسئلہ", "masla"],
        ["Idea", "خیال", "khayaal"],
        ["Reason", "وجہ", "wajah"],
        ["Result", "نتیجہ", "nateeja"],
        ["News", "خبر", "khabar"],
        ["Story", "کہانی", "kahaani"],
        ["Question", "سوال", "sawaal"],
        ["Answer", "جواب", "jawaab"],
        ["Name", "نام", "naam"],
        ["Address", "پتہ", "pata"],
        ["Money", "پیسہ", "paisa"],
        ["Price", "قیمت", "qeemat"],
        ["Size", "سائز / قد", "size / qad"],
        ["Weight", "وزن", "wazan"],
        ["Shape", "شکل", "shakl"],
        ["Kind / type", "قسم", "qism"],
    ],
}
