# Urdu Lesson 3 — Phrases chunk B (chapter IDs 566–596).

LESSONS_S3B = {
    566: [
        ["I want you to read this page before we discuss it in class.", "میں چاہتا ہوں کہ تم اس صفحے کو کلاس میں بات کرنے سے پہلے پڑھ لو", "main chahta hoon ke tum is safhe ko class mein baat karne se pehle padh lo"],
        ["She wants them to leave quietly so the baby can sleep.", "وہ چاہتی ہے کہ وہ خاموشی سے چلے جائیں تاکہ بچہ سو سکے", "woh chahti hai ke woh khamoshi se chale jaayein taake bachcha so sake"],
        ["We want the teacher to explain the grammar rule one more time.", "ہم چاہتے ہیں کہ استاد یہ گرامر کا قاعدہ ایک بار پھر سمجھائیں", "hum chahte hain ke ustaad yeh grammar ka qaaida ek baar phir samjhaayein"],
        ["My parents want me to call them every Sunday evening.", "میرے والدین چاہتے ہیں کہ میں ہر اتوار شام انہیں فون کروں", "mere walideen chahte hain ke main har itwaar shaam unhein phone karoon"],
        ["I do not want anyone to feel embarrassed in the meeting.", "میں نہیں چاہتا کہ میٹنگ میں کسی کو شرمندگی محسوس ہو", "main nahin chahta ke meeting mein kisi ko sharmindagi mehsoos ho"],
        ["They wanted us to wait outside until the guests arrived.", "انہوں نے چاہا کہ ہم باہر انتظار کریں جب تک مہمان نہ آ جائیں", "unhon ne chaha ke hum bahar intizaar karein jab tak mehmaan na aa jaayein"],
        ["The manager wants the report finished by Friday afternoon.", "مینیجر چاہتا ہے کہ رپورٹ جمعے کی دوپہر تک مکمل ہو جائے", "manager chahta hai ke report jum'ey ki dopehar tak mukammal ho jaaye"],
        ["We politely want you to review these notes at home.", "ہم مہذب طریقے سے چاہتے ہیں کہ آپ یہ نوٹس گھر پر دیکھ لیں", "hum muazzab tareeqe se chahte hain ke aap yeh notes ghar par dekh lein"],
        ["She wanted her brother to help her carry the heavy bags.", "وہ چاہتی تھی کہ اس کا بھائی اسے بھاری تھیلے اٹھانے میں مدد کرے", "woh chahti thi ke us ka bhai use bhari thaile uthane mein madad kare"],
        ["I want my friend to know that I am grateful for his support.", "میں چاہتا ہوں کہ میرا دوست جانے کہ میں اس کی حمایت کا شکر گزار ہوں", "main chahta hoon ke mera dost jaane ke main us ki himaayat ka shukr guzaar hoon"],
        ["Children often want their parents to stay a little longer at bedtime.", "بچے اکثر چاہتے ہیں کہ والدین سونے کے وقت تھوڑی دیر اور رکیں", "bachche aksar chahte hain ke walideen sone ke waqt thodi der aur rukein"],
        ["He wants the driver to take the shorter route through the city.", "وہ چاہتا ہے کہ ڈرائیور شہر کے اندر سے مختصر راستہ لے", "woh chahta hai ke driver sheher ke andar se mukhtasar rasta le"],
        ["We do not want the news to spread before the official announcement.", "ہم نہیں چاہتے کہ سرکاری اعلان سے پہلے خبر پھیل جائے", "hum nahin chahte ke sarkari elaan se pehle khabar pheil jaaye"],
        ["I wanted her to understand that my answer was honest.", "میں چاہتا تھا کہ وہ سمجھے کہ میرا جواب صاف دل سے تھا", "main chahta tha ke woh samjhe ke mera jawaab saaf dil se tha"],
        ["They want everyone to wear a name tag at the workshop.", "وہ چاہتے ہیں کہ ورکشاپ میں ہر شخص نام کی پٹی پہنے", "woh chahte hain ke workshop mein har shakhs naam ki patti pehne"],
        ["The teacher wants the students to ask questions without fear.", "استاد چاہتے ہیں کہ طلبہ بغیر خوف کے سوالات پوچھیں", "ustaad chahte hain ke talba baghair khauf ke sawaalat poochhein"],
        ["I want you to remember that we can always change the plan.", "میں چاہتا ہوں کہ تم یاد رکھو کہ ہم منصوبہ ہمیشہ بدل سکتے ہیں", "main chahta hoon ke tum yaad rakho ke hum mansooba hamesha badal sakte hain"],
    ],
    567: [
        ["I am supposed to call my mother before eight tonight.", "مجھے آج رات آٹھ بجے سے پہلے اپنی ماں کو فون کرنا ہے", "mujhe aaj raat aath baje se pehle apni maan ko phone karna hai"],
        ["You were supposed to be here when the meeting started.", "آپ کا یہاں ہونا تھا جب میٹنگ شروع ہوئی", "aap ka yahaan hona tha jab meeting shuroo hui"],
        ["We were supposed to submit the form before the deadline.", "ہمیں آخری تاریخ سے پہلے فارم جمع کرانا تھا", "hamein aakhri tareekh se pehle form jama karana tha"],
        ["The train was supposed to arrive on time, but it was delayed.", "ٹرین کا وقت پر آنا تھا مگر وہ تاخیر کا شکار ہو گئی", "train ka waqt par aana tha magar woh takheer ka shikaar ho gayi"],
        ["It was supposed to rain, so we carried umbrellas.", "بارش کا ہونا تھا اس لیے ہم چھتیاں لے کر آئے", "baarish ka hona tha is liye hum chhatiyaan le kar aaye"],
        ["They were supposed to send the email yesterday afternoon.", "ان کا کل دوپہر ای میل بھیجنا تھا", "unka kal dopehar email bhejna tha"],
        ["I am supposed to meet the doctor at ten in the morning.", "مجھے صبح دس بجے ڈاکٹر سے ملنا ہے", "mujhe subah das baje doctor se milna hai"],
        ["You are not supposed to use your phone during the exam.", "آپ کا امتحان کے دوران فون استعمال کرنا مناسب نہیں", "aap ka imtihaan ke dauraan phone istemaal karna munasib nahin"],
        ["He was supposed to pick us up, but his car broke down.", "اس کا ہمیں لینے آنا تھا مگر اس کی گاڑی خراب ہو گئی", "us ka hamein lene aana tha magar us ki gaari kharab ho gayi"],
        ["The guests were supposed to stay for dinner, but they left early.", "مہمانوں کا رات کے کھانے تک رکنا تھا مگر وہ جلدی چلے گئے", "mehmaanon ka raat ke khaane tak rukna tha magar woh jaldi chale gaye"],
        ["I am supposed to finish this chapter before the weekend.", "مجھے ہفتے کے آخر سے پہلے یہ باب ختم کرنا ہے", "mujhe hafte ke aakhir se pehle yeh baab khatam karna hai"],
        ["She is supposed to reply to every message within one day.", "اسے ہر پیغام کا ایک دن میں جواب دینا چاہیے", "use har paighaam ka ek din mein jawaab dena chahiye"],
        ["We were supposed to save money for the trip next month.", "ہمیں اگلے مہینے سفر کے لیے پیسے بچانے تھے", "hamein agle mahine safar ke liye paise bachane the"],
        ["The package was supposed to arrive today, not next week.", "پارسل کا آج آنا تھا اگلے ہفتے نہیں", "parcel ka aaj aana tha agle hafte nahin"],
        ["I am supposed to wear formal clothes at the ceremony.", "مجھے تقریب میں رسمی کپڑے پہننے ہیں", "mujhe taqreeb mein rasmi kapre pehnne hain"],
        ["You were supposed to tell me if the plan changed.", "آپ کا مجھے بتانا تھا اگر منصوبہ بدل گیا", "aap ka mujhe batana tha agar mansooba badal gaya"],
        ["They are supposed to clean the hall before the event begins.", "ان کا ہال کو تقریب شروع ہونے سے پہلے صاف کرنا ہے", "unka hall ko taqreeb shuroo hone se pehle saaf karna hai"],
    ],
    568: [
        ["I like to read novels when I have free time in the evening.", "مجھے شام کو فرصت ملے تو ناول پڑھنا پسند ہے", "mujhe shaam ko fursat mile to navel padhna pasand hai"],
        ["She likes walking in the park early in the morning.", "اسے صبح سویرے پارک میں چلنا پسند ہے", "use subah sowere park mein chalna pasand hai"],
        ["We enjoy cooking together on weekends for the whole family.", "ہمیں ہفتے کے آخر میں پورے خاندان کے لیے ساتھ کھانا بنانا پسند ہے", "hamein hafte ke aakhir mein poore khaandaan ke liye saath khaana banana pasand hai"],
        ["He does not like to wait in long lines at the bank.", "اسے بینک میں لمبی قطار میں انتظار پسند نہیں", "use bank mein lambi qataar mein intizaar pasand nahin"],
        ["I prefer tea to coffee on cold winter mornings.", "مجھے سرد صبحوں میں چائے کافی سے زیادہ پسند ہے", "mujhe sard subhon mein chaaye kaafi se zyada pasand hai"],
        ["They would rather stay home than go out in heavy rain.", "وہ بھاری بارش میں باہر جانے سے گھر رہنا زیادہ پسند کرتے ہیں", "woh bhari baarish mein bahar jaane se ghar rehna zyada pasand karte hain"],
        ["Children like games that make them laugh and run.", "بچوں کو ایسے کھیل پسند ہیں جن سے وہ ہنستے اور دوڑتے ہیں", "bachchon ko aise khel pasand hain jin se woh hansate aur daudte hain"],
        ["I like to listen to soft music while I study.", "مجھے پڑھتے وقت ہلکی موسیقی سننا پسند ہے", "mujhe padhte waqt halki mausiqi sunna pasand hai"],
        ["She likes to paint flowers and landscapes in bright colours.", "اسے چمکدار رنگوں میں پھول اور مناظر بنانا پسند ہے", "use chamakdaar rangon mein phool aur manazir banana pasand hai"],
        ["We do not like crowded places when we feel tired.", "ہم تھکے ہوئے ہوں تو بھیڑ والی جگہیں پسند نہیں کرتے", "hum thake hue hon to bheed wali jagahain pasand nahin karte"],
        ["He likes playing cricket with his cousins on holidays.", "اسے چھٹیوں میں کزنز کے ساتھ کرکٹ کھیلنا پسند ہے", "use chuttiyon mein cousins ke saath cricket khelna pasand hai"],
        ["I enjoy learning new words and using them in sentences.", "مجھے نئے الفاظ سیکھ کر جملوں میں استعمال کرنا پسند ہے", "mujhe naye alfaaz seekh kar jumlon mein istemaal karna pasand hai"],
        ["They like spicy food, but their grandmother prefers mild dishes.", "انہیں تیز مسالے والا کھانا پسند ہے مگر دادی ہلکا کھانا پسند کرتی ہیں", "unhein tez masale wala khaana pasand hai magar daadi halka khaana pasand karti hain"],
        ["I used to like swimming every summer when we lived near the sea.", "مجھے ہر گرمی تیراکی پسند تھی جب ہم سمندر کے پاس رہتے تھے", "mujhe har garmi tairaki pasand thi jab hum samandar ke paas rehte the"],
        ["She likes quiet cafés where she can read without noise.", "اسے خاموش کیفے پسند ہیں جہاں بغیر شور کے پڑھ سکے", "use khamosh café pasand hain jahan baghair shor ke padh sake"],
        ["We like to invite friends for dinner on special occasions.", "ہم خاص موقع پر دوستوں کو رات کے کھانے پر بلانا پسند کرتے ہیں", "hum khaas mauqe par doston ko raat ke khaane par bulana pasand karte hain"],
        ["I like honest people who say what they mean clearly.", "مجھے صاف گو لوگ پسند ہیں جو واضح بات کریں", "mujhe saaf go log pasand hain jo waazeh baat karein"],
    ],
    569: [
        ["I trust you because you have never broken a promise.", "میں آپ پر بھروسہ کرتا ہوں کیونکہ آپ نے کبھی وعدہ نہیں توڑا", "main aap par bharosa karta hoon kyunke aap ne kabhi vaada nahin toda"],
        ["She depends on him to drive her to work every day.", "وہ روز کام پر لے جانے کے لیے اس پر منحصر ہے", "woh roz kaam par le jaane ke liye us par munhasir hai"],
        ["We believe in hard work more than luck alone.", "ہم محنت پر صرف قسمت سے زیادہ یقین رکھتے ہیں", "hum mehnat par sirf qismat se zyada yaqeen rakhte hain"],
        ["You can rely on this map; it shows every small street.", "آپ اس نقشے پر بھروسہ کر سکتے ہیں یہ ہر چھوٹی گلی دکھاتا ہے", "aap is naqshe par bharosa kar sakte hain yeh har chhoti gali dikhata hai"],
        ["I agree with this idea, but we should test it first.", "میں اس خیال سے متفق ہوں مگر پہلے آزمانا چاہیے", "main is khayaal se muttafiq hoon magar pehle aazmana chahiye"],
        ["She is angry at him for forgetting her birthday.", "وہ اس پر اس کے سالگرہ بھولنے سے ناراض ہے", "woh us par us ke saalgirah bhoolne se naraz hai"],
        ["He is proud of his daughter for winning the science prize.", "وہ اپنی بیٹی پر سائنس کا انعام جیتنے پر فخر کرتا ہے", "woh apni beti par science ka inaam jeetne par fakhr karta hai"],
        ["Do not laugh at someone who is trying to learn.", "کسی پر مت ہنسو جو سیکھنے کی کوشش کر رہا ہو", "kisi par mat hanso jo seekhne ki koshish kar raha ho"],
        ["Think about your health before you skip meals every day.", "روزانہ کھانا چھوڑنے سے پہلے اپنی صحت کے بارے میں سوچیں", "rozana khaana chhodne se pehle apni sehat ke baare mein sochein"],
        ["I disagree with the plan to close the library early.", "میں لائبریری جلدی بند کرنے کے منصوبے سے متفق نہیں", "main library jaldi band karne ke mansoobe se muttafiq nahin"],
        ["They depend on rain for their crops in this village.", "اس گاؤں میں فصلوں کے لیے بارش پر انحصار ہے", "is gaon mein faslon ke liye baarish par inhisar hai"],
        ["She believes in speaking politely even when she is upset.", "وہ یقین رکھتی ہے کہ ناراض ہو کر بھی مہذب بولنا چاہیے", "woh yaqeen rakhti hai ke naraz ho kar bhi muazzab bolna chahiye"],
        ["We rely on our friends when life becomes difficult.", "زندگی مشکل ہو تو ہم دوستوں پر بھروسہ کرتے ہیں", "zindagi mushkil ho to hum doston par bharosa karte hain"],
        ["He is proud of his team for finishing the project on time.", "وہ اپنی ٹیم پر وقت پر منصوبہ ختم کرنے پر فخر کرتا ہے", "woh apni team par waqt par mansooba khatam karne par fakhr karta hai"],
        ["I trust this doctor because she explains everything clearly.", "میں اس ڈاکٹر پر بھروسہ کرتا ہوں کیونکہ وہ سب کچھ صاف بتلاتی ہیں", "main is doctor par bharosa karta hoon kyunke woh sab kuch saaf batlati hain"],
        ["They are angry at the company for changing the rules suddenly.", "وہ اچانک قوانین بدلنے پر کمپنی سے ناراض ہیں", "woh achanak qawaneen badalne par company se naraz hain"],
        ["Think about how your words might hurt a sensitive child.", "سوچیں کہ آپ کے الفاظ حساس بچے کو کیسے تکلیف دیں", "sochen ke aap ke alfaaz hassas bachche ko kaise takleef dein"],
    ],
    570: [
        ["What are you doing right now at your desk?", "ابھی اپنی میز پر کیا کر رہے ہو؟", "abhi apni mez par kya kar rahe ho?"],
        ["I am gonna leave in five minutes if the bus comes.", "اگر بس آ گئی تو میں پانچ منٹ میں نکلنے والا ہوں", "agar bus aa gayi to main paanch minute mein nikalne wala hoon"],
        ["I wanna learn Urdu so I can talk to my neighbours.", "مجھے اردو سیکھنی ہے تاکہ پڑوسیوں سے بات کر سکوں", "mujhe Urdu seekhni hai taake parosion se baat kar sakoon"],
        ["Lemme check the time before we order food.", "کھانا منگوانے سے پہلے مجھے وقت دیکھنے دو", "khaana mangwane se pehle mujhe waqt dekhne do"],
        ["Gimme a minute; I need to find my keys.", "ایک منٹ دو مجھے چابیاں ڈھونڈنی ہیں", "ek minute do mujhe chaabiyaan dhoondni hain"],
        ["Yaar, this traffic is worse than yesterday evening.", "یار آج شام کل شام سے زیادہ ٹریفک ہے", "yaar aaj shaam kal shaam se zyada traffic hai"],
        ["Bas, we have talked enough about that old problem.", "بس اب اس پرانی مشکل کے بارے میں کافی بات ہو گئی", "bas ab us purani mushkil ke baare mein kaafi baat ho gayi"],
        ["Abhi I cannot come; I am still at the office.", "ابھی میں نہیں آ سکتا میں ابھی دفتر میں ہوں", "abhi main nahin aa sakta main abhi daftar mein hoon"],
        ["Mat open that window; the room is already cold.", "وہ کھڑکی مت کھولو کمرہ پہلے ہی ٹھنڈا ہے", "woh khidki mat kholo kamra pehle hi thanda hai"],
        ["Thik hai, we will meet at the station at six.", "ٹھیک ہے ہم چھ بجے اسٹیشن پر ملیں گے", "theek hai hum chah baje station par milenge"],
        ["In formal writing, avoid slang like gonna and wanna.", "رسمی تحریر میں گونا اور وانا جیسی بول چال سے بچیں", "rasmi tahreer mein gonna aur wanna jaisi bol chaal se bachein"],
        ["Friends use short forms, but teachers prefer full sentences.", "دوست مختصر الفاظ استعمال کرتے ہیں مگر اساتذہ مکمل جملے پسند کرتے ہیں", "dost mukhtasar alfaaz istemaal karte hain magar asaatiza mukammal jumle pasand karte hain"],
        ["What are you gonna tell your parents about the result?", "نتیجے کے بارے میں اپنے والدین کو کیا بتاؤ گے؟", "nateeje ke baare mein apne walideen ko kya bataoge?"],
        ["I wanna help, but I do not know the rules yet.", "مجھے مدد کرنی ہے مگر ابھی قوانین معلوم نہیں", "mujhe madad karni hai magar abhi qawaneen maaloom nahin"],
        ["Lemme sit here; my legs hurt after the long walk.", "مجھے یہاں بیٹھنے دو لمبی چلنے کے بعد پاؤں میں درد ہے", "mujhe yahaan baithne do lambi chalne ke baad paon mein dard hai"],
        ["Yaar, listen carefully before you sign that paper.", "یار اس کاغذ پر دستخط کرنے سے پہلے غور سے سن", "yaar is kaaghaz par dastakhat karne se pehle ghaur se sun"],
        ["Thik hai, no problem; we can try again tomorrow morning.", "ٹھیک ہے کوئی بات نہیں کل صبح دوبارہ کوشش کر سکتے ہیں", "theek hai koi baat nahin kal subah dobara koshish kar sakte hain"],
    ],
    571: [
        ["When you enter a room, say Assalamu Alaikum with a smile.", "جب کمرے میں داخل ہوں تو مسکراتے ہوئے السلام علیکم کہیں", "jab kamre mein daakhil hon to muskurate hue Assalamu Alaikum kahein"],
        ["The polite reply is Wa alaikum assalam wa rahmatullah.", "مہذب جواب وعلیکم السلام و رحمۃ اللہ ہے", "muazzab jawaab Wa alaikum assalam wa rahmatullah hai"],
        ["We said mubaarak ho when our cousin passed the exam.", "ہم نے مبارک ہو کہا جب ہمارے کزن کا امتحان پاس ہوا", "hum ne mubaarak ho kaha jab hamare cousin ka imtihaan pass hua"],
        ["Happy birthday to you; may this year bring peace.", "سالگرہ مبارک ہو امید ہے یہ سال امن لائے", "saalgirah mubaarak ho umeed hai yeh saal aman laaye"],
        ["I wrote get well soon on the card for my sick teacher.", "میں نے بیمار استاد کے کارڈ پر جلد صحت یاب ہوں لکھا", "main ne bimaar ustaad ke card par jald sehat yaab hon likha"],
        ["Good luck; may your interview go better than you expect.", "نصیب اچھا ہو تمہاری انٹرویو تمہاری توقع سے بہتر جائے", "naseeb achchha ho tumhari interview tumhari toqe'a se behtar jaaye"],
        ["On Eid we greet everyone with Eid Mubaarak and hugs.", "عید پر ہم سب کو عید مبارک کہتے اور گلے ملتے ہیں", "Eid par hum sab ko Eid Mubaarak kehte aur gale milte hain"],
        ["At the wedding we wished the couple a happy life together.", "شادی پر ہم نے جوڑے کو ساتھ خوش زندگی کی دعا دی", "shaadi par hum ne jore ko saath khush zindagi ki dua di"],
        ["We offered ta'ziyat when we heard about their grandmother's death.", "جب ان کی دادی کی وفات کی خبر ملی تو ہم نے تعزیت کی", "jab un ki daadi ki wafaat ki khabar mili to hum ne ta'ziyat ki"],
        ["After a narrow escape he whispered Alhamdulillah with relief.", "بچنے کے بعد وہ سکون سے الحمد للہ بولا", "bachne ke baad woh sukoon se Alhamdulillah bola"],
        ["Short slogans on banners should be clear and easy to read.", "بینرز پر مختصر نعرے صاف اور پڑھنے میں آسان ہونے چاہئیں", "banners par mukhtasar na'are saaf aur padhne mein aasaan hone chahiye"],
        ["Say thank you when someone opens the door for you.", "جب کوئی دروازہ کھولے تو شکریہ کہیں", "jab koi darwaza khole to shukriya kahein"],
        ["We congratulate the team loudly when they win the match.", "جب ٹیم جیتے تو ہم زور سے مبارک دیتے ہیں", "jab team jeete to hum zor se mubaarak dete hain"],
        ["Your grandmother will feel happy if you call on her birthday.", "سالگرہ پر فون کرو گے تو دادی خوش ہوں گی", "saalgirah par phone karoge to daadi khush hongi"],
        ["He sent flowers with a card that said get well soon.", "اس نے پھول بھیجے اور کارڈ پر جلد صحت یاب ہوں لکھا", "us ne phool bheje aur card par jald sehat yaab hon likha"],
        ["Before the exam, friends often say good luck to each other.", "امتحان سے پہلے دوست اکثر ایک دوسرے کو نصیب اچھا کہتے ہیں", "imtihaan se pehle dost aksar ek doosre ko naseeb achchha kehte hain"],
        ["In our street, neighbours greet each other every morning.", "ہماری گلی میں پڑوسی ہر صبح ایک دوسرے کو سلام کرتے ہیں", "hamari gali mein parosi har subah ek doosre ko salaam karte hain"],
    ],
    572: [
        ["The children ate up every sweet on the plate in minutes.", "بچوں نے منٹوں میں پلیٹ پر مٹھائیاں کھا ڈالیں", "bachchon ne minute mein plate par mithaiyaan kha daalein"],
        ["Please throw away the old newspapers from the corner.", "کونے سے پرانے اخبار پھینک دیں", "kone se purane akhbaar pheink dein"],
        ["She sat down on the bench because her feet were tired.", "اس نے بنچ پر بیٹھ گئی کیونکہ پاؤں تھک گئے تھے", "us ne bench par baith gayi kyunke paon thak gaye the"],
        ["I will dekh lena the tickets before we leave the house.", "گھر سے نکلنے سے پہلے میں ٹکٹ دیکھ لوں گا", "ghar se nikalne se pehle main ticket dekh loonga"],
        ["He kar dena the homework before dinner so he could rest.", "اس نے رات کے کھانے سے پہلے کام کر دیا تاکہ آرام کر سکے", "us ne raat ke khaane se pehle kaam kar diya taake aaraam kar sake"],
        ["We uth jaana early to catch the first bus to the city.", "ہم شہر کی پہلی بس پکڑنے کے لیے جلدی اٹھ گئے", "hum sheher ki pehli bus pakadne ke liye jaldi uth gaye"],
        ["Compound verbs add a clear result to the main action.", "مرکب فعل مرکزی عمل کا واضح نتیجہ دیتے ہیں", "murakkab fe'l markazi amal ka waazeh nateeja dete hain"],
        ["She threw away the broken toy after the child cried.", "بچے کے رونے کے بعد اس نے ٹوٹا کھلونا پھینک دیا", "bachche ke rone ke baad us ne toota khilona pheink diya"],
        ["Finish your tea; drink it up before it gets cold.", "چائے ختم کرو ٹھنڈی ہونے سے پہلے پی جاؤ", "chaaye khatam karo thandi hone se pehle pee jao"],
        ["They dekh lena the weather report every morning on TV.", "وہ ہر صبح ٹی وی پر موسم کی خبر دیکھ لیتے ہیں", "woh har subah TV par mausam ki khabar dekh lete hain"],
        ["I kar dena the dishes while you put the baby to sleep.", "تم بچے کو سلاتے رہو میں برتن کر دیتا ہوں", "tum bachche ko sulāte raho main bartan kar deta hoon"],
        ["He ate up his fear and spoke in front of the crowd.", "اس نے خوف کھا کر بھیڑ کے سامنے بولا", "us ne khauf kha kar bheer ke saamne bola"],
        ["Writers in stories use compounds to sound natural.", "کہانیوں میں لکھاری قدرتی لہجے کے لیے مرکب استعمال کرتے ہیں", "kahaaniyon mein likhaari qudrati lahje ke liye murakkab istemaal karte hain"],
        ["Please sit down; standing too long is bad for your back.", "براہ کرم بیٹھ جائیں زیادہ دیر کھڑے رہنا کمر کے لیے برا ہے", "baraahe karam baith jaayein zyada der khare rehna kamar ke liye bura hai"],
        ["We threw away doubts and started the new course together.", "ہم نے شک پھینک کر نیا کورس ساتھ شروع کیا", "hum ne shak pheink kar naya course saath shuroo kiya"],
        ["She will dekh lena whether the door is locked at night.", "وہ رات کو دروازہ بند ہے یا نہیں دیکھ لے گی", "woh raat ko darwaza band hai ya nahin dekh legi"],
        ["They kar dena a kind thing when nobody was watching.", "جب کوئی نہ دیکھ رہا تھا تب انہوں نے نیک کام کر دیا", "jab koi nahin dekh raha tha tab unhon ne nek kaam kar diya"],
    ],
    573: [
        ["My uncle from Lahore visits us every winter with gifts.", "لاہور والے چچا ہر سرما تحفے لے کر ملنے آتے ہیں", "Lahore wale chacha har sarma tohfe le kar milne aate hain"],
        ["Her aunt makes delicious biryani for the whole family.", "اس کی خالہ پورے خاندان کے لیے مزیدار بریانی بناتی ہیں", "us ki khaala poore khaandaan ke liye mazedaar biryani banati hain"],
        ["We call elder brother bhai even if he is not our real brother.", "ہم بڑے بھائی کو بھائی کہتے ہیں چاہے وہ سگا ہو یا نہیں", "hum bare bhai ko bhai kehte hain chahe woh saga ho ya nahin"],
        ["Always say aap to teachers and older neighbours.", "اساتذہ اور بڑے پڑوسیوں سے ہمیشہ آپ کہیں", "asaatiza aur bare parosion se hamesha aap kahein"],
        ["Answer with ji when someone older asks you a question.", "جب کوئی بڑا سوال پوچھے تو جی سے جواب دیں", "jab koi bara sawaal pooche to ji se jawaab dein"],
        ["The letter begins with respected sahab at the top.", "خط کے اوپر محترم صاحب لکھا جاتا ہے", "khat ke upar muhtaram sahab likha jaata hai"],
        ["We wrote to begum sahiba to invite her to the talk.", "ہم نے بیگم صاحبہ کو تقریب کی دعوت کے لیے لکھا", "hum ne begum sahiba ko taqreeb ki dawat ke liye likha"],
        ["Her father said beta softly when she felt nervous.", "جب وہ گھبرائی تو باپ نے آہستہ بیٹا کہا", "jab woh ghabrai to baap ne aahista beta kaha"],
        ["Beta ji, please pass the salt from that side.", "بیٹا جی براہ کرم اس طرف سے نمک پاس کریں", "beta ji baraahe karam us taraf se namak paas karein"],
        ["In the restaurant he called the waiter bhai sahab politely.", "ریستوران میں اس نے ویٹر کو مہذب طریقے سے بھائی صاحب کہا", "restaurant mein us ne waiter ko muazzab tareeqe se bhai sahab kaha"],
        ["A rude tone can hurt people even if your words are short.", "سخت لہجے سے الفاظ چھوٹے ہوں تو بھی لوگوں کو تکلیف ہوتی ہے", "sakht lahje se alfaaz chhote hon to bhi logon ko takleef hoti hai"],
        ["We respect chacha and mamu equally in our family stories.", "ہم اپنے خاندانی کہانیوں میں چچا اور ماموں کو برابر عزت دیتے ہیں", "hum apne khaandaani kahaaniyon mein chacha aur maamu ko barabar izzat dete hain"],
        ["Your aunt will feel happy if you help her carry bags.", "خالہ کی تھیلیاں اٹھانے میں مدد کرو گے تو خوش ہوں گی", "khaala ki thailiyaan uthane mein madad karoge to khush hongi"],
        ["Say aap when you meet your friend's parents at the door.", "دوست کے والدین دروازے پر ملیں تو آپ کہیں", "dost ke walideen darwaze par milen to aap kahein"],
        ["The teacher asked the boy to say ji before he answered.", "استاد نے لڑکے سے کہا جواب سے پہلے جی بولے", "ustaad ne larke se kaha jawaab se pehle ji bole"],
        ["Sahab, could you tell me which bus goes to the museum?", "صاحب بتائیں کون سی بس عجائب گھر جاتی ہے؟", "sahab bataein kaun si bus ajaib ghar jaati hai?"],
        ["Begum, your speech yesterday was clear and kind.", "بیگم کل آپ کا خطاب صاف اور مہربان تھا", "begum kal aap ka khitaab saaf aur mehrbaan tha"],
    ],
    574: [
        ["Wow, that mountain looks even taller in the morning light.", "واہ صبح کی روشنی میں وہ پہاڑ اور بھی اونچا لگتا ہے", "waah subah ki roshni mein woh pahaar aur bhi ooncha lagta hai"],
        ["Oh, I forgot my umbrella when the sky turned grey.", "اوہ آسمان سرمئی ہوا تو میں چھتری بھول گیا", "oh aasmaan surmai hua to main chhatri bhool gaya"],
        ["Alas, the old tree fell in last night's storm.", "ہائے پرانا درخت کل رات طوفان میں گر گیا", "haaye purana darakht kal raat toofan mein gir gaya"],
        ["Bravo, you solved the puzzle faster than everyone else.", "شاباش تم نے سب سے پہلے پہیلی حل کی", "shaabaash tum ne sab se pehle paheli hal ki"],
        ["Ouch, I touched the hot pan with my bare hand.", "آؤچ میں نے گرم تلے کو ننگے ہاتھ سے چھوا", "ouch main ne garam tale ko nange haath se chhua"],
        ["Shh, the baby is sleeping; please talk softly.", "چپ بچہ سو رہا ہے آہستہ بولیں", "chup bachcha so raha hai aahista bolein"],
        ["Hey, wait for me; I cannot run as fast as you.", "ارے میرا انتظار کرو میں تم جلدی نہیں دوڑ سکتا", "arey mera intizaar karo main tum jaldi nahin daud sakta"],
        ["So beautiful, the garden looks after the first spring rain.", "کتنا خوب پہلی بہار کی بارش کے بعد باغ لگتا ہے", "kitna khoob pehli bahaar ki baarish ke baagh lagta hai"],
        ["What a pity, the concert was cancelled because of rain.", "افسوس موسم کی وجہ سے کنسرٹ منسوخ ہو گیا", "afsos mausam ki wajah se concert mansookh ho gaya"],
        ["Thank goodness, the test result was better than we feared.", "خیر ہے امتحان کا نتیجہ ڈر سے بہتر نکلا", "khair hai imtihaan ka nateeja dar se behtar nikla"],
        ["Exclamations show strong feeling in speech and stories.", "تعجب والے جملے بول چال اور کہانیوں میں جذبات دکھاتے ہیں", "ta'ajjub wale jumle bol chaal aur kahaaniyon mein jazbaat dikhate hain"],
        ["Wow, your Urdu handwriting is neater than mine.", "واہ تمہاری اردو کی لکھائی میری سے صاف ہے", "waah tumhari Urdu ki likhai meri se saaf hai"],
        ["Oh no, the train left one minute before we arrived.", "اوہ نہیں ٹرین ایک منٹ پہلے نکل گئی", "oh nahin train ek minute pehle nikal gayi"],
        ["Bravo to the team for helping the flood victims.", "سیلاب متاثرین کی مدد پر ٹیم کو شاباش", "sailaab mutasireen ki madad par team ko shaabaash"],
        ["Ouch, my toe hit the edge of the heavy table.", "آؤچ میرا پاؤں بھاری میز کے کونے سے لگا", "ouch mera paon bhari mez ke kone se laga"],
        ["Shh, the librarian is walking between the quiet shelves.", "چپ لائبریری والی خاموش الماریوں کے درمیان چل رہی ہے", "chup library waali khamosh almaariyon ke darmiyaan chal rahi hai"],
        ["Hey, look at that rainbow above the wet fields.", "ارے دیکھو گیلے کھیتوں کے اوپر وہ قوس قزح", "arey dekho geile kheeton ke upar woh qous quzah"],
    ],
    575: [
        ["May I come in and wait here until the doctor is free?", "کیا میں اندر آ سکتا ہوں اور یہاں انتظار کروں جب تک ڈاکٹر فارغ ہوں؟", "kya main andar aa sakta hoon aur yahaan intizaar karoon jab tak doctor farigh hon?"],
        ["Can you help me carry this heavy box to the car?", "کیا آپ اس بھاری ڈبے کو گاڑی تک لے جانے میں مدد کر سکتے ہیں؟", "kya aap is bhari dabbe ko gaari tak le jaane mein madad kar sakte hain?"],
        ["Could you repeat the last sentence a little more slowly?", "کیا آپ آخری جملہ تھوڑا آہستہ دہرا سکتے ہیں؟", "kya aap aakhri jumla thoda aahista dohra sakte hain?"],
        ["Please close the window; the wind is too strong today.", "براہ کرم کھڑکی بند کریں آج ہوا بہت تیز ہے", "baraahe karam khidki band karein aaj hawa bahut tez hai"],
        ["Would you mind if I sit next to you on this bench?", "کیا برا مانیں گے اگر میں اس بنچ پر آپ کے پاس بیٹھوں؟", "kya bura maanenge agar main is bench par aap ke paas baithoon?"],
        ["We need your permission before we use this room for practice.", "مشق کے لیے اس کمرے کا استعمال کرنے سے پہلے آپ کی اجازت چاہیے", "mashq ke liye is kamre ka istemaal karne se pehle aap ki ijaazat chahiye"],
        ["A polite question sounds softer than a sharp command.", "مہذب سوال تیز حکم سے نرم لگتا ہے", "muazzab sawaal tez hukm se narm lagta hai"],
        ["Perhaps we can meet tomorrow if your schedule allows.", "شاید کل مل سکتے ہیں اگر آپ کا وقت ملے", "shayad kal mil sakte hain agar aap ka waqt mile"],
        ["Barāh-e karam send the file before five o'clock today.", "براہ کرم آج پانچ بجے سے پہلے فائل بھیج دیں", "baraahe karam aaj paanch baje se pehle file bhej dein"],
        ["Informally you might say ek kaam karo to a close friend.", "قریبی دوست سے کہو گے ایک کام کرو", "qareebi dost se kahoge ek kaam karo"],
        ["In a formal letter we write iltimās at the end politely.", "رسمی خط کے آخر میں مہذب الفاظ میں التماس لکھتے ہیں", "rasmi khat ke aakhir mein muazzab alfaaz mein iltimaas likhte hain"],
        ["May I ask whether the meeting will still happen on Friday?", "کیا میں پوچھ سکتا ہوں کہ میٹنگ جمعے کو ہو گی یا نہیں؟", "kya main poochh sakta hoon ke meeting jum'ey ko hogi ya nahin?"],
        ["Can you help the old woman cross this busy road safely?", "کیا آپ بوڑھی عورت کو یہ بھیڑ والی سڑک پار کرانے میں مدد کریں گے؟", "kya aap borhi aurat ko yeh bheed wali sarak paar karane mein madad karenge?"],
        ["Could you speak a little louder? The fan is very noisy.", "کیا تھوڑا زور سے بول سکتے ہیں پنکھا بہت شور کر رہا ہے", "kya thoda zor se bol sakte hain pankha bahut shor kar raha hai"],
        ["Please wait here; the nurse will call your name soon.", "براہ کرم یہاں انتظار کریں نرس جلد آپ کا نام لے گی", "baraahe karam yahaan intizaar karein nurse jald aap ka naam legi"],
        ["Would you mind turning off your phone during the speech?", "کیا برا مانیں گے اگر تقریر کے دوران فون بند کر دیں؟", "kya bura maanenge agar taqreeb ke dauraan phone band kar dein?"],
        ["We beg your permission to photograph the hall for our blog.", "ہم اپنے بلاگ کے لیے ہال کی تصویر کی اجازت مانگتے ہیں", "hum apne blog ke liye hall ki tasveer ki ijaazat maangte hain"],
    ],
    576: [
        ["It may rain tonight, so take a coat when you go out.", "شاید آج رات بارش ہو باہر جاتے وقت کوٹ لے لو", "shayad aaj raat baarish ho bahar jaate waqt kot le lo"],
        ["He might come late because his first meeting ran long.", "وہ شاید دیر سے آئے کیونکہ پہلی میٹنگ لمبی چلی", "woh shayad der se aaye kyunke pehli meeting lambi chali"],
        ["Maybe we should leave now if the traffic is heavy.", "شاید اب نکلنا چاہیے اگر ٹریفک زیادہ ہو", "shayad ab nikalna chahiye agar traffic zyada ho"],
        ["Perhaps the shop is closed; I am not completely sure.", "ممکن ہے دکان بند ہو میں پوری طرح یقین نہیں", "mumkin hai dukaan band hon main poori tarah yaqeen nahin"],
        ["There is uncertainty about the exam date until Monday.", "پیر تک امتحان کی تاریخ یقین نہیں", "peer tak imtihaan ki tareekh yaqeen nahin"],
        ["I might be late if the bus does not arrive on time.", "اگر بس وقت پر نہ آئے تو میں دیر سے آ سکتا ہوں", "agar bus waqt par na aaye to main der se aa sakta hoon"],
        ["She might not know the answer because she missed that class.", "شاید اسے جواب معلوم نہ ہو کیونکہ وہ کلاس چھوٹ گئی", "shayad use jawaab maaloom na ho kyunke woh class chhoot gayi"],
        ["The news report uses soft words when facts are incomplete.", "خبر میں جب حقائق مکمل نہ ہوں نرم الفاظ استعمال ہوتے ہیں", "khabar mein jab haqaa'iq mukammal na hon narm alfaaz istemaal hote hain"],
        ["It is said that prices may rise next month.", "کہا جاتا ہے اگلے مہینے قیمتیں بڑھ سکتی ہیں", "kaha jaata hai agle mahine qeematein barh sakti hain"],
        ["Do not say definitely if you only mean perhaps.", "شاید کا مطلب ہو تو ضرور مت کہیں", "shayad ka matlab ho to zaroor mat kahein"],
        ["We should not overstate what the doctor merely suggested.", "ڈاکٹر نے جو تجویز کی اسے حتمی نہ کہیں", "doctor ne jo tajweez ki use hatmi na kahein"],
        ["The sky looks dark; it may storm before evening.", "آسمان اندھیرا لگتا ہے شام سے پہلے طوفان آ سکتا ہے", "aasmaan andhera lagta hai shaam se pehle toofan aa sakta hai"],
        ["She might join us later if her work finishes early.", "اگر کام جلدی ختم ہو تو شاید بعد میں شامل ہو", "agar kaam jaldi khatam ho to shayad baad mein shamil ho"],
        ["Maybe the letter was lost in the slow postal system.", "شاید خط سست ڈاک میں کھو گیا", "shayad khat sust daak mein kho gaya"],
        ["Perhaps we misunderstood him when he spoke quickly.", "ممکن ہے ہم نے جلدی بولنے پر غلط سمجھا", "mumkin hai hum ne jaldi bolne par ghalat samjha"],
        ["I might need your help tomorrow if the plan changes.", "منصوبہ بدلے تو کل شاید تمہاری مدد چاہیے", "mansooba badle to kal shayad tumhari madad chahiye"],
        ["They might cancel the outdoor event if it keeps raining.", "بارش جاری رہی تو شاید کھلی تقریب منسوخ کر دیں", "baarish jaari rahe to shayad khuli taqreeb mansookh kar dein"],
    ],
    577: [
        ["This novel is readable even for people who are still learning.", "یہ ناول ابھی سیکھنے والوں کے لیے بھی قابل مطالعہ ہے", "yeh navel abhi seekhne walon ke liye bhi qaabil-e mutaala hai"],
        ["Her explanation was understandable after she drew a diagram.", "اس نے خاکہ بنانے کے بعد وضاحت قابل فہم کر دی", "us ne khaaka banane ke baad wazaahat qaabil-e fahm kar di"],
        ["The old chair looks broken, so do not sit on it.", "پرانی کرسی ٹوٹی ہوئی لگتی ہے اس پر مت بیٹھو", "purani kursi tooti hui lagti hai is par mat baitho"],
        ["The rice is cooked; we can eat as soon as you arrive.", "چاول پکے ہوئے ہیں تم آتے ہی کھا سکتے ہیں", "chaawal pake hue hain tum aate hi khaa sakte hain"],
        ["Many Urdu adjectives come from past participles like paka hua.", "بہت سی اردو صفات پکا ہوا جیسے ماضی صفت سے بنتی ہیں", "bohot si Urdu sifaat paka hua jaise maazi sift se banti hain"],
        ["A qaabil teacher can explain hard ideas in simple words.", "قابل استاد مشکل خیالات کو سادہ الفاظ میں سمجھا سکتا ہے", "qaabil ustaad mushkil khayaalaat ko saade alfaaz mein samjha sakta hai"],
        ["This story is interesting because the ending surprises us.", "یہ کہانی دلچسپ ہے کیونکہ انجام حیران کرتا ہے", "yeh kahaani dilchasp hai kyunke anjaam hairaan karta hai"],
        ["Climbing those stairs every day is tiring for my knees.", "روزانہ وہ سیڑھیاں چڑھنا گھٹنوں کے لیے تھکا دینے والا ہے", "rozana woh seediyaan chadhna ghutton ke liye thaka dene wala hai"],
        ["In essays, readable sentences help the examiner follow your logic.", "انشاء میں قابل مطالعہ جملے امتحان کنندہ کو منطق سمجھنے میں مدد دیتے ہیں", "inshaa mein qaabil-e mutaala jumle imtihaan kunanda ko mantiq samajhne mein madad dete hain"],
        ["Spoken Urdu often shortens long adjectives in quick replies.", "بول چال میں لمبی صفات جلدی جواب میں مختصر ہو جاتی ہیں", "bol chaal mein lambi sifaat jaldi jawaab mein mukhtasar ho jaati hain"],
        ["Write a paragraph using at least five new adjectives today.", "آج کم از کم پانچ نئی صفات استعمال کرتے ہوئے پیرا لکھیں", "aaj kam az kam paanch nayi sifaat istemaal karte hue pira likhein"],
        ["The bridge does not look safe; it appears broken in places.", "پل محفوظ نہیں لگتا کئی جگہ ٹوٹا ہوا معلوم ہوتا ہے", "pul mehfooz nahin lagta kai jagah toota hua maaloom hota hai"],
        ["The instructions were understandable once we read them twice.", "ہدایات دو بار پڑھنے کے بعد قابل فہم ہو گئیں", "hadaayaat do baar padhne ke baad qaabil-e fahm ho gayin"],
        ["Fresh bread smells wonderful when it is still warm and soft.", "تازہ روٹی گرم اور نرم ہو تو خوشبو دلچسپ لگتی ہے", "taaza roti garam aur narm ho to khushbu dilchasp lagti hai"],
        ["This math problem is tiring, but the answer is short.", "یہ ریاضی کا سوال تھکا دینے والا ہے مگر جواب مختصر ہے", "yeh riyazi ka sawaal thaka dene wala hai magar jawaab mukhtasar hai"],
        ["Choose readable fonts when you print notes for older readers.", "بڑی عمر والے پڑھنے والوں کے لیے نوٹس پر صاف فونٹ چنیں", "bari umar wale padhne walon ke liye notes par saaf font chunein"],
        ["His handwriting is understandable though it is a little messy.", "اس کی لکھائی تھوڑی گندلی ہے پھر بھی سمجھ آ جاتی ہے", "us ki likhai thodi gandli hai phir bhi samajh aa jaati hai"],
    ],
    578: [
        ["The upstairs room is warmer than the one below.", "اوپر والا کمرہ نیچے والے سے گرم ہے", "oopar wala kamra neeche wale se garam hai"],
        ["The inside guard checks every bag at the gate.", "اندر والا محافظ دروازے پر ہر تھیلی چیک کرتا ہے", "andar wala muhafiz darwaze par har theli check karta hai"],
        ["This is not our route; we need the stop for this neighbourhood.", "یہ ہمارا راستہ نہیں ہمیں اس محلے کا اسٹاپ چاہیے", "yeh hamara rasta nahin hamein is mohalle ka stop chahiye"],
        ["Wala, wali, and wale change with gender and number.", "والا، والی، والے جنس اور تعداد کے ساتھ بدلتے ہیں", "wala, wali, wale jins aur tadaad ke saath badalte hain"],
        ["He bought the Dilli wala sweet that everyone recommends.", "اس نے وہ دہلی والی مٹھائی لی جس کی سب تعریف کرتے ہیں", "us ne woh Dilli wali mithai li jis ki sab ta'reef karte hain"],
        ["Take my side wala chair; it has a softer cushion.", "میرے طرف والی کرسی لے لو اس پر نرم تکیہ ہے", "mere taraf wali kursi le lo us par narm takiya hai"],
        ["We use place plus wala to say where something comes from.", "جگہ کے ساتھ والا لگا کر بتاتے ہیں چیز کہاں کی ہے", "jagah ke saath wala laga kar batate hain cheez kahaan ki hai"],
        ["Yeh wala pen writes more smoothly than woh wala.", "یہ والا قلم اس والے سے زیادہ صاف لکھتا ہے", "yeh wala qalam us wale se zyada saaf likhta hai"],
        ["In everyday speech wala is very common on the street.", "عام بول چال میں گلی گلی والا بہت سننے کو ملتا ہے", "aam bol chaal mein gali gali wala bahut sunne ko milta hai"],
        ["In formal writing you may prefer a longer phrase instead.", "رسمی تحریر میں لمبے فقرے استعمال کر سکتے ہیں", "rasmi tahreer mein lambe faqre istemaal kar sakte hain"],
        ["The Lahore wala driver knows every shortcut in the city.", "لاہور والا ڈرائیور شہر کی ہر مختصر راستہ جانتا ہے", "Lahore wala driver sheher ki har mukhtasar rasta jaanta hai"],
        ["Which wala book did the teacher ask us to buy?", "استاد نے کون سی والی کتاب خریدنے کو کہا؟", "ustaad ne kaun si wali kitaab khareedne ko kaha?"],
        ["The andar wala light is broken; use the torch.", "اندر والی بتی ٹوٹی ہے ٹارچ استعمال کرو", "andar wali batti tooti hai torch istemaal karo"],
        ["Her Karachi wala accent sounds clear on the phone.", "فون پر اس کا کراچی والا لہجہ صاف سنائی دیتا ہے", "phone par us ka Karachi wala lahja saaf sunaai deta hai"],
        ["Give me the chhota wala plate for the child.", "بچے کے لیے چھوٹا والا پلیٹ دو", "bachche ke liye chhota wala plate do"],
        ["The naya wala rules will start from next Monday.", "نئے والے قوانین اگلے پیر سے شروع ہوں گے", "naye wale qawaneen agle peer se shuroo honge"],
        ["I like the purana wala house more than the new flats.", "مجھے پرانے والے گھر نئی فلیٹس سے زیادہ پسند ہیں", "mujhe purane wale ghar nayi flats se zyada pasand hain"],
    ],
    579: [
        ["May God give you a long and healthy life.", "خدا تمہیں لمبی اور صحت مند عمر دے", "Khuda tumhein lambi aur sehat mand umar de"],
        ["May peace remain in every street of this city.", "اس شہر کی ہر گلی میں امن قائم رہے", "is sheher ki har gali mein aman qaaim rahe"],
        ["May your journey be safe and your heart stay calm.", "تمہارا سفر محفوظ ہو اور دل پر سکون رہے", "tumhara safar mehfooz ho aur dil par sukoon rahe"],
        ["We use ho after a wish to show what we hope will happen.", "دعا کے بعد ہو لگا کر بتاتے ہیں ہم کیا چاہتے ہیں", "dua ke baad ho laga kar batate hain hum kya chahte hain"],
        ["Prayer style sentences often begin with Khuda or Allah.", "دعائیہ جملے اکثر خدا یا اللہ سے شروع ہوتے ہیں", "duaiyah jumle aksar Khuda ya Allah se shuroo hote hain"],
        ["I hope you feel better soon after this cold.", "امید ہے تم جلد ٹھیک ہو جاؤ گے اس سردی کے بعد", "umeed hai tum jald theek ho jaoge is sardi ke baad"],
        ["May Allah protect your family during hard times.", "اللہ مشکل وقت میں تمہارے خاندان کی حفاظت کرے", "Allah mushkil waqt mein tumhare khaandaan ki hifaazat kare"],
        ["At weddings elders bless the couple with ceremonial phrases.", "شادیوں میں بڑے جوڑے کو رسمی دعائیں دیتے ہیں", "shaadiyon mein bare jore ko rasmi duaein dete hain"],
        ["Poets love the soft sound of subjunctive wishes in verse.", "شاعر شاعری میں نرم دعائیہ فعل پسند کرتے ہیں", "shaa'ir shaairi mein narm duaiyah fe'l pasand karte hain"],
        ["Shayad in lesson 576 is doubt, but here ho shows a blessing.", "شاید سبق 576 میں شک ہے مگر یہاں ہو دعا دکھاتا ہے", "shayad sabq 576 mein shak hai magar yahaan ho dua dikhata hai"],
        ["Cultural notes remind us to bless food before we eat.", "ثقافتی باتیں یاد دلاتی ہیں کھانے سے پہلے دعا کریں", "saqaafati baatein yaad dilati hain khaane se pehle dua karein"],
        ["May your parents smile when they hear this good news.", "تمہارے والدین یہ خوشخبری سن کر مسکرائیں", "tumhare walidein yeh khushkhabri sun kar muskuraayein"],
        ["May the exam go easily for every student in the hall.", "امتحان ہال میں ہر طالب علم کے لیے آسان ہو", "imtihaan hall mein har taalib ilm ke liye aasaan ho"],
        ["May our friendship stay strong through every season.", "دوستی ہر موسم میں مضبوط رہے", "dosti har mausam mein mazboot rahe"],
        ["May the rain soften the dry fields for the farmers.", "بارش خشک کھیتوں کو کسانوں کے لیے نرم کر دے", "baarish khushk kheeton ko kisaanon ke liye narm kar de"],
        ["May you never walk alone when trouble arrives.", "مصیبت آئے تو تم اکیلے نہ چلو", "museebat aaye to tum akele na chalo"],
        ["May your hard work bring honour to your whole house.", "تمہاری محنت پورے گھر کو عزت دے", "tumhari mehnat poore ghar ko izzat de"],
    ],
    580: [
        ["I made him sit on the chair because he looked tired.", "میں نے اسے کرسی پر بٹھایا کیونکہ وہ تھکا لگ رہا تھا", "main ne use kursi par bithaaya kyunke woh thaka lag raha tha"],
        ["Please get this letter typed; karwa do it today.", "براہ کرم یہ خط ٹائپ کروا دو آج ہی", "baraahe karam yeh khat type karwa do aaj hi"],
        ["The teacher makes us read aloud every Monday morning.", "استاد ہر پیر کی صبح ہم سے زور سے پڑھواتے ہیں", "ustaad har peer ki subah hum se zor se padhwaate hain"],
        ["She had the letter written by a clerk at the office.", "اس نے دفتر میں کلرک سے خط لکھوایا", "us ne daftar mein clerk se khat likhwaaya"],
        ["Causative verbs show that someone caused another action.", "سببی فعل بتاتے ہیں کسی نے دوسرا کام کروایا", "sabbi fe'l batate hain kisi ne doosra kaam karwaaya"],
        ["We add waana to many roots to build a causative verb.", "بہت سے جڑوں کے ساتھ وانا لگا کر سببی فعل بناتے ہیں", "bohot se jaron ke saath waana laga kar sabbi fe'l banate hain"],
        ["Lesson 538 also practised similar patterns with light verbs.", "538 میں بھی ہلکے فعل کے ساتھ ایسے ہی نمونے تھے", "538 mein bhi halka fe'l ke saath aise hi namoonay the"],
        ["Polite Urdu uses soft words when you ask someone to act.", "جب کسی سے کام کروانا ہو مہذب الفاظ استعمال کریں", "jab kisi se kaam karwana ho muazzab alfaaz istemaal karein"],
        ["They did not karwaaya the repair even after we paid.", "ادا کرنے کے بعد بھی انہوں نے مرمت نہیں کروائی", "ada karne ke baad bhi unhon ne murammat nahin karwaai"],
        ["Complex sentences mix a main clause with a causative part.", "مرکب جملے مرکزی فقرے کے ساتھ سببی حصہ ملاتے ہیں", "murakkab jumle markazi faqre ke saath sabbi hissa milate hain"],
        ["Drill these patterns until the endings feel automatic.", "ان نمونوں کی ورزش کریں جب تک اختتام خود بخود نہ لگے", "in namoonon ki warzish karein jab tak ikhtitaam khud ba khud na lage"],
        ["Review yesterday's sentences before you write new ones.", "نئے جملے لکھنے سے پہلے کل کے جملے دہرائیں", "naye jumle likhne se pehle kal ke jumle dohraayein"],
        ["The mother made the child drink milk before school.", "ماں نے بچے کو سکول سے پہلے دودھ پلایا", "maan ne bachche ko school se pehle doodh pilaya"],
        ["He will get the room painted before the guests arrive.", "وہ مہمانوں کے آنے سے پہلے کمرہ رنگ کروا لے گا", "woh mehmaanon ke aane se pehle kamra rang karwa lega"],
        ["We had the car washed while we drank tea at the café.", "ہم نے چائے پیتے وقت گاڑی دھلوائی", "hum ne chaaye peete waqt gaari dhlwaai"],
        ["Do not make people wait if you can finish the work sooner.", "کام جلدی ہو سکے تو لوگوں کو انتظار نہ کروائیں", "kaam jaldi ho sake to logon ko intizaar na karwaayein"],
        ["The boss got the report checked by two different readers.", "باس نے رپورٹ دو مختلف پڑھنے والوں سے چیک کروائی", "boss ne report do mukhtalif padhne walon se check karwaai"],
    ],
    581: [
        ["I left my keys somewhere in the house but I forgot where.", "میں نے چابیاں گھر میں کہیں رکھی تھیں مگر بھول گیا کہاں", "main ne chaabiyaan ghar mein kahin rakhi thin magar bhool gaya kahaan"],
        ["Somehow we finished the project even without extra money.", "کسی طرح ہم نے بغیر اضافی پیسے کے منصوبہ ختم کیا", "kisi tarah hum ne baghair izaafi paise ke mansooba khatam kiya"],
        ["Did you find anything useful in that old box?", "کیا تمہیں اس پرانے ڈبے میں کچھ بھی مفید ملا؟", "kya tumhein is purane dabbe mein kuchh bhi mufeed mila?"],
        ["Anybody can join the class if they register online.", "کوئی بھی آن لائن رجسٹر کرے تو کلاس میں شامل ہو سکتا ہے", "koi bhi online register kare to class mein shamil ho sakta hai"],
        ["I looked nowhere else; the answer was on the first page.", "میں نے کہیں اور نہیں دیکھا جواب پہلے صفحے پر تھا", "main ne kahin aur nahin dekha jawaab pehle safhe par tha"],
        ["He never speaks rudely to elders in public.", "وہ عوامی جگہوں پر بڑوں سے کبھی بے ادبی نہیں کرتا", "woh awami jagahon par baron se kabhi be-adabi nahin karta"],
        ["We searched everywhere for the lost puppy until evening.", "ہم نے گمشدہ پپی کو شام تک ہر جگہ ڈھونڈا", "hum ne gumshuda puppy ko shaam tak har jagah dhoonda"],
        ["Someone left an umbrella near the door; is it yours?", "کسی نے دروازے کے پاس چھتری چھوڑی ہے کیا یہ تمہاری ہے؟", "kisi ne darwaze ke paas chhatri chhori hai kya yeh tumhari hai?"],
        ["Indefinite pronouns help when we do not need exact names.", "غیر معین ضمیر تب مدد کرتے ہیں جب نام درکار نہ ہوں", "ghair mu'ayyan zameer tab madad karte hain jab naam darkaar na hon"],
        ["Urdu often uses double negatives for strong spoken emphasis.", "اردو بول چال میں دو منفی زور کے لیے استعمال ہوتے ہیں", "Urdu bol chaal mein do manfi zor ke liye istemaal hote hain"],
        ["Did you get anything to eat after the long journey?", "لمبے سفر کے بعد کیا کچھ کھانے کو ملا؟", "lambe safar ke baad kya kuchh khaane ko mila?"],
        ["Somehow the message reached him even without a phone.", "کسی طرح پیغام بغیر فون کے اس تک پہنچ گیا", "kisi tarah paighaam baghair phone ke us tak pahunch gaya"],
        ["Nobody saw anything strange on the quiet road last night.", "کل رات خاموش سڑک پر کسی کو کچھ بھی عجیب نظر نہیں آیا", "kal raat khamosh sarak par kisi ko kuchh bhi ajeeb nazar nahin aaya"],
        ["I will never forget the kindness someone showed me here.", "میں کبھی نہیں بھولوں گا کسی نے یہاں جو مہربانی کی", "main kabhi nahin bhoolunga kisi ne yahaan jo meherbaani ki"],
        ["Everywhere in the market people were buying sweets.", "بازار میں ہر جگہ لوگ مٹھائیاں خرید رہے تھے", "bazaar mein har jagah log mithaiyaan khareed rahe the"],
        ["Is there anybody who can translate this short paragraph?", "کیا کوئی ہے جو یہ مختصر پیرا ترجمہ کر سکے؟", "kya koi hai jo yeh mukhtasar pira tarjuma kar sake?"],
        ["I have nowhere to go tonight if the train is cancelled.", "اگر ٹرین منسوخ ہو تو آج رات کہیں جانے کی جگہ نہیں", "agar train mansookh ho to aaj raat kahin jaane ki jagah nahin"],
    ],
    582: [
        ["I have a book about Urdu poetry on my small shelf.", "میری چھوٹی الماری پر اردو شاعری کی ایک کتاب ہے", "meri chhoti almaari par Urdu shaa'iri ki ek kitaab hai"],
        ["She has two brothers who study engineering in another city.", "اس کے دو بھائی ہیں جو دوسرے شہر میں انجینئرنگ پڑھتے ہیں", "us ke do bhai hain jo doosre sheher mein engineering padhte hain"],
        ["I have a headache today so I will rest after lunch.", "آج سر درد ہے اس لیے دوپہر کے کھانے کے بعد آرام کروں گا", "aaj sar dard hai is liye dopehar ke khaane ke baad aaraam karunga"],
        ["There is fresh fruit in the bowl on the kitchen table.", "باورچی خانے کی میز پر پیالے میں تازہ پھل ہے", "baawarchi khaane ki mez par pyaale mein taaza phal hai"],
        ["We do not have enough chairs for every guest tonight.", "آج رات ہر مہمان کے لیے کافی کرسیاں نہیں ہیں", "aaj raat har mehmaan ke liye kaafi kursiyaan nahin hain"],
        ["His name shows that he is the son of a famous writer.", "اس کا نام بتاتا ہے کہ وہ مشہور لکھاری کا بیٹا ہے", "us ka naam batata hai ke woh mashoor likhaari ka beta hai"],
        ["There are many birds in the garden early in the morning.", "صبح سویرے باغ میں بہت پرندے ہوتے ہیں", "subah sowere baagh mein bohot parinde hote hain"],
        ["My grandparents have a small farm outside the town.", "میرے دادا دادی کے شہر کے باہر چھوٹا فارم ہے", "mere daada daadi ke sheher ke bahar chhota farm hai"],
        ["Lesson 553 taught obligation; here we simply describe what we own.", "553 میں ذمہ داری تھی یہاں ہم صرف بتاتے ہیں ہمارے پاس کیا ہے", "553 mein zimmedaari thi yahan hum sirf batate hain hamare paas kya hai"],
        ["There is a difference between mere paas hai and yeh hai.", "میرے پاس ہے اور یہ ہے میں فرق ہوتا ہے", "mere paas hai aur yeh hai mein farq hota hai"],
        ["The maalik of the shop smiled when we praised the cloth.", "دکان کے مالک نے مسکرایا جب ہم کپڑے کی تعریف کی", "dukaan ke maalik ne muskuraya jab hum kapre ki ta'reef ki"],
        ["She has a gentle voice that calms nervous students.", "اس کی آواز نرم ہے جو گھبرائے طلبہ کو سکون دیتی ہے", "us ki aawaaz narm hai jo ghabraaye talba ko sukoon deti hai"],
        ["We have no time today; can we meet tomorrow instead?", "آج وقت نہیں ہے کیا کل مل سکتے ہیں؟", "aaj waqt nahin hai kya kal mil sakte hain?"],
        ["There is water in the jug if you feel thirsty.", "اگر پیاس لگے تو جگ میں پانی ہے", "agar pyaas lage to jug mein paani hai"],
        ["He has three cousins who live in three different countries.", "اس کے تین کزن ہیں جو تین مختلف ممالک میں رہتے ہیں", "us ke teen cousins hain jo teen mukhtalif mumalik mein rehte hain"],
        ["I have an old camera that still takes clear photos.", "میرے پاس پرانا کیمرا ہے جو اب بھی صاف تصویریں کھینچتا ہے", "mere paas purana camera hai jo ab bhi saaf tasveerein kheenchta hai"],
        ["There are problems in every house, but love solves many.", "ہر گھر میں مسئلے ہوتے ہیں مگر محبت بہت حل کر دیتی ہے", "har ghar mein masail hote hain magar mohabbat bahut hal kar deti hai"],
    ],
    583: [
        ["What does this difficult word mean in simple Urdu?", "یہ مشکل لفظ سادہ اردو میں کیا مطلب رکھتا ہے؟", "yeh mushkil lafz saade Urdu mein kya matlab rakhta hai?"],
        ["When I said that, my matlab was only to help you.", "جب میں نے یہ کہا تو میرا مطلب صرف مدد کرنا تھا", "jab main ne yeh kaha to mera matlab sirf madad karna tha"],
        ["The ma'ni of peace is wider than the absence of war.", "امن کا معنی صرف جنگ کے نہ ہونے سے بڑا ہے", "aman ka ma'ni sirf jang ke na hone se bara hai"],
        ["What did he muraad hona when he used that old proverb?", "جب اس نے وہ پرانی کہاوت استعمال کی تو مراد کیا تھی؟", "jab us ne woh purani kahawat istemaal ki to muraad kya thi?"],
        ["Could you explain the word step by step for beginners?", "کیا آپ لفظ قدم بہ قدم نئے لوگوں کو سمجھا سکتے ہیں؟", "kya aap lafz qadam ba qadam naye logon ko samjha sakte hain?"],
        ["Kind and gentle are ham ma'ni in many everyday sentences.", "مہربان اور نرم بہت سے جملوں میں ہم معنی ہیں", "mehrbaan aur narm bohot se jumlon mein ham ma'ni hain"],
        ["Slang has an aam fahm meaning that books rarely teach.", "عام فہم بول چال کا مطلب کتابیں کم سکھاتی ہیں", "aam fahm bol chaal ka matlab kitaabein kam sikhati hain"],
        ["Open the lughat when a new word blocks your reading.", "جب نیا لفظ پڑھائی روکے تو لغت کھولیں", "jab naya lafz padhaai roke to lughat kholein"],
        ["How do native speakers say yeh when they mean maybe?", "مقامی بولنے والے شاید کے لیے یہ کیا کہتے ہیں؟", "maqaami bolne wale shayad ke liye yeh kya kehte hain?"],
        ["Good translators avoid getting lost in literal tarjuma.", "اچھے مترجم لفظی ترجمے میں کھو نہیں جاتے", "achchhe mutarjim lafzi tarjume mein kho nahin jaate"],
        ["The formal mafhoom of the speech was deeper than the jokes.", "تقریر کا رسمی مفہوم مذاقوں سے گہرا تھا", "taqreeb ka rasmi mafhoom mazaakon se gehra tha"],
        ["This sign does not mean what tourists often guess.", "اس نشان کا مطلب وہ نہیں جو سیاح اکثر سمجھتے ہیں", "is nishaán ka matlab woh nahin jo saiyah aksar samajhte hain"],
        ["I did not catch your matlab; could you say it again?", "میں آپ کا مطلب سمجھ نہیں سکا دوبارہ کہیں؟", "main aap ka matlab samajh nahin saka dobara kahein?"],
        ["Every ma'ni changes a little in poetry and in news.", "شاعری اور خبروں میں ہر معنی تھوڑا بدل جاتا ہے", "shaairi aur khabron mein har ma'ni thoda badal jaata hai"],
        ["She implied more than her words literally said.", "اس کے الفاظ سے زیادہ مراد تھی", "us ke alfaaz se zyada muraad thi"],
        ["The teacher asked us to explain five words from the story.", "استاد نے کہانی کے پانچ الفاظ سمجھانے کو کہا", "ustaad ne kahaani ke paanch alfaaz samjhaane ko kaha"],
        ["If the sentence feels unclear, ask what the writer muraad hona.", "جملہ غیر واضح لگے تو پوچھیں لکھاری کی مراد کیا ہے", "jumla ghair waazeh lage to poochhen likhaari ki muraad kya hai"],
    ],
    584: [
        ["I bought bread and milk at the small shop near our lane.", "میں نے اپنی گلی کے قریب دکان سے روٹی اور دودھ لیا", "main ne apni gali ke qareeb dukaan se roti aur doodh liya"],
        ["She wanted tea, but the kettle was still empty.", "وہ چائے چاہتی تھی مگر کیتلی ابھی خالی تھی", "woh chaaye chahti thi magar ketli abhi khaali thi"],
        ["We stayed home because the roads were flooded with rain.", "ہم گھر رہے کیونکہ بارش سے سڑکیں بھر گئیں", "hum ghar rahe kyunke baarish se sarakain bhar gayin"],
        ["He felt tired, so he slept early without dinner.", "اسے تھکن محسوس ہوئی اس لیے بغیر رات کے کھانے جلدی سو گیا", "use thakan mehsoos hui is liye baghair raat ke khaane jaldi so gaya"],
        ["She said that she would call when she reached the station.", "اس نے کہا کہ وہ اسٹیشن پہنچ کر فون کرے گی", "us ne kaha ke woh station pahunch kar phone karegi"],
        ["Although the wind was strong, the little boat stayed steady.", "اگرچہ ہوا تیز تھی مگر چھوٹی کشتی مستحکم رہی", "agarcheh hawa tez thi magar chhoti kashti mustahkam rahi"],
        ["The plan looked risky, yet we decided to try it once.", "منصوبہ خطرناک لگا پھر بھی ہم نے ایک بار آزمانے کا فیصلہ کیا", "mansooba khatarnaak laga phir bhi hum ne ek baar aazmane ka faisla kiya"],
        ["He is quiet in class, still his answers are always correct.", "وہ کلاس میں خاموش ہے پھر بھی اس کے جواب ہمیشہ درست ہوتے ہیں", "woh class mein khamosh hai phir bhi us ke jawaab hamesha durust hote hain"],
        ["We have not finished the work yet; the deadline is tomorrow.", "ہم نے ابھی تک کام ختم نہیں کیا آخری تاریخ کل ہے", "hum ne abhi tak kaam khatam nahin kiya aakhri tareekh kal hai"],
        ["Join two clauses with aur when both ideas feel equal.", "جب دونوں خیالات برابر ہوں تو اور سے جوڑیں", "jab dono khayaalaat barabar hon to aur se jorein"],
        ["Use a comma in writing when the pause is short and clear.", "جب وقفہ مختصر اور واضح ہو تحریر میں ویرام لگائیں", "jab waqfa mukhtasar aur waazeh ho tahreer mein weeraam lagayein"],
        ["I like fruit and nuts, but I avoid sugar in my tea.", "مجھے پھل اور گری پسند ہیں مگر چائے میں چینی نہیں لیتی", "mujhe phal aur gari pasand hain magar chaaye mein cheeni nahin leti"],
        ["They left early because the baby was crying in the heat.", "وہ جلدی چلے گئے کیونکہ گرمی میں بچہ رو رہا تھا", "woh jaldi chale gaye kyunke garmi mein bachcha ro raha tha"],
        ["The street was dark, so we walked together for safety.", "گلی اندھیری تھی اس لیے ہم نے محفوظی کے لیے ساتھ چلا", "gali andheri thi is liye hum ne mehfoozi ke liye saath chala"],
        ["He explained that he would send the file after lunch.", "اس نے بتایا کہ دوپہر کے کھانے کے بعد فائل بھیجے گا", "us ne bataya ke dopehar ke khaane ke baad file bhejega"],
        ["Although she was nervous, she spoke in a calm voice.", "اگرچہ وہ گھبرائی ہوئی تھی مگر آواز پر سکون تھا", "agarcheh woh ghabrai hui thi magar aawaaz par sukoon tha"],
        ["We have paid the fee, yet the card has not arrived.", "ہم نے فیس ادا کر دی ہے پھر بھی کارڈ نہیں آیا", "hum ne fees ada kar di hai phir bhi card nahin aaya"],
    ],
    585: [
        ["The sky looks grey, as if a storm will arrive soon.", "آسمان ایسا لگتا ہے گویا طوفان جلد آئے گا", "aasmaan aisa lagta hai goya toofan jald aaega"],
        ["Would you like tea or coffee with the morning biscuits?", "صبح کی بسکٹ کے ساتھ چائے پسند ہے یا کافی؟", "subah ki biscuit ke saath chaaye pasand hai ya kaafi?"],
        ["Neither he nor his brother could fix the broken lock.", "نہ وہ نہ اس کا بھائی ٹوٹی تالا ٹھیک کر سکا", "na woh na us ka bhai tooti taala theek kar saka"],
        ["She speaks neither loudly nor rudely in public meetings.", "وہ عوامی میٹنگ میں نہ زور سے بولتی ہے نہ بے ادبی سے", "woh awami meeting mein na zor se bolti hai na be-adabi se"],
        ["If you feel sick, please stay home and rest.", "اگر طبیعت خراب لگے تو گھر رہ کر آرام کریں", "agar tabiyat kharab lage to ghar reh kar aaraam karein"],
        ["Take an umbrella in case the weather changes suddenly.", "اچانک موسم بدلے تو چھتری ساتھ رکھیں", "achanak mausam badle to chhatri saath rakhein"],
        ["You may borrow my book provided you return it next week.", "اگلے ہفتے واپس کرنے کی شرط پر میری کتاب لے جائیں", "agle hafte wapas karne ki shart par meri kitaab le jaayein"],
        ["I am not sure whether he will travel by bus or train.", "مجھے یقین نہیں کہ وہ بس سے جائے گا یا ٹرین سے", "mujhe yaqeen nahin ke woh bus se jaega ya train se"],
        ["Either we leave now, or we miss the last bus home.", "یا تو اب نکلیں یا گھر کی آخری بس چھوٹ جائے گی", "ya to ab niklein ya ghar ki aakhiri bus chhoot jaegi"],
        ["Neither fear nor pride should control every decision.", "ہر فیصلے پر نہ خوف نہ غرور حاوی ہونا چاہیے", "har faisle par na khauf na ghuroor haawi hona chahiye"],
        ["Complex embedding helps when one story sits inside another.", "ایک کہانی دوسری کے اندر ہو تو مرکب جڑنا مدد کرتا ہے", "ek kahaani doosri ke andar ho to murakkab jurna madad karta hai"],
        ["If the road is closed, we will take the longer route.", "اگر سڑک بند ہو تو لمبا راستہ لیں گے", "agar sarak band ho to lamba rasta lenge"],
        ["Speak clearly, or people may misunderstand your kind words.", "صاف بولیں ورنہ لوگ آپ کے نرم الفاظ غلط سمجھیں", "saaf bolein warna log aap ke narm alfaaz ghalat samjhein"],
        ["Jaise the teacher writes on the board, copy every line.", "جیسے استاد بورڈ پر لکھے ہر سطر نقل کریں", "jaise ustaad board par likhe har satr naql karein"],
        ["Neither the cat nor the dog likes this cheap food.", "نہ بلی نہ کتا یہ سستا کھانا پسند کرتا", "na billi na kutta yeh sasta khaana pasand karta"],
        ["If guests arrive early, we will serve tea first.", "اگر مہمان جلدی آ جائیں تو پہلے چائے پلائیں گے", "agar mehmaan jaldi aa jaayein to pehle chaaye pilayenge"],
        ["He will help you provided you ask him with respect.", "وہ مدد کرے گا بشرطیکہ آپ احترام سے مانگیں", "woh madad karega bashart-e-ke aap ihtiraam se maangein"],
    ],
    586: [
        ["After dinner we walked slowly in the cool night air.", "رات کے کھانے کے بعد ہم ٹھنڈی ہوا میں آہستہ چلے", "raat ke khaane ke baad hum thandi hawa mein aahista chale"],
        ["He finished his work, then he called his mother happily.", "اس نے کام ختم کیا پھر خوشی سے ماں کو فون کیا", "us ne kaam khatam kiya phir khushi se maan ko phone kiya"],
        ["As far as I know, the shop opens at nine every day.", "جہاں تک مجھے معلوم ہے دکان ہر روز نو بجے کھلتی ہے", "jahaan tak mujhe maaloom hai dukaan har roz nau baje khulti hai"],
        ["You can stay as long as you promise to lock the door.", "جب تک وعدہ کرو گے کہ دروازہ بند کرو گے تب تک رہ سکتے ہو", "jab tak vaada karoge ke darwaza band karoge tab tak reh sakte ho"],
        ["He smiled as if he already knew the secret answer.", "وہ مسکرایا گویا اسے خفیہ جواب پہلے سے معلوم تھا", "woh muskuraya goya use khufiya jawaab pehle se maaloom tha"],
        ["First we pay the bill, then we leave the restaurant quietly.", "پہلے بل ادا کرتے ہیں پھر خاموشی سے ریسٹوران چھوڑتے ہیں", "pehle bill ada karte hain phir khamoshi se restaurant chhodte hain"],
        ["The time clause comes first when the sequence really matters.", "جب ترتیب اہم ہو تو زمانی فقرہ پہلے آتا ہے", "jab tarteeb ahem ho to zamaani faqra pehle aata hai"],
        ["Her eyes were bright like stars in the clear winter sky.", "اس کی آنکھیں صاف سردی کے آسمان میں ستاروں جیسی چمکتی تھیں", "us ki aankhein saaf sardi ke aasmaan mein sitaron jaisi chamakti thin"],
        ["After eating spicy food, he drank a full glass of water.", "تیز مسالے والا کھانے کے بعد اس نے پانی کا گلاس پی لیا", "tez masale wala khaane ke baad us ne paani ka glass pee liya"],
        ["Then the lights went out, and the children held hands.", "پھر بجلی گئی اور بچوں نے ہاتھ تھام لیے", "phir bijli gayi aur bachchon ne haath thaam liye"],
        ["She looked calm as if nothing bad had happened at all.", "وہ پرسکون لگ رہی تھی گویا برا کچھ ہوا ہی نہیں", "woh pursukoon lag rahi thi goya bura kuch hua hi nahin"],
        ["After the exam we rested, then we discussed every question.", "امتحان کے بعد آرام کیا پھر ہر سوال پر بات کی", "imtihaan ke baad aaraam kiya phir har sawaal par baat ki"],
        ["As far as the doctor can see, your heart is healthy.", "جہاں تک ڈاکٹر دیکھ سکتا ہے آپ کا دل صحت مند ہے", "jahaan tak doctor dekh sakta hai aap ka dil sehat mand hai"],
        ["Stay as long as you like; the door will stay unlocked.", "جب تک چاہو رہو دروازہ کھلا رہے گا", "jab tak chaho raho darwaza khula rahega"],
        ["The boy laughed as if he had heard the funniest joke.", "لڑکا ہنسا گویا اس نے سب سے مزاحیہ لطیفہ سنا ہو", "larka hansa goya us ne sab se mazahiyah lateefa suna ho"],
        ["After the long speech, people clapped with real energy.", "لمبی تقریر کے بعد لوگوں نے سچی توانائی سے تالیاں بجائیں", "lambi taqreeb ke baad logon ne sachchi tawaanni se taaliyaan bajaain"],
        ["Then she whispered the plan so softly that nobody else heard.", "پھر اس نے منصوبہ اتنی آہستہ بتایا کہ اور کوئی نہ سنا", "phir us ne mansooba itni aahista bataya ke aur koi na suna"],
    ],
    587: [
        ["As soon as the bell rang, the students opened their books.", "جیسے ہی گھنٹی بجی طلبہ نے کتابیں کھولیں", "jaise hi ghanti baji talba ne kitaabein kholein"],
        ["Once you understand the rule, the exercises feel easier.", "ایک بار قاعدہ سمجھ آ جائے تو مشقیں آسان لگتی ہیں", "ek baar qaaida samajh aa jaaye to mashqain aasaan lagti hain"],
        ["Take juice rather than soda if you want to sleep well.", "اچھی نیند چاہو تو سوڈے کی بجائے جوس لو", "achhi neend chaho to soda ki bajaa'e juice lo"],
        ["Instead of arguing, we listened and found a quiet solution.", "جھگڑے کی بجائے ہم نے سنا اور خاموش حل نکالا", "jhagre ki bajaa'e hum ne suna aur khamosh hal nikala"],
        ["She left early so that she could help her sister pack.", "وہ جلدی نکلی تاکہ بہن کو سامان باندھنے میں مدد کر سکے", "woh jaldi nikli taake behen ko saamaan baandhne mein madad kar sake"],
        ["The purpose clause explains why someone chose a certain action.", "غرضیہ فقرہ بتاتا ہے کسی نے کوئی عمل کیوں چنا", "gharziyah faqra batata hai kisi ne koi amal kyun chuna"],
        ["As soon as rain stopped, children ran out to the field.", "جیسے ہی بارش رکی بچے میدان میں دوڑے", "jaise hi baarish ruki bachche maidan mein daude"],
        ["I would rather walk than wait another hour for the bus.", "ایک گھنٹہ اور بس کا انتظار کرنے سے چلنا بہتر ہے", "ek ghanta aur bus ka intizaar karne se chalna behtar hai"],
        ["Instead of old maps, we used a phone app in the city.", "پرانے نقشوں کی بجائے شہر میں فون ایپ استعمال کی", "purane naqshon ki bajaa'e sheher mein phone app istemaal ki"],
        ["He spoke slowly so that every child could follow the story.", "وہ آہستہ بولا تاکہ ہر بچہ کہانی سمجھ سکے", "woh aahista bola taake har bachcha kahaani samajh sake"],
        ["The result was peace because we chose patience over pride.", "نتیجہ امن رہا کیونکہ ہم نے غرور پر صبر چنا", "nateeja aman raha kyunke hum ne ghuroor par sabr chuna"],
        ["As soon as you sign, we can print the final agreement.", "جیسے ہی دستخط کرو آخری معاہدہ چھاپ سکتے ہیں", "jaise hi dastakhat karo aakhri mo'ahida chhaap sakte hain"],
        ["Once the sun rose, the fog disappeared from the valley.", "ایک بار سورج نکلا تو وادی سے دھند اٹھ گئی", "ek baar suraj nikla to waadi se dhund uth gayi"],
        ["Rather than shout, she wrote a polite note to her neighbour.", "چیخنے کی بجائے اس نے پڑوسی کو مہربان نوٹ لکھا", "cheekhne ki bajaa'e us ne parosi ko mehrbaan note likha"],
        ["Instead of plastic bags, carry a cloth bag to the market.", "پلاسٹک تھیلی کی بجائے بازار میں کپڑے کی تھیلی لے جائیں", "plastic theli ki bajaa'e bazaar mein kapre ki theli le jaayein"],
        ["We left quietly so that we would not wake the sleeping baby.", "ہم خاموشی سے نکلے تاکہ سوتے بچے کو نہ جگائیں", "hum khamoshi se nikle taake sote bachche ko na jagaayein"],
        ["Practice these patterns until the order feels natural in speech.", "ان نمونوں کی مشق کریں جب تک بول چال میں ترتیب قدرتی نہ لگے", "in namoonon ki mashq karein jab tak bol chaal mein tarteeb qudrati na lage"],
    ],
    588: [
        ["We use aur, lekin, and kyunke to connect ideas in essays.", "انشاء میں خیالات جوڑنے کے لیے اور، لیکن، کیونکہ استعمال ہوتے ہیں", "inshaa mein khayaalaat jorne ke liye aur, lekin, kyunke istemaal hote hain"],
        ["Coordinating conjunctions join equal clauses without changing rank.", "ہم پلہ رابطے برابر فقرے جوڑتے ہیں بغیر درجہ بدلے", "ham palah raabte barabar faqre jorte hain baghair darja badle"],
        ["Subordinating words show which clause depends on the main idea.", "تابع الفاظ بتاتے ہیں کون سا فقرہ مرکزی خیال پر منحصر ہے", "taabi' alfaaz batate hain kaun sa faqra markazi khayaal par munhasir hai"],
        ["Correlative pairs like ya…ya need the same grammar on both sides.", "یا… یا جیسے متوازی جوڑ دونوں طرف ایک جیسا گرامر چاہتے ہیں", "ya… ya jaise mutawaazi jore dono taraf ek jaisa grammar chahte hain"],
        ["In a short essay, vary conjunctions so the rhythm stays lively.", "مختصر انشاء میں رابطے بدلیں تاکہ لہجہ زندہ رہے", "mukhtasar inshaa mein raabte badlein taake lahja zinda rahe"],
        ["Avoid overload: too many aur in one paragraph sounds childish.", "زیادہ اور ایک پیراگراف میں بچکانہ لگتا ہے", "zyada aur ek paragraph mein bachkaana lagta hai"],
        ["Use ramooz-e awqaaf carefully so readers know where to pause.", "رموز اوقاف سے پڑھنے والوں کو وقفے کا پتہ چلتا ہے", "ramooz awqaaf se padhne walon ko waqfe ka pata chalta hai"],
        ["Reading practice every day trains your eye for natural connectors.", "روزانہ پڑھائی آنکھ کو قدرتی رابطوں کے لیے تربیت دیتی ہے", "rozana padhaai aankh ko qudrati rabton ke liye tarbiyat deti hai"],
        ["Build your own list of favourite connectors from good articles.", "اچھی مضامین سے پسندیدہ رابطوں کی فہرست بنائیں", "achchhe mazaameen se pasandida rabton ki fehrist banaayein"],
        ["Compare parts one to four of this book to see style growth.", "اس کتاب کے حصے ایک سے چار موازنہ کریں انداز کی ترقی دیکھیں", "is kitaab ke hisse ek se chaar muwaazna karein andaaz ki tarqqi dekhein"],
        ["Self-test: rewrite a paragraph using only three conjunction types.", "خود امتحان: صرف تین قسم کے رابطے استعمال کرتے ہوئے پیرا دوبارہ لکھیں", "khud imtihaan: sirf teen qism ke raabte istemaal karte hue pira dobara likhein"],
        ["Review yesterday's draft and underline every connector you used.", "کل کا مسودہ دہرائیں اور ہر رابطے کو خط کشیدہ کریں", "kal ka musawwada dohraayein aur har raabte ko khat kashida karein"],
        ["Good writers mix short sentences with longer linked ones.", "اچھے لکھاری مختصر جملے لمبے جوڑے ہوئے جملوں کے ساتھ ملاتے ہیں", "achchhe likhaari mukhtasar jumle lambe jore hue jumlon ke saath milate hain"],
        ["When you read news, notice how kyunke supports a fact.", "خبر پڑھتے دیکھیں کیونکہ کس حقائق کو سہارا دیتا ہے", "khabar padhte dekhein kyunke kis haqaa'iq ko sahara deta hai"],
        ["A paragraph without lekin can sound too simple or too sure.", "بغیر لیکن کا پیراگراف بہت سادہ یا بہت یقینی لگ سکتا ہے", "baghair lekin ka paragraph bahut saada ya bahut yaqeeni lag sakta hai"],
        ["Students often overuse aur; try lekin for contrast instead.", "طلبہ اکثر اور کا زیادہ استعمال کرتے ہیں فرق کے لیے لیکن آزمائیں", "talba aksar aur ka zyada istemaal karte hain farq ke liye lekin aazmaaein"],
        ["Before you submit, read aloud and listen for natural flow.", "جمع کرانے سے پہلے زور سے پڑھیں اور قدرتی بہاؤ سنیں", "jama karane se pehle zor se padhein aur qudrati bahao sunein"],
    ],
    589: [
        ["Combine the two ideas with aur so the story moves forward.", "دو خیالات کو اور سے جوڑیں تاکہ کہانی آگے بڑھے", "do khayaalaat ko aur se jorein taake kahaani aage barhe"],
        ["Use lekin when the second part surprises the reader a little.", "جب دوسرا حصہ حیران کرے تھوڑا سا لیکن استعمال کریں", "jab doosra hissa hairaan kare thoda sa lekin istemaal karein"],
        ["Reduce repetition by replacing a repeated noun with jo or jahan.", "دہراؤ کم کریں دہرائے ہوئے اسم کی جگہ جو یا جہاں لگائیں", "dohrao kam karein dohraaye hue ism ki jagah jo ya jahaan lagayein"],
        ["A relative clause adds detail without starting a brand-new sentence.", "وصفی فقرہ تفصیل دیتا ہے بغیر نیا جملہ شروع کیے", "wasfi faqra tafseel deta hai baghair naya jumla shuroo kiye"],
        ["Participial phrases can shorten long explanations in formal Urdu.", "اسمی جملے رسمی اردو میں لمبی وضاحت مختصر کر سکتے ہیں", "ismi jumle rasmi Urdu mein lambi wazaahat mukhtasar kar sakte hain"],
        ["Formal style avoids slang when the audience expects careful Urdu.", "سامعین کو محتاط اردو چاہیے تو رسمی انداز عام بول چال سے بچے", "saameen ko muhtaat Urdu chahiye to rasmi andaaz aam bol chaal se bache"],
        ["Paragraph unity means every sentence supports the same main point.", "پیراگراف کی یکجائی کا مطلب ہر جملہ ایک ہی مرکزی نقطے کی حمایت کرے", "paragraph ki yakjaai ka matlab har jumla ek hi markazi nuqte ki himaayat kare"],
        ["Transition words like is liye guide the reader between steps.", "اس لیے جیسے رابطہ الفاظ قارئین کو قدموں کے درمیان لے جاتے ہیں", "is liye jaise rabita alfaaz qareen ko qadmon ke darmiyaan le jaate hain"],
        ["Editing means you delete weak lines and sharpen strong ones.", "ترمیم کا مطلب کمزور سطریں حذف کرنا اور مضبوط تیز کرنا", "tarmeem ka matlab kamzor satrein hazf karna aur mazboot tez karna"],
        ["Read this example paragraph and notice how ideas link smoothly.", "یہ مثالی پیرا پڑھیں اور دیکھیں خیالات کس طرح ہموار جڑتے ہیں", "yeh misaali pira padhein aur dekhein khayaalaat kis tarah hamwaar jurate hain"],
        ["Ask a friend for peer review before you print the final copy.", "آخری کاپی چھاپنے سے پہلے دوست سے جائزہ لیں", "aakhri copy chhaapne se pehle dost se jaiza lein"],
        ["Combine short choppy lines with aur to create one flowing sentence.", "چھوٹی ٹکڑی سطریں اور سے ملا کر ایک بہتا جملہ بنائیں", "chhoti tukri satrein aur se mila kar ek bahta jumla banaayein"],
        ["When lekin appears twice, consider whether you need a new paragraph.", "جب لیکن دو بار آئے سوچیں کہ نیا پیراگراف چاہیے", "jab lekin do baar aaye sochen ke naya paragraph chahiye"],
        ["Relative clauses help you describe a person without repeating their name.", "وصفی فقرے نام دہرائے بغیر شخص بیان کرنے میں مدد دیتے ہیں", "wasfi faqre naam dohraaye baghair shakhs bayaan karne mein madad dete hain"],
        ["Formal letters often open with respect, then state the request clearly.", "رسمی خط احترام سے شروع ہو کر واضح التماس دیتے ہیں", "rasmi khat ihtiraam se shuroo ho kar waazeh iltimaas dete hain"],
        ["After peer review, sleep on the draft and read it again fresh.", "دوست کے جائزے کے بعد مسودہ رکھ کر سوئیں پھر تازہ دم پڑھیں", "dost ke jaize ke baad musawwada rakh kar soein phir taaza dam padhein"],
        ["Strong paragraphs end with a sentence that looks toward the next idea.", "مضبوط پیراگراف آخری جملے سے اگلے خیال کی طرف اشارہ کرتے ہیں", "mazboot paragraph aakhri jumle se agle khayaal ki taraf ishaara karte hain"],
    ],
    590: [
        ["After work he likes to uth baithna and stretch his back.", "کام کے بعد وہ اٹھ بیٹھنا پسند کرتا ہے اور کمر کھینچتا ہے", "kaam ke baad woh uth baithna pasand karta hai aur kamar kheenchta hai"],
        ["On Sundays we chal phirna in the park with our cousins.", "اتوار کو ہم کزنز کے ساتھ پارک میں چل پھرنا کرتے ہیں", "itwaar ko hum cousins ke saath park mein chal phirna karte hain"],
        ["Light verbs like lena and dena add a precise shade of meaning.", "لینا اور دینا جیسے ہلکے فعل معنی کا درست رنگ دیتے ہیں", "lena aur dena jaise halka fe'l ma'ne ka durust rang dete hain"],
        ["The semantic nuance changes when you swap dena for lena in a pair.", "جوڑے میں دینا کی جگہ لینا بدلنے سے معنوی فرق آتا ہے", "jore mein dena ki jagah lena badalne se ma'nawi farq aata hai"],
        ["Literary compounds sound beautiful in poetry and old novels.", "ادبی مرکب شاعری اور پرانی ناولوں میں خوب لگتے ہیں", "adabi murakkab shaairi aur purani navlon mein khoob lagte hain"],
        ["Colloquial compounds appear every day in friendly conversation.", "عام مرکب دوستانہ گفتگو میں روز آتے ہیں", "aam murakkab dostana guftugu mein roz aate hain"],
        ["Drill these pairs until your mouth remembers the natural rhythm.", "ان جوڑوں کی ورزش کریں جب تک منہ قدرتی لے یاد نہ کرے", "in joron ki warzish karein jab tak muhn qudrati le yaad na kare"],
        ["Lesson 572 introduced similar patterns; compare them side by side.", "572 میں ایسے ہی نمونے تھے انہیں ساتھ رکھ کر دیکھیں", "572 mein aise hi namoonay the unhein saath rakh kar dekhein"],
        ["In a story, characters uth baithna when they hear sudden news.", "کہانی میں کردار اچانک خبر سن کر اٹھ بیٹھتے ہیں", "kahaani mein kirdaar achanak khabar sun kar uth baithte hain"],
        ["News headlines use tight compounds to save space on the page.", "خبروں کے سرخیاں تنگ مرکب سے جگہ بچاتی ہیں", "khabron ki surkhiyan tang murakkab se jagah bachati hain"],
        ["Make a review list of ten compounds you heard this week.", "اس ہفتے سنے دس مرکب کی فہرست بنائیں", "is hafte sune das murakkab ki fehrist banaayein"],
        ["She uth baithti thi whenever someone knocked late at night.", "جب کوئی دیر رات دستک دیتا وہ اٹھ بیٹھتی تھی", "jab koi der raat dastak deta woh uth baithti thi"],
        ["We chal phirna along the river until the sun turned orange.", "ہم دریا کے ساتھ چل پھرنا کرتے رہے جب تک سورج نارنجی نہ ہوا", "hum dariya ke saath chal phirna karte rahe jab tak suraj naaranji na hua"],
        ["Writers choose compounds to show whether an action is gentle or sudden.", "لکھاری مرکب چنتے ہیں بتانے کے لیے عمل ہلکا ہے یا اچانک", "likhaari murakkab chunte hain batane ke liye amal halka hai ya achanak"],
        ["Do not mix literary compounds with slang in one formal paragraph.", "ایک رسمی پیراگراف میں ادبی مرکب اور بول چال نہ ملائیں", "ek rasmi paragraph mein adabi murakkab aur bol chaal na milayein"],
        ["Practice writing five sentences using a different compound each time.", "ہر بار مختلف مرکب استعمال کرتے ہوئے پانچ جملے لکھیں", "har baar mukhtalif murakkab istemaal karte hue paanch jumle likhein"],
        ["Your notebook should show how meaning shifts with light verb choice.", "نوٹ بک دکھائے کہ ہلکے فعل کے انتخاب سے معنی کیسے بدلتا ہے", "notebook dikhaye ke halka fe'l ke intikhab se ma'ni kaise badalta hai"],
    ],
    591: [
        ["Saying main ne khaaya sounds direct when you tell a simple story.", "میں نے کھایا سیدھا لگتا ہے جب آپ سادہ کہانی سناتے ہیں", "main ne khaaya seedha lagta hai jab aap saada kahaani sunate hain"],
        ["Passive: khaaya gaya focuses on the food, not on who ate it.", "کھایا گیا کھانے پر مرکوز ہے کھانے والے پر نہیں", "khaaya gaya khaane par markooz hai khaane wale par nahin"],
        ["The food was cooked slowly over a low flame last night.", "کل رات کھانا ہلکی آہستہ آنچ پر پکایا گیا", "kal raat khaana halki aahista aanch par pakaaya gaya"],
        ["Match gaya, gayi, or gaye with the gender and number of the subject.", "گیا، گئی، گئے فاعل کی جنس اور تعداد سے ملائیں", "gaya, gayi, gaye faa'il ki jins aur tadaad se milayein"],
        ["The letter was written by her brother, not by a stranger.", "خط اس کے بھائی نے لکھا تھا کسی اجنبی نے نہیں", "khat us ke bhai ne likha tha kisi ajnabi ne nahin"],
        ["Formal passive appears often in official letters and public notices.", "رسمی مجہول سرکاری خطوں اور اعلانوں میں اکثر آتا ہے", "rasmi majhool sarkari khaton aur elaanon mein aksar aata hai"],
        ["In daily chat people prefer active sentences that name the doer.", "روزمرہ بات میں لوگ فاعل والے فعلی جملے پسند کرتے ہیں", "roz marrah baat mein log faal wale fa'li jumle pasand karte hain"],
        ["News reports say kiya gaya when the agency hides the actor.", "جب ادارہ فاعل چھپائے تو خبر میں کیا گیا آتا ہے", "jab idaara faal chhupaaye to khabar mein kiya gaya aata hai"],
        ["Science writing uses passive to describe experiments in neutral tone.", "سائنس کی تحریر تجربے بغیر طرفداری بیان کرنے کے لیے مجہول استعمال کرتی ہے", "science ki tahreer tajriba baghair tarafdari bayaan karne ke liye majhool istemaal karti hai"],
        ["Avoid ambiguity: say clearly who did the action if it matters.", "ابہام سے بچیں اگر اہم ہو تو صاف بتائیں کس نے کیا", "ibhaam se bachein agar ahem ho to saaf batayein kis ne kiya"],
        ["Practice transforms: change five passive lines into active voice.", "تبدیلی کی مشق: پانچ مجہول سطریں فعلی میں بدلیں", "tabdeeli ki mashq: paanch majhool satre fa'li mein badlein"],
        ["Review passive endings before you edit your Urdu essay tonight.", "آج رات اردو انشاء میں ترمیم سے پہلے مجہول اختتام دہرائیں", "aaj raat Urdu inshaa mein tarmeem se pehle majhool ikhtitaam dohraayein"],
        ["The door was opened quietly while everyone was still asleep.", "دروازہ خاموشی سے کھولا گیا جب سب سو رہے تھے", "darwaza khamoshi se khola gaya jab sab so rahe the"],
        ["Mistakes were found in the first draft, so we rewrote it.", "پہلے مسودے میں غلطیاں ملیں اس لیے ہم نے دوبارہ لکھا", "pehle musawwade mein ghaltiyaan milein is liye hum ne dobara likha"],
        ["The song was sung by children at the school assembly.", "نغمہ بچوں نے اسکول کی تقریب میں گایا", "nagma bachchon ne school ki taqreeb mein gaaya"],
        ["Rules were explained twice, yet some students still felt confused.", "قواعد دو بار سمجھائے پھر بھی کچھ طلبہ گھبرائے", "qawa'id do baar samjhaaye phir bhi kuch talba ghabraaye"],
        ["A clear passive sentence still names the tool or material used.", "صاف مجہول جملہ استعمال ہوا اوزار یا مادہ بھی بتاتا ہے", "saaf majhool jumla istemaal hua ozaar ya maada bhi batata hai"],
    ],
    592: [
        ["Ho jaata hai often softens a fact and sounds less personal.", "ہو جاتا ہے حقیقت نرم کرتا ہے کم ذاتی لگتا ہے", "ho jaata hai haqeeqat narm karta hai kam zaati lagta hai"],
        ["It is known that clean water saves lives in every village.", "معلوم ہے صاف پانی ہر گاؤں میں جانیں بچاتا ہے", "maaloom hai saaf paani har gaon mein jaanein bachata hai"],
        ["People say the old bridge will close next year for repairs.", "کہا جاتا ہے پرانا پل اگلے سال مرمت کے لیے بند ہو گا", "kaha jaata hai purana pul agle saal murammat ke liye band ho ga"],
        ["Impersonal style helps when you do not want to blame anyone.", "غیر شخصی انداز مدد کرتا ہے جب کسی پر الزام نہیں لگانا", "ghair shakhsi andaaz madad karta hai jab kisi par ilzaam nahin lagana"],
        ["Official memos avoid naming a careless clerk in angry words.", "سرکاری یادداشتیں غفلت والے کلرک کا نام غصے میں نہیں لیتی", "sarkari yaad dashte ghflat wale clerk ka naam ghusse mein nahin leti"],
        ["The annual report states what kiya gaya during the whole year.", "سالانہ رپورٹ بتاتی ہے پورے سال کیا گیا", "saalana report batati hai poore saal kiya gaya"],
        ["Lesson 591 used simple passive; here the tone feels even softer.", "591 میں سادہ مجہول تھا یہاں لہجہ اور نرم ہے", "591 mein saada majhool tha yahan lahja aur narm hai"],
        ["Natural Urdu prefers these patterns in polite advice to strangers.", "قدرتی اردو مہانے مشورے میں یہ نمونے پسند کرتی ہے", "qudrati Urdu mahan mashware mein yeh namoonay pasand karti hai"],
        ["Examples fill polite posters: smoking yahan mana hai is common.", "مثالیں مہذب پوسٹر بھرتی ہیں یہاں تمباکو نوشی منع ہے عام", "misaalain muazzab poster bharti hain yahan tambākū noshi mana hai aam"],
        ["Drill ho jaata hai with weather, habits, and gentle warnings.", "موسم، عادت، نرم تنبیہ کے ساتھ ہو جاتا ہے کی ورزش کریں", "mausim, aadat, narm tanbeeh ke saath ho jaata hai ki warzish karein"],
        ["Written exercise: rewrite five blunt lines in this softer style.", "تحریری مشق: پانچ سخت سطریں اس نرم انداز میں لکھیں", "tahreeri mashq: paanch sakht satre is narm andaaz mein likhein"],
        ["It happens that trains are late when the fog is thick.", "یہ ہو جاتا ہے کہ دھند گہری ہو تو ٹرینیں دیر سے ہوں", "yeh ho jaata hai ke dhund gehari ho to trainain der se hon"],
        ["It is said that kindness spreads faster than anger in a crowd.", "کہا جاتا ہے مہربانی بھیڑ میں غصے سے تیزی سے پھیلتی ہے", "kaha jaata hai mehrbaani bheer mein ghusse se tezi se pheilti hai"],
        ["People believe the new park will open before the summer heat.", "لوگ سمجھتے ہیں نیا باغ گرمی سے پہلے کھل جائے گا", "log samajhte hain naya baagh garmi se pehle khul jaega"],
        ["It becomes clear slowly why the old rule still matters.", "دھیرے دھیرے واضح ہو جاتا ہے پرانا قاعدہ کیوں اہم ہے", "dheere dheere waazeh ho jaata hai purana qaaida kyun ahem hai"],
        ["Official Urdu often hides the subject to keep the tone neutral.", "سرکاری اردو فاعل چھپا کر لہجہ بے طرف رکھتی ہے", "sarkari Urdu faal chhupa kar lahja be taraf rakhti hai"],
        ["Practice until ho jaata hai feels polite instead of distant.", "مشق کریں جب تک ہو جاتا ہے مہذب لگے دور نہ لگے", "mashq karein jab tak ho jaata hai muazzab lage door na lage"],
    ],
    593: [
        ["I feel cold, so I will wear a thicker sweater tonight.", "مجھے سردی لگ رہی ہے اس لیے آج موٹی سوئٹر پہنوں گا", "mujhe sardi lag rahi hai is liye aaj moti sweater pehnunga"],
        ["I think so because the numbers in the report look honest.", "مجھے لگتا ہے کیونکہ رپورٹ کے اعداد صاف لگتے ہیں", "mujhe lagta hai kyunke report ke adaad saaf lagte hain"],
        ["I feel peace when I sit under the old tree.", "پرانی درخت کے نیچے بیٹھ کر سکون محسوس کرتا ہوں", "purani darakht ke neeche baith kar sukoon mehsoos karta hoon"],
        ["I think about my future every night before I sleep.", "میں ہر رات سونے سے پہلے اپنے مستقبل کے بارے میں سوچتا ہوں", "main har raat sone se pehle apne mustaqbil ke baare mein sochta hoon"],
        ["I feel happy when my little sister learns a new word.", "مجھے خوشی محسوس ہوتی ہے جب چھوٹی بہن نیا لفظ سیکھے", "mujhe khushi mehsoos hoti hai jab chhoti behen naya lafz seekhe"],
        ["What do you think about moving to a quieter neighbourhood?", "آپ خاموش محلے میں جانے کے بارے میں کیا سوچتے ہیں؟", "aap khamosh mohalle mein jaane ke baare mein kya sochte hain?"],
        ["In my view, honesty builds stronger friendships than flattery.", "میرے خیال میں صداقت چاپلوسی سے مضبوط دوستی بناتی ہے", "mere khayaal mein sadaqat chaaploosi se mazboot dosti banati hai"],
        ["Shayad she is tired; her eyes look heavy this morning.", "شاید وہ تھکی ہے آج صبح اس کی آنکھیں بھاری لگتی ہیں", "shayad woh thaki hai aaj subah us ki aankhein bhari lagti hain"],
        ["Strong jazbaat can make it hard to choose calm words.", "مضبوط جذبات پرسکون الفاظ چننا مشکل بنا دیتے ہیں", "mazboot jazbaat pursukoon alfaaz chunna mushkil bana dete hain"],
        ["The difference between lagna and sochna matters in daily Urdu.", "لگنا اور سوچنا میں فرق روزمرہ اردو میں اہم ہے", "lagna aur sochna mein farq roz marrah Urdu mein ahem hai"],
        ["My head hurts and my throat burns; we often use lagna for such feelings.", "سر درد ہے گلا جلتا ہے ایسی حالت میں اکثر لگنا آتا ہے", "sar dard hai gala jalta hai aisi haalat mein aksar lagna aata hai"],
        ["Practice writing five lines that mix feelings and opinions clearly.", "پانچ سطریں لکھیں جہاں محسوس اور خیال صاف ہو", "paanch satre likhein jahan mehsoos aur khayaal saaf ho"],
        ["I feel nervous before every exam, even when I studied well.", "ہر امتحان سے پہلے گھبراہٹ محسوس کرتا ہوں چاہے اچھی پڑھائی ہو", "har imtihaan se pehle ghabraahat mehsoos karta hoon chahe achchi padhaai ho"],
        ["She thinks the city is safer than the news often claims.", "وہ سمجھتی ہے شہر خبروں کے دعوے سے محفوظ تر ہے", "woh samajhti hai sheher khabron ke daawe se mehfooz tar hai"],
        ["What do you think we should cook for the guests tonight?", "آپ کیا سوچتے ہیں آج رات مہمانوں کے لیے کیا پکائیں؟", "aap kya sochte hain aaj raat mehmaanon ke liye kya pakaein?"],
        ["I feel grateful when strangers help without asking for money.", "مجھے شکرگاری محسوس ہوتی ہے جب اجنبی بغیر پیسے مانگے مدد کریں", "mujhe shukr guzaari mehsoos hoti hai jab ajnabi baghair paise maange madad karein"],
        ["He thinks too much about small mistakes and loses sleep.", "وہ چھوٹی غلطیوں پر بہت سوچتا ہے اور نیند کھو دیتا ہے", "woh chhoti ghaltiyon par bohot sochta hai aur neend kho deta hai"],
    ],
    594: [
        ["For her, fixing that old bike was baayein haath ka khel.", "اس کے لیے پرانی سائیکل ٹھیک کرنا بائیں ہاتھ کا کھیل تھا", "us ke liye purani cycle theek karna baayein haath ka khel tha"],
        ["We see a blue moon kabhi kabhaar in this cloudy city.", "اس بادل والے شہر میں کبھی کبھار نیلا چاند دکھتا ہے", "is baadal wale sheher mein kabhi kabhaar neela chaand dikhta hai"],
        ["Students raat bhar jaagna before exams, then sleep through breakfast.", "طلبہ امتحان سے پہلے رات بھر جاگتے پھر ناشتہ سو کر گزارتے ہیں", "talba imtihaan se pehle raat bhar jaagte phir naashta so kar guzarte hain"],
        ["Every idiom carries culture; translate the feeling, not only words.", "ہر محاورہ ثقافت رکھتا ہے لفظ نہیں جذبہ ترجمہ کریں", "har mahaawra saqaafat rakhta hai lafz nahin jazba tarjuma karein"],
        ["Context matters: the same idiom can sound rude or funny.", "سیاق اہم ہے ایک محاورہ بے ادبی یا مزاح لگ سکتا ہے", "siyaq ahem hai ek mahaawra be-adabi ya mazaah lag sakta hai"],
        ["Do not translate lafzi tarjuma every line in a joke.", "لطیفے میں ہر سطر کا لفظی ترجمہ نہ کریں", "lateefe mein har satr ka lafzi tarjuma na karein"],
        ["Collect common idioms from films, elders, and sports commentary.", "فلموں، بزرگوں، کھیل کی تبصروں سے عام محاورے جمع کریں", "filmon, buzurgon, khel ke tabsiron se aam mahaawre jama karein"],
        ["Regional variants sound different, but the picture stays similar.", "علاقائی روپ الگ لگتا ہے مگر تصویر ملتی جلتی ہے", "ilaqaai roop alag lagta hai magar tasveer milti julti hai"],
        ["Literary idioms shine in poetry, not in a tax form.", "ادبی محاورے شاعری میں چمکتے ہیں ٹیکس کے فارم میں نہیں", "adabi mahaawre shaairi mein chamakte hain tax ke form mein nahin"],
        ["Practice five idioms by writing a short scene for each.", "ہر محاورے کے لیے مختصر منظر لکھ کر پانچ کی مشق کریں", "har mahaawre ke liye mukhtasar manzar likh kar paanch ki mashq karein"],
        ["Use each idiom in a full sentence, not as a lonely label.", "ہر محاورے کو مکمل جملے میں استعمال کریں تنہا لیبل نہیں", "har mahaawre ko mukammal jumle mein istemaal karein tanha label nahin"],
        ["Review your list weekly so fresh idioms stay in memory.", "فہرست ہر ہفتے دہرائیں تاکہ نئے محاورے یاد رہیں", "fehrist har hafte dohraayein taake naye mahaawre yaad rahein"],
        ["That puzzle was baayein haath ka khel once you saw the trick.", "جب چال نظر آ گئی تو وہ پہیلی بائیں ہاتھ کا کھیل بن گئی", "jab chaal nazar aa gayi to woh paheli baayein haath ka khel ban gayi"],
        ["True friends meet kabhi kabhaar, but their bond stays warm.", "سچے دوست کبھی کبھار ملتے مگر رشتہ گرم رہتا ہے", "sache dost kabhi kabhaar milte magar rishta garam rehta hai"],
        ["Burning midnight oil is unhealthy if you skip food and water.", "رات بھر جاگنا بغیر کھانے پانی کے صحت کے لیے برا ہے", "raat bhar jaagna baghair khaane paani ke sehat ke liye bura hai"],
        ["Teachers love when students use idioms correctly in essays.", "استاد خوش ہوتے ہیں جب طلبہ انشاء میں محاورے درست استعمال کریں", "ustaad khush hote hain jab talba inshaa mein mahaawre durust istemaal karein"],
        ["Ask elders for idioms about rain, travel, and family love.", "بارش، سفر، خاندانی محبت پر بزرگوں سے محاورے پوچھیں", "baarish, safar, khaandaani mohabbat par buzurgon se mahaawre poochhein"],
    ],
    595: [
        ["She told a small joke to pehal karna at the quiet table.", "اس نے خاموش میز پر پہل کرنے کے لیے چھوٹا سا لطیفہ سنایا", "us ne khamosh mez par pehal karne ke liye chhota sa lateefa sunaya"],
        ["Calling him sang dil was unfair; he was only shy.", "اسے سنگ دل کہنا ناانصافی تھی وہ تو شرمیلا تھا", "use sang dil kehna naainsaafi thi woh to sharmeela tha"],
        ["More mahaawre make sense when you know the speaker's childhood city.", "مزید محاورے اس وقت سمجھ آتے ہیں جب بولنے والے کا بچپن کا شہر معلوم ہو", "mazeed mahaawre us waqt samajh aate hain jab bolne wale ka bachpan ka sheher maaloom ho"],
        ["A kahawat often hides a lesson older than our grandparents.", "کہاوت اکثر ایسا سبق چھپاتی ہے جو دادا دادی سے بھی پرانا ہو", "kahawat aksar aisa sabaq chhupati hai jo daada daadi se bhi purana ho"],
        ["A maqoola on the classroom wall reminded us to share books.", "کلاس کی دیوار پر مقولہ کتابیں بانٹنے کی یاد دلاتا تھا", "class ki deewar par maqoola kitaabein baantne ki yaad dilata tha"],
        ["Gentle mazaah helps friends forgive honest mistakes.", "نرم مزاح دوستوں کو صادق غلطیاں معاف کرنے میں مدد دیتا ہے", "narm mazaah doston ko saadiq ghaltiyaan maaf karne mein madad deta hai"],
        ["Wisdom literature collects short lines that guide daily choices.", "حکمت کی تحریریں روزانہ انتخاب رہنمائی کرنے والی مختصر سطریں جمع کرتی ہیں", "hikmat ki tahreerein rozana intikhab rahnumai karne wali mukhtasar satrein jama karti hain"],
        ["Compare lesson 594 idioms with these longer conversational ones.", "594 کے محاوروں سے ان لمبی بول چال والوں کا موازنہ کریں", "594 ke mahaawron se in lambi bol chaal walon ka muwaazna karein"],
        ["Write three jumle that each hides a proverb inside natural speech.", "تین ایسے جملے لکھیں جن میں کہاوت قدرتی بول میں چھپی ہو", "teen aise jumle likhein jin mein kahawat qudrati bol mein chhupi ho"],
        ["Share your sentences with a dost se and listen for corrections.", "جملے دوست سے شیئر کریں اور درستی سنیں", "jumle dost se share karein aur durusti sunein"],
        ["Quiz yourself: explain each idiom without using the same words.", "خود امتحان: ہر محاورے کو بغیر وہی الفاظ استعمال کیے سمجھائیں", "khud imtihaan: har mahaawre ko baghair wahi alfaaz istemaal kiye samjhaaein"],
        ["Break the ice at meetings with a sincere compliment, not mockery.", "میٹنگ میں پہل سچی تعریف سے کریں مذاق نہیں", "meeting mein pehal sachchi ta'reef se karein mazaaq nahin"],
        ["People called the boss sang dil, but he paid fair wages.", "لوگ باس کو سنگ دل کہتے تھے مگر وہ منصفانہ اجرت دیتا تھا", "log boss ko sang dil kehte the magar woh insaaf aana ujrat deta tha"],
        ["Proverbs travel across villages and pick up local colour.", "کہاوتیں گاؤں گاؤں جاتی ہیں اور مقامی رنگ لیتی ہیں", "kahawatein gaon gaon jaati hain aur maqaali rang leti hain"],
        ["A short maqoola on kindness can calm a noisy classroom.", "مہربانی پر مختصر مقولہ شور والی کلاس پر سکون لا سکتا ہے", "mehrbaani par mukhtasar maqoola shor wali class par sukoon la sakta hai"],
        ["Humour fails when the listener feels attacked instead of included.", "مزاح تب ٹوٹتا ہے جب سننے والا شامل ہونے کی بجائے حملہ محسوس کرے", "mazaah tab tootta hai jab sunne wala shamil hone ki bajaye hamla mehsoos kare"],
        ["Collect wisdom lines from grandparents before their stories disappear.", "دادا دادی کی کہانیاں غائب ہونے سے پہلے حکمت کی سطریں جمع کریں", "daada daadi ki kahaaniyan ghaib hone se pehle hikmat ki satrein jama karein"],
    ],
    596: [
        ["If you study with focus, you will pass the exam comfortably.", "اگر توجہ سے پڑھو گے تو امتحان آرام سے پاس ہو جاؤ گے", "agar tawajju se padho ge to imtihaan aaraam se pass ho jaoge"],
        ["Shartiyah tarteeb keeps the if-clause clear in long sentences.", "لمبے جملوں میں شرطیہ ترتیب اگر والا حصہ صاف رکھتی ہے", "lambe jumlon mein shartiyah tarteeb agar wala hissa saaf rakhti hai"],
        ["Jab tak koshish na karo, you cannot expect a miracle.", "جب تک کوشش نہ کرو معجزے کی امید نہ رکھو", "jab tak koshish na karo mu'jize ki umeed na rakho"],
        ["Agarcheh the road was wet, the driver stayed calm and slow.", "اگرچہ سڑک گیلی تھی پھر بھی ڈرائیور پرسکون اور آہستہ رہا", "agarcheh sarak geeli thi phir bhi driver pursukoon aur aahista raha"],
        ["Finish your homework tonight, or the teacher will be upset.", "آج ہی کام ختم کرو ورنہ استاد ناراض ہوں گے", "aaj hi kaam khatam karo warna ustaad naraz honge"],
        ["Lesson 546 mixed conditions; here we tie them to daily plans.", "546 میں شرطیں ملیں تھیں یہاں انہیں روزانہ منصوبوں سے جوڑتے ہیں", "546 mein sharten milein thin yahan unhein rozana mansoobon se jorte hain"],
        ["A formal inshaa needs clear if-then links between paragraphs.", "رسمی انشاء میں پیراگرافوں کے درمیان واضح اگر پھر تعلق چاہیے", "rasmi inshaa mein paragraphon ke darmiyaan waazeh agar phir talluq chahiye"],
        ["Informal Urdu with friends often uses short if-you sentences.", "دوستوں کے ساتھ بول چال میں مختصر اگر تم جملے آتے ہیں", "doston ke saath bol chaal mein mukhtasar agar tum jumle aate hain"],
        ["Multiple muta'addad sharten need careful order so nobody gets lost.", "متعدد شرطیں احتیاط سے ترتیب چاہتی ہیں ورنہ کوئی بھول جائے", "muta'addad sharten ehtiyat se tarteeb chahti hain warna koi bhool jaaye"],
        ["Avoid ibhaam by saying exactly which action depends on which condition.", "ابہام سے بچیں صاف بتائیں کون سا عمل کس شرط پر منحصر ہے", "ibhaam se bachein saaf batayein kaun sa amal kis shart par munhasir hai"],
        ["Write one paragraph that uses three different types of if.", "ایک پیراگراف لکھیں جس میں تین قسم کے اگر ہوں", "ek paragraph likhein jis mein teen qism ke agar hon"],
        ["Review tamam agar patterns from this book before the final test.", "آخری امتحان سے پہلے اس کتاب کے تمام اگر کے نمونے دہرائیں", "aakhri imtihaan se pehle is kitaab ke tamam agar ke namoonay dohraayein"],
        ["If it rains, we will stay indoors; otherwise we will walk.", "اگر بارش ہوئی تو اندر رہیں گے ورنہ چلیں گے", "agar baarish hui to andar rahenge warna chalenge"],
        ["Unless you sleep early, you will feel tired at school.", "جب تک جلدی نہ سوؤ سکول میں تھکان محسوس ہو گی", "jab tak jaldi na sou school mein thakan mehsoos hogi"],
        ["Even if you fail once, you can try again with new methods.", "اگرچہ ایک بار ناکام ہو جاؤ نئے طریقے سے دوبارہ کوشش کر سکتے ہو", "agarcheh ek baar nakaam ho jao naye tareeqe se dobara koshish kar sakte ho"],
        ["If the bus is late, call me; otherwise I will wait outside.", "اگر بس دیر سے ہو تو فون کرنا ورنہ میں باہر انتظار کروں گا", "agar bus der se ho to phone karna warna main bahar intizaar karunga"],
        ["Think through every condition before you promise a quick answer.", "جلدی جواب دینے سے پہلے ہر شرط سوچ لیں", "jaldi jawaab dene se pehle har shart soch lein"],
    ],
}
