# Urdu Lesson 1 — Script & pronunciation (chapter IDs 501–509).
# Columns: English, Urdu (Arabic script), Transliteration (Roman Urdu).

LESSONS_S1 = {
    501: [
        ["Urdu is written from right to left", "اردو دائیں سے بائیں لکھی جاتی ہے", "Urdu daayen se baayen likhi jaati hai"],
        ["The Urdu alphabet has 36 consonant letters", "حروفِ تہجی میں چھتیس حروفِ صحیح ہیں", "Huroof-e tahajji mein chhattis huroof-e sahi hain"],
        ["ا alif — vowel carrier or long aa", "ا", "alif"],
        ["ب be", "ب", "be"],
        ["پ pe", "پ", "pe"],
        ["ت te", "ت", "te"],
        ["ٹ ṭe (retroflex)", "ٹ", "ṭe"],
        ["ث se", "ث", "se"],
        ["ج jeem", "ج", "jeem"],
        ["چ che", "چ", "che"],
        ["ح baṛi he", "ح", "baṛi he"],
        ["خ khe", "خ", "khe"],
        ["د daal", "د", "daal"],
        ["ڈ ḍaal", "ڈ", "ḍaal"],
        ["ذ zaal", "ذ", "zaal"],
        ["Practice: read aloud ب، پ، ت، ٹ", "ب پ ت ٹ پڑھیں", "be pe te ṭe padhein"],
    ],
    502: [
        ["Short vowel a — zabar above the letter", "زبر سے آوازِ 'ا' آتی ہے", "Zabar se aawaaz 'a' aati hai"],
        ["Short vowel i — zer below the letter", "زیر سے آوازِ 'اِ' آتی ہے", "Zer se aawaaz 'i' aati hai"],
        ["Short vowel u — pesh above the letter", "پیش سے آوازِ 'ُ' آتی ہے", "Pesh se aawaaz 'u' aati hai"],
        ["Long aa — alif after consonant", "بَ + ا = با", "ba"],
        ["Long ee — yā with two dots below in final form", "بِ + ی = بی", "bi"],
        ["Long oo — vāo with pesh", "بُ + و = بو", "bu / bo context"],
        ["Consonant ر re (rolled lightly)", "ر", "re"],
        ["Consonant ز ze", "ز", "ze"],
        ["ژ zhe (Persian)", "ژ", "zhe"],
        ["س seen", "س", "seen"],
        ["ش sheen", "ش", "sheen"],
        ["ص suaad", "ص", "suaad"],
        ["ض zuaad", "ض", "zuaad"],
        ["Practice syllables: کَ، کِ، کُ", "کَ کِ کُ", "ka ki ku"],
        ["Read words: کتاب، پانی", "کتاب، پانی", "kitaab, paani"],
    ],
    503: [
        ["Most letters change shape: initial, medial, final", "حروف کی شکلیں بدلتی ہیں", "Huroof ki shaklein badalti hain"],
        ["ب initial: بـ — medial: ـبـ — final: ـب", "بـ ـبـ ـب", "be joint forms"],
        ["ک + زبر + ن = کن (kan)", "کن", "kan"],
        ["م + زیر + ن = مِن (min)", "مِن", "min"],
        ["ل + پیش + ن = لُن", "لُن", "lun"],
        ["Double consonant: tashdeed ّ", "شُدّت", "shuddah / tashdeed"],
        ["Silent alif at end in some words", "الفِ مقصور", "alif maqsoora"],
        ["هَے he — often pronounced as aspiration or h", "ہ", "he"],
        ["ی ye — y sound or long ee", "ی", "ye"],
        ["ے bari ye — always long ae at end", "ے", "bari ye"],
        ["و vāo — u, o, or w", "و", "vāo"],
        ["Practice: مَدرَسَہ، مَکتَب", "مدرسہ، مکتب", "madrasa, maktab"],
        ["Write and read: سَلام", "سلام", "salaam"],
        ["Join: م + ل = مل", "مل", "mil"],
        ["Read a short line aloud and notice how each letter joins its neighbour.", "ایک مختصر سطر زور سے پڑھیں اور دیکھیں ہر حرف پڑوسی سے کیسے ملتا ہے", "ek mukhtasar satr zor se padhein aur dekhein har harf parosi se kaise milta hai"],
    ],
    504: [
        ["ق qaaf is back 'q' — not like English k", "قاف گلے سے ادا ہوتا ہے", "Qaaf gale se ada hota hai"],
        ["ک kaaf is forward k", "کاف زبان کے سامنے", "Kaaf zubaan ke saamne"],
        ["غ ghain is voiced velar fricative", "غین گلے کی آواز", "Ghain gale ki aawaaz"],
        ["ع ain is a glottal stop from throat", "عین حلق سے", "Ain halq se"],
        ["Don't confuse س seen and ص suaad", "سین اور صواد الگ ہیں", "Seen aur suaad alag hain"],
        ["Retroflex ٹ ڈ with tongue curled", "ٹ ڈ زبان پیچھے", "Ṭ ḍ zubaan peechhe"],
        ["ژ zhe is rare — like French 'j'", "ژ نایاب حرف", "Zhe nayaab harf"],
        ["Practice minimal pairs: کال، قال", "کال، قال", "kaal, qaal"],
        ["Listen: تین، طین (if distinguished)", "تین", "teen"],
        ["Clear aspiration: کھ not ک + ہ", "کھ ایک دم ہے", "Kh ek dum hai"],
        ["Read slowly: اَحْمَد، قُرآن", "احمد، قرآن", "Ahmad, Qur'an"],
        ["Stress: usually last syllable in Urdu words", "زور آخر پر", "Zor aakhir par"],
        ["Record and compare your reading", "اپنی آواز ریکارڈ کریں", "Apni aawaaz record karein"],
        ["Say qaal and kaal one after the other until the throat feels the difference.", "قال اور کال ایک کے بعد ایک بولیں جب تک گلے کو فرق محسوس نہ ہو", "qaal aur kaal ek ke baad ek bolein jab tak gale ko farq mehsoos na ho"],
        ["Ask a friend to listen and tell you if your qaaf is too soft.", "دوست سے کہیں وہ سن کر بتائے آیا آپ کا قاف بہت ہلکا تو نہیں", "dost se kahein woh sun kar bataye kya aap ka qaaf bahut halka to nahin"],
    ],
    505: [
        ["Noon ghunna: nasal ن when doubled or marked", "نونِ غنّہ ناک کی آواز", "Noon-e ghunna naak ki aawaaz"],
        ["In ـن٘ـ the sound is nasalized", "نشان سے ناک کی آواز", "Nishaan se naak ki aawaaz"],
        ["Compare: مَن (measure) vs مَں (with ghunna)", "فرق سمجھیں", "Farq samjhein"],
        ["At end of some words: گَن٘", "گان٘", "gan nasal"],
        ["Tanween: ً doubles noon sound (formal)", "تنوین", "Tanween"],
        ["Practice: اُن٘، مِن٘", "ان٘، من٘", "un, min nasal"],
        ["Listen to مَیں، تُمھیں", "میں، تمھیں", "main, tumhein"],
        ["Nasalization in phrases: اُس کا → اُسکا", "رَبط میں ناک کی آواز", "Rabt mein naak ki aawaaz"],
        ["Don't drop ghunna in مَیں", "میں میں غنّہ", "Main mein ghunna"],
        ["Poetry often keeps full nasal sounds", "شاعری میں واضح", "Shaairi mein waazeh"],
        ["Read: سَن٘گ، پَن٘چ", "سنگ، پنچ", "sang, panch"],
        ["Contrast: کَم (less) and nasal forms", "کم اور ناک والی آواز", "Kam aur naak waali aawaaz"],
        ["Minimal practice: اُن٘ vs اُن", "ان٘، ان", "nasal vs clear n"],
        ["Teacher models — repeat three times", "استاد کی آواز سنیں", "Ustaad ki aawaaz sunein"],
        ["Hum the word main and keep your nose gently engaged for ghunna.", "میں لفظ گنگنائیں اور غنّہ کے لیے ناک ہلکی سی شامل رکھیں", "main lafz gungunaayein aur ghunna ke liye naak halki si shaamil rakhein"],
    ],
    506: [
        ["Two consonants join without full vowel between", "حروف مل کر بَنْد ہوتے ہیں", "Huroof mil kar band hote hain"],
        ["ب + ج = بج (baj)", "بج", "baj"],
        ["ک + ت = کت (kat)", "کت", "kat"],
        ["س + ت = ست (sat)", "ست", "sat"],
        ["م + ل = مل (mil)", "مل", "mil"],
        ["ن + د = ند (nad)", "ند", "nad"],
        ["Split from right: شَکْل = ش + ک + ل", "شکل", "shakl"],
        ["Common cluster: سْت in اُسْتاد", "استاد", "ustaad"],
        ["سْپ in مَسْپَت", "مستقل", "mustaqil context"],
        ["Practice writing: پْر، تْر", "پر، تر", "par, tar"],
        ["Read: پْر، شَر، کْر", "پر، شر، کر", "par, shar, kar"],
        ["Initial cluster: فْر in فْرید", "فرید", "Fareed"],
        ["Don't insert extra vowel in clusters", "بیچ میں زائد حرکت نہ", "Beech mein zaid harakat na"],
        ["Dictation: کَمْرَہ، دَرْوازَہ", "کمرہ، دروازہ", "kamra, darwaaza"],
        ["Review: write پْرَن٘دَہ", "پرندہ", "parinda"],
    ],
    507: [
        ["ر joins as ـرـ in the middle", "ر وسط میں", "re wast mein"],
        ["ب + ر = بر (bar)", "بر", "bar"],
        ["پ + ر = پر (par)", "پر", "par"],
        ["س + ر = سر (sar)", "سر", "sar"],
        ["ش + ر = شر (shar)", "شر", "shar"],
        ["Double ر possible in Arabic loans", "دو رّ", "do rr"],
        ["Contrast: تَرَش (sharp) vs تَرَک", "ترش، ترک", "tarsh, tarak"],
        ["Practice: دَرْد، زَرْد", "درد، زرد", "dard, zard"],
        ["Read sentence: رَستَہ سَدَک", "راستہ، سڑک", "raasta, sadak"],
        ["ر at end: شَرْر", "شرر", "sharar"],
        ["Listen: قَدْر، حَضْر", "قدر، حاضر", "qadr, haazir"],
        ["Write: مُرْغی، پَر", "مرغی، پر", "murghi, par"],
        ["Common word: دُرُسْت", "درست", "durust"],
        ["Tongue tip for ر — light tap", "زبان کی نوک ہلکی", "Zubaan ki nok halki"],
        ["Review clusters with ر in daily words", "روزمرّہ الفاظ", "Rozmarrah alfaaz"],
    ],
    508: [
        ["هَے (he) often forms هَے، کہ، مَھ", "ہ کی شکلیں", "He ki shaklein"],
        ["ہ + ی = ہی (hi)", "ہی", "hi"],
        ["ک + ہ + ی = کہہ (kah)", "کہ", "kah"],
        ["م + ہ = مَھ (mh) in some dialects", "مھ", "mh"],
        ["Ghost vowel after ہ in کہنا", "کہنا", "kehna"],
        ["Contrast: ح (baṛi he) vs ہ (gol he)", "ح اور ہ فرق", "He aur he farq"],
        ["Practice: مَہْر، تَہْر", "مہر، تہر", "mahr, tahar"],
        ["Read: بَہْت، کَہْن٘ا", "بہت، کہنا", "bohat, kehna"],
        ["Final ہ silent sometimes: کَہْن٘ا", "کہنا", "kehna"],
        ["In شَہْر the ہ is pronounced", "شہر", "shehar"],
        ["Write: گَھر، بَھر", "گھر، بھر", "ghar, bhar"],
        ["Medial ہ: جَہَن٘ن٘", "جہنم", "jahannam"],
        ["Listen carefully: وَہْم vs وَاد", "وہم، واد", "vahm, waad"],
        ["Practice phrases: کَیا ہَے؟", "کیا ہے؟", "Kya hai?"],
        ["Review: ہَر، دَھوپ", "ہر، دھوپ", "har, dhoop"],
    ],
    509: [
        ["Special ligature: لا (lām + alif)", "لا", "laa"],
        ["Allah — unique joining", "اللہ", "Allah"],
        ["Lām + alif in ﻻ shape in some fonts", "ﻻ", "laa ligature"],
        ["چَشْم (eye) — Persian cluster", "چشم", "chashm"],
        ["Double ی in عَیْن shapes", "عین", "ain"],
        ["Arabic definite article الـ assimilates", "ال٘ (sun letters)", "al- assimilation"],
        ["Don't break لا in handwriting incorrectly", "لا کا جوڑ", "Laa ka jor"],
        ["Practice: مَسْجِد، مَدْرَسَہ", "مسجد، مدرسہ", "masjid, madrasa"],
        ["Read: بَخْشِش، شَکْرِیَہ", "بخشش، شکریہ", "bakhshish, shukriya"],
        ["Rare ligatures in loanwords", "قرض، ذخیرہ", "qarz, zakheera"],
        ["Font note: Nastaliq joins flowing shapes", "نستعلیق میں جوڑ", "Nasta'liq mein jor"],
        ["Write full phrase: بِسْمِ اللّٰہ", "بسم اللہ", "Bismillah"],
        ["Review all joint letters from Lessons 1–9", "تمام مشق دہرائیں", "Tamam mashq dohraayein"],
        ["Self-check: read a short line aloud", "ایک سطر اونچی آواز میں", "Ek satr oonchi aawaaz mein"],
        ["Next: grammar — pronouns and verbs", "آگے: ضمیر اور فعل", "Aage: zameer aur fe'l"],
    ],
}
