# Urdu Lesson 2 — Grammar chunk B (chapter IDs 527–542).

LESSONS_S2B = {
    527: [
        ["my book", "میری کتاب", "meri kitaab"],
        ["your pen (informal m.)", "تمہارا قلم", "tumhara qalam"],
        ["his house", "اس کا گھر", "us ka ghar"],
        ["her bag", "اس کا بیگ", "us ka bag"],
        ["our school", "ہمارا اسکول", "hamara school"],
        ["their car", "ان کی گاڑی", "unki gaadi"],
        ["my (m. object) — میرا", "میرا", "mera"],
        ["my (f.) — میری", "میری", "meri"],
        ["my (pl.) — میرے", "میرے", "mere"],
        ["his / her own — اپنا", "اپنا", "apna"],
        ["your (polite) — آپ کا", "آپ کا", "aap ka"],
        ["This is my friend", "یہ میرا دوست ہے", "yeh mera dost hai"],
        ["That is her book", "وہ اس کی کتاب ہے", "woh us ki kitaab hai"],
        ["Possession with کا، کی، کے", "کا، کی، کے", "ka, ki, ke"],
        ["After postposition: میرے گھر میں", "میرے گھر میں", "mere ghar mein"],
        ["Reflexive: وہ اپنا کام کرتا ہے", "وہ اپنا کام کرتا ہے", "woh apna kaam karta hai"],
    ],
    528: [
        ["what?", "کیا؟", "kya?"],
        ["who?", "کون؟", "kaun?"],
        ["where?", "کہاں؟", "kahaan?"],
        ["when?", "کب؟", "kab?"],
        ["why?", "کیوں؟", "kyun?"],
        ["how?", "کیسے؟", "kaise?"],
        ["how much / many?", "کتنا / کتنے؟", "kitna / kitne?"],
        ["which?", "کون سا؟", "kaun sa?"],
        ["What is your name? (polite)", "آپ کا نام کیا ہے؟", "aap ka naam kya hai?"],
        ["Where do you live?", "آپ کہاں رہتے ہیں؟", "aap kahaan rehte hain?"],
        ["When will you come?", "آپ کب آئیں گے؟", "aap kab aayenge?"],
        ["Why are you sad?", "آپ اداس کیوں ہیں؟", "aap udaas kyun hain?"],
        ["How is the weather?", "موسم کیسا ہے؟", "mausam kaisa hai?"],
        ["Whose book is this?", "یہ کتاب کس کی ہے؟", "yeh kitaab kis ki hai?"],
        ["Question word + کیا in emphasis", "کیا واقعی؟", "kya waqai?"],
        ["Indirect questions", "میں نے پوچھا کہ کہاں", "main ne poocha ke kahaan"],
    ],
    529: [
        ["I do not eat", "میں نہیں کھاتا", "main nahin khaata"],
        ["she does not read", "وہ نہیں پڑھتی", "woh nahin padhti"],
        ["we do not know", "ہم نہیں جانتے", "hum nahin jaante"],
        ["they do not come", "وہ نہیں آتے", "woh nahin aate"],
        ["it does not work", "یہ نہیں چلتا", "yeh nahin chalta"],
        ["I am not tired", "میں تھکا نہیں", "main thaka nahin"],
        ["No + verb: نہیں before verb", "نہیں فعل سے پہلے", "nahin fe'l se pehle"],
        ["I don't want tea", "مجھے چائے نہیں چاہیے", "mujhe chai nahin chahiye"],
        ["She doesn't speak Urdu", "وہ اردو نہیں بولتی", "woh Urdu nahin bolti"],
        ["Don't worry (informal)", "فکر مت کرو", "fikar mat karo"],
        ["We don't agree", "ہم متفق نہیں", "hum muttafiq nahin"],
        ["Negative of 'hai'", "نہیں ہے", "nahin hai"],
        ["Double negative avoided", "دو منفی نہ", "do manfi na"],
        ["Rhetorical: کیا میں نہیں جانتا؟", "کیا میں نہیں جانتا؟", "kya main nahin jaanta?"],
        ["Politeness: نہیں، شکریہ", "نہیں، شکریہ", "nahin, shukriya"],
    ],
    530: [
        ["I did not go", "میں نہیں گیا", "main nahin gaya"],
        ["she did not call", "وہ نہیں بلائی", "woh nahin bulaayi"],
        ["we did not see", "ہم نے نہیں دیکھا", "hum ne nahin dekha"],
        ["they did not arrive", "وہ نہیں پہنچے", "woh nahin pahunche"],
        ["I didn't eat (trans.)", "میں نے نہیں کھایا", "main ne nahin khaaya"],
        ["He didn't open", "اس نے نہیں کھولا", "us ne nahin khola"],
        ["Past negative with نے", "نے کے ساتھ نہیں", "ne ke saath nahin"],
        ["Was not / were not", "نہیں تھا / نہیں تھے", "nahin tha / nahin the"],
        ["I had no time", "میرے پاس وقت نہیں تھا", "mere paas waqt nahin tha"],
        ["She never lied", "اس نے کبھی جھوٹ نہیں بولا", "us ne kabhi jhoot nahin bola"],
        ["We couldn't find", "ہم نہیں ڈھونڈ سکے", "hum nahin dhoondh sake"],
        ["Negative in story", "کہانی میں منفی", "kahaani mein manfi"],
        ["Didn't you know? (polite)", "کیا آپ نہیں جانتے تھے؟", "kya aap nahin jaante the?"],
        ["Emphatic: بالکل نہیں", "بالکل نہیں", "bilqul nahin"],
        ["Compare present vs past neg.", "حال اور ماضی", "haal aur maazi"],
    ],
    531: [
        ["I will not go", "میں نہیں جاؤں گا", "main nahin jaaunga"],
        ["she will not come", "وہ نہیں آئے گی", "woh nahin aayegi"],
        ["we will not forget", "ہم نہیں بھولیں گے", "hum nahin bhooleinge"],
        ["they will not agree", "وہ متفق نہیں ہوں گے", "woh muttafiq nahin honge"],
        ["it will not rain", "بارش نہیں ہو گی", "baarish nahin hogi"],
        ["Future negative: نہیں + گا/گی/گے", "نہیں + گا", "nahin + ga"],
        ["I won't tell anyone", "میں کسی کو نہیں بتاؤں گا", "main kisi ko nahin bataunga"],
        ["He won't be late", "وہ دیر سے نہیں آئے گا", "woh der se nahin aayega"],
        ["We shall not give up", "ہم ہار نہیں مانیں گے", "hum haar nahin maanenge"],
        ["Polite: نہیں کریں گے", "نہیں کریں گے", "nahin karenge"],
        ["Probability neg: شاید نہ ہو", "شاید نہ ہو", "shayad na ho"],
        ["Promise: نہیں چھوڑوں گا", "نہیں چھوڑوں گا", "nahin chhorunga"],
        ["Conditional: تو نہیں جاؤں گا", "تو نہیں جاؤں گا", "to nahin jaaunga"],
        ["News style", "خبری جملے", "khabari jumle"],
        ["Practice: نہیں + مستقبل", "مشق", "mashq"],
    ],
    532: [
        ["boy (m.)", "لڑکا", "larka"],
        ["girl (f.)", "لڑکی", "larki"],
        ["books (m. plural)", "کتابیں", "kitaaben"],
        ["houses", "گھر", "ghar"],
        ["Plural: ـیں، ـوں", "یں، وں", "-en, -on"],
        ["Respect plural: لوگ", "لوگ", "log"],
        ["Oblique singular: لڑکے کو", "لڑکے کو", "larke ko"],
        ["Oblique plural: لڑکوں کو", "لڑکوں کو", "larkon ko"],
        ["Gender affects adjectives", "صفت میں جنس", "sifat mein jins"],
        ["big (m.) — بڑا", "بڑا", "baṛa"],
        ["big (f.) — بڑی", "بڑی", "baṛi"],
        ["big (pl.) — بڑے", "بڑے", "baṛe"],
        ["These boys", "یہ لڑکے", "yeh larke"],
        ["Those girls", "وہ لڑکیاں", "woh larkiyaan"],
        ["Counting: ایک، دو، تین", "ایک، دو، تین", "ek, do, teen"],
    ],
    533: [
        ["in the room", "کمرے میں", "kamre mein"],
        ["on the roof", "چھت پر", "chhat par"],
        ["under the tree", "درخت کے نیچے", "darakht ke neeche"],
        ["with my friend", "دوست کے ساتھ", "dost ke saath"],
        ["from Delhi", "دہلی سے", "Dilli se"],
        ["to the market", "بازار کو", "bazaar ko"],
        ["for the child", "بچے کے لیے", "bachche ke liye"],
        ["Oblique before postposition", "حالتِ جار", "haalat-e jaarr"],
        ["Noun + کے + postposition", "کے کا استعمال", "ke ka istemaal"],
        ["in my house", "میرے گھر میں", "mere ghar mein"],
        ["on this table", "اس میز پر", "is mez par"],
        ["without money", "پیسے کے بغیر", "paise ke baghair"],
        ["during the day", "دن کے دوران", "din ke dauraan"],
        ["until evening", "شام تک", "shaam tak"],
        ["between you and me", "تم اور میرے درمیان", "tum aur mere darmiyaan"],
    ],
    534: [
        ["on — پر (surface)", "پر", "par"],
        ["in — میں (inside)", "میں", "mein"],
        ["near — پاس", "پاس", "paas"],
        ["beside — کنارے", "کنارے", "kinaare"],
        ["par vs mein: book ___ table", "کتاب میز پر", "kitaab mez par"],
        ["se: from / by / since", "سے", "se"],
        ["tak: until", "تک", "tak"],
        ["tak vs se: وقت تک", "وقت تک", "waqt tak"],
        ["Similar sound: پر / پھر", "پر / پھر", "par / phir"],
        ["Mix-up: میں vs میں (I vs in)", "میں بمقابلہ میں", "main vs mein"],
        ["Listen minimal pairs", "سنئیے فرق", "suniye farq"],
        ["Practice: وہ گھر میں ہے", "وہ گھر میں ہے", "woh ghar mein hai"],
        ["He is on the way", "وہ راستے میں ہے", "woh raaste mein hai"],
        ["Context fixes meaning", "سیاق سے معنی", "siyaq se maani"],
        ["Review exercises", "ورزش", "warzish"],
    ],
    535: [
        ["Direct case (subject)", "مرفوع", "marfoo'"],
        ["Oblique before postposition", "مجرور", "majroor"],
        ["Ergative: نے with transitive past", "فاعلِ مجہول نہیں — نے", "faa'il — ne"],
        ["Dative: کو for recipient", "مفعولِ بیض — کو", "mafoo'l — ko"],
        ["Ablative: سے from", "جار — سے", "jaar — se"],
        ["Locative: میں، پر", "میں، پر", "mein, par"],
        ["Possessive: کا، کی، کے", "کا، کی، کے", "ka, ki, ke"],
        ["I — subject: میں", "میں", "main"],
        ["I — oblique: مجھ", "مجھ", "mujh"],
        ["with me: میرے ساتھ", "میرے ساتھ", "mere saath"],
        ["to me: مجھے", "مجھے", "mujhe"],
        ["Pronoun + ne: میں نے", "میں نے", "main ne"],
        ["Noun inflection: لڑکے نے", "لڑکے نے", "larke ne"],
        ["Cases in Urdu vs Sanskrit labels", "اردو میں حالات", "Urdu mein halaat"],
        ["Practice: سے، کو، نے", "مشق", "mashq"],
    ],
    536: [
        ["Come! (informal)", "آؤ!", "aao!"],
        ["Come! (polite)", "آئیے!", "aaiye!"],
        ["Sit!", "بیٹھو!", "baitho!"],
        ["Please sit (polite)", "بیٹھ جائیے!", "baith jaaiye!"],
        ["Go!", "جاؤ!", "jaao!"],
        ["Don't go! (informal)", "مت جاؤ!", "mat jaao!"],
        ["Don't worry!", "فکر مت کرو!", "fikar mat karo!"],
        ["Let's go", "چلیں!", "chalein!"],
        ["Let him speak", "بولنے دو", "bolne do"],
        ["Imperative for 'aap': ـیے", "لیجیے", "liijiye"],
        ["Negative imperative: مت + verb", "مت + فعل", "mat + fe'l"],
        ["Polite request: براہِ کرم", "براہِ کرم", "baraahe karam"],
        ["Written order: ہدایت", "ہدایت", "hidaayat"],
        ["Soft: ذرا یہ لیں", "ذرا یہ لیں", "zara yeh lein"],
        ["Strong: فوراً کرو", "فوراً کرو", "foran karo"],
    ],
    537: [
        ["today", "آج", "aaj"],
        ["yesterday", "کل", "kal"],
        ["tomorrow", "کل / آئندہ", "kal / aainda"],
        ["now", "اب", "ab"],
        ["then", "پھر", "phir"],
        ["morning", "صبح", "subah"],
        ["evening", "شام", "shaam"],
        ["night", "رات", "raat"],
        ["hour", "گھنٹہ", "ghanta"],
        ["minute", "منٹ", "minute"],
        ["week", "ہفتہ", "hafta"],
        ["month", "مہینہ", "maheena"],
        ["year", "سال", "saal"],
        ["often", "اکثر", "aksar"],
        ["sometimes", "کبھی کبھی", "kabhi kabhi"],
        ["I will come tomorrow", "میں کل آؤں گا", "main kal aaunga"],
    ],
    538: [
        ["to feed — کھلانا", "کھلانا", "khilaana"],
        ["to show — دکھلانا", "دکھلانا", "dikhlaana"],
        ["to read aloud — پڑھوانا", "پڑھوانا", "padhwaana"],
        ["Causative pattern", "سببیت", "sababiyat"],
        ["I made him sit", "میں نے اسے بٹھایا", "main ne use bithaaya"],
        ["She got the work done", "اس نے کام کروایا", "us ne kaam karwaaya"],
        ["Teacher makes us write", "استاد لکھواتے ہیں", "ustaad likhwaate hain"],
        ["Double causative (rare)", "دوہری سببیت", "dohri sababiyat"],
        ["padhana: to teach", "پڑھانا", "padhaana"],
        ["sunwana: to have someone listen", "سنوانا", "sunwaana"],
        ["Compare: کھانا vs کھلانا", "کھانا، کھلانا", "khaana, khilaana"],
        ["Politeness with causative", "ادب", "adab"],
        ["Children are fed", "بچوں کو کھلایا جاتا ہے", "bachchon ko khilaaya jaata hai"],
        ["Practice sentences", "جملے", "jumle"],
        ["Review", "دہرائیں", "dohraayein"],
    ],
    539: [
        ["Verb agrees with subject in present", "فعل فاعل سے", "fe'l faa'il se"],
        ["Past transitive: verb agrees with object", "ماضی متعدی", "maazi muta'addi"],
        ["Feminine object → feminine verb form", "مؤنث مفعول", "mu'annas mafoo'l"],
        ["Plural object → plural verb", "جمع مفعول", "jama' mafoo'l"],
        ["Examples: نے کتاب پڑھی", "نے کتاب پڑھی", "ne kitaab padhi"],
        ["نے کھانا کھایا (m. object)", "نے کھانا کھایا", "ne khaana khaaya"],
        ["Adjective with noun: بڑی کتاب", "بڑی کتاب", "baṛi kitaab"],
        ["Demonstratives agree: یہ اچھی ہے", "یہ اچھی ہے", "yeh achhi hai"],
        ["Honorific plural verb with آپ", "آپ ہیں", "aap hain"],
        ["Common errors", "عام غلطیاں", "aam ghaltiyaan"],
        ["Drill: وہاں، وہ، وہی", "وہاں، وہ", "wahaan, woh"],
        ["Agreement in subordinate clause", "ذیلی جملے میں", "zeele jumle mein"],
        ["Poetic freedom", "شاعری میں آزادی", "shaairi mein aazaadi"],
        ["Written vs spoken", "تحریری اور زبانی", "tahreeri aur zabaani"],
        ["Practice", "مشق", "mashq"],
    ],
    540: [
        ["I have done (alternate style)", "میں نے کر لیا", "main ne kar liya"],
        ["she has taken", "اس نے لے لی", "us ne le li"],
        ["we had gone", "ہم چلے گئے تھے", "hum chale gaye the"],
        ["Compound: چلا گیا، کر لیا", "چلا گیا", "chala gaya"],
        ["Light verbs: لینا، دینا، دینا", "لے، دے", "le, de"],
        ["Perfect with لینا: پڑھ لیا", "پڑھ لیا", "padh liya"],
        ["Gone: چلا گیا vs گیا", "فرق", "farq"],
        ["Colloquial shortening", "بول چال میں مختصر", "bol chaal mein mukhtasar"],
        ["I had finished eating", "میں نے کھانا کھا لیا تھا", "main ne khaana khaa liya tha"],
        ["She will have left", "وہ جا چکی ہو گی", "woh ja chuki hogi"],
        ["News: ہو چکا، کر دیا گیا", "ہو چکا", "ho chuka"],
        ["Formal letter style", "خط کی زبان", "khat ki zabaan"],
        ["Compare lesson 523 patterns", "523 سے موازنہ", "523 se muqaabla"],
        ["They had already closed the shop when we finally arrived.", "جب ہم آخر کار پہنچے دکان پہلے ہی بند ہو چکی تھی", "jab hum aakhir kaar pahunche dukaan pehle hi band ho chuki thi"],
        ["Practice", "مشق", "mashq"],
    ],
    541: [
        ["I have been reading", "میں پڑھ رہا ہوں (عرصے سے)", "main padh raha hoon (arse se)"],
        ["she has been working", "وہ کام کر رہی ہے (دیر سے)", "woh kaam kar rahi hai (der se)"],
        ["they had been waiting", "وہ انتظار کر رہے تھے", "woh intizaar kar rahe the"],
        ["for + time + se", "سے کے ساتھ", "se ke saath"],
        ["since morning I have been busy", "صبح سے مصروف ہوں", "subah se masroof hoon"],
        ["Emphasis on duration", "مدت پر زور", "muddat par zor"],
        ["Less common than English -ing for years", "سالوں سے", "saalon se"],
        ["Alternative: سے verb present", "سے + حال", "se + haal"],
        ["I have been living here since 2010", "۲۰۱۰ سے یہاں ہوں", "2010 se yahaan hoon"],
        ["She has been teaching", "وہ پڑھا رہی ہے", "woh padhaa rahi hai"],
        ["Negative: نہیں رہا", "نہیں رہا", "nahin raha"],
        ["Literary", "ادبی", "adabi"],
        ["Spoken shortcut", "مختصر بول", "mukhtasar bol"],
        ["Compare perfect continuous English", "انگریزی سے", "Angrezi se"],
        ["Review", "دہرائیں", "dohraayein"],
    ],
    542: [
        ["no — not any", "نہیں — کوئی نہیں", "nahin — koi nahin"],
        ["I don't want", "مجھے نہیں چاہیے", "mujhe nahin chahiye"],
        ["I don't want tea", "مجھے چائے نہیں چاہیے", "mujhe chai nahin chahiye"],
        ["no problem", "کوئی بات نہیں", "koi baat nahin"],
        ["there isn't / aren't", "نہیں ہے / نہیں ہیں", "nahin hai / nahin hain"],
        ["Don't want vs don't have", "چاہیے نہیں vs نہیں ہے", "chahiye nahin vs nahin hai"],
        ["Pasand nahin: dislike", "پسند نہیں", "pasand nahin"],
        ["Refusal politely", "نفی مہربانی سے", "nafi meherbaani se"],
        ["I don't need it", "مجھے ضرورت نہیں", "mujhe zaroorat nahin"],
        ["He doesn't want to go", "وہ جانا نہیں چاہتا", "woh jaana nahin chahta"],
        ["We don't wish to argue", "ہم بحث نہیں چاہتے", "hum behas nahin chahte"],
        ["no money — پیسے نہیں", "پیسے نہیں", "paise nahin"],
        ["Contrast: نہیں کھاتا vs کھانا نہیں چاہتا", "فرق", "farq"],
        ["Soft: شاید نہیں", "شاید نہیں", "shayad nahin"],
        ["Practice dialogues", "مکالمے", "mukaalme"],
    ],
}
